Affymetrix Fusion SDK: C:/f112/affy/sdk/calvin_files/writers/src/ArrayFileWriter.cpp File Reference
ArrayFileWriter.cpp File Reference
#include "calvin_files/writers/src/ArrayFileWriter.h"
#include "calvin_files/array/src/ArrayId.h"
#include "calvin_files/parsers/src/SAXArrayHandlers.h"
#include "calvin_files/utils/src/AffymetrixGuid.h"
#include <xercesc/dom/DOM.hpp>
#include <xercesc/dom/DOMImplementation.hpp>
#include <xercesc/dom/DOMImplementationLS.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/util/XMLString.hpp>
#include <cstring>
#include <string.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
Classes
class XMLChConversion
Defines
#define ARRAY_SET_FILE_VERSION_NUMBER "1.0"
#define ToXMLCh(s) (XMLChConversion(s).String())
Functions
DOMElement * CreateArrayElement (ArrayData &arrayData, DOMDocument *doc, const AffymetrixGuidType &dataTypeIdentifier)
void AddPhysicalArrays (ArrayData &arrayData, DOMDocument *doc, DOMElement *arrayElement)
void AddUserAttributes (ArrayData &arrayData, DOMDocument *doc, DOMElement *arrayElement)
Define Documentation
#define ARRAY_SET_FILE_VERSION_NUMBER "1.0"
The expected version number
Definition at line 54 of file ArrayFileWriter.cpp.
Referenced by CreateArrayElement().
#define ToXMLCh (s) (XMLChConversion(s).String())
A macro to help with converting a string to XML string
Definition at line 140 of file ArrayFileWriter.cpp.
Referenced by AddPhysicalArrays(), AddUserAttributes(), CreateArrayElement(), and affymetrix_calvin_io::ArrayFileWriter::Write().
Function Documentation
void AddPhysicalArrays (ArrayData & arrayData, DOMDocument * doc, DOMElement * arrayElement)
Definition at line 165 of file ArrayFileWriter.cpp.
References ARRAY_FILE_ELEMENT_CREATED_STEP_ATTRIBUTE, ARRAY_TYPE_IDENTIFIER, affymetrix_calvin_array::ArrayAttributes::ArrayBarcode(), affymetrix_calvin_array::ArrayAttributes::ArrayName(), affymetrix_calvin_array::ArrayAttributes::Attributes(), affymetrix_calvin_array::ArrayAttributes::Comment(), affymetrix_calvin_array::ArrayAttributes::CreatedBy(), affymetrix_calvin_array::ArrayAttributes::CreatedStep(), affymetrix_calvin_array::CreateStepToString(), affymetrix_calvin_array::ArrayAttributes::CreationDateTime(), affymetrix_calvin_array::ArrayAttributes::Identifier(), affymetrix_calvin_array::ArrayAttributes::LibraryPackageName(), affymetrix_calvin_array::ArrayAttributes::MasterFile(), affymetrix_calvin_array::ArrayAttributes::MasterFileId(), affymetrix_calvin_array::ArrayAttributes::Media(), affymetrix_calvin_array::ArrayAttributes::MediaCol(), affymetrix_calvin_array::ArrayAttributes::MediaFileGUID(), affymetrix_calvin_array::ArrayAttributes::MediaFileName(), affymetrix_calvin_array::ArrayAttributes::MediaRow(), affymetrix_calvin_array::MediaToString(), affymetrix_calvin_parameter::_tagParameterNameValuePair::Name, affymetrix_calvin_array::ArrayAttributes::PatAssignment(), affymetrix_calvin_array::PATAssignmentMethodToString(), PHYSICAL_ARRAY_ATTRIBUTE_ELEMENT, PHYSICAL_ARRAY_ATTRIBUTE_ELEMENT_NAME_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT, PHYSICAL_ARRAY_ELEMENT_ARRAY_TYPE_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_BARCODE_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_COL_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_COMMENT_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_CREATED_BY_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_CREATION_DATE_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_ID_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_LIB_PACKAGE_NAME_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_MASTERFILE_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_MASTERFILE_GUID_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_MEDIA_FILE_GUID_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_MEDIA_FILE_NAME_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_NAME_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_PAT_ASSIGNMENT_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_ROW_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_TYPE_ATTRIBUTE, PHYSICAL_ARRAYS_ELEMENT, affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), ToXMLCh, and affymetrix_calvin_parameter::_tagParameterNameValuePair::Value.
Referenced by affymetrix_calvin_io::ArrayFileWriter::Write().
void AddUserAttributes (ArrayData & arrayData, DOMDocument * doc, DOMElement * arrayElement)
Definition at line 211 of file ArrayFileWriter.cpp.
References affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlledVocabulary(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlMultiValues(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::DefaultToString(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::HasDefault(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::RequiredFlag(), affymetrix_calvin_parameter::ParameterNameValueType::ToString(), ToXMLCh, USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT, USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT_VALUE_ATTRIBUTE, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_DEFAULT_ATTRIBUTE, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_NAME_ATTRIBUTE, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_REQUIRED_ATTRIBUTE, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_TYPE_ATTRIBUTE, USER_ATTRIBUTES_ATTRIBUTE_VALUE_ELEMENT, USER_ATTRIBUTES_ELEMENT, affymetrix_calvin_array::ArrayData::UserAttributes(), and affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ValueType().
Referenced by affymetrix_calvin_io::TemplateFileWriter::Write(), and affymetrix_calvin_io::ArrayFileWriter::Write().
DOMElement* CreateArrayElement (ArrayData & arrayData, DOMDocument * doc, const AffymetrixGuidType & dataTypeIdentifier)
Definition at line 146 of file ArrayFileWriter.cpp.
References ARRAY_FILE_ELEMENT, ARRAY_FILE_ELEMENT_CREATE_DATE_TIME_ATTRIBUTE, ARRAY_FILE_ELEMENT_CREATED_BY_ATTRIBUTE, ARRAY_FILE_ELEMENT_CREATED_STEP_ATTRIBUTE, ARRAY_FILE_ELEMENT_ID_ATTRIBUTE, ARRAY_FILE_ELEMENT_PROJECT_ATTRIBUTE, ARRAY_FILE_ELEMENT_TYPE_ATTRIBUTE, ARRAY_FILE_ELEMENT_VERSION_ATTRIBUTE, ARRAY_SET_FILE_TYPE_IDENTIFIER, ARRAY_SET_FILE_VERSION_NUMBER, affymetrix_calvin_array::ArrayData::ArraySetFileIdentifier(), affymetrix_calvin_array::ArrayData::CreatedBy(), affymetrix_calvin_array::ArrayData::CreatedStep(), affymetrix_calvin_array::CreateStepToString(), affymetrix_calvin_array::ArrayData::CreationDateTime(), affymetrix_calvin_array::ArrayData::InitialProject(), and ToXMLCh.
Referenced by affymetrix_calvin_io::ArrayFileWriter::Write().