Affymetrix Fusion SDK: C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPMultiDataFileBufferWriter.cpp File Reference
CalvinCHPMultiDataFileBufferWriter.cpp File Reference
Class for writing MultiDatas to a buffer before writing to CHP files.
#include <sys/types.h>
#include <netinet/in.h>
#include <inttypes.h>
#include "calvin_files/writers/src/CalvinCHPMultiDataFileBufferWriter.h"
#include "calvin_files/writers/src/CalvinCHPFileUpdater.h"
#include "calvin_files/writers/src/FileOutput.h"
#include "file/FileIO.h"
#include <cstring>
#include <string.h>
#include <string>
Functions
static void ClearBuffer (std::vector< std::vector< char * > > &buffers, std::vector< int > &rowIndexes)
static int GetMetricBufferSize (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > &metrics)
static void CopyMetricToBuffer (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > &metrics, char *&pbuffer)
static void ClearBuffer (std::vector< char * > &buffer)
Detailed Description
Class for writing MultiDatas to a buffer before writing to CHP files.
Definition in file CalvinCHPMultiDataFileBufferWriter.cpp.
Function Documentation
static void ClearBuffer (std::vector< std::vector< char * > > & buffers, std::vector< int > & rowIndexes) [static]
Definition at line 67 of file CalvinCHPMultiDataFileBufferWriter.cpp.
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::Cleanup(), and affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
static void ClearBuffer (std::vector< char * > & buffer) [static]
Definition at line 966 of file CalvinCHPMultiDataFileBufferWriter.cpp.
static void CopyMetricToBuffer (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > & metrics, char *& pbuffer) [static]
Definition at line 222 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), MmSetFloat_N(), MmSetUInt16_N(), and MmSetUInt32_N().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberVariationRegionEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCytoRegionEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataExpressionEntry(), and affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataGenotypeEntry().
static int GetMetricBufferSize (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > & metrics) [static]
Definition at line 167 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberVariationRegionEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCytoRegionEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataExpressionEntry(), and affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataGenotypeEntry().