Affymetrix Fusion SDK: C:/f112/affy/sdk/calvin_files/writers/src/DataSetHeaderAppend.cpp File Reference
DataSetHeaderAppend.cpp File Reference
#include "calvin_files/writers/src/DataSetHeaderAppend.h"
#include "calvin_files/parsers/src/GenericFileReader.h"
#include "calvin_files/utils/src/StringUtils.h"
#include "calvin_files/writers/src/GenericFileUpdater.h"
Defines
#define VERBOSE(level, msg) { }
#define ERR(msg) { throw msg; }
Functions
static void AddDataSetHeaderToGroup (GenericFileWriter *gwf, int groupIndex, int nsets, FileHeader &fileHdr, const wstring &setName, const ParameterNameValueTypeList &params)
Define Documentation
#define ERR (msg) { throw msg; }
Definition at line 42 of file DataSetHeaderAppend.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), and AddDataSetHeaderToGroup().
#define VERBOSE (level, msg) { }
Definition at line 41 of file DataSetHeaderAppend.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader().
Function Documentation
static void AddDataSetHeaderToGroup (GenericFileWriter * gwf, int groupIndex, int nsets, FileHeader & fileHdr, const wstring & setName, const ParameterNameValueTypeList & params) [static]
Definition at line 45 of file DataSetHeaderAppend.cpp.
References affymetrix_calvin_io::DataSetHeader::AddNameValParam(), affymetrix_calvin_io::DataGroupWriter::CreateDataSetWriter(), ERR, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::FileHeader::GetFirstDataGroupFilePos(), affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::GenericFileWriter::SeekFromEndPos(), affymetrix_calvin_io::DataSetHeader::SetName(), affymetrix_calvin_io::DataSetHeader::SetRowCnt(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), affymetrix_calvin_io::GenericFileWriter::Write(), and affymetrix_calvin_io::DataSetWriter::WriteHeader().
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader().