Affymetrix Fusion SDK: C:/f112/affy/sdk/calvin_files/parsers/src/SAXTemplateHandlers.cpp File Reference
SAXTemplateHandlers.cpp File Reference
#include "calvin_files/parsers/src/SAXTemplateHandlers.h"
#include "calvin_files/utils/src/StringUtils.h"
#include <cstring>
#include <map>
#include <string>
Functions
static int WideToInt (wstring const &wstr)
static float WideToFloat (wstring const &wstr)
static wstring XMLChToWString (const XMLCh *const c1)
static bool operator== (const XMLCh *const &c1, wstring c2)
Variables
XERCES_CPP_NAMESPACE_USE
Function Documentation
static bool operator== (const XMLCh *const & c1, wstring c2) [static]
Comparison operator for XML strings to wide character strings.
Parameters:
c1 The XML string
c2 The wide string
Returns:
True if equal
Definition at line 88 of file SAXTemplateHandlers.cpp.
static float WideToFloat (wstring const & wstr) [static]
Converts a string to an integer.
Parameters:
wstr The string to convert
Returns:
The float representation of the string.
Definition at line 58 of file SAXTemplateHandlers.cpp.
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::characters().
static int WideToInt (wstring const & wstr) [static]
Converts a string to an integer.
Parameters:
wstr The string to convert
Returns:
The integer representation of the string.
Definition at line 45 of file SAXTemplateHandlers.cpp.
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::characters().
static wstring XMLChToWString (const XMLCh *const c1) [static]
Converts a XML character string to wide string.
Parameters:
c1 The XML string to convert
Returns:
The wide character string
Definition at line 71 of file SAXTemplateHandlers.cpp.
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::characters().
Variable Documentation
XERCES_CPP_NAMESPACE_USE
Definition at line 35 of file SAXTemplateHandlers.cpp.