Affymetrix Fusion SDK: affymetrix_calvin_io::CHPMultiDataData Class Reference
affymetrix_calvin_io::CHPMultiDataData Class Reference
#include <CHPMultiDataData.h>
Public Member Functions
CHPMultiDataData ()
CHPMultiDataData (const std::string &filename, const std::list< std::wstring > *groupNames=NULL)
~CHPMultiDataData ()
std::wstring GetGroupName (MultiDataType dataType)
std::map< MultiDataType,
DataSetInfo > & GetDataSetInfo ()
int GetMaxProbeSetName (MultiDataType dataType)
int GetMaxSegmentId (MultiDataType dataType)
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename () const
std::wstring GetArrayType ()
void SetArrayType (const std::wstring &value)
void SetEntryCount (MultiDataType dataType, int32_t ln, int32_t maxln, const std::vector< ColumnInfo > &columns, const std::wstring &groupName=L"")
void SetEntryCount (MultiDataType dataType, int32_t ln, int32_t maxln, const std::wstring &groupName=L"")
void SetEntryCount (MultiDataType dataType, int32_t ln, int segmentTypeMax, int referenceSegmentIDMax, int familialSegmentIDMax, const std::wstring &groupName=L"")
void SetEntryCount (MultiDataType dataType, int32_t ln, int familialARRIDMax, int familialCHPIDMax, int familialCHPFileMax, int familialRoleMax, const std::wstring &groupName=L"")
int32_t GetEntryCount (MultiDataType dataType)
std::wstring GetAlgName ()
void SetAlgName (const std::wstring &value)
std::wstring GetAlgVersion ()
void SetAlgVersion (const std::wstring &value)
ParameterNameValueTypeList GetAlgParams ()
void AddAlgParams (const ParameterNameValueTypeList &params)
void AddAppMetaInfo (const ParameterNameValueTypeList &params)
ParameterNameValueTypeList GetSummaryParams ()
void AddSummaryParams (const ParameterNameValueTypeList &params)
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
void GetGenotypeEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry)
void GetCopyNumberEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData &entry)
void GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::DmetCopyNumberData &entry)
void GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::DmetMultiAllelicData &entry)
void GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::DmetBiAllelicData &entry)
void GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::AllelePeaks &entry)
void GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::MarkerABSignals &entry)
void GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::CytoGenotypeCallData &entry)
void GetCopyNumberEntryLog2Ratio (MultiDataType dataType, int index, float *val)
void GetCytoEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData &entry)
void GetExpressionEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataExpressionData &entry)
u_int8_t GetGenoCall (MultiDataType dataType, int index)
float GetGenoConfidence (MultiDataType dataType, int index)
float GetExpressionQuantification (MultiDataType dataType, int index)
void GetCopyNumberVariationEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData &entry)
void GetChromosomeSegmentEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeSegmentData &entry)
void GetChromosomeSegmentEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeSegmentDataEx &entry)
void GetChromosomeSummaryEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeMultiDataSummaryData &entry)
void GetFamilialSegmentOverlapEntry (MultiDataType dataType, int index, affymetrix_calvin_data::FamilialSegmentOverlap &entry)
void GetFamilialSampleEntry (MultiDataType dataType, int index, affymetrix_calvin_data::FamilialSample &entry)
std::string GetProbeSetName (MultiDataType dataType, int index)
DataSetHeader * GetDataSetHeader (MultiDataType dataType)
DataGroupHeader * GetDataGroupHeader (const std::wstring &name)
int GetDataGroupIndex (MultiDataType dataType)
int32_t GetMetricColumnLength (MultiDataType dataType, int col)
int32_t GetNumMetricColumns (MultiDataType dataType)
std::wstring GetMetricColumnName (MultiDataType dataType, int colIndex)
Private Member Functions
void GetExtraMetricEntries (DataSetInfo *ds, int rowIndex, int colIndex, std::vector< affymetrix_calvin_parameter::ParameterNameValueType > &metrics)
void GetExtraCopyNumberFloatTypeNoNameLog2Ratio (DataSetInfo *ds, int rowIndex, float *val)
void GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry)
void GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData &entry)
void GetGenericCopyNumberEntryLog2Ratio (MultiDataType dataType, int index, float *val)
void GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData &entry)
void GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataExpressionData &entry)
void GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData &entry)
DataSetInfo * OpenMultiDataDataSet (MultiDataType dataType)
std::wstring GetWStringFromGenericHdr (const std::wstring &name)
void SetWStringToGenericHdr (const std::wstring &name, const std::wstring value, int32_t reserve=-1)
void AddColumns (DataSetInfo &info, DataSetHeader &hdr)
Private Attributes
GenericData genericData
std::map< MultiDataType,
DataSetInfo > dataSetInfo
std::map< MultiDataType,
std::wstring > dataTypeGroupNames
Detailed Description
Holds data associated with genotype or expression CHP files.
Definition at line 196 of file CHPMultiDataData.h.
Constructor & Destructor Documentation
CHPMultiDataData::CHPMultiDataData ()
Constructor
Definition at line 252 of file CHPMultiDataData.cpp.
CHPMultiDataData::CHPMultiDataData (const std::string & filename, const std::list< std::wstring > * groupNames = NULL)
Constructor with file name.
Parameters:
filename The name of the CHP file.
groupNames A list of names for the data groups.
Definition at line 257 of file CHPMultiDataData.cpp.
References CHP_MULTI_DATA_TYPE, and MULTI_DATA_NAME.
CHPMultiDataData::~CHPMultiDataData ()
Destructor
Definition at line 280 of file CHPMultiDataData.cpp.
Member Function Documentation
void affymetrix_calvin_io::CHPMultiDataData::AddAlgParams (const ParameterNameValueTypeList & params)
Adds the algorithm parameters.
Parameters:
params The algorithm parameters.
Referenced by CreateFileWithHeader(), and CopyNumberResultWriter::CreateResultFile().
void CHPMultiDataData::AddAppMetaInfo (const ParameterNameValueTypeList & params)
Adds the application meta data information
Parameters:
params The application meta data
Definition at line 1334 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), APPLICATION_META_INFO_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
void CHPMultiDataData::AddColumns (DataSetInfo & info, DataSetHeader & hdr) [private]
Adds the columns to the data set.
Parameters:
info The data info
hdr The data set header.
Definition at line 932 of file CHPMultiDataData.cpp.
References A_SIGNAL, affymetrix_calvin_io::DataSetHeader::AddAsciiColumn(), affymetrix_calvin_io::DataSetHeader::AddByteColumn(), affymetrix_calvin_io::DataSetHeader::AddColumn(), affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), affymetrix_calvin_io::DataSetHeader::AddIntColumn(), affymetrix_calvin_io::DataSetHeader::AddShortColumn(), affymetrix_calvin_io::DataSetHeader::AddUByteColumn(), affymetrix_calvin_io::DataSetHeader::AddUIntColumn(), affymetrix_calvin_io::DataSetHeader::AddUnicodeColumn(), ALLELE_COUNT, affymetrix_calvin_io::AllelePeaksMultiDataType, ARRID, B_SIGNAL, CALL, CHP_FILENAME, CHPID, CHR, CHR_DISPLAY, affymetrix_calvin_io::ChromosomeSummaryMultiDataType, CN_CALL, CN_CONFIDENCE, CN_ESTIMATE, CN_FORCE, CN_LOWER, CN_UPPER, CONFIDENCE, CONTEXT_A, CONTEXT_B, CONTEXT_C, CONTEXT_D, CONTEXT_E, CONTEXT_F, CONTRAST, affymetrix_calvin_io::CopyNumberMultiDataType, affymetrix_calvin_io::CopyNumberVariationMultiDataType, affymetrix_calvin_io::CytoGenotypeCallMultiDataType, affymetrix_calvin_io::CytoMultiDataType, affymetrix_calvin_io::DataSetInfo::dataType, affymetrix_calvin_io::DmetBiAllelicMultiDataType, affymetrix_calvin_io::DmetCopyNumberMultiDataType, affymetrix_calvin_io::DmetMultiAllelicMultiDataType, affymetrix_calvin_io::ExpressionMultiDataType, FAMILIAL_SAMPLE_KEY, FAMILIAL_SEGMENT_ID, affymetrix_calvin_io::FamilialSamplesMultiDataType, affymetrix_calvin_io::FamilialSegmentOverlapsMultiDataType, FORCE, affymetrix_calvin_io::GenotypeMultiDataType, HET_FREQ, HETEROZYGOSITY, HOM_FREQ, HOMOZYGOSITY, MARKER_COUNT, affymetrix_calvin_io::MarkerABSignalsMultiDataType, MAX_SIGNAL, affymetrix_calvin_io::DataSetInfo::maxFamilialARRID, affymetrix_calvin_io::DataSetInfo::maxFamilialCHPFile, affymetrix_calvin_io::DataSetInfo::maxFamilialCHPID, affymetrix_calvin_io::DataSetInfo::maxFamilialRole, affymetrix_calvin_io::DataSetInfo::maxFamilialSegmentID, affymetrix_calvin_io::DataSetInfo::maxName, affymetrix_calvin_io::DataSetInfo::maxReferenceSegmentID, affymetrix_calvin_io::DataSetInfo::maxSegmentType, MEAN_MARKER_DISTANCE, MEDIAN_CN_STATE, affymetrix_calvin_io::DataSetInfo::metricColumns, MIN_SIGNAL, POSITION, PROBE_SET_INDEX, PROBE_SET_NAME, QUANTIFICATION, REFERENCE_SAMPLE_KEY, REFERENCE_SEGMENT_ID, REGION, ROLE, ROLE_CONFIDENCE, ROLE_VALIDITY, SAMPLE_KEY, SEGMENT_ID, SEGMENT_TYPE, affymetrix_calvin_io::SegmentCNLossLOHConcordanceMultiDataType, affymetrix_calvin_io::SegmentCNMultiDataType, affymetrix_calvin_io::SegmentCNNeutralLOHConcordanceMultiDataType, affymetrix_calvin_io::SegmentCNNeutralLOHMultiDataType, affymetrix_calvin_io::SegmentDenovoCopyNumberMultiDataType, affymetrix_calvin_io::SegmentGenotypeConcordanceMultiDataType, affymetrix_calvin_io::SegmentGenotypeDiscordanceMultiDataType, affymetrix_calvin_io::SegmentHemizygousParentOfOriginMultiDataType, affymetrix_calvin_io::SegmentHeteroUPDMultiDataType, affymetrix_calvin_io::SegmentIsoUPDMultiDataType, affymetrix_calvin_io::SegmentLOHMultiDataType, affymetrix_calvin_io::SegmentMosaicismMultiDataType, affymetrix_calvin_io::SegmentNoCallMultiDataType, affymetrix_calvin_io::SegmentNormalDiploidMultiDataType, SIGNAL, SIGNAL_A, SIGNAL_B, SIGNAL_C, SIGNAL_D, SIGNAL_E, SIGNAL_F, SIGNAL_STRENGTH, START_INDEX, START_POSITION, and STOP_POSITION.
void affymetrix_calvin_io::CHPMultiDataData::AddSummaryParams (const ParameterNameValueTypeList & params)
Adds the summary parameters.
Parameters:
params The summary parameters.
Referenced by CreateFileWithHeader(), and CopyNumberResultWriter::CreateResultFile().
void CHPMultiDataData::Clear ()
Clears the members.
Definition at line 302 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetHeader::Clear(), affymetrix_calvin_io::DataSet::Delete(), affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::Header(), and affymetrix_calvin_io::DataSetInfo::metricColumns.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::Clear(), and affymetrix_calvin_io::CHPMultiDataFileReader::Read().
std::wstring CHPMultiDataData::GetAlgName ()
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 1280 of file CHPMultiDataData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgName().
ParameterNameValueTypeList CHPMultiDataData::GetAlgParams ()
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 1300 of file CHPMultiDataData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgParams().
std::wstring CHPMultiDataData::GetAlgVersion ()
Gets the algorithm version.
Returns:
The version.
Definition at line 1290 of file CHPMultiDataData.cpp.
References ALG_VERSION_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgVersion().
std::wstring CHPMultiDataData::GetArrayType ()
Sets the array type
Definition at line 1270 of file CHPMultiDataData.cpp.
References ARRAY_TYPE_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetArrayType().
void CHPMultiDataData::GetChromosomeSegmentEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeSegmentData & entry)
Gets the chromosome segment data.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 630 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_ChromosomeSegmentData::chr, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ChromosomeSegmentData::markerCount, affymetrix_calvin_data::_ChromosomeSegmentData::meanMarkerDistance, affymetrix_calvin_data::_ChromosomeSegmentData::metrics, affymetrix_calvin_data::_ChromosomeSegmentData::segmentId, affymetrix_calvin_data::_ChromosomeSegmentData::startPosition, and affymetrix_calvin_data::_ChromosomeSegmentData::stopPosition.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetChromosomeSegmentEntry().
void CHPMultiDataData::GetChromosomeSegmentEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeSegmentDataEx & entry)
Gets the chromosome segment data.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 646 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_ChromosomeSegmentDataEx::call, affymetrix_calvin_data::_ChromosomeSegmentDataEx::chr, affymetrix_calvin_data::_ChromosomeSegmentDataEx::confidence, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_data::_ChromosomeSegmentDataEx::familialSampleKey, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_data::_ChromosomeSegmentDataEx::heterozygosity, affymetrix_calvin_data::_ChromosomeSegmentDataEx::homozygosity, affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ChromosomeSegmentDataEx::markerCount, affymetrix_calvin_data::_ChromosomeSegmentDataEx::metrics, affymetrix_calvin_data::_ChromosomeSegmentDataEx::referenceSampleKey, affymetrix_calvin_data::_ChromosomeSegmentDataEx::segmentId, affymetrix_calvin_data::_ChromosomeSegmentDataEx::startPosition, and affymetrix_calvin_data::_ChromosomeSegmentDataEx::stopPosition.
void CHPMultiDataData::GetChromosomeSummaryEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeMultiDataSummaryData & entry)
Gets the chromosome summary data.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 667 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::chr, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::display, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::hetFrequency, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::homFrequency, affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::markerCount, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::maxSignal, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::medianCnState, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::metrics, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::minSignal, and affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::startIndex.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetChromosomeSummaryEntry().
void CHPMultiDataData::GetCopyNumberEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & entry)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 493 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetCopyNumberEntry(), and CalvinChpCheck::multiDataCopyNumberSame().
void CHPMultiDataData::GetCopyNumberEntryLog2Ratio (MultiDataType dataType, int index, float * val)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 610 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetCopyNumberEntryLog2Ratio().
void CHPMultiDataData::GetCopyNumberVariationEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData & entry)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number variation results.
Definition at line 625 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetCopyNumberVariationRegionEntry(), and CalvinChpCheck::multiDataCopyNumberVariationSame().
void CHPMultiDataData::GetCytoEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & entry)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The cyto results.
Definition at line 615 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetCytoRegionEntry().
DataGroupHeader * CHPMultiDataData::GetDataGroupHeader (const std::wstring & name)
Returns the data group header.
Parameters:
name The name of the group.
Definition at line 398 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetName().
int CHPMultiDataData::GetDataGroupIndex (MultiDataType dataType)
Returns the data group index.
Parameters:
dataType The data type.
Definition at line 385 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetName().
DataSetHeader * CHPMultiDataData::GetDataSetHeader (MultiDataType dataType)
Returns the data set header.
Parameters:
dataType The data type.
Definition at line 285 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), affymetrix_calvin_io::DataSetHeader::GetName(), and affymetrix_calvin_io::MultiDataDataSetNames.
Referenced by CopyNumberResultWriter::CreateResultFile(), and affymetrix_fusion_io::FusionCHPMultiDataData::GetDataSetHeader().
std::map< MultiDataType, DataSetInfo > & CHPMultiDataData::GetDataSetInfo ()
The data set information
Definition at line 245 of file CHPMultiDataData.cpp.
Referenced by CalvinChpCheck::check(), affymetrix_calvin_io::CHPMultiDataFileWriter::CHPMultiDataFileWriter(), and affymetrix_fusion_io::FusionCHPMultiDataData::GetDataSetInfo().
void CHPMultiDataData::GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::MarkerABSignals & entry)
Gets the marker AB signal data.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 579 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_data::_MarkerABSignals::index, affymetrix_calvin_io::DataSet::IsOpen(), and affymetrix_calvin_data::_MarkerABSignals::metrics.
void CHPMultiDataData::GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::CytoGenotypeCallData & entry)
Gets the genotype data for cyto.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 592 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_CytoGenotypeCallData::aSignal, affymetrix_calvin_data::_CytoGenotypeCallData::bSignal, affymetrix_calvin_data::_CytoGenotypeCallData::call, affymetrix_calvin_data::_CytoGenotypeCallData::confidence, affymetrix_calvin_data::_CytoGenotypeCallData::contrast, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_data::_CytoGenotypeCallData::forcedCall, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_data::_CytoGenotypeCallData::index, affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_CytoGenotypeCallData::metrics, and affymetrix_calvin_data::_CytoGenotypeCallData::signalStrength.
void CHPMultiDataData::GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::DmetCopyNumberData & entry)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 498 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_DmetCopyNumberData::call, affymetrix_calvin_data::_DmetCopyNumberData::confidence, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_data::_DmetCopyNumberData::estimate, affymetrix_calvin_data::_DmetCopyNumberData::force, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_DmetCopyNumberData::lower, affymetrix_calvin_data::_DmetCopyNumberData::metrics, affymetrix_calvin_data::_DmetCopyNumberData::name, and affymetrix_calvin_data::_DmetCopyNumberData::upper.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetAllelePeakEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetCytoGenotypeEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetDmetBiAllelicEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetDmetCopyNumberEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetDmetMultiAllelicEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetMarkerABSignalsEntry(), CalvinChpCheck::multiDataDmetBiAllelicSame(), CalvinChpCheck::multiDataDmetCopyNumberSame(), and CalvinChpCheck::multiDataDmetMultiAllelicSame().
void CHPMultiDataData::GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::DmetMultiAllelicData & entry)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 535 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_DmetMultiAllelicData::alleleCount, affymetrix_calvin_data::_DmetMultiAllelicData::call, affymetrix_calvin_data::_DmetMultiAllelicData::confidence, affymetrix_calvin_data::_DmetMultiAllelicData::contextA, affymetrix_calvin_data::_DmetMultiAllelicData::contextB, affymetrix_calvin_data::_DmetMultiAllelicData::contextC, affymetrix_calvin_data::_DmetMultiAllelicData::contextD, affymetrix_calvin_data::_DmetMultiAllelicData::contextE, affymetrix_calvin_data::_DmetMultiAllelicData::contextF, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_data::_DmetMultiAllelicData::force, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_DmetMultiAllelicData::metrics, affymetrix_calvin_data::_DmetMultiAllelicData::name, affymetrix_calvin_data::_DmetMultiAllelicData::signalA, affymetrix_calvin_data::_DmetMultiAllelicData::signalB, affymetrix_calvin_data::_DmetMultiAllelicData::signalC, affymetrix_calvin_data::_DmetMultiAllelicData::signalD, affymetrix_calvin_data::_DmetMultiAllelicData::signalE, and affymetrix_calvin_data::_DmetMultiAllelicData::signalF.
void CHPMultiDataData::GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::DmetBiAllelicData & entry)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 516 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_DmetBiAllelicData::call, affymetrix_calvin_data::_DmetBiAllelicData::confidence, affymetrix_calvin_data::_DmetBiAllelicData::contextA, affymetrix_calvin_data::_DmetBiAllelicData::contextB, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_data::_DmetBiAllelicData::force, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_DmetBiAllelicData::metrics, affymetrix_calvin_data::_DmetBiAllelicData::name, affymetrix_calvin_data::_DmetBiAllelicData::signalA, and affymetrix_calvin_data::_DmetBiAllelicData::signalB.
void CHPMultiDataData::GetEntry (MultiDataType dataType, int index, affymetrix_calvin_data::AllelePeaks & entry)
Gets the allele peak data.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 563 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_AllelePeaks::chr, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_AllelePeaks::name, affymetrix_calvin_data::_AllelePeaks::peaks, and affymetrix_calvin_data::_AllelePeaks::position.
int32_t CHPMultiDataData::GetEntryCount (MultiDataType dataType)
Gets the number of entries (probe sets)
Parameters:
dataType The data type
Definition at line 357 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetHeader::GetRowCnt().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetEntryCount(), CalvinChpCheck::multiDataCopyNumberSame(), CalvinChpCheck::multiDataCopyNumberVariationSame(), CalvinChpCheck::multiDataDmetBiAllelicSame(), CalvinChpCheck::multiDataDmetCopyNumberSame(), CalvinChpCheck::multiDataDmetMultiAllelicSame(), CalvinChpCheck::multiDataExpressionSame(), and CalvinChpCheck::multiDataGenotypeSame().
void CHPMultiDataData::GetExpressionEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataExpressionData & entry)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The expression results.
Definition at line 620 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetExpressionEntry(), and CalvinChpCheck::multiDataExpressionSame().
float CHPMultiDataData::GetExpressionQuantification (MultiDataType dataType, int index)
Gets the quantification of the probe set.
Parameters:
dataType The data type
index The row index.
Returns:
The quantification.
Definition at line 910 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), and affymetrix_calvin_io::DataSet::IsOpen().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetExpressionQuantification().
void CHPMultiDataData::GetExtraCopyNumberFloatTypeNoNameLog2Ratio (DataSetInfo * ds, int rowIndex, float * val) [private]
Get the extra metric columns.
Parameters:
ds The data set info.
rowIndex The row index.
colIndex The column index
metrics The results.
Definition at line 884 of file CHPMultiDataData.cpp.
References cnlog2RatioIndexOffset, affymetrix_calvin_io::DataSetInfo::entries, and affymetrix_calvin_io::DataSet::GetData().
void CHPMultiDataData::GetExtraMetricEntries (DataSetInfo * ds, int rowIndex, int colIndex, std::vector< affymetrix_calvin_parameter::ParameterNameValueType > & metrics) [private]
Get the extra metric columns.
Parameters:
ds The data set info.
rowIndex The row index.
colIndex The column index
metrics The results.
Definition at line 800 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::ASCIICharColType, affymetrix_calvin_io::ByteColType, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::FloatColType, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::IntColType, affymetrix_calvin_io::DataSetInfo::metricColumns, affymetrix_calvin_io::ShortColType, affymetrix_calvin_io::UByteColType, affymetrix_calvin_io::UIntColType, affymetrix_calvin_io::UnicodeCharColType, and affymetrix_calvin_io::UShortColType.
void CHPMultiDataData::GetFamilialSampleEntry (MultiDataType dataType, int index, affymetrix_calvin_data::FamilialSample & entry)
Gets the familial file entry.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 686 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_FamilialSample::arrID, affymetrix_calvin_data::_FamilialSample::chpFilename, affymetrix_calvin_data::_FamilialSample::chpID, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_FamilialSample::role, affymetrix_calvin_data::_FamilialSample::roleConfidence, affymetrix_calvin_data::_FamilialSample::roleValidity, and affymetrix_calvin_data::_FamilialSample::sampleKey.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetFamilialSampleEntry().
void CHPMultiDataData::GetFamilialSegmentOverlapEntry (MultiDataType dataType, int index, affymetrix_calvin_data::FamilialSegmentOverlap & entry)
Gets the familial file entry.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 704 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_data::_FamilialSegmentOverlap::familialSampleKey, affymetrix_calvin_data::_FamilialSegmentOverlap::familialSegmentID, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_FamilialSegmentOverlap::referenceSampleKey, affymetrix_calvin_data::_FamilialSegmentOverlap::referenceSegmentID, and affymetrix_calvin_data::_FamilialSegmentOverlap::segmentType.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetFamilialSegmentOverlapEntry().
FileHeader * CHPMultiDataData::GetFileHeader ()
Gets the file header.
Returns:
The file header.
Definition at line 318 of file CHPMultiDataData.cpp.
Referenced by affymetrix_calvin_io::CHPMultiDataFileWriter::CHPMultiDataFileWriter(), CreateFileWithHeader(), and CopyNumberResultWriter::CreateResultFile().
std::string CHPMultiDataData::GetFilename () const
Gets the file name.
Returns:
The file name.
Definition at line 334 of file CHPMultiDataData.cpp.
Referenced by CalvinChpCheck::multiDataCopyNumberSame(), CalvinChpCheck::multiDataCopyNumberVariationSame(), CalvinChpCheck::multiDataDmetBiAllelicSame(), CalvinChpCheck::multiDataDmetCopyNumberSame(), CalvinChpCheck::multiDataDmetMultiAllelicSame(), CalvinChpCheck::multiDataExpressionSame(), CalvinChpCheck::multiDataGenotypeSame(), and affymetrix_calvin_io::CHPMultiDataFileReader::Read().
void CHPMultiDataData::GetGenericCopyNumberEntryLog2Ratio (MultiDataType dataType, int index, float * val) [private]
Gets the probe set data (log2Ratio only).
Parameters:
dataType The data type
index The row index.
val The copy number result (log2Ratio).
Definition at line 746 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetInfo::entries, and affymetrix_calvin_io::DataSet::IsOpen().
GenericData & CHPMultiDataData::GetGenericData ()
Gets the generic data object.
Returns:
The data object.
Definition at line 325 of file CHPMultiDataData.cpp.
Referenced by CreateFileWithHeader(), affymetrix_fusion_io::FusionCHPMultiDataData::FileId(), affymetrix_fusion_io::FusionCHPMultiDataData::GetGenericData(), and affymetrix_calvin_io::CHPMultiDataFileReader::Read().
void CHPMultiDataData::GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & entry) [private]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The cyto region results.
Definition at line 755 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::chr, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::confidenceScore, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::name, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::startPosition, and affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::stopPosition.
void CHPMultiDataData::GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataExpressionData & entry) [private]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The expression results.
Definition at line 772 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::name, and affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::quantification.
void CHPMultiDataData::GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry) [private]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The genotype results.
Definition at line 718 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::metrics, and affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::name.
void CHPMultiDataData::GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & entry) [private]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 732 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::chr, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::position.
void CHPMultiDataData::GetGenericEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData & entry) [private]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number variation region results.
Definition at line 785 of file CHPMultiDataData.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::confidenceScore, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::IsOpen(), affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::signal.
u_int8_t CHPMultiDataData::GetGenoCall (MultiDataType dataType, int index)
Gets the call of the probe set.
Parameters:
dataType The data type
index The row index.
Returns:
The call.
Definition at line 892 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), and affymetrix_calvin_io::DataSet::IsOpen().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoCall().
float CHPMultiDataData::GetGenoConfidence (MultiDataType dataType, int index)
Gets the confidence in the call of the probe set.
Parameters:
dataType The data type
index The row index.
Returns:
The confidence.
Definition at line 901 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), and affymetrix_calvin_io::DataSet::IsOpen().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoConfidence().
void CHPMultiDataData::GetGenotypeEntry (MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry)
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The genotype results.
Definition at line 488 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetGenotypeEntry(), and CalvinChpCheck::multiDataGenotypeSame().
std::wstring CHPMultiDataData::GetGroupName (MultiDataType dataType)
Definition at line 240 of file CHPMultiDataData.cpp.
int CHPMultiDataData::GetMaxProbeSetName (MultiDataType dataType)
The maximum length of a probe set name.
Parameters:
dataType The data type
Returns:
The maximum probe set name length
Definition at line 363 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetMaxProbeSetName().
int CHPMultiDataData::GetMaxSegmentId (MultiDataType dataType)
The maximum length of a segment id.
Parameters:
dataType The data type
Returns:
The maximum length
Definition at line 374 of file CHPMultiDataData.cpp.
int32_t CHPMultiDataData::GetMetricColumnLength (MultiDataType dataType, int col)
Get the length of the metric columns.
Parameters:
dataType The data type
col The column index (of the metric columns)
Returns:
The length.
Definition at line 339 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetMetricColumnLength().
wstring CHPMultiDataData::GetMetricColumnName (MultiDataType dataType, int colIndex)
Get the metric column name.
Parameters:
dataType The data type
colIndex the metric column index
Returns:
The column name
Definition at line 351 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetMetricColumnName().
int32_t CHPMultiDataData::GetNumMetricColumns (MultiDataType dataType)
Get the length of the metric columns.
Parameters:
dataType The data type
Returns:
The number of columns.
Definition at line 345 of file CHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetNumMetricColumns().
std::string CHPMultiDataData::GetProbeSetName (MultiDataType dataType, int index)
Get the probe set name.
Parameters:
dataType The data type
index The row index.
Returns:
The probe set name.
Definition at line 921 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSet::GetData(), and affymetrix_calvin_io::DataSet::IsOpen().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetProbeSetName().
ParameterNameValueTypeList CHPMultiDataData::GetSummaryParams ()
Gets the summary parameters
Returns:
The summary parameters.
Definition at line 1347 of file CHPMultiDataData.cpp.
References CHIP_SUMMARY_PARAMETER_NAME_PREFIX, CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::GetSummaryParams().
std::wstring CHPMultiDataData::GetWStringFromGenericHdr (const std::wstring & name) [private]
Gets a parameter value as a string.
Parameters:
name The name of the parameter.
Returns:
The string representation.
Definition at line 1381 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueText().
DataSetInfo * CHPMultiDataData::OpenMultiDataDataSet (MultiDataType dataType) [private]
Opens a group for reading.
Parameters:
dataType The data type
Definition at line 1149 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::AllelePeaksMultiDataType, affymetrix_calvin_io::ChromosomeSummaryMultiDataType, affymetrix_calvin_io::CopyNumberMultiDataType, affymetrix_calvin_io::CopyNumberVariationMultiDataType, affymetrix_calvin_io::CytoGenotypeCallMultiDataType, affymetrix_calvin_io::CytoMultiDataType, affymetrix_calvin_io::DataSet::DataSet(), affymetrix_calvin_io::DmetBiAllelicMultiDataType, affymetrix_calvin_io::DmetCopyNumberMultiDataType, affymetrix_calvin_io::DmetMultiAllelicMultiDataType, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::ExpressionControlMultiDataType, affymetrix_calvin_io::ExpressionMultiDataType, affymetrix_calvin_io::FamilialSamplesMultiDataType, affymetrix_calvin_io::FamilialSegmentOverlapsMultiDataType, affymetrix_calvin_io::GenotypeControlMultiDataType, affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), affymetrix_calvin_io::DataSetHeader::GetName(), affymetrix_calvin_io::DataGroupHeader::GetName(), affymetrix_calvin_io::DataSet::Header(), affymetrix_calvin_io::MarkerABSignalsMultiDataType, affymetrix_calvin_io::DataSetInfo::metricColumns, affymetrix_calvin_io::MultiDataDataSetNames, affymetrix_calvin_io::MultiDataDataTypes, affymetrix_calvin_io::DataSet::Open(), affymetrix_calvin_io::SegmentCNLossLOHConcordanceMultiDataType, affymetrix_calvin_io::SegmentCNMultiDataType, affymetrix_calvin_io::SegmentCNNeutralLOHConcordanceMultiDataType, affymetrix_calvin_io::SegmentCNNeutralLOHMultiDataType, affymetrix_calvin_io::SegmentDenovoCopyNumberMultiDataType, affymetrix_calvin_io::SegmentGenotypeConcordanceMultiDataType, affymetrix_calvin_io::SegmentGenotypeDiscordanceMultiDataType, affymetrix_calvin_io::SegmentHemizygousParentOfOriginMultiDataType, affymetrix_calvin_io::SegmentHeteroUPDMultiDataType, affymetrix_calvin_io::SegmentIsoUPDMultiDataType, affymetrix_calvin_io::SegmentLOHMultiDataType, affymetrix_calvin_io::SegmentMosaicismMultiDataType, affymetrix_calvin_io::SegmentNoCallMultiDataType, and affymetrix_calvin_io::SegmentNormalDiploidMultiDataType.
void CHPMultiDataData::SetAlgName (const std::wstring & value)
Sets the name of the algorithm.
Parameters:
value The algorithm name.
Definition at line 1285 of file CHPMultiDataData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by CreateFileWithHeader(), and CopyNumberResultWriter::CreateResultFile().
void CHPMultiDataData::SetAlgVersion (const std::wstring & value)
Sets the algorithm version.
Parameters:
value The version.
Definition at line 1295 of file CHPMultiDataData.cpp.
References ALG_VERSION_PARAM_NAME.
Referenced by CreateFileWithHeader(), and CopyNumberResultWriter::CreateResultFile().
void CHPMultiDataData::SetArrayType (const std::wstring & value)
Sets the array type.
Definition at line 1275 of file CHPMultiDataData.cpp.
References ARRAY_TYPE_MAX_LEN, and ARRAY_TYPE_PARAM_NAME.
Referenced by CreateFileWithHeader(), and CopyNumberResultWriter::CreateResultFile().
void CHPMultiDataData::SetEntryCount (MultiDataType dataType, int32_t ln, int segmentTypeMax, int referenceSegmentIDMax, int familialSegmentIDMax, const std::wstring & groupName = L"")
Sets the number of entries specifically for the familial file.
Parameters:
dataType The data type
ln The number of probe sets.
segmentTypeMax The maximum length of the familial seg type column
referenceSegmentIDMax The maximum length of the familial ref seg id column
familialSegmentIDMax The maximum length of the familial seg id column
groupName The group name
Definition at line 439 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataSetInfo::dataSetIndex, affymetrix_calvin_io::DataSetInfo::dataType, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSetInfo::maxFamilialSegmentID, affymetrix_calvin_io::DataSetInfo::maxReferenceSegmentID, affymetrix_calvin_io::DataSetInfo::maxSegmentType, MULTI_DATA_NAME, affymetrix_calvin_io::MultiDataDataSetNames, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CHPMultiDataData::SetEntryCount (MultiDataType dataType, int32_t ln, int familialARRIDMax, int familialCHPIDMax, int familialCHPFileMax, int familialRoleMax, const std::wstring & groupName = L"")
Sets the number of entries specifically for the familial file.
Parameters:
dataType The data type
ln The number of probe sets.
familialSegmentIDMax The maximum length of the familial seg id column.
familialARRIDMax The maximum length of the familial sample ARR id.
familialCHPIDMax The maximum length of the familial sample CHP id.
familialCHPFile The maximum length of the familial sample CHP file name.
familialRole The maximum length of the familial sample role
groupName The group name
Definition at line 463 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataSetInfo::dataSetIndex, affymetrix_calvin_io::DataSetInfo::dataType, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSetInfo::maxFamilialARRID, affymetrix_calvin_io::DataSetInfo::maxFamilialCHPFile, affymetrix_calvin_io::DataSetInfo::maxFamilialCHPID, affymetrix_calvin_io::DataSetInfo::maxFamilialRole, MULTI_DATA_NAME, affymetrix_calvin_io::MultiDataDataSetNames, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CHPMultiDataData::SetEntryCount (MultiDataType dataType, int32_t ln, int32_t maxln, const std::vector< ColumnInfo > & columns, const std::wstring & groupName = L"")
Sets the number of entries (probe sets).
Parameters:
dataType The data type
ln The number of probe sets.
maxln The maximum length of a probe set name.
columns An array of metric columns
groupName The group name
Definition at line 410 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataSetInfo::dataSetIndex, affymetrix_calvin_io::DataSetInfo::dataType, affymetrix_calvin_io::DataSetInfo::entries, affymetrix_calvin_io::DataSetInfo::maxName, affymetrix_calvin_io::DataSetInfo::metricColumns, MULTI_DATA_NAME, affymetrix_calvin_io::MultiDataDataSetNames, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by CreateFileWithHeader(), and CopyNumberResultWriter::CreateResultFile().
void CHPMultiDataData::SetEntryCount (MultiDataType dataType, int32_t ln, int32_t maxln, const std::wstring & groupName = L"")
Sets the number of entries (probe sets).
Parameters:
dataType The data type
ln The number of probe sets.
maxln The maximum length of a probe set name.
groupName The group name
Definition at line 433 of file CHPMultiDataData.cpp.
void CHPMultiDataData::SetFilename (const std::string & p)
Sets the file name.
Parameters:
p The name of the CHP file
Definition at line 329 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::GenericData::Header(), and affymetrix_calvin_io::FileHeader::SetFilename().
void CHPMultiDataData::SetWStringToGenericHdr (const std::wstring & name, const std::wstring value, int32_t reserve = -1) [private]
Adds a parameter name/value pair to the parameters section.
Parameters:
name The name of the parameter.
value The value of the parameter.
reserve The length of the string to reserve.
Definition at line 1393 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
Member Data Documentation
std::map<MultiDataType, DataSetInfo> affymetrix_calvin_io::CHPMultiDataData::dataSetInfo [private]
chp data sets
Definition at line 217 of file CHPMultiDataData.h.
std::map<MultiDataType, std::wstring> affymetrix_calvin_io::CHPMultiDataData::dataTypeGroupNames [private]
data groups
Definition at line 220 of file CHPMultiDataData.h.
GenericData affymetrix_calvin_io::CHPMultiDataData::genericData [private]
The generic data item.
Definition at line 214 of file CHPMultiDataData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CHPMultiDataData.h
C:/f112/affy/sdk/calvin_files/data/src/CHPMultiDataData.cpp