Affymetrix Fusion SDK: affymetrix_calvin_io::GenericDataHeaderUpdater Class Reference
affymetrix_calvin_io::GenericDataHeaderUpdater Class Reference
#include <GenericDataHeaderUpdater.h>
Public Member Functions
GenericDataHeaderUpdater ()
~GenericDataHeaderUpdater ()
bool Update (std::ofstream &fileStream, GenericDataHeader &updateHeader, GenericDataHeader &currentHdr)
bool UpdateFileId ()
void UpdateParameters ()
Static Public Attributes
static const int32_t FIELD_LEN_SIZE = sizeof(int32_t)
Private Member Functions
int32_t GetFileHeaderSize ()
int32_t GetBytesFromGenericDataHdrStartToParameterList ()
Private Attributes
std::ofstream * os
GenericDataHeader * updateHdr
GenericDataHeader * currentHdr
Detailed Description
This class updates the GenericDataHeader of an existing file with new information.
Definition at line 39 of file GenericDataHeaderUpdater.h.
Constructor & Destructor Documentation
GenericDataHeaderUpdater::GenericDataHeaderUpdater ()
Constructor
Definition at line 37 of file GenericDataHeaderUpdater.cpp.
GenericDataHeaderUpdater::~GenericDataHeaderUpdater ()
Destructor
Definition at line 47 of file GenericDataHeaderUpdater.cpp.
Member Function Documentation
int32_t GenericDataHeaderUpdater::GetBytesFromGenericDataHdrStartToParameterList () [private]
Get the size of the GenericDataHeader up to the start of the parameter list.
Returns:
The size of the GenericDataHeader up to the start of the parameter list.
Definition at line 141 of file GenericDataHeaderUpdater.cpp.
References WCHAR_T_SIZE.
int32_t GenericDataHeaderUpdater::GetFileHeaderSize () [private]
Get the size of the FileHeader in bytes.
Returns:
The size of the FileHeader.
Definition at line 133 of file GenericDataHeaderUpdater.cpp.
bool GenericDataHeaderUpdater::Update (std::ofstream & fileStream, GenericDataHeader & updateHeader, GenericDataHeader & currentHdr)
Update the file with the new GenericDataHeader information. The current implementation just updates the FileId.
Parameters:
fileStream An output stream open with std::ios::out|std::ios::binary|std::ios::in.
updateHeader A GenericDataHeader with information to update the file.
currentHdr The GenericDataHeader object with the information currently in the file.
Returns:
Returns true if the FileId could be udpated.
Definition at line 54 of file GenericDataHeaderUpdater.cpp.
Referenced by affymetrix_calvin_io::FileHeaderUpdater::Update().
bool GenericDataHeaderUpdater::UpdateFileId ()
Update the FileId. Only update the FileId if update and current fileIDs are the same size.
Returns:
Returns true if successful.
Definition at line 68 of file GenericDataHeaderUpdater.cpp.
void GenericDataHeaderUpdater::UpdateParameters ()
Update the parameter list. Can only update types that have the same name and type and value size in the source and target
Definition at line 89 of file GenericDataHeaderUpdater.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetMIMEValue(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), and WCHAR_T_SIZE.
Member Data Documentation
GenericDataHeader* affymetrix_calvin_io::GenericDataHeaderUpdater::currentHdr [private]
The GenericDataHeader with current information
Definition at line 86 of file GenericDataHeaderUpdater.h.
const int32_t affymetrix_calvin_io::GenericDataHeaderUpdater::FIELD_LEN_SIZE = sizeof(int32_t) [static]
Definition at line 43 of file GenericDataHeaderUpdater.h.
std::ofstream* affymetrix_calvin_io::GenericDataHeaderUpdater::os [private]
Open output filestream
Definition at line 82 of file GenericDataHeaderUpdater.h.
GenericDataHeader* affymetrix_calvin_io::GenericDataHeaderUpdater::updateHdr [private]
A GenericDataHeader with information to use to update the target
Definition at line 84 of file GenericDataHeaderUpdater.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/GenericDataHeaderUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/GenericDataHeaderUpdater.cpp