Affymetrix Fusion SDK: CFusionCDFFileHeaderCOM Class Reference
CFusionCDFFileHeaderCOM Class Reference
#include <FusionCDFFileHeaderCOM.h>
Public Member Functions
CFusionCDFFileHeaderCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
void SetHeader (affymetrix_fusion_io::FusionCDFFileHeader *h)
STDMETHOD() get_Cols (int *pVal)
STDMETHOD() get_Rows (int *pVal)
STDMETHOD() get_NumProbeSets (int *pVal)
STDMETHOD() get_NumQCProbeSets (int *pVal)
STDMETHOD() get_Reference (BSTR *pVal)
STDMETHOD() get_FormatVersion (int *pVal)
STDMETHOD() get_GUID (BSTR *pVal)
STDMETHOD() get_IntegrityMd5 (BSTR *pVal)
Private Attributes
affymetrix_fusion_io::FusionCDFFileHeader * header
Detailed Description
Definition at line 30 of file FusionCDFFileHeaderCOM.h.
Constructor & Destructor Documentation
CFusionCDFFileHeaderCOM::CFusionCDFFileHeaderCOM () [inline]
Definition at line 37 of file FusionCDFFileHeaderCOM.h.
Member Function Documentation
HRESULT CFusionCDFFileHeaderCOM::FinalConstruct () [inline]
Definition at line 57 of file FusionCDFFileHeaderCOM.h.
void CFusionCDFFileHeaderCOM::FinalRelease () [inline]
Definition at line 62 of file FusionCDFFileHeaderCOM.h.
STDMETHODIMP CFusionCDFFileHeaderCOM::get_Cols (int * pVal)
Definition at line 42 of file FusionCDFFileHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCDFFileHeader::GetCols(), and header.
STDMETHODIMP CFusionCDFFileHeaderCOM::get_FormatVersion (int * pVal)
Definition at line 72 of file FusionCDFFileHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCDFFileHeader::GetFormatVersion(), and header.
STDMETHODIMP CFusionCDFFileHeaderCOM::get_GUID (BSTR * pVal)
Definition at line 78 of file FusionCDFFileHeaderCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionCDFFileHeader::GetGUID(), and header.
STDMETHODIMP CFusionCDFFileHeaderCOM::get_IntegrityMd5 (BSTR * pVal)
Definition at line 84 of file FusionCDFFileHeaderCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionCDFFileHeader::GetIntegrityMd5(), and header.
STDMETHODIMP CFusionCDFFileHeaderCOM::get_NumProbeSets (int * pVal)
Definition at line 54 of file FusionCDFFileHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), and header.
STDMETHODIMP CFusionCDFFileHeaderCOM::get_NumQCProbeSets (int * pVal)
Definition at line 60 of file FusionCDFFileHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCDFFileHeader::GetNumQCProbeSets(), and header.
STDMETHODIMP CFusionCDFFileHeaderCOM::get_Reference (BSTR * pVal)
Definition at line 66 of file FusionCDFFileHeaderCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionCDFFileHeader::GetReference(), and header.
STDMETHODIMP CFusionCDFFileHeaderCOM::get_Rows (int * pVal)
Definition at line 48 of file FusionCDFFileHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCDFFileHeader::GetRows(), and header.
STDMETHODIMP CFusionCDFFileHeaderCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 27 of file FusionCDFFileHeaderCOM.cpp.
void CFusionCDFFileHeaderCOM::SetHeader (affymetrix_fusion_io::FusionCDFFileHeader * h) [inline]
Definition at line 70 of file FusionCDFFileHeaderCOM.h.
Referenced by CFusionCDFDataCOM::GetHeader().
Member Data Documentation
affymetrix_fusion_io::FusionCDFFileHeader* CFusionCDFFileHeaderCOM::header [private]
Definition at line 67 of file FusionCDFFileHeaderCOM.h.
Referenced by get_Cols(), get_FormatVersion(), get_GUID(), get_IntegrityMd5(), get_NumProbeSets(), get_NumQCProbeSets(), get_Reference(), and get_Rows().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFFileHeaderCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFFileHeaderCOM.cpp