Affymetrix Fusion SDK: affymetrix_calvin_io::GenericFileUpdater Class Reference
affymetrix_calvin_io::GenericFileUpdater Class Reference
#include <GenericFileUpdater.h>
Public Member Functions
GenericFileUpdater (const std::string &path)
~GenericFileUpdater ()
DataSetWriter * GetUpdateDataSetWriter (DataSetHeader &dataSetHdr)
void IncrementDataSetCnt ()
Private Member Functions
void AppendDataSet (DataSetHeader &hdr, Uint8Vector &data, u_int32_t offset) const
bool FindLastDataSetHeader (FileHeader &fileHdr, DataSetHeader &dataSetHdr) const
FileHeader ReadFileHeader (const std::string &path) const
u_int32_t FindLastDataGroupOffset ()
u_int32_t GetLastDataGroupDataSetCnt ()
Private Attributes
GenericFileWriter * writer
FileHeader fileHdr
u_int32_t lastDataGrpOffset
u_int32_t lastDataGrpDataSetCnt
Detailed Description
Definition at line 36 of file GenericFileUpdater.h.
Constructor & Destructor Documentation
GenericFileUpdater::GenericFileUpdater (const std::string & path)
Definition at line 26 of file GenericFileUpdater.cpp.
References fileHdr, FindLastDataGroupOffset(), GetLastDataGroupDataSetCnt(), lastDataGrpDataSetCnt, lastDataGrpOffset, ReadFileHeader(), and writer.
GenericFileUpdater::~GenericFileUpdater ()
Definition at line 34 of file GenericFileUpdater.cpp.
References writer.
Member Function Documentation
void affymetrix_calvin_io::GenericFileUpdater::AppendDataSet (DataSetHeader & hdr, Uint8Vector & data, u_int32_t offset) const [private]
u_int32_t GenericFileUpdater::FindLastDataGroupOffset () [private]
Definition at line 136 of file GenericFileUpdater.cpp.
References fileHdr, affymetrix_calvin_io::FileHeader::GetDataGroupIts(), and affymetrix_calvin_io::FileHeader::GetFirstDataGroupFilePos().
Referenced by GenericFileUpdater().
bool GenericFileUpdater::FindLastDataSetHeader (FileHeader & fileHdr, DataSetHeader & dataSetHdr) const [private]
Definition at line 94 of file GenericFileUpdater.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), and affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt().
Referenced by GetUpdateDataSetWriter().
u_int32_t GenericFileUpdater::GetLastDataGroupDataSetCnt () [private]
Definition at line 120 of file GenericFileUpdater.cpp.
References fileHdr, and affymetrix_calvin_io::FileHeader::GetDataGroupIts().
Referenced by GenericFileUpdater().
DataSetWriter * GenericFileUpdater::GetUpdateDataSetWriter (DataSetHeader & dataSetHdr)
Definition at line 39 of file GenericFileUpdater.cpp.
References affymetrix_calvin_io::DataGroupWriter::CreateDataSetWriter(), fileHdr, FindLastDataSetHeader(), affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataSetHeader::GetHeaderStartFilePos(), affymetrix_calvin_io::DataSetHeader::GetName(), affymetrix_calvin_io::DataSetHeader::GetNextSetFilePos(), IncrementDataSetCnt(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), and writer.
void GenericFileUpdater::IncrementDataSetCnt ()
Definition at line 111 of file GenericFileUpdater.cpp.
References affymetrix_calvin_io::GenericFileWriter::GetFilePos(), lastDataGrpDataSetCnt, lastDataGrpOffset, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::GenericFileWriter::Write(), and writer.
Referenced by GetUpdateDataSetWriter().
FileHeader GenericFileUpdater::ReadFileHeader (const std::string & path) const [private]
Definition at line 84 of file GenericFileUpdater.cpp.
References affymetrix_calvin_io::GenericData::Close(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::GenericFileReader::ReadHeader(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
Referenced by GenericFileUpdater().
Member Data Documentation
FileHeader affymetrix_calvin_io::GenericFileUpdater::fileHdr [private]
Definition at line 42 of file GenericFileUpdater.h.
Referenced by FindLastDataGroupOffset(), GenericFileUpdater(), GetLastDataGroupDataSetCnt(), and GetUpdateDataSetWriter().
u_int32_t affymetrix_calvin_io::GenericFileUpdater::lastDataGrpDataSetCnt [private]
Definition at line 44 of file GenericFileUpdater.h.
Referenced by GenericFileUpdater(), and IncrementDataSetCnt().
u_int32_t affymetrix_calvin_io::GenericFileUpdater::lastDataGrpOffset [private]
Definition at line 43 of file GenericFileUpdater.h.
Referenced by GenericFileUpdater(), and IncrementDataSetCnt().
GenericFileWriter* affymetrix_calvin_io::GenericFileUpdater::writer [private]
Definition at line 41 of file GenericFileUpdater.h.
Referenced by GenericFileUpdater(), GetUpdateDataSetWriter(), IncrementDataSetCnt(), and ~GenericFileUpdater().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/GenericFileUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/GenericFileUpdater.cpp