Affymetrix Fusion SDK: affx::SpfFile Class Reference
affx::SpfFile Class Reference
#include <SpfFile.h>
Public Types
enum spf_format_t {
FMT_UNSET = 0, FMT_1 = 1, FMT_2 = 2, FMT_3 = 3,
FMT_4 = 4
}
Public Member Functions
SpfFile ()
void clearOptions ()
void clearHeaderInfo ()
void clearCidx ()
void dumpCidx ()
void setFormat (int fmt)
int determineFormat ()
int openSpf (const std::string &fileName)
void define_file (int version)
void define_v2 ()
void define_v3 ()
void define_v4 ()
int writeSpf (const std::string &fileName)
int writeSpf (const std::string &fileName, int format)
void addStandardHeaders ()
Public Attributes
int m_spf_format
1,2 or 3.
std::string m_header_format
std::vector< std::string > m_header_chipTypes
int m_header_numCols
int m_header_numRows
int m_header_numProbesets
int m_header_numChannels
int m_has_allele_info
enable/disable these on before calling "define_v{2,3}" to get the extra columns.
int m_has_context_info
int m_has_channel_info
int m_has_rep_type_info
int m_name_cidx
When openSpf is called all the "m_XXX_cidx" members are set.
int m_type_cidx
int m_num_match_cidx
int m_v2_num_blocks_cidx
int m_v2_block_sizes_cidx
int m_v2_block_annotations_cidx
int m_v2_num_probes_cidx
int m_v2_probes_cidx
int m_v2_block_alleles_cidx
int m_v2_block_contexts_cidx
int m_v2_block_channels_cidx
int m_v2_block_rep_types_cidx
int m_v3_allele_lbl_cidx
int m_v3_allele_code_cidx
int m_v3_context_lbl_cidx
int m_v3_context_code_cidx
int m_v3_channel_code_cidx
int m_v3_rep_type_cidx
int m_v3_annotation_code_cidx
int m_v3_probe_id_cidx
int m_v4_block_lbl_cidx
int m_v4_annotation_code_cidx
int m_v4_allele_code_cidx
int m_v4_context_code_cidx
int m_v4_channel_code_cidx
int m_v4_rep_type_cidx
int m_v4_probe_id_cidx
Private Member Functions
void define_v2_cols ()
Detailed Description
Definition at line 148 of file SpfFile.h.
Member Enumeration Documentation
enum affx::SpfFile::spf_format_t
Enumerator:
FMT_UNSET
FMT_1
FMT_2
FMT_3
FMT_4
Definition at line 151 of file SpfFile.h.
Constructor & Destructor Documentation
affx::SpfFile::SpfFile ()
Definition at line 22 of file SpfFile.cpp.
References clearCidx(), clearHeaderInfo(), and clearOptions().
Member Function Documentation
void affx::SpfFile::addStandardHeaders ()
Definition at line 448 of file SpfFile.cpp.
References spf_standard_headers.
void affx::SpfFile::clearCidx ()
Definition at line 51 of file SpfFile.cpp.
Referenced by SpfFile().
void affx::SpfFile::clearHeaderInfo ()
Definition at line 40 of file SpfFile.cpp.
Referenced by SpfFile().
void affx::SpfFile::clearOptions ()
Definition at line 29 of file SpfFile.cpp.
References FMT_UNSET.
Referenced by SpfFile().
void affx::SpfFile::define_file (int version)
Definition at line 281 of file SpfFile.cpp.
References APT_ERR_ABORT.
void affx::SpfFile::define_v2 ()
Definition at line 153 of file SpfFile.cpp.
void affx::SpfFile::define_v2_cols () [private]
void affx::SpfFile::define_v3 ()
Definition at line 197 of file SpfFile.cpp.
void affx::SpfFile::define_v4 ()
Definition at line 240 of file SpfFile.cpp.
int affx::SpfFile::determineFormat ()
Definition at line 324 of file SpfFile.cpp.
void affx::SpfFile::dumpCidx ()
Definition at line 98 of file SpfFile.cpp.
References DUMP_CIDX, and DUMP_CIDX_HEAD.
int affx::SpfFile::openSpf (const std::string & fileName)
Definition at line 370 of file SpfFile.cpp.
References APT_ERR_ABORT, ToStr(), and affx::TSV_OK.
void affx::SpfFile::setFormat (int fmt)
Definition at line 145 of file SpfFile.cpp.
int affx::SpfFile::writeSpf (const std::string & fileName, int format)
Definition at line 315 of file SpfFile.cpp.
int affx::SpfFile::writeSpf (const std::string & fileName)
Definition at line 297 of file SpfFile.cpp.
References APT_ERR_ABORT, FMT_1, FMT_2, FMT_3, and FMT_4.
Member Data Documentation
int affx::SpfFile::m_has_allele_info
enable/disable these on before calling "define_v{2,3}" to get the extra columns.
Definition at line 171 of file SpfFile.h.
int affx::SpfFile::m_has_channel_info
Definition at line 173 of file SpfFile.h.
int affx::SpfFile::m_has_context_info
Definition at line 172 of file SpfFile.h.
int affx::SpfFile::m_has_rep_type_info
Definition at line 174 of file SpfFile.h.
std::vector<std::string> affx::SpfFile::m_header_chipTypes
Definition at line 164 of file SpfFile.h.
std::string affx::SpfFile::m_header_format
Definition at line 163 of file SpfFile.h.
int affx::SpfFile::m_header_numChannels
Definition at line 168 of file SpfFile.h.
int affx::SpfFile::m_header_numCols
Definition at line 165 of file SpfFile.h.
int affx::SpfFile::m_header_numProbesets
Definition at line 167 of file SpfFile.h.
int affx::SpfFile::m_header_numRows
Definition at line 166 of file SpfFile.h.
int affx::SpfFile::m_name_cidx
When openSpf is called all the "m_XXX_cidx" members are set.
all formats v1,v2,v3,v4
Definition at line 180 of file SpfFile.h.
int affx::SpfFile::m_num_match_cidx
Definition at line 182 of file SpfFile.h.
int affx::SpfFile::m_spf_format
1,2 or 3.
Definition at line 160 of file SpfFile.h.
int affx::SpfFile::m_type_cidx
Definition at line 181 of file SpfFile.h.
int affx::SpfFile::m_v2_block_alleles_cidx
Definition at line 191 of file SpfFile.h.
int affx::SpfFile::m_v2_block_annotations_cidx
Definition at line 188 of file SpfFile.h.
int affx::SpfFile::m_v2_block_channels_cidx
Definition at line 193 of file SpfFile.h.
int affx::SpfFile::m_v2_block_contexts_cidx
Definition at line 192 of file SpfFile.h.
int affx::SpfFile::m_v2_block_rep_types_cidx
Definition at line 194 of file SpfFile.h.
int affx::SpfFile::m_v2_block_sizes_cidx
Definition at line 187 of file SpfFile.h.
int affx::SpfFile::m_v2_num_blocks_cidx
Definition at line 186 of file SpfFile.h.
int affx::SpfFile::m_v2_num_probes_cidx
Definition at line 189 of file SpfFile.h.
int affx::SpfFile::m_v2_probes_cidx
Definition at line 190 of file SpfFile.h.
int affx::SpfFile::m_v3_allele_code_cidx
Definition at line 199 of file SpfFile.h.
int affx::SpfFile::m_v3_allele_lbl_cidx
Definition at line 198 of file SpfFile.h.
int affx::SpfFile::m_v3_annotation_code_cidx
Definition at line 205 of file SpfFile.h.
int affx::SpfFile::m_v3_channel_code_cidx
Definition at line 203 of file SpfFile.h.
int affx::SpfFile::m_v3_context_code_cidx
Definition at line 202 of file SpfFile.h.
int affx::SpfFile::m_v3_context_lbl_cidx
Definition at line 201 of file SpfFile.h.
int affx::SpfFile::m_v3_probe_id_cidx
Definition at line 207 of file SpfFile.h.
int affx::SpfFile::m_v3_rep_type_cidx
Definition at line 204 of file SpfFile.h.
int affx::SpfFile::m_v4_allele_code_cidx
Definition at line 213 of file SpfFile.h.
int affx::SpfFile::m_v4_annotation_code_cidx
Definition at line 212 of file SpfFile.h.
int affx::SpfFile::m_v4_block_lbl_cidx
Definition at line 211 of file SpfFile.h.
int affx::SpfFile::m_v4_channel_code_cidx
Definition at line 215 of file SpfFile.h.
int affx::SpfFile::m_v4_context_code_cidx
Definition at line 214 of file SpfFile.h.
int affx::SpfFile::m_v4_probe_id_cidx
Definition at line 218 of file SpfFile.h.
int affx::SpfFile::m_v4_rep_type_cidx
Definition at line 216 of file SpfFile.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/SpfFile.h
C:/f112/affy/sdk/file/TsvFile/SpfFile.cpp