Affymetrix Fusion SDK: affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter Class Reference
affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter Class Reference
#include <CalvinCHPQuantificationDetectionFileBufferWriter.h>
Public Member Functions
CHPQuantificationDetectionFileBufferWriter ()
~CHPQuantificationDetectionFileBufferWriter ()
void SetMaxBufferSize (int MaxBufferSize)
void Cleanup ()
void Initialize (std::vector< std::string > *CHPFileNames)
void WriteQuantificationEntry (int target, float quantification)
void FlushBuffer ()
Private Attributes
std::vector< std::string > * m_CHPFileNames
std::vector< std::vector< float > > m_TargetQuantificationDetectionBuffers
std::vector< int > m_TargetQuantificationDetectionRowIndexes
int m_BufferSize
int m_MaxBufferSize
Detailed Description
Definition at line 41 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
Constructor & Destructor Documentation
CHPQuantificationDetectionFileBufferWriter::CHPQuantificationDetectionFileBufferWriter ()
Constructor
Definition at line 36 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References m_BufferSize, m_MaxBufferSize, and MAX_BUFFER_SIZE.
CHPQuantificationDetectionFileBufferWriter::~CHPQuantificationDetectionFileBufferWriter ()
Destructor
Definition at line 42 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References Cleanup(), and FlushBuffer().
Member Function Documentation
void CHPQuantificationDetectionFileBufferWriter::Cleanup ()
Cleans up memory
Definition at line 48 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References m_TargetQuantificationDetectionBuffers.
Referenced by Initialize(), and ~CHPQuantificationDetectionFileBufferWriter().
void CHPQuantificationDetectionFileBufferWriter::FlushBuffer ()
Write the content of the buffer to CHP files.
Definition at line 80 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References affymetrix_calvin_io::CalvinCHPFileUpdater::CloseCHPFile(), m_BufferSize, m_CHPFileNames, m_TargetQuantificationDetectionBuffers, m_TargetQuantificationDetectionRowIndexes, affymetrix_calvin_io::CalvinCHPFileUpdater::OpenCHPFile(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer().
Referenced by WriteQuantificationEntry(), and ~CHPQuantificationDetectionFileBufferWriter().
void CHPQuantificationDetectionFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames)
Initialize Quantification buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
Definition at line 57 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References Cleanup(), m_BufferSize, m_CHPFileNames, m_TargetQuantificationDetectionBuffers, and m_TargetQuantificationDetectionRowIndexes.
void affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::SetMaxBufferSize (int MaxBufferSize) [inline]
Set maximum buffer size
Definition at line 51 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
References m_MaxBufferSize.
void CHPQuantificationDetectionFileBufferWriter::WriteQuantificationEntry (int target, float quantification)
Write a quantification entry to buffer. If the buffer is full, flush it.
Parameters:
target Target for the quantification entry.
quantification Value for the quantification entry.
Definition at line 70 of file CalvinCHPQuantificationDetectionFileBufferWriter.cpp.
References FlushBuffer(), m_BufferSize, m_MaxBufferSize, and m_TargetQuantificationDetectionBuffers.
Member Data Documentation
int affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::m_BufferSize [private]
Definition at line 81 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
Referenced by CHPQuantificationDetectionFileBufferWriter(), FlushBuffer(), Initialize(), and WriteQuantificationEntry().
std::vector<std::string>* affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::m_CHPFileNames [private]
Definition at line 72 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
Referenced by FlushBuffer(), and Initialize().
int affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::m_MaxBufferSize [private]
Definition at line 84 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
Referenced by CHPQuantificationDetectionFileBufferWriter(), SetMaxBufferSize(), and WriteQuantificationEntry().
std::vector< std::vector<float> > affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::m_TargetQuantificationDetectionBuffers [private]
Definition at line 75 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
Referenced by Cleanup(), FlushBuffer(), Initialize(), and WriteQuantificationEntry().
std::vector<int> affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::m_TargetQuantificationDetectionRowIndexes [private]
Definition at line 78 of file CalvinCHPQuantificationDetectionFileBufferWriter.h.
Referenced by FlushBuffer(), and Initialize().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPQuantificationDetectionFileBufferWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPQuantificationDetectionFileBufferWriter.cpp