Affymetrix Fusion SDK: affymetrix_calvin_io::DataSetReader Class Reference
affymetrix_calvin_io::DataSetReader Class Reference
#include <DataSetReader.h>
Public Member Functions
DataSetReader (std::ifstream &s, DataSetHeader &d)
~DataSetReader ()
std::wstring GetDataSetName () const
const DataSetHeader & GetDataSetHeader ()
int32_t ReadBuffer (char *buffer, int32_t count)
void Read (int8_t &value)
void Read (u_int8_t &value)
void Read (int16_t &value)
void Read (u_int16_t &value)
void Read (int32_t &value)
void Read (u_int32_t &value)
void Read (float &value)
void Read (std::string &value)
void Read (std::wstring &value)
Private Attributes
std::ifstream & fileStream
DataSetHeader & dataSetHdr
Detailed Description
Class to read a DataSet
Definition at line 40 of file DataSetReader.h.
Constructor & Destructor Documentation
DataSetReader::DataSetReader (std::ifstream & s, DataSetHeader & d)
Constructor
Parameters:
s Reference to an open ifstream
d Reference to a DataSetHeader that has been initialized
Definition at line 31 of file DataSetReader.cpp.
References dataSetHdr, fileStream, and affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos().
DataSetReader::~DataSetReader ()
Destructor
Definition at line 40 of file DataSetReader.cpp.
Member Function Documentation
const DataSetHeader& affymetrix_calvin_io::DataSetReader::GetDataSetHeader () [inline]
Get the DataSetHeader
Returns:
DataSetHeader
Definition at line 64 of file DataSetReader.h.
References dataSetHdr.
Referenced by affymetrix_calvin_io::DATFileReader::ReadGlobalGrid(), and affymetrix_calvin_io::DATFileReader::ReadSubgrids().
std::wstring DataSetReader::GetDataSetName () const
Get the DataSet name
Returns:
DataSet name
Definition at line 47 of file DataSetReader.cpp.
References dataSetHdr, and affymetrix_calvin_io::DataSetHeader::GetName().
void DataSetReader::Read (std::string & value)
Read string from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 120 of file DataSetReader.cpp.
References fileStream, and affymetrix_calvin_io::FileInput::ReadString8().
void DataSetReader::Read (float & value)
Read float from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 112 of file DataSetReader.cpp.
References fileStream, and affymetrix_calvin_io::FileInput::ReadFloat().
void DataSetReader::Read (u_int32_t & value)
Read u_int32_t from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 104 of file DataSetReader.cpp.
References fileStream, and affymetrix_calvin_io::FileInput::ReadUInt32().
void DataSetReader::Read (int8_t & value)
Read int8_t from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 64 of file DataSetReader.cpp.
References fileStream, and ReadInt8().
Referenced by affymetrix_calvin_io::DATFileReader::ReadGlobalGrid(), and affymetrix_calvin_io::DATFileReader::ReadSubgrids().
void DataSetReader::Read (u_int16_t & value)
Read u_int16_t from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 88 of file DataSetReader.cpp.
References fileStream, and affymetrix_calvin_io::FileInput::ReadUInt16().
void DataSetReader::Read (std::wstring & value)
Read wstring from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 128 of file DataSetReader.cpp.
References fileStream, and affymetrix_calvin_io::FileInput::ReadString16().
void DataSetReader::Read (u_int8_t & value)
Read u_int8_t from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 72 of file DataSetReader.cpp.
References fileStream, and ReadUInt8().
void DataSetReader::Read (int32_t & value)
Read int32_t from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 96 of file DataSetReader.cpp.
References fileStream, and affymetrix_calvin_io::FileInput::ReadInt32().
void DataSetReader::Read (int16_t & value)
Read int16_t from the DataSet. File stream position is incremented
Parameters:
value Variable reference to receive the value
Definition at line 80 of file DataSetReader.cpp.
References fileStream, and affymetrix_calvin_io::FileInput::ReadInt16().
int32_t DataSetReader::ReadBuffer (char * buffer, int32_t count)
Reads a byte buffer from the DataSet. File stream position is incremented
Parameters:
buffer Pointer to the buffer.
count Size of the buffer.
Returns:
The number of bytes read.
Definition at line 55 of file DataSetReader.cpp.
References fileStream.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataSet().
Member Data Documentation
DataSetHeader& affymetrix_calvin_io::DataSetReader::dataSetHdr [private]
Data dataSet header that has been initialized
Definition at line 123 of file DataSetReader.h.
Referenced by DataSetReader(), GetDataSetHeader(), and GetDataSetName().
std::ifstream& affymetrix_calvin_io::DataSetReader::fileStream [private]
Open file stream
Definition at line 121 of file DataSetReader.h.
Referenced by DataSetReader(), Read(), and ReadBuffer().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/DataSetReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/DataSetReader.cpp