Affymetrix Fusion SDK: SocketHandler Class Reference
SocketHandler Class Reference
#include <SocketHandler.h>
Public Types
enum MsgType { UNKNOWN_TYPE, TEXT, LAST_TYPE }
What type/format of message coming across.
enum MsgChannel {
UNKNOWN_CHANNEL, VERBOSE, PROGRESS, KILLMSG,
COMPLETION, LAST_CHANNEL
}
What channel of message coming across (like stdout,stderr, etc.)
Public Member Functions
virtual bool handlesChannel (int channel)
virtual bool handlesType (int type)
virtual void handleMessage (int type, int channel, const std::string &msg)=0
Static Public Member Functions
static std::string serializeMap (std::map< std::string, std::string > &pairs)
static std::map< std::string,
std::string > deserializeMap (const std::string &s)
Static Protected Member Functions
static bool evenPrecedingSlash (const std::string &s, int pos)
static bool isEscaped (const std::string &s, char c, int pos)
static int findNextNonEscape (const std::string &s, char c, int start)
Protected Attributes
std::set< int > m_Channels
std::set< int > m_Types
Collection of channels that a handler is interested in.
Detailed Description
A listener class that will be called by SocketBase to parse and utilize messages over a socket.
Definition at line 36 of file SocketHandler.h.
Member Enumeration Documentation
enum SocketHandler::MsgChannel
What channel of message coming across (like stdout,stderr, etc.)
Enumerator:
UNKNOWN_CHANNEL
VERBOSE
PROGRESS
KILLMSG
COMPLETION
LAST_CHANNEL
Definition at line 47 of file SocketHandler.h.
enum SocketHandler::MsgType
What type/format of message coming across.
Enumerator:
UNKNOWN_TYPE
TEXT
LAST_TYPE
Definition at line 40 of file SocketHandler.h.
Member Function Documentation
map< string, string > SocketHandler::deserializeMap (const std::string & s) [static]
Turn a serialized map back into a full map by parsing out the key=val pairs
Definition at line 73 of file SocketHandler.cpp.
References APT_ERR_ASSERT, and Util::deEscapeString().
Referenced by SocketTextHandler::handleMessage().
bool SocketHandler::evenPrecedingSlash (const std::string & s, int pos) [static, protected]
Is there an even number of escape slashes preceeding position?
Definition at line 24 of file SocketHandler.cpp.
int SocketHandler::findNextNonEscape (const std::string & s, char c, int start) [static, protected]
Find the next occurance of c after start that is not escaped.
Definition at line 51 of file SocketHandler.cpp.
virtual void SocketHandler::handleMessage (int type, int channel, const std::string & msg) [pure virtual]
Take a message and do whatever functionality this handler implements from simply displaying message to
Parameters:
type - What type (i.e. text, xml,) of message is this message.
channel - What channel (i.e. verbose, progress, etc.) is this message.
msg - Data to be parsed out
Implemented in SocketTextHandler.
virtual bool SocketHandler::handlesChannel (int channel) [inline, virtual]
Determine if this handler should be called on messages from this channel
Parameters:
channel - What channel (e.g. SocketHandler::VERBOSE)
Returns:
true if this handler is interested in messages from this channel
Definition at line 61 of file SocketHandler.h.
References m_Channels.
virtual bool SocketHandler::handlesType (int type) [inline, virtual]
Determine if this handler should be called on messages from this type
Parameters:
type - What type (e.g. SocketHandler::TEXT)
Returns:
true if this handler is interested in messages from this type
Definition at line 70 of file SocketHandler.h.
References m_Types.
bool SocketHandler::isEscaped (const std::string & s, char c, int pos) [static, protected]
Is this character at position pos escaped?
Definition at line 37 of file SocketHandler.cpp.
References APT_ERR_ASSERT, and ToStr().
string SocketHandler::serializeMap (std::map< std::string, std::string > & pairs) [static]
Turn a map into a serialized string like "key1=val1,key2=val2," where value strings are escaped to protect the ',' characters.
Definition at line 60 of file SocketHandler.cpp.
References APT_ERR_ASSERT, and Util::escapeString().
Referenced by MsgSocketHandler::finishedMsg(), MsgSocketHandler::message(), MsgSocketHandler::progressBegin(), MsgSocketHandler::progressEnd(), and MsgSocketHandler::progressStep().
Member Data Documentation
std::set<int> SocketHandler::m_Channels [protected]
Definition at line 112 of file SocketHandler.h.
Referenced by SocketTextHandler::handleMessage(), handlesChannel(), and SocketTextHandler::SocketTextHandler().
std::set<int> SocketHandler::m_Types [protected]
Collection of channels that a handler is interested in.
Definition at line 113 of file SocketHandler.h.
Referenced by SocketTextHandler::handleMessage(), handlesType(), and SocketTextHandler::SocketTextHandler().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/SocketHandler.h
C:/f112/affy/sdk/util/SocketHandler.cpp