Affymetrix Fusion SDK: affymetrix_calvin_io::CHPTilingData Class Reference
affymetrix_calvin_io::CHPTilingData Class Reference
#include <CHPTilingData.h>
Public Member Functions
CHPTilingData ()
CHPTilingData (const std::string &filename)
~CHPTilingData ()
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename () const
int32_t GetNumberSequences ()
void SetNumberSequences (int32_t value)
std::wstring GetAlgName ()
void SetAlgName (const std::wstring &value)
std::wstring GetAlgVersion ()
void SetAlgVersion (const std::wstring &value)
ParameterNameValueTypeList GetAlgParams ()
void AddAlgParams (const ParameterNameValueTypeList &params)
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
void AddTilingSequenceData (int32_t numEntries, const TilingSequenceData &data)
TilingSequenceData GetTilingSequenceData ()
int32_t GetTilingSequenceEntryCount (int index)
void OpenTilingSequenceDataSet (int index)
void GetTilingSequenceEntry (int row, CHPTilingEntry &e)
Private Member Functions
std::wstring GetWStringFromGenericHdr (const std::wstring &name)
void SetWStringToGenericHdr (const std::wstring &name, const std::wstring value)
int32_t GetInt32FromGenericHdr (const std::wstring &name)
void SetInt32ToGenericHdr (const std::wstring &name, int32_t value)
void AddColumns (DataSetHeader &hdr)
Private Attributes
GenericData genericData
int32_t cachedNumSequences
DataSet * entries
Detailed Description
Holds data associated with tiling array CHP files.
Definition at line 72 of file CHPTilingData.h.
Constructor & Destructor Documentation
CHPTilingData::CHPTilingData ()
Constructor
Definition at line 36 of file CHPTilingData.cpp.
CHPTilingData::CHPTilingData (const std::string & filename)
Constructor with file name.
Parameters:
filename The name of the CHP file.
Definition at line 42 of file CHPTilingData.cpp.
References CHP_TILING_GROUP, and CHP_TILING_TYPE.
CHPTilingData::~CHPTilingData ()
Destructor
Definition at line 61 of file CHPTilingData.cpp.
Member Function Documentation
void CHPTilingData::AddAlgParams (const ParameterNameValueTypeList & params)
Adds the algorithm parameters.
Parameters:
params The algorithm parameters.
Definition at line 1322 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), ALGORITHM_PARAM_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
void CHPTilingData::AddColumns (DataSetHeader & hdr) [private]
Adds the columns to the data set.
Parameters:
hdr The data set header.
Definition at line 156 of file CHPTilingData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), affymetrix_calvin_io::DataSetHeader::AddUIntColumn(), GenomicPositionColName, and ValueColName.
void CHPTilingData::AddTilingSequenceData (int32_t numEntries, const TilingSequenceData & data)
Adds a data group to the file.
Parameters:
numEntries The number of entries in the sequence.
data The data associated with the sequence.
Definition at line 90 of file CHPTilingData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataSetHeader::AddNameValParam(), FormatString1, affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), _TilingSequenceData::groupName, _TilingSequenceData::name, _TilingSequenceData::parameters, affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_io::DataSetHeader::SetName(), affymetrix_calvin_io::DataSetHeader::SetRowCnt(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), TILING_SEQ_GROUP_NAME, TILING_SEQ_NAME, TILING_SEQ_VERSION, and _TilingSequenceData::version.
void CHPTilingData::Clear ()
Clears the members.
Definition at line 66 of file CHPTilingData.cpp.
Referenced by affymetrix_calvin_io::CHPTilingFileReader::Read().
std::wstring CHPTilingData::GetAlgName ()
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 171 of file CHPTilingData.cpp.
References TILING_ALG_NAME.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::GetAlgName().
ParameterNameValueTypeList CHPTilingData::GetAlgParams ()
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 204 of file CHPTilingData.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and TILING_PARAM_SUFFIX.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::GetAlgParams().
std::wstring CHPTilingData::GetAlgVersion ()
Gets the algorithm version.
Returns:
The version.
Definition at line 181 of file CHPTilingData.cpp.
References TILING_ALG_VERSION.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::GetAlgVersion().
FileHeader* affymetrix_calvin_io::CHPTilingData::GetFileHeader () [inline]
Gets the file header.
Returns:
The file header.
Definition at line 154 of file CHPTilingData.h.
References genericData, and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_calvin_io::CHPTilingFileWriter::CHPTilingFileWriter().
std::string CHPTilingData::GetFilename () const
Gets the file name.
Returns:
The file name.
Definition at line 78 of file CHPTilingData.cpp.
Referenced by affymetrix_calvin_io::CHPTilingFileReader::Read().
GenericData& affymetrix_calvin_io::CHPTilingData::GetGenericData () [inline]
Gets the generic data object.
Returns:
The data object.
Definition at line 159 of file CHPTilingData.h.
References genericData.
Referenced by affymetrix_calvin_io::CHPTilingFileReader::Read().
int32_t CHPTilingData::GetInt32FromGenericHdr (const std::wstring & name) [private]
Gets a parameter value as an integer.
Parameters:
name The name of the parameter.
Returns:
The integer representation.
Definition at line 260 of file CHPTilingData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32().
int32_t CHPTilingData::GetNumberSequences ()
Gets the number of sequences.
Returns:
The number of sequences.
Definition at line 191 of file CHPTilingData.cpp.
References TILING_NUM_SEQS.
Referenced by affymetrix_calvin_io::CHPTilingFileWriter::CHPTilingFileWriter(), and affymetrix_fusion_io::FusionCHPTilingData::GetNumberSequences().
TilingSequenceData CHPTilingData::GetTilingSequenceData ()
Gets the sequence data.
Returns:
The data associated with the sequence.
Definition at line 122 of file CHPTilingData.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::DataSetHeader::GetNameValIterators(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), _TilingSequenceData::groupName, _TilingSequenceData::name, _TilingSequenceData::parameters, TILING_SEQ_GROUP_NAME, TILING_SEQ_NAME, TILING_SEQ_VERSION, and _TilingSequenceData::version.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::GetTilingSequenceData().
void CHPTilingData::GetTilingSequenceEntry (int row, CHPTilingEntry & e)
Returns the entry for the given row. The data set must be open.
Parameters:
row The row index.
e The entry.
Definition at line 52 of file CHPTilingData.cpp.
References affymetrix_calvin_io::_CHPTilingEntry::position, and affymetrix_calvin_io::_CHPTilingEntry::value.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::GetTilingSequenceEntry().
int32_t CHPTilingData::GetTilingSequenceEntryCount (int index)
Gets the number of entries in a tiling sequence.
Parameters:
index The sequence index.
Returns:
The number of entries in the sequence.
Definition at line 83 of file CHPTilingData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSet(), and affymetrix_calvin_io::DataSetHeader::GetRowCnt().
Referenced by affymetrix_fusion_io::FusionCHPTilingData::GetTilingSequenceEntryCount().
std::wstring CHPTilingData::GetWStringFromGenericHdr (const std::wstring & name) [private]
Gets a parameter value as a string.
Parameters:
name The name of the parameter.
Returns:
The string representation.
Definition at line 239 of file CHPTilingData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueText().
void CHPTilingData::OpenTilingSequenceDataSet (int index)
Opens a group for reading.
Parameters:
index The index to the sequence.
Definition at line 162 of file CHPTilingData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::OpenTilingSequenceDataSet().
void CHPTilingData::SetAlgName (const std::wstring & value)
Sets the name of the algorithm.
Parameters:
value The algorithm name.
Definition at line 176 of file CHPTilingData.cpp.
References TILING_ALG_NAME.
void CHPTilingData::SetAlgVersion (const std::wstring & value)
Sets the algorithm version.
Parameters:
value The version.
Definition at line 186 of file CHPTilingData.cpp.
References TILING_ALG_VERSION.
void CHPTilingData::SetFilename (const std::string & p)
Sets the file name.
Parameters:
p The name of the CHP file
Definition at line 73 of file CHPTilingData.cpp.
void CHPTilingData::SetInt32ToGenericHdr (const std::wstring & name, int32_t value) [private]
Adds a parameter name/value pair to the parameters section.
Parameters:
name The name of the parameter.
value The value of the parameter.
Definition at line 272 of file CHPTilingData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32().
void CHPTilingData::SetNumberSequences (int32_t value)
Sets the number of sequences.
Parameters:
value The number of sequences.
Definition at line 198 of file CHPTilingData.cpp.
References TILING_NUM_SEQS.
void CHPTilingData::SetWStringToGenericHdr (const std::wstring & name, const std::wstring value) [private]
Adds a parameter name/value pair to the parameters section.
Parameters:
name The name of the parameter.
value The value of the parameter.
Definition at line 251 of file CHPTilingData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
Member Data Documentation
int32_t affymetrix_calvin_io::CHPTilingData::cachedNumSequences [private]
keep number of sequences from being read from the header all the time
Definition at line 91 of file CHPTilingData.h.
DataSet* affymetrix_calvin_io::CHPTilingData::entries [private]
chp data sets
Definition at line 94 of file CHPTilingData.h.
GenericData affymetrix_calvin_io::CHPTilingData::genericData [private]
The generic data item.
Definition at line 88 of file CHPTilingData.h.
Referenced by GetFileHeader(), and GetGenericData().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CHPTilingData.h
C:/f112/affy/sdk/calvin_files/data/src/CHPMultiDataData.cpp
C:/f112/affy/sdk/calvin_files/data/src/CHPQuantificationData.cpp
C:/f112/affy/sdk/calvin_files/data/src/CHPQuantificationDetectionData.cpp
C:/f112/affy/sdk/calvin_files/data/src/CHPTilingData.cpp