Affymetrix Fusion SDK: CalvinDataSet Class Reference
CalvinDataSet Class Reference
#include <Calvin.h>
Public Member Functions
CalvinDataSet ()
virtual ~CalvinDataSet ()
void clear ()
void setName (const AffxString &str)
AffxString & getName ()
AffxArray< AffxString > & getColumnHeaders ()
AffxArray< AffxArray
< CalvinValue > > & getCalvinValues ()
int compareTo (CalvinDataSet &that, int iCompareCode)
Protected Attributes
AffxString m_strName
AffxArray< AffxString > m_vColumnHeaders
AffxArray< AffxArray
< CalvinValue > > m_mxCalvinValues
Detailed Description
Definition at line 186 of file Calvin.h.
Constructor & Destructor Documentation
CalvinDataSet::CalvinDataSet () [inline]
Definition at line 194 of file Calvin.h.
virtual CalvinDataSet::~CalvinDataSet () [inline, virtual]
Definition at line 198 of file Calvin.h.
References clear().
Member Function Documentation
void CalvinDataSet::clear () [inline]
Definition at line 203 of file Calvin.h.
References AffxArray< TYPE >::deleteAll(), AffxArray< TYPE >::getAt(), AffxArray< TYPE >::getCount(), m_mxCalvinValues, and m_vColumnHeaders.
Referenced by ~CalvinDataSet().
int CalvinDataSet::compareTo (CalvinDataSet & that, int iCompareCode) [inline]
Compare function.
Parameters:
that - A reference to an instance of this class.
iCompareCode - The code to switch on when doing compares. (Each code is a different compare.)
Returns:
- int value. (-1 if *this < that, 0 if *this == that, 1 if *this > that)
Definition at line 224 of file Calvin.h.
References AffxString::compareTo(), and m_strName.
AffxArray<AffxArray<CalvinValue> >& CalvinDataSet::getCalvinValues () [inline]
Definition at line 216 of file Calvin.h.
References m_mxCalvinValues.
Referenced by Calvin::equivalent(), and Calvin::load().
AffxArray<AffxString>& CalvinDataSet::getColumnHeaders () [inline]
Definition at line 215 of file Calvin.h.
References m_vColumnHeaders.
Referenced by Calvin::equivalent(), and Calvin::load().
AffxString& CalvinDataSet::getName () [inline]
Definition at line 214 of file Calvin.h.
References m_strName.
Referenced by Calvin::equivalent().
void CalvinDataSet::setName (const AffxString & str) [inline]
Definition at line 213 of file Calvin.h.
References m_strName.
Referenced by Calvin::load().
Member Data Documentation
AffxArray<AffxArray<CalvinValue> > CalvinDataSet::m_mxCalvinValues [protected]
Definition at line 191 of file Calvin.h.
Referenced by clear(), and getCalvinValues().
AffxString CalvinDataSet::m_strName [protected]
Definition at line 189 of file Calvin.h.
Referenced by compareTo(), getName(), and setName().
AffxArray<AffxString> CalvinDataSet::m_vColumnHeaders [protected]
Definition at line 190 of file Calvin.h.
Referenced by clear(), and getColumnHeaders().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/calvin_files/utils/src/Calvin.h