Affymetrix Fusion SDK: affymetrix_calvin_io::CDFFileReader Class Reference
affymetrix_calvin_io::CDFFileReader Class Reference
#include <CDFFileReader.h>
Public Types
enum ReadMode { ReadSequential, ReadByProbeSetNumber, ReadByProbeSetName }
Public Member Functions
CDFFileReader ()
~CDFFileReader ()
const std::string GetFilename () const
void SetFilename (const std::string &name)
void Read (CDFData &data, ReadMode mode=ReadSequential)
Protected Attributes
std::string fileName
Detailed Description
This class reads a CDF library file. It is an interpreter class.
Definition at line 43 of file CDFFileReader.h.
Member Enumeration Documentation
enum affymetrix_calvin_io::CDFFileReader::ReadMode
Enumerator:
ReadSequential
ReadByProbeSetNumber
ReadByProbeSetName
Definition at line 46 of file CDFFileReader.h.
Constructor & Destructor Documentation
CDFFileReader::CDFFileReader ()
Constructor
Definition at line 33 of file CDFFileReader.cpp.
CDFFileReader::~CDFFileReader ()
Destructor
Definition at line 40 of file CDFFileReader.cpp.
Member Function Documentation
const std::string affymetrix_calvin_io::CDFFileReader::GetFilename () const [inline]
Gets the name of the input file.
Returns:
The name of the file to read.
Definition at line 59 of file CDFFileReader.h.
References fileName.
void CDFFileReader::Read (CDFData & data, ReadMode mode = ReadSequential)
Reads the file header of the generic file.
Parameters:
data A reference to a CDFData object that will receive information from the file.
mode Indicates how the CDF data will be accessed
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 46 of file CDFFileReader.cpp.
References affymetrix_calvin_io::CDFData::Clear(), affymetrix_calvin_io::CDFData::GetFilename(), affymetrix_calvin_io::CDFData::GetGenericData(), affymetrix_calvin_io::CDFData::PrepareForAccessByProbeSetIndex(), affymetrix_calvin_io::CDFData::PrepareForAccessByProbeSetName(), affymetrix_calvin_io::CDFData::PrepareForSequentialAccess(), affymetrix_calvin_io::GenericFileReader::ReadHeader(), affymetrix_calvin_io::GenericFileReader::ReadNoDataGroupHeader, and affymetrix_calvin_io::GenericFileReader::SetFilename().
Referenced by affymetrix_fusion_io::FusionCDFData::Read(), and affymetrix_fusion_io::FusionCDFData::ReadHeader().
void affymetrix_calvin_io::CDFFileReader::SetFilename (const std::string & name) [inline]
Sets the name of the input file.
Parameters:
name The name of the file to read.
Definition at line 65 of file CDFFileReader.h.
References fileName.
Referenced by affymetrix_fusion_io::FusionCDFData::Read(), and affymetrix_fusion_io::FusionCDFData::ReadHeader().
Member Data Documentation
std::string affymetrix_calvin_io::CDFFileReader::fileName [protected]
Name of the file to read
Definition at line 79 of file CDFFileReader.h.
Referenced by GetFilename(), and SetFilename().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/CDFFileReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/CDFFileReader.cpp