Affymetrix Fusion SDK: Util Class Reference
Util Class Reference
Utility functions for memory, etc.
#include <Util.h>
Classes
struct ltstr
struct ltstring
class StaticMem
Static Public Member Functions
static void downcaseString_inplace (std::string &str)
static std::string downcaseString (const std::string &str_orig)
Copy and downcase a 8bit string.
static void upcaseString_inplace (std::string &str)
static std::string upcaseString (const std::string &str_orig)
Copy and upcase a 8bit string.
static std::string getTimeStamp ()
static int round (double x)
static char * cloneString (const char *)
static bool stringEndsWith (const std::string &str, const std::string &end)
Does the string end with the other string?
static bool endsWithStr (const std::string &str, const std::string &ending)
Check to see if STR ends with ENDING.
static bool endsWithStr (const std::string &str, const std::string &ending, int posFromEnd)
Checks to see if STR ends with ENDING ignoring the last POSFROMEND chars. Basicly the POSFROMEND acts as a wildcard "." at the end of the string.
static void chompLastIfSep (std::string &s)
Chop off the last character if it is a path separator. windows stat() can't handle having it there.
static std::string chopSuffix (const std::string &s, char d= '.')
static void chopString (const std::string &s, const char delim, std::vector< std::string > &words)
static void chopString (const std::string &s, const char *delims, std::vector< std::string > &words)
static void trimString (std::string &s, const char *whitespace=" \r\n\t")
Cut off any preceding and trailing white space.
static void changeEnd (std::string &str, const std::string &from, const std::string &to)
Change the end of a string.
static void changeEnd (std::vector< std::string > &str_vec, const std::string &from, const std::string &to)
Change the endings of a vector of strings.
static bool sameString (const std::string &s1, const std::string &s2)
Check to see if two strings are the same.
static int matrixDifferences (const std::string &targetFile, const std::string &queryFile, int colSkip, int rowSkip, double epsilon, bool printMismatch, bool matchRows, double fraction=0.0, int printMismatchMax=-1)
static void subChar (std::string &s, char from, char to)
static void replaceString (std::string &s, const std::string &from, const std::string &to)
static void breakByString (const std::string &s, const std::string &delim, std::vector< std::string > &words)
static void removeChar (std::string &s, char character)
static bool is32Bit ()
static int32_t schrageRandom (int32_t *ix)
static std::string asMB (uint64_t x)
static bool memInfo (uint64_t &free, uint64_t &total, uint64_t &swapAvail, uint64_t &memAvail, bool cap32bit=true)
static uint64_t getMemFreeAtStart ()
static uint64_t getMemFreeAtBlock ()
static void pushMemFreeAtStart ()
static void popMemFreeAtStart ()
static const char * nextWhiteSpace (const char *)
static void printStringWidth (std::ostream &out, const std::string &str, int prefix, int currentPos, int maxWidth=70)
static bool isFinite (double x)
static void PrintTextClassTitle (const std::string &className)
static void PrintTextFunctionTitle (const std::string &className, const std::string &functionName)
static std::vector< std::string > addPrefixSuffix (std::vector< std::string > middle, const std::string &prefix, const std::string &suffix)
static std::vector< std::string > addPrefixSuffix (const char *middle[], const std::string &prefix, const std::string &suffix)
static std::vector< std::string > addPrefixSuffix (const char *middle[], int size, const std::string &prefix, const std::string &suffix)
static std::vector< std::string > listToVector (const char *in[], int size)
static std::vector< std::string > listToVector (const char *in[])
static std::vector< std::string > addPrefixSuffix (const char *middle[], const std::string &prefix)
static std::vector< std::string > addPrefixSuffix (std::string middle[], const std::string &prefix, const std::string &suffix)
static std::vector< std::string > addPrefixSuffix (std::string middle[], int size, const std::string &prefix, const std::string &suffix)
static std::vector< std::string > listToVector (std::string in[])
static std::vector< std::string > listToVector (std::string in[], int size)
static std::string joinVectorString (std::vector< std::string > toJoin, const std::string &sep)
static std::string escapeString (const std::string &s, char c, char escape='\\')
static std::string deEscapeString (std::string &s, char escape='\\')
static std::wstring toWString (const std::string &src)
static std::string toString (const std::wstring &src)
Static Private Member Functions
static StaticMem & getStaticMem ()
Detailed Description
Utility functions for memory, etc.
Util
Definition at line 99 of file Util.h.
Member Function Documentation
std::vector< std::string > Util::addPrefixSuffix (std::vector< std::string > middle, const std::string & prefix, const std::string & suffix) [static]
Definition at line 912 of file Util.cpp.
References Fs::Unc().
std::vector< std::string > Util::addPrefixSuffix (const char * middle[], const std::string & prefix, const std::string & suffix) [static]
Definition at line 925 of file Util.cpp.
std::vector< std::string > Util::addPrefixSuffix (const char * middle[], int size, const std::string & prefix, const std::string & suffix) [static]
Definition at line 933 of file Util.cpp.
std::vector< std::string > Util::addPrefixSuffix (const char * middle[], const std::string & prefix) [static]
Definition at line 941 of file Util.cpp.
std::vector< std::string > Util::addPrefixSuffix (std::string middle[], const std::string & prefix, const std::string & suffix) [static]
Definition at line 975 of file Util.cpp.
std::vector< std::string > Util::addPrefixSuffix (std::string middle[], int size, const std::string & prefix, const std::string & suffix) [static]
Definition at line 983 of file Util.cpp.
std::string Util::asMB (uint64_t x) [static]
Definition at line 456 of file Util.cpp.
References MEGABYTE, and ToStr().
void Util::breakByString (const std::string & s, const std::string & delim, std::vector< std::string > & words) [static]
Definition at line 231 of file Util.cpp.
References APT_ERR_ASSERT.
void Util::changeEnd (std::string & str, const std::string & from, const std::string & to) [static]
Change the end of a string.
Parameters:
str string to change
from string to change from
to string to change to
Definition at line 872 of file Util.cpp.
void Util::changeEnd (std::vector< std::string > & str_vec, const std::string & from, const std::string & to) [static]
Change the endings of a vector of strings.
Parameters:
str_vec vector to change
from string to change from
to string to change to
Definition at line 879 of file Util.cpp.
void Util::chompLastIfSep (std::string & s) [static]
Chop off the last character if it is a path separator. windows stat() can't handle having it there.
Parameters:
s - string to have '/' or '\' chopped off if last.
Definition at line 192 of file Util.cpp.
References Fs::osPathSep().
void Util::chopString (const std::string & s, const char delim, std::vector< std::string > & words) [static]
Chop up a string into a vector of words.
Parameters:
s - string of interest.
delim - delimiter to split on.
words - vector to put words into, will be cleared then filled.
Chop up a string into a vector of words.
Parameters:
s - string of interest.
delim - delimiter to split on.
words - vector to put words into, will be cleared then filled.
Todo:
shouldnt this be "split"?
Definition at line 258 of file Util.cpp.
Referenced by Fs::findLibFile(), Convert::strToIntVec(), and Convert::strToStrVec().
void Util::chopString (const std::string & s, const char * delims, std::vector< std::string > & words) [static]
Chop up a string into a vector of words.
Parameters:
s - string of interest.
delims - delimiters to split on. The split will occur at any character
among those present in the string.
words - vector to put words into, will be cleared then filled.
Definition at line 281 of file Util.cpp.
std::string Util::chopSuffix (const std::string & s, char d = '.') [static]
Chop the last suffix (as defined by '.') from a string
Parameters:
- string to chop
- delimiter, default '.'
Definition at line 203 of file Util.cpp.
char * Util::cloneString (const char * s) [static]
Create a copy of a string. Free this with delete [] (or freezArray()) when done.
Parameters:
s - c-string to be copied.
Returns:
char * newly allocated c-string.
Definition at line 122 of file Util.cpp.
Referenced by TableFile::open().
static std::string Util::deEscapeString (std::string & s, char escape = '\\') [inline, static]
Definition at line 449 of file Util.h.
Referenced by SocketHandler::deserializeMap().
static std::string Util::downcaseString (const std::string & str_orig) [inline, static]
Copy and downcase a 8bit string.
Parameters:
str_orig
Returns:
Definition at line 114 of file Util.h.
static void Util::downcaseString_inplace (std::string & str) [inline, static]
Make the string all lowercase.
Parameters:
s - string to be modified
Definition at line 106 of file Util.h.
References affx::tolower().
bool Util::endsWithStr (const std::string & str, const std::string & ending) [static]
Check to see if STR ends with ENDING.
Parameters:
str
ending
Returns:
true if it does.
Definition at line 182 of file Util.cpp.
bool Util::endsWithStr (const std::string & str, const std::string & ending, int posFromEnd) [static]
Checks to see if STR ends with ENDING ignoring the last POSFROMEND chars. Basicly the POSFROMEND acts as a wildcard "." at the end of the string.
Parameters:
str
ending
posFromEnd number
Returns:
true if it does
Definition at line 173 of file Util.cpp.
static std::string Util::escapeString (const std::string & s, char c, char escape = '\\') [inline, static]
Definition at line 437 of file Util.h.
Referenced by SocketHandler::serializeMap().
uint64_t Util::getMemFreeAtBlock () [static]
Definition at line 1012 of file Util.cpp.
References Util::StaticMem::getMemFreeAtBlock().
Referenced by LogStream::profileString().
uint64_t Util::getMemFreeAtStart () [static]
Definition at line 1007 of file Util.cpp.
References Util::StaticMem::getMemFreeAtStart().
Referenced by LogStream::profileString().
Util::StaticMem & Util::getStaticMem () [static, private]
Definition at line 1002 of file Util.cpp.
std::string Util::getTimeStamp () [static]
Get a timestamp string.
Returns:
- pointer to statically allocated buffer with time.
Definition at line 861 of file Util.cpp.
References APT_ERR_ASSERT.
Referenced by tsvJoin::beginOutputHeader(), BaseEngine::run(), and dumpPgf::writeOutputHeader().
static bool Util::is32Bit () [inline, static]
Definition at line 335 of file Util.h.
bool Util::isFinite (double x) [static]
Wrapper for different version of isnan() on different systems.
Parameters:
x - number to be checked for NaN or INF
Returns:
- true if x is finite (-INF < x && x < +INF && x != nan), false otherwise
Definition at line 851 of file Util.cpp.
Referenced by Calvin::equivalent().
std::string Util::joinVectorString (std::vector< std::string > toJoin, const std::string & sep) [static]
Definition at line 991 of file Util.cpp.
std::vector< std::string > Util::listToVector (std::string in[], int size) [static]
Definition at line 963 of file Util.cpp.
std::vector< std::string > Util::listToVector (const char * in[], int size) [static]
Definition at line 900 of file Util.cpp.
std::vector< std::string > Util::listToVector (std::string in[]) [static]
Definition at line 951 of file Util.cpp.
std::vector< std::string > Util::listToVector (const char * in[]) [static]
Definition at line 888 of file Util.cpp.
int Util::matrixDifferences (const std::string & targetFile, const std::string & queryFile, int colSkip, int rowSkip, double epsilon, bool printMismatch, bool matchRows, double fraction = 0.0, int printMismatchMax = -1) [static]
Check each entry in two matrices to see if they are the same. If doing 'match-rows' we will attempt to find the matching row by the row name.
Parameters:
targetFile - File to read target matrix from.
queryFile - File to read the query matrix from.
colSkip - How many of initial columns to ignore (i.e. row names)
rowSkip - How many of initial rows to ignore (i.e. column header)
epsilon - What is the tolerance of difference. i.e. if q[i][j] - t[i][j] >= epsilon then there is a difference.
printMismatch - Should we print out the cases where difference is >= epsilon
matchRows - Should we try to match the rows based on the row identifiers.
fraction - Maximum fractional difference considered equivalent (default: not used).
printMismatchMax - Maximum number of mismatches to print (default: no limit).
Returns:
- Number of differences >= epsilon found.
Check each entry in two matrices to see if they are the same. If doing 'match-rows' we will attempt to find the matching row by the row name.
Parameters:
targetFile - File to read target matrix from.
queryFile - File to read the query matrix from.
colSkip - How many of initial columns to ignore (i.e. row names)
rowSkip - How many of initial rows to ignore (i.e. column header)
epsilon - What is the tolerance of difference. i.e. if q[i][j] - t[i][j] >= epsilon then there is a difference.
printMismatch - Should we print out the cases where difference is >= epsilon
matchRows - Should we try to match the rows based on the row identifiers.
fraction - What fractional difference is tolerated, test for value equivalence (not used by default). i.e. if q[i][j] - t[i][j] < fraction*max(|q[i][j]|, |t[i][j]|)
Returns:
- Number of differences >= epsilon found.
Definition at line 315 of file Util.cpp.
References TableFile::columnFromFile(), Fs::convertToUncPath(), Err::errAbort(), failed, RowFile::matrixFromFile(), Max, Verbose::out(), and ToStr().
Referenced by MatrixCheck::check().
bool Util::memInfo (uint64_t & free, uint64_t & total, uint64_t & swapAvail, uint64_t & memAvail, bool cap32bit = true) [static]
Determine the free and total amount of memory in bytes on this machine.
Parameters:
free - Bytes available currently.
total - Total bytes installed on machine.
swapAvail - Amount of swap available on machine. OSX can use all disk space so reports 0 on OSX
memAvail - Amount of space we should consider available.
cap32bit - Cap the memory at 4GB.
Returns:
true if successful, false otherwise.
Todo:
is there a more robust way to determine 32 vs 64 bitness?
Definition at line 695 of file Util.cpp.
References MEMINFO_2GB_MAX.
Referenced by BaseEngine::BaseEngine(), main(), LogStream::profileString(), pushMemFreeAtStart(), and Util::StaticMem::StaticMem().
const char * Util::nextWhiteSpace (const char * s) [static]
Return a pointer to the next character that is white space or NULL if none found.
Parameters:
s - cstring to find white space in.
Returns:
- Pointer to next whitespace character or NULL if none found.
Definition at line 750 of file Util.cpp.
void Util::popMemFreeAtStart () [static]
Definition at line 1017 of file Util.cpp.
References Util::StaticMem::popMemFreeAtStart().
Referenced by BaseEngine::run().
void Util::printStringWidth (std::ostream & out, const std::string & str, int prefix, int currentPos, int maxWidth = 70) [static]
Print a string wrapping at max width from the current position.
Parameters:
out - stream to output string to.
str - The cstring to be printed.
prefix - How many spaces to put on begining of newline.
maxWidth - Where to wrap text at.
currentPos - What position in the line is cursor currently at.
Definition at line 767 of file Util.cpp.
Referenced by PgOptions::printStringWidth().
static void Util::PrintTextClassTitle (const std::string & className) [inline, static]
Definition at line 408 of file Util.h.
static void Util::PrintTextFunctionTitle (const std::string & className, const std::string & functionName) [inline, static]
Definition at line 412 of file Util.h.
void Util::pushMemFreeAtStart () [static]
Definition at line 1022 of file Util.cpp.
References memInfo(), and Util::StaticMem::pushMemFreeAtStart().
Referenced by BaseEngine::run().
static void Util::removeChar (std::string & s, char character) [inline, static]
Definition at line 325 of file Util.h.
void Util::replaceString (std::string & s, const std::string & from, const std::string & to) [static]
Replace the from string with the to string for all instances in string supplied.
Parameters:
s - string to do the replacement in.
from - original string to be replaced.
to - string to do the replacing with.
Definition at line 420 of file Util.cpp.
static int Util::round (double x) [inline, static]
Some older compilers (solaris) don't have a round function.
Definition at line 164 of file Util.h.
static bool Util::sameString (const std::string & s1, const std::string & s2) [inline, static]
Check to see if two strings are the same.
Parameters:
s1 - string 1.
s2 - string 2.
Returns:
true if compare() considers them the same.
Definition at line 264 of file Util.h.
int32_t Util::schrageRandom (int32_t * ix) [static]
Schrage's algorithm for generating random numbers in 32 bits.
Parameters:
ix - pointer to integer seed, cannot be zero.
Definition at line 438 of file Util.cpp.
References Err::check().
bool Util::stringEndsWith (const std::string & str, const std::string & end) [static]
Does the string end with the other string?
Parameters:
str string to check
endstr ending string.
Returns:
true if str ends with endstr.
Definition at line 151 of file Util.cpp.
static void Util::subChar (std::string & s, char from, char to) [inline, static]
Replace the from character with the to character for all instances in string supplied.
Parameters:
s - string to do the replacement in.
from - original character to be replaced.
to - character to do the replacing with.
Definition at line 303 of file Util.h.
std::string Util::toString (const std::wstring & src) [static]
Definition at line 1029 of file Util.cpp.
Referenced by Fs::convertToUncPathInPlace(), Fs::listDir(), and affymetrix_calvin_io::GenericData::MapFile().
static std::wstring Util::toWString (const std::string & src) [inline, static]
Definition at line 461 of file Util.h.
Referenced by Fs::convertToUncPathInPlace(), and Fs::convertToUncPathW().
static void Util::trimString (std::string & s, const char * whitespace = " \r\n\t") [inline, static]
Cut off any preceding and trailing white space.
Parameters:
s - String to be trimmed.
whitespace - String with characters to be trimmed.
Definition at line 239 of file Util.h.
Referenced by LineFile::getline(), and RowFile::nextLine().
static std::string Util::upcaseString (const std::string & str_orig) [inline, static]
Copy and upcase a 8bit string.
Parameters:
str_orig
Returns:
Definition at line 133 of file Util.h.
static void Util::upcaseString_inplace (std::string & str) [inline, static]
Make the string all uppercase.
Parameters:
s - string to be modified
Definition at line 125 of file Util.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/Util.h
C:/f112/affy/sdk/util/Util.cpp