Affymetrix Fusion SDK: affymetrix_calvin_io::CHPMultiDataFileWriter Class Reference
affymetrix_calvin_io::CHPMultiDataFileWriter Class Reference
#include <CalvinCHPMultiDataFileWriter.h>
Public Member Functions
CHPMultiDataFileWriter (CHPMultiDataData &p)
~CHPMultiDataFileWriter ()
void WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &p)
void WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData &p)
void WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData &p)
void WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataExpressionData &p)
void WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData &p)
void WriteEntry (const affymetrix_calvin_data::DmetBiAllelicData &p)
void WriteEntry (const affymetrix_calvin_data::DmetMultiAllelicData &p)
void WriteEntry (const affymetrix_calvin_data::DmetCopyNumberData &p)
void WriteEntry (const affymetrix_calvin_data::ChromosomeMultiDataSummaryData &p)
void WriteEntry (const affymetrix_calvin_data::ChromosomeSegmentData &p)
void WriteEntry (const affymetrix_calvin_data::ChromosomeSegmentDataEx &p)
void WriteEntry (const affymetrix_calvin_data::FamilialSample &p)
void WriteEntry (const affymetrix_calvin_data::FamilialSegmentOverlap &p)
void WriteEntry (const affymetrix_calvin_data::AllelePeaks &p)
void WriteEntry (const affymetrix_calvin_data::MarkerABSignals &p)
void WriteEntry (const affymetrix_calvin_data::CytoGenotypeCallData &p)
void SeekToDataSet (MultiDataType dataType)
Private Member Functions
void WriteMetrics (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > &metrics)
void WriteHeaders ()
int32_t SetFilePositions ()
Private Attributes
GenericFileWriter * writer
DataSetWriter * dataSetWriter
std::map< MultiDataType, int32_t > entryPos
std::map< MultiDataType, int > dataTypeToIndex
std::map< int, MultiDataType > indexToDataType
int maxName
int maxSegmentType
int maxReferenceSegmentID
int maxFamilialSegmentID
int maxFamilialARRID
int maxFamilialCHPID
int maxFamilialCHPFile
int maxFamilialRole
MultiDataType currentDataType
CHPMultiDataData * data
Detailed Description
A class to write a multi data CHP file.
Definition at line 37 of file CalvinCHPMultiDataFileWriter.h.
Constructor & Destructor Documentation
CHPMultiDataFileWriter::CHPMultiDataFileWriter (CHPMultiDataData & p)
Constructor
Parameters:
p Pointer to the multi data CHP data object.
Definition at line 29 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_io::CHPMultiDataData::GetDataSetInfo(), and affymetrix_calvin_io::CHPMultiDataData::GetFileHeader().
CHPMultiDataFileWriter::~CHPMultiDataFileWriter ()
Destructor
Definition at line 43 of file CalvinCHPMultiDataFileWriter.cpp.
Member Function Documentation
void CHPMultiDataFileWriter::SeekToDataSet (MultiDataType dataType)
Seeks to the data set.
Parameters:
dataType The data type
Definition at line 78 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_io::FamilialSamplesMultiDataType, affymetrix_calvin_io::FamilialSegmentOverlapsMultiDataType, and affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter().
int32_t CHPMultiDataFileWriter::SetFilePositions () [private]
Sets the file positions.
Returns:
The current file position.
Definition at line 69 of file CalvinCHPMultiDataFileWriter.cpp.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::ChromosomeMultiDataSummaryData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 242 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::chr, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::display, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::hetFrequency, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::homFrequency, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::markerCount, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::maxSignal, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::medianCnState, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::metrics, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::minSignal, and affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::startIndex.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::DmetCopyNumberData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 204 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_DmetCopyNumberData::call, affymetrix_calvin_data::_DmetCopyNumberData::confidence, affymetrix_calvin_data::_DmetCopyNumberData::estimate, affymetrix_calvin_data::_DmetCopyNumberData::force, affymetrix_calvin_data::_DmetCopyNumberData::lower, affymetrix_calvin_data::_DmetCopyNumberData::metrics, affymetrix_calvin_data::_DmetCopyNumberData::name, and affymetrix_calvin_data::_DmetCopyNumberData::upper.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 156 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::chr, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::confidenceScore, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::name, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::startPosition, and affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::stopPosition.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::MarkerABSignals & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 133 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_MarkerABSignals::index, and affymetrix_calvin_data::_MarkerABSignals::metrics.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::AllelePeaks & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 123 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_AllelePeaks::chr, affymetrix_calvin_data::_AllelePeaks::name, affymetrix_calvin_data::_AllelePeaks::peaks, and affymetrix_calvin_data::_AllelePeaks::position.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::FamilialSegmentOverlap & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 302 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_FamilialSegmentOverlap::familialSampleKey, affymetrix_calvin_data::_FamilialSegmentOverlap::familialSegmentID, affymetrix_calvin_data::_FamilialSegmentOverlap::referenceSampleKey, affymetrix_calvin_data::_FamilialSegmentOverlap::referenceSegmentID, and affymetrix_calvin_data::_FamilialSegmentOverlap::segmentType.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::FamilialSample & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 289 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_FamilialSample::arrID, affymetrix_calvin_data::_FamilialSample::chpFilename, affymetrix_calvin_data::_FamilialSample::chpID, affymetrix_calvin_data::_FamilialSample::role, affymetrix_calvin_data::_FamilialSample::roleConfidence, affymetrix_calvin_data::_FamilialSample::roleValidity, and affymetrix_calvin_data::_FamilialSample::sampleKey.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::ChromosomeSegmentDataEx & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 271 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_ChromosomeSegmentDataEx::call, affymetrix_calvin_data::_ChromosomeSegmentDataEx::chr, affymetrix_calvin_data::_ChromosomeSegmentDataEx::confidence, affymetrix_calvin_data::_ChromosomeSegmentDataEx::familialSampleKey, affymetrix_calvin_data::_ChromosomeSegmentDataEx::heterozygosity, affymetrix_calvin_data::_ChromosomeSegmentDataEx::homozygosity, affymetrix_calvin_data::_ChromosomeSegmentDataEx::markerCount, affymetrix_calvin_data::_ChromosomeSegmentDataEx::metrics, affymetrix_calvin_data::_ChromosomeSegmentDataEx::referenceSampleKey, affymetrix_calvin_data::_ChromosomeSegmentDataEx::segmentId, affymetrix_calvin_data::_ChromosomeSegmentDataEx::startPosition, and affymetrix_calvin_data::_ChromosomeSegmentDataEx::stopPosition.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::ChromosomeSegmentData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 258 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_ChromosomeSegmentData::chr, affymetrix_calvin_data::_ChromosomeSegmentData::markerCount, affymetrix_calvin_data::_ChromosomeSegmentData::meanMarkerDistance, affymetrix_calvin_data::_ChromosomeSegmentData::metrics, affymetrix_calvin_data::_ChromosomeSegmentData::segmentId, affymetrix_calvin_data::_ChromosomeSegmentData::startPosition, and affymetrix_calvin_data::_ChromosomeSegmentData::stopPosition.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataExpressionData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 169 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::name, and affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::quantification.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::CytoGenotypeCallData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 141 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_CytoGenotypeCallData::aSignal, affymetrix_calvin_data::_CytoGenotypeCallData::bSignal, affymetrix_calvin_data::_CytoGenotypeCallData::call, affymetrix_calvin_data::_CytoGenotypeCallData::confidence, affymetrix_calvin_data::_CytoGenotypeCallData::contrast, affymetrix_calvin_data::_CytoGenotypeCallData::forcedCall, affymetrix_calvin_data::_CytoGenotypeCallData::index, affymetrix_calvin_data::_CytoGenotypeCallData::metrics, and affymetrix_calvin_data::_CytoGenotypeCallData::signalStrength.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::DmetMultiAllelicData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 218 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_DmetMultiAllelicData::alleleCount, affymetrix_calvin_data::_DmetMultiAllelicData::call, affymetrix_calvin_data::_DmetMultiAllelicData::confidence, affymetrix_calvin_data::_DmetMultiAllelicData::contextA, affymetrix_calvin_data::_DmetMultiAllelicData::contextB, affymetrix_calvin_data::_DmetMultiAllelicData::contextC, affymetrix_calvin_data::_DmetMultiAllelicData::contextD, affymetrix_calvin_data::_DmetMultiAllelicData::contextE, affymetrix_calvin_data::_DmetMultiAllelicData::contextF, affymetrix_calvin_data::_DmetMultiAllelicData::force, affymetrix_calvin_data::_DmetMultiAllelicData::metrics, affymetrix_calvin_data::_DmetMultiAllelicData::name, affymetrix_calvin_data::_DmetMultiAllelicData::signalA, affymetrix_calvin_data::_DmetMultiAllelicData::signalB, affymetrix_calvin_data::_DmetMultiAllelicData::signalC, affymetrix_calvin_data::_DmetMultiAllelicData::signalD, affymetrix_calvin_data::_DmetMultiAllelicData::signalE, and affymetrix_calvin_data::_DmetMultiAllelicData::signalF.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::DmetBiAllelicData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 189 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_DmetBiAllelicData::call, affymetrix_calvin_data::_DmetBiAllelicData::confidence, affymetrix_calvin_data::_DmetBiAllelicData::contextA, affymetrix_calvin_data::_DmetBiAllelicData::contextB, affymetrix_calvin_data::_DmetBiAllelicData::force, affymetrix_calvin_data::_DmetBiAllelicData::metrics, affymetrix_calvin_data::_DmetBiAllelicData::name, affymetrix_calvin_data::_DmetBiAllelicData::signalA, and affymetrix_calvin_data::_DmetBiAllelicData::signalB.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 178 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::confidenceScore, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::signal.
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 103 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::name, and affymetrix_calvin_io::DataSetWriter::Write().
void CHPMultiDataFileWriter::WriteEntry (const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & p)
Write an entry.
Parameters:
p A pointer to a multi data entry.
Definition at line 113 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::chr, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::position.
void CHPMultiDataFileWriter::WriteHeaders () [private]
Writes the headers to the file.
Definition at line 49 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriterCnt(), affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), and affymetrix_calvin_io::DataGroupWriter::WriteHeader().
void CHPMultiDataFileWriter::WriteMetrics (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > & metrics) [private]
Write the metrics to the file.
Parameters:
metrics Other metrics associated with the probe set
Definition at line 313 of file CalvinCHPMultiDataFileWriter.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8().
Member Data Documentation
MultiDataType affymetrix_calvin_io::CHPMultiDataFileWriter::currentDataType [private]
The data type being written.
Definition at line 80 of file CalvinCHPMultiDataFileWriter.h.
CHPMultiDataData* affymetrix_calvin_io::CHPMultiDataFileWriter::data [private]
The data.
Definition at line 83 of file CalvinCHPMultiDataFileWriter.h.
DataSetWriter* affymetrix_calvin_io::CHPMultiDataFileWriter::dataSetWriter [private]
The data set writer.
Definition at line 44 of file CalvinCHPMultiDataFileWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileWriter::dataTypeToIndex [private]
A map of data type to data set index.
Definition at line 50 of file CalvinCHPMultiDataFileWriter.h.
std::map<MultiDataType, int32_t> affymetrix_calvin_io::CHPMultiDataFileWriter::entryPos [private]
The file position of the entry for each data set.
Definition at line 47 of file CalvinCHPMultiDataFileWriter.h.
std::map<int, MultiDataType> affymetrix_calvin_io::CHPMultiDataFileWriter::indexToDataType [private]
A map of data set index to data type
Definition at line 53 of file CalvinCHPMultiDataFileWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileWriter::maxFamilialARRID [private]
The maximum length of the familial sample ARR id
Definition at line 68 of file CalvinCHPMultiDataFileWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileWriter::maxFamilialCHPFile [private]
The maximum length of the familial sample CHP file name
Definition at line 74 of file CalvinCHPMultiDataFileWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileWriter::maxFamilialCHPID [private]
The maximum length of the familial sample CHP id
Definition at line 71 of file CalvinCHPMultiDataFileWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileWriter::maxFamilialRole [private]
The maximum length of the familial sample role
Definition at line 77 of file CalvinCHPMultiDataFileWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileWriter::maxFamilialSegmentID [private]
The maximum length of the familial seg id column.
Definition at line 65 of file CalvinCHPMultiDataFileWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileWriter::maxName [private]
The maximum length of the name column.
Definition at line 56 of file CalvinCHPMultiDataFileWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileWriter::maxReferenceSegmentID [private]
The maximum length of the familial ref seg id column.
Definition at line 62 of file CalvinCHPMultiDataFileWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileWriter::maxSegmentType [private]
The maximum length of the familial seg type column.
Definition at line 59 of file CalvinCHPMultiDataFileWriter.h.
GenericFileWriter* affymetrix_calvin_io::CHPMultiDataFileWriter::writer [private]
The file writer.
Definition at line 41 of file CalvinCHPMultiDataFileWriter.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPMultiDataFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPMultiDataFileWriter.cpp