Affymetrix Fusion SDK: RowFile Class Reference
RowFile Class Reference
Class for reading line oriented files and parsing them out into vectors of strings easily.
#include <RowFile.h>
Public Types
enum FileLineEnding { UNIX = 0, DOS = 1, MAC = 2, UNKNOWN = 3 }
Public Member Functions
RowFile (char delimChar= '\t', char commentChar= '#', char commentChar2= '%')
~RowFile ()
Destructor.
void open (const std::string &fileName)
void close ()
bool nextRowExpect (std::vector< std::string > &words, unsigned int expect)
bool nextCStringRowExpect (std::vector< const char * > &words, unsigned int expect)
bool nextCStringRow (std::vector< const char * > &words)
bool nextRow (std::vector< std::string > &words)
void setDelim (char nDelim)
char getDelim ()
void setComment (char nComment)
char getComment ()
const std::string * nextLine ()
const std::string * nextRealLine ()
void reuseLine ()
int getCurrentLineNumber ()
What line number are we reading?
enum FileLineEnding getFileType ()
What type of file is this one?
std::string getFileName ()
Static Public Member Functions
static void readHeader (RowFile &rf, std::map< std::string, std::vector< std::string > > &header, std::vector< std::string > &lines)
static void writeHeader (std::ostream &out, const std::vector< std::string > &lines)
static void matrixFromFile (const std::string &fileName, std::vector< std::vector< double > > &matrix, unsigned int skipLines=0, unsigned int skipCols=0)
static void matrixFromFile (const std::string &fileName, std::vector< std::vector< float > > &matrix, unsigned int skipLines=0, unsigned int skipCols=0)
Private Member Functions
enum RowFile::FileLineEnding determineLineEndingType (std::ifstream &input)
Private Attributes
std::string m_FileName
Name of file we are reading from.
std::ifstream m_In
Stream that we are reading from.
std::string m_CurrentLine
Current line read from the file.
char * m_Buffer
Utility buffer for chopping into char *s, faster than strings.
int m_BufferSize
Current size of the buffer.
int m_LineIx
Line number in file that is currently read.
char m_Delim
Separating delimiter, usually tab ('') or comma (',')
char m_Comment
Comment character usually '#'.
char m_Comment2
Secondary comment character, usually ''.
bool m_Reuse
Should we reuse the last line again?
FileLineEnding m_EndType
What type of line endings does this stream use?
Detailed Description
Class for reading line oriented files and parsing them out into vectors of strings easily.
RowFile
Definition at line 43 of file RowFile.h.
Member Enumeration Documentation
enum RowFile::FileLineEnding
Line endings are platform specific, this encodes different types we know of.
Enumerator:
UNIX
DOS
MAC
UNKNOWN
Definition at line 49 of file RowFile.h.
Constructor & Destructor Documentation
RowFile::RowFile (char delimChar = '\t', char commentChar = '#', char commentChar2 = '%')
Constructor. Open an object with delimiter and comment characters.
Parameters:
delimChar - word delimiter character.
commentChar - line comment character.
commentChar2 - second line comment character.
Constructor. Open an object with delimiter and comment characters.
Parameters:
delim - word delimiter character.
comment - line comment character.
Definition at line 49 of file RowFile.cpp.
RowFile::~RowFile ()
Destructor.
Definition at line 72 of file RowFile.cpp.
References m_Buffer, and m_In.
Member Function Documentation
void RowFile::close (void)
Close file streams.
Definition at line 84 of file RowFile.cpp.
References m_In.
Referenced by TableFile::open().
enum RowFile::FileLineEnding RowFile::determineLineEndingType (std::ifstream & input) [private]
What type of line endings do we see in this input stream?
Parameters:
input - stream to look for '','
', or '
' in.
Returns:
type of line endings we expect in the future.
Definition at line 372 of file RowFile.cpp.
References DOS, MAC, UNIX, and UNKNOWN.
Referenced by open().
char RowFile::getComment () [inline]
Get the comment.
Returns:
current comment character.
Definition at line 139 of file RowFile.h.
References m_Comment.
int RowFile::getCurrentLineNumber () [inline]
What line number are we reading?
Returns:
Line number.
Definition at line 161 of file RowFile.h.
References m_LineIx.
Referenced by TableFile::columnFromRowFile(), and TableFile::open().
char RowFile::getDelim () [inline]
Get the delimiter.
Returns:
current word delimiter.
Definition at line 127 of file RowFile.h.
References m_Delim.
std::string RowFile::getFileName () [inline]
What is the name of the rowfile we're reading from?
Returns:
name of file being read.
Definition at line 206 of file RowFile.h.
References m_FileName.
Referenced by TableFile::columnFromRowFile().
enum FileLineEnding RowFile::getFileType () [inline]
What type of file is this one?
Returns:
Type of file that has been determined.
Definition at line 200 of file RowFile.h.
References m_EndType.
void RowFile::matrixFromFile (const std::string & fileName, std::vector< std::vector< double > > & matrix, unsigned int skipLines = 0, unsigned int skipCols = 0) [static]
Read in a matrix from a file.
Parameters:
fileName - Name of file to read from.
matrix - where to read data into.
skipLines - lines (possibly header?) to skip.
skipCols - number of columns (row names?) to skip.
Definition at line 321 of file RowFile.cpp.
References Err::errAbort(), nextRow(), open(), and Convert::toDouble().
Referenced by Util::matrixDifferences().
void RowFile::matrixFromFile (const std::string & fileName, std::vector< std::vector< float > > & matrix, unsigned int skipLines = 0, unsigned int skipCols = 0) [static]
Read in a matrix from a file.
Parameters:
fileName - Name of file to read from.
matrix - where to read data into.
skipLines - lines (possibly header?) to skip.
skipCols - number of columns (row names?) to skip.
Definition at line 347 of file RowFile.cpp.
References Err::errAbort(), nextRow(), open(), and Convert::toFloat().
bool RowFile::nextCStringRow (std::vector< const char * > & words)
Chop the next row into words and return them in the vector. char* memory in vector is owned elsewhere and will change after an calls to nextRow or nextLine.
Parameters:
words - vector to fill in with words.
Returns:
bool - false at EOF true otherwise.
Definition at line 198 of file RowFile.cpp.
References FreezArray(), m_Buffer, m_BufferSize, m_CurrentLine, m_Delim, and nextRealLine().
Referenced by nextCStringRowExpect().
bool RowFile::nextCStringRowExpect (std::vector< const char * > & words, unsigned int expect)
Chop the next row into words and return them in the vector squawk and die if expected number was different from number found. char * memory in vector is owned elsewhere and will change after an calls to nextRow or nextLine.
Parameters:
words - vector to fill in with words.
expect - number of words that should be in next row.
Returns:
bool - false at EOF true otherwise.
Chop the next row into words and return them in the vector. char* memory in vector is owned elsewhere and will change after an calls to nextRow or nextLine.
Parameters:
words - vector to fill in with words.
Returns:
bool - false at EOF true otherwise.
Definition at line 180 of file RowFile.cpp.
References Err::errAbort(), m_LineIx, nextCStringRow(), and ToStr().
const string * RowFile::nextLine ()
Pull the next line from the input buffer or die trying.
Pull the next line from the input m_Buffer or die trying.
Returns:
- Pointer to string representation of current line or NULL at EOF.
Definition at line 94 of file RowFile.cpp.
References DOS, Err::errAbort(), m_CurrentLine, m_EndType, m_In, m_LineIx, m_Reuse, MAC, ToStr(), and Util::trimString().
Referenced by nextRealLine(), and readHeader().
const string * RowFile::nextRealLine ()
Return the next line that is non-blank and doesn't start with a comment character.
Return the next line that is non-blank and doesn't start with a comment character.
Returns:
- Pointer to string repesentation of current line or NULL at EOF.
Definition at line 130 of file RowFile.cpp.
References m_Comment, m_Comment2, m_CurrentLine, and nextLine().
Referenced by nextCStringRow(), and nextRow().
bool RowFile::nextRow (std::vector< std::string > & words)
Chop the next row into words and return them in the vector.
Parameters:
words - vector to fill in with words.
Returns:
bool - false at EOF true otherwise.
Definition at line 154 of file RowFile.cpp.
References m_CurrentLine, m_Delim, and nextRealLine().
Referenced by TableFile::columnFromFile(), TableFile::columnFromRowFile(), matrixFromFile(), nextRowExpect(), and TableFile::open().
bool RowFile::nextRowExpect (std::vector< std::string > & words, unsigned int expect)
Chop the next row into words and return them in the vector squawk and die if expected number was different from number found.
Parameters:
words - vector to fill in with words.
expect - number of words that should be in next row.
Returns:
bool - false at EOF true otherwise.
Definition at line 254 of file RowFile.cpp.
References Err::errAbort(), m_LineIx, nextRow(), and ToStr().
void RowFile::open (const std::string & fileName)
Open file fileName or die trying.
Parameters:
fileName - full path of fileName to be opened.
Open file fileName or die trying.
Parameters:
char * fileName - full path of fileName to be opened.
Definition at line 59 of file RowFile.cpp.
References Fs::aptOpen(), determineLineEndingType(), Err::errAbort(), FS_QUOTE_PATH, m_EndType, m_FileName, and m_In.
Referenced by TableFile::columnFromFile(), matrixFromFile(), and TableFile::open().
void RowFile::readHeader (RowFile & rf, std::map< std::string, std::vector< std::string > > & header, std::vector< std::string > & lines) [static]
Fill in a header map with data from the top of the file.
Definition at line 265 of file RowFile.cpp.
References Err::errAbort(), m_Comment, m_Comment2, nextLine(), reuseLine(), and ToStr().
Referenced by TableFile::open().
void RowFile::reuseLine () [inline]
Reuse the same line again.
Definition at line 155 of file RowFile.h.
References m_Reuse.
Referenced by TableFile::columnFromFile(), TableFile::open(), and readHeader().
void RowFile::setComment (char nComment) [inline]
Set the comment.
Parameters:
nComment - new comment character.
Definition at line 133 of file RowFile.h.
References m_Comment.
void RowFile::setDelim (char nDelim) [inline]
Set the delimiter.
Parameters:
nDelim - new word delimiter.
Definition at line 121 of file RowFile.h.
References m_Delim.
void RowFile::writeHeader (std::ostream & out, const std::vector< std::string > & lines) [static]
Write out a header in #key=value form.
Definition at line 307 of file RowFile.cpp.
Referenced by TableFile::write().
Member Data Documentation
char* RowFile::m_Buffer [private]
Utility buffer for chopping into char *s, faster than strings.
Definition at line 224 of file RowFile.h.
Referenced by nextCStringRow(), and ~RowFile().
int RowFile::m_BufferSize [private]
Current size of the buffer.
Definition at line 226 of file RowFile.h.
Referenced by nextCStringRow().
char RowFile::m_Comment [private]
Comment character usually '#'.
Definition at line 232 of file RowFile.h.
Referenced by getComment(), nextRealLine(), readHeader(), and setComment().
char RowFile::m_Comment2 [private]
Secondary comment character, usually ''.
Definition at line 234 of file RowFile.h.
Referenced by nextRealLine(), and readHeader().
std::string RowFile::m_CurrentLine [private]
Current line read from the file.
Definition at line 222 of file RowFile.h.
Referenced by nextCStringRow(), nextLine(), nextRealLine(), and nextRow().
char RowFile::m_Delim [private]
Separating delimiter, usually tab ('') or comma (',')
Definition at line 230 of file RowFile.h.
Referenced by getDelim(), nextCStringRow(), nextRow(), and setDelim().
FileLineEnding RowFile::m_EndType [private]
What type of line endings does this stream use?
Definition at line 238 of file RowFile.h.
Referenced by getFileType(), nextLine(), and open().
std::string RowFile::m_FileName [private]
Name of file we are reading from.
Definition at line 218 of file RowFile.h.
Referenced by getFileName(), and open().
std::ifstream RowFile::m_In [private]
Stream that we are reading from.
Definition at line 220 of file RowFile.h.
Referenced by close(), nextLine(), open(), and ~RowFile().
int RowFile::m_LineIx [private]
Line number in file that is currently read.
Definition at line 228 of file RowFile.h.
Referenced by getCurrentLineNumber(), nextCStringRowExpect(), nextLine(), and nextRowExpect().
bool RowFile::m_Reuse [private]
Should we reuse the last line again?
Definition at line 236 of file RowFile.h.
Referenced by nextLine(), and reuseLine().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/RowFile.h
C:/f112/affy/sdk/util/RowFile.cpp