Affymetrix Fusion SDK: CCmdLine Class Reference
CCmdLine Class Reference
#include <CmdLine.h>
Public Member Functions
int SplitLine (int argc, char **argv)
bool HasSwitch (const char *pSwitch)
StringType GetSafeArgument (const char *pSwitch, int iIdx, const char *pDefault)
StringType GetArgument (const char *pSwitch, int iIdx)
int GetArgumentCount (const char *pSwitch)
Protected Member Functions
bool IsSwitch (const char *pParam)
Detailed Description
Definition at line 157 of file CmdLine.h.
Member Function Documentation
StringType CCmdLine::GetArgument (const char * pSwitch, int iIdx)
Definition at line 255 of file CmdLine.cpp.
Referenced by main().
int CCmdLine::GetArgumentCount (const char * pSwitch)
Definition at line 285 of file CmdLine.cpp.
Referenced by main().
StringType CCmdLine::GetSafeArgument (const char * pSwitch, int iIdx, const char * pDefault)
Definition at line 219 of file CmdLine.cpp.
References StringType.
Referenced by main().
bool CCmdLine::HasSwitch (const char * pSwitch)
Definition at line 191 of file CmdLine.cpp.
bool CCmdLine::IsSwitch (const char * pParam) [protected]
Definition at line 152 of file CmdLine.cpp.
int CCmdLine::SplitLine (int argc, char ** argv)
Definition at line 72 of file CmdLine.cpp.
References CCmdParam::m_strings, and StringType.
Referenced by main().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/converters/utils/src/CmdLine.h
C:/f112/affy/sdk/calvin_files/converters/utils/src/CmdLine.cpp