Affymetrix Fusion SDK: SocketEngine Class Reference
SocketEngine Class Reference
SocketEngine design notes:
#include <SocketEngine.h>
Public Member Functions
SocketEngine (const std::string &program, const std::string &jobFile, const std::string &host="127.0.0.1", unsigned int port=7889)
SocketEngine (const std::string &program, const std::vector< std::string > &args, const std::string &host="127.0.0.1", unsigned int port=7889)
~SocketEngine ()
bool run ()
void TerminateLaunchedApp ()
Public Attributes
SocketServer server
Private Member Functions
int doWindows (SocketServer &server, SocketTextHandler &handler, std::string &host, std::string &port, std::vector< std::string > commandArgs)
int doUnix (SocketServer &server, SocketTextHandler &handler, std::string &host, std::string &port, std::vector< std::string > commandArgs)
void initVars ()
Private Attributes
std::string m_Program
std::vector< std::string > m_PgOpts
std::string m_Host
unsigned int m_Port
Detailed Description
SocketEngine design notes:
The SocketEngine utilizes a simple message passing protocol over a socket to run an APT engine cleass in a separate process. The idea being that it is cleaner and easier to have GUI programs like GTC run APT programs in a separate engine rather than try to run them via COM objects or managed from C# code.
The GUI programs traditionally tie into the global Verbose object's reporting system. For time reasons we didn't want to rewrite all of that code so the SocketEngine will handle running the other process remotely and translate the messages that come over the socket to the local Verbose object. This way all of the existing code that ties into the local Verbose object will work unchanged.
There are two phases to the socket engine. The first is the connection of the foriegn process to the local SocketServer ojbect.
Phase 1: Delegate process connects to the SocketServer in supervisor process.
The second phase is when the delegate process passes messages back from the delegate process Verbose calls to the supervising process and they are translated to calls in the local Verbose object.
Phase 2: Delegate process passes messages to the supervisor process which fires the usual calls in Verbose.
Definition at line 56 of file SocketEngine.h.
Constructor & Destructor Documentation
SocketEngine::SocketEngine (const std::string & program, const std::string & jobFile, const std::string & host = "127.0.0.1", unsigned int port = 7889)
Definition at line 55 of file SocketEngine.cpp.
References initVars(), m_PgOpts, and m_Program.
SocketEngine::SocketEngine (const std::string & program, const std::vector< std::string > & args, const std::string & host = "127.0.0.1", unsigned int port = 7889)
Definition at line 64 of file SocketEngine.cpp.
References initVars(), m_PgOpts, and m_Program.
SocketEngine::~SocketEngine ()
Definition at line 73 of file SocketEngine.cpp.
Member Function Documentation
int SocketEngine::doUnix (SocketServer & server, SocketTextHandler & handler, std::string & host, std::string & port, std::vector< std::string > commandArgs) [private]
Definition at line 203 of file SocketEngine.cpp.
References SocketServer::acceptNewConnection(), SocketServer::isConnected(), and SocketServer::processNewMessages().
Referenced by run().
int SocketEngine::doWindows (SocketServer & server, SocketTextHandler & handler, std::string & host, std::string & port, std::vector< std::string > commandArgs) [private]
Definition at line 104 of file SocketEngine.cpp.
References SocketServer::acceptNewConnection(), SocketServer::cleanUp(), Err::errAbort(), SocketServer::isConnected(), Verbose::out(), SocketServer::processNewMessages(), and ToStr().
Referenced by run().
void SocketEngine::initVars () [inline, private]
Definition at line 128 of file SocketEngine.h.
Referenced by SocketEngine().
bool SocketEngine::run (void)
Definition at line 76 of file SocketEngine.cpp.
References SocketBase::addHandler(), doUnix(), doWindows(), m_Host, m_PgOpts, m_Port, Verbose::out(), server, SocketServer::socketOpen(), SocketTextHandler::successfulRun(), and ToStr().
void SocketEngine::TerminateLaunchedApp ()
Definition at line 184 of file SocketEngine.cpp.
References SocketServer::cleanUp(), and server.
Member Data Documentation
std::string SocketEngine::m_Host [private]
Definition at line 110 of file SocketEngine.h.
Referenced by run().
std::vector<std::string> SocketEngine::m_PgOpts [private]
Definition at line 109 of file SocketEngine.h.
Referenced by run(), and SocketEngine().
unsigned int SocketEngine::m_Port [private]
Definition at line 111 of file SocketEngine.h.
Referenced by run().
std::string SocketEngine::m_Program [private]
Definition at line 108 of file SocketEngine.h.
Referenced by SocketEngine().
SocketServer SocketEngine::server
Definition at line 68 of file SocketEngine.h.
Referenced by run(), and TerminateLaunchedApp().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/SocketEngine.h
C:/f112/affy/sdk/util/SocketEngine.cpp