Affymetrix Fusion SDK: Except Class Reference
Except Class Reference
General purpose exception error for error handling.
#include <Except.h>
Public Member Functions
Except (const std::string &msg)
Constructor.
virtual ~Except () throw ()
virtual destructor for a base class.
virtual const char * what () const throw ()
Standard what() call, just returns error message.
Private Attributes
std::string m_Msg
Our error message.
Detailed Description
General purpose exception error for error handling.
Definition at line 39 of file Except.h.
Constructor & Destructor Documentation
Except::Except (const std::string & msg) [inline]
Constructor.
Parameters:
msg Message for the user/programmer.
Definition at line 46 of file Except.h.
virtual Except::~Except () throw () [inline, virtual]
virtual destructor for a base class.
Returns:
Definition at line 52 of file Except.h.
Member Function Documentation
virtual const char* Except::what () const throw () [inline, virtual]
Standard what() call, just returns error message.
Returns:
error message.
Definition at line 58 of file Except.h.
References m_Msg.
Referenced by MatrixCheck::check(), CalvinChpCheck::check(), ChpCheck::checkFilePair(), CelCheck::checkFilePair(), Calvin::equivalent(), and CalvinToText::run().
Member Data Documentation
std::string Except::m_Msg [private]
Our error message.
Definition at line 64 of file Except.h.
Referenced by what().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/Except.h