Affymetrix Fusion SDK: affymetrix_calvin_io::AuditFileReader Class Reference
affymetrix_calvin_io::AuditFileReader Class Reference
#include <AuditFileReader.h>
Public Member Functions
AuditFileReader ()
~AuditFileReader ()
bool Read (const std::string &fileName, affymetrix_calvin_array::ArrayAuditEntryList &auditData)
Detailed Description
This class provides interfaces to read an audit file.
Definition at line 34 of file AuditFileReader.h.
Constructor & Destructor Documentation
AuditFileReader::AuditFileReader ()
Constructor
Definition at line 43 of file AuditFileReader.cpp.
AuditFileReader::~AuditFileReader ()
Destructor
Definition at line 50 of file AuditFileReader.cpp.
Member Function Documentation
bool AuditFileReader::Read (const std::string & fileName, affymetrix_calvin_array::ArrayAuditEntryList & auditData)
Reads the entire contents of the file.
Parameters:
fileName The name of the audit file to read.
auditData The audit data to read from the file.
Definition at line 57 of file AuditFileReader.cpp.
References affymetrix_calvin_array::ArrayAuditEntry::ActionParameters(), affymetrix_calvin_array::ArrayAuditEntry::ActionType(), Fs::aptOpen(), affymetrix_calvin_array::ArrayAuditEntry::ArrayGuid(), AUDIT_ACTION_TAG, AUDIT_ARRAY_ID_TAG, AUDIT_DATE_TAG, AUDIT_END_TAG, AUDIT_INPUT_ID_TAG, AUDIT_OUTPUT_ID_TAG, AUDIT_START_TAG, AUDIT_TIME_TAG, AUDIT_USER_TAG, affymetrix_calvin_array::ArrayAuditEntry::Clear(), affymetrix_calvin_utilities::DateTime::Clear(), affymetrix_calvin_utilities::DateTime::Date(), affymetrix_calvin_array::ArrayAuditEntry::DateTime(), affymetrix_calvin_array::ArrayAuditEntry::InputFileGuids(), affymetrix_calvin_parameter::_tagParameterNameValuePair::Name, affymetrix_calvin_array::ArrayAuditEntry::OutputFileGuids(), affymetrix_calvin_utilities::DateTime::Time(), affymetrix_calvin_array::ArrayAuditEntry::UserName(), and affymetrix_calvin_parameter::_tagParameterNameValuePair::Value.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/AuditFileReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/AuditFileReader.cpp