Affymetrix Fusion SDK: SQLiteDatabase Class Reference
SQLiteDatabase Class Reference
#include <SQLite.h>
Public Member Functions
SQLiteDatabase ()
virtual ~SQLiteDatabase ()
sqlite3 & getConnection ()
void error (int iReturnCode, const std::string &strMessage)
void open (const std::string &strFileName, bool bReadOnly=false)
void close ()
void execute (const std::string &strSQL, bool bError=true, bool abortOnErr=true)
SQLiteRecordset * newRecordset ()
void deleteRecordset (SQLiteRecordset **pprset)
void beginTransaction ()
void commitTransaction ()
void rollbackTransaction ()
Static Public Member Functions
static void test ()
Protected Attributes
std::string m_dbName
sqlite3 * m_pdb
sqlite3_stmt * m_pstmt
bool m_bOpen
Detailed Description
SQLiteDatabase - Class for handling SQLite databases.
Definition at line 88 of file SQLite.h.
Constructor & Destructor Documentation
SQLiteDatabase::SQLiteDatabase ()
Constructs a SQLiteDatabase object.
Definition at line 99 of file SQLite.cpp.
References m_bOpen, m_pdb, and m_pstmt.
SQLiteDatabase::~SQLiteDatabase () [virtual]
Destroys a SQLiteDatabase object. Closes the database if it is left open.
Definition at line 110 of file SQLite.cpp.
References close().
Member Function Documentation
void SQLiteDatabase::beginTransaction () [inline]
Begin a transaction.
Definition at line 117 of file SQLite.h.
References execute().
Referenced by test().
void SQLiteDatabase::close (void)
Closes a SQLite database.
Definition at line 167 of file SQLite.cpp.
References error(), m_bOpen, m_dbName, and m_pdb.
Referenced by test(), and ~SQLiteDatabase().
void SQLiteDatabase::commitTransaction () [inline]
Commit a transaction.
Definition at line 122 of file SQLite.h.
References execute().
Referenced by test().
void SQLiteDatabase::deleteRecordset (SQLiteRecordset ** pprset) [inline]
Definition at line 112 of file SQLite.h.
void SQLiteDatabase::error (int iReturnCode, const std::string & strMessage)
Error handling function. Throws a SQLiteException pointer. The error code and Message will be combined into the SQLiteException message.
Parameters:
iReturnCode - The error code from SQLite.
strMessage - The error message.
Definition at line 121 of file SQLite.cpp.
References Fs::dirname(), Fs::isWriteableDir(), and m_dbName.
Referenced by close(), execute(), SQLiteRecordset::open(), and open().
void SQLiteDatabase::execute (const std::string & strSQL, bool bError = true, bool abortOnErr = true)
Executes a SQL statement. Does not return any data.
Parameters:
strSQL - The SQL statement to execute.
bError - Set to true to trap SQL statement errors, or false to ignore.
abortOnErr - true calls Err::abort on SQLite exception, else just throw the exception.
Definition at line 184 of file SQLite.cpp.
References Err::errAbort(), error(), SQLiteException::getMessage(), and m_pdb.
Referenced by beginTransaction(), commitTransaction(), rollbackTransaction(), and test().
sqlite3& SQLiteDatabase::getConnection () [inline]
Returns the sqlite3 reference.
Returns:
- The sqlite3 reference.
Definition at line 106 of file SQLite.h.
References m_pdb.
Referenced by SQLiteRecordset::open().
SQLiteRecordset* SQLiteDatabase::newRecordset () [inline]
Definition at line 111 of file SQLite.h.
void SQLiteDatabase::open (const std::string & strFileName, bool bReadOnly = false)
Opens a SQLite database.
Parameters:
strFileName - The name of the file to open.
bReadOnly - true if the file is to be opened read only, else false. (Defaults to false.)
Definition at line 148 of file SQLite.cpp.
References Fs::convertToUncPath(), error(), FS_QUOTE_PATH, m_bOpen, m_dbName, and m_pdb.
Referenced by test().
void SQLiteDatabase::rollbackTransaction () [inline]
Rollback a transaction.
Definition at line 127 of file SQLite.h.
References execute(), and m_bOpen.
Referenced by test().
void SQLiteDatabase::test () [static]
Definition at line 40 of file SQLite.cpp.
References beginTransaction(), close(), SQLiteRecordset::close(), commitTransaction(), execute(), SQLiteRecordset::fetch(), getInt(), SQLiteRecordset::getInteger(), SQLiteException::getMessage(), SQLiteRecordset::getString(), SQLiteRecordset::open(), open(), Verbose::out(), and rollbackTransaction().
Member Data Documentation
bool SQLiteDatabase::m_bOpen [protected]
Definition at line 98 of file SQLite.h.
Referenced by close(), open(), rollbackTransaction(), and SQLiteDatabase().
std::string SQLiteDatabase::m_dbName [protected]
Definition at line 95 of file SQLite.h.
Referenced by close(), error(), and open().
sqlite3* SQLiteDatabase::m_pdb [protected]
Definition at line 96 of file SQLite.h.
Referenced by close(), execute(), getConnection(), open(), and SQLiteDatabase().
sqlite3_stmt* SQLiteDatabase::m_pstmt [protected]
Definition at line 97 of file SQLite.h.
Referenced by SQLiteDatabase().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/SQLite.h
C:/f112/affy/sdk/util/SQLite.cpp