Affymetrix Fusion SDK: affymetrix_calvin_parameter::MIMEValue Class Reference
affymetrix_calvin_parameter::MIMEValue Class Reference
#include <ParameterNameValueType.h>
Public Member Functions
MIMEValue ()
MIMEValue (const void *value, u_int32_t size)
MIMEValue (const MIMEValue &source)
~MIMEValue ()
MIMEValue & operator= (const MIMEValue &source)
bool operator== (const MIMEValue &lhs)
bool operator!= (const MIMEValue &lhs)
void SetValue (const void *value, u_int32_t size)
const void * GetValue (u_int32_t &size) const
u_int32_t Size () const
Private Attributes
char * arr
u_int32_t arrSize
Detailed Description
A class to hold a MIME value Is responsible for managing the memory for the mime value
Definition at line 46 of file ParameterNameValueType.h.
Constructor & Destructor Documentation
MIMEValue::MIMEValue ()
Constructs a MIME value - default constructor
Definition at line 70 of file ParameterNameValueType.cpp.
MIMEValue::MIMEValue (const void * value, u_int32_t size)
Constructs a MIME value
Parameters:
value A pointer to array containing the MIME encoded value
size The size of the array
Definition at line 76 of file ParameterNameValueType.cpp.
MIMEValue::MIMEValue (const MIMEValue & source)
Copy constructor
Parameters:
source MIMEValue object to copy
Definition at line 83 of file ParameterNameValueType.cpp.
MIMEValue::~MIMEValue ()
Destructor
Definition at line 89 of file ParameterNameValueType.cpp.
Member Function Documentation
const void * MIMEValue::GetValue (u_int32_t & size) const
Get the controlled value
Parameters:
size Gets filled with the size of the constrolled array @ return Const pointer to the MIME value array. (for writing)
Definition at line 127 of file ParameterNameValueType.cpp.
Referenced by affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::DefaultValueToInt(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueAscii(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_io::DataSetHeaderUpdater::UpdateParameter(), and affymetrix_calvin_parameter::ParameterNameValueType::ValueToInt().
bool MIMEValue::operator!= (const MIMEValue & lhs)
Operator not equals.
Parameters:
lhs The let hand side to compare.
Returns:
True if not equal.
Definition at line 113 of file ParameterNameValueType.cpp.
MIMEValue & MIMEValue::operator= (const MIMEValue & source)
Assignment operator
Parameters:
source The source.
Returns:
The copied object.
Definition at line 94 of file ParameterNameValueType.cpp.
References arr, and arrSize.
bool MIMEValue::operator== (const MIMEValue & lhs)
Operator equals
Parameters:
lhs The left hand side to compare.
Returns:
True if the same.
Definition at line 106 of file ParameterNameValueType.cpp.
References arr, and arrSize.
void MIMEValue::SetValue (const void * value, u_int32_t size)
Set the controlled value
Parameters:
value A pointer to array containing the MIME encoded value
size The size of the array
Definition at line 118 of file ParameterNameValueType.cpp.
Referenced by affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::IntToDefaultValue(), affymetrix_calvin_parameter::ParameterNameValueType::IntToValue(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::SetDefaultValueAscii(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::SetDefaultValueText(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueAscii(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
u_int32_t affymetrix_calvin_parameter::MIMEValue::Size () const [inline]
Gets the size of the array
Definition at line 96 of file ParameterNameValueType.h.
References arrSize.
Referenced by affymetrix_calvin_io::DataSetHeaderUpdater::UpdateParameter().
Member Data Documentation
char* affymetrix_calvin_parameter::MIMEValue::arr [private]
The buffer to hold the data.
Definition at line 100 of file ParameterNameValueType.h.
Referenced by operator=(), and operator==().
u_int32_t affymetrix_calvin_parameter::MIMEValue::arrSize [private]
The size of the buffer.
Definition at line 103 of file ParameterNameValueType.h.
Referenced by operator=(), operator==(), and Size().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parameter/src/ParameterNameValueType.h
C:/f112/affy/sdk/calvin_files/parameter/src/ParameterNameValueType.cpp