Affymetrix Fusion SDK: AffxByteArray Class Reference
AffxByteArray Class Reference
A class for managing large byte arrays.
#include <AffxByteArray.h>
Public Member Functions
void lockBuffer (void)
void unlockBuffer (void)
bool isLocked (void)
void clear (void)
void empty (void)
bool isEmpty (void)
bool isClear (void)
const AffxByteArray & operator= (const AffxByteArray &ba)
int getInt (int &iIndex)
bool isAllWhitespace ()
void replace (const AffxString &str1, const AffxString &str2)
void replace (char c1, char c2)
AffxByteArray ()
AffxByteArray (const AffxByteArray &ba)
AffxByteArray (const AffxString &ba)
int getAllocLength () const
int getSize () const
int getUpperBound () const
void setSize (int nNewSize, int nGrowBy=-1)
void freeExtra ()
void removeAll ()
char getAt (int nIndex) const
void setAt (int nIndex, char newElement)
char & elementAt (int nIndex)
const char * getData () const
char * getData ()
void setAtGrow (int nIndex, char newElement)
int add (char newElement)
int append (const AffxByteArray &src)
int append (const AffxString &src)
int append (int i)
int append (unsigned int i)
int append (double d)
AffxByteArray & append (char bytes[], int offset, int len)
void copy (const AffxByteArray &src)
void assign (const AffxString &str)
char operator[] (int nIndex) const
char & operator[] (int nIndex)
void insertAt (int nIndex, char newElement, int nCount=1)
void removeAt (int nIndex, int nCount=1)
void insertAt (int nStartIndex, AffxByteArray *pNewArray)
bool operator== (const AffxByteArray &ba)
bool operator!= (const AffxByteArray &ba)
void copy (int iDestStart, const AffxByteArray &src, int iSrcStart, int iLength)
void setOffset (int iOffset)
bool getLine (AffxByteArray &ba)
int getColumnCount ()
AffxByteArray & getColumn (int iColumnNumber, AffxByteArray &ba)
int parseInt () const
char parseChar () const
bool parsebool () const
double parseDouble () const
AffxByteArray & trim ()
AffxByteArray & trimTabs ()
AffxString toString () const
bool startsWith (const AffxString &strCompare)
AffxString substring (int iIndex, int iEndIndex=-1)
AffxByteArray & toLowerCase ()
AffxByteArray & toUpperCase ()
void trimInternal ()
AffxString firstWord (int iOffset=0)
AffxByteArray reverseComplement ()
bool equals (const AffxString &str) const
bool equalsIgnoreCase (const AffxString &str)
int length () const
int getLength () const
bool nextLine (AffxByteArray &ba)
int getWordCount ()
AffxString getWord (int iWordIndex)
int parameterCount ()
AffxByteArray getParameter (int iParameterIndex)
int csvParameterCount ()
AffxByteArray getCsvParameter (int iParameterIndex)
int append (char by)
AffxByteArray getWord (int iWordIndex, AffxByteArray &ba)
int indexOf (const AffxString &str)
bool isValid ()
bool isValid (bool bParameterFile)
AffxByteArray nextColumn (AffxByteArray &ba)
int compareTo (const AffxString &that) const
int compareTo (const AffxByteArray &that) const
int compareTo (const AffxByteArray &obj, int iCompareCode) const
int getMaxRun (char byBase)
int getCountInWindow (char byBase, int iWindowSize)
int getCount (char byBase)
AffxByteArray nextField (AffxByteArray &ba)
bool readFile (const AffxString &strFileName)
~AffxByteArray ()
Protected Types
typedef char BASE_TYPE
typedef char BASE_ARG_TYPE
Protected Attributes
char * m_pData
int m_nSize
int m_nMaxSize
int m_nGrowBy
bool m_bLocked
int m_iOffset
int m_iFieldOffset
Private Member Functions
bool getLine (int iStart, int iIndex, int iLength, AffxByteArray &ba, bool bRemoveLastByte)
bool nextColumn (int iStart, int iIndex, int iLength, AffxByteArray &ba)
bool nextField (int iStart, int iIndex, int iLength, AffxByteArray &ba)
Detailed Description
A class for managing large byte arrays.
Definition at line 36 of file AffxByteArray.h.
Member Typedef Documentation
typedef char AffxByteArray::BASE_ARG_TYPE [protected]
Definition at line 174 of file AffxByteArray.h.
typedef char AffxByteArray::BASE_TYPE [protected]
Definition at line 173 of file AffxByteArray.h.
Constructor & Destructor Documentation
AffxByteArray::AffxByteArray ()
Definition at line 88 of file AffxByteArray.cpp.
AffxByteArray::AffxByteArray (const AffxByteArray & ba)
Definition at line 96 of file AffxByteArray.cpp.
References getSize(), and m_pData.
AffxByteArray::AffxByteArray (const AffxString & ba)
Definition at line 108 of file AffxByteArray.cpp.
References AffxString::charAt().
AffxByteArray::~AffxByteArray ()
Definition at line 124 of file AffxByteArray.cpp.
Member Function Documentation
int AffxByteArray::add (char newElement)
Definition at line 61 of file AffxByteArray.cpp.
int AffxByteArray::append (char by)
Definition at line 952 of file AffxByteArray.cpp.
int AffxByteArray::append (const AffxByteArray & src)
Definition at line 218 of file AffxByteArray.cpp.
References m_nSize, and m_pData.
Referenced by assign(), getCsvParameter(), getParameter(), getWord(), and replace().
int AffxByteArray::append (const AffxString & src)
Definition at line 206 of file AffxByteArray.cpp.
int AffxByteArray::append (int i) [inline]
Definition at line 82 of file AffxByteArray.h.
References append(), and getInt().
Referenced by append().
int AffxByteArray::append (unsigned int i) [inline]
Definition at line 83 of file AffxByteArray.h.
References append(), and getUnsignedInt().
Referenced by append().
int AffxByteArray::append (double d) [inline]
Definition at line 84 of file AffxByteArray.h.
References append(), and getDouble().
Referenced by append().
AffxByteArray & AffxByteArray::append (char bytes[], int offset, int len)
Definition at line 827 of file AffxByteArray.cpp.
void AffxByteArray::assign (const AffxString & str) [inline]
Definition at line 87 of file AffxByteArray.h.
References append(), and setSize().
Referenced by CalvinToText::run().
void AffxByteArray::clear (void)
Definition at line 83 of file AffxByteArray.cpp.
int AffxByteArray::compareTo (const AffxString & that) const
Definition at line 1312 of file AffxByteArray.cpp.
References __minimum, and AffxString::charAt().
int AffxByteArray::compareTo (const AffxByteArray & that) const
Definition at line 1292 of file AffxByteArray.cpp.
References __minimum, m_nSize, and m_pData.
int AffxByteArray::compareTo (const AffxByteArray & obj, int iCompareCode) const
Definition at line 1266 of file AffxByteArray.cpp.
References parseInt().
void AffxByteArray::copy (const AffxByteArray & src)
Definition at line 229 of file AffxByteArray.cpp.
References m_nSize, and m_pData.
Referenced by firstWord(), getColumn(), getLine(), and substring().
void AffxByteArray::copy (int iDestStart, const AffxByteArray & src, int iSrcStart, int iLength)
Definition at line 442 of file AffxByteArray.cpp.
References m_pData.
int AffxByteArray::csvParameterCount ()
Definition at line 996 of file AffxByteArray.cpp.
char & AffxByteArray::elementAt (int nIndex)
Definition at line 54 of file AffxByteArray.cpp.
void AffxByteArray::empty (void)
Definition at line 71 of file AffxByteArray.cpp.
bool AffxByteArray::equals (const AffxString & str) const
Definition at line 353 of file AffxByteArray.cpp.
References AffxString::getAt().
Referenced by parsebool().
bool AffxByteArray::equalsIgnoreCase (const AffxString & str)
Definition at line 381 of file AffxByteArray.cpp.
References AffxString::getAt().
AffxString AffxByteArray::firstWord (int iOffset = 0)
Definition at line 762 of file AffxByteArray.cpp.
References copy(), setSize(), and toString().
void AffxByteArray::freeExtra ()
Definition at line 237 of file AffxByteArray.cpp.
int AffxByteArray::getAllocLength () const
Definition at line 40 of file AffxByteArray.cpp.
char AffxByteArray::getAt (int nIndex) const
Definition at line 48 of file AffxByteArray.cpp.
Referenced by insertAt(), operator==(), and reverseComplement().
AffxByteArray & AffxByteArray::getColumn (int iColumnNumber, AffxByteArray & ba)
Definition at line 513 of file AffxByteArray.cpp.
References copy(), and setSize().
int AffxByteArray::getColumnCount ()
Definition at line 497 of file AffxByteArray.cpp.
int AffxByteArray::getCount (char byBase)
Definition at line 1401 of file AffxByteArray.cpp.
int AffxByteArray::getCountInWindow (char byBase, int iWindowSize)
Definition at line 1384 of file AffxByteArray.cpp.
References __minimum.
AffxByteArray AffxByteArray::getCsvParameter (int iParameterIndex)
Definition at line 1077 of file AffxByteArray.cpp.
References append(), and setSize().
const char * AffxByteArray::getData () const
Definition at line 57 of file AffxByteArray.cpp.
char * AffxByteArray::getData ()
Definition at line 59 of file AffxByteArray.cpp.
int AffxByteArray::getInt (int & iIndex)
Definition at line 425 of file AffxByteArray.cpp.
Referenced by append().
int AffxByteArray::getLength () const [inline]
Definition at line 125 of file AffxByteArray.h.
References getSize().
bool AffxByteArray::getLine (AffxByteArray & ba)
Definition at line 452 of file AffxByteArray.cpp.
References copy(), and setSize().
bool AffxByteArray::getLine (int iStart, int iIndex, int iLength, AffxByteArray & ba, bool bRemoveLastByte) [private]
Definition at line 894 of file AffxByteArray.cpp.
References m_pData, and setSize().
int AffxByteArray::getMaxRun (char byBase)
Definition at line 1366 of file AffxByteArray.cpp.
AffxByteArray AffxByteArray::getParameter (int iParameterIndex)
Definition at line 1030 of file AffxByteArray.cpp.
References append(), and setSize().
int AffxByteArray::getSize () const
Definition at line 42 of file AffxByteArray.cpp.
Referenced by AffxByteArray(), getLength(), insertAt(), length(), operator=(), and operator==().
int AffxByteArray::getUpperBound () const
Definition at line 44 of file AffxByteArray.cpp.
AffxString AffxByteArray::getWord (int iWordIndex)
Definition at line 922 of file AffxByteArray.cpp.
References append(), setSize(), and toString().
AffxByteArray AffxByteArray::getWord (int iWordIndex, AffxByteArray & ba)
Definition at line 1152 of file AffxByteArray.cpp.
References append(), and setSize().
int AffxByteArray::getWordCount ()
Definition at line 1124 of file AffxByteArray.cpp.
int AffxByteArray::indexOf (const AffxString & str) [inline]
Definition at line 137 of file AffxByteArray.h.
References AffxString::indexOf(), and toString().
void AffxByteArray::insertAt (int nIndex, char newElement, int nCount = 1)
Definition at line 269 of file AffxByteArray.cpp.
void AffxByteArray::insertAt (int nStartIndex, AffxByteArray * pNewArray)
Definition at line 307 of file AffxByteArray.cpp.
References getAt(), and getSize().
bool AffxByteArray::isAllWhitespace ()
Definition at line 1356 of file AffxByteArray.cpp.
bool AffxByteArray::isClear (void) [inline]
Definition at line 45 of file AffxByteArray.h.
References m_nSize.
bool AffxByteArray::isEmpty (void) [inline]
Definition at line 44 of file AffxByteArray.h.
References m_nMaxSize.
bool AffxByteArray::isLocked (void) [inline]
Definition at line 41 of file AffxByteArray.h.
References m_bLocked.
bool AffxByteArray::isValid () [inline]
Definition at line 139 of file AffxByteArray.h.
References isValid().
Referenced by isValid().
bool AffxByteArray::isValid (bool bParameterFile)
Definition at line 881 of file AffxByteArray.cpp.
References affx::trim().
int AffxByteArray::length () const [inline]
Definition at line 124 of file AffxByteArray.h.
References getSize().
void AffxByteArray::lockBuffer (void) [inline]
Definition at line 39 of file AffxByteArray.h.
References m_bLocked.
AffxByteArray AffxByteArray::nextColumn (AffxByteArray & ba)
Definition at line 1182 of file AffxByteArray.cpp.
References m_iFieldOffset, and setSize().
bool AffxByteArray::nextColumn (int iStart, int iIndex, int iLength, AffxByteArray & ba) [private]
Definition at line 1206 of file AffxByteArray.cpp.
References m_pData, and setSize().
bool AffxByteArray::nextField (int iStart, int iIndex, int iLength, AffxByteArray & ba) [private]
Definition at line 1247 of file AffxByteArray.cpp.
References m_pData, and setSize().
AffxByteArray AffxByteArray::nextField (AffxByteArray & ba)
Definition at line 1224 of file AffxByteArray.cpp.
References setSize().
bool AffxByteArray::nextLine (AffxByteArray & ba)
Definition at line 847 of file AffxByteArray.cpp.
References m_iOffset, and setSize().
bool AffxByteArray::operator!= (const AffxByteArray & ba) [inline]
Definition at line 100 of file AffxByteArray.h.
References operator==().
const AffxByteArray & AffxByteArray::operator= (const AffxByteArray & ba)
Definition at line 318 of file AffxByteArray.cpp.
References getSize().
bool AffxByteArray::operator== (const AffxByteArray & ba)
Definition at line 329 of file AffxByteArray.cpp.
References getAt(), and getSize().
Referenced by operator!=().
char AffxByteArray::operator[] (int nIndex) const
Definition at line 65 of file AffxByteArray.cpp.
char & AffxByteArray::operator[] (int nIndex)
Definition at line 67 of file AffxByteArray.cpp.
int AffxByteArray::parameterCount ()
Definition at line 962 of file AffxByteArray.cpp.
bool AffxByteArray::parsebool () const
Definition at line 567 of file AffxByteArray.cpp.
References equals(), toLowerCase(), and trimTabs().
char AffxByteArray::parseChar () const
Definition at line 554 of file AffxByteArray.cpp.
double AffxByteArray::parseDouble () const
Definition at line 817 of file AffxByteArray.cpp.
int AffxByteArray::parseInt () const
Definition at line 561 of file AffxByteArray.cpp.
Referenced by AffxArray< AffxArray< CalvinValue > >::compareAsInt(), AffxArray< AffxArray< CalvinValue > >::compareAsIntDescending(), and compareTo().
bool AffxByteArray::readFile (const AffxString & strFileName)
Definition at line 1412 of file AffxByteArray.cpp.
References Fs::aptOpen(), and Fs::fileSize().
void AffxByteArray::removeAll ()
Definition at line 46 of file AffxByteArray.cpp.
void AffxByteArray::removeAt (int nIndex, int nCount = 1)
Definition at line 296 of file AffxByteArray.cpp.
void AffxByteArray::replace (const AffxString & str1, const AffxString & str2)
Definition at line 1340 of file AffxByteArray.cpp.
References append(), setSize(), and toString().
Referenced by CalvinChpCheck::paramNamValTypeSame().
void AffxByteArray::replace (char c1, char c2)
Definition at line 1332 of file AffxByteArray.cpp.
AffxByteArray AffxByteArray::reverseComplement ()
Definition at line 791 of file AffxByteArray.cpp.
References getAt(), AffxString::getAt(), setAt(), and toLowerCase().
void AffxByteArray::setAt (int nIndex, char newElement)
Definition at line 51 of file AffxByteArray.cpp.
Referenced by reverseComplement().
void AffxByteArray::setAtGrow (int nIndex, char newElement)
Definition at line 262 of file AffxByteArray.cpp.
void AffxByteArray::setOffset (int iOffset)
Definition at line 451 of file AffxByteArray.cpp.
void AffxByteArray::setSize (int nNewSize, int nGrowBy = -1)
Definition at line 129 of file AffxByteArray.cpp.
References __maximum, and __minimum.
Referenced by assign(), firstWord(), getColumn(), getCsvParameter(), getLine(), getParameter(), getWord(), nextColumn(), nextField(), nextLine(), replace(), and substring().
bool AffxByteArray::startsWith (const AffxString & strCompare)
Definition at line 668 of file AffxByteArray.cpp.
References AffxString::getAt(), and AffxString::getLength().
AffxString AffxByteArray::substring (int iIndex, int iEndIndex = -1)
Definition at line 689 of file AffxByteArray.cpp.
References copy(), setSize(), and toString().
AffxByteArray & AffxByteArray::toLowerCase ()
Definition at line 706 of file AffxByteArray.cpp.
Referenced by parsebool(), and reverseComplement().
AffxString AffxByteArray::toString () const
Definition at line 648 of file AffxByteArray.cpp.
Referenced by firstWord(), getWord(), indexOf(), CalvinChpCheck::paramNamValTypeSame(), replace(), and substring().
AffxByteArray & AffxByteArray::toUpperCase ()
Definition at line 725 of file AffxByteArray.cpp.
AffxByteArray & AffxByteArray::trim ()
Definition at line 611 of file AffxByteArray.cpp.
void AffxByteArray::trimInternal ()
Definition at line 744 of file AffxByteArray.cpp.
AffxByteArray & AffxByteArray::trimTabs ()
Definition at line 579 of file AffxByteArray.cpp.
Referenced by parsebool().
void AffxByteArray::unlockBuffer (void) [inline]
Definition at line 40 of file AffxByteArray.h.
References m_bLocked.
Member Data Documentation
bool AffxByteArray::m_bLocked [protected]
Definition at line 160 of file AffxByteArray.h.
Referenced by isLocked(), lockBuffer(), and unlockBuffer().
int AffxByteArray::m_iFieldOffset [protected]
Definition at line 162 of file AffxByteArray.h.
Referenced by nextColumn().
int AffxByteArray::m_iOffset [protected]
Definition at line 161 of file AffxByteArray.h.
Referenced by nextLine().
int AffxByteArray::m_nGrowBy [protected]
Definition at line 158 of file AffxByteArray.h.
int AffxByteArray::m_nMaxSize [protected]
Definition at line 157 of file AffxByteArray.h.
Referenced by isEmpty().
int AffxByteArray::m_nSize [protected]
Definition at line 156 of file AffxByteArray.h.
Referenced by append(), compareTo(), copy(), and isClear().
char* AffxByteArray::m_pData [protected]
Definition at line 155 of file AffxByteArray.h.
Referenced by AffxByteArray(), append(), compareTo(), copy(), getLine(), nextColumn(), and nextField().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/AffxByteArray.h
C:/f112/affy/sdk/util/AffxByteArray.cpp