Affymetrix Fusion SDK: affymetrix_calvin_io::GenericDataHeader Class Reference
affymetrix_calvin_io::GenericDataHeader Class Reference
#include <GenericDataHeader.h>
Public Member Functions
GenericDataHeader ()
~GenericDataHeader ()
void Clear ()
void SetFileTypeId (const std::string &p)
std::string GetFileTypeId () const
void SetFileId (const affymetrix_calvin_utilities::AffymetrixGuidType &p)
affymetrix_calvin_utilities::AffymetrixGuidType GetFileId () const
void SetFileCreationTime (const std::wstring &f)
std::wstring GetFileCreationTime () const
void SetLocale (const std::wstring &p)
std::wstring GetLocale () const
void AddNameValParam (const ParameterNameValueType &p)
void AddNameValParam (const ParameterNameValueType &p, bool doUniqueAdds)
ParameterNameValueType GetNameValParam (int32_t index)
int32_t GetNameValParamCnt () const
void GetNameValIterators (ParameterNameValueTypeIt &begin, ParameterNameValueTypeIt &end)
int32_t GetParentCnt () const
void AddParent (const GenericDataHeader &hdr)
GenericDataHeader GetParent (int32_t index) const
void GetParentIterators (std::vector< GenericDataHeader >::iterator &begin, std::vector< GenericDataHeader >::iterator &end)
GenericDataHeader * FindParent (const std::string &fileTypeId)
bool FindNameValParam (const std::wstring &name, ParameterNameValueType &result)
bool GetNameValParamsBeginsWith (const std::wstring &beginsWith, ParameterNameValueTypeVector &p)
Protected Member Functions
ParameterNameValueTypeIt FindNameValParam (const ParameterNameValueType &p)
Private Attributes
std::string fileTypeId
affymetrix_calvin_utilities::AffymetrixGuidType fileId
std::wstring fileCreationTime
std::wstring locale
ParameterNameValueTypeVector nameValParams
std::vector< GenericDataHeader > GenericDataHdrs
std::map< std::wstring, int > paramNameIdxMap
Detailed Description
Definition at line 44 of file GenericDataHeader.h.
Constructor & Destructor Documentation
GenericDataHeader::GenericDataHeader ()
Definition at line 31 of file GenericDataHeader.cpp.
References US_ENGLISH_LOCALE.
affymetrix_calvin_io::GenericDataHeader::~GenericDataHeader () [inline]
Definition at line 49 of file GenericDataHeader.h.
Member Function Documentation
void GenericDataHeader::AddNameValParam (const ParameterNameValueType & p)
Calls AddNameValParam with the doUniqueAddds set to true.
Definition at line 85 of file GenericDataHeader.cpp.
Referenced by affxchpwriter::CCHPFileWriter::AddAlgorithmParameter(), affymetrix_calvin_io::CHPTilingData::AddAlgParams(), affymetrix_calvin_io::CHPMultiDataData::AddAppMetaInfo(), affymetrix_calvin_io::CHPQuantificationDetectionData::AddSummaryParams(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyGenericHeaderParams(), CreateFileWithHeader(), CopyNumberResultWriter::CreateResultFile(), affymetrix_calvin_io::GenericDataHeaderReader::Read(), affymetrix_calvin_io::DATData::SetArrayBarcode(), affymetrix_calvin_io::DATData::SetArrayId(), affymetrix_calvin_io::CHPData::SetFloatToGenericHdr(), affymetrix_calvin_io::DATData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CHPTilingData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CHPData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CelFileData::SetInt32ToGenericHdrParameterList(), affymetrix_calvin_io::DATData::SetPixelSize(), affymetrix_calvin_io::CDFData::SetRefSequence(), affymetrix_calvin_io::CDFData::SetUInt32ToGenericHdr(), affymetrix_calvin_io::CelFileData::SetVersion(), affymetrix_calvin_io::DATData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPTilingData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPQuantificationData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPMultiDataData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPData::SetWStringToGenericHdr(), affymetrix_calvin_io::CelFileData::SetWStringToGenericHdr(), and OutputMessageStream::Write().
void GenericDataHeader::AddNameValParam (const ParameterNameValueType & entry, bool doUniqueAdds)
Adds a ParameterNameValueType to the collection.
Parameters:
Parameter to add.
Hint to either perform a check to ensure unique parameters are in the collection (N^2 performance), else do not perfomr the check.
This override of the original method of the same name adds the parameter bool doUniqueAdds.
This parameter is a hint flag to determine whether to bypass the FindParameter call within. FindParameter is used to ensure duplicates do not get entered into the collection. In most cases, the calling application is not updating or adding parameter to the collection, but is just reading the header parameters. Through testing it has been found that bypassing the FindParameter call made, will reduce reads of the header greatly.
If an application is updating or adding parameters to the collection and require no duplicates to be added, then do not use this override method, but if you are just reading header parameters, then this will save time reading headers.
Definition at line 87 of file DataSetHeader.cpp.
References affymetrix_calvin_io::DataSetHeader::nameValParams.
void GenericDataHeader::AddParent (const GenericDataHeader & hdr)
Definition at line 139 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::CopyParentHeaders(), CreateFileWithHeader(), CopyNumberResultWriter::CreateResultFile(), and affymetrix_calvin_io::GenericDataHeaderReader::Read().
void GenericDataHeader::Clear ()
Definition at line 36 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::FileHeader::Clear().
bool GenericDataHeader::FindNameValParam (const std::wstring & name, ParameterNameValueType & result)
Finds a ParameterNameValueType by name in the nameValPairs collection
Parameters:
name The name of the NameValPair to find
result Reference to a ParameterNameValueType to fill with the found ParameterNameValueType.
Returns:
true if the ParameterNameValueType was found
Definition at line 179 of file GenericDataHeader.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
Referenced by affymetrix_calvin_io::GenericData::ArrayIdentifier(), affymetrix_calvin_io::CelFileData::FindAlgorithmParameter(), affymetrix_calvin_io::CHPData::GetAlgParam(), affymetrix_calvin_io::DATData::GetArrayBarcode(), affymetrix_calvin_io::DATData::GetArrayId(), affymetrix_calvin_io::CelFileData::GetChannels(), affymetrix_calvin_io::CHPData::GetChipSum(), affymetrix_fusion_io::CalvinCELDataAdapter::GetDatHeader(), affymetrix_calvin_io::CelFileData::GetDatHeader(), affymetrix_calvin_io::DATData::GetInt32FromGenericHdr(), affymetrix_calvin_io::CHPTilingData::GetInt32FromGenericHdr(), affymetrix_calvin_io::CHPData::GetInt32FromGenericHdr(), affymetrix_calvin_io::CelFileData::GetInt32FromGenericHdrParameterList(), affymetrix_calvin_io::DATData::GetPixelSize(), affymetrix_calvin_io::CDFData::GetRefSequence(), affymetrix_calvin_io::CDFData::GetUInt32FromGenericHdr(), affymetrix_calvin_io::CelFileData::GetVersion(), affymetrix_calvin_io::DATData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPTilingData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPQuantificationData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPMultiDataData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CelFileData::GetWStringFromGenericHdr(), affymetrix_calvin_io::GridControlFileReader::Read(), and affymetrix_calvin_io::MultiChannelCelFileCollater::UpdateWavelength().
ParameterNameValueTypeIt GenericDataHeader::FindNameValParam (const ParameterNameValueType & p) [protected]
Finds a ParameterNameValueType by name in the nameValPairs collection
Parameters:
p The ParameterNameValueType to find
Returns:
An iterator referencing the NameValPair if it exists, otherwise it returns nameValPairs.end()
Definition at line 193 of file GenericDataHeader.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetName().
GenericDataHeader * GenericDataHeader::FindParent (const std::string & fileTypeId)
Find an immediate parent GenericDataHeader based on file type id. Does not search grand-parents or above.
Parameters:
fileTypeId The fileTypeId of the parent header to find.
Returns:
Returns a pointer to the parent GenericDataHeader if found, otherwise returns 0.
Definition at line 163 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::GenericData::ArrayFileIdentifier(), affymetrix_calvin_io::GenericData::ArrayIdentifier(), affymetrix_calvin_io::CelFileData::GetChannels(), affymetrix_fusion_io::CalvinCELDataAdapter::GetDatHeader(), affymetrix_calvin_io::CelFileData::GetDatHeader(), and affymetrix_calvin_io::DATData::GetParentArrayGenericDataHeader().
std::wstring GenericDataHeader::GetFileCreationTime () const
Definition at line 70 of file GenericDataHeader.cpp.
Referenced by CalvinToText::OutputFileHeaderParameters(), and affymetrix_calvin_io::GenericDataHeaderWriter::WriteFileCreationTime().
affymetrix_calvin_utilities::AffymetrixGuidType GenericDataHeader::GetFileId () const
Definition at line 60 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::GenericData::ArrayFileIdentifier(), Calvin::equivalentHeader(), affymetrix_fusion_io::CalvinCHPDataAdapter::FileId(), affymetrix_calvin_io::GenericData::FileIdentifier(), Calvin::loadHeader(), CalvinToText::OutputDataHeaderParameters(), affymetrix_calvin_io::GenericDataHeaderWriter::WriteFileId(), and affymetrix_calvin_io::FileHeaderWriter::WriteGenericDataHdr().
std::string GenericDataHeader::GetFileTypeId () const
Definition at line 50 of file GenericDataHeader.cpp.
Referenced by CalvinChpCheck::check(), Calvin::equivalentHeader(), affymetrix_calvin_io::CDFData::GetDataTypeId(), Calvin::loadHeader(), CalvinToText::OutputDataHeaderParameters(), ReadGuidFromFile(), and affymetrix_calvin_io::GenericDataHeaderWriter::WriteFileTypeId().
std::wstring GenericDataHeader::GetLocale () const
Definition at line 80 of file GenericDataHeader.cpp.
Referenced by Calvin::equivalentHeader(), Calvin::loadHeader(), CalvinToText::OutputDataHeaderParameters(), and affymetrix_calvin_io::GenericDataHeaderWriter::WriteLocale().
void GenericDataHeader::GetNameValIterators (ParameterNameValueTypeIt & begin, ParameterNameValueTypeIt & end)
Definition at line 133 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::CopyGenericHeaderParams(), affymetrix_calvin_io::CHPTilingData::GetAlgParams(), CalvinToText::OutputDataHeaderParameters(), and affymetrix_calvin_io::GenericDataHeaderWriter::WriteNameValParams().
ParameterNameValueType GenericDataHeader::GetNameValParam (int32_t index)
Definition at line 123 of file GenericDataHeader.cpp.
Referenced by Calvin::equivalentHeader(), and Calvin::loadHeader().
int32_t GenericDataHeader::GetNameValParamCnt () const
Definition at line 128 of file GenericDataHeader.cpp.
Referenced by Calvin::equivalentHeader(), Calvin::loadHeader(), and affymetrix_calvin_io::GenericDataHeaderWriter::WriteNameValParamCnt().
bool GenericDataHeader::GetNameValParamsBeginsWith (const std::wstring & beginsWith, ParameterNameValueTypeVector & p)
Gets all ParameterNameValueType where the name starts with a given string.
Parameters:
beginsWith The string that the beginning of the ParameterNameValueType name needs to match.
p A result vector of ParameterNameValueTypes where the name begins with the beginsWith argument.
Definition at line 203 of file GenericDataHeader.cpp.
GenericDataHeader GenericDataHeader::GetParent (int32_t index) const
Definition at line 155 of file GenericDataHeader.cpp.
Referenced by CalvinToText::OutputDataHeaderParameters().
int32_t GenericDataHeader::GetParentCnt () const
Definition at line 150 of file GenericDataHeader.cpp.
Referenced by CalvinToText::OutputDataHeaderParameters(), and affymetrix_calvin_io::GenericDataHeaderWriter::WriteParentHdrCnt().
void GenericDataHeader::GetParentIterators (std::vector< GenericDataHeader >::iterator & begin, std::vector< GenericDataHeader >::iterator & end)
Definition at line 144 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::CopyParentHeaders(), and affymetrix_calvin_io::GenericDataHeaderWriter::WriteParentHdrs().
void GenericDataHeader::SetFileCreationTime (const std::wstring & f)
Definition at line 65 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read().
void GenericDataHeader::SetFileId (const affymetrix_calvin_utilities::AffymetrixGuidType & p)
Definition at line 55 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read(), affymetrix_calvin_io::DATFileUpdater::UpdateFileHeader(), OutputMessageStream::Write(), and affymetrix_calvin_io::FileHeaderWriter::WriteGenericDataHdr().
void GenericDataHeader::SetFileTypeId (const std::string & p)
Definition at line 45 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::CopyGenericHeader(), affymetrix_calvin_io::DATData::GetParentArrayGenericDataHeader(), affymetrix_calvin_io::GenericDataHeaderReader::Read(), affymetrix_calvin_io::CDFData::SetDataTypeId(), and OutputMessageStream::Write().
void GenericDataHeader::SetLocale (const std::wstring & p)
Definition at line 75 of file GenericDataHeader.cpp.
Referenced by affymetrix_calvin_io::GenericDataHeaderReader::Read().
Member Data Documentation
std::wstring affymetrix_calvin_io::GenericDataHeader::fileCreationTime [private]
Definition at line 58 of file GenericDataHeader.h.
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_io::GenericDataHeader::fileId [private]
Definition at line 56 of file GenericDataHeader.h.
std::string affymetrix_calvin_io::GenericDataHeader::fileTypeId [private]
Definition at line 54 of file GenericDataHeader.h.
std::vector<GenericDataHeader> affymetrix_calvin_io::GenericDataHeader::GenericDataHdrs [private]
Definition at line 64 of file GenericDataHeader.h.
std::wstring affymetrix_calvin_io::GenericDataHeader::locale [private]
Definition at line 60 of file GenericDataHeader.h.
ParameterNameValueTypeVector affymetrix_calvin_io::GenericDataHeader::nameValParams [private]
Definition at line 62 of file GenericDataHeader.h.
std::map<std::wstring, int> affymetrix_calvin_io::GenericDataHeader::paramNameIdxMap [private]
Definition at line 66 of file GenericDataHeader.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/GenericDataHeader.h
C:/f112/affy/sdk/calvin_files/data/src/DataSetHeader.cpp
C:/f112/affy/sdk/calvin_files/data/src/GenericDataHeader.cpp