Affymetrix Fusion SDK: affymetrix_calvin_io::DataSetWriter Class Reference
affymetrix_calvin_io::DataSetWriter Class Reference
#include <DataSetWriter.h>
Public Member Functions
DataSetWriter (std::ofstream *s, DataSetHeader *d)
~DataSetWriter ()
void WriteHeader ()
void UpdateNextDataSetOffset () const
void UpdateNextDataSetOffset (u_int32_t pos) const
void Write (int8_t p)
void Write (u_int8_t p)
void Write (int16_t p)
void Write (u_int16_t p)
void Write (int32_t p)
void Write (u_int32_t p)
void Write (float p)
void Write (const std::string &p, int32_t maxLn)
void Write (const std::wstring &p, int32_t maxLn)
void WriteBuffer (char *psBuffer, int32_t iLength)
std::wstring GetDataSetName () const
int32_t GetDataSetSize () const
Private Attributes
DataSetHeader * dataSetHdr
DataSetHeaderWriter hdrWriter
std::ofstream * os
int32_t columnCnt
int32_t columnIdx
int32_t rowIdx
int32_t rowCnt
Detailed Description
Definition at line 36 of file DataSetWriter.h.
Constructor & Destructor Documentation
DataSetWriter::DataSetWriter (std::ofstream * s, DataSetHeader * d)
Definition at line 24 of file DataSetWriter.cpp.
References columnCnt, columnIdx, dataSetHdr, affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), os, rowCnt, and rowIdx.
affymetrix_calvin_io::DataSetWriter::~DataSetWriter () [inline]
Definition at line 42 of file DataSetWriter.h.
References os.
Member Function Documentation
std::wstring DataSetWriter::GetDataSetName () const
Definition at line 54 of file DataSetWriter.cpp.
References dataSetHdr, and affymetrix_calvin_io::DataSetHeader::GetName().
Referenced by affymetrix_calvin_io::DATFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPFileWriter::SetFilePositions(), and affymetrix_calvin_io::CelFileWriter::SetFilePositions().
int32_t DataSetWriter::GetDataSetSize () const
Definition at line 59 of file DataSetWriter.cpp.
References dataSetHdr, and affymetrix_calvin_io::DataSetHeader::GetDataSize().
Referenced by affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader(), affymetrix_calvin_io::DATFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPTilingFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPQuantificationFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPFileWriter::SetFilePositions(), and affymetrix_calvin_io::CelFileWriter::SetFilePositions().
void DataSetWriter::UpdateNextDataSetOffset (u_int32_t pos) const
Definition at line 48 of file DataSetWriter.cpp.
References dataSetHdr, hdrWriter, os, affymetrix_calvin_io::DataSetHeader::SetNextSetFilePos(), and affymetrix_calvin_io::DataSetHeaderWriter::UpdateNextDataSetOffset().
void DataSetWriter::UpdateNextDataSetOffset () const
Definition at line 42 of file DataSetWriter.cpp.
References os.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::CDFProbeSetWriter::Close(), affymetrix_calvin_io::CDFCntrlProbeSetWriter::Close(), affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader(), affymetrix_calvin_io::DATFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPTilingFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPQuantificationFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPFileWriter::SetFilePositions(), affymetrix_calvin_io::CelFileWriter::SetFilePositions(), OutputMessageStream::Write(), affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataSet(), affymetrix_calvin_io::DATFileUpdater::WriteGridData(), and affymetrix_calvin_io::DATFileUpdater::WriteSubGridData().
void DataSetWriter::Write (int8_t p)
Definition at line 64 of file DataSetWriter.cpp.
References os, and WriteInt8().
Referenced by OutputMessageStream::Write(), affymetrix_calvin_io::CDFProbeSetWriter::Write(), affymetrix_calvin_io::CDFCntrlProbeSetWriter::Write(), affymetrix_calvin_io::CHPFileWriter::WriteBackgroundZone(), affymetrix_calvin_io::CDFFileWriter::WriteContentsEntry(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteContentsEntry(), affymetrix_calvin_io::CHPQuantificationFileWriter::WriteEntry(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::WriteEntry(), affymetrix_calvin_io::CHPMultiDataFileWriter::WriteEntry(), affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry(), affymetrix_calvin_io::CHPFileWriter::WriteForceCall(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), affymetrix_calvin_io::DATFileUpdater::WriteGridData(), affymetrix_calvin_io::CelFileWriter::WriteIntensities(), affymetrix_calvin_io::CelFileWriter::WriteMaskCoords(), affymetrix_calvin_io::CHPFileWriter::WriteOrigCall(), affymetrix_calvin_io::CelFileWriter::WriteOutlierCoords(), affymetrix_calvin_io::DATFileWriter::WritePixels(), affymetrix_calvin_io::CelFileWriter::WritePixels(), affymetrix_calvin_io::CHPFileWriter::WriteReseqEntry(), affymetrix_calvin_io::DATFileWriter::WriteStats(), affymetrix_calvin_io::CelFileWriter::WriteStdDevs(), affymetrix_calvin_io::DATFileUpdater::WriteSubGridData(), affymetrix_calvin_io::CHPTilingFileWriter::WriteTilingEntry(), and affymetrix_calvin_io::CHPFileWriter::WriteUniversalEntry().
void DataSetWriter::Write (const std::string & p, int32_t maxLn)
Definition at line 99 of file DataSetWriter.cpp.
References os, and affymetrix_calvin_io::FileOutput::WriteString8().
void DataSetWriter::Write (float p)
Definition at line 94 of file DataSetWriter.cpp.
References os, and affymetrix_calvin_io::FileOutput::WriteFloat().
void DataSetWriter::Write (int32_t p)
Definition at line 84 of file DataSetWriter.cpp.
References os, and affymetrix_calvin_io::FileOutput::WriteInt32().
void DataSetWriter::Write (u_int32_t p)
Definition at line 89 of file DataSetWriter.cpp.
References os, and affymetrix_calvin_io::FileOutput::WriteUInt32().
void DataSetWriter::Write (u_int16_t p)
Definition at line 79 of file DataSetWriter.cpp.
References os, and affymetrix_calvin_io::FileOutput::WriteUInt16().
void DataSetWriter::Write (const std::wstring & p, int32_t maxLn)
Definition at line 104 of file DataSetWriter.cpp.
References os, and affymetrix_calvin_io::FileOutput::WriteString16().
void DataSetWriter::Write (u_int8_t p)
Definition at line 69 of file DataSetWriter.cpp.
References os, and WriteUInt8().
void DataSetWriter::Write (int16_t p)
Definition at line 74 of file DataSetWriter.cpp.
References os, and affymetrix_calvin_io::FileOutput::WriteInt16().
void DataSetWriter::WriteBuffer (char * psBuffer, int32_t iLength)
Definition at line 109 of file DataSetWriter.cpp.
References os.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataSet().
void DataSetWriter::WriteHeader ()
Definition at line 34 of file DataSetWriter.cpp.
References dataSetHdr, hdrWriter, os, affymetrix_calvin_io::DataSetHeader::SetDataStartFilePos(), affymetrix_calvin_io::DataSetHeaderWriter::UpdateDataOffset(), and affymetrix_calvin_io::DataSetHeaderWriter::Write().
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader(), OutputMessageStream::Write(), affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataSet(), affymetrix_calvin_io::DATFileUpdater::WriteGridData(), affymetrix_calvin_io::CDFProbeSetWriter::WriteHeader(), affymetrix_calvin_io::CDFCntrlProbeSetWriter::WriteHeader(), affymetrix_calvin_io::DATFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPTilingFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPMultiDataFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPFileWriter::WriteHeaders(), affymetrix_calvin_io::CelFileWriter::WriteHeaders(), and affymetrix_calvin_io::DATFileUpdater::WriteSubGridData().
Member Data Documentation
int32_t affymetrix_calvin_io::DataSetWriter::columnCnt [private]
Definition at line 49 of file DataSetWriter.h.
Referenced by DataSetWriter().
int32_t affymetrix_calvin_io::DataSetWriter::columnIdx [private]
Definition at line 50 of file DataSetWriter.h.
Referenced by DataSetWriter().
DataSetHeader* affymetrix_calvin_io::DataSetWriter::dataSetHdr [private]
Definition at line 42 of file DataSetWriter.h.
Referenced by DataSetWriter(), GetDataSetName(), GetDataSetSize(), UpdateNextDataSetOffset(), and WriteHeader().
DataSetHeaderWriter affymetrix_calvin_io::DataSetWriter::hdrWriter [private]
Definition at line 47 of file DataSetWriter.h.
Referenced by UpdateNextDataSetOffset(), and WriteHeader().
std::ofstream* affymetrix_calvin_io::DataSetWriter::os [private]
Definition at line 48 of file DataSetWriter.h.
Referenced by DataSetWriter(), UpdateNextDataSetOffset(), Write(), WriteBuffer(), WriteHeader(), and ~DataSetWriter().
int32_t affymetrix_calvin_io::DataSetWriter::rowCnt [private]
Definition at line 52 of file DataSetWriter.h.
Referenced by DataSetWriter().
int32_t affymetrix_calvin_io::DataSetWriter::rowIdx [private]
Definition at line 51 of file DataSetWriter.h.
Referenced by DataSetWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DataSetWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/DataSetWriter.cpp