Affymetrix Fusion SDK: CProbeSetMultiDataCopyNumberVariationRegionDataCOM Class Reference
CProbeSetMultiDataCopyNumberVariationRegionDataCOM Class Reference
#include <ProbeSetMultiDataCopyNumberVariationRegionDataCOM.h>
Public Member Functions
CProbeSetMultiDataCopyNumberVariationRegionDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData & Data ()
STDMETHOD() get_name (BSTR *pVal)
STDMETHOD() get_signal (float *pVal)
STDMETHOD() get_call (int *pVal)
STDMETHOD() get_confidenceScore (float *pVal)
STDMETHOD() get_metricCount (int *pVal)
STDMETHOD() GetMetric (int index, VARIANT *pVal)
STDMETHOD() GetMetricName (int index, BSTR *pVal)
Private Attributes
affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData data
Detailed Description
Definition at line 36 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.h.
Constructor & Destructor Documentation
CProbeSetMultiDataCopyNumberVariationRegionDataCOM::CProbeSetMultiDataCopyNumberVariationRegionDataCOM () [inline]
Definition at line 43 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.h.
Member Function Documentation
affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData& CProbeSetMultiDataCopyNumberVariationRegionDataCOM::Data () [inline]
Definition at line 76 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.h.
Referenced by CFusionCHPMultiDataDataCOM::GetCopyNumberVariationRegionEntry().
HRESULT CProbeSetMultiDataCopyNumberVariationRegionDataCOM::FinalConstruct () [inline]
Definition at line 63 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.h.
void CProbeSetMultiDataCopyNumberVariationRegionDataCOM::FinalRelease () [inline]
Definition at line 68 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.h.
STDMETHODIMP CProbeSetMultiDataCopyNumberVariationRegionDataCOM::get_call (int * pVal)
Definition at line 57 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCopyNumberVariationRegionDataCOM::get_confidenceScore (float * pVal)
Definition at line 64 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCopyNumberVariationRegionDataCOM::get_metricCount (int * pVal)
Definition at line 70 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCopyNumberVariationRegionDataCOM::get_name (BSTR * pVal)
Definition at line 45 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CProbeSetMultiDataCopyNumberVariationRegionDataCOM::get_signal (float * pVal)
Definition at line 51 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric (int index, VARIANT * pVal)
Definition at line 83 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::AsciiType, COMStringUtils::ConvertString(), COMStringUtils::ConvertWString(), affymetrix_calvin_parameter::ParameterNameValueType::FloatType, affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), affymetrix_calvin_parameter::ParameterNameValueType::Int16Type, affymetrix_calvin_parameter::ParameterNameValueType::Int32Type, affymetrix_calvin_parameter::ParameterNameValueType::Int8Type, affymetrix_calvin_parameter::ParameterNameValueType::TextType, affymetrix_calvin_parameter::ParameterNameValueType::UInt16Type, affymetrix_calvin_parameter::ParameterNameValueType::UInt32Type, and affymetrix_calvin_parameter::ParameterNameValueType::UInt8Type.
STDMETHODIMP CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetricName (int index, BSTR * pVal)
Definition at line 76 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp.
References COMStringUtils::ConvertWString(), and affymetrix_calvin_parameter::ParameterNameValueType::GetName().
STDMETHODIMP CProbeSetMultiDataCopyNumberVariationRegionDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 30 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp.
Member Data Documentation
affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData CProbeSetMultiDataCopyNumberVariationRegionDataCOM::data [private]
Definition at line 73 of file ProbeSetMultiDataCopyNumberVariationRegionDataCOM.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataCopyNumberVariationRegionDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataCopyNumberVariationRegionDataCOM.cpp