Affymetrix Fusion SDK: affymetrix_fusion_io::FusionForceCallType Class Reference
affymetrix_fusion_io::FusionForceCallType Class Reference
#include <FusionProbeSetResults.h>
Public Member Functions
FusionForceCallType ()
Constructor.
FusionForceCallType (int32_t p, int8_t c, u_int8_t r)
Constructor.
~FusionForceCallType ()
Destructor.
void Clear ()
Clears members.
u_int8_t GetReason () const
Gets the reason.
void SetReason (u_int8_t r)
Sets the call.
Protected Attributes
int8_t reason
Detailed Description
A class to hold a force call, its position and reason.
A force call is the call the algorithm would have made if the thresholds were not applied.
Definition at line 479 of file FusionProbeSetResults.h.
Constructor & Destructor Documentation
FusionForceCallType::FusionForceCallType ()
Constructor.
Definition at line 416 of file FusionProbeSetResults.cpp.
References Clear().
FusionForceCallType::FusionForceCallType (int32_t p, int8_t c, u_int8_t r)
Constructor.
Parameters:
p Position
c Call
r Reason
Definition at line 421 of file FusionProbeSetResults.cpp.
References affymetrix_fusion_io::FusionBaseCallType::call, affymetrix_fusion_io::FusionBaseCallType::position, and reason.
FusionForceCallType::~FusionForceCallType ()
Destructor.
Definition at line 428 of file FusionProbeSetResults.cpp.
References Clear().
Member Function Documentation
void FusionForceCallType::Clear (void)
Clears members.
Reimplemented from affymetrix_fusion_io::FusionBaseCallType.
Definition at line 433 of file FusionProbeSetResults.cpp.
References affymetrix_fusion_io::FusionBaseCallType::call, affymetrix_fusion_io::FusionBaseCallType::position, and reason.
Referenced by FusionForceCallType(), and ~FusionForceCallType().
u_int8_t affymetrix_fusion_io::FusionForceCallType::GetReason () const [inline]
Gets the reason.
Returns:
Reason.
Definition at line 506 of file FusionProbeSetResults.h.
References reason.
Referenced by CFusionForceCallTypeCOM::get_Reason().
void affymetrix_fusion_io::FusionForceCallType::SetReason (u_int8_t r) [inline]
Sets the call.
Parameters:
r Reason value to set.
Definition at line 511 of file FusionProbeSetResults.h.
References reason.
Member Data Documentation
int8_t affymetrix_fusion_io::FusionForceCallType::reason [protected]
The reason for the call.
Definition at line 483 of file FusionProbeSetResults.h.
Referenced by Clear(), FusionForceCallType(), GetReason(), and SetReason().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.cpp