Affymetrix Fusion SDK: CProbeSetMultiDataGenotypeDataCOM Class Reference
CProbeSetMultiDataGenotypeDataCOM Class Reference
#include <ProbeSetMultiDataGenotypeDataCOM.h>
Public Member Functions
CProbeSetMultiDataGenotypeDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & Data ()
STDMETHOD() get_name (BSTR *pVal)
STDMETHOD() get_call (int *pVal)
STDMETHOD() get_confidence (float *pVal)
STDMETHOD() get_metricCount (int *pVal)
STDMETHOD() GetMetric (int index, VARIANT *pVal)
STDMETHOD() GetMetricName (int index, BSTR *pVal)
Private Attributes
affymetrix_calvin_data::ProbeSetMultiDataGenotypeData data
Detailed Description
Definition at line 29 of file ProbeSetMultiDataGenotypeDataCOM.h.
Constructor & Destructor Documentation
CProbeSetMultiDataGenotypeDataCOM::CProbeSetMultiDataGenotypeDataCOM () [inline]
Definition at line 36 of file ProbeSetMultiDataGenotypeDataCOM.h.
Member Function Documentation
affymetrix_calvin_data::ProbeSetMultiDataGenotypeData& CProbeSetMultiDataGenotypeDataCOM::Data () [inline]
Definition at line 68 of file ProbeSetMultiDataGenotypeDataCOM.h.
Referenced by CFusionCHPMultiDataDataCOM::GetGenotypeEntry().
HRESULT CProbeSetMultiDataGenotypeDataCOM::FinalConstruct () [inline]
Definition at line 55 of file ProbeSetMultiDataGenotypeDataCOM.h.
void CProbeSetMultiDataGenotypeDataCOM::FinalRelease () [inline]
Definition at line 60 of file ProbeSetMultiDataGenotypeDataCOM.h.
STDMETHODIMP CProbeSetMultiDataGenotypeDataCOM::get_call (int * pVal)
Definition at line 51 of file ProbeSetMultiDataGenotypeDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataGenotypeDataCOM::get_confidence (float * pVal)
Definition at line 57 of file ProbeSetMultiDataGenotypeDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataGenotypeDataCOM::get_metricCount (int * pVal)
Definition at line 63 of file ProbeSetMultiDataGenotypeDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataGenotypeDataCOM::get_name (BSTR * pVal)
Definition at line 45 of file ProbeSetMultiDataGenotypeDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CProbeSetMultiDataGenotypeDataCOM::GetMetric (int index, VARIANT * pVal)
Definition at line 76 of file ProbeSetMultiDataGenotypeDataCOM.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::AsciiType, COMStringUtils::ConvertString(), COMStringUtils::ConvertWString(), affymetrix_calvin_parameter::ParameterNameValueType::FloatType, affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), affymetrix_calvin_parameter::ParameterNameValueType::Int16Type, affymetrix_calvin_parameter::ParameterNameValueType::Int32Type, affymetrix_calvin_parameter::ParameterNameValueType::Int8Type, affymetrix_calvin_parameter::ParameterNameValueType::TextType, affymetrix_calvin_parameter::ParameterNameValueType::UInt16Type, affymetrix_calvin_parameter::ParameterNameValueType::UInt32Type, and affymetrix_calvin_parameter::ParameterNameValueType::UInt8Type.
STDMETHODIMP CProbeSetMultiDataGenotypeDataCOM::GetMetricName (int index, BSTR * pVal)
Definition at line 69 of file ProbeSetMultiDataGenotypeDataCOM.cpp.
References COMStringUtils::ConvertWString(), and affymetrix_calvin_parameter::ParameterNameValueType::GetName().
STDMETHODIMP CProbeSetMultiDataGenotypeDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 30 of file ProbeSetMultiDataGenotypeDataCOM.cpp.
Member Data Documentation
affymetrix_calvin_data::ProbeSetMultiDataGenotypeData CProbeSetMultiDataGenotypeDataCOM::data [private]
Definition at line 65 of file ProbeSetMultiDataGenotypeDataCOM.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataGenotypeDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataGenotypeDataCOM.cpp