Affymetrix Fusion SDK: affymetrix_calvin_io::CDFProbeSetWriter Class Reference
affymetrix_calvin_io::CDFProbeSetWriter Class Reference
#include <CDFProbeSetWriter.h>
Public Member Functions
CDFProbeSetWriter (DataSetWriter *dpw)
~CDFProbeSetWriter ()
void WriteHeader ()
void Close ()
void Write (u_int16_t xCoord, u_int16_t yCoord, u_int32_t atom, u_int32_t indexPos, int8_t baseProbe, int8_t baseTarget)
Private Attributes
DataSetWriter * writer
Detailed Description
Definition at line 34 of file CDFProbeSetWriter.h.
Constructor & Destructor Documentation
affymetrix_calvin_io::CDFProbeSetWriter::CDFProbeSetWriter (DataSetWriter * dpw) [inline]
Definition at line 39 of file CDFProbeSetWriter.h.
References writer.
affymetrix_calvin_io::CDFProbeSetWriter::~CDFProbeSetWriter () [inline]
Definition at line 40 of file CDFProbeSetWriter.h.
References writer.
Member Function Documentation
void CDFProbeSetWriter::Close (void)
Definition at line 29 of file CDFProbeSetWriter.cpp.
References affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), and writer.
void CDFProbeSetWriter::Write (u_int16_t xCoord, u_int16_t yCoord, u_int32_t atom, u_int32_t indexPos, int8_t baseProbe, int8_t baseTarget)
Definition at line 36 of file CDFProbeSetWriter.cpp.
References affymetrix_calvin_io::DataSetWriter::Write(), and writer.
void CDFProbeSetWriter::WriteHeader ()
Definition at line 24 of file CDFProbeSetWriter.cpp.
References affymetrix_calvin_io::DataSetWriter::WriteHeader(), and writer.
Member Data Documentation
DataSetWriter* affymetrix_calvin_io::CDFProbeSetWriter::writer [private]
Definition at line 40 of file CDFProbeSetWriter.h.
Referenced by CDFProbeSetWriter(), Close(), Write(), WriteHeader(), and ~CDFProbeSetWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CDFProbeSetWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CDFProbeSetWriter.cpp