Affymetrix Fusion SDK: affxcel::CCELFileHeaderData Class Reference
affxcel::CCELFileHeaderData Class Reference
CEL file header information.
#include <CELFileData.h>
Public Member Functions
CCELFileHeaderData ()
Default constructor.
~CCELFileHeaderData ()
Destructor.
void Clear ()
Clear and initialize content of member variables.
void SetMagic (int i)
Set magic number for xda format.
int GetMagic ()
Retrieve magic number from xda format.
void SetVersion (int i)
Set file format version number.
int GetVersion ()
Retrieve fiel format version number.
void SetCols (int i)
Set number of columns in array.
int GetCols ()
Retrieve number of columns in array.
void SetRows (int i)
Set number of rows in array.
int GetRows ()
Retrieve number of rows in array.
void SetCells (int i)
Set number of cells in array.
int GetCells ()
Retrieve number of cells in array.
void AppendHeader (const char *p)
Append data to header string.
void SetHeader (const char *p)
Set header information of CEL File in a single string.
std::string GetHeader ()
Concatenate header data into a string and return it.
void SetAlg (const char *p)
Set algorithm name.
std::string GetAlg ()
Retrieve algorithm name.
void SetParams (const char *p)
Set algorithm parameters.
std::string GetParams ()
Retrieve algorithm parameters.
void ParseChipType ()
Parse chip type of array from header string.
void SetChipType (const char *p)
Set chip type of array.
std::string GetChipType ()
Retrieve chip type of array.
void ParseDatHeader ()
Parse DAT header from header string.
void SetDatHeader ()
Set default DAT header.
void SetDatHeader (const char *p)
Set DAT header with input string.
std::string GetDatHeader ()
Retrieve DAT header.
void SetMargin (int i)
Set cell margin.
int GetMargin ()
Retrieve cell margin.
void SetOutliers (uint32_t l)
Set number of outliers.
uint32_t GetOutliers ()
Retrieve number of outliers.
void IncrementOutliers ()
Increment number of outliers by 1.
void DecrementOutliers ()
Decrement number of outliers by 1.
void SetMasked (uint32_t l)
Set number of masked cells.
uint32_t GetMasked ()
Retrieve number of masked cells.
void IncrementMasked ()
Increment number of masked cells by 1.
void DecrementMasked ()
Decrement number of masked cells by 1.
void ParseAlgorithmParameters ()
Parse algorithm parameters from single string into STL map.
void AddAlgorithmParameter (std::string &tag, std::string &value)
Add algorithm parameter into STL map. If tag already exists, the addition will be ignored.
void AddAlgorithmParameter (const char *tag, const char *value)
Call AddAlgorithmParameter() to add algorithm paramter into STL map. If tag already exists, the addition will be ignored.
void SetAlgorithmParameter (const char *tag, const char *value)
Set algorithm parameter value of existing specified tag.
void SetAddAlgorithmParameter (std::string &tag, std::string &value)
Set or Add algorithm parameter value.
void SetAddAlgorithmParameter (const char *tag, const char *value)
Set or Add algorithm parameter value.
std::string GetAlgorithmParameter (const char *tag)
Retrieve algorithm parameter value of specified tag.
std::string GetAlgorithmParameterTag (int index)
Retrieve algorithm parameter name of specified index.
int GetNumberAlgorithmParameters ()
std::string GetAlgorithmParameters ()
Retreive algorithm parameters from STL map and format them into a single string.
void SetGridCorners (GridCoordinatesType grid)
Set array grid coordinates.
void ParseCorners ()
Parse array grid coordinates from header string.
GridCoordinatesType GetGridCorners ()
Retrieve grid coordinates.
Private Attributes
int m_Magic
Magic number for identifying XDA format.
int m_Version
CEL file format version number.
int m_nCols
Number of columns in array.
int m_nRows
Number of rows in array.
int m_nCells
Number of cells in array.
std::string m_Header
Header information concatenated in a string.
std::string m_Alg
Algorithm name.
std::string m_Params
Algorithm parameters.
std::string m_ChipType
Chip type of array.
std::string m_DatHeader
DAT header string.
int m_Margin
Cell margin.
uint32_t m_nOutliers
Number of outliers.
uint32_t m_nMasked
Number of masked cells.
GridCoordinatesType m_CellGrid
Grid coordinates of array.
std::map< std::string,
std::string > m_Parameters
STL map of algorithm parameters.
std::map< int, std::string > m_ParameterIndices
STL map of algorithm parameter keys.
Detailed Description
CEL file header information.
affxcel::CCELFileHeaderData
Remarks:
Object instance is included in affxcel::CCELFileData
Definition at line 136 of file CELFileData.h.
Constructor & Destructor Documentation
CCELFileHeaderData::CCELFileHeaderData ()
Default constructor.
Constructor
public constructor CCELFileHeaderData
Returns:
void
Definition at line 131 of file CELFileData.cpp.
References CELL_FILE_VERSION_NUMBER, _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_Alg, m_CellGrid, m_ChipType, m_DatHeader, m_Header, m_Magic, m_Margin, m_nCells, m_nCols, m_nMasked, m_nOutliers, m_nRows, m_Params, m_Version, _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
CCELFileHeaderData::~CCELFileHeaderData ()
Destructor.
Destructor
public destructor ~CCELFileHeaderData
Returns:
void
Definition at line 162 of file CELFileData.cpp.
References Clear().
Member Function Documentation
void CCELFileHeaderData::AddAlgorithmParameter (std::string & tag, std::string & value)
Add algorithm parameter into STL map. If tag already exists, the addition will be ignored.
Adds a parameter to the list
Parameters:
tag The parameter name.
value The parameter value.
public overloaded AddAlgorithmParameter
Parameters:
tag std::string & Algorithm parameter tag
value std::string & Algorithm parameter value
Returns:
void
Definition at line 434 of file CELFileData.cpp.
References m_ParameterIndices, and m_Parameters.
Referenced by affxcel::CCELFileData::AddAlgorithmParameter(), AddAlgorithmParameter(), ParseAlgorithmParameters(), and SetMargin().
void CCELFileHeaderData::AddAlgorithmParameter (const char * tag, const char * value)
Call AddAlgorithmParameter() to add algorithm paramter into STL map. If tag already exists, the addition will be ignored.
Adds a parameter to the list
Parameters:
tag The parameter name.
value The parameter value.
public overloaded AddAlgorithmParameter
Parameters:
tag const char * Algorithm parameter tag
value const char * Algorithm parameter value
Returns:
void
Definition at line 414 of file CELFileData.cpp.
References AddAlgorithmParameter().
void affxcel::CCELFileHeaderData::AppendHeader (const char * p) [inline]
Append data to header string.
inline public AppendHeader
Parameters:
p const char * Header information
Returns:
void
Definition at line 264 of file CELFileData.h.
References m_Header.
Referenced by affxcel::CCELFileData::ReadTextCel().
void CCELFileHeaderData::Clear (void)
Clear and initialize content of member variables.
Clears the members
public Clear
Returns:
void
Definition at line 173 of file CELFileData.cpp.
References CELL_FILE_MAGIC_NUMBER, CELL_FILE_VERSION_NUMBER, _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_Alg, m_CellGrid, m_ChipType, m_DatHeader, m_Header, m_Magic, m_Margin, m_nCells, m_nCols, m_nMasked, m_nOutliers, m_nRows, m_ParameterIndices, m_Parameters, m_Params, m_Version, _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Referenced by affxcel::CCELFileData::Clear(), and ~CCELFileHeaderData().
void affxcel::CCELFileHeaderData::DecrementMasked () [inline]
Decrement number of masked cells by 1.
inline public DecrementMasked
Returns:
void
Definition at line 433 of file CELFileData.h.
References m_nMasked.
Referenced by affxcel::CCELFileData::SetMask().
void affxcel::CCELFileHeaderData::DecrementOutliers () [inline]
Decrement number of outliers by 1.
inline public DecrementOutliers
Returns:
void
Definition at line 404 of file CELFileData.h.
References m_nOutliers.
Referenced by affxcel::CCELFileData::SetOutlier().
std::string affxcel::CCELFileHeaderData::GetAlg () [inline]
Retrieve algorithm name.
inline public GetAlg
Returns:
std::string Algorithm name
Definition at line 294 of file CELFileData.h.
References m_Alg.
Referenced by affxcel::CCELFileData::GetAlg(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
std::string CCELFileHeaderData::GetAlgorithmParameter (const char * tag)
Retrieve algorithm parameter value of specified tag.
Retrieves a parameter value.
Parameters:
tag The parameter name.
Returns:
The parameter value.
public GetAlgorithmParameter
Parameters:
tag const char * Algorithm parameter tag
Returns:
std::string Algorithm parameter value or NULL if tag is not found
Definition at line 518 of file CELFileData.cpp.
References m_Parameters.
Referenced by affxcel::CCELFileData::GetAlgorithmParameter(), affxcel::CCELFileData::ReadTextCel(), and affxcel::CCELFileData::ReadTranscriptomeBCel().
std::string CCELFileHeaderData::GetAlgorithmParameters ()
Retreive algorithm parameters from STL map and format them into a single string.
Retrieves a parameters as a formatted string.
Returns:
The parameter name/value pairs.
public GetAlgorithmParameters
Returns:
std::string Algorithm parameters
Definition at line 554 of file CELFileData.cpp.
References m_ParameterIndices, and m_Parameters.
Referenced by affxcel::CCELFileData::GetAlgorithmParameters(), GetHeader(), affxcel::CCELFileData::GetParams(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
std::string CCELFileHeaderData::GetAlgorithmParameterTag (int index)
Retrieve algorithm parameter name of specified index.
Retrieves a parameter name.
Parameters:
index The index to the parameter array.
Returns:
The parameter name.
public GetAlgorithmParameterTag
Parameters:
index int Algorithm parameter index
Returns:
std::string Algorithm parameter name or NULL if not found
Definition at line 537 of file CELFileData.cpp.
References m_ParameterIndices.
Referenced by affxcel::CCELFileData::GetAlgorithmParameterTag().
int affxcel::CCELFileHeaderData::GetCells () [inline]
Retrieve number of cells in array.
inline public GetCells
Returns:
int Number of cells
Definition at line 256 of file CELFileData.h.
References m_nCells.
Referenced by affxcel::CCELFileData::AllocateEntries(), affxcel::CCELFileData::AllocateTranscriptomeEntries(), affxcel::CCELFileData::GetEntry(), affxcel::CCELFileData::GetIntensities(), affxcel::CCELFileData::GetIntensity(), affxcel::CCELFileData::GetNumCells(), affxcel::CCELFileData::GetPixels(), affxcel::CCELFileData::GetStdv(), affxcel::CCELFileData::GetTranscriptomeEntry(), affxcel::CCELFileData::IsMasked(), affxcel::CCELFileData::IsOutlier(), affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), affxcel::CCELFileData::SetIntensity(), affxcel::CCELFileData::SetMask(), affxcel::CCELFileData::SetOutlier(), affxcel::CCELFileData::SetPixels(), affxcel::CCELFileData::SetStdv(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
std::string affxcel::CCELFileHeaderData::GetChipType () [inline]
Retrieve chip type of array.
inline public GetChipType
Returns:
std::string Chip type
Definition at line 331 of file CELFileData.h.
References m_ChipType.
Referenced by affxcel::CCELFileData::GetChipType(), and affxcel::CCELFileData::SetChipType().
int affxcel::CCELFileHeaderData::GetCols () [inline]
Retrieve number of columns in array.
inline public GetCols
Returns:
int Number of columns
Definition at line 226 of file CELFileData.h.
References m_nCols.
Referenced by affxcel::CCELFileData::GetCols(), affxcel::CCELFileData::GetEntry(), affxcel::CCELFileData::GetIntensity(), affxcel::CCELFileData::GetPixels(), affxcel::CCELFileData::GetStdv(), affxcel::CCELFileData::GetTranscriptomeEntry(), affxcel::CCELFileData::IndexToX(), affxcel::CCELFileData::IndexToY(), affxcel::CCELFileData::IsMasked(), affxcel::CCELFileData::IsOutlier(), affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), affxcel::CCELFileData::SetIntensity(), affxcel::CCELFileData::SetMask(), affxcel::CCELFileData::SetOutlier(), affxcel::CCELFileData::SetPixels(), affxcel::CCELFileData::SetStdv(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), affxcel::CCELFileWriter::WriteXDABCel(), and affxcel::CCELFileData::XYToIndex().
std::string affxcel::CCELFileHeaderData::GetDatHeader () [inline]
Retrieve DAT header.
inline public GetDatHeader
Returns:
std::string DAT header
Definition at line 360 of file CELFileData.h.
References m_DatHeader.
Referenced by affxcel::CCELFileData::GetDatHeader(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileWriter::WriteTextCel(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
GridCoordinatesType affxcel::CCELFileHeaderData::GetGridCorners () [inline]
Retrieve grid coordinates.
inline public GetGridCorners
Returns:
GridCoordinatesType Grid coordinates
Definition at line 503 of file CELFileData.h.
References m_CellGrid.
Referenced by affxcel::CCELFileData::GetGridCorners(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileWriter::WriteTextCel(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
std::string CCELFileHeaderData::GetHeader ()
Concatenate header data into a string and return it.
public GetHeader
Returns:
std::string Header string
Definition at line 208 of file CELFileData.cpp.
References GetAlgorithmParameters(), _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_Alg, m_CellGrid, m_DatHeader, m_Header, m_nCols, m_nRows, SetDatHeader(), _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Referenced by affxcel::CCELFileData::GetHeaderString(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::SetChipType(), affxcel::CCELFileWriter::WriteCompactBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
int affxcel::CCELFileHeaderData::GetMagic () [inline]
Retrieve magic number from xda format.
inline public GetMagic
Returns:
int Magic number
Definition at line 196 of file CELFileData.h.
References m_Magic.
int affxcel::CCELFileHeaderData::GetMargin () [inline]
Retrieve cell margin.
inline public GetMargin
Returns:
int Cell margin
Definition at line 375 of file CELFileData.h.
References m_Margin.
Referenced by affxcel::CCELFileData::GetCellMargin(), affxcel::CCELFileWriter::WriteCompactBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
uint32_t affxcel::CCELFileHeaderData::GetMasked () [inline]
Retrieve number of masked cells.
inline public GetMasked
Returns:
uint32_t Number of masked cells
Definition at line 419 of file CELFileData.h.
References m_nMasked.
Referenced by affxcel::CCELFileData::GetNumMasked(), affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
int affxcel::CCELFileHeaderData::GetNumberAlgorithmParameters () [inline]
Retrieves the number of parameter name/value pairs.
Returns:
The number of parameter name/value pairs.
Definition at line 483 of file CELFileData.h.
References m_Parameters.
Referenced by affxcel::CCELFileData::GetNumberAlgorithmParameters().
uint32_t affxcel::CCELFileHeaderData::GetOutliers () [inline]
Retrieve number of outliers.
inline public GetOutliers
Returns:
unsigned int32_t Number of outliers
Definition at line 390 of file CELFileData.h.
References m_nOutliers.
Referenced by affxcel::CCELFileData::GetNumOutliers(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
std::string affxcel::CCELFileHeaderData::GetParams () [inline]
Retrieve algorithm parameters.
inline public GetParams
Returns:
std::string Algorithm parameters
Definition at line 309 of file CELFileData.h.
References m_Params.
Referenced by affxcel::CCELFileData::ReadTranscriptomeBCel().
int affxcel::CCELFileHeaderData::GetRows () [inline]
Retrieve number of rows in array.
inline public GetRows
Returns:
int Number of rows
Definition at line 241 of file CELFileData.h.
References m_nRows.
Referenced by affxcel::CCELFileData::GetEntry(), affxcel::CCELFileData::GetIntensity(), affxcel::CCELFileData::GetPixels(), affxcel::CCELFileData::GetRows(), affxcel::CCELFileData::GetStdv(), affxcel::CCELFileData::GetTranscriptomeEntry(), affxcel::CCELFileData::IsMasked(), affxcel::CCELFileData::IsOutlier(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::SetIntensity(), affxcel::CCELFileData::SetMask(), affxcel::CCELFileData::SetOutlier(), affxcel::CCELFileData::SetPixels(), affxcel::CCELFileData::SetStdv(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), affxcel::CCELFileWriter::WriteXDABCel(), and affxcel::CCELFileData::XYToIndex().
int affxcel::CCELFileHeaderData::GetVersion () [inline]
Retrieve fiel format version number.
inline public GetVersion
Returns:
int Version number
Definition at line 211 of file CELFileData.h.
References m_Version.
Referenced by affxcel::CCELFileData::GetVersion(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileWriter::WriteCompactBCel(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
void affxcel::CCELFileHeaderData::IncrementMasked () [inline]
Increment number of masked cells by 1.
inline public IncrementMasked
Returns:
void
Definition at line 426 of file CELFileData.h.
References m_nMasked.
Referenced by affxcel::CCELFileData::SetMask().
void affxcel::CCELFileHeaderData::IncrementOutliers () [inline]
Increment number of outliers by 1.
inline public IncrementOutliers
Returns:
void
Definition at line 397 of file CELFileData.h.
References m_nOutliers.
Referenced by affxcel::CCELFileData::SetOutlier().
void CCELFileHeaderData::ParseAlgorithmParameters ()
Parse algorithm parameters from single string into STL map.
Parses the algorithm parameters from the parameter string
public ParseAlgorithmParameters
Returns:
void
Definition at line 373 of file CELFileData.cpp.
References AddAlgorithmParameter(), and m_Params.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), and SetParams().
void CCELFileHeaderData::ParseChipType ()
Parse chip type of array from header string.
public ParseChipType
Returns:
void
Definition at line 337 of file CELFileData.cpp.
References DELIMCHAR, m_ChipType, and m_Header.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), and affxcel::CCELFileData::ReadXDABCel().
void CCELFileHeaderData::ParseCorners ()
Parse array grid coordinates from header string.
Parses the grid coordinates from the header.
public ParseCorners
Returns:
void
Definition at line 623 of file CELFileData.cpp.
References _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_CellGrid, m_Header, _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), and affxcel::CCELFileData::ReadXDABCel().
void CCELFileHeaderData::ParseDatHeader ()
Parse DAT header from header string.
public ParseDatHeader
Returns:
void
Definition at line 314 of file CELFileData.cpp.
References m_DatHeader, and m_Header.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), and affxcel::CCELFileData::ReadXDABCel().
void CCELFileHeaderData::SetAddAlgorithmParameter (const char * tag, const char * value)
Set or Add algorithm parameter value.
Set or Update the parameter value.
Parameters:
tag The parameter name.
value The parameter value.
public SetAddAlgorithmParameter
Parameters:
tag const char * Algorithm parameter tag
value const char * Algorithm parameter value
Returns:
void
Definition at line 476 of file CELFileData.cpp.
References SetAddAlgorithmParameter().
void CCELFileHeaderData::SetAddAlgorithmParameter (std::string & tag, std::string & value)
Set or Add algorithm parameter value.
Set or Update the parameter value.
Parameters:
tag The parameter name.
value The parameter value.
public SetAddAlgorithmParameter
Parameters:
tag const char * Algorithm parameter tag
value const char * Algorithm parameter value
Returns:
void
Definition at line 496 of file CELFileData.cpp.
References m_ParameterIndices, and m_Parameters.
Referenced by affxcel::CCELFileData::SetAddAlgorithmParameter(), and SetAddAlgorithmParameter().
void affxcel::CCELFileHeaderData::SetAlg (const char * p) [inline]
Set algorithm name.
inline public SetAlg
Parameters:
p const char * Algorithm name
Returns:
void
Definition at line 287 of file CELFileData.h.
References m_Alg.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), and affxcel::CCELFileData::SetAlgorithmName().
void CCELFileHeaderData::SetAlgorithmParameter (const char * tag, const char * value)
Set algorithm parameter value of existing specified tag.
Updates the parameter value.
Parameters:
tag The parameter name.
value The parameter value.
public SetAlgorithmParameter
Parameters:
tag const char * Algorithm parameter tag
value const char * Algorithm parameter value
Returns:
void
Definition at line 456 of file CELFileData.cpp.
References m_Parameters.
Referenced by affxcel::CCELFileData::SetAlgorithmParameter().
void affxcel::CCELFileHeaderData::SetCells (int i) [inline]
Set number of cells in array.
inline public SetCells
Parameters:
i int Number of cells
Returns:
void
Definition at line 249 of file CELFileData.h.
References m_nCells.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), and affxcel::CCELFileData::SetDimensions().
void affxcel::CCELFileHeaderData::SetChipType (const char * p) [inline]
Set chip type of array.
inline public SetChipType
Parameters:
p const char * Chip type
Returns:
void
Definition at line 324 of file CELFileData.h.
References m_ChipType.
Referenced by affxcel::CCELFileData::SetChipType().
void affxcel::CCELFileHeaderData::SetCols (int i) [inline]
Set number of columns in array.
inline public SetCols
Parameters:
i int Number of columns
Returns:
void
Definition at line 219 of file CELFileData.h.
References m_nCols.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), and affxcel::CCELFileData::SetDimensions().
void affxcel::CCELFileHeaderData::SetDatHeader (const char * p) [inline]
Set DAT header with input string.
inline public overloaded SetDatHeader
Parameters:
p const char * DAT header
Returns:
void
Definition at line 353 of file CELFileData.h.
References m_DatHeader.
void CCELFileHeaderData::SetDatHeader ()
Set default DAT header.
public overloaded SetDatHeader
Returns:
void
Definition at line 239 of file CELFileData.cpp.
References DELIMCHAR, m_ChipType, and m_DatHeader.
Referenced by GetHeader(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
void CCELFileHeaderData::SetGridCorners (GridCoordinatesType grid)
Set array grid coordinates.
Sets the grid coordinates.
Parameters:
grid The new grid coordinates.
public SetGridCorners
Parameters:
grid GridCoordinatesType Grid coordinates
Returns:
void
Definition at line 604 of file CELFileData.cpp.
References _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_CellGrid, _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Referenced by affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::SetDimensions(), and affxcel::CCELFileData::SetGridCorners().
void affxcel::CCELFileHeaderData::SetHeader (const char * p) [inline]
Set header information of CEL File in a single string.
inline public SetHeader
Parameters:
p const char * Header string
Returns:
void
Definition at line 272 of file CELFileData.h.
References m_Header.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), and affxcel::CCELFileData::SetChipType().
void affxcel::CCELFileHeaderData::SetMagic (int i) [inline]
Set magic number for xda format.
inline public SetMagic
Parameters:
i int Magic number
Returns:
void
Definition at line 189 of file CELFileData.h.
References m_Magic.
Referenced by affxcel::CCELFileData::ReadXDABCel().
void CCELFileHeaderData::SetMargin (int i)
Set cell margin.
inline public SetMargin
Parameters:
i int Cell margin
Returns:
void
Definition at line 589 of file CELFileData.cpp.
References AddAlgorithmParameter(), and m_Margin.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), and affxcel::CCELFileData::SetMargin().
void affxcel::CCELFileHeaderData::SetMasked (uint32_t l) [inline]
Set number of masked cells.
inline public SetMasked
Parameters:
l unsigned int32_t Number of masked cells
Returns:
void
Definition at line 412 of file CELFileData.h.
References m_nMasked.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), and affxcel::CCELFileData::ReadXDABCel().
void affxcel::CCELFileHeaderData::SetOutliers (uint32_t l) [inline]
Set number of outliers.
inline public SetOutliers
Parameters:
l unsigned int32_t Number of outliers
Returns:
void
Definition at line 383 of file CELFileData.h.
References m_nOutliers.
Referenced by affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), and affxcel::CCELFileData::ReadXDABCel().
void affxcel::CCELFileHeaderData::SetParams (const char * p) [inline]
Set algorithm parameters.
inline public SetParams
Parameters:
p const char * Algorithm parameters
Returns:
void
Definition at line 302 of file CELFileData.h.
References m_Params, and ParseAlgorithmParameters().
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), and affxcel::CCELFileData::ReadXDABCel().
void affxcel::CCELFileHeaderData::SetRows (int i) [inline]
Set number of rows in array.
inline public SetRows
Parameters:
i int Number of rows
Returns:
void
Definition at line 234 of file CELFileData.h.
References m_nRows.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), affxcel::CCELFileData::ReadXDABCel(), and affxcel::CCELFileData::SetDimensions().
void affxcel::CCELFileHeaderData::SetVersion (int i) [inline]
Set file format version number.
inline public SetVersion
Parameters:
i int Version number
Returns:
void
Definition at line 204 of file CELFileData.h.
References m_Version.
Referenced by affxcel::CCELFileData::ReadCompactBCel(), affxcel::CCELFileData::ReadTextCel(), affxcel::CCELFileData::ReadTranscriptomeBCel(), and affxcel::CCELFileData::ReadXDABCel().
Member Data Documentation
std::string affxcel::CCELFileHeaderData::m_Alg [private]
Algorithm name.
Definition at line 152 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetAlg(), GetHeader(), and SetAlg().
GridCoordinatesType affxcel::CCELFileHeaderData::m_CellGrid [private]
Grid coordinates of array.
Definition at line 166 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetGridCorners(), GetHeader(), ParseCorners(), and SetGridCorners().
std::string affxcel::CCELFileHeaderData::m_ChipType [private]
Chip type of array.
Definition at line 156 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetChipType(), ParseChipType(), SetChipType(), and SetDatHeader().
std::string affxcel::CCELFileHeaderData::m_DatHeader [private]
DAT header string.
Definition at line 158 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetDatHeader(), GetHeader(), ParseDatHeader(), and SetDatHeader().
std::string affxcel::CCELFileHeaderData::m_Header [private]
Header information concatenated in a string.
Definition at line 150 of file CELFileData.h.
Referenced by AppendHeader(), CCELFileHeaderData(), Clear(), GetHeader(), ParseChipType(), ParseCorners(), ParseDatHeader(), and SetHeader().
int affxcel::CCELFileHeaderData::m_Magic [private]
Magic number for identifying XDA format.
Definition at line 140 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetMagic(), and SetMagic().
int affxcel::CCELFileHeaderData::m_Margin [private]
Cell margin.
Definition at line 160 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetMargin(), and SetMargin().
int affxcel::CCELFileHeaderData::m_nCells [private]
Number of cells in array.
Definition at line 148 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetCells(), and SetCells().
int affxcel::CCELFileHeaderData::m_nCols [private]
Number of columns in array.
Definition at line 144 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetCols(), GetHeader(), and SetCols().
uint32_t affxcel::CCELFileHeaderData::m_nMasked [private]
Number of masked cells.
Definition at line 164 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), DecrementMasked(), GetMasked(), IncrementMasked(), and SetMasked().
uint32_t affxcel::CCELFileHeaderData::m_nOutliers [private]
Number of outliers.
Definition at line 162 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), DecrementOutliers(), GetOutliers(), IncrementOutliers(), and SetOutliers().
int affxcel::CCELFileHeaderData::m_nRows [private]
Number of rows in array.
Definition at line 146 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetHeader(), GetRows(), and SetRows().
std::map<int, std::string> affxcel::CCELFileHeaderData::m_ParameterIndices [private]
STL map of algorithm parameter keys.
Definition at line 171 of file CELFileData.h.
Referenced by AddAlgorithmParameter(), Clear(), GetAlgorithmParameters(), GetAlgorithmParameterTag(), and SetAddAlgorithmParameter().
std::map<std::string, std::string> affxcel::CCELFileHeaderData::m_Parameters [private]
STL map of algorithm parameters.
Definition at line 169 of file CELFileData.h.
Referenced by AddAlgorithmParameter(), Clear(), GetAlgorithmParameter(), GetAlgorithmParameters(), GetNumberAlgorithmParameters(), SetAddAlgorithmParameter(), and SetAlgorithmParameter().
std::string affxcel::CCELFileHeaderData::m_Params [private]
Algorithm parameters.
Definition at line 154 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetParams(), ParseAlgorithmParameters(), and SetParams().
int affxcel::CCELFileHeaderData::m_Version [private]
CEL file format version number.
Definition at line 142 of file CELFileData.h.
Referenced by CCELFileHeaderData(), Clear(), GetVersion(), and SetVersion().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CELFileData.h
C:/f112/affy/sdk/file/CELFileData.cpp