Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCDFProbeInformation Class Reference
affymetrix_fusion_io::FusionCDFProbeInformation Class Reference
#include <FusionCDFData.h>
Public Member Functions
int GetListIndex () const
int GetExpos () const
int GetX () const
int GetY () const
char GetPBase () const
char GetTBase () const
unsigned short GetProbeLength () const
unsigned short GetProbeGrouping () const
FusionCDFProbeInformation ()
~FusionCDFProbeInformation ()
Private Member Functions
void Initialize (int index, affxcdf::CCDFProbeGroupInformation *gcosGroup)
void Initialize (int index, affymetrix_calvin_io::CDFProbeGroupInformation *calvinGroup)
void Clear ()
Private Attributes
affxcdf::CCDFProbeInformation * gcosProbe
affymetrix_calvin_io::CDFProbeInformation * calvinProbe
Friends
class FusionCDFProbeGroupInformation
Detailed Description
This class provides storage for an individual probe in a CDF file
Definition at line 111 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFProbeInformation::FusionCDFProbeInformation ()
Constructor
Definition at line 505 of file FusionCDFData.cpp.
FusionCDFProbeInformation::~FusionCDFProbeInformation ()
Destructor
Definition at line 514 of file FusionCDFData.cpp.
Member Function Documentation
void FusionCDFProbeInformation::Clear (void) [private]
Deallocates any used memory.
Definition at line 542 of file FusionCDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetCell().
int FusionCDFProbeInformation::GetExpos () const
Returns the expos value.
Returns:
The expos value.
Definition at line 412 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeInformationCOM::get_Expos().
int FusionCDFProbeInformation::GetListIndex () const
Returns the list index.
Returns:
The list index.
Definition at line 399 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeInformationCOM::get_ListIndex().
char FusionCDFProbeInformation::GetPBase () const
Returns the probes base at the interrogation position.
Returns:
The probes base at the interrogation position.
Definition at line 451 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeInformationCOM::get_PBase().
unsigned short FusionCDFProbeInformation::GetProbeGrouping () const
Returns the probe grouping.
Returns:
The probe grouping.
Definition at line 492 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeInformationCOM::get_ProbeGrouping().
unsigned short FusionCDFProbeInformation::GetProbeLength () const
Returns the probe length.
Returns:
The probe length.
Definition at line 479 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeInformationCOM::get_ProbeLength().
char FusionCDFProbeInformation::GetTBase () const
Returns the targets base at the interrogation position.
Returns:
The targets base at the interrogation position.
Definition at line 465 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeInformationCOM::get_TBase().
int FusionCDFProbeInformation::GetX () const
Returns the X coordinate.
Returns:
The X coordinate.
Definition at line 425 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeInformationCOM::get_X(), ReadSingleChannelCelFile(), and ReadSingleOrMultiChannelCelFile().
int FusionCDFProbeInformation::GetY () const
Returns the Y coordinate.
Returns:
The Y coordinate.
Definition at line 438 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeInformationCOM::get_Y(), ReadSingleChannelCelFile(), and ReadSingleOrMultiChannelCelFile().
void FusionCDFProbeInformation::Initialize (int index, affxcdf::CCDFProbeGroupInformation * gcosGroup) [private]
Initializes the class for GCOS file reading.
Parameters:
index The index to the probe.
gcosGroup The GCOS probe group object.
Definition at line 522 of file FusionCDFData.cpp.
References affxcdf::CCDFProbeGroupInformation::GetCell().
Referenced by affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetCell().
void FusionCDFProbeInformation::Initialize (int index, affymetrix_calvin_io::CDFProbeGroupInformation * calvinGroup) [private]
Initializes the class for Calvin file reading.
Parameters:
index The index to the probe.
calvinGroup The Calvin probe group object.
Definition at line 532 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeGroupInformation::GetCell().
Friends And Related Function Documentation
friend class FusionCDFProbeGroupInformation [friend]
Friend to the parent class.
Definition at line 136 of file FusionCDFData.h.
Member Data Documentation
affymetrix_calvin_io::CDFProbeInformation* affymetrix_fusion_io::FusionCDFProbeInformation::calvinProbe [private]
The Calvin probe object.
Definition at line 118 of file FusionCDFData.h.
affxcdf::CCDFProbeInformation* affymetrix_fusion_io::FusionCDFProbeInformation::gcosProbe [private]
The GCOS probe object.
Definition at line 115 of file FusionCDFData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.cpp