Affymetrix Fusion SDK: affxutil::Guid Class Reference
affxutil::Guid Class Reference
#include <Guid.h>
Public Member Functions
Guid ()
~Guid ()
Static Public Member Functions
static GuidType GenerateNewGuid ()
Detailed Description
This class provides functions for creating globally unique identifiers.
Todo:
: Why do we need GuidType and this class?
Definition at line 64 of file Guid.h.
Constructor & Destructor Documentation
Guid::Guid ()
Constructor
Definition at line 106 of file Guid.cpp.
References affxutil::ensure_srand_seeded().
Guid::~Guid ()
Destructor
Definition at line 118 of file Guid.cpp.
Member Function Documentation
GuidType Guid::GenerateNewGuid () [static]
Generates a new GUID.
Returns:
The new GUID.
Todo:
This is bad -- consecutive calles to "rand()" are not random. The values should be hashed with something stronger than ones complement.
Todo:
printf will pad with "0" if the format string has a leading "0". The format string should be: "%010d-%010d-%010d-%010d-%010d", And is this what a uuid is supposed to look like? 'uuidgen' prints a value like: "a5b4b2ca-006d-4b89-b7ca-14eedb1e02b9"
Definition at line 166 of file Guid.cpp.
References affxutil::ensure_srand_seeded(), and affxutil::CheckSum::OnesComplementCheckSum().
Referenced by tsvJoin::beginOutput(), dumpPgf::beginOutput(), tsvJoin::beginOutputHeader(), main(), affx::TsvFileDiff::open_residuals(), CalvinToText::OutputDataHeaderParameters(), and dumpPgf::writeOutputHeader().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/Guid.h
C:/f112/affy/sdk/util/Guid.cpp