Affymetrix Fusion SDK: affymetrix_fusion_io::FusionExpressionProbeSetResults Class Reference
affymetrix_fusion_io::FusionExpressionProbeSetResults Class Reference
#include <FusionProbeSetResults.h>
Public Member Functions
void Clear ()
Clears the members.
float GetDetectionPValue () const
Gets detection pvalue.
float GetSignal () const
Gets the signal.
u_int16_t GetNumPairs () const
gets the number of pairs.
u_int16_t GetNumUsedPairs () const
Gets the number used pairs.
u_int8_t GetDetection () const
Gets the detection.
bool HasCompResults () const
Determines if comp results exsist.
float GetChangePValue () const
Gets the change pvalue.
float GetSignalLogRatio () const
Gets the signal log ratio.
float GetSignalLogRatioLow () const
Gets the signal log ratio low.
float GetSignalLogRatioHigh () const
Gets the signal log ratio high.
u_int16_t GetNumCommonPairs () const
Gets the number of common pairs.
u_int8_t GetChange () const
Gets the change.
void SetDetectionPValue (float p)
Sets the detection pvalue.
void SetSignal (float p)
Sets the signal.
void SetNumPairs (u_int16_t p)
Sets the number of pairs.
void SetNumUsedPairs (u_int16_t p)
Sets the number of used pairs.
void SetDetection (u_int8_t p)
Sets detection.
void SetHasCompResults (bool p)
Sets whether has comp results.
void SetChangePValue (float p)
Sets the change pvalue.
void SetSignalLogRatio (float p)
Sets the signal log ratio.
void SetSignalLogRatioLow (float p)
Sets the signal log ratio low.
void SetSignalLogRatioHigh (float p)
Sets the signal log ratio high.
void SetNumCommonPairs (u_int16_t p)
Sets the number of common pairs.
void SetChange (u_int8_t p)
Sets the change.
std::string GetDetectionString ()
Gets a string representation of the detection call.
std::string GetChangeString ()
Gets a string representation of the change call.
FusionExpressionProbeSetResults operator= (FusionExpressionProbeSetResults &src)
FusionExpressionProbeSetResults ()
Constructor.
~FusionExpressionProbeSetResults ()
Destructor.
Private Attributes
float detectionPValue
float signal
u_int16_t numPairs
u_int16_t numPairsUsed
u_int8_t detection
bool hasCompResults
float changePValue
float sigLogRatio
float sigLogRatioLo
float sigLogRatioHi
u_int16_t numCommonPairs
u_int8_t change
Detailed Description
Expression analysis probe set results for the MAS5 algorithm
Definition at line 64 of file FusionProbeSetResults.h.
Constructor & Destructor Documentation
FusionExpressionProbeSetResults::FusionExpressionProbeSetResults ()
Constructor.
Definition at line 28 of file FusionProbeSetResults.cpp.
References Clear().
FusionExpressionProbeSetResults::~FusionExpressionProbeSetResults ()
Destructor.
Definition at line 33 of file FusionProbeSetResults.cpp.
Member Function Documentation
void FusionExpressionProbeSetResults::Clear (void)
Clears the members.
Definition at line 52 of file FusionProbeSetResults.cpp.
References SetChange(), SetChangePValue(), SetDetection(), SetDetectionPValue(), SetHasCompResults(), SetNumCommonPairs(), SetNumPairs(), SetNumUsedPairs(), SetSignal(), SetSignalLogRatio(), SetSignalLogRatioHigh(), and SetSignalLogRatioLow().
Referenced by FusionExpressionProbeSetResults().
u_int8_t FusionExpressionProbeSetResults::GetChange () const
Gets the change.
Returns:
Change.
Definition at line 123 of file FusionProbeSetResults.cpp.
References change.
Referenced by CFusionExpressionProbeSetResultsCOM::get_Change(), GetChangeString(), and operator=().
float FusionExpressionProbeSetResults::GetChangePValue () const
Gets the change pvalue.
Returns:
Cahnge pvalue.
Definition at line 98 of file FusionProbeSetResults.cpp.
References changePValue.
Referenced by CFusionExpressionProbeSetResultsCOM::get_ChangePValue(), and operator=().
std::string FusionExpressionProbeSetResults::GetChangeString ()
Gets a string representation of the change call.
Returns:
The change call
Definition at line 214 of file FusionProbeSetResults.cpp.
References COMP_DECREASE_CALL, COMP_INCREASE_CALL, COMP_MOD_DECREASE_CALL, COMP_MOD_INCREASE_CALL, COMP_NO_CALL, COMP_NO_CHANGE_CALL, and GetChange().
Referenced by CFusionExpressionProbeSetResultsCOM::GetChangeString().
u_int8_t FusionExpressionProbeSetResults::GetDetection () const
Gets the detection.
Returns:
Detection.
Definition at line 88 of file FusionProbeSetResults.cpp.
References detection.
Referenced by CFusionExpressionProbeSetResultsCOM::get_Detection(), GetDetectionString(), and operator=().
float FusionExpressionProbeSetResults::GetDetectionPValue () const
Gets detection pvalue.
Returns:
Detection pvalue.
Definition at line 68 of file FusionProbeSetResults.cpp.
References detectionPValue.
Referenced by CFusionExpressionProbeSetResultsCOM::get_DetectionPValue(), and operator=().
std::string FusionExpressionProbeSetResults::GetDetectionString ()
Gets a string representation of the detection call.
Returns:
The detection call
Definition at line 188 of file FusionProbeSetResults.cpp.
References ABS_ABSENT_CALL, ABS_MARGINAL_CALL, ABS_NO_CALL, ABS_PRESENT_CALL, and GetDetection().
Referenced by CFusionExpressionProbeSetResultsCOM::GetDetectionString().
u_int16_t FusionExpressionProbeSetResults::GetNumCommonPairs () const
Gets the number of common pairs.
Returns:
Number of common pairs.
Definition at line 118 of file FusionProbeSetResults.cpp.
References numCommonPairs.
Referenced by CFusionExpressionProbeSetResultsCOM::get_NumCommonPairs(), and operator=().
u_int16_t FusionExpressionProbeSetResults::GetNumPairs () const
gets the number of pairs.
Returns:
Number of pairs.
Definition at line 78 of file FusionProbeSetResults.cpp.
References numPairs.
Referenced by CFusionExpressionProbeSetResultsCOM::get_NumPairs(), and operator=().
u_int16_t FusionExpressionProbeSetResults::GetNumUsedPairs () const
Gets the number used pairs.
Returns:
Number of used pairs.
Definition at line 83 of file FusionProbeSetResults.cpp.
References numPairsUsed.
Referenced by CFusionExpressionProbeSetResultsCOM::get_NumUsedPairs(), and operator=().
float FusionExpressionProbeSetResults::GetSignal () const
Gets the signal.
Returns:
Signal.
Definition at line 73 of file FusionProbeSetResults.cpp.
References signal.
Referenced by ExpressionLegacyExample(), CFusionExpressionProbeSetResultsCOM::get_Signal(), and operator=().
float FusionExpressionProbeSetResults::GetSignalLogRatio () const
Gets the signal log ratio.
Returns:
Signal log ratio.
Definition at line 103 of file FusionProbeSetResults.cpp.
References sigLogRatio.
Referenced by CFusionExpressionProbeSetResultsCOM::get_SignalLogRatio(), and operator=().
float FusionExpressionProbeSetResults::GetSignalLogRatioHigh () const
Gets the signal log ratio high.
Returns:
Signal log ratio high.
Definition at line 113 of file FusionProbeSetResults.cpp.
References sigLogRatioHi.
Referenced by CFusionExpressionProbeSetResultsCOM::get_SignalLogRatioHigh(), and operator=().
float FusionExpressionProbeSetResults::GetSignalLogRatioLow () const
Gets the signal log ratio low.
Returns:
Signal log ratio low.
Definition at line 108 of file FusionProbeSetResults.cpp.
References sigLogRatioLo.
Referenced by CFusionExpressionProbeSetResultsCOM::get_SignalLogRatioLow(), and operator=().
bool FusionExpressionProbeSetResults::HasCompResults () const
Determines if comp results exsist.
Returns:
True if comp results exsist.
Definition at line 93 of file FusionProbeSetResults.cpp.
References hasCompResults.
Referenced by CFusionExpressionProbeSetResultsCOM::get_HasCompResults(), and operator=().
FusionExpressionProbeSetResults FusionExpressionProbeSetResults::operator= (FusionExpressionProbeSetResults & src)
Assignment operator
Parameters:
src The object to copy
Returns:
The copied object
Definition at line 35 of file FusionProbeSetResults.cpp.
References GetChange(), GetChangePValue(), GetDetection(), GetDetectionPValue(), GetNumCommonPairs(), GetNumPairs(), GetNumUsedPairs(), GetSignal(), GetSignalLogRatio(), GetSignalLogRatioHigh(), GetSignalLogRatioLow(), HasCompResults(), SetChange(), SetChangePValue(), SetDetection(), SetDetectionPValue(), SetHasCompResults(), SetNumCommonPairs(), SetNumPairs(), SetNumUsedPairs(), SetSignal(), SetSignalLogRatio(), SetSignalLogRatioHigh(), and SetSignalLogRatioLow().
void FusionExpressionProbeSetResults::SetChange (u_int8_t p)
Sets the change.
Parameters:
p Change value to set.
Definition at line 183 of file FusionProbeSetResults.cpp.
References change.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetChangePValue (float p)
Sets the change pvalue.
Parameters:
p Change pvalue to set.
Definition at line 158 of file FusionProbeSetResults.cpp.
References changePValue.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetDetection (u_int8_t p)
Sets detection.
Parameters:
p Detection to set.
Definition at line 148 of file FusionProbeSetResults.cpp.
References detection.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetDetectionPValue (float p)
Sets the detection pvalue.
Parameters:
p pvalue to set.
Definition at line 128 of file FusionProbeSetResults.cpp.
References detectionPValue.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetHasCompResults (bool p)
Sets whether has comp results.
Parameters:
p Flag whether comp results exsists.
Definition at line 153 of file FusionProbeSetResults.cpp.
References hasCompResults.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetNumCommonPairs (u_int16_t p)
Sets the number of common pairs.
Parameters:
p Number of common pairs.
Definition at line 178 of file FusionProbeSetResults.cpp.
References numCommonPairs.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetNumPairs (u_int16_t p)
Sets the number of pairs.
Parameters:
p Number of pairs.
Definition at line 138 of file FusionProbeSetResults.cpp.
References numPairs.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetNumUsedPairs (u_int16_t p)
Sets the number of used pairs.
Parameters:
p Number of used pairs to set.
Definition at line 143 of file FusionProbeSetResults.cpp.
References numPairsUsed.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetSignal (float p)
Sets the signal.
Parameters:
p Signal to set.
Definition at line 133 of file FusionProbeSetResults.cpp.
References signal.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetSignalLogRatio (float p)
Sets the signal log ratio.
Parameters:
p Signal log ratio.
Definition at line 163 of file FusionProbeSetResults.cpp.
References sigLogRatio.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetSignalLogRatioHigh (float p)
Sets the signal log ratio high.
Parameters:
p Signal log ratio high to set.
Definition at line 173 of file FusionProbeSetResults.cpp.
References sigLogRatioHi.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
void FusionExpressionProbeSetResults::SetSignalLogRatioLow (float p)
Sets the signal log ratio low.
Parameters:
p Signal ratio low.
Definition at line 168 of file FusionProbeSetResults.cpp.
References sigLogRatioLo.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), and operator=().
Member Data Documentation
u_int8_t affymetrix_fusion_io::FusionExpressionProbeSetResults::change [private]
The change call
Definition at line 101 of file FusionProbeSetResults.h.
Referenced by GetChange(), and SetChange().
float affymetrix_fusion_io::FusionExpressionProbeSetResults::changePValue [private]
The change p-value
Definition at line 86 of file FusionProbeSetResults.h.
Referenced by GetChangePValue(), and SetChangePValue().
u_int8_t affymetrix_fusion_io::FusionExpressionProbeSetResults::detection [private]
The detection call
Definition at line 80 of file FusionProbeSetResults.h.
Referenced by GetDetection(), and SetDetection().
float affymetrix_fusion_io::FusionExpressionProbeSetResults::detectionPValue [private]
The detection p-value
Definition at line 68 of file FusionProbeSetResults.h.
Referenced by GetDetectionPValue(), and SetDetectionPValue().
bool affymetrix_fusion_io::FusionExpressionProbeSetResults::hasCompResults [private]
Flag indicating that comparison results exist
Definition at line 83 of file FusionProbeSetResults.h.
Referenced by HasCompResults(), and SetHasCompResults().
u_int16_t affymetrix_fusion_io::FusionExpressionProbeSetResults::numCommonPairs [private]
The number of probe pairs in common between the experiment and baseline data
Definition at line 98 of file FusionProbeSetResults.h.
Referenced by GetNumCommonPairs(), and SetNumCommonPairs().
u_int16_t affymetrix_fusion_io::FusionExpressionProbeSetResults::numPairs [private]
The number of probe pairs in the set
Definition at line 74 of file FusionProbeSetResults.h.
Referenced by GetNumPairs(), and SetNumPairs().
u_int16_t affymetrix_fusion_io::FusionExpressionProbeSetResults::numPairsUsed [private]
The number of probe pairs used to calculate the signal value
Definition at line 77 of file FusionProbeSetResults.h.
Referenced by GetNumUsedPairs(), and SetNumUsedPairs().
float affymetrix_fusion_io::FusionExpressionProbeSetResults::sigLogRatio [private]
The signal log ratio
Definition at line 89 of file FusionProbeSetResults.h.
Referenced by GetSignalLogRatio(), and SetSignalLogRatio().
float affymetrix_fusion_io::FusionExpressionProbeSetResults::sigLogRatioHi [private]
The signal log ratio high value
Definition at line 95 of file FusionProbeSetResults.h.
Referenced by GetSignalLogRatioHigh(), and SetSignalLogRatioHigh().
float affymetrix_fusion_io::FusionExpressionProbeSetResults::sigLogRatioLo [private]
The signal log ratio low value
Definition at line 92 of file FusionProbeSetResults.h.
Referenced by GetSignalLogRatioLow(), and SetSignalLogRatioLow().
float affymetrix_fusion_io::FusionExpressionProbeSetResults::signal [private]
The signal value
Definition at line 71 of file FusionProbeSetResults.h.
Referenced by GetSignal(), and SetSignal().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.cpp