Affymetrix Fusion SDK: affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater Class Reference
affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater Class Reference
#include <CalvinCHPMultiDataFileUpdater.h>
Public Member Functions
CalvinCHPMultiDataFileUpdater ()
~CalvinCHPMultiDataFileUpdater ()
void Initialize (const char *file)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry, const std::vector< ColumnInfo > &metricColumns)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData &entry, const std::vector< ColumnInfo > &metricColumns)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData &entry, const std::vector< ColumnInfo > &metricColumns)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataExpressionData &entry, const std::vector< ColumnInfo > &metricColumns)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataExpressionData &entry)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData &entry, const std::vector< ColumnInfo > &metricColumns)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetBiAllelicData &entry, const std::vector< ColumnInfo > &metricColumns)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetBiAllelicData &entry)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetCopyNumberData &entry, const std::vector< ColumnInfo > &metricColumns)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetCopyNumberData &entry)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetMultiAllelicData &entry, const std::vector< ColumnInfo > &metricColumns)
void UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetMultiAllelicData &entry)
Private Member Functions
void UpdateMetrics (int dataSetIndex, int row, int startColIndex, const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > &metrics, const std::vector< ColumnInfo > &metricColumns)
Private Attributes
std::map< MultiDataType, int > dataSetIndexMap
Detailed Description
Provides interfaces to update data in a "Calvin" binary "MultiData" data file. This class assumes that the file has been completely written and that only existing data groups/sets/rows/cols are being modified.
Definition at line 41 of file CalvinCHPMultiDataFileUpdater.h.
Constructor & Destructor Documentation
CalvinCHPMultiDataFileUpdater::CalvinCHPMultiDataFileUpdater ()
Constructor
Definition at line 35 of file CalvinCHPMultiDataFileUpdater.cpp.
CalvinCHPMultiDataFileUpdater::~CalvinCHPMultiDataFileUpdater ()
Destructor
Definition at line 42 of file CalvinCHPMultiDataFileUpdater.cpp.
Member Function Documentation
void CalvinCHPMultiDataFileUpdater::Initialize (const char * file) [virtual]
Initialize the class given a "calvin" data file.
Parameters:
file The name of the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Reimplemented from affymetrix_calvin_io::DataSetUpdater.
Definition at line 46 of file CalvinCHPMultiDataFileUpdater.cpp.
References dataSetIndexMap, affymetrix_calvin_io::DataSetUpdater::dataSetNames, affymetrix_calvin_io::MultiDataDataSetNames, and affymetrix_calvin_io::MultiDataDataTypes.
void CalvinCHPMultiDataFileUpdater::UpdateMetrics (int dataSetIndex, int row, int startColIndex, const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > & metrics, const std::vector< ColumnInfo > & metricColumns) [private]
Update the metrics for the given row
Parameters:
row The row index.
dataSetIndex The data set index
startColIndex The starting column
metricColumns The column information.
Definition at line 980 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), affymetrix_calvin_io::CalvinCHPFileUpdater::m_CHPFile, affymetrix_calvin_io::FileOutput::WriteFloat(), affymetrix_calvin_io::FileOutput::WriteInt16(), affymetrix_calvin_io::FileOutput::WriteInt32(), WriteInt8(), affymetrix_calvin_io::FileOutput::WriteString16(), affymetrix_calvin_io::FileOutput::WriteString8(), affymetrix_calvin_io::FileOutput::WriteUInt16(), affymetrix_calvin_io::FileOutput::WriteUInt32(), and WriteUInt8().
Referenced by UpdateMultiData().
void CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetMultiAllelicData & entry)
Update only the call and confidence for the given row
Parameters:
row The row index.
entry The new MultiData value.
Definition at line 196 of file CalvinCHPMultiDataFileUpdater.cpp.
References UpdateMultiData().
void affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetMultiAllelicData & entry, const std::vector< ColumnInfo > & metricColumns)
Update the entry for the given row
Parameters:
row The row index.
entry The new MultiData value.
metricColumns The column information.
void CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetCopyNumberData & entry)
Update only the call and confidence for the given row
Parameters:
row The row index.
entry The new MultiData value.
Definition at line 169 of file CalvinCHPMultiDataFileUpdater.cpp.
References UpdateMultiData().
void affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetCopyNumberData & entry, const std::vector< ColumnInfo > & metricColumns)
Update the entry for the given row
Parameters:
row The row index.
entry The new MultiData value.
metricColumns The column information.
void CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetBiAllelicData & entry)
Update only the call and confidence for the given row
Parameters:
row The row index.
entry The new MultiData value.
Definition at line 141 of file CalvinCHPMultiDataFileUpdater.cpp.
References UpdateMultiData().
void affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetBiAllelicData & entry, const std::vector< ColumnInfo > & metricColumns)
Update the entry for the given row
Parameters:
row The row index.
entry The new MultiData value.
metricColumns The column information.
void CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData & entry, const std::vector< ColumnInfo > & metricColumns)
Update the entry for the given row
Parameters:
row The row index.
entry The new MultiData value.
Definition at line 128 of file CalvinCHPMultiDataFileUpdater.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::confidenceScore, dataSetIndexMap, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::metrics, MULTI_DATA_DATA_GROUP, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::signal, affymetrix_calvin_io::DataSetUpdater::Update(), and UpdateMetrics().
void CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry)
Update only the call and confidence for the given row
Parameters:
row The row index.
entry The new MultiData value.
Definition at line 67 of file CalvinCHPMultiDataFileUpdater.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, dataSetIndexMap, MULTI_DATA_DATA_GROUP, and affymetrix_calvin_io::DataSetUpdater::Update().
void affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataExpressionData & entry, const std::vector< ColumnInfo > & metricColumns)
Update the entry for the given row
Parameters:
row The row index.
entry The new MultiData value.
metricColumns The column information.
void affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & entry, const std::vector< ColumnInfo > & metricColumns)
Update the entry for the given row
Parameters:
row The row index.
entry The new MultiData value.
void affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & entry, const std::vector< ColumnInfo > & metricColumns)
Update the entry for the given row
Parameters:
row The row index.
entry The new MultiData value.
metricColumns The column information.
void CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataExpressionData & entry)
Update only the call and confidence for the given row
Parameters:
row The row index.
entry The new MultiData value.
Definition at line 112 of file CalvinCHPMultiDataFileUpdater.cpp.
References dataSetIndexMap, MULTI_DATA_DATA_GROUP, affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::quantification, and affymetrix_calvin_io::DataSetUpdater::Update().
void affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMultiData (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry, const std::vector< ColumnInfo > & metricColumns)
Update the entry for the given row
Parameters:
row The row index.
entry The new MultiData value.
metricColumns The column information.
Referenced by UpdateMultiData().
Member Data Documentation
std::map<MultiDataType, int> affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::dataSetIndexMap [private]
Definition at line 144 of file CalvinCHPMultiDataFileUpdater.h.
Referenced by Initialize(), and UpdateMultiData().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPMultiDataFileUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPFileUpdater.cpp
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPMultiDataFileUpdater.cpp