Affymetrix Fusion SDK: LineFile Class Reference
LineFile Class Reference
Platform safe class for reading lines.
#include <LineFile.h>
Public Types
enum FileLineEnding { UNIX = 0, DOS = 1, MAC = 2, UNKNOWN = 3 }
Public Member Functions
LineFile ()
virtual ~LineFile ()
Destructor closes stream.
std::ifstream & open (const std::string &fileName, bool abortOnError=false)
Platform safe open for read, can be used multiple times with different file names.
void close ()
close the ifstream if needed.
bool getline (std::string &line, bool trim=false)
Platform safe reading of a line, stripping the eol. File is automatically closed when eof is reached.
enum FileLineEnding getFileType ()
What type of file is this one?
std::string getFileName ()
What is the name of the file we're reading from?
std::ifstream & getStream ()
get the input file stream.
bool is_open ()
bool fail ()
bool eof ()
Private Attributes
std::string m_fileName
std::ifstream m_fileStream
enum FileLineEnding m_endType
Detailed Description
Platform safe class for reading lines.
LineFile For Test Code ONLY. Chances are you should be using file/TsvFile/TsvFile and not this object. This file is intended for test code in util/ being used by file/TsvFile/TsvFile and other code not using TsvFile.
Definition at line 47 of file LineFile.h.
Member Enumeration Documentation
enum LineFile::FileLineEnding
Line endings are platform specific, this encodes different types we know of.
Enumerator:
UNIX
DOS
MAC
UNKNOWN
Definition at line 54 of file LineFile.h.
Constructor & Destructor Documentation
LineFile::LineFile ()
Constructor.
Definition at line 68 of file LineFile.cpp.
LineFile::~LineFile () [virtual]
Destructor closes stream.
Destructor.
Definition at line 73 of file LineFile.cpp.
References m_fileStream.
Member Function Documentation
void LineFile::close (void)
close the ifstream if needed.
Returns:
void
Close file streams.
Definition at line 109 of file LineFile.cpp.
References m_fileStream.
bool LineFile::eof () [inline]
Definition at line 124 of file LineFile.h.
References m_fileStream.
Referenced by TextFileCheck::check().
bool LineFile::fail () [inline]
Definition at line 121 of file LineFile.h.
References m_fileStream.
Referenced by TextFileCheck::check().
std::string LineFile::getFileName () [inline]
What is the name of the file we're reading from?
Returns:
name of file being read.
Definition at line 106 of file LineFile.h.
References m_fileName.
enum FileLineEnding LineFile::getFileType () [inline]
What type of file is this one?
Returns:
Type of file that has been determined.
Definition at line 98 of file LineFile.h.
References m_endType.
bool LineFile::getline (std::string & line, bool trim = false)
Platform safe reading of a line, stripping the eol. File is automatically closed when eof is reached.
Parameters:
line - returned if possible, cleared otherwise.
trim - false by default, true strips trailing spaces.
Returns:
true if line is returned. line will be cleared when false is returned. .
LineFile::getline
Read the next line if the stream is open. When eof is reached, close the file.
Returns:
- at EOF.
Definition at line 124 of file LineFile.cpp.
References DOS, m_endType, m_fileStream, MAC, and Util::trimString().
Referenced by TextFileCheck::check().
std::ifstream& LineFile::getStream () [inline]
get the input file stream.
Returns:
ifstream reference.
Definition at line 114 of file LineFile.h.
References m_fileStream.
bool LineFile::is_open () [inline]
Definition at line 118 of file LineFile.h.
References m_fileStream.
Referenced by TextFileCheck::check().
std::ifstream & LineFile::open (const std::string & fileName, bool abortOnError = false)
Platform safe open for read, can be used multiple times with different file names.
Returns:
ifstream in question.
Open file fileName or die trying.
Parameters:
char * fileName - full path of fileName to be opened.
Definition at line 84 of file LineFile.cpp.
References _determineLineEndingType(), Fs::aptOpen(), Err::errAbort(), FS_QUOTE_PATH, m_endType, m_fileName, and m_fileStream.
Referenced by TextFileCheck::check().
Member Data Documentation
enum FileLineEnding LineFile::m_endType [private]
Definition at line 132 of file LineFile.h.
Referenced by getFileType(), getline(), and open().
std::string LineFile::m_fileName [private]
Definition at line 130 of file LineFile.h.
Referenced by getFileName(), and open().
std::ifstream LineFile::m_fileStream [private]
Definition at line 131 of file LineFile.h.
Referenced by close(), eof(), fail(), getline(), getStream(), is_open(), open(), and ~LineFile().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/LineFile.h
C:/f112/affy/sdk/util/LineFile.cpp