Affymetrix Fusion SDK: affx::TsvFileField Class Reference
affx::TsvFileField Class Reference
#include <TsvFile.h>
Public Member Functions
TsvFileField ()
Creator of TsvFileField.
~TsvFileField ()
void init ()
Init the internal bookkeeping data. (Different than clear)
void clear ()
Clear the values of this feild.
bool isNull ()
Is the Column null?
bool isEmpty ()
int setBuffer (const std::string &str)
Set the buffer value of the column.
int setPrecision (int places)
void convertToString ()
std::string get_name ()
affx::tsv_type_t get_type ()
Return the expected type of the field.
int get_max_size ()
affx::tsv_type_t set_type (affx::tsv_type_t ctype)
Set the expected type of the field.
int get (std::string *val)
Get the value as a string.
int get (short *val)
Get the value as an int.
int get (int *val)
Get the value as an int.
int get (double *val)
Get the value as a double.
int get (float *val)
Get the value as a float.
int get (unsigned int *val)
Get the value as an unsigned int.
int get (uint64_t *val)
Get the value as an uint64_t.
int get (std::vector< int > *val, char sep=',')
int get (std::vector< float > *val, char sep=',')
int get (std::vector< double > *val, char sep=',')
int get (std::vector< std::string > *val, char sep=',')
int set (const std::string &val)
set the val
int set (int val)
set the val
int set (short val)
set the val
int set (double val)
set the val
int set (unsigned int val)
set the val
int set (uint64_t val)
set the val
int set (float val)
set the val
int set (const std::vector< std::string > &val, char sep=',')
int set (const std::vector< int > &val, char sep=',')
int set (const std::vector< float > &val, char sep=',')
int set (const std::vector< double > &val, char sep=',')
void linkedvars_assign (affx::TsvFile *tsvfile)
Assign each linked var a value.
void linkedvar_push (affx::TsvFileBinding *var)
Add the var to the collection of linked vars.
void linkedvars_clear ()
Clear the linkages to bound variables.
std::string get_bound_types_str ()
Public Attributes
int m_clvl
The indent level of the column.
int m_cidx
The column number of the column.
std::string m_cname
Column name. (Could be blank)
tsv_type_t m_ctype
bool m_optAutoDequote
Automatically strip quotes?
bool m_optAutoTrim
Automatically strip white space?
std::string m_buffer
Buffer space.
int m_interncache_size
std::vector< std::string > m_interncache_vec
int m_precision
the output precision
bool m_isnull
True if null.
bool m_ignore
If this column should be ignored.
int m_val_state
int m_value_int
The cached value.
bool m_value_int_done
Has this value been converted?
int m_value_int_rv
The return value for the conversion.
int m_max_size
double m_value_double
Cached "double" conversions.
bool m_value_double_done
same as int
int m_value_double_rv
same as int
unsigned int m_value_uint
Cached "unsigned int" conversions.
bool m_value_uint_done
same as int
int m_value_uint_rv
same as int
uint64_t m_value_ulonglong
Cached "uint64_t" conversions.
bool m_value_ulonglong_done
same as int
int m_value_ulonglong_rv
same as int
std::vector
< affx::TsvFileBinding * > m_linkedvar_vec
Linked bindings.
Detailed Description
TsvFileField holds the data read from a column. The data is read into a std::string buffer. Rather than resizing the buffer all the time, we try and fill it "in place". Most of the time the new value should be the same size as the old value. We store the clvl and cidx info in the Column as well. Saves having to search for it in the TsvFile object.
"cidx" is counted from *after* the leading tabs.
Definition at line 234 of file TsvFile.h.
Constructor & Destructor Documentation
affx::TsvFileField::TsvFileField ()
Creator of TsvFileField.
Returns:
A cleared object
Definition at line 339 of file TsvFile.cpp.
affx::TsvFileField::~TsvFileField ()
Definition at line 344 of file TsvFile.cpp.
Member Function Documentation
void affx::TsvFileField::clear ()
Clear the values of this feild.
Definition at line 366 of file TsvFile.cpp.
References TSV_DEFAULT_PRECISION, and affx::VALSTATE_STRING.
Referenced by check_empty(), check_field_convert(), and check_field_vec_convert().
void affx::TsvFileField::convertToString ()
Definition at line 459 of file TsvFile.cpp.
References ToStr(), TSV_ERR_ABORT, affx::VALSTATE_DOUBLE, affx::VALSTATE_INT, affx::VALSTATE_NONE, and affx::VALSTATE_STRING.
int affx::TsvFileField::get (float * val)
Get the value as a float.
Parameters:
val val to set
Returns:
tsv_error_t
Definition at line 605 of file TsvFile.cpp.
int affx::TsvFileField::get (unsigned int * val)
Get the value as an unsigned int.
Parameters:
val val to set
Returns:
tsv_error_t
Definition at line 623 of file TsvFile.cpp.
References affx::TSV_ERR_CONVERSION, TSV_NULL_RETURN, and affx::TSV_OK.
int affx::TsvFileField::get (uint64_t * val)
Get the value as an uint64_t.
Parameters:
val val to set
Returns:
tsv_error_t
Definition at line 653 of file TsvFile.cpp.
References affx::TSV_ERR_CONVERSION, TSV_NULL_RETURN, and affx::TSV_OK.
int affx::TsvFileField::get (std::vector< int > * val, char sep = ',')
Definition at line 714 of file TsvFile.cpp.
References TSV_SPLIT_VEC_BODY.
int affx::TsvFileField::get (std::vector< float > * val, char sep = ',')
Definition at line 721 of file TsvFile.cpp.
References TSV_SPLIT_VEC_BODY.
int affx::TsvFileField::get (std::vector< double > * val, char sep = ',')
Definition at line 728 of file TsvFile.cpp.
References TSV_SPLIT_VEC_BODY.
int affx::TsvFileField::get (std::vector< std::string > * val, char sep = ',')
Definition at line 736 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFileField::get (std::string * val)
Get the value as a string.
Parameters:
val val to set
Returns:
tsv_error_t
Definition at line 496 of file TsvFile.cpp.
References TSV_NULL_RETURN, affx::TSV_OK, and affx::VALSTATE_STRING.
Referenced by check_field_convert(), check_field_vec_convert(), and affx::TsvFileIndex::data_add().
int affx::TsvFileField::get (short * val)
Get the value as an int.
Parameters:
val val to set
Returns:
tsv_error_t
Definition at line 514 of file TsvFile.cpp.
References affx::TSV_ERR_CONVERSION, and affx::TSV_OK.
int affx::TsvFileField::get (int * val)
Get the value as an int.
Parameters:
val val to set
Returns:
tsv_error_t
Todo:
: "" should be an error?
Definition at line 539 of file TsvFile.cpp.
References affx::TSV_ERR_CONVERSION, TSV_NULL_RETURN, and affx::TSV_OK.
int affx::TsvFileField::get (double * val)
Get the value as a double.
Parameters:
val val to set
Returns:
tsv_error_t
Definition at line 574 of file TsvFile.cpp.
References affx::TSV_ERR_CONVERSION, TSV_NULL_RETURN, and affx::TSV_OK.
std::string affx::TsvFileField::get_bound_types_str ()
Definition at line 960 of file TsvFile.cpp.
References affx::TsvFileBinding::m_ptr_double, affx::TsvFileBinding::m_ptr_float, affx::TsvFileBinding::m_ptr_int, affx::TsvFileBinding::m_ptr_string, affx::TsvFileBinding::m_ptr_uint, and affx::TsvFileBinding::m_ptr_ulonglong.
int affx::TsvFileField::get_max_size ()
Definition at line 402 of file TsvFile.cpp.
std::string affx::TsvFileField::get_name ()
Definition at line 390 of file TsvFile.cpp.
affx::tsv_type_t affx::TsvFileField::get_type ()
Return the expected type of the field.
Returns:
Definition at line 397 of file TsvFile.cpp.
Referenced by affx::TsvFile::get_type().
void affx::TsvFileField::init ()
Init the internal bookkeeping data. (Different than clear)
Definition at line 351 of file TsvFile.cpp.
References affx::TSV_TYPE_UNKNOWN.
bool affx::TsvFileField::isEmpty ()
Definition at line 424 of file TsvFile.cpp.
Referenced by check_empty(), and affx::TsvFile::isEmpty().
bool affx::TsvFileField::isNull ()
Is the Column null?
Returns:
true if it is null
Definition at line 418 of file TsvFile.cpp.
Referenced by check_empty(), and affx::TsvFile::isNull().
void affx::TsvFileField::linkedvar_push (affx::TsvFileBinding * var)
Add the var to the collection of linked vars.
Parameters:
var var to add
Definition at line 902 of file TsvFile.cpp.
Referenced by affx::TsvFile::linkvar_column().
void affx::TsvFileField::linkedvars_assign (affx::TsvFile * tsvfile)
Assign each linked var a value.
Definition at line 914 of file TsvFile.cpp.
References affx::TsvFileBinding::get_type_str(), affx::TsvFile::lineNumber(), affx::TsvFile::m_fileName, affx::TsvFileBinding::m_flags, affx::TsvFileBinding::m_ptr_double, affx::TsvFileBinding::m_ptr_float, affx::TsvFileBinding::m_ptr_int, affx::TsvFileBinding::m_ptr_string, affx::TsvFileBinding::m_ptr_uint, affx::TsvFileBinding::m_ptr_ulonglong, ToStr(), affx::TSV_BIND_REQUIRED, TSV_ERR_ABORT, and affx::TSV_OK.
void affx::TsvFileField::linkedvars_clear ()
Clear the linkages to bound variables.
Definition at line 908 of file TsvFile.cpp.
int affx::TsvFileField::set (uint64_t val)
set the val
set the value of the buffer
Parameters:
val the new value
Returns:
tsv_return_t
Todo:
dont use ostringstream, use something faster
Definition at line 889 of file TsvFile.cpp.
int affx::TsvFileField::set (short val)
set the val
int affx::TsvFileField::set (float val)
set the val
set the value of the buffer
Parameters:
val the new value
Returns:
tsv_return_t
Todo:
dont use ostringstream, use something faster
Definition at line 847 of file TsvFile.cpp.
References affx::TSV_OK, and affx::VALSTATE_DOUBLE.
int affx::TsvFileField::set (const std::vector< std::string > & val, char sep = ',')
Definition at line 780 of file TsvFile.cpp.
References TSV_CONCAT_VEC_BODY.
int affx::TsvFileField::set (const std::vector< float > & val, char sep = ',')
Definition at line 792 of file TsvFile.cpp.
References TSV_CONCAT_VEC_BODY.
int affx::TsvFileField::set (const std::vector< double > & val, char sep = ',')
Definition at line 800 of file TsvFile.cpp.
References TSV_CONCAT_VEC_BODY.
int affx::TsvFileField::set (const std::string & val)
set the val
set the value of the buffer
Parameters:
val the new string value
Returns:
tsv_return_t
Definition at line 816 of file TsvFile.cpp.
Referenced by check_field_vec_convert().
int affx::TsvFileField::set (const std::vector< int > & val, char sep = ',')
Definition at line 786 of file TsvFile.cpp.
References TSV_CONCAT_VEC_BODY.
int affx::TsvFileField::set (unsigned int val)
set the val
set the value of the buffer
Parameters:
val the new value
Returns:
tsv_return_t
Todo:
dont use ostringstream, use something faster
Definition at line 877 of file TsvFile.cpp.
int affx::TsvFileField::set (int val)
set the val
set the value of the buffer
Parameters:
val the new value
Returns:
tsv_return_t
Todo:
dont use ostringstream, use something faster
Definition at line 825 of file TsvFile.cpp.
References affx::TSV_OK, and affx::VALSTATE_INT.
int affx::TsvFileField::set (double val)
set the val
set the value of the buffer
Parameters:
val the new value
Returns:
tsv_return_t
Todo:
dont use ostringstream, use something faster
Definition at line 861 of file TsvFile.cpp.
References affx::TSV_OK, and affx::VALSTATE_DOUBLE.
affx::tsv_type_t affx::TsvFileField::set_type (affx::tsv_type_t ctype)
Set the expected type of the field.
Parameters:
type
Returns:
Definition at line 410 of file TsvFile.cpp.
Referenced by affx::TsvFile::set_type().
int affx::TsvFileField::setBuffer (const std::string & str)
Set the buffer value of the column.
Parameters:
str The new value
Definition at line 435 of file TsvFile.cpp.
References affx::TSV_OK, and affx::VALSTATE_STRING.
Referenced by check_empty(), check_field_convert(), and check_field_vec_convert().
int affx::TsvFileField::setPrecision (int places)
Definition at line 452 of file TsvFile.cpp.
References affx::TSV_OK.
Referenced by check_field_vec_convert(), and affx::TsvFile::setPrecision().
Member Data Documentation
std::string affx::TsvFileField::m_buffer
Buffer space.
Definition at line 242 of file TsvFile.h.
Referenced by check_field_vec_convert(), affx::TsvFileIndex::data_add(), affx::TsvFile::deduce_sizes(), affx::TsvFile::f_read_column(), and affx::TsvFile::writeLevel().
int affx::TsvFileField::m_cidx
The column number of the column.
Definition at line 237 of file TsvFile.h.
int affx::TsvFileField::m_clvl
The indent level of the column.
Definition at line 236 of file TsvFile.h.
std::string affx::TsvFileField::m_cname
Column name. (Could be blank)
Definition at line 238 of file TsvFile.h.
Referenced by affx::TsvFile::cidx2cname().
tsv_type_t affx::TsvFileField::m_ctype
Definition at line 239 of file TsvFile.h.
bool affx::TsvFileField::m_ignore
If this column should be ignored.
Definition at line 252 of file TsvFile.h.
int affx::TsvFileField::m_interncache_size
Definition at line 245 of file TsvFile.h.
std::vector<std::string> affx::TsvFileField::m_interncache_vec
Definition at line 246 of file TsvFile.h.
bool affx::TsvFileField::m_isnull
True if null.
Definition at line 251 of file TsvFile.h.
Referenced by affx::TsvFile::f_read_column().
std::vector<affx::TsvFileBinding*> affx::TsvFileField::m_linkedvar_vec
Linked bindings.
Definition at line 279 of file TsvFile.h.
int affx::TsvFileField::m_max_size
Definition at line 262 of file TsvFile.h.
Referenced by affx::TsvFile::deduce_sizes().
bool affx::TsvFileField::m_optAutoDequote
Automatically strip quotes?
Definition at line 240 of file TsvFile.h.
Referenced by affx::TsvFile::f_read_column().
bool affx::TsvFileField::m_optAutoTrim
Automatically strip white space?
Definition at line 241 of file TsvFile.h.
int affx::TsvFileField::m_precision
the output precision
Definition at line 248 of file TsvFile.h.
Referenced by affx::TsvFile::writeLevel().
int affx::TsvFileField::m_val_state
Definition at line 254 of file TsvFile.h.
Referenced by affx::TsvFile::writeLevel().
double affx::TsvFileField::m_value_double
Cached "double" conversions.
same as int
Definition at line 265 of file TsvFile.h.
Referenced by affx::TsvFile::writeLevel().
bool affx::TsvFileField::m_value_double_done
same as int
Definition at line 266 of file TsvFile.h.
Referenced by affx::TsvFile::f_read_column().
int affx::TsvFileField::m_value_double_rv
same as int
Definition at line 267 of file TsvFile.h.
int affx::TsvFileField::m_value_int
The cached value.
Definition at line 257 of file TsvFile.h.
Referenced by affx::TsvFile::writeLevel().
bool affx::TsvFileField::m_value_int_done
Has this value been converted?
Definition at line 258 of file TsvFile.h.
Referenced by affx::TsvFile::f_read_column().
int affx::TsvFileField::m_value_int_rv
The return value for the conversion.
Definition at line 259 of file TsvFile.h.
unsigned int affx::TsvFileField::m_value_uint
Cached "unsigned int" conversions.
same as int
Definition at line 270 of file TsvFile.h.
bool affx::TsvFileField::m_value_uint_done
same as int
Definition at line 271 of file TsvFile.h.
Referenced by affx::TsvFile::f_read_column().
int affx::TsvFileField::m_value_uint_rv
same as int
Definition at line 272 of file TsvFile.h.
uint64_t affx::TsvFileField::m_value_ulonglong
Cached "uint64_t" conversions.
same as int
Definition at line 275 of file TsvFile.h.
bool affx::TsvFileField::m_value_ulonglong_done
same as int
Definition at line 276 of file TsvFile.h.
Referenced by affx::TsvFile::f_read_column().
int affx::TsvFileField::m_value_ulonglong_rv
same as int
Definition at line 277 of file TsvFile.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/TsvFile.h
C:/f112/affy/sdk/file/TsvFile/TsvFile.cpp