Affymetrix Fusion SDK: affymetrix_calvin_io::CHPQuantificationFileReader Class Reference
affymetrix_calvin_io::CHPQuantificationFileReader Class Reference
#include <CHPQuantificationFileReader.h>
Public Member Functions
CHPQuantificationFileReader ()
~CHPQuantificationFileReader ()
const std::string GetFilename () const
void SetFilename (const std::string &name)
void Read (CHPQuantificationData &data)
Protected Attributes
std::string fileName
Detailed Description
This class reads a Signal CHP data file. It is an interpreter class.
Definition at line 38 of file CHPQuantificationFileReader.h.
Constructor & Destructor Documentation
CHPQuantificationFileReader::CHPQuantificationFileReader ()
Constructor
Definition at line 33 of file CHPQuantificationFileReader.cpp.
CHPQuantificationFileReader::~CHPQuantificationFileReader ()
Destructor
Definition at line 40 of file CHPQuantificationFileReader.cpp.
Member Function Documentation
const std::string affymetrix_calvin_io::CHPQuantificationFileReader::GetFilename () const [inline]
Gets the name of the input file.
Returns:
The name of the file to read.
Definition at line 52 of file CHPQuantificationFileReader.h.
References fileName.
void CHPQuantificationFileReader::Read (CHPQuantificationData & data)
Reads the file header of the generic file and reads all the DataPlaneHeader information.
Parameters:
data A reference to a GenericData object that will receive information from the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 44 of file CHPQuantificationFileReader.cpp.
References affymetrix_calvin_io::CHPQuantificationData::Clear(), affymetrix_calvin_io::CHPQuantificationData::GetFilename(), affymetrix_calvin_io::CHPQuantificationData::GetGenericData(), affymetrix_calvin_io::GenericFileReader::ReadHeader(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
Referenced by CalvinChpCheck::check(), and affymetrix_fusion_io::FusionCHPQuantificationData::Read().
void affymetrix_calvin_io::CHPQuantificationFileReader::SetFilename (const std::string & name) [inline]
Sets the name of the input file.
Parameters:
name The name of the file to read.
Definition at line 58 of file CHPQuantificationFileReader.h.
References fileName.
Referenced by CalvinChpCheck::check(), and affymetrix_fusion_io::FusionCHPQuantificationData::Read().
Member Data Documentation
std::string affymetrix_calvin_io::CHPQuantificationFileReader::fileName [protected]
Name of the file to read
Definition at line 71 of file CHPQuantificationFileReader.h.
Referenced by GetFilename(), and SetFilename().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/CHPQuantificationFileReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/CHPQuantificationFileReader.cpp