Affymetrix Fusion SDK: affxcms::CCMSFileHeader Class Reference
affxcms::CCMSFileHeader Class Reference
#include <CMSFileData.h>
Public Member Functions
int GetVersion () const
int GetArrayCount () const
int GetSNPCount () const
std::string GetAssay () const
void SetVersion (int value)
void SetArrayCount (int value)
void SetSNPCount (int value)
void SetAssay (const char *value)
CCMSFileHeader ()
Protected Attributes
int m_nVersion
int m_nArrayCount
int m_nSNPCount
std::string m_strAssay
Detailed Description
Definition at line 79 of file CMSFileData.h.
Constructor & Destructor Documentation
CCMSFileHeader::CCMSFileHeader ()
Definition at line 39 of file CMSFileData.cpp.
Member Function Documentation
int affxcms::CCMSFileHeader::GetArrayCount () const [inline]
Definition at line 91 of file CMSFileData.h.
References m_nArrayCount.
std::string affxcms::CCMSFileHeader::GetAssay () const [inline]
Definition at line 93 of file CMSFileData.h.
References m_strAssay.
int affxcms::CCMSFileHeader::GetSNPCount () const [inline]
Definition at line 92 of file CMSFileData.h.
References m_nSNPCount.
Referenced by affxcms::CCMSFileData::ReadFile().
int affxcms::CCMSFileHeader::GetVersion () const [inline]
Definition at line 90 of file CMSFileData.h.
References m_nVersion.
void affxcms::CCMSFileHeader::SetArrayCount (int value) [inline]
Definition at line 97 of file CMSFileData.h.
References m_nArrayCount.
Referenced by affxcms::CCMSFileData::ReadFile().
void affxcms::CCMSFileHeader::SetAssay (const char * value) [inline]
Definition at line 99 of file CMSFileData.h.
References m_strAssay.
Referenced by affxcms::CCMSFileData::ReadFile().
void affxcms::CCMSFileHeader::SetSNPCount (int value) [inline]
Definition at line 98 of file CMSFileData.h.
References m_nSNPCount.
Referenced by affxcms::CCMSFileData::ReadFile().
void affxcms::CCMSFileHeader::SetVersion (int value) [inline]
Definition at line 96 of file CMSFileData.h.
References m_nVersion.
Referenced by affxcms::CCMSFileData::ReadFile().
Member Data Documentation
int affxcms::CCMSFileHeader::m_nArrayCount [protected]
Definition at line 83 of file CMSFileData.h.
Referenced by GetArrayCount(), and SetArrayCount().
int affxcms::CCMSFileHeader::m_nSNPCount [protected]
Definition at line 84 of file CMSFileData.h.
Referenced by GetSNPCount(), and SetSNPCount().
int affxcms::CCMSFileHeader::m_nVersion [protected]
Definition at line 82 of file CMSFileData.h.
Referenced by GetVersion(), and SetVersion().
std::string affxcms::CCMSFileHeader::m_strAssay [protected]
Definition at line 85 of file CMSFileData.h.
Referenced by GetAssay(), and SetAssay().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CMSFileData.h
C:/f112/affy/sdk/file/CMSFileData.cpp