Affymetrix Fusion SDK: CFGridCoordsCOM Class Reference
CFGridCoordsCOM Class Reference
#include <FGridCoordsCOM.h>
Public Member Functions
CFGridCoordsCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
void SetGrid (affymetrix_fusion_io::FGridCoords &g)
STDMETHOD() get_upperleft (IFPoint **pVal)
STDMETHOD() get_upperright (IFPoint **pVal)
STDMETHOD() get_lowerright (IFPoint **pVal)
STDMETHOD() get_lowerleft (IFPoint **pVal)
Private Attributes
affymetrix_fusion_io::FGridCoords grid
Detailed Description
Definition at line 30 of file FGridCoordsCOM.h.
Constructor & Destructor Documentation
CFGridCoordsCOM::CFGridCoordsCOM () [inline]
Definition at line 37 of file FGridCoordsCOM.h.
Member Function Documentation
HRESULT CFGridCoordsCOM::FinalConstruct () [inline]
Definition at line 56 of file FGridCoordsCOM.h.
void CFGridCoordsCOM::FinalRelease () [inline]
Definition at line 61 of file FGridCoordsCOM.h.
STDMETHODIMP CFGridCoordsCOM::get_lowerleft (IFPoint ** pVal)
Definition at line 72 of file FGridCoordsCOM.cpp.
References grid, affymetrix_fusion_io::FGridCoords::lowerleft, and CFPointCOM::SetPoint().
STDMETHODIMP CFGridCoordsCOM::get_lowerright (IFPoint ** pVal)
Definition at line 62 of file FGridCoordsCOM.cpp.
References grid, affymetrix_fusion_io::FGridCoords::lowerright, and CFPointCOM::SetPoint().
STDMETHODIMP CFGridCoordsCOM::get_upperleft (IFPoint ** pVal)
Definition at line 42 of file FGridCoordsCOM.cpp.
References grid, CFPointCOM::SetPoint(), and affymetrix_fusion_io::FGridCoords::upperleft.
STDMETHODIMP CFGridCoordsCOM::get_upperright (IFPoint ** pVal)
Definition at line 52 of file FGridCoordsCOM.cpp.
References grid, CFPointCOM::SetPoint(), and affymetrix_fusion_io::FGridCoords::upperright.
STDMETHODIMP CFGridCoordsCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 27 of file FGridCoordsCOM.cpp.
void CFGridCoordsCOM::SetGrid (affymetrix_fusion_io::FGridCoords & g) [inline]
Definition at line 69 of file FGridCoordsCOM.h.
Referenced by CFusionCELDataCOM::GetGridCorners().
Member Data Documentation
affymetrix_fusion_io::FGridCoords CFGridCoordsCOM::grid [private]
Definition at line 66 of file FGridCoordsCOM.h.
Referenced by get_lowerleft(), get_lowerright(), get_upperleft(), and get_upperright().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FGridCoordsCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FGridCoordsCOM.cpp