Affymetrix Fusion SDK: CalvinParameter Class Reference
CalvinParameter Class Reference
#include <Calvin.h>
Classes
struct ComparePred
struct ComparePred< 0 >
Public Member Functions
CalvinParameter ()
CalvinParameter (const AffxString &strName, CalvinValue::ParameterType eParameterType, const AffxString &strValue)
void set (const AffxString &strName, CalvinValue::ParameterType eParameterType, const AffxString &strValue)
AffxString & getName ()
void clear ()
int compareTo (CalvinParameter &that, int iCompareCode)
Protected Attributes
AffxString m_strName
Detailed Description
Definition at line 106 of file Calvin.h.
Constructor & Destructor Documentation
CalvinParameter::CalvinParameter () [inline]
Definition at line 112 of file Calvin.h.
CalvinParameter::CalvinParameter (const AffxString & strName, CalvinValue::ParameterType eParameterType, const AffxString & strValue) [inline]
Definition at line 116 of file Calvin.h.
References m_strName.
Member Function Documentation
void CalvinParameter::clear () [inline]
Reimplemented from CalvinValue.
Definition at line 130 of file Calvin.h.
References m_strName.
int CalvinParameter::compareTo (CalvinParameter & that, int iCompareCode) [inline]
Compare function.
Parameters:
that - A reference to an instance of this class.
iCompareCode - The code to switch on when doing compares. (Each code is a different compare.)
Returns:
- int value. (-1 if *this < that, 0 if *this == that, 1 if *this > that)
Definition at line 138 of file Calvin.h.
References AffxString::compareTo(), and m_strName.
AffxString& CalvinParameter::getName () [inline]
Definition at line 128 of file Calvin.h.
References m_strName.
Referenced by Calvin::equivalentHeader(), and Calvin::equivalentParameter().
void CalvinParameter::set (const AffxString & strName, CalvinValue::ParameterType eParameterType, const AffxString & strValue) [inline]
Definition at line 121 of file Calvin.h.
References CalvinValue::m_eParameterType, m_strName, and CalvinValue::m_strValue.
Referenced by Calvin::equivalentHeader().
Member Data Documentation
AffxString CalvinParameter::m_strName [protected]
Definition at line 109 of file Calvin.h.
Referenced by CalvinParameter(), clear(), compareTo(), getName(), CalvinParameter::ComparePred< 0 >::operator()(), and set().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/calvin_files/utils/src/Calvin.h