Affymetrix Fusion SDK: affymetrix_calvin_io::DataGroupWriter Class Reference
affymetrix_calvin_io::DataGroupWriter Class Reference
#include <DataGroupWriter.h>
Public Member Functions
DataGroupWriter (std::ofstream *o, DataGroupHeader *p)
~DataGroupWriter ()
std::wstring GetName ()
void WriteHeader ()
void Close () const
void GetDataSetWriters (DataSetWriterIt &begin, DataSetWriterIt &end)
DataSetWriter & GetDataSetWriter (int32_t index)
int32_t GetDataSetWriterCnt () const
std::wstring GetDataGroupName () const
DataSetWriter * CreateDataSetWriter (DataSetHeader &hdr)
void UpdateNextDataGroupPos () const
Private Member Functions
void CreateWriters ()
Private Attributes
std::ofstream * os
DataGroupHeader * dataGroupHdr
DataGroupHeaderWriter dataGroupHdrWriter
DataSetWriterVector writers
Detailed Description
Definition at line 35 of file DataGroupWriter.h.
Constructor & Destructor Documentation
DataGroupWriter::DataGroupWriter (std::ofstream * o, DataGroupHeader * p)
Definition at line 27 of file DataGroupWriter.cpp.
References CreateWriters(), dataGroupHdr, and os.
DataGroupWriter::~DataGroupWriter ()
Definition at line 33 of file DataGroupWriter.cpp.
References writers.
Member Function Documentation
void DataGroupWriter::Close (void) const
Definition at line 50 of file DataGroupWriter.cpp.
References dataGroupHdrWriter, os, and affymetrix_calvin_io::DataGroupHeaderWriter::UpdateNextDataGroupPos().
Referenced by affymetrix_calvin_io::CDFFileWriter::CloseDataGroup(), affymetrix_calvin_io::CDFCntrlFileWriter::CloseDataGroup(), and OutputMessageStream::Write().
DataSetWriter * DataGroupWriter::CreateDataSetWriter (DataSetHeader & hdr)
Definition at line 83 of file DataGroupWriter.cpp.
References os.
Referenced by AddDataSetHeaderToGroup(), affymetrix_calvin_io::CDFFileWriter::CreateProbeSetWriter(), CreateWriters(), affymetrix_calvin_io::CDFCntrlFileWriter::GetCntrlProbeSetWriter(), affymetrix_calvin_io::GenericFileUpdater::GetUpdateDataSetWriter(), affymetrix_calvin_io::DATFileUpdater::WriteGridData(), and affymetrix_calvin_io::DATFileUpdater::WriteSubGridData().
void DataGroupWriter::CreateWriters () [private]
Definition at line 72 of file DataGroupWriter.cpp.
References CreateDataSetWriter(), dataGroupHdr, affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), and writers.
Referenced by DataGroupWriter().
std::wstring DataGroupWriter::GetDataGroupName () const
Definition at line 88 of file DataGroupWriter.cpp.
References dataGroupHdr, and affymetrix_calvin_io::DataGroupHeader::GetName().
DataSetWriter & DataGroupWriter::GetDataSetWriter (int32_t index)
Definition at line 62 of file DataGroupWriter.cpp.
References writers.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::CHPTilingFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPQuantificationFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPMultiDataFileWriter::SeekToDataSet(), OutputMessageStream::Write(), affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroup(), affymetrix_calvin_io::CDFFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteHeaders(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteHeaders().
int32_t DataGroupWriter::GetDataSetWriterCnt () const
Definition at line 67 of file DataGroupWriter.cpp.
References writers.
Referenced by affymetrix_calvin_io::CHPMultiDataFileWriter::WriteHeaders().
void DataGroupWriter::GetDataSetWriters (DataSetWriterIt & begin, DataSetWriterIt & end)
Definition at line 56 of file DataGroupWriter.cpp.
References writers.
Referenced by affymetrix_calvin_io::FileHeaderUpdater::AppendDataGroupHeader(), affymetrix_calvin_io::DATFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPTilingFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPFileWriter::WriteHeaders(), and affymetrix_calvin_io::CelFileWriter::WriteHeaders().
std::wstring DataGroupWriter::GetName ()
Definition at line 38 of file DataGroupWriter.cpp.
References dataGroupHdr, and affymetrix_calvin_io::DataGroupHeader::GetName().
void DataGroupWriter::UpdateNextDataGroupPos () const
Definition at line 93 of file DataGroupWriter.cpp.
References dataGroupHdrWriter, os, and affymetrix_calvin_io::DataGroupHeaderWriter::UpdateNextDataGroupPos().
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::CDFCntrlFileWriter::CDFCntrlFileWriter(), affymetrix_calvin_io::CDFFileWriter::CDFFileWriter(), affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroup(), affymetrix_calvin_io::CHPTilingFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPMultiDataFileWriter::WriteHeaders(), and affymetrix_calvin_io::CHPFileWriter::WriteHeaders().
void DataGroupWriter::WriteHeader ()
Definition at line 43 of file DataGroupWriter.cpp.
References dataGroupHdr, dataGroupHdrWriter, os, affymetrix_calvin_io::DataGroupHeaderWriter::UpdateDataSetPos(), and affymetrix_calvin_io::DataGroupHeaderWriter::Write().
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::FileHeaderUpdater::AppendDataGroupHeader(), affymetrix_calvin_io::CDFFileWriter::OpenDataGroup(), affymetrix_calvin_io::CDFCntrlFileWriter::OpenDataGroup(), OutputMessageStream::Write(), affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroup(), affymetrix_calvin_io::DATFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPTilingFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPMultiDataFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPFileWriter::WriteHeaders(), and affymetrix_calvin_io::CelFileWriter::WriteHeaders().
Member Data Documentation
DataGroupHeader* affymetrix_calvin_io::DataGroupWriter::dataGroupHdr [private]
Definition at line 40 of file DataGroupWriter.h.
Referenced by CreateWriters(), DataGroupWriter(), GetDataGroupName(), GetName(), and WriteHeader().
DataGroupHeaderWriter affymetrix_calvin_io::DataGroupWriter::dataGroupHdrWriter [private]
Definition at line 41 of file DataGroupWriter.h.
Referenced by Close(), UpdateNextDataGroupPos(), and WriteHeader().
std::ofstream* affymetrix_calvin_io::DataGroupWriter::os [private]
Definition at line 39 of file DataGroupWriter.h.
Referenced by Close(), CreateDataSetWriter(), DataGroupWriter(), UpdateNextDataGroupPos(), and WriteHeader().
DataSetWriterVector affymetrix_calvin_io::DataGroupWriter::writers [private]
Definition at line 42 of file DataGroupWriter.h.
Referenced by CreateWriters(), GetDataSetWriter(), GetDataSetWriterCnt(), GetDataSetWriters(), and ~DataGroupWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DataGroupWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/DataGroupWriter.cpp