Affymetrix Fusion SDK: FrugalVector< T > Class Template Reference
FrugalVector< T > Class Template Reference
#include <FrugalVector.h>
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef size_t size_type
typedef T * iterator
typedef const T * const_iterator
typedef FrugalVector< T > vector_type
Public Member Functions
FrugalVector (size_type n, const value_type &val)
FrugalVector (size_type n)
FrugalVector ()
~FrugalVector ()
T * begin ()
T * end ()
const T * begin () const
const T * end () const
reference operator[] (size_type n)
const_reference operator[] (size_type n) const
void resize (size_type n, const T &t)
void resize (size_type n)
void clear ()
void push_back (const value_type &t)
size_type capacity () const
bool empty () const
size_type size () const
Public Attributes
T * m_Start
T * m_End
Detailed Description
template<typename T>
class FrugalVector< T >
Definition at line 28 of file FrugalVector.h.
Member Typedef Documentation
template<typename T > typedef const T* FrugalVector< T >::const_iterator
Definition at line 38 of file FrugalVector.h.
template<typename T > typedef const T* FrugalVector< T >::const_pointer
Definition at line 33 of file FrugalVector.h.
template<typename T > typedef const T& FrugalVector< T >::const_reference
Definition at line 35 of file FrugalVector.h.
template<typename T > typedef T* FrugalVector< T >::iterator
Definition at line 37 of file FrugalVector.h.
template<typename T > typedef T* FrugalVector< T >::pointer
Definition at line 32 of file FrugalVector.h.
template<typename T > typedef T& FrugalVector< T >::reference
Definition at line 34 of file FrugalVector.h.
template<typename T > typedef size_t FrugalVector< T >::size_type
Definition at line 36 of file FrugalVector.h.
template<typename T > typedef T FrugalVector< T >::value_type
Definition at line 31 of file FrugalVector.h.
template<typename T > typedef FrugalVector<T> FrugalVector< T >::vector_type
Definition at line 39 of file FrugalVector.h.
Constructor & Destructor Documentation
template<typename T > FrugalVector< T >::FrugalVector (size_type n, const value_type & val) [inline]
Definition at line 44 of file FrugalVector.h.
References FrugalVector< T >::m_End, and FrugalVector< T >::m_Start.
template<typename T > FrugalVector< T >::FrugalVector (size_type n) [inline]
Definition at line 50 of file FrugalVector.h.
References FrugalVector< T >::m_End, and FrugalVector< T >::m_Start.
template<typename T > FrugalVector< T >::FrugalVector () [inline]
Definition at line 55 of file FrugalVector.h.
References FrugalVector< T >::m_End, and FrugalVector< T >::m_Start.
template<typename T > FrugalVector< T >::~FrugalVector () [inline]
Definition at line 59 of file FrugalVector.h.
References FrugalVector< T >::m_Start.
Member Function Documentation
template<typename T > T* FrugalVector< T >::begin () [inline]
Definition at line 63 of file FrugalVector.h.
References FrugalVector< T >::m_Start.
Referenced by FrugalVector< T >::operator[]().
template<typename T > const T* FrugalVector< T >::begin () const [inline]
Definition at line 66 of file FrugalVector.h.
References FrugalVector< T >::m_Start.
template<typename T > size_type FrugalVector< T >::capacity () const [inline]
Definition at line 108 of file FrugalVector.h.
References FrugalVector< T >::m_End, and FrugalVector< T >::m_Start.
template<typename T > void FrugalVector< T >::clear (void) [inline]
Definition at line 98 of file FrugalVector.h.
References FreezArray(), FrugalVector< T >::m_End, and FrugalVector< T >::m_Start.
Referenced by FrugalVector< T >::resize().
template<typename T > bool FrugalVector< T >::empty (void) const [inline]
Definition at line 110 of file FrugalVector.h.
References FrugalVector< T >::m_End, and FrugalVector< T >::m_Start.
template<typename T > T* FrugalVector< T >::end () [inline]
Definition at line 64 of file FrugalVector.h.
References FrugalVector< T >::m_End.
template<typename T > const T* FrugalVector< T >::end () const [inline]
Definition at line 67 of file FrugalVector.h.
References FrugalVector< T >::m_End.
template<typename T > reference FrugalVector< T >::operator[] (size_type n) [inline]
Definition at line 70 of file FrugalVector.h.
References FrugalVector< T >::begin().
template<typename T > const_reference FrugalVector< T >::operator[] (size_type n) const [inline]
Definition at line 73 of file FrugalVector.h.
References FrugalVector< T >::begin().
template<typename T > void FrugalVector< T >::push_back (const value_type & t) [inline]
Definition at line 103 of file FrugalVector.h.
References FrugalVector< T >::m_End, FrugalVector< T >::resize(), and FrugalVector< T >::size().
template<typename T > void FrugalVector< T >::resize (size_type n) [inline]
Definition at line 96 of file FrugalVector.h.
References FrugalVector< T >::resize().
Referenced by FrugalVector< T >::resize().
template<typename T > void FrugalVector< T >::resize (size_type n, const T & t) [inline]
Definition at line 75 of file FrugalVector.h.
References FrugalVector< T >::clear(), FrugalVector< T >::m_End, FrugalVector< T >::m_Start, and FrugalVector< T >::size().
Referenced by FrugalVector< T >::push_back().
template<typename T > size_type FrugalVector< T >::size () const [inline]
Definition at line 112 of file FrugalVector.h.
References FrugalVector< T >::m_End, and FrugalVector< T >::m_Start.
Referenced by FrugalVector< T >::push_back(), and FrugalVector< T >::resize().
Member Data Documentation
template<typename T > T* FrugalVector< T >::m_End
Definition at line 42 of file FrugalVector.h.
Referenced by FrugalVector< T >::capacity(), FrugalVector< T >::clear(), FrugalVector< T >::empty(), FrugalVector< T >::end(), FrugalVector< T >::FrugalVector(), FrugalVector< T >::push_back(), FrugalVector< T >::resize(), and FrugalVector< T >::size().
template<typename T > T* FrugalVector< T >::m_Start
Definition at line 41 of file FrugalVector.h.
Referenced by FrugalVector< T >::begin(), FrugalVector< T >::capacity(), FrugalVector< T >::clear(), FrugalVector< T >::empty(), FrugalVector< T >::FrugalVector(), FrugalVector< T >::resize(), FrugalVector< T >::size(), and FrugalVector< T >::~FrugalVector().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/FrugalVector.h