Affymetrix Fusion SDK: AffxString Class Reference
AffxString Class Reference
A class derived from std::string.
#include <AffxString.h>
Classes
struct ComparePred
struct ComparePred< 0 >
Public Member Functions
AffxString ()
AffxString (const std::string &stringSrc)
AffxString (const AffxString &stringSrc)
AffxString (char ch, int nRepeat=1)
AffxString (const char *psz)
AffxString (const char *pch, int nLength)
bool isTab (int nIndex) const
bool isWhiteSpace (int nIndex) const
bool isAlphabetic (int nIndex) const
bool isAlphanumeric (int nIndex) const
bool isBlank (int nIndex) const
bool isPunctuation (int nIndex) const
bool isUppercase (int nIndex) const
bool isLowercase (int nIndex) const
bool isNumeric (int nIndex) const
bool isHexNumeric (int nIndex) const
AffxString getKey ()
AffxString getValue ()
AffxString removeCruft ()
void toUpper (int nIndex)
void toLower (int nIndex)
void expandTabs (int nTabSize=8)
unsigned int getLength () const
AffxString mid (int iStartIndex, int iLength) const
void stripTrailingBlanks ()
void stripPrecedingBlanks ()
void stripTrailingCharacters (char cChar)
void stripPrecedingCharacters (char cChar)
void padBlanks (short nMax)
bool isBlank ()
bool isBlankOrEmpty ()
bool isNumber ()
int printf (const char *pszFormat,...)
int sprintf (const char *pszFormat,...)
void stripAndPad (int iLength)
void strip (void)
AffxString & trim ()
void zeroFill (int i, int iLength)
void setAt (unsigned int iIndex, char c)
char getAt (unsigned int iIndex) const
char charAt (unsigned int iIndex) const
AffxString & toLowerCase ()
AffxString & toUpperCase ()
AffxString substring (unsigned int iIndex) const
AffxString & replace (char cOld, char cNew)
AffxString substring (unsigned int iIndex, unsigned int iEndIndex) const
bool equals (const AffxString &str) const
AffxString reverseComplement ()
AffxString reverse ()
AffxString complement ()
void convertAmbiguities (char chAmbiguity)
bool startsWith (const AffxString &strCompare) const
int compareTo (const AffxString &obj, int iCompareCode) const
bool endsWith (const AffxString &str) const
int indexOf (const AffxString &strSubstring) const
int nextIndexOf (const AffxString &strSubstring, int iIndex) const
int lastIndexOf (char ch) const
AffxString & operator+ (char ch)
AffxString & operator+ (int i)
AffxString removeSurroundingQuotes ()
bool isBaseAt (int iIndex)
bool isSnpAt (int iIndex)
bool isIUPACCodeAt (int iIndex)
AffxString getSnpStringAt (int iIndex)
double calculateMeltingTemp ()
double calculateMeltingTempWithSNPs ()
bool isBiAllelic ()
bool isTriAllelic ()
AffxString getIUPACCode ()
AffxString getIUPACCodeRC ()
double getGCContent ()
unsigned int hash () const
int compareNoCase (const AffxString &str) const
int CompareNoCase (const AffxString &str) const
Static Public Member Functions
static AffxString intToString (int i, bool bCommas)
static AffxString doubleToString (double d, int iDecimalPlaces, bool bCommas)
Detailed Description
A class derived from std::string.
Definition at line 46 of file AffxString.h.
Constructor & Destructor Documentation
AffxString::AffxString () [inline]
Definition at line 208 of file AffxString.h.
Referenced by calculateMeltingTempWithSNPs().
AffxString::AffxString (const std::string & stringSrc) [inline]
Definition at line 209 of file AffxString.h.
AffxString::AffxString (const AffxString & stringSrc) [inline]
Definition at line 210 of file AffxString.h.
AffxString::AffxString (char ch, int nRepeat = 1) [inline]
Definition at line 211 of file AffxString.h.
AffxString::AffxString (const char * psz) [inline]
Definition at line 212 of file AffxString.h.
AffxString::AffxString (const char * pch, int nLength) [inline]
Definition at line 213 of file AffxString.h.
Member Function Documentation
double AffxString::calculateMeltingTemp ()
calculates the melting temperature of a DNA sequence according to an algorithmn provided by Tom. Does not handle ambigous DNA symbols (e.g. SNP b = c/g/t)
Definition at line 539 of file AffxString.cpp.
References charAt().
Referenced by calculateMeltingTempWithSNPs().
double AffxString::calculateMeltingTempWithSNPs ()
calculates the melting temperature of a DNA sequence. If the Sequence contains SNPs (with IUPac codes like b = c/g/t it calcuates the temp for all possible alleles and returns the MINIMUM temp
Definition at line 681 of file AffxString.cpp.
References AffxArray< TYPE >::add(), AffxString(), calculateMeltingTemp(), charAt(), AffxArray< TYPE >::deleteAll(), AffxArray< TYPE >::getAt(), AffxArray< TYPE >::getCount(), getSnpStringAt(), isSnpAt(), AffxArray< TYPE >::nullAll(), and substring().
char AffxString::charAt (unsigned int iIndex) const [inline]
Definition at line 120 of file AffxString.h.
References Err::errAbort().
Referenced by AffxByteArray::AffxByteArray(), calculateMeltingTemp(), calculateMeltingTempWithSNPs(), AffxByteArray::compareTo(), getGCContent(), getIUPACCodeRC(), getSnpStringAt(), isBaseAt(), isSnpAt(), stripPrecedingCharacters(), and stripTrailingCharacters().
int AffxString::compareNoCase (const AffxString & str) const [inline]
Definition at line 181 of file AffxString.h.
References CompareNoCase().
int AffxString::CompareNoCase (const AffxString & str) const [inline]
Definition at line 182 of file AffxString.h.
References compareTo(), and toLowerCase().
Referenced by compareNoCase(), AffxArray< AffxArray< CalvinValue > >::compareNoCase(), getIUPACCode(), isBiAllelic(), and isTriAllelic().
int AffxString::compareTo (const AffxString & obj, int iCompareCode) const
Definition at line 284 of file AffxString.cpp.
Referenced by AffxArray< AffxArray< CalvinValue > >::compareCase(), CompareNoCase(), CalvinDataGroup::compareTo(), CalvinDataSet::compareTo(), CalvinParameter::compareTo(), CalvinValue::compareTo(), and CalvinParameter::ComparePred< 0 >::operator()().
AffxString AffxString::complement ()
Definition at line 169 of file AffxString.cpp.
References getAt(), setAt(), and toLowerCase().
void AffxString::convertAmbiguities (char chAmbiguity)
Definition at line 203 of file AffxString.cpp.
References getAt(), and setAt().
AffxString AffxString::doubleToString (double d, int iDecimalPlaces, bool bCommas) [static]
Definition at line 225 of file AffxString.cpp.
References getDouble().
bool AffxString::endsWith (const AffxString & str) const
Definition at line 313 of file AffxString.cpp.
References getLength().
Referenced by removeSurroundingQuotes().
bool AffxString::equals (const AffxString & str) const [inline]
Definition at line 140 of file AffxString.h.
References operator==().
void AffxString::expandTabs (int nTabSize = 8)
char AffxString::getAt (unsigned int iIndex) const [inline]
Definition at line 119 of file AffxString.h.
References Err::errAbort().
Referenced by complement(), convertAmbiguities(), AffxByteArray::equals(), AffxByteArray::equalsIgnoreCase(), hash(), isAlphabetic(), isAlphanumeric(), isBlank(), isHexNumeric(), isLowercase(), isNumber(), isNumeric(), isPunctuation(), isUppercase(), isWhiteSpace(), reverse(), reverseComplement(), AffxByteArray::reverseComplement(), AffxByteArray::startsWith(), toLower(), and toUpper().
double AffxString::getGCContent ()
Definition at line 764 of file AffxString.cpp.
References charAt().
AffxString AffxString::getIUPACCode ()
Definition at line 407 of file AffxString.cpp.
References CompareNoCase(), and indexOf().
AffxString AffxString::getIUPACCodeRC ()
Definition at line 435 of file AffxString.cpp.
References charAt().
AffxString AffxString::getKey ()
Definition at line 232 of file AffxString.cpp.
unsigned int AffxString::getLength () const [inline]
Definition at line 91 of file AffxString.h.
Referenced by endsWith(), nextIndexOf(), and AffxByteArray::startsWith().
AffxString AffxString::getSnpStringAt (int iIndex)
Definition at line 498 of file AffxString.cpp.
References charAt().
Referenced by calculateMeltingTempWithSNPs().
AffxString AffxString::getValue ()
Definition at line 269 of file AffxString.cpp.
unsigned int AffxString::hash () const [inline]
Definition at line 171 of file AffxString.h.
References getAt().
int AffxString::indexOf (const AffxString & strSubstring) const [inline]
Definition at line 149 of file AffxString.h.
Referenced by getIUPACCode(), and AffxByteArray::indexOf().
AffxString AffxString::intToString (int i, bool bCommas) [static]
Definition at line 218 of file AffxString.cpp.
References getInt().
bool AffxString::isAlphabetic (int nIndex) const [inline]
Definition at line 220 of file AffxString.h.
References getAt().
bool AffxString::isAlphanumeric (int nIndex) const [inline]
Definition at line 225 of file AffxString.h.
References getAt().
bool AffxString::isBaseAt (int iIndex)
Definition at line 361 of file AffxString.cpp.
References charAt().
Referenced by isIUPACCodeAt().
bool AffxString::isBiAllelic ()
Definition at line 468 of file AffxString.cpp.
References CompareNoCase().
bool AffxString::isBlank (int nIndex) const [inline]
Definition at line 235 of file AffxString.h.
References getAt().
bool AffxString::isBlank ()
Definition at line 71 of file AffxString.cpp.
Referenced by isBlankOrEmpty().
bool AffxString::isBlankOrEmpty () [inline]
Definition at line 292 of file AffxString.h.
References isBlank().
bool AffxString::isHexNumeric (int nIndex) const [inline]
Definition at line 260 of file AffxString.h.
References getAt().
bool AffxString::isIUPACCodeAt (int iIndex) [inline]
Definition at line 161 of file AffxString.h.
References isBaseAt(), and isSnpAt().
bool AffxString::isLowercase (int nIndex) const [inline]
Definition at line 250 of file AffxString.h.
References getAt().
bool AffxString::isNumber () [inline]
Definition at line 300 of file AffxString.h.
References getAt().
bool AffxString::isNumeric (int nIndex) const [inline]
Definition at line 255 of file AffxString.h.
References getAt().
bool AffxString::isPunctuation (int nIndex) const [inline]
Definition at line 240 of file AffxString.h.
References getAt().
bool AffxString::isSnpAt (int iIndex)
Definition at line 377 of file AffxString.cpp.
References charAt().
Referenced by calculateMeltingTempWithSNPs(), and isIUPACCodeAt().
bool AffxString::isTab (int nIndex) const [inline]
Definition at line 215 of file AffxString.h.
References _TAB_CHAR.
bool AffxString::isTriAllelic ()
Definition at line 485 of file AffxString.cpp.
References CompareNoCase().
bool AffxString::isUppercase (int nIndex) const [inline]
Definition at line 245 of file AffxString.h.
References getAt().
bool AffxString::isWhiteSpace (int nIndex) const [inline]
Definition at line 230 of file AffxString.h.
References getAt().
int AffxString::lastIndexOf (char ch) const [inline]
Definition at line 151 of file AffxString.h.
AffxString AffxString::mid (int iStartIndex, int iLength) const [inline]
Definition at line 92 of file AffxString.h.
int AffxString::nextIndexOf (const AffxString & strSubstring, int iIndex) const
Definition at line 349 of file AffxString.cpp.
References getLength(), and substring().
AffxString& AffxString::operator+ (int i) [inline]
Definition at line 153 of file AffxString.h.
References getInt().
AffxString& AffxString::operator+ (char ch) [inline]
Definition at line 152 of file AffxString.h.
void AffxString::padBlanks (short nMax)
Definition at line 64 of file AffxString.cpp.
Referenced by stripAndPad().
int AffxString::printf (const char * pszFormat, ...)
Definition at line 79 of file AffxString.cpp.
References MAX_SPRINTF_SIZE.
AffxString AffxString::removeCruft ()
Definition at line 246 of file AffxString.cpp.
References startsWith().
AffxString AffxString::removeSurroundingQuotes ()
Definition at line 340 of file AffxString.cpp.
References endsWith(), startsWith(), and substring().
AffxString & AffxString::replace (char cOld, char cNew)
Definition at line 303 of file AffxString.cpp.
References setAt().
AffxString AffxString::reverse ()
Definition at line 185 of file AffxString.cpp.
References getAt(), and setAt().
AffxString AffxString::reverseComplement ()
Definition at line 140 of file AffxString.cpp.
References getAt(), setAt(), and toLowerCase().
void AffxString::setAt (unsigned int iIndex, char c) [inline]
Definition at line 118 of file AffxString.h.
References Err::errAbort().
Referenced by complement(), convertAmbiguities(), replace(), reverse(), reverseComplement(), toLower(), and toUpper().
int AffxString::sprintf (const char * pszFormat, ...)
Definition at line 97 of file AffxString.cpp.
References MAX_SPRINTF_SIZE.
Referenced by AffxTime::getRuntime().
bool AffxString::startsWith (const AffxString & strCompare) const
Definition at line 128 of file AffxString.cpp.
Referenced by removeCruft(), and removeSurroundingQuotes().
void AffxString::strip (void)
Definition at line 122 of file AffxString.cpp.
References stripPrecedingBlanks(), and stripTrailingBlanks().
Referenced by trim().
void AffxString::stripAndPad (int iLength)
Definition at line 115 of file AffxString.cpp.
References padBlanks(), stripPrecedingBlanks(), and stripTrailingBlanks().
void AffxString::stripPrecedingBlanks () [inline]
Definition at line 283 of file AffxString.h.
References stripPrecedingCharacters().
Referenced by strip(), and stripAndPad().
void AffxString::stripPrecedingCharacters (char cChar)
Definition at line 39 of file AffxString.cpp.
References charAt().
Referenced by stripPrecedingBlanks().
void AffxString::stripTrailingBlanks () [inline]
Definition at line 287 of file AffxString.h.
References stripTrailingCharacters().
Referenced by strip(), and stripAndPad().
void AffxString::stripTrailingCharacters (char cChar)
Definition at line 52 of file AffxString.cpp.
References charAt().
Referenced by stripTrailingBlanks().
AffxString AffxString::substring (unsigned int iIndex, unsigned int iEndIndex) const [inline]
Definition at line 139 of file AffxString.h.
AffxString AffxString::substring (unsigned int iIndex) const [inline]
Definition at line 137 of file AffxString.h.
Referenced by calculateMeltingTempWithSNPs(), nextIndexOf(), and removeSurroundingQuotes().
void AffxString::toLower (int nIndex) [inline]
Definition at line 274 of file AffxString.h.
References getAt(), setAt(), and affx::tolower().
Referenced by toLowerCase().
AffxString& AffxString::toLowerCase () [inline]
Definition at line 121 of file AffxString.h.
References toLower().
Referenced by CompareNoCase(), complement(), and reverseComplement().
void AffxString::toUpper (int nIndex) [inline]
Definition at line 269 of file AffxString.h.
References getAt(), and setAt().
Referenced by toUpperCase().
AffxString& AffxString::toUpperCase () [inline]
Definition at line 129 of file AffxString.h.
References toUpper().
AffxString& AffxString::trim () [inline]
Definition at line 111 of file AffxString.h.
References strip().
Referenced by PgOptionsSAXHandler::toString().
void AffxString::zeroFill (int i, int iLength)
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/AffxString.h
C:/f112/affy/sdk/util/AffxString.cpp