Affymetrix Fusion SDK: CFusionCHPMultiDataDataCOM Class Reference
CFusionCHPMultiDataDataCOM Class Reference
#include <FusionCHPMultiDataDataCOM.h>
Public Member Functions
CFusionCHPMultiDataDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
STDMETHOD() get_FileTypeIdentifiers (VARIANT *pVal)
STDMETHOD() get_FileId (BSTR *pVal)
STDMETHOD() FromBase (IFusionCHPData *baseChp, VARIANT_BOOL *pVal)
STDMETHOD() get_AlgName (BSTR *pVal)
STDMETHOD() get_AlgVersion (BSTR *pVal)
STDMETHOD() get_ArrayType (BSTR *pVal)
STDMETHOD() get_AlgorithmParameters (VARIANT *pVal)
STDMETHOD() get_SummaryParameters (VARIANT *pVal)
STDMETHOD() GetEntryCount (MultiDataType dataType, int *pVal)
STDMETHOD() GetGenotypeEntry (MultiDataType dataType, int index, IProbeSetMultiDataGenotypeData *pVal)
STDMETHOD() GetGenoCall (MultiDataType dataType, int index, int *pVal)
STDMETHOD() GetGenoConfidence (MultiDataType dataType, int index, float *pVal)
STDMETHOD() GetProbeSetName (MultiDataType dataType, int index, BSTR *pVal)
STDMETHOD() GetExpressionEntry (MultiDataType dataType, int index, IProbeSetMultiDataExpressionData *pVal)
STDMETHOD() GetExpressionQuantification (MultiDataType dataType, int index, float *pVal)
STDMETHOD() GetNumMetricColumns (MultiDataType dataType, int *pVal)
STDMETHOD() GetMetricColumnName (MultiDataType dataType, int index, BSTR *pVal)
STDMETHOD() GetProbesetNamesAndGenotypeCalls (MultiDataType dataType, VARIANT *names, VARIANT *calls, int startIndex, int *pVal)
STDMETHOD() GetProbesetNamesAndExpressionSignals (MultiDataType dataType, VARIANT *names, VARIANT *signals, int startIndex, int *pVal)
STDMETHOD() InitializeGetGenotypeEntries (MultiDataType dataType, BSTR *forcedName, BSTR *signalAName, BSTR *signalBName)
STDMETHOD() GetGenotypeEntries (MultiDataType dataType, VARIANT *names, VARIANT *calls, VARIANT *confidences, VARIANT *forcedcalls, VARIANT *signalsA, VARIANT *signalsB, int startIndex, int *pVal)
STDMETHOD() GetGenotypeEntriesGivenIndicies (MultiDataType dataType, VARIANT *indicies, VARIANT *names, VARIANT *calls, VARIANT *confidences, VARIANT *forcedcalls, VARIANT *signalsA, VARIANT *signalsB)
STDMETHOD() Close ()
STDMETHOD() GetCopyNumberEntry (MultiDataType dataType, int index, IProbeSetMultiDataCopyNumberData *pVal)
STDMETHOD() GetCytoRegionEntry (MultiDataType dataType, int index, IProbeSetMultiDataCytoRegionData *pVal)
STDMETHOD() GetCytoRegionEntries (MultiDataType dataType, VARIANT *names, VARIANT *calls, VARIANT *confidences, VARIANT *callsLOH, VARIANT *confidencesLOH, int startIndex, int *pVal)
STDMETHOD() GetDataSetHeaderParameters (MultiDataType dataType, VARIANT *pVal)
STDMETHOD() InitializeGetCNStateEntries (MultiDataType dataType)
STDMETHOD() GetCopyNumberState (MultiDataType dataType, VARIANT *names, VARIANT *chromosomes, VARIANT *positions, VARIANT *cnStates, int startIndex, int *pVal)
STDMETHOD() InitializeGetLOHStateEntries (MultiDataType dataType)
STDMETHOD() GetLOHState (MultiDataType dataType, VARIANT *names, VARIANT *chromosomes, VARIANT *positions, VARIANT *lohStates, int startIndex, int *pVal)
STDMETHOD() InitializeGetLog2RatioEntries (MultiDataType dataType)
STDMETHOD() GetLog2Ratio (MultiDataType dataType, int startIndex, int count, VARIANT *names, VARIANT *positions, VARIANT *values)
STDMETHOD() GetLog2Ratio2 (MultiDataType dataType, int startIndex, int count, VARIANT *values)
STDMETHOD() GetCopyNumberVariationRegionEntry (MultiDataType dataType, int index, IProbeSetMultiDataCopyNumberVariationRegionData *pVal)
STDMETHOD() GetCopyNumberVariationRegionNamesAndResults (MultiDataType dataType, VARIANT *regionNames, VARIANT *calls, VARIANT *signals, VARIANT *confidenceScores, int *pVal)
STDMETHOD() InitializeGetCopyNumberVariationEntries (MultiDataType dataType)
STDMETHOD() GetCopyNumberVariationResults (MultiDataType dataType, VARIANT *calls, VARIANT *signals, VARIANT *confidenceScores, int *pVal)
STDMETHOD() GetCopyNumberEntryLog2Ratio (MultiDataType dataType, int index, float *pVal)
Private Attributes
affymetrix_fusion_io::FusionCHPMultiDataData * chp
int forceIndex
int sigAIndex
int sigBIndex
int cnStateIndex
int lohStateIndex
int log2RatioIndex
int signalIndex
int callIndex
int confidenceIndex
Detailed Description
Definition at line 29 of file FusionCHPMultiDataDataCOM.h.
Constructor & Destructor Documentation
CFusionCHPMultiDataDataCOM::CFusionCHPMultiDataDataCOM () [inline]
Definition at line 36 of file FusionCHPMultiDataDataCOM.h.
Member Function Documentation
STDMETHODIMP CFusionCHPMultiDataDataCOM::Close (void)
Definition at line 439 of file FusionCHPMultiDataDataCOM.cpp.
HRESULT CFusionCHPMultiDataDataCOM::FinalConstruct () [inline]
Definition at line 62 of file FusionCHPMultiDataDataCOM.h.
void CFusionCHPMultiDataDataCOM::FinalRelease () [inline]
Definition at line 67 of file FusionCHPMultiDataDataCOM.h.
STDMETHODIMP CFusionCHPMultiDataDataCOM::FromBase (IFusionCHPData * baseChp, VARIANT_BOOL * pVal)
Definition at line 86 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_fusion_io::FusionCHPMultiDataData::FromBase(), and CFusionCHPDataCOM::GetChip().
STDMETHODIMP CFusionCHPMultiDataDataCOM::get_AlgName (BSTR * pVal)
Definition at line 99 of file FusionCHPMultiDataDataCOM.cpp.
References COMStringUtils::ConvertWString().
STDMETHODIMP CFusionCHPMultiDataDataCOM::get_AlgorithmParameters (VARIANT * pVal)
Definition at line 123 of file FusionCHPMultiDataDataCOM.cpp.
References CFusionTagValuePairTypeCOM::SetParam(), affymetrix_fusion_io::FusionTagValuePairType::Tag, and affymetrix_fusion_io::FusionTagValuePairType::Value.
STDMETHODIMP CFusionCHPMultiDataDataCOM::get_AlgVersion (BSTR * pVal)
Definition at line 107 of file FusionCHPMultiDataDataCOM.cpp.
References COMStringUtils::ConvertWString().
STDMETHODIMP CFusionCHPMultiDataDataCOM::get_ArrayType (BSTR * pVal)
Definition at line 115 of file FusionCHPMultiDataDataCOM.cpp.
References COMStringUtils::ConvertWString().
STDMETHODIMP CFusionCHPMultiDataDataCOM::get_FileId (BSTR * pVal)
Definition at line 55 of file FusionCHPMultiDataDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CFusionCHPMultiDataDataCOM::get_FileTypeIdentifiers (VARIANT * pVal)
Definition at line 61 of file FusionCHPMultiDataDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CFusionCHPMultiDataDataCOM::get_SummaryParameters (VARIANT * pVal)
Definition at line 154 of file FusionCHPMultiDataDataCOM.cpp.
References CFusionTagValuePairTypeCOM::SetParam(), affymetrix_fusion_io::FusionTagValuePairType::Tag, and affymetrix_fusion_io::FusionTagValuePairType::Value.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetCopyNumberEntry (MultiDataType dataType, int index, IProbeSetMultiDataCopyNumberData * pVal)
Definition at line 446 of file FusionCHPMultiDataDataCOM.cpp.
References CProbeSetMultiDataCopyNumberDataCOM::Data().
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetCopyNumberEntryLog2Ratio (MultiDataType dataType, int index, float * pVal)
Definition at line 455 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetCopyNumberState (MultiDataType dataType, VARIANT * names, VARIANT * chromosomes, VARIANT * positions, VARIANT * cnStates, int startIndex, int * pVal)
Definition at line 563 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::chr, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::position.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetCopyNumberVariationRegionEntry (MultiDataType dataType, int index, IProbeSetMultiDataCopyNumberVariationRegionData * pVal)
Definition at line 712 of file FusionCHPMultiDataDataCOM.cpp.
References CProbeSetMultiDataCopyNumberVariationRegionDataCOM::Data().
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetCopyNumberVariationRegionNamesAndResults (MultiDataType dataType, VARIANT * names, VARIANT * calls, VARIANT * signals, VARIANT * confidenceScores, int * pVal)
returns the region names, calls, signals and confidenceScores in a cnvchp file
Definition at line 750 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::confidenceScore, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::signal.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetCopyNumberVariationResults (MultiDataType dataType, VARIANT * calls, VARIANT * signals, VARIANT * confidenceScores, int * pVal)
returns the calls, signals and confidenceScores in a cnvchp file
Definition at line 789 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::confidenceScore, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::signal.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetCytoRegionEntries (MultiDataType dataType, VARIANT * names, VARIANT * calls, VARIANT * confidences, VARIANT * callsLOH, VARIANT * confidencesLOH, int startIndex, int * pVal)
Definition at line 472 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::confidenceScore, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::metrics, and affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::name.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetCytoRegionEntry (MultiDataType dataType, int index, IProbeSetMultiDataCytoRegionData * pVal)
Definition at line 463 of file FusionCHPMultiDataDataCOM.cpp.
References CProbeSetMultiDataCytoRegionDataCOM::Data().
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetDataSetHeaderParameters (MultiDataType dataType, VARIANT * pVal)
Definition at line 514 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_io::DataSetHeader::GetNameValIterators(), affymetrix_calvin_io::DataSetHeader::GetNameValParamCnt(), CFusionTagValuePairTypeCOM::SetParam(), affymetrix_fusion_io::FusionTagValuePairType::Tag, and affymetrix_fusion_io::FusionTagValuePairType::Value.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetEntryCount (MultiDataType dataType, int * pVal)
Definition at line 185 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetExpressionEntry (MultiDataType dataType, int index, IProbeSetMultiDataExpressionData * pVal)
Definition at line 226 of file FusionCHPMultiDataDataCOM.cpp.
References CProbeSetMultiDataExpressionDataCOM::Data().
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetExpressionQuantification (MultiDataType dataType, int index, float * pVal)
Definition at line 235 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetGenoCall (MultiDataType dataType, int index, int * pVal)
Definition at line 202 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetGenoConfidence (MultiDataType dataType, int index, float * pVal)
Definition at line 210 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetGenotypeEntries (MultiDataType dataType, VARIANT * names, VARIANT * calls, VARIANT * confidences, VARIANT * forcedcalls, VARIANT * signalsA, VARIANT * signalsB, int startIndex, int * pVal)
Definition at line 288 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::metrics, and affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::name.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetGenotypeEntriesGivenIndicies (MultiDataType dataType, VARIANT * indicies, VARIANT * names, VARIANT * calls, VARIANT * confidences, VARIANT * forcedcalls, VARIANT * signalsA, VARIANT * signalsB)
Definition at line 330 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::metrics, and affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::name.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetGenotypeEntry (MultiDataType dataType, int index, IProbeSetMultiDataGenotypeData * pVal)
Definition at line 193 of file FusionCHPMultiDataDataCOM.cpp.
References CProbeSetMultiDataGenotypeDataCOM::Data().
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetLog2Ratio (MultiDataType dataType, int startIndex, int count, VARIANT * names, VARIANT * positions, VARIANT * values)
Definition at line 674 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::position.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetLog2Ratio2 (MultiDataType dataType, int startIndex, int count, VARIANT * values)
Definition at line 697 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetLOHState (MultiDataType dataType, VARIANT * names, VARIANT * chromosomes, VARIANT * positions, VARIANT * lohStates, int startIndex, int * pVal)
Definition at line 618 of file FusionCHPMultiDataDataCOM.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::chr, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::position.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetMetricColumnName (MultiDataType dataType, int index, BSTR * pVal)
Definition at line 251 of file FusionCHPMultiDataDataCOM.cpp.
References COMStringUtils::ConvertWString().
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetNumMetricColumns (MultiDataType dataType, int * pVal)
Definition at line 243 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetProbeSetName (MultiDataType dataType, int index, BSTR * pVal)
Definition at line 218 of file FusionCHPMultiDataDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetProbesetNamesAndExpressionSignals (MultiDataType dataType, VARIANT * names, VARIANT * signals, int startIndex, int * pVal)
Definition at line 404 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::GetProbesetNamesAndGenotypeCalls (MultiDataType dataType, VARIANT * names, VARIANT * calls, int startIndex, int * pVal)
Definition at line 369 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::InitializeGetCNStateEntries (MultiDataType dataType)
Definition at line 547 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::InitializeGetCopyNumberVariationEntries (MultiDataType dataType)
Definition at line 721 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::InitializeGetGenotypeEntries (MultiDataType dataType, BSTR * forcedName, BSTR * signalAName, BSTR * signalBName)
Definition at line 259 of file FusionCHPMultiDataDataCOM.cpp.
References COMStringUtils::ConvertWString().
STDMETHODIMP CFusionCHPMultiDataDataCOM::InitializeGetLog2RatioEntries (MultiDataType dataType)
Definition at line 657 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::InitializeGetLOHStateEntries (MultiDataType dataType)
Definition at line 602 of file FusionCHPMultiDataDataCOM.cpp.
STDMETHODIMP CFusionCHPMultiDataDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 40 of file FusionCHPMultiDataDataCOM.cpp.
Member Data Documentation
int CFusionCHPMultiDataDataCOM::callIndex [private]
Definition at line 82 of file FusionCHPMultiDataDataCOM.h.
affymetrix_fusion_io::FusionCHPMultiDataData* CFusionCHPMultiDataDataCOM::chp [private]
Definition at line 74 of file FusionCHPMultiDataDataCOM.h.
int CFusionCHPMultiDataDataCOM::cnStateIndex [private]
Definition at line 78 of file FusionCHPMultiDataDataCOM.h.
int CFusionCHPMultiDataDataCOM::confidenceIndex [private]
Definition at line 83 of file FusionCHPMultiDataDataCOM.h.
int CFusionCHPMultiDataDataCOM::forceIndex [private]
Definition at line 75 of file FusionCHPMultiDataDataCOM.h.
int CFusionCHPMultiDataDataCOM::log2RatioIndex [private]
Definition at line 80 of file FusionCHPMultiDataDataCOM.h.
int CFusionCHPMultiDataDataCOM::lohStateIndex [private]
Definition at line 79 of file FusionCHPMultiDataDataCOM.h.
int CFusionCHPMultiDataDataCOM::sigAIndex [private]
Definition at line 76 of file FusionCHPMultiDataDataCOM.h.
int CFusionCHPMultiDataDataCOM::sigBIndex [private]
Definition at line 77 of file FusionCHPMultiDataDataCOM.h.
int CFusionCHPMultiDataDataCOM::signalIndex [private]
Definition at line 81 of file FusionCHPMultiDataDataCOM.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPMultiDataDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPMultiDataDataCOM.cpp