Affymetrix Fusion SDK: affymetrix_calvin_io::GenericFileWriter Class Reference
affymetrix_calvin_io::GenericFileWriter Class Reference
#include <GenericFileWriter.h>
Public Member Functions
GenericFileWriter (FileHeader *p, bool truncate=true)
~GenericFileWriter ()
void WriteHeader ()
void GetDataGroupWriters (DataGroupWriterIt &begin, DataGroupWriterIt &end)
DataGroupWriter & GetDataGroupWriter (int32_t index)
int32_t GetDataGroupCnt ()
int32_t GetFilePos ()
void SeekFromCurrentPos (int32_t offset)
void SeekFromBeginPos (int32_t offset)
void SeekFromEndPos (int32_t offset)
DataGroupWriter * CreateDataGroupWriter (DataGroupHeader &hdr)
void Write (u_int32_t p)
std::ofstream & GetFileOStream ()
Private Member Functions
void OpenFileOStream (const std::string &filename, bool truncate)
void CreateWriters ()
Private Attributes
std::ofstream os
FileHeader * fileHdr
DataGroupWriterVector writers
Detailed Description
Definition at line 38 of file GenericFileWriter.h.
Constructor & Destructor Documentation
GenericFileWriter::GenericFileWriter (FileHeader * p, bool truncate = true)
Definition at line 27 of file GenericFileWriter.cpp.
GenericFileWriter::~GenericFileWriter ()
Definition at line 34 of file GenericFileWriter.cpp.
Member Function Documentation
DataGroupWriter * GenericFileWriter::CreateDataGroupWriter (DataGroupHeader & hdr)
Definition at line 112 of file GenericFileWriter.cpp.
Referenced by affymetrix_calvin_io::CDFFileWriter::OpenDataGroup(), and affymetrix_calvin_io::CDFCntrlFileWriter::OpenDataGroup().
void GenericFileWriter::CreateWriters () [private]
Definition at line 101 of file GenericFileWriter.cpp.
int32_t GenericFileWriter::GetDataGroupCnt ()
Definition at line 73 of file GenericFileWriter.cpp.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroups().
DataGroupWriter & GenericFileWriter::GetDataGroupWriter (int32_t index)
Definition at line 68 of file GenericFileWriter.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::CDFCntrlFileWriter::CDFCntrlFileWriter(), affymetrix_calvin_io::CDFFileWriter::CDFFileWriter(), affymetrix_calvin_io::GenericFileUpdater::GetUpdateDataSetWriter(), affymetrix_calvin_io::CHPTilingFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPQuantificationFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::SeekToDataSet(), OutputMessageStream::Write(), affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroups(), affymetrix_calvin_io::DATFileUpdater::WriteGridData(), affymetrix_calvin_io::DATFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPTilingFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::WriteHeaders(), affymetrix_calvin_io::CelFileWriter::WriteHeaders(), and affymetrix_calvin_io::DATFileUpdater::WriteSubGridData().
void GenericFileWriter::GetDataGroupWriters (DataGroupWriterIt & begin, DataGroupWriterIt & end)
Definition at line 78 of file GenericFileWriter.cpp.
Referenced by affymetrix_calvin_io::CHPFileWriter::WriteHeaders().
std::ofstream& affymetrix_calvin_io::GenericFileWriter::GetFileOStream () [inline]
Definition at line 71 of file GenericFileWriter.h.
References os.
Referenced by affymetrix_calvin_io::DATFileUpdater::UpdateFileHeader().
int32_t GenericFileWriter::GetFilePos ()
Definition at line 41 of file GenericFileWriter.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::GenericFileUpdater::IncrementDataSetCnt(), affymetrix_calvin_io::DATFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPTilingFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPQuantificationFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPFileWriter::SetFilePositions(), affymetrix_calvin_io::CelFileWriter::SetFilePositions(), affymetrix_calvin_io::CDFFileWriter::WriteContentsEntry(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteContentsEntry(), affymetrix_calvin_io::CDFFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteHeaders(), affymetrix_calvin_io::CelFileWriter::WriteIntensities(), affymetrix_calvin_io::CelFileWriter::WriteMaskCoords(), affymetrix_calvin_io::CelFileWriter::WriteOutlierCoords(), affymetrix_calvin_io::DATFileWriter::WritePixels(), affymetrix_calvin_io::CelFileWriter::WritePixels(), affymetrix_calvin_io::DATFileWriter::WriteStats(), and affymetrix_calvin_io::CelFileWriter::WriteStdDevs().
void GenericFileWriter::OpenFileOStream (const std::string & filename, bool truncate) [private]
Definition at line 84 of file GenericFileWriter.cpp.
References Fs::aptOpen().
void GenericFileWriter::SeekFromBeginPos (int32_t offset)
Definition at line 51 of file GenericFileWriter.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::GenericFileUpdater::GetUpdateDataSetWriter(), affymetrix_calvin_io::GenericFileUpdater::IncrementDataSetCnt(), affymetrix_calvin_io::CHPFileWriter::SeekToBgSet(), affymetrix_calvin_io::CHPTilingFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPQuantificationFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPFileWriter::SeekToDataSet(), affymetrix_calvin_io::CHPFileWriter::SeekToForceSet(), affymetrix_calvin_io::CHPFileWriter::SeekToOrigCallSet(), affymetrix_calvin_io::DATFileUpdater::UpdateDataSetCnt(), affymetrix_calvin_io::CDFFileWriter::WriteContentsEntry(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteContentsEntry(), affymetrix_calvin_io::DATFileUpdater::WriteGridData(), affymetrix_calvin_io::CelFileWriter::WriteIntensities(), affymetrix_calvin_io::CelFileWriter::WriteMaskCoords(), affymetrix_calvin_io::CelFileWriter::WriteOutlierCoords(), affymetrix_calvin_io::DATFileWriter::WritePixels(), affymetrix_calvin_io::CelFileWriter::WritePixels(), affymetrix_calvin_io::DATFileWriter::WriteStats(), affymetrix_calvin_io::CelFileWriter::WriteStdDevs(), and affymetrix_calvin_io::DATFileUpdater::WriteSubGridData().
void GenericFileWriter::SeekFromCurrentPos (int32_t offset)
Definition at line 46 of file GenericFileWriter.cpp.
Referenced by affymetrix_calvin_io::CDFCntrlFileWriter::CDFCntrlFileWriter(), affymetrix_calvin_io::CDFFileWriter::CDFFileWriter(), affymetrix_calvin_io::DATFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPTilingFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPQuantificationFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::SetFilePositions(), affymetrix_calvin_io::CHPFileWriter::SetFilePositions(), and affymetrix_calvin_io::CelFileWriter::SetFilePositions().
void GenericFileWriter::SeekFromEndPos (int32_t offset)
Definition at line 56 of file GenericFileWriter.cpp.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), and AddDataSetHeaderToGroup().
void GenericFileWriter::Write (u_int32_t p)
Definition at line 117 of file GenericFileWriter.cpp.
References affymetrix_calvin_io::FileOutput::WriteUInt32().
Referenced by AddDataSetHeaderToGroup(), affymetrix_calvin_io::GenericFileUpdater::IncrementDataSetCnt(), and affymetrix_calvin_io::DATFileUpdater::UpdateDataSetCnt().
void GenericFileWriter::WriteHeader ()
Definition at line 61 of file GenericFileWriter.cpp.
References affymetrix_calvin_io::FileHeaderWriter::UpdateDataGroupOffset(), and affymetrix_calvin_io::FileHeaderWriter::Write().
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::MultiChannelCelFileCollater::Collate(), OutputMessageStream::Write(), affymetrix_calvin_io::DATFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFFileWriter::WriteHeaders(), affymetrix_calvin_io::CDFCntrlFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPTilingFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::WriteHeaders(), affymetrix_calvin_io::CHPFileWriter::WriteHeaders(), and affymetrix_calvin_io::CelFileWriter::WriteHeaders().
Member Data Documentation
FileHeader* affymetrix_calvin_io::GenericFileWriter::fileHdr [private]
Definition at line 43 of file GenericFileWriter.h.
std::ofstream affymetrix_calvin_io::GenericFileWriter::os [private]
Definition at line 42 of file GenericFileWriter.h.
Referenced by GetFileOStream().
DataGroupWriterVector affymetrix_calvin_io::GenericFileWriter::writers [private]
Definition at line 44 of file GenericFileWriter.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/GenericFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/GenericFileWriter.cpp