Affymetrix Fusion SDK: SequentialClfFile Class Reference
SequentialClfFile Class Reference
#include <SequentialClfFile.h>
Public Member Functions
SequentialClfFile (void)
bool isSequential (affx::TsvFile &clfTsv)
void getProbeCoordinates (const int probeId, int &x, int &y)
Private Attributes
unsigned int m_Rows
Number of rows.
unsigned int m_Cols
Number of columns.
Detailed Description
Class for calculating probe coordinates using a sequential clf file.
Definition at line 39 of file SequentialClfFile.h.
Constructor & Destructor Documentation
SequentialClfFile::SequentialClfFile (void)
Constructor.
Definition at line 30 of file SequentialClfFile.cpp.
Member Function Documentation
void SequentialClfFile::getProbeCoordinates (const int probeId, int & x, int & y)
Calculate the coordinates of a probe, given its id.
Parameters:
probeId Probe id.
x Calculated x value.
y Calculated y value.
Definition at line 62 of file SequentialClfFile.cpp.
References m_Cols, and m_Rows.
Referenced by dumpPgf::getCoordsBySequentialClf().
bool SequentialClfFile::isSequential (affx::TsvFile & clfTsv)
Check whether a clf file is sequential.
Parameters:
clfTsv Clf file tsv object.
Returns:
bool Returns true if the file is sequential, else false.
Definition at line 40 of file SequentialClfFile.cpp.
References affx::TsvFile::headersFindNext(), m_Cols, m_Rows, and Convert::toInt().
Referenced by dumpPgf::openInputFiles().
Member Data Documentation
unsigned int SequentialClfFile::m_Cols [private]
Number of columns.
Definition at line 68 of file SequentialClfFile.h.
Referenced by getProbeCoordinates(), and isSequential().
unsigned int SequentialClfFile::m_Rows [private]
Number of rows.
Definition at line 66 of file SequentialClfFile.h.
Referenced by getProbeCoordinates(), and isSequential().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/SequentialClfFile.h
C:/f112/affy/sdk/file/TsvFile/SequentialClfFile.cpp