Affymetrix Fusion SDK: MixedFileCheck Class Reference
MixedFileCheck Class Reference
#include <MixedFileCheck.h>
Public Member Functions
MixedFileCheck (const std::string &generatedFile, const std::string &goldFile, const double eps, const unsigned int skipDataLines, const unsigned int allowedMismatch, const double frac=0.0)
void setMaxError (int max)
bool check (std::string &errorMsg)
Private Member Functions
const std::string lineErrorMsg (const std::string &generatedLine, const std::string &goldLine)
Private Attributes
std::string m_GeneratedFile
Name of file generated by application being tested.
std::string m_GoldFile
Name of file assumed to be correct.
const double m_Eps
Maximum accepted absolute difference in numeric values.
const unsigned int m_SkipDataLines
Number of data lines to skip (header lines are already auto-skipped).
const unsigned int m_AllowedMismatch
Maximum number of non-matching numeric values accepted.
int m_MaxErrorsReport
The maximum number of errors to report.
const double m_Frac
Maximum fractional difference considered equivalent.
Detailed Description
Class for testing whether two files, containing both text and numeric data, are equal, within tolerances for numeric data, ignoring line endings.
Definition at line 44 of file MixedFileCheck.h.
Constructor & Destructor Documentation
MixedFileCheck::MixedFileCheck (const std::string & generatedFile, const std::string & goldFile, const double eps, const unsigned int skipDataLines, const unsigned int allowedMismatch, const double frac = 0.0) [inline]
Constructor.
Parameters:
generatedFile File generated by application.
goldFile Comparison file, assumed to be correct.
eps Maximum accepted absolute difference in numeric values. i.e. if |generated-gold| >= eps then there is a difference.
skipDataLines Number of data lines to skip (after header lines auto-skipped).
allowedMismatch Maximum number of non-matching numeric values accepted.
frac Maximum accepted fractional difference in numeric values (not used by default). i.e. if |generated-gold| >= frac*max(|generated|,|gold|) then there is a difference.
Definition at line 59 of file MixedFileCheck.h.
References Fs::basename().
Member Function Documentation
bool MixedFileCheck::check (std::string & errorMsg) [inline]
Check that the two files are the same, within tolerances.
Parameters:
errorMsg Error message generated if the test fails.
Returns:
bool Return true if files pass tests, else false.
Definition at line 82 of file MixedFileCheck.h.
References Fs::aptOpen(), Fs::convertToUncPath(), lineErrorMsg(), m_AllowedMismatch, m_Eps, m_Frac, m_GeneratedFile, m_GoldFile, m_MaxErrorsReport, m_SkipDataLines, Max, Verbose::out(), Convert::toDoubleCheck(), and ToStr().
Referenced by main().
const std::string MixedFileCheck::lineErrorMsg (const std::string & generatedLine, const std::string & goldLine) [inline, private]
Generate a generic error message for a line mismatch.
Parameters:
generatedLine Line generated by the application.
goldLine Line considered to be correct.
Returns:
Error message.
Definition at line 237 of file MixedFileCheck.h.
References m_GeneratedFile.
Referenced by check().
void MixedFileCheck::setMaxError (int max) [inline]
Utility function to set the max number of errors reported
Parameters:
max - maximum number of errors to report (set to -1 for no limit default behavior)
Returns:
- void
Definition at line 72 of file MixedFileCheck.h.
References m_MaxErrorsReport.
Member Data Documentation
const unsigned int MixedFileCheck::m_AllowedMismatch [private]
Maximum number of non-matching numeric values accepted.
Definition at line 253 of file MixedFileCheck.h.
Referenced by check().
const double MixedFileCheck::m_Eps [private]
Maximum accepted absolute difference in numeric values.
Definition at line 249 of file MixedFileCheck.h.
Referenced by check().
const double MixedFileCheck::m_Frac [private]
Maximum fractional difference considered equivalent.
Definition at line 257 of file MixedFileCheck.h.
Referenced by check().
std::string MixedFileCheck::m_GeneratedFile [private]
Name of file generated by application being tested.
Definition at line 245 of file MixedFileCheck.h.
Referenced by check(), and lineErrorMsg().
std::string MixedFileCheck::m_GoldFile [private]
Name of file assumed to be correct.
Definition at line 247 of file MixedFileCheck.h.
Referenced by check().
int MixedFileCheck::m_MaxErrorsReport [private]
The maximum number of errors to report.
Definition at line 255 of file MixedFileCheck.h.
Referenced by check(), and setMaxError().
const unsigned int MixedFileCheck::m_SkipDataLines [private]
Number of data lines to skip (header lines are already auto-skipped).
Definition at line 251 of file MixedFileCheck.h.
Referenced by check().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/MixedFileCheck.h