Affymetrix Fusion SDK: affymetrix_calvin_io::CDFCntrlFileWriter Class Reference
affymetrix_calvin_io::CDFCntrlFileWriter Class Reference
#include <CDFCntrlFileWriter.h>
Public Member Functions
CDFCntrlFileWriter (CDFData &p)
~CDFCntrlFileWriter ()
CDFCntrlProbeSetWriter * GetCntrlProbeSetWriter (const std::wstring &probeSetType)
void OpenDataGroup (const std::wstring &probeSetName, int dataSetCnt)
void CloseDataGroup ()
Private Member Functions
void WriteHeaders ()
void WriteContentsEntry (const std::wstring &probeSetType)
Private Attributes
GenericFileWriter * writer
DataGroupWriter * dataGroupWriter
DataSetWriter * contentsWriter
DataSetHeader dataSetHdr
int32_t contentsPos
int32_t currentCubePos
Detailed Description
Definition at line 40 of file CDFCntrlFileWriter.h.
Constructor & Destructor Documentation
CDFCntrlFileWriter::CDFCntrlFileWriter (CDFData & p)
Definition at line 24 of file CDFCntrlFileWriter.cpp.
References contentsPos, dataGroupWriter, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::CDFData::GetFileHeader(), affymetrix_calvin_io::CDFData::GetProbeSetCnt(), MAX_CDF_PROBE_SET_NAME_LENGTH, affymetrix_calvin_io::GenericFileWriter::SeekFromCurrentPos(), affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos(), WriteHeaders(), and writer.
CDFCntrlFileWriter::~CDFCntrlFileWriter ()
Definition at line 40 of file CDFCntrlFileWriter.cpp.
References dataGroupWriter, and writer.
Member Function Documentation
void CDFCntrlFileWriter::CloseDataGroup ()
Closes data group after writing
Definition at line 90 of file CDFCntrlFileWriter.cpp.
References affymetrix_calvin_io::DataGroupWriter::Close(), and dataGroupWriter.
CDFCntrlProbeSetWriter * CDFCntrlFileWriter::GetCntrlProbeSetWriter (const std::wstring & probeSetType)
Definition at line 56 of file CDFCntrlFileWriter.cpp.
References affymetrix_calvin_io::DataSetHeader::AddNameValParam(), affymetrix_calvin_io::DataSetHeader::AddUByteColumn(), affymetrix_calvin_io::DataSetHeader::AddUShortColumn(), affymetrix_calvin_io::DataSetHeader::Clear(), affymetrix_calvin_io::DataGroupWriter::CreateDataSetWriter(), dataGroupWriter, dataSetHdr, affymetrix_calvin_io::QC_PROBESET_TYPE, and affymetrix_calvin_io::DataSetHeader::SetName().
void CDFCntrlFileWriter::OpenDataGroup (const std::wstring & probeSetName, int dataSetCnt)
Prepares a data group for writing
Parameters:
probeSetName Probe set name
dataSetCnt number of data sets to be written
Definition at line 75 of file CDFCntrlFileWriter.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::GenericFileWriter::CreateDataGroupWriter(), dataGroupWriter, WriteContentsEntry(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), and writer.
void CDFCntrlFileWriter::WriteContentsEntry (const std::wstring & probeSetType) [private]
Definition at line 97 of file CDFCntrlFileWriter.cpp.
References contentsPos, contentsWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::DataSetWriter::Write(), and writer.
Referenced by OpenDataGroup().
void CDFCntrlFileWriter::WriteHeaders () [private]
Definition at line 46 of file CDFCntrlFileWriter.cpp.
References contentsPos, contentsWriter, dataGroupWriter, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), and writer.
Referenced by CDFCntrlFileWriter().
Member Data Documentation
int32_t affymetrix_calvin_io::CDFCntrlFileWriter::contentsPos [private]
Definition at line 49 of file CDFCntrlFileWriter.h.
Referenced by CDFCntrlFileWriter(), WriteContentsEntry(), and WriteHeaders().
DataSetWriter* affymetrix_calvin_io::CDFCntrlFileWriter::contentsWriter [private]
Definition at line 47 of file CDFCntrlFileWriter.h.
Referenced by WriteContentsEntry(), and WriteHeaders().
int32_t affymetrix_calvin_io::CDFCntrlFileWriter::currentCubePos [private]
Definition at line 50 of file CDFCntrlFileWriter.h.
DataGroupWriter* affymetrix_calvin_io::CDFCntrlFileWriter::dataGroupWriter [private]
Definition at line 46 of file CDFCntrlFileWriter.h.
Referenced by CDFCntrlFileWriter(), CloseDataGroup(), GetCntrlProbeSetWriter(), OpenDataGroup(), WriteHeaders(), and ~CDFCntrlFileWriter().
DataSetHeader affymetrix_calvin_io::CDFCntrlFileWriter::dataSetHdr [private]
Definition at line 48 of file CDFCntrlFileWriter.h.
Referenced by GetCntrlProbeSetWriter().
GenericFileWriter* affymetrix_calvin_io::CDFCntrlFileWriter::writer [private]
Definition at line 45 of file CDFCntrlFileWriter.h.
Referenced by CDFCntrlFileWriter(), OpenDataGroup(), WriteContentsEntry(), WriteHeaders(), and ~CDFCntrlFileWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CDFCntrlFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CDFCntrlFileWriter.cpp