Affymetrix Fusion SDK: ChpCheck Class Reference
ChpCheck Class Reference
#include <ChpCheck.h>
Public Member Functions
ChpCheck (std::vector< std::string > &generated, std::vector< std::string > &gold, int diffAllowed=0, const std::string &prefix="apt-", double eps=0.0001, bool bCheckHeaders=true, double frac=0.0)
Constructor.
ChpCheck (const std::string &generated, const std::string &gold, int diffAllowed=0, const std::string &prefix="apt-", double eps=0.0001, bool bCheckHeaders=true, double frac=0.0)
bool checkFilePair (int genIdx, int goldIdx, std::string &msg)
bool check (std::string &msg)
void clearHeaderIgnore ()
void addHeaderIgnore (std::string &key)
Private Member Functions
bool tagValuePairMostlySame (TagValuePairTypeList &gold, TagValuePairTypeList &test, std::string &msg)
bool headersSame (const std::string &generated, const std::string &gold, std::string &msgs)
bool dataSame (const std::string &generated, const std::string &gold, std::string &msgs)
Static Private Member Functions
static void fillInToIgnore (std::set< std::string > &ignoreMap, const std::string &prefix)
Private Attributes
std::vector< std::string > m_Gold
Filenames for the gold standard or correct data chp files.
std::vector< std::string > m_Generated
Matching filenames for the chp files to be tested.
double m_Eps_confidence
Epsilon, small value that two floats can differ by but still be considered equivalent.
double m_Eps_pvalue
double m_Eps_signal
double m_Frac_confidence
double m_Frac_pvalue
double m_Frac_signal
bool m_CheckHeaders
int m_DiffAllowed
How many differences will we tolerate?
std::string m_Prefix
What is the expected prefix for parameter names?
std::set< std::string > m_IgnoreMap
Header entries to ignore.
Detailed Description
Class for testing that CHP files are the same +/- some epsilon. Also checks to make sure that at least some of the headers are the same (times/dates/versions change so not checked).
Definition at line 54 of file ChpCheck.h.
Constructor & Destructor Documentation
ChpCheck::ChpCheck (std::vector< std::string > & generated, std::vector< std::string > & gold, int diffAllowed = 0, const std::string & prefix = "apt-", double eps = 0.0001, bool bCheckHeaders = true, double frac = 0.0) [inline]
Constructor.
Parameters:
generated
gold the reference data to compare with
diffAllowed the number of differences allowed (default 0)
prefix the prefix for the header string alg part
eps epsilon [confidence, pvalue] i.e. if |gen-gold| >= frac*max(|gen|,|gold|) then there is a difference.
bCheckHeaders Check headers? (boolean, default: true).
frac maximum accepted fractional difference in numeric values (not used by default). i.e. if |gen-gold| >= frac*max(|gen|,|gold|) then there is a difference.
Definition at line 68 of file ChpCheck.h.
References fillInToIgnore(), m_CheckHeaders, m_DiffAllowed, m_Eps_confidence, m_Eps_pvalue, m_Eps_signal, m_Frac_confidence, m_Frac_pvalue, m_Frac_signal, m_Generated, m_Gold, m_IgnoreMap, and m_Prefix.
ChpCheck::ChpCheck (const std::string & generated, const std::string & gold, int diffAllowed = 0, const std::string & prefix = "apt-", double eps = 0.0001, bool bCheckHeaders = true, double frac = 0.0) [inline]
Definition at line 89 of file ChpCheck.h.
References fillInToIgnore(), m_CheckHeaders, m_DiffAllowed, m_Eps_confidence, m_Eps_pvalue, m_Eps_signal, m_Frac_confidence, m_Frac_pvalue, m_Frac_signal, m_Generated, m_Gold, m_IgnoreMap, and m_Prefix.
Member Function Documentation
void ChpCheck::addHeaderIgnore (std::string & key) [inline]
Add a header item to ignore
Parameters:
key - reference to a wide string
Definition at line 169 of file ChpCheck.h.
References m_IgnoreMap.
bool ChpCheck::check (std::string & msg) [inline]
Check to make sure that two files are the same +/- some epsilon.
Parameters:
msg - Fills in an error message if test fails, empty string otherwise.
Returns:
- Returns true if files are close enough, false otherwise.
Definition at line 138 of file ChpCheck.h.
References checkFilePair(), m_Generated, and m_Gold.
Referenced by main().
bool ChpCheck::checkFilePair (int genIdx, int goldIdx, std::string & msg) [inline]
Definition at line 110 of file ChpCheck.h.
References Fs::convertToUncPath(), dataSame(), headersSame(), m_CheckHeaders, m_Generated, m_Gold, ToStr(), and Except::what().
Referenced by check().
void ChpCheck::clearHeaderIgnore () [inline]
Clear out the default set of header entries to ignore
Definition at line 161 of file ChpCheck.h.
References m_IgnoreMap.
bool ChpCheck::dataSame (const std::string & generated, const std::string & gold, std::string & msgs) [inline, private]
Todo:
check RAS fields
Todo:
check other fields
Definition at line 286 of file ChpCheck.h.
References affxchp::CGenotypeProbeSetResults::AlleleCall, affxchp::CGenotypeProbeSetResults::Confidence, Err::errAbort(), Expression, affymetrix_calvin_io::Genotyping, affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileData::GetError(), affxchp::CCHPFileData::GetExpressionResults(), affxchp::CCHPFileData::GetGenotypingResults(), affxchp::CCHPFileData::GetHeader(), affxchp::CCHPFileHeader::GetNumProbeSets(), m_DiffAllowed, m_Eps_confidence, m_Eps_pvalue, m_Eps_signal, m_Frac_confidence, m_Frac_pvalue, m_Frac_signal, Verbose::out(), affxchp::CGenotypeProbeSetResults::pvalue_AA, affxchp::CGenotypeProbeSetResults::pvalue_AB, affxchp::CGenotypeProbeSetResults::pvalue_BB, affxchp::CGenotypeProbeSetResults::pvalue_NoCall, affxchp::CCHPFileData::Read(), affxchp::CCHPFileData::SetFileName(), affxchp::CExpressionProbeSetResults::Signal, and ToStr().
Referenced by checkFilePair().
static void ChpCheck::fillInToIgnore (std::set< std::string > & ignoreMap, const std::string & prefix) [inline, static, private]
Definition at line 176 of file ChpCheck.h.
Referenced by ChpCheck().
bool ChpCheck::headersSame (const std::string & generated, const std::string & gold, std::string & msgs) [inline, private]
Definition at line 246 of file ChpCheck.h.
References affxchp::CCHPFileHeader::AlgorithmParameters(), affxchp::CCHPFileHeader::GetAlgVersion(), affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileHeader::GetChipType(), affxchp::CCHPFileHeader::GetCols(), affxchp::CCHPFileData::GetError(), affxchp::CCHPFileData::GetHeader(), affxchp::CCHPFileHeader::GetNumProbeSets(), affxchp::CCHPFileHeader::GetProgID(), affxchp::CCHPFileHeader::GetRows(), affxchp::CCHPFileData::ReadHeader(), affxchp::CCHPFileData::SetFileName(), affxchp::CCHPFileHeader::SummaryParameters(), tagValuePairMostlySame(), and ToStr().
Referenced by checkFilePair().
bool ChpCheck::tagValuePairMostlySame (TagValuePairTypeList & gold, TagValuePairTypeList & test, std::string & msg) [inline, private]
Check the gold tag value pairs to make sure they are getting the same values in the test. We only check items that are in gold, which means that if a new field has been added it will not be checked.
Parameters:
gold - List of key, value pairs in the gold set.
test - List of key, value pairs in the set to be checked.
msg - Place for adding error messages as they are encountered.
Returns:
- true if same, false otherwise.
Definition at line 200 of file ChpCheck.h.
References Fs::basename(), m_Eps_confidence, m_IgnoreMap, Convert::toFloatCheck(), and ToStr().
Referenced by headersSame().
Member Data Documentation
bool ChpCheck::m_CheckHeaders [private]
Definition at line 395 of file ChpCheck.h.
Referenced by checkFilePair(), and ChpCheck().
int ChpCheck::m_DiffAllowed [private]
How many differences will we tolerate?
Definition at line 397 of file ChpCheck.h.
Referenced by ChpCheck(), and dataSame().
double ChpCheck::m_Eps_confidence [private]
Epsilon, small value that two floats can differ by but still be considered equivalent.
Definition at line 389 of file ChpCheck.h.
Referenced by ChpCheck(), dataSame(), and tagValuePairMostlySame().
double ChpCheck::m_Eps_pvalue [private]
Definition at line 390 of file ChpCheck.h.
Referenced by ChpCheck(), and dataSame().
double ChpCheck::m_Eps_signal [private]
Definition at line 391 of file ChpCheck.h.
Referenced by ChpCheck(), and dataSame().
double ChpCheck::m_Frac_confidence [private]
Definition at line 392 of file ChpCheck.h.
Referenced by ChpCheck(), and dataSame().
double ChpCheck::m_Frac_pvalue [private]
Definition at line 393 of file ChpCheck.h.
Referenced by ChpCheck(), and dataSame().
double ChpCheck::m_Frac_signal [private]
Definition at line 394 of file ChpCheck.h.
Referenced by ChpCheck(), and dataSame().
std::vector<std::string> ChpCheck::m_Generated [private]
Matching filenames for the chp files to be tested.
Definition at line 387 of file ChpCheck.h.
Referenced by check(), checkFilePair(), and ChpCheck().
std::vector<std::string> ChpCheck::m_Gold [private]
Filenames for the gold standard or correct data chp files.
Definition at line 385 of file ChpCheck.h.
Referenced by check(), checkFilePair(), and ChpCheck().
std::set<std::string> ChpCheck::m_IgnoreMap [private]
Header entries to ignore.
Definition at line 401 of file ChpCheck.h.
Referenced by addHeaderIgnore(), ChpCheck(), clearHeaderIgnore(), and tagValuePairMostlySame().
std::string ChpCheck::m_Prefix [private]
What is the expected prefix for parameter names?
Definition at line 399 of file ChpCheck.h.
Referenced by ChpCheck().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/ChpCheck.h