Affymetrix Fusion SDK: affx Namespace Reference
affx Namespace Reference
Classes
class BgpFile
To be called a BGP file, the file requires.
class ClfFile
To be called a CLF file, the file requires.
class PgfFile
class SpfFile
class TsvFileBinding
class TsvFileField
class TsvFileIndex
TsvFileIndex maps values to line positions.
class TsvFileHeaderLine
This is a key-value pair with sort order.
class TsvFile
A class for reading and writing Tab Seperated Value (TSV) files. See the TsvFile format document and the example program tsv-example.cpp .
class TsvFileDiff
class md5sum
an object oriented interface to generating MD5s. provides methods to do strings and files with one call.
Typedefs
typedef uint32_t linenum_t
line numbers cant be negative
Enumerations
enum bindto_t { TSV_BINDTO_NONE = 0, TSV_BINDTO_CIDX = 1, TSV_BINDTO_CNAME = 2 }
Selector for what is used to link the binding.
enum valstate_t { VALSTATE_NONE = 0, VALSTATE_INT = 1, VALSTATE_DOUBLE = 2, VALSTATE_STRING = 3 }
enum tsv_type_t {
TSV_TYPE_UNKNOWN = 0, TSV_TYPE_ERR = 1, TSV_TYPE_STRING = 2, TSV_TYPE_INT = 3,
TSV_TYPE_FLOAT = 4, TSV_TYPE_DOUBLE = 5
}
enum tsv_return_t {
TSV_OK = -1, TSV_LINE_BLANK = -2, TSV_LINE_COMMENT = -3, TSV_ERR_UNKNOWN = -11,
TSV_ERR_NOTFOUND = -12, TSV_ERR_NULL = -13, TSV_ERR_CONVERSION = -14, TSV_ERR_FILEIO = -15,
TSV_ERR_FORMAT = -16, TSV_ERR_EOF = -17, TSV_HEADER = -30, TSV_HEADER_LAST = -31,
TSV_LEVEL_LAST = -32, TSV_FIND_LAST = -33, TSV_ERR_BINARY = -40, TSV_ERR_CALVIN = -41,
TSV_ERR_HDF5 = -42, TSV_LASTVALUE = -99
}
Return values to signal Error codes.
enum tsv_op_t {
TSV_OP_LT = 0x01, TSV_OP_LTEQ = 0x03, TSV_OP_EQ = 0x02, TSV_OP_GTEQ = 0x06,
TSV_OP_GT = 0x04
}
Flags supplied to when finding matches.
enum tsv_indexkind_t {
TSV_INDEX_STRING = 0x1, TSV_INDEX_INT = 0x2, TSV_INDEX_DOUBLE = 0x3, TSV_INDEX_UINT = 0x4,
TSV_INDEX_ULONGLONG = 0x5
}
The datatype of a index.
enum tsv_orderby_t { TSV_ORDERBY_LINE = 0x01, TSV_ORDERBY_VAL = 0x02 }
Should the results be ordered by the line nubmer or value.
enum tsv_fileformat_t {
TSV_FORMAT_NONE = 0x00, TSV_FORMAT_V1 = 0x01, TSV_FORMAT_V2 = 0x02, TSV_FORMAT_TABLE = 0x03,
TSV_FORMAT_BAD = 0xff
}
The format of the file.
enum tsv_bindopt_t { TSV_BIND_OPTIONAL = 0x01, TSV_BIND_WARNING = 0x02, TSV_BIND_REQUIRED = 0x04, TSV_BIND_NOFLAG = 0x00 }
Requirements for binding.
enum tsv_addflag_t { TSV_ADD_NONE = 0x00, TSV_ADD_KEYS = 0x01, TSV_ADD_COMMENTS = 0x02, TSV_ADD_ALL = (TSV_ADD_KEYS|TSV_ADD_COMMENTS) }
Flags for querying headers.
enum tsv_optionflag_t { TSV_OPT_NONE = 0x00, TSV_OPT_CASESENSTIVE = 0x01, TSV_OPT_CASEINSENSTIVE = 0x02 }
misc optional flags
Functions
void ltrim (std::string &str)
Trim whitespace from the left of a string.
void rtrim (std::string &str)
Trim whitespace from the right of a string.
void trim (std::string &str)
Trim whitespace from both sides of a string.
std::string tolower (const std::string &str)
void dequote (std::string &str)
Remove quotes from a string if they are matching.
int splitstr (const std::string &str, char c, std::vector< std::string > &vec)
Split a string into a vector.
int countchars (const std::string &str, char c)
int unescapeChar (int c)
Convert the escaped char to the char which it represents.
int escapeChar (int c)
std::string escapeString (const std::string &str, const char escapeChar)
bool header_ptr_less (const affx::TsvFileHeaderLine *a, const affx::TsvFileHeaderLine *b)
Function for comparing TsvFileHeaderLine pointers.
void touchEngines ()
Variables
const int TSV_INTERNSIZE_UNSET = -1
Detailed Description
This defines an object which has fields and some methods to make working with PGF files a snap. Basicly we define user friendly method which map to TsvFile mothods.
Typedef Documentation
typedef uint32_t affx::linenum_t
line numbers cant be negative
Definition at line 59 of file TsvFile.h.
Enumeration Type Documentation
enum affx::bindto_t
Selector for what is used to link the binding.
Enumerator:
TSV_BINDTO_NONE
The binding wont be bound.
TSV_BINDTO_CIDX
Bound to column indexed by number.
TSV_BINDTO_CNAME
Bound to a column index by name.
Definition at line 68 of file TsvFile.h.
enum affx::tsv_addflag_t
Flags for querying headers.
Enumerator:
TSV_ADD_NONE
TSV_ADD_KEYS
just for nothing...
TSV_ADD_COMMENTS
return keys
TSV_ADD_ALL
return comments
Definition at line 153 of file TsvFile.h.
enum affx::tsv_bindopt_t
Requirements for binding.
Enumerator:
TSV_BIND_OPTIONAL
TSV_BIND_WARNING
bind if present
TSV_BIND_REQUIRED
warn if not bound
TSV_BIND_NOFLAG
error if not bound
Definition at line 146 of file TsvFile.h.
enum affx::tsv_fileformat_t
The format of the file.
Enumerator:
TSV_FORMAT_NONE
TSV_FORMAT_V1
TSV_FORMAT_V2
TSV_FORMAT_TABLE
TSV_FORMAT_BAD
Definition at line 138 of file TsvFile.h.
enum affx::tsv_indexkind_t
The datatype of a index.
Enumerator:
TSV_INDEX_STRING
TSV_INDEX_INT
TSV_INDEX_DOUBLE
TSV_INDEX_UINT
TSV_INDEX_ULONGLONG
Definition at line 125 of file TsvFile.h.
enum affx::tsv_op_t
Flags supplied to when finding matches.
Enumerator:
TSV_OP_LT
TSV_OP_LTEQ
TSV_OP_EQ
TSV_OP_GTEQ
TSV_OP_GT
Definition at line 116 of file TsvFile.h.
enum affx::tsv_optionflag_t
misc optional flags
Enumerator:
TSV_OPT_NONE
TSV_OPT_CASESENSTIVE
TSV_OPT_CASEINSENSTIVE
Definition at line 160 of file TsvFile.h.
enum affx::tsv_orderby_t
Should the results be ordered by the line nubmer or value.
Enumerator:
TSV_ORDERBY_LINE
TSV_ORDERBY_VAL
Definition at line 133 of file TsvFile.h.
enum affx::tsv_return_t
Return values to signal Error codes.
Enumerator:
TSV_OK
No Error.
TSV_LINE_BLANK
The line is blank (m_lineLvl)
TSV_LINE_COMMENT
The line is a comment line (m_lineLvl)
TSV_ERR_UNKNOWN
An otherwise unknown error.
TSV_ERR_NOTFOUND
The value was not found.
TSV_ERR_NULL
The value was null.
TSV_ERR_CONVERSION
The value could not be converted.
TSV_ERR_FILEIO
Some sort of file IO error.
TSV_ERR_FORMAT
The format of the file is bad.
TSV_ERR_EOF
Hit the end of the file.
TSV_HEADER
A header line was read.
TSV_HEADER_LAST
Did not read a header line.
TSV_LEVEL_LAST
Did not read a line of the correct level.
TSV_FIND_LAST
Found the last matching value.
TSV_ERR_BINARY
This is some sort of binary file.
TSV_ERR_CALVIN
This is a calvin file.
TSV_ERR_HDF5
This is a HDF5 file.
TSV_LASTVALUE
end of errors
Definition at line 91 of file TsvFile.h.
enum affx::tsv_type_t
Enumerator:
TSV_TYPE_UNKNOWN
TSV_TYPE_ERR
TSV_TYPE_STRING
TSV_TYPE_INT
TSV_TYPE_FLOAT
TSV_TYPE_DOUBLE
Definition at line 81 of file TsvFile.h.
enum affx::valstate_t
Enumerator:
VALSTATE_NONE
VALSTATE_INT
VALSTATE_DOUBLE
VALSTATE_STRING
Definition at line 74 of file TsvFile.h.
Function Documentation
int affx::countchars (const std::string & str, char c)
Definition at line 172 of file TsvFile.cpp.
Referenced by check_countchars(), and affx::TsvFile::f_read_header_v1().
void affx::dequote (std::string & str)
Remove quotes from a string if they are matching.
Parameters:
str String to remove them from
Definition at line 154 of file TsvFile.cpp.
Referenced by affx::TsvFile::f_read_column(), and affx::TsvFile::f_read_header_v1().
int affx::escapeChar (int c)
Definition at line 233 of file TsvFile.cpp.
References TSV_CHAR_CR, TSV_CHAR_LF, and TSV_CHAR_TAB.
Referenced by check_escapeString(), and escapeString().
std::string affx::escapeString (const std::string & str, const char escapeChar)
Definition at line 250 of file TsvFile.cpp.
References escapeChar().
Referenced by check_escapeString(), and affx::TsvFile::writeLevel().
bool affx::header_ptr_less (const affx::TsvFileHeaderLine * a, const affx::TsvFileHeaderLine * b)
Function for comparing TsvFileHeaderLine pointers.
Definition at line 1289 of file TsvFile.cpp.
Referenced by affx::TsvFile::resortHeaders().
void affx::ltrim (std::string & str)
Trim whitespace from the left of a string.
Parameters:
str the string to trim
Definition at line 108 of file TsvFile.cpp.
Referenced by check_trim(), affx::TsvFile::f_read_header_v2(), and trim().
void affx::rtrim (std::string & str)
Trim whitespace from the right of a string.
Parameters:
str the string to trim
Definition at line 121 of file TsvFile.cpp.
Referenced by check_trim(), affx::TsvFile::f_read_header_v2(), and trim().
int affx::splitstr (const std::string & str, char c, std::vector< std::string > & vec)
Split a string into a vector.
Parameters:
str string to split
c character to split on
vec vector to fill with split strings
Returns:
number of resulting strings
Definition at line 189 of file TsvFile.cpp.
Referenced by check_splitstr(), affx::TsvFile::defineFileParse(), affx::TsvFile::f_read_header_v1(), and affx::TsvFile::headers_to_fields_v2().
std::string affx::tolower (const std::string & str)
Referenced by check_tolower(), affx::TsvFile::cname2cidx(), Util::downcaseString_inplace(), affxbpmapwriter::CBPMAPFileWriter::ReadTpmap(), and AffxString::toLower().
void affx::touchEngines ()
Definition at line 41 of file Engines.h.
void affx::trim (std::string & str)
Trim whitespace from both sides of a string.
Parameters:
str the string to trim
Definition at line 134 of file TsvFile.cpp.
References ltrim(), and rtrim().
Referenced by check_trim(), affx::TsvFile::f_read_column(), affx::TsvFile::f_read_header_v2(), and AffxByteArray::isValid().
int affx::unescapeChar (int c)
Convert the escaped char to the char which it represents.
Parameters:
c the escaped char
Returns:
the converted char
Definition at line 217 of file TsvFile.cpp.
References TSV_CHAR_CR, TSV_CHAR_LF, and TSV_CHAR_TAB.
Referenced by affx::TsvFile::f_read_column().
Variable Documentation
const int affx::TSV_INTERNSIZE_UNSET = -1
Definition at line 65 of file TsvFile.h.