Affymetrix Fusion SDK: C:/f112/affy/sdk/parser_examples/cpp/read_chp/read_chp.cpp File Reference
read_chp.cpp File Reference
#include "calvin_files/fusion/src/FusionCHPData.h"
#include "calvin_files/fusion/src/FusionCHPLegacyData.h"
#include "calvin_files/fusion/src/FusionCHPMultiDataData.h"
#include <iostream>
Functions
static void ExpressionLegacyExample (FusionCHPLegacyData *legchp)
static void GenotypeLegacyExample (FusionCHPLegacyData *legchp)
static void LegacyExample (FusionCHPLegacyData *legchp)
static void MultiDataExample (FusionCHPMultiDataData *dchp)
int main (int argc, char **argv)
Function Documentation
static void ExpressionLegacyExample (FusionCHPLegacyData * legchp) [static]
Definition at line 11 of file read_chp.cpp.
References affymetrix_fusion_io::FusionCHPLegacyData::GetExpressionResults(), affymetrix_fusion_io::FusionCHPLegacyData::GetHeader(), affymetrix_fusion_io::FusionCHPHeader::GetNumProbeSets(), and affymetrix_fusion_io::FusionExpressionProbeSetResults::GetSignal().
Referenced by LegacyExample().
static void GenotypeLegacyExample (FusionCHPLegacyData * legchp) [static]
Definition at line 25 of file read_chp.cpp.
Referenced by LegacyExample().
static void LegacyExample (FusionCHPLegacyData * legchp) [static]
Definition at line 29 of file read_chp.cpp.
References ExpressionLegacyExample(), FusionExpression, FusionGenotyping, GenotypeLegacyExample(), affymetrix_fusion_io::FusionCHPHeader::GetAssayType(), and affymetrix_fusion_io::FusionCHPLegacyData::GetHeader().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 79 of file read_chp.cpp.
References LegacyExample(), and MultiDataExample().
static void MultiDataExample (FusionCHPMultiDataData * dchp) [static]
Definition at line 41 of file read_chp.cpp.
References ALLELE_A_CALL, ALLELE_AB_CALL, ALLELE_B_CALL, affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_fusion_io::FusionCHPMultiDataData::GetEntryCount(), affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoCall(), and affymetrix_fusion_io::FusionCHPMultiDataData::GetSummaryParams().
Referenced by main().