Affymetrix Fusion SDK: C:/f112/affy/sdk/parser_examples/cpp/read_cytoV2/read_cytov2.cpp File Reference
read_cytov2.cpp File Reference
#include "calvin_files/fusion/src/FusionCHPMultiDataData.h"
#include "util/convert.h"
#include <iostream>
Functions
static void printParams (std::list< ParameterNameValueType > &params)
static void printParams (std::vector< ParameterNameValueType > &params)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 30 of file read_cytov2.cpp.
References affymetrix_calvin_io::AllelePeaksMultiDataType, affymetrix_calvin_data::_CytoGenotypeCallData::aSignal, affymetrix_calvin_data::_CytoGenotypeCallData::bSignal, affymetrix_calvin_data::_CytoGenotypeCallData::call, affymetrix_calvin_data::_AllelePeaks::chr, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::chr, affymetrix_calvin_data::_ChromosomeSegmentData::chr, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::chr, affymetrix_calvin_io::ChromosomeSummaryMultiDataType, affymetrix_calvin_data::_CytoGenotypeCallData::confidence, affymetrix_calvin_data::_CytoGenotypeCallData::contrast, affymetrix_calvin_io::CopyNumberMultiDataType, affymetrix_calvin_io::CytoGenotypeCallMultiDataType, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::display, affymetrix_calvin_data::_CytoGenotypeCallData::forcedCall, affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgName(), affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgParams(), affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgVersion(), affymetrix_fusion_io::FusionCHPMultiDataData::GetAllelePeakEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetArrayType(), affymetrix_fusion_io::FusionCHPMultiDataData::GetChromosomeSegmentEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetChromosomeSummaryEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetCopyNumberEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetCytoGenotypeEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetEntryCount(), affymetrix_fusion_io::FusionCHPMultiDataData::GetMarkerABSignalsEntry(), affymetrix_fusion_io::FusionCHPMultiDataData::GetSummaryParams(), affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::hetFrequency, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::homFrequency, affymetrix_calvin_data::_CytoGenotypeCallData::index, affymetrix_calvin_data::_MarkerABSignals::index, affymetrix_calvin_io::MarkerABSignalsMultiDataType, affymetrix_calvin_data::_ChromosomeSegmentData::markerCount, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::markerCount, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::maxSignal, affymetrix_calvin_data::_ChromosomeSegmentData::meanMarkerDistance, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::medianCnState, affymetrix_calvin_data::_CytoGenotypeCallData::metrics, affymetrix_calvin_data::_MarkerABSignals::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::metrics, affymetrix_calvin_data::_ChromosomeSegmentData::metrics, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::metrics, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::minSignal, affymetrix_calvin_data::_AllelePeaks::name, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::name, affymetrix_calvin_data::_AllelePeaks::peaks, affymetrix_calvin_data::_AllelePeaks::position, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::position, printParams(), affymetrix_calvin_io::SegmentCNMultiDataType, affymetrix_calvin_io::SegmentCNNeutralLOHMultiDataType, affymetrix_calvin_data::_ChromosomeSegmentData::segmentId, affymetrix_calvin_io::SegmentLOHMultiDataType, affymetrix_calvin_io::SegmentMosaicismMultiDataType, affymetrix_calvin_io::SegmentNoCallMultiDataType, affymetrix_calvin_io::SegmentNormalDiploidMultiDataType, affymetrix_calvin_data::_CytoGenotypeCallData::signalStrength, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::startIndex, affymetrix_calvin_data::_ChromosomeSegmentData::startPosition, affymetrix_calvin_data::_ChromosomeSegmentData::stopPosition, and ToStr().
static void printParams (std::list< ParameterNameValueType > & params) [static]
Definition at line 12 of file read_cytov2.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::ToString().
Referenced by main().
static void printParams (std::vector< ParameterNameValueType > & params) [static]
Definition at line 21 of file read_cytov2.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::ToString().