Affymetrix Fusion SDK: C:/f112/affy/sdk/util/test-md5sum.cpp File Reference
test-md5sum.cpp File Reference
#include <util/md5sum.h>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
Functions
void self_test ()
void nbo_test_int (unsigned int val, const std::string &ref)
void nbo_test ()
int main (int argc, char *argv[])
Variables
const char * self_test_data []
Function Documentation
int main (int argc, char * argv[])
Definition at line 97 of file test-md5sum.cpp.
References nbo_test(), affx::md5sum::ofFile(), and self_test().
void nbo_test ()
Definition at line 83 of file test-md5sum.cpp.
References nbo_test_int().
Referenced by main().
void nbo_test_int (unsigned int val, const std::string & ref)
Definition at line 69 of file test-md5sum.cpp.
References affx::md5sum::final(), affx::md5sum::init(), and affx::md5sum::update_nbo().
Referenced by nbo_test().
void self_test ()
Definition at line 42 of file test-md5sum.cpp.
References affx::md5sum::final(), affx::md5sum::init(), self_test_data, and affx::md5sum::update().
Referenced by main().
Variable Documentation
const char* self_test_data[]
Initial value:
{
  "","d41d8cd98f00b204e9800998ecf8427e",
  "a","0cc175b9c0f1b6a831c399e269772661",
  "The quick brown fox jumps over the lazy dog","9e107d9d372bb6826bd81d3542a419d6",
  "The quick brown fox jumps over the lazy cog","1055d3e698d289f2af8663725127bd4b",
  NULL, NULL
}
Definition at line 32 of file test-md5sum.cpp.
Referenced by self_test().