Affymetrix Fusion SDK: C:/f112/affy/sdk/file/TsvFile/tsv-test.cpp File Reference
tsv-test.cpp File Reference
#include "file/TsvFile/BgpFile.h"
#include "file/TsvFile/ClfFile.h"
#include "file/TsvFile/PgfFile.h"
#include "file/TsvFile/SnpTable.h"
#include "file/TsvFile/TsvFile.h"
#include <sstream>
Defines
#define CHECK_DEQUOTE(Xstr1, Xstr2)
Check the dequoting of a string.
#define TEST_VEC_CONVERT_123(TYPE)
#define TEST_VEC_CONVERT_BLANK(TYPE)
#define CH2_CNT 10
Functions
void check_trim ()
Check that the tsv->trim methods work.
void check_tolower ()
void check_dequote ()
Check that dequoting works as expected.
void check_countchars ()
Check splitstr works.
void check_splitstr_print (std::vector< std::string > &strvec)
print the results of splitstr
void check_splitstr ()
Check splitstr works.
void check_escapeString ()
void check_field_name ()
Check that the column name functions work.
void check_empty ()
void check_field_convert ()
Check the conversion of a field buffer.
void check_field_vec_convert ()
void check_headers_1 ()
Check that the headers work.
void check_read_table_1 ()
Check table reading.
void check_headers_2 ()
Check the behavior of headers.
void check_comment_1 ()
void check_headers_3 ()
Check the behavior of headers.
void check_headers_4 ()
void check_csv_1 ()
Check the reading of a Comma Seperated Value file.
void check_nextline ()
Check that next line skips comments.
void check_index_1 ()
Check that indexes work.
void check_winpath_1 ()
Check that we can read a windows path name.
void check_read_vec_1 ()
void check_write_10 ()
void check_write_vec_1 ()
void check_read_colvec_1 ()
void check_read_pgf_1 ()
void check_line_count ()
void check_replace ()
int main (int argc, char *argv[])
Main function to call all the check tests.
Define Documentation
#define CH2_CNT 10
Definition at line 746 of file tsv-test.cpp.
Referenced by check_headers_3().
#define CHECK_DEQUOTE (Xstr1, Xstr2)
Value:
str1=Xstr1; \
  str2=str1;  \
  dequote(str2); \
  if (0) printf("dequote('%s')=='%s'\n",str1.c_str(),str2.c_str());  \
  assert(str2==Xstr2);
Check the dequoting of a string.
Definition at line 94 of file tsv-test.cpp.
Referenced by check_dequote().
#define TEST_VEC_CONVERT_123 (TYPE)
Value:
do {                         \
    std::vector<TYPE> out_vec_##TYPE;                           \
    rv=col.get(&out_vec_##TYPE,',');                            \
    assert((rv==TSV_OK)&&(out_vec_##TYPE.size()==3)&&           \
           (out_vec_##TYPE[0]==123)&&(out_vec_##TYPE[2]==789)); \
  } while(0)
Referenced by check_field_vec_convert().
#define TEST_VEC_CONVERT_BLANK (TYPE)
Value:
do {                       \
    std::vector<TYPE> out_vec_##TYPE;                           \
    rv=col.get(&out_vec_##TYPE,',');                            \
    assert((rv==TSV_OK)&&(out_vec_##TYPE.size()==0));           \
  } while (0)
Referenced by check_field_vec_convert().
Function Documentation
void check_comment_1 ()
Definition at line 717 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::headersBegin(), affx::TsvFileHeaderLine::m_key, affx::TsvFileHeaderLine::m_value, affx::TsvFile::nextHeaderPtr(), affx::TsvFile::open(), affx::TSV_OK, affx::TsvFile::writeFileComment(), and affx::TsvFile::writeTsv().
Referenced by main().
void check_countchars ()
Check splitstr works.
Definition at line 122 of file tsv-test.cpp.
References affx::countchars().
Referenced by main().
void check_csv_1 ()
Check the reading of a Comma Seperated Value file.
Definition at line 819 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::countTotalDataLines(), affx::TsvFile::get(), affx::TsvFile::isEmpty(), affx::TsvFile::isNull(), affx::TsvFile::lineLevel(), affx::TsvFile::nextLevel(), affx::TsvFile::nextLine(), affx::TsvFile::open(), and affx::TSV_OK.
Referenced by main().
void check_dequote ()
Check that dequoting works as expected.
Definition at line 103 of file tsv-test.cpp.
References CHECK_DEQUOTE.
Referenced by main().
void check_empty ()
Definition at line 248 of file tsv-test.cpp.
References affx::TsvFileField::clear(), affx::TsvFileField::isEmpty(), affx::TsvFileField::isNull(), and affx::TsvFileField::setBuffer().
Referenced by main().
void check_escapeString ()
Definition at line 165 of file tsv-test.cpp.
References affx::escapeChar(), and affx::escapeString().
Referenced by main().
void check_field_convert ()
Check the conversion of a field buffer.
Definition at line 270 of file tsv-test.cpp.
References affx::TsvFileField::clear(), affx::TsvFileField::get(), affx::TsvFileField::setBuffer(), affx::TSV_ERR_CONVERSION, and affx::TSV_OK.
Referenced by main().
void check_field_name ()
Check that the column name functions work.
Definition at line 190 of file tsv-test.cpp.
References affx::TsvFile::cname2cidx(), affx::TsvFile::defineColumn(), affx::TSV_ERR_NOTFOUND, and affx::TSV_OPT_CASEINSENSTIVE.
Referenced by main().
void check_field_vec_convert ()
Definition at line 367 of file tsv-test.cpp.
References affx::TsvFileField::clear(), affx::TsvFileField::get(), affx::TsvFileField::m_buffer, affx::TsvFileField::set(), affx::TsvFileField::setBuffer(), affx::TsvFileField::setPrecision(), TEST_VEC_CONVERT_123, TEST_VEC_CONVERT_BLANK, and affx::TSV_OK.
Referenced by main().
void check_headers_1 ()
Check that the headers work.
Definition at line 496 of file tsv-test.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::addHeaderComment(), affx::TsvFile::getHeader(), affx::TsvFile::getHeaderAppend(), affx::TsvFile::getHeaderMatchingKeySubstr(), affx::TsvFile::getHeaderMatchingKeySubstrAppend(), affx::TsvFile::hasHeaderEqualTo(), affx::TsvFile::headersBegin(), affx::TsvFile::headersFindNext(), affx::TsvFile::headersNext(), affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
Referenced by main().
void check_headers_2 ()
Check the behavior of headers.
Definition at line 646 of file tsv-test.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::addHeaderComment(), affx::TsvFile::close(), affx::TsvFile::getHeader(), affx::TsvFile::headerCount(), affx::TsvFile::resortHeaders(), affx::TSV_ERR_NOTFOUND, affx::TSV_OK, and affx::TsvFile::writeTsv().
Referenced by main().
void check_headers_3 ()
Check the behavior of headers.
Definition at line 750 of file tsv-test.cpp.
References affx::TsvFile::addHeader(), CH2_CNT, affx::TsvFile::headersBegin(), affx::TsvFile::headersFindNext(), and affx::TSV_OK.
Referenced by main().
void check_headers_4 ()
Definition at line 777 of file tsv-test.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::deleteHeaders(), and affx::TsvFile::headersCount().
Referenced by main().
void check_index_1 ()
Check that indexes work.
Definition at line 909 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::defineIndex(), affx::TsvFile::findBegin(), affx::TsvFile::findNext(), affx::TsvFile::get(), affx::TsvFile::open(), affx::TSV_FIND_LAST, affx::TSV_INDEX_INT, affx::TSV_OK, and affx::TSV_OP_EQ.
Referenced by main().
void check_line_count ()
Definition at line 1117 of file tsv-test.cpp.
References affx::TsvFile::getLineCountInFile().
Referenced by main().
void check_nextline ()
Check that next line skips comments.
Definition at line 892 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::lineLevel(), affx::TsvFile::lineNumber(), affx::TsvFile::nextLine(), affx::TsvFile::open(), and affx::TSV_OK.
void check_read_colvec_1 ()
Definition at line 1080 of file tsv-test.cpp.
References affx::TsvFile::extractColToVec().
Referenced by main().
void check_read_pgf_1 ()
Definition at line 1096 of file tsv-test.cpp.
References affx::PgfFile::close(), affx::PgfFile::next_atom(), affx::PgfFile::next_probe(), affx::PgfFile::next_probeset(), affx::PgfFile::open(), affx::PgfFile::rewind(), and affx::TSV_OK.
Referenced by main().
void check_read_table_1 ()
Check table reading.
Definition at line 617 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::countTotalDataLines(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), affx::TsvFile::lineLevel(), affx::TsvFile::nextLevel(), affx::TsvFile::openTable(), and affx::TSV_OK.
Referenced by main().
void check_read_vec_1 ()
Definition at line 971 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::get(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), and affx::TSV_OK.
Referenced by main().
void check_replace ()
Definition at line 1142 of file tsv-test.cpp.
References affx::TsvFile::getLineCountInFile(), affx::TsvFile::replaceCharInFile(), and affx::TSV_OK.
Referenced by main().
void check_splitstr ()
Check splitstr works.
Definition at line 143 of file tsv-test.cpp.
References affx::splitstr().
Referenced by main().
void check_splitstr_print (std::vector< std::string > & strvec)
print the results of splitstr
Parameters:
strvec
Definition at line 133 of file tsv-test.cpp.
void check_tolower ()
Definition at line 82 of file tsv-test.cpp.
References affx::tolower().
Referenced by main().
void check_trim ()
Check that the tsv->trim methods work.
Definition at line 43 of file tsv-test.cpp.
References affx::ltrim(), affx::rtrim(), and affx::trim().
Referenced by main().
void check_winpath_1 ()
Check that we can read a windows path name.
Definition at line 951 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::get(), affx::TsvFile::m_optEscapeOk, affx::TsvFile::nextLevel(), affx::TsvFile::open(), and affx::TSV_OK.
Referenced by main().
void check_write_10 ()
Definition at line 1016 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::defineColumn(), affx::TsvFile::flush(), affx::TsvFile::set(), affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv_v1().
Referenced by main().
void check_write_vec_1 ()
Definition at line 1031 of file tsv-test.cpp.
References affx::TsvFile::close(), affx::TsvFile::defineColumn(), affx::TsvFile::set(), affx::TsvFile::setPrecision(), affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv_v1().
Referenced by main().
int main (int argc, char * argv[])
Main function to call all the check tests.
Parameters:
argc count
argv strings
Returns:
error code
Definition at line 1161 of file tsv-test.cpp.
References check_comment_1(), check_countchars(), check_csv_1(), check_dequote(), check_empty(), check_escapeString(), check_field_convert(), check_field_name(), check_field_vec_convert(), check_headers_1(), check_headers_2(), check_headers_3(), check_headers_4(), check_index_1(), check_line_count(), check_read_colvec_1(), check_read_pgf_1(), check_read_table_1(), check_read_vec_1(), check_replace(), check_splitstr(), check_tolower(), check_trim(), check_winpath_1(), check_write_10(), and check_write_vec_1().