Affymetrix Fusion SDK: C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPFileUpdater.cpp File Reference
CalvinCHPFileUpdater.cpp File Reference
#include "calvin_files/writers/src/CalvinCHPFileUpdater.h"
#include "calvin_files/parsers/src/CHPMultiDataFileReader.h"
#include "calvin_files/writers/src/FileOutput.h"
#include "file/FileIO.h"
#include "util/Err.h"
#include "util/Util.h"
#include <cstring>
#include <string.h>
Defines
#define ENTRY_DATA_SET 0
#define ENTRY_DATA_GROUP 0
#define NAME_COLUMN 0
#define ENTRY_COLUMN 1
Functions
static int GetMetricBufferSize (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > &metrics)
static void CopyMetricToBuffer (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > &metrics, char *&pbuffer)
Define Documentation
#define ENTRY_COLUMN 1
Definition at line 45 of file CalvinCHPFileUpdater.cpp.
Referenced by affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantification(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataExpressionEntry(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntry().
#define ENTRY_DATA_GROUP 0
The data group index.
Definition at line 41 of file CalvinCHPFileUpdater.cpp.
Referenced by affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantification(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntry(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer().
#define ENTRY_DATA_SET 0
The data set index.
Definition at line 38 of file CalvinCHPFileUpdater.cpp.
Referenced by affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantification(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntry(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer().
#define NAME_COLUMN 0
Probetset name and signal columns.
Definition at line 44 of file CalvinCHPFileUpdater.cpp.
Referenced by affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataAllelePeaksEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCopyNumberVariationRegionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCytoGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCytoRegionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataExpressionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataMarkerABSignalsEntryBuffer().
Function Documentation
static void CopyMetricToBuffer (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > & metrics, char *& pbuffer) [static]
Definition at line 207 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), MmSetFloat_N(), MmSetUInt16_N(), and MmSetUInt32_N().
Referenced by affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer().
static int GetMetricBufferSize (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > & metrics) [static]
Definition at line 153 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8().
Referenced by affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer().