Affymetrix Fusion SDK: C:/f112/affy/sdk/file/MDLFileData.cpp File Reference
MDLFileData.cpp File Reference
#include "file/MDLFileData.h"
#include "file/FileIO.h"
#include "file/FileWriter.h"
#include <cassert>
#include <cstring>
#include <ctime>
#include <fstream>
#include <istream>
#include <string.h>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>
Functions
static void SwapToLittleEndian (MDLData &data)
static void SwapFromLittleEndian (MDLData &data)
static void SwapToLittleEndian (MDLHeader &header)
static void SwapFromLittleEndian (MDLHeader &header)
Function Documentation
static void SwapFromLittleEndian (MDLData & data) [static]
Definition at line 66 of file MDLFileData.cpp.
References SwapToLittleEndian().
Referenced by affxmdl::CMDLFileData::ReadFile(), and affxmdl::CMDLFileData::ReadFileHeader().
static void SwapFromLittleEndian (MDLHeader & header) [static]
Definition at line 83 of file MDLFileData.cpp.
References SwapToLittleEndian().
static void SwapToLittleEndian (MDLHeader & header) [static]
Definition at line 73 of file MDLFileData.cpp.
References affxmdl::_MDLHeader::bMasked, MmGetInt32_I(), affxmdl::_MDLHeader::nAnalysisType, affxmdl::_MDLHeader::nNumProbes, and affxmdl::_MDLHeader::nVersion.
static void SwapToLittleEndian (MDLData & data) [static]
Definition at line 46 of file MDLFileData.cpp.
References affxmdl::_MDLData::Affinity, MmGetFloat_I(), affxmdl::_MDLData::Offset, affxmdl::_MDLData::RelativeBkg, and affxmdl::_MDLData::Saturation.
Referenced by SwapFromLittleEndian(), and affxmdl::CMDLFileData::Write().