Affymetrix Fusion SDK: C:/f112/affy/sdk/util/apt-check-mixedfile.cpp File Reference
apt-check-mixedfile.cpp File Reference
#include "util/MixedFileCheck.h"
#include "util/PgOptions.h"
#include "util/RegressionCheck.h"
#include "util/Util.h"
#include "util/Verbose.h"
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
Functions
int main (int argc, char *argv[])
Variables
const int passed = 0
const int failed = 1
Function Documentation
int main (int argc, char * argv[])
Definition at line 37 of file apt-check-mixedfile.cpp.
References PgOpt::BOOL_OPT, MixedFileCheck::check(), PgOptions::defineOption(), PgOpt::DOUBLE_OPT, failed, PgOptions::get(), PgOptions::getBool(), PgOptions::getDouble(), PgOptions::getInt(), PgOpt::INT_OPT, Verbose::out(), PgOptions::parseArgv(), passed, PgOptions::setUsage(), PgOpt::STRING_OPT, and PgOptions::usage().
Variable Documentation
const int failed = 1
Definition at line 35 of file apt-check-mixedfile.cpp.
const int passed = 0
Definition at line 34 of file apt-check-mixedfile.cpp.