Affymetrix Fusion SDK: SQLiteRecordset Class Reference
SQLiteRecordset Class Reference
#include <SQLite.h>
Public Member Functions
SQLiteRecordset (SQLiteDatabase &db)
virtual ~SQLiteRecordset ()
void open (const std::string &strSQL)
void close ()
bool fetch ()
std::string getString (int iColumnIndex)
int getInteger (int iColumnIndex)
double getDouble (int iColumnIndex)
Protected Attributes
SQLiteDatabase * m_pdb
sqlite3_stmt * m_pstmt
bool m_bFirstRow
bool m_bEOF
bool m_bOpen
Detailed Description
SQLiteRecordset - Class for handling query result sets.
Definition at line 63 of file SQLite.h.
Constructor & Destructor Documentation
SQLiteRecordset::SQLiteRecordset (SQLiteDatabase & db)
Constructs a SQLiteRecordset object.
Parameters:
pdb - The pointer to the SQLiteDatabase.
Definition at line 219 of file SQLite.cpp.
References m_bEOF, m_bFirstRow, m_bOpen, and m_pdb.
SQLiteRecordset::~SQLiteRecordset () [virtual]
Destroys a SQLiteRecordset object. Closes the recordset if left open.
Definition at line 231 of file SQLite.cpp.
References close().
Member Function Documentation
void SQLiteRecordset::close (void)
Closes the SQLiterecordset.
Definition at line 253 of file SQLite.cpp.
References m_bFirstRow, m_bOpen, and m_pstmt.
Referenced by SQLiteDatabase::test(), and ~SQLiteRecordset().
bool SQLiteRecordset::fetch ()
Steps through the result set from a prepared SQL statement.
Returns:
- bool true if more rows to fetch, or false if the end of the recordset has been reached.
Definition at line 269 of file SQLite.cpp.
References m_bEOF, and m_pstmt.
Referenced by SQLiteDatabase::test().
double SQLiteRecordset::getDouble (int iColumnIndex)
Get a Double value from the recordset.
Parameters:
iColumnIndex - The zero based index of the column.
Returns:
- Double value retrieved from column.
Definition at line 304 of file SQLite.cpp.
References m_pstmt.
int SQLiteRecordset::getInteger (int iColumnIndex)
Get an integer value from the recordset.
Parameters:
iColumnIndex - The zero based index of the column.
Returns:
- integer value retrieved from column.
Definition at line 294 of file SQLite.cpp.
References m_pstmt.
Referenced by SQLiteDatabase::test().
std::string SQLiteRecordset::getString (int iColumnIndex)
Get a String value from the recordset.
Parameters:
iColumnIndex - The zero based index of the column.
Returns:
- String value retrieved from column.
Definition at line 281 of file SQLite.cpp.
References m_pstmt.
Referenced by SQLiteDatabase::test().
void SQLiteRecordset::open (const std::string & strSQL)
Prepares a SQL statement.
Parameters:
strSQL - The SQL statement.
Definition at line 240 of file SQLite.cpp.
References SQLiteDatabase::error(), SQLiteDatabase::getConnection(), m_bEOF, m_bFirstRow, m_bOpen, m_pdb, and m_pstmt.
Referenced by SQLiteDatabase::test().
Member Data Documentation
bool SQLiteRecordset::m_bEOF [protected]
Definition at line 69 of file SQLite.h.
Referenced by fetch(), open(), and SQLiteRecordset().
bool SQLiteRecordset::m_bFirstRow [protected]
Definition at line 68 of file SQLite.h.
Referenced by close(), open(), and SQLiteRecordset().
bool SQLiteRecordset::m_bOpen [protected]
Definition at line 70 of file SQLite.h.
Referenced by close(), open(), and SQLiteRecordset().
SQLiteDatabase* SQLiteRecordset::m_pdb [protected]
Definition at line 66 of file SQLite.h.
Referenced by open(), and SQLiteRecordset().
sqlite3_stmt* SQLiteRecordset::m_pstmt [protected]
Definition at line 67 of file SQLite.h.
Referenced by close(), fetch(), getDouble(), getInteger(), getString(), and open().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/SQLite.h
C:/f112/affy/sdk/util/SQLite.cpp