Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPData Class Reference
affymetrix_fusion_io::FusionCHPData Class Reference
#include <FusionCHPData.h>
Public Member Functions
virtual ~FusionCHPData ()
virtual
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()=0
virtual
affymetrix_calvin_io::GenericData * GetGenericData ()=0
virtual
affymetrix_calvin_utilities::AffymetrixGuidType GetObjectName ()=0
affymetrix_calvin_utilities::AffymetrixGuidTypeList FileTypeIdentifiers () const
affymetrix_calvin_utilities::AffymetrixGuidType FileTypeIdentifier ()
Protected Member Functions
void SetFileName (const char *str)
std::string GetFileName () const
virtual bool Read ()=0
virtual bool ReadHeader ()=0
Protected Attributes
std::string filename
affymetrix_calvin_utilities::AffymetrixGuidTypeList fileTypeIdentifiers
affymetrix_calvin_utilities::AffymetrixGuidType fileTypeIdentifier
Friends
class FusionCHPDataReg
Detailed Description
A base class for all CHP data objects.
Definition at line 40 of file FusionCHPData.h.
Constructor & Destructor Documentation
virtual affymetrix_fusion_io::FusionCHPData::~FusionCHPData () [inline, virtual]
Destructor
Definition at line 78 of file FusionCHPData.h.
Member Function Documentation
virtual affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_fusion_io::FusionCHPData::FileId () [pure virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implemented in affymetrix_fusion_io::FusionCHPGenericData, affymetrix_fusion_io::FusionCHPLegacyData, affymetrix_fusion_io::FusionCHPMultiDataData, affymetrix_fusion_io::FusionCHPQuantificationData, affymetrix_fusion_io::FusionCHPQuantificationDetectionData, and affymetrix_fusion_io::FusionCHPTilingData.
Referenced by CFusionCHPDataCOM::get_FileId().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_fusion_io::FusionCHPData::FileTypeIdentifier () [inline]
Gets the file type identifier in the file (blank for GCOS files).
Returns:
The id of the file.
Definition at line 99 of file FusionCHPData.h.
References fileTypeIdentifier.
Referenced by CFusionCHPLegacyDataCOM::get_FileTypeIdentifier(), and CFusionCHPDataCOM::get_FileTypeIdentifier().
affymetrix_calvin_utilities::AffymetrixGuidTypeList affymetrix_fusion_io::FusionCHPData::FileTypeIdentifiers () const [inline]
Gets the file type identifiers associated with the CHP files the reader can parse.
Returns:
The ids
Definition at line 94 of file FusionCHPData.h.
References fileTypeIdentifiers.
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_FileTypeIdentifiers(), CFusionCHPQuantificationDataCOM::get_FileTypeIdentifiers(), CFusionCHPLegacyDataCOM::get_FileTypeIdentifiers(), and CFusionCHPDataCOM::get_FileTypeIdentifiers().
std::string affymetrix_fusion_io::FusionCHPData::GetFileName () const [inline, protected]
Gets the file name.
Returns:
The file name.
Definition at line 52 of file FusionCHPData.h.
References filename.
virtual affymetrix_calvin_io::GenericData* affymetrix_fusion_io::FusionCHPData::GetGenericData () [pure virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implemented in affymetrix_fusion_io::FusionCHPGenericData, affymetrix_fusion_io::FusionCHPLegacyData, affymetrix_fusion_io::FusionCHPMultiDataData, affymetrix_fusion_io::FusionCHPQuantificationData, affymetrix_fusion_io::FusionCHPQuantificationDetectionData, and affymetrix_fusion_io::FusionCHPTilingData.
virtual affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_fusion_io::FusionCHPData::GetObjectName () [pure virtual]
Gets the class name.
Implemented in affymetrix_fusion_io::FusionCHPGenericData, affymetrix_fusion_io::FusionCHPLegacyData, affymetrix_fusion_io::FusionCHPMultiDataData, affymetrix_fusion_io::FusionCHPQuantificationData, affymetrix_fusion_io::FusionCHPQuantificationDetectionData, and affymetrix_fusion_io::FusionCHPTilingData.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::FromBase(), affymetrix_fusion_io::FusionCHPQuantificationDetectionData::FromBase(), affymetrix_fusion_io::FusionCHPQuantificationData::FromBase(), affymetrix_fusion_io::FusionCHPMultiDataData::FromBase(), affymetrix_fusion_io::FusionCHPLegacyData::FromBase(), and affymetrix_fusion_io::FusionCHPGenericData::FromBase().
virtual bool affymetrix_fusion_io::FusionCHPData::Read () [protected, pure virtual]
Reads the contents of the file.
Returns:
True if successfully read.
Implemented in affymetrix_fusion_io::FusionCHPGenericData, affymetrix_fusion_io::FusionCHPLegacyData, affymetrix_fusion_io::FusionCHPMultiDataData, affymetrix_fusion_io::FusionCHPQuantificationData, affymetrix_fusion_io::FusionCHPQuantificationDetectionData, and affymetrix_fusion_io::FusionCHPTilingData.
Referenced by affymetrix_fusion_io::FusionCHPDataReg::Read().
virtual bool affymetrix_fusion_io::FusionCHPData::ReadHeader () [protected, pure virtual]
Reads the header.
Returns:
True if successfully read.
Implemented in affymetrix_fusion_io::FusionCHPGenericData, affymetrix_fusion_io::FusionCHPLegacyData, affymetrix_fusion_io::FusionCHPMultiDataData, affymetrix_fusion_io::FusionCHPQuantificationData, affymetrix_fusion_io::FusionCHPQuantificationDetectionData, and affymetrix_fusion_io::FusionCHPTilingData.
Referenced by affymetrix_fusion_io::FusionCHPDataReg::ReadHeader().
void affymetrix_fusion_io::FusionCHPData::SetFileName (const char * str) [inline, protected]
Sets the file name.
Parameters:
str The file name.
Definition at line 47 of file FusionCHPData.h.
References filename.
Referenced by affymetrix_fusion_io::FusionCHPDataReg::Read(), and affymetrix_fusion_io::FusionCHPDataReg::ReadHeader().
Friends And Related Function Documentation
friend class FusionCHPDataReg [friend]
Friend to the registration class as it will call the Read function.
Definition at line 68 of file FusionCHPData.h.
Member Data Documentation
std::string affymetrix_fusion_io::FusionCHPData::filename [protected]
The CHP file name.
Definition at line 55 of file FusionCHPData.h.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::CreateAdapter(), GetFileName(), affymetrix_fusion_io::FusionCHPLegacyData::Read(), affymetrix_fusion_io::FusionCHPLegacyData::ReadHeader(), and SetFileName().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_fusion_io::FusionCHPData::fileTypeIdentifier [protected]
The actual file type identifier in the file.
Definition at line 74 of file FusionCHPData.h.
Referenced by affymetrix_fusion_io::FusionCHPDataReg::CreateObject(), and FileTypeIdentifier().
affymetrix_calvin_utilities::AffymetrixGuidTypeList affymetrix_fusion_io::FusionCHPData::fileTypeIdentifiers [protected]
The file type identifiers associated with the CHP files the reader can parse.
Definition at line 71 of file FusionCHPData.h.
Referenced by affymetrix_fusion_io::FusionCHPDataReg::CreateObject(), and FileTypeIdentifiers().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPData.h