Affymetrix Fusion SDK: affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType Class Reference
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType Class Reference
#include <ParameterNameValueType.h>
Public Types
enum ParameterValueType {
NoParameterType, IntegerParameterType, FloatParameterType, TextParameterType,
DateParameterType, TimeParameterType, DateTimeParameterType, ControlSingleParameterType,
ControlMultiParameterType
}
Public Member Functions
std::list< std::wstring > & ControlMultiValues ()
ParameterValueType & ValueType ()
std::list< std::wstring > & ControlledVocabulary ()
MIMEValue & DefaultMIMEValue ()
bool & RequiredFlag ()
bool & HasDefault ()
ParameterNameValueDefaultRequiredType ()
ParameterNameValueDefaultRequiredType (const std::wstring &name, const void *mimeValue, int32_t mimeValueSize, const std::wstring &mimeType, const void *defaultMimeValue, int32_t defaultMimeValueSize, bool req)
ParameterNameValueDefaultRequiredType (const std::wstring &name, const MIMEValue &mimeValue, const std::wstring &mimeType, const MIMEValue &defaultMimeValue, bool req)
ParameterNameValueDefaultRequiredType operator= (const ParameterNameValueDefaultRequiredType &param)
std::wstring DefaultToString ()
int8_t GetDefaultValueInt8 () const
void SetDefaultValueInt8 (int8_t value)
u_int8_t GetDefaultValueUInt8 () const
void SetDefaultValueUInt8 (u_int8_t value)
int16_t GetDefaultValueInt16 () const
void SetDefaultValueInt16 (int16_t value)
u_int16_t GetDefaultValueUInt16 () const
void SetDefaultValueUInt16 (u_int16_t value)
int32_t GetDefaultValueInt32 () const
void SetDefaultValueInt32 (int32_t value)
u_int32_t GetDefaultValueUInt32 () const
void SetDefaultValueUInt32 (u_int32_t value)
float GetDefaultValueFloat () const
void SetDefaultValueFloat (float value)
std::wstring GetDefaultValueText () const
void SetDefaultValueText (const std::wstring &value, int32_t reserve=-1)
std::string GetDefaultValueAscii () const
void SetDefaultValueAscii (const std::string &value, int32_t reserve=-1)
Static Public Member Functions
static std::wstring ParameterValueTypeToString (ParameterValueType value)
static ParameterValueType ParameterValueTypeFromString (const std::wstring &value)
Protected Member Functions
u_int32_t DefaultValueToInt (const wchar_t *mimeType) const
void IntToDefaultValue (u_int32_t value, const wchar_t *type)
void SetParameterType ()
Protected Attributes
MIMEValue defaultValue
bool hasDefault
bool required
std::list< std::wstring > controlled
std::list< std::wstring > controlMultiValues
ParameterValueType valueType
Detailed Description
A class to hold a name/value/type/default/required attributes.
Definition at line 364 of file ParameterNameValueType.h.
Member Enumeration Documentation
enum affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ParameterValueType
The type of value.
Enumerator:
NoParameterType
IntegerParameterType
Not set.
FloatParameterType
Integer stored in the MIME value.
TextParameterType
Floating point stored in the MIME value.
DateParameterType
Text stored in the MIME value.
TimeParameterType
Date stored in the MIME value as text.
DateTimeParameterType
Time stored in the MIME value as text.
ControlSingleParameterType
DateTime stored in the MIME value as text.
ControlMultiParameterType
Controlled single selection stored in the MIME value as text.
Controlled multi selection stored in the controlMulti list.
Definition at line 368 of file ParameterNameValueType.h.
Constructor & Destructor Documentation
affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ParameterNameValueDefaultRequiredType () [inline]
Default constructor
Definition at line 458 of file ParameterNameValueType.h.
References hasDefault, NoParameterType, required, and valueType.
ParameterNameValueDefaultRequiredType::ParameterNameValueDefaultRequiredType (const std::wstring & name, const void * mimeValue, int32_t mimeValueSize, const std::wstring & mimeType, const void * defaultMimeValue, int32_t defaultMimeValueSize, bool req)
MIME constructor. Useful when reading in from a file
Parameters:
name Parameter name
mimeValue MIME encoded value in a buffer
mimeValueSize The size in bytes of the MIME encoded value.
mimeType The MIME type.
defaultMimeValue The default MIME encoded value in a buffer.
defaultMimeValueSize The size in bytes of the default MIME encoded value.
req Flag to indicate if the parameter is required.
Definition at line 499 of file ParameterNameValueType.cpp.
ParameterNameValueDefaultRequiredType::ParameterNameValueDefaultRequiredType (const std::wstring & name, const MIMEValue & mimeValue, const std::wstring & mimeType, const MIMEValue & defaultMimeValue, bool req)
MIME constructor. Useful when reading in from a file
Parameters:
name Parameter name
mimeValue MIME encoded value
mimeType The MIME type.
defaultMimeValue The default MIME encoded value in a buffer.
req Flag to indicate if the parameter is required.
Definition at line 523 of file ParameterNameValueType.cpp.
Member Function Documentation
std::list<std::wstring>& affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlledVocabulary () [inline]
A list of parameter values for controlled vocabulary.
Returns:
The list of parameter values for controlled vocabulary.
Definition at line 440 of file ParameterNameValueType.h.
References controlled.
Referenced by AddUserAttributes(), and affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttributeControl().
std::list<std::wstring>& affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlMultiValues () [inline]
A list of multi-selected controlled values.
Returns:
The multi-selected controlled values.
Definition at line 432 of file ParameterNameValueType.h.
References controlMultiValues.
Referenced by AddUserAttributes(), affymetrix_calvin_io::SAXTemplateHandlers::characters(), and affymetrix_calvin_io::SAXArrayHandlers::characters().
MIMEValue& affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::DefaultMIMEValue () [inline]
Returns the mime value without interpretation.
Returns:
MIME encoded string.
Definition at line 445 of file ParameterNameValueType.h.
References defaultValue.
std::wstring ParameterNameValueDefaultRequiredType::DefaultToString ()
Converts default value to a string
Returns:
A string representation of the default value
Definition at line 416 of file ParameterNameValueType.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::AsciiType, affymetrix_calvin_parameter::ParameterNameValueType::FloatType, FormatString1, GetDefaultValueAscii(), GetDefaultValueFloat(), GetDefaultValueInt16(), GetDefaultValueInt32(), GetDefaultValueInt8(), GetDefaultValueText(), GetDefaultValueUInt16(), GetDefaultValueUInt32(), GetDefaultValueUInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::Int16Type, affymetrix_calvin_parameter::ParameterNameValueType::Int32Type, affymetrix_calvin_parameter::ParameterNameValueType::Int8Type, affymetrix_calvin_parameter::ParameterNameValueType::TextType, affymetrix_calvin_parameter::ParameterNameValueType::UInt16Type, affymetrix_calvin_parameter::ParameterNameValueType::UInt32Type, and affymetrix_calvin_parameter::ParameterNameValueType::UInt8Type.
Referenced by AddUserAttributes().
u_int32_t ParameterNameValueDefaultRequiredType::DefaultValueToInt (const wchar_t * mimeType) const [protected]
Converts a value to an integer.
Parameters:
mimeType The string representation.
Returns:
The integer representation.
Definition at line 736 of file ParameterNameValueType.cpp.
References defaultValue, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_parameter::MIMEValue::GetValue(), affymetrix_calvin_parameter::ParameterNameValueType::ToString(), and affymetrix_calvin_parameter::ParameterNameValueType::Type.
Referenced by GetDefaultValueFloat(), GetDefaultValueInt16(), GetDefaultValueInt32(), GetDefaultValueInt8(), GetDefaultValueUInt16(), GetDefaultValueUInt32(), and GetDefaultValueUInt8().
std::string ParameterNameValueDefaultRequiredType::GetDefaultValueAscii () const
Ges the default value as a string
Returns:
Value of the parameter as an string
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a text type
Definition at line 694 of file ParameterNameValueType.cpp.
References AsciiMIMEType, defaultValue, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_parameter::MIMEValue::GetValue(), affymetrix_calvin_parameter::ParameterNameValueType::ToString(), and affymetrix_calvin_parameter::ParameterNameValueType::Type.
Referenced by DefaultToString().
float ParameterNameValueDefaultRequiredType::GetDefaultValueFloat () const
Ges the default value as a float
Returns:
Value of the parameter as an float
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a float
Definition at line 624 of file ParameterNameValueType.cpp.
References DefaultValueToInt(), FloatMIMEType, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_parameter::ParameterNameValueType::ToString(), and affymetrix_calvin_parameter::ParameterNameValueType::Type.
Referenced by DefaultToString().
int16_t ParameterNameValueDefaultRequiredType::GetDefaultValueInt16 () const
Ges the default value as a int16_t
Returns:
Value of the parameter as an int16_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not an int16_t
Definition at line 580 of file ParameterNameValueType.cpp.
References DefaultValueToInt(), and Int16MIMEType.
Referenced by DefaultToString().
int32_t ParameterNameValueDefaultRequiredType::GetDefaultValueInt32 () const
Ges the default value as a int32_t
Returns:
Value of the parameter as an int32_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not an int32_t
Definition at line 602 of file ParameterNameValueType.cpp.
References DefaultValueToInt(), and Int32MIMEType.
Referenced by DefaultToString().
int8_t ParameterNameValueDefaultRequiredType::GetDefaultValueInt8 () const
Gets default value as a int8_t
Returns:
Value of the parameter as an int8_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not an int8_t
Definition at line 558 of file ParameterNameValueType.cpp.
References DefaultValueToInt(), and Int8MIMEType.
Referenced by DefaultToString().
std::wstring ParameterNameValueDefaultRequiredType::GetDefaultValueText () const
Ges the default value as a wstring
Returns:
Value of the parameter as an wstring
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a text type
Definition at line 648 of file ParameterNameValueType.cpp.
References defaultValue, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_parameter::MIMEValue::GetValue(), TextMIMEType, affymetrix_calvin_parameter::ParameterNameValueType::ToString(), and affymetrix_calvin_parameter::ParameterNameValueType::Type.
Referenced by DefaultToString().
u_int16_t ParameterNameValueDefaultRequiredType::GetDefaultValueUInt16 () const
Ges the default value as a u_int16_t
Returns:
Value of the parameter as an u_int16_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a u_int16_t
Definition at line 591 of file ParameterNameValueType.cpp.
References DefaultValueToInt(), and UInt16MIMEType.
Referenced by DefaultToString().
u_int32_t ParameterNameValueDefaultRequiredType::GetDefaultValueUInt32 () const
Ges the default value as a u_int32_t
Returns:
Value of the parameter as an u_int32_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a u_int32_t
Definition at line 613 of file ParameterNameValueType.cpp.
References DefaultValueToInt(), and UInt32MIMEType.
Referenced by DefaultToString().
u_int8_t ParameterNameValueDefaultRequiredType::GetDefaultValueUInt8 () const
Ges the default value as a u_int8_t
Returns:
Value of the parameter as an u_int8_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a u_int8_t
Definition at line 569 of file ParameterNameValueType.cpp.
References DefaultValueToInt(), and UInt8MIMEType.
Referenced by DefaultToString().
bool& affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::HasDefault () [inline]
A flag to indicate if a default exist.
Returns:
The flag indicating if a default value exists.
Definition at line 455 of file ParameterNameValueType.h.
References hasDefault.
Referenced by AddUserAttributes().
void ParameterNameValueDefaultRequiredType::IntToDefaultValue (u_int32_t value, const wchar_t * type) [protected]
Converts an integer to a value.
Parameters:
value The integer representation.
type The string representation.
Definition at line 754 of file ParameterNameValueType.cpp.
References defaultValue, NUMBER_BUFFER_LEN, affymetrix_calvin_parameter::MIMEValue::SetValue(), and affymetrix_calvin_parameter::ParameterNameValueType::Type.
Referenced by SetDefaultValueFloat(), SetDefaultValueInt16(), SetDefaultValueInt32(), SetDefaultValueInt8(), SetDefaultValueUInt16(), SetDefaultValueUInt32(), and SetDefaultValueUInt8().
ParameterNameValueDefaultRequiredType ParameterNameValueDefaultRequiredType::operator= (const ParameterNameValueDefaultRequiredType & param)
A copy operator.
Parameters:
param The parameter to copy.
Definition at line 544 of file ParameterNameValueType.cpp.
References controlled, controlMultiValues, defaultValue, hasDefault, affymetrix_calvin_parameter::ParameterNameValueType::Name, required, affymetrix_calvin_parameter::ParameterNameValueType::Type, affymetrix_calvin_parameter::ParameterNameValueType::Value, and valueType.
ParameterNameValueDefaultRequiredType::ParameterValueType ParameterNameValueDefaultRequiredType::ParameterValueTypeFromString (const std::wstring & value) [static]
Converts the string to a type.
Parameters:
value The string representation.
Returns:
The type.
Definition at line 806 of file ParameterNameValueType.cpp.
References ControlMultiParameterType, ControlSingleParameterType, DateParameterType, DateTimeParameterType, FloatParameterType, IntegerParameterType, NoParameterType, TextParameterType, and TimeParameterType.
std::wstring ParameterNameValueDefaultRequiredType::ParameterValueTypeToString (ParameterValueType value) [static]
Converts the type to a string.
Parameters:
value The type.
Returns:
The string representation.
Definition at line 767 of file ParameterNameValueType.cpp.
References ControlMultiParameterType, ControlSingleParameterType, DateParameterType, DateTimeParameterType, FloatParameterType, IntegerParameterType, NoParameterType, TextParameterType, and TimeParameterType.
bool& affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::RequiredFlag () [inline]
Gets the required flag.
Returns:
The required flag.
Definition at line 450 of file ParameterNameValueType.h.
References required.
Referenced by AddUserAttributes(), and affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute().
void ParameterNameValueDefaultRequiredType::SetDefaultValueAscii (const std::string & value, int32_t reserve = -1)
Sets the default value as a text type.
Parameters:
value String representation of the default value.
reserve The total number of characters to reserve for the value. -1 indicates not to reserve any extra space.
Definition at line 715 of file ParameterNameValueType.cpp.
References AsciiMIMEType, defaultValue, hasDefault, affymetrix_calvin_parameter::MIMEValue::SetValue(), and affymetrix_calvin_parameter::ParameterNameValueType::Type.
void ParameterNameValueDefaultRequiredType::SetDefaultValueFloat (float value)
Sets the default value as a float
Parameters:
value The value
Definition at line 640 of file ParameterNameValueType.cpp.
References FloatMIMEType, hasDefault, IntToDefaultValue(), type_punned::v_float, and type_punned::v_int32.
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute().
void ParameterNameValueDefaultRequiredType::SetDefaultValueInt16 (int16_t value)
Sets the default value as an int16_t
Parameters:
value The value
Definition at line 585 of file ParameterNameValueType.cpp.
References hasDefault, Int16MIMEType, and IntToDefaultValue().
void ParameterNameValueDefaultRequiredType::SetDefaultValueInt32 (int32_t value)
Sets the default value as an int32_t
Parameters:
value The value
Definition at line 607 of file ParameterNameValueType.cpp.
References hasDefault, Int32MIMEType, and IntToDefaultValue().
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute().
void ParameterNameValueDefaultRequiredType::SetDefaultValueInt8 (int8_t value)
Sets the default value as an int8_t
Parameters:
value The value
Definition at line 563 of file ParameterNameValueType.cpp.
References hasDefault, Int8MIMEType, and IntToDefaultValue().
void ParameterNameValueDefaultRequiredType::SetDefaultValueText (const std::wstring & value, int32_t reserve = -1)
Sets the default value as a text type.
Parameters:
value String representation of the default value.
reserve The total number of characters to reserve for the value. -1 indicates not to reserve any extra space.
Definition at line 673 of file ParameterNameValueType.cpp.
References defaultValue, hasDefault, affymetrix_calvin_parameter::MIMEValue::SetValue(), TextMIMEType, and affymetrix_calvin_parameter::ParameterNameValueType::Type.
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute().
void ParameterNameValueDefaultRequiredType::SetDefaultValueUInt16 (u_int16_t value)
Sets the default value as a u_int16_t
Parameters:
value The value
Definition at line 596 of file ParameterNameValueType.cpp.
References hasDefault, IntToDefaultValue(), and UInt16MIMEType.
void ParameterNameValueDefaultRequiredType::SetDefaultValueUInt32 (u_int32_t value)
Sets the default value as a u_int32_t
Parameters:
value The value
Definition at line 618 of file ParameterNameValueType.cpp.
References hasDefault, IntToDefaultValue(), and UInt32MIMEType.
void ParameterNameValueDefaultRequiredType::SetDefaultValueUInt8 (u_int8_t value)
Sets the default value as a u_int8_t
Parameters:
value The value
Definition at line 574 of file ParameterNameValueType.cpp.
References hasDefault, IntToDefaultValue(), and UInt8MIMEType.
void ParameterNameValueDefaultRequiredType::SetParameterType () [protected]
Sets the parameter type.
Definition at line 467 of file ParameterNameValueType.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::AsciiType, FloatParameterType, affymetrix_calvin_parameter::ParameterNameValueType::FloatType, affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::Int16Type, affymetrix_calvin_parameter::ParameterNameValueType::Int32Type, affymetrix_calvin_parameter::ParameterNameValueType::Int8Type, IntegerParameterType, TextParameterType, affymetrix_calvin_parameter::ParameterNameValueType::TextType, affymetrix_calvin_parameter::ParameterNameValueType::UInt16Type, affymetrix_calvin_parameter::ParameterNameValueType::UInt32Type, affymetrix_calvin_parameter::ParameterNameValueType::UInt8Type, and valueType.
ParameterValueType& affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ValueType () [inline]
The type of value stored.
Definition at line 435 of file ParameterNameValueType.h.
References valueType.
Referenced by AddUserAttributes(), affymetrix_calvin_io::SAXTemplateHandlers::characters(), affymetrix_calvin_io::SAXArrayHandlers::characters(), and affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute().
Member Data Documentation
std::list<std::wstring> affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::controlled [protected]
A list of parameter values for controlled vocabulary.
Definition at line 404 of file ParameterNameValueType.h.
Referenced by ControlledVocabulary(), and operator=().
std::list<std::wstring> affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::controlMultiValues [protected]
A list of multi-selected controlled values.
Definition at line 407 of file ParameterNameValueType.h.
Referenced by ControlMultiValues(), and operator=().
MIMEValue affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::defaultValue [protected]
The MIME value of the default parameter
Definition at line 395 of file ParameterNameValueType.h.
Referenced by DefaultMIMEValue(), DefaultValueToInt(), GetDefaultValueAscii(), GetDefaultValueText(), IntToDefaultValue(), operator=(), SetDefaultValueAscii(), and SetDefaultValueText().
bool affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::hasDefault [protected]
A flag to indicate if a default exist.
Definition at line 398 of file ParameterNameValueType.h.
Referenced by HasDefault(), operator=(), ParameterNameValueDefaultRequiredType(), SetDefaultValueAscii(), SetDefaultValueFloat(), SetDefaultValueInt16(), SetDefaultValueInt32(), SetDefaultValueInt8(), SetDefaultValueText(), SetDefaultValueUInt16(), SetDefaultValueUInt32(), and SetDefaultValueUInt8().
bool affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::required [protected]
A flag to indicate if the parameter is required.
Definition at line 401 of file ParameterNameValueType.h.
Referenced by operator=(), ParameterNameValueDefaultRequiredType(), and RequiredFlag().
ParameterValueType affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::valueType [protected]
The type of value stored.
Definition at line 410 of file ParameterNameValueType.h.
Referenced by operator=(), ParameterNameValueDefaultRequiredType(), SetParameterType(), and ValueType().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parameter/src/ParameterNameValueType.h
C:/f112/affy/sdk/calvin_files/parameter/src/ParameterNameValueType.cpp