Affymetrix Fusion SDK: affx::PgfFile Class Reference
affx::PgfFile Class Reference
#include <PgfFile.h>
Public Member Functions
PgfFile ()
Create the PgfFile object.
~PgfFile ()
Destroy a PgfFile object.
void makePgfBindings ()
Make the normal bindings to the standard PGF slots.
int open (const std::string &filename)
Open a PGF file.
int write (const std::string &filename)
start the write of a PGF file.
int close ()
Close a PGF file.
int rewind ()
Rewind back to the start of the PGF data.
int next_probeset ()
Skip to the next probeset.
int next_atom ()
Skip to the next atom, but not beyond.
int next_probe ()
Skip to the next probe, but not beyond.
int defineFilePgf (TsvFile *tsv)
Define a tsv file as a PGF file.
int defineFilePgf ()
Define this file as a pgf file.
affx::TsvFile * tsv_ptr ()
Get a ptr for SWIG.
Public Attributes
affx::TsvFile m_tsv
If you want to work with the underling tsv: "pgf.m_tsv.method()".
int probeset_id
pgf
std::string probeset_type
pgf
std::string probeset_name
pgf
int atom_id
pgf
int probe_id
pgf
std::string probe_type
pgf
int gc_count
pgf
int probe_length
pgf
int interrogation_position
pgf
std::string probe_sequence
pgf
int exon_position
pgf
Detailed Description
This defines an object which has fields and some methods to make working with PGF files a snap. Basicly we define user friendly method which map to TsvFile mothods.
Definition at line 44 of file PgfFile.h.
Constructor & Destructor Documentation
affx::PgfFile::PgfFile ()
Create the PgfFile object.
Definition at line 281 of file PgfFile.cpp.
References atom_id, gc_count, interrogation_position, makePgfBindings(), probe_id, probe_length, probe_sequence, probe_type, probeset_id, probeset_name, and probeset_type.
affx::PgfFile::~PgfFile ()
Destroy a PgfFile object.
Definition at line 297 of file PgfFile.cpp.
Member Function Documentation
int affx::PgfFile::close ()
Close a PGF file.
Returns:
tsv_return_t
Definition at line 345 of file PgfFile.cpp.
References affx::TsvFile::close(), and m_tsv.
Referenced by check_read_pgf_1(), and example_walk_pgf().
int affx::PgfFile::defineFilePgf (TsvFile * tsv)
Define a tsv file as a PGF file.
Parameters:
tsv pointer to tsv to define
Returns:
tsv_return_t
Definition at line 376 of file PgfFile.cpp.
References Err::check(), and affx::TsvFile::defineFile().
Referenced by example_write_2().
int affx::PgfFile::defineFilePgf ()
Define this file as a pgf file.
Returns:
tsv_return_t
Definition at line 387 of file PgfFile.cpp.
References m_tsv.
void affx::PgfFile::makePgfBindings ()
Make the normal bindings to the standard PGF slots.
Definition at line 302 of file PgfFile.cpp.
References atom_id, affx::TsvFile::bind(), gc_count, interrogation_position, m_tsv, probe_id, probe_length, probe_sequence, probe_type, probeset_id, probeset_name, probeset_type, affx::TSV_BIND_REQUIRED, and affx::TsvFile::unbindAll().
Referenced by PgfFile().
int affx::PgfFile::next_atom ()
Skip to the next atom, but not beyond.
Returns:
TSV_LEVEL_LAST when out of atoms
Definition at line 363 of file PgfFile.cpp.
References m_tsv, and affx::TsvFile::nextLevel().
Referenced by check_read_pgf_1(), and example_walk_pgf().
int affx::PgfFile::next_probe ()
Skip to the next probe, but not beyond.
Returns:
TSV_LEVEL_LAST when out of probes
Definition at line 369 of file PgfFile.cpp.
References m_tsv, and affx::TsvFile::nextLevel().
Referenced by check_read_pgf_1(), and example_walk_pgf().
int affx::PgfFile::next_probeset ()
Skip to the next probeset.
Returns:
TSV_LEVEL_LAST when out of probesets
Definition at line 357 of file PgfFile.cpp.
References m_tsv, and affx::TsvFile::nextLevel().
Referenced by check_read_pgf_1(), and example_walk_pgf().
int affx::PgfFile::open (const std::string & filename)
Open a PGF file.
Parameters:
filename the pathname of the file
Returns:
tsv_return_t
Definition at line 325 of file PgfFile.cpp.
References Err::check(), affx::TsvFile::getHeader(), m_tsv, affx::TsvFile::open(), and affx::TSV_OK.
Referenced by check_read_pgf_1(), example_index_2(), and example_walk_pgf().
int affx::PgfFile::rewind ()
Rewind back to the start of the PGF data.
Returns:
tsv_return_t
Definition at line 351 of file PgfFile.cpp.
References m_tsv, and affx::TsvFile::rewind().
Referenced by check_read_pgf_1().
affx::TsvFile * affx::PgfFile::tsv_ptr ()
Get a ptr for SWIG.
Returns:
a pointer to the internal TSV file object
Definition at line 394 of file PgfFile.cpp.
References m_tsv.
int affx::PgfFile::write (const std::string & filename)
start the write of a PGF file.
Parameters:
filename
Returns:
tsv_return_t
Definition at line 339 of file PgfFile.cpp.
References m_tsv, and affx::TsvFile::writeTsv().
Referenced by example_write_2().
Member Data Documentation
int affx::PgfFile::atom_id
pgf
Definition at line 60 of file PgfFile.h.
Referenced by makePgfBindings(), and PgfFile().
int affx::PgfFile::exon_position
pgf
Definition at line 68 of file PgfFile.h.
int affx::PgfFile::gc_count
pgf
Definition at line 64 of file PgfFile.h.
Referenced by makePgfBindings(), and PgfFile().
int affx::PgfFile::interrogation_position
pgf
Definition at line 66 of file PgfFile.h.
Referenced by makePgfBindings(), and PgfFile().
affx::TsvFile affx::PgfFile::m_tsv
If you want to work with the underling tsv: "pgf.m_tsv.method()".
Definition at line 48 of file PgfFile.h.
Referenced by close(), defineFilePgf(), example_index_2(), example_walk_pgf(), example_write_2(), makePgfBindings(), next_atom(), next_probe(), next_probeset(), open(), rewind(), tsv_ptr(), and write().
int affx::PgfFile::probe_id
pgf
Definition at line 62 of file PgfFile.h.
Referenced by example_index_2(), makePgfBindings(), and PgfFile().
int affx::PgfFile::probe_length
pgf
Definition at line 65 of file PgfFile.h.
Referenced by makePgfBindings(), and PgfFile().
std::string affx::PgfFile::probe_sequence
pgf
Definition at line 67 of file PgfFile.h.
Referenced by example_index_2(), makePgfBindings(), and PgfFile().
std::string affx::PgfFile::probe_type
pgf
Definition at line 63 of file PgfFile.h.
Referenced by makePgfBindings(), and PgfFile().
int affx::PgfFile::probeset_id
pgf
Definition at line 56 of file PgfFile.h.
Referenced by makePgfBindings(), and PgfFile().
std::string affx::PgfFile::probeset_name
pgf
Definition at line 58 of file PgfFile.h.
Referenced by makePgfBindings(), and PgfFile().
std::string affx::PgfFile::probeset_type
pgf
Definition at line 57 of file PgfFile.h.
Referenced by makePgfBindings(), and PgfFile().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/PgfFile.h
C:/f112/affy/sdk/file/TsvFile/PgfFile.cpp