Affymetrix Fusion SDK: CProbeSetMultiDataCytoRegionDataCOM Class Reference
CProbeSetMultiDataCytoRegionDataCOM Class Reference
#include <ProbeSetMultiDataCytoRegionDataCOM.h>
Public Member Functions
CProbeSetMultiDataCytoRegionDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & Data ()
STDMETHOD() get_name (BSTR *pVal)
STDMETHOD() get_chr (int *pVal)
STDMETHOD() get_startPosition (int *pVal)
STDMETHOD() get_stopPosition (int *pVal)
STDMETHOD() get_call (CytoCallType *pVal)
STDMETHOD() get_confidenceScore (float *pVal)
STDMETHOD() get_metricCount (int *pVal)
STDMETHOD() GetMetric (int index, VARIANT *pVal)
STDMETHOD() GetMetricName (int index, BSTR *pVal)
Private Attributes
affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData data
Detailed Description
Definition at line 35 of file ProbeSetMultiDataCytoRegionDataCOM.h.
Constructor & Destructor Documentation
CProbeSetMultiDataCytoRegionDataCOM::CProbeSetMultiDataCytoRegionDataCOM () [inline]
Definition at line 42 of file ProbeSetMultiDataCytoRegionDataCOM.h.
Member Function Documentation
affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData& CProbeSetMultiDataCytoRegionDataCOM::Data () [inline]
Definition at line 73 of file ProbeSetMultiDataCytoRegionDataCOM.h.
Referenced by CFusionCHPMultiDataDataCOM::GetCytoRegionEntry().
HRESULT CProbeSetMultiDataCytoRegionDataCOM::FinalConstruct () [inline]
Definition at line 61 of file ProbeSetMultiDataCytoRegionDataCOM.h.
void CProbeSetMultiDataCytoRegionDataCOM::FinalRelease () [inline]
Definition at line 66 of file ProbeSetMultiDataCytoRegionDataCOM.h.
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::get_call (CytoCallType * pVal)
Definition at line 51 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::get_chr (int * pVal)
Definition at line 63 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::get_confidenceScore (float * pVal)
Definition at line 57 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::get_metricCount (int * pVal)
Definition at line 81 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::get_name (BSTR * pVal)
Definition at line 45 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::get_startPosition (int * pVal)
Definition at line 69 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::get_stopPosition (int * pVal)
Definition at line 75 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::GetMetric (int index, VARIANT * pVal)
Definition at line 94 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
References COMStringUtils::ConvertString(), COMStringUtils::ConvertWString(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8().
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::GetMetricName (int index, BSTR * pVal)
Definition at line 87 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
References COMStringUtils::ConvertWString(), and affymetrix_calvin_parameter::ParameterNameValueType::GetName().
STDMETHODIMP CProbeSetMultiDataCytoRegionDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 30 of file ProbeSetMultiDataCytoRegionDataCOM.cpp.
Member Data Documentation
affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData CProbeSetMultiDataCytoRegionDataCOM::data [private]
Definition at line 71 of file ProbeSetMultiDataCytoRegionDataCOM.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataCytoRegionDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataCytoRegionDataCOM.cpp