Affymetrix Fusion SDK: affxchp::CCHPFileData Class Reference
affxchp::CCHPFileData Class Reference
#include <CHPFileData.h>
Public Member Functions
CCHPFileData ()
~CCHPFileData ()
CCHPFileHeader & GetHeader ()
CExpressionProbeSetResults * GetExpressionResults (int index)
CGenotypeProbeSetResults * GetGenotypingResults (int index)
CUniversalProbeSetResults * GetUniversalResults (int index)
CResequencingResults * GetResequencingResults ()
std::string GetError () const
bool Read ()
bool ReadHeader ()
bool Exists ()
bool IsXDACompatibleFile ()
bool IsMas5File ()
void SetFileName (const char *name)
std::string GetFileName () const
void Clear ()
Protected Member Functions
bool Open (bool bReadHeaderOnly=false)
Protected Attributes
CCHPFileHeader m_Header
std::string m_FileName
std::string m_strError
std::vector< CProbeSetResults * > m_ProbeSetResults
CResequencingResults m_ReseqResults
Detailed Description
This class provides storage and reading capabilities for CHP files
Definition at line 699 of file CHPFileData.h.
Constructor & Destructor Documentation
CCHPFileData::CCHPFileData ()
Constructor
Definition at line 235 of file CHPFileData.cpp.
References Clear().
CCHPFileData::~CCHPFileData ()
Destructor
Definition at line 242 of file CHPFileData.cpp.
References Clear().
Member Function Documentation
void CCHPFileData::Clear (void)
Deallocates any memory used by the class object
Definition at line 249 of file CHPFileData.cpp.
References affxchp::CCHPFileHeader::Clear(), m_FileName, m_Header, m_ProbeSetResults, and m_strError.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::CanReadFile(), CCHPFileData(), affymetrix_fusion_io::GCOSCHPDataAdapter::Clear(), Read(), ReadHeader(), ~CCHPFileData(), affxchpwriter::CCHPFileWriter::~CCHPFileWriter(), and affymetrix_fusion_io::GCOSCHPDataAdapter::~GCOSCHPDataAdapter().
bool CCHPFileData::Exists ()
Determines if the file specified by the FileName property exists.
Returns:
True if the file exists.
Definition at line 464 of file CHPFileData.cpp.
References m_FileName.
std::string affxchp::CCHPFileData::GetError () const [inline]
Error string when the read functions fail.
Returns:
A string message describing a read error
Definition at line 762 of file CHPFileData.h.
References m_strError.
Referenced by ChpCheck::dataSame(), and ChpCheck::headersSame().
CExpressionProbeSetResults * CCHPFileData::GetExpressionResults (int index)
Returns the expression probe set result
Parameters:
index The index to the result object of interest.
Returns:
The expression result.
Definition at line 265 of file CHPFileData.cpp.
References Expression, affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileHeader::GetNumProbeSets(), m_Header, and m_ProbeSetResults.
Referenced by ChpCheck::dataSame(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetExpressionResults(), affxchpwriter::CCHPFileWriter::Save(), and affxchpwriter::CCHPFileWriter::SetExpressionEntry().
std::string affxchp::CCHPFileData::GetFileName () const [inline]
Gets the file name.
Returns:
The full path to the CHP file.
Definition at line 792 of file CHPFileData.h.
References m_FileName.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetFileName().
CGenotypeProbeSetResults * CCHPFileData::GetGenotypingResults (int index)
Returns the genotyping probe set result
Parameters:
index The index to the result object of interest.
Returns:
The genotyping result.
Definition at line 276 of file CHPFileData.cpp.
References affymetrix_calvin_io::Genotyping, affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileHeader::GetNumProbeSets(), m_Header, and m_ProbeSetResults.
Referenced by ChpCheck::dataSame(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affxchpwriter::CCHPFileWriter::Save(), and affxchpwriter::CCHPFileWriter::SetMappingEntry().
CCHPFileHeader& affxchp::CCHPFileData::GetHeader () [inline]
Accessors to header.
Returns:
The header data object
Definition at line 734 of file CHPFileData.h.
References m_Header.
Referenced by ChpCheck::dataSame(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgName(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgorithmParameter(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgorithmParameterCount(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgorithmParameters(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAlgVersion(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetAssayType(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetBackgroundZone(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetBackgroundZoneInfo(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetBackgroundZones(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetChipType(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetCols(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetMagic(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetNumProbeSets(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetParentCellFile(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetProgID(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetRows(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetSummaryParameter(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetSummaryParameterCount(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetSummaryParameters(), affymetrix_fusion_io::GCOSCHPHeaderAdapter::GetVersion(), and ChpCheck::headersSame().
CResequencingResults * CCHPFileData::GetResequencingResults ()
Returns the resequencing results.
Returns:
The resequencing results.
Definition at line 287 of file CHPFileData.cpp.
References affxchp::CCHPFileHeader::GetAssayType(), m_Header, m_ReseqResults, and affxchp::CCHPFileHeader::Resequencing.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetResequencingResults().
CUniversalProbeSetResults * CCHPFileData::GetUniversalResults (int index)
Returns the universal (tag array) probe set result
Parameters:
index The index to the result object of interest.
Returns:
The universal result.
Definition at line 294 of file CHPFileData.cpp.
References affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileHeader::GetNumProbeSets(), m_Header, m_ProbeSetResults, and affxchp::CCHPFileHeader::Universal.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetUniversalResults(), affxchpwriter::CCHPFileWriter::Save(), and affxchpwriter::CCHPFileWriter::SetUniversalEntry().
bool CCHPFileData::IsMas5File ()
Definition at line 1380 of file CHPFileData.cpp.
References Fs::aptOpen(), m_FileName, ReadFixedCString(), and ReadInt32_I().
bool CCHPFileData::IsXDACompatibleFile ()
Determines if the CHP file specified by the FileName property is an XDA format file
Returns:
True if the file is an XDA file
Definition at line 1361 of file CHPFileData.cpp.
References Fs::aptOpen(), CHP_FILE_MAGIC_NUMBER, m_FileName, and ReadInt32_I().
Referenced by Open().
bool CCHPFileData::Open (bool bReadHeaderOnly = false) [protected]
Opens the file for reading.
Parameters:
bReadHeaderOnly Flag to indicate if the header is to be read only.
Returns:
True if successful.
Definition at line 473 of file CHPFileData.cpp.
References ALLELE_NO_CALL, affxchp::CGenotypeProbeSetResults::AlleleCall, Fs::aptOpen(), affxchp::_BackgroundZoneType::background, affxchp::_BaseCallType::call, affxchp::_ForceCallType::call, affxchp::_BackgroundZoneType::centerx, affxchp::_BackgroundZoneType::centery, affxchp::CExpressionProbeSetResults::Change, affxchp::CExpressionProbeSetResults::ChangePValue, CHP_FILE_MAGIC_NUMBER, CHP_FILE_VERSION_NUMBER, affxchp::CResequencingResults::Clear(), affxchp::CGenotypeProbeSetResults::Confidence, affxchp::CExpressionProbeSetResults::Detection, affxchp::CExpressionProbeSetResults::DetectionPValue, Expression, affxchp::CCHPFileHeader::Expression, EXPRESSION_ABSOLUTE_STAT_ANALYSIS, EXPRESSION_COMPARISON_STAT_ANALYSIS, affymetrix_calvin_io::Genotyping, affxchp::CCHPFileHeader::Genotyping, IsXDACompatibleFile(), affxchp::CCHPFileHeader::m_AlgorithmName, affxchp::CCHPFileHeader::m_AlgorithmParameters, affxchp::CCHPFileHeader::m_AlgorithmVersion, affxchp::CCHPFileHeader::m_AssayType, affxchp::CCHPFileHeader::m_BackgroundZoneInfo, affxchp::CCHPFileHeader::m_ChipType, affxchp::CCHPFileHeader::m_Cols, m_FileName, affxchp::CExpressionProbeSetResults::m_HasCompResults, m_Header, affxchp::CCHPFileHeader::m_Magic, affxchp::CCHPFileHeader::m_NumProbeSets, affxchp::CCHPFileHeader::m_ParentCellFile, m_ProbeSetResults, affxchp::CCHPFileHeader::m_ProgID, m_ReseqResults, affxchp::CCHPFileHeader::m_Rows, m_strError, affxchp::CCHPFileHeader::m_SummaryParameters, affxchp::CCHPFileHeader::m_Version, affxchp::_BackgroundZoneInfo::number_zones, affxchp::CExpressionProbeSetResults::NumCommonPairs, affxchp::CExpressionProbeSetResults::NumPairs, affxchp::CExpressionProbeSetResults::NumUsedPairs, affxchp::CCHPFileHeader::ParseString(), affxchp::_BaseCallType::position, affxchp::_ForceCallType::position, affxchp::CGenotypeProbeSetResults::pvalue_AA, affxchp::CGenotypeProbeSetResults::pvalue_AB, affxchp::CGenotypeProbeSetResults::pvalue_BB, affxchp::CGenotypeProbeSetResults::pvalue_NoCall, affxchp::CGenotypeProbeSetResults::RAS1, affxchp::CGenotypeProbeSetResults::RAS2, ReadCString_I(), ReadFixedCString(), ReadFixedString(), ReadFloat_I(), ReadInt16_I(), ReadInt32_I(), ReadInt8(), ReadUInt16_I(), ReadUInt8(), affxchp::_ForceCallType::reason, affymetrix_calvin_io::Resequencing, affxchp::CCHPFileHeader::Resequencing, affxchp::CResequencingResults::ResizeCalledBases(), affxchp::CResequencingResults::ResizeForceCalls(), affxchp::CResequencingResults::ResizeOrigCalls(), affxchp::CResequencingResults::ResizeScores(), ROUNDFLOAT, affxchp::CUniversalProbeSetResults::SetBackground(), affxchp::CResequencingResults::SetCalledBase(), affxchp::CResequencingResults::SetForceCall(), affxchp::CResequencingResults::SetOrigCall(), affxchp::CResequencingResults::SetScore(), affxchp::CExpressionProbeSetResults::Signal, affxchp::CExpressionProbeSetResults::SignalLogRatio, affxchp::CExpressionProbeSetResults::SignalLogRatioHigh, affxchp::CExpressionProbeSetResults::SignalLogRatioLow, affxchp::_BackgroundZoneInfo::smooth_factor, _TagValuePairType::Tag, affxchp::CCHPFileHeader::Universal, affxchp::CCHPFileHeader::Unknown, _TagValuePairType::Value, and affxchp::_BackgroundZoneInfo::zones.
Referenced by Read(), and ReadHeader().
bool CCHPFileData::Read ()
Definition at line 438 of file CHPFileData.cpp.
References Clear(), and Open().
Referenced by ChpCheck::dataSame(), and affymetrix_fusion_io::GCOSCHPDataAdapter::Read().
bool CCHPFileData::ReadHeader ()
Reads the header of the CHP file
Returns:
True if successful
Definition at line 451 of file CHPFileData.cpp.
References Clear(), and Open().
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::CanReadFile(), ChpCheck::headersSame(), and affymetrix_fusion_io::GCOSCHPDataAdapter::ReadHeader().
void affxchp::CCHPFileData::SetFileName (const char * name) [inline]
Sets the file name.
Parameters:
name The full path to the CHP file
Definition at line 787 of file CHPFileData.h.
References m_FileName.
Referenced by ChpCheck::dataSame(), ChpCheck::headersSame(), and affymetrix_fusion_io::GCOSCHPDataAdapter::SetFileName().
Member Data Documentation
std::string affxchp::CCHPFileData::m_FileName [protected]
The full path of the CHP file
Definition at line 713 of file CHPFileData.h.
Referenced by Clear(), affxchpwriter::CCHPFileWriter::CreateNewFile(), Exists(), GetFileName(), IsMas5File(), IsXDACompatibleFile(), Open(), and SetFileName().
CCHPFileHeader affxchp::CCHPFileData::m_Header [protected]
The file header object
Definition at line 710 of file CHPFileData.h.
Referenced by affxchpwriter::CCHPFileWriter::AddBackgroundInfo(), affxchpwriter::CCHPFileWriter::AddBackgroundZone(), affxchpwriter::CCHPFileWriter::AddChipSummaryParameter(), Clear(), GetExpressionResults(), GetGenotypingResults(), GetHeader(), GetResequencingResults(), GetUniversalResults(), affxchpwriter::CCHPFileWriter::InitializeForWriting(), Open(), affxchpwriter::CCHPFileWriter::Save(), affxchpwriter::CCHPFileWriter::SaveHeader(), affxchpwriter::CCHPFileWriter::SetAlgorithmName(), affxchpwriter::CCHPFileWriter::SetAlgorithmVersion(), affxchpwriter::CCHPFileWriter::SetParentCelFileName(), and affxchpwriter::CCHPFileWriter::SetProgID().
std::vector<CProbeSetResults *> affxchp::CCHPFileData::m_ProbeSetResults [protected]
The vector of probe set results
Definition at line 719 of file CHPFileData.h.
Referenced by Clear(), GetExpressionResults(), GetGenotypingResults(), GetUniversalResults(), affxchpwriter::CCHPFileWriter::InitializeForWriting(), and Open().
CResequencingResults affxchp::CCHPFileData::m_ReseqResults [protected]
The resequencing results.
Definition at line 722 of file CHPFileData.h.
Referenced by GetResequencingResults(), Open(), affxchpwriter::CCHPFileWriter::Save(), and affxchpwriter::CCHPFileWriter::SetResequencingResults().
std::string affxchp::CCHPFileData::m_strError [protected]
A string to hold an error message associated with a read operation
Definition at line 716 of file CHPFileData.h.
Referenced by Clear(), affxchpwriter::CCHPFileWriter::CreateNewFile(), GetError(), Open(), and affxchpwriter::CCHPFileWriter::SaveHeader().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CHPFileData.h
C:/f112/affy/sdk/file/CHPFileData.cpp