Affymetrix Fusion SDK: affymetrix_calvin_io::FileOutput Class Reference
affymetrix_calvin_io::FileOutput Class Reference
#include <FileOutput.h>
Static Public Member Functions
static void WriteInt8 (std::ofstream &outstr, int8_t value)
static void WriteInt16 (std::ofstream &outstr, int16_t value)
static void WriteInt32 (std::ofstream &outstr, int32_t value)
static void WriteUInt8 (std::ofstream &outstr, u_int8_t value)
static void WriteUInt16 (std::ofstream &outstr, u_int16_t value)
static void WriteUInt32 (std::ofstream &outstr, u_int32_t value)
static void WriteFloat (std::ofstream &outstr, float value)
static void WriteString16 (std::ofstream &outstr, const wchar_t *value, int32_t len)
static void WriteString16 (std::ofstream &outstr, const std::wstring &value)
static void WriteString8 (std::ofstream &outstr, const char *value, int32_t len)
static void WriteString8 (std::ofstream &outstr, const std::string &value)
static void WriteString8 (std::ofstream &outstr, const std::string &value, int32_t maxLn)
static void WriteString16 (std::ofstream &outstr, const std::wstring &value, int32_t maxLn)
static void WriteBlob (std::ofstream &outstr, const void *value, int32_t size)
static void WriteBlob (std::ofstream &outstr, const void *value, int32_t data_size, int32_t reserved_size)
Detailed Description
Definition at line 37 of file FileOutput.h.
Member Function Documentation
void FileOutput::WriteBlob (std::ofstream & outstr, const void * value, int32_t size) [static]
Writes a blob to a file (as is; no htonl). It is the responsibility of the caller to ensure the blob is in a portable form.
Parameters:
outstr The output file stream.
value A pointer to the blob.
size The size of the blob.
Definition at line 210 of file FileOutput.cpp.
References WriteInt32().
Referenced by affymetrix_calvin_io::GenericDataHeaderWriter::WriteNameValParams(), and affymetrix_calvin_io::DataSetHeaderWriter::WriteNameValParams().
void FileOutput::WriteBlob (std::ofstream & outstr, const void * value, int32_t data_size, int32_t reserved_size) [static]
Writes a blob to a file with reserved space(as is; no htonl). It is the responsibility of the caller to ensure the blob is in a portable form.
Parameters:
outstr The output file stream.
value A pointer to the blob.
data_size The size of the blob.
reserved_size The size of the reserved space (total size including the blob size).
Definition at line 219 of file FileOutput.cpp.
References WriteInt32().
void FileOutput::WriteFloat (std::ofstream & outstr, float value) [static]
Writes a 32 bit floating point number from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 96 of file FileOutput.cpp.
References type_punned::v_float, type_punned::v_int32, and WriteInt32().
Referenced by affymetrix_calvin_io::DataSetUpdater::Update(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantification(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataExpressionEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataExpressionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntry(), and affymetrix_calvin_io::DataSetWriter::Write().
void FileOutput::WriteInt16 (std::ofstream & outstr, int16_t value) [static]
Writes a 16 bit integer from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 52 of file FileOutput.cpp.
Referenced by affymetrix_calvin_io::DataSetUpdater::Update(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntry(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::DataSetWriter::Write().
void FileOutput::WriteInt32 (std::ofstream & outstr, int32_t value) [static]
Writes a 32 bit integer from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 61 of file FileOutput.cpp.
Referenced by affymetrix_calvin_io::DataSetUpdater::Update(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), affymetrix_calvin_io::DataSetWriter::Write(), WriteBlob(), affymetrix_calvin_io::DataSetHeaderWriter::WriteColumnCnt(), affymetrix_calvin_io::DataSetHeaderWriter::WriteColumnTypes(), affymetrix_calvin_io::FileHeaderWriter::WriteDataGroupCnt(), affymetrix_calvin_io::DataSetHeaderWriter::WriteDataOffset(), affymetrix_calvin_io::DataGroupHeaderWriter::WriteDataSetCnt(), affymetrix_calvin_io::DataGroupHeaderWriter::WriteDataSetPos(), WriteFloat(), affymetrix_calvin_io::DataSetHeaderWriter::WriteNameValCnt(), affymetrix_calvin_io::GenericDataHeaderWriter::WriteNameValParamCnt(), affymetrix_calvin_io::DataGroupHeaderWriter::WriteNextDataGroupPos(), affymetrix_calvin_io::DataSetHeaderWriter::WriteNextDataSetOffset(), affymetrix_calvin_io::GenericDataHeaderWriter::WriteParentHdrCnt(), affymetrix_calvin_io::DataSetHeaderWriter::WriteRowCnt(), WriteString16(), and WriteString8().
void FileOutput::WriteInt8 (std::ofstream & outstr, int8_t value) [static]
Writes an 8 bit integer from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 44 of file FileOutput.cpp.
void FileOutput::WriteString16 (std::ofstream & outstr, const wchar_t * value, int32_t len) [static]
Writes a 16 bit unicode string of fixed size from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
len The length of the string.
Definition at line 179 of file FileOutput.cpp.
Referenced by affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), affymetrix_calvin_io::DataSetWriter::Write(), affymetrix_calvin_io::DataSetHeaderWriter::WriteColumnTypes(), affymetrix_calvin_io::GenericDataHeaderWriter::WriteFileCreationTime(), affymetrix_calvin_io::GenericDataHeaderWriter::WriteLocale(), affymetrix_calvin_io::DataSetHeaderWriter::WriteName(), affymetrix_calvin_io::DataGroupHeaderWriter::WriteName(), affymetrix_calvin_io::GenericDataHeaderWriter::WriteNameValParams(), affymetrix_calvin_io::DataSetHeaderWriter::WriteNameValParams(), and WriteString16().
void FileOutput::WriteString16 (std::ofstream & outstr, const std::wstring & value) [static]
Writes a 16 bit unicode string from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 144 of file FileOutput.cpp.
References WriteInt32(), and WriteString16().
void FileOutput::WriteString16 (std::ofstream & outstr, const std::wstring & value, int32_t maxLn) [static]
Writes an 16 bit string from a big endian file with a fixed maximum size. If the string length is less than maxLn then null's are appended.
Parameters:
outstr The output file stream.
value The value to write to the file.
maxLn Maximum length of the string.
Definition at line 154 of file FileOutput.cpp.
References WriteInt32(), and WriteString16().
void FileOutput::WriteString8 (std::ofstream & outstr, const std::string & value) [static]
Writes an 8 bit string from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 106 of file FileOutput.cpp.
References WriteInt32(), and WriteString8().
void FileOutput::WriteString8 (std::ofstream & outstr, const char * value, int32_t len) [static]
Writes an 8 bit string of fixed size from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
len The length of the string.
Definition at line 116 of file FileOutput.cpp.
Referenced by affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), affymetrix_calvin_io::DataSetWriter::Write(), affymetrix_calvin_io::GenericDataHeaderWriter::WriteFileId(), affymetrix_calvin_io::GenericDataHeaderWriter::WriteFileTypeId(), and WriteString8().
void FileOutput::WriteString8 (std::ofstream & outstr, const std::string & value, int32_t maxLn) [static]
Writes an 8 bit string from a big endian file with a fixed maximum size. If the string length is less than maxLn then null's are appended.
Parameters:
outstr The output file stream.
value The value to write to the file.
maxLn Maximum length of the string.
Definition at line 193 of file FileOutput.cpp.
References WriteString8().
void FileOutput::WriteUInt16 (std::ofstream & outstr, u_int16_t value) [static]
Writes a 16 bit unsigned integer from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 78 of file FileOutput.cpp.
Referenced by affymetrix_calvin_io::DataSetUpdater::Update(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::DataSetWriter::Write().
void FileOutput::WriteUInt32 (std::ofstream & outstr, u_int32_t value) [static]
Writes a 32 bit unsigned integer from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 87 of file FileOutput.cpp.
Referenced by affymetrix_calvin_io::DataSetUpdater::Update(), affymetrix_calvin_io::FileHeaderUpdater::UpdateDataGroupCount(), affymetrix_calvin_io::FileHeaderWriter::UpdateDataGroupOffset(), affymetrix_calvin_io::DataSetHeaderWriter::UpdateDataOffset(), affymetrix_calvin_io::DataGroupHeaderWriter::UpdateDataSetPos(), affymetrix_calvin_io::FileHeaderUpdater::UpdateLeadDataGroupOffset(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), affymetrix_calvin_io::DataGroupHeaderWriter::UpdateNextDataGroupPos(), affymetrix_calvin_io::DataSetHeaderWriter::UpdateNextDataSetOffset(), affymetrix_calvin_io::GenericFileWriter::Write(), affymetrix_calvin_io::DataSetWriter::Write(), and affymetrix_calvin_io::FileHeaderWriter::WriteDataGroupOffset().
void FileOutput::WriteUInt8 (std::ofstream & outstr, u_int8_t value) [static]
Writes an 8 bit unsigned integer from a big endian file.
Parameters:
outstr The output file stream.
value The value to write to the file.
Definition at line 70 of file FileOutput.cpp.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/FileOutput.h
C:/f112/affy/sdk/calvin_files/writers/src/FileOutput.cpp