Affymetrix Fusion SDK: BaseEngine Class Reference
BaseEngine Class Reference
Base class for analysis engines.
#include <BaseEngine.h>
Public Member Functions
virtual std::string getEngineName ()
BaseEngine ()
BaseEngine (char *argv[])
virtual ~BaseEngine ()
void run ()
Top level function to open up files and make sure things look ok then start analysis pathway.
virtual int parseArgv (const char *const *const argv, int start=1)
std::string getProgName ()
void checkOptions ()
void checkDiskSpace ()
void openStandardLog (const std::string &log_name, std::ofstream &log_ofstream, LogStream &log_logstream)
void setLibFileOpt (const std::string &option)
std::vector< std::pair
< std::string, std::string > > getMetaDataDescription ()
virtual void defineOptions ()
Protected Member Functions
virtual void runImp ()
virtual void checkOptionsImp ()
virtual void checkDiskSpaceImp ()
virtual void extraHelp ()
void printEngineOptions ()
void printEngineOptions (const std::string &label)
void makeTempDir (std::string temp_dir)
void removeTempDir (std::string temp_dir)
Private Member Functions
virtual void defineStates ()
Private Attributes
bool m_OptionsChecked
bool m_DiskChecked
bool m_created_new_tempdir
MsgSocketHandler * m_SocketHandler
Detailed Description
Base class for analysis engines.
Definition at line 49 of file BaseEngine.h.
Constructor & Destructor Documentation
BaseEngine::BaseEngine ()
Constructor
Definition at line 86 of file BaseEngine.cpp.
References defineOptions(), m_SocketHandler, Util::memInfo(), Verbose::out(), Options::setOpt(), and ToStr().
BaseEngine::BaseEngine (char * argv[])
Constructor
Parameters:
argv - vector of args to parse
Definition at line 97 of file BaseEngine.cpp.
References m_SocketHandler, and parseArgv().
BaseEngine::~BaseEngine () [virtual]
Destructor
Definition at line 102 of file BaseEngine.cpp.
References Freez(), m_SocketHandler, and Verbose::out().
Member Function Documentation
void BaseEngine::checkDiskSpace ()
Query available disk space and compare it to estimated disk space needed for temporary and CHP files
Definition at line 265 of file BaseEngine.cpp.
References checkDiskSpaceImp(), checkOptions(), Freez(), Options::getOptBool(), m_DiskChecked, Err::popHandler(), and Err::setThrowStatus().
Referenced by run().
virtual void BaseEngine::checkDiskSpaceImp () [inline, protected, virtual]
Definition at line 137 of file BaseEngine.h.
Referenced by checkDiskSpace().
void BaseEngine::checkOptions ()
Check the validity of options specified
Definition at line 201 of file BaseEngine.cpp.
References checkOptionsImp(), defineStates(), extraHelp(), Freez(), Options::getOpt(), Options::getOptBool(), m_OptionsChecked, Options::optionUsage(), Err::popHandler(), Err::setThrowStatus(), and Options::snapshotOptions().
Referenced by checkDiskSpace(), and run().
virtual void BaseEngine::checkOptionsImp () [inline, protected, virtual]
Definition at line 136 of file BaseEngine.h.
Referenced by checkOptions().
void BaseEngine::defineOptions () [virtual]
Definition at line 335 of file BaseEngine.cpp.
References PgOpt::BOOL_OPT, Options::defineOption(), Options::defineOptionSection(), Options::defOptMult(), PgOpt::INT_OPT, and PgOpt::STRING_OPT.
Referenced by BaseEngine().
void BaseEngine::defineStates () [private, virtual]
Definition at line 442 of file BaseEngine.cpp.
References Options::defineOption(), and PgOpt::STRING_OPT.
Referenced by checkOptions().
virtual void BaseEngine::extraHelp () [inline, protected, virtual]
Definition at line 138 of file BaseEngine.h.
Referenced by checkOptions().
virtual std::string BaseEngine::getEngineName () [inline, virtual]
Definition at line 53 of file BaseEngine.h.
Referenced by run().
std::vector< std::pair< std::string, std::string > > BaseEngine::getMetaDataDescription ()
Get a vector of the key=value pairs specified via the "meta-data-info" parameters
Returns:
vector of pairs of strings with first string being key and second being the value
Definition at line 170 of file BaseEngine.cpp.
References Err::errAbort(), Options::getPgOpt(), PgOpt::getValue(), and PgOpt::getValueCount().
std::string BaseEngine::getProgName ()
Set the build versioning infomation. Get the name of the Engine
Definition at line 136 of file BaseEngine.cpp.
void BaseEngine::makeTempDir (std::string temp_dir) [protected]
Definition at line 463 of file BaseEngine.cpp.
References Fs::dirExists(), Fs::ensureWriteableDirPath(), Err::errAbort(), FS_QUOTE_PATH, Fs::isWriteableDir(), and m_created_new_tempdir.
void BaseEngine::openStandardLog (const std::string & log_name, std::ofstream & log_ofstream, LogStream & log_logstream)
Opens the log file in the normal way. Cant take ownership of these as we done know when to close them.
Definition at line 145 of file BaseEngine.cpp.
References APT_OK, Err::errAbort(), Options::getOpt(), Fs::isWriteableDir(), Fs::join(), Fs::mkdirPath(), Fs::mustOpenToWrite(), Verbose::pushMsgHandler(), Verbose::pushProgressHandler(), Verbose::pushWarnHandler(), and LogStream::setStream().
int BaseEngine::parseArgv (const char *const *const argv, int start = 1) [virtual]
Parse and set options from argv
Parameters:
argv - arg vector
Reimplemented from Options.
Definition at line 112 of file BaseEngine.cpp.
References Err::configureErrHandler(), Options::getOpt(), Options::getOptBool(), Options::getOptInt(), Verbose::getParam(), m_SocketHandler, MsgSocketHandler::openSocket(), Verbose::out(), Verbose::pushMsgHandler(), Verbose::pushProgressHandler(), Verbose::removeDefault(), and MsgSocketHandler::setEndOfLine().
Referenced by BaseEngine(), and main().
void BaseEngine::printEngineOptions () [inline, protected]
Definition at line 140 of file BaseEngine.h.
References Options::printOptions().
Referenced by run().
void BaseEngine::printEngineOptions (const std::string & label) [inline, protected]
Definition at line 144 of file BaseEngine.h.
References Options::printOptions().
void BaseEngine::removeTempDir (std::string temp_dir) [protected]
Definition at line 475 of file BaseEngine.cpp.
References m_created_new_tempdir, and Fs::rmdir().
void BaseEngine::run (void)
Top level function to open up files and make sure things look ok then start analysis pathway.
Run the engine -- entry point to run the engine Will call Verbose::out() and Err::errAbort().
Definition at line 290 of file BaseEngine.cpp.
References checkDiskSpace(), checkOptions(), MsgSocketHandler::finishedMsg(), Freez(), getEngineName(), Options::getOptBool(), Util::getTimeStamp(), m_SocketHandler, Verbose::out(), Err::popHandler(), Util::popMemFreeAtStart(), printEngineOptions(), Util::pushMemFreeAtStart(), Verbose::removeMsgHandler(), Verbose::removeProgressHandler(), runImp(), Options::setOpt(), Err::setThrowStatus(), and ToStr().
Referenced by main().
virtual void BaseEngine::runImp () [inline, protected, virtual]
Engine implementations in child Will call Verbose::out() and Err::errAbort().
Definition at line 135 of file BaseEngine.h.
Referenced by run().
void BaseEngine::setLibFileOpt (const std::string & option)
Swap the option value to include the full path if found
Parameters:
option
Definition at line 140 of file BaseEngine.cpp.
References Fs::findLibFile(), Options::getOpt(), and Options::setOpt().
Member Data Documentation
bool BaseEngine::m_created_new_tempdir [private]
flag to indicate if tempdir should be deleted at end of run
Definition at line 158 of file BaseEngine.h.
Referenced by makeTempDir(), and removeTempDir().
bool BaseEngine::m_DiskChecked [private]
Definition at line 156 of file BaseEngine.h.
Referenced by checkDiskSpace().
bool BaseEngine::m_OptionsChecked [private]
Definition at line 155 of file BaseEngine.h.
Referenced by checkOptions().
MsgSocketHandler* BaseEngine::m_SocketHandler [private]
Definition at line 159 of file BaseEngine.h.
Referenced by BaseEngine(), parseArgv(), run(), and ~BaseEngine().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/BaseEngine.h
C:/f112/affy/sdk/util/BaseEngine.cpp