Affymetrix Fusion SDK: affymetrix_calvin_io::CHPQuantificationFileBufferWriter Class Reference
affymetrix_calvin_io::CHPQuantificationFileBufferWriter Class Reference
#include <CalvinCHPQuantificationFileBufferWriter.h>
Public Member Functions
CHPQuantificationFileBufferWriter ()
~CHPQuantificationFileBufferWriter ()
void SetMaxBufferSize (int MaxBufferSize)
void Cleanup ()
void Initialize (std::vector< std::string > *CHPFileNames)
void WriteQuantificationEntry (int target, float quantification)
void FlushBuffer ()
Private Attributes
std::vector< std::string > * m_CHPFileNames
std::vector< std::vector< float > > m_TargetQuantificationBuffers
std::vector< int > m_TargetQuantificationRowIndexes
int m_BufferSize
int m_MaxBufferSize
Detailed Description
Definition at line 41 of file CalvinCHPQuantificationFileBufferWriter.h.
Constructor & Destructor Documentation
CHPQuantificationFileBufferWriter::CHPQuantificationFileBufferWriter ()
Constructor
Definition at line 36 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References m_BufferSize, m_MaxBufferSize, and MAX_BUFFER_SIZE.
CHPQuantificationFileBufferWriter::~CHPQuantificationFileBufferWriter ()
Destructor
Definition at line 42 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References Cleanup(), and FlushBuffer().
Member Function Documentation
void CHPQuantificationFileBufferWriter::Cleanup ()
Cleans up memory
Definition at line 48 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References m_TargetQuantificationBuffers.
Referenced by Initialize(), and ~CHPQuantificationFileBufferWriter().
void CHPQuantificationFileBufferWriter::FlushBuffer ()
Write the content of the buffer to CHP files.
Definition at line 80 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References affymetrix_calvin_io::CalvinCHPFileUpdater::CloseCHPFile(), m_BufferSize, m_CHPFileNames, m_TargetQuantificationBuffers, m_TargetQuantificationRowIndexes, affymetrix_calvin_io::CalvinCHPFileUpdater::OpenCHPFile(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer().
Referenced by UpdateQuantifications(), WriteQuantificationEntry(), and ~CHPQuantificationFileBufferWriter().
void CHPQuantificationFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames)
Initialize quantification buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
Definition at line 57 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References Cleanup(), m_BufferSize, m_CHPFileNames, m_TargetQuantificationBuffers, and m_TargetQuantificationRowIndexes.
Referenced by UpdateQuantifications().
void affymetrix_calvin_io::CHPQuantificationFileBufferWriter::SetMaxBufferSize (int MaxBufferSize) [inline]
Set maximum buffer size
Definition at line 51 of file CalvinCHPQuantificationFileBufferWriter.h.
References m_MaxBufferSize.
void CHPQuantificationFileBufferWriter::WriteQuantificationEntry (int target, float quantification)
Write a quantification entry to buffer. If the buffer is full, flush it.
Parameters:
target Target for the quantification entry.
quantification Value for the quantification entry.
Definition at line 70 of file CalvinCHPQuantificationFileBufferWriter.cpp.
References FlushBuffer(), m_BufferSize, m_MaxBufferSize, and m_TargetQuantificationBuffers.
Referenced by UpdateQuantifications().
Member Data Documentation
int affymetrix_calvin_io::CHPQuantificationFileBufferWriter::m_BufferSize [private]
Definition at line 81 of file CalvinCHPQuantificationFileBufferWriter.h.
Referenced by CHPQuantificationFileBufferWriter(), FlushBuffer(), Initialize(), and WriteQuantificationEntry().
std::vector<std::string>* affymetrix_calvin_io::CHPQuantificationFileBufferWriter::m_CHPFileNames [private]
Definition at line 72 of file CalvinCHPQuantificationFileBufferWriter.h.
Referenced by FlushBuffer(), and Initialize().
int affymetrix_calvin_io::CHPQuantificationFileBufferWriter::m_MaxBufferSize [private]
Definition at line 84 of file CalvinCHPQuantificationFileBufferWriter.h.
Referenced by CHPQuantificationFileBufferWriter(), SetMaxBufferSize(), and WriteQuantificationEntry().
std::vector< std::vector<float> > affymetrix_calvin_io::CHPQuantificationFileBufferWriter::m_TargetQuantificationBuffers [private]
Definition at line 75 of file CalvinCHPQuantificationFileBufferWriter.h.
Referenced by Cleanup(), FlushBuffer(), Initialize(), and WriteQuantificationEntry().
std::vector<int> affymetrix_calvin_io::CHPQuantificationFileBufferWriter::m_TargetQuantificationRowIndexes [private]
Definition at line 78 of file CalvinCHPQuantificationFileBufferWriter.h.
Referenced by FlushBuffer(), and Initialize().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPQuantificationFileBufferWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPQuantificationFileBufferWriter.cpp