Affymetrix Fusion SDK: CFPointCOM Class Reference
CFPointCOM Class Reference
#include <FPointCOM.h>
Public Member Functions
CFPointCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
void SetPoint (affymetrix_fusion_io::FPoint &p)
STDMETHOD() get_x (float *pVal)
STDMETHOD() get_y (float *pVal)
Private Attributes
affymetrix_fusion_io::FPoint pt
Detailed Description
Definition at line 30 of file FPointCOM.h.
Constructor & Destructor Documentation
CFPointCOM::CFPointCOM () [inline]
Definition at line 37 of file FPointCOM.h.
Member Function Documentation
HRESULT CFPointCOM::FinalConstruct () [inline]
Definition at line 56 of file FPointCOM.h.
void CFPointCOM::FinalRelease () [inline]
Definition at line 61 of file FPointCOM.h.
STDMETHODIMP CFPointCOM::get_x (float * pVal)
Definition at line 43 of file FPointCOM.cpp.
References pt, and affymetrix_fusion_io::FPoint::x.
STDMETHODIMP CFPointCOM::get_y (float * pVal)
Definition at line 49 of file FPointCOM.cpp.
References pt, and affymetrix_fusion_io::FPoint::y.
STDMETHODIMP CFPointCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 28 of file FPointCOM.cpp.
void CFPointCOM::SetPoint (affymetrix_fusion_io::FPoint & p) [inline]
Definition at line 69 of file FPointCOM.h.
Referenced by CFGridCoordsCOM::get_lowerleft(), CFGridCoordsCOM::get_lowerright(), CFGridCoordsCOM::get_upperleft(), and CFGridCoordsCOM::get_upperright().
Member Data Documentation
affymetrix_fusion_io::FPoint CFPointCOM::pt [private]
Definition at line 66 of file FPointCOM.h.
Referenced by get_x(), and get_y().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FPointCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FPointCOM.cpp