Affymetrix Fusion SDK: affymetrix_calvin_io::CHPFileBufferWriter Class Reference
affymetrix_calvin_io::CHPFileBufferWriter Class Reference
#include <CalvinCHPFileBufferWriter.h>
Classes
class GenotypeBufferEntry
Public Member Functions
CHPFileBufferWriter ()
~CHPFileBufferWriter ()
void SetMaxBufferSize (int MaxBufferSize)
void Cleanup ()
void Initialize (std::vector< std::string > *CHPFileNames)
void WriteGenotypeEntry (int target, CHPGenotypeEntry &entry)
void FlushBuffer ()
Private Attributes
std::vector< std::string > * m_CHPFileNames
std::vector< std::vector
< GenotypeBufferEntry > > m_TargetEntryBuffers
std::vector< int > m_TargetEntryRowIndexes
int m_BufferSize
int m_MaxBufferSize
Detailed Description
Definition at line 43 of file CalvinCHPFileBufferWriter.h.
Constructor & Destructor Documentation
CHPFileBufferWriter::CHPFileBufferWriter ()
Constructor
Definition at line 36 of file CalvinCHPFileBufferWriter.cpp.
References m_BufferSize, m_MaxBufferSize, and MAX_BUFFER_SIZE.
CHPFileBufferWriter::~CHPFileBufferWriter ()
Destructor
Definition at line 42 of file CalvinCHPFileBufferWriter.cpp.
References Cleanup(), and FlushBuffer().
Member Function Documentation
void CHPFileBufferWriter::Cleanup ()
Cleans up memory
Definition at line 48 of file CalvinCHPFileBufferWriter.cpp.
References m_TargetEntryBuffers.
Referenced by Initialize(), and ~CHPFileBufferWriter().
void CHPFileBufferWriter::FlushBuffer ()
Write the content of the buffer to Command Console CHP file.
Definition at line 89 of file CalvinCHPFileBufferWriter.cpp.
References affymetrix_calvin_io::CalvinCHPFileUpdater::CloseCHPFile(), m_BufferSize, m_CHPFileNames, m_TargetEntryBuffers, m_TargetEntryRowIndexes, affymetrix_calvin_io::CalvinCHPFileUpdater::OpenCHPFile(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer().
Referenced by WriteGenotypeEntry(), and ~CHPFileBufferWriter().
void CHPFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames)
Initialize entry buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
Definition at line 57 of file CalvinCHPFileBufferWriter.cpp.
References Cleanup(), m_BufferSize, m_CHPFileNames, m_TargetEntryBuffers, and m_TargetEntryRowIndexes.
void affymetrix_calvin_io::CHPFileBufferWriter::SetMaxBufferSize (int MaxBufferSize) [inline]
Set maximum buffer size
Definition at line 67 of file CalvinCHPFileBufferWriter.h.
References m_MaxBufferSize.
void CHPFileBufferWriter::WriteGenotypeEntry (int target, CHPGenotypeEntry & entry)
Write an entry to buffer. If the buffer is full, flush it.
Parameters:
target Target for the Signal entry.
entry CHP genotype entry.
Definition at line 70 of file CalvinCHPFileBufferWriter.cpp.
References affymetrix_calvin_io::CHPFileBufferWriter::GenotypeBufferEntry::aaCall, affymetrix_calvin_io::CHPFileBufferWriter::GenotypeBufferEntry::abCall, affymetrix_calvin_io::CHPFileBufferWriter::GenotypeBufferEntry::bbCall, affymetrix_calvin_io::CHPFileBufferWriter::GenotypeBufferEntry::call, affymetrix_calvin_io::CHPFileBufferWriter::GenotypeBufferEntry::confidence, FlushBuffer(), affymetrix_calvin_io::CHPGenotypeEntry::GetAACall(), affymetrix_calvin_io::CHPGenotypeEntry::GetABCall(), affymetrix_calvin_io::CHPGenotypeEntry::GetBBCall(), affymetrix_calvin_io::CHPGenotypeEntry::GetCall(), affymetrix_calvin_io::CHPGenotypeEntry::GetConfidence(), affymetrix_calvin_io::CHPGenotypeEntry::GetNoCall(), affymetrix_calvin_io::CHPGenotypeEntry::GetRAS1(), affymetrix_calvin_io::CHPGenotypeEntry::GetRAS2(), m_BufferSize, m_MaxBufferSize, m_TargetEntryBuffers, affymetrix_calvin_io::CHPFileBufferWriter::GenotypeBufferEntry::noCall, affymetrix_calvin_io::CHPFileBufferWriter::GenotypeBufferEntry::RAS1, and affymetrix_calvin_io::CHPFileBufferWriter::GenotypeBufferEntry::RAS2.
Member Data Documentation
int affymetrix_calvin_io::CHPFileBufferWriter::m_BufferSize [private]
Definition at line 97 of file CalvinCHPFileBufferWriter.h.
Referenced by CHPFileBufferWriter(), FlushBuffer(), Initialize(), and WriteGenotypeEntry().
std::vector<std::string>* affymetrix_calvin_io::CHPFileBufferWriter::m_CHPFileNames [private]
Definition at line 88 of file CalvinCHPFileBufferWriter.h.
Referenced by FlushBuffer(), and Initialize().
int affymetrix_calvin_io::CHPFileBufferWriter::m_MaxBufferSize [private]
Definition at line 100 of file CalvinCHPFileBufferWriter.h.
Referenced by CHPFileBufferWriter(), SetMaxBufferSize(), and WriteGenotypeEntry().
std::vector< std::vector<GenotypeBufferEntry> > affymetrix_calvin_io::CHPFileBufferWriter::m_TargetEntryBuffers [private]
Definition at line 91 of file CalvinCHPFileBufferWriter.h.
Referenced by Cleanup(), FlushBuffer(), Initialize(), and WriteGenotypeEntry().
std::vector<int> affymetrix_calvin_io::CHPFileBufferWriter::m_TargetEntryRowIndexes [private]
Definition at line 94 of file CalvinCHPFileBufferWriter.h.
Referenced by FlushBuffer(), and Initialize().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPFileBufferWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPFileBufferWriter.cpp