Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPHeader Class Reference
affymetrix_fusion_io::FusionCHPHeader Class Reference
#include <FusionCHPLegacyData.h>
Public Member Functions
FusionCHPHeader ()
~FusionCHPHeader ()
int GetCols () const
int GetRows () const
int GetNumProbeSets () const
AssayType GetAssayType () const
std::wstring GetChipType () const
std::wstring GetAlgName () const
std::wstring GetAlgVersion () const
void AlgorithmParameters (FusionTagValuePairTypeList &values)
u_int32_t AlgorithmParameterCount ()
void SummaryParameters (FusionTagValuePairTypeList &p)
u_int32_t SummaryParameterCount ()
std::wstring GetParentCellFile () const
std::wstring GetProgID () const
std::wstring GetAlgorithmParameter (const wchar_t *tag)
std::wstring GetSummaryParameter (const wchar_t *tag)
void GetBackgroundZoneInfo (affxchp::BackgroundZoneInfo &info)
void GetBackgroundZones (affxchp::BackgroundZoneTypeList &zones)
void GetBackgroundZone (affxchp::BackgroundZoneType &type, int x, int y)
int GetMagic () const
int GetVersion () const
void CheckAdapter () const
void Clear ()
Protected Attributes
IFusionCHPDataAdapter * adapter
Friends
class FusionCHPLegacyData
Detailed Description
This class provides storage for the CHP file header
Definition at line 48 of file FusionCHPLegacyData.h.
Constructor & Destructor Documentation
FusionCHPHeader::FusionCHPHeader ()
Constructor
Definition at line 62 of file FusionCHPLegacyData.cpp.
References adapter.
FusionCHPHeader::~FusionCHPHeader ()
Destructor
Definition at line 69 of file FusionCHPLegacyData.cpp.
Member Function Documentation
u_int32_t FusionCHPHeader::AlgorithmParameterCount ()
Gets the algorithm parameters count
Returns:
The number of algorithm parameters.
Definition at line 151 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetAlgorithmParameterCount(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader().
Referenced by CFusionCHPHeaderCOM::get_AlgorithmParameterCount().
void FusionCHPHeader::AlgorithmParameters (FusionTagValuePairTypeList & values)
Gets the algorithm parameters
Parameters:
values The fusion tag value pair type list
Definition at line 145 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetAlgorithmParameters(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader().
Referenced by CFusionCHPHeaderCOM::get_AlgorithmParameters(), and CFusionCHPHeaderCOM::GetAlgorithmParameterName().
void FusionCHPHeader::CheckAdapter () const
Check the adapter and throw exception if not set
Exceptions:
FileNotOpenException
Definition at line 224 of file FusionCHPLegacyData.cpp.
References adapter, and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
Referenced by AlgorithmParameterCount(), AlgorithmParameters(), GetAlgName(), GetAlgorithmParameter(), GetAlgVersion(), GetAssayType(), affxchp::CCHPFileHeader::GetBackgroundZone(), GetChipType(), GetCols(), GetMagic(), GetNumProbeSets(), GetParentCellFile(), GetProgID(), GetRows(), GetSummaryParameter(), GetVersion(), SummaryParameterCount(), and SummaryParameters().
void FusionCHPHeader::Clear (void)
Clears the members.
Definition at line 219 of file FusionCHPLegacyData.cpp.
References adapter.
Referenced by CFusionCHPHeaderCOM::Clear(), and affymetrix_fusion_io::FusionCHPLegacyData::CreateAdapter().
std::wstring FusionCHPHeader::GetAlgName () const
Gets the algorithm name
Returns:
The algorithm name
Definition at line 133 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetAlgName(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader().
Referenced by CFusionCHPHeaderCOM::get_AlgName().
std::wstring FusionCHPHeader::GetAlgorithmParameter (const wchar_t * tag)
Gets a specific algorithm parameter given a name/tag
Returns:
The specific algorithm parameter given a name/tag
Definition at line 181 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetAlgorithmParameter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader().
Referenced by CFusionCHPHeaderCOM::GetAlgorithmParameter().
std::wstring FusionCHPHeader::GetAlgVersion () const
Gets the algorithm version
Returns:
The algorithm version
Definition at line 139 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetAlgVersion(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader().
Referenced by CFusionCHPHeaderCOM::get_AlgVersion().
AssayType FusionCHPHeader::GetAssayType () const
Gets the assay type
Returns:
The assay type
Definition at line 121 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetAssayType(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader().
Referenced by CFusionCHPHeaderCOM::get_AssayType(), and LegacyExample().
void affymetrix_fusion_io::FusionCHPHeader::GetBackgroundZone (affxchp::BackgroundZoneType & type, int x, int y)
Gets the background value for a given center coordinate
Returns:
The background value for a given center coordinate
Referenced by CFusionCHPHeaderCOM::GetBackgroundZone().
void affymetrix_fusion_io::FusionCHPHeader::GetBackgroundZoneInfo (affxchp::BackgroundZoneInfo & info)
Gets the background zone information
Returns:
The background zone information
Referenced by CFusionCHPHeaderCOM::get_BackgroundZoneInfo().
void affymetrix_fusion_io::FusionCHPHeader::GetBackgroundZones (affxchp::BackgroundZoneTypeList & zones)
Gets the list of background zone positions and values
Returns:
The list of background zone positions and values
Referenced by CFusionCHPHeaderCOM::GetBackgroundZones().
std::wstring FusionCHPHeader::GetChipType () const
Gets the chip type
Returns:
The chip type
Definition at line 127 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetChipType(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader().
Referenced by CFusionCHPHeaderCOM::get_ChipType().
int FusionCHPHeader::GetCols () const
Gets the number of feature columns
Returns:
The number of feature columns
Definition at line 100 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetCols(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader().
Referenced by CFusionCHPHeaderCOM::get_Cols().
int FusionCHPHeader::GetMagic () const
Gets the magic number
Returns:
The magic number
Definition at line 212 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetMagic().
int FusionCHPHeader::GetNumProbeSets () const
Gets the number of probe sets
Returns:
The number of probe sets
Definition at line 115 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetNumProbeSets().
Referenced by ExpressionLegacyExample(), and CFusionCHPHeaderCOM::get_NumProbeSets().
std::wstring FusionCHPHeader::GetParentCellFile () const
Gets the parent CEL file
Returns:
The parent CEL file
Definition at line 169 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetParentCellFile().
Referenced by CFusionCHPHeaderCOM::get_ParentCellFile().
std::wstring FusionCHPHeader::GetProgID () const
Gets the prog ID
Returns:
The prog ID
Definition at line 175 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetProgID().
Referenced by CFusionCHPHeaderCOM::get_ProgID().
int FusionCHPHeader::GetRows () const
Gets the number of feature rows
Returns:
The number of feature rows
Definition at line 108 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetRows().
Referenced by CFusionCHPHeaderCOM::get_Rows().
std::wstring FusionCHPHeader::GetSummaryParameter (const wchar_t * tag)
Gets a specific summary parameter given a name/tag
Returns:
The specific summary parameter given a name/tag
Definition at line 188 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetSummaryParameter().
Referenced by CFusionCHPHeaderCOM::GetSummaryParameter().
int FusionCHPHeader::GetVersion () const
Gets the version number
Returns:
The version number
Definition at line 92 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetVersion().
u_int32_t FusionCHPHeader::SummaryParameterCount ()
Gets the summary parameters count
Returns:
The number of summary parameters.
Definition at line 157 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetSummaryParameterCount().
Referenced by CFusionCHPHeaderCOM::get_SummaryParameterCount().
void FusionCHPHeader::SummaryParameters (FusionTagValuePairTypeList & p)
Gets the summary parameters
Returns:
The summary parameters
Definition at line 163 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader(), and affymetrix_fusion_io::IFusionCHPHeaderAdapter::GetSummaryParameters().
Referenced by CFusionCHPHeaderCOM::get_SummaryParameters(), and CFusionCHPHeaderCOM::GetSummaryParameterName().
Friends And Related Function Documentation
friend class FusionCHPLegacyData [friend]
Definition at line 168 of file FusionCHPLegacyData.h.
Member Data Documentation
IFusionCHPDataAdapter* affymetrix_fusion_io::FusionCHPHeader::adapter [protected]
The adapter interface.
Definition at line 171 of file FusionCHPLegacyData.h.
Referenced by AlgorithmParameterCount(), AlgorithmParameters(), CheckAdapter(), Clear(), affymetrix_fusion_io::FusionCHPLegacyData::CreateAdapter(), affymetrix_fusion_io::FusionCHPLegacyData::DeleteAdapter(), FusionCHPHeader(), GetAlgName(), GetAlgorithmParameter(), GetAlgVersion(), GetAssayType(), affxchp::CCHPFileHeader::GetBackgroundZone(), GetChipType(), GetCols(), GetMagic(), GetNumProbeSets(), GetParentCellFile(), GetProgID(), GetRows(), GetSummaryParameter(), GetVersion(), SummaryParameterCount(), and SummaryParameters().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPLegacyData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPLegacyData.cpp