Affymetrix Fusion SDK: affymetrix_calvin_io::CHPQuantificationData Class Reference
affymetrix_calvin_io::CHPQuantificationData Class Reference
#include <CHPQuantificationData.h>
Public Member Functions
CHPQuantificationData ()
CHPQuantificationData (const std::string &filename)
~CHPQuantificationData ()
int GetMaxProbeSetName () const
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename () const
std::wstring GetArrayType ()
void SetArrayType (const std::wstring &value)
void SetEntryCount (int32_t ln, int32_t maxln)
void SetEntryCount (int32_t ln)
int32_t GetEntryCount ()
std::wstring GetAlgName ()
void SetAlgName (const std::wstring &value)
std::wstring GetAlgVersion ()
void SetAlgVersion (const std::wstring &value)
ParameterNameValueTypeList GetAlgParams ()
void AddAlgParams (const ParameterNameValueTypeList &params)
ParameterNameValueTypeList GetSummaryParams ()
void AddSummaryParams (const ParameterNameValueTypeList &params)
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
void GetQuantificationEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationData &entry)
void OpenQuantificationDataSet ()
DataSetHeader & GetDataSetHeader ()
Private Member Functions
std::wstring GetWStringFromGenericHdr (const std::wstring &name)
void SetWStringToGenericHdr (const std::wstring &name, const std::wstring value, int32_t reserve=-1)
void AddColumns (DataSetHeader &hdr, bool keyIsID)
Private Attributes
DataSetColumnTypes firstColumnType
GenericData genericData
DataSet * entries
int maxProbeSetName
Detailed Description
Holds data associated with quantification CHP files.
Definition at line 40 of file CHPQuantificationData.h.
Constructor & Destructor Documentation
CHPQuantificationData::CHPQuantificationData ()
Constructor
Definition at line 40 of file CHPQuantificationData.cpp.
References affymetrix_calvin_io::UnicodeCharColType.
CHPQuantificationData::CHPQuantificationData (const std::string & filename)
Constructor with file name.
Parameters:
filename The name of the CHP file.
Definition at line 48 of file CHPQuantificationData.cpp.
References CHP_QUANTIFICATION_TYPE, QUANTIFICATION_QUANTIFICATION_NAME, and affymetrix_calvin_io::UnicodeCharColType.
CHPQuantificationData::~CHPQuantificationData ()
Destructor
Definition at line 60 of file CHPQuantificationData.cpp.
Member Function Documentation
void affymetrix_calvin_io::CHPQuantificationData::AddAlgParams (const ParameterNameValueTypeList & params)
Adds the algorithm parameters.
Parameters:
params The algorithm parameters.
Referenced by CreateFileWithHeader().
void CHPQuantificationData::AddColumns (DataSetHeader & hdr, bool keyIsID) [private]
Adds the columns to the data set.
Parameters:
hdr The data set header.
keyIsID True if the probe set ids are to be stored, false for probe set names.
Definition at line 140 of file CHPQuantificationData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddAsciiColumn(), affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), affymetrix_calvin_io::DataSetHeader::AddIntColumn(), QUANTIFICATION_PROBE_SET_ID, QUANTIFICATION_PROBE_SET_NAME, and QUANTIFICATION_QUANTIFICATION_NAME.
void affymetrix_calvin_io::CHPQuantificationData::AddSummaryParams (const ParameterNameValueTypeList & params)
Adds the summary parameters.
Parameters:
params The summary parameters.
Referenced by CreateFileWithHeader().
void CHPQuantificationData::Clear ()
Clears the members.
Definition at line 70 of file CHPQuantificationData.cpp.
Referenced by affymetrix_calvin_io::CHPQuantificationFileReader::Read().
std::wstring CHPQuantificationData::GetAlgName ()
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 172 of file CHPQuantificationData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgName().
ParameterNameValueTypeList CHPQuantificationData::GetAlgParams ()
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 192 of file CHPQuantificationData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgParams().
std::wstring CHPQuantificationData::GetAlgVersion ()
Gets the algorithm version.
Returns:
The version.
Definition at line 182 of file CHPQuantificationData.cpp.
References ALG_VERSION_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgVersion().
std::wstring CHPQuantificationData::GetArrayType ()
Sets the array type
Definition at line 162 of file CHPQuantificationData.cpp.
References ARRAY_TYPE_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::GetArrayType().
DataSetHeader & CHPQuantificationData::GetDataSetHeader ()
Returns the data set header.
Definition at line 65 of file CHPQuantificationData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::GetDataSetHeader().
int32_t CHPQuantificationData::GetEntryCount ()
Gets the number of entries (probe sets)
Definition at line 86 of file CHPQuantificationData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSet(), and affymetrix_calvin_io::DataSetHeader::GetRowCnt().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::GetEntryCount(), and CalvinChpCheck::quantificationDataSame().
FileHeader* affymetrix_calvin_io::CHPQuantificationData::GetFileHeader () [inline]
Gets the file header.
Returns:
The file header.
Definition at line 148 of file CHPQuantificationData.h.
References genericData, and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_calvin_io::CHPQuantificationFileWriter::CHPQuantificationFileWriter(), and CreateFileWithHeader().
std::string CHPQuantificationData::GetFilename () const
Gets the file name.
Returns:
The file name.
Definition at line 81 of file CHPQuantificationData.cpp.
Referenced by CalvinChpCheck::quantificationDataSame(), and affymetrix_calvin_io::CHPQuantificationFileReader::Read().
GenericData& affymetrix_calvin_io::CHPQuantificationData::GetGenericData () [inline]
Gets the generic data object.
Returns:
The data object.
Definition at line 153 of file CHPQuantificationData.h.
References genericData.
Referenced by CreateFileWithHeader(), and affymetrix_calvin_io::CHPQuantificationFileReader::Read().
int affymetrix_calvin_io::CHPQuantificationData::GetMaxProbeSetName () const [inline]
The maximum length of a probe set name.
Definition at line 70 of file CHPQuantificationData.h.
References maxProbeSetName.
Referenced by affymetrix_calvin_io::CHPQuantificationFileWriter::CHPQuantificationFileWriter().
void CHPQuantificationData::GetQuantificationEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationData & entry)
Gets the sequence data.
Parameters:
index The row index.
entry The quantification value.
Definition at line 119 of file CHPQuantificationData.cpp.
References affymetrix_calvin_io::ASCIICharColType, affymetrix_calvin_data::_ProbeSetQuantificationData::id, affymetrix_calvin_io::IntColType, affymetrix_calvin_data::_ProbeSetQuantificationData::name, affymetrix_calvin_data::_ProbeSetQuantificationData::quantification, and affymetrix_calvin_io::UnicodeCharColType.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::GetQuantificationEntry(), and CalvinChpCheck::quantificationDataSame().
ParameterNameValueTypeList CHPQuantificationData::GetSummaryParams ()
Gets the summary parameters
Returns:
The summary parameters.
Definition at line 226 of file CHPQuantificationData.cpp.
References CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::GetSummaryParams().
std::wstring CHPQuantificationData::GetWStringFromGenericHdr (const std::wstring & name) [private]
Gets a parameter value as a string.
Parameters:
name The name of the parameter.
Returns:
The string representation.
Definition at line 260 of file CHPQuantificationData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueText().
void CHPQuantificationData::OpenQuantificationDataSet ()
Opens a group for reading.
Definition at line 149 of file CHPQuantificationData.cpp.
void CHPQuantificationData::SetAlgName (const std::wstring & value)
Sets the name of the algorithm.
Parameters:
value The algorithm name.
Definition at line 177 of file CHPQuantificationData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by CreateFileWithHeader().
void CHPQuantificationData::SetAlgVersion (const std::wstring & value)
Sets the algorithm version.
Parameters:
value The version.
Definition at line 187 of file CHPQuantificationData.cpp.
References ALG_VERSION_PARAM_NAME.
Referenced by CreateFileWithHeader().
void CHPQuantificationData::SetArrayType (const std::wstring & value)
Sets the array type.
Definition at line 167 of file CHPQuantificationData.cpp.
References ARRAY_TYPE_MAX_LEN, and ARRAY_TYPE_PARAM_NAME.
Referenced by CreateFileWithHeader().
void CHPQuantificationData::SetEntryCount (int32_t ln, int32_t maxln)
Sets the number of entries (probe sets). Use this function if names are to be stored.
Parameters:
ln The number of probe sets.
maxln The maximum length of a probe set name.
Definition at line 93 of file CHPQuantificationData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::ASCIICharColType, QUANTIFICATION_QUANTIFICATION_NAME, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by CreateFileWithHeader().
void CHPQuantificationData::SetEntryCount (int32_t ln)
Sets the number of entries (probe sets). Use this function if ids are to be stored.
Parameters:
ln The number of probe sets.
Definition at line 106 of file CHPQuantificationData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::IntColType, QUANTIFICATION_QUANTIFICATION_NAME, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CHPQuantificationData::SetFilename (const std::string & p)
Sets the file name.
Parameters:
p The name of the CHP file
Definition at line 76 of file CHPQuantificationData.cpp.
void CHPQuantificationData::SetWStringToGenericHdr (const std::wstring & name, const std::wstring value, int32_t reserve = -1) [private]
Adds a parameter name/value pair to the parameters section.
Parameters:
name The name of the parameter.
value The value of the parameter.
reserve The length of the string to reserve.
Definition at line 272 of file CHPQuantificationData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
Member Data Documentation
DataSet* affymetrix_calvin_io::CHPQuantificationData::entries [private]
chp data sets
Definition at line 62 of file CHPQuantificationData.h.
DataSetColumnTypes affymetrix_calvin_io::CHPQuantificationData::firstColumnType [private]
Flag indicating if the probe set names were stored in wide character format.
Definition at line 56 of file CHPQuantificationData.h.
GenericData affymetrix_calvin_io::CHPQuantificationData::genericData [private]
The generic data item.
Definition at line 59 of file CHPQuantificationData.h.
Referenced by GetFileHeader(), and GetGenericData().
int affymetrix_calvin_io::CHPQuantificationData::maxProbeSetName [private]
The maximum length of a probe set name.
Definition at line 65 of file CHPQuantificationData.h.
Referenced by GetMaxProbeSetName().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CHPQuantificationData.h
C:/f112/affy/sdk/calvin_files/data/src/CHPQuantificationData.cpp