Affymetrix Fusion SDK: affx::ClfFile Class Reference
affx::ClfFile Class Reference
To be called a CLF file, the file requires.
#include <ClfFile.h>
Public Member Functions
ClfFile ()
Create the ClfFile object.
~ClfFile ()
Destroy a ClfFile object.
int getXMax ()
int getYMax ()
int getSequential ()
Return the value of the sequential header.
std::string getOrder ()
Return the value of the order header.
void makeClfBindings ()
Make the bindings which define a CLF file.
int open (const std::string &filename)
Open a CLF file.
int write (const std::string &filename)
Start the write to a file.
int close ()
Close a PGF file.
int rewind ()
Rewind back to the start of the CLF data.
int next_probe ()
Skip to the next probe.
int defineFileClf (TsvFile *tsv)
Define a tsv file as a CLF file.
int defineFileClf ()
Define this file as a pgf file.
Public Attributes
affx::TsvFile m_tsv
public so people can work with it
int probe_id
If you want the string forms, use "clf->tsv->get(0,"probe_id",probe_id_string)".
int x
The x position of the probe.
int y
The y position of the probe.
Detailed Description
To be called a CLF file, the file requires.
Definition at line 41 of file ClfFile.h.
Constructor & Destructor Documentation
affx::ClfFile::ClfFile ()
Create the ClfFile object.
Definition at line 152 of file ClfFile.cpp.
References makeClfBindings().
affx::ClfFile::~ClfFile ()
Destroy a ClfFile object.
Definition at line 157 of file ClfFile.cpp.
Member Function Documentation
int affx::ClfFile::close ()
Close a PGF file.
Returns:
tsv_return_t
Definition at line 248 of file ClfFile.cpp.
References affx::TsvFile::close(), and m_tsv.
int affx::ClfFile::defineFileClf (TsvFile * tsv)
Define a tsv file as a CLF file.
Parameters:
tsv pointer to tsv to define
Returns:
tsv_return_t
Definition at line 267 of file ClfFile.cpp.
References Err::check(), and affx::TsvFile::defineFile().
int affx::ClfFile::defineFileClf ()
Define this file as a pgf file.
Returns:
tsv_return_t
Definition at line 274 of file ClfFile.cpp.
References m_tsv.
std::string affx::ClfFile::getOrder ()
Return the value of the order header.
Returns:
the value of the order header if present
Definition at line 199 of file ClfFile.cpp.
References Err::check(), affx::TsvFile::getHeader(), m_tsv, and affx::TSV_OK.
int affx::ClfFile::getSequential ()
Return the value of the sequential header.
Returns:
int value of the header or -1 if not present
Definition at line 184 of file ClfFile.cpp.
References Err::check(), affx::TsvFile::getHeader(), m_tsv, and affx::TSV_OK.
int affx::ClfFile::getXMax ()
Definition at line 162 of file ClfFile.cpp.
References Err::check(), affx::TsvFile::getHeader(), m_tsv, and affx::TSV_OK.
int affx::ClfFile::getYMax ()
Definition at line 172 of file ClfFile.cpp.
References Err::check(), affx::TsvFile::getHeader(), m_tsv, and affx::TSV_OK.
void affx::ClfFile::makeClfBindings ()
Make the bindings which define a CLF file.
Definition at line 216 of file ClfFile.cpp.
References affx::TsvFile::bind(), m_tsv, probe_id, affx::TSV_BIND_REQUIRED, affx::TsvFile::unbindAll(), x, and y.
Referenced by ClfFile().
int affx::ClfFile::next_probe ()
Skip to the next probe.
Returns:
TSV_LEVEL_LAST when out of probesets
Definition at line 260 of file ClfFile.cpp.
References m_tsv, and affx::TsvFile::nextLevel().
Referenced by example_walk_clf().
int affx::ClfFile::open (const std::string & filename)
Open a CLF file.
Parameters:
filename the pathname of the file
Returns:
tsv_return_t
Definition at line 228 of file ClfFile.cpp.
References Err::check(), affx::TsvFile::getHeader(), m_tsv, affx::TsvFile::open(), and affx::TSV_OK.
Referenced by example_walk_clf().
int affx::ClfFile::rewind ()
Rewind back to the start of the CLF data.
Returns:
tsv_return_t
Definition at line 254 of file ClfFile.cpp.
References m_tsv, and affx::TsvFile::rewind().
int affx::ClfFile::write (const std::string & filename)
Start the write to a file.
Parameters:
filename
Returns:
tsv_return_t
Definition at line 242 of file ClfFile.cpp.
References m_tsv, and affx::TsvFile::writeTsv().
Member Data Documentation
affx::TsvFile affx::ClfFile::m_tsv
public so people can work with it
Definition at line 43 of file ClfFile.h.
Referenced by close(), defineFileClf(), example_walk_clf(), getOrder(), getSequential(), getXMax(), getYMax(), makeClfBindings(), next_probe(), open(), rewind(), and write().
int affx::ClfFile::probe_id
If you want the string forms, use "clf->tsv->get(0,"probe_id",probe_id_string)".
The probe id
Definition at line 47 of file ClfFile.h.
Referenced by makeClfBindings().
int affx::ClfFile::x
The x position of the probe.
Definition at line 48 of file ClfFile.h.
Referenced by makeClfBindings().
int affx::ClfFile::y
The y position of the probe.
Definition at line 49 of file ClfFile.h.
Referenced by makeClfBindings().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/ClfFile.h
C:/f112/affy/sdk/file/TsvFile/ClfFile.cpp