Affymetrix Fusion SDK: AptVersionInfo Class Reference
AptVersionInfo Class Reference
#include <AptVersionInfo.h>
Static Public Member Functions
static std::string version ()
static std::string cvsId ()
static std::string versionToReport ()
static std::string reportBambooBuild ()
static std::string reportCompileCCVersion ()
static std::string reportCompileDate ()
static std::string reportCompileHost ()
static std::string reportCompileOS ()
static std::string reportRelease ()
static std::string reportSVNVersion ()
static std::string reportSVNURL ()
Detailed Description
Definition at line 108 of file AptVersionInfo.h.
Member Function Documentation
static std::string AptVersionInfo::cvsId () [inline, static]
Definition at line 114 of file AptVersionInfo.h.
References APT_VER_SVN_URL, APT_VER_SVN_VERSION, and ToStr().
Referenced by main(), and versionToReport().
static std::string AptVersionInfo::reportBambooBuild () [inline, static]
Definition at line 122 of file AptVersionInfo.h.
References APT_VER_BAMBOO_BUILD, and ToStr().
static std::string AptVersionInfo::reportCompileCCVersion () [inline, static]
Definition at line 125 of file AptVersionInfo.h.
References APT_VER_COMPILE_CC_VERSION, and ToStr().
static std::string AptVersionInfo::reportCompileDate () [inline, static]
Definition at line 128 of file AptVersionInfo.h.
References APT_VER_COMPILE_DATE, and ToStr().
static std::string AptVersionInfo::reportCompileHost () [inline, static]
Definition at line 131 of file AptVersionInfo.h.
References APT_VER_COMPILE_HOST, and ToStr().
static std::string AptVersionInfo::reportCompileOS () [inline, static]
Definition at line 134 of file AptVersionInfo.h.
References APT_VER_COMPILE_OS, and ToStr().
static std::string AptVersionInfo::reportRelease () [inline, static]
Definition at line 137 of file AptVersionInfo.h.
References APT_VER_RELEASE, and ToStr().
static std::string AptVersionInfo::reportSVNURL () [inline, static]
Definition at line 143 of file AptVersionInfo.h.
References APT_VER_SVN_URL, and ToStr().
static std::string AptVersionInfo::reportSVNVersion () [inline, static]
Definition at line 140 of file AptVersionInfo.h.
References APT_VER_SVN_VERSION, and ToStr().
static std::string AptVersionInfo::version () [inline, static]
Definition at line 110 of file AptVersionInfo.h.
References APT_VER_RELEASE, and ToStr().
Referenced by main(), and versionToReport().
static std::string AptVersionInfo::versionToReport () [inline, static]
Definition at line 118 of file AptVersionInfo.h.
References APT_VER_BAMBOO_BUILD, cvsId(), ToStr(), and version().
Referenced by main().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/AptVersionInfo.h