Affymetrix Fusion SDK: FsPath Class Reference
FsPath Class Reference
A class for working with richer filepaths than just a string. APT would like to be able to name where to read and write data. when there was just one dataset per file the filename was sufficient to to do this. The dataset name was simply mapped into the file system. Now things are more complicated. A file can contain several datasets.
#include <FsPath.h>
Public Types
enum FileFmt_t {
FILEFMT_NONE = 0, FILEFMT_ANY, FILEFMT_AUTO, FILEFMT_CALVIN,
FILEFMT_FILE5, FILEFMT_TEXT, FILEFMT_TSVFILE
}
Codes for the different formats APT might expect files to be in.
Public Member Functions
FsPath ()
new and empty path
FsPath (const FsPath &fspath)
a new copy of fspath
FsPath (const std::string &path)
new fspath and call setPath.
FsPath (const std::string &dir, const std::string &name, const std::string &ext)
new fspath and the user tells us the three parts.
void init ()
clear and reset the defaults.
void clear ()
clear the data only.
void dump ()
dump the FsPath to stdout.
bool empty ()
True if it does not have a value.
void setErrAbort (bool abortOnErr)
when set to false, dont throw an exception on an error.
AptErr_t getErrNum () const
the error value.
AptErr_t clearErr ()
clear the error; always returns APT_OK
AptErr_t setErr (AptErr_t err_num, const std::string &err_msg)
sets the error value and throws if abortOnErr==true
AptErr_t setErrFromFs ()
copies the error code from the current APT Fs error code
AptErr_t setPath (const std::string &pathname)
parses the string into its parts.
AptErr_t setPath (const FsPath &fspath)
copies the value
AptErr_t setPath (const std::string &dirname, const std::string &file_name, const std::string &file_ext)
sets the three components at once. (no parsing.)
const FsPath & operator= (const FsPath &path)
assignment.
void copyFrom (const FsPath &path)
assignment again.
void copyDirNameFrom (const FsPath &path)
just copy the directory parts.
void copyFileNameFrom (const FsPath &path)
just copy the filename parts.
bool operator== (const FsPath &path)
do the names match?
bool equals (const FsPath &path)
do the names match?
void setDirDrive (const std::string &val)
set the option of pathsep.
void setDirName (const std::string &val)
treat the entire path as a dir name.
void setFileName (const std::string &val)
sets the file name (not the dirname or ext)
void setFileNameExt (const std::string &file, const std::string &ext)
sets the file and ext (not the dirname)
void setFileExt (const std::string &val)
sets the extension (".foo")
void setInternalGroupName (const std::string &val)
sets the internal group name (like for file5)
void setInternalTableName (const std::string &val)
sets the internal table name (like for file5)
std::string getOriginalPath () const
the orginal path given to setPath (For debugging)
std::string getDirDrive () const
the windows drive
std::string getDirName () const
the directory path (no slash)
std::string getDirNameSlash () const
the directory path (with slash)
std::vector< std::string > getDirNames () const
the directory path as a list of components.
std::string getFileName () const
the filename (wo ext; "foo.bar" => "foo")
std::string getFileNameWoExt () const
the filename (wo ext; "foo.bar" => "foo")
std::string getFileExt () const
just the extention ("foo.bar" => "bar")
std::string getBaseName () const
the file and extension. (like unix basename)
std::string getInternalGroupName () const
the internal group name (like for file5)
std::string getInternalTableName () const
the internal table name (like for file5)
void pushDir (const std::string &dir)
push a dirname on the end of the dir path.
bool canPopDir () const
could we pop another name off the directory path?
std::string popDir ()
pops a dirname off the end of the path. ("foo/bar/baz" => "foo/bar" returns "baz")
FsPath::FileFmt_t fmtFromExt () const
map the extension to a filefmt.
FsPath::FileFmt_t getFileFmt () const
void setFileFmt (FsPath::FileFmt_t fmt)
std::string asString () const
std::string asUnixPath () const
format the path for unix. (Which is our internal format.)
const char * asUnixPathCstr () const
format the path and return a tmp "const char*".
std::string asUncPath () const
what should pass to the OS to open with. (a no-op on unix)
const char * osUncPathCstr () const
selects asWindowsPath or asUnixPath.
bool isAbsolute () const
is this an absolute path? "/foo/..."?
bool isDirName () const
Does this name a directory? (no file name or ext)
bool isFileName () const
Does this name a file? (file name or ext is set.)
bool exists () const
does this exist in the filesystem? (file or dir)
bool dirExists () const
bool fileExists () const
bool isWriteableDir () const
bool isWriteableDir (AptErr_t &rv) const
bool isReadable () const
Could we read from this path? (file or dir)
bool isWriteable () const
Could we write to this path? (file or dir)
int64_t fileSize ()
the size of the file in bytes.
AptErr_t mkdir (bool errIfExists=true)
tries to make one directory (just the last part of dirpath)
AptErr_t mkdirPath (bool errIfExists=true)
tries to make the entire path. (like mkdir -p)
AptErr_t ensureWriteableDirPath ()
Makes.
AptErr_t rmdir (bool errIfNotExists=true)
remove the directory. (dir must be empty.)
AptErr_t rmdirPath (bool errIfNotExists=true)
remove the path of dirs (all dirs must be empty.)
AptErr_t listDir (std::vector< std::string > &names)
returns a list of names in the dir.
AptErr_t rm (bool errIfNotExists=false)
removes a file.
AptErr_t chmod (int mode, bool errIfNotExists=true)
changes the mode (dir or file)
AptErr_t touch ()
creates the file if it does not exist.
int64_t getFreeDiskSpace () const
rename the file to the new name
bool isSameVolume (const std::string &dirname)
are the paths on the same volume?
bool isSameVolume (const FsPath &fspath)
are the paths on the same volume?
bool isSameVolume (const FsPath &fspath, AptErr_t &rv)
are the paths on the same volume?
Static Public Member Functions
static FsPath getPathFor (const std::string &loc)
static void addExt2Fmt (const std::string &ext, FsPath::FileFmt_t fmt)
add a mapping from ".foo" to FILEFMT_FOO
static FileFmt_t ext2Fmt (const std::string &ext)
convert the extention to the format based on the extension.
Private Attributes
bool m_err_doAbort
true=throw and error when m_err_num != APT_OK
AptErr_t m_err_num
the last error.
std::string m_err_msg
the last error message
std::string m_original_path
std::string m_dir_drive
the windows drive "C:"
std::string m_dir_name
the directory path "/var/tmp"
std::string m_file_name
the filename part of the name: "myfile"
std::string m_file_ext
the extension part of the name: ".cpp", ".h"
std::string m_tmp_cstr
tmp string used for buffer the return of a "const char*"
std::string m_internal_group_name
the group name inside the file.
std::string m_internal_table_name
the tablename/dataset inside the file.
FsPath::FileFmt_t m_filefmt
Static Private Attributes
static std::map< std::string,
FsPath::FileFmt_t > m_ext2fmt_map
static int m_ext2fmt_map_isloaded = 0
Detailed Description
A class for working with richer filepaths than just a string. APT would like to be able to name where to read and write data. when there was just one dataset per file the filename was sufficient to to do this. The dataset name was simply mapped into the file system. Now things are more complicated. A file can contain several datasets.
Currently this is handled by also passing in more options to name the group and table. However this is done different ways in APT. The goal of FsPath is to be able to name these datasets and provide a convenient set of methods to work with the names.
FsPath keeps its names in seperate pieces so the can be worked on and recombined without parsing a string in the code. The directory name, file name, internal group name and tablename (dataset) are all kept in the one object. This FsPath can be passed to the File libraries who can extract what they need.
The format of the FsPath is: /os/path/name/filename.EXT:group/names/tablename
(A) The path in the os. ("/os/path/name") (B) The filename and extension. ("filename.EXT") (C) The external/internal separator (":") (D) The internal path. ("group/names") file5 could have several parts. calvin must have one and only one level of group names. TsvFile can be extended to use the filesystem to have groups. (E) The tablename/dataset name ("tablename")
With all this we could then write:
FsPath path("path/to/file.EXT:/group/table") DaoDataSet dataset;
dataset->open(path);
and the EXT would do the magic for Calvin, File5 or TsvFile.
Thinking about this some more, it might be best to break out the operating system calls into a seperate module which takes a string or a FsPath object to do things with.
Note: according to APT-380, "Desktop" and other special windows dirs might be flagged as write-only, but actually be writeable. If this is really the case then "isWriteable" should be a two step process: if (s_writeable()) { return true; } if (is_windows()) { if (try_and_make_a_dir_works()) { return true; } } return false.
Ideas: * Add "void*" to the actual file being opened for reference. and marker for what type is being held.
To migrate current functionality:
UncPath() here
BaseName()
FileRoot()
Openers for raw streams.
IsWritable() or equivalent
Definition at line 119 of file FsPath.h.
Member Enumeration Documentation
enum FsPath::FileFmt_t
Codes for the different formats APT might expect files to be in.
Enumerator:
FILEFMT_NONE
FILEFMT_ANY
FILEFMT_AUTO
FILEFMT_CALVIN
FILEFMT_FILE5
FILEFMT_TEXT
FILEFMT_TSVFILE
Definition at line 123 of file FsPath.h.
Constructor & Destructor Documentation
FsPath::FsPath ()
new and empty path
Definition at line 138 of file FsPath.cpp.
References init().
FsPath::FsPath (const FsPath & fspath)
a new copy of fspath
Definition at line 142 of file FsPath.cpp.
References copyFrom().
FsPath::FsPath (const std::string & path)
new fspath and call setPath.
Definition at line 146 of file FsPath.cpp.
References init(), and setPath().
FsPath::FsPath (const std::string & dir, const std::string & name, const std::string & ext)
new fspath and the user tells us the three parts.
Definition at line 151 of file FsPath.cpp.
References Fs::addTrailingSlash(), init(), m_dir_name, m_file_ext, and m_file_name.
Member Function Documentation
void FsPath::addExt2Fmt (const std::string & ext, FsPath::FileFmt_t fmt) [static]
add a mapping from ".foo" to FILEFMT_FOO
Definition at line 83 of file FsPath.cpp.
References m_ext2fmt_map.
Referenced by ext2Fmt().
std::string FsPath::asString () const
a printable string which could be passed to our "setPath()" but it cant be opened in the filesystem. it has the internal group and table names.
Definition at line 503 of file FsPath.cpp.
References FSPATH_EXTSEP, FSPATH_INTERNAL_PATHSEP, FSPATH_PATHSEP, m_dir_drive, m_dir_name, m_file_ext, m_file_name, m_internal_group_name, and m_internal_table_name.
Referenced by dump().
std::string FsPath::asUncPath () const
what should pass to the OS to open with. (a no-op on unix)
Definition at line 488 of file FsPath.cpp.
References asUnixPath(), and Fs::convertToUncPathInPlace().
Referenced by osUncPathCstr().
std::string FsPath::asUnixPath () const
format the path for unix. (Which is our internal format.)
Definition at line 448 of file FsPath.cpp.
References FSPATH_EXTSEP, FSPATH_PATHSEP, m_dir_drive, m_dir_name, m_file_ext, and m_file_name.
Referenced by asUncPath(), asUnixPathCstr(), chmod(), dirExists(), dump(), exists(), fileExists(), getFreeDiskSpace(), isReadable(), isSameVolume(), isWriteableDir(), listDir(), mkdir(), rm(), rmdir(), and touch().
const char * FsPath::asUnixPathCstr () const
format the path and return a tmp "const char*".
Definition at line 473 of file FsPath.cpp.
References asUnixPath(), and m_tmp_cstr.
bool FsPath::canPopDir () const
could we pop another name off the directory path?
Definition at line 571 of file FsPath.cpp.
References FSPATH_PATHSEP, and m_dir_name.
Referenced by rmdirPath().
AptErr_t FsPath::chmod (int mode, bool errIfNotExists = true)
changes the mode (dir or file)
Definition at line 651 of file FsPath.cpp.
References asUnixPath(), Fs::chmodBasic(), and setErrFromFs().
void FsPath::clear (void)
clear the data only.
Definition at line 167 of file FsPath.cpp.
References FILEFMT_AUTO, m_dir_drive, m_dir_name, m_file_ext, m_file_name, m_filefmt, m_internal_group_name, m_internal_table_name, and m_original_path.
Referenced by init(), mkdirPath(), and setPath().
AptErr_t FsPath::clearErr ()
clear the error; always returns APT_OK
Definition at line 305 of file FsPath.cpp.
References APT_OK, m_err_msg, and m_err_num.
Referenced by mkdirPath(), rmdir(), and rmdirPath().
void FsPath::copyDirNameFrom (const FsPath & path)
just copy the directory parts.
Definition at line 231 of file FsPath.cpp.
References m_dir_name.
void FsPath::copyFileNameFrom (const FsPath & path)
just copy the filename parts.
Definition at line 235 of file FsPath.cpp.
References m_file_ext, m_file_name, and m_filefmt.
void FsPath::copyFrom (const FsPath & path)
assignment again.
Definition at line 211 of file FsPath.cpp.
References m_dir_drive, m_dir_name, m_file_ext, m_file_name, m_filefmt, m_internal_group_name, and m_internal_table_name.
Referenced by FsPath(), operator=(), and setPath().
bool FsPath::dirExists () const
Definition at line 557 of file FsPath.cpp.
References asUnixPath().
void FsPath::dump ()
dump the FsPath to stdout.
Definition at line 184 of file FsPath.cpp.
References asString(), asUnixPath(), FSPATH_DUMP_D, FSPATH_DUMP_S, m_dir_name, m_file_ext, m_file_name, m_filefmt, m_internal_group_name, m_internal_table_name, and m_original_path.
bool FsPath::empty (void)
True if it does not have a value.
Definition at line 200 of file FsPath.cpp.
References m_dir_name, m_file_ext, m_file_name, m_internal_group_name, and m_internal_table_name.
AptErr_t FsPath::ensureWriteableDirPath ()
Makes.
Definition at line 631 of file FsPath.cpp.
References APT_ERR, APT_OK, isWriteableDir(), mkdirPath(), and setErr().
bool FsPath::equals (const FsPath & path)
do the names match?
Definition at line 242 of file FsPath.cpp.
References FSPATH_NEQ, m_dir_name, m_file_ext, m_file_name, m_internal_group_name, and m_internal_table_name.
Referenced by operator==().
bool FsPath::exists () const
does this exist in the filesystem? (file or dir)
Definition at line 553 of file FsPath.cpp.
References asUnixPath().
FsPath::FileFmt_t FsPath::ext2Fmt (const std::string & ext) [static]
convert the extention to the format based on the extension.
Todo:
handle case (e.g. 'A5' && 'a5' are equivalent
Definition at line 89 of file FsPath.cpp.
References addExt2Fmt(), FILEFMT_NONE, initial_ext2fmt, FsPath_Ext2fmt_t::m_ext, m_ext2fmt_map, m_ext2fmt_map_isloaded, and FsPath_Ext2fmt_t::m_fmt.
Referenced by fmtFromExt().
bool FsPath::fileExists () const
Definition at line 561 of file FsPath.cpp.
References asUnixPath().
int64_t FsPath::fileSize ()
the size of the file in bytes.
FsPath::FileFmt_t FsPath::fmtFromExt () const
map the extension to a filefmt.
Definition at line 427 of file FsPath.cpp.
References ext2Fmt(), and m_file_ext.
Referenced by getFileFmt().
std::string FsPath::getBaseName () const
the file and extension. (like unix basename)
Definition at line 438 of file FsPath.cpp.
References FSPATH_EXTSEP, m_file_ext, and m_file_name.
std::string FsPath::getDirDrive () const [inline]
the windows drive
Definition at line 227 of file FsPath.h.
References m_dir_drive.
std::string FsPath::getDirName () const
the directory path (no slash)
Definition at line 409 of file FsPath.cpp.
References m_dir_drive, m_dir_name, and Fs::trimTrailingSlash().
std::vector< std::string > FsPath::getDirNames () const
the directory path as a list of components.
Definition at line 417 of file FsPath.cpp.
References m_dir_name, and Fs::splitPath().
Referenced by mkdirPath().
std::string FsPath::getDirNameSlash () const
the directory path (with slash)
Definition at line 413 of file FsPath.cpp.
References Fs::addTrailingSlash(), m_dir_drive, and m_dir_name.
AptErr_t FsPath::getErrNum () const
the error value.
Definition at line 281 of file FsPath.cpp.
References m_err_num.
Referenced by mkdirPath().
std::string FsPath::getFileExt () const [inline]
just the extention ("foo.bar" => "bar")
Definition at line 239 of file FsPath.h.
References m_file_ext.
FsPath::FileFmt_t FsPath::getFileFmt () const
Definition at line 431 of file FsPath.cpp.
References FILEFMT_AUTO, fmtFromExt(), and m_filefmt.
std::string FsPath::getFileName () const [inline]
the filename (wo ext; "foo.bar" => "foo")
Definition at line 235 of file FsPath.h.
References m_file_name.
std::string FsPath::getFileNameWoExt () const [inline]
the filename (wo ext; "foo.bar" => "foo")
Definition at line 237 of file FsPath.h.
References m_file_name.
int64_t FsPath::getFreeDiskSpace () const
rename the file to the new name
copy the file to the path the free space measured in bytes.
Definition at line 753 of file FsPath.cpp.
References asUnixPath().
std::string FsPath::getInternalGroupName () const [inline]
the internal group name (like for file5)
Definition at line 243 of file FsPath.h.
References m_internal_group_name.
std::string FsPath::getInternalTableName () const [inline]
the internal table name (like for file5)
Definition at line 245 of file FsPath.h.
References m_internal_table_name.
std::string FsPath::getOriginalPath () const [inline]
the orginal path given to setPath (For debugging)
Definition at line 225 of file FsPath.h.
References m_original_path.
FsPath FsPath::getPathFor (const std::string & loc) [static]
get a FsPath for a named location. (HOME, TMP, CWD) presently read from the process environment.
Definition at line 114 of file FsPath.cpp.
References setDirName(), and setPath().
void FsPath::init ()
clear and reset the defaults.
Definition at line 159 of file FsPath.cpp.
References clear(), and m_err_doAbort.
Referenced by FsPath().
bool FsPath::isAbsolute () const
is this an absolute path? "/foo/..."?
Definition at line 530 of file FsPath.cpp.
References FSPATH_PATHSEP, and m_dir_name.
bool FsPath::isDirName () const
Does this name a directory? (no file name or ext)
Definition at line 544 of file FsPath.cpp.
References m_dir_name, m_file_ext, and m_file_name.
bool FsPath::isFileName () const
Does this name a file? (file name or ext is set.)
Definition at line 537 of file FsPath.cpp.
References m_file_ext, and m_file_name.
bool FsPath::isReadable () const
Could we read from this path? (file or dir)
Definition at line 617 of file FsPath.cpp.
References asUnixPath().
bool FsPath::isSameVolume (const std::string & dirname)
are the paths on the same volume?
Definition at line 759 of file FsPath.cpp.
References asUnixPath(), and m_err_doAbort.
Referenced by isSameVolume().
bool FsPath::isSameVolume (const FsPath & fspath, AptErr_t & rv)
are the paths on the same volume?
bool FsPath::isSameVolume (const FsPath & fspath)
are the paths on the same volume?
Definition at line 765 of file FsPath.cpp.
References asUnixPath(), isSameVolume(), and m_err_doAbort.
bool FsPath::isWriteable () const
Could we write to this path? (file or dir)
bool FsPath::isWriteableDir (AptErr_t & rv) const
Definition at line 626 of file FsPath.cpp.
References asUnixPath(), and isWriteableDir().
bool FsPath::isWriteableDir () const
is this a directory we can write to? note that this is special on windows as we actually test it.
Definition at line 622 of file FsPath.cpp.
References asUnixPath().
Referenced by ensureWriteableDirPath(), and isWriteableDir().
AptErr_t FsPath::listDir (std::vector< std::string > & names)
returns a list of names in the dir.
Definition at line 739 of file FsPath.cpp.
References asUnixPath().
AptErr_t FsPath::mkdir (bool errIfExists = true)
tries to make one directory (just the last part of dirpath)
true if is a file and is in HDF5 format. bool osIsHdf5() const;
Definition at line 657 of file FsPath.cpp.
References asUnixPath(), and setErrFromFs().
Referenced by mkdirPath().
AptErr_t FsPath::mkdirPath (bool errIfExists = true)
tries to make the entire path. (like mkdir -p)
Definition at line 663 of file FsPath.cpp.
References APT_OK, clear(), clearErr(), getDirNames(), getErrNum(), m_err_msg, m_err_num, mkdir(), pushDir(), setErr(), and setErrAbort().
Referenced by ensureWriteableDirPath().
const FsPath& FsPath::operator= (const FsPath & path) [inline]
assignment.
Definition at line 181 of file FsPath.h.
References copyFrom().
bool FsPath::operator== (const FsPath & path) [inline]
do the names match?
Definition at line 195 of file FsPath.h.
References equals().
const char * FsPath::osUncPathCstr () const
selects asWindowsPath or asUnixPath.
Definition at line 496 of file FsPath.cpp.
References asUncPath(), and m_tmp_cstr.
std::string FsPath::popDir ()
pops a dirname off the end of the path. ("foo/bar/baz" => "foo/bar" returns "baz")
Definition at line 578 of file FsPath.cpp.
References FSPATH_PATHSEP, m_dir_name, and Fs::trimTrailingSlash().
Referenced by rmdirPath().
void FsPath::pushDir (const std::string & dir)
push a dirname on the end of the dir path.
Definition at line 567 of file FsPath.cpp.
References Fs::addTrailingSlash(), and m_dir_name.
Referenced by mkdirPath().
AptErr_t FsPath::rm (bool errIfNotExists = false)
removes a file.
Definition at line 689 of file FsPath.cpp.
References APT_ERR_NOTEXISTS, APT_OK, asUnixPath(), Fs::fileExists(), and setErr().
AptErr_t FsPath::rmdir (bool errIfNotExists = true)
remove the directory. (dir must be empty.)
Definition at line 699 of file FsPath.cpp.
References APT_ERR_NOTEXISTS, APT_ERR_NOTREMOVED, asUnixPath(), clearErr(), Fs::dirExists(), and setErr().
Referenced by rmdirPath().
AptErr_t FsPath::rmdirPath (bool errIfNotExists = true)
remove the path of dirs (all dirs must be empty.)
Definition at line 718 of file FsPath.cpp.
References APT_OK, canPopDir(), clearErr(), popDir(), and rmdir().
void FsPath::setDirDrive (const std::string & val)
set the option of pathsep.
The value for windows. ("C:")
Definition at line 254 of file FsPath.cpp.
References m_dir_drive.
void FsPath::setDirName (const std::string & val)
treat the entire path as a dir name.
Definition at line 259 of file FsPath.cpp.
References Fs::addTrailingSlash(), m_dir_drive, m_dir_name, and Fs::unixifyPathInPlace().
Referenced by getPathFor().
AptErr_t FsPath::setErr (AptErr_t err_num, const std::string & err_msg)
sets the error value and throws if abortOnErr==true
Definition at line 285 of file FsPath.cpp.
References APT_OK, Err::errAbort(), m_err_doAbort, m_err_msg, and m_err_num.
Referenced by ensureWriteableDirPath(), mkdirPath(), rm(), rmdir(), and setErrFromFs().
void FsPath::setErrAbort (bool abortOnErr)
when set to false, dont throw an exception on an error.
Definition at line 277 of file FsPath.cpp.
References m_err_doAbort.
Referenced by mkdirPath().
AptErr_t FsPath::setErrFromFs ()
copies the error code from the current APT Fs error code
Definition at line 301 of file FsPath.cpp.
References Fs::getErrMsg(), Fs::getErrNum(), and setErr().
Referenced by chmod(), mkdir(), and touch().
void FsPath::setFileExt (const std::string & val) [inline]
sets the extension (".foo")
Definition at line 218 of file FsPath.h.
References m_file_ext.
void FsPath::setFileFmt (FsPath::FileFmt_t fmt) [inline]
Definition at line 257 of file FsPath.h.
References m_filefmt.
void FsPath::setFileName (const std::string & val) [inline]
sets the file name (not the dirname or ext)
Definition at line 211 of file FsPath.h.
References m_file_name.
void FsPath::setFileNameExt (const std::string & file, const std::string & ext) [inline]
sets the file and ext (not the dirname)
Definition at line 213 of file FsPath.h.
References m_file_ext, and m_file_name.
void FsPath::setInternalGroupName (const std::string & val) [inline]
sets the internal group name (like for file5)
Definition at line 220 of file FsPath.h.
References m_internal_group_name.
void FsPath::setInternalTableName (const std::string & val) [inline]
sets the internal table name (like for file5)
Definition at line 222 of file FsPath.h.
References m_internal_table_name.
AptErr_t FsPath::setPath (const std::string & dirname, const std::string & file_name, const std::string & file_ext)
sets the three components at once. (no parsing.)
Definition at line 318 of file FsPath.cpp.
References Fs::addTrailingSlash(), APT_OK, m_dir_name, m_file_ext, and m_file_name.
AptErr_t FsPath::setPath (const FsPath & fspath)
copies the value
Definition at line 313 of file FsPath.cpp.
References APT_OK, and copyFrom().
AptErr_t FsPath::setPath (const std::string & pathname)
parses the string into its parts.
Definition at line 330 of file FsPath.cpp.
References Fs::addTrailingSlash(), APT_OK, clear(), FSPATH_EXTSEP, FSPATH_INTERNAL_PATHSEP, FSPATH_PATHSEP, m_dir_drive, m_dir_name, m_file_ext, m_file_name, m_internal_group_name, m_internal_table_name, m_original_path, and Fs::unixifyPathInPlace().
Referenced by FsPath(), and getPathFor().
AptErr_t FsPath::touch ()
creates the file if it does not exist.
Definition at line 745 of file FsPath.cpp.
References asUnixPath(), and setErrFromFs().
Member Data Documentation
std::string FsPath::m_dir_drive [private]
the windows drive "C:"
Definition at line 358 of file FsPath.h.
Referenced by asString(), asUnixPath(), clear(), copyFrom(), getDirDrive(), getDirName(), getDirNameSlash(), setDirDrive(), setDirName(), and setPath().
std::string FsPath::m_dir_name [private]
the directory path "/var/tmp"
Definition at line 360 of file FsPath.h.
Referenced by asString(), asUnixPath(), canPopDir(), clear(), copyDirNameFrom(), copyFrom(), dump(), empty(), equals(), FsPath(), getDirName(), getDirNames(), getDirNameSlash(), isAbsolute(), isDirName(), popDir(), pushDir(), setDirName(), and setPath().
bool FsPath::m_err_doAbort [private]
true=throw and error when m_err_num != APT_OK
Definition at line 348 of file FsPath.h.
Referenced by init(), isSameVolume(), setErr(), and setErrAbort().
std::string FsPath::m_err_msg [private]
the last error message
Definition at line 352 of file FsPath.h.
Referenced by clearErr(), mkdirPath(), and setErr().
AptErr_t FsPath::m_err_num [private]
the last error.
Definition at line 350 of file FsPath.h.
Referenced by clearErr(), getErrNum(), mkdirPath(), and setErr().
std::map< std::string, FsPath::FileFmt_t > FsPath::m_ext2fmt_map [static, private]
Definition at line 376 of file FsPath.h.
Referenced by addExt2Fmt(), and ext2Fmt().
int FsPath::m_ext2fmt_map_isloaded = 0 [static, private]
Definition at line 378 of file FsPath.h.
Referenced by ext2Fmt().
std::string FsPath::m_file_ext [private]
the extension part of the name: ".cpp", ".h"
Definition at line 364 of file FsPath.h.
Referenced by asString(), asUnixPath(), clear(), copyFileNameFrom(), copyFrom(), dump(), empty(), equals(), fmtFromExt(), FsPath(), getBaseName(), getFileExt(), isDirName(), isFileName(), setFileExt(), setFileNameExt(), and setPath().
std::string FsPath::m_file_name [private]
the filename part of the name: "myfile"
Definition at line 362 of file FsPath.h.
Referenced by asString(), asUnixPath(), clear(), copyFileNameFrom(), copyFrom(), dump(), empty(), equals(), FsPath(), getBaseName(), getFileName(), getFileNameWoExt(), isDirName(), isFileName(), setFileName(), setFileNameExt(), and setPath().
FsPath::FileFmt_t FsPath::m_filefmt [private]
Definition at line 373 of file FsPath.h.
Referenced by clear(), copyFileNameFrom(), copyFrom(), dump(), getFileFmt(), and setFileFmt().
std::string FsPath::m_internal_group_name [private]
the group name inside the file.
Definition at line 368 of file FsPath.h.
Referenced by asString(), clear(), copyFrom(), dump(), empty(), equals(), getInternalGroupName(), setInternalGroupName(), and setPath().
std::string FsPath::m_internal_table_name [private]
the tablename/dataset inside the file.
Definition at line 370 of file FsPath.h.
Referenced by asString(), clear(), copyFrom(), dump(), empty(), equals(), getInternalTableName(), setInternalTableName(), and setPath().
std::string FsPath::m_original_path [private]
The path as it was given to us. only used for debugging.
Definition at line 356 of file FsPath.h.
Referenced by clear(), dump(), getOriginalPath(), and setPath().
std::string FsPath::m_tmp_cstr [mutable, private]
tmp string used for buffer the return of a "const char*"
Definition at line 366 of file FsPath.h.
Referenced by asUnixPathCstr(), and osUncPathCstr().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/FsPath.h
C:/f112/affy/sdk/util/FsPath.cpp