Affymetrix Fusion SDK: affymetrix_calvin_io::AuditFileWriter Class Reference
affymetrix_calvin_io::AuditFileWriter Class Reference
#include <AuditFileWriter.h>
Public Member Functions
AuditFileWriter ()
~AuditFileWriter ()
bool Write (const std::string &fileName, affymetrix_calvin_array::ArrayAuditEntry &auditData)
Detailed Description
This class provides interfaces to write an audit file.
Definition at line 34 of file AuditFileWriter.h.
Constructor & Destructor Documentation
AuditFileWriter::AuditFileWriter ()
Constructor
Definition at line 38 of file AuditFileWriter.cpp.
AuditFileWriter::~AuditFileWriter ()
Destructor
Definition at line 45 of file AuditFileWriter.cpp.
Member Function Documentation
bool AuditFileWriter::Write (const std::string & fileName, affymetrix_calvin_array::ArrayAuditEntry & auditData)
Writes the audit object to an audit file.
Parameters:
fileName The name of the audit file to write.
auditData The audit data to write to the file.
Returns:
True if the file was successfully written.
Definition at line 52 of file AuditFileWriter.cpp.
References affymetrix_calvin_array::ArrayAuditEntry::ActionParameters(), affymetrix_calvin_array::ArrayAuditEntry::ActionType(), affymetrix_calvin_array::ArrayAuditEntry::ArrayGuid(), AUDIT_ACTION_TAG, AUDIT_ARRAY_ID_TAG, AUDIT_DATE_TAG, AUDIT_END_TAG, AUDIT_INPUT_ID_TAG, AUDIT_OUTPUT_ID_TAG, AUDIT_START_TAG, AUDIT_TIME_TAG, AUDIT_USER_TAG, affymetrix_calvin_utilities::DateTime::Date(), affymetrix_calvin_array::ArrayAuditEntry::DateTime(), affymetrix_calvin_array::ArrayAuditEntry::InputFileGuids(), affymetrix_calvin_parameter::_tagParameterNameValuePair::Name, affymetrix_calvin_array::ArrayAuditEntry::OutputFileGuids(), affymetrix_calvin_utilities::DateTime::Time(), affymetrix_calvin_array::ArrayAuditEntry::UserName(), and affymetrix_calvin_parameter::_tagParameterNameValuePair::Value.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/AuditFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/AuditFileWriter.cpp