Affymetrix Fusion SDK: affymetrix_calvin_io::DataGroupHeaderUpdater Class Reference
affymetrix_calvin_io::DataGroupHeaderUpdater Class Reference
#include <DataGroupHeaderUpdater.h>
Public Member Functions
DataGroupHeaderUpdater (std::ofstream &fileStream, DataGroupHeader &hdr)
~DataGroupHeaderUpdater ()
void UpdateNextDataGroupOffset (u_int32_t offset)
void UpdateLeadDataSetOffset (u_int32_t offset)
void UpdateDataSetCount (u_int32_t count)
void AppendDataSetHeader (DataSetHeader &setHdr)
void ReplaceDataSetHeader (std::wstring targetName, DataSetHeader &newHdr)
Private Member Functions
void SeekNextDataGrpPosition ()
void SeekLeadDataSetPosition ()
void SeekDataSetCntPosition ()
Private Attributes
std::ofstream * os
DataGroupHeader * grpHdr
Detailed Description
This class updates the data set header of an existing file with new information.
Definition at line 41 of file DataGroupHeaderUpdater.h.
Constructor & Destructor Documentation
DataGroupHeaderUpdater::DataGroupHeaderUpdater (std::ofstream & fileStream, DataGroupHeader & hdr)
Constructor
Definition at line 36 of file DataGroupHeaderUpdater.cpp.
DataGroupHeaderUpdater::~DataGroupHeaderUpdater ()
Destructor
Definition at line 45 of file DataGroupHeaderUpdater.cpp.
Member Function Documentation
void DataGroupHeaderUpdater::AppendDataSetHeader (DataSetHeader & setHdr)
Append a new data set in this data group.
Parameters:
setHdr The new data set that will be appended.
Definition at line 94 of file DataGroupHeaderUpdater.cpp.
References affymetrix_calvin_io::DataSetWriter::GetDataSetSize(), affymetrix_calvin_io::DataSetHeader::SetDataStartFilePos(), affymetrix_calvin_io::DataSetHeader::SetHeaderStartFilePos(), affymetrix_calvin_io::DataSetHeader::SetNextSetFilePos(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), affymetrix_calvin_io::DataSetHeaderUpdater::UpdateNextDataSetPosition(), and affymetrix_calvin_io::DataSetWriter::WriteHeader().
void DataGroupHeaderUpdater::ReplaceDataSetHeader (std::wstring targetName, DataSetHeader & newHdr)
Replace a data set in this data group with a new one.
Parameters:
targetName The name of the data set to be replaced.
newHdr The new data set that will be written into the file.
Definition at line 122 of file DataGroupHeaderUpdater.cpp.
References affymetrix_calvin_io::DataSetWriter::GetDataSetSize(), affymetrix_calvin_io::DataSetHeader::SetDataStartFilePos(), affymetrix_calvin_io::DataSetHeader::SetHeaderStartFilePos(), affymetrix_calvin_io::DataSetHeader::SetNextSetFilePos(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), affymetrix_calvin_io::DataSetHeaderUpdater::UpdateNextDataSetPosition(), and affymetrix_calvin_io::DataSetWriter::WriteHeader().
void DataGroupHeaderUpdater::SeekDataSetCntPosition () [private]
Definition at line 62 of file DataGroupHeaderUpdater.cpp.
void DataGroupHeaderUpdater::SeekLeadDataSetPosition () [private]
Definition at line 55 of file DataGroupHeaderUpdater.cpp.
void DataGroupHeaderUpdater::SeekNextDataGrpPosition () [private]
Definition at line 49 of file DataGroupHeaderUpdater.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetHeaderStartFilePos().
void DataGroupHeaderUpdater::UpdateDataSetCount (u_int32_t count)
Definition at line 86 of file DataGroupHeaderUpdater.cpp.
void DataGroupHeaderUpdater::UpdateLeadDataSetOffset (u_int32_t offset)
Definition at line 78 of file DataGroupHeaderUpdater.cpp.
void DataGroupHeaderUpdater::UpdateNextDataGroupOffset (u_int32_t offset)
Definition at line 70 of file DataGroupHeaderUpdater.cpp.
Referenced by affymetrix_calvin_io::FileHeaderUpdater::AppendDataGroupHeader().
Member Data Documentation
DataGroupHeader* affymetrix_calvin_io::DataGroupHeaderUpdater::grpHdr [private]
The data set header
Definition at line 74 of file DataGroupHeaderUpdater.h.
std::ofstream* affymetrix_calvin_io::DataGroupHeaderUpdater::os [private]
Open output filestream
Definition at line 71 of file DataGroupHeaderUpdater.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DataGroupHeaderUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/DataGroupHeaderUpdater.cpp