Affymetrix Fusion SDK: affymetrix_calvin_io::CHPUniversalEntry Class Reference
affymetrix_calvin_io::CHPUniversalEntry Class Reference
#include <CHPUniversalEntry.h>
Public Member Functions
CHPUniversalEntry ()
CHPUniversalEntry (float background)
~CHPUniversalEntry ()
void Clear ()
CHPUniversalEntry operator= (CHPUniversalEntry zn)
float GetBackground () const
void SetBackground (float p)
Private Attributes
float background
Detailed Description
This class stores a zone's background value
Definition at line 37 of file CHPUniversalEntry.h.
Constructor & Destructor Documentation
CHPUniversalEntry::CHPUniversalEntry ()
Definition at line 26 of file CHPUniversalEntry.cpp.
References Clear().
CHPUniversalEntry::CHPUniversalEntry (float background)
Definition at line 31 of file CHPUniversalEntry.cpp.
References background.
CHPUniversalEntry::~CHPUniversalEntry ()
Definition at line 37 of file CHPUniversalEntry.cpp.
Member Function Documentation
void CHPUniversalEntry::Clear ()
Definition at line 39 of file CHPUniversalEntry.cpp.
References background.
Referenced by CHPUniversalEntry().
float CHPUniversalEntry::GetBackground () const
Definition at line 50 of file CHPUniversalEntry.cpp.
References background.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetUniversalResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteUniversalEntry().
CHPUniversalEntry CHPUniversalEntry::operator= (CHPUniversalEntry zn)
Assignment operator
Parameters:
zn The zone to copy
Returns:
The new zone object
Definition at line 44 of file CHPUniversalEntry.cpp.
References background, and GetBackground().
void CHPUniversalEntry::SetBackground (float p)
Definition at line 55 of file CHPUniversalEntry.cpp.
References background.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
Member Data Documentation
float affymetrix_calvin_io::CHPUniversalEntry::background [private]
Definition at line 42 of file CHPUniversalEntry.h.
Referenced by CHPUniversalEntry(), Clear(), GetBackground(), operator=(), and SetBackground().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CHPUniversalEntry.h
C:/f112/affy/sdk/calvin_files/data/src/CHPUniversalEntry.cpp