Affymetrix Fusion SDK: PgOptions Class Reference
PgOptions Class Reference
#include <PgOptions.h>
Public Types
typedef std::map< std::string,
PgOpt * > optionMap_t
typedef optionMap_t::iterator optionMapIterator_t
Public Member Functions
PgOptions ()
Creates a new PgOptions object.
PgOptions (const PgOptions &options)
Creates a new PgOptions from an existing one.
~PgOptions ()
Destroys a PgOptions object and its PgOpts.
void clear ()
clear all the data & free memory.
void appendOptions (const PgOptions &options)
appendOptions
PgOptions & operator= (const PgOptions &options)
Assignment.
std::string getUsage ()
Get the usage info.
void setUsage (const std::string &usage)
set the usage info for this program
PgOpt * defineOption (const std::string &shortName, const std::string &longName, PgOpt::PgOptType_t type, const std::string &help, const std::string &defaultVal)
define an option to be handled by this option parser.
PgOpt * defOpt (const std::string &shortName, const std::string &longName, PgOpt::PgOptType_t type, const std::string &help, const std::string &defaultVal)
Short form of defineOption.
PgOpt * defOptMult (const std::string &shortName, const std::string &longName, PgOpt::PgOptType_t type, const std::string &help, const std::string &defaultVal)
Short for to define an option with multiple values.
void defineOptionSection (const std::string &sectionName)
Define a new section for options.
PgOpt * addPgOpt (const PgOpt *option)
Copies and adds an PgOpt to the internal state.
PgOpt * addPgOpt_nocopy (PgOpt *option)
Adds an PgOpt to the internal state.
void bind (const std::string &opt_name, PgOpt *opt)
Add the option name and PgOpt to our map of name,value pairs.
PgOpt * findOpt (const std::string &longName)
Finds the option which is bound to this name.
PgOpt * mustFindOpt (const std::string &name)
Same as findOpt, but aborts if not option is not found.
void usage (bool printOpts=true)
Print out a litte ditty about program and its usage.
void usage (std::set< std::string > &hiddenOpts, bool printOpts=true)
int parseArgv (const char *const *const argv, int start=1)
Match the command line arguments from.
void setArgv (const char *const *const argv)
the args to m_arg
void matchOneArg (size_t *arg_idx)
Match the arg found at argv[arg_idx].
void clear (const std::string &name)
Clear the values for an option.
void set (const std::string &name, const std::string &new_value)
Set the value of an option.
void push (const std::string &name, const std::string &value)
Add a value to an option vector.
std::string get (const std::string &opt_name)
Get the value of the option as a string.
bool getBool (const std::string &opt_name)
Get the value of the option as a boolean.
double getDouble (const std::string &opt_name)
Get the value of the option as a double.
int getInt (const std::string &opt_name)
Get the value of the option as a int.
int getArgCount ()
The number of left over args.
std::string getArg (int index)
Get the IDXth arg.
std::vector< std::string > getArgVector ()
Get the args as a vector.
std::string getProgName ()
The name of the program (argv[0])
void resetToDefaults ()
same as clearValues
void clearValues ()
clear all the values from the PgOpts and internal state.
std::string commandLine ()
A space seperated list of the argv we were given.
int argc ()
The size of the argv we were inited with.
std::string argv (int idx)
Get the idxth entry in the argv which was supplied.
void dump ()
Dump the internal state for debugging.
bool isOptDefined (const std::string &name)
std::string getXMLParameterFileName ()
std::string getXMLParameterFileGuid ()
Static Public Member Functions
static void printStringWidth (const std::string &str, int prefix=0, int currentPos=0, int maxWidth=70)
Print a string wrapping at max width from the current position.
Public Attributes
std::string m_usageMsg
< Helpful message explaining the program and purpose.
std::vector< PgOpt * > m_option_vec
Map of indexes for option section starts.
std::map< int, std::string > m_option_section
Map option names to PgOpt.
optionMap_t m_option_map
name of this program.
std::string m_progName
A copy argv we were given.
std::vector< std::string > m_argv
Non option arguments.
std::vector< std::string > m_args
std::string m_strXMLParameterFileName
std::string m_strXMLParameterFileGuid
Protected Member Functions
void setOptionsFromXMLFile (const std::string &strFileName, std::vector< std::string > &vFileNames)
Friends
class PgOptionsSAXHandler
Detailed Description
Definition at line 202 of file PgOptions.h.
Member Typedef Documentation
typedef std::map<std::string, PgOpt *> PgOptions::optionMap_t
Definition at line 209 of file PgOptions.h.
typedef optionMap_t::iterator PgOptions::optionMapIterator_t
Definition at line 210 of file PgOptions.h.
Constructor & Destructor Documentation
PgOptions::PgOptions ()
Creates a new PgOptions object.
Definition at line 356 of file PgOptions.cpp.
PgOptions::PgOptions (const PgOptions & options)
Creates a new PgOptions from an existing one.
Definition at line 413 of file PgOptions.cpp.
References m_args, m_argv, m_option_section, m_option_vec, m_progName, m_strXMLParameterFileGuid, m_strXMLParameterFileName, and m_usageMsg.
PgOptions::~PgOptions ()
Destroys a PgOptions object and its PgOpts.
Definition at line 360 of file PgOptions.cpp.
Member Function Documentation
PgOpt * PgOptions::addPgOpt (const PgOpt * option)
Copies and adds an PgOpt to the internal state.
Parameters:
option option to add
Returns:
pointer to copy.
Definition at line 500 of file PgOptions.cpp.
PgOpt * PgOptions::addPgOpt_nocopy (PgOpt * option)
Adds an PgOpt to the internal state.
Parameters:
option option to add
Returns:
pointer to the passed in option
Definition at line 507 of file PgOptions.cpp.
References PgOpt::checkParseIsOk(), Err::errAbort(), PgOpt::getDefaultValue(), PgOpt::m_longName, and PgOpt::m_shortName.
void PgOptions::appendOptions (const PgOptions & options)
appendOptions
Definition at line 398 of file PgOptions.cpp.
References m_option_section, and m_option_vec.
int PgOptions::argc ()
The size of the argv we were inited with.
Returns:
the size of argv
Definition at line 843 of file PgOptions.cpp.
Referenced by dumpPgf::dumpPgf().
std::string PgOptions::argv (int idx)
Get the idxth entry in the argv which was supplied.
Parameters:
idx the index.
Returns:
the entry.
Definition at line 846 of file PgOptions.cpp.
void PgOptions::bind (const std::string & opt_name, PgOpt * opt)
Add the option name and PgOpt to our map of name,value pairs.
Parameters:
opt_name name to bind. null strings ("") are ignored.
opt option for this name.
Definition at line 492 of file PgOptions.cpp.
void PgOptions::clear (const std::string & name)
Clear the values for an option.
Parameters:
name the name of the option
Definition at line 820 of file PgOptions.cpp.
void PgOptions::clear (void)
clear all the data & free memory.
Definition at line 364 of file PgOptions.cpp.
void PgOptions::clearValues ()
clear all the values from the PgOpts and internal state.
Definition at line 486 of file PgOptions.cpp.
std::string PgOptions::commandLine ()
A space seperated list of the argv we were given.
Returns:
string
Definition at line 470 of file PgOptions.cpp.
Referenced by dumpPgf::dumpPgf().
PgOpt * PgOptions::defineOption (const std::string & shortName, const std::string & longName, PgOpt::PgOptType_t type, const std::string & help, const std::string & defaultVal)
define an option to be handled by this option parser.
Parameters:
shortName one or two letter option name.
longName full length option name.
type the type of option (string,int,bool,double)
help help text.
defaultVal Default value to use if not set.
Returns:
pointer to the PgOpt created.
Remarks:
This calls addPgOpt to add the created option to the option state.
Definition at line 535 of file PgOptions.cpp.
References PgOpt::m_defaultValue, PgOpt::m_help, PgOpt::m_longName, PgOpt::m_shortName, PgOpt::m_type, and PgOpt::m_values.
Referenced by define_dumppgf_options(), define_tsvjoin_options(), and main().
void PgOptions::defineOptionSection (const std::string & sectionName)
Define a new section for options.
Parameters:
sectionName name for the section
Returns:
void
Definition at line 531 of file PgOptions.cpp.
PgOpt * PgOptions::defOpt (const std::string & shortName, const std::string & longName, PgOpt::PgOptType_t type, const std::string & help, const std::string & defaultVal)
Short form of defineOption.
Parameters:
shortName
longName
type
help
defaultVal
Returns:
Definition at line 553 of file PgOptions.cpp.
PgOpt * PgOptions::defOptMult (const std::string & shortName, const std::string & longName, PgOpt::PgOptType_t type, const std::string & help, const std::string & defaultVal)
Short for to define an option with multiple values.
Parameters:
shortName
longName
type
help
defaultVal
Returns:
Definition at line 563 of file PgOptions.cpp.
References PgOpt::allowMutipleValues().
Referenced by define_dumppgf_options().
void PgOptions::dump ()
Dump the internal state for debugging.
Definition at line 668 of file PgOptions.cpp.
PgOpt* PgOptions::findOpt (const std::string & longName) [inline]
Finds the option which is bound to this name.
Parameters:
name
Returns:
pointer to option or NULL
Definition at line 322 of file PgOptions.h.
std::string PgOptions::get (const std::string & opt_name) [inline]
Get the value of the option as a string.
Parameters:
opt_name option name (short or long)
Returns:
the value. Abort if not found.
Definition at line 399 of file PgOptions.h.
References PgOpt::getValue().
Referenced by dumpPgf::dumpPgf(), main(), and tsvJoin::tsvJoin().
std::string PgOptions::getArg (int index)
Get the IDXth arg.
Parameters:
index index of arg to get.
Returns:
string
Definition at line 445 of file PgOptions.cpp.
Referenced by main(), and tsvJoin::tsvJoin().
int PgOptions::getArgCount ()
The number of left over args.
Returns:
int
Definition at line 449 of file PgOptions.cpp.
Referenced by main(), and tsvJoin::tsvJoin().
std::vector< std::string > PgOptions::getArgVector ()
Get the args as a vector.
Returns:
vector of args.
Definition at line 441 of file PgOptions.cpp.
Referenced by main().
bool PgOptions::getBool (const std::string & opt_name)
Get the value of the option as a boolean.
Parameters:
opt_name option name (short or long)
Returns:
the value. Abort if not found.
Definition at line 825 of file PgOptions.cpp.
References PgOpt::getValueBool().
Referenced by dumpPgf::dumpPgf(), main(), and tsvJoin::tsvJoin().
double PgOptions::getDouble (const std::string & opt_name)
Get the value of the option as a double.
Parameters:
opt_name option name (short or long)
Returns:
the value. Abort if not found.
Definition at line 830 of file PgOptions.cpp.
References PgOpt::getValueDouble().
Referenced by main().
int PgOptions::getInt (const std::string & opt_name)
Get the value of the option as a int.
Parameters:
opt_name option name (short or long)
Returns:
the value. Abort if not found.
Definition at line 835 of file PgOptions.cpp.
References PgOpt::getValueInt().
Referenced by main().
std::string PgOptions::getProgName ()
The name of the program (argv[0])
Returns:
string
Definition at line 453 of file PgOptions.cpp.
Referenced by main().
std::string PgOptions::getUsage ()
Get the usage info.
Returns:
string
Definition at line 435 of file PgOptions.cpp.
std::string PgOptions::getXMLParameterFileGuid () [inline]
Definition at line 457 of file PgOptions.h.
Referenced by PgOptionsSAXHandler::startElement().
std::string PgOptions::getXMLParameterFileName () [inline]
Definition at line 456 of file PgOptions.h.
bool PgOptions::isOptDefined (const std::string & name) [inline]
Definition at line 454 of file PgOptions.h.
Referenced by PgOptionsSAXHandler::startElement().
void PgOptions::matchOneArg (size_t * arg_idx)
Match the arg found at argv[arg_idx].
Parameters:
arg_idx arg_idx is updated to point to the next arg to match.
Definition at line 678 of file PgOptions.cpp.
References PgOpt::BOOL_OPT, PgOpt::checkParseIsOk(), Err::errAbort(), PgOpt::isSet(), PgOpt::m_allowMultiple, PgOpt::m_longName, PgOpt::m_type, PgOpt::pushValue(), PgOpt::setValue(), and Convert::toBoolCheck().
PgOpt* PgOptions::mustFindOpt (const std::string & name) [inline]
Same as findOpt, but aborts if not option is not found.
Parameters:
name
Returns:
pointer to option
Definition at line 333 of file PgOptions.h.
References Err::errAbort().
Referenced by dumpPgf::dumpPgf(), PgOptionsSAXHandler::endDocument(), main(), and PgOptionsSAXHandler::startElement().
PgOptions & PgOptions::operator= (const PgOptions & options)
Assignment.
Definition at line 383 of file PgOptions.cpp.
References m_args, m_argv, m_progName, and m_usageMsg.
int PgOptions::parseArgv (const char *const *const argv, int start = 1)
Match the command line arguments from.
Parameters:
argv Arguments supplied to program. argv[0] is the program name.
start The position to start parsing at (default 1)
Returns:
the last position in argv parsed (will stop at "--")
Definition at line 645 of file PgOptions.cpp.
Referenced by dumpPgf::dumpPgf(), main(), and tsvJoin::tsvJoin().
void PgOptions::printStringWidth (const std::string & str, int prefix = 0, int currentPos = 0, int maxWidth = 70) [static]
Print a string wrapping at max width from the current position.
Parameters:
str - The cstring to be printed.
prefix - How many spaces to put on begining of newline.
maxWidth - Where to wrap text at.
currentPos - What position in the line is cursor currently at.
Definition at line 574 of file PgOptions.cpp.
References Util::printStringWidth().
void PgOptions::push (const std::string & name, const std::string & value) [inline]
Add a value to an option vector.
Parameters:
name the name of the option
value the value to push
Definition at line 393 of file PgOptions.h.
Referenced by PgOptionsSAXHandler::endDocument(), and PgOptionsSAXHandler::startElement().
void PgOptions::resetToDefaults ()
same as clearValues
Definition at line 660 of file PgOptions.cpp.
void PgOptions::set (const std::string & name, const std::string & new_value) [inline]
Set the value of an option.
Parameters:
name the name of the option
new_value the value of the option
Definition at line 379 of file PgOptions.h.
References Err::errAbort().
Referenced by PgOptionsSAXHandler::endDocument(), and PgOptionsSAXHandler::startElement().
void PgOptions::setArgv (const char *const *const argv)
the args to m_arg
Parameters:
argv Arguments to copy
Definition at line 458 of file PgOptions.cpp.
void PgOptions::setOptionsFromXMLFile (const std::string & strFileNameIn, std::vector< std::string > & vFileNames) [protected]
Load parameters from an XML file.
Parameters:
strFileName - The name of the XML file to load parameters from.
Definition at line 855 of file PgOptions.cpp.
References Fs::basename(), Err::errAbort(), Verbose::out(), and PgOptionsSAXHandler::toString().
Referenced by PgOptionsSAXHandler::startElement().
void PgOptions::setUsage (const std::string & usage)
set the usage info for this program
Parameters:
usage
Definition at line 431 of file PgOptions.cpp.
Referenced by define_dumppgf_options(), define_tsvjoin_options(), and main().
void PgOptions::usage (bool printOpts = true) [inline]
Print out a litte ditty about program and its usage.
Parameters:
printOpts - Print out options and help for each one?
Definition at line 351 of file PgOptions.h.
References usage().
Referenced by dumpPgf::dumpPgf(), main(), and tsvJoin::tsvJoin().
void PgOptions::usage (std::set< std::string > & hiddenOpts, bool printOpts = true)
Print out a litte ditty about program and its usage.
Parameters:
hiddenOpts - Set containing the long name of options to hide.
printOpts - Print out options and help for each one?
Definition at line 578 of file PgOptions.cpp.
References PgOpt::m_defaultValue, PgOpt::m_help, PgOpt::m_longName, and PgOpt::m_shortName.
Friends And Related Function Documentation
friend class PgOptionsSAXHandler [friend]
Definition at line 205 of file PgOptions.h.
Member Data Documentation
std::vector<std::string> PgOptions::m_args
Definition at line 228 of file PgOptions.h.
Referenced by operator=(), and PgOptions().
std::vector<std::string> PgOptions::m_argv
Non option arguments.
Definition at line 227 of file PgOptions.h.
Referenced by operator=(), and PgOptions().
optionMap_t PgOptions::m_option_map
name of this program.
Definition at line 223 of file PgOptions.h.
std::map<int,std::string> PgOptions::m_option_section
Map option names to PgOpt.
Definition at line 220 of file PgOptions.h.
Referenced by appendOptions(), and PgOptions().
std::vector<PgOpt*> PgOptions::m_option_vec
Map of indexes for option section starts.
Definition at line 218 of file PgOptions.h.
Referenced by appendOptions(), PgOptions(), and Options::setOptions().
std::string PgOptions::m_progName
A copy argv we were given.
Definition at line 225 of file PgOptions.h.
Referenced by operator=(), and PgOptions().
std::string PgOptions::m_strXMLParameterFileGuid
Definition at line 234 of file PgOptions.h.
Referenced by PgOptions(), and PgOptionsSAXHandler::startElement().
std::string PgOptions::m_strXMLParameterFileName
Definition at line 231 of file PgOptions.h.
Referenced by PgOptions().
std::string PgOptions::m_usageMsg
< Helpful message explaining the program and purpose.
Vec of all the options defined.
Definition at line 216 of file PgOptions.h.
Referenced by operator=(), and PgOptions().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/PgOptions.h
C:/f112/affy/sdk/util/PgOptions.cpp