Affymetrix Fusion SDK: affymetrix_calvin_io::CDFFileWriter Class Reference
affymetrix_calvin_io::CDFFileWriter Class Reference
#include <CDFFileWriter.h>
Public Member Functions
CDFFileWriter (CDFData &p)
~CDFFileWriter ()
CDFProbeSetWriter * CreateProbeSetWriter (const std::wstring &xdaBlockName, u_int8_t unitType, u_int8_t direction, u_int32_t atoms, u_int32_t cells, u_int32_t probeSetNumber, u_int8_t cellsPerAtom)
void OpenDataGroup (const std::wstring &probeSetName, int dataSetCnt)
void CloseDataGroup ()
Private Member Functions
void WriteHeaders ()
void WriteContentsEntry (const std::wstring &probeSetName)
Private Attributes
GenericFileWriter * writer
DataGroupWriter * dataGroupWriter
DataSetWriter * contentsWriter
DataSetHeader probeSetPlaneHdr
int32_t contentsPos
int32_t currentCubePos
Detailed Description
Definition at line 36 of file CDFFileWriter.h.
Constructor & Destructor Documentation
CDFFileWriter::CDFFileWriter (CDFData & p)
Definition at line 26 of file CDFFileWriter.cpp.
References contentsPos, dataGroupWriter, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::CDFData::GetFileHeader(), affymetrix_calvin_io::CDFData::GetProbeSetCnt(), MAX_CDF_PROBE_SET_NAME_LENGTH, affymetrix_calvin_io::GenericFileWriter::SeekFromCurrentPos(), affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos(), WriteHeaders(), and writer.
CDFFileWriter::~CDFFileWriter ()
Definition at line 42 of file CDFFileWriter.cpp.
References dataGroupWriter, and writer.
Member Function Documentation
void CDFFileWriter::CloseDataGroup ()
Closes data group after writing
Definition at line 127 of file CDFFileWriter.cpp.
References affymetrix_calvin_io::DataGroupWriter::Close(), and dataGroupWriter.
CDFProbeSetWriter * CDFFileWriter::CreateProbeSetWriter (const std::wstring & xdaBlockName, u_int8_t unitType, u_int8_t direction, u_int32_t atoms, u_int32_t cells, u_int32_t probeSetNumber, u_int8_t cellsPerAtom)
Definition at line 58 of file CDFFileWriter.cpp.
References affymetrix_calvin_io::DataSetHeader::AddByteColumn(), affymetrix_calvin_io::DataSetHeader::AddNameValParam(), affymetrix_calvin_io::DataSetHeader::AddUIntColumn(), affymetrix_calvin_io::DataSetHeader::AddUShortColumn(), CDF_ATOMS, CDF_CELLS, CDF_CELLS_PER_ATOM, CDF_DIRECTION, CDF_PROBE_SET_NUMBER, CDF_UNIT_TYPE, affymetrix_calvin_io::DataSetHeader::Clear(), affymetrix_calvin_io::DataGroupWriter::CreateDataSetWriter(), dataGroupWriter, probeSetPlaneHdr, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CDFFileWriter::OpenDataGroup (const std::wstring & probeSetName, int dataSetCnt)
Prepares a data group for writing
Parameters:
probeSetName Probe set name
dataSetCnt number of data sets to be written
Definition at line 114 of file CDFFileWriter.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::GenericFileWriter::CreateDataGroupWriter(), dataGroupWriter, WriteContentsEntry(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), and writer.
void CDFFileWriter::WriteContentsEntry (const std::wstring & probeSetName) [private]
Definition at line 134 of file CDFFileWriter.cpp.
References contentsPos, contentsWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), MAX_CDF_PROBE_SET_NAME_LENGTH, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::DataSetWriter::Write(), and writer.
Referenced by OpenDataGroup().
void CDFFileWriter::WriteHeaders () [private]
Definition at line 48 of file CDFFileWriter.cpp.
References contentsPos, contentsWriter, dataGroupWriter, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), and writer.
Referenced by CDFFileWriter().
Member Data Documentation
int32_t affymetrix_calvin_io::CDFFileWriter::contentsPos [private]
Definition at line 45 of file CDFFileWriter.h.
Referenced by CDFFileWriter(), WriteContentsEntry(), and WriteHeaders().
DataSetWriter* affymetrix_calvin_io::CDFFileWriter::contentsWriter [private]
Definition at line 43 of file CDFFileWriter.h.
Referenced by WriteContentsEntry(), and WriteHeaders().
int32_t affymetrix_calvin_io::CDFFileWriter::currentCubePos [private]
Definition at line 46 of file CDFFileWriter.h.
DataGroupWriter* affymetrix_calvin_io::CDFFileWriter::dataGroupWriter [private]
Definition at line 42 of file CDFFileWriter.h.
Referenced by CDFFileWriter(), CloseDataGroup(), CreateProbeSetWriter(), OpenDataGroup(), WriteHeaders(), and ~CDFFileWriter().
DataSetHeader affymetrix_calvin_io::CDFFileWriter::probeSetPlaneHdr [private]
Definition at line 44 of file CDFFileWriter.h.
Referenced by CreateProbeSetWriter().
GenericFileWriter* affymetrix_calvin_io::CDFFileWriter::writer [private]
Definition at line 41 of file CDFFileWriter.h.
Referenced by CDFFileWriter(), OpenDataGroup(), WriteContentsEntry(), WriteHeaders(), and ~CDFFileWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CDFFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CDFFileWriter.cpp