Affymetrix Fusion SDK: affymetrix_calvin_utilities::FileUtils Class Reference
affymetrix_calvin_utilities::FileUtils Class Reference
#include <FileUtils.h>
Static Public Member Functions
static bool Exists (const char *fileName)
static bool LockFile (const char *fileName)
static bool UnlockFile (const char *fileName)
static std::list< std::string > ListFiles (const char *pathName, const char *ext)
static bool RemoveFile (const char *fileName)
static void RemovePath (const char *path)
Detailed Description
This class provides utility functions for files.
Definition at line 37 of file FileUtils.h.
Member Function Documentation
bool FileUtils::Exists (const char * fileName) [static]
Checks for the existance of a file.
Parameters:
fileName The name of the file to test for existance.
Returns:
True if the file exists.
Todo:
this is an ugly hack to prevent APT dependencies. The following is a copy from Util::fileReadable()
Definition at line 200 of file FileUtils.cpp.
References Fs::aptOpen(), convertPathNameLocal(), and POSIX_CLOSE.
Referenced by LockFile(), and UnlockFile().
list< string > FileUtils::ListFiles (const char * pathName, const char * ext) [static]
Retrieves the list of files in a path that match the extension.
Parameters:
pathName The path to search.
ext The file extension.
Returns:
The list of files (full path) found in the directory.
Definition at line 258 of file FileUtils.cpp.
References Fs::fileExists().
bool FileUtils::LockFile (const char * fileName) [static]
Locks a file for exclusive use. This is a soft locking mechanism. The actual file is not locked, instead it uses a "LCK" file to determine the lock status.
Parameters:
fileName The name of the file to lock.
Returns:
True if the file was successfully locked.
Definition at line 230 of file FileUtils.cpp.
References Fs::aptOpen(), Exists(), and LockFileExtension.
bool FileUtils::RemoveFile (const char * fileName) [static]
Deletes a file.
Parameters:
fileName The name of the file to delete.
Returns:
True if the file was deleted.
Definition at line 220 of file FileUtils.cpp.
Referenced by RemovePath().
void FileUtils::RemovePath (const char * path) [static]
Deletes a file.
Parameters:
path The name of the path to delete.
Returns:
True if the path was deleted.
Definition at line 331 of file FileUtils.cpp.
References Fs::fileExists(), and RemoveFile().
bool FileUtils::UnlockFile (const char * fileName) [static]
Unlocks a file for exclusive use. This is a soft locking mechanism. The actual file is not locked, instead it uses a "LCK" file to determine the lock status.
Parameters:
fileName The name of the file to unlock.
Returns:
True if the file was successfully unlocked.
Definition at line 250 of file FileUtils.cpp.
References Exists(), and LockFileExtension.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/utils/src/FileUtils.h
C:/f112/affy/sdk/calvin_files/utils/src/FileUtils.cpp