Affymetrix Fusion SDK: dumpPgf Class Reference
dumpPgf Class Reference
#include <DumpPgf.h>
Public Member Functions
dumpPgf (const char *argv[], const std::string &version)
Constructor.
~dumpPgf ()
void run ()
Public Attributes
PgOptions m_Opts
Command line options.
Private Types
typedef void(dumpPgf::* PMemProbeCoord_t)(const int probeId)
Private Member Functions
void clear ()
void readIdFiles (void)
Read optional probeset or probe id files.
void beginOutput (void)
void openInputFiles (void)
Open input pgf, clf files.
void writeOutputHeader (void)
void writeMatches (void)
void dumpProbesetData (void)
void dumpProbeData (void)
void splitTypes (const std::string &inputString, std::vector< std::string > &inputTypes)
void getCoordsBySequentialClf (const int probeId)
Calculate probe coordinates using SequentialClfFile.
void getCoordsByIndex (const int probeId)
Calculate probe coordinates using index.
Private Attributes
const std::string & m_Version
std::string m_CommandLine
Command line as a string.
std::string m_PgfFileName
Pgf file name.
std::string m_ClfFileName
Clf file name.
std::vector< std::string > m_ProbesetTypes
Probeset type(s).
std::vector< std::string > m_ProbesetIdFileNames
Probeset id file name(s).
std::vector< std::string > m_ProbeIdFileNames
Probe id file name(s).
bool m_DumpProbesetsOnly
Should probeset level information only be dumped?
bool m_DumpUnion
Should the union of the types requested be dumped?
affx::TsvFile m_PgfTsv
Pgf file tsv object.
affx::TsvFile m_ClfTsv
Clf file tsv object.
SequentialClfFile m_SequentialClf
Sequential clf file object.
std::vector< std::string > m_OutputColNames
Column names for output.
unsigned int m_ProbesetDataCount
Number of probeset (level 0) data columns.
unsigned int m_AtomDataCount
Number of atom (level 1) data columns.
unsigned int m_ProbeDataCount
Number of probe (level 2) data columns.
std::vector< std::string > m_ProbesetData
Probeset (level 0) data, excluding probeset_id.
std::vector< std::string > m_AtomProbeData
Atom and probe (levels 1 and 2) data, excluding probe_id.
std::string m_ExecGuid
Execution guid.
std::vector< int > m_ProbesetIds
Probeset ids requested.
std::vector< int > m_ProbeIds
Probe ids requested.
int m_PgfProbesetId
Pgf file probeset_id.
int m_PgfProbeId
Pgf file probe_id.
unsigned int m_ProbesetTypeCol
Column containing probeset type.
int m_ClfProbeId
Clf file probe_id.
int m_ClfX
Clf file x value.
int m_ClfY
Clf file y value.
std::string m_Outfile
Output file name.
std::ostream * m_Out
Output stream.
std::ofstream m_FileOut
File output stream.
PMemProbeCoord_t m_GetProbeCoordinates
Detailed Description
Definition at line 42 of file DumpPgf.h.
Member Typedef Documentation
typedef void(dumpPgf::* dumpPgf::PMemProbeCoord_t)(const int probeId) [private]
Definition at line 184 of file DumpPgf.h.
Constructor & Destructor Documentation
dumpPgf::dumpPgf (const char * argv[], const std::string & version)
Constructor.
Constructor.
Parameters:
argc Number of command line arguments.
argv Command line arguments.
version Version string.
argc Number of command line arguments.
argv Command line arguments.
version Version string.
Errors: throw exception to display help messages, if unsupported option choices were made.
Definition at line 95 of file DumpPgf.cpp.
References PgOptions::argc(), PgOptions::commandLine(), define_dumppgf_options(), Err::errAbort(), PgOptions::get(), PgOptions::getBool(), m_ClfFileName, m_CommandLine, m_DumpProbesetsOnly, m_DumpUnion, m_FileOut, m_Opts, m_Out, m_Outfile, m_PgfFileName, m_ProbeIdFileNames, m_ProbesetIdFileNames, m_ProbesetTypes, PgOptions::mustFindOpt(), Fs::mustOpenToWrite(), PgOptions::parseArgv(), PgOpt::push_user_values_into(), Err::setThrowStatus(), and PgOptions::usage().
dumpPgf::~dumpPgf () [inline]
Destructor.
Definition at line 56 of file DumpPgf.h.
References clear().
Member Function Documentation
void dumpPgf::beginOutput (void) [private]
Begin output.
Definition at line 247 of file DumpPgf.cpp.
References affxutil::Guid::GenerateNewGuid(), m_CommandLine, m_ExecGuid, m_Version, and Verbose::out().
Referenced by run().
void dumpPgf::clear () [inline, private]
Clear data.
Definition at line 69 of file DumpPgf.h.
Referenced by ~dumpPgf().
void dumpPgf::dumpProbeData (void) [private]
Dump information for a given probe id.
Definition at line 585 of file DumpPgf.cpp.
References m_AtomDataCount, m_AtomProbeData, m_ClfFileName, m_ClfX, m_ClfY, m_GetProbeCoordinates, m_Out, m_PgfProbeId, m_PgfProbesetId, m_ProbeDataCount, m_ProbesetData, and m_ProbesetDataCount.
Referenced by dumpProbesetData(), and writeMatches().
void dumpPgf::dumpProbesetData (void) [private]
Dump information for a given probeset id.
Definition at line 565 of file DumpPgf.cpp.
References dumpProbeData(), m_DumpProbesetsOnly, m_Out, m_PgfProbesetId, m_PgfTsv, m_ProbesetData, m_ProbesetDataCount, affx::TsvFile::nextLevel(), and affx::TSV_OK.
Referenced by writeMatches().
void dumpPgf::getCoordsByIndex (const int probeId) [private]
Calculate probe coordinates using index.
Calculate probe coordinates using index.
Parameters:
probeId Probe id.
Definition at line 626 of file DumpPgf.cpp.
References Err::errAbort(), affx::TsvFile::findBegin(), affx::TsvFile::findNext(), affx::TsvFile::findResultsCount(), m_ClfFileName, m_ClfTsv, m_ClfX, m_ClfY, m_PgfProbeId, ToStr(), affx::TSV_OK, and affx::TSV_OP_EQ.
Referenced by openInputFiles().
void dumpPgf::getCoordsBySequentialClf (const int probeId) [private]
Calculate probe coordinates using SequentialClfFile.
Calculate probe coordinates using SequentialClfFile.
Parameters:
probeId Probe id.
Definition at line 618 of file DumpPgf.cpp.
References SequentialClfFile::getProbeCoordinates(), m_ClfX, m_ClfY, and m_SequentialClf.
Referenced by openInputFiles().
void dumpPgf::openInputFiles (void) [private]
Open input pgf, clf files.
Open input files.
Errors: abort if a file could not be opened or if a required column name was not found.
Definition at line 261 of file DumpPgf.cpp.
References affx::TsvFile::bind(), affx::TsvFile::cidx2cname(), affx::TsvFile::defineIndex(), Err::errAbort(), affx::TsvFile::getColumnCount(), getCoordsByIndex(), getCoordsBySequentialClf(), SequentialClfFile::isSequential(), m_AtomDataCount, m_AtomProbeData, m_ClfFileName, m_ClfProbeId, m_ClfTsv, m_ClfX, m_ClfY, m_DumpProbesetsOnly, m_GetProbeCoordinates, m_OutputColNames, m_PgfFileName, m_PgfProbeId, m_PgfProbesetId, m_PgfTsv, m_ProbeDataCount, m_ProbeIdFileNames, m_ProbesetData, m_ProbesetDataCount, m_ProbesetIdFileNames, m_ProbesetTypeCol, m_ProbesetTypes, m_SequentialClf, affx::TsvFile::open(), Verbose::out(), affx::TSV_BIND_REQUIRED, affx::TSV_INDEX_INT, and affx::TSV_OK.
Referenced by run().
void dumpPgf::readIdFiles (void) [private]
Read optional probeset or probe id files.
Read optional transcript cluster id and probeset id files.
Definition at line 206 of file DumpPgf.cpp.
References affx::TsvFile::bind(), affx::TsvFile::close(), Err::errAbort(), m_ProbeIdFileNames, m_ProbeIds, m_ProbesetIdFileNames, m_ProbesetIds, affx::TsvFile::nextLevel(), affx::TsvFile::open(), Verbose::out(), ToStr(), affx::TSV_BIND_REQUIRED, and affx::TSV_OK.
Referenced by run().
void dumpPgf::run ()
Read, process data, write output.
Errors: abort if unable to read any input file.
Definition at line 185 of file DumpPgf.cpp.
References beginOutput(), openInputFiles(), readIdFiles(), writeMatches(), and writeOutputHeader().
Referenced by main().
void dumpPgf::splitTypes (const std::string & inputString, std::vector< std::string > & inputTypes) [private]
Split type by '->'.
Definition at line 537 of file DumpPgf.cpp.
Referenced by writeMatches().
void dumpPgf::writeMatches (void) [private]
Write lines matching selection criteria.
Definition at line 405 of file DumpPgf.cpp.
References dumpProbeData(), dumpProbesetData(), Err::errAbort(), affx::TsvFile::findBegin(), affx::TsvFile::findNext(), affx::TsvFile::findResultsCount(), m_ClfFileName, m_DumpUnion, m_GetProbeCoordinates, m_PgfFileName, m_PgfTsv, m_ProbeIdFileNames, m_ProbeIds, m_ProbesetData, m_ProbesetIdFileNames, m_ProbesetIds, m_ProbesetTypeCol, m_ProbesetTypes, affx::TsvFile::nextLevel(), Verbose::out(), splitTypes(), ToStr(), affx::TSV_OK, and affx::TSV_OP_EQ.
Referenced by run().
void dumpPgf::writeOutputHeader (void) [private]
Write output file header.
Definition at line 374 of file DumpPgf.cpp.
References affxutil::Guid::GenerateNewGuid(), Util::getTimeStamp(), affx::TsvFile::headersBegin(), affx::TsvFile::headersNext(), m_CommandLine, m_ExecGuid, m_Out, m_OutputColNames, m_PgfTsv, m_Version, and affx::TSV_OK.
Referenced by run().
Member Data Documentation
unsigned int dumpPgf::m_AtomDataCount [private]
Number of atom (level 1) data columns.
Definition at line 152 of file DumpPgf.h.
Referenced by dumpProbeData(), and openInputFiles().
std::vector<std::string> dumpPgf::m_AtomProbeData [private]
Atom and probe (levels 1 and 2) data, excluding probe_id.
Definition at line 158 of file DumpPgf.h.
Referenced by dumpProbeData(), and openInputFiles().
std::string dumpPgf::m_ClfFileName [private]
Clf file name.
Definition at line 130 of file DumpPgf.h.
Referenced by dumpPgf(), dumpProbeData(), getCoordsByIndex(), openInputFiles(), and writeMatches().
int dumpPgf::m_ClfProbeId [private]
Clf file probe_id.
Definition at line 172 of file DumpPgf.h.
Referenced by openInputFiles().
affx::TsvFile dumpPgf::m_ClfTsv [private]
Clf file tsv object.
Definition at line 144 of file DumpPgf.h.
Referenced by getCoordsByIndex(), and openInputFiles().
int dumpPgf::m_ClfX [private]
Clf file x value.
Definition at line 174 of file DumpPgf.h.
Referenced by dumpProbeData(), getCoordsByIndex(), getCoordsBySequentialClf(), and openInputFiles().
int dumpPgf::m_ClfY [private]
Clf file y value.
Definition at line 176 of file DumpPgf.h.
Referenced by dumpProbeData(), getCoordsByIndex(), getCoordsBySequentialClf(), and openInputFiles().
std::string dumpPgf::m_CommandLine [private]
Command line as a string.
Definition at line 126 of file DumpPgf.h.
Referenced by beginOutput(), dumpPgf(), and writeOutputHeader().
bool dumpPgf::m_DumpProbesetsOnly [private]
Should probeset level information only be dumped?
Definition at line 138 of file DumpPgf.h.
Referenced by dumpPgf(), dumpProbesetData(), and openInputFiles().
bool dumpPgf::m_DumpUnion [private]
Should the union of the types requested be dumped?
Definition at line 140 of file DumpPgf.h.
Referenced by dumpPgf(), and writeMatches().
std::string dumpPgf::m_ExecGuid [private]
Execution guid.
Definition at line 160 of file DumpPgf.h.
Referenced by beginOutput(), and writeOutputHeader().
std::ofstream dumpPgf::m_FileOut [private]
File output stream.
Definition at line 182 of file DumpPgf.h.
Referenced by dumpPgf().
PMemProbeCoord_t dumpPgf::m_GetProbeCoordinates [private]
Definition at line 186 of file DumpPgf.h.
Referenced by dumpProbeData(), openInputFiles(), and writeMatches().
PgOptions dumpPgf::m_Opts
Command line options.
Definition at line 123 of file DumpPgf.h.
Referenced by dumpPgf().
std::ostream* dumpPgf::m_Out [private]
Output stream.
Definition at line 180 of file DumpPgf.h.
Referenced by dumpPgf(), dumpProbeData(), dumpProbesetData(), and writeOutputHeader().
std::string dumpPgf::m_Outfile [private]
Output file name.
Definition at line 178 of file DumpPgf.h.
Referenced by dumpPgf().
std::vector<std::string> dumpPgf::m_OutputColNames [private]
Column names for output.
Definition at line 148 of file DumpPgf.h.
Referenced by openInputFiles(), and writeOutputHeader().
std::string dumpPgf::m_PgfFileName [private]
Pgf file name.
Definition at line 128 of file DumpPgf.h.
Referenced by dumpPgf(), openInputFiles(), and writeMatches().
int dumpPgf::m_PgfProbeId [private]
Pgf file probe_id.
Definition at line 168 of file DumpPgf.h.
Referenced by dumpProbeData(), getCoordsByIndex(), and openInputFiles().
int dumpPgf::m_PgfProbesetId [private]
Pgf file probeset_id.
Definition at line 166 of file DumpPgf.h.
Referenced by dumpProbeData(), dumpProbesetData(), and openInputFiles().
affx::TsvFile dumpPgf::m_PgfTsv [private]
Pgf file tsv object.
Definition at line 142 of file DumpPgf.h.
Referenced by dumpProbesetData(), openInputFiles(), writeMatches(), and writeOutputHeader().
unsigned int dumpPgf::m_ProbeDataCount [private]
Number of probe (level 2) data columns.
Definition at line 154 of file DumpPgf.h.
Referenced by dumpProbeData(), and openInputFiles().
std::vector<std::string> dumpPgf::m_ProbeIdFileNames [private]
Probe id file name(s).
Definition at line 136 of file DumpPgf.h.
Referenced by dumpPgf(), openInputFiles(), readIdFiles(), and writeMatches().
std::vector<int> dumpPgf::m_ProbeIds [private]
Probe ids requested.
Definition at line 164 of file DumpPgf.h.
Referenced by readIdFiles(), and writeMatches().
std::vector<std::string> dumpPgf::m_ProbesetData [private]
Probeset (level 0) data, excluding probeset_id.
Definition at line 156 of file DumpPgf.h.
Referenced by dumpProbeData(), dumpProbesetData(), openInputFiles(), and writeMatches().
unsigned int dumpPgf::m_ProbesetDataCount [private]
Number of probeset (level 0) data columns.
Definition at line 150 of file DumpPgf.h.
Referenced by dumpProbeData(), dumpProbesetData(), and openInputFiles().
std::vector<std::string> dumpPgf::m_ProbesetIdFileNames [private]
Probeset id file name(s).
Definition at line 134 of file DumpPgf.h.
Referenced by dumpPgf(), openInputFiles(), readIdFiles(), and writeMatches().
std::vector<int> dumpPgf::m_ProbesetIds [private]
Probeset ids requested.
Definition at line 162 of file DumpPgf.h.
Referenced by readIdFiles(), and writeMatches().
unsigned int dumpPgf::m_ProbesetTypeCol [private]
Column containing probeset type.
Definition at line 170 of file DumpPgf.h.
Referenced by openInputFiles(), and writeMatches().
std::vector<std::string> dumpPgf::m_ProbesetTypes [private]
Probeset type(s).
Definition at line 132 of file DumpPgf.h.
Referenced by dumpPgf(), openInputFiles(), and writeMatches().
SequentialClfFile dumpPgf::m_SequentialClf [private]
Sequential clf file object.
Definition at line 146 of file DumpPgf.h.
Referenced by getCoordsBySequentialClf(), and openInputFiles().
const std::string& dumpPgf::m_Version [private]
private data Version string.
Definition at line 120 of file DumpPgf.h.
Referenced by beginOutput(), and writeOutputHeader().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/DumpPgf.h
C:/f112/affy/sdk/file/TsvFile/DumpPgf.cpp