Affymetrix Fusion SDK: affymetrix_calvin_io::CalvinCHPFileUpdater Class Reference
affymetrix_calvin_io::CalvinCHPFileUpdater Class Reference
#include <CalvinCHPFileUpdater.h>
Public Member Functions
CalvinCHPFileUpdater ()
~CalvinCHPFileUpdater ()
void Initialize (const char *file)
void OpenCHPFile (const char *fileName)
void UpdateExpressionQuantification (int row, float quantification)
void UpdateExpressionQuantificationBuffer (int row_start, std::vector< float > &expressionSignalBuffer)
void UpdateGenotypeEntry (int row, u_int8_t call, float confidence, float RAS1, float RAS2, float aaCall, float abCall, float bbCall, float noCall)
void UpdateGenotypeEntryBuffer (int row_start, const std::vector< CHPFileBufferWriter::GenotypeBufferEntry > &genotypeEntryBuffer)
void UpdateMultiDataGenotypeEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry)
void UpdateMultiDataGenotypeEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::ProbeSetMultiDataGenotypeData > &genotypeEntryBuffer)
void UpdateMultiDataGenotypeEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &genotypeEntryBuffer)
void UpdateMultiDataCopyNumberEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &copyNumberEntryBuffer)
void UpdateMultiDataCytoRegionEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &cytoEntryBuffer)
void UpdateMultiDataCopyNumberVariationRegionEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &cnVariationEntryBuffer)
void UpdateMultiDataExpressionEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataExpressionData &entry)
void UpdateMultiDataExpressionEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::ProbeSetMultiDataExpressionData > &expressionEntryBuffer)
void UpdateMultiDataExpressionEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &expressionEntryBuffer)
void UpdateDmetBiAllelicEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetBiAllelicData &entry)
void UpdateDmetBiAllelicEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::DmetBiAllelicData > &entryBuffer)
void UpdateDmetBiAllelicEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void UpdateDmetCopyNumberEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetCopyNumberData &entry)
void UpdateDmetCopyNumberEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::DmetCopyNumberData > &entryBuffer)
void UpdateDmetCopyNumberEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void UpdateDmetMultiAllelicEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetMultiAllelicData &entry)
void UpdateDmetMultiAllelicEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::DmetMultiAllelicData > &entryBuffer)
void UpdateDmetMultiAllelicEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void UpdateChromosomeSegmentEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void UpdateChromosomeSummaryEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void UpdateFamilialSegmentOverlapEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void UpdateFamilialSampleEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void UpdateMultiDataAllelePeaksEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &allelePeakEntryBuffer)
void UpdateMultiDataMarkerABSignalsEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void UpdateMultiDataCytoGenotypeEntryBuffer (MultiDataType dataType, int rowStart, int bufferEntrySize, const std::vector< char * > &entryBuffer)
void CloseCHPFile ()
Private Member Functions
void UpdateMetrics (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > &metrics)
Private Attributes
std::ofstream * m_CHPFile
std::map< MultiDataType, int > dataSetIndexMap
std::map< MultiDataType, int > dataGroupIndexMap
Detailed Description
Provides interfaces to update data in a "Calvin" binary "signal" data file. This class assumes that the file has been completely written and that only existing data groups/sets/rows/cols are being modified.
Definition at line 42 of file CalvinCHPFileUpdater.h.
Constructor & Destructor Documentation
CalvinCHPFileUpdater::CalvinCHPFileUpdater ()
Constructor
Definition at line 50 of file CalvinCHPFileUpdater.cpp.
References m_CHPFile.
CalvinCHPFileUpdater::~CalvinCHPFileUpdater ()
Destructor
Definition at line 58 of file CalvinCHPFileUpdater.cpp.
References CloseCHPFile().
Member Function Documentation
void CalvinCHPFileUpdater::CloseCHPFile ()
Close CHP signal file.
Definition at line 1030 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, and m_CHPFile.
Referenced by affymetrix_calvin_io::CHPQuantificationFileBufferWriter::FlushBuffer(), affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::FlushBuffer(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer(), affymetrix_calvin_io::CHPFileBufferWriter::FlushBuffer(), OpenCHPFile(), and ~CalvinCHPFileUpdater().
void CalvinCHPFileUpdater::Initialize (const char * file) [virtual]
Initialize the class given a "calvin" data file.
Parameters:
file The name of the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Reimplemented from affymetrix_calvin_io::DataSetUpdater.
Definition at line 63 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, affymetrix_calvin_io::DataSetUpdater::dataSetNames, affymetrix_calvin_io::MultiDataDataSetNames, and affymetrix_calvin_io::MultiDataDataTypes.
Referenced by OpenCHPFile().
void CalvinCHPFileUpdater::OpenCHPFile (const char * fileName)
Open CHP signal file and initialize it.
Parameters:
fileName The name of the CHP signal file.
Definition at line 85 of file CalvinCHPFileUpdater.cpp.
References CloseCHPFile(), Err::errAbort(), Initialize(), m_CHPFile, and ToStr().
Referenced by affymetrix_calvin_io::CHPQuantificationFileBufferWriter::FlushBuffer(), affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::FlushBuffer(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer(), and affymetrix_calvin_io::CHPFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateChromosomeSegmentEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update the segment entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
entryBuffer The vector contain all buffered entries to be updated.
Definition at line 789 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateChromosomeSummaryEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update the summary entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
entryBuffer The vector contain all buffered entries to be updated.
Definition at line 816 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateDmetBiAllelicEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetBiAllelicData & entry)
Seek to appropriate file position and update genotype entry
Parameters:
dataType The data type.
row The row index.
call CHP call representation.
confidence CHP confidence value.
Definition at line 258 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_data::_DmetBiAllelicData::call, affymetrix_calvin_data::_DmetBiAllelicData::confidence, affymetrix_calvin_data::_DmetBiAllelicData::contextA, affymetrix_calvin_data::_DmetBiAllelicData::contextB, dataGroupIndexMap, dataSetIndexMap, ENTRY_COLUMN, affymetrix_calvin_data::_DmetBiAllelicData::force, m_CHPFile, affymetrix_calvin_data::_DmetBiAllelicData::metrics, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), affymetrix_calvin_data::_DmetBiAllelicData::signalA, affymetrix_calvin_data::_DmetBiAllelicData::signalB, UpdateMetrics(), affymetrix_calvin_io::FileOutput::WriteFloat(), and WriteUInt8().
void CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::DmetBiAllelicData > & entryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 273 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_io::DataSetUpdater::colsizes, CopyMetricToBuffer(), dataGroupIndexMap, dataSetIndexMap, GetMetricBufferSize(), m_CHPFile, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 330 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
void CalvinCHPFileUpdater::UpdateDmetCopyNumberEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetCopyNumberData & entry)
Seek to appropriate file position and update genotype entry
Parameters:
dataType The data type.
row The row index.
call CHP call representation.
confidence CHP confidence value.
Definition at line 358 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_data::_DmetCopyNumberData::call, affymetrix_calvin_data::_DmetCopyNumberData::confidence, dataGroupIndexMap, dataSetIndexMap, ENTRY_COLUMN, affymetrix_calvin_data::_DmetCopyNumberData::estimate, affymetrix_calvin_data::_DmetCopyNumberData::force, affymetrix_calvin_data::_DmetCopyNumberData::lower, m_CHPFile, affymetrix_calvin_data::_DmetCopyNumberData::metrics, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), UpdateMetrics(), affymetrix_calvin_data::_DmetCopyNumberData::upper, affymetrix_calvin_io::FileOutput::WriteFloat(), and affymetrix_calvin_io::FileOutput::WriteInt16().
void CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::DmetCopyNumberData > & entryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 372 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_io::DataSetUpdater::colsizes, CopyMetricToBuffer(), dataGroupIndexMap, dataSetIndexMap, GetMetricBufferSize(), m_CHPFile, MmSetFloat_N(), MmSetUInt16_N(), MmSetUInt32_N(), NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 426 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
void CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::DmetMultiAllelicData & entry)
Seek to appropriate file position and update genotype entry
Parameters:
dataType The data type.
row The row index.
call CHP call representation.
confidence CHP confidence value.
Definition at line 454 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_data::_DmetMultiAllelicData::alleleCount, affymetrix_calvin_data::_DmetMultiAllelicData::call, affymetrix_calvin_data::_DmetMultiAllelicData::confidence, affymetrix_calvin_data::_DmetMultiAllelicData::contextA, affymetrix_calvin_data::_DmetMultiAllelicData::contextB, affymetrix_calvin_data::_DmetMultiAllelicData::contextC, affymetrix_calvin_data::_DmetMultiAllelicData::contextD, affymetrix_calvin_data::_DmetMultiAllelicData::contextE, affymetrix_calvin_data::_DmetMultiAllelicData::contextF, dataGroupIndexMap, dataSetIndexMap, ENTRY_COLUMN, affymetrix_calvin_data::_DmetMultiAllelicData::force, m_CHPFile, affymetrix_calvin_data::_DmetMultiAllelicData::metrics, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), affymetrix_calvin_data::_DmetMultiAllelicData::signalA, affymetrix_calvin_data::_DmetMultiAllelicData::signalB, affymetrix_calvin_data::_DmetMultiAllelicData::signalC, affymetrix_calvin_data::_DmetMultiAllelicData::signalD, affymetrix_calvin_data::_DmetMultiAllelicData::signalE, affymetrix_calvin_data::_DmetMultiAllelicData::signalF, UpdateMetrics(), affymetrix_calvin_io::FileOutput::WriteFloat(), and WriteUInt8().
void CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::DmetMultiAllelicData > & entryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 478 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_io::DataSetUpdater::colsizes, CopyMetricToBuffer(), dataGroupIndexMap, dataSetIndexMap, GetMetricBufferSize(), m_CHPFile, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 562 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
void CalvinCHPFileUpdater::UpdateExpressionQuantification (int row, float quantification)
Seek to appropriate file position and update expression signal
Parameters:
row The row index.
quantification The new quantification value.
Definition at line 93 of file CalvinCHPFileUpdater.cpp.
References ENTRY_COLUMN, ENTRY_DATA_GROUP, ENTRY_DATA_SET, m_CHPFile, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), and affymetrix_calvin_io::FileOutput::WriteFloat().
void CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer (int row_start, std::vector< float > & expressionSignalBuffer)
Seek to appropriate file position and update expression signal vector
Parameters:
row_start The start row for updating.
expressionSignalBuffer The vector contain all buffered signals to be updated.
Definition at line 99 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_io::DataSetUpdater::colsizes, ENTRY_DATA_GROUP, ENTRY_DATA_SET, m_CHPFile, NAME_COLUMN, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), and affymetrix_calvin_io::FileOutput::WriteFloat().
Referenced by affymetrix_calvin_io::CHPQuantificationFileBufferWriter::FlushBuffer(), and affymetrix_calvin_io::CHPQuantificationDetectionFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateFamilialSampleEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update the sample entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
entryBuffer The vector contain all buffered entries to be updated.
Definition at line 870 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateFamilialSegmentOverlapEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update the summary entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
entryBuffer The vector contain all buffered entries to be updated.
Definition at line 843 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateGenotypeEntry (int row, u_int8_t call, float confidence, float RAS1, float RAS2, float aaCall, float abCall, float bbCall, float noCall)
Seek to appropriate file position and update genotype entry
Parameters:
row The row index.
call CHP call representation.
confidence CHP confidence value.
RAS1 CHP RAS1 value.
RAS2 CHP RAS2 value.
aaCall CHP aaCall value.
abCall CHP abCall value.
bbCall CHP bbCall value.
noCall CHP noCall value.
Definition at line 111 of file CalvinCHPFileUpdater.cpp.
References ENTRY_COLUMN, ENTRY_DATA_GROUP, ENTRY_DATA_SET, m_CHPFile, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), affymetrix_calvin_io::FileOutput::WriteFloat(), and WriteUInt8().
void CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer (int row_start, const std::vector< CHPFileBufferWriter::GenotypeBufferEntry > & genotypeEntryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
row_start The start row for updating.
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 124 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_io::DataSetUpdater::colsizes, ENTRY_DATA_GROUP, ENTRY_DATA_SET, m_CHPFile, NAME_COLUMN, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), affymetrix_calvin_io::FileOutput::WriteFloat(), and WriteUInt8().
Referenced by affymetrix_calvin_io::CHPFileBufferWriter::FlushBuffer().
void affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMetrics (const std::vector< affymetrix_calvin_parameter::ParameterNameValueType > & metrics) [private]
Update the metrics
Referenced by UpdateDmetBiAllelicEntry(), UpdateDmetCopyNumberEntry(), UpdateDmetMultiAllelicEntry(), UpdateMultiDataExpressionEntry(), UpdateMultiDataExpressionEntryBuffer(), and UpdateMultiDataGenotypeEntry().
void CalvinCHPFileUpdater::UpdateMultiDataAllelePeaksEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & allelePeakEntryBuffer)
Seek to appropriate file position and update allele peak entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
allelePeakEntryBuffer The vector contain all buffered entries to be updated.
Definition at line 897 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateMultiDataCopyNumberEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & copyNumberEntryBuffer)
Seek to appropriate file position and update copy number entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
copyNumberEntryBuffer The vector contain all buffered entries to be updated.
Definition at line 655 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateMultiDataCopyNumberVariationRegionEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & cnVariationEntryBuffer)
Seek to appropriate file position and update cyto entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
cytoEntryBuffer The vector contain all buffered entries to be updated.
Definition at line 709 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateMultiDataCytoGenotypeEntryBuffer (MultiDataType dataType, int rowStart, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update Cyto genotyping call entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
entryBuffer The vector contain all buffered entries to be updated.
Definition at line 953 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateMultiDataCytoRegionEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & cytoEntryBuffer)
Seek to appropriate file position and update cyto entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
cytoEntryBuffer The vector contain all buffered entries to be updated.
Definition at line 682 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateMultiDataExpressionEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataExpressionData & entry)
Seek to appropriate file position and update expression entry
Parameters:
dataType The data type.
row The row index.
call CHP call representation.
confidence CHP confidence value.
Definition at line 738 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, ENTRY_COLUMN, m_CHPFile, affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::quantification, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), UpdateMetrics(), and affymetrix_calvin_io::FileOutput::WriteFloat().
void CalvinCHPFileUpdater::UpdateMultiDataExpressionEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::ProbeSetMultiDataExpressionData > & expressionEntryBuffer)
Seek to appropriate file position and update expression entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
expressionBufferEntry The vector contain all buffered entries to be updated.
Definition at line 747 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_io::DataSetUpdater::colsizes, dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), UpdateMetrics(), and affymetrix_calvin_io::FileOutput::WriteFloat().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateMultiDataExpressionEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & expressionEntryBuffer)
Seek to appropriate file position and update expression entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
expressionBufferEntry The vector contain all buffered entries to be updated.
Definition at line 762 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
void CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntry (MultiDataType dataType, int row, const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry)
Seek to appropriate file position and update genotype entry
Parameters:
dataType The data type.
row The row index.
call CHP call representation.
confidence CHP confidence value.
Definition at line 143 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, dataGroupIndexMap, dataSetIndexMap, ENTRY_COLUMN, m_CHPFile, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::metrics, affymetrix_calvin_io::DataSetUpdater::SeekToPosition(), UpdateMetrics(), affymetrix_calvin_io::FileOutput::WriteFloat(), and WriteUInt8().
void CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer (MultiDataType dataType, int row_start, const std::vector< affymetrix_calvin_data::ProbeSetMultiDataGenotypeData > & genotypeEntryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 589 of file CalvinCHPFileUpdater.cpp.
References affymetrix_calvin_io::DataSetUpdater::colsizes, CopyMetricToBuffer(), dataGroupIndexMap, dataSetIndexMap, GetMetricBufferSize(), m_CHPFile, MmSetFloat_N(), MmSetUInt32_N(), NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
void CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & genotypeEntryBuffer)
Seek to appropriate file position and update genotype entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
genotypeBufferEntry The vector contain all buffered entries to be updated.
Definition at line 628 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
void CalvinCHPFileUpdater::UpdateMultiDataMarkerABSignalsEntryBuffer (MultiDataType dataType, int row_start, int bufferEntrySize, const std::vector< char * > & entryBuffer)
Seek to appropriate file position and update AB signal entry vector
Parameters:
dataType The data type.
row_start The start row for updating.
bufferEntrySize The size of the buffer for a given element in the vector
entryBuffer The vector contain all buffered entries to be updated.
Definition at line 925 of file CalvinCHPFileUpdater.cpp.
References dataGroupIndexMap, dataSetIndexMap, m_CHPFile, NAME_COLUMN, and affymetrix_calvin_io::DataSetUpdater::SeekToPosition().
Referenced by affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer().
Member Data Documentation
std::map<MultiDataType, int> affymetrix_calvin_io::CalvinCHPFileUpdater::dataGroupIndexMap [private]
Map of data type to data group index.
Definition at line 303 of file CalvinCHPFileUpdater.h.
Referenced by CloseCHPFile(), Initialize(), UpdateChromosomeSegmentEntryBuffer(), UpdateChromosomeSummaryEntryBuffer(), UpdateDmetBiAllelicEntry(), UpdateDmetBiAllelicEntryBuffer(), UpdateDmetCopyNumberEntry(), UpdateDmetCopyNumberEntryBuffer(), UpdateDmetMultiAllelicEntry(), UpdateDmetMultiAllelicEntryBuffer(), UpdateFamilialSampleEntryBuffer(), UpdateFamilialSegmentOverlapEntryBuffer(), UpdateMultiDataAllelePeaksEntryBuffer(), UpdateMultiDataCopyNumberEntryBuffer(), UpdateMultiDataCopyNumberVariationRegionEntryBuffer(), UpdateMultiDataCytoGenotypeEntryBuffer(), UpdateMultiDataCytoRegionEntryBuffer(), UpdateMultiDataExpressionEntry(), UpdateMultiDataExpressionEntryBuffer(), UpdateMultiDataGenotypeEntry(), UpdateMultiDataGenotypeEntryBuffer(), and UpdateMultiDataMarkerABSignalsEntryBuffer().
std::map<MultiDataType, int> affymetrix_calvin_io::CalvinCHPFileUpdater::dataSetIndexMap [private]
Map of data type to index.
Definition at line 300 of file CalvinCHPFileUpdater.h.
Referenced by CloseCHPFile(), Initialize(), UpdateChromosomeSegmentEntryBuffer(), UpdateChromosomeSummaryEntryBuffer(), UpdateDmetBiAllelicEntry(), UpdateDmetBiAllelicEntryBuffer(), UpdateDmetCopyNumberEntry(), UpdateDmetCopyNumberEntryBuffer(), UpdateDmetMultiAllelicEntry(), UpdateDmetMultiAllelicEntryBuffer(), UpdateFamilialSampleEntryBuffer(), UpdateFamilialSegmentOverlapEntryBuffer(), UpdateMultiDataAllelePeaksEntryBuffer(), UpdateMultiDataCopyNumberEntryBuffer(), UpdateMultiDataCopyNumberVariationRegionEntryBuffer(), UpdateMultiDataCytoGenotypeEntryBuffer(), UpdateMultiDataCytoRegionEntryBuffer(), UpdateMultiDataExpressionEntry(), UpdateMultiDataExpressionEntryBuffer(), UpdateMultiDataGenotypeEntry(), UpdateMultiDataGenotypeEntryBuffer(), and UpdateMultiDataMarkerABSignalsEntryBuffer().
std::ofstream* affymetrix_calvin_io::CalvinCHPFileUpdater::m_CHPFile [private]
Definition at line 297 of file CalvinCHPFileUpdater.h.
Referenced by CalvinCHPFileUpdater(), CloseCHPFile(), OpenCHPFile(), UpdateChromosomeSegmentEntryBuffer(), UpdateChromosomeSummaryEntryBuffer(), UpdateDmetBiAllelicEntry(), UpdateDmetBiAllelicEntryBuffer(), UpdateDmetCopyNumberEntry(), UpdateDmetCopyNumberEntryBuffer(), UpdateDmetMultiAllelicEntry(), UpdateDmetMultiAllelicEntryBuffer(), UpdateExpressionQuantification(), UpdateExpressionQuantificationBuffer(), UpdateFamilialSampleEntryBuffer(), UpdateFamilialSegmentOverlapEntryBuffer(), UpdateGenotypeEntry(), UpdateGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), UpdateMultiDataAllelePeaksEntryBuffer(), UpdateMultiDataCopyNumberEntryBuffer(), UpdateMultiDataCopyNumberVariationRegionEntryBuffer(), UpdateMultiDataCytoGenotypeEntryBuffer(), UpdateMultiDataCytoRegionEntryBuffer(), UpdateMultiDataExpressionEntry(), UpdateMultiDataExpressionEntryBuffer(), UpdateMultiDataGenotypeEntry(), UpdateMultiDataGenotypeEntryBuffer(), and UpdateMultiDataMarkerABSignalsEntryBuffer().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPFileUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPFileUpdater.cpp