Affymetrix Fusion SDK: ErrHandler Class Reference
ErrHandler Class Reference
#include <ErrHandler.h>
Public Member Functions
virtual ~ErrHandler ()
virtual void handleError (const std::string &msg)=0
virtual bool getThrows ()
virtual void setThrows (bool doThrow)
virtual void setExitOnError (bool val)
virtual void setExitOnErrorValue (int val)
Detailed Description
Abstract base class (aka interface) for handling errors that come from Err::errAbort(). Write a class inheriting from ErrHandler and push it onto the handler stack via Err::pushErrHandler().
Definition at line 41 of file ErrHandler.h.
Constructor & Destructor Documentation
virtual ErrHandler::~ErrHandler () [inline, virtual]
Virtual destructor for a virtual class.
Definition at line 45 of file ErrHandler.h.
Member Function Documentation
virtual bool ErrHandler::getThrows () [inline, virtual]
Will this error handler be throwing exceptions?
Reimplemented in VerboseErrHandler.
Definition at line 51 of file ErrHandler.h.
Referenced by Err::getThrowStatus().
virtual void ErrHandler::handleError (const std::string & msg) [pure virtual]
Prototype for the function
Implemented in VerboseErrHandler.
virtual void ErrHandler::setExitOnError (bool val) [inline, virtual]
Will this error handler set the value returned when exiting on errors
Definition at line 60 of file ErrHandler.h.
Referenced by Err::setExitOnError().
virtual void ErrHandler::setExitOnErrorValue (int val) [inline, virtual]
The value to return if the error handler returns specifies the value
Definition at line 64 of file ErrHandler.h.
Referenced by Err::setExitOnErrorValue().
virtual void ErrHandler::setThrows (bool doThrow) [inline, virtual]
Will this error handler be throwing exceptions?
Reimplemented in VerboseErrHandler.
Definition at line 54 of file ErrHandler.h.
Referenced by Err::setThrowStatus().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/ErrHandler.h