Affymetrix Fusion SDK: Options Class Reference
Options Class Reference
base class for tracking class options
#include <Options.h>
Public Member Functions
Options ()
Options (char *argv[])
~Options ()
std::string getProgName (int oI=0)
int getArgCount (int oI=0)
std::string getArg (int index, int oI=0)
void getOptionNames (std::vector< std::string > &names, int oI=0)
void getOptionTypes (std::vector< PgOpt::PgOptType > &types, int oI=0)
std::string commandLine (int oI=0)
void setUsage (const std::string &usage)
PgOpt * defineOption (const std::string &shortName, const std::string &longName, PgOpt::PgOptType_t type, const std::string &help, const std::string &defaultVal)
PgOpt * defOptMult (const std::string &shortName, const std::string &longName, PgOpt::PgOptType_t type, const std::string &help, const std::string &defaultVal)
void defineOptionSection (const std::string &sectionName)
void optionsClear ()
void optionUsage (std::set< std::string > &hiddenOpts, bool printOpts=true, int oI=0)
bool isOptDefined (const std::string &name, int oI=0)
void setOpt (const std::string &name, const std::string &value)
void setOpt (const std::string &name, std::vector< std::string > &values)
void setOpt (const std::string &name, std::vector< std::vector< std::string > > &values)
void pushOpt (const std::string &name, const std::string &value)
void pushOpt (const std::string &name, std::vector< std::string > values)
virtual int parseArgv (const char *const *const argv, int start=1)
PgOpt * getPgOpt (const std::string &name, int oI=0)
std::string getOpt (const std::string &name, int oI=0)
bool getOptBool (const std::string &name, int oI=0)
int getOptInt (const std::string &name, int oI=0)
double getOptDouble (const std::string &name, int oI=0)
std::vector< std::string > & getOptVector (const std::string &name, int oI=0)
void printOptions (const std::string &prefix, int oI=0)
std::string getXMLParameterFileName (int oI=0)
std::string getXMLParameterFileGuid (int oI=0)
void setOptions (PgOptions &opts)
int snapshotOptions ()
int snapshotOptions (const std::string &label)
Private Attributes
std::vector< PgOptions > m_Options
Underlying options implementation.
std::map< std::string, int > m_Labels
Detailed Description
base class for tracking class options
Definition at line 44 of file Options.h.
Constructor & Destructor Documentation
Options::Options ()
Constructor
Definition at line 27 of file Options.cpp.
References m_Labels, and m_Options.
Options::Options (char * argv[])
Constructor
Parameters:
argv - vector of args to parse
Options::~Options ()
Destructor
Definition at line 35 of file Options.cpp.
Member Function Documentation
std::string Options::commandLine (int oI = 0) [inline]
Definition at line 78 of file Options.h.
PgOpt* Options::defineOption (const std::string & shortName, const std::string & longName, PgOpt::PgOptType_t type, const std::string & help, const std::string & defaultVal) [inline]
Definition at line 86 of file Options.h.
Referenced by BaseEngine::defineOptions(), and BaseEngine::defineStates().
void Options::defineOptionSection (const std::string & sectionName) [inline]
Definition at line 102 of file Options.h.
Referenced by BaseEngine::defineOptions().
PgOpt* Options::defOptMult (const std::string & shortName, const std::string & longName, PgOpt::PgOptType_t type, const std::string & help, const std::string & defaultVal) [inline]
Definition at line 94 of file Options.h.
Referenced by BaseEngine::defineOptions(), and pushOpt().
std::string Options::getArg (int index, int oI = 0) [inline]
Definition at line 72 of file Options.h.
int Options::getArgCount (int oI = 0) [inline]
Definition at line 69 of file Options.h.
std::string Options::getOpt (const std::string & name, int oI = 0) [inline]
Get the value of an option
Parameters:
name - the name of the option
Definition at line 182 of file Options.h.
References Err::errAbort().
Referenced by BaseEngine::checkOptions(), getOptBool(), BaseEngine::openStandardLog(), BaseEngine::parseArgv(), and BaseEngine::setLibFileOpt().
bool Options::getOptBool (const std::string & name, int oI = 0)
Get the boolean value of an option
Parameters:
name - the name of the option
Definition at line 158 of file Options.cpp.
References Err::errAbort(), getOpt(), isOptDefined(), and m_Options.
Referenced by BaseEngine::checkDiskSpace(), BaseEngine::checkOptions(), BaseEngine::parseArgv(), and BaseEngine::run().
double Options::getOptDouble (const std::string & name, int oI = 0)
Get the integer value of an option
Parameters:
name - the name of the option
Definition at line 182 of file Options.cpp.
References Err::errAbort(), isOptDefined(), and m_Options.
int Options::getOptInt (const std::string & name, int oI = 0)
Get the integer value of an option
Parameters:
name - the name of the option
Definition at line 172 of file Options.cpp.
References Err::errAbort(), isOptDefined(), and m_Options.
Referenced by BaseEngine::parseArgv().
void Options::getOptionNames (std::vector< std::string > & names, int oI = 0)
Definition at line 37 of file Options.cpp.
References m_Options.
void Options::getOptionTypes (std::vector< PgOpt::PgOptType > & types, int oI = 0)
Definition at line 43 of file Options.cpp.
References m_Options.
std::vector< std::string > & Options::getOptVector (const std::string & name, int oI = 0)
Return a vector of values for a particular option
Parameters:
name - option name
Definition at line 192 of file Options.cpp.
References Err::errAbort(), isOptDefined(), and m_Options.
PgOpt * Options::getPgOpt (const std::string & name, int oI = 0)
Get the underlying PgOpt containing information
Parameters:
name - the name of the option
Definition at line 148 of file Options.cpp.
References Err::errAbort(), isOptDefined(), and m_Options.
Referenced by BaseEngine::getMetaDataDescription().
std::string Options::getProgName (int oI = 0)
Get the name of the options set
Get the name of the Engine
Definition at line 208 of file Options.cpp.
References m_Options.
std::string Options::getXMLParameterFileGuid (int oI = 0)
Definition at line 201 of file Options.cpp.
References m_Options.
std::string Options::getXMLParameterFileName (int oI = 0)
Definition at line 197 of file Options.cpp.
References m_Options.
bool Options::isOptDefined (const std::string & name, int oI = 0)
Check to see if an option is defined.
Parameters:
name - option name
Definition at line 54 of file Options.cpp.
References m_Options.
Referenced by getOptBool(), getOptDouble(), getOptInt(), getOptVector(), getPgOpt(), pushOpt(), and setOpt().
void Options::optionsClear () [inline]
Definition at line 106 of file Options.h.
void Options::optionUsage (std::set< std::string > & hiddenOpts, bool printOpts = true, int oI = 0) [inline]
Definition at line 112 of file Options.h.
Referenced by BaseEngine::checkOptions(), and main().
int Options::parseArgv (const char *const *const argv, int start = 1) [virtual]
Parse and set options from argv
Parameters:
argv - arg vector
Reimplemented in BaseEngine.
Definition at line 144 of file Options.cpp.
References m_Options.
void Options::printOptions (const std::string & prefix, int oI = 0)
Todo:
kind of ugly how we are abusing PgOptions
Definition at line 212 of file Options.cpp.
References m_Options, and Verbose::out().
Referenced by BaseEngine::printEngineOptions().
void Options::pushOpt (const std::string & name, const std::string & value)
Add a value to a vector of values for option
Parameters:
name - option name
value - value to push onto vector of values
Definition at line 115 of file Options.cpp.
References Err::errAbort(), isOptDefined(), and m_Options.
Referenced by setOpt().
void Options::pushOpt (const std::string & name, std::vector< std::string > values)
Add a vector of values to the values for an option
Parameters:
name - option name
value - vector of values to push
Todo:
should roll into PgOptions support for this rather than using a stand alone hack
Definition at line 126 of file Options.cpp.
References defOptMult(), Err::errAbort(), isOptDefined(), m_Options, PgOpt::STRING_OPT, and ToStr().
void Options::setOpt (const std::string & name, std::vector< std::vector< std::string > > & values)
Set option to vector of vector of values
Parameters:
name - option name
value - vector of vector of values
Todo:
should roll into PgOptions support for this rather than using a stand alone hack
Definition at line 100 of file Options.cpp.
References Err::errAbort(), isOptDefined(), m_Options, pushOpt(), and ToStr().
void Options::setOpt (const std::string & name, const std::string & value)
Set option value
Parameters:
name - option name
value - value for the option
Definition at line 65 of file Options.cpp.
References Err::errAbort(), isOptDefined(), and m_Options.
Referenced by BaseEngine::BaseEngine(), BaseEngine::run(), BaseEngine::setLibFileOpt(), and setOpt().
void Options::setOpt (const std::string & name, std::vector< std::string > & values)
Set option to vector of values
Parameters:
name - option name
value - vector of values
Definition at line 77 of file Options.cpp.
References Err::errAbort(), isOptDefined(), m_Options, and setOpt().
void Options::setOptions (PgOptions & opts) [inline]
Definition at line 221 of file Options.h.
References PgOptions::m_option_vec.
void Options::setUsage (const std::string & usage) [inline]
Definition at line 82 of file Options.h.
int Options::snapshotOptions () [inline]
Definition at line 227 of file Options.h.
Referenced by BaseEngine::checkOptions().
int Options::snapshotOptions (const std::string & label) [inline]
Definition at line 232 of file Options.h.
Member Data Documentation
std::map<std::string,int> Options::m_Labels [private]
Definition at line 243 of file Options.h.
Referenced by Options().
std::vector<PgOptions> Options::m_Options [private]
Underlying options implementation.
Definition at line 238 of file Options.h.
Referenced by getOptBool(), getOptDouble(), getOptInt(), getOptionNames(), getOptionTypes(), getOptVector(), getPgOpt(), getProgName(), getXMLParameterFileGuid(), getXMLParameterFileName(), isOptDefined(), Options(), parseArgv(), printOptions(), pushOpt(), and setOpt().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/Options.h
C:/f112/affy/sdk/util/Options.cpp