Affymetrix Fusion SDK: affxsmd::SMDFileData Class Reference
affxsmd::SMDFileData Class Reference
#include <SMDFileData.h>
Public Member Functions
SMDFileData ()
virtual ~SMDFileData ()
void SetFileName (const char *name)
const std::string GetFileName () const
bool Exists ()
bool Read ()
SMDFrame GetFrame (unsigned int frameIdx)
unsigned int NumFrames ()
Public Attributes
unsigned int frameRows
unsigned int frameCols
Protected Member Functions
bool ReadData ()
void Clear ()
CIniFile::Record * FindRecord (std::vector< CIniFile::Record > &records, std::string section, std::string key)
bool GetIntValue (std::vector< CIniFile::Record > &records, std::string section, std::string key, int &value)
Protected Attributes
bool isRead
std::string filename
std::vector< SMDFrame > smdFrames
Detailed Description
This class reads a SMD file.
Definition at line 56 of file SMDFileData.h.
Constructor & Destructor Documentation
SMDFileData::SMDFileData ()
Constructor
Definition at line 75 of file SMDFileData.cpp.
References Clear().
SMDFileData::~SMDFileData () [virtual]
Destructor
Definition at line 83 of file SMDFileData.cpp.
Member Function Documentation
void SMDFileData::Clear (void) [protected]
Clear all members except filename
Definition at line 184 of file SMDFileData.cpp.
References frameCols, frameRows, isRead, and smdFrames.
Referenced by ReadData(), and SMDFileData().
bool SMDFileData::Exists ()
Checks for the existance of the file passed to SetFileName.
Returns:
True if the file exists.
Definition at line 91 of file SMDFileData.cpp.
References filename.
CIniFile::Record * SMDFileData::FindRecord (std::vector< CIniFile::Record > & records, std::string section, std::string key) [protected]
Find a Record in a collection.
Parameters:
records A collection of Records.
section The section name of the Record to find.
key The key name of the Record to find.
Returns:
A Record that matches the criteria, otherwise 0.
Definition at line 196 of file SMDFileData.cpp.
Referenced by GetIntValue().
const std::string affxsmd::SMDFileData::GetFileName () const [inline]
Gets the file name.
Returns:
The full path to the SMD file.
Definition at line 72 of file SMDFileData.h.
References filename.
SMDFrame SMDFileData::GetFrame (unsigned int frameIdx)
Get the SMDFrame information for a frame.
Parameters:
frameIdx The frame index.
Returns:
A SMDFrame with information of the frame indicated by the frameIdx parameter.
Definition at line 101 of file SMDFileData.cpp.
References smdFrames.
bool SMDFileData::GetIntValue (std::vector< CIniFile::Record > & records, std::string section, std::string key, int & value) [protected]
Get the integer value of a key.
Parameters:
records A collection of Records.
section The section name of the value.
key The key name of the value.
value The value found.
Returns:
Returns true if the value was found in the collection.
Definition at line 209 of file SMDFileData.cpp.
References FindRecord(), and CIniFile::Record::Value.
Referenced by ReadData().
unsigned int affxsmd::SMDFileData::NumFrames () [inline]
Get the number of frames in the SMD.
Returns:
Number of frames.
Definition at line 93 of file SMDFileData.h.
References smdFrames.
bool SMDFileData::Read ()
Read the SMD file.
Returns:
Returns true if the file was successfully read.
Definition at line 69 of file FusionArrayFileReader.cpp.
References ARRAY_SET_FILE_TYPE_IDENTIFIER, affymetrix_calvin_array::ArrayAttributes::Attributes(), affymetrix_dttarray::DttArrayData::Attributes(), affymetrix_calvin_array::ArrayData::Clear(), affxexp::CEXPFileData::GetArrayType(), affymetrix_dttarray::DttArrayData::GetArrayType(), affxexp::CEXPFileData::GetSampleParameters(), affymetrix_calvin_parameter::_tagParameterNameValuePair::Name, affymetrix_dttarray::_AttributeNameValueType::name, affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affxexp::CEXPFileData::Read(), affymetrix_dttarray::DttArrayFileReader::Read(), affymetrix_calvin_io::ArrayFileReader::Read(), affxexp::CEXPFileData::SetFileName(), affymetrix_dttarray::DttArrayFileReader::SetFileName(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), _TagValuePairType::Tag, affymetrix_calvin_array::ArrayData::UserAttributes(), _TagValuePairType::Value, affymetrix_calvin_parameter::_tagParameterNameValuePair::Value, and affymetrix_dttarray::_AttributeNameValueType::value.
bool SMDFileData::ReadData () [protected]
Read the SMD data.
Returns:
Returns true if the SMD data was successfully read.
Definition at line 129 of file SMDFileData.cpp.
References Clear(), affxsmd::SMDFrame::cols, filename, frameCols, FrameCols, affxsmd::SMDFrame::frameIdx, frameRows, FrameRows, Frames, CIniFile::GetAllRecords(), GetIntValue(), KeyCols, KeyRows, KeyStartCol, KeyStartRow, affxsmd::SMDFrame::rows, smdFrames, affxsmd::SMDFrame::startCol, affxsmd::SMDFrame::startRow, and SummarySec.
void affxsmd::SMDFileData::SetFileName (const char * name) [inline]
Sets the file name.
Parameters:
name The full path to the SMD file.
Definition at line 67 of file SMDFileData.h.
References filename.
Member Data Documentation
std::string affxsmd::SMDFileData::filename [protected]
SMD file name. Including the relation or full path.
Definition at line 129 of file SMDFileData.h.
Referenced by Exists(), GetFileName(), ReadData(), and SetFileName().
unsigned int affxsmd::SMDFileData::frameCols
The number of frame columns in the SMD (frames per row)
Definition at line 98 of file SMDFileData.h.
Referenced by Clear(), and ReadData().
unsigned int affxsmd::SMDFileData::frameRows
The number of frames rows in the SMD (frames per column)
Definition at line 93 of file SMDFileData.h.
Referenced by Clear(), and ReadData().
bool affxsmd::SMDFileData::isRead [protected]
A flag indicating if a SMD has been read.
Definition at line 127 of file SMDFileData.h.
Referenced by Clear().
std::vector<SMDFrame> affxsmd::SMDFileData::smdFrames [protected]
A collection of SMDFrame information for all frames in the SMD.
Definition at line 131 of file SMDFileData.h.
Referenced by Clear(), GetFrame(), NumFrames(), and ReadData().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/SMDFileData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionArrayFileReader.cpp
C:/f112/affy/sdk/calvin_files/fusion/src/FusionGrcFileReader.cpp
C:/f112/affy/sdk/file/SMDFileData.cpp