Affymetrix Fusion SDK: CFusionForceCallTypeCOM Class Reference
CFusionForceCallTypeCOM Class Reference
#include <FusionForceCallTypeCOM.h>
Public Member Functions
CFusionForceCallTypeCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_fusion_io::FusionForceCallType & Force ()
STDMETHOD() get_Position (int *pVal)
STDMETHOD() get_Call (CHAR *pVal)
STDMETHOD() get_Reason (CHAR *pVal)
Private Attributes
affymetrix_fusion_io::FusionForceCallType force
Detailed Description
Definition at line 29 of file FusionForceCallTypeCOM.h.
Constructor & Destructor Documentation
CFusionForceCallTypeCOM::CFusionForceCallTypeCOM () [inline]
Definition at line 36 of file FusionForceCallTypeCOM.h.
Member Function Documentation
HRESULT CFusionForceCallTypeCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionForceCallTypeCOM.h.
void CFusionForceCallTypeCOM::FinalRelease () [inline]
Definition at line 60 of file FusionForceCallTypeCOM.h.
affymetrix_fusion_io::FusionForceCallType& CFusionForceCallTypeCOM::Force () [inline]
Definition at line 68 of file FusionForceCallTypeCOM.h.
Referenced by CFusionResequencingResultsCOM::GetForceCall().
STDMETHODIMP CFusionForceCallTypeCOM::get_Call (CHAR * pVal)
Definition at line 54 of file FusionForceCallTypeCOM.cpp.
References force, and affymetrix_fusion_io::FusionBaseCallType::GetCall().
STDMETHODIMP CFusionForceCallTypeCOM::get_Position (int * pVal)
Definition at line 48 of file FusionForceCallTypeCOM.cpp.
References force, and affymetrix_fusion_io::FusionBaseCallType::GetPosition().
STDMETHODIMP CFusionForceCallTypeCOM::get_Reason (CHAR * pVal)
Definition at line 42 of file FusionForceCallTypeCOM.cpp.
References force, and affymetrix_fusion_io::FusionForceCallType::GetReason().
STDMETHODIMP CFusionForceCallTypeCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 27 of file FusionForceCallTypeCOM.cpp.
Member Data Documentation
affymetrix_fusion_io::FusionForceCallType CFusionForceCallTypeCOM::force [private]
Definition at line 65 of file FusionForceCallTypeCOM.h.
Referenced by get_Call(), get_Position(), and get_Reason().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionForceCallTypeCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionForceCallTypeCOM.cpp