Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPDataReg Class Reference
affymetrix_fusion_io::FusionCHPDataReg Class Reference
#include <FusionCHPData.h>
Public Member Functions
FusionCHPDataReg ()
virtual ~FusionCHPDataReg ()
void SetFileTypeIds (const affymetrix_calvin_utilities::AffymetrixGuidTypeList &fileTypeIds)
Static Public Member Functions
static FusionCHPData * Read (const std::string &fileName)
static FusionCHPData * ReadHeader (const std::string &fileName)
Private Member Functions
virtual FusionCHPData * MakeObject ()=0
Static Private Member Functions
static FusionCHPData * CreateObject (const affymetrix_calvin_utilities::AffymetrixGuidType &fileTypeId)
Private Attributes
FusionCHPDataReg * m_Next
affymetrix_calvin_utilities::AffymetrixGuidTypeList fileTypeIdentifiers
Static Private Attributes
static FusionCHPDataReg * m_Head = NULL
Detailed Description
A class used to self register CHP data classes.
Definition at line 103 of file FusionCHPData.h.
Constructor & Destructor Documentation
FusionCHPDataReg::FusionCHPDataReg ()
Constructor
Definition at line 45 of file FusionCHPData.cpp.
References m_Head.
FusionCHPDataReg::~FusionCHPDataReg () [virtual]
Destructor
Definition at line 50 of file FusionCHPData.cpp.
References fileTypeIdentifiers.
Member Function Documentation
FusionCHPData * FusionCHPDataReg::CreateObject (const affymetrix_calvin_utilities::AffymetrixGuidType & fileTypeId) [static, private]
Creates a CHP reading object.
Parameters:
fileTypeId The file type in the CHP file.
Returns:
The CHP object, NULL if not able to read the file.
Definition at line 59 of file FusionCHPData.cpp.
References affymetrix_fusion_io::FusionCHPData::fileTypeIdentifier, affymetrix_fusion_io::FusionCHPData::fileTypeIdentifiers, m_Head, and m_Next.
Referenced by Read(), and ReadHeader().
virtual FusionCHPData* affymetrix_fusion_io::FusionCHPDataReg::MakeObject () [private, pure virtual]
Makes an CHP data object.
Returns:
The CHP data object.
Implemented in affymetrix_fusion_io::FusionCHPGenericData::Reg, affymetrix_fusion_io::FusionCHPLegacyData::Reg, affymetrix_fusion_io::FusionCHPMultiDataData::Reg, affymetrix_fusion_io::FusionCHPQuantificationData::Reg, affymetrix_fusion_io::FusionCHPQuantificationDetectionData::Reg, and affymetrix_fusion_io::FusionCHPTilingData::Reg.
FusionCHPData * FusionCHPDataReg::Read (const std::string & fileName) [static]
Reads the contents of a CHP file.
Parameters:
fileName The full path to the input CHP file.
Returns:
A pointer to the CHP data object. NULL if the read failed.
Definition at line 147 of file FusionCHPData.cpp.
References CreateObject(), affymetrix_fusion_io::FusionCHPData::Read(), ReadGuidFromFile(), and affymetrix_fusion_io::FusionCHPData::SetFileName().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataAccessor::ExtractData(), affxchpwriter::CCHPFileBufferWriter::Initialize(), and CFusionCHPDataRegCOM::Read().
FusionCHPData * FusionCHPDataReg::ReadHeader (const std::string & fileName) [static]
Reads the header of a CHP file.
Parameters:
fileName The full path to the input CHP file.
Returns:
A pointer to the CHP data object. NULL if the read failed.
Definition at line 123 of file FusionCHPData.cpp.
References CreateObject(), ReadGuidFromFile(), affymetrix_fusion_io::FusionCHPData::ReadHeader(), and affymetrix_fusion_io::FusionCHPData::SetFileName().
Referenced by CFusionCHPDataRegCOM::ReadHeader().
void FusionCHPDataReg::SetFileTypeIds (const affymetrix_calvin_utilities::AffymetrixGuidTypeList & fileTypeIds)
Definition at line 37 of file FusionCHPData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::Reg::Reg(), affymetrix_fusion_io::FusionCHPQuantificationDetectionData::Reg::Reg(), affymetrix_fusion_io::FusionCHPQuantificationData::Reg::Reg(), affymetrix_fusion_io::FusionCHPMultiDataData::Reg::Reg(), affymetrix_fusion_io::FusionCHPLegacyData::Reg::Reg(), and affymetrix_fusion_io::FusionCHPGenericData::Reg::Reg().
Member Data Documentation
affymetrix_calvin_utilities::AffymetrixGuidTypeList affymetrix_fusion_io::FusionCHPDataReg::fileTypeIdentifiers [private]
The file type identifiers associated with the CHP files the reader can parse.
Definition at line 149 of file FusionCHPData.h.
Referenced by ~FusionCHPDataReg().
FusionCHPDataReg * FusionCHPDataReg::m_Head = NULL [static, private]
A pointer to the first registered CHP reader.
The head of the CHP data objects.
Definition at line 143 of file FusionCHPData.h.
Referenced by CreateObject(), and FusionCHPDataReg().
FusionCHPDataReg* affymetrix_fusion_io::FusionCHPDataReg::m_Next [private]
A pointer to the next registered CHP reader.
Definition at line 146 of file FusionCHPData.h.
Referenced by CreateObject().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPData.cpp