Affymetrix Fusion SDK: AffxArray< TYPE > Class Template Reference
AffxArray< TYPE > Class Template Reference
A template class derived from std::vector.
#include <AffxArray.h>
Public Member Functions
AffxArray (int iSize, int iCapacity)
AffxArray ()
virtual ~AffxArray ()
void reserve (int iSize)
std::vector< TYPE * >::size_type size () const
void resize (int iNewSize)
TYPE *& at (int iIndex)
void nullAll ()
void deleteAll ()
int getCount ()
void setAt (int iIndex, TYPE *obj)
TYPE * getAt (int iIndex)
void add (TYPE *obj)
int binarySearch (TYPE &obj, int iCompareCode)
void quickSort ()
void quickSort (int iCompareCode)
void quickSort (int iFrom, int iTo, int iCompareCode)
void swap (int iIndex1, int iIndex2)
void shuffle ()
void qsort ()
void qsort (int iCompareCode)
void qsort (int iFrom, int iTo, int iCompareCode)
void removeAt (int iIndex)
void deleteAt (int iIndex)
Static Public Member Functions
static int compareAsInt (const AffxString &strThis, const AffxString &strThat)
static int compareAsIntDescending (const AffxString &strThis, const AffxString &strThat)
static int compareCase (const AffxString &iThis, const AffxString &iThat)
static int compareNoCase (const AffxString &iThis, const AffxString &iThat)
static int compare (bool bThis, bool bThat)
static int compare (int iThis, int iThat)
static int compare (unsigned int iThis, unsigned int iThat)
static int compare (double dThis, double dThat)
static int compareCaseDescending (const AffxString &iThis, const AffxString &iThat)
static int compareDescending (bool bThis, bool bThat)
static int compareDescending (int iThis, int iThat)
static int compareDescending (double dThis, double dThat)
Detailed Description
template<class TYPE>
class AffxArray< TYPE >
A template class derived from std::vector.
Definition at line 39 of file AffxArray.h.
Constructor & Destructor Documentation
template<class TYPE> AffxArray< TYPE >::AffxArray (int iSize, int iCapacity) [inline]
Definition at line 169 of file AffxArray.h.
template<class TYPE> AffxArray< TYPE >::AffxArray () [inline]
Definition at line 170 of file AffxArray.h.
template<class TYPE> virtual AffxArray< TYPE >::~AffxArray () [inline, virtual]
Definition at line 171 of file AffxArray.h.
Member Function Documentation
template<class TYPE> void AffxArray< TYPE >::add (TYPE * obj) [inline]
Definition at line 211 of file AffxArray.h.
Referenced by AffxString::calculateMeltingTempWithSNPs(), Calvin::load(), and Calvin::loadHeader().
template<class TYPE> TYPE*& AffxArray< TYPE >::at (int iIndex) [inline]
Definition at line 176 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::at(), AffxArray< AffxArray< CalvinValue > >::binarySearch(), AffxArray< AffxArray< CalvinValue > >::deleteAll(), AffxArray< AffxArray< CalvinValue > >::deleteAt(), AffxArray< AffxArray< CalvinValue > >::getAt(), AffxArray< AffxArray< CalvinValue > >::nullAll(), AffxArray< AffxArray< CalvinValue > >::setAt(), AffxArray< AffxArray< CalvinValue > >::shuffle(), and AffxArray< AffxArray< CalvinValue > >::swap().
template<class TYPE> int AffxArray< TYPE >::binarySearch (TYPE & obj, int iCompareCode) [inline]
Definition at line 216 of file AffxArray.h.
Referenced by Calvin::equivalentHeader().
template<class TYPE> static int AffxArray< TYPE >::compare (double dThis, double dThat) [inline, static]
Definition at line 118 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compare (bool bThis, bool bThat) [inline, static]
Definition at line 88 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::compareAsInt().
template<class TYPE> static int AffxArray< TYPE >::compare (int iThis, int iThat) [inline, static]
Definition at line 98 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compare (unsigned int iThis, unsigned int iThat) [inline, static]
Definition at line 108 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compareAsInt (const AffxString & strThis, const AffxString & strThat) [inline, static]
Definition at line 43 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compareAsIntDescending (const AffxString & strThis, const AffxString & strThat) [inline, static]
Definition at line 54 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compareCase (const AffxString & iThis, const AffxString & iThat) [inline, static]
Definition at line 65 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compareCaseDescending (const AffxString & iThis, const AffxString & iThat) [inline, static]
Definition at line 128 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compareDescending (bool bThis, bool bThat) [inline, static]
Definition at line 139 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::compareAsIntDescending().
template<class TYPE> static int AffxArray< TYPE >::compareDescending (int iThis, int iThat) [inline, static]
Definition at line 149 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compareDescending (double dThis, double dThat) [inline, static]
Definition at line 159 of file AffxArray.h.
template<class TYPE> static int AffxArray< TYPE >::compareNoCase (const AffxString & iThis, const AffxString & iThat) [inline, static]
Definition at line 76 of file AffxArray.h.
template<class TYPE> void AffxArray< TYPE >::deleteAll () [inline]
Definition at line 187 of file AffxArray.h.
Referenced by AffxString::calculateMeltingTempWithSNPs(), Calvin::clear(), CalvinDataGroup::clear(), and CalvinDataSet::clear().
template<class TYPE> void AffxArray< TYPE >::deleteAt (int iIndex) [inline]
Definition at line 332 of file AffxArray.h.
template<class TYPE> TYPE* AffxArray< TYPE >::getAt (int iIndex) [inline]
Definition at line 199 of file AffxArray.h.
Referenced by AffxString::calculateMeltingTempWithSNPs(), CalvinDataSet::clear(), Calvin::equivalent(), Calvin::equivalentHeader(), and AffxArray< AffxArray< CalvinValue > >::qsort().
template<class TYPE> int AffxArray< TYPE >::getCount () [inline]
Definition at line 197 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::binarySearch(), AffxString::calculateMeltingTempWithSNPs(), CalvinDataSet::clear(), AffxArray< AffxArray< CalvinValue > >::deleteAll(), Calvin::equivalent(), Calvin::equivalentHeader(), AffxArray< AffxArray< CalvinValue > >::getAt(), AffxArray< AffxArray< CalvinValue > >::nullAll(), AffxArray< AffxArray< CalvinValue > >::qsort(), AffxArray< AffxArray< CalvinValue > >::quickSort(), AffxArray< AffxArray< CalvinValue > >::setAt(), and AffxArray< AffxArray< CalvinValue > >::shuffle().
template<class TYPE> void AffxArray< TYPE >::nullAll () [inline]
Definition at line 178 of file AffxArray.h.
Referenced by AffxString::calculateMeltingTempWithSNPs().
template<class TYPE> void AffxArray< TYPE >::qsort (int iFrom, int iTo, int iCompareCode) [inline]
Definition at line 303 of file AffxArray.h.
template<class TYPE> void AffxArray< TYPE >::qsort () [inline]
Definition at line 301 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::qsort().
template<class TYPE> void AffxArray< TYPE >::qsort (int iCompareCode) [inline]
Definition at line 302 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::qsort().
template<class TYPE> void AffxArray< TYPE >::quickSort () [inline]
Definition at line 246 of file AffxArray.h.
Referenced by Calvin::equivalentHeader(), and AffxArray< AffxArray< CalvinValue > >::quickSort().
template<class TYPE> void AffxArray< TYPE >::quickSort (int iCompareCode) [inline]
Definition at line 247 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::quickSort().
template<class TYPE> void AffxArray< TYPE >::quickSort (int iFrom, int iTo, int iCompareCode) [inline]
Definition at line 248 of file AffxArray.h.
template<class TYPE> void AffxArray< TYPE >::removeAt (int iIndex) [inline]
Definition at line 327 of file AffxArray.h.
template<class TYPE> void AffxArray< TYPE >::reserve (int iSize) [inline]
Definition at line 173 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::AffxArray(), Calvin::load(), Calvin::loadHeader(), and AffxArray< AffxArray< CalvinValue > >::reserve().
template<class TYPE> void AffxArray< TYPE >::resize (int iNewSize) [inline]
Definition at line 175 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::AffxArray(), and AffxArray< AffxArray< CalvinValue > >::resize().
template<class TYPE> void AffxArray< TYPE >::setAt (int iIndex, TYPE * obj) [inline]
Definition at line 198 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::qsort().
template<class TYPE> void AffxArray< TYPE >::shuffle () [inline]
Definition at line 285 of file AffxArray.h.
template<class TYPE> std::vector<TYPE*>::size_type AffxArray< TYPE >::size () const [inline]
Definition at line 174 of file AffxArray.h.
Referenced by AffxArray< AffxArray< CalvinValue > >::getCount(), and AffxArray< AffxArray< CalvinValue > >::size().
template<class TYPE> void AffxArray< TYPE >::swap (int iIndex1, int iIndex2) [inline]
Definition at line 278 of file AffxArray.h.
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/AffxArray.h