Affymetrix Fusion SDK: CFusionCELDataCOM Class Reference
CFusionCELDataCOM Class Reference
#include <FusionCELDataCOM.h>
Public Member Functions
CFusionCELDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
STDMETHOD() get_FileName (BSTR *pVal)
STDMETHOD() put_FileName (BSTR newVal)
STDMETHOD() get_Error (BSTR *pVal)
STDMETHOD() GetHeaderKey (BSTR key, BSTR *pVal)
STDMETHOD() get_Version (int *pVal)
STDMETHOD() get_Cols (int *pVal)
STDMETHOD() get_Rows (int *pVal)
STDMETHOD() get_NumCells (int *pVal)
STDMETHOD() get_Header (BSTR *pVal)
STDMETHOD() get_Alg (BSTR *pVal)
STDMETHOD() get_Params (BSTR *pVal)
STDMETHOD() GetAlgorithmParameter (BSTR tag, BSTR *pVal)
STDMETHOD() GetAlgorithmParameterTag (int index, BSTR *pVal)
STDMETHOD() get_NumberAlgorithmParameters (int *pVal)
STDMETHOD() get_AlgorithmParameters (BSTR *pVal)
STDMETHOD() get_DatHeader (BSTR *pVal)
STDMETHOD() get_ChipType (BSTR *pVal)
STDMETHOD() get_CellMargin (int *pVal)
STDMETHOD() get_NumOutliers (int *pVal)
STDMETHOD() get_NumMasked (int *pVal)
STDMETHOD() IndexToX (int index, int *x)
STDMETHOD() IndexToY (int index, int *y)
STDMETHOD() XYToIndex (int x, int y, int *index)
STDMETHOD() XYToIndexStatic (int x, int y, int r, int c, int *index)
STDMETHOD() GetEntryByIndex (int index, IFusionCELFileEntryType *entry)
STDMETHOD() GetEntryByCoordinate (int x, int y, IFusionCELFileEntryType *entry)
STDMETHOD() GetIntensityByIndex (int index, float *intensity)
STDMETHOD() GetIntensityByCoordinate (int x, int y, float *intensity)
STDMETHOD() GetStdvByIndex (int index, float *stdv)
STDMETHOD() GetStdvByCoordinate (int x, int y, float *stdv)
STDMETHOD() GetPixelsByIndex (int index, short *pixels)
STDMETHOD() GetPixelsByCoordinate (int x, int y, short *pixels)
STDMETHOD() IsOutlierByIndex (int index, VARIANT_BOOL *value)
STDMETHOD() IsOutlierByCoordinate (int x, int y, VARIANT_BOOL *value)
STDMETHOD() IsMaskedByIndex (int index, VARIANT_BOOL *value)
STDMETHOD() IsMaskedByCoordinate (int x, int y, VARIANT_BOOL *value)
STDMETHOD() Close (void)
STDMETHOD() GetFileSize (LONG *size)
STDMETHOD() Exists (VARIANT_BOOL *pVal)
STDMETHOD() ReadHeader (VARIANT_BOOL *pVal)
STDMETHOD() Read (VARIANT_BOOL includeMaskAndOutliers, VARIANT_BOOL *pVal)
STDMETHOD() Clear (void)
STDMETHOD() GetParameters (VARIANT *params)
STDMETHOD() GetGridCorners (IFGridCoords **grid)
STDMETHOD() get_FileId (BSTR *pVal)
STDMETHOD() get_MasterFileName (BSTR *pVal)
STDMETHOD() get_LibraryPackageName (BSTR *pVal)
STDMETHOD() SetActiveDataGroup (BSTR channel)
STDMETHOD() IsMultiColor (VARIANT_BOOL *pVal)
STDMETHOD() GetChannels (VARIANT *channels)
Private Attributes
affymetrix_fusion_io::FusionCELData cellData
Detailed Description
Definition at line 31 of file FusionCELDataCOM.h.
Constructor & Destructor Documentation
CFusionCELDataCOM::CFusionCELDataCOM () [inline]
Definition at line 38 of file FusionCELDataCOM.h.
Member Function Documentation
STDMETHODIMP CFusionCELDataCOM::Clear (void)
Definition at line 292 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::Clear().
STDMETHODIMP CFusionCELDataCOM::Close (void)
Definition at line 262 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::Close().
STDMETHODIMP CFusionCELDataCOM::Exists (VARIANT_BOOL * pVal)
Definition at line 274 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::Exists().
HRESULT CFusionCELDataCOM::FinalConstruct () [inline]
Definition at line 57 of file FusionCELDataCOM.h.
void CFusionCELDataCOM::FinalRelease () [inline]
Definition at line 62 of file FusionCELDataCOM.h.
STDMETHODIMP CFusionCELDataCOM::get_Alg (BSTR * pVal)
Definition at line 98 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetAlg().
STDMETHODIMP CFusionCELDataCOM::get_AlgorithmParameters (BSTR * pVal)
Definition at line 128 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetAlgorithmParameters().
STDMETHODIMP CFusionCELDataCOM::get_CellMargin (int * pVal)
Definition at line 146 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetCellMargin().
STDMETHODIMP CFusionCELDataCOM::get_ChipType (BSTR * pVal)
Definition at line 140 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetChipType().
STDMETHODIMP CFusionCELDataCOM::get_Cols (int * pVal)
Definition at line 74 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetCols().
STDMETHODIMP CFusionCELDataCOM::get_DatHeader (BSTR * pVal)
Definition at line 134 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetDatHeader().
STDMETHODIMP CFusionCELDataCOM::get_Error (BSTR * pVal)
Definition at line 56 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetError().
STDMETHODIMP CFusionCELDataCOM::get_FileId (BSTR * pVal)
Definition at line 333 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCELData::GetFileId().
STDMETHODIMP CFusionCELDataCOM::get_FileName (BSTR * pVal)
Definition at line 44 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCELData::GetFileName().
STDMETHODIMP CFusionCELDataCOM::get_Header (BSTR * pVal)
Definition at line 92 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetHeader().
STDMETHODIMP CFusionCELDataCOM::get_LibraryPackageName (BSTR * pVal)
Definition at line 345 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetLibraryPackageName().
STDMETHODIMP CFusionCELDataCOM::get_MasterFileName (BSTR * pVal)
Definition at line 339 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetMasterFileName().
STDMETHODIMP CFusionCELDataCOM::get_NumberAlgorithmParameters (int * pVal)
Definition at line 122 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetNumberAlgorithmParameters().
STDMETHODIMP CFusionCELDataCOM::get_NumCells (int * pVal)
Definition at line 86 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetNumCells().
STDMETHODIMP CFusionCELDataCOM::get_NumMasked (int * pVal)
Definition at line 158 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetNumMasked().
STDMETHODIMP CFusionCELDataCOM::get_NumOutliers (int * pVal)
Definition at line 152 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetNumOutliers().
STDMETHODIMP CFusionCELDataCOM::get_Params (BSTR * pVal)
Definition at line 104 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetParams().
STDMETHODIMP CFusionCELDataCOM::get_Rows (int * pVal)
Definition at line 80 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetRows().
STDMETHODIMP CFusionCELDataCOM::get_Version (int * pVal)
Definition at line 68 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetVersion().
STDMETHODIMP CFusionCELDataCOM::GetAlgorithmParameter (BSTR tag, BSTR * pVal)
Definition at line 110 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetAlgorithmParameter().
STDMETHODIMP CFusionCELDataCOM::GetAlgorithmParameterTag (int index, BSTR * pVal)
Definition at line 116 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetAlgorithmParameterTag().
STDMETHODIMP CFusionCELDataCOM::GetChannels (VARIANT * channels)
Definition at line 362 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetChannels().
STDMETHODIMP CFusionCELDataCOM::GetEntryByCoordinate (int x, int y, IFusionCELFileEntryType * entry)
Definition at line 195 of file FusionCELDataCOM.cpp.
References cellData, CFusionCELFileEntryTypeCOM::Entry(), and affymetrix_fusion_io::FusionCELData::GetEntry().
STDMETHODIMP CFusionCELDataCOM::GetEntryByIndex (int index, IFusionCELFileEntryType * entry)
Definition at line 188 of file FusionCELDataCOM.cpp.
References cellData, CFusionCELFileEntryTypeCOM::Entry(), and affymetrix_fusion_io::FusionCELData::GetEntry().
STDMETHODIMP CFusionCELDataCOM::GetFileSize (LONG * size)
Definition at line 268 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetFileSize().
STDMETHODIMP CFusionCELDataCOM::GetGridCorners (IFGridCoords ** grid)
Definition at line 323 of file FusionCELDataCOM.cpp.
References cellData, affymetrix_fusion_io::FusionCELData::GetGridCorners(), and CFGridCoordsCOM::SetGrid().
STDMETHODIMP CFusionCELDataCOM::GetHeaderKey (BSTR key, BSTR * pVal)
Definition at line 62 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::GetHeaderKey().
STDMETHODIMP CFusionCELDataCOM::GetIntensityByCoordinate (int x, int y, float * intensity)
Definition at line 208 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetIntensity().
STDMETHODIMP CFusionCELDataCOM::GetIntensityByIndex (int index, float * intensity)
Definition at line 202 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetIntensity().
STDMETHODIMP CFusionCELDataCOM::GetParameters (VARIANT * params)
Definition at line 298 of file FusionCELDataCOM.cpp.
References cellData, affymetrix_fusion_io::FusionCELData::GetParameters(), and CFusionTagValuePairTypeCOM::SetParam().
STDMETHODIMP CFusionCELDataCOM::GetPixelsByCoordinate (int x, int y, short * pixels)
Definition at line 232 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetPixels().
STDMETHODIMP CFusionCELDataCOM::GetPixelsByIndex (int index, short * pixels)
Definition at line 226 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetPixels().
STDMETHODIMP CFusionCELDataCOM::GetStdvByCoordinate (int x, int y, float * stdv)
Definition at line 220 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetStdv().
STDMETHODIMP CFusionCELDataCOM::GetStdvByIndex (int index, float * stdv)
Definition at line 214 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::GetStdv().
STDMETHODIMP CFusionCELDataCOM::IndexToX (int index, int * x)
Definition at line 164 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::IndexToX().
STDMETHODIMP CFusionCELDataCOM::IndexToY (int index, int * y)
Definition at line 170 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::IndexToY().
STDMETHODIMP CFusionCELDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 29 of file FusionCELDataCOM.cpp.
STDMETHODIMP CFusionCELDataCOM::IsMaskedByCoordinate (int x, int y, VARIANT_BOOL * value)
Definition at line 256 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::IsMasked().
STDMETHODIMP CFusionCELDataCOM::IsMaskedByIndex (int index, VARIANT_BOOL * value)
Definition at line 250 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::IsMasked().
STDMETHODIMP CFusionCELDataCOM::IsMultiColor (VARIANT_BOOL * pVal)
Definition at line 356 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::IsMultiColor().
STDMETHODIMP CFusionCELDataCOM::IsOutlierByCoordinate (int x, int y, VARIANT_BOOL * value)
Definition at line 244 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::IsOutlier().
STDMETHODIMP CFusionCELDataCOM::IsOutlierByIndex (int index, VARIANT_BOOL * value)
Definition at line 238 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::IsOutlier().
STDMETHODIMP CFusionCELDataCOM::put_FileName (BSTR newVal)
Definition at line 50 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCELData::SetFileName().
STDMETHODIMP CFusionCELDataCOM::Read (VARIANT_BOOL includeMaskAndOutliers, VARIANT_BOOL * pVal)
Definition at line 286 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::Read().
STDMETHODIMP CFusionCELDataCOM::ReadHeader (VARIANT_BOOL * pVal)
Definition at line 280 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::ReadHeader().
STDMETHODIMP CFusionCELDataCOM::SetActiveDataGroup (BSTR channel)
Definition at line 351 of file FusionCELDataCOM.cpp.
References cellData, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCELData::SetActiveDataGroup().
STDMETHODIMP CFusionCELDataCOM::XYToIndex (int x, int y, int * index)
Definition at line 176 of file FusionCELDataCOM.cpp.
References cellData, and affymetrix_fusion_io::FusionCELData::XYToIndex().
Referenced by XYToIndexStatic().
STDMETHODIMP CFusionCELDataCOM::XYToIndexStatic (int x, int y, int r, int c, int * index)
Definition at line 182 of file FusionCELDataCOM.cpp.
References XYToIndex().
Member Data Documentation
affymetrix_fusion_io::FusionCELData CFusionCELDataCOM::cellData [private]
Definition at line 67 of file FusionCELDataCOM.h.
Referenced by Clear(), Close(), Exists(), get_Alg(), get_AlgorithmParameters(), get_CellMargin(), get_ChipType(), get_Cols(), get_DatHeader(), get_Error(), get_FileId(), get_FileName(), get_Header(), get_LibraryPackageName(), get_MasterFileName(), get_NumberAlgorithmParameters(), get_NumCells(), get_NumMasked(), get_NumOutliers(), get_Params(), get_Rows(), get_Version(), GetAlgorithmParameter(), GetAlgorithmParameterTag(), GetChannels(), GetEntryByCoordinate(), GetEntryByIndex(), GetFileSize(), GetGridCorners(), GetHeaderKey(), GetIntensityByCoordinate(), GetIntensityByIndex(), GetParameters(), GetPixelsByCoordinate(), GetPixelsByIndex(), GetStdvByCoordinate(), GetStdvByIndex(), IndexToX(), IndexToY(), IsMaskedByCoordinate(), IsMaskedByIndex(), IsMultiColor(), IsOutlierByCoordinate(), IsOutlierByIndex(), put_FileName(), Read(), ReadHeader(), SetActiveDataGroup(), and XYToIndex().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCELDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCELDataCOM.cpp