Affymetrix Fusion SDK: affymetrix_calvin_io::DataGroupHeaderWriter Class Reference
affymetrix_calvin_io::DataGroupHeaderWriter Class Reference
#include <DataGroupHeaderWriter.h>
Public Member Functions
DataGroupHeaderWriter ()
~DataGroupHeaderWriter ()
void Write (std::ofstream &os, const DataGroupHeader &dc)
void UpdateDataSetPos (std::ofstream &os, u_int32_t pos) const
void UpdateNextDataGroupPos (std::ofstream &os, u_int32_t pos) const
Private Member Functions
void WriteDataSetPos (std::ofstream &os, u_int32_t pos)
void WriteNextDataGroupPos (std::ofstream &os, u_int32_t pos)
void WriteName (std::ofstream &os, const DataGroupHeader &dc) const
void WriteDataSetCnt (std::ofstream &os, const DataGroupHeader &dc) const
Private Attributes
u_int32_t dataSetPos
u_int32_t nextDataGroupPos
Detailed Description
Definition at line 34 of file DataGroupHeaderWriter.h.
Constructor & Destructor Documentation
DataGroupHeaderWriter::DataGroupHeaderWriter ()
Definition at line 26 of file DataGroupHeaderWriter.cpp.
References dataSetPos, and nextDataGroupPos.
affymetrix_calvin_io::DataGroupHeaderWriter::~DataGroupHeaderWriter () [inline]
Definition at line 45 of file DataGroupHeaderWriter.h.
Member Function Documentation
void DataGroupHeaderWriter::UpdateDataSetPos (std::ofstream & os, u_int32_t pos) const
Definition at line 46 of file DataGroupHeaderWriter.cpp.
References dataSetPos, and affymetrix_calvin_io::FileOutput::WriteUInt32().
Referenced by affymetrix_calvin_io::DataGroupWriter::WriteHeader().
void DataGroupHeaderWriter::UpdateNextDataGroupPos (std::ofstream & os, u_int32_t pos) const
Definition at line 62 of file DataGroupHeaderWriter.cpp.
References nextDataGroupPos, and affymetrix_calvin_io::FileOutput::WriteUInt32().
Referenced by affymetrix_calvin_io::DataGroupWriter::Close(), and affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos().
void DataGroupHeaderWriter::Write (std::ofstream & os, const DataGroupHeader & dc)
Definition at line 32 of file DataGroupHeaderWriter.cpp.
References WriteDataSetCnt(), WriteDataSetPos(), WriteName(), and WriteNextDataGroupPos().
Referenced by affymetrix_calvin_io::DataGroupWriter::WriteHeader().
void DataGroupHeaderWriter::WriteDataSetCnt (std::ofstream & os, const DataGroupHeader & dc) const [private]
Definition at line 77 of file DataGroupHeaderWriter.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
void DataGroupHeaderWriter::WriteDataSetPos (std::ofstream & os, u_int32_t pos) [private]
Definition at line 40 of file DataGroupHeaderWriter.cpp.
References dataSetPos, and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
void DataGroupHeaderWriter::WriteName (std::ofstream & os, const DataGroupHeader & dc) const [private]
Definition at line 72 of file DataGroupHeaderWriter.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetName(), and affymetrix_calvin_io::FileOutput::WriteString16().
Referenced by Write().
void DataGroupHeaderWriter::WriteNextDataGroupPos (std::ofstream & os, u_int32_t pos) [private]
Definition at line 56 of file DataGroupHeaderWriter.cpp.
References nextDataGroupPos, and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
Member Data Documentation
u_int32_t affymetrix_calvin_io::DataGroupHeaderWriter::dataSetPos [private]
Definition at line 39 of file DataGroupHeaderWriter.h.
Referenced by DataGroupHeaderWriter(), UpdateDataSetPos(), and WriteDataSetPos().
u_int32_t affymetrix_calvin_io::DataGroupHeaderWriter::nextDataGroupPos [private]
Definition at line 40 of file DataGroupHeaderWriter.h.
Referenced by DataGroupHeaderWriter(), UpdateNextDataGroupPos(), and WriteNextDataGroupPos().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DataGroupHeaderWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/DataGroupHeaderWriter.cpp