Affymetrix Fusion SDK: affxgrc::CGRCFileData Class Reference
affxgrc::CGRCFileData Class Reference
#include <GRCFileData.h>
Public Member Functions
CGRCFileData ()
~CGRCFileData ()
void SetFileName (const char *name)
const std::string & GetFileName () const
bool Read (affymetrix_grid_control::GridControlData &grid)
bool Exists ()
Protected Member Functions
bool IsReleaseFormat ()
bool ReadPreReleaseFormat (affymetrix_grid_control::GridControlData &grid)
bool ReadReleaseFormat (affymetrix_grid_control::GridControlData &grid)
Protected Attributes
std::string m_strFileName
int32_t m_Version
Detailed Description
This class holds the coordinates of those probes used by the GCAST algorithm.
Definition at line 52 of file GRCFileData.h.
Constructor & Destructor Documentation
CGRCFileData::CGRCFileData ()
Constructor
Definition at line 43 of file GRCFileData.cpp.
CGRCFileData::~CGRCFileData ()
Destructor
Definition at line 52 of file GRCFileData.cpp.
Member Function Documentation
bool CGRCFileData::Exists ()
Checks for the existance of a file.
Returns:
True if the file exists.
Definition at line 61 of file GRCFileData.cpp.
const std::string& affxgrc::CGRCFileData::GetFileName () const [inline]
Gets the file name.
Returns:
The full path to the GRC file.
Definition at line 97 of file GRCFileData.h.
References m_strFileName.
bool CGRCFileData::IsReleaseFormat () [protected]
Checks if the file is of a release format
Returns:
True if release format (not early access)
Definition at line 87 of file GRCFileData.cpp.
References GRC_MAGIC, GRC_VERSION, and ReadUInt8().
bool CGRCFileData::Read (affymetrix_grid_control::GridControlData & grid)
Reads the contents of the file.
Parameters:
grid The grid control data to fill from the GRC file.
Returns:
True if successful.
Definition at line 73 of file GRCFileData.cpp.
References affymetrix_grid_control::GridControlData::Clear().
bool CGRCFileData::ReadPreReleaseFormat (affymetrix_grid_control::GridControlData & grid) [protected]
Reads a pre-release (early access) format GRC file.
Parameters:
grid The grid control data to fill from the GRC file.
Returns:
True if successful
Definition at line 104 of file GRCFileData.cpp.
References affymetrix_grid_control::GridControlData::GetColumns(), affymetrix_grid_control::GridControlData::GetNumB1Probes(), affymetrix_grid_control::GridControlData::GetNumB2Probes(), affymetrix_grid_control::GridControlData::GetNumNSProbes(), affymetrix_grid_control::GridControlData::GetRows(), ReadInt16_I(), ReadInt32_I(), affymetrix_grid_control::GridControlData::ResizeB1(), affymetrix_grid_control::GridControlData::ResizeB2(), affymetrix_grid_control::GridControlData::ResizeNS(), affymetrix_grid_control::GridControlData::SetB1(), affymetrix_grid_control::GridControlData::SetB2(), affymetrix_grid_control::GridControlData::SetColumns(), affymetrix_grid_control::GridControlData::SetNS(), affymetrix_grid_control::GridControlData::SetRows(), affymetrix_grid_control::_FeatureCoordinate::x, and affymetrix_grid_control::_FeatureCoordinate::y.
bool CGRCFileData::ReadReleaseFormat (affymetrix_grid_control::GridControlData & grid) [protected]
Reads a release format GRC file.
Parameters:
grid The grid control data to fill from the GRC file.
Returns:
True if successful
Definition at line 183 of file GRCFileData.cpp.
References affymetrix_grid_control::GridControlData::GetNumB1Probes(), affymetrix_grid_control::GridControlData::GetNumB2Probes(), affymetrix_grid_control::GridControlData::GetNumNSProbes(), ReadInt32_N(), ReadUInt16_N(), ReadUInt8(), affymetrix_grid_control::GridControlData::ResizeB1(), affymetrix_grid_control::GridControlData::ResizeB2(), affymetrix_grid_control::GridControlData::ResizeNS(), affymetrix_grid_control::GridControlData::SetB1(), affymetrix_grid_control::GridControlData::SetB2(), affymetrix_grid_control::GridControlData::SetColumns(), affymetrix_grid_control::GridControlData::SetNS(), affymetrix_grid_control::GridControlData::SetRows(), affymetrix_grid_control::_FeatureCoordinate::x, and affymetrix_grid_control::_FeatureCoordinate::y.
void affxgrc::CGRCFileData::SetFileName (const char * name) [inline]
Sets the file name.
Parameters:
name The full path to the GRC file.
Definition at line 92 of file GRCFileData.h.
References m_strFileName.
Member Data Documentation
std::string affxgrc::CGRCFileData::m_strFileName [protected]
The name of the GRC file
Definition at line 63 of file GRCFileData.h.
Referenced by GetFileName(), and SetFileName().
int32_t affxgrc::CGRCFileData::m_Version [protected]
The version number of the file
Definition at line 66 of file GRCFileData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/GRCFileData.h
C:/f112/affy/sdk/file/GRCFileData.cpp