Affymetrix Fusion SDK: CFusionCDFProbeInformationCOM Class Reference
CFusionCDFProbeInformationCOM Class Reference
#include <FusionCDFProbeInformationCOM.h>
Public Member Functions
CFusionCDFProbeInformationCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_fusion_io::FusionCDFProbeInformation & Probe ()
STDMETHOD() get_ListIndex (int *pVal)
STDMETHOD() get_Expos (int *pVal)
STDMETHOD() get_X (int *pVal)
STDMETHOD() get_Y (int *pVal)
STDMETHOD() get_PBase (CHAR *pVal)
STDMETHOD() get_TBase (CHAR *pVal)
STDMETHOD() get_ProbeLength (USHORT *pVal)
STDMETHOD() get_ProbeGrouping (USHORT *pVal)
Private Attributes
affymetrix_fusion_io::FusionCDFProbeInformation probe
Detailed Description
Definition at line 29 of file FusionCDFProbeInformationCOM.h.
Constructor & Destructor Documentation
CFusionCDFProbeInformationCOM::CFusionCDFProbeInformationCOM () [inline]
Definition at line 36 of file FusionCDFProbeInformationCOM.h.
Member Function Documentation
HRESULT CFusionCDFProbeInformationCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionCDFProbeInformationCOM.h.
void CFusionCDFProbeInformationCOM::FinalRelease () [inline]
Definition at line 60 of file FusionCDFProbeInformationCOM.h.
STDMETHODIMP CFusionCDFProbeInformationCOM::get_Expos (int * pVal)
Definition at line 47 of file FusionCDFProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetExpos(), and probe.
STDMETHODIMP CFusionCDFProbeInformationCOM::get_ListIndex (int * pVal)
Definition at line 41 of file FusionCDFProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetListIndex(), and probe.
STDMETHODIMP CFusionCDFProbeInformationCOM::get_PBase (CHAR * pVal)
Definition at line 65 of file FusionCDFProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetPBase(), and probe.
STDMETHODIMP CFusionCDFProbeInformationCOM::get_ProbeGrouping (USHORT * pVal)
Definition at line 83 of file FusionCDFProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetProbeGrouping(), and probe.
STDMETHODIMP CFusionCDFProbeInformationCOM::get_ProbeLength (USHORT * pVal)
Definition at line 77 of file FusionCDFProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetProbeLength(), and probe.
STDMETHODIMP CFusionCDFProbeInformationCOM::get_TBase (CHAR * pVal)
Definition at line 71 of file FusionCDFProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetTBase(), and probe.
STDMETHODIMP CFusionCDFProbeInformationCOM::get_X (int * pVal)
Definition at line 53 of file FusionCDFProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetX(), and probe.
STDMETHODIMP CFusionCDFProbeInformationCOM::get_Y (int * pVal)
Definition at line 59 of file FusionCDFProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::GetY(), and probe.
STDMETHODIMP CFusionCDFProbeInformationCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 26 of file FusionCDFProbeInformationCOM.cpp.
affymetrix_fusion_io::FusionCDFProbeInformation& CFusionCDFProbeInformationCOM::Probe () [inline]
Definition at line 68 of file FusionCDFProbeInformationCOM.h.
Referenced by CFusionCDFProbeGroupInformationCOM::GetCell().
Member Data Documentation
affymetrix_fusion_io::FusionCDFProbeInformation CFusionCDFProbeInformationCOM::probe [private]
Definition at line 65 of file FusionCDFProbeInformationCOM.h.
Referenced by get_Expos(), get_ListIndex(), get_PBase(), get_ProbeGrouping(), get_ProbeLength(), get_TBase(), get_X(), and get_Y().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFProbeInformationCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFProbeInformationCOM.cpp