Affymetrix Fusion SDK: CFusionCHPHeaderCOM Class Reference
CFusionCHPHeaderCOM Class Reference
#include <FusionCHPHeaderCOM.h>
Public Member Functions
CFusionCHPHeaderCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
void SetHeader (affymetrix_fusion_io::FusionCHPHeader *h)
STDMETHOD() get_Cols (int *pVal)
STDMETHOD() get_Rows (int *pVal)
STDMETHOD() get_NumProbeSets (int *pVal)
STDMETHOD() get_AssayType (AssayType *pVal)
STDMETHOD() get_ChipType (BSTR *pVal)
STDMETHOD() get_AlgName (BSTR *pVal)
STDMETHOD() get_AlgVersion (BSTR *pVal)
STDMETHOD() get_AlgorithmParameters (VARIANT *pVal)
STDMETHOD() get_AlgorithmParameterCount (int *pVal)
STDMETHOD() get_SummaryParameters (VARIANT *pVal)
STDMETHOD() get_SummaryParameterCount (int *pVal)
STDMETHOD() get_ParentCellFile (BSTR *pVal)
STDMETHOD() get_ProgID (BSTR *pVal)
STDMETHOD() GetAlgorithmParameter (BSTR tag, BSTR *pVal)
STDMETHOD() GetSummaryParameter (BSTR tag, BSTR *pVal)
STDMETHOD() GetAlgorithmParameterName (int index, BSTR *pVal)
STDMETHOD() GetSummaryParameterName (int index, BSTR *pVal)
STDMETHOD() Clear (void)
STDMETHOD() get_BackgroundZoneInfo (IBackgroundZoneInfo **pVal)
STDMETHOD() GetBackgroundZones (VARIANT *zones)
STDMETHOD() GetBackgroundZone (int x, int y, IBackgroundZoneType **pVal)
Private Attributes
affymetrix_fusion_io::FusionCHPHeader * header
std::vector< std::wstring > sumParamNames
std::vector< std::wstring > algParamNames
Detailed Description
Definition at line 31 of file FusionCHPHeaderCOM.h.
Constructor & Destructor Documentation
CFusionCHPHeaderCOM::CFusionCHPHeaderCOM () [inline]
Definition at line 38 of file FusionCHPHeaderCOM.h.
Member Function Documentation
STDMETHODIMP CFusionCHPHeaderCOM::Clear (void)
Definition at line 212 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::Clear(), and header.
HRESULT CFusionCHPHeaderCOM::FinalConstruct () [inline]
Definition at line 58 of file FusionCHPHeaderCOM.h.
void CFusionCHPHeaderCOM::FinalRelease () [inline]
Definition at line 63 of file FusionCHPHeaderCOM.h.
STDMETHODIMP CFusionCHPHeaderCOM::get_AlgName (BSTR * pVal)
Definition at line 76 of file FusionCHPHeaderCOM.cpp.
References COMStringUtils::ConvertWString(), affymetrix_fusion_io::FusionCHPHeader::GetAlgName(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_AlgorithmParameterCount (int * pVal)
Definition at line 114 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::AlgorithmParameterCount(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_AlgorithmParameters (VARIANT * pVal)
Definition at line 88 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::AlgorithmParameters(), header, and CFusionTagValuePairTypeCOM::SetParam().
STDMETHODIMP CFusionCHPHeaderCOM::get_AlgVersion (BSTR * pVal)
Definition at line 82 of file FusionCHPHeaderCOM.cpp.
References COMStringUtils::ConvertWString(), affymetrix_fusion_io::FusionCHPHeader::GetAlgVersion(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_AssayType (AssayType * pVal)
Definition at line 64 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::GetAssayType(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_BackgroundZoneInfo (IBackgroundZoneInfo ** pVal)
Definition at line 218 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::GetBackgroundZoneInfo(), header, and CBackgroundZoneInfoCOM::Zone().
STDMETHODIMP CFusionCHPHeaderCOM::get_ChipType (BSTR * pVal)
Definition at line 70 of file FusionCHPHeaderCOM.cpp.
References COMStringUtils::ConvertWString(), affymetrix_fusion_io::FusionCHPHeader::GetChipType(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_Cols (int * pVal)
Definition at line 46 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::GetCols(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_NumProbeSets (int * pVal)
Definition at line 58 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::GetNumProbeSets(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_ParentCellFile (BSTR * pVal)
Definition at line 152 of file FusionCHPHeaderCOM.cpp.
References COMStringUtils::ConvertWString(), affymetrix_fusion_io::FusionCHPHeader::GetParentCellFile(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_ProgID (BSTR * pVal)
Definition at line 158 of file FusionCHPHeaderCOM.cpp.
References COMStringUtils::ConvertWString(), affymetrix_fusion_io::FusionCHPHeader::GetProgID(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_Rows (int * pVal)
Definition at line 52 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::GetRows(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::get_SummaryParameterCount (int * pVal)
Definition at line 120 of file FusionCHPHeaderCOM.cpp.
References header, and affymetrix_fusion_io::FusionCHPHeader::SummaryParameterCount().
STDMETHODIMP CFusionCHPHeaderCOM::get_SummaryParameters (VARIANT * pVal)
Definition at line 126 of file FusionCHPHeaderCOM.cpp.
References header, CFusionTagValuePairTypeCOM::SetParam(), and affymetrix_fusion_io::FusionCHPHeader::SummaryParameters().
STDMETHODIMP CFusionCHPHeaderCOM::GetAlgorithmParameter (BSTR tag, BSTR * pVal)
Definition at line 164 of file FusionCHPHeaderCOM.cpp.
References COMStringUtils::ConvertWString(), affymetrix_fusion_io::FusionCHPHeader::GetAlgorithmParameter(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::GetAlgorithmParameterName (int index, BSTR * pVal)
Definition at line 176 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::AlgorithmParameters(), algParamNames, COMStringUtils::ConvertWString(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::GetBackgroundZone (int x, int y, IBackgroundZoneType ** pVal)
Definition at line 254 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::GetBackgroundZone(), header, and CBackgroundZoneTypeCOM::SetBg().
STDMETHODIMP CFusionCHPHeaderCOM::GetBackgroundZones (VARIANT * zones)
Definition at line 228 of file FusionCHPHeaderCOM.cpp.
References affymetrix_fusion_io::FusionCHPHeader::GetBackgroundZones(), header, and CBackgroundZoneTypeCOM::SetBg().
STDMETHODIMP CFusionCHPHeaderCOM::GetSummaryParameter (BSTR tag, BSTR * pVal)
Definition at line 170 of file FusionCHPHeaderCOM.cpp.
References COMStringUtils::ConvertWString(), affymetrix_fusion_io::FusionCHPHeader::GetSummaryParameter(), and header.
STDMETHODIMP CFusionCHPHeaderCOM::GetSummaryParameterName (int index, BSTR * pVal)
Definition at line 194 of file FusionCHPHeaderCOM.cpp.
References COMStringUtils::ConvertWString(), header, affymetrix_fusion_io::FusionCHPHeader::SummaryParameters(), and sumParamNames.
STDMETHODIMP CFusionCHPHeaderCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 31 of file FusionCHPHeaderCOM.cpp.
void CFusionCHPHeaderCOM::SetHeader (affymetrix_fusion_io::FusionCHPHeader * h) [inline]
Definition at line 73 of file FusionCHPHeaderCOM.h.
Referenced by CFusionCHPLegacyDataCOM::GetHeader().
Member Data Documentation
std::vector<std::wstring> CFusionCHPHeaderCOM::algParamNames [private]
Definition at line 70 of file FusionCHPHeaderCOM.h.
Referenced by GetAlgorithmParameterName().
affymetrix_fusion_io::FusionCHPHeader* CFusionCHPHeaderCOM::header [private]
Definition at line 68 of file FusionCHPHeaderCOM.h.
Referenced by Clear(), get_AlgName(), get_AlgorithmParameterCount(), get_AlgorithmParameters(), get_AlgVersion(), get_AssayType(), get_BackgroundZoneInfo(), get_ChipType(), get_Cols(), get_NumProbeSets(), get_ParentCellFile(), get_ProgID(), get_Rows(), get_SummaryParameterCount(), get_SummaryParameters(), GetAlgorithmParameter(), GetAlgorithmParameterName(), GetBackgroundZone(), GetBackgroundZones(), GetSummaryParameter(), and GetSummaryParameterName().
std::vector<std::wstring> CFusionCHPHeaderCOM::sumParamNames [private]
Definition at line 69 of file FusionCHPHeaderCOM.h.
Referenced by GetSummaryParameterName().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPHeaderCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPHeaderCOM.cpp