Affymetrix Fusion SDK: affymetrix_calvin_io::DataGroupHeader Class Reference
affymetrix_calvin_io::DataGroupHeader Class Reference
#include <DataGroupHeader.h>
Public Member Functions
DataGroupHeader ()
DataGroupHeader (const std::wstring &n)
~DataGroupHeader ()
void Clear ()
void SetName (const std::wstring &p)
std::wstring GetName () const
int32_t GetDataSetCnt () const
void AddDataSetHdr (const DataSetHeader &p)
void ReplaceDataSetHdr (const DataSetHeader &p)
DataSetHeader & GetDataSet (int32_t index)
const DataSetHeader & GetDataSetConst (int32_t index) const
void GetDataSetIterators (DataSetHdrIt &begin, DataSetHdrIt &end)
void SetHeaderStartFilePos (u_int32_t pos)
u_int32_t GetHeaderStartFilePos () const
void SetDataSetPos (u_int32_t pos)
u_int32_t GetDataSetPos () const
void SetNextGroupPos (u_int32_t pos)
u_int32_t GetNextGroupPos () const
affymetrix_calvin_io::DataSetHeader * FindDataSetHeader (const std::wstring &dataSetName)
Private Attributes
std::wstring name
u_int32_t dataSetPos
u_int32_t nextGrpPos
u_int32_t headerStartFilePos
DataSetHdrVector dataSetHdrs
Detailed Description
Definition at line 38 of file DataGroupHeader.h.
Constructor & Destructor Documentation
DataGroupHeader::DataGroupHeader ()
Definition at line 28 of file DataGroupHeader.cpp.
References dataSetPos, and nextGrpPos.
DataGroupHeader::DataGroupHeader (const std::wstring & n)
Definition at line 33 of file DataGroupHeader.cpp.
References dataSetPos, headerStartFilePos, name, and nextGrpPos.
DataGroupHeader::~DataGroupHeader ()
Definition at line 41 of file DataGroupHeader.cpp.
References Clear().
Member Function Documentation
void DataGroupHeader::AddDataSetHdr (const DataSetHeader & p)
Definition at line 69 of file DataGroupHeader.cpp.
References dataSetHdrs.
Referenced by affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataGroupHdr(), affymetrix_calvin_io::CDFData::CreateContentsGroup(), affymetrix_calvin_io::DATData::InsertDataSetHeader(), affymetrix_calvin_io::CelFileData::InsertDataSetHeader(), affymetrix_calvin_io::CDFFileWriter::OpenDataGroup(), affymetrix_calvin_io::CDFCntrlFileWriter::OpenDataGroup(), affymetrix_calvin_io::DataSetHeaderReader::ReadAll(), affymetrix_calvin_io::DataSetHeaderReader::ReadAllMinimumInfo(), affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::SetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetForceCnt(), affymetrix_calvin_io::CHPData::SetOrigCnt(), and OutputMessageStream::Write().
void DataGroupHeader::Clear ()
Definition at line 46 of file DataGroupHeader.cpp.
References dataSetHdrs, dataSetPos, name, and nextGrpPos.
Referenced by ~DataGroupHeader().
DataSetHeader * DataGroupHeader::FindDataSetHeader (const std::wstring & dataSetName)
Definition at line 105 of file DataGroupHeader.cpp.
References GetDataSetIterators().
Referenced by affymetrix_calvin_io::GenericData::FindDataSetHeader(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), and affymetrix_calvin_io::MMDATFileWriter::MMDATFileWriter().
DataSetHeader & DataGroupHeader::GetDataSet (int32_t index)
Definition at line 86 of file DataGroupHeader.cpp.
References dataSetHdrs.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::DataGroupWriter::CreateWriters(), affymetrix_calvin_io::GenericData::FindDataSetHeader(), affymetrix_calvin_io::GenericFileUpdater::FindLastDataSetHeader(), affymetrix_calvin_io::CHPData::GetBackgroundZoneCnt(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetForceCnt(), affymetrix_calvin_io::DATFileUpdater::GetGridDataSetOffset(), affymetrix_calvin_io::CHPData::GetOrigCnt(), affymetrix_calvin_io::DATFileUpdater::GetSubGridDataSetOffset(), affymetrix_calvin_io::CHPTilingData::GetTilingSequenceEntryCount(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), affymetrix_calvin_io::DATData::UpdateDataSetRowCount(), affymetrix_calvin_io::CelFileData::UpdateDataSetRowCount(), and affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroup().
int32_t DataGroupHeader::GetDataSetCnt () const
Get the data set count
Definition at line 64 of file DataGroupHeader.cpp.
References dataSetHdrs.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::DataGroupWriter::CreateWriters(), affymetrix_calvin_io::GenericData::DataSetCnt(), affymetrix_calvin_io::GenericFileUpdater::FindLastDataSetHeader(), affymetrix_calvin_io::DataGroupReader::GetDataSetCnt(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), affymetrix_calvin_io::DATFileUpdater::GetGridDataSetOffset(), affymetrix_calvin_io::DATFileUpdater::GetSubGridDataSetOffset(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup(), affymetrix_calvin_io::DATData::UpdateDataSetRowCount(), affymetrix_calvin_io::CelFileData::UpdateDataSetRowCount(), and affymetrix_calvin_io::DataGroupHeaderWriter::WriteDataSetCnt().
const DataSetHeader & DataGroupHeader::GetDataSetConst (int32_t index) const
Definition at line 91 of file DataGroupHeader.cpp.
References dataSetHdrs.
Referenced by affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup().
void DataGroupHeader::GetDataSetIterators (DataSetHdrIt & begin, DataSetHdrIt & end)
Definition at line 96 of file DataGroupHeader.cpp.
References dataSetHdrs.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataGroupHdr(), affymetrix_calvin_io::GenericData::DataSetNames(), and FindDataSetHeader().
u_int32_t affymetrix_calvin_io::DataGroupHeader::GetDataSetPos () const [inline]
Get the file position of the DataSet header.
Definition at line 97 of file DataGroupHeader.h.
References dataSetPos.
Referenced by affymetrix_calvin_io::DataSetHeaderReader::ReadAll(), and affymetrix_calvin_io::DataSetHeaderReader::ReadAllMinimumInfo().
u_int32_t affymetrix_calvin_io::DataGroupHeader::GetHeaderStartFilePos () const [inline]
Get the file position of the start of the DataSet header.
Definition at line 90 of file DataGroupHeader.h.
References headerStartFilePos.
Referenced by affymetrix_calvin_io::DataGroupHeaderUpdater::SeekNextDataGrpPosition().
std::wstring DataGroupHeader::GetName () const
Definition at line 59 of file DataGroupHeader.cpp.
References name.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupHeader(), affymetrix_calvin_io::CHPMultiDataData::GetDataGroupIndex(), affymetrix_calvin_io::DataGroupWriter::GetDataGroupName(), affymetrix_calvin_io::DataGroupReader::GetDataGroupName(), affymetrix_calvin_io::DataGroupWriter::GetName(), affymetrix_calvin_io::CDFProbeSetInformation::GetName(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), ReplaceDataSetHdr(), and affymetrix_calvin_io::DataGroupHeaderWriter::WriteName().
u_int32_t affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos () const [inline]
Get the file position of the next DataGroup header.
Definition at line 101 of file DataGroupHeader.h.
References nextGrpPos.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::CDFData::GetProbeSetInformation(), affymetrix_calvin_io::CDFData::GetQCProbeSetInformation(), affymetrix_calvin_io::CDFData::PrepareForSequentialAccess(), affymetrix_calvin_io::DataGroupHeaderReader::Read(), and affymetrix_calvin_io::DataGroupHeaderReader::ReadMinimumInfo().
void DataGroupHeader::ReplaceDataSetHdr (const DataSetHeader & p)
Replace a data set header with a new data set header of the same name.
Parameters:
new data set header with the same name as the header it replaces.
Definition at line 74 of file DataGroupHeader.cpp.
References dataSetHdrs, affymetrix_calvin_io::DataSetHeader::GetName(), and GetName().
void affymetrix_calvin_io::DataGroupHeader::SetDataSetPos (u_int32_t pos) [inline]
Set the file position of the DataSet header. The value set here is not necessarily the value written to the file.
Definition at line 95 of file DataGroupHeader.h.
References dataSetPos.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::FileHeaderUpdater::AppendDataGroupHeader(), and affymetrix_calvin_io::DataGroupHeaderReader::ReadFirstDataSetFilePos().
void affymetrix_calvin_io::DataGroupHeader::SetHeaderStartFilePos (u_int32_t pos) [inline]
Set the file position of the start of the DataSet header. The value set here is not written to the file.
Definition at line 87 of file DataGroupHeader.h.
References headerStartFilePos.
Referenced by affymetrix_calvin_io::FileHeaderUpdater::AppendDataGroupHeader(), and affymetrix_calvin_io::DataGroupHeaderReader::ReadDataGroupStartFilePos().
void DataGroupHeader::SetName (const std::wstring & p)
Definition at line 54 of file DataGroupHeader.cpp.
References name.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataGroupHdr(), affymetrix_calvin_io::DataGroupHeaderReader::ReadDataGroupName(), and OutputMessageStream::Write().
void affymetrix_calvin_io::DataGroupHeader::SetNextGroupPos (u_int32_t pos) [inline]
Set the file position of the next DataGroup header.
Definition at line 99 of file DataGroupHeader.h.
References nextGrpPos.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), and affymetrix_calvin_io::DataGroupHeaderReader::ReadNextDataGroupFilePos().
Member Data Documentation
DataSetHdrVector affymetrix_calvin_io::DataGroupHeader::dataSetHdrs [private]
data dataSets in this dataGroup
Definition at line 57 of file DataGroupHeader.h.
Referenced by AddDataSetHdr(), Clear(), GetDataSet(), GetDataSetCnt(), GetDataSetConst(), GetDataSetIterators(), and ReplaceDataSetHdr().
u_int32_t affymetrix_calvin_io::DataGroupHeader::dataSetPos [private]
file position of the 1st data dataSet
Definition at line 51 of file DataGroupHeader.h.
Referenced by Clear(), DataGroupHeader(), GetDataSetPos(), and SetDataSetPos().
u_int32_t affymetrix_calvin_io::DataGroupHeader::headerStartFilePos [private]
file position of the start of the data group header
Definition at line 55 of file DataGroupHeader.h.
Referenced by DataGroupHeader(), GetHeaderStartFilePos(), and SetHeaderStartFilePos().
std::wstring affymetrix_calvin_io::DataGroupHeader::name [private]
data dataGroup name
Definition at line 49 of file DataGroupHeader.h.
Referenced by Clear(), DataGroupHeader(), GetName(), and SetName().
u_int32_t affymetrix_calvin_io::DataGroupHeader::nextGrpPos [private]
file position of the next dataGroup
Definition at line 53 of file DataGroupHeader.h.
Referenced by Clear(), DataGroupHeader(), GetNextGroupPos(), and SetNextGroupPos().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/DataGroupHeader.h
C:/f112/affy/sdk/calvin_files/data/src/DataGroupHeader.cpp