Affymetrix Fusion SDK: affxcdf::CCDFProbeSetNames Class Reference
affxcdf::CCDFProbeSetNames Class Reference
#include <CDFFileData.h>
Public Member Functions
CCDFProbeSetNames ()
~CCDFProbeSetNames ()
void Clear ()
std::string GetName (int index) const
Protected Member Functions
void Resize (int size)
void SetName (int index, std::string name)
Protected Attributes
std::vector< std::string > m_ProbeSetNames
Friends
class CCDFFileData
Detailed Description
This class provides storage for the list of probe set names.
Definition at line 607 of file CDFFileData.h.
Constructor & Destructor Documentation
CCDFProbeSetNames::CCDFProbeSetNames ()
Constructor
Definition at line 240 of file CDFFileData.cpp.
CCDFProbeSetNames::~CCDFProbeSetNames ()
Destructor
Definition at line 246 of file CDFFileData.cpp.
References Clear().
Member Function Documentation
void CCDFProbeSetNames::Clear (void)
Deallocates memory used by the class.
Definition at line 253 of file CDFFileData.cpp.
References m_ProbeSetNames.
Referenced by affxcdf::CCDFFileData::Close(), and ~CCDFProbeSetNames().
std::string CCDFProbeSetNames::GetName (int index) const
Gets the probe set name.
Parameters:
index The zero-based index to the probe set name of interest.
Returns:
The name of the probe set.
Definition at line 260 of file CDFFileData.cpp.
References m_ProbeSetNames.
Referenced by affxcdf::CCDFFileData::GetProbeSetName().
void CCDFProbeSetNames::Resize (int size) [protected]
Resizes the probe set name array.
Definition at line 267 of file CDFFileData.cpp.
References m_ProbeSetNames.
Referenced by affxcdf::CCDFFileData::ReadTextFormat().
void CCDFProbeSetNames::SetName (int index, std::string name) [protected]
Stores the name of the probe set in the internal array.
Definition at line 274 of file CDFFileData.cpp.
References m_ProbeSetNames.
Referenced by affxcdf::CCDFFileData::ReadTextFormat().
Friends And Related Function Documentation
friend class CCDFFileData [friend]
Friend to the top level class.
Definition at line 611 of file CDFFileData.h.
Member Data Documentation
std::vector<std::string> affxcdf::CCDFProbeSetNames::m_ProbeSetNames [protected]
Array of probe set names, used if not memory mapping.
Definition at line 625 of file CDFFileData.h.
Referenced by Clear(), GetName(), Resize(), and SetName().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CDFFileData.h
C:/f112/affy/sdk/file/CDFFileData.cpp