Affymetrix Fusion SDK: affymetrix_calvin_io::SAXArrayHandlers Class Reference
affymetrix_calvin_io::SAXArrayHandlers Class Reference
#include <SAXArrayHandlers.h>
Public Member Functions
SAXArrayHandlers (affymetrix_calvin_array::ArrayData *data, bool headerOnly=false)
~SAXArrayHandlers ()
void startDocument ()
void endDocument ()
void characters (const XMLCh *const chars, const XMLSize_t length)
void startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList &attributes)
void endElement (const XMLCh *const name)
const
affymetrix_calvin_utilities::AffymetrixGuidType & DataTypeIdentifier () const
std::wstring FileVersionNumber () const
Private Member Functions
void StoreArrayFileAttributes (std::map< std::wstring, std::wstring > &attributes)
void StorePhysicalArrayElementAttributes (std::map< std::wstring, std::wstring > &attributes)
void StorePhysicalArrayAttribute (std::map< std::wstring, std::wstring > &attributes)
void StoreUserAttribute (std::map< std::wstring, std::wstring > &attributes)
void StoreUserAttributeControl (std::map< std::wstring, std::wstring > &attributes)
void MoveCurrentElementBack (const XMLCh *const name)
bool MoveCurrentElementForward (const XMLCh *const name)
Private Attributes
affymetrix_calvin_array::ArrayData * arrayData
bool readHeaderOnly
ArrayFileElements currentElement
std::wstring fileVersionNumber
affymetrix_calvin_utilities::AffymetrixGuidType dataTypeIdentifier
Detailed Description
This class provides the SAX handlers for reading calvin array files.
Definition at line 181 of file SAXArrayHandlers.h.
Constructor & Destructor Documentation
SAXArrayHandlers::SAXArrayHandlers (affymetrix_calvin_array::ArrayData * data, bool headerOnly = false)
Constructor
Parameters:
data The array data.
headerOnly Flag to indicate that the header line should only be read.
Definition at line 103 of file SAXArrayHandlers.cpp.
SAXArrayHandlers::~SAXArrayHandlers ()
Destructor
Definition at line 113 of file SAXArrayHandlers.cpp.
Member Function Documentation
void SAXArrayHandlers::characters (const XMLCh *const chars, const XMLSize_t length)
Receive notification of character data inside an element.
Parameters:
chars The character data.
length The length of the character string.
Definition at line 270 of file SAXArrayHandlers.cpp.
References arrayData, affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlMultiValues(), currentElement, affymetrix_calvin_io::PHYSICAL_ARRAY_ATTRIBUTES, affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), affymetrix_calvin_io::USER_ATTRIBUTES_ATTRIBUTE_VALUE, affymetrix_calvin_array::ArrayData::UserAttributes(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ValueType(), WideToFloat(), WideToInt(), and XMLChToWString().
const affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_io::SAXArrayHandlers::DataTypeIdentifier () const [inline]
The identifier of the type of data stored in the file.
Returns:
The identifier of the type of data.
Definition at line 282 of file SAXArrayHandlers.h.
References dataTypeIdentifier.
void SAXArrayHandlers::endDocument ()
Called at the end of the document
Definition at line 127 of file SAXArrayHandlers.cpp.
void SAXArrayHandlers::endElement (const XMLCh *const name)
Called at the end of each element.
Parameters:
name The name of the element.
Definition at line 134 of file SAXArrayHandlers.cpp.
References MoveCurrentElementBack().
std::wstring affymetrix_calvin_io::SAXArrayHandlers::FileVersionNumber () const [inline]
The files version number.
Returns:
The file version.
Definition at line 288 of file SAXArrayHandlers.h.
References fileVersionNumber.
Referenced by affymetrix_calvin_io::ArrayFileReader::Read().
void SAXArrayHandlers::MoveCurrentElementBack (const XMLCh *const name) [private]
Modifies the state machine given the end of an element.
Parameters:
name The name of the element.
Definition at line 142 of file SAXArrayHandlers.cpp.
References affymetrix_calvin_io::ARRAY_FILE, currentElement, affymetrix_calvin_io::PHYSICAL_ARRAY, PHYSICAL_ARRAY_ATTRIBUTE_ELEMENT, affymetrix_calvin_io::PHYSICAL_ARRAY_ATTRIBUTES, PHYSICAL_ARRAY_ELEMENT, affymetrix_calvin_io::PHYSICAL_ARRAYS, PHYSICAL_ARRAYS_ELEMENT, affymetrix_calvin_io::USER_ATTRIBUTES, affymetrix_calvin_io::USER_ATTRIBUTES_ATTRIBUTE, affymetrix_calvin_io::USER_ATTRIBUTES_ATTRIBUTE_CONTROL, USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT, affymetrix_calvin_io::USER_ATTRIBUTES_ATTRIBUTE_VALUE, USER_ATTRIBUTES_ATTRIBUTE_VALUE_ELEMENT, and USER_ATTRIBUTES_ELEMENT.
Referenced by endElement().
bool SAXArrayHandlers::MoveCurrentElementForward (const XMLCh *const name) [private]
Modifies the state machine given the start of an element.
Parameters:
name The name of the element.
Returns:
True is a valid element was found.
Definition at line 172 of file SAXArrayHandlers.cpp.
References affymetrix_calvin_io::ARRAY_FILE, ARRAY_FILE_ELEMENT, currentElement, affymetrix_calvin_io::PHYSICAL_ARRAY, PHYSICAL_ARRAY_ATTRIBUTE_ELEMENT, affymetrix_calvin_io::PHYSICAL_ARRAY_ATTRIBUTES, PHYSICAL_ARRAY_ELEMENT, affymetrix_calvin_io::PHYSICAL_ARRAYS, PHYSICAL_ARRAYS_ELEMENT, affymetrix_calvin_io::USER_ATTRIBUTES, affymetrix_calvin_io::USER_ATTRIBUTES_ATTRIBUTE, affymetrix_calvin_io::USER_ATTRIBUTES_ATTRIBUTE_CONTROL, USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT, affymetrix_calvin_io::USER_ATTRIBUTES_ATTRIBUTE_VALUE, USER_ATTRIBUTES_ATTRIBUTE_VALUE_ELEMENT, and USER_ATTRIBUTES_ELEMENT.
void SAXArrayHandlers::startDocument ()
Called at the start of the document
Definition at line 120 of file SAXArrayHandlers.cpp.
void affymetrix_calvin_io::SAXArrayHandlers::startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList & attributes)
Called at the start of each element.
Parameters:
name The name of the element.
attributes The attributes of the element.
void SAXArrayHandlers::StoreArrayFileAttributes (std::map< std::wstring, std::wstring > & attributes) [private]
Stores the attributes from the array file element.
Parameters:
attributes The name/value attributes.
Definition at line 476 of file SAXArrayHandlers.cpp.
References ARRAY_FILE_ELEMENT_CREATE_DATE_TIME_ATTRIBUTE, ARRAY_FILE_ELEMENT_CREATED_BY_ATTRIBUTE, ARRAY_FILE_ELEMENT_CREATED_STEP_ATTRIBUTE, ARRAY_FILE_ELEMENT_ID_ATTRIBUTE, ARRAY_FILE_ELEMENT_PROJECT_ATTRIBUTE, ARRAY_FILE_ELEMENT_TYPE_ATTRIBUTE, ARRAY_FILE_ELEMENT_VERSION_ATTRIBUTE, arrayData, affymetrix_calvin_array::ArrayData::ArraySetFileIdentifier(), affymetrix_calvin_array::ArrayData::CreatedBy(), affymetrix_calvin_array::ArrayData::CreatedStep(), affymetrix_calvin_array::CreateStepFromString(), affymetrix_calvin_array::ArrayData::CreationDateTime(), affymetrix_calvin_array::ArrayData::DataTypeIdentifier(), fileVersionNumber, and affymetrix_calvin_array::ArrayData::InitialProject().
void SAXArrayHandlers::StorePhysicalArrayAttribute (std::map< std::wstring, std::wstring > & attributes) [private]
Stores an attribute from the physical array attribute element.
Parameters:
attributes The name/value attributes.
Definition at line 385 of file SAXArrayHandlers.cpp.
References arrayData, PHYSICAL_ARRAY_ATTRIBUTE_ELEMENT_NAME_ATTRIBUTE, PHYSICAL_ARRAY_ATTRIBUTE_ELEMENT_VALUE_ATTRIBUTE, and affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes().
void SAXArrayHandlers::StorePhysicalArrayElementAttributes (std::map< std::wstring, std::wstring > & attributes) [private]
Stores the attrobites from the physical array element.
Parameters:
attributes The name/value attributes.
Definition at line 398 of file SAXArrayHandlers.cpp.
References ARRAY_FILE_ELEMENT_CREATED_STEP_ATTRIBUTE, arrayData, affymetrix_calvin_array::CreateStepFromString(), affymetrix_calvin_array::MediaFromString(), affymetrix_calvin_array::PATAssignmentMethodFromString(), PHYSICAL_ARRAY_ELEMENT_BARCODE_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_COL_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_COMMENT_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_CREATED_BY_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_CREATION_DATE_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_ID_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_LIB_PACKAGE_NAME_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_MASTERFILE_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_MASTERFILE_GUID_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_MEDIA_FILE_GUID_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_MEDIA_FILE_NAME_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_NAME_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_PAT_ASSIGNMENT_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_ROW_ATTRIBUTE, PHYSICAL_ARRAY_ELEMENT_TYPE_ATTRIBUTE, affymetrix_calvin_array::ArrayData::PhysicalArraysAttributes(), and WideToInt().
void affymetrix_calvin_io::SAXArrayHandlers::StoreUserAttribute (std::map< std::wstring, std::wstring > & attributes) [private]
Stores an attribute from the user attribute element.
Parameters:
attributes The name/value attributes.
void affymetrix_calvin_io::SAXArrayHandlers::StoreUserAttributeControl (std::map< std::wstring, std::wstring > & attributes) [private]
Stores a control value from the user attribute element.
Parameters:
attributes The name/value attributes.
Member Data Documentation
affymetrix_calvin_array::ArrayData* affymetrix_calvin_io::SAXArrayHandlers::arrayData [private]
A pointer to the array object.
Definition at line 185 of file SAXArrayHandlers.h.
Referenced by characters(), StoreArrayFileAttributes(), StorePhysicalArrayAttribute(), StorePhysicalArrayElementAttributes(), affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute(), and affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttributeControl().
ArrayFileElements affymetrix_calvin_io::SAXArrayHandlers::currentElement [private]
The parent element that is currently being processed.
Definition at line 191 of file SAXArrayHandlers.h.
Referenced by characters(), MoveCurrentElementBack(), and MoveCurrentElementForward().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_io::SAXArrayHandlers::dataTypeIdentifier [private]
An identifier to the type of data stored in the file
Definition at line 197 of file SAXArrayHandlers.h.
Referenced by DataTypeIdentifier().
std::wstring affymetrix_calvin_io::SAXArrayHandlers::fileVersionNumber [private]
The files version number.
Definition at line 194 of file SAXArrayHandlers.h.
Referenced by FileVersionNumber(), and StoreArrayFileAttributes().
bool affymetrix_calvin_io::SAXArrayHandlers::readHeaderOnly [private]
A flag used to indicate that the header line should only be read.
Definition at line 188 of file SAXArrayHandlers.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/SAXArrayHandlers.h
C:/f112/affy/sdk/calvin_files/parsers/src/SAXArrayHandlers.cpp