Affymetrix Fusion SDK: affymetrix_calvin_io::CDFData Class Reference
affymetrix_calvin_io::CDFData Class Reference
#include <CDFData.h>
Public Member Functions
CDFData ()
CDFData (const std::string &filename)
~CDFData ()
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename ()
int32_t GetFormatVersion ()
int32_t GetProbeSetCnt ()
void SetProbeSetCnt (u_int32_t cnt, CDFDataTypeIds type)
std::wstring GetProbeSetName (int32_t index)
void SetArrayRows (u_int32_t value)
u_int32_t GetArrayRows ()
void SetArrayCols (u_int32_t value)
u_int32_t GetArrayCols ()
void SetRefSequence (const std::string &seq)
std::string GetRefSequence ()
std::string GetDataTypeId ()
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
void GetProbeSetInformation (int32_t index, CDFProbeSetInformation &info)
void GetProbeSetInformation (const std::wstring &probeSetName, CDFProbeSetInformation &info)
void GetQCProbeSetInformation (int32_t index, CDFQCProbeSetInformation &info)
void GetQCProbeSetInformation (const std::wstring &probeSetName, CDFQCProbeSetInformation &info)
Private Types
enum AccessMode { NoMode, SequentialMode, ProbeSetIndexMode, ProbeSetNameMode }
enum TOCColumns { TOCProbeSetNameCol, TOCFilePosCol }
Private Member Functions
void CreateDataGroups (const std::wstring &p, int32_t probesetCnt)
void CreateContentsGroup (const std::wstring &p, int32_t probesetCnt)
void CreateProbeSetGroups (int32_t probesetCnt)
void SetDataTypeId (CDFDataTypeIds p, int32_t probesetCnt)
void SetUInt32ToGenericHdr (const std::wstring &name, u_int32_t value)
u_int32_t GetUInt32FromGenericHdr (const std::wstring &name)
void PrepareForSequentialAccess ()
void PrepareForAccessByProbeSetIndex ()
void PrepareForAccessByProbeSetName ()
u_int32_t GetTOCFilePosByIndex (int32_t index)
u_int32_t GetTOCFilePosByName (const std::wstring &name)
Private Attributes
GenericData genericData
bool setTocMetaData
AccessMode mode
int32_t curIndex
u_int32_t curGroupFilePos
DataSet * tocDataSet
std::map< std::wstring, u_int32_t > nameToFilePosMap
Friends
class CDFFileReader
Detailed Description
This class stores data from a Calvin CDF file.
Definition at line 88 of file CDFData.h.
Member Enumeration Documentation
enum affymetrix_calvin_io::CDFData::AccessMode [private]
The type of access for parsing the file.
Enumerator:
NoMode
SequentialMode
No access mode.
ProbeSetIndexMode
Sequencial access to probe set data.
ProbeSetNameMode
Optimized for access given a probe set index.
Optimized for access given a probe set name.
Definition at line 216 of file CDFData.h.
enum affymetrix_calvin_io::CDFData::TOCColumns [private]
The columns in the probe set name set.
Enumerator:
TOCProbeSetNameCol
TOCFilePosCol
The probe set name column.
The file position column.
Definition at line 224 of file CDFData.h.
Constructor & Destructor Documentation
CDFData::CDFData ()
Constructor
Definition at line 31 of file CDFData.cpp.
CDFData::CDFData (const std::string & filename)
Constructor with file name as input.
Definition at line 37 of file CDFData.cpp.
CDFData::~CDFData ()
Destructor
Definition at line 44 of file CDFData.cpp.
Member Function Documentation
void CDFData::Clear ()
Clear member variables
Definition at line 49 of file CDFData.cpp.
Referenced by affymetrix_calvin_io::CDFFileReader::Read().
void CDFData::CreateContentsGroup (const std::wstring & p, int32_t probesetCnt) [private]
Create the table of contents group indexes.
Parameters:
p The group name.
probesetCnt The number of probe sets.
Definition at line 180 of file CDFData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataSetHeader::AddIntColumn(), affymetrix_calvin_io::DataSetHeader::AddUnicodeColumn(), MAX_CDF_PROBE_SET_NAME_LENGTH, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CDFData::CreateDataGroups (const std::wstring & p, int32_t probesetCnt) [private]
Create the data groups.
Parameters:
p The group name.
probesetCnt The number of probe sets.
Definition at line 174 of file CDFData.cpp.
void CDFData::CreateProbeSetGroups (int32_t probesetCnt) [private]
Create a data group for every probe set.
Parameters:
probesetCnt The number of probe sets.
Definition at line 192 of file CDFData.cpp.
u_int32_t CDFData::GetArrayCols ()
The number of columns of features in the array.
Returns:
The column count.
Definition at line 87 of file CDFData.cpp.
References CDF_COLS_PARAM.
u_int32_t CDFData::GetArrayRows ()
The number of rows of features in the array.
Returns:
The row count.
Definition at line 77 of file CDFData.cpp.
References CDF_ROWS_PARAM.
std::string CDFData::GetDataTypeId ()
Gets the data type identifier.
Returns:
The data type identifier.
Definition at line 168 of file CDFData.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetFileTypeId().
FileHeader* affymetrix_calvin_io::CDFData::GetFileHeader () [inline]
Gets the file header object.
Returns:
The file header object.
Definition at line 173 of file CDFData.h.
References genericData, and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_calvin_io::CDFCntrlFileWriter::CDFCntrlFileWriter(), and affymetrix_calvin_io::CDFFileWriter::CDFFileWriter().
std::string CDFData::GetFilename ()
Get filename.
Returns:
The file name.
Definition at line 118 of file CDFData.cpp.
Referenced by affymetrix_calvin_io::CDFFileReader::Read().
int32_t CDFData::GetFormatVersion ()
Get format version.
Returns:
The CDF format version.
Definition at line 67 of file CDFData.cpp.
GenericData& affymetrix_calvin_io::CDFData::GetGenericData () [inline]
Gets the generic data header.
Returns:
The generic data header.
Definition at line 178 of file CDFData.h.
References genericData.
Referenced by affymetrix_calvin_io::CDFFileReader::Read().
int32_t CDFData::GetProbeSetCnt ()
Gets the probe set count.
Returns:
The number of probe sets.
Definition at line 123 of file CDFData.cpp.
References CDF_SETS_PARAM.
Referenced by affymetrix_calvin_io::CDFCntrlFileWriter::CDFCntrlFileWriter(), and affymetrix_calvin_io::CDFFileWriter::CDFFileWriter().
void CDFData::GetProbeSetInformation (int32_t index, CDFProbeSetInformation & info)
Gets the information about a probe set.
Parameters:
index The index to the probe set. Must be between 0 and the number of probe sets - 1.
info The probe set information.
Exceptions:
CDFAccessNotSupportedByModeException
DataSetNotOpenException
Definition at line 287 of file CDFData.cpp.
References AFFY_CNTRL_PS, affymetrix_calvin_io::DataGroup::DataGroup(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), affymetrix_calvin_io::DataGroup::Header(), and affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup().
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::Initialize().
void CDFData::GetProbeSetInformation (const std::wstring & probeSetName, CDFProbeSetInformation & info)
Gets the information about a probe set.
Parameters:
probeSetName The name of the probe set.
info The probe set information.
Exceptions:
CDFAccessNotSupportedByModeException
DataSetNotOpenException
ProbeSetNotFoundException
Definition at line 331 of file CDFData.cpp.
References AFFY_CNTRL_PS, affymetrix_calvin_io::DataGroup::DataGroup(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup().
std::wstring CDFData::GetProbeSetName (int32_t index)
Get the name of a probe set name based on index. Use this method to get the probe set name for either a regular or QC probe set.
Parameters:
index The index to the probe set. Must be between 0 and the number of probe sets - 1.
Definition at line 448 of file CDFData.cpp.
References affymetrix_calvin_io::DataGroup::DataGroup(), affymetrix_calvin_io::DataGroup::DataSet(), and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
void CDFData::GetQCProbeSetInformation (int32_t index, CDFQCProbeSetInformation & info)
Gets the information about a QC probe set.
Parameters:
index The index of the QC probe set.
info The probe set information.
Exceptions:
CDFAccessNotSupportedByModeException
DataSetNotOpenException
Definition at line 351 of file CDFData.cpp.
References AFFY_CNTRL_PS, affymetrix_calvin_io::DataGroup::DataGroup(), affymetrix_calvin_io::DataGroup::DataSet(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), affymetrix_calvin_io::DataGroup::Header(), and affymetrix_calvin_io::CDFQCProbeSetInformation::SetDataSet().
Referenced by affymetrix_fusion_io::FusionCDFQCProbeSetInformation::Initialize().
void CDFData::GetQCProbeSetInformation (const std::wstring & probeSetName, CDFQCProbeSetInformation & info)
Gets the information about a QC probe set.
Parameters:
probeSetName The name of the QC probe set.
info The probe set information.
Exceptions:
CDFAccessNotSupportedByModeException
DataSetNotOpenException
ProbeSetNotFoundException
Definition at line 397 of file CDFData.cpp.
References AFFY_CNTRL_PS, affymetrix_calvin_io::DataGroup::DataGroup(), affymetrix_calvin_io::DataGroup::DataSet(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and affymetrix_calvin_io::CDFQCProbeSetInformation::SetDataSet().
std::string CDFData::GetRefSequence ()
Gets the reference sequence.
Returns:
The reference sequence.
Definition at line 101 of file CDFData.cpp.
References CDF_REFSEQ_PARAM, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii().
Referenced by affymetrix_fusion_io::FusionCDFFileHeader::Initialize().
u_int32_t CDFData::GetTOCFilePosByIndex (int32_t index) [private]
Gets the table of contents file position by the probe set index.
Parameters:
index The probe set index.
Exceptions:
DataSetNotOpenException
Definition at line 417 of file CDFData.cpp.
References affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
u_int32_t CDFData::GetTOCFilePosByName (const std::wstring & name) [private]
Gets the table of contents file position by probe set name.
Parameters:
name The probe set name.
Exceptions:
DataSetNotOpenException
ProbeSetNotFoundException
Definition at line 430 of file CDFData.cpp.
References affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
u_int32_t CDFData::GetUInt32FromGenericHdr (const std::wstring & name) [private]
Gets an integer parameter from the header given the parameter name.
Parameters:
name The parameter name.
Definition at line 201 of file CDFData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32().
void CDFData::PrepareForAccessByProbeSetIndex () [private]
Prepares the object for probe set index access.
Definition at line 235 of file CDFData.cpp.
References affymetrix_calvin_io::DataGroup::DataGroup(), affymetrix_calvin_io::DataGroup::DataSet(), and affymetrix_calvin_io::DataSet::Open().
Referenced by affymetrix_calvin_io::CDFFileReader::Read().
void CDFData::PrepareForAccessByProbeSetName () [private]
Prepares the object for probe set name access.
Definition at line 251 of file CDFData.cpp.
References affymetrix_calvin_io::DataGroup::DataGroup(), affymetrix_calvin_io::DataGroup::DataSet(), and affymetrix_calvin_io::DataSet::Rows().
Referenced by affymetrix_calvin_io::CDFFileReader::Read().
void CDFData::PrepareForSequentialAccess () [private]
Prepares the object for sequencial access.
Definition at line 222 of file CDFData.cpp.
References affymetrix_calvin_io::DataGroup::DataGroup(), affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), and affymetrix_calvin_io::DataGroup::Header().
Referenced by affymetrix_calvin_io::CDFFileReader::Read().
void CDFData::SetArrayCols (u_int32_t value)
Sets the number of columns of features in the array.
Parameters:
value The column count.
Definition at line 82 of file CDFData.cpp.
References CDF_COLS_PARAM.
void CDFData::SetArrayRows (u_int32_t value)
Sets the number of rows of features in the array.
Parameters:
value The row count.
Definition at line 72 of file CDFData.cpp.
References CDF_ROWS_PARAM.
void CDFData::SetDataTypeId (CDFDataTypeIds p, int32_t probesetCnt) [private]
Sets the data type identifier.
Parameters:
p The probe set type.
probesetCnt The number of probe sets.
Definition at line 134 of file CDFData.cpp.
References AFFY_CNTRL_PS, AFFY_EXPR_PS, AFFY_GENO_PS, AFFY_RESEQ_PS, AFFY_TAG_PS, CDF_PS_GROUP_LBL, CDF_QC_GROUP_LBL, affymetrix_calvin_io::Expression, affymetrix_calvin_io::Genotyping, affymetrix_calvin_io::Resequencing, affymetrix_calvin_io::GenericDataHeader::SetFileTypeId(), and affymetrix_calvin_io::Tag.
void CDFData::SetFilename (const std::string & p)
Set filename.
Parameters:
p The name of the file.
Definition at line 113 of file CDFData.cpp.
void CDFData::SetProbeSetCnt (u_int32_t cnt, CDFDataTypeIds type)
The number of probe sets.
Returns:
The number of probe sets.
Definition at line 128 of file CDFData.cpp.
References CDF_SETS_PARAM.
void CDFData::SetRefSequence (const std::string & seq)
Sets the reference sequence for a resequencing array.
Parameters:
seq The reference sequence.
Definition at line 92 of file CDFData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), CDF_REFSEQ_PARAM, affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueAscii().
void CDFData::SetUInt32ToGenericHdr (const std::wstring & name, u_int32_t value) [private]
Sets an integer parameter to the header.
Parameters:
name The parameter name.
value The parameter value.
Definition at line 213 of file CDFData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueUInt32().
Friends And Related Function Documentation
friend class CDFFileReader [friend]
Friend to the reader.
Definition at line 310 of file CDFData.h.
Member Data Documentation
u_int32_t affymetrix_calvin_io::CDFData::curGroupFilePos [private]
file position of the current DataGroup
Definition at line 301 of file CDFData.h.
int32_t affymetrix_calvin_io::CDFData::curIndex [private]
sequential index
Definition at line 298 of file CDFData.h.
GenericData affymetrix_calvin_io::CDFData::genericData [private]
The generic data header.
Definition at line 289 of file CDFData.h.
Referenced by GetFileHeader(), and GetGenericData().
AccessMode affymetrix_calvin_io::CDFData::mode [private]
Access mode
Definition at line 295 of file CDFData.h.
std::map<std::wstring, u_int32_t> affymetrix_calvin_io::CDFData::nameToFilePosMap [private]
map of probe set name to file position
Definition at line 307 of file CDFData.h.
bool affymetrix_calvin_io::CDFData::setTocMetaData [private]
Definition at line 292 of file CDFData.h.
DataSet* affymetrix_calvin_io::CDFData::tocDataSet [private]
pointer to the table of contents DataSet
Definition at line 304 of file CDFData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CDFData.h
C:/f112/affy/sdk/calvin_files/data/src/CDFData.cpp