Affymetrix Fusion SDK: C:/f112/affy/sdk/file/test-fileio.cpp File Reference
test-fileio.cpp File Reference
#include "file/FileIO.h"
#include "file/FileWriter.h"
#include "portability/affy-base-types.h"
#include <cstdio>
#include <cstring>
#include <fstream>
#include <iostream>
#include <netinet/in.h>
#include <string.h>
#include <sys/types.h>
Defines
#define HDR_SIZE 16
#define HDR_W(ostr) WRITE_STRING(ostm,str)
#define HDR_R()
#define TEST_STR "0123456789AB"
#define TEST_CNT_INT32 (2*(16/4))
#define TEST_CNT_INT16 (2*(16/2))
#define TEST_CNT_INT8 (2*(16/1))
#define TEST_CNT_FLOAT (2*(16/4))
#define TEST_CNT_STRING 4
#define CMP_XY() printf("O: %2d: x=%08X => y=%08X %s\n",i,x,y,((x==y)?"":"Error"))
#define UNALIGN_BUF_SIZE 100
#define UNALIGN_LOOP(type_t, func_set, func_get, fmt)
Functions
int main (int argc, char *argv[])
Define Documentation
#define CMP_XY () printf("O: %2d: x=%08X => y=%08X %s\n",i,x,y,((x==y)?"":"Error"))
Referenced by main().
#define HDR_R ()
Value:
do { string str; \
   ReadFixedString(istm,str,HDR_SIZE); \
   printf("%s\n",str.c_str()); \
  } while (0)
Definition at line 51 of file test-fileio.cpp.
Referenced by main().
#define HDR_SIZE 16
Definition at line 49 of file test-fileio.cpp.
#define HDR_W (ostr) WRITE_STRING(ostm,str)
Definition at line 50 of file test-fileio.cpp.
Referenced by main().
#define TEST_CNT_FLOAT (2*(16/4))
Definition at line 60 of file test-fileio.cpp.
Referenced by main().
#define TEST_CNT_INT16 (2*(16/2))
Definition at line 58 of file test-fileio.cpp.
Referenced by main().
#define TEST_CNT_INT32 (2*(16/4))
Definition at line 57 of file test-fileio.cpp.
Referenced by main().
#define TEST_CNT_INT8 (2*(16/1))
Definition at line 59 of file test-fileio.cpp.
Referenced by main().
#define TEST_CNT_STRING 4
Definition at line 61 of file test-fileio.cpp.
Referenced by main().
#define TEST_STR "0123456789AB"
Definition at line 56 of file test-fileio.cpp.
Referenced by main().
#define UNALIGN_BUF_SIZE 100
#define UNALIGN_LOOP (type_t, func_set, func_get, fmt)
Value:
do { \
  uint8_t buf[UNALIGN_BUF_SIZE]; \
  printf("UNALIGN TEST(" #type_t ")==========\n"); \
  for (int off=0;off<16;off++) { \
    for (int idx=0;idx<1;idx++) { \
      type_t vi=(idx+off)*0x00000101; \
      type_t vo; \
      uint8_t* ptr=&buf[((idx*sizeof(type_t))+off)]; \
         func_set((type_t*)ptr,vi); \
         vo=func_get((type_t*)ptr);                                     \
      printf("ptr=(idx=%2d,off=%2d)=%p  vi=" #fmt " vo=" #fmt "\n",idx,off,ptr,vi,vo,((vi==vo)?"":"Error")); \
    } \
  } } while (0)
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 64 of file test-fileio.cpp.
References CMP_XY, HDR_R, HDR_W, MmGetFloat_I(), MmGetUInt16_I(), MmGetUInt32_I(), MmGetUInt8(), MmSetFloat_I(), MmSetUInt16_I(), MmSetUInt32_I(), MmSetUInt8(), ReadFloat_I(), ReadString_N(), ReadUInt16_I(), ReadUInt32_I(), ReadUInt8(), TEST_CNT_FLOAT, TEST_CNT_INT16, TEST_CNT_INT32, TEST_CNT_INT8, TEST_CNT_STRING, TEST_STR, UNALIGN_LOOP, WriteFloat_I(), WriteInt16_I(), WriteString_N(), WriteUInt16_I(), WriteUInt32_I(), and WriteUInt8().