Affymetrix Fusion SDK: C:/f112/affy/sdk/file/BPMAPFileData.cpp File Reference
BPMAPFileData.cpp File Reference
#include "file/BPMAPFileData.h"
#include "file/FileIO.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <istream>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/mman.h>
Defines
#define DNA_BASE_A 0
#define DNA_BASE_C 1
#define DNA_BASE_G 2
#define DNA_BASE_T 3
#define DNA_BASE_OTHER 4
Functions
static int int_to_acgt (unsigned int i, char *c)
static int byte_to_dna (const char *b, unsigned short n_b, char *d, unsigned short n_d)
Variables
static bool g_OlderBPMAPFileFormat = true
Define Documentation
#define DNA_BASE_A 0
Definition at line 172 of file BPMAPFileData.cpp.
Referenced by int_to_acgt().
#define DNA_BASE_C 1
Definition at line 173 of file BPMAPFileData.cpp.
Referenced by int_to_acgt().
#define DNA_BASE_G 2
Definition at line 174 of file BPMAPFileData.cpp.
Referenced by int_to_acgt().
#define DNA_BASE_OTHER 4
Definition at line 176 of file BPMAPFileData.cpp.
#define DNA_BASE_T 3
Definition at line 175 of file BPMAPFileData.cpp.
Referenced by int_to_acgt().
Function Documentation
static int byte_to_dna (const char * b, unsigned short n_b, char * d, unsigned short n_d) [static]
Definition at line 205 of file BPMAPFileData.cpp.
References int_to_acgt().
Referenced by affxbpmap::CGDACSequenceItem::GetHitItem(), and affxbpmap::CBPMAPFileData::ReadDataSection().
static int int_to_acgt (unsigned int i, char * c) [static]
Definition at line 178 of file BPMAPFileData.cpp.
References DNA_BASE_A, DNA_BASE_C, DNA_BASE_G, and DNA_BASE_T.
Referenced by byte_to_dna().
Variable Documentation
bool g_OlderBPMAPFileFormat = true [static]
Definition at line 49 of file BPMAPFileData.cpp.
Referenced by affxbpmap::CGDACSequenceItem::GetHitItem(), affxbpmap::CBPMAPFileData::ReadDataSection(), and affxbpmap::CBPMAPFileData::ReadHeaderSection().