Affymetrix Fusion SDK: C:/f112/affy/sdk/calvin_files/utils/src/FileUtils.cpp File Reference
FileUtils.cpp File Reference
#include "calvin_files/utils/src/FileUtils.h"
#include "util/Fs.h"
#include <fcntl.h>
#include <sstream>
#include <string>
#include <sys/types.h>
#include <dirent.h>
Defines
#define POSIX_OPEN open
#define POSIX_CLOSE close
Functions
template<class T >
std::string FUToStr (const T &t)
static void subChar (std::string &s, char from, char to)
std::string convertPathNameLocal (const std::string &path, bool singleFile)
Variables
static string LockFileExtension = ".lock"
Define Documentation
#define POSIX_CLOSE close
Definition at line 48 of file FileUtils.cpp.
Referenced by affymetrix_calvin_utilities::FileUtils::Exists().
#define POSIX_OPEN open
Definition at line 47 of file FileUtils.cpp.
Function Documentation
std::string convertPathNameLocal (const std::string & path, bool singleFile)
Todo:
copy of the code from Util::convertPathName. Ugly Hack to prevent APT dependencies
Todo:
copy of the code from Util::convertPathName. Ugly Hack to prevent APT dependencies
Definition at line 157 of file FileUtils.cpp.
References subChar().
Referenced by affymetrix_calvin_utilities::FileUtils::Exists().
template<class T > std::string FUToStr (const T & t)
Little template function to make string conversion easy. this isn't the fastest way to do things, but it is easy.
Definition at line 58 of file FileUtils.cpp.
static void subChar (std::string & s, char from, char to) [static]
Todo:
copy of the code from Util::subChar. Ugly Hack to prevent APT dependencies
Definition at line 80 of file FileUtils.cpp.
Referenced by convertPathNameLocal(), and MsgStream::message().
Variable Documentation
string LockFileExtension = ".lock" [static]
Definition at line 53 of file FileUtils.cpp.
Referenced by affymetrix_calvin_utilities::FileUtils::LockFile(), and affymetrix_calvin_utilities::FileUtils::UnlockFile().