Affymetrix Fusion SDK: C:/f112/affy/sdk/file/FileIO.cpp File Reference
FileIO.cpp File Reference
#include "file/FileIO.h"
#include "portability/affy-base-types.h"
#include "util/Convert.h"
#include "util/Err.h"
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string.h>
#include <string>
#include <sys/types.h>
#include <netinet/in.h>
#include <inttypes.h>
Functions
void ReadUInt32_I (IFSTREAM &instr, uint32_t &val)
void ReadInt32_I (IFSTREAM &instr, int32_t &val)
void ReadFloat_I (IFSTREAM &instr, float &val)
void ReadUInt16_I (IFSTREAM &instr, uint16_t &val)
void ReadInt16_I (IFSTREAM &instr, int16_t &val)
void ReadUInt8 (IFSTREAM &instr, uint8_t &val)
void ReadInt8 (IFSTREAM &instr, int8_t &val)
void ReadUInt32_N (IFSTREAM &instr, uint32_t &val)
void ReadInt32_N (IFSTREAM &instr, int32_t &val)
void ReadFloat_N (IFSTREAM &instr, float &val)
void ReadUInt16_N (IFSTREAM &instr, uint16_t &val)
void ReadInt16_N (IFSTREAM &instr, int16_t &val)
void ReadFloatFromOldBPMAP_N (IFSTREAM &instr, float &fval)
void ReadFixedCString (IFSTREAM &instr, char *str, uint32_t len)
void ReadFixedUCString (IFSTREAM &instr, unsigned char *str, uint32_t len)
void ReadCString_I (IFSTREAM &instr, char *&str)
void ReadCString_I (IFSTREAM &instr, std::string &str)
void ReadCharacterArray (IFSTREAM &instr, char *str, uint32_t len)
void ReadFixedString (IFSTREAM &instr, string &str, uint32_t len)
void ReadString_I (IFSTREAM &instr, string &str)
void ReadUIntLenString_I (IFSTREAM &instr, std::string &s)
void ReadCString_N (IFSTREAM &instr, char *&str)
void ReadString_N (IFSTREAM &instr, string &str)
void ReadUIntLenString_N (IFSTREAM &instr, std::string &s)
void ReadNextLine (IFSTREAM &instr, char *line, int len)
int32_t MmGetInt32_I (int32_t *ptr)
int16_t MmGetInt16_I (int16_t *ptr)
int32_t MmGetInt32_N (int32_t *ptr)
int16_t MmGetInt16_N (int16_t *ptr)
int8_t MmGetInt8 (int8_t *ptr)
uint32_t MmGetUInt32_I (uint32_t *ptr)
void MmSetUInt32_I (uint32_t *ptr, uint32_t val)
uint32_t MmGetUInt32_N (uint32_t *ptr)
void MmSetUInt32_N (uint32_t *ptr, uint32_t val)
uint16_t MmGetUInt16_I (uint16_t *ptr)
void MmSetUInt16_I (uint16_t *ptr, uint16_t val)
uint16_t MmGetUInt16_N (uint16_t *ptr)
void MmSetUInt16_N (uint16_t *ptr, uint16_t val)
uint8_t MmGetUInt8 (uint8_t *ptr)
void MmSetUInt8 (uint8_t *ptr, uint8_t val)
float MmGetFloat_I (float *ptr)
void MmSetFloat_I (float *ptr, float val)
float MmGetFloat_N (float *ptr)
void MmSetFloat_N (float *ptr, float val)
float MmGetFloatFromOldBPMAP_N (float *ptr)
Function Documentation
float MmGetFloat_I (float * ptr)
Gets a float from a little endian data stream.
Parameters:
ptr A pointer to a little endian data stream
Returns:
The host ordered value
Definition at line 388 of file FileIO.cpp.
References itohl, type_punned::v_float, and type_punned::v_uint32.
Referenced by affxcel::CCELFileData::GetIntensities(), affxcel::CCELFileData::GetIntensity(), affxcel::CCELFileData::GetStdv(), main(), and SwapToLittleEndian().
float MmGetFloat_N (float * ptr)
Gets a float from a big endian data stream.
Parameters:
ptr A pointer to a big endian data stream
Returns:
The host ordered value
Definition at line 404 of file FileIO.cpp.
References type_punned::v_float, and type_punned::v_uint32.
Referenced by affxgrd::CGRDFileData::GetCenter(), affxbar::CGDACSequenceResultItem::GetData(), affxbpmap::CGDACSequenceItem::GetHitItem(), affxgrd::CGRDFileData::ReadFixedHeader(), and affxgrd::CGRDFileData::ReadOptimumCornerHeader().
float MmGetFloatFromOldBPMAP_N (float * ptr)
This function is for older BPMAP file with incorrectly written float's
Parameters:
ptr A pointer to a little endian data stream
Returns:
The host ordered value
Definition at line 422 of file FileIO.cpp.
References affy_swap32(), type_punned::v_float, and type_punned::v_uint32.
Referenced by affxbpmap::CGDACSequenceItem::GetHitItem().
int16_t MmGetInt16_I (int16_t * ptr)
Gets a 16 bit signed int from a little endian data stream.
Parameters:
ptr A pointer to a little endian data stream
Returns:
The host ordered value
Definition at line 304 of file FileIO.cpp.
References MmGetUInt16_I().
Referenced by affxcel::CCELFileData::GetPixels().
int16_t MmGetInt16_N (int16_t * ptr)
Gets a 16 bit signed int from a big endian data stream.
Parameters:
ptr A pointer to a big endian data stream
Returns:
The host ordered value
Definition at line 314 of file FileIO.cpp.
References MmGetUInt16_N().
int32_t MmGetInt32_I (int32_t * ptr)
Gets a 32 bit signed int from a little endian data stream.
Parameters:
ptr A pointer to a little endian data stream
Returns:
The host ordered value
Definition at line 299 of file FileIO.cpp.
References MmGetUInt32_I().
Referenced by SwapToLittleEndian().
int32_t MmGetInt32_N (int32_t * ptr)
Gets a 32 bit signed int from a big endian data stream.
Parameters:
ptr A pointer to a big endian data stream
Returns:
The host ordered value
Definition at line 309 of file FileIO.cpp.
References MmGetUInt32_N().
Referenced by affxgrd::CGRDFileData::ReadTagHeader().
int8_t MmGetInt8 (int8_t * ptr)
Gets a 8 bit signed int from a data stream.
Parameters:
ptr A pointer to the data stream
Returns:
The host ordered value
Definition at line 319 of file FileIO.cpp.
References MmGetUInt8().
uint16_t MmGetUInt16_I (uint16_t * ptr)
Gets a 16 bit unsigned int from a little endian data stream.
Parameters:
ptr A pointer to a little endian data stream
Returns:
The host ordered value
Definition at line 354 of file FileIO.cpp.
References itohs.
Referenced by affxcel::CCELFileData::GetIntensities(), affxcel::CCELFileData::GetIntensity(), affxdat::CDATFileData::GetPixels(), main(), MmGetInt16_I(), affxcel::CCELFileData::ReadCompactBCel(), and affxcel::CCELFileData::ReadXDABCel().
uint16_t MmGetUInt16_N (uint16_t * ptr)
Gets a 16 bit unsigned int from a big endian data stream.
Parameters:
ptr A pointer to a big endian data stream
Returns:
The host ordered value
Definition at line 365 of file FileIO.cpp.
Referenced by affxcel::CCELFileData::GetIntensities(), affxcel::CCELFileData::GetIntensity(), affxcel::CCELFileData::GetStdv(), and MmGetInt16_N().
uint32_t MmGetUInt32_I (uint32_t * ptr)
Gets a 32 bit unsigned int from a little endian data stream.
Parameters:
ptr A pointer to a little endian data stream
Returns:
The host ordered value
Definition at line 332 of file FileIO.cpp.
References itohl.
Referenced by main(), and MmGetInt32_I().
uint32_t MmGetUInt32_N (uint32_t * ptr)
Gets a 32 bit unsigned int from a big endian data stream.
Parameters:
ptr A pointer to a big endian data stream
Returns:
The host ordered value
Definition at line 343 of file FileIO.cpp.
Referenced by affxbar::CGDACSequenceResultItem::GetData(), affxbpmap::CGDACSequenceItem::GetHitItem(), MmGetInt32_N(), affxgrd::CGRDFileData::ReadFixedHeader(), affxgrd::CGRDFileData::ReadOptimumCornerHeader(), affxgrd::CGRDFileData::ReadTagHeader(), and affxcel::CCELFileData::ReadTranscriptomeBCel().
uint8_t MmGetUInt8 (uint8_t * ptr)
Gets a 8 bit unsigned int from a data stream.
Parameters:
ptr A pointer to the data stream
Returns:
The host ordered value
Definition at line 376 of file FileIO.cpp.
Referenced by affxcel::CCELFileData::GetPixels(), main(), and MmGetInt8().
void MmSetFloat_I (float * ptr, float val)
Assigns a float value to a little endian data stream.
Parameters:
ptr The data stream to set.
val The value to store in the data stream.
Definition at line 396 of file FileIO.cpp.
References htoil, type_punned::v_float, and type_punned::v_uint32.
Referenced by main(), affxcel::CCELFileData::SetIntensity(), and affxcel::CCELFileData::SetStdv().
void MmSetFloat_N (float * ptr, float val)
Assigns a float value to a big endian data stream.
Parameters:
ptr The data stream to set.
val The value to store in the data stream.
Definition at line 412 of file FileIO.cpp.
References type_punned::v_float, and type_punned::v_uint32.
Referenced by CopyMetricToBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberVariationRegionEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCytoRegionEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataExpressionEntry(), and affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataGenotypeEntry().
void MmSetUInt16_I (uint16_t * ptr, uint16_t val)
Assigns a 16 bit unsigned value to a little endian data stream.
Parameters:
ptr The data stream to set.
val The value to store in the data stream.
Definition at line 359 of file FileIO.cpp.
References htois.
Referenced by main(), affxcel::CCELFileData::SetIntensity(), and affxcel::CCELFileData::SetPixels().
void MmSetUInt16_N (uint16_t * ptr, uint16_t val)
Assigns a 16 bit unsigned value to a big endian data stream.
Parameters:
ptr The data stream to set.
val The value to store in the data stream.
Definition at line 370 of file FileIO.cpp.
Referenced by CopyMetricToBuffer(), affxcel::CCELFileData::SetIntensity(), affxcel::CCELFileData::SetStdv(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), and affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteEntry().
void MmSetUInt32_I (uint32_t * ptr, uint32_t val)
Assigns a 32 bit unsigned value to a little endian data stream.
Parameters:
ptr The data stream to set.
val The value to store in the data stream.
Definition at line 337 of file FileIO.cpp.
References htoil.
Referenced by main().
void MmSetUInt32_N (uint32_t * ptr, uint32_t val)
Assigns a 32 bit unsigned value to a big endian data stream.
Parameters:
ptr The data stream to set.
val The value to store in the data stream.
Definition at line 348 of file FileIO.cpp.
Referenced by CopyMetricToBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberVariationRegionEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCytoRegionEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataExpressionEntry(), and affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataGenotypeEntry().
void MmSetUInt8 (uint8_t * ptr, uint8_t val)
Assigns an 8 bit unsigned value to a data stream.
Parameters:
ptr The data stream to set.
val The value to store in the data stream.
Definition at line 381 of file FileIO.cpp.
Referenced by main(), affxcel::CCELFileData::SetPixels(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberEntry(), affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberVariationRegionEntry(), and affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataCytoRegionEntry().
void ReadCharacterArray (IFSTREAM & instr, char * str, uint32_t len)
Reads a fixed length array of characters from a file.
Parameters:
instr The input file stream
str The returned string value.
len The length of the string to read
Definition at line 202 of file FileIO.cpp.
void ReadCString_I (IFSTREAM & instr, std::string & str)
Definition at line 193 of file FileIO.cpp.
References ReadUInt32_I().
void ReadCString_I (IFSTREAM & instr, char *& str)
Reads a string from a little endian file
Parameters:
instr The input file stream
str The returned value
Definition at line 183 of file FileIO.cpp.
References ReadUInt32_I().
Referenced by affxchp::CCHPFileData::Open(), affxcel::CCELFileData::ReadCompactBCel(), and affxcel::CCELFileData::ReadXDABCel().
void ReadCString_N (IFSTREAM & instr, char *& str)
Reads a string from a big endian file
Parameters:
instr The input file stream
str The returned value
Definition at line 239 of file FileIO.cpp.
References ReadUInt32_N().
void ReadFixedCString (IFSTREAM & instr, char * str, uint32_t len)
Reads a fixed length string from a file.
Parameters:
instr The input file stream
str The returned string value.
len The length of the string to read
Definition at line 171 of file FileIO.cpp.
Referenced by affxcdf::CCDFFileData::GetProbeSetName(), affxcel::CCELFileData::IsCompactCelFile(), affxchp::CCHPFileData::IsMas5File(), affxcel::CCELFileData::IsTranscriptomeBcelFile(), affxcel::CCELFileData::IsUnsupportedCompactCelFile(), and affxchp::CCHPFileData::Open().
void ReadFixedString (IFSTREAM & instr, string & str, uint32_t len)
Definition at line 213 of file FileIO.cpp.
Referenced by affxcdf::CCDFFileData::GetProbeSetInformation(), affxchp::CCHPFileData::Open(), affxcel::CCELFileData::ReadCompactBCel(), affxbpmap::CBPMAPFileData::ReadHeaderSection(), affxbar::CBARFileData::ReadHeaderSection(), SimpleBinaryFile::ReadRow(), ReadString_I(), ReadString_N(), affxcel::CCELFileData::ReadTranscriptomeBCel(), ReadUIntLenString_I(), ReadUIntLenString_N(), and affxcdf::CCDFFileData::ReadXDAHeader().
void ReadFixedUCString (IFSTREAM & instr, unsigned char * str, uint32_t len)
Reads a fixed length string from a file.
Parameters:
instr The input file stream
str The returned string value.
len The length of the string to read.
Definition at line 177 of file FileIO.cpp.
Referenced by affxbpmap::CBPMAPFileData::ReadDataSection().
void ReadFloat_I (IFSTREAM & instr, float & val)
Reads a float from a file
Parameters:
instr The input file stream
val The returned value
Definition at line 77 of file FileIO.cpp.
References ReadUInt32_I().
Referenced by main(), and affxchp::CCHPFileData::Open().
void ReadFloat_N (IFSTREAM & instr, float & val)
Reads a float value from a big endian file
Parameters:
instr The input file stream
val The returned value
Definition at line 125 of file FileIO.cpp.
References ReadUInt32_N().
Referenced by affxbpmap::CBPMAPFileData::ReadDataSection(), affxbar::CBARFileData::ReadDataSection(), affxbpmap::CBPMAPFileData::ReadHeaderSection(), affxbar::CBARFileData::ReadHeaderSection(), SimpleBinaryFile::ReadRow(), and affxcel::CCELFileData::ReadTranscriptomeBCel().
void ReadFloatFromOldBPMAP_N (IFSTREAM & instr, float & fval)
This function is for older BPMAP file with incorrectly written float's The floats were written as ints
Parameters:
instr The input file stream.
fval The returned float
Definition at line 151 of file FileIO.cpp.
References affy_swap32(), FLOAT_SIZE, type_punned::v_float, and type_punned::v_uint32.
Referenced by affxbpmap::CBPMAPFileData::ReadDataSection(), and affxbpmap::CBPMAPFileData::ReadHeaderSection().
void ReadInt16_I (IFSTREAM & instr, int16_t & val)
Reads a signed 16 bit integer from a file
Parameters:
instr The input file stream
val The returned value
Definition at line 90 of file FileIO.cpp.
References ReadUInt16_I().
Referenced by affxchp::CCHPFileData::Open(), affxdat::CDATFileData::Read(), and affxgrc::CGRCFileData::ReadPreReleaseFormat().
void ReadInt16_N (IFSTREAM & instr, int16_t & val)
Reads a signed 16 bit value from a big endian file
Parameters:
instr The input file stream
val The returned value
Definition at line 138 of file FileIO.cpp.
References ReadUInt16_N().
void ReadInt32_I (IFSTREAM & instr, int32_t & val)
Reads a signed 32 bit integer from a file
Parameters:
instr The input file stream
val The returned value
Definition at line 72 of file FileIO.cpp.
References ReadUInt32_I().
Referenced by affxcdf::CCDFFileData::GetProbeSetInformation(), affxcdf::CCDFFileData::GetQCProbeSetInformation(), affxchp::CCHPFileData::IsMas5File(), affxchp::CCHPFileData::IsXDACompatibleFile(), affxcdf::CCDFFileData::IsXDACompatibleFile(), affxchp::CCHPFileData::Open(), affxcel::CCELFileData::ReadCompactBCel(), affxgrc::CGRCFileData::ReadPreReleaseFormat(), affxcel::CCELFileData::ReadXDABCel(), and affxcdf::CCDFFileData::ReadXDAHeader().
void ReadInt32_N (IFSTREAM & instr, int32_t & val)
Reads a signed 32 bit value from a big endian file
Parameters:
instr The input file stream
val The returned value
Definition at line 120 of file FileIO.cpp.
References ReadUInt32_N().
Referenced by SimpleBinaryFile::OpenFile(), affxbar::CBARFileData::ReadDataSection(), affxbar::CBARFileData::ReadHeaderSection(), and affxgrc::CGRCFileData::ReadReleaseFormat().
void ReadInt8 (IFSTREAM & instr, int8_t & val)
Reads an 8 bit value from a file
Parameters:
instr The input file stream
val The returned value
Definition at line 102 of file FileIO.cpp.
References ReadUInt8().
Referenced by affymetrix_calvin_io::DataSet::AssignValue(), affymetrix_calvin_io::DataSet::GetData(), affxchp::CCHPFileData::Open(), affymetrix_calvin_io::DataSetReader::Read(), affymetrix_calvin_io::DataSetHeaderReader::ReadColumns(), affymetrix_calvin_io::FileHeaderReader::ReadMagicNumber(), and affymetrix_calvin_io::FileHeaderReader::ReadVersion().
void ReadNextLine (IFSTREAM & instr, char * line, int len)
Reads the next line from a text file.
Parameters:
instr The input file stream
line The returned string (the data must already be allocated)
len The maximum length of the line to read.
Definition at line 266 of file FileIO.cpp.
Referenced by affxexp::CEXPFileData::Read(), affx1lq::C1LQFileData::Read(), and affxcdf::CCDFFileData::ReadTextFormat().
void ReadString_I (IFSTREAM & instr, string & str)
Definition at line 223 of file FileIO.cpp.
References ReadFixedString(), and ReadUInt32_I().
Referenced by affxcdf::CCDFFileData::ReadXDAHeader().
void ReadString_N (IFSTREAM & instr, string & str)
Definition at line 250 of file FileIO.cpp.
References ReadFixedString(), and ReadUInt32_N().
Referenced by main(), SimpleBinaryFile::OpenFile(), affxbar::CBARFileData::ReadDataSection(), and affxbar::CBARFileData::ReadHeaderSection().
void ReadUInt16_I (IFSTREAM & instr, uint16_t & val)
Reads an unsigned 16 bit integer from a file
Parameters:
instr The input file stream
val The returned value
Definition at line 83 of file FileIO.cpp.
References itohs.
Referenced by affxdat::CDATFileData::GetPixel(), affxcdf::CCDFFileData::GetProbeSetInformation(), affxcdf::CCDFFileData::GetProbeSetType(), affxcdf::CCDFFileData::GetQCProbeSetInformation(), main(), affxchp::CCHPFileData::Open(), affxdat::CDATFileData::Read(), ReadInt16_I(), and affxcdf::CCDFFileData::ReadXDAHeader().
void ReadUInt16_N (IFSTREAM & instr, uint16_t & val)
Reads an unsigned 16 bit value from a big endian file
Parameters:
instr The input file stream
val The returned value
Definition at line 131 of file FileIO.cpp.
Referenced by ReadInt16_N(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxcel::CCELFileData::ReadTranscriptomeBCel().
void ReadUInt32_I (IFSTREAM & instr, uint32_t & val)
Reads an unsigned 32 bit integer from a file
Parameters:
instr The input file stream
val The returned value
Definition at line 65 of file FileIO.cpp.
References itohl.
Referenced by affxcdf::CCDFFileData::GetProbeSetInformation(), affxcdf::CCDFFileData::GetProbeSetType(), affxcel::CCELFileData::IsXDACompatibleFile(), main(), affxdat::CDATFileData::Read(), affxcel::CCELFileData::ReadCompactBCel(), ReadCString_I(), ReadFloat_I(), ReadInt32_I(), ReadString_I(), ReadUIntLenString_I(), and affxcel::CCELFileData::ReadXDABCel().
void ReadUInt32_N (IFSTREAM & instr, uint32_t & val)
Reads an unsigned 32 bit value from a big endian file
Parameters:
instr The input file stream
val The returned value
Definition at line 113 of file FileIO.cpp.
Referenced by ReadCString_N(), affxbpmap::CBPMAPFileData::ReadDataSection(), ReadFloat_N(), affxbpmap::CBPMAPFileData::ReadHeaderSection(), ReadInt32_N(), ReadString_N(), affxcel::CCELFileData::ReadTranscriptomeBCel(), and ReadUIntLenString_N().
void ReadUInt8 (IFSTREAM & instr, uint8_t & val)
Reads an unsigned 8 bit value from a file
Parameters:
instr The input file stream
val The returned value
Definition at line 97 of file FileIO.cpp.
Referenced by affymetrix_calvin_io::DataSet::AssignValue(), affymetrix_calvin_io::DataSet::GetData(), affxcdf::CCDFFileData::GetProbeSetInformation(), affxcdf::CCDFFileData::GetQCProbeSetInformation(), affxdat::CDATFileData::IsGCOSDATFile(), affxgrc::CGRCFileData::IsReleaseFormat(), main(), affxchp::CCHPFileData::Open(), affxdat::CDATFileData::Read(), affymetrix_calvin_io::DataSetReader::Read(), affxbpmap::CBPMAPFileData::ReadDataSection(), ReadInt8(), affxgrc::CGRCFileData::ReadReleaseFormat(), and affxcdf::CCDFFileData::ReadXDAHeader().
void ReadUIntLenString_I (IFSTREAM & instr, std::string & s)
Reads a string frome a little endian file where the string length is stored as an unsigned integer.
Parameters:
instr The input file stream
s The returned value
Definition at line 231 of file FileIO.cpp.
References ReadFixedString(), and ReadUInt32_I().
void ReadUIntLenString_N (IFSTREAM & instr, std::string & s)
Reads a string frome a big endian file where the string length is stored as an unsigned integer.
Parameters:
instr The input file stream
s The returned value
Definition at line 258 of file FileIO.cpp.
References ReadFixedString(), and ReadUInt32_N().
Referenced by affxbpmap::CBPMAPFileData::ReadDataSection().