Affymetrix Fusion SDK: C:/f112/affy/sdk/file/FileWriter.cpp File Reference
FileWriter.cpp File Reference
#include "file/FileWriter.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string.h>
#include <string>
#include <inttypes.h>
#include <netinet/in.h>
#include <sys/types.h>
Functions
void WriteUInt32_I (OFSTREAM &outstr, uint32_t val)
void WriteInt32_I (OFSTREAM &outstr, int32_t val)
void WriteUInt32_N (OFSTREAM &outstr, uint32_t val)
void WriteInt32_N (OFSTREAM &outstr, int32_t val)
void WriteUInt16_I (OFSTREAM &outstr, uint16_t val)
void WriteInt16_I (OFSTREAM &outstr, int16_t val)
void WriteUInt16_N (OFSTREAM &outstr, uint16_t val)
void WriteInt16_N (OFSTREAM &outstr, int16_t val)
void WriteUInt8 (OFSTREAM &outstr, uint8_t val)
void WriteInt8 (OFSTREAM &outstr, int8_t val)
void WriteFloat_I (OFSTREAM &outstr, float fval)
void WriteFloat_N (OFSTREAM &outstr, float fval)
void WriteFloatLowPrecision (OFSTREAM &outstr, float fval)
void WriteFixedCString (OFSTREAM &outstr, const char *str, size_t outlen)
void WriteCString (OFSTREAM &outstr, const char *str)
void WriteCString (OFSTREAM &outstr, std::string str)
void WriteFixedString (OFSTREAM &outstr, const std::string str, size_t outlen)
void WriteString_I (OFSTREAM &outstr, const std::string str)
void WriteString_N (OFSTREAM &outstr, const std::string str)
void WriteCharacterArray (OFSTREAM &outstr, char *c, size_t outlen)
Function Documentation
void WriteCharacterArray (OFSTREAM & outstr, char * str, size_t len)
Writes packed character array to the output file
Parameters:
outstr The output file stream.
str The string value to write
len The length of the string
Definition at line 180 of file FileWriter.cpp.
Referenced by affxbpmapwriter::CBPMAPFileWriter::WriteBpmap().
void WriteCString (OFSTREAM & outstr, const char * str)
Writes a string to a little endian binary file
Parameters:
outstr The output file stream.
str The string value to write
Definition at line 144 of file FileWriter.cpp.
References WriteFixedCString(), and WriteUInt32_I().
Referenced by affxchpwriter::CCHPFileWriter::SaveHeader(), WriteCString(), and WriteString_I().
void WriteCString (OFSTREAM & outstr, std::string str)
Definition at line 151 of file FileWriter.cpp.
References WriteCString().
void WriteFixedCString (OFSTREAM & outstr, const char * str, size_t len)
Writes a string to the output file
Parameters:
outstr The output file stream.
str The string value to write
len The length of the string
Definition at line 133 of file FileWriter.cpp.
Referenced by WriteCString(), and WriteFixedString().
void WriteFixedString (OFSTREAM & outstr, const std::string str, size_t len)
Writes a fixed number of bytes of a string to the output file Pads with nulls if the string is shorter than bytes to write
Parameters:
outstr The output file stream.
str The string value to write
len The length of the string
Definition at line 159 of file FileWriter.cpp.
References WriteFixedCString().
Referenced by affxbarwriter::CBARFileWriter::Save(), affxbpmapwriter::CBPMAPFileWriter::WriteBpmap(), affxcel::CCELFileWriter::WriteCompactBCel(), SimpleBinaryFile::WriteRowLabel(), WriteString_N(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
void WriteFloat_I (OFSTREAM & outstr, float val)
Writes a float int to a little endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 105 of file FileWriter.cpp.
References type_punned::v_float, type_punned::v_uint32, and WriteUInt32_I().
Referenced by main(), affxchpwriter::CCHPFileWriter::Save(), affxchpwriter::CCHPFileWriter::SaveExpressionEntry(), affxchpwriter::CCHPFileWriter::SaveHeader(), affxchpwriter::CCHPFileWriter::SaveMappingEntry(), affxchpwriter::CCHPFileWriter::SaveUniversalEntry(), affxchpwriter::CCHPFileUpdater::UpdateExpressionEntry(), affxchpwriter::CCHPFileUpdater::UpdateGenotypeEntry(), and WriteFloatLowPrecision().
void WriteFloat_N (OFSTREAM & outstr, float val)
Writes a float int to a big endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 112 of file FileWriter.cpp.
References type_punned::v_float, type_punned::v_uint32, and WriteUInt32_N().
Referenced by affxbarwriter::CBARFileWriter::Save(), affxbpmapwriter::CBPMAPFileWriter::WriteBpmap(), affxgrd::CGRDFileWriter::WriteCenter(), SimpleBinaryFile::WriteData(), affxgrd::CGRDFileWriter::WriteFixedHeader(), affxgrd::CGRDFileWriter::WriteOptimumCorners(), SimpleBinaryFile::WriteRow(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
void WriteFloatLowPrecision (OFSTREAM & outstr, float val)
Writes a float to a little endian file with just 1 digit of precision.
Parameters:
outstr The output file stream
val The value to write
Definition at line 123 of file FileWriter.cpp.
References WriteFloat_I().
Referenced by affxcel::CCELFileWriter::WriteXDABCel().
void WriteInt16_I (OFSTREAM & outstr, int16_t val)
Writes a signed 16 bit int to a little endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 75 of file FileWriter.cpp.
References WriteUInt16_I().
Referenced by main(), and affxdat::CDATFileData::UpdateGridCorners().
void WriteInt16_N (OFSTREAM & outstr, int16_t val)
Writes a signed 16 bit int to a big endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 86 of file FileWriter.cpp.
References WriteUInt16_N().
void WriteInt32_I (OFSTREAM & outstr, int32_t val)
Writes a signed 32 bit int to a little endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 50 of file FileWriter.cpp.
References WriteUInt32_I().
Referenced by affxchpwriter::CCHPFileWriter::Save(), affxchpwriter::CCHPFileWriter::SaveExpressionEntry(), affxchpwriter::CCHPFileWriter::SaveHeader(), affxchpwriter::CCHPFileWriter::SaveMappingEntry(), affxchpwriter::CCHPFileWriter::SaveUniversalEntry(), affxchpwriter::CCHPFileUpdater::UpdateExpressionEntry(), and affxchpwriter::CCHPFileUpdater::UpdateGenotypeEntry().
void WriteInt32_N (OFSTREAM & outstr, int32_t val)
Writes a signed 32 bit int to a big endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 62 of file FileWriter.cpp.
References WriteUInt32_N().
Referenced by affxbarwriter::CBARFileWriter::Save(), SimpleBinaryFile::UpdateRowCount(), affxgrc::CGRCFileWriter::WriteFile(), SimpleBinaryFile::WriteHeader(), and WriteString_N().
void WriteInt8 (OFSTREAM & outstr, int8_t val)
Writes a signed 8 bit int to a file
Parameters:
outstr The output file stream
val The value to write
Definition at line 98 of file FileWriter.cpp.
References WriteUInt8().
Referenced by affxchpwriter::CCHPFileWriter::Save(), affymetrix_calvin_io::DataSetUpdater::Update(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), affymetrix_calvin_io::DataSetWriter::Write(), affymetrix_calvin_io::DataSetHeaderWriter::WriteColumnTypes(), affymetrix_calvin_io::FileHeaderWriter::WriteMagicNumber(), and affymetrix_calvin_io::FileHeaderWriter::WriteVersion().
void WriteString_I (OFSTREAM & outstr, const std::string str)
Writes a string to a little endian binary file Pads with nulls if the string is shorter than bytes to write
Parameters:
outstr The output file stream.
str The string value to write
Definition at line 165 of file FileWriter.cpp.
References WriteCString().
Referenced by affxcel::CCELFileWriter::WriteCompactBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
void WriteString_N (OFSTREAM & outstr, const std::string str)
Writes a string to a big endian binary file
Parameters:
outstr The output file stream.
str The string value to write
Definition at line 171 of file FileWriter.cpp.
References WriteFixedString(), and WriteInt32_N().
Referenced by main(), affxbarwriter::CBARFileWriter::Save(), affxbpmapwriter::CBPMAPFileWriter::WriteBpmap(), SimpleBinaryFile::WriteHeader(), and affxgrd::CGRDFileWriter::WriteTagHeader().
void WriteUInt16_I (OFSTREAM & outstr, uint16_t val)
Writes an unsigned 16 bit int to a little endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 69 of file FileWriter.cpp.
References htois.
Referenced by main(), affxchpwriter::CCHPFileWriter::SaveExpressionEntry(), affxchpwriter::CCHPFileWriter::SaveHeader(), affxchpwriter::CCHPFileUpdater::UpdateExpressionEntry(), affxcel::CCELFileWriter::WriteCompactBCel(), WriteInt16_I(), and affxcel::CCELFileWriter::WriteXDABCel().
void WriteUInt16_N (OFSTREAM & outstr, uint16_t val)
Writes an unsigned 16 bit int to a big endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 80 of file FileWriter.cpp.
Referenced by affxgrc::CGRCFileWriter::WriteFile(), WriteInt16_N(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
void WriteUInt32_I (OFSTREAM & outstr, uint32_t val)
Writes an unsigned 32 bit int to a little endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 44 of file FileWriter.cpp.
References htoil.
Referenced by main(), affxcel::CCELFileWriter::WriteCompactBCel(), WriteCString(), WriteFloat_I(), WriteInt32_I(), and affxcel::CCELFileWriter::WriteXDABCel().
void WriteUInt32_N (OFSTREAM & outstr, uint32_t val)
Writes an unsigned 32 bit int to a big endian file
Parameters:
outstr The output file stream
val The value to write
Definition at line 56 of file FileWriter.cpp.
Referenced by affxbpmapwriter::CBPMAPFileWriter::WriteBpmap(), affxgrd::CGRDFileWriter::WriteFixedHeader(), WriteFloat_N(), WriteInt32_N(), affxgrd::CGRDFileWriter::WriteOptimumCorners(), affxgrd::CGRDFileWriter::WriteTagHeader(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
void WriteUInt8 (OFSTREAM & outstr, uint8_t val)
Writes an unsigned 8 bit int to a file
Parameters:
outstr The output file stream
val The value to write
Definition at line 93 of file FileWriter.cpp.
Referenced by main(), affxchpwriter::CCHPFileWriter::Save(), affxchpwriter::CCHPFileWriter::SaveExpressionEntry(), affxchpwriter::CCHPFileWriter::SaveMappingEntry(), affymetrix_calvin_io::DataSetUpdater::Update(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntry(), affxchpwriter::CCHPFileUpdater::UpdateExpressionEntry(), affxchpwriter::CCHPFileUpdater::UpdateGenotypeEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntry(), affymetrix_calvin_io::DataSetWriter::Write(), affxbpmapwriter::CBPMAPFileWriter::WriteBpmap(), affxgrc::CGRCFileWriter::WriteFile(), WriteInt8(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().