Affymetrix Fusion SDK: C:/f112/affy/sdk/util/Fs.cpp File Reference
Fs.cpp File Reference
#include "util/Fs.h"
#include "util/Convert.h"
#include "util/Err.h"
#include "util/Util.h"
#include <algorithm>
#include <errno.h>
#include <fstream>
#include <sstream>
#include <dirent.h>
#include <unistd.h>
Defines
#define POSIX_CHMOD ::chmod
#define POSIX_MKDIR ::mkdir
#define POSIX_UNLINK ::unlink
#define FS_ERRNO_STR() std::string("(errno="+ToStr(errno)+")")
Functions
AptErr_t Fs__stat (const std::string &path, struct stat &stat_buf, int &rv, bool abortOnErr)
utility function to fill in a filesystem stat struct.
bool Fs__isreadable (struct stat &stat_buf)
bool Fs__iswriteable (struct stat &stat_buf)
static bool file_starts_with (const std::string &path, const int *magic_bytes)
Does the file exist and start with the sequence of bytes.
static bool _uncheckedFileRename (const std::string &in, const std::string &out, int tries, int sec)
Define Documentation
#define FS_ERRNO_STR () std::string("(errno="+ToStr(errno)+")")
Definition at line 103 of file Fs.cpp.
Referenced by Fs::chmodBasic(), Fs::listDir(), and Fs::rmdir().
#define POSIX_CHMOD ::chmod
Definition at line 97 of file Fs.cpp.
Referenced by Fs::chmodBasic().
#define POSIX_MKDIR ::mkdir
Definition at line 98 of file Fs.cpp.
Referenced by Fs::mkdir().
#define POSIX_UNLINK ::unlink
Definition at line 99 of file Fs.cpp.
Referenced by Fs::rm().
Function Documentation
static bool _uncheckedFileRename (const std::string & in, const std::string & out, int tries, int sec) [static]
Not intended to direct use. Only indirectly via Fs::fileRename() We make multiple attempts to get around read lock issues.
Definition at line 1583 of file Fs.cpp.
References Fs::convertToUncPathW().
Referenced by Fs::fileRename().
static bool file_starts_with (const std::string & path, const int * magic_bytes) [static]
Does the file exist and start with the sequence of bytes.
Parameters:
path path to the file to test.
bytes vector of ints with a terminal "0".
Returns:
true if the file does exist and have the byte sequence.
Definition at line 891 of file Fs.cpp.
References Fs::aptOpen().
Referenced by Fs::isCalvinFile(), and Fs::isHdf5File().
bool Fs__isreadable (struct stat & stat_buf)
Definition at line 161 of file Fs.cpp.
Referenced by Fs::isReadable(), and Fs::isReadableDir().
bool Fs__iswriteable (struct stat & stat_buf)
Definition at line 181 of file Fs.cpp.
Referenced by Fs::isWriteable(), and Fs::isWriteableDir().
AptErr_t Fs__stat (const std::string & path, struct stat & stat_buf, int & rv, bool abortOnErr)
utility function to fill in a filesystem stat struct.
Definition at line 108 of file Fs.cpp.
References APT_ERR, Fs::aptOpen(), Fs::clearErr(), Fs::setErr(), and Fs::UncW().
Referenced by Fs::dirExists(), Fs::exists(), Fs::fileExists(), Fs::fileSize(), Fs::isReadable(), Fs::isReadableDir(), Fs::isWriteable(), and Fs::isWriteableDir().