Affymetrix Fusion SDK: C:/f112/affy/sdk/util/LogStream.cpp File Reference
LogStream.cpp File Reference
Output verbose messages to log file as we go along.
#include "util/LogStream.h"
#include "util/AffxTime.h"
#include "util/Util.h"
Functions
void printHeader (std::ostream *out, bool profile)
std::string toMB (int64_t mem)
Detailed Description
Output verbose messages to log file as we go along.
Author:
Chuck Sugnet
Date:
Tue Mar 21 10:35:22 PST 2006
Definition in file LogStream.cpp.
Function Documentation
void printHeader (std::ostream * out, bool profile)
Definition at line 50 of file LogStream.cpp.
Referenced by LogStream::LogStream(), and LogStream::setStream().
std::string toMB (int64_t mem)
Definition at line 235 of file LogStream.cpp.
References MEGABYTE, and ToStr().
Referenced by LogStream::profileString().