Affymetrix Fusion SDK: C:/f112/affy/sdk/file/SAXDttArrayHandlers.cpp File Reference
SAXDttArrayHandlers.cpp File Reference
#include "file/SAXDttArrayHandlers.h"
#include <cstring>
#include <map>
#include <string>
Functions
static string XMLChToString (const XMLCh *const c1)
static bool operator== (const XMLCh *const &c1, wstring c2)
Variables
XERCES_CPP_NAMESPACE_USE
Function Documentation
static bool operator== (const XMLCh *const & c1, wstring c2) [static]
Comparison operator for XML strings to wide character strings.
Parameters:
c1 The XML string
c2 The wide string
Returns:
True if equal
Definition at line 53 of file SAXDttArrayHandlers.cpp.
static string XMLChToString (const XMLCh *const c1) [static]
Converts a XML character string to string.
Parameters:
c1 The XML string to convert
Returns:
The converted string
Definition at line 36 of file SAXDttArrayHandlers.cpp.
Referenced by affymetrix_dttarray::SAXArrayHandlers::StoreArrayType(), affymetrix_dttarray::SAXArrayHandlers::StoreExperimentNameAttribute(), affymetrix_dttarray::SAXArrayHandlers::StoreNameValueAttributes(), affymetrix_dttarray::SAXArrayHandlers::StoreSampleNameAttribute(), affymetrix_dttarray::SAXArrayHandlers::StoreSampleProjectAttribute(), and affymetrix_dttarray::SAXArrayHandlers::StoreSampleTypeAttribute().
Variable Documentation
XERCES_CPP_NAMESPACE_USE
Definition at line 29 of file SAXDttArrayHandlers.cpp.