Affymetrix Fusion SDK: C:/f112/affy/sdk/calvin_files/writers/src/TemplateFileWriter.cpp File Reference
TemplateFileWriter.cpp File Reference
#include "calvin_files/writers/src/TemplateFileWriter.h"
#include "calvin_files/parsers/src/SAXTemplateHandlers.h"
#include "calvin_files/template/src/TemplateData.h"
#include "calvin_files/template/src/TemplateId.h"
#include "calvin_files/utils/src/AffymetrixGuid.h"
#include <xercesc/dom/DOM.hpp>
#include <xercesc/dom/DOMImplementation.hpp>
#include <xercesc/dom/DOMImplementationLS.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/util/XMLString.hpp>
#include <cstring>
#include <string.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
Classes
class XMLChConversion
Defines
#define TEMPLATE_SET_FILE_VERSION_NUMBER "1.0"
#define ToXMLCh(s) (XMLChConversion(s).String())
Functions
DOMElement * CreateTemplateElement (TemplateData &templateData, DOMDocument *doc, const AffymetrixGuidType &dataTypeIdentifier)
void AddUserAttributes (TemplateData &templateData, DOMDocument *doc, DOMElement *arrayElement)
Define Documentation
#define TEMPLATE_SET_FILE_VERSION_NUMBER "1.0"
The expected version number
Definition at line 55 of file TemplateFileWriter.cpp.
Referenced by CreateTemplateElement().
#define ToXMLCh (s) (XMLChConversion(s).String())
A macro to help with converting a string to XML string
Definition at line 139 of file TemplateFileWriter.cpp.
Referenced by AddUserAttributes(), CreateTemplateElement(), and affymetrix_calvin_io::TemplateFileWriter::Write().
Function Documentation
void AddUserAttributes (TemplateData & templateData, DOMDocument * doc, DOMElement * arrayElement)
Definition at line 160 of file TemplateFileWriter.cpp.
References affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlledVocabulary(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlMultiValues(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::DefaultToString(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::HasDefault(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::RequiredFlag(), TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT_VALUE_ATTRIBUTE, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_ELEMENT, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_DEFAULT_ATTRIBUTE, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_NAME_ATTRIBUTE, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_REQUIRED_ATTRIBUTE, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_TYPE_ATTRIBUTE, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_VALUE_ELEMENT, TEMPLATE_USER_ATTRIBUTES_ELEMENT, ToXMLCh, affymetrix_calvin_template::TemplateData::UserAttributes(), and affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ValueType().
DOMElement* CreateTemplateElement (TemplateData & templateData, DOMDocument * doc, const AffymetrixGuidType & dataTypeIdentifier)
Definition at line 145 of file TemplateFileWriter.cpp.
References affymetrix_calvin_template::TemplateData::CreatedBy(), affymetrix_calvin_template::TemplateData::CreationDateTime(), TEMPLATE_FILE_ELEMENT, TEMPLATE_FILE_ELEMENT_CREATE_DATE_TIME_ATTRIBUTE, TEMPLATE_FILE_ELEMENT_CREATED_BY_ATTRIBUTE, TEMPLATE_FILE_ELEMENT_ID_ATTRIBUTE, TEMPLATE_FILE_ELEMENT_TYPE_ATTRIBUTE, TEMPLATE_FILE_ELEMENT_VERSION_ATTRIBUTE, TEMPLATE_FILE_TYPE_IDENTIFIER, TEMPLATE_SET_FILE_VERSION_NUMBER, affymetrix_calvin_template::TemplateData::TemplateFileIdentifier(), and ToXMLCh.
Referenced by affymetrix_calvin_io::TemplateFileWriter::Write().