Affymetrix Fusion SDK: C:/f112/affy/sdk/file/TsvFile/TsvJoin.cpp File Reference
TsvJoin.cpp File Reference
Class for merging multiple tab separated text files.
#include "file/TsvFile/TsvJoin.h"
#include "util/Fs.h"
#include "util/Guid.h"
#include "util/Util.h"
#include <algorithm>
Functions
void define_tsvjoin_options (PgOptions *opts)
Detailed Description
Class for merging multiple tab separated text files.
Definition in file TsvJoin.cpp.
Function Documentation
void define_tsvjoin_options (PgOptions * opts)
Definition at line 36 of file TsvJoin.cpp.
References PgOpt::BOOL_OPT, PgOptions::defineOption(), PgOptions::setUsage(), and PgOpt::STRING_OPT.
Referenced by tsvJoin::tsvJoin().