Affymetrix Fusion SDK: C:/f112/affy/sdk/util/Util.h File Reference
Util.h File Reference
General Utilities.
#include "portability/affy-base-types.h"
#include "portability/apt-win-dll.h"
#include "util/Convert.h"
#include "util/Err.h"
#include <cassert>
#include <cctype>
#include <cstring>
#include <ctime>
#include <fstream>
#include <string>
#include <vector>
Classes
class Util
Utility functions for memory, etc.
struct Util::ltstr
struct Util::ltstring
class Util::StaticMem
Defines
#define MEGABYTE 1048576
uncomment this to remove functions which are
#define MEMINFO_2GB_MAX (2UL*1024*1024*1024)
#define log2(x) (log((x))/log((2.0)))
Log base two.
#define sqr(x) ((x)*(x))
#define ArraySize(a) (sizeof(a)/sizeof((a)[0]))
Returns the number of elements in the array.
InstanceOf
Check at run time if an object is an instance of a class. This differs from comparing the result of type_id, as it takes inheritance into account. Note that base class must be polymorphic, that is it must have a virtual function or inherit from another class.
Parameters:
objPtr A pointer to the object to check. A pointer must be used, not an object. If necessary, generate an address.
The class name to test against.
Returns:
true if the object is an instance of the class.
#define InstanceOf(objPtr, className) ((bool)(dynamic_cast<const className*>(objPtr) != NULL))
Functions
template<class T >
void Freez (T *&p)
template<class T >
void FreezArray (T *&p)
Detailed Description
General Utilities.
Author:
Chuck Sugnet
Date:
Mon May 16 15:52:31 2005
Definition in file Util.h.
Define Documentation
#define ArraySize (a) (sizeof(a)/sizeof((a)[0]))
Returns the number of elements in the array.
Definition at line 72 of file Util.h.
#define InstanceOf (objPtr, className) ((bool)(dynamic_cast<const className*>(objPtr) != NULL))
Definition at line 92 of file Util.h.
#define log2 (x) (log((x))/log((2.0)))
Log base two.
Definition at line 66 of file Util.h.
#define MEGABYTE 1048576
uncomment this to remove functions which are
Definition at line 49 of file Util.h.
Referenced by Util::asMB(), and toMB().
#define MEMINFO_2GB_MAX (2UL*1024*1024*1024)
386 systems cant map more than 2GB of user memory. (unless you have a patched kernel...)
Definition at line 62 of file Util.h.
Referenced by Util::memInfo().
#define sqr (x) ((x)*(x))
Square of the two numbers (Note: this is bad style due to X being evaled twice.)
Definition at line 69 of file Util.h.
Function Documentation
template<class T > void Freez (T *& p) [inline]
delete function that deletes the pointer and sets it to NULL.
Definition at line 75 of file Util.h.
Referenced by BaseEngine::checkDiskSpace(), BaseEngine::checkOptions(), BaseEngine::run(), and BaseEngine::~BaseEngine().
template<class T > void FreezArray (T *& p) [inline]
delete function that deletes an array and sets the pointer to NULL.
Definition at line 77 of file Util.h.
Referenced by FrugalVector< T >::clear(), RowFile::nextCStringRow(), and SocketBase::sendMsg().