Affymetrix Fusion SDK: C:/f112/affy/sdk/file/TsvFile/apt-tsv-join.cpp File Reference
apt-tsv-join.cpp File Reference
Main for merging multiple tab separated text files.
#include "file/TsvFile/TsvJoin.h"
#include "util/AptVersionInfo.h"
Functions
int main (int argc, const char *argv[])
Detailed Description
Main for merging multiple tab separated text files.
/ /
Definition in file apt-tsv-join.cpp.
Function Documentation
int main (int argc, const char * argv[])
Definition at line 33 of file apt-tsv-join.cpp.
References Verbose::out(), tsvJoin::run(), and AptVersionInfo::versionToReport().