Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPQuantificationData Class Reference
affymetrix_fusion_io::FusionCHPQuantificationData Class Reference
#include <FusionCHPQuantificationData.h>
Classes
class Reg
Public Member Functions
~FusionCHPQuantificationData ()
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()
affymetrix_calvin_io::GenericData * GetGenericData ()
affymetrix_calvin_io::DataSetHeader & GetDataSetHeader ()
affymetrix_calvin_utilities::AffymetrixGuidType GetObjectName ()
std::wstring GetAlgName ()
std::wstring GetAlgVersion ()
std::wstring GetArrayType ()
ParameterNameValueTypeList GetAlgParams ()
ParameterNameValueTypeList GetSummaryParams ()
int32_t GetEntryCount ()
void GetQuantificationEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationData &entry)
Static Public Member Functions
static
FusionCHPQuantificationData * FromBase (FusionCHPData *chip)
Static Public Attributes
static Reg reg
Private Member Functions
FusionCHPQuantificationData ()
bool Read ()
bool ReadHeader ()
Private Attributes
affymetrix_calvin_io::CHPQuantificationData chpData
Detailed Description
This class provides storage and reading capabilities for quantification CHP files
Definition at line 34 of file FusionCHPQuantificationData.h.
Constructor & Destructor Documentation
FusionCHPQuantificationData::FusionCHPQuantificationData () [private]
Constructor
Definition at line 40 of file FusionCHPQuantificationData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationData::Reg::MakeObject().
FusionCHPQuantificationData::~FusionCHPQuantificationData ()
Destructor
Definition at line 47 of file FusionCHPQuantificationData.cpp.
Member Function Documentation
AffymetrixGuidType FusionCHPQuantificationData::FileId () [virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 96 of file FusionCHPQuantificationData.cpp.
Referenced by CFusionCHPQuantificationDataCOM::get_FileId().
FusionCHPQuantificationData * FusionCHPQuantificationData::FromBase (FusionCHPData * chip) [static]
Converts the type to the quantification CHP type.
Parameters:
chip The pointer to the CHP data object.
Returns:
The quantification CHP data type or NULL if not compatible.
Definition at line 81 of file FusionCHPQuantificationData.cpp.
References affymetrix_fusion_io::FusionCHPData::GetObjectName(), and ObjectName.
std::wstring affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgName () [inline]
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 66 of file FusionCHPQuantificationData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationData::GetAlgName().
Referenced by CFusionCHPQuantificationDataCOM::get_AlgName().
ParameterNameValueTypeList affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgParams () [inline]
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 79 of file FusionCHPQuantificationData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationData::GetAlgParams().
Referenced by CFusionCHPQuantificationDataCOM::get_AlgorithmParameters().
std::wstring affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgVersion () [inline]
Gets the algorithm version.
Returns:
The version.
Definition at line 71 of file FusionCHPQuantificationData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationData::GetAlgVersion().
Referenced by CFusionCHPQuantificationDataCOM::get_AlgVersion().
std::wstring affymetrix_fusion_io::FusionCHPQuantificationData::GetArrayType () [inline]
Sets the array type
Definition at line 74 of file FusionCHPQuantificationData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationData::GetArrayType().
Referenced by CFusionCHPQuantificationDataCOM::get_ArrayType().
affymetrix_calvin_io::DataSetHeader& affymetrix_fusion_io::FusionCHPQuantificationData::GetDataSetHeader () [inline]
Returns the data set header.
Definition at line 58 of file FusionCHPQuantificationData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationData::GetDataSetHeader().
int32_t affymetrix_fusion_io::FusionCHPQuantificationData::GetEntryCount () [inline]
Gets the number of entries (probe sets)
Definition at line 87 of file FusionCHPQuantificationData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationData::GetEntryCount().
Referenced by CFusionCHPQuantificationDataCOM::get_EntryCount().
GenericData * FusionCHPQuantificationData::GetGenericData () [virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 104 of file FusionCHPQuantificationData.cpp.
AffymetrixGuidType FusionCHPQuantificationData::GetObjectName () [virtual]
Gets the class name.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 88 of file FusionCHPQuantificationData.cpp.
References ObjectName.
void affymetrix_fusion_io::FusionCHPQuantificationData::GetQuantificationEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationData & entry) [inline]
Gets the sequence data.
Parameters:
index The row index.
entry The quantification value.
Definition at line 93 of file FusionCHPQuantificationData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationData::GetQuantificationEntry().
Referenced by CFusionCHPQuantificationDataCOM::GetQuantificationEntry().
ParameterNameValueTypeList affymetrix_fusion_io::FusionCHPQuantificationData::GetSummaryParams () [inline]
Gets the summary parameters
Returns:
The summary parameters.
Definition at line 84 of file FusionCHPQuantificationData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationData::GetSummaryParams().
Referenced by CFusionCHPQuantificationDataCOM::get_SummaryParameters().
bool FusionCHPQuantificationData::Read () [private, virtual]
Reads the CHP file.
Returns:
True if successful.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 63 of file FusionCHPQuantificationData.cpp.
References affymetrix_calvin_io::CHPQuantificationFileReader::Read(), and affymetrix_calvin_io::CHPQuantificationFileReader::SetFilename().
bool FusionCHPQuantificationData::ReadHeader () [private, virtual]
Reads the header of the CHP file
Returns:
True if successful
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 55 of file FusionCHPQuantificationData.cpp.
Member Data Documentation
affymetrix_calvin_io::CHPQuantificationData affymetrix_fusion_io::FusionCHPQuantificationData::chpData [private]
The CHP object.
Definition at line 42 of file FusionCHPQuantificationData.h.
Referenced by GetAlgName(), GetAlgParams(), GetAlgVersion(), GetArrayType(), GetDataSetHeader(), GetEntryCount(), GetQuantificationEntry(), and GetSummaryParams().
FusionCHPQuantificationData::Reg FusionCHPQuantificationData::reg [static]
The one and only registration object. This registers the class as a CHP reader.
Used to register the CHP reader.
Definition at line 127 of file FusionCHPQuantificationData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPQuantificationData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPQuantificationData.cpp