Affymetrix Fusion SDK: affymetrix_calvin_io::DataSetUpdater Class Reference
affymetrix_calvin_io::DataSetUpdater Class Reference
#include <DataSetUpdater.h>
Public Member Functions
DataSetUpdater ()
~DataSetUpdater ()
virtual void Initialize (const char *file)
void Update (int groupIndex, int setIndex, int row, int col, const std::string &value)
void Update (int groupIndex, int setIndex, int row, int col, const std::wstring &value)
void Update (int groupIndex, int setIndex, int row, int col, int8_t value)
void Update (int groupIndex, int setIndex, int row, int col, int16_t value)
void Update (int groupIndex, int setIndex, int row, int col, int32_t value)
void Update (int groupIndex, int setIndex, int row, int col, u_int8_t value)
void Update (int groupIndex, int setIndex, int row, int col, u_int16_t value)
void Update (int groupIndex, int setIndex, int row, int col, u_int32_t value)
void Update (int groupIndex, int setIndex, int row, int col, float value)
Protected Member Functions
void SeekToPosition (std::ofstream &os, int groupIndex, int setIndex, int row, int col)
Protected Attributes
std::string fileName
std::vector< std::vector< int > > positions
std::vector< std::vector< int > > rowsizes
std::vector< std::vector
< std::vector< int > > > colsizes
std::vector< std::vector
< std::wstring > > dataSetNames
Detailed Description
Provides interfaces to update data in a "Calvin" binary data file. This class assumes that the file has been completely written and that only existing data groups/sets/rows/cols are being modified.
Definition at line 41 of file DataSetUpdater.h.
Constructor & Destructor Documentation
DataSetUpdater::DataSetUpdater ()
Constructor
Definition at line 35 of file DataSetUpdater.cpp.
DataSetUpdater::~DataSetUpdater ()
Destructor
Definition at line 42 of file DataSetUpdater.cpp.
Member Function Documentation
void DataSetUpdater::Initialize (const char * file) [virtual]
Initialize the class given a "calvin" data file.
Parameters:
file The name of the file.
Exceptions:
affymetrix_calvin_exceptions::FileNotFoundException The file does not exist.
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Reimplemented in affymetrix_calvin_io::CalvinCHPFileUpdater, and affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater.
Definition at line 49 of file DataSetUpdater.cpp.
References affymetrix_calvin_io::GenericFileReader::Close(), affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), affymetrix_calvin_io::DataSetHeader::GetName(), affymetrix_calvin_io::DataSetHeader::GetRowSize(), affymetrix_calvin_io::ColumnInfo::GetSize(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::GenericFileReader::Open(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
void DataSetUpdater::SeekToPosition (std::ofstream & os, int groupIndex, int setIndex, int row, int col) [protected]
Seek to the position of the data.
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
Definition at line 86 of file DataSetUpdater.cpp.
Referenced by affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateChromosomeSegmentEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateChromosomeSummaryEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantification(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateFamilialSampleEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateFamilialSegmentOverlapEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataAllelePeaksEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCopyNumberVariationRegionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCytoGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCytoRegionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataExpressionEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataExpressionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntry(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataMarkerABSignalsEntryBuffer().
void DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, u_int32_t value)
Updates an integer value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
Definition at line 176 of file DataSetUpdater.cpp.
References affymetrix_calvin_io::FileOutput::WriteUInt32().
void DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, u_int16_t value)
Updates an integer value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
Definition at line 165 of file DataSetUpdater.cpp.
References affymetrix_calvin_io::FileOutput::WriteUInt16().
void DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, u_int8_t value)
Updates an integer value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
Definition at line 154 of file DataSetUpdater.cpp.
References WriteUInt8().
void DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, int32_t value)
Updates an integer value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
Definition at line 143 of file DataSetUpdater.cpp.
References affymetrix_calvin_io::FileOutput::WriteInt32().
void DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, int16_t value)
Updates an integer value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
Definition at line 132 of file DataSetUpdater.cpp.
References affymetrix_calvin_io::FileOutput::WriteInt16().
void DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, int8_t value)
Updates an integer value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
Definition at line 121 of file DataSetUpdater.cpp.
References WriteInt8().
void affymetrix_calvin_io::DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, const std::wstring & value)
Updates a wstring value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
void affymetrix_calvin_io::DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, const std::string & value)
Updates a string value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
Referenced by affymetrix_calvin_io::CalvinCHPQuantificationDetectionFileUpdater::UpdateDetection(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMultiData(), affymetrix_calvin_io::CalvinCHPQuantificationFileUpdater::UpdateQuantification(), and affymetrix_calvin_io::CalvinCHPQuantificationDetectionFileUpdater::UpdateQuantification().
void DataSetUpdater::Update (int groupIndex, int setIndex, int row, int col, float value)
Updates a floating point value in the data set
Parameters:
groupIndex The index to the data groups.
setIndex The index to the data sets.
row The index to the rows.
col The index to the columns.
value The new value.
Definition at line 187 of file DataSetUpdater.cpp.
References affymetrix_calvin_io::FileOutput::WriteFloat().
Member Data Documentation
std::vector<std::vector<std::vector<int> > > affymetrix_calvin_io::DataSetUpdater::colsizes [protected]
The size of a column for all data sets in the file.
Definition at line 54 of file DataSetUpdater.h.
Referenced by affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateExpressionQuantificationBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataExpressionEntryBuffer(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer().
std::vector<std::vector<std::wstring> > affymetrix_calvin_io::DataSetUpdater::dataSetNames [protected]
The data set names.
Definition at line 57 of file DataSetUpdater.h.
Referenced by affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::Initialize(), and affymetrix_calvin_io::CalvinCHPFileUpdater::Initialize().
std::string affymetrix_calvin_io::DataSetUpdater::fileName [protected]
The name of the file being updated.
Definition at line 45 of file DataSetUpdater.h.
std::vector<std::vector<int> > affymetrix_calvin_io::DataSetUpdater::positions [protected]
The position of a data set for all data sets in the file.
Definition at line 48 of file DataSetUpdater.h.
std::vector<std::vector<int> > affymetrix_calvin_io::DataSetUpdater::rowsizes [protected]
The size of a row for all data sets in the file.
Definition at line 51 of file DataSetUpdater.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DataSetUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/DataSetUpdater.cpp