Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPTilingData Class Reference
affymetrix_fusion_io::FusionCHPTilingData Class Reference
#include <FusionCHPTilingData.h>
Classes
class Reg
Public Member Functions
~FusionCHPTilingData ()
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()
affymetrix_calvin_io::GenericData * GetGenericData ()
affymetrix_calvin_utilities::AffymetrixGuidType GetObjectName ()
int GetNumberSequences ()
std::wstring GetAlgName ()
std::wstring GetAlgVersion ()
ParameterNameValueTypeList GetAlgParams ()
TilingSequenceData GetTilingSequenceData ()
int32_t GetTilingSequenceEntryCount (int index)
void OpenTilingSequenceDataSet (int index)
void GetTilingSequenceEntry (int row, affymetrix_calvin_io::CHPTilingEntry &e)
Static Public Member Functions
static FusionCHPTilingData * FromBase (FusionCHPData *chip)
Private Member Functions
FusionCHPTilingData ()
bool Read ()
bool ReadHeader ()
Private Attributes
affymetrix_calvin_io::CHPTilingData chpData
Static Private Attributes
static Reg reg
Detailed Description
This class provides storage and reading capabilities for tiling CHP files
Definition at line 34 of file FusionCHPTilingData.h.
Constructor & Destructor Documentation
FusionCHPTilingData::FusionCHPTilingData () [private]
Constructor
Definition at line 40 of file FusionCHPTilingData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPTilingData::Reg::MakeObject().
FusionCHPTilingData::~FusionCHPTilingData ()
Destructor
Definition at line 47 of file FusionCHPTilingData.cpp.
Member Function Documentation
AffymetrixGuidType FusionCHPTilingData::FileId () [virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 96 of file FusionCHPTilingData.cpp.
FusionCHPTilingData * FusionCHPTilingData::FromBase (FusionCHPData * chip) [static]
Converts the type to the tiling CHP type.
Parameters:
chip The pointer to the CHP data object.
Returns:
The tiling CHP data type or NULL if not compatible.
Definition at line 81 of file FusionCHPTilingData.cpp.
References affymetrix_fusion_io::FusionCHPData::GetObjectName(), and ObjectName.
std::wstring affymetrix_fusion_io::FusionCHPTilingData::GetAlgName () [inline]
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 68 of file FusionCHPTilingData.h.
References chpData, and affymetrix_calvin_io::CHPTilingData::GetAlgName().
ParameterNameValueTypeList affymetrix_fusion_io::FusionCHPTilingData::GetAlgParams () [inline]
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 78 of file FusionCHPTilingData.h.
References chpData, and affymetrix_calvin_io::CHPTilingData::GetAlgParams().
std::wstring affymetrix_fusion_io::FusionCHPTilingData::GetAlgVersion () [inline]
Gets the algorithm version.
Returns:
The version.
Definition at line 73 of file FusionCHPTilingData.h.
References chpData, and affymetrix_calvin_io::CHPTilingData::GetAlgVersion().
GenericData * FusionCHPTilingData::GetGenericData () [virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 104 of file FusionCHPTilingData.cpp.
int affymetrix_fusion_io::FusionCHPTilingData::GetNumberSequences () [inline]
Gets the number of sequence stored in the file.
Returns:
The number of sequence stored in the file.
Definition at line 63 of file FusionCHPTilingData.h.
References chpData, and affymetrix_calvin_io::CHPTilingData::GetNumberSequences().
AffymetrixGuidType FusionCHPTilingData::GetObjectName () [virtual]
Gets the class name.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 88 of file FusionCHPTilingData.cpp.
References ObjectName.
TilingSequenceData affymetrix_fusion_io::FusionCHPTilingData::GetTilingSequenceData () [inline]
Gets the sequence data.
Returns:
The data associated with the sequence.
Definition at line 83 of file FusionCHPTilingData.h.
References chpData, and affymetrix_calvin_io::CHPTilingData::GetTilingSequenceData().
void affymetrix_fusion_io::FusionCHPTilingData::GetTilingSequenceEntry (int row, affymetrix_calvin_io::CHPTilingEntry & e) [inline]
Returns the entry for the given row. The data set must be open.
Parameters:
row The row index.
e The entry.
Definition at line 100 of file FusionCHPTilingData.h.
References chpData, and affymetrix_calvin_io::CHPTilingData::GetTilingSequenceEntry().
int32_t affymetrix_fusion_io::FusionCHPTilingData::GetTilingSequenceEntryCount (int index) [inline]
Gets the number of entries in a tiling sequence.
Parameters:
index The sequence index.
Returns:
The number of entries in the sequence.
Definition at line 89 of file FusionCHPTilingData.h.
References chpData, and affymetrix_calvin_io::CHPTilingData::GetTilingSequenceEntryCount().
void affymetrix_fusion_io::FusionCHPTilingData::OpenTilingSequenceDataSet (int index) [inline]
Opens a group for reading.
Parameters:
index The index to the sequence.
Definition at line 94 of file FusionCHPTilingData.h.
References chpData, and affymetrix_calvin_io::CHPTilingData::OpenTilingSequenceDataSet().
bool FusionCHPTilingData::Read () [private, virtual]
Reads the CHP file.
Returns:
True if successful.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 63 of file FusionCHPTilingData.cpp.
References affymetrix_calvin_io::CHPTilingFileReader::Read(), and affymetrix_calvin_io::CHPTilingFileReader::SetFilename().
bool FusionCHPTilingData::ReadHeader () [private, virtual]
Reads the header of the CHP file
Returns:
True if successful
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 55 of file FusionCHPTilingData.cpp.
Member Data Documentation
affymetrix_calvin_io::CHPTilingData affymetrix_fusion_io::FusionCHPTilingData::chpData [private]
The CHP object.
Definition at line 42 of file FusionCHPTilingData.h.
Referenced by GetAlgName(), GetAlgParams(), GetAlgVersion(), GetNumberSequences(), GetTilingSequenceData(), GetTilingSequenceEntry(), GetTilingSequenceEntryCount(), and OpenTilingSequenceDataSet().
FusionCHPTilingData::Reg FusionCHPTilingData::reg [static, private]
The one and only registration object. This registers the class as a CHP reader.
Used to register the CHP reader.
Definition at line 134 of file FusionCHPTilingData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPTilingData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPTilingData.cpp