Affymetrix Fusion SDK: affymetrix_fusion_io::FusionGenotypeProbeSetResults Class Reference
affymetrix_fusion_io::FusionGenotypeProbeSetResults Class Reference
#include <FusionProbeSetResults.h>
Public Member Functions
void Clear ()
u_int8_t GetAlleleCall ()
The allele call.
float GetConfidence ()
The confidence associated with the allele call.
float GetRAS1 ()
The relative allele strength for the first block.
float GetRAS2 ()
The relative allele strength for the second block.
float GetPValueAA ()
The p-value associated with an AA call.
float GetPValueAB ()
The p-value associated with an AB call.
float GetPValueBB ()
The p-value associated with an BB call.
float GetPValueNoCall ()
The p-value associated with an no call call.
void SetAlleleCall (u_int8_t p)
Sets the allele call.
void SetConfidence (float p)
The confidence associated with the allele call.
void SetRAS1 (float p)
Sets the relative allele strength for the first block.
void SetRAS2 (float p)
Sets the relative allele strength for the second block.
void SetPValueAA (float p)
Sets the p-value associated with an AA call.
void SetPValueAB (float p)
Sets the p-value associated with an AB call.
void SetPValueBB (float p)
Sets the p-value associated with an BB call.
void SetPValueNoCall (float p)
Sets the p-value associated with an no call call.
std::string GetAlleleCallString ()
Gets a string representation of the allele call.
FusionGenotypeProbeSetResults operator= (FusionGenotypeProbeSetResults &src)
Assignment operator.
FusionGenotypeProbeSetResults ()
Constructor.
~FusionGenotypeProbeSetResults ()
Destructor.
Private Attributes
u_int8_t alleleCall
float confidence
float RAS1
float RAS2
float pValueAA
float pValueAB
float pValueBB
float pValueNoCall
Detailed Description
Genotyping analysis probe set results
Definition at line 254 of file FusionProbeSetResults.h.
Constructor & Destructor Documentation
FusionGenotypeProbeSetResults::FusionGenotypeProbeSetResults ()
Constructor.
Definition at line 250 of file FusionProbeSetResults.cpp.
References Clear().
FusionGenotypeProbeSetResults::~FusionGenotypeProbeSetResults ()
Destructor.
Definition at line 255 of file FusionProbeSetResults.cpp.
Member Function Documentation
void FusionGenotypeProbeSetResults::Clear (void)
Definition at line 270 of file FusionProbeSetResults.cpp.
References SetAlleleCall(), SetConfidence(), SetPValueAA(), SetPValueAB(), SetPValueBB(), SetPValueNoCall(), SetRAS1(), and SetRAS2().
Referenced by FusionGenotypeProbeSetResults().
u_int8_t FusionGenotypeProbeSetResults::GetAlleleCall ()
The allele call.
Returns:
Allele call.
Definition at line 282 of file FusionProbeSetResults.cpp.
References alleleCall.
Referenced by CFusionGenotypeProbeSetResultsCOM::get_AlleleCall(), GetAlleleCallString(), and operator=().
std::string FusionGenotypeProbeSetResults::GetAlleleCallString ()
Gets a string representation of the allele call.
Returns:
Allele call.
Definition at line 362 of file FusionProbeSetResults.cpp.
References ALLELE_A_CALL, ALLELE_AB_CALL, ALLELE_B_CALL, and GetAlleleCall().
Referenced by CFusionGenotypeProbeSetResultsCOM::GetAlleleCallString().
float FusionGenotypeProbeSetResults::GetConfidence ()
The confidence associated with the allele call.
Returns:
Confidence.
Definition at line 287 of file FusionProbeSetResults.cpp.
References confidence.
Referenced by CFusionGenotypeProbeSetResultsCOM::get_Confidence(), and operator=().
float FusionGenotypeProbeSetResults::GetPValueAA ()
The p-value associated with an AA call.
Returns:
pvalue for AA.
Definition at line 302 of file FusionProbeSetResults.cpp.
References pValueAA.
Referenced by CFusionGenotypeProbeSetResultsCOM::get_PValueAA(), and operator=().
float FusionGenotypeProbeSetResults::GetPValueAB ()
The p-value associated with an AB call.
Returns:
pvalue for AB.
Definition at line 307 of file FusionProbeSetResults.cpp.
References pValueAB.
Referenced by CFusionGenotypeProbeSetResultsCOM::get_PValueAB(), and operator=().
float FusionGenotypeProbeSetResults::GetPValueBB ()
The p-value associated with an BB call.
Returns:
pvalue for BB.
Definition at line 312 of file FusionProbeSetResults.cpp.
References pValueBB.
Referenced by CFusionGenotypeProbeSetResultsCOM::get_PValueBB(), and operator=().
float FusionGenotypeProbeSetResults::GetPValueNoCall ()
The p-value associated with an no call call.
Returns:
pvalue no call.
Definition at line 317 of file FusionProbeSetResults.cpp.
References pValueNoCall.
Referenced by CFusionGenotypeProbeSetResultsCOM::get_PValueNoCall(), and operator=().
float FusionGenotypeProbeSetResults::GetRAS1 ()
The relative allele strength for the first block.
Returns:
RAS1.
Definition at line 292 of file FusionProbeSetResults.cpp.
References RAS1.
Referenced by CFusionGenotypeProbeSetResultsCOM::get_RAS1(), and operator=().
float FusionGenotypeProbeSetResults::GetRAS2 ()
The relative allele strength for the second block.
Returns:
RAS2.
Definition at line 297 of file FusionProbeSetResults.cpp.
References RAS2.
Referenced by CFusionGenotypeProbeSetResultsCOM::get_RAS2(), and operator=().
FusionGenotypeProbeSetResults FusionGenotypeProbeSetResults::operator= (FusionGenotypeProbeSetResults & src)
Assignment operator.
Parameters:
src Object to copy
Returns:
Copied object
Definition at line 257 of file FusionProbeSetResults.cpp.
References GetAlleleCall(), GetConfidence(), GetPValueAA(), GetPValueAB(), GetPValueBB(), GetPValueNoCall(), GetRAS1(), GetRAS2(), SetAlleleCall(), SetConfidence(), SetPValueAA(), SetPValueAB(), SetPValueBB(), SetPValueNoCall(), SetRAS1(), and SetRAS2().
void FusionGenotypeProbeSetResults::SetAlleleCall (u_int8_t p)
Sets the allele call.
Parameters:
p Allele call to set.
Definition at line 322 of file FusionProbeSetResults.cpp.
References alleleCall.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), and operator=().
void FusionGenotypeProbeSetResults::SetConfidence (float p)
The confidence associated with the allele call.
Parameters:
p Confidence to value to set.
Definition at line 327 of file FusionProbeSetResults.cpp.
References confidence.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), and operator=().
void FusionGenotypeProbeSetResults::SetPValueAA (float p)
Sets the p-value associated with an AA call.
Parameters:
p pvalue aa to set.
Definition at line 342 of file FusionProbeSetResults.cpp.
References pValueAA.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), and operator=().
void FusionGenotypeProbeSetResults::SetPValueAB (float p)
Sets the p-value associated with an AB call.
Parameters:
p pvalue AB to set.
Definition at line 347 of file FusionProbeSetResults.cpp.
References pValueAB.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), and operator=().
void FusionGenotypeProbeSetResults::SetPValueBB (float p)
Sets the p-value associated with an BB call.
Parameters:
p pvalue BB to set.
Definition at line 352 of file FusionProbeSetResults.cpp.
References pValueBB.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), and operator=().
void FusionGenotypeProbeSetResults::SetPValueNoCall (float p)
Sets the p-value associated with an no call call.
Parameters:
p pvalue no call to set.
Definition at line 357 of file FusionProbeSetResults.cpp.
References pValueNoCall.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), and operator=().
void FusionGenotypeProbeSetResults::SetRAS1 (float p)
Sets the relative allele strength for the first block.
Parameters:
p RAS1 value to set.
Definition at line 332 of file FusionProbeSetResults.cpp.
References RAS1.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), and operator=().
void FusionGenotypeProbeSetResults::SetRAS2 (float p)
Sets the relative allele strength for the second block.
Parameters:
p RAS2 value to set.
Definition at line 337 of file FusionProbeSetResults.cpp.
References RAS2.
Referenced by Clear(), affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenotypingResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), and operator=().
Member Data Documentation
u_int8_t affymetrix_fusion_io::FusionGenotypeProbeSetResults::alleleCall [private]
The allele call
Definition at line 258 of file FusionProbeSetResults.h.
Referenced by GetAlleleCall(), and SetAlleleCall().
float affymetrix_fusion_io::FusionGenotypeProbeSetResults::confidence [private]
The confidence associated with the allele call
Definition at line 261 of file FusionProbeSetResults.h.
Referenced by GetConfidence(), and SetConfidence().
float affymetrix_fusion_io::FusionGenotypeProbeSetResults::pValueAA [private]
The p-value associated with an AA call
Definition at line 270 of file FusionProbeSetResults.h.
Referenced by GetPValueAA(), and SetPValueAA().
float affymetrix_fusion_io::FusionGenotypeProbeSetResults::pValueAB [private]
The p-value associated with an AB call
Definition at line 273 of file FusionProbeSetResults.h.
Referenced by GetPValueAB(), and SetPValueAB().
float affymetrix_fusion_io::FusionGenotypeProbeSetResults::pValueBB [private]
The p-value associated with an BB call
Definition at line 276 of file FusionProbeSetResults.h.
Referenced by GetPValueBB(), and SetPValueBB().
float affymetrix_fusion_io::FusionGenotypeProbeSetResults::pValueNoCall [private]
The p-value associated with an no call call
Definition at line 279 of file FusionProbeSetResults.h.
Referenced by GetPValueNoCall(), and SetPValueNoCall().
float affymetrix_fusion_io::FusionGenotypeProbeSetResults::RAS1 [private]
The relative allele strength for the first block
Definition at line 264 of file FusionProbeSetResults.h.
Referenced by GetRAS1(), and SetRAS1().
float affymetrix_fusion_io::FusionGenotypeProbeSetResults::RAS2 [private]
The relative allele strength for the second block
Definition at line 267 of file FusionProbeSetResults.h.
Referenced by GetRAS2(), and SetRAS2().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.cpp