Affymetrix Fusion SDK: SocketServer Class Reference
SocketServer Class Reference
#include <SocketServer.h>
Public Member Functions
SocketServer ()
Constructor.
~SocketServer ()
Destructor, clean up open sockets.
unsigned int socketOpen (const std::string &host, unsigned int &startPort)
bool socketOpen (const std::string &host, const std::string &port)
bool checkForMsgs (std::vector< std::string > &messages)
bool processNewMessages ()
void sendMsg (const std::string &msg, int type, int channel)
bool acceptNewConnection ()
bool isConnected ()
void cleanUp ()
Static Public Member Functions
static void * getInAddr (struct sockaddr *sa)
Private Attributes
int m_ListenSocket
listening socket descriptor for new connection
int m_RWSocket
Client socket for reading and writing.
std::string m_Port
Port open for new connections. ///< Address information for socket connections.
Detailed Description
Basic version of a server that will listen for connections on a dedicated socket and then listen on those connections for new messages from clients.
Definition at line 40 of file SocketServer.h.
Constructor & Destructor Documentation
SocketServer::SocketServer ()
Constructor.
Definition at line 37 of file SocketServer.cpp.
References Err::errAbort().
SocketServer::~SocketServer ()
Destructor, clean up open sockets.
Definition at line 47 of file SocketServer.cpp.
Member Function Documentation
bool SocketServer::acceptNewConnection ()
See if any clients have connected to server.
Returns:
- Number of clients connected in this function
Definition at line 159 of file SocketServer.cpp.
References APT_ERR_ABORT, Verbose::out(), and ToStr().
Referenced by SocketEngine::doUnix(), and SocketEngine::doWindows().
bool SocketServer::checkForMsgs (std::vector< std::string > & messages)
Try reading from the socket to see if there is anything sent.
Parameters:
messages - data from the socket as delivered by recv()
Definition at line 141 of file SocketServer.cpp.
References APT_ERR_ABORT, and SocketBase::checkForMsgs().
void SocketServer::cleanUp ()
Definition at line 51 of file SocketServer.cpp.
References CLOSE_SOCKET.
Referenced by SocketEngine::doWindows(), and SocketEngine::TerminateLaunchedApp().
void * SocketServer::getInAddr (struct sockaddr * sa) [static]
Wrapper to get IPv4 or IPv6 as appropriate
Parameters:
sa - Pointer to socket address structure
Returns:
- Pointer to correct socket address
Definition at line 197 of file SocketServer.cpp.
bool SocketServer::isConnected ()
Check to see if the server has any connections yet.
Returns:
Definition at line 137 of file SocketServer.cpp.
Referenced by SocketEngine::doUnix(), and SocketEngine::doWindows().
bool SocketServer::processNewMessages ()
Try reading from the socket to see if there is anything sent.
Definition at line 148 of file SocketServer.cpp.
References SocketBase::checkForMsgs().
Referenced by SocketEngine::doUnix(), and SocketEngine::doWindows().
void SocketServer::sendMsg (const std::string & msg, int type, int channel)
Write string to open socket.
Parameters:
msg - Message to write into the socket
Definition at line 152 of file SocketServer.cpp.
References APT_ERR_ABORT, and SocketBase::sendMsg().
unsigned int SocketServer::socketOpen (const std::string & host, unsigned int & startPort)
Open a connection to a listening server with a range of possible ports to try.
Parameters:
host - ip address or name of computer to open connection on, often just 127.0.0.1
port - which port number to start the open connection request with.
This is current coded to allow for 5 trys. TBD: is this a good number of ports Should the caller control the number of trys.
Definition at line 64 of file SocketServer.cpp.
References ToStr().
Referenced by SocketEngine::run().
bool SocketServer::socketOpen (const std::string & host, const std::string & port)
Open a connection to a listening server.
Parameters:
host - ip address or name of computer to open connection on, often just 127.0.0.1
port - which port to open.
Definition at line 84 of file SocketServer.cpp.
References CLOSE_SOCKET.
Member Data Documentation
int SocketServer::m_ListenSocket [private]
listening socket descriptor for new connection
Definition at line 114 of file SocketServer.h.
std::string SocketServer::m_Port [private]
Port open for new connections. ///< Address information for socket connections.
Definition at line 116 of file SocketServer.h.
int SocketServer::m_RWSocket [private]
Client socket for reading and writing.
Definition at line 115 of file SocketServer.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/SocketServer.h
C:/f112/affy/sdk/util/SocketServer.cpp