Affymetrix Fusion SDK: PgOpt Class Reference
PgOpt Class Reference
The definition of this option and the values.
#include <PgOptions.h>
Public Types
enum PgOptType {
INVALID_OPT, BOOL_OPT, DOUBLE_OPT, INT_OPT,
STRING_OPT
}
typedef enum PgOpt::PgOptType PgOptType_t
Public Member Functions
PgOpt ()
Creates and inits a new PgOpt.
PgOpt (const PgOpt *orig)
void allowMutipleValues (int val)
Allows mutiple values for this option?
bool isSet ()
was this option set by the user?
int getValueCount () const
The number of values for this option.
std::string getValue (size_t idx=0) const
Get the string value of this option.
bool getValueBool (int idx=0) const
Get the value as a boolean. Abort if it cant be converted.
int getValueInt (int idx=0) const
Get the value as an int. Abort if it cant be converted.
double getValueDouble (int idx=0) const
Get the value as a double. Abort if it cant be converted.
std::string getDefaultValue () const
The default value of this option.
void clearValues ()
Clear all the values on this option.
void setValue (const std::string &new_value)
Set the value of this option to a single value.
void pushValue (const std::string &new_value)
Push the new value onto the list of values for this option.
void resetToDefault ()
same as clearValues()
std::vector< std::string > getValueVector () const
int checkParseIsOk (const std::string &value) const
Check to see if the parse of the string is ok for this option.
void push_user_values_into (std::vector< std::string > &dest_vec)
Push all our user supplied values into another vector.
void dump () const
Dump the internal state of the option for debugging.
Public Attributes
std::string m_shortName
Short name without the '-' (-h -> h).
std::string m_longName
Long name without the '--' prefix.
std::string m_help
Maybe help, possibly NULL.
PgOptType m_type
Type of option.
std::string m_defaultValue
Default value if any.
std::vector< std::string > m_values
Values for this option.
int m_allowMultiple
Allow mutiple args.
Detailed Description
The definition of this option and the values.
Definition at line 108 of file PgOptions.h.
Member Typedef Documentation
typedef enum PgOpt::PgOptType PgOpt::PgOptType_t
Types of allowed options.
Member Enumeration Documentation
enum PgOpt::PgOptType
Types of allowed options.
Enumerator:
INVALID_OPT
BOOL_OPT
DOUBLE_OPT
INT_OPT
STRING_OPT
Definition at line 111 of file PgOptions.h.
Constructor & Destructor Documentation
PgOpt::PgOpt ()
Creates and inits a new PgOpt.
Definition at line 228 of file PgOptions.cpp.
References INVALID_OPT.
PgOpt::PgOpt (const PgOpt * orig)
Definition at line 240 of file PgOptions.cpp.
References m_allowMultiple, m_defaultValue, m_help, m_longName, m_shortName, m_type, and m_values.
Member Function Documentation
void PgOpt::allowMutipleValues (int val)
Allows mutiple values for this option?
Parameters:
val 1=yes 0=no
Definition at line 254 of file PgOptions.cpp.
Referenced by PgOptions::defOptMult().
int PgOpt::checkParseIsOk (const std::string & value) const
Check to see if the parse of the string is ok for this option.
Parameters:
value string to parse.
Returns:
1 if ok.
Definition at line 334 of file PgOptions.cpp.
References Err::errAbort(), Convert::toDoubleCheck(), and Convert::toIntCheck().
Referenced by PgOptions::addPgOpt_nocopy(), and PgOptions::matchOneArg().
void PgOpt::clearValues ()
Clear all the values on this option.
Definition at line 250 of file PgOptions.cpp.
void PgOpt::dump () const
Dump the internal state of the option for debugging.
Definition at line 316 of file PgOptions.cpp.
std::string PgOpt::getDefaultValue () const
The default value of this option.
Returns:
string
Definition at line 258 of file PgOptions.cpp.
Referenced by PgOptions::addPgOpt_nocopy().
std::string PgOpt::getValue (size_t idx = 0) const
Get the string value of this option.
Parameters:
idx (optional) the index
Returns:
string value
Definition at line 282 of file PgOptions.cpp.
References Err::errAbort().
Referenced by PgOptions::get(), and BaseEngine::getMetaDataDescription().
bool PgOpt::getValueBool (int idx = 0) const
Get the value as a boolean. Abort if it cant be converted.
Parameters:
idx (optional) the index
Returns:
boolean
Definition at line 299 of file PgOptions.cpp.
References Convert::toBool().
Referenced by PgOptions::getBool().
int PgOpt::getValueCount () const
The number of values for this option.
Returns:
int
Definition at line 274 of file PgOptions.cpp.
Referenced by BaseEngine::getMetaDataDescription().
double PgOpt::getValueDouble (int idx = 0) const
Get the value as a double. Abort if it cant be converted.
Parameters:
idx (optional) the index
Returns:
the value as a double
Definition at line 305 of file PgOptions.cpp.
References Convert::toDouble().
Referenced by PgOptions::getDouble().
int PgOpt::getValueInt (int idx = 0) const
Get the value as an int. Abort if it cant be converted.
Parameters:
idx (optional) the index
Returns:
the value as an int
Definition at line 302 of file PgOptions.cpp.
References Convert::toInt().
Referenced by PgOptions::getInt().
std::vector< std::string > PgOpt::getValueVector () const
Definition at line 278 of file PgOptions.cpp.
bool PgOpt::isSet ()
was this option set by the user?
Returns:
true if it was set, false if it is the default value.
Definition at line 265 of file PgOptions.cpp.
Referenced by main(), and PgOptions::matchOneArg().
void PgOpt::push_user_values_into (std::vector< std::string > & dest_vec)
Push all our user supplied values into another vector.
Parameters:
dest_vec vector to add them to.
Definition at line 309 of file PgOptions.cpp.
Referenced by dumpPgf::dumpPgf().
void PgOpt::pushValue (const std::string & new_value)
Push the new value onto the list of values for this option.
Parameters:
new_value
Remarks:
only valid for options which allow mutiple values.
Definition at line 269 of file PgOptions.cpp.
Referenced by PgOptions::matchOneArg().
void PgOpt::resetToDefault ()
same as clearValues()
Definition at line 261 of file PgOptions.cpp.
void PgOpt::setValue (const std::string & new_value) [inline]
Set the value of this option to a single value.
Parameters:
new_value
Definition at line 167 of file PgOptions.h.
Referenced by main(), and PgOptions::matchOneArg().
Member Data Documentation
int PgOpt::m_allowMultiple
Allow mutiple args.
Definition at line 127 of file PgOptions.h.
Referenced by PgOptionsSAXHandler::endDocument(), PgOptions::matchOneArg(), PgOpt(), and PgOptionsSAXHandler::startElement().
std::string PgOpt::m_defaultValue
Default value if any.
Definition at line 125 of file PgOptions.h.
Referenced by PgOptions::defineOption(), PgOpt(), and PgOptions::usage().
std::string PgOpt::m_help
Maybe help, possibly NULL.
Definition at line 123 of file PgOptions.h.
Referenced by PgOptions::defineOption(), PgOpt(), and PgOptions::usage().
std::string PgOpt::m_longName
Long name without the '--' prefix.
Definition at line 121 of file PgOptions.h.
Referenced by PgOptions::addPgOpt_nocopy(), PgOptions::defineOption(), PgOptions::matchOneArg(), PgOpt(), and PgOptions::usage().
std::string PgOpt::m_shortName
Short name without the '-' (-h -> h).
Definition at line 120 of file PgOptions.h.
Referenced by PgOptions::addPgOpt_nocopy(), PgOptions::defineOption(), PgOpt(), and PgOptions::usage().
PgOptType PgOpt::m_type
Type of option.
Definition at line 124 of file PgOptions.h.
Referenced by PgOptions::defineOption(), PgOptions::matchOneArg(), and PgOpt().
std::vector<std::string> PgOpt::m_values
Values for this option.
Definition at line 126 of file PgOptions.h.
Referenced by PgOptions::defineOption(), and PgOpt().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/PgOptions.h
C:/f112/affy/sdk/util/PgOptions.cpp