Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPGenericData Class Reference
affymetrix_fusion_io::FusionCHPGenericData Class Reference
#include <FusionCHPGenericData.h>
Classes
class Reg
Public Member Functions
~FusionCHPGenericData ()
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()
affymetrix_calvin_io::GenericData * GetGenericData ()
affymetrix_calvin_utilities::AffymetrixGuidType GetObjectName ()
void Clear ()
affymetrix_calvin_io::GenericData & GetData ()
Static Public Member Functions
static FusionCHPGenericData * FromBase (FusionCHPData *chip)
Private Member Functions
FusionCHPGenericData ()
bool Read ()
bool ReadHeader ()
Private Attributes
affymetrix_calvin_io::GenericData genericData
Static Private Attributes
static Reg reg
Detailed Description
This class provides storage and reading capabilities for CHP files
Definition at line 39 of file FusionCHPGenericData.h.
Constructor & Destructor Documentation
FusionCHPGenericData::~FusionCHPGenericData ()
Destructor
Definition at line 57 of file FusionCHPGenericData.cpp.
FusionCHPGenericData::FusionCHPGenericData () [private]
Constructor
Definition at line 53 of file FusionCHPGenericData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPGenericData::Reg::MakeObject().
Member Function Documentation
void FusionCHPGenericData::Clear (void)
Deallocates any memory used by the class object
Definition at line 98 of file FusionCHPGenericData.cpp.
AffymetrixGuidType FusionCHPGenericData::FileId () [virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 65 of file FusionCHPGenericData.cpp.
FusionCHPGenericData * FusionCHPGenericData::FromBase (FusionCHPData * chip) [static]
Converts the type to the generic CHP type.
Parameters:
chip The pointer to the CHP data object.
Returns:
The generic CHP data type or NULL if not compatible.
Definition at line 41 of file FusionCHPGenericData.cpp.
References affymetrix_fusion_io::FusionCHPData::GetObjectName(), and ObjectName.
affymetrix_calvin_io::GenericData& affymetrix_fusion_io::FusionCHPGenericData::GetData () [inline]
Gets the generic data object.
Returns:
The generic data object.
Definition at line 63 of file FusionCHPGenericData.h.
References genericData.
GenericData * FusionCHPGenericData::GetGenericData () [virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 73 of file FusionCHPGenericData.cpp.
AffymetrixGuidType FusionCHPGenericData::GetObjectName () [virtual]
Gets the class name.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 48 of file FusionCHPGenericData.cpp.
References ObjectName.
bool FusionCHPGenericData::Read () [private, virtual]
Reads the CHP file.
Returns:
True if successful.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 78 of file FusionCHPGenericData.cpp.
References affymetrix_calvin_io::GenericFileReader::Open(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
bool FusionCHPGenericData::ReadHeader () [private, virtual]
Reads the header of the CHP file
Returns:
True if successful
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 93 of file FusionCHPGenericData.cpp.
Member Data Documentation
affymetrix_calvin_io::GenericData affymetrix_fusion_io::FusionCHPGenericData::genericData [private]
The generic file data object.
Definition at line 71 of file FusionCHPGenericData.h.
Referenced by GetData().
FusionCHPGenericData::Reg FusionCHPGenericData::reg [static, private]
The one and only registration object. This registers the class as a CHP reader.
Used to register the CHP reader.
Definition at line 101 of file FusionCHPGenericData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPGenericData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPGenericData.cpp