Affymetrix Fusion SDK: AffxTimeSpan Class Reference
AffxTimeSpan Class Reference
#include <AffxTime.h>
Public Member Functions
AffxTimeSpan ()
AffxTimeSpan (time_t time)
AffxTimeSpan (int lDays, int nHours, int nMins, int nSecs)
AffxTimeSpan (double dt)
AffxTimeSpan (const AffxTimeSpan &timeSpanSrc)
const AffxTimeSpan & operator= (const AffxTimeSpan &timeSpanSrc)
void empty (void)
double getDATE (void)
int getDays () const
int getTotalHours () const
int getHours () const
int getTotalMinutes () const
int getMinutes () const
int getTotalSeconds () const
int getSeconds () const
AffxTimeSpan operator- (AffxTimeSpan timeSpan) const
AffxTimeSpan operator+ (AffxTimeSpan timeSpan) const
const AffxTimeSpan & operator+= (AffxTimeSpan timeSpan)
const AffxTimeSpan & operator-= (AffxTimeSpan timeSpan)
bool operator== (AffxTimeSpan timeSpan) const
bool operator!= (AffxTimeSpan timeSpan) const
bool operator< (AffxTimeSpan timeSpan) const
bool operator> (AffxTimeSpan timeSpan) const
bool operator<= (AffxTimeSpan timeSpan) const
bool operator>= (AffxTimeSpan timeSpan) const
AffxString format (char *pFormat) const
Private Attributes
time_t m_timeSpan
Friends
class AffxTime
Detailed Description
Definition at line 33 of file AffxTime.h.
Constructor & Destructor Documentation
AffxTimeSpan::AffxTimeSpan ()
Definition at line 53 of file AffxTime.cpp.
Referenced by operator+(), and operator-().
AffxTimeSpan::AffxTimeSpan (time_t time) [inline]
Definition at line 142 of file AffxTime.h.
References m_timeSpan.
AffxTimeSpan::AffxTimeSpan (int lDays, int nHours, int nMins, int nSecs) [inline]
Definition at line 144 of file AffxTime.h.
References m_timeSpan.
AffxTimeSpan::AffxTimeSpan (double dt)
Definition at line 371 of file AffxTime.cpp.
References m_timeSpan.
AffxTimeSpan::AffxTimeSpan (const AffxTimeSpan & timeSpanSrc) [inline]
Definition at line 146 of file AffxTime.h.
References m_timeSpan.
Member Function Documentation
void AffxTimeSpan::empty (void)
Definition at line 365 of file AffxTime.cpp.
References m_timeSpan.
AffxString AffxTimeSpan::format (char * pFormat) const
Definition at line 307 of file AffxTime.cpp.
References Err::errAbort(), and maxTimeBufferSize.
double AffxTimeSpan::getDATE (void)
Definition at line 378 of file AffxTime.cpp.
References getDays(), getHours(), getMinutes(), and getSeconds().
Referenced by AffxTime::operator+(), AffxTime::operator+=(), AffxTime::operator-(), and AffxTime::operator-=().
int AffxTimeSpan::getDays () const [inline]
Definition at line 150 of file AffxTime.h.
References m_timeSpan.
Referenced by getDATE(), and getHours().
int AffxTimeSpan::getHours () const [inline]
Definition at line 154 of file AffxTime.h.
References getDays(), and getTotalHours().
Referenced by getDATE().
int AffxTimeSpan::getMinutes () const [inline]
Definition at line 158 of file AffxTime.h.
References getTotalHours(), and getTotalMinutes().
Referenced by getDATE().
int AffxTimeSpan::getSeconds () const [inline]
Definition at line 162 of file AffxTime.h.
References getTotalMinutes(), and getTotalSeconds().
Referenced by getDATE().
int AffxTimeSpan::getTotalHours () const [inline]
Definition at line 152 of file AffxTime.h.
References m_timeSpan.
Referenced by getHours(), and getMinutes().
int AffxTimeSpan::getTotalMinutes () const [inline]
Definition at line 156 of file AffxTime.h.
References m_timeSpan.
Referenced by getMinutes(), and getSeconds().
int AffxTimeSpan::getTotalSeconds () const [inline]
Definition at line 160 of file AffxTime.h.
References m_timeSpan.
Referenced by getSeconds().
bool AffxTimeSpan::operator!= (AffxTimeSpan timeSpan) const [inline]
Definition at line 174 of file AffxTime.h.
References m_timeSpan.
AffxTimeSpan AffxTimeSpan::operator+ (AffxTimeSpan timeSpan) const [inline]
Definition at line 166 of file AffxTime.h.
References AffxTimeSpan(), and m_timeSpan.
const AffxTimeSpan & AffxTimeSpan::operator+= (AffxTimeSpan timeSpan) [inline]
Definition at line 168 of file AffxTime.h.
References m_timeSpan.
AffxTimeSpan AffxTimeSpan::operator- (AffxTimeSpan timeSpan) const [inline]
Definition at line 164 of file AffxTime.h.
References AffxTimeSpan(), and m_timeSpan.
const AffxTimeSpan & AffxTimeSpan::operator-= (AffxTimeSpan timeSpan) [inline]
Definition at line 170 of file AffxTime.h.
References m_timeSpan.
bool AffxTimeSpan::operator< (AffxTimeSpan timeSpan) const [inline]
Definition at line 176 of file AffxTime.h.
References m_timeSpan.
bool AffxTimeSpan::operator<= (AffxTimeSpan timeSpan) const [inline]
Definition at line 180 of file AffxTime.h.
References m_timeSpan.
const AffxTimeSpan & AffxTimeSpan::operator= (const AffxTimeSpan & timeSpanSrc) [inline]
Definition at line 148 of file AffxTime.h.
References m_timeSpan.
bool AffxTimeSpan::operator== (AffxTimeSpan timeSpan) const [inline]
Definition at line 172 of file AffxTime.h.
References m_timeSpan.
bool AffxTimeSpan::operator> (AffxTimeSpan timeSpan) const [inline]
Definition at line 178 of file AffxTime.h.
References m_timeSpan.
bool AffxTimeSpan::operator>= (AffxTimeSpan timeSpan) const [inline]
Definition at line 182 of file AffxTime.h.
References m_timeSpan.
Friends And Related Function Documentation
friend class AffxTime [friend]
Definition at line 76 of file AffxTime.h.
Member Data Documentation
time_t AffxTimeSpan::m_timeSpan [private]
Definition at line 75 of file AffxTime.h.
Referenced by AffxTimeSpan(), empty(), getDays(), getTotalHours(), getTotalMinutes(), getTotalSeconds(), operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), and operator>=().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/AffxTime.h
C:/f112/affy/sdk/util/AffxTime.cpp