Affymetrix Fusion SDK: affxchpwriter::CCHPFileBufferWriter Class Reference
affxchpwriter::CCHPFileBufferWriter Class Reference
#include <CHPFileBufferWriter.h>
Classes
class ExpressionBufferEntry
class GenotypeBufferEntry
Public Member Functions
CCHPFileBufferWriter ()
~CCHPFileBufferWriter ()
void SetMaxBufferSize (int MaxBufferSize)
void Cleanup ()
void Initialize (std::vector< std::string > *CHPFileNames, bool IsGenotype)
void WriteGenotypeEntry (int target, affxchp::CGenotypeProbeSetResults &entry)
void WriteExpressionEntry (int target, affxchp::CExpressionProbeSetResults &entry)
void FlushBuffer ()
Private Attributes
std::vector< std::string > * m_CHPFileNames
std::vector< std::vector
< GenotypeBufferEntry > > m_TargetGenotypeEntryBuffers
std::vector< std::vector
< ExpressionBufferEntry > > m_TargetExpressionEntryBuffers
std::vector< int > m_TargetEntryRowIndexes
int m_BufferSize
int m_MaxBufferSize
bool m_IsGenotype
Detailed Description
Definition at line 46 of file CHPFileBufferWriter.h.
Constructor & Destructor Documentation
CCHPFileBufferWriter::CCHPFileBufferWriter ()
Constructor
Definition at line 36 of file CHPFileBufferWriter.cpp.
References m_BufferSize, m_IsGenotype, m_MaxBufferSize, and MAX_BUFFER_SIZE.
CCHPFileBufferWriter::~CCHPFileBufferWriter ()
Destructor
Definition at line 43 of file CHPFileBufferWriter.cpp.
References Cleanup(), and FlushBuffer().
Member Function Documentation
void CCHPFileBufferWriter::Cleanup ()
Cleans up memory
Definition at line 49 of file CHPFileBufferWriter.cpp.
References m_IsGenotype, m_TargetExpressionEntryBuffers, and m_TargetGenotypeEntryBuffers.
Referenced by ~CCHPFileBufferWriter().
void CCHPFileBufferWriter::FlushBuffer ()
Write the content of the buffer to CHP files.
Definition at line 126 of file CHPFileBufferWriter.cpp.
References affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::aaCall, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::abCall, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::bbCall, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::call, affxchpwriter::CCHPFileUpdater::CloseCHPFile(), affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::confidence, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::Detection, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::DetectionPValue, m_BufferSize, m_CHPFileNames, m_IsGenotype, m_TargetEntryRowIndexes, m_TargetExpressionEntryBuffers, m_TargetGenotypeEntryBuffers, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::noCall, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::NumPairs, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::NumUsedPairs, affxchpwriter::CCHPFileUpdater::OpenCHPFile(), affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::RAS1, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::RAS2, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::Signal, affxchpwriter::CCHPFileUpdater::UpdateExpressionEntry(), and affxchpwriter::CCHPFileUpdater::UpdateGenotypeEntry().
Referenced by WriteExpressionEntry(), WriteGenotypeEntry(), and ~CCHPFileBufferWriter().
void CCHPFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames, bool IsGenotype)
Initialize entry buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
IsGenotype Genotype or Expression CHP file.
Definition at line 38 of file FusionCHPMultiDataAccessor.cpp.
References affymetrix_fusion_io::FusionCHPMultiDataData::FromBase(), affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_fusion_io::FusionCHPMultiDataData::GetEntryCount(), affymetrix_fusion_io::FusionCHPMultiDataData::GetProbeSetName(), and affymetrix_fusion_io::FusionCHPDataReg::Read().
void affxchpwriter::CCHPFileBufferWriter::SetMaxBufferSize (int MaxBufferSize) [inline]
Set maximum buffer size
Definition at line 79 of file CHPFileBufferWriter.h.
References m_MaxBufferSize.
void CCHPFileBufferWriter::WriteExpressionEntry (int target, affxchp::CExpressionProbeSetResults & entry)
Write an entry to buffer. If the buffer is full, flush it.
Parameters:
target Target for the Signal entry.
entry CHP expression entry.
Definition at line 110 of file CHPFileBufferWriter.cpp.
References affxchp::CExpressionProbeSetResults::Detection, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::Detection, affxchp::CExpressionProbeSetResults::DetectionPValue, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::DetectionPValue, FlushBuffer(), m_BufferSize, m_MaxBufferSize, m_TargetExpressionEntryBuffers, affxchp::CExpressionProbeSetResults::NumPairs, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::NumPairs, affxchp::CExpressionProbeSetResults::NumUsedPairs, affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::NumUsedPairs, affxchp::CExpressionProbeSetResults::Signal, and affxchpwriter::CCHPFileBufferWriter::ExpressionBufferEntry::Signal.
void CCHPFileBufferWriter::WriteGenotypeEntry (int target, affxchp::CGenotypeProbeSetResults & entry)
Write an entry to buffer. If the buffer is full, flush it.
Parameters:
target Target for the Signal entry.
entry CHP genotype entry.
Definition at line 91 of file CHPFileBufferWriter.cpp.
References affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::aaCall, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::abCall, affxchp::CGenotypeProbeSetResults::AlleleCall, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::bbCall, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::call, affxchp::CGenotypeProbeSetResults::Confidence, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::confidence, FlushBuffer(), m_BufferSize, m_MaxBufferSize, m_TargetGenotypeEntryBuffers, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::noCall, affxchp::CGenotypeProbeSetResults::pvalue_AA, affxchp::CGenotypeProbeSetResults::pvalue_AB, affxchp::CGenotypeProbeSetResults::pvalue_BB, affxchp::CGenotypeProbeSetResults::pvalue_NoCall, affxchp::CGenotypeProbeSetResults::RAS1, affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::RAS1, affxchp::CGenotypeProbeSetResults::RAS2, and affxchpwriter::CCHPFileBufferWriter::GenotypeBufferEntry::RAS2.
Member Data Documentation
int affxchpwriter::CCHPFileBufferWriter::m_BufferSize [private]
Definition at line 119 of file CHPFileBufferWriter.h.
Referenced by CCHPFileBufferWriter(), FlushBuffer(), WriteExpressionEntry(), and WriteGenotypeEntry().
std::vector<std::string>* affxchpwriter::CCHPFileBufferWriter::m_CHPFileNames [private]
Definition at line 107 of file CHPFileBufferWriter.h.
Referenced by FlushBuffer().
bool affxchpwriter::CCHPFileBufferWriter::m_IsGenotype [private]
Definition at line 125 of file CHPFileBufferWriter.h.
Referenced by CCHPFileBufferWriter(), Cleanup(), and FlushBuffer().
int affxchpwriter::CCHPFileBufferWriter::m_MaxBufferSize [private]
Definition at line 122 of file CHPFileBufferWriter.h.
Referenced by CCHPFileBufferWriter(), SetMaxBufferSize(), WriteExpressionEntry(), and WriteGenotypeEntry().
std::vector<int> affxchpwriter::CCHPFileBufferWriter::m_TargetEntryRowIndexes [private]
Definition at line 116 of file CHPFileBufferWriter.h.
Referenced by FlushBuffer().
std::vector< std::vector<ExpressionBufferEntry> > affxchpwriter::CCHPFileBufferWriter::m_TargetExpressionEntryBuffers [private]
Definition at line 113 of file CHPFileBufferWriter.h.
Referenced by Cleanup(), FlushBuffer(), and WriteExpressionEntry().
std::vector< std::vector<GenotypeBufferEntry> > affxchpwriter::CCHPFileBufferWriter::m_TargetGenotypeEntryBuffers [private]
Definition at line 110 of file CHPFileBufferWriter.h.
Referenced by Cleanup(), FlushBuffer(), and WriteGenotypeEntry().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CHPFileBufferWriter.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPMultiDataAccessor.cpp
C:/f112/affy/sdk/file/CHPFileBufferWriter.cpp