Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPMultiDataData Class Reference
affymetrix_fusion_io::FusionCHPMultiDataData Class Reference
#include <FusionCHPMultiDataData.h>
Classes
class Reg
Public Member Functions
~FusionCHPMultiDataData ()
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()
affymetrix_calvin_io::GenericData * GetGenericData ()
affymetrix_calvin_io::DataSetHeader * GetDataSetHeader (affymetrix_calvin_io::MultiDataType dataType)
std::map
< affymetrix_calvin_io::MultiDataType,
affymetrix_calvin_io::DataSetInfo > & GetDataSetInfo ()
int GetMaxProbeSetName (affymetrix_calvin_io::MultiDataType dataType)
void Clear ()
affymetrix_calvin_utilities::AffymetrixGuidType GetObjectName ()
std::wstring GetAlgName ()
std::wstring GetAlgVersion ()
std::wstring GetArrayType ()
ParameterNameValueTypeList GetAlgParams ()
ParameterNameValueTypeList GetSummaryParams ()
int32_t GetEntryCount (affymetrix_calvin_io::MultiDataType dataType)
void GetGenotypeEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry)
void GetCopyNumberEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData &entry)
void GetCopyNumberEntryLog2Ratio (affymetrix_calvin_io::MultiDataType dataType, int index, int log2RatioIndex, float *val)
void GetCytoRegionEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData &entry)
void GetCopyNumberVariationRegionEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData &entry)
void GetExpressionEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataExpressionData &entry)
u_int8_t GetGenoCall (affymetrix_calvin_io::MultiDataType dataType, int index)
float GetGenoConfidence (affymetrix_calvin_io::MultiDataType dataType, int index)
float GetExpressionQuantification (affymetrix_calvin_io::MultiDataType dataType, int index)
void GetChromosomeSegmentEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeSegmentData &entry)
void GetChromosomeSegmentEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeSegmentDataEx &entry)
void GetChromosomeSummaryEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeMultiDataSummaryData &entry)
void GetFamilialSegmentOverlapEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::FamilialSegmentOverlap &entry)
void GetFamilialSampleEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::FamilialSample &entry)
void GetDmetCopyNumberEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::DmetCopyNumberData &entry)
void GetDmetMultiAllelicEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::DmetMultiAllelicData &entry)
void GetDmetBiAllelicEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::DmetBiAllelicData &entry)
void GetAllelePeakEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::AllelePeaks &entry)
void GetMarkerABSignalsEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::MarkerABSignals &entry)
void GetCytoGenotypeEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::CytoGenotypeCallData &entry)
std::string GetProbeSetName (affymetrix_calvin_io::MultiDataType dataType, int index)
int32_t GetMetricColumnLength (affymetrix_calvin_io::MultiDataType dataType, int col)
int32_t GetNumMetricColumns (affymetrix_calvin_io::MultiDataType dataType)
std::wstring GetMetricColumnName (affymetrix_calvin_io::MultiDataType dataType, int colIndex)
Static Public Member Functions
static FusionCHPMultiDataData * FromBase (FusionCHPData *chip)
Static Public Attributes
static Reg reg
Private Member Functions
FusionCHPMultiDataData ()
bool Read ()
bool ReadHeader ()
Private Attributes
affymetrix_calvin_io::CHPMultiDataData chpData
Detailed Description
This class provides storage and reading capabilities for multi-data CHP files
Definition at line 34 of file FusionCHPMultiDataData.h.
Constructor & Destructor Documentation
FusionCHPMultiDataData::FusionCHPMultiDataData () [private]
Constructor
Definition at line 40 of file FusionCHPMultiDataData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataData::Reg::MakeObject().
FusionCHPMultiDataData::~FusionCHPMultiDataData ()
Destructor
Definition at line 47 of file FusionCHPMultiDataData.cpp.
Member Function Documentation
void affymetrix_fusion_io::FusionCHPMultiDataData::Clear (void) [inline]
Clears the members.
Definition at line 72 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::Clear().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_fusion_io::FusionCHPMultiDataData::FileId () [inline, virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 52 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetGenericData().
FusionCHPMultiDataData * FusionCHPMultiDataData::FromBase (FusionCHPData * chip) [static]
Converts the type to the MultiData CHP type.
Parameters:
chip The pointer to the CHP data object.
Returns:
The MultiData CHP data type or NULL if not compatible.
Definition at line 81 of file FusionCHPMultiDataData.cpp.
References affymetrix_fusion_io::FusionCHPData::GetObjectName(), and ObjectName.
Referenced by affymetrix_fusion_io::FusionCHPMultiDataAccessor::ExtractData(), CFusionCHPMultiDataDataCOM::FromBase(), and affxchpwriter::CCHPFileBufferWriter::Initialize().
std::wstring affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgName () [inline]
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 80 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetAlgName().
Referenced by main().
ParameterNameValueTypeList affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgParams () [inline]
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 93 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetAlgParams().
Referenced by main().
std::wstring affymetrix_fusion_io::FusionCHPMultiDataData::GetAlgVersion () [inline]
Gets the algorithm version.
Returns:
The version.
Definition at line 85 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetAlgVersion().
Referenced by main().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetAllelePeakEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::AllelePeaks & entry) [inline]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 243 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetEntry().
Referenced by main().
std::wstring affymetrix_fusion_io::FusionCHPMultiDataData::GetArrayType () [inline]
Sets the array type
Definition at line 88 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetArrayType().
Referenced by main().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetChromosomeSegmentEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeSegmentData & entry) [inline]
Gets the chromosome segment data.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 179 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetChromosomeSegmentEntry().
Referenced by main().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetChromosomeSegmentEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeSegmentDataEx & entry) [inline]
Gets the chromosome segment data.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 187 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetChromosomeSegmentEntry().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetChromosomeSummaryEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ChromosomeMultiDataSummaryData & entry) [inline]
Gets the chromosome summary data.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 195 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetChromosomeSummaryEntry().
Referenced by main().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetCopyNumberEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & entry) [inline]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 118 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetCopyNumberEntry().
Referenced by main().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetCopyNumberEntryLog2Ratio (affymetrix_calvin_io::MultiDataType dataType, int index, int log2RatioIndex, float * val) [inline]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 126 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetCopyNumberEntryLog2Ratio().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetCopyNumberVariationRegionEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData & entry) [inline]
Gets the copy number variation region data.
Parameters:
dataType The data type
index The row index.
entry The cyto region results.
Definition at line 142 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetCopyNumberVariationEntry().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetCytoGenotypeEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::CytoGenotypeCallData & entry) [inline]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 259 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetEntry().
Referenced by main().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetCytoRegionEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & entry) [inline]
Gets the cyto region data.
Parameters:
dataType The data type
index The row index.
entry The cyto region results.
Definition at line 134 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetCytoEntry().
affymetrix_calvin_io::DataSetHeader* affymetrix_fusion_io::FusionCHPMultiDataData::GetDataSetHeader (affymetrix_calvin_io::MultiDataType dataType) [inline]
Returns the data set header.
Parameters:
dataType The data type.
Definition at line 60 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader().
std::map<affymetrix_calvin_io::MultiDataType, affymetrix_calvin_io::DataSetInfo>& affymetrix_fusion_io::FusionCHPMultiDataData::GetDataSetInfo () [inline]
The data set information
Definition at line 63 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetDataSetInfo().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetDmetBiAllelicEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::DmetBiAllelicData & entry) [inline]
Gets the DMET probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 235 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetEntry().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetDmetCopyNumberEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::DmetCopyNumberData & entry) [inline]
Gets the DMET probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 219 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetEntry().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetDmetMultiAllelicEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::DmetMultiAllelicData & entry) [inline]
Gets the DMET probe set data.
Parameters:
dataType The data type
index The row index.
entry The copy number results.
Definition at line 227 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetEntry().
int32_t affymetrix_fusion_io::FusionCHPMultiDataData::GetEntryCount (affymetrix_calvin_io::MultiDataType dataType) [inline]
Gets the number of entries (probe sets)
Parameters:
dataType The data type
Definition at line 103 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetEntryCount().
Referenced by affxchpwriter::CCHPFileBufferWriter::Initialize(), main(), and MultiDataExample().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetExpressionEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataExpressionData & entry) [inline]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The expression results.
Definition at line 150 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetExpressionEntry().
float affymetrix_fusion_io::FusionCHPMultiDataData::GetExpressionQuantification (affymetrix_calvin_io::MultiDataType dataType, int index) [inline]
Gets the quantification of the probe set.
Parameters:
dataType The data type
index The row index.
Returns:
The quantification.
Definition at line 172 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetExpressionQuantification().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetFamilialSampleEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::FamilialSample & entry) [inline]
Gets the familial file entry.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 211 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetFamilialSampleEntry().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetFamilialSegmentOverlapEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::FamilialSegmentOverlap & entry) [inline]
Gets the familial file entry.
Parameters:
dataType The data type
index The row index.
entry The results.
Definition at line 203 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetFamilialSegmentOverlapEntry().
affymetrix_calvin_io::GenericData* affymetrix_fusion_io::FusionCHPMultiDataData::GetGenericData () [inline, virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 55 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetGenericData().
u_int8_t affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoCall (affymetrix_calvin_io::MultiDataType dataType, int index) [inline]
Gets the call of the probe set.
Parameters:
dataType The data type
index The row index.
Returns:
The call.
Definition at line 158 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetGenoCall().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataAccessor::ExtractData(), and MultiDataExample().
float affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoConfidence (affymetrix_calvin_io::MultiDataType dataType, int index) [inline]
Gets the confidence in the call of the probe set.
Parameters:
dataType The data type
index The row index.
Returns:
The confidence.
Definition at line 165 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetGenoConfidence().
Referenced by affymetrix_fusion_io::FusionCHPMultiDataAccessor::ExtractData().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetGenotypeEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry) [inline]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The genotype results.
Definition at line 110 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetGenotypeEntry().
void affymetrix_fusion_io::FusionCHPMultiDataData::GetMarkerABSignalsEntry (affymetrix_calvin_io::MultiDataType dataType, int index, affymetrix_calvin_data::MarkerABSignals & entry) [inline]
Gets the probe set data.
Parameters:
dataType The data type
index The row index.
entry The AB signals.
Definition at line 251 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetEntry().
Referenced by main().
int affymetrix_fusion_io::FusionCHPMultiDataData::GetMaxProbeSetName (affymetrix_calvin_io::MultiDataType dataType) [inline]
The maximum length of a probe set name.
Parameters:
dataType The data type
Returns:
The maximum probe set name length
Definition at line 69 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetMaxProbeSetName().
int32_t affymetrix_fusion_io::FusionCHPMultiDataData::GetMetricColumnLength (affymetrix_calvin_io::MultiDataType dataType, int col) [inline]
Get the length of the metric columns.
Parameters:
dataType The data type
col The column index (of the metric columns)
Returns:
The length.
Definition at line 274 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetMetricColumnLength().
std::wstring affymetrix_fusion_io::FusionCHPMultiDataData::GetMetricColumnName (affymetrix_calvin_io::MultiDataType dataType, int colIndex) [inline]
Get the metric column name.
Parameters:
dataType The data type
colIndex the metric column index
Returns:
The column name
Definition at line 287 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetMetricColumnName().
int32_t affymetrix_fusion_io::FusionCHPMultiDataData::GetNumMetricColumns (affymetrix_calvin_io::MultiDataType dataType) [inline]
Get the length of the metric columns.
Parameters:
dataType The data type
Returns:
The number of columns.
Definition at line 280 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetNumMetricColumns().
AffymetrixGuidType FusionCHPMultiDataData::GetObjectName () [virtual]
Gets the class name.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 88 of file FusionCHPMultiDataData.cpp.
References ObjectName.
std::string affymetrix_fusion_io::FusionCHPMultiDataData::GetProbeSetName (affymetrix_calvin_io::MultiDataType dataType, int index) [inline]
Get the probe set name.
Parameters:
dataType The data type
index The row index.
Returns:
The probe set name.
Definition at line 267 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetProbeSetName().
Referenced by affxchpwriter::CCHPFileBufferWriter::Initialize().
ParameterNameValueTypeList affymetrix_fusion_io::FusionCHPMultiDataData::GetSummaryParams () [inline]
Gets the summary parameters
Returns:
The summary parameters.
Definition at line 98 of file FusionCHPMultiDataData.h.
References chpData, and affymetrix_calvin_io::CHPMultiDataData::GetSummaryParams().
Referenced by main(), and MultiDataExample().
bool FusionCHPMultiDataData::Read () [private, virtual]
Reads the CHP file.
Returns:
True if successful.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 63 of file FusionCHPMultiDataData.cpp.
References affymetrix_calvin_io::CHPMultiDataFileReader::Read(), and affymetrix_calvin_io::CHPMultiDataFileReader::SetFilename().
bool FusionCHPMultiDataData::ReadHeader () [private, virtual]
Reads the header of the CHP file
Returns:
True if successful
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 55 of file FusionCHPMultiDataData.cpp.
Member Data Documentation
affymetrix_calvin_io::CHPMultiDataData affymetrix_fusion_io::FusionCHPMultiDataData::chpData [private]
The CHP object.
Definition at line 42 of file FusionCHPMultiDataData.h.
Referenced by Clear(), FileId(), GetAlgName(), GetAlgParams(), GetAlgVersion(), GetAllelePeakEntry(), GetArrayType(), GetChromosomeSegmentEntry(), GetChromosomeSummaryEntry(), GetCopyNumberEntry(), GetCopyNumberEntryLog2Ratio(), GetCopyNumberVariationRegionEntry(), GetCytoGenotypeEntry(), GetCytoRegionEntry(), GetDataSetHeader(), GetDataSetInfo(), GetDmetBiAllelicEntry(), GetDmetCopyNumberEntry(), GetDmetMultiAllelicEntry(), GetEntryCount(), GetExpressionEntry(), GetExpressionQuantification(), GetFamilialSampleEntry(), GetFamilialSegmentOverlapEntry(), GetGenericData(), GetGenoCall(), GetGenoConfidence(), GetGenotypeEntry(), GetMarkerABSignalsEntry(), GetMaxProbeSetName(), GetMetricColumnLength(), GetMetricColumnName(), GetNumMetricColumns(), GetProbeSetName(), and GetSummaryParams().
FusionCHPMultiDataData::Reg FusionCHPMultiDataData::reg [static]
The one and only registration object. This registers the class as a CHP reader.
Used to register the CHP reader.
Definition at line 322 of file FusionCHPMultiDataData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPMultiDataData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPMultiDataData.cpp