Affymetrix Fusion SDK: SocketBase Class Reference
SocketBase Class Reference
#include <SocketBase.h>
Public Member Functions
virtual int sendAll (int socket, const char *buf, int toSend, int &sent)
virtual void parseMsgFromBuffer (std::vector< char > &buffer, std::vector< std::string > *messages)
virtual bool checkForMsgs (std::vector< std::string > &messages, int &socket)
virtual bool checkForMsgs (int &socket)
void sendMsg (const std::string &msg, int type, int channel, int &conn)
virtual void addHandler (SocketHandler *handler)
bool fillBufferFromSocket (int &conn)
Static Public Member Functions
static void unPackInt32NetOrder (const char *buf, int32_t &x)
static void packInt32NetOrder (char *buf, int32_t x)
Protected Attributes
std::vector< char > m_Buffer
Data coming over socket, including any partial messages.
std::vector< SocketHandler * > m_Handlers
Detailed Description
Class with static utility functions for working with Sockets.
The messages passsed back and forth have a standard message header which consists of three 4 byte integers consisting of the message size, message type and message channel This information is used to know when the full message has been recieved and what to do with the resulting following the header. The type of the message would be something like the format and the channel would be which handler would be interested. So for exampe a basic type would be "text" and a basic channel would be "stdout", or progress. This is analagous to the type being the format of the signal coming in (eg high definition or regular tv) and the channel being the address of where to send the data (eg hbo television channel).
Msg format:
Todo:
supported types, versions, etc.?
 int32_t|int32_t|int32_t|int32_t|int32_t | bytes
  size  | type  |channel|version|reserved| msg bytes
Definition at line 73 of file SocketBase.h.
Member Function Documentation
void SocketBase::addHandler (SocketHandler * handler) [virtual]
Add a handler for incoming messages. This handler will have a chance see the message type and channel and decide if it should do something. Like a java listener or a regular callback
Parameters:
-
Definition at line 160 of file SocketBase.cpp.
Referenced by SocketEngine::run().
bool SocketBase::checkForMsgs (int & socket) [virtual]
Try to read new messages from socket.
Parameters:
socket - socket to read messages from. Set to -1 if disconnected.
Definition at line 120 of file SocketBase.cpp.
bool SocketBase::checkForMsgs (std::vector< std::string > & messages, int & socket) [virtual]
Try to read new messages from socket.
Parameters:
messages - Vector to fill with char * messages from socket.
socket - socket to read messages from. Set to -1 if disconnected.
Definition at line 113 of file SocketBase.cpp.
Referenced by SocketServer::checkForMsgs(), SocketClient::checkForMsgs(), and SocketServer::processNewMessages().
bool SocketBase::fillBufferFromSocket (int & conn)
Fill in our buffer from the socket connection
Parameters:
conn - Socket fd desc
Returns:
Definition at line 76 of file SocketBase.cpp.
References APT_ERR_ABORT, CLOSE_SOCKET, Verbose::out(), and ToStr().
void SocketBase::packInt32NetOrder (char * buf, int32_t x) [static]
Pack int x into first 4 bytes pointed at by buf.
Parameters:
buf - Buffer containing at least 4 bytes to write int into
x - integer to be written.
Definition at line 152 of file SocketBase.cpp.
void SocketBase::parseMsgFromBuffer (std::vector< char > & buffer, std::vector< std::string > * messages) [virtual]
Tokenize the buffer into distinct messages
Parameters:
buffer - String to break into individual messages
messages - Vector of messages to fill in
Definition at line 39 of file SocketBase.cpp.
References APT_ERR_ASSERT, HEADER_SIZE, SOCKET_PROTOCOL_VER, and ToStr().
int SocketBase::sendAll (int socket, const char * buf, int toSend, int & sent) [virtual]
Send a message over multiple socket send calls as necessary
Parameters:
socket - Socket to write to
buf - Buffer to send over socket
toSend - How long is buffer
sent - Number characters actually sent
Returns:
Definition at line 126 of file SocketBase.cpp.
void SocketBase::sendMsg (const std::string & msg, int type, int channel, int & conn)
Write char * messages into a socket.
Parameters:
msg - Message to write to the socket.
type - What format of message? e.g. SocketHandler::TEXT
channel - What channel or sort of message? e.g. SocketHandler::VERBOSE
socket - Socket that could be written to.
Definition at line 164 of file SocketBase.cpp.
References APT_ERR_ABORT, FreezArray(), HEADER_SIZE, SOCKET_PROTOCOL_VER, and ToStr().
Referenced by SocketServer::sendMsg(), and SocketClient::sendMsg().
void SocketBase::unPackInt32NetOrder (const char * buf, int32_t & x) [static]
Take a 4 byte 32bit int from buff and parse it into x.
Parameters:
buf - Buffer with at least 4 bytes in it.
x - Integer to be filled in.
Definition at line 147 of file SocketBase.cpp.
Member Data Documentation
std::vector<char> SocketBase::m_Buffer [protected]
Data coming over socket, including any partial messages.
Definition at line 160 of file SocketBase.h.
std::vector<SocketHandler *> SocketBase::m_Handlers [protected]
Definition at line 162 of file SocketBase.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/SocketBase.h
C:/f112/affy/sdk/util/SocketBase.cpp