Affymetrix Fusion SDK: affymetrix_calvin_io::CHPTilingFileWriter Class Reference
affymetrix_calvin_io::CHPTilingFileWriter Class Reference
#include <CalvinCHPTilingFileWriter.h>
Public Member Functions
CHPTilingFileWriter (CHPTilingData &p)
~CHPTilingFileWriter ()
void WriteTilingEntry (const CHPTilingEntry &p)
void SeekToDataSet (int index)
Private Member Functions
void WriteHeaders ()
int32_t SetFilePositions ()
Private Attributes
GenericFileWriter * writer
DataSetWriter * dataSetWriter
int32_t * entryPos
int dataSetIndex
Detailed Description
A class to write a tiling CHP file.
Definition at line 35 of file CalvinCHPTilingFileWriter.h.
Constructor & Destructor Documentation
CHPTilingFileWriter::CHPTilingFileWriter (CHPTilingData & p)
Constructor
Parameters:
p Pointer to the tiling CHP data object.
Definition at line 26 of file CalvinCHPTilingFileWriter.cpp.
References dataSetIndex, entryPos, affymetrix_calvin_io::CHPTilingData::GetFileHeader(), affymetrix_calvin_io::CHPTilingData::GetNumberSequences(), WriteHeaders(), and writer.
CHPTilingFileWriter::~CHPTilingFileWriter ()
Destructor
Definition at line 34 of file CalvinCHPTilingFileWriter.cpp.
References entryPos, and writer.
Member Function Documentation
void CHPTilingFileWriter::SeekToDataSet (int index)
Seeks to the data set.
Parameters:
index The data set index.
Definition at line 60 of file CalvinCHPTilingFileWriter.cpp.
References dataSetIndex, dataSetWriter, entryPos, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), and writer.
int32_t CHPTilingFileWriter::SetFilePositions () [private]
Sets the file positions.
Returns:
The current file position.
Definition at line 74 of file CalvinCHPTilingFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::DataSetWriter::GetDataSetSize(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::GenericFileWriter::SeekFromCurrentPos(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), and writer.
Referenced by WriteHeaders().
void CHPTilingFileWriter::WriteHeaders () [private]
Writes the headers to the file.
Definition at line 40 of file CalvinCHPTilingFileWriter.cpp.
References dataSetWriter, entryPos, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriters(), SetFilePositions(), affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), and writer.
Referenced by CHPTilingFileWriter().
void CHPTilingFileWriter::WriteTilingEntry (const CHPTilingEntry & p)
Write a tiling entry.
Parameters:
p A pointer to a tiling entry.
Definition at line 68 of file CalvinCHPTilingFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::_CHPTilingEntry::position, affymetrix_calvin_io::_CHPTilingEntry::value, and affymetrix_calvin_io::DataSetWriter::Write().
Member Data Documentation
int affymetrix_calvin_io::CHPTilingFileWriter::dataSetIndex [private]
The current data set index.
Definition at line 70 of file CalvinCHPTilingFileWriter.h.
Referenced by CHPTilingFileWriter(), and SeekToDataSet().
DataSetWriter* affymetrix_calvin_io::CHPTilingFileWriter::dataSetWriter [private]
The data set writer.
Definition at line 42 of file CalvinCHPTilingFileWriter.h.
Referenced by SeekToDataSet(), SetFilePositions(), WriteHeaders(), and WriteTilingEntry().
int32_t* affymetrix_calvin_io::CHPTilingFileWriter::entryPos [private]
The file position of the entry for each data set.
Definition at line 45 of file CalvinCHPTilingFileWriter.h.
Referenced by CHPTilingFileWriter(), SeekToDataSet(), WriteHeaders(), and ~CHPTilingFileWriter().
GenericFileWriter* affymetrix_calvin_io::CHPTilingFileWriter::writer [private]
The file writer.
Definition at line 39 of file CalvinCHPTilingFileWriter.h.
Referenced by CHPTilingFileWriter(), SeekToDataSet(), SetFilePositions(), WriteHeaders(), and ~CHPTilingFileWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPTilingFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPTilingFileWriter.cpp