Affymetrix Fusion SDK: affxmdl::CMDLProbeData Class Reference
affxmdl::CMDLProbeData Class Reference
#include <MDLFileData.h>
Public Member Functions
double GetAffinity () const
float GetRelativeBkg () const
float GetSaturation () const
float GetOffset () const
void SetAffinity (double value)
void SetRelativeBkg (float value)
void SetSaturation (float value)
void SetOffset (float value)
CMDLProbeData ()
Protected Member Functions
void MakeShallowCopy (CMDLProbeData &orig)
Protected Attributes
double m_dAffinity
float m_fRelativeBkg
float m_fSaturation
float m_fOffset
int32_t m_nIndex
bool m_bMapped
char * m_lpData
Friends
class CMDLFileData
Detailed Description
PLIER model probe data class
Definition at line 196 of file MDLFileData.h.
Constructor & Destructor Documentation
CMDLProbeData::CMDLProbeData ()
Constructor
Definition at line 115 of file MDLFileData.cpp.
Member Function Documentation
double affxmdl::CMDLProbeData::GetAffinity () const [inline]
The affinity value
Returns:
The affinity value
Definition at line 220 of file MDLFileData.h.
References m_dAffinity.
Referenced by affxmdl::CMDLFileData::GetDataInfo(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
float affxmdl::CMDLProbeData::GetOffset () const [inline]
The offset
Returns:
The offset
Definition at line 235 of file MDLFileData.h.
References m_fOffset.
Referenced by affxmdl::CMDLFileData::GetDataInfo(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
float affxmdl::CMDLProbeData::GetRelativeBkg () const [inline]
The relative background
Returns:
The relative background
Definition at line 225 of file MDLFileData.h.
References m_fRelativeBkg.
Referenced by affxmdl::CMDLFileData::GetDataInfo(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
float affxmdl::CMDLProbeData::GetSaturation () const [inline]
The saturation
Returns:
The saturation
Definition at line 230 of file MDLFileData.h.
References m_fSaturation.
Referenced by affxmdl::CMDLFileData::GetDataInfo(), and affxmdl::CMDLFileData::PrintMDLToTextFile().
void CMDLProbeData::MakeShallowCopy (CMDLProbeData & orig) [protected]
Friend to parent object
Copies the class object, one member at a time
Parameters:
orig The object to copy
Definition at line 128 of file MDLFileData.cpp.
References m_bMapped, m_dAffinity, m_fOffset, m_fRelativeBkg, m_fSaturation, and m_lpData.
Referenced by affxmdl::CMDLFileData::GetProbeData().
void affxmdl::CMDLProbeData::SetAffinity (double value) [inline]
Sets the affinity
Parameters:
value The affinity
Definition at line 240 of file MDLFileData.h.
References m_dAffinity.
Referenced by affxmdl::CMDLFileData::CMDLFileData(), affxmdl::CMDLFileData::InitializeForWriting(), and affxmdl::CMDLFileData::SetDataInfo().
void affxmdl::CMDLProbeData::SetOffset (float value) [inline]
Sets the offset
Parameters:
value The offset
Definition at line 255 of file MDLFileData.h.
References m_fOffset.
Referenced by affxmdl::CMDLFileData::SetDataInfo().
void affxmdl::CMDLProbeData::SetRelativeBkg (float value) [inline]
Sets the relative background
Parameters:
value The relative background
Definition at line 245 of file MDLFileData.h.
References m_fRelativeBkg.
Referenced by affxmdl::CMDLFileData::SetDataInfo().
void affxmdl::CMDLProbeData::SetSaturation (float value) [inline]
Sets the saturation
Parameters:
value The saturation
Definition at line 250 of file MDLFileData.h.
References m_fSaturation.
Referenced by affxmdl::CMDLFileData::SetDataInfo().
Friends And Related Function Documentation
friend class CMDLFileData [friend]
Memory map pointer
Definition at line 208 of file MDLFileData.h.
Member Data Documentation
bool affxmdl::CMDLProbeData::m_bMapped [protected]
An index for the object
Definition at line 205 of file MDLFileData.h.
Referenced by affxmdl::CMDLFileData::GetProbeData(), and MakeShallowCopy().
double affxmdl::CMDLProbeData::m_dAffinity [protected]
Definition at line 199 of file MDLFileData.h.
Referenced by GetAffinity(), affxmdl::CMDLFileData::GetProbeData(), MakeShallowCopy(), and SetAffinity().
float affxmdl::CMDLProbeData::m_fOffset [protected]
Reserved for future use
Definition at line 202 of file MDLFileData.h.
Referenced by GetOffset(), affxmdl::CMDLFileData::GetProbeData(), MakeShallowCopy(), and SetOffset().
float affxmdl::CMDLProbeData::m_fRelativeBkg [protected]
Probe affinity value
Definition at line 200 of file MDLFileData.h.
Referenced by affxmdl::CMDLFileData::GetProbeData(), GetRelativeBkg(), MakeShallowCopy(), and SetRelativeBkg().
float affxmdl::CMDLProbeData::m_fSaturation [protected]
Reserved for future use
Definition at line 201 of file MDLFileData.h.
Referenced by affxmdl::CMDLFileData::GetProbeData(), GetSaturation(), MakeShallowCopy(), and SetSaturation().
char* affxmdl::CMDLProbeData::m_lpData [protected]
Flag indicating if memory mapped
Definition at line 206 of file MDLFileData.h.
Referenced by affxmdl::CMDLFileData::GetProbeData(), and MakeShallowCopy().
int32_t affxmdl::CMDLProbeData::m_nIndex [protected]
Reserved for future use
Definition at line 204 of file MDLFileData.h.
Referenced by affxmdl::CMDLFileData::GetProbeData().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/MDLFileData.h
C:/f112/affy/sdk/file/MDLFileData.cpp