Affymetrix Fusion SDK: affymetrix_calvin_io::MMDATFileWriter Class Reference
affymetrix_calvin_io::MMDATFileWriter Class Reference
#include <MMDATFileWriter.h>
Public Member Functions
MMDATFileWriter (DATData &p)
~MMDATFileWriter ()
bool Open ()
bool Close ()
void MapPixelData (int32_t firstRow, int32_t rowsToMap)
u_int16_t * GetMappedPixelDataPtr ()
int32_t GetFirstPixelRowMapped ()
int32_t GetPixelRowsMapped ()
int32_t GetMaxPixelRowsToMap ()
Private Member Functions
virtual void WritePixels (const Uint16Vector &v)
void HTONPixelDataSet ()
Private Attributes
MMDataSetDataWriter * pixelWriter
std::string filename
affymetrix_calvin_io::DataSetHeader * dataSetHdr
int32_t rows
int32_t cols
Detailed Description
This class writes a DAT file. The pixel DataSet data is written using Windows memory-mapping
Definition at line 44 of file MMDATFileWriter.h.
Constructor & Destructor Documentation
MMDATFileWriter::MMDATFileWriter (DATData & p)
Constructor Creates the DAT file and writes header sections of the file.
Parameters:
p The DATData object to write to the file.
Definition at line 49 of file MMDATFileWriter.cpp.
References cols, DAT_PIXEL, dataSetHdr, filename, affymetrix_calvin_io::DataGroupHeader::FindDataSetHeader(), affymetrix_calvin_io::DATData::GetCols(), affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::DATData::GetFileHeader(), affymetrix_calvin_io::DATData::GetFilename(), affymetrix_calvin_io::DATData::GetRows(), pixelWriter, and rows.
MMDATFileWriter::~MMDATFileWriter ()
Destructor
Definition at line 61 of file MMDATFileWriter.cpp.
References Close().
Member Function Documentation
bool MMDATFileWriter::Close (void)
Closes the writer. This writes the pixel data to the file in network order and closes the file. Once the writer is closed it should not be used to open and read the pixel data, overwritting existing pixel data is OK.
Returns:
true if it succeeded. Method may also throw exceptions.
Definition at line 90 of file MMDATFileWriter.cpp.
References affymetrix_calvin_io::MMDataSetDataWriter::Close(), HTONPixelDataSet(), and pixelWriter.
Referenced by ~MMDATFileWriter().
int32_t MMDATFileWriter::GetFirstPixelRowMapped ()
Get the first DAT image row that has been mapped.
Returns:
Index of the first DAT image row mapped for access.
Definition at line 130 of file MMDATFileWriter.cpp.
References cols, affymetrix_calvin_io::MMDataSetDataWriter::GetFirstRowMapped(), and pixelWriter.
u_int16_t * MMDATFileWriter::GetMappedPixelDataPtr ()
Get a pointer to the pixel data that has been mapped for access.
Returns:
Pointer to the mapped data.
Definition at line 118 of file MMDATFileWriter.cpp.
References affymetrix_calvin_io::MMDataSetDataWriter::GetMappedDataPtr(), and pixelWriter.
int32_t MMDATFileWriter::GetMaxPixelRowsToMap ()
Get the suggested maximum number of DAT image rows to map.
Returns:
The suggested maximum number of DAT image rows to map
Definition at line 154 of file MMDATFileWriter.cpp.
References cols, affymetrix_calvin_io::MMDataSetDataWriter::GetMaxRowsToMap(), and pixelWriter.
int32_t MMDATFileWriter::GetPixelRowsMapped ()
Get the number of DAT image rows that have been mapped. The number of pixels mapped is the number of row mapped times the number of pixels per row (DATData::GetCols).
Returns:
The number of DAT image rows mapped for access.
Definition at line 142 of file MMDATFileWriter.cpp.
References cols, affymetrix_calvin_io::MMDataSetDataWriter::GetRowsMapped(), and pixelWriter.
void MMDATFileWriter::HTONPixelDataSet () [private]
Writes the pixel DataSet data in network byte order. Once this method is called this writer should not be used to read the pixel DataSet data.
Definition at line 166 of file MMDATFileWriter.cpp.
References affymetrix_calvin_io::MMDataSetDataWriter::Close(), cols, affymetrix_calvin_io::MMDataSetDataWriter::GetFirstRowMapped(), affymetrix_calvin_io::MMDataSetDataWriter::GetMappedDataPtr(), affymetrix_calvin_io::MMDataSetDataWriter::GetMaxRowsToMap(), affymetrix_calvin_io::MMDataSetDataWriter::GetRowsMapped(), affymetrix_calvin_io::MMDataSetDataWriter::MapData(), affymetrix_calvin_io::MMDataSetDataWriter::Open(), pixelWriter, and rows.
Referenced by Close().
void MMDATFileWriter::MapPixelData (int32_t firstRow, int32_t rowsToMap)
Maps the pixel data for access starting at firstRow and continuing for rowsToMap. The number of pixels mapped is the number of row mapped times the number of pixels per row (DATData::GetCols).
Parameters:
firstRow First row of the DAT image to map for access.
rowsToMap Requested number of DAT image rows to map. Use GetRowsMapped for number of rows actually mapped.
Definition at line 107 of file MMDATFileWriter.cpp.
References cols, affymetrix_calvin_io::MMDataSetDataWriter::MapData(), and pixelWriter.
bool MMDATFileWriter::Open ()
Opens the writer. This opens the file and a memory-mapped view of the pixel DataSet. It closes a previously opened file.
Returns:
true if it succeeded. Method may also throw exceptions.
Exceptions:
affymetrix_calvin_exceptions::FileCreateException
Definition at line 69 of file MMDATFileWriter.cpp.
References dataSetHdr, filename, affymetrix_calvin_io::MMDataSetDataWriter::Open(), and pixelWriter.
virtual void affymetrix_calvin_io::MMDATFileWriter::WritePixels (const Uint16Vector & v) [inline, private, virtual]
Reimplemented from affymetrix_calvin_io::DATFileWriter.
Definition at line 101 of file MMDATFileWriter.h.
Member Data Documentation
int32_t affymetrix_calvin_io::MMDATFileWriter::cols [private]
Number of columns of pixels in the DAT image
Definition at line 123 of file MMDATFileWriter.h.
Referenced by GetFirstPixelRowMapped(), GetMaxPixelRowsToMap(), GetPixelRowsMapped(), HTONPixelDataSet(), MapPixelData(), and MMDATFileWriter().
affymetrix_calvin_io::DataSetHeader* affymetrix_calvin_io::MMDATFileWriter::dataSetHdr [private]
Pointer to the pixel DataSetHeader
Definition at line 117 of file MMDATFileWriter.h.
Referenced by MMDATFileWriter(), and Open().
std::string affymetrix_calvin_io::MMDATFileWriter::filename [private]
DAT file name
Definition at line 114 of file MMDATFileWriter.h.
Referenced by MMDATFileWriter(), and Open().
MMDataSetDataWriter* affymetrix_calvin_io::MMDATFileWriter::pixelWriter [private]
Memory-mapped DataSet data writer
Definition at line 111 of file MMDATFileWriter.h.
Referenced by Close(), GetFirstPixelRowMapped(), GetMappedPixelDataPtr(), GetMaxPixelRowsToMap(), GetPixelRowsMapped(), HTONPixelDataSet(), MapPixelData(), MMDATFileWriter(), and Open().
int32_t affymetrix_calvin_io::MMDATFileWriter::rows [private]
Number of rows of pixels in the DAT image
Definition at line 120 of file MMDATFileWriter.h.
Referenced by HTONPixelDataSet(), and MMDATFileWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/MMDATFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/MMDATFileWriter.cpp