Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCDFQCProbeInformation Class Reference
affymetrix_fusion_io::FusionCDFQCProbeInformation Class Reference
#include <FusionCDFData.h>
Public Member Functions
FusionCDFQCProbeInformation ()
~FusionCDFQCProbeInformation ()
int GetX () const
int GetY () const
int GetPLen () const
bool IsPerfectMatchProbe () const
bool IsBackgroundProbe () const
Private Member Functions
void Initialize (int index, affxcdf::CCDFQCProbeSetInformation *gcosSet)
void Initialize (int index, affymetrix_calvin_io::CDFQCProbeSetInformation *calvinSet)
void Clear ()
Private Attributes
affxcdf::CCDFQCProbeInformation * gcosProbe
affymetrix_calvin_io::CDFQCProbeInformation * calvinProbe
Friends
class FusionCDFQCProbeSetInformation
Detailed Description
This class provides storage for QC probes
Definition at line 361 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFQCProbeInformation::FusionCDFQCProbeInformation ()
Constructor
Definition at line 168 of file FusionCDFData.cpp.
FusionCDFQCProbeInformation::~FusionCDFQCProbeInformation ()
Destructor
Definition at line 177 of file FusionCDFData.cpp.
Member Function Documentation
void FusionCDFQCProbeInformation::Clear (void) [private]
Deallocates any used memory.
Definition at line 205 of file FusionCDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFQCProbeSetInformation::GetProbeInformation().
int FusionCDFQCProbeInformation::GetPLen () const
Gets the probe length.
Returns:
The probe length. This value may be 1 for non-synthesized features.
Gets the probe length.
Definition at line 239 of file FusionCDFData.cpp.
Referenced by CFusionCDFQCProbeInformationCOM::get_PLen().
int FusionCDFQCProbeInformation::GetX () const
Gets the X cooridnate of the probe.
Returns:
The X coordinate.
Gets the X cooridnate of the probe.
Definition at line 215 of file FusionCDFData.cpp.
Referenced by CFusionCDFQCProbeInformationCOM::get_X().
int FusionCDFQCProbeInformation::GetY () const
Gets the Y cooridnate of the probe.
Returns:
The Y coordinate.
Gets the Y cooridnate of the probe.
Definition at line 227 of file FusionCDFData.cpp.
Referenced by CFusionCDFQCProbeInformationCOM::get_Y().
void FusionCDFQCProbeInformation::Initialize (int index, affymetrix_calvin_io::CDFQCProbeSetInformation * calvinSet) [private]
Initializes the class for Calvin file reading.
Parameters:
index The index to the probe.
calvinSet The Calvin QC probe set.
Definition at line 195 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFQCProbeSetInformation::GetProbeInformation().
void FusionCDFQCProbeInformation::Initialize (int index, affxcdf::CCDFQCProbeSetInformation * gcosSet) [private]
Initializes the class for GCOS file reading.
Parameters:
index The index to the probe.
gcosSet The GCOS QC probe set.
Definition at line 185 of file FusionCDFData.cpp.
References affxcdf::CCDFQCProbeSetInformation::GetProbeInformation().
Referenced by affymetrix_fusion_io::FusionCDFQCProbeSetInformation::GetProbeInformation().
bool FusionCDFQCProbeInformation::IsBackgroundProbe () const
Gets a flag indicating if the probe is used for background calculations (blank feature).
Returns:
Flag indicating if the probe is used for background calculations (blank feature).
Gets a flag indicating if the probe is used for background calculations (blank feature).
Definition at line 263 of file FusionCDFData.cpp.
Referenced by CFusionCDFQCProbeInformationCOM::IsBackgroundProbe().
bool FusionCDFQCProbeInformation::IsPerfectMatchProbe () const
Gets the flag indicating if the probe is a perfect match probe.
Returns:
The flag indicating if the probe is a perfect match probe
Gets the flag indicating if the probe is a perfect match probe.
Definition at line 251 of file FusionCDFData.cpp.
Referenced by CFusionCDFQCProbeInformationCOM::IsPerfectMatchProbe().
Friends And Related Function Documentation
friend class FusionCDFQCProbeSetInformation [friend]
Friend to the parent class.
Definition at line 386 of file FusionCDFData.h.
Member Data Documentation
affymetrix_calvin_io::CDFQCProbeInformation* affymetrix_fusion_io::FusionCDFQCProbeInformation::calvinProbe [private]
The Calvin probe object.
Definition at line 368 of file FusionCDFData.h.
affxcdf::CCDFQCProbeInformation* affymetrix_fusion_io::FusionCDFQCProbeInformation::gcosProbe [private]
The GCOS probe object.
Definition at line 365 of file FusionCDFData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.cpp