Affymetrix Fusion SDK: CFusionCDFDataCOM Class Reference
CFusionCDFDataCOM Class Reference
#include <FusionCDFDataCOM.h>
Public Member Functions
CFusionCDFDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
STDMETHOD() get_FileName (BSTR *pVal)
STDMETHOD() put_FileName (BSTR newVal)
STDMETHOD() GetHeader (IFusionCDFFileHeader **pVal)
STDMETHOD() get_Error (BSTR *pVal)
STDMETHOD() GetProbeSetName (int index, BSTR *pVal)
STDMETHOD() get_ChipType (BSTR *pVal)
STDMETHOD() Read (VARIANT_BOOL *pVal)
STDMETHOD() ReadHeader (VARIANT_BOOL *pVal)
STDMETHOD() Exists (VARIANT_BOOL *pVal)
STDMETHOD() Close (void)
STDMETHOD() IsXDACompatibleFile (BSTR fileName, VARIANT_BOOL *pVal)
STDMETHOD() IsCalvinCompatibleFile (BSTR fileName, VARIANT_BOOL *pVal)
STDMETHOD() GetProbeSetType (int index, GeneChipProbeSetType *pVal)
STDMETHOD() GetProbeSetInformation (int index, IFusionCDFProbeSetInformation *pVal)
STDMETHOD() GetQCProbeSetInformation (int index, IFusionCDFQCProbeSetInformation *pVal)
STDMETHOD() GetQCProbeSetInformationByType (GeneChipQCProbeSetType qcType, IFusionCDFQCProbeSetInformation *pVal)
STDMETHOD() get_ChipTypes (VARIANT *pVal)
STDMETHOD() get_GUID (BSTR *pVal)
STDMETHOD() get_IntegrityMd5 (BSTR *pVal)
Private Attributes
affymetrix_fusion_io::FusionCDFData cdf
Detailed Description
Definition at line 30 of file FusionCDFDataCOM.h.
Constructor & Destructor Documentation
CFusionCDFDataCOM::CFusionCDFDataCOM () [inline]
Definition at line 37 of file FusionCDFDataCOM.h.
Member Function Documentation
STDMETHODIMP CFusionCDFDataCOM::Close (void)
Definition at line 103 of file FusionCDFDataCOM.cpp.
References cdf, and affymetrix_fusion_io::FusionCDFData::Close().
STDMETHODIMP CFusionCDFDataCOM::Exists (VARIANT_BOOL * pVal)
Definition at line 97 of file FusionCDFDataCOM.cpp.
References cdf, and affymetrix_fusion_io::FusionCDFData::Exists().
HRESULT CFusionCDFDataCOM::FinalConstruct () [inline]
Definition at line 56 of file FusionCDFDataCOM.h.
void CFusionCDFDataCOM::FinalRelease () [inline]
Definition at line 61 of file FusionCDFDataCOM.h.
STDMETHODIMP CFusionCDFDataCOM::get_ChipType (BSTR * pVal)
Definition at line 79 of file FusionCDFDataCOM.cpp.
References cdf, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCDFData::GetChipType().
STDMETHODIMP CFusionCDFDataCOM::get_ChipTypes (VARIANT * pVal)
Definition at line 148 of file FusionCDFDataCOM.cpp.
References cdf, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCDFData::GetChipTypes().
STDMETHODIMP CFusionCDFDataCOM::get_Error (BSTR * pVal)
Definition at line 67 of file FusionCDFDataCOM.cpp.
References cdf, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCDFData::GetError().
STDMETHODIMP CFusionCDFDataCOM::get_FileName (BSTR * pVal)
Definition at line 45 of file FusionCDFDataCOM.cpp.
References cdf, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCDFData::GetFileName().
STDMETHODIMP CFusionCDFDataCOM::get_GUID (BSTR * pVal)
Definition at line 167 of file FusionCDFDataCOM.cpp.
References cdf, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCDFData::GetGUID().
STDMETHODIMP CFusionCDFDataCOM::get_IntegrityMd5 (BSTR * pVal)
Definition at line 173 of file FusionCDFDataCOM.cpp.
References cdf, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCDFData::GetIntegrityMd5().
STDMETHODIMP CFusionCDFDataCOM::GetHeader (IFusionCDFFileHeader ** pVal)
Definition at line 57 of file FusionCDFDataCOM.cpp.
References cdf, affymetrix_fusion_io::FusionCDFData::GetHeader(), and CFusionCDFFileHeaderCOM::SetHeader().
STDMETHODIMP CFusionCDFDataCOM::GetProbeSetInformation (int index, IFusionCDFProbeSetInformation * pVal)
Definition at line 127 of file FusionCDFDataCOM.cpp.
References cdf, and affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation().
STDMETHODIMP CFusionCDFDataCOM::GetProbeSetName (int index, BSTR * pVal)
Definition at line 73 of file FusionCDFDataCOM.cpp.
References cdf, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCDFData::GetProbeSetName().
STDMETHODIMP CFusionCDFDataCOM::GetProbeSetType (int index, GeneChipProbeSetType * pVal)
Definition at line 121 of file FusionCDFDataCOM.cpp.
References cdf, and affymetrix_fusion_io::FusionCDFData::GetProbeSetType().
STDMETHODIMP CFusionCDFDataCOM::GetQCProbeSetInformation (int index, IFusionCDFQCProbeSetInformation * pVal)
Definition at line 134 of file FusionCDFDataCOM.cpp.
References cdf, and affymetrix_fusion_io::FusionCDFData::GetQCProbeSetInformation().
STDMETHODIMP CFusionCDFDataCOM::GetQCProbeSetInformationByType (GeneChipQCProbeSetType qcType, IFusionCDFQCProbeSetInformation * pVal)
Definition at line 141 of file FusionCDFDataCOM.cpp.
References cdf, and affymetrix_fusion_io::FusionCDFData::GetQCProbeSetInformation().
STDMETHODIMP CFusionCDFDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 30 of file FusionCDFDataCOM.cpp.
STDMETHODIMP CFusionCDFDataCOM::IsCalvinCompatibleFile (BSTR fileName, VARIANT_BOOL * pVal)
Definition at line 115 of file FusionCDFDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CFusionCDFDataCOM::IsXDACompatibleFile (BSTR fileName, VARIANT_BOOL * pVal)
Definition at line 109 of file FusionCDFDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CFusionCDFDataCOM::put_FileName (BSTR newVal)
Definition at line 51 of file FusionCDFDataCOM.cpp.
References cdf, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCDFData::SetFileName().
STDMETHODIMP CFusionCDFDataCOM::Read (VARIANT_BOOL * pVal)
Definition at line 85 of file FusionCDFDataCOM.cpp.
References cdf, and affymetrix_fusion_io::FusionCDFData::Read().
STDMETHODIMP CFusionCDFDataCOM::ReadHeader (VARIANT_BOOL * pVal)
Definition at line 91 of file FusionCDFDataCOM.cpp.
References cdf, and affymetrix_fusion_io::FusionCDFData::ReadHeader().
Member Data Documentation
affymetrix_fusion_io::FusionCDFData CFusionCDFDataCOM::cdf [private]
Definition at line 66 of file FusionCDFDataCOM.h.
Referenced by Close(), Exists(), get_ChipType(), get_ChipTypes(), get_Error(), get_FileName(), get_GUID(), get_IntegrityMd5(), GetHeader(), GetProbeSetInformation(), GetProbeSetName(), GetProbeSetType(), GetQCProbeSetInformation(), GetQCProbeSetInformationByType(), put_FileName(), Read(), and ReadHeader().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFDataCOM.cpp