Affymetrix Fusion SDK: affymetrix_calvin_io::FileHeaderUpdater Class Reference
affymetrix_calvin_io::FileHeaderUpdater Class Reference
#include <FileHeaderUpdater.h>
Public Member Functions
FileHeaderUpdater ()
FileHeaderUpdater (std::ofstream &ostrm, FileHeader &fileHdr)
~FileHeaderUpdater ()
bool Update (std::ofstream &ostrm, FileHeader &updateHdr, FileHeader &currentHdr)
void AppendDataGroupHeader (DataGroupHeader &grpHdr)
void UpdateDataGroupCount (int32_t count)
void UpdateLeadDataGroupOffset (u_int32_t pos)
Private Member Functions
void SeekDataGrpCntPosition ()
void SeekLeadDataGrpPosition ()
void SeekVersionPosition ()
Private Attributes
std::ofstream * os
FileHeader * fileHdr
Detailed Description
This class updates the FileHeader of an existing file with new information.
Definition at line 43 of file FileHeaderUpdater.h.
Constructor & Destructor Documentation
FileHeaderUpdater::FileHeaderUpdater ()
Constructor
Definition at line 31 of file FileHeaderUpdater.cpp.
References fileHdr, and os.
FileHeaderUpdater::FileHeaderUpdater (std::ofstream & ostrm, FileHeader & fileHdr)
Constructor
Definition at line 37 of file FileHeaderUpdater.cpp.
References fileHdr, and os.
FileHeaderUpdater::~FileHeaderUpdater ()
Destructor
Definition at line 46 of file FileHeaderUpdater.cpp.
Member Function Documentation
void FileHeaderUpdater::AppendDataGroupHeader (DataGroupHeader & grpHdr)
Definition at line 121 of file FileHeaderUpdater.cpp.
References affymetrix_calvin_io::FileHeader::AddDataGroupHdr(), fileHdr, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriters(), os, affymetrix_calvin_io::DataGroupHeader::SetDataSetPos(), affymetrix_calvin_io::DataGroupHeader::SetHeaderStartFilePos(), UpdateDataGroupCount(), UpdateLeadDataGroupOffset(), affymetrix_calvin_io::DataGroupHeaderUpdater::UpdateNextDataGroupOffset(), and affymetrix_calvin_io::DataGroupWriter::WriteHeader().
void FileHeaderUpdater::SeekDataGrpCntPosition () [private]
Definition at line 94 of file FileHeaderUpdater.cpp.
References os.
Referenced by UpdateDataGroupCount().
void FileHeaderUpdater::SeekLeadDataGrpPosition () [private]
Definition at line 103 of file FileHeaderUpdater.cpp.
References os.
Referenced by UpdateLeadDataGroupOffset().
void FileHeaderUpdater::SeekVersionPosition () [private]
Definition at line 86 of file FileHeaderUpdater.cpp.
References os.
bool FileHeaderUpdater::Update (std::ofstream & ostrm, FileHeader & updateHdr, FileHeader & currentHdr)
Update the file with new FileHeader information
Parameters:
os An output stream open with std::ios::out|std::ios::binary|std::ios::in.
updateHdr A FileHeader with information to update the file.
currentHdr A FileHeader with information current in the file.
Returns:
Returns true if successful.
Definition at line 53 of file FileHeaderUpdater.cpp.
References affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), and affymetrix_calvin_io::GenericDataHeaderUpdater::Update().
Referenced by affymetrix_calvin_io::DATFileUpdater::UpdateFileHeader().
void FileHeaderUpdater::UpdateDataGroupCount (int32_t count)
Definition at line 78 of file FileHeaderUpdater.cpp.
References os, SeekDataGrpCntPosition(), and affymetrix_calvin_io::FileOutput::WriteUInt32().
Referenced by AppendDataGroupHeader().
void FileHeaderUpdater::UpdateLeadDataGroupOffset (u_int32_t pos)
Definition at line 113 of file FileHeaderUpdater.cpp.
References os, SeekLeadDataGrpPosition(), and affymetrix_calvin_io::FileOutput::WriteUInt32().
Referenced by AppendDataGroupHeader().
Member Data Documentation
FileHeader* affymetrix_calvin_io::FileHeaderUpdater::fileHdr [private]
The data set header
Definition at line 75 of file FileHeaderUpdater.h.
Referenced by AppendDataGroupHeader(), and FileHeaderUpdater().
std::ofstream* affymetrix_calvin_io::FileHeaderUpdater::os [private]
Open output filestream
Definition at line 72 of file FileHeaderUpdater.h.
Referenced by AppendDataGroupHeader(), FileHeaderUpdater(), SeekDataGrpCntPosition(), SeekLeadDataGrpPosition(), SeekVersionPosition(), UpdateDataGroupCount(), and UpdateLeadDataGroupOffset().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/FileHeaderUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/FileHeaderUpdater.cpp