Affymetrix Fusion SDK: affxchp::CUniversalProbeSetResults Class Reference
affxchp::CUniversalProbeSetResults Class Reference
#include <CHPFileData.h>
Public Member Functions
float GetBackground () const
void SetBackground (float bg)
CUniversalProbeSetResults operator= (CUniversalProbeSetResults &src)
CUniversalProbeSetResults ()
~CUniversalProbeSetResults ()
Protected Attributes
float background
Detailed Description
Universal (tag array) analysis probe set results.
Definition at line 480 of file CHPFileData.h.
Constructor & Destructor Documentation
affxchp::CUniversalProbeSetResults::CUniversalProbeSetResults () [inline]
Constructor
Definition at line 504 of file CHPFileData.h.
References background.
affxchp::CUniversalProbeSetResults::~CUniversalProbeSetResults () [inline]
Destructor
Definition at line 507 of file CHPFileData.h.
Member Function Documentation
float affxchp::CUniversalProbeSetResults::GetBackground () const [inline]
Gets the background value.
Returns:
The background value.
Definition at line 490 of file CHPFileData.h.
References background.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetUniversalResults(), operator=(), and affxchpwriter::CCHPFileWriter::SaveUniversalEntry().
CUniversalProbeSetResults CUniversalProbeSetResults::operator= (CUniversalProbeSetResults & src)
Assignment operator
Parameters:
src The object to copy
Returns:
The copied object
Definition at line 305 of file CHPFileData.cpp.
References GetBackground(), and SetBackground().
void affxchp::CUniversalProbeSetResults::SetBackground (float bg) [inline]
Sets the background value.
Parameters:
bg The background value.
Definition at line 495 of file CHPFileData.h.
References background.
Referenced by affxchp::CCHPFileData::Open(), and operator=().
Member Data Documentation
float affxchp::CUniversalProbeSetResults::background [protected]
The background value.
Definition at line 484 of file CHPFileData.h.
Referenced by CUniversalProbeSetResults(), GetBackground(), and SetBackground().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CHPFileData.h
C:/f112/affy/sdk/file/CHPFileData.cpp