Affymetrix Fusion SDK: affxbarwriter::CBARFileWriter Class Reference
affxbarwriter::CBARFileWriter Class Reference
#include <BARFileWriter.h>
Public Member Functions
CBARFileWriter ()
~CBARFileWriter ()
bool CreateNewFile ()
bool Save ()
Protected Attributes
std::ofstream m_NewBarFile
Detailed Description
This class provides writing capabilities for BAR files.
Definition at line 46 of file BARFileWriter.h.
Constructor & Destructor Documentation
CBARFileWriter::CBARFileWriter ()
Constructor
Definition at line 53 of file BARFileWriter.cpp.
CBARFileWriter::~CBARFileWriter ()
Destructor
Definition at line 59 of file BARFileWriter.cpp.
References affxbar::CBARFileData::Close().
Member Function Documentation
bool CBARFileWriter::CreateNewFile ()
Creates a new file.
Returns:
True if successful
Definition at line 66 of file BARFileWriter.cpp.
References affxbar::CBARFileData::m_FileName, m_NewBarFile, affxbar::CBARFileData::m_strError, and affxbar::CBARFileData::m_Version.
bool CBARFileWriter::Save ()
Saves the data to the BAR file.
Returns:
True if successful
Definition at line 83 of file BARFileWriter.cpp.
References affxbar::BAR_DATA_INTEGER, BAR_VERSION, affxbar::_BarSequenceResultData::fValue, affxbar::CBARFileData::GetNumberColumns(), affxbar::CBARFileData::GetNumberParameters(), affxbar::CBARFileData::GetParameter(), affxbar::CBARFileData::GetVersion(), affxbar::_BarSequenceResultData::iValue, affxbar::CBARFileData::m_ColumnTypes, m_NewBarFile, affxbar::CBARFileData::m_NumberColumns, affxbar::CBARFileData::m_NumberParameters, affxbar::CBARFileData::m_NumberSequences, affxbar::CBARFileData::m_Parameters, affxbar::CBARFileData::m_Results, affymetrix_calvin_io::Tag, WriteFixedString(), WriteFloat_N(), WriteInt32_N(), and WriteString_N().
Member Data Documentation
std::ofstream affxbarwriter::CBARFileWriter::m_NewBarFile [protected]
The output file stream.
Definition at line 57 of file BARFileWriter.h.
Referenced by CreateNewFile(), and Save().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/BARFileWriter.h
C:/f112/affy/sdk/file/BARFileWriter.cpp