Affymetrix Fusion SDK: affymetrix_calvin_io::SAXParameterFileHandlers Class Reference
affymetrix_calvin_io::SAXParameterFileHandlers Class Reference
#include <SAXParameterFileHandlers.h>
Public Member Functions
SAXParameterFileHandlers (affymetrix_calvin_parameter::ParameterFileData *data)
~SAXParameterFileHandlers ()
void startDocument ()
void endDocument ()
void characters (const XMLCh *const chars, const unsigned int length)
void startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList &attributes)
void endElement (const XMLCh *const name)
Private Member Functions
void StoreParameterFileAttributes (std::map< std::wstring, std::wstring > &attributes)
void StoreImplementationAttributes (std::map< std::wstring, std::wstring > &attributes)
void StoreParameterAttributes (std::map< std::wstring, std::wstring > &attributes)
void MoveCurrentElementBack (const XMLCh *const name)
bool MoveCurrentElementForward (const XMLCh *const name)
Private Attributes
affymetrix_calvin_parameter::ParameterFileData * parameterFileData
ParameterFileElements currentElement
Detailed Description
This class provides the SAX handlers for reading calvin parameter files.
Definition at line 188 of file SAXParameterFileHandlers.h.
Constructor & Destructor Documentation
SAXParameterFileHandlers::SAXParameterFileHandlers (affymetrix_calvin_parameter::ParameterFileData * data)
Constructor
Parameters:
data The parameter file data.
Definition at line 77 of file SAXParameterFileHandlers.cpp.
SAXParameterFileHandlers::~SAXParameterFileHandlers ()
Destructor
Definition at line 86 of file SAXParameterFileHandlers.cpp.
Member Function Documentation
void SAXParameterFileHandlers::characters (const XMLCh *const chars, const unsigned int length)
Receive notification of character data inside an element.
Parameters:
chars The character data.
length The length of the character string.
Definition at line 188 of file SAXParameterFileHandlers.cpp.
void SAXParameterFileHandlers::endDocument ()
Called at the end of the document
Definition at line 100 of file SAXParameterFileHandlers.cpp.
void SAXParameterFileHandlers::endElement (const XMLCh *const name)
Called at the end of each element.
Parameters:
name The name of the element.
Definition at line 107 of file SAXParameterFileHandlers.cpp.
References MoveCurrentElementBack().
void SAXParameterFileHandlers::MoveCurrentElementBack (const XMLCh *const name) [private]
Modifies the state machine given the end of an element.
Parameters:
name The name of the element.
Definition at line 115 of file SAXParameterFileHandlers.cpp.
References currentElement, IMPLEMENTATION_ELEMENT, PARAMETER_ELEMENT, and affymetrix_calvin_io::PARAMETER_FILE.
Referenced by endElement().
bool SAXParameterFileHandlers::MoveCurrentElementForward (const XMLCh *const name) [private]
Modifies the state machine given the start of an element.
Parameters:
name The name of the element.
Returns:
True is a valid element was found.
Definition at line 130 of file SAXParameterFileHandlers.cpp.
References currentElement, affymetrix_calvin_io::IMPLEMENTATION, IMPLEMENTATION_ELEMENT, affymetrix_calvin_io::PARAMETER, PARAMETER_ELEMENT, affymetrix_calvin_io::PARAMETER_FILE, and PARAMETER_FILE_ELEMENT.
void SAXParameterFileHandlers::startDocument ()
Called at the start of the document
Definition at line 93 of file SAXParameterFileHandlers.cpp.
void affymetrix_calvin_io::SAXParameterFileHandlers::startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList & attributes)
Called at the start of each element.
Parameters:
name The name of the element.
attributes The attributes of the element.
void SAXParameterFileHandlers::StoreImplementationAttributes (std::map< std::wstring, std::wstring > & attributes) [private]
Stores the attribites from the implementation element.
Parameters:
attributes The name/value attributes.
Definition at line 219 of file SAXParameterFileHandlers.cpp.
References affymetrix_calvin_parameter::_ImplementationAttributesType::description, affymetrix_calvin_parameter::_ImplementationAttributesType::executableFileName, IMPLEMENTATION_DESC_ATTRIBUTE, IMPLEMENTATION_EXE_FILE_NAME_ATTRIBUTE, IMPLEMENTATION_NAME_ATTRIBUTE, IMPLEMENTATION_VERSION_ATTRIBUTE, affymetrix_calvin_parameter::ParameterFileData::ImplementationAttributes(), affymetrix_calvin_parameter::_ImplementationAttributesType::name, parameterFileData, and affymetrix_calvin_parameter::_ImplementationAttributesType::version.
void SAXParameterFileHandlers::StoreParameterAttributes (std::map< std::wstring, std::wstring > & attributes) [private]
Stores the attributes from the parameter attribute element.
Parameters:
attributes The name/value attributes.
Definition at line 195 of file SAXParameterFileHandlers.cpp.
References affymetrix_calvin_parameter::_ParameterType::category, affymetrix_calvin_parameter::_ParameterType::currentValue, affymetrix_calvin_parameter::_ParameterType::defaultValue, affymetrix_calvin_parameter::_ParameterType::description, affymetrix_calvin_parameter::_ParameterType::displayName, affymetrix_calvin_parameter::_ParameterType::index, affymetrix_calvin_parameter::_ParameterType::isEditable, affymetrix_calvin_parameter::_ParameterType::maxLength, affymetrix_calvin_parameter::_ParameterType::maxValue, affymetrix_calvin_parameter::_ParameterType::minValue, affymetrix_calvin_parameter::_ParameterType::name, PARAMETER_CATEGORY_ATTRIBUTE, PARAMETER_CURVALUE_ATTRIBUTE, PARAMETER_DEFVALUE_ATTRIBUTE, PARAMETER_DESC_ATTRIBUTE, PARAMETER_DISPLAY_NAME_ATTRIBUTE, PARAMETER_INDEX_ATTRIBUTE, PARAMETER_ISEDITABLE_ATTRIBUTE, PARAMETER_MAXLENGTH_ATTRIBUTE, PARAMETER_MAXVALUE_ATTRIBUTE, PARAMETER_MINVALUE_ATTRIBUTE, PARAMETER_NAME_ATTRIBUTE, PARAMETER_PRECISION_ATTRIBUTE, PARAMETER_TYPE_ATTRIBUTE, parameterFileData, affymetrix_calvin_parameter::ParameterFileData::Parameters(), affymetrix_calvin_parameter::_ParameterType::precision, and affymetrix_calvin_parameter::_ParameterType::type.
void SAXParameterFileHandlers::StoreParameterFileAttributes (std::map< std::wstring, std::wstring > & attributes) [private]
Stores the attributes from the parameter file element.
Parameters:
attributes The name/value attributes.
Definition at line 230 of file SAXParameterFileHandlers.cpp.
References affymetrix_calvin_parameter::_ParameterFileAttributesType::company, affymetrix_calvin_parameter::_ParameterFileAttributesType::contentVersion, PARAMETER_FILE_COMPANY_ATTRIBUTE, PARAMETER_FILE_CONTENT_VERSION_ATTRIBUTE, PARAMETER_FILE_USER_NAME_ATTRIBUTE, affymetrix_calvin_parameter::ParameterFileData::ParameterFileAttributes(), parameterFileData, and affymetrix_calvin_parameter::_ParameterFileAttributesType::userName.
Member Data Documentation
ParameterFileElements affymetrix_calvin_io::SAXParameterFileHandlers::currentElement [private]
The parent element that is currently being processed.
Definition at line 195 of file SAXParameterFileHandlers.h.
Referenced by MoveCurrentElementBack(), and MoveCurrentElementForward().
affymetrix_calvin_parameter::ParameterFileData* affymetrix_calvin_io::SAXParameterFileHandlers::parameterFileData [private]
A pointer to the parameter file data object.
Definition at line 192 of file SAXParameterFileHandlers.h.
Referenced by StoreImplementationAttributes(), StoreParameterAttributes(), and StoreParameterFileAttributes().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/SAXParameterFileHandlers.h
C:/f112/affy/sdk/calvin_files/parsers/src/SAXParameterFileHandlers.cpp