Affymetrix Fusion SDK: affymetrix_calvin_io::DataGroup Class Reference
affymetrix_calvin_io::DataGroup Class Reference
#include <DataGroup.h>
Public Member Functions
DataGroup (const std::string &filename, const DataGroupHeader &dch, void *handle, bool loadEntireDataSetHint=false)
DataGroup (const std::string &filename, const DataGroupHeader &dch, std::ifstream &ifs, bool loadEntireDataSetHint=false)
const
affymetrix_calvin_io::DataGroupHeader & Header ()
affymetrix_calvin_io::DataSet * DataSet (u_int32_t dataSetIdx)
affymetrix_calvin_io::DataSet * DataSet (const std::wstring &dataSetName)
Protected Attributes
std::string filename
DataGroupHeader dataGroupHeader
bool useMemoryMapping
void * handle
std::ifstream * fileStream
bool loadEntireDataSetHint
Detailed Description
This class provides methods to get a DataSet in a DataGroup.
Definition at line 49 of file DataGroup.h.
Constructor & Destructor Documentation
DataGroup::DataGroup (const std::string & filename, const DataGroupHeader & dch, void * handle, bool loadEntireDataSetHint = false)
Constructor
Parameters:
filename The name of the generic file to access.
dch The DataGroupHeader of the DataGroup to access.
handle A handle to the file mapping object
loadEntireDataSetHint Indicates if DataSets created by DataGroup will attempt to read the entire DataSet data into a memory buffer.
Definition at line 35 of file DataGroup.cpp.
Referenced by affymetrix_calvin_io::CDFData::GetProbeSetInformation(), affymetrix_calvin_io::CDFData::GetProbeSetName(), affymetrix_calvin_io::CDFData::GetQCProbeSetInformation(), affymetrix_calvin_io::CDFData::PrepareForAccessByProbeSetIndex(), affymetrix_calvin_io::CDFData::PrepareForAccessByProbeSetName(), and affymetrix_calvin_io::CDFData::PrepareForSequentialAccess().
DataGroup::DataGroup (const std::string & filename, const DataGroupHeader & dch, std::ifstream & ifs, bool loadEntireDataSetHint = false)
Constructor
Parameters:
filename The name of the generic file to access.
dch The DataGroupHeader of the DataGroup to access.
ifs An open ifstream object.
loadEntireDataSetHint Indicates if DataSets created by DataGroup will attempt to read the entire DataSet data into a memory buffer.
Definition at line 43 of file DataGroup.cpp.
Member Function Documentation
affymetrix_calvin_io::DataSet * DataGroup::DataSet (u_int32_t dataSetIdx)
Returns a pointer to the DataSet object by DataSet index. Each call will return a new DataSet object. The caller should call Delete when finished with the DataSet.
Parameters:
dataSetIdx The index of the DataSet to return.
Returns:
DataSet
Exceptions:
affymetrix_calvin_exceptions::DataGroupNotFoundException DataGroup not found.
affymetrix_calvin_exceptions::DataSetNotFoundException DataSet not found.
Returns a pointer to the DataSet object by DataSet index. Each call will return a new DataSet object. The caller should call Delete when finished with the DataSet.
Parameters:
dataSetIdx The index of the DataSet to return.
Returns:
DataSet
Exceptions:
affymetrix_calvin_exceptions::DataSetNotFoundException DataSet not found.
Definition at line 56 of file DataGroup.cpp.
References dataGroupHeader, filename, fileStream, affymetrix_calvin_io::GenericData::FindDataSetHeader(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), handle, loadEntireDataSetHint, and useMemoryMapping.
Referenced by DataSet(), affymetrix_calvin_io::CDFProbeSetInformation::GetGroupInformation(), affymetrix_calvin_io::CDFData::GetProbeSetName(), affymetrix_calvin_io::CDFData::GetQCProbeSetInformation(), affymetrix_calvin_io::CDFData::PrepareForAccessByProbeSetIndex(), and affymetrix_calvin_io::CDFData::PrepareForAccessByProbeSetName().
affymetrix_calvin_io::DataSet * DataGroup::DataSet (const std::wstring & dataSetName)
Returns a pointer to the DataSet object by DataSet name. Each call will return a new DataSet object. The caller should call Delete when finished with the DataSet.
Parameters:
dataSetName The name of the DataSet to return.
Returns:
DataSet
Exceptions:
affymetrix_calvin_exceptions::DataGroupNotFoundException DataGroup not found.
affymetrix_calvin_exceptions::DataSetNotFoundException DataSet not found.
Returns a pointer to the DataSet object by DataSet name. Each call will return a new DataSet object. The caller should call Delete when finished with the DataSet.
Parameters:
dataSetName The name of the DataSet to return.
Returns:
DataSet
Exceptions:
affymetrix_calvin_exceptions::DataSetNotFoundException DataSet not found.
Definition at line 81 of file DataGroup.cpp.
References dataGroupHeader, DataSet(), filename, fileStream, affymetrix_calvin_io::GenericData::FindDataSetHeader(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), handle, loadEntireDataSetHint, and useMemoryMapping.
const affymetrix_calvin_io::DataGroupHeader& affymetrix_calvin_io::DataGroup::Header () [inline]
Method to get a reference to the DataGroupHeader
Returns:
A reference to the DataGroupHeader.
Definition at line 71 of file DataGroup.h.
References dataGroupHeader.
Referenced by affymetrix_calvin_io::CDFProbeSetInformation::GetName(), affymetrix_calvin_io::CDFData::GetProbeSetInformation(), affymetrix_calvin_io::CDFData::GetQCProbeSetInformation(), affymetrix_calvin_io::CDFData::PrepareForSequentialAccess(), and affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup().
Member Data Documentation
DataGroupHeader affymetrix_calvin_io::DataGroup::dataGroupHeader [protected]
DataGroupHeader of the DataGroup from which to get DataSets
Definition at line 99 of file DataGroup.h.
Referenced by DataSet(), and Header().
std::string affymetrix_calvin_io::DataGroup::filename [protected]
Name of the generic file to access
Definition at line 97 of file DataGroup.h.
Referenced by DataSet().
std::ifstream* affymetrix_calvin_io::DataGroup::fileStream [protected]
An open ifstream object
Definition at line 105 of file DataGroup.h.
Referenced by DataSet().
void* affymetrix_calvin_io::DataGroup::handle [protected]
File mapping object handle
Definition at line 103 of file DataGroup.h.
Referenced by DataSet().
bool affymetrix_calvin_io::DataGroup::loadEntireDataSetHint [protected]
Indicates whether DataSets created by DataGroup should attempt to read all data into a memory buffer.
Definition at line 107 of file DataGroup.h.
Referenced by DataSet().
bool affymetrix_calvin_io::DataGroup::useMemoryMapping [protected]
A flag the indicates the data access mode. True = access the data using memory-mapping. False = access the data using std::ifstream
Definition at line 101 of file DataGroup.h.
Referenced by DataSet().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/DataGroup.h
C:/f112/affy/sdk/calvin_files/data/src/DataGroup.cpp