Affymetrix Fusion SDK: CFusionCDFQCProbeInformationCOM Class Reference
CFusionCDFQCProbeInformationCOM Class Reference
#include <FusionCDFQCProbeInformationCOM.h>
Public Member Functions
CFusionCDFQCProbeInformationCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_fusion_io::FusionCDFQCProbeInformation & Probe ()
STDMETHOD() get_X (int *pVal)
STDMETHOD() get_Y (int *pVal)
STDMETHOD() get_PLen (int *pVal)
STDMETHOD() IsPerfectMatchProbe (VARIANT_BOOL *pVal)
STDMETHOD() IsBackgroundProbe (VARIANT_BOOL *pVal)
Private Attributes
affymetrix_fusion_io::FusionCDFQCProbeInformation probe
Detailed Description
Definition at line 30 of file FusionCDFQCProbeInformationCOM.h.
Constructor & Destructor Documentation
CFusionCDFQCProbeInformationCOM::CFusionCDFQCProbeInformationCOM () [inline]
Definition at line 37 of file FusionCDFQCProbeInformationCOM.h.
Member Function Documentation
HRESULT CFusionCDFQCProbeInformationCOM::FinalConstruct () [inline]
Definition at line 56 of file FusionCDFQCProbeInformationCOM.h.
void CFusionCDFQCProbeInformationCOM::FinalRelease () [inline]
Definition at line 61 of file FusionCDFQCProbeInformationCOM.h.
STDMETHODIMP CFusionCDFQCProbeInformationCOM::get_PLen (int * pVal)
Definition at line 54 of file FusionCDFQCProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFQCProbeInformation::GetPLen(), and probe.
STDMETHODIMP CFusionCDFQCProbeInformationCOM::get_X (int * pVal)
Definition at line 42 of file FusionCDFQCProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFQCProbeInformation::GetX(), and probe.
STDMETHODIMP CFusionCDFQCProbeInformationCOM::get_Y (int * pVal)
Definition at line 48 of file FusionCDFQCProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFQCProbeInformation::GetY(), and probe.
STDMETHODIMP CFusionCDFQCProbeInformationCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 27 of file FusionCDFQCProbeInformationCOM.cpp.
STDMETHODIMP CFusionCDFQCProbeInformationCOM::IsBackgroundProbe (VARIANT_BOOL * pVal)
Definition at line 66 of file FusionCDFQCProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFQCProbeInformation::IsBackgroundProbe(), and probe.
STDMETHODIMP CFusionCDFQCProbeInformationCOM::IsPerfectMatchProbe (VARIANT_BOOL * pVal)
Definition at line 60 of file FusionCDFQCProbeInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFQCProbeInformation::IsPerfectMatchProbe(), and probe.
affymetrix_fusion_io::FusionCDFQCProbeInformation& CFusionCDFQCProbeInformationCOM::Probe () [inline]
Definition at line 69 of file FusionCDFQCProbeInformationCOM.h.
Referenced by CFusionCDFQCProbeSetInformationCOM::GetProbeInformation().
Member Data Documentation
affymetrix_fusion_io::FusionCDFQCProbeInformation CFusionCDFQCProbeInformationCOM::probe [private]
Definition at line 66 of file FusionCDFQCProbeInformationCOM.h.
Referenced by get_PLen(), get_X(), get_Y(), IsBackgroundProbe(), and IsPerfectMatchProbe().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFQCProbeInformationCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFQCProbeInformationCOM.cpp