Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPQuantificationDetectionData Class Reference
affymetrix_fusion_io::FusionCHPQuantificationDetectionData Class Reference
#include <FusionCHPQuantificationDetectionData.h>
Classes
class Reg
Public Member Functions
~FusionCHPQuantificationDetectionData ()
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()
affymetrix_calvin_io::GenericData * GetGenericData ()
affymetrix_calvin_io::DataSetHeader & GetDataSetHeader ()
affymetrix_calvin_utilities::AffymetrixGuidType GetObjectName ()
std::wstring GetAlgName ()
std::wstring GetAlgVersion ()
std::wstring GetArrayType ()
ParameterNameValueTypeList GetAlgParams ()
ParameterNameValueTypeList GetSummaryParams ()
int32_t GetEntryCount ()
void GetQuantificationDetectionEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationDetectionData &entry)
Static Public Member Functions
static
FusionCHPQuantificationDetectionData * FromBase (FusionCHPData *chip)
Static Public Attributes
static Reg reg
Private Member Functions
FusionCHPQuantificationDetectionData ()
bool Read ()
bool ReadHeader ()
Private Attributes
affymetrix_calvin_io::CHPQuantificationDetectionData chpData
Detailed Description
This class provides storage and reading capabilities for quantification/detection CHP files
Definition at line 34 of file FusionCHPQuantificationDetectionData.h.
Constructor & Destructor Documentation
FusionCHPQuantificationDetectionData::FusionCHPQuantificationDetectionData () [private]
Constructor
Definition at line 40 of file FusionCHPQuantificationDetectionData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::Reg::MakeObject().
FusionCHPQuantificationDetectionData::~FusionCHPQuantificationDetectionData ()
Destructor
Definition at line 47 of file FusionCHPQuantificationDetectionData.cpp.
Member Function Documentation
AffymetrixGuidType FusionCHPQuantificationDetectionData::FileId () [virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 96 of file FusionCHPQuantificationDetectionData.cpp.
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_FileId().
FusionCHPQuantificationDetectionData * FusionCHPQuantificationDetectionData::FromBase (FusionCHPData * chip) [static]
Converts the type to the quantification/detection CHP type.
Parameters:
chip The pointer to the CHP data object.
Returns:
The quantification/detection CHP data type or NULL if not compatible.
Definition at line 81 of file FusionCHPQuantificationDetectionData.cpp.
References affymetrix_fusion_io::FusionCHPData::GetObjectName(), and ObjectName.
std::wstring affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgName () [inline]
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 66 of file FusionCHPQuantificationDetectionData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationDetectionData::GetAlgName().
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_AlgName().
ParameterNameValueTypeList affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgParams () [inline]
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 79 of file FusionCHPQuantificationDetectionData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationDetectionData::GetAlgParams().
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_AlgorithmParameters().
std::wstring affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgVersion () [inline]
Gets the algorithm version.
Returns:
The version.
Definition at line 71 of file FusionCHPQuantificationDetectionData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationDetectionData::GetAlgVersion().
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_AlgVersion().
std::wstring affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetArrayType () [inline]
Sets the array type
Definition at line 74 of file FusionCHPQuantificationDetectionData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationDetectionData::GetArrayType().
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_ArrayType().
affymetrix_calvin_io::DataSetHeader& affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetDataSetHeader () [inline]
Returns the data set header.
Definition at line 58 of file FusionCHPQuantificationDetectionData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationDetectionData::GetDataSetHeader().
int32_t affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetEntryCount () [inline]
Gets the number of entries (probe sets)
Definition at line 87 of file FusionCHPQuantificationDetectionData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationDetectionData::GetEntryCount().
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_EntryCount().
GenericData * FusionCHPQuantificationDetectionData::GetGenericData () [virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 104 of file FusionCHPQuantificationDetectionData.cpp.
AffymetrixGuidType FusionCHPQuantificationDetectionData::GetObjectName () [virtual]
Gets the class name.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 88 of file FusionCHPQuantificationDetectionData.cpp.
References ObjectName.
void affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetQuantificationDetectionEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationDetectionData & entry) [inline]
Gets the sequence data.
Parameters:
index The row index.
entry The quantification/detection value.
Definition at line 93 of file FusionCHPQuantificationDetectionData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationDetectionData::GetQuantificationDetectionEntry().
Referenced by CFusionCHPQuantificationDetectionDataCOM::GetQuantificationDetectionEntry().
ParameterNameValueTypeList affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetSummaryParams () [inline]
Gets the summary parameters
Returns:
The summary parameters.
Definition at line 84 of file FusionCHPQuantificationDetectionData.h.
References chpData, and affymetrix_calvin_io::CHPQuantificationDetectionData::GetSummaryParams().
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_SummaryParameters().
bool FusionCHPQuantificationDetectionData::Read () [private, virtual]
Reads the CHP file.
Returns:
True if successful.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 63 of file FusionCHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read(), and affymetrix_calvin_io::CHPQuantificationDetectionFileReader::SetFilename().
bool FusionCHPQuantificationDetectionData::ReadHeader () [private, virtual]
Reads the header of the CHP file
Returns:
True if successful
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 55 of file FusionCHPQuantificationDetectionData.cpp.
Member Data Documentation
affymetrix_calvin_io::CHPQuantificationDetectionData affymetrix_fusion_io::FusionCHPQuantificationDetectionData::chpData [private]
The CHP object.
Definition at line 42 of file FusionCHPQuantificationDetectionData.h.
Referenced by GetAlgName(), GetAlgParams(), GetAlgVersion(), GetArrayType(), GetDataSetHeader(), GetEntryCount(), GetQuantificationDetectionEntry(), and GetSummaryParams().
FusionCHPQuantificationDetectionData::Reg FusionCHPQuantificationDetectionData::reg [static]
The one and only registration object. This registers the class as a CHP reader.
Used to register the CHP reader.
Definition at line 127 of file FusionCHPQuantificationDetectionData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPQuantificationDetectionData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPQuantificationDetectionData.cpp