Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCDFQCProbeSetInformation Class Reference
affymetrix_fusion_io::FusionCDFQCProbeSetInformation Class Reference
#include <FusionCDFData.h>
Public Member Functions
affxcdf::GeneChipQCProbeSetType GetQCProbeSetType () const
int GetNumCells () const
void GetProbeInformation (int index, FusionCDFQCProbeInformation &info)
FusionCDFQCProbeSetInformation ()
~FusionCDFQCProbeSetInformation ()
Private Member Functions
void Initialize (int index, affxcdf::CCDFFileData *cdf)
void Initialize (affxcdf::GeneChipQCProbeSetType qcType, affxcdf::CCDFFileData *cdf)
void Initialize (int index, affymetrix_calvin_io::CDFData *cdf)
void Initialize (affxcdf::GeneChipQCProbeSetType qcType, affymetrix_calvin_io::CDFData *cdf)
void Clear ()
Private Attributes
affxcdf::CCDFQCProbeSetInformation * gcosSet
affymetrix_calvin_io::CDFQCProbeSetInformation * calvinSet
Friends
class FusionCDFData
Detailed Description
This class provides storage for the probes in a QC probe set.
Definition at line 422 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFQCProbeSetInformation::FusionCDFQCProbeSetInformation ()
Constructor
Definition at line 329 of file FusionCDFData.cpp.
FusionCDFQCProbeSetInformation::~FusionCDFQCProbeSetInformation ()
Destructor
Definition at line 338 of file FusionCDFData.cpp.
Member Function Documentation
void FusionCDFQCProbeSetInformation::Clear (void) [private]
Deallocates any used memory.
Definition at line 386 of file FusionCDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFData::GetQCProbeSetInformation().
int FusionCDFQCProbeSetInformation::GetNumCells () const
Gets the number of probes in the set.
Returns:
The number of probes in the set.
Definition at line 303 of file FusionCDFData.cpp.
void FusionCDFQCProbeSetInformation::GetProbeInformation (int index, FusionCDFQCProbeInformation & info)
Gets the information about a single probe in the set.
Parameters:
index The index to the probe of interest.
info The information about the probe.
Definition at line 316 of file FusionCDFData.cpp.
References affymetrix_fusion_io::FusionCDFQCProbeInformation::Clear(), and affymetrix_fusion_io::FusionCDFQCProbeInformation::Initialize().
affxcdf::GeneChipQCProbeSetType FusionCDFQCProbeSetInformation::GetQCProbeSetType () const
Gets the probe set type.
Returns:
The probe set type.
Definition at line 278 of file FusionCDFData.cpp.
References affymetrix_fusion_io::FusionCDFQCProbeSetNames::GetStaticCDFQCProbeSetName(), affxcdf::SpatialNormalizationPositiveQCProbeSetType, affxcdf::UnknownQCProbeSetType, and UnknownQCProbeSetType.
void FusionCDFQCProbeSetInformation::Initialize (affxcdf::GeneChipQCProbeSetType qcType, affxcdf::CCDFFileData * cdf) [private]
Initializes the class for GCOS file reading.
Parameters:
qcType The type of QC probe set.
cdf The GCOS CDF file object.
Definition at line 356 of file FusionCDFData.cpp.
References affxcdf::CCDFFileData::GetQCProbeSetInformation().
void FusionCDFQCProbeSetInformation::Initialize (int index, affxcdf::CCDFFileData * cdf) [private]
Initializes the class for GCOS file reading.
Parameters:
index The index to the QC probe set.
cdf The GCOS CDF file object.
Definition at line 346 of file FusionCDFData.cpp.
References affxcdf::CCDFFileData::GetQCProbeSetInformation().
Referenced by affymetrix_fusion_io::FusionCDFData::GetQCProbeSetInformation().
void FusionCDFQCProbeSetInformation::Initialize (int index, affymetrix_calvin_io::CDFData * cdf) [private]
Initializes the class for Calvin file reading.
Parameters:
index The index to the QC probe set.
cdf The Calvin CDF file object.
Definition at line 366 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFData::GetQCProbeSetInformation().
void FusionCDFQCProbeSetInformation::Initialize (affxcdf::GeneChipQCProbeSetType qcType, affymetrix_calvin_io::CDFData * cdf) [private]
Initializes the class for Calvin file reading.
Parameters:
qcType The type of QC probe set.
cdf The Calvin CDF file object.
Definition at line 376 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFData::GetQCProbeSetInformation().
Friends And Related Function Documentation
friend class FusionCDFData [friend]
Friend to the parent class.
Definition at line 459 of file FusionCDFData.h.
Member Data Documentation
affymetrix_calvin_io::CDFQCProbeSetInformation* affymetrix_fusion_io::FusionCDFQCProbeSetInformation::calvinSet [private]
The Calvin probe set object.
Definition at line 429 of file FusionCDFData.h.
affxcdf::CCDFQCProbeSetInformation* affymetrix_fusion_io::FusionCDFQCProbeSetInformation::gcosSet [private]
The GCOS probe set object.
Definition at line 426 of file FusionCDFData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.cpp