Affymetrix Fusion SDK: affxcms::CCMSFileData Class Reference
affxcms::CCMSFileData Class Reference
#include <CMSFileData.h>
Public Member Functions
void SetFileName (const char *value)
std::string GetFileName () const
std::string GetError () const
CCMSFileHeader & GetHeader ()
std::map< int, std::string > & ArrayTypeInformation ()
SNPTypeInfoList & SNPInformation ()
bool Read ()
bool ReadHeader ()
bool Exists ()
void Close ()
CCMSFileData ()
~CCMSFileData ()
Protected Member Functions
bool Open (bool bReadHeaderOnly=false)
bool ReadFile (bool bReadHeaderOnly=false)
Protected Attributes
CCMSFileHeader m_Header
std::string m_strFileName
std::string m_strError
std::map< int, std::string > m_arrayList
SNPTypeInfoList m_snpList
Detailed Description
Definition at line 109 of file CMSFileData.h.
Constructor & Destructor Documentation
CCMSFileData::CCMSFileData ()
Definition at line 45 of file CMSFileData.cpp.
CCMSFileData::~CCMSFileData ()
Definition at line 51 of file CMSFileData.cpp.
Member Function Documentation
std::map<int,std::string>& affxcms::CCMSFileData::ArrayTypeInformation () [inline]
Definition at line 134 of file CMSFileData.h.
References m_arrayList.
void CCMSFileData::Close (void)
Definition at line 101 of file CMSFileData.cpp.
References m_arrayList, and m_snpList.
Referenced by Open(), Read(), and ReadHeader().
bool CCMSFileData::Exists ()
Definition at line 210 of file CMSFileData.cpp.
References m_strError, and m_strFileName.
Referenced by Read(), and ReadHeader().
std::string affxcms::CCMSFileData::GetError () const [inline]
Definition at line 128 of file CMSFileData.h.
References m_strError.
std::string affxcms::CCMSFileData::GetFileName () const [inline]
Definition at line 127 of file CMSFileData.h.
References m_strFileName.
CCMSFileHeader& affxcms::CCMSFileData::GetHeader () [inline]
Definition at line 131 of file CMSFileData.h.
References m_Header.
bool CCMSFileData::Open (bool bReadHeaderOnly = false) [protected]
Definition at line 91 of file CMSFileData.cpp.
References Close(), and ReadFile().
Referenced by Read(), and ReadHeader().
bool CCMSFileData::Read ()
Definition at line 57 of file CMSFileData.cpp.
References Close(), Exists(), and Open().
bool CCMSFileData::ReadFile (bool bReadHeaderOnly = false) [protected]
Definition at line 109 of file CMSFileData.cpp.
References affxcms::_SNPTypeInfo::chiptype_to_unit, CMS_DATA_DEL, CMS_DATA_SNP, CMS_DATA_TYPES, CMS_HEADER_KEY_ARRAYCOUNT, CMS_HEADER_KEY_ASSAY, CMS_HEADER_KEY_SNPCOUNT, CMS_HEADER_KEY_VERSION, CMS_SECTION_DATA, CMS_SECTION_HEADER, affxcms::CCMSFileHeader::GetSNPCount(), CIniFile::GetValue(), m_arrayList, m_Header, m_snpList, m_strError, m_strFileName, affxcms::CCMSFileHeader::SetArrayCount(), affxcms::CCMSFileHeader::SetAssay(), affxcms::CCMSFileHeader::SetSNPCount(), affxcms::CCMSFileHeader::SetVersion(), and affxcms::_SNPTypeInfo::snpID.
Referenced by Open().
bool CCMSFileData::ReadHeader ()
Definition at line 74 of file CMSFileData.cpp.
References Close(), Exists(), and Open().
void affxcms::CCMSFileData::SetFileName (const char * value) [inline]
Definition at line 126 of file CMSFileData.h.
References m_strFileName.
SNPTypeInfoList& affxcms::CCMSFileData::SNPInformation () [inline]
Definition at line 135 of file CMSFileData.h.
References m_snpList.
Member Data Documentation
std::map<int,std::string> affxcms::CCMSFileData::m_arrayList [protected]
Definition at line 117 of file CMSFileData.h.
Referenced by ArrayTypeInformation(), Close(), and ReadFile().
CCMSFileHeader affxcms::CCMSFileData::m_Header [protected]
Definition at line 112 of file CMSFileData.h.
Referenced by GetHeader(), and ReadFile().
SNPTypeInfoList affxcms::CCMSFileData::m_snpList [protected]
Definition at line 118 of file CMSFileData.h.
Referenced by Close(), ReadFile(), and SNPInformation().
std::string affxcms::CCMSFileData::m_strError [protected]
Definition at line 115 of file CMSFileData.h.
Referenced by Exists(), GetError(), and ReadFile().
std::string affxcms::CCMSFileData::m_strFileName [protected]
Definition at line 114 of file CMSFileData.h.
Referenced by Exists(), GetFileName(), ReadFile(), and SetFileName().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CMSFileData.h
C:/f112/affy/sdk/file/CMSFileData.cpp