Affymetrix Fusion SDK: affymetrix_calvin_io::DataSet Class Reference
affymetrix_calvin_io::DataSet Class Reference
#include <DataSet.h>
Public Member Functions
DataSet (const std::string &fileName, const affymetrix_calvin_io::DataSetHeader &header, void *handle, bool loadEntireDataSetHint=false)
DataSet (const std::string &fileName, const affymetrix_calvin_io::DataSetHeader &header, std::ifstream &ifs, bool loadEntireDataSetHint=false)
void Delete ()
bool Open ()
void Close ()
const
affymetrix_calvin_io::DataSetHeader & Header ()
int32_t Rows ()
int32_t Cols ()
bool IsOpen ()
void GetData (int32_t row, int32_t col, u_int8_t &value)
void GetData (int32_t row, int32_t col, int8_t &value)
void GetData (int32_t row, int32_t col, u_int16_t &value)
void GetData (int32_t row, int32_t col, int16_t &value)
void GetData (int32_t row, int32_t col, u_int32_t &value)
void GetData (int32_t row, int32_t col, int32_t &value)
void GetData (int32_t row, int32_t col, float &value)
void GetData (int32_t row, int32_t col, std::string &value)
void GetData (int32_t row, int32_t col, std::wstring &value)
void GetData (int32_t col, int32_t startRow, int32_t count, Uint8Vector &values)
void GetData (int32_t col, int32_t startRow, int32_t count, Int8Vector &values)
void GetData (int32_t col, int32_t startRow, int32_t count, Uint16Vector &values)
void GetData (int32_t col, int32_t startRow, int32_t count, Int16Vector &values)
void GetData (int32_t col, int32_t startRow, int32_t count, Uint32Vector &values)
void GetData (int32_t col, int32_t startRow, int32_t count, Int32Vector &values)
void GetData (int32_t col, int32_t startRow, int32_t count, FloatVector &values)
void GetData (int32_t col, int32_t startRow, int32_t count, std::vector< std::string > &values)
void GetData (int32_t col, int32_t startRow, int32_t count, WStringVector &values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, u_int8_t *values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, int8_t *values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, u_int16_t *values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, int16_t *values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, u_int32_t *values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, int32_t *values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, float *values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, std::string *values)
int32_t GetDataRaw (int32_t col, int32_t startRow, int32_t count, std::wstring *values)
void CheckRowColumnAndType (int32_t row, int32_t col, affymetrix_calvin_io::DataSetColumnTypes type)
int32_t BytesPerRow ()
~DataSet ()
Protected Member Functions
bool OpenMM ()
void ReadDataSetUsingStream ()
void UnmapFile ()
void ClearStreamData ()
char * FilePosition (int32_t rowStart, int32_t col, int32_t rowCount=1)
char * LoadDataAndReturnFilePosition (int32_t rowStart, int32_t col, int32_t rowCount)
void UpdateColumnByteOffsets ()
int32_t ComputeEndRow (int32_t startRow, int32_t count)
template<typename T >
void ClearAndSizeVector (std::vector< T > &values, u_int32_t size)
template<typename T >
void GetDataT (int32_t col, int32_t startRow, int32_t count, T &values)
template<typename T >
int32_t GetDataRawT (int32_t col, int32_t startRow, int32_t count, T *values)
int32_t LastRowMapped ()
bool MapDataPosix (u_int32_t start, u_int32_t bytes)
void AssignValue (int32_t index, Uint8Vector &values, char *&instr)
void AssignValue (int32_t index, Int8Vector &values, char *&instr)
void AssignValue (int32_t index, Uint16Vector &values, char *&instr)
void AssignValue (int32_t index, Int16Vector &values, char *&instr)
void AssignValue (int32_t index, Uint32Vector &values, char *&instr)
void AssignValue (int32_t index, Int32Vector &values, char *&instr)
void AssignValue (int32_t index, FloatVector &values, char *&instr)
void AssignValue (int32_t index, StringVector &values, char *&instr)
void AssignValue (int32_t index, WStringVector &values, char *&instr)
void AssignValue (int32_t index, u_int8_t *values, char *&instr)
void AssignValue (int32_t index, int8_t *values, char *&instr)
void AssignValue (int32_t index, u_int16_t *values, char *&instr)
void AssignValue (int32_t index, int16_t *values, char *&instr)
void AssignValue (int32_t index, u_int32_t *values, char *&instr)
void AssignValue (int32_t index, int32_t *values, char *&instr)
void AssignValue (int32_t index, float *values, char *&instr)
void AssignValue (int32_t index, std::string *values, char *&instr)
void AssignValue (int32_t index, std::wstring *values, char *&instr)
Protected Attributes
std::string fileName
affymetrix_calvin_io::DataSetHeader header
void * mappedData
char * data
Int32Vector columnByteOffsets
FILE * fp
bool isOpen
u_int32_t mapStart
u_int32_t mapLen
bool useMemoryMapping
std::ifstream * fileStream
bool loadEntireDataSetHint
Detailed Description
This class provides methods to access the data of a DataSet.
Definition at line 46 of file DataSet.h.
Constructor & Destructor Documentation
DataSet::DataSet (const std::string & fileName, const affymetrix_calvin_io::DataSetHeader & header, void * handle, bool loadEntireDataSetHint = false)
Constructor. Use this constructor do access the data using memory-mapping. On Windows, memory-mapping will be restricted to 200MB view of the DataSet data.
Parameters:
fileName The name of the generic file to access.
header The DataSetHeader of the DataSet to access.
handle A handle to the file mapping object
loadEntireDataSetHint Indicate if DataSet will attempt to read the entire DataSet data into a memory buffer.
Definition at line 55 of file DataSet.cpp.
References data, fileName, fileStream, fp, header, isOpen, loadEntireDataSetHint, mapLen, mappedData, mapStart, and useMemoryMapping.
Referenced by affymetrix_calvin_io::CelFileData::GetDataSetParameters(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), affymetrix_calvin_io::CelFileData::PrepareMaskedPlane(), affymetrix_calvin_io::CelFileData::PrepareOutlierPlane(), and affymetrix_calvin_io::DATData::PrepareSet().
DataSet::DataSet (const std::string & fileName, const affymetrix_calvin_io::DataSetHeader & header, std::ifstream & ifs, bool loadEntireDataSetHint = false)
Constructor. Use this constructor do access the data using std::ifstream. With fstream access the entire DataSet data will be read into memory.
Parameters:
fileName The name of the generic file to access.
header The DataSetHeader of the DataSet to access.
ifs A reference to an open ifstream.
loadEntireDataSetHint Indicate if DataSet will attempt to read the entire DataSet data into a memory buffer.
Definition at line 79 of file DataSet.cpp.
References data, fileName, fileStream, fp, header, isOpen, loadEntireDataSetHint, mapLen, mappedData, mapStart, and useMemoryMapping.
DataSet::~DataSet ()
Destructor.
Definition at line 104 of file DataSet.cpp.
References Close().
Member Function Documentation
void DataSet::AssignValue (int32_t index, Uint8Vector & values, char *& instr) [protected]
Reads from the instr pointer into the vector at the index indicated.
Parameters:
index Index to the vector where to write the value.
values The vector into which to write the value.
instr A pointer to the data in the memory buffer. The pointer is advanced by the method.
Definition at line 576 of file DataSet.cpp.
References ReadUInt8().
Referenced by GetDataRawT(), and GetDataT().
void DataSet::AssignValue (int32_t index, int32_t * values, char *& instr) [protected]
Definition at line 721 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadInt32().
void DataSet::AssignValue (int32_t index, float * values, char *& instr) [protected]
Definition at line 726 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadFloat().
void DataSet::AssignValue (int32_t index, std::string * values, char *& instr) [protected]
Definition at line 731 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadString8().
void DataSet::AssignValue (int32_t index, std::wstring * values, char *& instr) [protected]
Definition at line 735 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadString16().
void DataSet::AssignValue (int32_t index, u_int32_t * values, char *& instr) [protected]
Definition at line 716 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt32().
void DataSet::AssignValue (int32_t index, Int8Vector & values, char *& instr) [protected]
Definition at line 581 of file DataSet.cpp.
References ReadInt8().
void DataSet::AssignValue (int32_t index, Uint16Vector & values, char *& instr) [protected]
Definition at line 586 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt16().
void DataSet::AssignValue (int32_t index, Int16Vector & values, char *& instr) [protected]
Definition at line 591 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadInt16().
void DataSet::AssignValue (int32_t index, u_int8_t * values, char *& instr) [protected]
Definition at line 696 of file DataSet.cpp.
References ReadUInt8().
void DataSet::AssignValue (int32_t index, Uint32Vector & values, char *& instr) [protected]
Definition at line 596 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt32().
void DataSet::AssignValue (int32_t index, Int32Vector & values, char *& instr) [protected]
Definition at line 601 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadInt32().
void DataSet::AssignValue (int32_t index, FloatVector & values, char *& instr) [protected]
Definition at line 606 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadFloat().
void DataSet::AssignValue (int32_t index, StringVector & values, char *& instr) [protected]
Definition at line 611 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadString8().
void DataSet::AssignValue (int32_t index, WStringVector & values, char *& instr) [protected]
Definition at line 616 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadString16().
void DataSet::AssignValue (int32_t index, int8_t * values, char *& instr) [protected]
Definition at line 701 of file DataSet.cpp.
References ReadInt8().
void DataSet::AssignValue (int32_t index, u_int16_t * values, char *& instr) [protected]
Definition at line 706 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt16().
void DataSet::AssignValue (int32_t index, int16_t * values, char *& instr) [protected]
Definition at line 711 of file DataSet.cpp.
References affymetrix_calvin_io::FileInput::ReadInt16().
int32_t affymetrix_calvin_io::DataSet::BytesPerRow () [inline]
Return the bytes per row.
Returns:
Bytes in a row.
Definition at line 194 of file DataSet.h.
References columnByteOffsets, and affymetrix_calvin_io::DataSetHeader::GetColumnCnt().
Referenced by FilePosition(), LastRowMapped(), and LoadDataAndReturnFilePosition().
void DataSet::CheckRowColumnAndType (int32_t row, int32_t col, affymetrix_calvin_io::DataSetColumnTypes type)
Check that the requested data matches the type of data in the column and that row and column are in bounds.
Parameters:
row Row index to check.
col Column index to check.
type Column type to check.
Exceptions:
affymetrix_calvin_exceptions::DataSetNotOpenException The file is not memory-mapped.
affymetrix_calvin_exceptions::ColumnIndexOutOfBoundsException The column index is out-of-bounds.
affymetrix_calvin_exceptions::RowIndexOutOfBoundsException The row index is out-of-bounds.
affymetrix_calvin_exceptions::UnexpectedColumnTypeException The column type does not match the type requested.
Definition at line 338 of file DataSet.cpp.
References affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::ColumnInfo::GetColumnType(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), header, and isOpen.
template<typename T > void DataSet::ClearAndSizeVector (std::vector< T > & values, u_int32_t size) [protected]
Clears and resizes the vector
Parameters:
values Reference to a vector to clear and resize.
size Target size of the vector
Definition at line 539 of file DataSet.cpp.
Referenced by GetDataT().
void DataSet::ClearStreamData () [protected]
Delete the DataSet data read in by ifstream::read
Definition at line 327 of file DataSet.cpp.
References data, mapLen, and mapStart.
Referenced by Close(), and LoadDataAndReturnFilePosition().
void DataSet::Close ()
Method to close the DataSet.
Definition at line 177 of file DataSet.cpp.
References ClearStreamData(), UnmapFile(), and useMemoryMapping.
Referenced by Delete(), Calvin::load(), MapDataPosix(), affymetrix_calvin_io::GridControlFileReader::Read(), affymetrix_calvin_io::CDFQCProbeSetInformation::SetDataSet(), affymetrix_calvin_io::CDFProbeGroupInformation::SetDataSet(), affymetrix_calvin_io::CDFProbeGroupInformation::~CDFProbeGroupInformation(), affymetrix_calvin_io::CDFQCProbeSetInformation::~CDFQCProbeSetInformation(), and ~DataSet().
int32_t affymetrix_calvin_io::DataSet::Cols () [inline]
Return the number of columns in the DataSet.
Definition at line 89 of file DataSet.h.
References affymetrix_calvin_io::DataSetHeader::GetColumnCnt().
Referenced by Calvin::equivalent(), Calvin::load(), and CalvinToText::OutputSetInfo().
int32_t DataSet::ComputeEndRow (int32_t startRow, int32_t count) [protected]
Computes the index of the row after last to read.
Parameters:
startRow Row index of the data to be inserted into the vector at [0].
count Number of elements to be retrieved. -1 indicates read to the last element.
Returns:
Index of row after the last row to read.
Definition at line 530 of file DataSet.cpp.
References affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and header.
Referenced by GetDataRawT(), and GetDataT().
void DataSet::Delete ()
Method to release memory held by this object. Closes object before deleting.
Definition at line 112 of file DataSet.cpp.
References Close().
Referenced by affymetrix_calvin_io::CHPMultiDataData::Clear(), Calvin::equivalent(), Calvin::load(), CalvinToText::OutputSetInfo(), affymetrix_calvin_io::CelFileData::PrepareMaskedPlane(), affymetrix_calvin_io::CelFileData::PrepareOutlierPlane(), affymetrix_calvin_io::GridControlFileReader::Read(), affymetrix_calvin_io::CDFQCProbeSetInformation::SetDataSet(), affymetrix_calvin_io::CDFProbeGroupInformation::SetDataSet(), affymetrix_calvin_io::CDFProbeGroupInformation::~CDFProbeGroupInformation(), and affymetrix_calvin_io::CDFQCProbeSetInformation::~CDFQCProbeSetInformation().
char * DataSet::FilePosition (int32_t rowStart, int32_t col, int32_t rowCount = 1) [protected]
Returns the address of a data element given a row and column. Ensures that data from rowStart to rowCount+rowStart are mapped unless that is larger than the mapped window.
Parameters:
rowStart Row index
col Column index
rowCount The number of rows to ensure are mapped starting at rowStart
Returns:
Pointer to the data element at rowStart
Exceptions:
affymetrix_calvin_exceptions::DataSetNotOpenException The file is not open.
affymetrix_calvin_exceptions::DataSetRemapException There was an error during a remap.
Definition at line 370 of file DataSet.cpp.
References BytesPerRow(), columnByteOffsets, data, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_io::DataSetHeader::GetDataSize(), affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), header, isOpen, LoadDataAndReturnFilePosition(), loadEntireDataSetHint, mapLen, mapStart, and useMemoryMapping.
Referenced by GetData(), GetDataRawT(), and GetDataT().
void DataSet::GetData (int32_t row, int32_t col, int8_t & value)
Definition at line 473 of file DataSet.cpp.
References FilePosition(), and ReadInt8().
void DataSet::GetData (int32_t row, int32_t col, std::wstring & value)
Definition at line 522 of file DataSet.cpp.
References FilePosition(), and affymetrix_calvin_io::FileInput::ReadString16().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, Uint8Vector & values)
Provides access to multiple data elements in the same column. If count elements could not be read, it is not considered an error. The vector is filled with only the data that could be read.
Parameters:
col Column index.
startRow Row index of the data to be inserted into the vector at [0].
count Number of elements to retrieve. -1 indicates to read all
values Reference to the data type to fill with the data.
Exceptions:
affymetrix_calvin_exceptions::DataSetNotOpenException The file is not memory-mapped.
Definition at line 621 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t row, int32_t col, u_int8_t & value)
Provides access to single data elements
Parameters:
row Row index.
col Column index.
value Reference to the data type to fill with the data.
Exceptions:
affymetrix_calvin_exceptions::DataSetNotOpenException The file is not memory-mapped.
Definition at line 466 of file DataSet.cpp.
References FilePosition(), and ReadUInt8().
Referenced by affymetrix_calvin_io::CDFQCProbeInformation::CopyFromDataSet(), affymetrix_calvin_io::CDFProbeInformation::CopyFromDataSet(), Calvin::equivalent(), affymetrix_calvin_io::CHPMultiDataData::GetChromosomeSegmentEntry(), affymetrix_calvin_io::CHPMultiDataData::GetChromosomeSummaryEntry(), affymetrix_calvin_io::CHPMultiDataData::GetEntry(), affymetrix_calvin_io::CHPMultiDataData::GetExpressionQuantification(), affymetrix_calvin_io::CHPMultiDataData::GetExtraCopyNumberFloatTypeNoNameLog2Ratio(), affymetrix_calvin_io::CHPMultiDataData::GetExtraMetricEntries(), affymetrix_calvin_io::CHPMultiDataData::GetFamilialSampleEntry(), affymetrix_calvin_io::CHPMultiDataData::GetFamilialSegmentOverlapEntry(), affymetrix_calvin_io::CHPMultiDataData::GetGenericEntry(), affymetrix_calvin_io::CHPMultiDataData::GetGenoCall(), affymetrix_calvin_io::CHPMultiDataData::GetGenoConfidence(), affymetrix_calvin_io::CHPMultiDataData::GetProbeSetName(), Calvin::load(), affymetrix_calvin_io::CelFileData::PrepareMaskedPlane(), affymetrix_calvin_io::CelFileData::PrepareOutlierPlane(), and affymetrix_calvin_io::GridControlFileReader::Read().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, Int8Vector & values)
Definition at line 626 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, Uint16Vector & values)
Definition at line 631 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t row, int32_t col, u_int16_t & value)
Definition at line 480 of file DataSet.cpp.
References FilePosition(), and affymetrix_calvin_io::FileInput::ReadUInt16().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, Int16Vector & values)
Definition at line 636 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, Uint32Vector & values)
Definition at line 641 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, Int32Vector & values)
Definition at line 646 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t row, int32_t col, int16_t & value)
Definition at line 487 of file DataSet.cpp.
References FilePosition(), and affymetrix_calvin_io::FileInput::ReadInt16().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, FloatVector & values)
Definition at line 651 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, WStringVector & values)
Definition at line 661 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t col, int32_t startRow, int32_t count, std::vector< std::string > & values)
Definition at line 656 of file DataSet.cpp.
References GetDataT().
void DataSet::GetData (int32_t row, int32_t col, u_int32_t & value)
Definition at line 494 of file DataSet.cpp.
References FilePosition(), and affymetrix_calvin_io::FileInput::ReadUInt32().
void DataSet::GetData (int32_t row, int32_t col, int32_t & value)
Definition at line 501 of file DataSet.cpp.
References FilePosition(), and affymetrix_calvin_io::FileInput::ReadInt32().
void DataSet::GetData (int32_t row, int32_t col, std::string & value)
Definition at line 515 of file DataSet.cpp.
References FilePosition(), and affymetrix_calvin_io::FileInput::ReadString8().
void DataSet::GetData (int32_t row, int32_t col, float & value)
Definition at line 508 of file DataSet.cpp.
References FilePosition(), and affymetrix_calvin_io::FileInput::ReadFloat().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, int32_t * values)
Definition at line 765 of file DataSet.cpp.
References GetDataRawT().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, float * values)
Definition at line 770 of file DataSet.cpp.
References GetDataRawT().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, std::string * values)
Definition at line 775 of file DataSet.cpp.
References GetDataRawT().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, std::wstring * values)
Definition at line 780 of file DataSet.cpp.
References GetDataRawT().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, int8_t * values)
Definition at line 745 of file DataSet.cpp.
References GetDataRawT().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, u_int16_t * values)
Definition at line 750 of file DataSet.cpp.
References GetDataRawT().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, int16_t * values)
Definition at line 755 of file DataSet.cpp.
References GetDataRawT().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, u_int8_t * values)
Provides access to multiple data elements in the same column. The caller is responsible for allocating the storage to which count element values can be written. If count elements could not be read, it is not considered an error. The array is filled with only the data that could be read.
Parameters:
col Column index.
startRow Row index of the data to be inserted into the vector at [0].
count Number of elements to retrieve. -1 indicates to read all
values Reference to the data type to fill with the data.
Returns:
Number of elements read.
Exceptions:
affymetrix_calvin_exceptions::DataSetNotOpenException The file is not memory-mapped.
Definition at line 740 of file DataSet.cpp.
References GetDataRawT().
int32_t DataSet::GetDataRaw (int32_t col, int32_t startRow, int32_t count, u_int32_t * values)
Definition at line 760 of file DataSet.cpp.
References GetDataRawT().
template<typename T > int32_t DataSet::GetDataRawT (int32_t col, int32_t startRow, int32_t count, T * values) [protected]
Template method to get data into an array
Parameters:
col Column index.
startRow Row index of the data to be inserted into the vector at [0].
count Number of elements to retrieve. -1 indicates to read all
values Reference to the data type to fill with the data.
Returns:
Number of elements read.
Exceptions:
affymetrix_calvin_exceptions::DataSetNotOpenException The file is not memory-mapped.
Definition at line 666 of file DataSet.cpp.
References AssignValue(), ComputeEndRow(), FilePosition(), affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), header, and LastRowMapped().
Referenced by GetDataRaw().
template<typename T > void DataSet::GetDataT (int32_t col, int32_t startRow, int32_t count, T & values) [protected]
Template method to get data into a vector
Parameters:
col Column index.
startRow Row index of the data to be inserted into the vector at [0].
count Number of elements to retrieve. -1 indicates to read all
values Reference to the data type to fill with the data.
Exceptions:
affymetrix_calvin_exceptions::DataSetNotOpenException The file is not memory-mapped.
Definition at line 545 of file DataSet.cpp.
References AssignValue(), ClearAndSizeVector(), ComputeEndRow(), FilePosition(), affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), header, and LastRowMapped().
Referenced by GetData().
const affymetrix_calvin_io::DataSetHeader& affymetrix_calvin_io::DataSet::Header () [inline]
Method to get a reference to the DataSetHeader
Returns:
A reference to the DataSetHeader.
Definition at line 83 of file DataSet.h.
References header.
Referenced by affymetrix_calvin_io::CHPMultiDataData::Clear(), Calvin::equivalent(), affymetrix_calvin_io::CDFProbeGroupInformation::GetName(), affymetrix_calvin_io::CDFQCProbeSetInformation::GetQCProbeSetType(), Calvin::load(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), CalvinToText::OutputSetInfo(), and affymetrix_calvin_io::CDFProbeGroupInformation::SetDataSet().
bool affymetrix_calvin_io::DataSet::IsOpen () [inline]
Determines if the DataSet is open
Returns:
true if the DataSet is open
Definition at line 94 of file DataSet.h.
References isOpen.
Referenced by affymetrix_calvin_io::CHPMultiDataData::GetChromosomeSegmentEntry(), affymetrix_calvin_io::CHPMultiDataData::GetChromosomeSummaryEntry(), affymetrix_calvin_io::CHPMultiDataData::GetEntry(), affymetrix_calvin_io::CHPMultiDataData::GetExpressionQuantification(), affymetrix_calvin_io::CHPMultiDataData::GetFamilialSampleEntry(), affymetrix_calvin_io::CHPMultiDataData::GetFamilialSegmentOverlapEntry(), affymetrix_calvin_io::CHPMultiDataData::GetGenericCopyNumberEntryLog2Ratio(), affymetrix_calvin_io::CHPMultiDataData::GetGenericEntry(), affymetrix_calvin_io::CHPMultiDataData::GetGenoCall(), affymetrix_calvin_io::CHPMultiDataData::GetGenoConfidence(), and affymetrix_calvin_io::CHPMultiDataData::GetProbeSetName().
int32_t DataSet::LastRowMapped () [protected]
Returns the index of the last row mapped.
Returns:
Index of the last row mapped.
Definition at line 785 of file DataSet.cpp.
References BytesPerRow(), affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), header, mapLen, and mapStart.
Referenced by GetDataRawT(), and GetDataT().
char * DataSet::LoadDataAndReturnFilePosition (int32_t rowStart, int32_t col, int32_t rowCount) [protected]
Returns the address of a data element given a row and column. Ensures that data from rowStart to rowCount+rowStart are copied from the file into a memory buffer. The memory buffer will remain intact until the next call to LoadDataAndReturnFilePosition.
Parameters:
rowStart Row index
col Column index
rowCount The number of rows to ensure are mapped starting at rowStart
Returns:
Pointer to the data element at rowStart
Exceptions:
affymetrix_calvin_exceptions::DataSetNotOpenException The file is not open.
Definition at line 435 of file DataSet.cpp.
References BytesPerRow(), ClearStreamData(), columnByteOffsets, data, fileStream, affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), header, mapLen, and mapStart.
Referenced by FilePosition().
bool DataSet::MapDataPosix (u_int32_t start, u_int32_t bytes) [protected]
Platform specific memory-mapping method
Definition at line 258 of file DataSet.cpp.
References Close(), data, Fs::fileExists(), fileName, Fs::fileSize(), fp, mapLen, mappedData, mapStart, and PAGE_TRUNC.
Referenced by OpenMM().
bool DataSet::Open ()
Method to open the DataSet to access the data.
Returns:
true if successful
Definition at line 121 of file DataSet.cpp.
References isOpen, OpenMM(), ReadDataSetUsingStream(), UpdateColumnByteOffsets(), and useMemoryMapping.
Referenced by Calvin::equivalent(), Calvin::load(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), CalvinToText::OutputData(), affymetrix_calvin_io::CDFData::PrepareForAccessByProbeSetIndex(), affymetrix_calvin_io::CelFileData::PrepareMaskedPlane(), affymetrix_calvin_io::CelFileData::PrepareOutlierPlane(), affymetrix_calvin_io::DATData::PrepareSet(), affymetrix_calvin_io::GridControlFileReader::Read(), affymetrix_calvin_io::CDFQCProbeSetInformation::SetDataSet(), and affymetrix_calvin_io::CDFProbeGroupInformation::SetDataSet().
bool DataSet::OpenMM () [protected]
Open the DataSet using memory-mapping
Returns:
True if the DataSet was successully mapped.
Definition at line 138 of file DataSet.cpp.
References fileName, fp, affymetrix_calvin_io::DataSetHeader::GetDataSize(), affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), header, and MapDataPosix().
Referenced by Open().
void DataSet::ReadDataSetUsingStream () [protected]
Read the DataSet data into a buffer using ifstream::read.
Definition at line 161 of file DataSet.cpp.
References data, fileStream, affymetrix_calvin_io::DataSetHeader::GetDataSize(), affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), header, loadEntireDataSetHint, mapLen, and mapStart.
Referenced by Open().
int32_t affymetrix_calvin_io::DataSet::Rows () [inline]
Return the number of rows in the DataSet.
Definition at line 86 of file DataSet.h.
References affymetrix_calvin_io::DataSetHeader::GetRowCnt().
Referenced by Calvin::equivalent(), affymetrix_calvin_io::CDFProbeGroupInformation::GetCell(), affymetrix_calvin_io::CDFQCProbeSetInformation::GetNumCells(), affxcdf::CCDFQCProbeSetInformation::GetProbeInformation(), Calvin::load(), CalvinToText::OutputSetInfo(), affymetrix_calvin_io::CDFData::PrepareForAccessByProbeSetName(), affymetrix_calvin_io::CelFileData::PrepareMaskedPlane(), affymetrix_calvin_io::CelFileData::PrepareOutlierPlane(), and affymetrix_calvin_io::GridControlFileReader::Read().
void DataSet::UnmapFile () [protected]
Close the memory mapped file.
Definition at line 294 of file DataSet.cpp.
References data, fp, mapLen, mappedData, and mapStart.
Referenced by Close().
void DataSet::UpdateColumnByteOffsets () [protected]
Updates the columnByteOffsets member.
Definition at line 452 of file DataSet.cpp.
References columnByteOffsets, affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::ColumnInfo::GetSize(), and header.
Referenced by Open().
Member Data Documentation
Int32Vector affymetrix_calvin_io::DataSet::columnByteOffsets [protected]
Array of column byte offsets. Updated when the file is opened. There are columns + 1 elements
Definition at line 347 of file DataSet.h.
Referenced by BytesPerRow(), FilePosition(), LoadDataAndReturnFilePosition(), and UpdateColumnByteOffsets().
char* affymetrix_calvin_io::DataSet::data [protected]
pointer to the data. In memory-mapping mode, the pointer has been adjusted for the allocation granularity.
Definition at line 342 of file DataSet.h.
Referenced by ClearStreamData(), DataSet(), FilePosition(), LoadDataAndReturnFilePosition(), MapDataPosix(), ReadDataSetUsingStream(), and UnmapFile().
std::string affymetrix_calvin_io::DataSet::fileName [protected]
name of the file containing the data data set*.
Definition at line 333 of file DataSet.h.
Referenced by DataSet(), MapDataPosix(), and OpenMM().
std::ifstream* affymetrix_calvin_io::DataSet::fileStream [protected]
An open ifstream object
Definition at line 371 of file DataSet.h.
Referenced by DataSet(), LoadDataAndReturnFilePosition(), and ReadDataSetUsingStream().
FILE* affymetrix_calvin_io::DataSet::fp [protected]
Definition at line 358 of file DataSet.h.
Referenced by DataSet(), MapDataPosix(), OpenMM(), and UnmapFile().
affymetrix_calvin_io::DataSetHeader affymetrix_calvin_io::DataSet::header [protected]
copy of the DataSetHeader
Definition at line 336 of file DataSet.h.
Referenced by CheckRowColumnAndType(), ComputeEndRow(), DataSet(), FilePosition(), GetDataRawT(), GetDataT(), Header(), LastRowMapped(), LoadDataAndReturnFilePosition(), OpenMM(), ReadDataSetUsingStream(), and UpdateColumnByteOffsets().
bool affymetrix_calvin_io::DataSet::isOpen [protected]
Indicates if the DataSet is open
Definition at line 363 of file DataSet.h.
Referenced by CheckRowColumnAndType(), DataSet(), FilePosition(), IsOpen(), and Open().
bool affymetrix_calvin_io::DataSet::loadEntireDataSetHint [protected]
Indicates whether to attempt to read all data into a memory buffer.
Definition at line 373 of file DataSet.h.
Referenced by DataSet(), FilePosition(), and ReadDataSetUsingStream().
u_int32_t affymetrix_calvin_io::DataSet::mapLen [protected]
Number of bytes mapped to the view
Definition at line 367 of file DataSet.h.
Referenced by ClearStreamData(), DataSet(), FilePosition(), LastRowMapped(), LoadDataAndReturnFilePosition(), MapDataPosix(), ReadDataSetUsingStream(), and UnmapFile().
void* affymetrix_calvin_io::DataSet::mappedData [protected]
pointer to the mapped data, doesn't account for allocation granularity.
Definition at line 339 of file DataSet.h.
Referenced by DataSet(), MapDataPosix(), and UnmapFile().
u_int32_t affymetrix_calvin_io::DataSet::mapStart [protected]
Byte offset to the start of the view
Definition at line 365 of file DataSet.h.
Referenced by ClearStreamData(), DataSet(), FilePosition(), LastRowMapped(), LoadDataAndReturnFilePosition(), MapDataPosix(), ReadDataSetUsingStream(), and UnmapFile().
bool affymetrix_calvin_io::DataSet::useMemoryMapping [protected]
A flag the indicates the data access mode. True = access the data using memory-mapping. False = access the data using std::ifstream
Definition at line 369 of file DataSet.h.
Referenced by Close(), DataSet(), FilePosition(), and Open().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/DataSet.h
C:/f112/affy/sdk/calvin_files/data/src/DataSet.cpp