Affymetrix Fusion SDK: affymetrix_calvin_io::SAXTemplateHandlers Class Reference
affymetrix_calvin_io::SAXTemplateHandlers Class Reference
#include <SAXTemplateHandlers.h>
Public Member Functions
SAXTemplateHandlers (affymetrix_calvin_template::TemplateData *data, bool headerOnly=false)
~SAXTemplateHandlers ()
void startDocument ()
void endDocument ()
void characters (const XMLCh *const chars, const XMLSize_t length)
void startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList &attributes)
void endElement (const XMLCh *const name)
const
affymetrix_calvin_utilities::AffymetrixGuidType & DataTypeIdentifier () const
std::wstring FileVersionNumber () const
Private Member Functions
void StoreTemplateFileAttributes (std::map< std::wstring, std::wstring > &attributes)
void StoreUserAttribute (std::map< std::wstring, std::wstring > &attributes)
void StoreUserAttributeControl (std::map< std::wstring, std::wstring > &attributes)
void MoveCurrentElementBack (const XMLCh *const name)
bool MoveCurrentElementForward (const XMLCh *const name)
Private Attributes
affymetrix_calvin_template::TemplateData * templateData
bool readHeaderOnly
TemplateFileElements currentElement
std::wstring fileVersionNumber
affymetrix_calvin_utilities::AffymetrixGuidType dataTypeIdentifier
Detailed Description
This class provides the SAX handlers for reading calvin template files.
Definition at line 110 of file SAXTemplateHandlers.h.
Constructor & Destructor Documentation
SAXTemplateHandlers::SAXTemplateHandlers (affymetrix_calvin_template::TemplateData * data, bool headerOnly = false)
Constructor
Parameters:
data The template data.
headerOnly Flag to indicate that the header line should only be read.
Definition at line 103 of file SAXTemplateHandlers.cpp.
SAXTemplateHandlers::~SAXTemplateHandlers ()
Destructor
Definition at line 113 of file SAXTemplateHandlers.cpp.
Member Function Documentation
void SAXTemplateHandlers::characters (const XMLCh *const chars, const XMLSize_t length)
Receive notification of character data inside an element.
Parameters:
chars The character data.
length The length of the character string.
Definition at line 241 of file SAXTemplateHandlers.cpp.
References affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlMultiValues(), currentElement, affymetrix_calvin_parameter::ParameterNameValueType::SetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_VALUE, templateData, affymetrix_calvin_template::TemplateData::UserAttributes(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ValueType(), WideToFloat(), WideToInt(), and XMLChToWString().
const affymetrix_calvin_utilities::AffymetrixGuidType& affymetrix_calvin_io::SAXTemplateHandlers::DataTypeIdentifier () const [inline]
The identifier of the type of data stored in the file.
Returns:
The identifier of the type of data.
Definition at line 199 of file SAXTemplateHandlers.h.
References dataTypeIdentifier.
void SAXTemplateHandlers::endDocument ()
Called at the end of the document
Definition at line 127 of file SAXTemplateHandlers.cpp.
void SAXTemplateHandlers::endElement (const XMLCh *const name)
Called at the end of each element.
Parameters:
name The name of the element.
Definition at line 134 of file SAXTemplateHandlers.cpp.
References MoveCurrentElementBack().
std::wstring affymetrix_calvin_io::SAXTemplateHandlers::FileVersionNumber () const [inline]
The files version number.
Returns:
The file version.
Definition at line 205 of file SAXTemplateHandlers.h.
References fileVersionNumber.
Referenced by affymetrix_calvin_io::TemplateFileReader::Read().
void SAXTemplateHandlers::MoveCurrentElementBack (const XMLCh *const name) [private]
Modifies the state machine given the end of an element.
Parameters:
name The name of the element.
Definition at line 142 of file SAXTemplateHandlers.cpp.
References currentElement, affymetrix_calvin_io::TEMPLATE_FILE, affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES, affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE, affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_CONTROL, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_ELEMENT, affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_VALUE, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_VALUE_ELEMENT, and TEMPLATE_USER_ATTRIBUTES_ELEMENT.
Referenced by endElement().
bool SAXTemplateHandlers::MoveCurrentElementForward (const XMLCh *const name) [private]
Modifies the state machine given the start of an element.
Parameters:
name The name of the element.
Returns:
True is a valid element was found.
Definition at line 163 of file SAXTemplateHandlers.cpp.
References currentElement, affymetrix_calvin_io::TEMPLATE_FILE, TEMPLATE_FILE_ELEMENT, affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES, affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE, affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_CONTROL, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_ELEMENT, affymetrix_calvin_io::TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_VALUE, TEMPLATE_USER_ATTRIBUTES_ATTRIBUTE_VALUE_ELEMENT, and TEMPLATE_USER_ATTRIBUTES_ELEMENT.
void SAXTemplateHandlers::startDocument ()
Called at the start of the document
Definition at line 120 of file SAXTemplateHandlers.cpp.
void affymetrix_calvin_io::SAXTemplateHandlers::startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList & attributes)
Called at the start of each element.
Parameters:
name The name of the element.
attributes The attributes of the element.
void SAXTemplateHandlers::StoreTemplateFileAttributes (std::map< std::wstring, std::wstring > & attributes) [private]
Stores the attributes from the template file element.
Parameters:
attributes The name/value attributes.
Definition at line 348 of file SAXTemplateHandlers.cpp.
References affymetrix_calvin_template::TemplateData::CreatedBy(), affymetrix_calvin_template::TemplateData::CreationDateTime(), affymetrix_calvin_template::TemplateData::DataTypeIdentifier(), fileVersionNumber, TEMPLATE_FILE_ELEMENT_CREATE_DATE_TIME_ATTRIBUTE, TEMPLATE_FILE_ELEMENT_CREATED_BY_ATTRIBUTE, TEMPLATE_FILE_ELEMENT_ID_ATTRIBUTE, TEMPLATE_FILE_ELEMENT_TYPE_ATTRIBUTE, TEMPLATE_FILE_ELEMENT_VERSION_ATTRIBUTE, templateData, and affymetrix_calvin_template::TemplateData::TemplateFileIdentifier().
void SAXTemplateHandlers::StoreUserAttribute (std::map< std::wstring, std::wstring > & attributes) [private]
Stores an attribute from the user attribute element.
Parameters:
attributes The name/value attributes.
Definition at line 314 of file SAXArrayHandlers.cpp.
References affymetrix_calvin_io::SAXArrayHandlers::arrayData, affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::RequiredFlag(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::SetDefaultValueFloat(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::SetDefaultValueInt32(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::SetDefaultValueText(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_DEFAULT_ATTRIBUTE, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_NAME_ATTRIBUTE, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_REQUIRED_ATTRIBUTE, USER_ATTRIBUTES_ATTRIBUTE_ELEMENT_TYPE_ATTRIBUTE, affymetrix_calvin_array::ArrayData::UserAttributes(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ValueType(), WideToFloat(), and WideToInt().
void SAXTemplateHandlers::StoreUserAttributeControl (std::map< std::wstring, std::wstring > & attributes) [private]
Stores a control value from the user attribute element.
Parameters:
attributes The name/value attributes.
Definition at line 376 of file SAXArrayHandlers.cpp.
References affymetrix_calvin_io::SAXArrayHandlers::arrayData, affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::ControlledVocabulary(), USER_ATTRIBUTES_ATTRIBUTE_CONTROL_ELEMENT_VALUE_ATTRIBUTE, and affymetrix_calvin_array::ArrayData::UserAttributes().
Member Data Documentation
TemplateFileElements affymetrix_calvin_io::SAXTemplateHandlers::currentElement [private]
The parent element that is currently being processed.
Definition at line 120 of file SAXTemplateHandlers.h.
Referenced by characters(), MoveCurrentElementBack(), and MoveCurrentElementForward().
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_io::SAXTemplateHandlers::dataTypeIdentifier [private]
An identifier to the type of data stored in the file
Definition at line 126 of file SAXTemplateHandlers.h.
Referenced by DataTypeIdentifier().
std::wstring affymetrix_calvin_io::SAXTemplateHandlers::fileVersionNumber [private]
The files version number.
Definition at line 123 of file SAXTemplateHandlers.h.
Referenced by FileVersionNumber(), and StoreTemplateFileAttributes().
bool affymetrix_calvin_io::SAXTemplateHandlers::readHeaderOnly [private]
A flag used to indicate that the header line should only be read.
Definition at line 117 of file SAXTemplateHandlers.h.
affymetrix_calvin_template::TemplateData* affymetrix_calvin_io::SAXTemplateHandlers::templateData [private]
A pointer to the template object.
Definition at line 114 of file SAXTemplateHandlers.h.
Referenced by characters(), and StoreTemplateFileAttributes().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/SAXTemplateHandlers.h
C:/f112/affy/sdk/calvin_files/parsers/src/SAXArrayHandlers.cpp
C:/f112/affy/sdk/calvin_files/parsers/src/SAXTemplateHandlers.cpp