Affymetrix Fusion SDK: affymetrix_calvin_io::DATData Class Reference
affymetrix_calvin_io::DATData Class Reference
#include <DATData.h>
Public Types
enum GridStatus { GridOK = 0x1, GridError = 0x2, GridManualAdjust = 0x4 }
Public Member Functions
DATData ()
DATData (const std::string &filename)
~DATData ()
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename ()
void SetPixelCount (int32_t ln)
void SetStatsCount (int32_t ln)
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
std::wstring GetArrayType ()
void SetArrayType (const std::wstring &value)
affymetrix_calvin_utilities::AffymetrixGuidType GetArrayId ()
void SetArrayId (affymetrix_calvin_utilities::AffymetrixGuidType &value)
std::wstring GetArrayBarcode ()
void SetArrayBarcode (std::wstring &value)
float GetPixelSize ()
void SetPixelSize (float value)
std::wstring GetScannerType ()
void SetScannerType (const std::wstring &value)
std::wstring GetScannerID ()
void SetScannerID (const std::wstring &value)
std::wstring GetExposureTime ()
void SetExposureTime (std::wstring &value)
int32_t GetPegSubImageIndex ()
void SetPegSubImageIndex (int32_t value)
affymetrix_calvin_utilities::DateTime GetScanDate ()
void SetScanDate (affymetrix_calvin_utilities::DateTime value)
int32_t GetRows ()
void SetRows (int32_t value)
int32_t GetCols ()
void SetCols (int32_t value)
bool GetPixels (u_int16_t *pixelBuffer, u_int32_t startRow, u_int32_t rowCnt)
bool GetPixels (u_int16_t *pixelBuffer, u_int32_t startRow, u_int32_t startCol, u_int32_t rowCnt, u_int32_t colCnt)
bool GetRange (u_int16_t &min, u_int16_t &max)
FRegion GetGlobalGrid () const
u_int32_t GetGlobalGridStatus () const
bool HasGlobalGridData () const
void SetGlobalGrid (u_int32_t gridStatus, FRegion &grid)
int32_t GetSubgridCnt () const
FRegion GetSubgrid (int32_t index) const
u_int32_t GetSubgridStatus (int32_t index) const
void AddSubgrid (u_int32_t status, const FRegion &subgrid)
void ClearSubgrids ()
void AddGridAlignmentAlgorithmParameter (const ParameterNameValueType &nvt)
void ClearGridAlignmentAlgorithmParameters ()
bool FindGridAlignmentAlgorithmParameter (const std::wstring &name, ParameterNameValueType &param)
void GetGridAlignmentAlgorithmParameters (ParameterNameValueTypeVector &algParams)
GenericDataHeader * GetParentArrayGenericDataHeader ()
Private Member Functions
void InsertDataSetHeader (const DataSetHeader &hdr)
void UpdateDataSetRowCount (const DataSetHeader &hdr)
std::wstring GetWStringFromGenericHdr (const std::wstring &name)
void SetWStringToGenericHdr (const std::wstring &name, const std::wstring value, int32_t reserve=-1)
int32_t GetInt32FromGenericHdr (const std::wstring &name)
void SetInt32ToGenericHdr (const std::wstring &name, int32_t value)
void PreparePixelSet ()
void PrepareSmallMemoryPixelSet ()
void PrepareStatsSet ()
void PrepareSet (const std::wstring &name, DataSet *&ds)
Private Attributes
GenericData genericData
bool setPixelMetaData
bool setStatsMetaData
int32_t cachedRows
int32_t cachedCols
DataSet * dsPixel
DataSet * dsSMPixel
DataSet * dsStats
FRegion globalGrid
u_int32_t globalGridStatus
FRegionVector subgrids
Uint32Vector subgridsStatus
ParameterNameValueTypeVector gridAlignParams
Detailed Description
This class is a data container object for DAT data.
Definition at line 50 of file DATData.h.
Member Enumeration Documentation
enum affymetrix_calvin_io::DATData::GridStatus
The grid and subgrid status flags. May be combined in an OR fashion.
Enumerator:
GridOK
GridError
GridManualAdjust
Definition at line 66 of file DATData.h.
Constructor & Destructor Documentation
DATData::DATData ()
Constructor
Definition at line 37 of file DATData.cpp.
DATData::DATData (const std::string & filename)
Constructor
Parameters:
filename Name of the DAT file
Definition at line 46 of file DATData.cpp.
References DAT_DATAGROUP, and SCAN_ACQUISITION_DATA_TYPE.
DATData::~DATData ()
Destructor
Definition at line 59 of file DATData.cpp.
Member Function Documentation
void DATData::AddGridAlignmentAlgorithmParameter (const ParameterNameValueType & nvt)
Add a grid alignment algorithm parameter. If the parameter already exists, it will be overwritten.
Parameters:
nvt Algorithm parameter to add to the list.
Definition at line 481 of file DATData.cpp.
Referenced by affymetrix_calvin_io::DATFileReader::ReadGridAlignmentAlgorithmParameters().
void DATData::AddSubgrid (u_int32_t status, const FRegion & subgrid)
Add a subgrid.
Parameters:
status A combination of the GridStatus flags indicating the status of the subgrid grid.
subgrid Subgrid region to be added.
Definition at line 317 of file DATData.cpp.
Referenced by affymetrix_calvin_io::DATFileReader::ReadSubgrids().
void DATData::Clear ()
Clear the class members
Definition at line 64 of file DATData.cpp.
Referenced by affymetrix_calvin_io::DATFileReader::Read().
void DATData::ClearGridAlignmentAlgorithmParameters ()
Remove all grid alignment algorithm parameters.
Definition at line 489 of file DATData.cpp.
Referenced by affymetrix_calvin_io::DATFileReader::ReadGridAlignmentAlgorithmParameters().
void affymetrix_calvin_io::DATData::ClearSubgrids () [inline]
Clear subgrids.
Definition at line 279 of file DATData.h.
bool DATData::FindGridAlignmentAlgorithmParameter (const std::wstring & name, ParameterNameValueType & param)
Return a grid alignment algorithm parameter given a name.
Parameters:
name Name of the grid alignment algorithm parameter to find.
param The found parameter.
Returns:
True if the parameter was found.
Definition at line 497 of file DATData.cpp.
std::wstring DATData::GetArrayBarcode ()
Get the array barcode.
Returns:
The barcode.
Definition at line 192 of file DATData.cpp.
References ARRAY_BARCODE_PARAM_NAME, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueText().
AffymetrixGuidType DATData::GetArrayId ()
Get the array id.
Returns:
The array id.
Definition at line 164 of file DATData.cpp.
References ARRAY_ID_PARAM_NAME, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii().
std::wstring DATData::GetArrayType ()
Get the array type.
Returns:
Returns the name of the array type of the DAT
Definition at line 151 of file DATData.cpp.
References ARRAY_TYPE_PARAM_NAME.
int32_t DATData::GetCols ()
Get the number of columns of pixels in the DAT.
Returns:
Returns the number of pixel columns in the DAT.
Definition at line 304 of file DATData.cpp.
References COLS_PARAM_NAME.
Referenced by affymetrix_calvin_io::MMDATFileWriter::MMDATFileWriter().
std::wstring DATData::GetExposureTime ()
Definition at line 258 of file DATData.cpp.
References PLATE_EXPOSURE_TIME.
FileHeader* affymetrix_calvin_io::DATData::GetFileHeader () [inline]
Get the FileHeader.
Returns:
Returns a pointer to the FileHeader.
Definition at line 119 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileUpdater::DATFileUpdater(), affymetrix_calvin_io::DATFileWriter::DATFileWriter(), affymetrix_calvin_io::MMDATFileWriter::MMDATFileWriter(), and affymetrix_calvin_io::DATFileUpdater::UpdateFileHeader().
std::string DATData::GetFilename ()
Get the file name.
Returns:
Returns the file name.
Definition at line 84 of file DATData.cpp.
Referenced by affymetrix_calvin_io::MMDATFileWriter::MMDATFileWriter(), affymetrix_calvin_io::DATFileReader::Read(), and affymetrix_calvin_io::DATFileUpdater::ReadCurrentData().
GenericData& affymetrix_calvin_io::DATData::GetGenericData () [inline]
Get the GenericData object.
Returns:
Returns a reference to the GenericData object.
Definition at line 123 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileReader::Read(), and affymetrix_calvin_io::DATFileUpdater::Update().
FRegion affymetrix_calvin_io::DATData::GetGlobalGrid () const [inline]
Get the global grid positions. Use FGridCoords::FGridCoords(FRegion&) cast constructor to convert to FGridCoords.
Returns:
Global grid position.
Definition at line 239 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileUpdater::WriteGridData().
u_int32_t affymetrix_calvin_io::DATData::GetGlobalGridStatus () const [inline]
Get the global grid status.
Returns:
Returns the status of the global grid. Can be a combination of GridStatus values.
Definition at line 244 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileUpdater::WriteGridData().
void DATData::GetGridAlignmentAlgorithmParameters (ParameterNameValueTypeVector & algParams)
Return the grid alignment algorithm parameters.
Parameters:
algParams Vector with grid alignment algorithm parameters.
Definition at line 513 of file DATData.cpp.
Referenced by affymetrix_calvin_io::DATFileUpdater::AddGridDataSetHeaderParameters().
int32_t DATData::GetInt32FromGenericHdr (const std::wstring & name) [private]
Definition at line 344 of file DATData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32().
GenericDataHeader * DATData::GetParentArrayGenericDataHeader ()
Get a pointer to the parent array GenericDataHeader object.
Returns:
A pointer to the parent array GenericDataHeader. Never null.
Definition at line 462 of file DATData.cpp.
References ARRAY_TYPE_IDENTIFIER, affymetrix_calvin_io::GenericDataHeader::FindParent(), and affymetrix_calvin_io::GenericDataHeader::SetFileTypeId().
int32_t DATData::GetPegSubImageIndex ()
Get the index of the subimage of the peg.
Returns:
Return the index of the subimage of the peg.
Definition at line 268 of file DATData.cpp.
References PLATE_PEG_SUBIMAGE_INDEX.
bool DATData::GetPixels (u_int16_t * pixelBuffer, u_int32_t startRow, u_int32_t rowCnt)
Fills the array with pixel values
Parameters:
pixelBuffer Pointer to the buffer to receive pixel intensities
startRow The row from which to start copying pixel intensities
rowCnt The number of rows of pixel intensities to copy to the buffer
Returns:
true if the method succeeded
Definition at line 368 of file DATData.cpp.
bool DATData::GetPixels (u_int16_t * pixelBuffer, u_int32_t startRow, u_int32_t startCol, u_int32_t rowCnt, u_int32_t colCnt)
Fills the array with requested pixel values. Uses a small-memory footprint access. Good for retrieving small parts of the image.
Parameters:
pixelBuffer Pointer to the buffer to receive the pixel intensities
startRow The row from which to start copying pixel intensities
startCol The col from which to start copying pixel intensities
rowCnt The number of rows of pixel intensities to copy to the buffer
colCnt The number of columns of pixel intensities to copy to the buffer
Returns:
true if the method succeeded
Definition at line 390 of file DATData.cpp.
float DATData::GetPixelSize ()
Get the pixel size.
Returns:
Returns the pixel size in microns.
Definition at line 217 of file DATData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), and PIXEL_SIZE_PARAM_NAME.
bool DATData::GetRange (u_int16_t & min, u_int16_t & max)
Gets the range of pixel intensities.
Parameters:
min Reference to a u_int16_t to receive the min pixel intensity
max Reference to a u_int16_t to receive the max pixel intensity
Returns:
true if the max and min intensities can be returned.
Definition at line 419 of file DATData.cpp.
int32_t DATData::GetRows ()
Get the number of rows of pixels in the DAT.
Returns:
Returns the number of pixel rows in the DAT.
Definition at line 291 of file DATData.cpp.
References ROWS_PARAM_NAME.
Referenced by affymetrix_calvin_io::MMDATFileWriter::MMDATFileWriter().
affymetrix_calvin_utilities::DateTime DATData::GetScanDate ()
Get the date of the scan.
Returns:
Returns the date of the scan.
Definition at line 278 of file DATData.cpp.
References SCAN_DATE_PARAM_NAME.
std::wstring DATData::GetScannerID ()
Get the ID of the scanner used to generate the DAT.
Returns:
Returns the ID of the scanner used to generate the DAT.
Definition at line 248 of file DATData.cpp.
References SCANNER_ID_PARAM_NAME.
std::wstring DATData::GetScannerType ()
Get the type of scanner used to generate the DAT.
Returns:
Returns the type of scanner used to generate the DAT.
Definition at line 238 of file DATData.cpp.
References SCANNER_TYPE_PARAM_NAME.
FRegion affymetrix_calvin_io::DATData::GetSubgrid (int32_t index) const [inline]
Return a subgrid by index.
Parameters:
index Index of the subgrid to get
Returns:
A region defining the subgrid.
Definition at line 265 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileUpdater::WriteSubGridData().
int32_t affymetrix_calvin_io::DATData::GetSubgridCnt () const [inline]
Get the number of subgrids.
Returns:
Number of subgrids
Definition at line 260 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileUpdater::CreateSubGridDataSetHeader(), affymetrix_calvin_io::DATFileUpdater::Update(), and affymetrix_calvin_io::DATFileUpdater::WriteSubGridData().
u_int32_t affymetrix_calvin_io::DATData::GetSubgridStatus (int32_t index) const [inline]
Get the status of a subgrid.
Parameters:
index Index of the subgrid status to get.
Returns:
Returns the status of the subgrid. Can be a combination of GridStatus values.
Definition at line 270 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileUpdater::WriteSubGridData().
std::wstring DATData::GetWStringFromGenericHdr (const std::wstring & name) [private]
Definition at line 323 of file DATData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueText().
bool affymetrix_calvin_io::DATData::HasGlobalGridData () const [inline]
Has global grid data been set.
Returns:
True if there is global grid data.
Definition at line 249 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileUpdater::Update().
void DATData::InsertDataSetHeader (const DataSetHeader & hdr) [private]
Definition at line 145 of file DATData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr().
void DATData::PreparePixelSet () [private]
Definition at line 434 of file DATData.cpp.
References DAT_PIXEL.
void DATData::PrepareSet (const std::wstring & name, DataSet *& ds) [private]
Definition at line 452 of file DATData.cpp.
References DAT_DATAGROUP, affymetrix_calvin_io::DataSet::DataSet(), and affymetrix_calvin_io::DataSet::Open().
void DATData::PrepareSmallMemoryPixelSet () [private]
Definition at line 439 of file DATData.cpp.
References DAT_PIXEL.
void DATData::PrepareStatsSet () [private]
Definition at line 447 of file DATData.cpp.
References DAT_STATS.
void DATData::SetArrayBarcode (std::wstring & value)
Set the array barcode.
Parameters:
value The barcode.
Definition at line 208 of file DATData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), ARRAY_BARCODE_MAX_LEN, ARRAY_BARCODE_PARAM_NAME, affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
void DATData::SetArrayId (affymetrix_calvin_utilities::AffymetrixGuidType & value)
Set the array id.
Parameters:
value The array id.
Definition at line 180 of file DATData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), AFFY_GUID_LEN, ARRAY_ID_PARAM_NAME, affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueAscii().
void DATData::SetArrayType (const std::wstring & value)
Set the array type.
Parameters:
value The name of the DAT array type.
Definition at line 156 of file DATData.cpp.
References ARRAY_TYPE_MAX_LEN, and ARRAY_TYPE_PARAM_NAME.
void DATData::SetCols (int32_t value)
Set the number of colums of pixels in the DAT.
Parameters:
value The number of pixel columns in the DAT.
Definition at line 311 of file DATData.cpp.
References COLS_PARAM_NAME.
void DATData::SetExposureTime (std::wstring & value)
Definition at line 263 of file DATData.cpp.
References PLATE_EXPOSURE_TIME.
void DATData::SetFilename (const std::string & p)
Set the file name.
Parameters:
p Name of the file.
Definition at line 79 of file DATData.cpp.
Referenced by affymetrix_calvin_io::DATFileUpdater::ReadCurrentData().
void affymetrix_calvin_io::DATData::SetGlobalGrid (u_int32_t gridStatus, FRegion & grid) [inline]
Set the global grid positions. Use FRegion::FRegion(FGridCoords&) cast constructor to convert from FGridCoords.
Parameters:
gridStatus A combination of the GridStatus flags indicating the status of the global grid.
grid Global grid position
Definition at line 255 of file DATData.h.
Referenced by affymetrix_calvin_io::DATFileReader::ReadGlobalGrid().
void DATData::SetInt32ToGenericHdr (const std::wstring & name, int32_t value) [private]
Definition at line 356 of file DATData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32().
void DATData::SetPegSubImageIndex (int32_t value)
Set the index of the subimage of the peg.
Returns:
void and set the subimage of the peg to the DAT file.
Definition at line 273 of file DATData.cpp.
References PLATE_PEG_SUBIMAGE_INDEX.
void DATData::SetPixelCount (int32_t ln)
Set the total number of pixels in the DAT.
Parameters:
ln Number of pixels.
Definition at line 89 of file DATData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddUShortColumn(), DAT_PIXEL, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void DATData::SetPixelSize (float value)
Set the pixel size.
Parameters:
value The pixel size in microns.
Definition at line 229 of file DATData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), PIXEL_SIZE_PARAM_NAME, affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueFloat().
void DATData::SetRows (int32_t value)
Set the number of rows of pixels in the DAT.
Parameters:
value The number of pixel rows in the DAT.
Definition at line 298 of file DATData.cpp.
References ROWS_PARAM_NAME.
void DATData::SetScanDate (affymetrix_calvin_utilities::DateTime value)
Set the date of the scan.
Parameters:
value The date of the scan.
Definition at line 285 of file DATData.cpp.
References SCAN_DATE_PARAM_NAME, and affymetrix_calvin_utilities::DateTime::ToString().
void DATData::SetScannerID (const std::wstring & value)
Set the ID of the scanner used to generate the DAT.
Parameters:
value The ID of the scanner used to generate the DAT.
Definition at line 253 of file DATData.cpp.
References SCANNER_ID_PARAM_NAME.
void DATData::SetScannerType (const std::wstring & value)
Set the type of scanner used to generate the DAT.
Parameters:
value The type of scanner used to generate the DAT.
Definition at line 243 of file DATData.cpp.
References SCANNER_TYPE_PARAM_NAME.
void DATData::SetStatsCount (int32_t ln)
Set the total number of statistic rows in the DAT.
Parameters:
ln Number of rows of statistic rows.
Definition at line 106 of file DATData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddUShortColumn(), DAT_STATS, MaxIntensityColName, MinIntensityColName, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void DATData::SetWStringToGenericHdr (const std::wstring & name, const std::wstring value, int32_t reserve = -1) [private]
Definition at line 335 of file DATData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
void DATData::UpdateDataSetRowCount (const DataSetHeader & hdr) [private]
Definition at line 124 of file DATData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), affymetrix_calvin_io::DataSetHeader::GetName(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Member Data Documentation
int32_t affymetrix_calvin_io::DATData::cachedCols [private]
keep cols from being read from the header all the time
Definition at line 78 of file DATData.h.
int32_t affymetrix_calvin_io::DATData::cachedRows [private]
keep rows from being read from the header all the time
Definition at line 76 of file DATData.h.
DataSet* affymetrix_calvin_io::DATData::dsPixel [private]
Pixel intensity DataSet
Definition at line 80 of file DATData.h.
DataSet* affymetrix_calvin_io::DATData::dsSMPixel [private]
Small memory pixel DataSet
Definition at line 82 of file DATData.h.
DataSet* affymetrix_calvin_io::DATData::dsStats [private]
Stats DataSet
Definition at line 84 of file DATData.h.
GenericData affymetrix_calvin_io::DATData::genericData [private]
generic file object
Definition at line 71 of file DATData.h.
FRegion affymetrix_calvin_io::DATData::globalGrid [private]
Global grid
Definition at line 86 of file DATData.h.
u_int32_t affymetrix_calvin_io::DATData::globalGridStatus [private]
Global grid status flag - indicates the state of the global grid
Definition at line 88 of file DATData.h.
ParameterNameValueTypeVector affymetrix_calvin_io::DATData::gridAlignParams [private]
Grid Alignment Algorithm Parameters
Definition at line 94 of file DATData.h.
bool affymetrix_calvin_io::DATData::setPixelMetaData [private]
Definition at line 72 of file DATData.h.
bool affymetrix_calvin_io::DATData::setStatsMetaData [private]
Definition at line 73 of file DATData.h.
FRegionVector affymetrix_calvin_io::DATData::subgrids [private]
Subgrids
Definition at line 90 of file DATData.h.
Uint32Vector affymetrix_calvin_io::DATData::subgridsStatus [private]
Subgrids status flag - indicates the state of each subgrid
Definition at line 92 of file DATData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/DATData.h
C:/f112/affy/sdk/calvin_files/data/src/DATData.cpp