Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCDFProbeGroupInformation Class Reference
affymetrix_fusion_io::FusionCDFProbeGroupInformation Class Reference
#include <FusionCDFData.h>
Public Member Functions
affxcdf::DirectionType GetDirection () const
int GetNumLists () const
int GetNumCells () const
int GetNumCellsPerList () const
int GetStart () const
int GetStop () const
std::string GetName () const
unsigned short GetWobbleSituation () const
unsigned short GetAlleleCode () const
unsigned char GetChannel () const
affxcdf::ReplicationType GetRepType () const
void GetCell (int cell_index, FusionCDFProbeInformation &info)
FusionCDFProbeGroupInformation ()
~FusionCDFProbeGroupInformation ()
Private Member Functions
void Initialize (int index, affxcdf::CCDFProbeSetInformation *gcosSet)
void Initialize (int index, affymetrix_calvin_io::CDFProbeSetInformation *calvinSet)
void Clear ()
Private Attributes
affxcdf::CCDFProbeGroupInformation * gcosGroup
affymetrix_calvin_io::CDFProbeGroupInformation * calvinGroup
Friends
class FusionCDFProbeSetInformation
Detailed Description
This class provides storage for a group of probes, also known as a block.
Definition at line 187 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFProbeGroupInformation::FusionCDFProbeGroupInformation ()
Constructor
Definition at line 767 of file FusionCDFData.cpp.
FusionCDFProbeGroupInformation::~FusionCDFProbeGroupInformation ()
Destructor
Definition at line 776 of file FusionCDFData.cpp.
Member Function Documentation
void FusionCDFProbeGroupInformation::Clear (void) [private]
Deallocates any used memory.
Definition at line 784 of file FusionCDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetGroupInformation().
unsigned short FusionCDFProbeGroupInformation::GetAlleleCode () const
Gets the allele code.
Returns:
The allele code.
Definition at line 691 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeGroupInformationCOM::get_AlleleCode().
void FusionCDFProbeGroupInformation::GetCell (int cell_index, FusionCDFProbeInformation & info)
Retrieves the probe object given an index.
Parameters:
cell_index Index to the probe of interest.
info The returned probe data.
Definition at line 754 of file FusionCDFData.cpp.
References affymetrix_fusion_io::FusionCDFProbeInformation::Clear(), and affymetrix_fusion_io::FusionCDFProbeInformation::Initialize().
Referenced by CFusionCDFProbeGroupInformationCOM::GetCell(), ReadSingleChannelCelFile(), and ReadSingleOrMultiChannelCelFile().
unsigned char FusionCDFProbeGroupInformation::GetChannel () const
Gets the channel.
Returns:
The channel.
Definition at line 704 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeGroupInformationCOM::get_Channel().
affxcdf::DirectionType FusionCDFProbeGroupInformation::GetDirection () const
Gets the groups direction.
Returns:
The groups direction.
Definition at line 555 of file FusionCDFData.cpp.
References AntiSenseDirection, EitherDirection, NoDirection, affymetrix_calvin_io::ProbeAntiSenseDirection, affymetrix_calvin_io::ProbeEitherDirection, affymetrix_calvin_io::ProbeNoDirection, affymetrix_calvin_io::ProbeSenseDirection, and SenseDirection.
Referenced by CFusionCDFProbeGroupInformationCOM::get_Direction().
std::string FusionCDFProbeGroupInformation::GetName () const
Gets the group name.
Returns:
The group name.
Definition at line 665 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeGroupInformationCOM::get_Name().
int FusionCDFProbeGroupInformation::GetNumCells () const
Gets the number of probes in the group.
Returns:
The number of probes in the group.
Definition at line 605 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeGroupInformationCOM::get_NumCells(), ReadSingleChannelCelFile(), and ReadSingleOrMultiChannelCelFile().
int FusionCDFProbeGroupInformation::GetNumCellsPerList () const
Gets the number of probes per list.
Returns:
The number of probes per list.
Definition at line 618 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeGroupInformationCOM::get_NumCellsPerList().
int FusionCDFProbeGroupInformation::GetNumLists () const
Gets the number of lists (atoms) in the group.
Returns:
The number of lists (atoms) in the group.
Definition at line 592 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeGroupInformationCOM::get_NumLists().
affxcdf::ReplicationType FusionCDFProbeGroupInformation::GetRepType () const
Gets the probe replication type.
Returns:
The probe replication type.
Definition at line 717 of file FusionCDFData.cpp.
References affymetrix_calvin_io::DifferentProbeRepType, DifferentRepType, affymetrix_calvin_io::IdenticalProbeRepType, IdenticalRepType, affymetrix_calvin_io::MixedProbeRepType, MixedRepType, affymetrix_calvin_io::UnknownProbeRepType, and UnknownRepType.
Referenced by CFusionCDFProbeGroupInformationCOM::get_RepType().
int FusionCDFProbeGroupInformation::GetStart () const
Gets the start list index value.
Returns:
The start list index value.
Definition at line 631 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeInformation::GetListIndex().
Referenced by CFusionCDFProbeGroupInformationCOM::get_Start().
int FusionCDFProbeGroupInformation::GetStop () const
Gets the stop list index value.
Returns:
The stop list index value.
Definition at line 648 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeInformation::GetListIndex().
Referenced by CFusionCDFProbeGroupInformationCOM::get_Stop().
unsigned short FusionCDFProbeGroupInformation::GetWobbleSituation () const
Gets the wobble situation.
Returns:
The wobble situation.
Definition at line 678 of file FusionCDFData.cpp.
Referenced by CFusionCDFProbeGroupInformationCOM::get_WobbleSituation().
void FusionCDFProbeGroupInformation::Initialize (int index, affxcdf::CCDFProbeSetInformation * gcosSet) [private]
Initializes the class for GCOS file reading.
Parameters:
index The index to the probe group.
gcosSet The GCOS probe set object.
Definition at line 795 of file FusionCDFData.cpp.
References affxcdf::CCDFProbeSetInformation::GetGroupInformation().
Referenced by affymetrix_fusion_io::FusionCDFProbeSetInformation::GetGroupInformation().
void FusionCDFProbeGroupInformation::Initialize (int index, affymetrix_calvin_io::CDFProbeSetInformation * calvinSet) [private]
Initializes the class for Calvin file reading.
Parameters:
index The index to the probe group.
calvinSet The Calvin probe set object.
Definition at line 805 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFProbeSetInformation::GetGroupInformation().
Friends And Related Function Documentation
friend class FusionCDFProbeSetInformation [friend]
Friend to the parent class.
Definition at line 212 of file FusionCDFData.h.
Member Data Documentation
affymetrix_calvin_io::CDFProbeGroupInformation* affymetrix_fusion_io::FusionCDFProbeGroupInformation::calvinGroup [private]
The Calvin probe group object.
Definition at line 194 of file FusionCDFData.h.
affxcdf::CCDFProbeGroupInformation* affymetrix_fusion_io::FusionCDFProbeGroupInformation::gcosGroup [private]
The GCOS probe group object.
Definition at line 191 of file FusionCDFData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.cpp