Affymetrix Fusion SDK: affymetrix_calvin_io::GenericDataHeaderReader Class Reference
affymetrix_calvin_io::GenericDataHeaderReader Class Reference
#include <GenericDataHeaderReader.h>
Public Member Functions
GenericDataHeaderReader (std::ifstream &fs)
void Read (GenericDataHeader &gdh)
void Read (GenericDataHeader &gdh, bool doUniqueAdds)
Protected Attributes
std::ifstream & fileStream
Detailed Description
This class reads the GenericDataHeader from a file.
Definition at line 39 of file GenericDataHeaderReader.h.
Constructor & Destructor Documentation
GenericDataHeaderReader::GenericDataHeaderReader (std::ifstream & fs)
Constructor
Parameters:
fs Open stream positioned at the start of the first GenericDataHeader.
Definition at line 35 of file GenericDataHeaderReader.cpp.
Member Function Documentation
void GenericDataHeaderReader::Read (GenericDataHeader & gdh)
Read the GenericDataHeader and all parent GenericDataHeaders from the input stream.
Parameters:
gdh Reference to the GenericDataHeader object to which to add the GenericDataHeader information.
Definition at line 44 of file GenericDataHeaderReader.cpp.
Referenced by Read(), and affymetrix_calvin_io::FileHeaderReader::ReadGenericDataHdr().
void GenericDataHeaderReader::Read (GenericDataHeader & gdh, bool doUniqueAdds)
Read the GenericDataHeader and all parent GenericDataHeaders from the input stream.
Parameters:
gdh Reference to the GenericDataHeader object to which to add the GenericDataHeader information.
doUniqueAdds Hint to indicate to ensure no duplicates are added to the collection. If true, the check is made and performance is N^2, if false, no check is made and is assuming you are just reading from a file.
Definition at line 54 of file GenericDataHeaderReader.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_io::GenericDataHeader::AddParent(), fileStream, Read(), affymetrix_calvin_io::FileInput::ReadBlob(), affymetrix_calvin_io::FileInput::ReadString16(), affymetrix_calvin_io::FileInput::ReadString8(), affymetrix_calvin_io::FileInput::ReadUInt32(), affymetrix_calvin_io::GenericDataHeader::SetFileCreationTime(), affymetrix_calvin_io::GenericDataHeader::SetFileId(), affymetrix_calvin_io::GenericDataHeader::SetFileTypeId(), and affymetrix_calvin_io::GenericDataHeader::SetLocale().
Member Data Documentation
std::ifstream& affymetrix_calvin_io::GenericDataHeaderReader::fileStream [protected]
A reference to the file stream.
Definition at line 61 of file GenericDataHeaderReader.h.
Referenced by Read().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/GenericDataHeaderReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/GenericDataHeaderReader.cpp