Affymetrix Fusion SDK: affymetrix_calvin_io::FileHeaderReader Class Reference
affymetrix_calvin_io::FileHeaderReader Class Reference
#include <FileHeaderReader.h>
Public Member Functions
FileHeaderReader (std::ifstream &fs, FileHeader &fh)
void Read ()
u_int32_t GetDataGroupCnt () const
u_int32_t GetFirstDataGroupFilePos () const
Protected Member Functions
void ReadMagicNumber ()
void ReadVersion ()
void ReadDataGroupCnt ()
void ReadFirstDataGroupFilePos ()
void ReadGenericDataHdr ()
Protected Attributes
std::ifstream & fileStream
FileHeader & header
u_int32_t dataGroupCnt
u_int32_t firstDataGroupFilePos
Detailed Description
This class reads the FileHeader of the generic data file.
Definition at line 44 of file FileHeaderReader.h.
Constructor & Destructor Documentation
FileHeaderReader::FileHeaderReader (std::ifstream & fs, FileHeader & fh)
Constructor
Parameters:
fs Open fstream positioned at the start of the file.
fh FileHeader object to fill.
Definition at line 41 of file FileHeaderReader.cpp.
References dataGroupCnt, and firstDataGroupFilePos.
Member Function Documentation
u_int32_t affymetrix_calvin_io::FileHeaderReader::GetDataGroupCnt () const [inline]
Gets the number of DataGroups in the file.
Returns:
Number of DataGroups.
Definition at line 62 of file FileHeaderReader.h.
References dataGroupCnt.
u_int32_t affymetrix_calvin_io::FileHeaderReader::GetFirstDataGroupFilePos () const [inline]
Gets the file position of the first DataGroup header.
Definition at line 65 of file FileHeaderReader.h.
References firstDataGroupFilePos.
void FileHeaderReader::Read ()
Reads the FileHeader.
Exceptions:
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 51 of file FileHeaderReader.cpp.
References ReadDataGroupCnt(), ReadFirstDataGroupFilePos(), ReadGenericDataHdr(), ReadMagicNumber(), and ReadVersion().
Referenced by affymetrix_calvin_io::GenericFileReader::ReadFileHeader(), affymetrix_calvin_io::GenericFileReader::ReadFileHeaderMinDP(), and affymetrix_calvin_io::GenericFileReader::ReadFileHeaderNoDataGroupHeader().
void FileHeaderReader::ReadDataGroupCnt () [protected]
Reads the DataGroup count from the file.
Definition at line 91 of file FileHeaderReader.cpp.
References dataGroupCnt, fileStream, header, affymetrix_calvin_io::FileInput::ReadUInt32(), and affymetrix_calvin_io::FileHeader::SetNumDataGroups().
Referenced by Read().
void FileHeaderReader::ReadFirstDataGroupFilePos () [protected]
Reads the file position of the first DataGroup.
Definition at line 100 of file FileHeaderReader.cpp.
References fileStream, firstDataGroupFilePos, header, affymetrix_calvin_io::FileInput::ReadUInt32(), and affymetrix_calvin_io::FileHeader::SetFirstDataGroupFilePos().
Referenced by Read().
void FileHeaderReader::ReadGenericDataHdr () [protected]
Reads the GenericDataHeader from the file.
Definition at line 109 of file FileHeaderReader.cpp.
References fileStream, header, affymetrix_calvin_io::GenericDataHeaderReader::Read(), and affymetrix_calvin_io::FileHeader::SetGenericDataHdr().
Referenced by Read().
void FileHeaderReader::ReadMagicNumber () [protected]
Reads the magic number from the file.
Exceptions:
affymetrix_calvin_exceptions::InvalidFileTypeException The file is not of the right type.
Definition at line 63 of file FileHeaderReader.cpp.
References DATA_FILE_MAGIC_NUMBER, fileStream, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and ReadInt8().
Referenced by Read().
void FileHeaderReader::ReadVersion () [protected]
Reads the generic file version number from the file.
Exceptions:
affymetrix_calvin_exceptions::InvalidVersionException The file version does not match.
Definition at line 77 of file FileHeaderReader.cpp.
References DATA_FILE_VERSION_NUMBER, fileStream, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and ReadInt8().
Referenced by Read().
Member Data Documentation
u_int32_t affymetrix_calvin_io::FileHeaderReader::dataGroupCnt [protected]
Number of DataGroups.
Definition at line 95 of file FileHeaderReader.h.
Referenced by FileHeaderReader(), GetDataGroupCnt(), and ReadDataGroupCnt().
std::ifstream& affymetrix_calvin_io::FileHeaderReader::fileStream [protected]
A reference to the file stream.
Definition at line 89 of file FileHeaderReader.h.
Referenced by ReadDataGroupCnt(), ReadFirstDataGroupFilePos(), ReadGenericDataHdr(), ReadMagicNumber(), and ReadVersion().
u_int32_t affymetrix_calvin_io::FileHeaderReader::firstDataGroupFilePos [protected]
Position of the first DataGroup.
Definition at line 98 of file FileHeaderReader.h.
Referenced by FileHeaderReader(), GetFirstDataGroupFilePos(), and ReadFirstDataGroupFilePos().
FileHeader& affymetrix_calvin_io::FileHeaderReader::header [protected]
FileHeader object to fill.
Definition at line 92 of file FileHeaderReader.h.
Referenced by ReadDataGroupCnt(), ReadFirstDataGroupFilePos(), and ReadGenericDataHdr().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/FileHeaderReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/FileHeaderReader.cpp