Affymetrix Fusion SDK: CalvinValue Class Reference
CalvinValue Class Reference
#include <Calvin.h>
Public Types
enum ParameterType {
Int8Type, UInt8Type, Int16Type, UInt16Type,
Int32Type, UInt32Type, FloatType, TextType,
AsciiType, UnknownType
}
Public Member Functions
CalvinValue ()
CalvinValue (ParameterType eParameterType, const AffxString &strValue)
ParameterType getParameterType ()
AffxString & getValue ()
void clear ()
int compareTo (CalvinValue &that, int iCompareCode)
Protected Attributes
ParameterType m_eParameterType
AffxString m_strValue
Detailed Description
Definition at line 43 of file Calvin.h.
Member Enumeration Documentation
enum CalvinValue::ParameterType
Enumerant of the built-in parameter types.
Enumerator:
Int8Type
UInt8Type
an 8 bit integer.
Int16Type
an 8 bit unsigned integer.
UInt16Type
a 16 bit integer.
Int32Type
a 16 bit unsigned integer.
UInt32Type
a 32 bit integer.
FloatType
a 32 bit unsigned integer.
TextType
a 32 bit floating point.
AsciiType
a 16 bit character.
UnknownType
an 8 bit character.
an 8 bit integer.
Definition at line 47 of file Calvin.h.
Constructor & Destructor Documentation
CalvinValue::CalvinValue () [inline]
Definition at line 65 of file Calvin.h.
References clear().
CalvinValue::CalvinValue (ParameterType eParameterType, const AffxString & strValue) [inline]
Definition at line 66 of file Calvin.h.
References m_eParameterType, and m_strValue.
Member Function Documentation
void CalvinValue::clear () [inline]
Reimplemented in CalvinParameter.
Definition at line 73 of file Calvin.h.
References m_eParameterType, m_strValue, and UnknownType.
Referenced by CalvinValue().
int CalvinValue::compareTo (CalvinValue & that, int iCompareCode) [inline]
Compare function.
Parameters:
that - A reference to an instance of this class.
iCompareCode - The code to switch on when doing compares. (Each code is a different compare.)
Returns:
- int value. (-1 if *this < that, 0 if *this == that, 1 if *this > that)
Definition at line 81 of file Calvin.h.
References AsciiType, AffxString::compareTo(), FloatType, getDouble(), getInt(), getUnsignedInt(), m_eParameterType, m_strValue, TextType, and UInt32Type.
ParameterType CalvinValue::getParameterType () [inline]
Definition at line 71 of file Calvin.h.
References m_eParameterType.
Referenced by Calvin::equivalent(), and Calvin::equivalentParameter().
AffxString& CalvinValue::getValue () [inline]
Definition at line 72 of file Calvin.h.
References m_strValue.
Referenced by Calvin::equivalent(), and Calvin::equivalentParameter().
Member Data Documentation
ParameterType CalvinValue::m_eParameterType [protected]
Definition at line 61 of file Calvin.h.
Referenced by CalvinValue(), clear(), compareTo(), getParameterType(), and CalvinParameter::set().
AffxString CalvinValue::m_strValue [protected]
Definition at line 62 of file Calvin.h.
Referenced by CalvinValue(), clear(), compareTo(), getValue(), and CalvinParameter::set().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/calvin_files/utils/src/Calvin.h