Affymetrix Fusion SDK: PgOptionsSAXHandler Class Reference
PgOptionsSAXHandler Class Reference
Public Member Functions
PgOptionsSAXHandler (PgOptions *pPgOptions, std::vector< std::string > &vFileNames)
~PgOptionsSAXHandler ()
unsigned int getOptionCount () const
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exc)
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exc)
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exc)
void startDocument ()
void endDocument ()
void startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList &attributes)
Static Public Member Functions
static std::string toString (const XMLCh *const in)
Private Attributes
PgOptions * m_pPgOptions
std::vector< std::string > * m_pvFileNames
unsigned int m_uiOptionCount
AffxString m_strPrevCategory
AffxString m_strAnalysis
Detailed Description
Definition at line 56 of file PgOptions.cpp.
Constructor & Destructor Documentation
PgOptionsSAXHandler::PgOptionsSAXHandler (PgOptions * pPgOptions, std::vector< std::string > & vFileNames) [inline]
Definition at line 66 of file PgOptions.cpp.
References Err::errAbort(), and m_pPgOptions.
PgOptionsSAXHandler::~PgOptionsSAXHandler () [inline]
Definition at line 71 of file PgOptions.cpp.
Member Function Documentation
void PgOptionsSAXHandler::endDocument () [inline]
Definition at line 81 of file PgOptions.cpp.
References PgOpt::m_allowMultiple, m_pPgOptions, m_strAnalysis, PgOptions::mustFindOpt(), Verbose::out(), PgOptions::push(), and PgOptions::set().
void PgOptionsSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exc) [inline]
Definition at line 76 of file PgOptions.cpp.
References Err::errAbort(), and toString().
void PgOptionsSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exc) [inline]
Definition at line 77 of file PgOptions.cpp.
References Err::errAbort(), and toString().
unsigned int PgOptionsSAXHandler::getOptionCount () const [inline]
Definition at line 73 of file PgOptions.cpp.
References m_uiOptionCount.
void PgOptionsSAXHandler::startDocument () [inline]
Definition at line 79 of file PgOptions.cpp.
References m_uiOptionCount.
void SAXTemplateHandlers::startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList & attributes) [inline]
Definition at line 106 of file PgOptions.cpp.
References PgOptions::getXMLParameterFileGuid(), PgOptions::isOptDefined(), PgOpt::m_allowMultiple, m_pPgOptions, m_pvFileNames, m_strAnalysis, m_strPrevCategory, PgOptions::m_strXMLParameterFileGuid, m_uiOptionCount, PgOptions::mustFindOpt(), Verbose::out(), PgOptions::push(), PgOptions::set(), PgOptions::setOptionsFromXMLFile(), and toString().
static std::string PgOptionsSAXHandler::toString (const XMLCh *const in) [inline, static]
Definition at line 97 of file PgOptions.cpp.
References AffxString::trim().
Referenced by error(), fatalError(), PgOptions::setOptionsFromXMLFile(), startElement(), and warning().
void PgOptionsSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exc) [inline]
Definition at line 75 of file PgOptions.cpp.
References Verbose::out(), and toString().
Member Data Documentation
PgOptions* PgOptionsSAXHandler::m_pPgOptions [private]
Definition at line 59 of file PgOptions.cpp.
Referenced by endDocument(), PgOptionsSAXHandler(), and startElement().
std::vector<std::string>* PgOptionsSAXHandler::m_pvFileNames [private]
Definition at line 60 of file PgOptions.cpp.
Referenced by startElement().
AffxString PgOptionsSAXHandler::m_strAnalysis [private]
Definition at line 63 of file PgOptions.cpp.
Referenced by endDocument(), and startElement().
AffxString PgOptionsSAXHandler::m_strPrevCategory [private]
Definition at line 62 of file PgOptions.cpp.
Referenced by startElement().
unsigned int PgOptionsSAXHandler::m_uiOptionCount [private]
Definition at line 61 of file PgOptions.cpp.
Referenced by getOptionCount(), startDocument(), and startElement().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/PgOptions.cpp
C:/f112/affy/sdk/calvin_files/parsers/src/SAXParameterFileHandlers.cpp
C:/f112/affy/sdk/calvin_files/parsers/src/SAXTemplateHandlers.cpp