Affymetrix Fusion SDK: affxchpwriter::CCHPFileUpdater Class Reference
affxchpwriter::CCHPFileUpdater Class Reference
#include <CHPFileUpdater.h>
Public Member Functions
CCHPFileUpdater ()
~CCHPFileUpdater ()
void OpenCHPFile (const char *fileName)
void UpdateExpressionEntry (int row, unsigned char Detection, float DetectionPValue, float Signal, unsigned short NumPairs, unsigned short NumUsedPairs)
void UpdateGenotypeEntry (int row, uint8_t call, float confidence, float RAS1, float RAS2, float aaCall, float abCall, float bbCall, float noCall)
void CloseCHPFile ()
Private Attributes
std::ofstream * m_CHPFile
Detailed Description
Provides interfaces to update data in a "Calvin" binary "signal" data file. This class assumes that the file has been completely written and that only existing data groups/sets/rows/cols are being modified.
Definition at line 41 of file CHPFileUpdater.h.
Constructor & Destructor Documentation
CCHPFileUpdater::CCHPFileUpdater ()
Constructor
Definition at line 42 of file CHPFileUpdater.cpp.
References m_CHPFile.
CCHPFileUpdater::~CCHPFileUpdater ()
Destructor
Definition at line 50 of file CHPFileUpdater.cpp.
References CloseCHPFile().
Member Function Documentation
void CCHPFileUpdater::CloseCHPFile ()
Close CHP signal file.
Definition at line 101 of file CHPFileUpdater.cpp.
References m_CHPFile.
Referenced by affxchpwriter::CCHPFileBufferWriter::FlushBuffer(), OpenCHPFile(), and ~CCHPFileUpdater().
void CCHPFileUpdater::OpenCHPFile (const char * fileName)
Open CHP signal file and initialize it.
Parameters:
fileName The name of the CHP signal file.
Definition at line 55 of file CHPFileUpdater.cpp.
References CloseCHPFile(), Err::errAbort(), m_CHPFile, and ToStr().
Referenced by affxchpwriter::CCHPFileBufferWriter::FlushBuffer().
void CCHPFileUpdater::UpdateExpressionEntry (int row, unsigned char Detection, float DetectionPValue, float Signal, unsigned short NumPairs, unsigned short NumUsedPairs)
Seek to appropriate file position and update expression signal
Parameters:
row The row index.
Detection The detection call.
DetectionPValue The detection p-value.
Signal The new signal value.
NumPairs The number of probe pairs in the set.
NumUsedPairs The number of probe pairs used to calculate the signal value.
Definition at line 62 of file CHPFileUpdater.cpp.
References EXPRESSION_ABSOLUTE_STAT_ANALYSIS, FLOAT_SIZE, m_CHPFile, UCHAR_SIZE, USHORT_SIZE, WriteFloat_I(), WriteInt32_I(), WriteUInt16_I(), and WriteUInt8().
Referenced by affxchpwriter::CCHPFileBufferWriter::FlushBuffer().
void CCHPFileUpdater::UpdateGenotypeEntry (int row, uint8_t call, float confidence, float RAS1, float RAS2, float aaCall, float abCall, float bbCall, float noCall)
Seek to appropriate file position and update genotype entry
Parameters:
row The row index.
call CHP call representation.
confidence CHP confidence value.
RAS1 CHP RAS1 value.
RAS2 CHP RAS2 value.
aaCall CHP aaCall value.
abCall CHP abCall value.
bbCall CHP bbCall value.
noCall CHP noCall value.
Definition at line 81 of file CHPFileUpdater.cpp.
References FLOAT_SIZE, m_CHPFile, UCHAR_SIZE, WriteFloat_I(), WriteInt32_I(), and WriteUInt8().
Referenced by affxchpwriter::CCHPFileBufferWriter::FlushBuffer().
Member Data Documentation
std::ofstream* affxchpwriter::CCHPFileUpdater::m_CHPFile [private]
Definition at line 83 of file CHPFileUpdater.h.
Referenced by CCHPFileUpdater(), CloseCHPFile(), OpenCHPFile(), UpdateExpressionEntry(), and UpdateGenotypeEntry().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CHPFileUpdater.h
C:/f112/affy/sdk/file/CHPFileUpdater.cpp