Affymetrix Fusion SDK: affymetrix_calvin_io::FileHeaderWriter Class Reference
affymetrix_calvin_io::FileHeaderWriter Class Reference
#include <FileHeaderWriter.h>
Public Member Functions
FileHeaderWriter ()
~FileHeaderWriter ()
void Write (std::ofstream &os, FileHeader &p)
void UpdateDataGroupOffset (std::ofstream &os, u_int32_t offset) const
Private Member Functions
void WriteMagicNumber (std::ofstream &os, FileHeader &p)
void WriteVersion (std::ofstream &os, FileHeader &p)
void WriteDataGroupCnt (std::ofstream &os, FileHeader &p)
void WriteDataGroupOffset (std::ofstream &os, u_int32_t offset)
void WriteGenericDataHdr (std::ofstream &os, FileHeader &f)
Private Attributes
u_int32_t dataSetOffsetPos
Detailed Description
Definition at line 34 of file FileHeaderWriter.h.
Constructor & Destructor Documentation
affymetrix_calvin_io::FileHeaderWriter::FileHeaderWriter () [inline]
Definition at line 42 of file FileHeaderWriter.h.
References dataSetOffsetPos.
affymetrix_calvin_io::FileHeaderWriter::~FileHeaderWriter () [inline]
Definition at line 43 of file FileHeaderWriter.h.
Member Function Documentation
void FileHeaderWriter::UpdateDataGroupOffset (std::ofstream & os, u_int32_t offset) const
Definition at line 59 of file FileHeaderWriter.cpp.
References affymetrix_calvin_io::FileOutput::WriteUInt32().
Referenced by affymetrix_calvin_io::GenericFileWriter::WriteHeader().
void FileHeaderWriter::Write (std::ofstream & os, FileHeader & p)
Definition at line 29 of file FileHeaderWriter.cpp.
Referenced by affymetrix_calvin_io::GenericFileWriter::WriteHeader().
void FileHeaderWriter::WriteDataGroupCnt (std::ofstream & os, FileHeader & p) [private]
Definition at line 48 of file FileHeaderWriter.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), and affymetrix_calvin_io::FileOutput::WriteInt32().
void FileHeaderWriter::WriteDataGroupOffset (std::ofstream & os, u_int32_t offset) [private]
Definition at line 53 of file FileHeaderWriter.cpp.
References affymetrix_calvin_io::FileOutput::WriteUInt32().
void FileHeaderWriter::WriteGenericDataHdr (std::ofstream & os, FileHeader & f) [private]
Definition at line 69 of file FileHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetFileId(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_calvin_io::GenericDataHeader::SetFileId(), and affymetrix_calvin_io::GenericDataHeaderWriter::Write().
void FileHeaderWriter::WriteMagicNumber (std::ofstream & os, FileHeader & p) [private]
Definition at line 38 of file FileHeaderWriter.cpp.
References affymetrix_calvin_io::FileHeader::GetMagicNumber(), and WriteInt8().
void FileHeaderWriter::WriteVersion (std::ofstream & os, FileHeader & p) [private]
Definition at line 43 of file FileHeaderWriter.cpp.
References affymetrix_calvin_io::FileHeader::GetVersion(), and WriteInt8().
Member Data Documentation
u_int32_t affymetrix_calvin_io::FileHeaderWriter::dataSetOffsetPos [private]
Definition at line 38 of file FileHeaderWriter.h.
Referenced by FileHeaderWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/FileHeaderWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/FileHeaderWriter.cpp