Affymetrix Fusion SDK: affymetrix_calvin_parameter::ParameterNameValueType Class Reference
affymetrix_calvin_parameter::ParameterNameValueType Class Reference
#include <ParameterNameValueType.h>
Public Types
enum ParameterType {
Int8Type, UInt8Type, Int16Type, UInt16Type,
Int32Type, UInt32Type, FloatType, TextType,
AsciiType, UnknownType
}
Public Member Functions
ParameterNameValueType ()
ParameterNameValueType (const std::wstring &name, const void *mimeValue, int32_t mimeValueSize, const std::wstring &mimeType)
ParameterNameValueType (const std::wstring &name, const MIMEValue &mimeValue, const std::wstring &mimeType)
ParameterNameValueType operator= (const ParameterNameValueType &param)
bool operator== (const ParameterNameValueType &param) const
bool operator!= (const ParameterNameValueType &param) const
bool operator== (const std::wstring &name) const
bool operator!= (const std::wstring &name) const
bool operator< (const ParameterNameValueType &param) const
bool operator> (const ParameterNameValueType &param) const
std::wstring GetName () const
void SetName (const std::wstring &value)
ParameterType GetParameterType () const
int8_t GetValueInt8 () const
void SetValueInt8 (int8_t value)
u_int8_t GetValueUInt8 () const
void SetValueUInt8 (u_int8_t value)
int16_t GetValueInt16 () const
void SetValueInt16 (int16_t value)
u_int16_t GetValueUInt16 () const
void SetValueUInt16 (u_int16_t value)
int32_t GetValueInt32 () const
void SetValueInt32 (int32_t value)
u_int32_t GetValueUInt32 () const
void SetValueUInt32 (u_int32_t value)
float GetValueFloat () const
void SetValueFloat (float value)
std::wstring GetValueText () const
void SetValueText (const std::wstring &value, int32_t reserve=-1)
std::string GetValueAscii () const
void SetValueAscii (const std::string &value, int32_t reserve=-1)
std::wstring GetMIMEType () const
void SetMIMEType (const std::wstring &value)
MIMEValue GetMIMEValue () const
void SetMIMEValue (const MIMEValue &value)
std::wstring ToString () const
Protected Member Functions
u_int32_t ValueToInt (const wchar_t *mimeType) const
void IntToValue (u_int32_t value, const wchar_t *type)
Protected Attributes
std::wstring Name
std::wstring Type
MIMEValue Value
Detailed Description
A class to hold a parameter name/value/type. This class will convert several built-in types between the MIME string and their native types.
Definition at line 109 of file ParameterNameValueType.h.
Member Enumeration Documentation
enum affymetrix_calvin_parameter::ParameterNameValueType::ParameterType
Enumerant of the built-in parameter types.
Enumerator:
Int8Type
UInt8Type
an 8 bit integer.
Int16Type
an 8 bit unsigned integer.
UInt16Type
a 16 bit integer.
Int32Type
a 16 bit unsigned integer.
UInt32Type
a 32 bit integer.
FloatType
a 32 bit unsigned integer.
TextType
a 32 bit floating point.
AsciiType
a 16 bit character.
UnknownType
an 8 bit character.
an 8 bit integer.
Definition at line 183 of file ParameterNameValueType.h.
Constructor & Destructor Documentation
affymetrix_calvin_parameter::ParameterNameValueType::ParameterNameValueType () [inline]
Default constructor
Definition at line 113 of file ParameterNameValueType.h.
ParameterNameValueType::ParameterNameValueType (const std::wstring & name, const void * mimeValue, int32_t mimeValueSize, const std::wstring & mimeType)
MIME constructor. Useful when reading in from a file
Parameters:
name Parameter name
mimeValue MIME encoded value in a buffer
mimeValueSize The size in bytes of the MIME encoded value.
mimeType
Definition at line 136 of file ParameterNameValueType.cpp.
ParameterNameValueType::ParameterNameValueType (const std::wstring & name, const MIMEValue & mimeValue, const std::wstring & mimeType)
MIME constructor. Useful when reading in from a file
Parameters:
name Parameter name
mimeValue MIME encoded value
mimeType
Definition at line 144 of file ParameterNameValueType.cpp.
Member Function Documentation
std::wstring affymetrix_calvin_parameter::ParameterNameValueType::GetMIMEType () const [inline]
Returns the mime type without interpretation.
Returns:
String of the MIME type
Definition at line 305 of file ParameterNameValueType.h.
References Type.
Referenced by affymetrix_calvin_io::DataSetHeaderUpdater::UpdateParameter().
MIMEValue affymetrix_calvin_parameter::ParameterNameValueType::GetMIMEValue () const [inline]
Returns the mime value without interpretation.
Returns:
MIME encoded string.
Definition at line 315 of file ParameterNameValueType.h.
References Value.
Referenced by affymetrix_calvin_io::DataSetHeaderUpdater::UpdateParameter(), and affymetrix_calvin_io::GenericDataHeaderUpdater::UpdateParameters().
std::wstring affymetrix_calvin_parameter::ParameterNameValueType::GetName () const [inline]
Get the name of the parameter @ Name of the parameter
Definition at line 175 of file ParameterNameValueType.h.
References Name.
Referenced by affxchpwriter::CCHPFileWriter::AddAlgorithmParameter(), affymetrix_calvin_io::CHPTilingData::AddAlgParams(), affymetrix_calvin_io::CHPMultiDataData::AddAppMetaInfo(), affymetrix_calvin_io::CHPQuantificationDetectionData::AddSummaryParams(), AddUserAttributes(), Calvin::equivalentHeader(), affymetrix_calvin_io::CelFileData::FindAlgorithmParameter(), affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_io::CHPTilingData::GetAlgParams(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetAlgParams(), affymetrix_calvin_io::CHPQuantificationData::GetAlgParams(), affymetrix_calvin_io::CHPMultiDataData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetChipSums(), CProbeSetMultiDataGenotypeDataCOM::GetMetricName(), CProbeSetMultiDataExpressionDataCOM::GetMetricName(), CProbeSetMultiDataCytoRegionDataCOM::GetMetricName(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetricName(), CProbeSetMultiDataCopyNumberDataCOM::GetMetricName(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetSummaryParams(), affymetrix_calvin_io::CHPQuantificationData::GetSummaryParams(), affymetrix_calvin_io::CHPMultiDataData::GetSummaryParams(), affymetrix_calvin_io::CHPTilingData::GetTilingSequenceData(), Calvin::loadHeader(), CalvinToText::OutputParameters(), printParams(), and affymetrix_calvin_io::DataSetHeaderUpdater::UpdateParameter().
ParameterNameValueType::ParameterType ParameterNameValueType::GetParameterType () const
Get the parameter type
Returns:
The parameter type of the object.
Definition at line 152 of file ParameterNameValueType.cpp.
References Type, TypeTable, and UnknownType.
Referenced by CopyMetricToBuffer(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::DefaultToString(), Calvin::equivalentHeader(), affymetrix_calvin_io::CelFileData::GetDatHeader(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), Calvin::loadHeader(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::SetParameterType(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), affymetrix_calvin_io::DataSetHeaderUpdater::UpdateParameter(), affymetrix_calvin_io::GenericDataHeaderUpdater::UpdateParameters(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
std::string ParameterNameValueType::GetValueAscii () const
Gets value as a string
Returns:
Value of the parameter as an string
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a text type
Definition at line 296 of file ParameterNameValueType.cpp.
References AsciiMIMEType, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_parameter::MIMEValue::GetValue(), ToString(), Type, and Value.
Referenced by CopyMetricToBuffer(), Calvin::equivalentHeader(), affymetrix_calvin_io::DATData::GetArrayId(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), affymetrix_calvin_io::CDFData::GetRefSequence(), Calvin::loadHeader(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
float ParameterNameValueType::GetValueFloat () const
Gets value as a float
Returns:
Value of the parameter as an float
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a float
Definition at line 226 of file ParameterNameValueType.cpp.
References FloatMIMEType, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), ToString(), Type, and ValueToInt().
Referenced by CopyMetricToBuffer(), Calvin::equivalentHeader(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), affymetrix_calvin_io::DATData::GetPixelSize(), Calvin::loadHeader(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
int16_t ParameterNameValueType::GetValueInt16 () const
Gets value as a int16_t
Returns:
Value of the parameter as an int16_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not an int16_t
Definition at line 186 of file ParameterNameValueType.cpp.
References Int16MIMEType, and ValueToInt().
Referenced by CopyMetricToBuffer(), Calvin::equivalentHeader(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), Calvin::loadHeader(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
int32_t ParameterNameValueType::GetValueInt32 () const
Gets value as a int32_t
Returns:
Value of the parameter as an int32_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not an int32_t
Definition at line 206 of file ParameterNameValueType.cpp.
References Int32MIMEType, and ValueToInt().
Referenced by CopyMetricToBuffer(), Calvin::equivalentHeader(), affymetrix_calvin_io::DATData::GetInt32FromGenericHdr(), affymetrix_calvin_io::CHPTilingData::GetInt32FromGenericHdr(), affymetrix_calvin_io::CHPData::GetInt32FromGenericHdr(), affymetrix_calvin_io::CelFileData::GetInt32FromGenericHdrParameterList(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), Calvin::loadHeader(), affymetrix_calvin_io::GridControlFileReader::Read(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
int8_t ParameterNameValueType::GetValueInt8 () const
Gets value as a int8_t
Returns:
Value of the parameter as an int8_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not an int8_t
Definition at line 166 of file ParameterNameValueType.cpp.
References Int8MIMEType, and ValueToInt().
Referenced by CopyMetricToBuffer(), Calvin::equivalentHeader(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), Calvin::loadHeader(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
std::wstring ParameterNameValueType::GetValueText () const
Gets value as a wstring
Returns:
Value of the parameter as an wstring
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a text type
Definition at line 249 of file ParameterNameValueType.cpp.
References affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_parameter::MIMEValue::GetValue(), TextMIMEType, ToString(), Type, and Value.
Referenced by Calvin::equivalentHeader(), affymetrix_calvin_io::DATData::GetArrayBarcode(), affymetrix_calvin_io::CelFileData::GetDatHeader(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), affymetrix_calvin_io::CHPTilingData::GetTilingSequenceData(), affymetrix_calvin_io::DATData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPTilingData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPQuantificationData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPMultiDataData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CHPData::GetWStringFromGenericHdr(), affymetrix_calvin_io::CelFileData::GetWStringFromGenericHdr(), Calvin::loadHeader(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
u_int16_t ParameterNameValueType::GetValueUInt16 () const
Gets value as a u_int16_t
Returns:
Value of the parameter as an u_int16_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a u_int16_t
Definition at line 196 of file ParameterNameValueType.cpp.
References UInt16MIMEType, and ValueToInt().
Referenced by CopyMetricToBuffer(), Calvin::equivalentHeader(), affymetrix_calvin_io::CelFileData::GetDatHeader(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), Calvin::loadHeader(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
u_int32_t ParameterNameValueType::GetValueUInt32 () const
Gets value as a u_int32_t
Returns:
Value of the parameter as an u_int32_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a u_int32_t
Definition at line 216 of file ParameterNameValueType.cpp.
References UInt32MIMEType, and ValueToInt().
Referenced by CopyMetricToBuffer(), Calvin::equivalentHeader(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), affymetrix_calvin_io::CDFData::GetUInt32FromGenericHdr(), Calvin::loadHeader(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
u_int8_t ParameterNameValueType::GetValueUInt8 () const
Gets value as a u_int8_t
Returns:
Value of the parameter as an u_int8_t
Exceptions:
affymetrix_calvin_exceptions::ParameterMismatchException Parameter is not a u_int8_t
Definition at line 176 of file ParameterNameValueType.cpp.
References UInt8MIMEType, and ValueToInt().
Referenced by CopyMetricToBuffer(), Calvin::equivalentHeader(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), GetMetricBufferSize(), affymetrix_calvin_io::CelFileData::GetVersion(), Calvin::loadHeader(), ToString(), affymetrix_calvin_io::CalvinCHPMultiDataFileUpdater::UpdateMetrics(), and affymetrix_calvin_io::CHPMultiDataFileWriter::WriteMetrics().
void ParameterNameValueType::IntToValue (u_int32_t value, const wchar_t * type) [protected]
Converts an integer to a value.
Parameters:
value The integer representation.
type The string representation.
Definition at line 357 of file ParameterNameValueType.cpp.
References NUMBER_BUFFER_LEN, affymetrix_calvin_parameter::MIMEValue::SetValue(), Type, and Value.
Referenced by SetValueFloat(), SetValueInt16(), SetValueInt32(), SetValueInt8(), SetValueUInt16(), SetValueUInt32(), and SetValueUInt8().
bool affymetrix_calvin_parameter::ParameterNameValueType::operator!= (const std::wstring & name) const [inline]
An inequality operator. Compares the parameter name.
Parameters:
name A parameter name to compare.
Returns:
True if the parameter names are diffenent.
Definition at line 159 of file ParameterNameValueType.h.
References Name.
bool affymetrix_calvin_parameter::ParameterNameValueType::operator!= (const ParameterNameValueType & param) const [inline]
An inequality operator. Compares the parameter name.
Parameters:
param The parameter to compare.
Returns:
True if the parameter names are different.
Definition at line 147 of file ParameterNameValueType.h.
References Name.
bool affymetrix_calvin_parameter::ParameterNameValueType::operator< (const ParameterNameValueType & param) const [inline]
Less than comparison operator. Compares the parameter name.
Parameters:
param The parameter to compare.
Returns:
True if the target parameter name is lexically less than param.
Definition at line 165 of file ParameterNameValueType.h.
References Name.
ParameterNameValueType affymetrix_calvin_parameter::ParameterNameValueType::operator= (const ParameterNameValueType & param) [inline]
A copy operator.
Parameters:
param The parameter to copy.
Definition at line 135 of file ParameterNameValueType.h.
References Name, Type, and Value.
bool affymetrix_calvin_parameter::ParameterNameValueType::operator== (const ParameterNameValueType & param) const [inline]
An equality operator. Compares the parameter name.
Parameters:
param The parameter to compare.
Returns:
True if the parameter names are the same.
Definition at line 141 of file ParameterNameValueType.h.
References Name.
bool affymetrix_calvin_parameter::ParameterNameValueType::operator== (const std::wstring & name) const [inline]
An equality operator. Compares the parameter name.
Parameters:
name A parameter name to compare.
Returns:
True if the parameter names are the same.
Definition at line 153 of file ParameterNameValueType.h.
References Name.
bool affymetrix_calvin_parameter::ParameterNameValueType::operator> (const ParameterNameValueType & param) const [inline]
Greater than comparison operator. Compares the parameter name.
Parameters:
param The parameter to compare.
Returns:
True if the target parameter name is lexically greter than param.
Definition at line 170 of file ParameterNameValueType.h.
References Name.
void affymetrix_calvin_parameter::ParameterNameValueType::SetMIMEType (const std::wstring & value) [inline]
Sets the mime type without attempting to interpret it.
Parameters:
value
Definition at line 310 of file ParameterNameValueType.h.
References Type.
void affymetrix_calvin_parameter::ParameterNameValueType::SetMIMEValue (const MIMEValue & value) [inline]
Sets the mime value without attempting to interpret it.
Parameters:
value MIME encoded string.
Definition at line 320 of file ParameterNameValueType.h.
References Value.
void affymetrix_calvin_parameter::ParameterNameValueType::SetName (const std::wstring & value) [inline]
Set the name of the parameter.
Parameters:
value Name of the parameter.
Definition at line 180 of file ParameterNameValueType.h.
References Name.
Referenced by affxchpwriter::CCHPFileWriter::AddAlgorithmParameter(), affymetrix_calvin_io::CHPTilingData::AddAlgParams(), affymetrix_calvin_io::CHPMultiDataData::AddAppMetaInfo(), affymetrix_calvin_io::CHPQuantificationDetectionData::AddSummaryParams(), affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), CopyNumberResultWriter::CreateResultFile(), affymetrix_calvin_io::CelFileData::FindAlgorithmParameter(), affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_io::CHPData::GetAlgParam(), affymetrix_calvin_io::CHPTilingData::GetAlgParams(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetAlgParams(), affymetrix_calvin_io::CHPQuantificationData::GetAlgParams(), affymetrix_calvin_io::CHPMultiDataData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetChipSum(), affymetrix_calvin_io::CHPData::GetChipSums(), affymetrix_fusion_io::GCOSCELDataAdapter::GetParameters(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetSummaryParams(), affymetrix_calvin_io::CHPQuantificationData::GetSummaryParams(), affymetrix_calvin_io::CHPMultiDataData::GetSummaryParams(), affxsmd::SMDFileData::Read(), affymetrix_calvin_io::DATData::SetArrayBarcode(), affymetrix_calvin_io::DATData::SetArrayId(), CopyNumberResultWriter::SetChromosomeProbeSetIndexInformation(), affymetrix_calvin_io::CHPData::SetFloatToGenericHdr(), affymetrix_calvin_io::DATData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CHPTilingData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CHPData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CelFileData::SetInt32ToGenericHdrParameterList(), affymetrix_calvin_io::DATData::SetPixelSize(), affymetrix_calvin_io::CDFData::SetRefSequence(), affymetrix_calvin_io::CDFData::SetUInt32ToGenericHdr(), affymetrix_calvin_io::CelFileData::SetVersion(), affymetrix_calvin_io::DATData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPTilingData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPQuantificationData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPMultiDataData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPData::SetWStringToGenericHdr(), affymetrix_calvin_io::CelFileData::SetWStringToGenericHdr(), affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute(), and OutputMessageStream::Write().
void ParameterNameValueType::SetValueAscii (const std::string & value, int32_t reserve = -1)
Sets the value as a text type.
Parameters:
value String representation of the value.
reserve The total number of characters to reserve for the value. -1 indicates not to reserve any extra space.
Definition at line 317 of file ParameterNameValueType.cpp.
References AsciiMIMEType, affymetrix_calvin_parameter::MIMEValue::SetValue(), Type, and Value.
Referenced by affymetrix_calvin_io::DATData::SetArrayId(), and affymetrix_calvin_io::CDFData::SetRefSequence().
void ParameterNameValueType::SetValueFloat (float value)
Sets the value as a float
Parameters:
value
Definition at line 242 of file ParameterNameValueType.cpp.
References FloatMIMEType, IntToValue(), type_punned::v_float, and type_punned::v_int32.
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::characters(), affymetrix_calvin_io::SAXArrayHandlers::characters(), affymetrix_calvin_io::CHPData::SetFloatToGenericHdr(), affymetrix_calvin_io::DATData::SetPixelSize(), and affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute().
void ParameterNameValueType::SetValueInt16 (int16_t value)
Sets the value as an int16_t
Parameters:
value
Definition at line 191 of file ParameterNameValueType.cpp.
References Int16MIMEType, and IntToValue().
void ParameterNameValueType::SetValueInt32 (int32_t value)
Sets the value as an int32_t
Parameters:
value
Definition at line 211 of file ParameterNameValueType.cpp.
References Int32MIMEType, and IntToValue().
Referenced by affymetrix_calvin_io::SAXTemplateHandlers::characters(), affymetrix_calvin_io::SAXArrayHandlers::characters(), affymetrix_calvin_io::DATData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CHPTilingData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CHPData::SetInt32ToGenericHdr(), affymetrix_calvin_io::CelFileData::SetInt32ToGenericHdrParameterList(), affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute(), and OutputMessageStream::Write().
void ParameterNameValueType::SetValueInt8 (int8_t value)
Sets the value as an int8_t
Parameters:
value
Definition at line 171 of file ParameterNameValueType.cpp.
References Int8MIMEType, and IntToValue().
void ParameterNameValueType::SetValueText (const std::wstring & value, int32_t reserve = -1)
Sets the value as a text type.
Parameters:
value String representation of the value.
reserve The total number of characters to reserve for the value. -1 indicates not to reserve any extra space.
Definition at line 274 of file ParameterNameValueType.cpp.
References affymetrix_calvin_parameter::MIMEValue::SetValue(), TextMIMEType, Type, and Value.
Referenced by affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::SAXTemplateHandlers::characters(), affymetrix_calvin_io::SAXArrayHandlers::characters(), CopyNumberResultWriter::CreateResultFile(), affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_fusion_io::GCOSCELDataAdapter::GetParameters(), affxsmd::SMDFileData::Read(), affymetrix_calvin_io::DATData::SetArrayBarcode(), affymetrix_calvin_io::DATData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPTilingData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPQuantificationData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPMultiDataData::SetWStringToGenericHdr(), affymetrix_calvin_io::CHPData::SetWStringToGenericHdr(), affymetrix_calvin_io::CelFileData::SetWStringToGenericHdr(), and affymetrix_calvin_io::SAXTemplateHandlers::StoreUserAttribute().
void ParameterNameValueType::SetValueUInt16 (u_int16_t value)
Sets the value as a u_int16_t
Parameters:
value
Definition at line 201 of file ParameterNameValueType.cpp.
References IntToValue(), and UInt16MIMEType.
void ParameterNameValueType::SetValueUInt32 (u_int32_t value)
Sets the value as a u_int32_t
Parameters:
value
Definition at line 221 of file ParameterNameValueType.cpp.
References IntToValue(), and UInt32MIMEType.
Referenced by affymetrix_calvin_io::CDFData::SetUInt32ToGenericHdr().
void ParameterNameValueType::SetValueUInt8 (u_int8_t value)
Sets the value as a u_int8_t
Parameters:
value
Definition at line 181 of file ParameterNameValueType.cpp.
References IntToValue(), and UInt8MIMEType.
Referenced by affymetrix_calvin_io::CelFileData::SetVersion().
std::wstring ParameterNameValueType::ToString () const
Converts the value of known types to a string
Returns:
A string representation of the value
Definition at line 368 of file ParameterNameValueType.cpp.
References AsciiType, FloatType, FormatString1, GetParameterType(), GetValueAscii(), GetValueFloat(), GetValueInt16(), GetValueInt32(), GetValueInt8(), GetValueText(), GetValueUInt16(), GetValueUInt32(), GetValueUInt8(), Int16Type, Int32Type, Int8Type, TextType, UInt16Type, UInt32Type, and UInt8Type.
Referenced by AddUserAttributes(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::DefaultValueToInt(), CFusionTagValuePairTypeCOM::get_Value(), affymetrix_calvin_io::CelFileData::GetChannels(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueAscii(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueFloat(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueText(), GetValueAscii(), GetValueFloat(), GetValueText(), CalvinToText::OutputParameters(), printParams(), and ValueToInt().
u_int32_t ParameterNameValueType::ValueToInt (const wchar_t * mimeType) const [protected]
Converts a value to an integer.
Parameters:
mimeType The string representation.
Returns:
The integer representation.
Definition at line 339 of file ParameterNameValueType.cpp.
References affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_parameter::MIMEValue::GetValue(), ToString(), Type, and Value.
Referenced by GetValueFloat(), GetValueInt16(), GetValueInt32(), GetValueInt8(), GetValueUInt16(), GetValueUInt32(), and GetValueUInt8().
Member Data Documentation
std::wstring affymetrix_calvin_parameter::ParameterNameValueType::Name [protected]
The name of the parameter
Definition at line 342 of file ParameterNameValueType.h.
Referenced by GetName(), operator!=(), operator<(), operator=(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::operator=(), operator==(), operator>(), and SetName().
std::wstring affymetrix_calvin_parameter::ParameterNameValueType::Type [protected]
The MIME type of the parameter
Definition at line 345 of file ParameterNameValueType.h.
Referenced by affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::DefaultValueToInt(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueAscii(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueFloat(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::GetDefaultValueText(), GetMIMEType(), GetParameterType(), GetValueAscii(), GetValueFloat(), GetValueText(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::IntToDefaultValue(), IntToValue(), operator=(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::operator=(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::SetDefaultValueAscii(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::SetDefaultValueText(), SetMIMEType(), SetValueAscii(), SetValueText(), and ValueToInt().
MIMEValue affymetrix_calvin_parameter::ParameterNameValueType::Value [protected]
The MIME value of the parameter
Definition at line 348 of file ParameterNameValueType.h.
Referenced by GetMIMEValue(), GetValueAscii(), GetValueText(), IntToValue(), operator=(), affymetrix_calvin_parameter::ParameterNameValueDefaultRequiredType::operator=(), SetMIMEValue(), SetValueAscii(), SetValueText(), and ValueToInt().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parameter/src/ParameterNameValueType.h
C:/f112/affy/sdk/calvin_files/parameter/src/ParameterNameValueType.cpp