Affymetrix Fusion SDK: CFusionPSIFileCOM Class Reference
CFusionPSIFileCOM Class Reference
#include <FusionPSIFileCOM.h>
Public Member Functions
CFusionPSIFileCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
STDMETHOD() get_FileName (BSTR *pVal)
STDMETHOD() put_FileName (BSTR newVal)
STDMETHOD() get_ProbeSetCount (int *pVal)
STDMETHOD() GetProbeSetName (int index, BSTR *pVal)
STDMETHOD() GetProbePairs (int index, int *pVal)
STDMETHOD() Read (VARIANT_BOOL *pVal)
STDMETHOD() Exists (VARIANT_BOOL *pVal)
STDMETHOD() Clear ()
Private Attributes
affxpsi::CPSIFileData psi
Detailed Description
Definition at line 29 of file FusionPSIFileCOM.h.
Constructor & Destructor Documentation
CFusionPSIFileCOM::CFusionPSIFileCOM () [inline]
Definition at line 36 of file FusionPSIFileCOM.h.
Member Function Documentation
STDMETHODIMP CFusionPSIFileCOM::Clear (void)
Definition at line 86 of file FusionPSIFileCOM.cpp.
STDMETHODIMP CFusionPSIFileCOM::Exists (VARIANT_BOOL * pVal)
Definition at line 80 of file FusionPSIFileCOM.cpp.
HRESULT CFusionPSIFileCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionPSIFileCOM.h.
void CFusionPSIFileCOM::FinalRelease () [inline]
Definition at line 60 of file FusionPSIFileCOM.h.
STDMETHODIMP CFusionPSIFileCOM::get_FileName (BSTR * pVal)
Definition at line 44 of file FusionPSIFileCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CFusionPSIFileCOM::get_ProbeSetCount (int * pVal)
Definition at line 56 of file FusionPSIFileCOM.cpp.
STDMETHODIMP CFusionPSIFileCOM::GetProbePairs (int index, int * pVal)
Definition at line 68 of file FusionPSIFileCOM.cpp.
STDMETHODIMP CFusionPSIFileCOM::GetProbeSetName (int index, BSTR * pVal)
Definition at line 62 of file FusionPSIFileCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CFusionPSIFileCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 29 of file FusionPSIFileCOM.cpp.
STDMETHODIMP CFusionPSIFileCOM::put_FileName (BSTR newVal)
Definition at line 50 of file FusionPSIFileCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CFusionPSIFileCOM::Read (VARIANT_BOOL * pVal)
Definition at line 74 of file FusionPSIFileCOM.cpp.
Member Data Documentation
affxpsi::CPSIFileData CFusionPSIFileCOM::psi [private]
Definition at line 65 of file FusionPSIFileCOM.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionPSIFileCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionPSIFileCOM.cpp