Affymetrix Fusion SDK: SimpleBinaryFile Class Reference
SimpleBinaryFile Class Reference
#include <SimpleBinaryFile.h>
Public Member Functions
SimpleBinaryFile ()
~SimpleBinaryFile ()
bool CreateNewFile (const std::string &fileName)
void WriteHeader (int rows, int cols, const std::string &rowHeaderLabel, int rowHeaderLabelMaxLength, const std::vector< std::string > &colIds, const std::vector< std::string > &colNames)
void WriteRow (const std::string &rowLabel, const std::vector< float > &values)
void WriteRowLabel (const std::string &rowLabel)
void WriteData (float data)
bool Close ()
void UpdateRowCount (const std::string &fileName, int rows)
bool OpenFile (const std::string &fileName, int &rows, int &cols, std::string &rowHeaderLabel, std::vector< std::string > &colNames)
void ReadRow (int row, std::string &rowLabel, std::vector< float > &data)
Private Attributes
std::ofstream outFile
std::ifstream inFile
int rowHeaderLength
int dataStartPos
int rowSize
Detailed Description
Used to create a simple binary file storing a table of data.
Definition at line 35 of file SimpleBinaryFile.h.
Constructor & Destructor Documentation
SimpleBinaryFile::SimpleBinaryFile ()
Constructor
Definition at line 26 of file SimpleBinaryFile.cpp.
SimpleBinaryFile::~SimpleBinaryFile ()
Destructor
Definition at line 30 of file SimpleBinaryFile.cpp.
Member Function Documentation
bool SimpleBinaryFile::Close (void)
Close the file and check the status.
Definition at line 53 of file SimpleBinaryFile.cpp.
References inFile, and outFile.
bool SimpleBinaryFile::CreateNewFile (const std::string & fileName)
Create a new file.
Parameters:
fileName The file name.
Returns:
True if created.
Definition at line 34 of file SimpleBinaryFile.cpp.
References outFile.
bool SimpleBinaryFile::OpenFile (const std::string & fileName, int & rows, int & cols, std::string & rowHeaderLabel, std::vector< std::string > & colNames)
Open an existing file.
Parameters:
fileName The file name.
rows The number of rows
cols The number of columns of data (not including the row label.
rowHeaderLabel The label for the row header.
colNames The names of each column
Returns:
True if successful.
Definition at line 93 of file SimpleBinaryFile.cpp.
References dataStartPos, inFile, outFile, ReadInt32_N(), ReadString_N(), rowHeaderLength, and rowSize.
void SimpleBinaryFile::ReadRow (int row, std::string & rowLabel, std::vector< float > & data)
Read a row of data
Parameters:
row The row index
rowLabel The row label
data The data
Definition at line 110 of file SimpleBinaryFile.cpp.
References dataStartPos, inFile, ReadFixedString(), ReadFloat_N(), rowHeaderLength, and rowSize.
void SimpleBinaryFile::UpdateRowCount (const std::string & fileName, int rows)
Update the row count.
Parameters:
fileName The name of the file.
rows The row count.
Definition at line 85 of file SimpleBinaryFile.cpp.
References WriteInt32_N().
void SimpleBinaryFile::WriteData (float data)
Write a data point.
Parameters:
data The data to write.
Definition at line 80 of file SimpleBinaryFile.cpp.
References outFile, and WriteFloat_N().
void SimpleBinaryFile::WriteHeader (int rows, int cols, const std::string & rowHeaderLabel, int rowHeaderLabelMaxLength, const std::vector< std::string > & colIds, const std::vector< std::string > & colNames)
Write the header
Parameters:
rows The number of rows
cols The number of columns of data (not including the row label.
rowHeaderLabel The label for the row header.
rowHeaderLabelMaxLength The maximum length of the row header values
colIds A unique id for each column
colNames The names of each column
Definition at line 40 of file SimpleBinaryFile.cpp.
References outFile, rowHeaderLength, WriteInt32_N(), and WriteString_N().
void SimpleBinaryFile::WriteRow (const std::string & rowLabel, const std::vector< float > & values)
Write a row of data.
Parameters:
rowLabel The label for the row
values The column data
Definition at line 68 of file SimpleBinaryFile.cpp.
References outFile, WriteFloat_N(), and WriteRowLabel().
void SimpleBinaryFile::WriteRowLabel (const std::string & rowLabel)
Write a row label.
Parameters:
rowLabel The label for the row
Definition at line 75 of file SimpleBinaryFile.cpp.
References outFile, rowHeaderLength, and WriteFixedString().
Referenced by WriteRow().
Member Data Documentation
int SimpleBinaryFile::dataStartPos [private]
The position where the data starts.
Definition at line 113 of file SimpleBinaryFile.h.
Referenced by OpenFile(), and ReadRow().
std::ifstream SimpleBinaryFile::inFile [private]
The input stream.
Definition at line 107 of file SimpleBinaryFile.h.
Referenced by Close(), OpenFile(), and ReadRow().
std::ofstream SimpleBinaryFile::outFile [private]
The output stream.
Definition at line 104 of file SimpleBinaryFile.h.
Referenced by Close(), CreateNewFile(), OpenFile(), WriteData(), WriteHeader(), WriteRow(), and WriteRowLabel().
int SimpleBinaryFile::rowHeaderLength [private]
The length of the row headers.
Definition at line 110 of file SimpleBinaryFile.h.
Referenced by OpenFile(), ReadRow(), WriteHeader(), and WriteRowLabel().
int SimpleBinaryFile::rowSize [private]
The size of each row.
Definition at line 116 of file SimpleBinaryFile.h.
Referenced by OpenFile(), and ReadRow().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/SimpleBinaryFile.h
C:/f112/affy/sdk/file/SimpleBinaryFile.cpp