Affymetrix Fusion SDK: affymetrix_calvin_io::DataSetHeaderUpdater Class Reference
affymetrix_calvin_io::DataSetHeaderUpdater Class Reference
#include <DataSetHeaderUpdater.h>
Public Member Functions
DataSetHeaderUpdater (std::ofstream &fileStream, DataSetHeader &hdr)
~DataSetHeaderUpdater ()
bool UpdateParameter (affymetrix_calvin_parameter::ParameterNameValueType &nvt)
void UpdateNextDataSetPosition (u_int32_t position)
Private Member Functions
void SeekNextDataSetPosition ()
Private Attributes
std::ofstream * os
DataSetHeader * setHdr
u_int32_t filePos
Detailed Description
This class updates the data set header of an existing file with new information.
Definition at line 40 of file DataSetHeaderUpdater.h.
Constructor & Destructor Documentation
DataSetHeaderUpdater::DataSetHeaderUpdater (std::ofstream & fileStream, DataSetHeader & hdr)
Constructor
Definition at line 36 of file DataSetHeaderUpdater.cpp.
References affymetrix_calvin_io::DataSetHeader::GetHeaderStartFilePos(), affymetrix_calvin_io::DataSetHeader::GetName(), and WCHAR_T_SIZE.
DataSetHeaderUpdater::~DataSetHeaderUpdater ()
Destructor
Definition at line 52 of file DataSetHeaderUpdater.cpp.
Member Function Documentation
void DataSetHeaderUpdater::SeekNextDataSetPosition () [private]
Definition at line 93 of file DataSetHeaderUpdater.cpp.
void DataSetHeaderUpdater::UpdateNextDataSetPosition (u_int32_t position)
Definition at line 100 of file DataSetHeaderUpdater.cpp.
Referenced by affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), and affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader().
bool DataSetHeaderUpdater::UpdateParameter (affymetrix_calvin_parameter::ParameterNameValueType & nvt)
Update the parameter list. Can only update types that have the same name and type and value size in the source and target
Definition at line 59 of file DataSetHeaderUpdater.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::GetMIMEType(), affymetrix_calvin_parameter::ParameterNameValueType::GetMIMEValue(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::MIMEValue::GetValue(), affymetrix_calvin_parameter::MIMEValue::Size(), and WCHAR_T_SIZE.
Member Data Documentation
u_int32_t affymetrix_calvin_io::DataSetHeaderUpdater::filePos [private]
Definition at line 65 of file DataSetHeaderUpdater.h.
std::ofstream* affymetrix_calvin_io::DataSetHeaderUpdater::os [private]
Open output filestream
Definition at line 60 of file DataSetHeaderUpdater.h.
DataSetHeader* affymetrix_calvin_io::DataSetHeaderUpdater::setHdr [private]
The data set header
Definition at line 63 of file DataSetHeaderUpdater.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DataSetHeaderUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/DataSetHeaderUpdater.cpp