Affymetrix Fusion SDK: LogStream Class Reference
LogStream Class Reference
Log messages with timestamps.
#include <LogStream.h>
Public Member Functions
LogStream (int verbosity=3, std::ostream *out=NULL, bool profile=true)
~LogStream ()
void setStream (std::ostream *out)
void unsetStream (std::ostream *out)
virtual void message (int verbosity, const std::string &log, bool delimiter=true)
virtual void progressBegin (int verbosity, const std::string &msg, int total)
virtual void progressStep (int verbosity)
virtual void progressEnd (int verbosity, const std::string &msg)
void setBaseVerbosity (int verbosity)
Protected Member Functions
std::string profileString ()
Protected Attributes
int m_Verbosity
What level of messages is wanted, larger num == more msgs.
std::ostream * m_Out
Stream to print messages to.
bool m_Profile
Should we report profile info.
std::vector< time_t > m_ProgressTimeStart
Start times for progress segments.
std::vector< uint64_t > m_ProgressTotal
Number of times step is expected to be called.
Detailed Description
Log messages with timestamps.
Definition at line 44 of file LogStream.h.
Constructor & Destructor Documentation
LogStream::LogStream (int verbosity = 3, std::ostream * out = NULL, bool profile = true)
Constructor.
Definition at line 80 of file LogStream.cpp.
References m_Out, m_Profile, and printHeader().
LogStream::~LogStream ()
Definition at line 86 of file LogStream.cpp.
References m_ProgressTimeStart, and m_ProgressTotal.
Member Function Documentation
void LogStream::message (int verbosity, const std::string & log, bool delimiter = true) [virtual]
A message to be processed by the stream.
Parameters:
verbosity - What level of verbosity is associated with this message, higher number == more verbosity.
log - Message that is to be processed.
delimiter - Should a delimiter be emitted as well?
Implements MsgHandler.
Definition at line 107 of file LogStream.cpp.
References AffxTime::getCurrentTime(), AffxTime::getTimeStampString(), m_Out, m_Profile, and profileString().
std::string LogStream::profileString () [protected]
Definition at line 316 of file LogStream.cpp.
References Util::getMemFreeAtBlock(), Util::getMemFreeAtStart(), Util::memInfo(), and toMB().
Referenced by message(), progressBegin(), progressEnd(), and progressStep().
void LogStream::progressBegin (int verbosity, const std::string & msg, int total) [virtual]
Begin a progress reporting. After this initial call the progressStep call will be called N times where N = the parameter total passed in below.
Parameters:
verbosity - What level of verbosity is the progress associated with. Higher levels of verbosity produce more messages.
msg - String message associated with the beginning of this task.
total - Expected number of times that the progressStep() will be called after this.
Implements ProgressHandler.
Definition at line 133 of file LogStream.cpp.
References AffxTime::getCurrentTime(), AffxTime::getTimeStampString(), m_Out, m_Profile, m_ProgressTimeStart, m_ProgressTotal, and profileString().
void LogStream::progressEnd (int verbosity, const std::string & msg) [virtual]
Signals the end of progress report.
Parameters:
verbosity - Level of verbosity associated with this progress report.
msg - Closing message from calling function.
Implements ProgressHandler.
Definition at line 184 of file LogStream.cpp.
References AffxTime::getCurrentTime(), getDouble(), AffxTime::getTimeStampString(), m_Out, m_Profile, m_ProgressTimeStart, m_ProgressTotal, and profileString().
void LogStream::progressStep (int verbosity) [virtual]
This function is called when one unit of work has been done. In general it is expected that the units of work should be roughly equal in size.
Parameters:
verbosity - At what verbosity levell should this step be displayed.
Implements ProgressHandler.
Definition at line 162 of file LogStream.cpp.
References AffxTime::getCurrentTime(), AffxTime::getTimeStampString(), m_Out, m_Profile, and profileString().
void LogStream::setBaseVerbosity (int verbosity)
What level of verbosity is requested. We force lots of output here.
Parameters:
verbosity - Level below which progress messages are printed.
Reimplemented from MsgHandler.
Definition at line 232 of file LogStream.cpp.
void LogStream::setStream (std::ostream * out)
Definition at line 91 of file LogStream.cpp.
References m_Out, m_Profile, and printHeader().
Referenced by main(), and BaseEngine::openStandardLog().
void LogStream::unsetStream (std::ostream * out)
Definition at line 96 of file LogStream.cpp.
References m_Out.
Member Data Documentation
std::ostream* LogStream::m_Out [protected]
Stream to print messages to.
Definition at line 63 of file LogStream.h.
Referenced by LogStream(), message(), progressBegin(), progressEnd(), progressStep(), setStream(), and unsetStream().
bool LogStream::m_Profile [protected]
Should we report profile info.
Definition at line 64 of file LogStream.h.
Referenced by LogStream(), message(), progressBegin(), progressEnd(), progressStep(), and setStream().
std::vector<time_t> LogStream::m_ProgressTimeStart [protected]
Start times for progress segments.
Definition at line 65 of file LogStream.h.
Referenced by progressBegin(), progressEnd(), and ~LogStream().
std::vector<uint64_t> LogStream::m_ProgressTotal [protected]
Number of times step is expected to be called.
Definition at line 66 of file LogStream.h.
Referenced by progressBegin(), progressEnd(), and ~LogStream().
int LogStream::m_Verbosity [protected]
What level of messages is wanted, larger num == more msgs.
Reimplemented from MsgHandler.
Definition at line 62 of file LogStream.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/LogStream.h
C:/f112/affy/sdk/util/LogStream.cpp