Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPMultiDataAccessor Class Reference
affymetrix_fusion_io::FusionCHPMultiDataAccessor Class Reference
#include <FusionCHPMultiDataAccessor.h>
Public Member Functions
FusionCHPMultiDataAccessor ()
~FusionCHPMultiDataAccessor ()
bool Initialize (const std::vector< std::string > &chps)
void ExtractData (const std::vector< std::string > &snps, std::vector< std::vector< u_int8_t > > &calls, std::vector< std::vector< float > > &confidences)
Private Attributes
std::vector< std::string > chpFileNames
std::map< std::string, int > snpNameIndexMap
Detailed Description
This class provides a simple interface to extract SNP calls and confidence values from a multi data CHP file.
Definition at line 35 of file FusionCHPMultiDataAccessor.h.
Constructor & Destructor Documentation
FusionCHPMultiDataAccessor::FusionCHPMultiDataAccessor ()
Constructor
Definition at line 30 of file FusionCHPMultiDataAccessor.cpp.
FusionCHPMultiDataAccessor::~FusionCHPMultiDataAccessor ()
Destructor
Definition at line 34 of file FusionCHPMultiDataAccessor.cpp.
Member Function Documentation
void FusionCHPMultiDataAccessor::ExtractData (const std::vector< std::string > & snps, std::vector< std::vector< u_int8_t > > & calls, std::vector< std::vector< float > > & confidences)
Extract the calls and confidences for each input SNP.
Parameters:
snps The list of snps to extract data for.
calls A matrix to hold the calls.
confidences A matrix to hold the confidence values.
Definition at line 69 of file FusionCHPMultiDataAccessor.cpp.
References affymetrix_fusion_io::FusionCHPMultiDataData::FromBase(), affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoCall(), affymetrix_fusion_io::FusionCHPMultiDataData::GetGenoConfidence(), and affymetrix_fusion_io::FusionCHPDataReg::Read().
bool affymetrix_fusion_io::FusionCHPMultiDataAccessor::Initialize (const std::vector< std::string > & chps)
Initialize the map of SNP names to indicies.
Parameters:
chps The list of CHP files to extract data from.
Member Data Documentation
std::vector<std::string> affymetrix_fusion_io::FusionCHPMultiDataAccessor::chpFileNames [private]
The list of CHP file names to extract the data from.
Definition at line 39 of file FusionCHPMultiDataAccessor.h.
std::map<std::string, int> affymetrix_fusion_io::FusionCHPMultiDataAccessor::snpNameIndexMap [private]
A map of SNP name to CHP file index.
Definition at line 42 of file FusionCHPMultiDataAccessor.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPMultiDataAccessor.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPMultiDataAccessor.cpp