Affymetrix Fusion SDK: CFusionExpressionProbeSetResultsCOM Class Reference
CFusionExpressionProbeSetResultsCOM Class Reference
#include <FusionExpressionProbeSetResultsCOM.h>
Public Member Functions
CFusionExpressionProbeSetResultsCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_fusion_io::FusionExpressionProbeSetResults & Results ()
STDMETHOD() get_DetectionPValue (float *pVal)
STDMETHOD() get_Signal (float *pVal)
STDMETHOD() get_NumPairs (int *pVal)
STDMETHOD() get_NumUsedPairs (int *pVal)
STDMETHOD() get_Detection (CHAR *pVal)
STDMETHOD() get_HasCompResults (VARIANT_BOOL *pVal)
STDMETHOD() get_ChangePValue (float *pVal)
STDMETHOD() get_SignalLogRatio (float *pVal)
STDMETHOD() get_SignalLogRatioLow (float *pVal)
STDMETHOD() get_SignalLogRatioHigh (float *pVal)
STDMETHOD() get_NumCommonPairs (int *pVal)
STDMETHOD() get_Change (CHAR *pVal)
STDMETHOD() GetDetectionString (BSTR *pVal)
STDMETHOD() GetChangeString (BSTR *pVal)
Private Attributes
affymetrix_fusion_io::FusionExpressionProbeSetResults results
Detailed Description
Definition at line 29 of file FusionExpressionProbeSetResultsCOM.h.
Constructor & Destructor Documentation
CFusionExpressionProbeSetResultsCOM::CFusionExpressionProbeSetResultsCOM () [inline]
Definition at line 36 of file FusionExpressionProbeSetResultsCOM.h.
Member Function Documentation
HRESULT CFusionExpressionProbeSetResultsCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionExpressionProbeSetResultsCOM.h.
void CFusionExpressionProbeSetResultsCOM::FinalRelease () [inline]
Definition at line 60 of file FusionExpressionProbeSetResultsCOM.h.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_Change (CHAR * pVal)
Definition at line 108 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetChange(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_ChangePValue (float * pVal)
Definition at line 78 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetChangePValue(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_Detection (CHAR * pVal)
Definition at line 66 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetDetection(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_DetectionPValue (float * pVal)
Definition at line 42 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetDetectionPValue(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_HasCompResults (VARIANT_BOOL * pVal)
Definition at line 72 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::HasCompResults(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_NumCommonPairs (int * pVal)
Definition at line 102 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetNumCommonPairs(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_NumPairs (int * pVal)
Definition at line 54 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetNumPairs(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_NumUsedPairs (int * pVal)
Definition at line 60 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetNumUsedPairs(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_Signal (float * pVal)
Definition at line 48 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetSignal(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_SignalLogRatio (float * pVal)
Definition at line 84 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetSignalLogRatio(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_SignalLogRatioHigh (float * pVal)
Definition at line 96 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetSignalLogRatioHigh(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::get_SignalLogRatioLow (float * pVal)
Definition at line 90 of file FusionExpressionProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionExpressionProbeSetResults::GetSignalLogRatioLow(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::GetChangeString (BSTR * pVal)
Definition at line 120 of file FusionExpressionProbeSetResultsCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionExpressionProbeSetResults::GetChangeString(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::GetDetectionString (BSTR * pVal)
Definition at line 114 of file FusionExpressionProbeSetResultsCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionExpressionProbeSetResults::GetDetectionString(), and results.
STDMETHODIMP CFusionExpressionProbeSetResultsCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 27 of file FusionExpressionProbeSetResultsCOM.cpp.
affymetrix_fusion_io::FusionExpressionProbeSetResults& CFusionExpressionProbeSetResultsCOM::Results () [inline]
Definition at line 68 of file FusionExpressionProbeSetResultsCOM.h.
Referenced by CFusionCHPLegacyDataCOM::GetExpressionResults().
Member Data Documentation
affymetrix_fusion_io::FusionExpressionProbeSetResults CFusionExpressionProbeSetResultsCOM::results [private]
Definition at line 65 of file FusionExpressionProbeSetResultsCOM.h.
Referenced by get_Change(), get_ChangePValue(), get_Detection(), get_DetectionPValue(), get_HasCompResults(), get_NumCommonPairs(), get_NumPairs(), get_NumUsedPairs(), get_Signal(), get_SignalLogRatio(), get_SignalLogRatioHigh(), get_SignalLogRatioLow(), GetChangeString(), and GetDetectionString().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionExpressionProbeSetResultsCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionExpressionProbeSetResultsCOM.cpp