Affymetrix Fusion SDK: affymetrix_dttarray::DttArrayData Class Reference
affymetrix_dttarray::DttArrayData Class Reference
#include <DttArrayFileReader.h>
Public Member Functions
DttArrayData ()
~DttArrayData ()
std::string GetArrayType () const
void SetArrayType (std::string const &aType)
std::string GetExperimentName () const
void SetExperimentName (std::string const &name)
AttributeNameValueTypeList & Attributes ()
void Clear ()
Private Attributes
std::string arrayType
std::string expName
AttributeNameValueTypeList attributes
Detailed Description
This class provides storage of the DTT array file data.
Definition at line 63 of file DttArrayFileReader.h.
Constructor & Destructor Documentation
DttArrayData::DttArrayData ()
Constructor
Definition at line 37 of file DttArrayFileReader.cpp.
DttArrayData::~DttArrayData ()
Destructor
Definition at line 44 of file DttArrayFileReader.cpp.
References Clear().
Member Function Documentation
AttributeNameValueTypeList& affymetrix_dttarray::DttArrayData::Attributes () [inline]
Gets the attributes.
Returns:
The sample and experiemnt attributes.
Definition at line 105 of file DttArrayFileReader.h.
References attributes.
Referenced by affxsmd::SMDFileData::Read(), affymetrix_dttarray::SAXArrayHandlers::StoreNameValueAttributes(), affymetrix_dttarray::SAXArrayHandlers::StoreSampleNameAttribute(), affymetrix_dttarray::SAXArrayHandlers::StoreSampleProjectAttribute(), and affymetrix_dttarray::SAXArrayHandlers::StoreSampleTypeAttribute().
void DttArrayData::Clear (void)
Clears the members.
Definition at line 52 of file DttArrayFileReader.cpp.
References arrayType, attributes, and expName.
Referenced by affymetrix_dttarray::DttArrayFileReader::Read(), and ~DttArrayData().
std::string affymetrix_dttarray::DttArrayData::GetArrayType () const [inline]
Gets the probe array type name.
Returns:
The probe array type.
Definition at line 85 of file DttArrayFileReader.h.
References arrayType.
Referenced by affxsmd::SMDFileData::Read().
std::string affymetrix_dttarray::DttArrayData::GetExperimentName () const [inline]
Gets the experiemnt name.
Returns:
The experiment name.
Definition at line 95 of file DttArrayFileReader.h.
References expName.
void affymetrix_dttarray::DttArrayData::SetArrayType (std::string const & aType) [inline]
Sets the probe array type name.
Parameters:
aType The array type.
Definition at line 90 of file DttArrayFileReader.h.
References arrayType.
Referenced by affymetrix_dttarray::SAXArrayHandlers::StoreArrayType(), and affymetrix_dttarray::SAXArrayHandlers::StoreNameValueAttributes().
void affymetrix_dttarray::DttArrayData::SetExperimentName (std::string const & name) [inline]
Sets the experiment name.
Parameters:
name The experiment name.
Definition at line 100 of file DttArrayFileReader.h.
References expName.
Referenced by affymetrix_dttarray::SAXArrayHandlers::StoreExperimentNameAttribute().
Member Data Documentation
std::string affymetrix_dttarray::DttArrayData::arrayType [private]
The probe array type.
Definition at line 67 of file DttArrayFileReader.h.
Referenced by Clear(), GetArrayType(), and SetArrayType().
AttributeNameValueTypeList affymetrix_dttarray::DttArrayData::attributes [private]
The attributes.
Definition at line 73 of file DttArrayFileReader.h.
Referenced by Attributes(), and Clear().
std::string affymetrix_dttarray::DttArrayData::expName [private]
The experiment name.
Definition at line 70 of file DttArrayFileReader.h.
Referenced by Clear(), GetExperimentName(), and SetExperimentName().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/DttArrayFileReader.h
C:/f112/affy/sdk/file/DttArrayFileReader.cpp