Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCDFProbeSetInformation Class Reference
affymetrix_fusion_io::FusionCDFProbeSetInformation Class Reference
#include <FusionCDFData.h>
Public Member Functions
affxcdf::GeneChipProbeSetType GetProbeSetType ()
affxcdf::DirectionType GetDirection () const
int GetNumLists () const
int GetNumGroups () const
int GetNumCells () const
int GetNumCellsPerList () const
int GetProbeSetNumber () const
void GetGroupInformation (int index, FusionCDFProbeGroupInformation &info)
FusionCDFProbeSetInformation ()
~FusionCDFProbeSetInformation ()
Private Member Functions
void Initialize (int index, affxcdf::CCDFFileData *cdf)
void Initialize (int index, affymetrix_calvin_io::CDFData *cdf)
void Clear ()
Private Attributes
affxcdf::CCDFProbeSetInformation * gcosSet
affymetrix_calvin_io::CDFProbeSetInformation * calvinSet
Friends
class FusionCDFData
Detailed Description
This class provides storage for a probe set.
Definition at line 284 of file FusionCDFData.h.
Constructor & Destructor Documentation
FusionCDFProbeSetInformation::FusionCDFProbeSetInformation ()
Constructor
Definition at line 817 of file FusionCDFData.cpp.
FusionCDFProbeSetInformation::~FusionCDFProbeSetInformation ()
Destructor
Definition at line 826 of file FusionCDFData.cpp.
Member Function Documentation
void FusionCDFProbeSetInformation::Clear (void) [private]
Deallocates any used memory.
Definition at line 834 of file FusionCDFData.cpp.
Referenced by affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation().
affxcdf::DirectionType FusionCDFProbeSetInformation::GetDirection () const
Gets the probe sets direction.
Returns:
The probe sets direction.
Definition at line 922 of file FusionCDFData.cpp.
References AntiSenseDirection, EitherDirection, NoDirection, affymetrix_calvin_io::ProbeAntiSenseDirection, affymetrix_calvin_io::ProbeEitherDirection, affymetrix_calvin_io::ProbeNoDirection, affymetrix_calvin_io::ProbeSenseDirection, and SenseDirection.
void FusionCDFProbeSetInformation::GetGroupInformation (int index, FusionCDFProbeGroupInformation & info)
Gets a group object.
Parameters:
index The index to the group of interest.
info The returned group data.
Definition at line 1024 of file FusionCDFData.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::Clear(), and affymetrix_fusion_io::FusionCDFProbeGroupInformation::Initialize().
int FusionCDFProbeSetInformation::GetNumCells () const
The number of probes in the set.
Returns:
The number of probes in the set.
Definition at line 985 of file FusionCDFData.cpp.
int FusionCDFProbeSetInformation::GetNumCellsPerList () const
Gets the number of probes per list.
Returns:
The number of probes per list.
Definition at line 998 of file FusionCDFData.cpp.
int FusionCDFProbeSetInformation::GetNumGroups () const
The number of groups in the set.
Returns:
The number of groups in the set.
Definition at line 972 of file FusionCDFData.cpp.
int FusionCDFProbeSetInformation::GetNumLists () const
Gets the number of lists (atoms) in the group.
Returns:
The number of lists (atoms) in the group.
Definition at line 959 of file FusionCDFData.cpp.
int FusionCDFProbeSetInformation::GetProbeSetNumber () const
Gets the probe set number.
Returns:
The probe set number.
Definition at line 1011 of file FusionCDFData.cpp.
affxcdf::GeneChipProbeSetType FusionCDFProbeSetInformation::GetProbeSetType ()
Gets the probe set type.
Returns:
The probe set type.
Definition at line 865 of file FusionCDFData.cpp.
References CopyNumber, CopyNumberProbeSetType, Expression, ExpressionControl, ExpressionControlProbeSetType, ExpressionProbeSetType, GenotypeControl, GenotypeControlProbeSetType, affymetrix_calvin_io::Genotyping, GenotypingProbeSetType, affymetrix_calvin_io::Marker, MarkerProbeSetType, affymetrix_calvin_io::MultichannelMarker, affxcdf::MultichannelMarkerProbeSetType, affymetrix_calvin_io::Resequencing, ResequencingProbeSetType, affymetrix_calvin_io::Tag, TagProbeSetType, and UnknownProbeSetType.
void FusionCDFProbeSetInformation::Initialize (int index, affxcdf::CCDFFileData * cdf) [private]
Initializes the class for GCOS file reading.
Parameters:
index The index to the probe set.
cdf The GCOS CDF file object.
Definition at line 845 of file FusionCDFData.cpp.
References affxcdf::CCDFFileData::GetProbeSetInformation().
Referenced by affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation().
void FusionCDFProbeSetInformation::Initialize (int index, affymetrix_calvin_io::CDFData * cdf) [private]
Initializes the class for Calvin file reading.
Parameters:
index The index to the probe set.
cdf The Calvin CDF file object.
Definition at line 855 of file FusionCDFData.cpp.
References affymetrix_calvin_io::CDFData::GetProbeSetInformation().
Friends And Related Function Documentation
friend class FusionCDFData [friend]
Friend to the parent class.
Definition at line 309 of file FusionCDFData.h.
Member Data Documentation
affymetrix_calvin_io::CDFProbeSetInformation* affymetrix_fusion_io::FusionCDFProbeSetInformation::calvinSet [private]
The Calvin probe set object.
Definition at line 291 of file FusionCDFData.h.
affxcdf::CCDFProbeSetInformation* affymetrix_fusion_io::FusionCDFProbeSetInformation::gcosSet [private]
The GCOS probe set object.
Definition at line 288 of file FusionCDFData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCDFData.cpp