Affymetrix Fusion SDK: affymetrix_fusion_io::FusionCHPLegacyData Class Reference
affymetrix_fusion_io::FusionCHPLegacyData Class Reference
#include <FusionCHPLegacyData.h>
Classes
class Reg
Public Member Functions
~FusionCHPLegacyData ()
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()
affymetrix_calvin_io::GenericData * GetGenericData ()
affymetrix_calvin_utilities::AffymetrixGuidType GetObjectName ()
std::string GetProbeSetName (int index)
bool GetExpressionResults (int index, FusionExpressionProbeSetResults &result)
bool GetGenotypingResults (int index, FusionGenotypeProbeSetResults &result)
bool GetUniversalResults (int index, FusionUniversalProbeSetResults &result)
bool GetReseqResults (FusionResequencingResults &results)
void Clear ()
FusionCHPHeader & GetHeader ()
Static Public Member Functions
static FusionCHPLegacyData * FromBase (FusionCHPData *chip)
Private Member Functions
FusionCHPLegacyData ()
bool Open (bool bReadHeaderOnly=false)
void CheckAdapter () const
void CreateAdapter ()
void DeleteAdapter ()
bool Read ()
bool ReadHeader ()
Private Attributes
IFusionCHPDataAdapter * adapter
FusionCHPHeader header
Static Private Attributes
static Reg reg
Detailed Description
This class provides storage and reading capabilities for CHP files
Definition at line 177 of file FusionCHPLegacyData.h.
Constructor & Destructor Documentation
FusionCHPLegacyData::FusionCHPLegacyData () [private]
Constructor
Definition at line 251 of file FusionCHPLegacyData.cpp.
References adapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::Reg::MakeObject().
FusionCHPLegacyData::~FusionCHPLegacyData ()
Destructor
Definition at line 256 of file FusionCHPLegacyData.cpp.
References DeleteAdapter().
Member Function Documentation
void FusionCHPLegacyData::CheckAdapter () const [private]
Check the adapter and throw exception if not set
Exceptions:
FileNotOpenException
Definition at line 242 of file FusionCHPLegacyData.cpp.
References adapter, and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
Referenced by Clear(), FileId(), GetExpressionResults(), GetGenericData(), GetGenotypingResults(), GetHeader(), GetProbeSetName(), GetReseqResults(), and GetUniversalResults().
void FusionCHPLegacyData::Clear (void)
Deallocates any memory used by the class object
Definition at line 317 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::Clear().
Referenced by CFusionCHPLegacyDataCOM::Clear().
void FusionCHPLegacyData::CreateAdapter () [private]
Create the adapter.
Definition at line 324 of file FusionCHPLegacyData.cpp.
References affymetrix_fusion_io::FusionCHPHeader::adapter, adapter, affymetrix_fusion_io::IFusionCHPDataAdapter::CanReadFile(), affymetrix_fusion_io::FusionCHPHeader::Clear(), affymetrix_fusion_io::FusionCHPData::filename, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), header, and affymetrix_fusion_io::IFusionCHPDataAdapter::SetFileName().
Referenced by Read(), and ReadHeader().
void FusionCHPLegacyData::DeleteAdapter () [private]
Delete the adapter.
Definition at line 376 of file FusionCHPLegacyData.cpp.
References affymetrix_fusion_io::FusionCHPHeader::adapter, adapter, and header.
Referenced by ~FusionCHPLegacyData().
AffymetrixGuidType FusionCHPLegacyData::FileId () [virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 261 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::FileId().
Referenced by CFusionCHPLegacyDataCOM::get_FileId().
FusionCHPLegacyData * FusionCHPLegacyData::FromBase (FusionCHPData * chip) [static]
Converts the type to the legacy CHP type.
Parameters:
chip The pointer to the CHP data object.
Returns:
The legacy CHP data type or NULL if not compatible.
Definition at line 77 of file FusionCHPLegacyData.cpp.
References affymetrix_fusion_io::FusionCHPData::GetObjectName(), and ObjectName.
bool FusionCHPLegacyData::GetExpressionResults (int index, FusionExpressionProbeSetResults & result)
Returns the expression probe set result
Parameters:
index The index to the result object of interest.
result The expression result.
Returns:
True if the expression result was found.
Definition at line 279 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetExpressionResults().
Referenced by ExpressionLegacyExample(), and CFusionCHPLegacyDataCOM::GetExpressionResults().
GenericData * FusionCHPLegacyData::GetGenericData () [virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 267 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetGenericData().
bool FusionCHPLegacyData::GetGenotypingResults (int index, FusionGenotypeProbeSetResults & result)
Returns the genotyping probe set result
Parameters:
index The index to the result object of interest.
result The genotyping result.
Returns:
True if the genotyping result was found.
Definition at line 285 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetGenotypingResults().
Referenced by CFusionCHPLegacyDataCOM::GetGenotypingResults().
FusionCHPHeader & FusionCHPLegacyData::GetHeader ()
Gets the headre.
Definition at line 236 of file FusionCHPLegacyData.cpp.
References CheckAdapter(), and header.
Referenced by ExpressionLegacyExample(), CFusionCHPLegacyDataCOM::GetHeader(), and LegacyExample().
AffymetrixGuidType FusionCHPLegacyData::GetObjectName () [virtual]
Gets the class name.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 84 of file FusionCHPLegacyData.cpp.
References ObjectName.
std::string FusionCHPLegacyData::GetProbeSetName (int index)
Get the probe set name (only valid for Command Console "calvin" files of expression or genotype assay)
Parameters:
index The index to the result object of interest.
Returns:
The probe set name.
Definition at line 273 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetProbeSetName().
Referenced by CFusionCHPLegacyDataCOM::GetProbeSetName().
bool FusionCHPLegacyData::GetReseqResults (FusionResequencingResults & results)
Returns the resequencing results.
Parameters:
results The results.
Returns:
True if the reseq result was found.
Definition at line 297 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetResequencingResults().
Referenced by CFusionCHPLegacyDataCOM::GetReseqResults().
bool FusionCHPLegacyData::GetUniversalResults (int index, FusionUniversalProbeSetResults & result)
Returns the universal (tag array) probe set result
Parameters:
index The index to the result object of interest.
result The universal result.
Returns:
True if the universal result was found.
Definition at line 291 of file FusionCHPLegacyData.cpp.
References adapter, CheckAdapter(), and affymetrix_fusion_io::IFusionCHPDataAdapter::GetUniversalResults().
Referenced by CFusionCHPLegacyDataCOM::GetUniversalResults().
bool affymetrix_fusion_io::FusionCHPLegacyData::Open (bool bReadHeaderOnly = false) [private]
Opens the file for reading.
Parameters:
bReadHeaderOnly Flag to indicate if the header is to be read only.
Returns:
True if successful.
bool FusionCHPLegacyData::Read () [private, virtual]
Reads the CHP file.
Returns:
True if successful.
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 303 of file FusionCHPLegacyData.cpp.
References adapter, CreateAdapter(), affymetrix_fusion_io::FusionCHPData::filename, affymetrix_fusion_io::IFusionCHPDataAdapter::Read(), and affymetrix_fusion_io::IFusionCHPDataAdapter::SetFileName().
bool FusionCHPLegacyData::ReadHeader () [private, virtual]
Reads the header of the CHP file
Returns:
True if successful
Implements affymetrix_fusion_io::FusionCHPData.
Definition at line 310 of file FusionCHPLegacyData.cpp.
References adapter, CreateAdapter(), affymetrix_fusion_io::FusionCHPData::filename, affymetrix_fusion_io::IFusionCHPDataAdapter::ReadHeader(), and affymetrix_fusion_io::IFusionCHPDataAdapter::SetFileName().
Member Data Documentation
IFusionCHPDataAdapter* affymetrix_fusion_io::FusionCHPLegacyData::adapter [private]
The fusion CHP adapter.
Definition at line 269 of file FusionCHPLegacyData.h.
Referenced by CheckAdapter(), Clear(), CreateAdapter(), DeleteAdapter(), FileId(), FusionCHPLegacyData(), GetExpressionResults(), GetGenericData(), GetGenotypingResults(), GetProbeSetName(), GetReseqResults(), GetUniversalResults(), Read(), and ReadHeader().
FusionCHPHeader affymetrix_fusion_io::FusionCHPLegacyData::header [private]
The CHP header
Definition at line 272 of file FusionCHPLegacyData.h.
Referenced by CreateAdapter(), DeleteAdapter(), and GetHeader().
FusionCHPLegacyData::Reg FusionCHPLegacyData::reg [static, private]
The one and only registration object. This registers the class as a CHP reader.
Used to register the CHP reader.
Definition at line 288 of file FusionCHPLegacyData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPLegacyData.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPLegacyData.cpp