Affymetrix Fusion SDK: affymetrix_fusion_io::GCOSCHPDataAdapter Class Reference
affymetrix_fusion_io::GCOSCHPDataAdapter Class Reference
Data class for the GCOS CHP adapter.
#include <GCOSCHPDataAdapter.h>
Public Member Functions
GCOSCHPDataAdapter ()
Constructor.
virtual ~GCOSCHPDataAdapter ()
Destructor.
virtual IFusionCHPHeaderAdapter & GetHeader ()
Accessors to header.
virtual bool CanReadFile ()
Can this object read the file.
virtual std::string GetProbeSetName (int index)
virtual bool GetExpressionResults (int index, FusionExpressionProbeSetResults &result)
Returns the expression probe set result.
virtual bool GetGenotypingResults (int index, FusionGenotypeProbeSetResults &result)
Returns the genotyping probe set result.
virtual bool GetUniversalResults (int index, FusionUniversalProbeSetResults &result)
Returns the universal (tag array) probe set result.
virtual bool GetResequencingResults (FusionResequencingResults &results)
Gets resequencing results.
virtual bool Read ()
Functions to read file.
virtual bool ReadHeader ()
Reads the header of the CHP file.
virtual void SetFileName (const std::string &value)
Sets the file name.
virtual std::string GetFileName () const
Gets the file name.
virtual void Clear ()
Deallocates any memory used by the class object.
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()
affymetrix_calvin_io::GenericData * GetGenericData ()
Protected Attributes
affxchp::CCHPFileData gcosChp
GCOSCHPHeaderAdapter * header
Detailed Description
Data class for the GCOS CHP adapter.
Definition at line 158 of file GCOSCHPDataAdapter.h.
Constructor & Destructor Documentation
GCOSCHPDataAdapter::GCOSCHPDataAdapter ()
Constructor.
Definition at line 196 of file GCOSCHPDataAdapter.cpp.
References gcosChp, and header.
GCOSCHPDataAdapter::~GCOSCHPDataAdapter () [virtual]
Destructor.
Definition at line 204 of file GCOSCHPDataAdapter.cpp.
References affxchp::CCHPFileData::Clear(), gcosChp, and header.
Member Function Documentation
bool GCOSCHPDataAdapter::CanReadFile () [virtual]
Can this object read the file.
Returns:
If the cell file can be read.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 365 of file GCOSCHPDataAdapter.cpp.
References affxchp::CCHPFileData::Clear(), gcosChp, and affxchp::CCHPFileData::ReadHeader().
void GCOSCHPDataAdapter::Clear (void) [virtual]
Deallocates any memory used by the class object.
Deallocates any memory used by the class object
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 357 of file GCOSCHPDataAdapter.cpp.
References affxchp::CCHPFileData::Clear(), and gcosChp.
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_fusion_io::GCOSCHPDataAdapter::FileId () [inline, virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 235 of file GCOSCHPDataAdapter.h.
bool GCOSCHPDataAdapter::GetExpressionResults (int index, FusionExpressionProbeSetResults & result) [virtual]
Returns the expression probe set result.
Parameters:
index Index to the result object of interest.
result Expression result.
Returns:
True if the expression result was found.
Returns the expression probe set result
Parameters:
index The index to the result object of interest.
result The expression result.
Returns:
True if the expression result was found.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 223 of file GCOSCHPDataAdapter.cpp.
References affxchp::CExpressionProbeSetResults::Change, affxchp::CExpressionProbeSetResults::ChangePValue, affxchp::CExpressionProbeSetResults::Detection, affxchp::CExpressionProbeSetResults::DetectionPValue, gcosChp, affxchp::CCHPFileData::GetExpressionResults(), affxchp::CExpressionProbeSetResults::m_HasCompResults, affxchp::CExpressionProbeSetResults::NumCommonPairs, affxchp::CExpressionProbeSetResults::NumPairs, affxchp::CExpressionProbeSetResults::NumUsedPairs, affymetrix_fusion_io::FusionExpressionProbeSetResults::SetChange(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetChangePValue(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetDetection(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetDetectionPValue(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetHasCompResults(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetNumCommonPairs(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetNumPairs(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetNumUsedPairs(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetSignal(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetSignalLogRatio(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetSignalLogRatioHigh(), affymetrix_fusion_io::FusionExpressionProbeSetResults::SetSignalLogRatioLow(), affxchp::CExpressionProbeSetResults::Signal, affxchp::CExpressionProbeSetResults::SignalLogRatio, affxchp::CExpressionProbeSetResults::SignalLogRatioHigh, and affxchp::CExpressionProbeSetResults::SignalLogRatioLow.
std::string GCOSCHPDataAdapter::GetFileName () const [virtual]
Gets the file name.
Returns:
Full path to the CHP file.
Gets the file name.
Returns:
The full path to the CHP file.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 351 of file GCOSCHPDataAdapter.cpp.
References gcosChp, and affxchp::CCHPFileData::GetFileName().
affymetrix_calvin_io::GenericData* affymetrix_fusion_io::GCOSCHPDataAdapter::GetGenericData () [inline, virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 238 of file GCOSCHPDataAdapter.h.
bool GCOSCHPDataAdapter::GetGenotypingResults (int index, FusionGenotypeProbeSetResults & result) [virtual]
Returns the genotyping probe set result.
Parameters:
index Index to the result object of interest.
result Genotyping result.
Returns:
True if the genotyping result was found.
Returns the genotyping probe set result
Parameters:
index The index to the result object of interest.
result The genotyping result.
Returns:
True if the genotyping result was found.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 253 of file GCOSCHPDataAdapter.cpp.
References affxchp::CGenotypeProbeSetResults::AlleleCall, affxchp::CGenotypeProbeSetResults::Confidence, gcosChp, affxchp::CCHPFileData::GetGenotypingResults(), affxchp::CGenotypeProbeSetResults::pvalue_AA, affxchp::CGenotypeProbeSetResults::pvalue_AB, affxchp::CGenotypeProbeSetResults::pvalue_BB, affxchp::CGenotypeProbeSetResults::pvalue_NoCall, affxchp::CGenotypeProbeSetResults::RAS1, affxchp::CGenotypeProbeSetResults::RAS2, affymetrix_fusion_io::FusionGenotypeProbeSetResults::SetAlleleCall(), affymetrix_fusion_io::FusionGenotypeProbeSetResults::SetConfidence(), affymetrix_fusion_io::FusionGenotypeProbeSetResults::SetPValueAA(), affymetrix_fusion_io::FusionGenotypeProbeSetResults::SetPValueAB(), affymetrix_fusion_io::FusionGenotypeProbeSetResults::SetPValueBB(), affymetrix_fusion_io::FusionGenotypeProbeSetResults::SetPValueNoCall(), affymetrix_fusion_io::FusionGenotypeProbeSetResults::SetRAS1(), and affymetrix_fusion_io::FusionGenotypeProbeSetResults::SetRAS2().
IFusionCHPHeaderAdapter & GCOSCHPDataAdapter::GetHeader () [virtual]
Accessors to header.
Returns:
Header object
Accessors to header.
Returns:
The header data object
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 213 of file GCOSCHPDataAdapter.cpp.
References header.
virtual std::string affymetrix_fusion_io::GCOSCHPDataAdapter::GetProbeSetName (int index) [inline, virtual]
Get the probe set name (only valid for Command Console "calvin" files)
Parameters:
index The index to the result object of interest.
Returns:
The probe set name.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 180 of file GCOSCHPDataAdapter.h.
bool GCOSCHPDataAdapter::GetResequencingResults (FusionResequencingResults & results) [virtual]
Gets resequencing results.
Parameters:
results Hold the resequencing results.
Returns:
True if resequencing results were retrieved.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 290 of file GCOSCHPDataAdapter.cpp.
References affymetrix_fusion_io::FusionResequencingResults::AddCalledBase(), affymetrix_fusion_io::FusionResequencingResults::AddForceCall(), affymetrix_fusion_io::FusionResequencingResults::AddOrigCall(), affymetrix_fusion_io::FusionResequencingResults::AddScore(), affxchp::_BaseCallType::call, affxchp::_ForceCallType::call, gcosChp, affxchp::CResequencingResults::GetCalledBase(), affxchp::CResequencingResults::GetCalledBasesSize(), affxchp::CResequencingResults::GetForceCall(), affxchp::CResequencingResults::GetForceCallsSize(), affxchp::CResequencingResults::GetOrigCall(), affxchp::CResequencingResults::GetOrigCallsSize(), affxchp::CCHPFileData::GetResequencingResults(), affxchp::CResequencingResults::GetScore(), affxchp::CResequencingResults::GetScoresSize(), affxchp::_BaseCallType::position, affxchp::_ForceCallType::position, and affxchp::_ForceCallType::reason.
bool GCOSCHPDataAdapter::GetUniversalResults (int index, FusionUniversalProbeSetResults & result) [virtual]
Returns the universal (tag array) probe set result.
Parameters:
index Index to the result object of interest.
result Universal result.
Returns:
True if the universal result was found.
Returns the universal (tag array) probe set result
Parameters:
index The index to the result object of interest.
The universal result.
Returns:
True if the universal result was found.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 278 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CUniversalProbeSetResults::GetBackground(), affxchp::CCHPFileData::GetUniversalResults(), and affymetrix_fusion_io::FusionUniversalProbeSetResults::SetBackground().
bool GCOSCHPDataAdapter::Read () [virtual]
Functions to read file.
Returns:
True if the cell file was read.
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 327 of file GCOSCHPDataAdapter.cpp.
References gcosChp, and affxchp::CCHPFileData::Read().
bool GCOSCHPDataAdapter::ReadHeader () [virtual]
Reads the header of the CHP file.
Returns:
True if successful
Reads the header of the CHP file
Returns:
True if successful
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 335 of file GCOSCHPDataAdapter.cpp.
References gcosChp, and affxchp::CCHPFileData::ReadHeader().
void GCOSCHPDataAdapter::SetFileName (const std::string & value) [virtual]
Sets the file name.
Parameters:
value Full path to the CHP file
Sets the file name.
Parameters:
name The full path to the CHP file
Implements affymetrix_fusion_io::IFusionCHPDataAdapter.
Definition at line 343 of file GCOSCHPDataAdapter.cpp.
References gcosChp, and affxchp::CCHPFileData::SetFileName().
Member Data Documentation
affxchp::CCHPFileData affymetrix_fusion_io::GCOSCHPDataAdapter::gcosChp [protected]
The underlying data access object
Definition at line 242 of file GCOSCHPDataAdapter.h.
Referenced by CanReadFile(), Clear(), GCOSCHPDataAdapter(), GetExpressionResults(), GetFileName(), GetGenotypingResults(), GetResequencingResults(), GetUniversalResults(), Read(), ReadHeader(), SetFileName(), and ~GCOSCHPDataAdapter().
GCOSCHPHeaderAdapter* affymetrix_fusion_io::GCOSCHPDataAdapter::header [protected]
Header adapter
Definition at line 245 of file GCOSCHPDataAdapter.h.
Referenced by GCOSCHPDataAdapter(), GetHeader(), and ~GCOSCHPDataAdapter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/GCOSAdapter/GCOSCHPDataAdapter.h
C:/f112/affy/sdk/calvin_files/fusion/src/GCOSAdapter/GCOSCHPDataAdapter.cpp