Affymetrix Fusion SDK: affymetrix_calvin_io::GenericDataHeaderWriter Class Reference
affymetrix_calvin_io::GenericDataHeaderWriter Class Reference
#include <GenericDataHeaderWriter.h>
Public Member Functions
GenericDataHeaderWriter ()
~GenericDataHeaderWriter ()
void Write (std::ofstream &os, GenericDataHeader &g)
Private Member Functions
void WriteFileTypeId (std::ofstream &os, const GenericDataHeader &g) const
void WriteFileId (std::ofstream &os, const GenericDataHeader &g) const
void WriteFileCreationTime (std::ofstream &os, const GenericDataHeader &g) const
void WriteLocale (std::ofstream &os, const GenericDataHeader &g) const
void WriteNameValParamCnt (std::ofstream &os, const GenericDataHeader &dc) const
void WriteNameValParams (std::ofstream &os, GenericDataHeader &g)
void WriteParentHdrCnt (std::ofstream &os, const GenericDataHeader &dc) const
void WriteParentHdrs (std::ofstream &os, GenericDataHeader &g)
Detailed Description
Definition at line 36 of file GenericDataHeaderWriter.h.
Constructor & Destructor Documentation
affymetrix_calvin_io::GenericDataHeaderWriter::GenericDataHeaderWriter () [inline]
Definition at line 41 of file GenericDataHeaderWriter.h.
affymetrix_calvin_io::GenericDataHeaderWriter::~GenericDataHeaderWriter () [inline]
Definition at line 42 of file GenericDataHeaderWriter.h.
Member Function Documentation
void GenericDataHeaderWriter::Write (std::ofstream & os, GenericDataHeader & g)
Definition at line 28 of file GenericDataHeaderWriter.cpp.
References WriteFileCreationTime(), WriteFileId(), WriteFileTypeId(), WriteLocale(), WriteNameValParamCnt(), WriteNameValParams(), WriteParentHdrCnt(), and WriteParentHdrs().
Referenced by affymetrix_calvin_io::FileHeaderWriter::WriteGenericDataHdr(), and WriteParentHdrs().
void GenericDataHeaderWriter::WriteFileCreationTime (std::ofstream & os, const GenericDataHeader & g) const [private]
Definition at line 50 of file GenericDataHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetFileCreationTime(), and affymetrix_calvin_io::FileOutput::WriteString16().
Referenced by Write().
void GenericDataHeaderWriter::WriteFileId (std::ofstream & os, const GenericDataHeader & g) const [private]
Definition at line 45 of file GenericDataHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetFileId(), and affymetrix_calvin_io::FileOutput::WriteString8().
Referenced by Write().
void GenericDataHeaderWriter::WriteFileTypeId (std::ofstream & os, const GenericDataHeader & g) const [private]
Definition at line 40 of file GenericDataHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), and affymetrix_calvin_io::FileOutput::WriteString8().
Referenced by Write().
void GenericDataHeaderWriter::WriteLocale (std::ofstream & os, const GenericDataHeader & g) const [private]
Definition at line 55 of file GenericDataHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetLocale(), and affymetrix_calvin_io::FileOutput::WriteString16().
Referenced by Write().
void GenericDataHeaderWriter::WriteNameValParamCnt (std::ofstream & os, const GenericDataHeader & dc) const [private]
Definition at line 60 of file GenericDataHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetNameValParamCnt(), and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
void GenericDataHeaderWriter::WriteNameValParams (std::ofstream & os, GenericDataHeader & g) [private]
Definition at line 65 of file GenericDataHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), affymetrix_calvin_io::FileOutput::WriteBlob(), and affymetrix_calvin_io::FileOutput::WriteString16().
Referenced by Write().
void GenericDataHeaderWriter::WriteParentHdrCnt (std::ofstream & os, const GenericDataHeader & dc) const [private]
Definition at line 82 of file GenericDataHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetParentCnt(), and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
void GenericDataHeaderWriter::WriteParentHdrs (std::ofstream & os, GenericDataHeader & g) [private]
Definition at line 87 of file GenericDataHeaderWriter.cpp.
References affymetrix_calvin_io::GenericDataHeader::GetParentIterators(), and Write().
Referenced by Write().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/GenericDataHeaderWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/GenericDataHeaderWriter.cpp