Affymetrix Fusion SDK: CFusionCHPDataRegCOM Class Reference
CFusionCHPDataRegCOM Class Reference
#include <FusionCHPDataRegCOM.h>
Public Member Functions
CFusionCHPDataRegCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
STDMETHOD() Read (BSTR fileName, IFusionCHPData **pVal)
STDMETHOD() ReadHeader (BSTR fileName, IFusionCHPData **pVal)
Detailed Description
Definition at line 29 of file FusionCHPDataRegCOM.h.
Constructor & Destructor Documentation
CFusionCHPDataRegCOM::CFusionCHPDataRegCOM () [inline]
Definition at line 36 of file FusionCHPDataRegCOM.h.
Member Function Documentation
HRESULT CFusionCHPDataRegCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionCHPDataRegCOM.h.
void CFusionCHPDataRegCOM::FinalRelease () [inline]
Definition at line 60 of file FusionCHPDataRegCOM.h.
STDMETHODIMP CFusionCHPDataRegCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 32 of file FusionCHPDataRegCOM.cpp.
STDMETHODIMP CFusionCHPDataRegCOM::Read (BSTR fileName, IFusionCHPData ** pVal)
Definition at line 47 of file FusionCHPDataRegCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionCHPDataReg::Read(), and CFusionCHPDataCOM::SetChip().
STDMETHODIMP CFusionCHPDataRegCOM::ReadHeader (BSTR fileName, IFusionCHPData ** pVal)
Definition at line 63 of file FusionCHPDataRegCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionCHPDataReg::ReadHeader(), and CFusionCHPDataCOM::SetChip().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPDataRegCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPDataRegCOM.cpp