Affymetrix Fusion SDK: affymetrix_calvin_io::DataSetHeaderReader Class Reference
affymetrix_calvin_io::DataSetHeaderReader Class Reference
#include <DataSetHeaderReader.h>
Public Member Functions
DataSetHeaderReader ()
void ReadAllMinimumInfo (std::ifstream &fileStream, DataGroupHeader &dch, u_int32_t dataSetCnt)
void ReadAll (std::ifstream &fileStream, DataGroupHeader &dch, u_int32_t dataSetCnt)
u_int32_t ReadMinimumInfo (std::ifstream &fileStream, DataSetHeader &dsh)
u_int32_t Read (std::ifstream &fileStream, DataSetHeader &dsh)
Protected Member Functions
void ReadDataSetStartFilePos (std::ifstream &fileStream, DataSetHeader &dsh)
void ReadDataFilePos (std::ifstream &fileStream, DataSetHeader &dsh)
u_int32_t ReadNextDataSetFilePos (std::ifstream &fileStream, DataSetHeader &dsh)
void ReadName (std::ifstream &fileStream, DataSetHeader &dsh)
void ReadParameters (std::ifstream &fileStream, DataSetHeader &dsh)
void ReadColumns (std::ifstream &fileStream, DataSetHeader &dsh)
void ReadRowCount (std::ifstream &fileStream, DataSetHeader &dsh)
Detailed Description
This class reads the all DataSetHeader information associated with a DataGroup from a file.
Definition at line 44 of file DataSetHeaderReader.h.
Constructor & Destructor Documentation
DataSetHeaderReader::DataSetHeaderReader ()
Constructor
Definition at line 35 of file DataSetHeaderReader.cpp.
Member Function Documentation
u_int32_t DataSetHeaderReader::Read (std::ifstream & fileStream, DataSetHeader & dsh)
Reads the complete DataSetHeader information.
Parameters:
fileStream Open fstream positioned at the start of the DataSetHeader.
dsh Reference to the DataSetHeader object to fill.
Returns:
The file position of the next DataSet.
Definition at line 100 of file DataSetHeaderReader.cpp.
References ReadColumns(), ReadDataFilePos(), ReadDataSetStartFilePos(), ReadName(), ReadNextDataSetFilePos(), ReadParameters(), and ReadRowCount().
Referenced by ReadAll(), and affymetrix_calvin_io::GenericData::ReadFullDataSetHeader().
void DataSetHeaderReader::ReadAll (std::ifstream & fileStream, DataGroupHeader & dch, u_int32_t dataSetCnt)
Reads the complete DataSetHeader information for all DataSets associated with a DataGroup.
Parameters:
fileStream Open fstream positioned at the start of the first DataSetHeader in a DataGroup.
dch DataGroupHeader object to which to add the DataSetHeader information.
dataSetCnt Number of DataSets in the DataGroup.
Definition at line 65 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataGroupHeader::GetDataSetPos(), and Read().
Referenced by affymetrix_calvin_io::DataGroupHeaderReader::Read().
void DataSetHeaderReader::ReadAllMinimumInfo (std::ifstream & fileStream, DataGroupHeader & dch, u_int32_t dataSetCnt)
Reads the minimum DataSetHeader information for all DataSets associated with a DataGroup.
Parameters:
fileStream Open fstream positioned at the start of the first DataSetHeader in a DataGroup.
dch DataGroupHeader object to which to add the DataSetHeader information.
dataSetCnt Number of DataSets in the DataGroup.
Definition at line 43 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::DataGroupHeader::GetDataSetPos(), and ReadMinimumInfo().
Referenced by affymetrix_calvin_io::DataGroupHeaderReader::ReadMinimumInfo().
void DataSetHeaderReader::ReadColumns (std::ifstream & fileStream, DataSetHeader & dsh) [protected]
Read column information.
Parameters:
fileStream Open fstream positioned at the start of the DataSetHeader column count.
dsh Reference to the DataSetHeader object to fill.
Definition at line 172 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::DataSetHeader::AddColumn(), affymetrix_calvin_io::FileInput::ReadInt32(), ReadInt8(), affymetrix_calvin_io::FileInput::ReadString16(), and affymetrix_calvin_io::FileInput::ReadUInt32().
Referenced by Read().
void DataSetHeaderReader::ReadDataFilePos (std::ifstream & fileStream, DataSetHeader & dsh) [protected]
Read the file position to the start of the data.
Parameters:
fileStream Open fstream positioned at the start of the data file position.
dsh Reference to the DataSetHeader object to fill.
Definition at line 126 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt32(), and affymetrix_calvin_io::DataSetHeader::SetDataStartFilePos().
Referenced by Read(), and ReadMinimumInfo().
void DataSetHeaderReader::ReadDataSetStartFilePos (std::ifstream & fileStream, DataSetHeader & dsh) [protected]
Read the file position of the start of the DataSet.
Parameters:
fileStream Open fstream positioned at the start of the DataSetHeader.
dsh Reference to the DataSetHeader object to fill.
Definition at line 118 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::DataSetHeader::SetHeaderStartFilePos().
Referenced by Read(), and ReadMinimumInfo().
u_int32_t DataSetHeaderReader::ReadMinimumInfo (std::ifstream & fileStream, DataSetHeader & dsh)
Reads the minimum DataSetHeader information.
Parameters:
fileStream Open fstream positioned at the start of the DataSetHeader.
dsh Reference to the DataSetHeader object to fill.
Returns:
The file position of the next DataSet.
Definition at line 87 of file DataSetHeaderReader.cpp.
References ReadDataFilePos(), ReadDataSetStartFilePos(), ReadName(), and ReadNextDataSetFilePos().
Referenced by ReadAllMinimumInfo().
void DataSetHeaderReader::ReadName (std::ifstream & fileStream, DataSetHeader & dsh) [protected]
Read the DataSetHeader name.
Parameters:
fileStream Open fstream positioned at the start of the DataSetHeader name.
dsh Reference to the DataSetHeader object to fill.
Definition at line 144 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::FileInput::ReadString16(), and affymetrix_calvin_io::DataSetHeader::SetName().
Referenced by Read(), and ReadMinimumInfo().
u_int32_t DataSetHeaderReader::ReadNextDataSetFilePos (std::ifstream & fileStream, DataSetHeader & dsh) [protected]
Read the file position to the next DataSet.
Parameters:
fileStream Open fstream positioned at the start of the next DataSet file position.
dsh Reference to the DataSetHeader object to fill.
Returns:
The file position of the next data set.
Definition at line 134 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::FileInput::ReadUInt32(), and affymetrix_calvin_io::DataSetHeader::SetNextSetFilePos().
Referenced by Read(), and ReadMinimumInfo().
void DataSetHeaderReader::ReadParameters (std::ifstream & fileStream, DataSetHeader & dsh) [protected]
Read the parameter list (name-value-type).
Parameters:
fileStream Open fstream positioned at the start of the DataSetHeader parameter list count.
dsh Reference to the DataSetHeader object to fill.
Definition at line 153 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::DataSetHeader::AddNameValParam(), affymetrix_calvin_io::FileInput::ReadBlob(), affymetrix_calvin_io::FileInput::ReadString16(), and affymetrix_calvin_io::FileInput::ReadUInt32().
Referenced by Read().
void DataSetHeaderReader::ReadRowCount (std::ifstream & fileStream, DataSetHeader & dsh) [protected]
Read the number of rows.
Parameters:
fileStream Open fstream positioned at the start of the DataSetHeader row count.
dsh Reference to the DataSetHeader object to fill.
Definition at line 193 of file DataSetHeaderReader.cpp.
References affymetrix_calvin_io::FileInput::ReadInt32(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by Read().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/DataSetHeaderReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/DataSetHeaderReader.cpp