Affymetrix Fusion SDK: affxchpwriter::CCHPFileWriter Class Reference
affxchpwriter::CCHPFileWriter Class Reference
#include <CHPFileWriter.h>
Public Member Functions
CCHPFileWriter ()
~CCHPFileWriter ()
bool CreateNewFile ()
void InitializeForWriting (affxcdf::CCDFFileData &cdf, bool allocateMemory=true)
void InitializeForWriting (int numRows, int numCols, int numProbeSets, const char *chipType, affxcdf::GeneChipProbeSetType probeSetType, bool allocateMemory=true)
void SetParentCelFileName (const char *str)
void SetProgID (const char *str)
void SetAlgorithmName (const char *str)
void SetAlgorithmVersion (const char *str)
void AddAlgorithmParameter (const char *tag, const char *value)
void AddChipSummaryParameter (const char *tag, const char *value)
void SetExpressionEntry (int index, affxchp::CExpressionProbeSetResults *pEntry)
bool SaveExpressionEntry (affxchp::CExpressionProbeSetResults *pEntry)
void SetMappingEntry (int index, affxchp::CGenotypeProbeSetResults *pEntry)
bool SaveMappingEntry (affxchp::CGenotypeProbeSetResults *pEntry)
void SetUniversalEntry (int index, affxchp::CUniversalProbeSetResults *pEntry)
bool SaveUniversalEntry (affxchp::CUniversalProbeSetResults *pEntry)
void SetResequencingResults (affxchp::CResequencingResults *pResults)
bool Save ()
bool SaveHeader ()
bool Close ()
void AddBackgroundInfo (int nZones, float smoothFactor)
void AddBackgroundZone (int x, int y, float value)
Protected Attributes
std::ofstream m_NewChpFile
int m_ProbeSetIndex
Detailed Description
This class is used for writing CHP files.
Definition at line 52 of file CHPFileWriter.h.
Constructor & Destructor Documentation
CCHPFileWriter::CCHPFileWriter ()
Constructor
Definition at line 49 of file CHPFileWriter.cpp.
References m_ProbeSetIndex.
CCHPFileWriter::~CCHPFileWriter ()
Destructor
Definition at line 56 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::Clear().
Member Function Documentation
void CCHPFileWriter::AddAlgorithmParameter (const char * tag, const char * value)
Adds a parameter name/value pair to the list of algorithm parameters
Parameters:
tag The name of the parameter
value The value of the parameter
Definition at line 993 of file CELData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), ALGORITHM_PARAM_NAME_PREFIX, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
void CCHPFileWriter::AddBackgroundInfo (int nZones, float smoothFactor)
Initializes the object which stores the background zone information
Parameters:
nZones The number of zones
smoothFactor The smooth factor used by the background algorithm.
Definition at line 225 of file CHPFileWriter.cpp.
References affxchp::CCHPFileHeader::GetBackgroundZoneInfo(), affxchp::CCHPFileData::m_Header, affxchp::_BackgroundZoneInfo::number_zones, and affxchp::_BackgroundZoneInfo::smooth_factor.
void CCHPFileWriter::AddBackgroundZone (int x, int y, float value)
Adds a background zone to the list
Parameters:
x The central x coordinate of the background zone.
y The central y coordinate of the background zone.
value The background value for the zone.
Definition at line 233 of file CHPFileWriter.cpp.
References affxchp::_BackgroundZoneType::background, affxchp::_BackgroundZoneType::centerx, affxchp::_BackgroundZoneType::centery, affxchp::CCHPFileHeader::GetBackgroundZoneInfo(), affxchp::CCHPFileData::m_Header, and affxchp::_BackgroundZoneInfo::zones.
void CCHPFileWriter::AddChipSummaryParameter (const char * tag, const char * value)
Adds a parameter name/value pair to the list of summary parameters
Parameters:
tag The name of the parameter
value The value of the parameter
Definition at line 214 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::m_Header, affxchp::CCHPFileHeader::SummaryParameters(), _TagValuePairType::Tag, and _TagValuePairType::Value.
bool CCHPFileWriter::Close (void)
Closes the file.
Returns:
True if successful
Definition at line 518 of file CHPFileWriter.cpp.
References m_NewChpFile.
Referenced by Save().
bool CCHPFileWriter::CreateNewFile ()
Creates the new file (empty) given the file name.
Returns:
True if successful
Definition at line 63 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::m_FileName, m_NewChpFile, and affxchp::CCHPFileData::m_strError.
void CCHPFileWriter::InitializeForWriting (affxcdf::CCDFFileData & cdf, bool allocateMemory = true)
Allocates memory for the results objects and prepares the object for writing.
Parameters:
cdf The associated CDF file.
allocateMemory Allocates memory for the results.
Definition at line 78 of file CHPFileWriter.cpp.
References affxcdf::CCDFFileData::GetChipType(), affxcdf::CCDFFileData::GetHeader(), and affxcdf::CCDFFileData::GetProbeSetType().
void CCHPFileWriter::InitializeForWriting (int numRows, int numCols, int numProbeSets, const char * chipType, affxcdf::GeneChipProbeSetType probeSetType, bool allocateMemory = true)
Allocates memory for the results objects and prepares the object for writing.
Parameters:
numRows The number of rows of features on the array.
numCols The number of columns of features on the array.
numProbeSets The number of probe sets.
chipType The chip type or probe array type.
probeSetType The type of probe sets in the file.
allocateMemory Allocates memory for the results.
Definition at line 91 of file CHPFileWriter.cpp.
References Expression, affxcdf::ExpressionProbeSetType, affymetrix_calvin_io::Genotyping, affxcdf::GenotypingProbeSetType, affxchp::CCHPFileData::m_Header, m_ProbeSetIndex, affxchp::CCHPFileData::m_ProbeSetResults, affymetrix_calvin_io::Resequencing, affxcdf::ResequencingProbeSetType, affxchp::CCHPFileHeader::SetAssayType(), affxchp::CCHPFileHeader::SetChipType(), affxchp::CCHPFileHeader::SetCols(), affxchp::CCHPFileHeader::SetNumProbeSets(), affxchp::CCHPFileHeader::SetRows(), affxcdf::TagProbeSetType, and affxcdf::UnknownProbeSetType.
bool CCHPFileWriter::Save ()
Saves the results to the file.
Returns:
True if successful
Definition at line 431 of file CHPFileWriter.cpp.
References affxchp::_BaseCallType::call, affxchp::_ForceCallType::call, Close(), Expression, affymetrix_calvin_io::Genotyping, affxchp::CCHPFileHeader::GetAssayType(), affxchp::CResequencingResults::GetCalledBase(), affxchp::CResequencingResults::GetCalledBasesSize(), affxchp::CCHPFileData::GetExpressionResults(), affxchp::CResequencingResults::GetForceCall(), affxchp::CResequencingResults::GetForceCallsSize(), affxchp::CCHPFileData::GetGenotypingResults(), affxchp::CCHPFileHeader::GetNumProbeSets(), affxchp::CResequencingResults::GetOrigCall(), affxchp::CResequencingResults::GetOrigCallsSize(), affxchp::CResequencingResults::GetScore(), affxchp::CCHPFileData::GetUniversalResults(), affxchp::CCHPFileData::m_Header, m_NewChpFile, affxchp::CCHPFileData::m_ReseqResults, affxchp::_BaseCallType::position, affxchp::_ForceCallType::position, affxchp::_ForceCallType::reason, affymetrix_calvin_io::Resequencing, SaveExpressionEntry(), SaveHeader(), SaveMappingEntry(), SaveUniversalEntry(), WriteFloat_I(), WriteInt32_I(), WriteInt8(), and WriteUInt8().
bool CCHPFileWriter::SaveExpressionEntry (affxchp::CExpressionProbeSetResults * pEntry)
Saves the results to the file.
Parameters:
pEntry A pointer to the results.
Definition at line 339 of file CHPFileWriter.cpp.
References affxchp::CExpressionProbeSetResults::Change, affxchp::CExpressionProbeSetResults::ChangePValue, affxchp::CExpressionProbeSetResults::Detection, affxchp::CExpressionProbeSetResults::DetectionPValue, EXPRESSION_ABSOLUTE_STAT_ANALYSIS, EXPRESSION_COMPARISON_STAT_ANALYSIS, FLOAT_SIZE, affxchp::CExpressionProbeSetResults::m_HasCompResults, m_NewChpFile, m_ProbeSetIndex, affxchp::CExpressionProbeSetResults::NumCommonPairs, affxchp::CExpressionProbeSetResults::NumPairs, affxchp::CExpressionProbeSetResults::NumUsedPairs, affxchp::CExpressionProbeSetResults::Signal, affxchp::CExpressionProbeSetResults::SignalLogRatio, affxchp::CExpressionProbeSetResults::SignalLogRatioHigh, affxchp::CExpressionProbeSetResults::SignalLogRatioLow, UCHAR_SIZE, USHORT_SIZE, WriteFloat_I(), WriteInt32_I(), WriteUInt16_I(), and WriteUInt8().
Referenced by Save().
bool CCHPFileWriter::SaveHeader ()
Saves the results to the file.
Returns:
True if successful
Definition at line 275 of file CHPFileWriter.cpp.
References affxchp::CCHPFileHeader::AlgorithmParameters(), CHP_FILE_MAGIC_NUMBER, Expression, affymetrix_calvin_io::Genotyping, affxchp::CCHPFileHeader::GetAlgName(), affxchp::CCHPFileHeader::GetAlgVersion(), affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileHeader::GetBackgroundZoneInfo(), affxchp::CCHPFileHeader::GetChipType(), affxchp::CCHPFileHeader::GetCols(), affxchp::CCHPFileHeader::GetNumProbeSets(), affxchp::CCHPFileHeader::GetParentCellFile(), affxchp::CCHPFileHeader::GetProgID(), affxchp::CCHPFileHeader::GetRows(), affxchp::CCHPFileData::m_Header, m_NewChpFile, affxchp::CCHPFileData::m_strError, NON_RESEQ_CHP_FILE_VERSION_NUMBER, affxchp::_BackgroundZoneInfo::number_zones, RESEQ_CHP_FILE_VERSION_NUMBER, affymetrix_calvin_io::Resequencing, affxchp::_BackgroundZoneInfo::smooth_factor, affxchp::CCHPFileHeader::SummaryParameters(), WriteCString(), WriteFloat_I(), WriteInt32_I(), WriteUInt16_I(), and affxchp::_BackgroundZoneInfo::zones.
Referenced by Save().
bool CCHPFileWriter::SaveMappingEntry (affxchp::CGenotypeProbeSetResults * pEntry)
Saves the results to the file.
Parameters:
pEntry A pointer to the results.
Definition at line 380 of file CHPFileWriter.cpp.
References affxchp::CGenotypeProbeSetResults::AlleleCall, affxchp::CGenotypeProbeSetResults::Confidence, FLOAT_SIZE, m_NewChpFile, m_ProbeSetIndex, affxchp::CGenotypeProbeSetResults::pvalue_AA, affxchp::CGenotypeProbeSetResults::pvalue_AB, affxchp::CGenotypeProbeSetResults::pvalue_BB, affxchp::CGenotypeProbeSetResults::pvalue_NoCall, affxchp::CGenotypeProbeSetResults::RAS1, affxchp::CGenotypeProbeSetResults::RAS2, UCHAR_SIZE, WriteFloat_I(), WriteInt32_I(), and WriteUInt8().
Referenced by Save().
bool CCHPFileWriter::SaveUniversalEntry (affxchp::CUniversalProbeSetResults * pEntry)
Saves the results to the file.
Parameters:
pEntry A pointer to the results.
Definition at line 414 of file CHPFileWriter.cpp.
References FLOAT_SIZE, affxchp::CUniversalProbeSetResults::GetBackground(), m_NewChpFile, m_ProbeSetIndex, WriteFloat_I(), and WriteInt32_I().
Referenced by Save().
void CCHPFileWriter::SetAlgorithmName (const char * str)
Sets the algorithm name used to create the CHP file data.
Parameters:
str The name of the algorithm.
Definition at line 179 of file CHPFileWriter.cpp.
References Expression, affymetrix_calvin_io::Genotyping, affxchp::CCHPFileHeader::GetAssayType(), affxchp::CCHPFileData::m_Header, and affxchp::CCHPFileHeader::SetAlgName().
void CCHPFileWriter::SetAlgorithmVersion (const char * str)
Sets the algorithm version used to create the CHP file data.
Parameters:
str The algorithm version.
Definition at line 197 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::m_Header, and affxchp::CCHPFileHeader::SetAlgVersion().
void CCHPFileWriter::SetExpressionEntry (int index, affxchp::CExpressionProbeSetResults * pEntry)
Sets the expression probe set result
Parameters:
index The index to the probe set results
pEntry A pointer to the results
Definition at line 244 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::GetExpressionResults().
void CCHPFileWriter::SetMappingEntry (int index, affxchp::CGenotypeProbeSetResults * pEntry)
Sets the genotyping probe set result
Parameters:
index The index to the probe set results
pEntry A pointer to the results
Definition at line 252 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::GetGenotypingResults().
void CCHPFileWriter::SetParentCelFileName (const char * str)
Sets the parent CEL file name.
Parameters:
str The parent CEL file name (full path).
Definition at line 165 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::m_Header, and affxchp::CCHPFileHeader::SetParentCellFile().
void CCHPFileWriter::SetProgID (const char * str)
Sets the prog ID of the algorithm used to create the CHP file data.
Parameters:
str The prog ID.
Definition at line 172 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::m_Header, and affxchp::CCHPFileHeader::SetProgID().
void CCHPFileWriter::SetResequencingResults (affxchp::CResequencingResults * pResults)
Sets the resequencing results
Parameters:
pResults A pointer to the results
Definition at line 268 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::m_ReseqResults.
void CCHPFileWriter::SetUniversalEntry (int index, affxchp::CUniversalProbeSetResults * pEntry)
Sets the universal probe set result
Parameters:
index The index to the probe set results
pEntry A pointer to the results
Definition at line 260 of file CHPFileWriter.cpp.
References affxchp::CCHPFileData::GetUniversalResults().
Member Data Documentation
std::ofstream affxchpwriter::CCHPFileWriter::m_NewChpFile [protected]
The output file stream object
Definition at line 63 of file CHPFileWriter.h.
Referenced by Close(), CreateNewFile(), Save(), SaveExpressionEntry(), SaveHeader(), SaveMappingEntry(), and SaveUniversalEntry().
int affxchpwriter::CCHPFileWriter::m_ProbeSetIndex [protected]
A flag to indicate the first entry is being saved.
Definition at line 66 of file CHPFileWriter.h.
Referenced by CCHPFileWriter(), InitializeForWriting(), SaveExpressionEntry(), SaveMappingEntry(), and SaveUniversalEntry().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CHPFileWriter.h
C:/f112/affy/sdk/calvin_files/data/src/CELData.cpp
C:/f112/affy/sdk/file/CHPFileWriter.cpp