Affymetrix Fusion SDK: tsvJoin Class Reference
tsvJoin Class Reference
#include <TsvJoin.h>
Public Member Functions
tsvJoin (int argc, const char *argv[], const std::string &version)
Constructor.
~tsvJoin ()
void run ()
Private Member Functions
void clear ()
void beginOutput (void)
void openInputFiles (void)
void beginOutputHeader (void)
void writeHeadersFromFile (affx::TsvFile &tsv, const unsigned int idx, std::vector< std::string > &columnNames)
Write header lines copied from input file.
void writeColumnNames (void)
Write output column names.
void writeMatches (void)
void headerLine (const unsigned int i)
Private Attributes
const std::string & m_Version
PgOptions * m_Opts
Command line options.
std::string m_CommandLine
Command line as a string.
std::string m_Key
Key.
std::string m_Outfile
Output file name.
bool m_Prepend
Should filenames be prepended?
unsigned int m_FileCount
Number of input files.
std::vector< std::string > m_FileNames
Input file names.
std::ofstream m_Out
Output file stream.
affx::TsvFile m_StreamTsv
Stream mode input file tsv object.
std::vector< std::string > m_StreamColNames
Stream mode input file column names.
std::string m_StreamKeyValue
Stream mode input file key value for row.
std::vector< std::string > m_StreamData
Stream mode input file data values for row.
std::vector< affx::TsvFile * > m_IndexTsvs
Index mode input file tsv objects.
std::vector< std::string > m_IndexKeyValues
Index mode input file key values.
std::vector< std::vector
< std::string > > m_IndexColNames
Index mode input file column names.
std::vector< std::vector
< std::string > > m_IndexData
Index mode input file data values.
std::string m_ExecGuid
Execution guid.
const std::string m_CommentLine
Output section separator.
unsigned int m_StreamDataColCount
Number of data columns in stream file.
std::vector< unsigned int > m_IndexDataColCount
Number of data columns in index files.
Detailed Description
Definition at line 41 of file TsvJoin.h.
Constructor & Destructor Documentation
tsvJoin::tsvJoin (int argc, const char * argv[], const std::string & version)
Constructor.
Constructor.
Parameters:
argc Number of command line arguments.
argv Command line arguments.
version Version string.
argc Number of command line arguments.
argv Command line arguments.
version Version string.
Errors: throw exception to display help messages, if too few input files.
Definition at line 68 of file TsvJoin.cpp.
References define_tsvjoin_options(), Err::errAbort(), PgOptions::get(), PgOptions::getArg(), PgOptions::getArgCount(), PgOptions::getBool(), m_CommandLine, m_FileCount, m_FileNames, m_Key, m_Opts, m_Out, m_Outfile, m_Prepend, Fs::mustOpenToWrite(), PgOptions::parseArgv(), Err::setThrowStatus(), and PgOptions::usage().
tsvJoin::~tsvJoin ()
Destructor.
Definition at line 435 of file TsvJoin.cpp.
References clear().
Member Function Documentation
void tsvJoin::beginOutput (void) [private]
Begin output.
Definition at line 168 of file TsvJoin.cpp.
References affxutil::Guid::GenerateNewGuid(), m_CommandLine, m_ExecGuid, m_Version, and Verbose::out().
Referenced by run().
void tsvJoin::beginOutputHeader (void) [private]
Begin output file header.
Definition at line 285 of file TsvJoin.cpp.
References affxutil::Guid::GenerateNewGuid(), Util::getTimeStamp(), m_CommandLine, m_ExecGuid, m_Out, and m_Version.
Referenced by run().
void tsvJoin::clear () [private]
Clear data.
Definition at line 442 of file TsvJoin.cpp.
References m_IndexTsvs, and m_Opts.
Referenced by ~tsvJoin().
void tsvJoin::headerLine (const unsigned int i) [private]
Write first part of file related header line.
Parameters:
i File index.
Definition at line 452 of file TsvJoin.cpp.
References m_Out.
Referenced by writeHeadersFromFile().
void tsvJoin::openInputFiles (void) [private]
Open input files.
Errors: abort if a file could not be opened or if the key column name was not found.
Definition at line 182 of file TsvJoin.cpp.
References affx::TsvFile::bind(), affx::TsvFile::cidx2cname(), affx::TsvFile::defineIndex(), Err::errAbort(), affx::TsvFile::getColumnCount(), m_FileCount, m_FileNames, m_IndexColNames, m_IndexData, m_IndexDataColCount, m_IndexKeyValues, m_IndexTsvs, m_Key, affx::TsvFile::m_optAllowDataComment, m_StreamColNames, m_StreamData, m_StreamDataColCount, m_StreamKeyValue, m_StreamTsv, affx::TsvFile::open(), Verbose::out(), affx::TSV_INDEX_STRING, and affx::TSV_OK.
Referenced by run().
void tsvJoin::run (void)
Read, process data, write output.
Errors: abort if unable to read any input file.
Definition at line 140 of file TsvJoin.cpp.
References beginOutput(), beginOutputHeader(), m_CommentLine, m_FileCount, m_IndexColNames, m_IndexTsvs, m_Out, m_StreamColNames, m_StreamTsv, openInputFiles(), writeHeadersFromFile(), and writeMatches().
Referenced by main().
void tsvJoin::writeColumnNames (void) [private]
Write output column names.
Write column names.
Definition at line 332 of file TsvJoin.cpp.
References m_FileCount, m_FileNames, m_IndexColNames, m_Key, m_Out, m_Prepend, and m_StreamColNames.
Referenced by writeMatches().
void tsvJoin::writeHeadersFromFile (affx::TsvFile & tsv, const unsigned int idx, std::vector< std::string > & columnNames) [private]
Write header lines copied from input file.
Write header lines copied from input file.
Parameters:
tsv Tsv object for file.
idx File index.
columnNames Column names.
Definition at line 298 of file TsvJoin.cpp.
References headerLine(), affx::TsvFile::headersBegin(), affx::TsvFile::headersNext(), m_CommentLine, m_FileNames, m_Key, m_Out, and affx::TSV_OK.
Referenced by run().
void tsvJoin::writeMatches (void) [private]
Write matching lines.
Definition at line 369 of file TsvJoin.cpp.
References Err::errAbort(), affx::TsvFile::findBegin(), affx::TsvFile::findNext(), affx::TsvFile::findResultsCount(), m_FileCount, m_FileNames, m_IndexData, m_IndexDataColCount, m_IndexTsvs, m_Key, m_Out, m_StreamData, m_StreamDataColCount, m_StreamKeyValue, m_StreamTsv, affx::TsvFile::nextLevel(), Verbose::out(), affx::TSV_OK, affx::TSV_OP_EQ, and writeColumnNames().
Referenced by run().
Member Data Documentation
std::string tsvJoin::m_CommandLine [private]
Command line as a string.
Definition at line 107 of file TsvJoin.h.
Referenced by beginOutput(), beginOutputHeader(), and tsvJoin().
const std::string tsvJoin::m_CommentLine [private]
Output section separator.
Definition at line 139 of file TsvJoin.h.
Referenced by run(), and writeHeadersFromFile().
std::string tsvJoin::m_ExecGuid [private]
Execution guid.
Definition at line 137 of file TsvJoin.h.
Referenced by beginOutput(), and beginOutputHeader().
unsigned int tsvJoin::m_FileCount [private]
Number of input files.
Definition at line 115 of file TsvJoin.h.
Referenced by openInputFiles(), run(), tsvJoin(), writeColumnNames(), and writeMatches().
std::vector<std::string> tsvJoin::m_FileNames [private]
Input file names.
Definition at line 117 of file TsvJoin.h.
Referenced by openInputFiles(), tsvJoin(), writeColumnNames(), writeHeadersFromFile(), and writeMatches().
std::vector<std::vector<std::string> > tsvJoin::m_IndexColNames [private]
Index mode input file column names.
Definition at line 133 of file TsvJoin.h.
Referenced by openInputFiles(), run(), and writeColumnNames().
std::vector<std::vector<std::string> > tsvJoin::m_IndexData [private]
Index mode input file data values.
Definition at line 135 of file TsvJoin.h.
Referenced by openInputFiles(), and writeMatches().
std::vector<unsigned int> tsvJoin::m_IndexDataColCount [private]
Number of data columns in index files.
Definition at line 143 of file TsvJoin.h.
Referenced by openInputFiles(), and writeMatches().
std::vector<std::string> tsvJoin::m_IndexKeyValues [private]
Index mode input file key values.
Definition at line 131 of file TsvJoin.h.
Referenced by openInputFiles().
std::vector<affx::TsvFile*> tsvJoin::m_IndexTsvs [private]
Index mode input file tsv objects.
Definition at line 129 of file TsvJoin.h.
Referenced by clear(), openInputFiles(), run(), and writeMatches().
std::string tsvJoin::m_Key [private]
Key.
Definition at line 109 of file TsvJoin.h.
Referenced by openInputFiles(), tsvJoin(), writeColumnNames(), writeHeadersFromFile(), and writeMatches().
PgOptions* tsvJoin::m_Opts [private]
Command line options.
Definition at line 105 of file TsvJoin.h.
Referenced by clear(), and tsvJoin().
std::ofstream tsvJoin::m_Out [private]
Output file stream.
Definition at line 119 of file TsvJoin.h.
Referenced by beginOutputHeader(), headerLine(), run(), tsvJoin(), writeColumnNames(), writeHeadersFromFile(), and writeMatches().
std::string tsvJoin::m_Outfile [private]
Output file name.
Definition at line 111 of file TsvJoin.h.
Referenced by tsvJoin().
bool tsvJoin::m_Prepend [private]
Should filenames be prepended?
Definition at line 113 of file TsvJoin.h.
Referenced by tsvJoin(), and writeColumnNames().
std::vector<std::string> tsvJoin::m_StreamColNames [private]
Stream mode input file column names.
Definition at line 123 of file TsvJoin.h.
Referenced by openInputFiles(), run(), and writeColumnNames().
std::vector<std::string> tsvJoin::m_StreamData [private]
Stream mode input file data values for row.
Definition at line 127 of file TsvJoin.h.
Referenced by openInputFiles(), and writeMatches().
unsigned int tsvJoin::m_StreamDataColCount [private]
Number of data columns in stream file.
Definition at line 141 of file TsvJoin.h.
Referenced by openInputFiles(), and writeMatches().
std::string tsvJoin::m_StreamKeyValue [private]
Stream mode input file key value for row.
Definition at line 125 of file TsvJoin.h.
Referenced by openInputFiles(), and writeMatches().
affx::TsvFile tsvJoin::m_StreamTsv [private]
Stream mode input file tsv object.
Definition at line 121 of file TsvJoin.h.
Referenced by openInputFiles(), run(), and writeMatches().
const std::string& tsvJoin::m_Version [private]
private data Version string.
Definition at line 103 of file TsvJoin.h.
Referenced by beginOutput(), and beginOutputHeader().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/TsvJoin.h
C:/f112/affy/sdk/file/TsvFile/TsvJoin.cpp