Affymetrix Fusion SDK: affymetrix_calvin_io::DataSetHeaderAppend Class Reference
affymetrix_calvin_io::DataSetHeaderAppend Class Reference
#include <DataSetHeaderAppend.h>
Public Member Functions
void AddDataSetHeader (const std::string &file, const std::wstring &groupName, const std::list< DataSetHeaderInformation > &params)
Detailed Description
A class to provide functions to add a data set to an existing file.
Definition at line 45 of file DataSetHeaderAppend.h.
Member Function Documentation
void DataSetHeaderAppend::AddDataSetHeader (const std::string & file, const std::wstring & groupName, const std::list< DataSetHeaderInformation > & params)
Add a data set header to the file
Parameters:
file The name of the file.
params The parameters for the data set.
groupName The name of the data group.
setName The name of the data set.
Add a data set header to the file
Parameters:
file The name of the file.
groupName The name of the group for the data sets.
params A list of data set name/parameters.
Definition at line 86 of file DataSetHeaderAppend.cpp.
References affymetrix_calvin_io::FileHeader::AddDataGroupHdr(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::GenericData::Close(), ERR, affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::DataSetHeader::GetHeaderStartFilePos(), affymetrix_calvin_io::DataSetHeader::GetName(), affymetrix_calvin_io::DataGroupHeader::GetName(), affymetrix_calvin_io::DataGroupHeader::GetNextGroupPos(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::GenericFileReader::ReadHeader(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::GenericFileWriter::SeekFromEndPos(), affymetrix_calvin_io::DataGroupHeader::SetDataSetPos(), affymetrix_calvin_io::GenericFileReader::SetFilename(), affymetrix_calvin_io::DataGroupHeader::SetName(), affymetrix_calvin_io::DataSetHeader::SetName(), affymetrix_calvin_io::DataGroupHeader::SetNextGroupPos(), affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), VERBOSE, affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), and affymetrix_calvin_io::DataSetWriter::WriteHeader().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DataSetHeaderAppend.h
C:/f112/affy/sdk/calvin_files/writers/src/DataSetHeaderAppend.cpp