Affymetrix Fusion SDK: AffxTime Class Reference
AffxTime Class Reference
#include <AffxTime.h>
Public Member Functions
AffxTime ()
AffxTime (time_t time)
AffxTime (int nYear, int nMonth, int nDay, int nHour, int nMin, int nSec, int nDST=-1)
AffxTime (double dtSrc)
AffxTime (const AffxTime &timeSrc)
const AffxTime & operator= (const AffxTime &timeSrc)
void clear (void)
void empty (void)
bool isEmpty (void)
bool isClear (void)
double getDATE (void)
time_t getTime ()
int getYear () const
int getMonth () const
int getDay () const
int getHour () const
int getMinute () const
int getSecond () const
int getDayOfWeek () const
AffxTimeSpan operator- (AffxTime time)
AffxTime operator- (AffxTimeSpan timeSpan)
AffxTime operator+ (AffxTimeSpan timeSpan)
const AffxTime & operator+= (AffxTimeSpan timeSpan)
const AffxTime & operator-= (AffxTimeSpan timeSpan)
bool operator== (AffxTime time)
bool operator!= (AffxTime time)
bool operator< (AffxTime time)
bool operator> (AffxTime time)
bool operator<= (AffxTime time)
bool operator>= (AffxTime time)
AffxString format (char *pFormat)
AffxString formatGmt (char *pFormat)
AffxString getDateString (void)
AffxString getHourMinuteString (void)
AffxString getTimeStampString (void)
Static Public Member Functions
static AffxTime getCurrentTime ()
static AffxString getRuntime (AffxString strAction, double timeElapsed)
static void startTime ()
static AffxString getRuntime (AffxString strAction)
Static Public Attributes
static long m_lStartTime = 0
static long m_lStopTime = 0
Private Attributes
tm m_time
Detailed Description
Definition at line 79 of file AffxTime.h.
Constructor & Destructor Documentation
AffxTime::AffxTime ()
Definition at line 47 of file AffxTime.cpp.
References empty().
Referenced by operator+(), and operator-().
AffxTime::AffxTime (time_t time)
Definition at line 59 of file AffxTime.cpp.
References HALF_SECOND, m_time, MAX_DATE, MIN_DATE, and rgMonthDays.
AffxTime::AffxTime (int nYear, int nMonth, int nDay, int nHour, int nMin, int nSec, int nDST = -1)
Definition at line 191 of file AffxTime.cpp.
References Err::errAbort(), and m_time.
AffxTime::AffxTime (double dtSrc)
Definition at line 451 of file AffxTime.cpp.
References HALF_SECOND, m_time, MAX_DATE, MIN_DATE, and rgMonthDays.
AffxTime::AffxTime (const AffxTime & timeSrc)
Definition at line 50 of file AffxTime.cpp.
References m_time.
Member Function Documentation
void AffxTime::clear (void) [inline]
Definition at line 99 of file AffxTime.h.
References empty().
void AffxTime::empty (void)
Definition at line 358 of file AffxTime.cpp.
References m_time.
Referenced by AffxTime(), and clear().
AffxString AffxTime::format (char * pFormat)
AffxString AffxTime::formatGmt (char * pFormat)
AffxTime AffxTime::getCurrentTime () [static]
Definition at line 210 of file AffxTime.cpp.
References m_time.
Referenced by LogStream::message(), LogStream::progressBegin(), LogStream::progressEnd(), and LogStream::progressStep().
double AffxTime::getDATE (void)
Definition at line 395 of file AffxTime.cpp.
References getDay(), getHour(), getMinute(), getMonth(), getSecond(), getYear(), and rgMonthDays.
Referenced by isEmpty(), operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
AffxString AffxTime::getDateString (void)
Definition at line 605 of file AffxTime.cpp.
References getDay(), getMonth(), getYear(), and isEmpty().
int AffxTime::getDay () const [inline]
Definition at line 191 of file AffxTime.h.
References m_time.
Referenced by getDATE(), getDateString(), and getTimeStampString().
int AffxTime::getDayOfWeek () const [inline]
Definition at line 199 of file AffxTime.h.
References m_time.
int AffxTime::getHour () const [inline]
Definition at line 193 of file AffxTime.h.
References m_time.
Referenced by getDATE(), getHourMinuteString(), and getTimeStampString().
AffxString AffxTime::getHourMinuteString (void)
Definition at line 624 of file AffxTime.cpp.
References getHour(), getMinute(), and isEmpty().
int AffxTime::getMinute () const [inline]
Definition at line 195 of file AffxTime.h.
References m_time.
Referenced by getDATE(), getHourMinuteString(), and getTimeStampString().
int AffxTime::getMonth () const [inline]
Definition at line 189 of file AffxTime.h.
References m_time.
Referenced by getDATE(), getDateString(), and getTimeStampString().
AffxString AffxTime::getRuntime (AffxString strAction, double timeElapsed) [static]
Definition at line 234 of file AffxTime.cpp.
References AffxString::sprintf().
Referenced by getRuntime().
AffxString AffxTime::getRuntime (AffxString strAction) [static]
Definition at line 267 of file AffxTime.cpp.
References getRuntime(), m_lStartTime, m_lStopTime, and AffxString::sprintf().
int AffxTime::getSecond () const [inline]
Definition at line 197 of file AffxTime.h.
References m_time.
Referenced by getDATE(), and getTimeStampString().
time_t AffxTime::getTime ()
AffxString AffxTime::getTimeStampString (void)
Definition at line 583 of file AffxTime.cpp.
References getDay(), getHour(), getMinute(), getMonth(), getSecond(), getYear(), and isEmpty().
Referenced by LogStream::message(), LogStream::progressBegin(), LogStream::progressEnd(), and LogStream::progressStep().
int AffxTime::getYear () const [inline]
Definition at line 187 of file AffxTime.h.
References m_time.
Referenced by getDATE(), getDateString(), and getTimeStampString().
bool AffxTime::isClear (void) [inline]
Definition at line 102 of file AffxTime.h.
References isEmpty().
bool AffxTime::isEmpty (void) [inline]
Definition at line 101 of file AffxTime.h.
References getDATE().
Referenced by getDateString(), getHourMinuteString(), getTimeStampString(), and isClear().
bool AffxTime::operator!= (AffxTime time) [inline]
Definition at line 213 of file AffxTime.h.
References getDATE().
AffxTime AffxTime::operator+ (AffxTimeSpan timeSpan) [inline]
Definition at line 205 of file AffxTime.h.
References AffxTime(), AffxTimeSpan::getDATE(), and getDATE().
const AffxTime & AffxTime::operator+= (AffxTimeSpan timeSpan) [inline]
Definition at line 207 of file AffxTime.h.
References AffxTimeSpan::getDATE(), and getDATE().
AffxTimeSpan AffxTime::operator- (AffxTime time) [inline]
Definition at line 201 of file AffxTime.h.
References getDATE().
AffxTime AffxTime::operator- (AffxTimeSpan timeSpan) [inline]
Definition at line 203 of file AffxTime.h.
References AffxTime(), AffxTimeSpan::getDATE(), and getDATE().
const AffxTime & AffxTime::operator-= (AffxTimeSpan timeSpan) [inline]
Definition at line 209 of file AffxTime.h.
References AffxTimeSpan::getDATE(), and getDATE().
bool AffxTime::operator< (AffxTime time) [inline]
Definition at line 215 of file AffxTime.h.
References getDATE().
bool AffxTime::operator<= (AffxTime time) [inline]
Definition at line 219 of file AffxTime.h.
References getDATE().
const AffxTime & AffxTime::operator= (const AffxTime & timeSrc) [inline]
Definition at line 185 of file AffxTime.h.
References m_time.
bool AffxTime::operator== (AffxTime time) [inline]
Definition at line 211 of file AffxTime.h.
References getDATE().
bool AffxTime::operator> (AffxTime time) [inline]
Definition at line 217 of file AffxTime.h.
References getDATE().
bool AffxTime::operator>= (AffxTime time) [inline]
Definition at line 221 of file AffxTime.h.
References getDATE().
void AffxTime::startTime () [static]
Definition at line 258 of file AffxTime.cpp.
References m_lStartTime.
Member Data Documentation
long AffxTime::m_lStartTime = 0 [static]
Definition at line 87 of file AffxTime.h.
Referenced by getRuntime(), and startTime().
long AffxTime::m_lStopTime = 0 [static]
Definition at line 88 of file AffxTime.h.
Referenced by getRuntime().
tm AffxTime::m_time [private]
Definition at line 138 of file AffxTime.h.
Referenced by AffxTime(), empty(), getCurrentTime(), getDay(), getDayOfWeek(), getHour(), getMinute(), getMonth(), getSecond(), getYear(), and operator=().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/AffxTime.h
C:/f112/affy/sdk/util/AffxTime.cpp