Affymetrix Fusion SDK: affymetrix_dttarray::SAXArrayHandlers Class Reference
affymetrix_dttarray::SAXArrayHandlers Class Reference
#include <SAXDttArrayHandlers.h>
Public Member Functions
SAXArrayHandlers (DttArrayData *data)
~SAXArrayHandlers ()
void startDocument ()
void endDocument ()
void startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList &attributes)
void endElement (const XMLCh *const name)
Private Member Functions
void StoreExperimentNameAttribute (XERCES_CPP_NAMESPACE::AttributeList &attributes)
void StoreSampleNameAttribute (XERCES_CPP_NAMESPACE::AttributeList &attributes)
void StoreSampleTypeAttribute (XERCES_CPP_NAMESPACE::AttributeList &attributes)
void StoreSampleProjectAttribute (XERCES_CPP_NAMESPACE::AttributeList &attributes)
void StoreNameValueAttributes (XERCES_CPP_NAMESPACE::AttributeList &attributes)
void StoreArrayType (XERCES_CPP_NAMESPACE::AttributeList &attributes)
void MoveCurrentElementBack (const XMLCh *const name)
bool MoveCurrentElementForward (const XMLCh *const name)
Private Attributes
int levelsDeep
DttArrayData * arrayData
DttArrayFileElements currentElement
Detailed Description
This class provides the SAX handlers for reading calvin array files.
Definition at line 127 of file SAXDttArrayHandlers.h.
Constructor & Destructor Documentation
SAXArrayHandlers::SAXArrayHandlers (DttArrayData * data)
Constructor
Parameters:
data The array data.
Definition at line 68 of file SAXDttArrayHandlers.cpp.
SAXArrayHandlers::~SAXArrayHandlers ()
Destructor
Definition at line 78 of file SAXDttArrayHandlers.cpp.
Member Function Documentation
void SAXArrayHandlers::endDocument ()
Called at the end of the document
Definition at line 92 of file SAXDttArrayHandlers.cpp.
void SAXArrayHandlers::endElement (const XMLCh *const name)
Called at the end of each element.
Parameters:
name The name of the element.
Definition at line 99 of file SAXDttArrayHandlers.cpp.
References MoveCurrentElementBack().
void SAXArrayHandlers::MoveCurrentElementBack (const XMLCh *const name) [private]
Modifies the state machine given the end of an element.
Parameters:
name The name of the element.
Definition at line 107 of file SAXDttArrayHandlers.cpp.
References affymetrix_dttarray::ARRAY_DESIGN_ASSNLIST, ARRAY_DESIGN_ASSNLIST_ELEMENT, affymetrix_dttarray::ARRAY_DESIGN_PACKAGE, ARRAY_DESIGN_PACKAGE_ELEMENT, affymetrix_dttarray::BIOMATERIAL_ASSNLIST, BIOMATERIAL_ASSNLIST_ELEMENT, affymetrix_dttarray::BIOMATERIAL_PACKAGE, BIOMATERIAL_PACKAGE_ELEMENT, affymetrix_dttarray::BIOSOURCE, affymetrix_dttarray::BIOSOURCE_CHARACTERISTICS_ASSNLIST, affymetrix_dttarray::BIOSOURCE_CHARACTERISTICS_ASSNLIST_ONTOLOGY, BIOSOURCE_ELEMENT, affymetrix_dttarray::BIOSOURCE_MATERIALTYPE_ASSNLIST, affymetrix_dttarray::BIOSOURCE_MATERIALTYPE_ASSNLIST_ONTOLOGY, affymetrix_dttarray::BIOSOURCE_PROPERTYSETS_ASSNLIST, affymetrix_dttarray::BIOSOURCE_PROPERTYSETS_ASSNLIST_NAMEVALUETYPE, CHARACTERISTICS_ASSNLIST_ELEMENT, currentElement, affymetrix_dttarray::DTT_ARRAY_FILE, affymetrix_dttarray::EXPERIMENT, affymetrix_dttarray::EXPERIMENT_ASSNLIST, EXPERIMENT_ASSNLIST_ELEMENT, EXPERIMENT_ELEMENT, affymetrix_dttarray::EXPERIMENT_PACKAGE, EXPERIMENT_PACKAGE_ELEMENT, affymetrix_dttarray::EXPERIMENT_PROPERTYSETS_ASSNLIST, affymetrix_dttarray::EXPERIMENT_PROPERTYSETS_ASSNLIST_NAMEVALUETYPE, levelsDeep, MATERIAL_TYPE_ASSN_ELEMENT, NAME_VALUE_TYPE_ELEMENT, ONTOLOGY_ENTRY_ELEMENT, PHYSICAL_ARRAY_DESIGN_ELEMENT, and PROPERTYSETS_ASSNLIST_ELEMENT.
Referenced by endElement().
bool SAXArrayHandlers::MoveCurrentElementForward (const XMLCh *const name) [private]
Modifies the state machine given the start of an element.
Parameters:
name The name of the element.
Returns:
True is a valid element was found.
Definition at line 173 of file SAXDttArrayHandlers.cpp.
References affymetrix_dttarray::ARRAY_DESIGN_ASSNLIST, ARRAY_DESIGN_ASSNLIST_ELEMENT, affymetrix_dttarray::ARRAY_DESIGN_PACKAGE, ARRAY_DESIGN_PACKAGE_ELEMENT, affymetrix_dttarray::BIOMATERIAL_ASSNLIST, BIOMATERIAL_ASSNLIST_ELEMENT, affymetrix_dttarray::BIOMATERIAL_PACKAGE, BIOMATERIAL_PACKAGE_ELEMENT, affymetrix_dttarray::BIOSOURCE, affymetrix_dttarray::BIOSOURCE_CHARACTERISTICS_ASSNLIST, affymetrix_dttarray::BIOSOURCE_CHARACTERISTICS_ASSNLIST_ONTOLOGY, BIOSOURCE_ELEMENT, affymetrix_dttarray::BIOSOURCE_MATERIALTYPE_ASSNLIST, affymetrix_dttarray::BIOSOURCE_MATERIALTYPE_ASSNLIST_ONTOLOGY, affymetrix_dttarray::BIOSOURCE_PROPERTYSETS_ASSNLIST, affymetrix_dttarray::BIOSOURCE_PROPERTYSETS_ASSNLIST_NAMEVALUETYPE, CHARACTERISTICS_ASSNLIST_ELEMENT, currentElement, affymetrix_dttarray::EXPERIMENT, affymetrix_dttarray::EXPERIMENT_ASSNLIST, EXPERIMENT_ASSNLIST_ELEMENT, EXPERIMENT_ELEMENT, affymetrix_dttarray::EXPERIMENT_PACKAGE, EXPERIMENT_PACKAGE_ELEMENT, affymetrix_dttarray::EXPERIMENT_PROPERTYSETS_ASSNLIST, affymetrix_dttarray::EXPERIMENT_PROPERTYSETS_ASSNLIST_NAMEVALUETYPE, levelsDeep, MATERIAL_TYPE_ASSN_ELEMENT, NAME_VALUE_TYPE_ELEMENT, ONTOLOGY_ENTRY_ELEMENT, affymetrix_dttarray::PHYSICAL_ARRAY_DESIGN, PHYSICAL_ARRAY_DESIGN_ELEMENT, and PROPERTYSETS_ASSNLIST_ELEMENT.
void SAXArrayHandlers::startDocument ()
Called at the start of the document
Definition at line 85 of file SAXDttArrayHandlers.cpp.
void affymetrix_dttarray::SAXArrayHandlers::startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList & attributes)
Called at the start of each element.
Parameters:
name The name of the element.
attributes The attributes of the element.
void SAXArrayHandlers::StoreArrayType (XERCES_CPP_NAMESPACE::AttributeList & attributes) [private]
Stores the array type from the physical array design element.
Parameters:
attributes The name/value attributes.
Definition at line 286 of file SAXDttArrayHandlers.cpp.
References arrayData, NAME_ATTRIBUTE, affymetrix_dttarray::DttArrayData::SetArrayType(), and XMLChToString().
void SAXArrayHandlers::StoreExperimentNameAttribute (XERCES_CPP_NAMESPACE::AttributeList & attributes) [private]
Stores the experiment name attribute from the experiment element.
Parameters:
attributes The name/value attributes.
Definition at line 302 of file SAXDttArrayHandlers.cpp.
References arrayData, NAME_ATTRIBUTE, affymetrix_dttarray::DttArrayData::SetExperimentName(), and XMLChToString().
void SAXArrayHandlers::StoreNameValueAttributes (XERCES_CPP_NAMESPACE::AttributeList & attributes) [private]
Stores the attributes from a name value type element.
Parameters:
attributes The name/value attributes.
Definition at line 379 of file SAXDttArrayHandlers.cpp.
References arrayData, affymetrix_dttarray::DttArrayData::Attributes(), affymetrix_dttarray::_AttributeNameValueType::name, NAME_ATTRIBUTE, PROBE_ARRAY_TYPE_PARAMETER_NAME, affymetrix_dttarray::DttArrayData::SetArrayType(), affymetrix_dttarray::_AttributeNameValueType::type, TYPE_ATTRIBUTE, affymetrix_dttarray::_AttributeNameValueType::value, VALUE_ATTRIBUTE, and XMLChToString().
void SAXArrayHandlers::StoreSampleNameAttribute (XERCES_CPP_NAMESPACE::AttributeList & attributes) [private]
Stores the sample name attribute from the bio source element.
Parameters:
attributes The name/value attributes.
Definition at line 318 of file SAXDttArrayHandlers.cpp.
References arrayData, affymetrix_dttarray::DttArrayData::Attributes(), GCOS_SAMPLE_NAME_PARAMETER_NAME, affymetrix_dttarray::_AttributeNameValueType::name, NAME_ATTRIBUTE, STRING_TYPE, affymetrix_dttarray::_AttributeNameValueType::type, affymetrix_dttarray::_AttributeNameValueType::value, and XMLChToString().
void SAXArrayHandlers::StoreSampleProjectAttribute (XERCES_CPP_NAMESPACE::AttributeList & attributes) [private]
Stores the sample project attribute from the biosource/characteristics element.
Parameters:
attributes The name/value attributes.
Definition at line 358 of file SAXDttArrayHandlers.cpp.
References arrayData, affymetrix_dttarray::DttArrayData::Attributes(), GCOS_SAMPLE_PROJECT_PARAMETER_NAME, affymetrix_dttarray::_AttributeNameValueType::name, ONTOLOGY_VALUE_ATTRIBUTE, STRING_TYPE, affymetrix_dttarray::_AttributeNameValueType::type, affymetrix_dttarray::_AttributeNameValueType::value, and XMLChToString().
void SAXArrayHandlers::StoreSampleTypeAttribute (XERCES_CPP_NAMESPACE::AttributeList & attributes) [private]
Stores the sample type attribute from the biosource/materialtype element.
Parameters:
attributes The name/value attributes.
Definition at line 338 of file SAXDttArrayHandlers.cpp.
References arrayData, affymetrix_dttarray::DttArrayData::Attributes(), GCOS_SAMPLE_TYPE_PARAMETER_NAME, affymetrix_dttarray::_AttributeNameValueType::name, ONTOLOGY_VALUE_ATTRIBUTE, STRING_TYPE, affymetrix_dttarray::_AttributeNameValueType::type, affymetrix_dttarray::_AttributeNameValueType::value, and XMLChToString().
Member Data Documentation
DttArrayData* affymetrix_dttarray::SAXArrayHandlers::arrayData [private]
A pointer to the array object.
Definition at line 134 of file SAXDttArrayHandlers.h.
Referenced by StoreArrayType(), StoreExperimentNameAttribute(), StoreNameValueAttributes(), StoreSampleNameAttribute(), StoreSampleProjectAttribute(), and StoreSampleTypeAttribute().
DttArrayFileElements affymetrix_dttarray::SAXArrayHandlers::currentElement [private]
The parent element that is currently being processed.
Definition at line 137 of file SAXDttArrayHandlers.h.
Referenced by MoveCurrentElementBack(), and MoveCurrentElementForward().
int affymetrix_dttarray::SAXArrayHandlers::levelsDeep [private]
Used to determine the number of levels past the expected name/value type element.
Definition at line 131 of file SAXDttArrayHandlers.h.
Referenced by MoveCurrentElementBack(), and MoveCurrentElementForward().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/SAXDttArrayHandlers.h
C:/f112/affy/sdk/file/SAXDttArrayHandlers.cpp