Affymetrix Fusion SDK: OutputMessageStream Class Reference
OutputMessageStream Class Reference
#include <OutputMessageStream.h>
Public Member Functions
OutputMessageStream (int level, std::ostream *strm=&std::cout)
void Write (int level, const std::string &msg)
Private Attributes
std::ostream * outstr
Detailed Description
Provides a base class definition for streaming back messages to the parent process.
Definition at line 32 of file OutputMessageStream.h.
Constructor & Destructor Documentation
OutputMessageStream::OutputMessageStream (int level, std::ostream * strm = &std::cout)
Construct a class with the type of output.
Parameters:
level - level of verbosity desired.
strm The output stream.
Definition at line 30 of file OutputMessageStream.cpp.
Member Function Documentation
void OutputMessageStream::Write (int level, const std::string & msg) [virtual]
Send a message.
Parameters:
level - level of verbosity desired.
msg The message to send.
Implements MessageStream.
Definition at line 51 of file GridControlFileWriter.cpp.
References affymetrix_calvin_io::FileHeader::AddDataGroupHdr(), affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_io::DataSetHeader::AddUShortColumn(), affymetrix_calvin_io::DataSetHeader::Clear(), affymetrix_calvin_io::DataGroupWriter::Close(), affymetrix_grid_control::GridControlData::GetB1(), affymetrix_grid_control::GridControlData::GetB2(), affymetrix_grid_control::GridControlData::GetColumns(), affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_grid_control::GridControlData::GetNS(), affymetrix_grid_control::GridControlData::GetNumB1Probes(), affymetrix_grid_control::GridControlData::GetNumB2Probes(), affymetrix_grid_control::GridControlData::GetNumNSProbes(), affymetrix_grid_control::GridControlData::GetRows(), GRD_COLUMNS_PARAMETER_NAME, GRD_FILE_B1_SET_NAME, GRD_FILE_B2_SET_NAME, GRD_FILE_COORDINATE_GROUP_NAME, GRD_FILE_NS_SET_NAME, GRD_FILE_TYPE_IDENTIFIER, GRD_ROWS_PARAMETER_NAME, affymetrix_calvin_io::GenericDataHeader::SetFileId(), affymetrix_calvin_io::FileHeader::SetFilename(), affymetrix_calvin_io::GenericDataHeader::SetFileTypeId(), affymetrix_calvin_io::DataSetHeader::SetName(), affymetrix_calvin_io::DataGroupHeader::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_io::DataSetHeader::SetRowCnt(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), affymetrix_calvin_io::DataSetWriter::Write(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), affymetrix_grid_control::_FeatureCoordinate::x, and affymetrix_grid_control::_FeatureCoordinate::y.
Member Data Documentation
std::ostream* OutputMessageStream::outstr [private]
Where to stream the messages.
Definition at line 36 of file OutputMessageStream.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/OutputMessageStream.h
C:/f112/affy/sdk/calvin_files/writers/src/GridControlFileWriter.cpp
C:/f112/affy/sdk/util/OutputMessageStream.cpp