Affymetrix Fusion SDK: affymetrix_calvin_io::FileHeader Class Reference
affymetrix_calvin_io::FileHeader Class Reference
#include <FileHeader.h>
Public Member Functions
FileHeader ()
~FileHeader ()
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename () const
u_int8_t GetMagicNumber () const
u_int8_t GetVersion () const
int32_t GetDataGroupCnt () const
void AddDataGroupHdr (const DataGroupHeader &p)
DataGroupHeader & GetDataGroup (int32_t index)
const DataGroupHeader & GetDataGroupConst (int32_t index) const
void GetDataGroupIts (DataGroupHdrIt &begin, DataGroupHdrIt &end)
void SetGenericDataHdr (const GenericDataHeader &p)
GenericDataHeader * GetGenericDataHdr ()
DataGroupHeader * FindDataGroupHeader (const std::wstring &name)
int32_t GetNumDataGroups () const
void SetNumDataGroups (int32_t value)
u_int32_t GetFirstDataGroupFilePos ()
void SetFirstDataGroupFilePos (u_int32_t value)
Private Attributes
std::string filename
u_int8_t magic
u_int8_t version
DataGroupHdrVector dataGroupHdrs
GenericDataHeader genericHdr
int32_t numDataGroups
u_int32_t firstDataGroupFilePos
Detailed Description
This class defines a data container for the generic file header
Definition at line 48 of file FileHeader.h.
Constructor & Destructor Documentation
FileHeader::FileHeader ()
Definition at line 26 of file FileHeader.cpp.
References affymetrix_calvin_io::CALVINIOVERSION, magic, affymetrix_calvin_io::MAGIC_NUM, and version.
affymetrix_calvin_io::FileHeader::~FileHeader () [inline]
Definition at line 53 of file FileHeader.h.
References Clear().
Member Function Documentation
void FileHeader::AddDataGroupHdr (const DataGroupHeader & p)
Definition at line 60 of file FileHeader.cpp.
References dataGroupHdrs.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::FileHeaderUpdater::AppendDataGroupHeader(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyHeaders(), affymetrix_calvin_io::DataGroupHeaderReader::ReadAll(), affymetrix_calvin_io::DataGroupHeaderReader::ReadAllMinimumInfo(), and OutputMessageStream::Write().
void FileHeader::Clear ()
Definition at line 32 of file FileHeader.cpp.
References affymetrix_calvin_io::GenericDataHeader::Clear(), dataGroupHdrs, firstDataGroupFilePos, genericHdr, and numDataGroups.
Referenced by affymetrix_calvin_io::GenericData::Clear(), and ~FileHeader().
DataGroupHeader * FileHeader::FindDataGroupHeader (const std::wstring & name)
Finds a DataGroupHeader by name.
Parameters:
name The name of the DataGroup
Returns:
A pointer to the DataGroupHeader. If not found, the return is 0.
Definition at line 99 of file FileHeader.cpp.
References GetDataGroupIts().
Referenced by affymetrix_calvin_io::GenericData::FindDataGroupHeader().
DataGroupHeader & FileHeader::GetDataGroup (int32_t index)
Get a DataGroupHeader by index. Max index < GetDataGroupCnt
Definition at line 65 of file FileHeader.cpp.
References dataGroupHdrs.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::FileHeaderUpdater::AppendDataGroupHeader(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyHeaders(), affymetrix_calvin_io::GenericData::FindDataGroupHeader(), affymetrix_calvin_io::GenericFileUpdater::FindLastDataSetHeader(), affymetrix_calvin_io::DATFileUpdater::GetGridDataSetOffset(), affymetrix_calvin_io::DATFileUpdater::GetSubGridDataSetOffset(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::MMDATFileWriter::MMDATFileWriter(), and affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroups().
int32_t FileHeader::GetDataGroupCnt () const
Get the number of DataGroupHeaders added
Definition at line 91 of file FileHeader.cpp.
References dataGroupHdrs.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::FileHeaderUpdater::AppendDataGroupHeader(), affymetrix_calvin_io::GenericData::DataGroupCnt(), affymetrix_calvin_io::GenericData::FindDataGroupHeader(), affymetrix_calvin_io::GenericFileUpdater::FindLastDataSetHeader(), affymetrix_calvin_io::DATFileUpdater::GetGridDataSetOffset(), affymetrix_calvin_io::DATFileUpdater::GetSubGridDataSetOffset(), affymetrix_calvin_io::GenericFileUpdater::GetUpdateDataSetWriter(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::GenericFileReader::ReadFileHeader(), affymetrix_calvin_io::GenericFileReader::ReadFileHeaderMinDP(), and affymetrix_calvin_io::FileHeaderWriter::WriteDataGroupCnt().
const DataGroupHeader & FileHeader::GetDataGroupConst (int32_t index) const
Definition at line 70 of file FileHeader.cpp.
References dataGroupHdrs.
void FileHeader::GetDataGroupIts (DataGroupHdrIt & begin, DataGroupHdrIt & end)
Definition at line 75 of file FileHeader.cpp.
References dataGroupHdrs.
Referenced by affymetrix_calvin_io::GenericData::DataGroupNames(), FindDataGroupHeader(), affymetrix_calvin_io::GenericFileUpdater::FindLastDataGroupOffset(), and affymetrix_calvin_io::GenericFileUpdater::GetLastDataGroupDataSetCnt().
std::string FileHeader::GetFilename () const
Definition at line 45 of file FileHeader.cpp.
References filename.
u_int32_t affymetrix_calvin_io::FileHeader::GetFirstDataGroupFilePos () [inline]
Get the file position to the first DataGroup
Definition at line 96 of file FileHeader.h.
References firstDataGroupFilePos.
Referenced by AddDataSetHeaderToGroup(), affymetrix_calvin_io::GenericFileUpdater::FindLastDataGroupOffset(), affymetrix_calvin_io::DataGroupHeaderReader::ReadAll(), affymetrix_calvin_io::DataGroupHeaderReader::ReadAllMinimumInfo(), and affymetrix_calvin_io::DATFileUpdater::UpdateDataSetCnt().
GenericDataHeader * FileHeader::GetGenericDataHdr ()
Definition at line 86 of file FileHeader.cpp.
References genericHdr.
Referenced by affymetrix_calvin_io::GenericData::ArrayFileIdentifier(), affymetrix_calvin_io::GenericData::ArrayIdentifier(), CalvinChpCheck::check(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyFileHdr(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyHeaders(), CreateFileWithHeader(), CopyNumberResultWriter::CreateResultFile(), affymetrix_fusion_io::CalvinCHPDataAdapter::FileId(), affymetrix_calvin_io::GenericData::FileIdentifier(), CalvinToText::OutputFileHeaderParameters(), CalvinToText::OutputHeader(), affymetrix_calvin_io::GridControlFileReader::Read(), ReadGuidFromFile(), affymetrix_calvin_io::FileHeaderUpdater::Update(), affymetrix_calvin_io::DATFileUpdater::UpdateFileHeader(), OutputMessageStream::Write(), and affymetrix_calvin_io::FileHeaderWriter::WriteGenericDataHdr().
u_int8_t FileHeader::GetMagicNumber () const
Definition at line 50 of file FileHeader.cpp.
References magic.
Referenced by CalvinToText::OutputFileHeaderParameters(), and affymetrix_calvin_io::FileHeaderWriter::WriteMagicNumber().
int32_t affymetrix_calvin_io::FileHeader::GetNumDataGroups () const [inline]
Get the number of DataGroups in a file.
Definition at line 92 of file FileHeader.h.
References numDataGroups.
Referenced by CalvinChpCheck::headersSame().
u_int8_t FileHeader::GetVersion () const
Definition at line 55 of file FileHeader.cpp.
References version.
Referenced by CalvinChpCheck::headersSame(), CalvinToText::OutputFileHeaderParameters(), and affymetrix_calvin_io::FileHeaderWriter::WriteVersion().
void FileHeader::SetFilename (const std::string & p)
Definition at line 40 of file FileHeader.cpp.
References filename.
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::Collate(), affymetrix_calvin_io::GenericFileReader::ReadFileHeader(), affymetrix_calvin_io::GenericFileReader::ReadFileHeaderMinDP(), affymetrix_calvin_io::GenericFileReader::ReadFileHeaderNoDataGroupHeader(), affymetrix_calvin_io::CHPMultiDataData::SetFilename(), and OutputMessageStream::Write().
void affymetrix_calvin_io::FileHeader::SetFirstDataGroupFilePos (u_int32_t value) [inline]
Set the file postion to the first DataGroup. Method should be protected. It is set when the object is being read.
Definition at line 98 of file FileHeader.h.
References firstDataGroupFilePos.
Referenced by affymetrix_calvin_io::FileHeaderReader::ReadFirstDataGroupFilePos().
void FileHeader::SetGenericDataHdr (const GenericDataHeader & p)
Definition at line 81 of file FileHeader.cpp.
References genericHdr.
Referenced by affymetrix_calvin_io::FileHeaderReader::ReadGenericDataHdr().
void affymetrix_calvin_io::FileHeader::SetNumDataGroups (int32_t value) [inline]
Set the number of DataGroups. Set when reading a file
Definition at line 94 of file FileHeader.h.
References numDataGroups.
Referenced by affymetrix_calvin_io::FileHeaderReader::ReadDataGroupCnt().
Member Data Documentation
DataGroupHdrVector affymetrix_calvin_io::FileHeader::dataGroupHdrs [private]
Definition at line 61 of file FileHeader.h.
Referenced by AddDataGroupHdr(), Clear(), GetDataGroup(), GetDataGroupCnt(), GetDataGroupConst(), and GetDataGroupIts().
std::string affymetrix_calvin_io::FileHeader::filename [private]
filename
Definition at line 58 of file FileHeader.h.
Referenced by GetFilename(), and SetFilename().
u_int32_t affymetrix_calvin_io::FileHeader::firstDataGroupFilePos [private]
Position of the first DataGroup.
Definition at line 66 of file FileHeader.h.
Referenced by Clear(), GetFirstDataGroupFilePos(), and SetFirstDataGroupFilePos().
GenericDataHeader affymetrix_calvin_io::FileHeader::genericHdr [private]
Definition at line 62 of file FileHeader.h.
Referenced by Clear(), GetGenericDataHdr(), and SetGenericDataHdr().
u_int8_t affymetrix_calvin_io::FileHeader::magic [private]
Definition at line 59 of file FileHeader.h.
Referenced by FileHeader(), and GetMagicNumber().
int32_t affymetrix_calvin_io::FileHeader::numDataGroups [private]
Number of data dataGroups in the file
Definition at line 64 of file FileHeader.h.
Referenced by Clear(), GetNumDataGroups(), and SetNumDataGroups().
u_int8_t affymetrix_calvin_io::FileHeader::version [private]
Definition at line 60 of file FileHeader.h.
Referenced by FileHeader(), and GetVersion().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/FileHeader.h
C:/f112/affy/sdk/calvin_files/data/src/FileHeader.cpp