Affymetrix Fusion SDK: CProbeSetMultiDataCopyNumberDataCOM Class Reference
CProbeSetMultiDataCopyNumberDataCOM Class Reference
#include <ProbeSetMultiDataCopyNumberDataCOM.h>
Public Member Functions
CProbeSetMultiDataCopyNumberDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & Data ()
STDMETHOD() get_name (BSTR *pVal)
STDMETHOD() get_chr (int *pVal)
STDMETHOD() get_position (int *pVal)
STDMETHOD() get_metricCount (int *pVal)
STDMETHOD() GetMetric (int index, VARIANT *pVal)
STDMETHOD() GetMetricName (int index, BSTR *pVal)
Private Attributes
affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData data
Detailed Description
Definition at line 32 of file ProbeSetMultiDataCopyNumberDataCOM.h.
Constructor & Destructor Documentation
CProbeSetMultiDataCopyNumberDataCOM::CProbeSetMultiDataCopyNumberDataCOM () [inline]
Definition at line 39 of file ProbeSetMultiDataCopyNumberDataCOM.h.
Member Function Documentation
affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData& CProbeSetMultiDataCopyNumberDataCOM::Data () [inline]
Definition at line 71 of file ProbeSetMultiDataCopyNumberDataCOM.h.
Referenced by CFusionCHPMultiDataDataCOM::GetCopyNumberEntry().
HRESULT CProbeSetMultiDataCopyNumberDataCOM::FinalConstruct () [inline]
Definition at line 58 of file ProbeSetMultiDataCopyNumberDataCOM.h.
void CProbeSetMultiDataCopyNumberDataCOM::FinalRelease () [inline]
Definition at line 63 of file ProbeSetMultiDataCopyNumberDataCOM.h.
STDMETHODIMP CProbeSetMultiDataCopyNumberDataCOM::get_chr (int * pVal)
Definition at line 51 of file ProbeSetMultiDataCopyNumberDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCopyNumberDataCOM::get_metricCount (int * pVal)
Definition at line 63 of file ProbeSetMultiDataCopyNumberDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCopyNumberDataCOM::get_name (BSTR * pVal)
Definition at line 45 of file ProbeSetMultiDataCopyNumberDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CProbeSetMultiDataCopyNumberDataCOM::get_position (int * pVal)
Definition at line 57 of file ProbeSetMultiDataCopyNumberDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataCopyNumberDataCOM::GetMetric (int index, VARIANT * pVal)
Definition at line 76 of file ProbeSetMultiDataCopyNumberDataCOM.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::AsciiType, COMStringUtils::ConvertString(), COMStringUtils::ConvertWString(), affymetrix_calvin_parameter::ParameterNameValueType::FloatType, affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), affymetrix_calvin_parameter::ParameterNameValueType::Int16Type, affymetrix_calvin_parameter::ParameterNameValueType::Int32Type, affymetrix_calvin_parameter::ParameterNameValueType::Int8Type, affymetrix_calvin_parameter::ParameterNameValueType::TextType, affymetrix_calvin_parameter::ParameterNameValueType::UInt16Type, affymetrix_calvin_parameter::ParameterNameValueType::UInt32Type, and affymetrix_calvin_parameter::ParameterNameValueType::UInt8Type.
STDMETHODIMP CProbeSetMultiDataCopyNumberDataCOM::GetMetricName (int index, BSTR * pVal)
Definition at line 69 of file ProbeSetMultiDataCopyNumberDataCOM.cpp.
References COMStringUtils::ConvertWString(), and affymetrix_calvin_parameter::ParameterNameValueType::GetName().
STDMETHODIMP CProbeSetMultiDataCopyNumberDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 30 of file ProbeSetMultiDataCopyNumberDataCOM.cpp.
Member Data Documentation
affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData CProbeSetMultiDataCopyNumberDataCOM::data [private]
Definition at line 68 of file ProbeSetMultiDataCopyNumberDataCOM.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataCopyNumberDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataCopyNumberDataCOM.cpp