Affymetrix Fusion SDK: affymetrix_calvin_io::MMDataSetDataWriter Class Reference
affymetrix_calvin_io::MMDataSetDataWriter Class Reference
#include <MMDataSetDataWriter.h>
Public Member Functions
MMDataSetDataWriter (DataSetHeader &dsHdr, const std::string &name)
~MMDataSetDataWriter ()
bool Open ()
bool Close ()
bool MapData (int32_t firstRow, int32_t rowsToMap)
char * GetMappedDataPtr ()
int32_t GetFirstRowMapped ()
int32_t GetRowsMapped ()
int32_t GetMaxRowsToMap ()
Protected Member Functions
bool OpenData ()
Private Attributes
MemMapFile mmfile
DataSetHeader & dataSetHeader
std::string filename
int32_t dataSetDataSize
int32_t bytesPerRow
Detailed Description
This class writes a DataSet data. The DataSet data is written to the file using memory-mapping. This class assumes that the DataSetHeaderWriter has already written the DataSetHeader to the file or more accurately, that the file has already been created by the GenericFileWriter.
Definition at line 45 of file MMDataSetDataWriter.h.
Constructor & Destructor Documentation
MMDataSetDataWriter::MMDataSetDataWriter (DataSetHeader & dsHdr, const std::string & name)
Constructor
Parameters:
dsHdr The DataSetHeader object that is to be written to the file.
name DAT file name.
Definition at line 36 of file MMDataSetDataWriter.cpp.
References bytesPerRow, dataSetDataSize, dataSetHeader, affymetrix_calvin_io::DataSetHeader::GetDataSize(), and affymetrix_calvin_io::DataSetHeader::GetRowSize().
MMDataSetDataWriter::~MMDataSetDataWriter ()
Destructor
Definition at line 46 of file MMDataSetDataWriter.cpp.
References Close().
Member Function Documentation
bool MMDataSetDataWriter::Close (void)
Closes the writer. This closes the memory-mapped view.
Returns:
true if it succeeded. Method may also throw exceptions.
Definition at line 91 of file MMDataSetDataWriter.cpp.
References affymetrix_calvin_io::MemMapFile::Close(), and mmfile.
Referenced by affymetrix_calvin_io::MMDATFileWriter::Close(), affymetrix_calvin_io::MMDATFileWriter::HTONPixelDataSet(), Open(), and ~MMDataSetDataWriter().
int32_t MMDataSetDataWriter::GetFirstRowMapped ()
Get the first DataSet row that has been mapped.
Returns:
Index of the first DataSet row mapped for access.
Definition at line 129 of file MMDataSetDataWriter.cpp.
References bytesPerRow, dataSetHeader, affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), affymetrix_calvin_io::MemMapFile::GetFirstMappedBytePos(), and mmfile.
Referenced by affymetrix_calvin_io::MMDATFileWriter::GetFirstPixelRowMapped(), and affymetrix_calvin_io::MMDATFileWriter::HTONPixelDataSet().
char * MMDataSetDataWriter::GetMappedDataPtr ()
Get a pointer to the data that has been mapped for access.
Returns:
Pointer to the mapped data.
Definition at line 121 of file MMDataSetDataWriter.cpp.
References affymetrix_calvin_io::MemMapFile::GetDataPtr(), and mmfile.
Referenced by affymetrix_calvin_io::MMDATFileWriter::GetMappedPixelDataPtr(), and affymetrix_calvin_io::MMDATFileWriter::HTONPixelDataSet().
int32_t MMDataSetDataWriter::GetMaxRowsToMap ()
Get the suggested maximum number of DataSet rows to map.
Returns:
The suggested maximum number of DataSet rows to map.
Definition at line 100 of file MMDataSetDataWriter.cpp.
References bytesPerRow, and MAXFILEMAPSIZE.
Referenced by affymetrix_calvin_io::MMDATFileWriter::GetMaxPixelRowsToMap(), affymetrix_calvin_io::MMDATFileWriter::HTONPixelDataSet(), and OpenData().
int32_t MMDataSetDataWriter::GetRowsMapped ()
Get the number of DataSet rows that have been mapped.
Returns:
The number of DataSet rows mapped for access.
Definition at line 137 of file MMDataSetDataWriter.cpp.
References bytesPerRow, affymetrix_calvin_io::MemMapFile::GetBytesMapped(), and mmfile.
Referenced by affymetrix_calvin_io::MMDATFileWriter::GetPixelRowsMapped(), and affymetrix_calvin_io::MMDATFileWriter::HTONPixelDataSet().
bool MMDataSetDataWriter::MapData (int32_t firstRow, int32_t rowsToMap)
Maps the pixel data for access starting at firstRow and continuing for rowsToMap.
Parameters:
firstRow First DataSet row to map for access.
rowsToMap Requested number of DataSet rows to map. Use GetRowsMapped for number of rows actually mapped.
Returns:
True if successful.
Definition at line 110 of file MMDataSetDataWriter.cpp.
References bytesPerRow, dataSetHeader, affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), affymetrix_calvin_io::MemMapFile::MapData(), and mmfile.
Referenced by affymetrix_calvin_io::MMDATFileWriter::HTONPixelDataSet(), and affymetrix_calvin_io::MMDATFileWriter::MapPixelData().
bool MMDataSetDataWriter::Open ()
Opens the writer. It closes the previously opened view and opens a memory-mapped view of the first section of the DataSet.
Returns:
true if it succeeded. Method may also throw exceptions.
Exceptions:
affymetrix_calvin_exceptions::FileCreateException
Definition at line 54 of file MMDataSetDataWriter.cpp.
References Close(), and OpenData().
Referenced by affymetrix_calvin_io::MMDATFileWriter::HTONPixelDataSet(), and affymetrix_calvin_io::MMDATFileWriter::Open().
bool MMDataSetDataWriter::OpenData () [protected]
Open a memory-mapped view of the DataSet data section.
Returns:
True if successful.
Definition at line 63 of file MMDataSetDataWriter.cpp.
References affymetrix_calvin_io::ALLOWREAD_AND_WRITE, bytesPerRow, dataSetHeader, filename, affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos(), GetMaxRowsToMap(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), affymetrix_calvin_io::MemMapFile::MapData(), mmfile, affymetrix_calvin_io::MemMapFile::Open(), affymetrix_calvin_io::READ_AND_WRITE, and affymetrix_calvin_io::MemMapFile::SetFilename().
Referenced by Open().
Member Data Documentation
int32_t affymetrix_calvin_io::MMDataSetDataWriter::bytesPerRow [private]
Bytes per DataSet row
Definition at line 114 of file MMDataSetDataWriter.h.
Referenced by GetFirstRowMapped(), GetMaxRowsToMap(), GetRowsMapped(), MapData(), MMDataSetDataWriter(), and OpenData().
int32_t affymetrix_calvin_io::MMDataSetDataWriter::dataSetDataSize [private]
Size of the data section of the DataSet
Definition at line 111 of file MMDataSetDataWriter.h.
Referenced by MMDataSetDataWriter().
DataSetHeader& affymetrix_calvin_io::MMDataSetDataWriter::dataSetHeader [private]
DataSetHeader
Definition at line 107 of file MMDataSetDataWriter.h.
Referenced by GetFirstRowMapped(), MapData(), MMDataSetDataWriter(), and OpenData().
std::string affymetrix_calvin_io::MMDataSetDataWriter::filename [private]
Name of the file to memory map
Definition at line 109 of file MMDataSetDataWriter.h.
Referenced by OpenData().
MemMapFile affymetrix_calvin_io::MMDataSetDataWriter::mmfile [private]
Windows memory-mapped file access
Definition at line 105 of file MMDataSetDataWriter.h.
Referenced by Close(), GetFirstRowMapped(), GetMappedDataPtr(), GetRowsMapped(), MapData(), and OpenData().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/MMDataSetDataWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/MMDataSetDataWriter.cpp