Affymetrix Fusion SDK: affymetrix_calvin_io::DATFileUpdater Class Reference
affymetrix_calvin_io::DATFileUpdater Class Reference
#include <DATFileUpdater.h>
Public Member Functions
DATFileUpdater (DATData &p)
~DATFileUpdater ()
void Update ()
Private Member Functions
void WriteGridData (DataSetHeader &gridHdr, u_int32_t offset) const
void WriteSubGridData (DataSetHeader &SubGridHdr, u_int32_t offset) const
u_int32_t GetGridDataSetOffset (FileHeader fh) const
u_int32_t GetSubGridDataSetOffset (FileHeader fh) const
DataSetHeader CreateGridDataSetHeader () const
DataSetHeader CreateSubGridDataSetHeader () const
void UpdateDataSetCnt (FileHeader fh, u_int32_t cnt) const
void ReadCurrentData () const
void UpdateFileHeader ()
void AddGridDataSetHeaderParameters (DataSetHeader &hdr) const
Private Attributes
DATData * updateData
DATData * currentData
GenericFileWriter * writer
DataSetWriter * dataSetWriter
Detailed Description
Definition at line 37 of file DATFileUpdater.h.
Constructor & Destructor Documentation
DATFileUpdater::DATFileUpdater (DATData & p)
Definition at line 32 of file DATFileUpdater.cpp.
References currentData, affymetrix_calvin_io::DATData::GetFileHeader(), ReadCurrentData(), updateData, and writer.
DATFileUpdater::~DATFileUpdater ()
Definition at line 40 of file DATFileUpdater.cpp.
References currentData, and writer.
Member Function Documentation
void DATFileUpdater::AddGridDataSetHeaderParameters (DataSetHeader & hdr) const [private]
Definition at line 204 of file DATFileUpdater.cpp.
References affymetrix_calvin_io::DataSetHeader::AddNameValParam(), affymetrix_calvin_io::DATData::GetGridAlignmentAlgorithmParameters(), and updateData.
Referenced by CreateGridDataSetHeader(), and CreateSubGridDataSetHeader().
DataSetHeader DATFileUpdater::CreateGridDataSetHeader () const [private]
Definition at line 159 of file DATFileUpdater.cpp.
References affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), AddGridDataSetHeaderParameters(), affymetrix_calvin_io::DataSetHeader::AddUIntColumn(), DAT_GLOBAL_GRID, GridColNames, GridStatusColName, NumGridCols, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by Update().
DataSetHeader DATFileUpdater::CreateSubGridDataSetHeader () const [private]
Definition at line 173 of file DATFileUpdater.cpp.
References affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), AddGridDataSetHeaderParameters(), affymetrix_calvin_io::DataSetHeader::AddUIntColumn(), DAT_SUBGRID, affymetrix_calvin_io::DATData::GetSubgridCnt(), GridColNames, GridStatusColName, NumGridCols, affymetrix_calvin_io::DataSetHeader::SetName(), affymetrix_calvin_io::DataSetHeader::SetRowCnt(), and updateData.
Referenced by Update().
u_int32_t DATFileUpdater::GetGridDataSetOffset (FileHeader fh) const [private]
Definition at line 93 of file DATFileUpdater.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), and affymetrix_calvin_io::DataSetHeader::GetNextSetFilePos().
Referenced by Update().
u_int32_t DATFileUpdater::GetSubGridDataSetOffset (FileHeader fh) const [private]
Definition at line 108 of file DATFileUpdater.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::FileHeader::GetDataGroupCnt(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), and affymetrix_calvin_io::DataSetHeader::GetNextSetFilePos().
Referenced by Update().
void DATFileUpdater::ReadCurrentData () const [private]
Definition at line 187 of file DATFileUpdater.cpp.
References currentData, affymetrix_calvin_io::DATData::GetFilename(), affymetrix_calvin_io::DATFileReader::Read(), affymetrix_calvin_io::DATData::SetFilename(), and updateData.
Referenced by DATFileUpdater().
void DATFileUpdater::Update ()
Definition at line 46 of file DATFileUpdater.cpp.
References CreateGridDataSetHeader(), CreateSubGridDataSetHeader(), currentData, affymetrix_calvin_io::DATData::GetGenericData(), GetGridDataSetOffset(), affymetrix_calvin_io::DATData::GetSubgridCnt(), GetSubGridDataSetOffset(), affymetrix_calvin_io::DATData::HasGlobalGridData(), affymetrix_calvin_io::GenericData::Header(), updateData, UpdateDataSetCnt(), UpdateFileHeader(), WriteGridData(), and WriteSubGridData().
void DATFileUpdater::UpdateDataSetCnt (FileHeader fh, u_int32_t cnt) const [private]
Definition at line 86 of file DATFileUpdater.cpp.
References affymetrix_calvin_io::FileHeader::GetFirstDataGroupFilePos(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::GenericFileWriter::Write(), and writer.
Referenced by Update().
void DATFileUpdater::UpdateFileHeader () [private]
Definition at line 194 of file DATFileUpdater.cpp.
References currentData, affymetrix_calvin_io::DATData::GetFileHeader(), affymetrix_calvin_io::GenericFileWriter::GetFileOStream(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_calvin_io::GenericDataHeader::SetFileId(), affymetrix_calvin_io::FileHeaderUpdater::Update(), updateData, and writer.
Referenced by Update().
void DATFileUpdater::WriteGridData (DataSetHeader & gridHdr, u_int32_t offset) const [private]
Definition at line 123 of file DATFileUpdater.cpp.
References affymetrix_calvin_io::DataGroupWriter::CreateDataSetWriter(), affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DATData::GetGlobalGrid(), affymetrix_calvin_io::DATData::GetGlobalGridStatus(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), updateData, affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), affymetrix_calvin_io::DataSetWriter::Write(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), and writer.
Referenced by Update().
void DATFileUpdater::WriteSubGridData (DataSetHeader & SubGridHdr, u_int32_t offset) const [private]
Definition at line 139 of file DATFileUpdater.cpp.
References affymetrix_calvin_io::DataGroupWriter::CreateDataSetWriter(), affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DATData::GetSubgrid(), affymetrix_calvin_io::DATData::GetSubgridCnt(), affymetrix_calvin_io::DATData::GetSubgridStatus(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), updateData, affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), affymetrix_calvin_io::DataSetWriter::Write(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), and writer.
Referenced by Update().
Member Data Documentation
DATData* affymetrix_calvin_io::DATFileUpdater::currentData [private]
Definition at line 43 of file DATFileUpdater.h.
Referenced by DATFileUpdater(), ReadCurrentData(), Update(), UpdateFileHeader(), and ~DATFileUpdater().
DataSetWriter* affymetrix_calvin_io::DATFileUpdater::dataSetWriter [private]
Definition at line 45 of file DATFileUpdater.h.
DATData* affymetrix_calvin_io::DATFileUpdater::updateData [private]
Definition at line 42 of file DATFileUpdater.h.
Referenced by AddGridDataSetHeaderParameters(), CreateSubGridDataSetHeader(), DATFileUpdater(), ReadCurrentData(), Update(), UpdateFileHeader(), WriteGridData(), and WriteSubGridData().
GenericFileWriter* affymetrix_calvin_io::DATFileUpdater::writer [private]
Definition at line 44 of file DATFileUpdater.h.
Referenced by DATFileUpdater(), UpdateDataSetCnt(), UpdateFileHeader(), WriteGridData(), WriteSubGridData(), and ~DATFileUpdater().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DATFileUpdater.h
C:/f112/affy/sdk/calvin_files/writers/src/DATFileUpdater.cpp