Affymetrix Fusion SDK: affymetrix_calvin_io::CelFileWriter Class Reference
affymetrix_calvin_io::CelFileWriter Class Reference
#include <CalvinCelFileWriter.h>
Public Member Functions
CelFileWriter (CelFileData &p)
~CelFileWriter ()
void WriteIntensities (const FloatVector &v)
void WriteStdDevs (const FloatVector &v)
void WritePixels (const Int16Vector &v)
void WriteOutlierCoords (const XYCoordVector &coords)
void WriteMaskCoords (const XYCoordVector &coords)
Private Member Functions
void WriteHeaders ()
void SetFilePositions ()
Private Attributes
GenericFileWriter * writer
DataSetWriter * dataSetWriter
int32_t intensityPos
int32_t stdDevPos
int32_t pixelPos
int32_t outlierPos
int32_t maskPos
int32_t intensityLimitPos
int32_t stdDevLimitPos
int32_t pixelLimitPos
int32_t outlierLimitPos
int32_t maskLimitPos
Detailed Description
Definition at line 35 of file CalvinCelFileWriter.h.
Constructor & Destructor Documentation
CelFileWriter::CelFileWriter (CelFileData & p)
Definition at line 26 of file CalvinCelFileWriter.cpp.
References CurrentCelFileVersion, affymetrix_calvin_io::CelFileData::GetFileHeader(), intensityPos, maskPos, outlierPos, pixelPos, affymetrix_calvin_io::CelFileData::SetVersion(), stdDevPos, WriteHeaders(), and writer.
CelFileWriter::~CelFileWriter ()
Definition at line 38 of file CalvinCelFileWriter.cpp.
References writer.
Member Function Documentation
void CelFileWriter::SetFilePositions () [private]
Definition at line 128 of file CalvinCelFileWriter.cpp.
References CelIntensityLabel, CelOutlierLabel, CelPixelLabel, CelStdDevLabel, dataSetWriter, affymetrix_calvin_io::DataSetWriter::GetDataSetName(), affymetrix_calvin_io::DataSetWriter::GetDataSetSize(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), intensityLimitPos, intensityPos, maskLimitPos, maskPos, outlierLimitPos, outlierPos, pixelLimitPos, pixelPos, affymetrix_calvin_io::GenericFileWriter::SeekFromCurrentPos(), stdDevLimitPos, stdDevPos, affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), and writer.
Referenced by WriteHeaders().
void CelFileWriter::WriteHeaders () [private]
Definition at line 43 of file CalvinCelFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriters(), SetFilePositions(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), and writer.
Referenced by CelFileWriter().
void CelFileWriter::WriteIntensities (const FloatVector & v)
Definition at line 61 of file CalvinCelFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), intensityPos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::DataSetWriter::Write(), and writer.
void CelFileWriter::WriteMaskCoords (const XYCoordVector & coords)
Definition at line 114 of file CalvinCelFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), maskPos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::DataSetWriter::Write(), and writer.
void CelFileWriter::WriteOutlierCoords (const XYCoordVector & coords)
Definition at line 100 of file CalvinCelFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), outlierPos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::DataSetWriter::Write(), and writer.
void CelFileWriter::WritePixels (const Int16Vector & v)
Definition at line 87 of file CalvinCelFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), pixelPos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::DataSetWriter::Write(), and writer.
void CelFileWriter::WriteStdDevs (const FloatVector & v)
Definition at line 74 of file CalvinCelFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), stdDevPos, affymetrix_calvin_io::DataSetWriter::Write(), and writer.
Member Data Documentation
DataSetWriter* affymetrix_calvin_io::CelFileWriter::dataSetWriter [private]
Definition at line 41 of file CalvinCelFileWriter.h.
Referenced by SetFilePositions(), WriteHeaders(), WriteIntensities(), WriteMaskCoords(), WriteOutlierCoords(), WritePixels(), and WriteStdDevs().
int32_t affymetrix_calvin_io::CelFileWriter::intensityLimitPos [private]
Definition at line 47 of file CalvinCelFileWriter.h.
Referenced by SetFilePositions().
int32_t affymetrix_calvin_io::CelFileWriter::intensityPos [private]
Definition at line 42 of file CalvinCelFileWriter.h.
Referenced by CelFileWriter(), SetFilePositions(), and WriteIntensities().
int32_t affymetrix_calvin_io::CelFileWriter::maskLimitPos [private]
Definition at line 51 of file CalvinCelFileWriter.h.
Referenced by SetFilePositions().
int32_t affymetrix_calvin_io::CelFileWriter::maskPos [private]
Definition at line 46 of file CalvinCelFileWriter.h.
Referenced by CelFileWriter(), SetFilePositions(), and WriteMaskCoords().
int32_t affymetrix_calvin_io::CelFileWriter::outlierLimitPos [private]
Definition at line 50 of file CalvinCelFileWriter.h.
Referenced by SetFilePositions().
int32_t affymetrix_calvin_io::CelFileWriter::outlierPos [private]
Definition at line 45 of file CalvinCelFileWriter.h.
Referenced by CelFileWriter(), SetFilePositions(), and WriteOutlierCoords().
int32_t affymetrix_calvin_io::CelFileWriter::pixelLimitPos [private]
Definition at line 49 of file CalvinCelFileWriter.h.
Referenced by SetFilePositions().
int32_t affymetrix_calvin_io::CelFileWriter::pixelPos [private]
Definition at line 44 of file CalvinCelFileWriter.h.
Referenced by CelFileWriter(), SetFilePositions(), and WritePixels().
int32_t affymetrix_calvin_io::CelFileWriter::stdDevLimitPos [private]
Definition at line 48 of file CalvinCelFileWriter.h.
Referenced by SetFilePositions().
int32_t affymetrix_calvin_io::CelFileWriter::stdDevPos [private]
Definition at line 43 of file CalvinCelFileWriter.h.
Referenced by CelFileWriter(), SetFilePositions(), and WriteStdDevs().
GenericFileWriter* affymetrix_calvin_io::CelFileWriter::writer [private]
Definition at line 40 of file CalvinCelFileWriter.h.
Referenced by CelFileWriter(), SetFilePositions(), WriteHeaders(), WriteIntensities(), WriteMaskCoords(), WriteOutlierCoords(), WritePixels(), WriteStdDevs(), and ~CelFileWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCelFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCelFileWriter.cpp