Affymetrix Fusion SDK: CalvinChpCheck Class Reference
CalvinChpCheck Class Reference
#include <CalvinChpCheck.h>
Public Member Functions
CalvinChpCheck (std::vector< std::string > &generated, std::vector< std::string > &gold, int diffAllowed=0, const std::wstring &prefix=L"apt-", double eps=0.0001, bool bCheckHeaders=true, double fraction=0.0)
CalvinChpCheck (const std::string &generated, const std::string &gold, int diffAllowed=0, const std::wstring &prefix=L"apt-", double eps=0.0001, bool bCheckHeaders=true, double fraction=0.0)
void setDiffReportMax (int max)
bool check (std::string &msg)
void clearHeaderIgnore ()
void addHeaderIgnore (std::wstring &key)
Private Member Functions
bool paramNamValTypeSame (ParameterNameValueType &gold, ParameterNameValueType &generated)
bool paramVectorsSame (std::vector< ParameterNameValueType > &gold, std::vector< ParameterNameValueType > &generated)
bool ParameterNameValueTypeMostlySame (ParameterNameValueTypeVector &gold, ParameterNameValueTypeVector &test, std::string &msg, std::wstring &prefix)
bool headersSame (CHPData &goldChp, CHPData &generatedChp, std::string &msgs)
void checkMultiDataDmetCopyNumberEntry (DmetCopyNumberData &goldEntry, DmetCopyNumberData &generatedEntry, bool &localSuccess, double &maxConfDiff, double &maxSignalDiff, int &numDiff)
void checkMultiDataDmetMultiAllelicEntry (DmetMultiAllelicData &goldEntry, DmetMultiAllelicData &generatedEntry, bool &localSuccess, double &maxConfDiff, double &maxSignalDiff, int &numDiff)
void checkMultiDataDmetBiAllelicEntry (DmetBiAllelicData &goldEntry, DmetBiAllelicData &generatedEntry, bool &localSuccess, double &maxConfDiff, double &maxSignalDiff, int &numDiff)
void checkMultiDataGenotypeEntry (ProbeSetMultiDataGenotypeData &goldEntry, ProbeSetMultiDataGenotypeData &generatedEntry, bool &localSuccess, double &maxDiff, int &numDiff)
void checkMultiDataExpressionEntry (ProbeSetMultiDataExpressionData &goldEntry, ProbeSetMultiDataExpressionData &generatedEntry, bool &localSuccess, double &maxDiff, int &numDiff)
void checkMultiDataCopyNumberEntry (ProbeSetMultiDataCopyNumberData &goldEntry, ProbeSetMultiDataCopyNumberData &generatedEntry, bool &localSuccess, double &maxLog2RatioDiff, double &maxSmoothSignalDiff, double &maxAllelicDifferenceDiff, int &numDiff)
void checkMultiDataCopyNumberVariationEntry (ProbeSetMultiDataCopyNumberVariationRegionData &goldEntry, ProbeSetMultiDataCopyNumberVariationRegionData &generatedEntry, bool &localSuccess, double &maxSignalDiff, double &maxConfidenceDiff, int &numDiff)
void checkQuantificationEntry (ProbeSetQuantificationData &goldEntry, ProbeSetQuantificationData &generatedEntry, bool &localSuccess, double &maxDiff, int &numDiff)
void checkQuantificationDetectionEntry (ProbeSetQuantificationDetectionData &goldEntry, ProbeSetQuantificationDetectionData &generatedEntry, bool &localSuccess, double &maxDiff, int &numDiff, double &pvalMaxDiff)
bool multiDataDmetCopyNumberSame (CHPMultiDataData &goldChp, CHPMultiDataData &generatedChp, std::string &msgs, MultiDataType dataType)
bool multiDataDmetMultiAllelicSame (CHPMultiDataData &goldChp, CHPMultiDataData &generatedChp, std::string &msgs, MultiDataType dataType)
bool multiDataDmetBiAllelicSame (CHPMultiDataData &goldChp, CHPMultiDataData &generatedChp, std::string &msgs, MultiDataType dataType)
bool multiDataCopyNumberSame (CHPMultiDataData &goldChp, CHPMultiDataData &generatedChp, std::string &msgs, MultiDataType dataType)
bool multiDataCopyNumberVariationSame (CHPMultiDataData &goldChp, CHPMultiDataData &generatedChp, std::string &msgs, MultiDataType dataType)
bool multiDataGenotypeSame (CHPMultiDataData &goldChp, CHPMultiDataData &generatedChp, std::string &msgs, MultiDataType dataType)
bool multiDataExpressionSame (CHPMultiDataData &goldChp, CHPMultiDataData &generatedChp, std::string &msgs, MultiDataType dataType)
bool quantificationDataSame (CHPQuantificationData &goldChp, CHPQuantificationData &generatedChp, std::string &msgs)
bool quantificationDetectionDataSame (CHPQuantificationDetectionData &goldChp, CHPQuantificationDetectionData &generatedChp, std::string &msgs)
Static Private Member Functions
static void fillInToIgnore (std::set< std::wstring > &ignoreMap, const std::wstring &prefix)
Private Attributes
std::vector< std::string > m_Gold
Filenames for the gold standard or correct data chp files.
std::vector< std::string > m_Generated
Matching filenames for the chp files to be tested.
double m_EpsConfidence
Epsilon, small value that two floats can differ by but still be considered equivalent.
double m_FracConfidence
double m_EpsQuantification
double m_FracQuantification
double m_EpsParam
double m_FracParam
bool m_CheckHeaders
int m_DiffAllowed
How many differences will we tolerate?
std::wstring m_Prefix
What is the expected prefix for parameter names?
std::set< std::wstring > m_IgnoreMap
Header entries to ignore.
Detailed Description
Class for testing that CHP files are the same +/- some epsilon. Also checks to make sure that at least some of the headers are the same (times/dates/versions change so not checked).
Definition at line 62 of file CalvinChpCheck.h.
Constructor & Destructor Documentation
CalvinChpCheck::CalvinChpCheck (std::vector< std::string > & generated, std::vector< std::string > & gold, int diffAllowed = 0, const std::wstring & prefix = L"apt-", double eps = 0.0001, bool bCheckHeaders = true, double fraction = 0.0) [inline]
Constructor.
Parameters:
generated - vector of filenames to be tested.
gold - matching vector of filenames for gold standard data to test against.
diffAllowed - number of differences allowed
prefix - argument name prefix in header (default: "apt-")
eps - epsilon: Maximum accepted absolute difference in numeric values. i.e. if |generated-gold| >= eps then there is a difference.
bCheckHeaders Check headers? (boolean, default: true).
frac - Maximum accepted fractional difference in numeric values (not used by default). i.e. if |generated-gold| >= frac*max(|generated|,|gold|) then there is a difference.
Todo:
allow for a vector of eps for checking extra metrics
Definition at line 78 of file CalvinChpCheck.h.
CalvinChpCheck::CalvinChpCheck (const std::string & generated, const std::string & gold, int diffAllowed = 0, const std::wstring & prefix = L"apt-", double eps = 0.0001, bool bCheckHeaders = true, double fraction = 0.0) [inline]
Todo:
allow for a vector of eps for checking extra metrics
Definition at line 104 of file CalvinChpCheck.h.
Member Function Documentation
void CalvinChpCheck::addHeaderIgnore (std::wstring & key) [inline]
Add a header item to ignore
Parameters:
key - reference to a wide string
Definition at line 290 of file CalvinChpCheck.h.
bool CalvinChpCheck::check (std::string & msg) [inline]
Check to make sure that two files are the same +/- some epsilon.
Parameters:
msg - Fills in an error message if test fails, empty string otherwise.
Returns:
- Returns true if files are close enough, false otherwise.
Definition at line 145 of file CalvinChpCheck.h.
References CHP_GENOTYPING_ASSAY_TYPE, CHP_MULTI_DATA_TYPE, CHP_RESEQUENCING_ASSAY_TYPE, CHP_UNIVERSAL_ASSAY_TYPE, Fs::convertToUncPath(), affymetrix_calvin_io::CopyNumberMultiDataType, affymetrix_calvin_io::CopyNumberVariationMultiDataType, affymetrix_calvin_exceptions::CalvinException::Description(), affymetrix_calvin_io::DmetBiAllelicMultiDataType, affymetrix_calvin_io::DmetCopyNumberMultiDataType, affymetrix_calvin_io::DmetMultiAllelicMultiDataType, affymetrix_calvin_io::ExpressionMultiDataType, FS_QUOTE_PATH, affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetDataSetInfo(), affymetrix_calvin_io::CHPData::GetFileHeader(), affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_calvin_io::MultiDataDataSetNames, affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read(), affymetrix_calvin_io::CHPQuantificationFileReader::Read(), affymetrix_calvin_io::CHPMultiDataFileReader::Read(), affymetrix_calvin_io::CHPFileReader::Read(), affymetrix_calvin_io::CHPQuantificationDetectionFileReader::SetFilename(), affymetrix_calvin_io::CHPQuantificationFileReader::SetFilename(), affymetrix_calvin_io::CHPMultiDataFileReader::SetFilename(), affymetrix_calvin_io::CHPFileReader::SetFilename(), ToStr(), and Except::what().
Referenced by main().
void CalvinChpCheck::checkMultiDataCopyNumberEntry (ProbeSetMultiDataCopyNumberData & goldEntry, ProbeSetMultiDataCopyNumberData & generatedEntry, bool & localSuccess, double & maxLog2RatioDiff, double & maxSmoothSignalDiff, double & maxAllelicDifferenceDiff, int & numDiff) [inline, private]
Determine if two copnumber chp file entries are equivalent.
Parameters:
goldEntry - "correct" entry.
generatedEntry - entry to be tested against gold standard.
localSuccess - set to to false if entries not equivalent.
maxLog2RatioDiff - maximum difference seen so far.
maxSmoothSignalDiff - maximum difference seen so far.
maxAllelicDifferenceDiff - maximum difference seen so far.
numDiff - number of differences seen so far, incremented if these entries not equivalent.
Definition at line 705 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::chr, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::position.
void CalvinChpCheck::checkMultiDataCopyNumberVariationEntry (ProbeSetMultiDataCopyNumberVariationRegionData & goldEntry, ProbeSetMultiDataCopyNumberVariationRegionData & generatedEntry, bool & localSuccess, double & maxSignalDiff, double & maxConfidenceDiff, int & numDiff) [inline, private]
Determine if two cnv chp file entries are equivalent.
Parameters:
goldEntry - "correct" entry.
generatedEntry - entry to be tested against gold standard.
localSuccess - set to to false if entries not equivalent.
maxSignalDiff - maximum difference seen so far.
maxConfidenceDiff - maximum difference seen so far.
numDiff - number of differences seen so far, incremented if these entries not equivalent.
Definition at line 760 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::confidenceScore, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::name, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::signal, and ToStr().
void CalvinChpCheck::checkMultiDataDmetBiAllelicEntry (DmetBiAllelicData & goldEntry, DmetBiAllelicData & generatedEntry, bool & localSuccess, double & maxConfDiff, double & maxSignalDiff, int & numDiff) [inline, private]
Definition at line 594 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_DmetBiAllelicData::call, affymetrix_calvin_data::_DmetBiAllelicData::confidence, affymetrix_calvin_data::_DmetBiAllelicData::contextA, affymetrix_calvin_data::_DmetBiAllelicData::contextB, affymetrix_calvin_data::_DmetBiAllelicData::force, affymetrix_calvin_data::_DmetBiAllelicData::metrics, affymetrix_calvin_data::_DmetBiAllelicData::name, affymetrix_calvin_data::_DmetBiAllelicData::signalA, affymetrix_calvin_data::_DmetBiAllelicData::signalB, and ToStr().
void CalvinChpCheck::checkMultiDataDmetCopyNumberEntry (DmetCopyNumberData & goldEntry, DmetCopyNumberData & generatedEntry, bool & localSuccess, double & maxConfDiff, double & maxSignalDiff, int & numDiff) [inline, private]
Definition at line 470 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_DmetCopyNumberData::call, affymetrix_calvin_data::_DmetCopyNumberData::confidence, affymetrix_calvin_data::_DmetCopyNumberData::estimate, affymetrix_calvin_data::_DmetCopyNumberData::force, affymetrix_calvin_data::_DmetCopyNumberData::lower, affymetrix_calvin_data::_DmetCopyNumberData::metrics, affymetrix_calvin_data::_DmetCopyNumberData::name, ToStr(), and affymetrix_calvin_data::_DmetCopyNumberData::upper.
void CalvinChpCheck::checkMultiDataDmetMultiAllelicEntry (DmetMultiAllelicData & goldEntry, DmetMultiAllelicData & generatedEntry, bool & localSuccess, double & maxConfDiff, double & maxSignalDiff, int & numDiff) [inline, private]
Definition at line 514 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_DmetMultiAllelicData::alleleCount, affymetrix_calvin_data::_DmetMultiAllelicData::call, affymetrix_calvin_data::_DmetMultiAllelicData::confidence, affymetrix_calvin_data::_DmetMultiAllelicData::contextA, affymetrix_calvin_data::_DmetMultiAllelicData::contextB, affymetrix_calvin_data::_DmetMultiAllelicData::contextC, affymetrix_calvin_data::_DmetMultiAllelicData::contextD, affymetrix_calvin_data::_DmetMultiAllelicData::contextE, affymetrix_calvin_data::_DmetMultiAllelicData::contextF, affymetrix_calvin_data::_DmetMultiAllelicData::force, affymetrix_calvin_data::_DmetMultiAllelicData::metrics, affymetrix_calvin_data::_DmetMultiAllelicData::name, affymetrix_calvin_data::_DmetMultiAllelicData::signalA, affymetrix_calvin_data::_DmetMultiAllelicData::signalB, affymetrix_calvin_data::_DmetMultiAllelicData::signalC, affymetrix_calvin_data::_DmetMultiAllelicData::signalD, affymetrix_calvin_data::_DmetMultiAllelicData::signalE, affymetrix_calvin_data::_DmetMultiAllelicData::signalF, and ToStr().
void CalvinChpCheck::checkMultiDataExpressionEntry (ProbeSetMultiDataExpressionData & goldEntry, ProbeSetMultiDataExpressionData & generatedEntry, bool & localSuccess, double & maxDiff, int & numDiff) [inline, private]
Determine if two expression chp file entries are equivalent.
Parameters:
goldEntry - "correct" entry.
generatedEntry - entry to be tested against gold standard.
localSuccess - set to to false if entries not equivalent.
maxDiff - maximum difference seen so far.
numDiff - number of differences seen so far, incremented if these entries not equivalent.
Definition at line 679 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::name, and affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::quantification.
void CalvinChpCheck::checkMultiDataGenotypeEntry (ProbeSetMultiDataGenotypeData & goldEntry, ProbeSetMultiDataGenotypeData & generatedEntry, bool & localSuccess, double & maxDiff, int & numDiff) [inline, private]
Determine if two gentoyping chp file entries are equivalent.
Parameters:
goldEntry - "correct" entry.
generatedEntry - entry to be tested against gold standard.
localSuccess - set to to false if entries not equivalent.
maxDiff - maximum difference seen so far.
numDiff - number of differences seen so far, incremented if these entries not equivalent.
Definition at line 648 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::metrics, and affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::name.
void CalvinChpCheck::checkQuantificationDetectionEntry (ProbeSetQuantificationDetectionData & goldEntry, ProbeSetQuantificationDetectionData & generatedEntry, bool & localSuccess, double & maxDiff, int & numDiff, double & pvalMaxDiff) [inline, private]
Definition at line 807 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::id, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::name, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::pvalue, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::quantification, and ToStr().
void CalvinChpCheck::checkQuantificationEntry (ProbeSetQuantificationData & goldEntry, ProbeSetQuantificationData & generatedEntry, bool & localSuccess, double & maxDiff, int & numDiff) [inline, private]
Determine if two expression chp file entries are equivalent.
Parameters:
goldEntry - "correct" entry.
generatedEntry - entry to be tested against gold standard.
localSuccess - set to to false if entries not equivalent.
maxDiff - maximum difference seen so far.
numDiff - number of differences seen so far, incremented if these entries not equivalent.
Definition at line 792 of file CalvinChpCheck.h.
References affymetrix_calvin_data::_ProbeSetQuantificationData::id, affymetrix_calvin_data::_ProbeSetQuantificationData::name, affymetrix_calvin_data::_ProbeSetQuantificationData::quantification, and ToStr().
void CalvinChpCheck::clearHeaderIgnore () [inline]
Clear out the default set of header entries to ignore
Definition at line 282 of file CalvinChpCheck.h.
static void CalvinChpCheck::fillInToIgnore (std::set< std::wstring > & ignoreMap, const std::wstring & prefix) [inline, static, private]
Definition at line 297 of file CalvinChpCheck.h.
bool CalvinChpCheck::headersSame (CHPData & goldChp, CHPData & generatedChp, std::string & msgs) [inline, private]
Are the headers for to CHP files the same? Ignore some fields known to change like time, run id, etc.
Parameters:
goldChp - "correct" chp file.
generatedChp - chp file to be tested against gold standard.
msgs - ongoing list of messages about what when wrong if anything.
Returns:
- true if headers are equivalent, false otherwise.
Definition at line 434 of file CalvinChpCheck.h.
References affymetrix_calvin_io::CHPData::GetAlgName(), affymetrix_calvin_io::CHPData::GetAlgParams(), affymetrix_calvin_io::CHPData::GetAlgVersion(), affymetrix_calvin_io::CHPData::GetArrayType(), affymetrix_calvin_io::CHPData::GetChipSums(), affymetrix_calvin_io::CHPData::GetFileHeader(), affymetrix_calvin_io::FileHeader::GetNumDataGroups(), and affymetrix_calvin_io::FileHeader::GetVersion().
bool CalvinChpCheck::multiDataCopyNumberSame (CHPMultiDataData & goldChp, CHPMultiDataData & generatedChp, std::string & msgs, MultiDataType dataType) [inline, private]
Check to see if the copynumber entries for MultiDataType are the same.
Parameters:
goldChp - "correct" data.
generatedChp - chp file data to test against gold standard.
msgs - any ongoing messages for user.
dataType - Either genotype or control genotype, they are conceptually separate in chp file.
Returns:
- true if genotype entries are equivalent, false otherwise.
Definition at line 964 of file CalvinChpCheck.h.
References affymetrix_calvin_io::CopyNumberMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetCopyNumberEntry(), affymetrix_calvin_io::CHPMultiDataData::GetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::GetFilename(), affymetrix_calvin_io::MultiDataDataSetNames, Verbose::out(), and ToStr().
bool CalvinChpCheck::multiDataCopyNumberVariationSame (CHPMultiDataData & goldChp, CHPMultiDataData & generatedChp, std::string & msgs, MultiDataType dataType) [inline, private]
Check to see if the copynumber entries for MultiDataType are the same.
Parameters:
goldChp - "correct" data.
generatedChp - chp file data to test against gold standard.
msgs - any ongoing messages for user.
dataType - Either genotype or control genotype, they are conceptually separate in chp file.
Returns:
- true if genotype entries are equivalent, false otherwise.
Definition at line 1020 of file CalvinChpCheck.h.
References affymetrix_calvin_io::CopyNumberVariationMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetCopyNumberVariationEntry(), affymetrix_calvin_io::CHPMultiDataData::GetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::GetFilename(), affymetrix_calvin_io::MultiDataDataSetNames, Verbose::out(), and ToStr().
bool CalvinChpCheck::multiDataDmetBiAllelicSame (CHPMultiDataData & goldChp, CHPMultiDataData & generatedChp, std::string & msgs, MultiDataType dataType) [inline, private]
Definition at line 912 of file CalvinChpCheck.h.
References affymetrix_calvin_io::DmetBiAllelicMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetEntry(), affymetrix_calvin_io::CHPMultiDataData::GetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::GetFilename(), affymetrix_calvin_io::MultiDataDataSetNames, Verbose::out(), and ToStr().
bool CalvinChpCheck::multiDataDmetCopyNumberSame (CHPMultiDataData & goldChp, CHPMultiDataData & generatedChp, std::string & msgs, MultiDataType dataType) [inline, private]
Definition at line 824 of file CalvinChpCheck.h.
References affymetrix_calvin_io::DmetCopyNumberMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetEntry(), affymetrix_calvin_io::CHPMultiDataData::GetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::GetFilename(), affymetrix_calvin_io::MultiDataDataSetNames, Verbose::out(), and ToStr().
bool CalvinChpCheck::multiDataDmetMultiAllelicSame (CHPMultiDataData & goldChp, CHPMultiDataData & generatedChp, std::string & msgs, MultiDataType dataType) [inline, private]
Definition at line 868 of file CalvinChpCheck.h.
References affymetrix_calvin_io::DmetMultiAllelicMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetEntry(), affymetrix_calvin_io::CHPMultiDataData::GetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::GetFilename(), affymetrix_calvin_io::MultiDataDataSetNames, Verbose::out(), and ToStr().
bool CalvinChpCheck::multiDataExpressionSame (CHPMultiDataData & goldChp, CHPMultiDataData & generatedChp, std::string & msgs, MultiDataType dataType) [inline, private]
Check to see if the expression entries for MultiDataType are the same.
Parameters:
goldChp - "correct" data.
generatedChp - chp file data to test against gold standard.
msgs - any ongoing messages for user.
dataType - Either expression or control expression, they are conceptually separate in chp file.
Returns:
- true if expression entries are equivalent, false otherwise.
Definition at line 1120 of file CalvinChpCheck.h.
References affymetrix_calvin_io::ExpressionMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::GetExpressionEntry(), affymetrix_calvin_io::CHPMultiDataData::GetFilename(), affymetrix_calvin_io::MultiDataDataSetNames, Verbose::out(), and ToStr().
bool CalvinChpCheck::multiDataGenotypeSame (CHPMultiDataData & goldChp, CHPMultiDataData & generatedChp, std::string & msgs, MultiDataType dataType) [inline, private]
Check to see if the genotype entries for MultiDataType are the same.
Parameters:
goldChp - "correct" data.
generatedChp - chp file data to test against gold standard.
msgs - any ongoing messages for user.
dataType - Either genotype or control genotype, they are conceptually separate in chp file.
Returns:
- true if genotype entries are equivalent, false otherwise.
Definition at line 1072 of file CalvinChpCheck.h.
References affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::GetFilename(), affymetrix_calvin_io::CHPMultiDataData::GetGenotypeEntry(), affymetrix_calvin_io::MultiDataDataSetNames, Verbose::out(), and ToStr().
bool CalvinChpCheck::ParameterNameValueTypeMostlySame (ParameterNameValueTypeVector & gold, ParameterNameValueTypeVector & test, std::string & msg, std::wstring & prefix) [inline, private]
Definition at line 389 of file CalvinChpCheck.h.
References Fs::basename().
bool CalvinChpCheck::paramNamValTypeSame (ParameterNameValueType & gold, ParameterNameValueType & generated) [inline, private]
Check to see if two generic types are equivalent. If floats then makes sure they are withing epsilon (small number). Otherwise tested as strings which should work for other types.
Parameters:
gold - Type with "correct" values.
generated - Type with values to be tested.
Returns:
- true if same, false otherwise.
Definition at line 345 of file CalvinChpCheck.h.
References AffxByteArray::replace(), and AffxByteArray::toString().
bool CalvinChpCheck::paramVectorsSame (std::vector< ParameterNameValueType > & gold, std::vector< ParameterNameValueType > & generated) [inline, private]
Utility function for checking if two vectors of generic types are the same.
Parameters:
gold - Vector with the "correct" values.
generated - Vector to be tested against the gold values.
Returns:
- true if same, false othewise.
Definition at line 378 of file CalvinChpCheck.h.
bool CalvinChpCheck::quantificationDataSame (CHPQuantificationData & goldChp, CHPQuantificationData & generatedChp, std::string & msgs) [inline, private]
Check to see if the expression entries for Quantification are the same.
Parameters:
goldChp - "correct" data.
generatedChp - chp file data to test against gold standard.
msgs - any ongoing messages for user.
Returns:
- true if expression entries are equivalent, false otherwise.
Definition at line 1166 of file CalvinChpCheck.h.
References affymetrix_calvin_io::CHPQuantificationData::GetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::GetFilename(), affymetrix_calvin_io::CHPQuantificationData::GetQuantificationEntry(), Verbose::out(), and ToStr().
bool CalvinChpCheck::quantificationDetectionDataSame (CHPQuantificationDetectionData & goldChp, CHPQuantificationDetectionData & generatedChp, std::string & msgs) [inline, private]
Check to see if the expression entries for Quantification are the same.
Parameters:
goldChp - "correct" data.
generatedChp - chp file data to test against gold standard.
msgs - any ongoing messages for user.
Returns:
- true if expression entries are equivalent, false otherwise.
Definition at line 1211 of file CalvinChpCheck.h.
References affymetrix_calvin_io::CHPQuantificationDetectionData::GetEntryCount(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetFilename(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetQuantificationDetectionEntry(), Verbose::out(), and ToStr().
void CalvinChpCheck::setDiffReportMax (int max) [inline]
Utility function to set the max number of errors to report
Parameters:
max - maximum number of errors to report (-1 for no limit)
Returns:
- void
Definition at line 135 of file CalvinChpCheck.h.
Member Data Documentation
bool CalvinChpCheck::m_CheckHeaders [private]
Definition at line 1262 of file CalvinChpCheck.h.
int CalvinChpCheck::m_DiffAllowed [private]
How many differences will we tolerate?
Definition at line 1264 of file CalvinChpCheck.h.
double CalvinChpCheck::m_EpsConfidence [private]
Epsilon, small value that two floats can differ by but still be considered equivalent.
Definition at line 1256 of file CalvinChpCheck.h.
double CalvinChpCheck::m_EpsParam [private]
Definition at line 1260 of file CalvinChpCheck.h.
double CalvinChpCheck::m_EpsQuantification [private]
Definition at line 1258 of file CalvinChpCheck.h.
double CalvinChpCheck::m_FracConfidence [private]
Definition at line 1257 of file CalvinChpCheck.h.
double CalvinChpCheck::m_FracParam [private]
Definition at line 1261 of file CalvinChpCheck.h.
double CalvinChpCheck::m_FracQuantification [private]
Definition at line 1259 of file CalvinChpCheck.h.
std::vector<std::string> CalvinChpCheck::m_Generated [private]
Matching filenames for the chp files to be tested.
Definition at line 1254 of file CalvinChpCheck.h.
std::vector<std::string> CalvinChpCheck::m_Gold [private]
Filenames for the gold standard or correct data chp files.
Definition at line 1252 of file CalvinChpCheck.h.
std::set<std::wstring> CalvinChpCheck::m_IgnoreMap [private]
Header entries to ignore.
Definition at line 1268 of file CalvinChpCheck.h.
std::wstring CalvinChpCheck::m_Prefix [private]
What is the expected prefix for parameter names?
Definition at line 1266 of file CalvinChpCheck.h.
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/CalvinChpCheck.h