Affymetrix Fusion SDK: affymetrix_calvin_io::DATFileWriter Class Reference
affymetrix_calvin_io::DATFileWriter Class Reference
#include <DATFileWriter.h>
Public Member Functions
DATFileWriter (DATData &p)
~DATFileWriter ()
virtual void WriteStats (const Uint16Vector &v)
virtual void WritePixels (const Uint16Vector &v)
Private Member Functions
void WriteHeaders ()
void SetFilePositions ()
Private Attributes
GenericFileWriter * writer
DataSetWriter * dataSetWriter
int32_t pixelPos
int32_t statsPos
int32_t pixelLimitPos
int32_t statsLimitPos
Detailed Description
Definition at line 35 of file DATFileWriter.h.
Constructor & Destructor Documentation
DATFileWriter::DATFileWriter (DATData & p)
Definition at line 26 of file DATFileWriter.cpp.
References affymetrix_calvin_io::DATData::GetFileHeader(), pixelPos, statsPos, WriteHeaders(), and writer.
DATFileWriter::~DATFileWriter ()
Definition at line 34 of file DATFileWriter.cpp.
References writer.
Member Function Documentation
void DATFileWriter::SetFilePositions () [private]
Definition at line 83 of file DATFileWriter.cpp.
References DAT_PIXEL, dataSetWriter, affymetrix_calvin_io::DataSetWriter::GetDataSetName(), affymetrix_calvin_io::DataSetWriter::GetDataSetSize(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), pixelLimitPos, pixelPos, affymetrix_calvin_io::GenericFileWriter::SeekFromCurrentPos(), statsLimitPos, statsPos, affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), and writer.
Referenced by WriteHeaders().
void DATFileWriter::WriteHeaders () [private]
Definition at line 39 of file DATFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriters(), SetFilePositions(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), and writer.
Referenced by DATFileWriter().
void DATFileWriter::WritePixels (const Uint16Vector & v) [virtual]
Reimplemented in affymetrix_calvin_io::MMDATFileWriter.
Definition at line 70 of file DATFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), pixelPos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), affymetrix_calvin_io::DataSetWriter::Write(), and writer.
void DATFileWriter::WriteStats (const Uint16Vector & v) [virtual]
Definition at line 57 of file DATFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), statsPos, affymetrix_calvin_io::DataSetWriter::Write(), and writer.
Member Data Documentation
DataSetWriter* affymetrix_calvin_io::DATFileWriter::dataSetWriter [private]
Definition at line 41 of file DATFileWriter.h.
Referenced by SetFilePositions(), WriteHeaders(), WritePixels(), and WriteStats().
int32_t affymetrix_calvin_io::DATFileWriter::pixelLimitPos [private]
Definition at line 44 of file DATFileWriter.h.
Referenced by SetFilePositions().
int32_t affymetrix_calvin_io::DATFileWriter::pixelPos [private]
Definition at line 42 of file DATFileWriter.h.
Referenced by DATFileWriter(), SetFilePositions(), and WritePixels().
int32_t affymetrix_calvin_io::DATFileWriter::statsLimitPos [private]
Definition at line 45 of file DATFileWriter.h.
Referenced by SetFilePositions().
int32_t affymetrix_calvin_io::DATFileWriter::statsPos [private]
Definition at line 43 of file DATFileWriter.h.
Referenced by DATFileWriter(), SetFilePositions(), and WriteStats().
GenericFileWriter* affymetrix_calvin_io::DATFileWriter::writer [private]
Definition at line 40 of file DATFileWriter.h.
Referenced by DATFileWriter(), SetFilePositions(), WriteHeaders(), WritePixels(), WriteStats(), and ~DATFileWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DATFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/DATFileWriter.cpp