Affymetrix Fusion SDK: affymetrix_fusion_io::GCOSCHPHeaderAdapter Class Reference
affymetrix_fusion_io::GCOSCHPHeaderAdapter Class Reference
Header class for the GCOS CHP adapter.
#include <GCOSCHPDataAdapter.h>
Public Member Functions
GCOSCHPHeaderAdapter (affxchp::CCHPFileData *chp)
Constructor.
~GCOSCHPHeaderAdapter ()
Destructor.
virtual int GetCols () const
Get numbers columns.
virtual int GetRows () const
Get number of rows.
virtual int GetNumProbeSets () const
Get the number of probesets.
virtual AssayType GetAssayType () const
Get assay type.
virtual std::wstring GetChipType () const
Get chip type.
virtual std::wstring GetAlgName () const
Get algorithm name.
virtual std::wstring GetAlgVersion () const
Get algorithm version.
virtual void GetAlgorithmParameters (FusionTagValuePairTypeList &values)
Gets the algorithm parameters.
virtual u_int32_t GetAlgorithmParameterCount ()
Gets the algorithm parameter count.
virtual u_int32_t GetSummaryParameterCount ()
Gets the summary parameter count.
virtual void GetSummaryParameters (FusionTagValuePairTypeList &values)
Gets summary parameters.
virtual std::wstring GetParentCellFile () const
Gets the parent CEL file.
virtual std::wstring GetProgID () const
Gets the prog ID.
virtual std::wstring GetAlgorithmParameter (const wchar_t *tag)
Gets a specific algorithm parameter given a name/tag.
virtual std::wstring GetSummaryParameter (const wchar_t *tag)
Gets a specific summary parameter given a name/tag.
virtual void GetBackgroundZoneInfo (BackgroundZoneInfo &info)
Gets the background zone information.
virtual void GetBackgroundZones (BackgroundZoneTypeList &zones)
Gets the list of background zone positions and values.
virtual void GetBackgroundZone (BackgroundZoneType &type, int x, int y)
Gets the background value for a given center coordinate.
virtual int GetMagic () const
Gets the magic number.
virtual int GetVersion () const
Gets the version number.
Private Attributes
affxchp::CCHPFileData * gcosChp
Detailed Description
Header class for the GCOS CHP adapter.
Definition at line 40 of file GCOSCHPDataAdapter.h.
Constructor & Destructor Documentation
GCOSCHPHeaderAdapter::GCOSCHPHeaderAdapter (affxchp::CCHPFileData * chp)
Constructor.
Definition at line 33 of file GCOSCHPDataAdapter.cpp.
GCOSCHPHeaderAdapter::~GCOSCHPHeaderAdapter ()
Destructor.
Definition at line 38 of file GCOSCHPDataAdapter.cpp.
Member Function Documentation
std::wstring GCOSCHPHeaderAdapter::GetAlgName () const [virtual]
Get algorithm name.
Returns:
Algorithm name.
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 74 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetAlgName(), and affxchp::CCHPFileData::GetHeader().
std::wstring GCOSCHPHeaderAdapter::GetAlgorithmParameter (const wchar_t * tag) [virtual]
Gets a specific algorithm parameter given a name/tag.
Parameters:
tag Parameter name.
Returns:
Specific algorithm parameter given a name/tag
Gets a specific algorithm parameter given a name/tag
Returns:
The specific algorithm parameter given a name/tag
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 136 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetAlgorithmParameter(), and affxchp::CCHPFileData::GetHeader().
u_int32_t GCOSCHPHeaderAdapter::GetAlgorithmParameterCount () [virtual]
Gets the algorithm parameter count.
Returns:
Number of algorithm parameters.
Gets the algorithm parameter count
Returns:
The number of algorithm parameters
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 95 of file GCOSCHPDataAdapter.cpp.
References affxchp::CCHPFileHeader::AlgorithmParameters(), gcosChp, and affxchp::CCHPFileData::GetHeader().
void GCOSCHPHeaderAdapter::GetAlgorithmParameters (FusionTagValuePairTypeList & values) [virtual]
Gets the algorithm parameters.
Parameters:
values Name/Value type list to be filled.
Gets the algorithm parameters
Returns:
The number of feature columns
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 87 of file GCOSCHPDataAdapter.cpp.
References affxchp::CCHPFileHeader::AlgorithmParameters(), affymetrix_fusion_io::ConvertGCOS(), gcosChp, and affxchp::CCHPFileData::GetHeader().
std::wstring GCOSCHPHeaderAdapter::GetAlgVersion () const [virtual]
Get algorithm version.
Returns:
Algorithm version number.
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 80 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetAlgVersion(), and affxchp::CCHPFileData::GetHeader().
AssayType GCOSCHPHeaderAdapter::GetAssayType () const [virtual]
Get assay type.
Returns:
Assay Type.
Assay Types FusionExpression - Expression assay FusionGenotyping - Genotyping assay FusionResequencing - Resequencing assay FusionUniversal - Tag (universal) assay FusionUnknown - Unknown assay type
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 61 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetAssayType(), and affxchp::CCHPFileData::GetHeader().
void GCOSCHPHeaderAdapter::GetBackgroundZone (BackgroundZoneType & type, int x, int y) [virtual]
Gets the background value for a given center coordinate.
Parameters:
type Background value for a given center coordinate to be filled.
x X position of zone.
y Y position of zone.
Gets the background value for a given center coordinate
Returns:
The background value for a given center coordinate
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 170 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetBackgroundZone(), and affxchp::CCHPFileData::GetHeader().
void GCOSCHPHeaderAdapter::GetBackgroundZoneInfo (BackgroundZoneInfo & info) [virtual]
Gets the background zone information.
Parameters:
info Background zone information to be filled.
Gets the background zone information
Returns:
The background zone information
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 154 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetBackgroundZoneInfo(), and affxchp::CCHPFileData::GetHeader().
void GCOSCHPHeaderAdapter::GetBackgroundZones (BackgroundZoneTypeList & zones) [virtual]
Gets the list of background zone positions and values.
Parameters:
zones List of background zone positions and values to be filled.
Gets the list of background zone positions and values
Returns:
The list of background zone positions and values
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 162 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetBackgroundZones(), and affxchp::CCHPFileData::GetHeader().
std::wstring GCOSCHPHeaderAdapter::GetChipType () const [virtual]
Get chip type.
Returns:
The chip type.
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 68 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetChipType(), and affxchp::CCHPFileData::GetHeader().
int GCOSCHPHeaderAdapter::GetCols () const [virtual]
Get numbers columns.
Returns:
Number of columns.
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 43 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileHeader::GetCols(), and affxchp::CCHPFileData::GetHeader().
int GCOSCHPHeaderAdapter::GetMagic () const [virtual]
Gets the magic number.
Returns:
Magic number.
Gets the magic number
Returns:
The magic number
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 178 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::GetMagicNumber().
int GCOSCHPHeaderAdapter::GetNumProbeSets () const [virtual]
Get the number of probesets.
Returns:
Number of probesets.
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 55 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::GetNumProbeSets().
std::wstring GCOSCHPHeaderAdapter::GetParentCellFile () const [virtual]
Gets the parent CEL file.
Returns:
Parent CEL file name.
Gets the parent CEL file
Returns:
The parent CEL file
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 121 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::GetParentCellFile().
std::wstring GCOSCHPHeaderAdapter::GetProgID () const [virtual]
Gets the prog ID.
Returns:
Prog ID
Gets the prog ID
Returns:
The prog ID
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 129 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::GetProgID().
int GCOSCHPHeaderAdapter::GetRows () const [virtual]
Get number of rows.
Returns:
Number of rows.
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 49 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::GetRows().
std::wstring GCOSCHPHeaderAdapter::GetSummaryParameter (const wchar_t * tag) [virtual]
Gets a specific summary parameter given a name/tag.
Parameters:
tag Parameter name.
Returns:
Specific summary parameter given a name/tag.
Gets a specific summary parameter given a name/tag
Returns:
The specific summary parameter given a name/tag
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 145 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::GetSummaryParameter().
u_int32_t GCOSCHPHeaderAdapter::GetSummaryParameterCount () [virtual]
Gets the summary parameter count.
Returns:
Number of summary parameters.
Gets the summary parameter count
Returns:
The number of summary parameters
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 104 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::SummaryParameters().
void GCOSCHPHeaderAdapter::GetSummaryParameters (FusionTagValuePairTypeList & values) [virtual]
Gets summary parameters.
Parameters:
values Name/Value type list to be filled.
Gets the summary parameters
Returns:
The summary parameters
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 113 of file GCOSCHPDataAdapter.cpp.
References affymetrix_fusion_io::ConvertGCOS(), gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::SummaryParameters().
int GCOSCHPHeaderAdapter::GetVersion () const [virtual]
Gets the version number.
Returns:
Version number
Gets the version number
Returns:
The version number
Implements affymetrix_fusion_io::IFusionCHPHeaderAdapter.
Definition at line 186 of file GCOSCHPDataAdapter.cpp.
References gcosChp, affxchp::CCHPFileData::GetHeader(), and affxchp::CCHPFileHeader::GetVersionNumber().
Member Data Documentation
affxchp::CCHPFileData* affymetrix_fusion_io::GCOSCHPHeaderAdapter::gcosChp [private]
A pointer to the root data access object
Definition at line 154 of file GCOSCHPDataAdapter.h.
Referenced by GetAlgName(), GetAlgorithmParameter(), GetAlgorithmParameterCount(), GetAlgorithmParameters(), GetAlgVersion(), GetAssayType(), GetBackgroundZone(), GetBackgroundZoneInfo(), GetBackgroundZones(), GetChipType(), GetCols(), GetMagic(), GetNumProbeSets(), GetParentCellFile(), GetProgID(), GetRows(), GetSummaryParameter(), GetSummaryParameterCount(), GetSummaryParameters(), and GetVersion().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/GCOSAdapter/GCOSCHPDataAdapter.h
C:/f112/affy/sdk/calvin_files/fusion/src/GCOSAdapter/GCOSCHPDataAdapter.cpp