Affymetrix Fusion SDK: affymetrix_calvin_io::CHPExpressionEntry Class Reference
affymetrix_calvin_io::CHPExpressionEntry Class Reference
#include <CHPExpressionEntry.h>
Public Member Functions
CHPExpressionEntry ()
CHPExpressionEntry (const std::string &probeSetname, u_int8_t detection, float detectionPValue, float signal, u_int16_t numPairs, u_int16_t numPairsUsed, bool compData, u_int8_t change, float changePValue, float sigLogRatio, float sigLogRatioLo, float sigLogRatioHi, u_int16_t commonPairs)
CHPExpressionEntry (const std::string &probeSetname, u_int8_t detection, float detectionPValue, float signal, u_int16_t numPairs, u_int16_t numPairsUsed)
~CHPExpressionEntry ()
void Clear ()
CHPExpressionEntry operator= (CHPExpressionEntry e)
std::string GetProbeSetName () const
u_int8_t GetDetection () const
float GetDetectionPValue () const
float GetSignal () const
u_int16_t GetNumPairs () const
u_int16_t GetNumPairsUsed () const
bool GetHasComparisonData () const
u_int8_t GetChange () const
float GetChangePValue () const
float GetSigLogRatio () const
float GetSigLogRatioLo () const
float GetSigLogRatioHi () const
u_int16_t GetCommonPairs () const
void SetProbeSetName (const std::string &p)
void SetDetection (u_int8_t p)
void SetDetectionPValue (float p)
void SetSignal (float p)
void SetNumPairs (u_int16_t p)
void SetNumPairsUsed (u_int16_t p)
void SetHasComparisonData (bool b)
void SetChange (u_int8_t p)
void SetChangePValue (float p)
void SetSigLogRatio (float p)
void SetSigLogRatioLo (float p)
void SetSigLogRatioHi (float p)
void SetCommonPairs (u_int16_t p)
Private Attributes
std::string probeSetName
u_int8_t detection
float detectionPValue
float signal
u_int16_t numPairs
u_int16_t numPairsUsed
bool hasComparisonData
u_int8_t change
float changePValue
float sigLogRatio
float sigLogRatioLo
float sigLogRatioHi
u_int16_t commonPairs
Detailed Description
This class stores the expression probe set analysis results.
Definition at line 35 of file CHPExpressionEntry.h.
Constructor & Destructor Documentation
CHPExpressionEntry::CHPExpressionEntry ()
Constructor.
Definition at line 26 of file CHPExpressionEntry.cpp.
References Clear().
CHPExpressionEntry::CHPExpressionEntry (const std::string & probeSetname, u_int8_t detection, float detectionPValue, float signal, u_int16_t numPairs, u_int16_t numPairsUsed, bool compData, u_int8_t change, float changePValue, float sigLogRatio, float sigLogRatioLo, float sigLogRatioHi, u_int16_t commonPairs)
Constructor with absolute and comparison data.
Parameters:
probeSetname The probe set name
detection The detection
detectionPValue The detection p-value
signal The signal
numPairs The number of probe pairs in the set.
numPairsUsed The number of probe pairs used in the analysis
compData Flag indicating if comp data exists.
change The change call
changePValue The change p-value
sigLogRatio The signal log ratio
sigLogRatioLo The signal log ratio low
sigLogRatioHi The signal log ratio high
commonPairs The number of probe pairs in common between control and experiment
Definition at line 31 of file CHPExpressionEntry.cpp.
References change, changePValue, commonPairs, detection, detectionPValue, hasComparisonData, numPairs, numPairsUsed, probeSetName, sigLogRatio, sigLogRatioHi, sigLogRatioLo, and signal.
CHPExpressionEntry::CHPExpressionEntry (const std::string & probeSetname, u_int8_t detection, float detectionPValue, float signal, u_int16_t numPairs, u_int16_t numPairsUsed)
Constructor with absolute data only.
Parameters:
probeSetname The probe set name
detection The detection
detectionPValue The detection p-value
signal The signal
numPairs The number of probe pairs in the set.
numPairsUsed The number of probe pairs used in the analysis
Definition at line 60 of file CHPExpressionEntry.cpp.
References change, changePValue, commonPairs, detection, detectionPValue, hasComparisonData, numPairs, numPairsUsed, probeSetName, sigLogRatio, sigLogRatioHi, sigLogRatioLo, and signal.
CHPExpressionEntry::~CHPExpressionEntry ()
Destructor
Definition at line 82 of file CHPExpressionEntry.cpp.
Member Function Documentation
void CHPExpressionEntry::Clear ()
Clears the members.
Definition at line 84 of file CHPExpressionEntry.cpp.
References change, changePValue, commonPairs, detection, detectionPValue, hasComparisonData, numPairs, numPairsUsed, probeSetName, sigLogRatio, sigLogRatioHi, sigLogRatioLo, and signal.
Referenced by CHPExpressionEntry().
u_int8_t affymetrix_calvin_io::CHPExpressionEntry::GetChange () const [inline]
Gets the change call.
Definition at line 161 of file CHPExpressionEntry.h.
References change.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
float affymetrix_calvin_io::CHPExpressionEntry::GetChangePValue () const [inline]
Gets the change p-value.
Definition at line 164 of file CHPExpressionEntry.h.
References changePValue.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
u_int16_t affymetrix_calvin_io::CHPExpressionEntry::GetCommonPairs () const [inline]
Gets the number of probe pairs in common between control and experiment.
Definition at line 176 of file CHPExpressionEntry.h.
References commonPairs.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
u_int8_t affymetrix_calvin_io::CHPExpressionEntry::GetDetection () const [inline]
Get the detection call.
Definition at line 143 of file CHPExpressionEntry.h.
References detection.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
float affymetrix_calvin_io::CHPExpressionEntry::GetDetectionPValue () const [inline]
Gets the detection p-value.
Definition at line 146 of file CHPExpressionEntry.h.
References detectionPValue.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
bool affymetrix_calvin_io::CHPExpressionEntry::GetHasComparisonData () const [inline]
A flag to indicate if comparison data exists.
Definition at line 158 of file CHPExpressionEntry.h.
References hasComparisonData.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
u_int16_t affymetrix_calvin_io::CHPExpressionEntry::GetNumPairs () const [inline]
Gets the number of probe pairs in the set.
Definition at line 152 of file CHPExpressionEntry.h.
References numPairs.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
u_int16_t affymetrix_calvin_io::CHPExpressionEntry::GetNumPairsUsed () const [inline]
Gets the number of probe pairs used in the analysis.
Definition at line 155 of file CHPExpressionEntry.h.
References numPairsUsed.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
std::string affymetrix_calvin_io::CHPExpressionEntry::GetProbeSetName () const [inline]
Gets the probe set name.
Definition at line 140 of file CHPExpressionEntry.h.
References probeSetName.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetProbeSetName(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
float affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatio () const [inline]
Gets the signal log ratio.
Definition at line 167 of file CHPExpressionEntry.h.
References sigLogRatio.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
float affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatioHi () const [inline]
Gets the signal log ratio high.
Definition at line 173 of file CHPExpressionEntry.h.
References sigLogRatioHi.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
float affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatioLo () const [inline]
Gets the signal log ratio low.
Definition at line 170 of file CHPExpressionEntry.h.
References sigLogRatioLo.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
float affymetrix_calvin_io::CHPExpressionEntry::GetSignal () const [inline]
Gets the signal value.
Definition at line 149 of file CHPExpressionEntry.h.
References signal.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetExpressionResults(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteExpressionEntry().
CHPExpressionEntry CHPExpressionEntry::operator= (CHPExpressionEntry e)
Assignment operator
Parameters:
e The entry to copy
Returns:
The new object
Definition at line 101 of file CHPExpressionEntry.cpp.
References change, changePValue, commonPairs, detection, detectionPValue, GetChange(), GetChangePValue(), GetCommonPairs(), GetDetection(), GetDetectionPValue(), GetHasComparisonData(), GetNumPairs(), GetNumPairsUsed(), GetProbeSetName(), GetSigLogRatio(), GetSigLogRatioHi(), GetSigLogRatioLo(), GetSignal(), hasComparisonData, numPairs, numPairsUsed, probeSetName, sigLogRatio, sigLogRatioHi, sigLogRatioLo, and signal.
void affymetrix_calvin_io::CHPExpressionEntry::SetChange (u_int8_t p) [inline]
Sets the change call.
Definition at line 200 of file CHPExpressionEntry.h.
References change.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetChangePValue (float p) [inline]
Sets the change p-value.
Definition at line 203 of file CHPExpressionEntry.h.
References changePValue.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetCommonPairs (u_int16_t p) [inline]
Sets the number of probe pairs in common between control and experiment.
Definition at line 215 of file CHPExpressionEntry.h.
References commonPairs.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetDetection (u_int8_t p) [inline]
Sets the detection value.
Definition at line 182 of file CHPExpressionEntry.h.
References detection.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetDetectionPValue (float p) [inline]
Sets the detection p-value.
Definition at line 185 of file CHPExpressionEntry.h.
References detectionPValue.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetHasComparisonData (bool b) [inline]
Sets the flag to indicate if comparison data exists.
Definition at line 197 of file CHPExpressionEntry.h.
References hasComparisonData.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetNumPairs (u_int16_t p) [inline]
Sets the number of pairs in the probe sets.
Definition at line 191 of file CHPExpressionEntry.h.
References numPairs.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetNumPairsUsed (u_int16_t p) [inline]
Sets the number of pairs used in the analysis.
Definition at line 194 of file CHPExpressionEntry.h.
References numPairsUsed.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetProbeSetName (const std::string & p) [inline]
Sets the probe set name.
Definition at line 179 of file CHPExpressionEntry.h.
References probeSetName.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetSigLogRatio (float p) [inline]
Sets the signal log ratio.
Definition at line 206 of file CHPExpressionEntry.h.
References sigLogRatio.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetSigLogRatioHi (float p) [inline]
Sets the signal log ratio high.
Definition at line 212 of file CHPExpressionEntry.h.
References sigLogRatioHi.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetSigLogRatioLo (float p) [inline]
Sets the signal log ratio low.
Definition at line 209 of file CHPExpressionEntry.h.
References sigLogRatioLo.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void affymetrix_calvin_io::CHPExpressionEntry::SetSignal (float p) [inline]
Sets the signal value.
Definition at line 188 of file CHPExpressionEntry.h.
References signal.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
Member Data Documentation
u_int8_t affymetrix_calvin_io::CHPExpressionEntry::change [private]
The change call.
Definition at line 61 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetChange(), operator=(), and SetChange().
float affymetrix_calvin_io::CHPExpressionEntry::changePValue [private]
The change p-value.
Definition at line 64 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetChangePValue(), operator=(), and SetChangePValue().
u_int16_t affymetrix_calvin_io::CHPExpressionEntry::commonPairs [private]
The number of probe pairs in common between control and experiment.
Definition at line 76 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetCommonPairs(), operator=(), and SetCommonPairs().
u_int8_t affymetrix_calvin_io::CHPExpressionEntry::detection [private]
The detection call.
Definition at line 43 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetDetection(), operator=(), and SetDetection().
float affymetrix_calvin_io::CHPExpressionEntry::detectionPValue [private]
The detection p-value.
Definition at line 46 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetDetectionPValue(), operator=(), and SetDetectionPValue().
bool affymetrix_calvin_io::CHPExpressionEntry::hasComparisonData [private]
A flag to indicate if comparison data exists.
Definition at line 58 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetHasComparisonData(), operator=(), and SetHasComparisonData().
u_int16_t affymetrix_calvin_io::CHPExpressionEntry::numPairs [private]
The number of probe pairs in the probe set.
Definition at line 52 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetNumPairs(), operator=(), and SetNumPairs().
u_int16_t affymetrix_calvin_io::CHPExpressionEntry::numPairsUsed [private]
The number of probe pairs used in the analysis.
Definition at line 55 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetNumPairsUsed(), operator=(), and SetNumPairsUsed().
std::string affymetrix_calvin_io::CHPExpressionEntry::probeSetName [private]
The probe set name.
Definition at line 40 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetProbeSetName(), operator=(), and SetProbeSetName().
float affymetrix_calvin_io::CHPExpressionEntry::sigLogRatio [private]
The signal log ratio.
Definition at line 67 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetSigLogRatio(), operator=(), and SetSigLogRatio().
float affymetrix_calvin_io::CHPExpressionEntry::sigLogRatioHi [private]
The signal log ratio high.
Definition at line 73 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetSigLogRatioHi(), operator=(), and SetSigLogRatioHi().
float affymetrix_calvin_io::CHPExpressionEntry::sigLogRatioLo [private]
The signal log ratio low.
Definition at line 70 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetSigLogRatioLo(), operator=(), and SetSigLogRatioLo().
float affymetrix_calvin_io::CHPExpressionEntry::signal [private]
The signal.
Definition at line 49 of file CHPExpressionEntry.h.
Referenced by CHPExpressionEntry(), Clear(), GetSignal(), operator=(), and SetSignal().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CHPExpressionEntry.h
C:/f112/affy/sdk/calvin_files/data/src/CHPExpressionEntry.cpp