Affymetrix Fusion SDK: CalvinDataGroup Class Reference
CalvinDataGroup Class Reference
#include <Calvin.h>
Public Member Functions
CalvinDataGroup ()
virtual ~CalvinDataGroup ()
void clear ()
void setName (const AffxString &str)
AffxString & getName ()
AffxArray< CalvinDataSet > & getCalvinDataSets ()
int compareTo (CalvinDataGroup &that, int iCompareCode)
Protected Attributes
AffxString m_strName
AffxArray< CalvinDataSet > m_vCalvinDataSets
Detailed Description
Definition at line 237 of file Calvin.h.
Constructor & Destructor Documentation
CalvinDataGroup::CalvinDataGroup () [inline]
Definition at line 244 of file Calvin.h.
virtual CalvinDataGroup::~CalvinDataGroup () [inline, virtual]
Definition at line 247 of file Calvin.h.
References clear().
Member Function Documentation
void CalvinDataGroup::clear () [inline]
Definition at line 252 of file Calvin.h.
References AffxArray< TYPE >::deleteAll(), and m_vCalvinDataSets.
Referenced by ~CalvinDataGroup().
int CalvinDataGroup::compareTo (CalvinDataGroup & that, int iCompareCode) [inline]
Compare function.
Parameters:
that - A reference to an instance of this class.
iCompareCode - The code to switch on when doing compares. (Each code is a different compare.)
Returns:
- int value. (-1 if *this < that, 0 if *this == that, 1 if *this > that)
Definition at line 264 of file Calvin.h.
References AffxString::compareTo(), and m_strName.
AffxArray<CalvinDataSet>& CalvinDataGroup::getCalvinDataSets () [inline]
Definition at line 256 of file Calvin.h.
References m_vCalvinDataSets.
Referenced by Calvin::equivalent(), and Calvin::load().
AffxString& CalvinDataGroup::getName () [inline]
Definition at line 255 of file Calvin.h.
References m_strName.
Referenced by Calvin::equivalent().
void CalvinDataGroup::setName (const AffxString & str) [inline]
Definition at line 254 of file Calvin.h.
References m_strName.
Referenced by Calvin::load().
Member Data Documentation
AffxString CalvinDataGroup::m_strName [protected]
Definition at line 240 of file Calvin.h.
Referenced by compareTo(), getName(), and setName().
AffxArray<CalvinDataSet> CalvinDataGroup::m_vCalvinDataSets [protected]
Definition at line 241 of file Calvin.h.
Referenced by clear(), and getCalvinDataSets().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/calvin_files/utils/src/Calvin.h