Affymetrix Fusion SDK: affymetrix_fusion_io::FusionBaseCallType Class Reference
affymetrix_fusion_io::FusionBaseCallType Class Reference
#include <FusionProbeSetResults.h>
Public Member Functions
FusionBaseCallType ()
FusionBaseCallType (int32_t p, int8_t c)
~FusionBaseCallType ()
void Clear ()
int32_t GetPosition () const
int8_t GetCall () const
void SetPosition (int32_t p)
void SetCall (int8_t c)
Protected Attributes
int32_t position
int8_t call
Detailed Description
A structure to hold a base call at a given position (index).
Definition at line 422 of file FusionProbeSetResults.h.
Constructor & Destructor Documentation
FusionBaseCallType::FusionBaseCallType ()
Constructor.
Definition at line 442 of file FusionProbeSetResults.cpp.
References Clear().
FusionBaseCallType::FusionBaseCallType (int32_t p, int8_t c)
Constructor with values.
Parameters:
p The position.
c The call.
Definition at line 447 of file FusionProbeSetResults.cpp.
References call, and position.
FusionBaseCallType::~FusionBaseCallType ()
Destructor
Definition at line 453 of file FusionProbeSetResults.cpp.
References Clear().
Member Function Documentation
void FusionBaseCallType::Clear (void)
Clears the values.
Reimplemented in affymetrix_fusion_io::FusionForceCallType.
Definition at line 458 of file FusionProbeSetResults.cpp.
References call, and position.
Referenced by FusionBaseCallType(), and ~FusionBaseCallType().
int8_t affymetrix_fusion_io::FusionBaseCallType::GetCall () const [inline]
Gets the call.
Returns:
The call
Definition at line 456 of file FusionProbeSetResults.h.
References call.
Referenced by CFusionForceCallTypeCOM::get_Call(), and CFusionBaseCallTypeCOM::get_Call().
int32_t affymetrix_fusion_io::FusionBaseCallType::GetPosition () const [inline]
Gets the position.
Returns:
The position.
Definition at line 451 of file FusionProbeSetResults.h.
References position.
Referenced by CFusionForceCallTypeCOM::get_Position(), and CFusionBaseCallTypeCOM::get_Position().
void affymetrix_fusion_io::FusionBaseCallType::SetCall (int8_t c) [inline]
Sets the call.
Parameters:
c The call.
Definition at line 466 of file FusionProbeSetResults.h.
References call.
void affymetrix_fusion_io::FusionBaseCallType::SetPosition (int32_t p) [inline]
Sets the position
Parameters:
p The position.
Definition at line 461 of file FusionProbeSetResults.h.
References position.
Member Data Documentation
int8_t affymetrix_fusion_io::FusionBaseCallType::call [protected]
The call.
Definition at line 429 of file FusionProbeSetResults.h.
Referenced by Clear(), affymetrix_fusion_io::FusionForceCallType::Clear(), FusionBaseCallType(), affymetrix_fusion_io::FusionForceCallType::FusionForceCallType(), GetCall(), and SetCall().
int32_t affymetrix_fusion_io::FusionBaseCallType::position [protected]
The position (index) of the call.
Definition at line 426 of file FusionProbeSetResults.h.
Referenced by Clear(), affymetrix_fusion_io::FusionForceCallType::Clear(), FusionBaseCallType(), affymetrix_fusion_io::FusionForceCallType::FusionForceCallType(), GetPosition(), and SetPosition().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.cpp