Affymetrix Fusion SDK: affymetrix_calvin_parameter::ParameterFileData Class Reference
affymetrix_calvin_parameter::ParameterFileData Class Reference
#include <ParameterFileData.h>
Public Member Functions
void Clear ()
ParameterFileData ()
ParameterFileAttributesType & ParameterFileAttributes ()
ImplementationAttributesType & ImplementationAttributes ()
ParameterTypeList & Parameters ()
Private Attributes
ParameterFileAttributesType parameterFileAttributes
ImplementationAttributesType implementationAttributes
ParameterTypeList parameters
Detailed Description
Provides data storage for ParameterFile files. This version does not store all of the contents of a parameter file. Missing items includes the ParameterSet, MetaData and Control elements.
Definition at line 78 of file ParameterFileData.h.
Constructor & Destructor Documentation
ParameterFileData::ParameterFileData ()
Constructor.
Definition at line 29 of file ParameterFileData.cpp.
References Clear().
Member Function Documentation
void ParameterFileData::Clear (void)
Clears the members in the class.
Definition at line 37 of file ParameterFileData.cpp.
References affymetrix_calvin_parameter::_ParameterFileAttributesType::company, affymetrix_calvin_parameter::_ParameterFileAttributesType::contentVersion, affymetrix_calvin_parameter::_ImplementationAttributesType::description, affymetrix_calvin_parameter::_ImplementationAttributesType::executableFileName, implementationAttributes, affymetrix_calvin_parameter::_ImplementationAttributesType::name, parameterFileAttributes, parameters, affymetrix_calvin_parameter::_ParameterFileAttributesType::userName, and affymetrix_calvin_parameter::_ImplementationAttributesType::version.
Referenced by ParameterFileData(), and affymetrix_calvin_io::ParameterFileReader::Read().
ImplementationAttributesType& affymetrix_calvin_parameter::ParameterFileData::ImplementationAttributes () [inline]
The implementation attributes.
Definition at line 91 of file ParameterFileData.h.
References implementationAttributes.
Referenced by affymetrix_calvin_io::SAXParameterFileHandlers::StoreImplementationAttributes().
ParameterFileAttributesType& affymetrix_calvin_parameter::ParameterFileData::ParameterFileAttributes () [inline]
The parameter file attributes.
Definition at line 88 of file ParameterFileData.h.
References parameterFileAttributes.
Referenced by affymetrix_calvin_io::SAXParameterFileHandlers::StoreParameterFileAttributes().
ParameterTypeList& affymetrix_calvin_parameter::ParameterFileData::Parameters () [inline]
The list of parameters.
Definition at line 94 of file ParameterFileData.h.
References parameters.
Referenced by affymetrix_calvin_io::SAXParameterFileHandlers::StoreParameterAttributes().
Member Data Documentation
ImplementationAttributesType affymetrix_calvin_parameter::ParameterFileData::implementationAttributes [private]
The implementation attributes.
Definition at line 101 of file ParameterFileData.h.
Referenced by Clear(), and ImplementationAttributes().
ParameterFileAttributesType affymetrix_calvin_parameter::ParameterFileData::parameterFileAttributes [private]
The parameter file attributes.
Definition at line 98 of file ParameterFileData.h.
Referenced by Clear(), and ParameterFileAttributes().
ParameterTypeList affymetrix_calvin_parameter::ParameterFileData::parameters [private]
The list of parameters.
Definition at line 104 of file ParameterFileData.h.
Referenced by Clear(), and Parameters().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parameter/src/ParameterFileData.h
C:/f112/affy/sdk/calvin_files/parameter/src/ParameterFileData.cpp