Affymetrix Fusion SDK: Calvin Class Reference
Calvin Class Reference
#include <Calvin.h>
Public Member Functions
Calvin ()
virtual ~Calvin ()
void clear ()
AffxString & getFileName ()
CalvinHeader & getCalvinHeader ()
AffxArray< CalvinHeader > & getParentCalvinHeaders ()
AffxArray< CalvinDataGroup > & getCalvinDataGroups ()
bool load (const AffxString &strFileName)
bool equivalent (Calvin &that, std::set< std::string > &setIgnore, std::map< std::string, float > &mapEpsilon, float fEpsilon=0.0001, bool bCheckHeader=true, float fFraction=0.0)
Static Public Member Functions
static void test ()
static bool equivalent (const AffxString &strFileName1, const AffxString &strFileName2, std::set< std::string > &setIgnore, std::set< std::string > &setSetIgnore, std::map< std::string, float > &mapEpsilon, float fEpsilon=0.0001, double dCorrelationCutoff=1.0, bool bCheckHeader=true, int iMessageLimit=1000, float fFraction=0.0)
static bool equivalent (const AffxString &strFileName1, const AffxString &strFileName2, std::set< std::string > &setIgnore, std::map< std::string, float > &mapEpsilon, float fEpsilon=0.0001, double dCorrelationCutoff=1.0, bool bCheckHeader=true, int iMessageLimit=1000, float fFraction=0.0)
Protected Member Functions
void loadHeader (affymetrix_calvin_io::GenericDataHeader &Header, CalvinHeader &header)
bool equivalentHeader (const AffxString &strPrompt, CalvinHeader &headerThis, CalvinHeader &headerThat, std::set< std::string > &setIgnore, std::map< std::string, float > &mapEpsilon, float fEpsilon, float fFraction=0.0)
Static Protected Member Functions
static bool equivalentParameter (const AffxString &strPrompt, CalvinParameter &This, CalvinParameter &That, std::set< std::string > &setIgnore, std::map< std::string, float > &mapEpsilon, float fEpsilon, float fFraction=0.0)
static bool equivalentHeader (const AffxString &strPrompt, affymetrix_calvin_io::GenericDataHeader &Header1, affymetrix_calvin_io::GenericDataHeader &Header2, std::set< std::string > &setIgnore, std::map< std::string, float > &mapEpsilon, float fEpsilon, float fFraction=0.0)
Protected Attributes
AffxString m_strFileName
CalvinHeader m_objCalvinHeader
AffxArray< CalvinHeader > m_vParentCalvinHeaders
AffxArray< CalvinDataGroup > m_vCalvinDataGroups
Detailed Description
Definition at line 277 of file Calvin.h.
Constructor & Destructor Documentation
Calvin::Calvin () [inline]
Definition at line 288 of file Calvin.h.
virtual Calvin::~Calvin () [inline, virtual]
Definition at line 292 of file Calvin.h.
References clear().
Member Function Documentation
void Calvin::clear () [inline]
Definition at line 297 of file Calvin.h.
References CalvinHeader::clear(), AffxArray< TYPE >::deleteAll(), m_objCalvinHeader, m_vCalvinDataGroups, and m_vParentCalvinHeaders.
Referenced by load(), and ~Calvin().
bool Calvin::equivalent (Calvin & that, std::set< std::string > & setIgnore, std::map< std::string, float > & mapEpsilon, float fEpsilon = 0.0001, bool bCheckHeader = true, float fFraction = 0.0)
Definition at line 245 of file Calvin.cpp.
References equivalentHeader(), CalvinValue::FloatType, AffxArray< TYPE >::getAt(), getCalvinDataGroups(), CalvinDataGroup::getCalvinDataSets(), getCalvinHeader(), CalvinDataSet::getCalvinValues(), CalvinDataSet::getColumnHeaders(), AffxArray< TYPE >::getCount(), getDouble(), getInt(), CalvinDataSet::getName(), CalvinDataGroup::getName(), CalvinValue::getParameterType(), getParentCalvinHeaders(), CalvinValue::getValue(), Max, and Verbose::out().
Referenced by equivalent(), and test().
bool Calvin::equivalent (const AffxString & strFileName1, const AffxString & strFileName2, std::set< std::string > & setIgnore, std::set< std::string > & setSetIgnore, std::map< std::string, float > & mapEpsilon, float fEpsilon = 0.0001, double dCorrelationCutoff = 1.0, bool bCheckHeader = true, int iMessageLimit = 1000, float fFraction = 0.0) [static]
Definition at line 450 of file Calvin.cpp.
References affymetrix_calvin_io::DataSet::Cols(), Fs::convertToUncPath(), affymetrix_calvin_utilities::StringUtils::ConvertWCSToMBS(), affymetrix_calvin_io::GenericData::DataGroupNames(), affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::GenericData::DataSetNames(), affymetrix_calvin_io::DataSet::Delete(), affymetrix_calvin_exceptions::CalvinException::Description(), equivalentHeader(), equivalentParameter(), CalvinValue::FloatType, affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::DataSet::GetData(), getDouble(), getInt(), getUnsignedInt(), affymetrix_calvin_io::DataSet::Header(), affymetrix_calvin_io::GenericData::Header(), CalvinValue::Int16Type, CalvinValue::Int32Type, CalvinValue::Int8Type, Util::isFinite(), Max, Min, affymetrix_calvin_io::DataSet::Open(), affymetrix_calvin_io::GenericFileReader::Open(), Verbose::out(), affymetrix_calvin_io::DataSet::Rows(), affymetrix_calvin_io::GenericFileReader::SetFilename(), CalvinValue::TextType, ToStr(), CalvinValue::UInt16Type, CalvinValue::UInt32Type, CalvinValue::UInt8Type, and Except::what().
bool Calvin::equivalent (const AffxString & strFileName1, const AffxString & strFileName2, std::set< std::string > & setIgnore, std::map< std::string, float > & mapEpsilon, float fEpsilon = 0.0001, double dCorrelationCutoff = 1.0, bool bCheckHeader = true, int iMessageLimit = 1000, float fFraction = 0.0) [static]
Definition at line 426 of file Calvin.cpp.
References equivalent().
bool Calvin::equivalentHeader (const AffxString & strPrompt, CalvinHeader & headerThis, CalvinHeader & headerThat, std::set< std::string > & setIgnore, std::map< std::string, float > & mapEpsilon, float fEpsilon, float fFraction = 0.0) [protected]
Definition at line 353 of file Calvin.cpp.
References AffxArray< TYPE >::binarySearch(), equivalentParameter(), AffxArray< TYPE >::getAt(), AffxArray< TYPE >::getCount(), CalvinParameter::getName(), Verbose::out(), and AffxArray< TYPE >::quickSort().
Referenced by equivalent().
bool Calvin::equivalentHeader (const AffxString & strPrompt, affymetrix_calvin_io::GenericDataHeader & Header1, affymetrix_calvin_io::GenericDataHeader & Header2, std::set< std::string > & setIgnore, std::map< std::string, float > & mapEpsilon, float fEpsilon, float fFraction = 0.0) [static, protected]
Load the Calvin header into memory.
Parameters:
pHeader - A pointer to the affymetrix_calvin_io::GenericDataHeader for the specified Calvin file.
Definition at line 836 of file Calvin.cpp.
References CalvinValue::AsciiType, equivalentParameter(), CalvinValue::FloatType, getDouble(), affymetrix_calvin_io::GenericDataHeader::GetFileId(), affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), getInt(), affymetrix_calvin_io::GenericDataHeader::GetLocale(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::GenericDataHeader::GetNameValParam(), affymetrix_calvin_io::GenericDataHeader::GetNameValParamCnt(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), getUnsignedInt(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), CalvinValue::Int16Type, CalvinValue::Int32Type, CalvinValue::Int8Type, Verbose::out(), CalvinParameter::set(), CalvinValue::TextType, CalvinValue::UInt16Type, CalvinValue::UInt32Type, and CalvinValue::UInt8Type.
bool Calvin::equivalentParameter (const AffxString & strPrompt, CalvinParameter & This, CalvinParameter & That, std::set< std::string > & setIgnore, std::map< std::string, float > & mapEpsilon, float fEpsilon, float fFraction = 0.0) [static, protected]
Definition at line 384 of file Calvin.cpp.
References CalvinValue::FloatType, getDouble(), CalvinParameter::getName(), CalvinValue::getParameterType(), CalvinValue::getValue(), Max, and Verbose::out().
Referenced by equivalent(), and equivalentHeader().
AffxArray<CalvinDataGroup>& Calvin::getCalvinDataGroups () [inline]
Definition at line 302 of file Calvin.h.
References m_vCalvinDataGroups.
Referenced by equivalent(), and load().
CalvinHeader& Calvin::getCalvinHeader () [inline]
Definition at line 300 of file Calvin.h.
References m_objCalvinHeader.
Referenced by equivalent(), and load().
AffxString& Calvin::getFileName () [inline]
Definition at line 299 of file Calvin.h.
References m_strFileName.
AffxArray<CalvinHeader>& Calvin::getParentCalvinHeaders () [inline]
Definition at line 301 of file Calvin.h.
References m_vParentCalvinHeaders.
Referenced by equivalent(), and load().
bool Calvin::load (const AffxString & strFileName)
Read the Calvin file, and store the data in memory.
Parameters:
strFileName - The name of the Calvin file to load data from.
Returns:
- bool value. (true if successful)
Definition at line 72 of file Calvin.cpp.
References AffxArray< TYPE >::add(), affymetrix_calvin_io::GenericData::Clear(), clear(), affymetrix_calvin_io::DataSet::Close(), affymetrix_calvin_io::DataSet::Cols(), affymetrix_calvin_io::GenericData::DataGroupNames(), affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::GenericData::DataSetNames(), affymetrix_calvin_io::DataSet::Delete(), Err::errAbort(), CalvinValue::FloatType, getCalvinDataGroups(), CalvinDataGroup::getCalvinDataSets(), getCalvinHeader(), CalvinDataSet::getCalvinValues(), CalvinDataSet::getColumnHeaders(), affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::DataSet::GetData(), getDouble(), getInt(), getParentCalvinHeaders(), getUnsignedInt(), affymetrix_calvin_io::DataSet::Header(), affymetrix_calvin_io::GenericData::Header(), CalvinValue::Int16Type, CalvinValue::Int32Type, CalvinValue::Int8Type, loadHeader(), m_strFileName, affymetrix_calvin_io::DataSet::Open(), affymetrix_calvin_io::GenericFileReader::Open(), Verbose::out(), AffxArray< TYPE >::reserve(), affymetrix_calvin_io::DataSet::Rows(), affymetrix_calvin_io::GenericFileReader::SetFilename(), CalvinDataSet::setName(), CalvinDataGroup::setName(), CalvinValue::TextType, CalvinValue::UInt16Type, CalvinValue::UInt32Type, and CalvinValue::UInt8Type.
void Calvin::loadHeader (affymetrix_calvin_io::GenericDataHeader & Header, CalvinHeader & header) [protected]
Load the Calvin header into memory.
Parameters:
Header - A pointer to the affymetrix_calvin_io::GenericDataHeader for the specified Calvin file.
Definition at line 192 of file Calvin.cpp.
References AffxArray< TYPE >::add(), CalvinValue::AsciiType, CalvinValue::FloatType, getDouble(), affymetrix_calvin_io::GenericDataHeader::GetFileId(), affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), getInt(), affymetrix_calvin_io::GenericDataHeader::GetLocale(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), affymetrix_calvin_io::GenericDataHeader::GetNameValParam(), affymetrix_calvin_io::GenericDataHeader::GetNameValParamCnt(), affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), getUnsignedInt(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), CalvinValue::Int16Type, CalvinValue::Int32Type, CalvinValue::Int8Type, AffxArray< TYPE >::reserve(), CalvinValue::TextType, CalvinValue::UInt16Type, CalvinValue::UInt32Type, and CalvinValue::UInt8Type.
Referenced by load().
void Calvin::test () [static]
Definition at line 30 of file Calvin.cpp.
References equivalent(), and Verbose::out().
Member Data Documentation
CalvinHeader Calvin::m_objCalvinHeader [protected]
Definition at line 281 of file Calvin.h.
Referenced by clear(), and getCalvinHeader().
AffxString Calvin::m_strFileName [protected]
Definition at line 280 of file Calvin.h.
Referenced by getFileName(), and load().
AffxArray<CalvinDataGroup> Calvin::m_vCalvinDataGroups [protected]
Definition at line 283 of file Calvin.h.
Referenced by clear(), and getCalvinDataGroups().
AffxArray<CalvinHeader> Calvin::m_vParentCalvinHeaders [protected]
Definition at line 282 of file Calvin.h.
Referenced by clear(), and getParentCalvinHeaders().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/utils/src/Calvin.h
C:/f112/affy/sdk/calvin_files/utils/src/Calvin.cpp