Affymetrix Fusion SDK: CFusionGenotypeProbeSetResultsCOM Class Reference
CFusionGenotypeProbeSetResultsCOM Class Reference
#include <FusionGenotypeProbeSetResultsCOM.h>
Public Member Functions
CFusionGenotypeProbeSetResultsCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_fusion_io::FusionGenotypeProbeSetResults & Results ()
STDMETHOD() get_AlleleCall (CHAR *pVal)
STDMETHOD() get_Confidence (float *pVal)
STDMETHOD() get_RAS1 (float *pVal)
STDMETHOD() get_RAS2 (float *pVal)
STDMETHOD() get_PValueAA (float *pVal)
STDMETHOD() get_PValueAB (float *pVal)
STDMETHOD() get_PValueBB (float *pVal)
STDMETHOD() get_PValueNoCall (float *pVal)
STDMETHOD() GetAlleleCallString (BSTR *pVal)
Private Attributes
affymetrix_fusion_io::FusionGenotypeProbeSetResults results
Detailed Description
Definition at line 30 of file FusionGenotypeProbeSetResultsCOM.h.
Constructor & Destructor Documentation
CFusionGenotypeProbeSetResultsCOM::CFusionGenotypeProbeSetResultsCOM () [inline]
Definition at line 37 of file FusionGenotypeProbeSetResultsCOM.h.
Member Function Documentation
HRESULT CFusionGenotypeProbeSetResultsCOM::FinalConstruct () [inline]
Definition at line 56 of file FusionGenotypeProbeSetResultsCOM.h.
void CFusionGenotypeProbeSetResultsCOM::FinalRelease () [inline]
Definition at line 61 of file FusionGenotypeProbeSetResultsCOM.h.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::get_AlleleCall (CHAR * pVal)
Definition at line 42 of file FusionGenotypeProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetAlleleCall(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::get_Confidence (float * pVal)
Definition at line 48 of file FusionGenotypeProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetConfidence(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::get_PValueAA (float * pVal)
Definition at line 66 of file FusionGenotypeProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetPValueAA(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::get_PValueAB (float * pVal)
Definition at line 72 of file FusionGenotypeProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetPValueAB(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::get_PValueBB (float * pVal)
Definition at line 78 of file FusionGenotypeProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetPValueBB(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::get_PValueNoCall (float * pVal)
Definition at line 84 of file FusionGenotypeProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetPValueNoCall(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::get_RAS1 (float * pVal)
Definition at line 54 of file FusionGenotypeProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetRAS1(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::get_RAS2 (float * pVal)
Definition at line 60 of file FusionGenotypeProbeSetResultsCOM.cpp.
References affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetRAS2(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::GetAlleleCallString (BSTR * pVal)
Definition at line 90 of file FusionGenotypeProbeSetResultsCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionGenotypeProbeSetResults::GetAlleleCallString(), and results.
STDMETHODIMP CFusionGenotypeProbeSetResultsCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 27 of file FusionGenotypeProbeSetResultsCOM.cpp.
affymetrix_fusion_io::FusionGenotypeProbeSetResults& CFusionGenotypeProbeSetResultsCOM::Results () [inline]
Definition at line 69 of file FusionGenotypeProbeSetResultsCOM.h.
Referenced by CFusionCHPLegacyDataCOM::GetGenotypingResults().
Member Data Documentation
affymetrix_fusion_io::FusionGenotypeProbeSetResults CFusionGenotypeProbeSetResultsCOM::results [private]
Definition at line 66 of file FusionGenotypeProbeSetResultsCOM.h.
Referenced by get_AlleleCall(), get_Confidence(), get_PValueAA(), get_PValueAB(), get_PValueBB(), get_PValueNoCall(), get_RAS1(), get_RAS2(), and GetAlleleCallString().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionGenotypeProbeSetResultsCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionGenotypeProbeSetResultsCOM.cpp