Affymetrix Fusion SDK: affymetrix_calvin_io::CDFQCProbeSetInformation Class Reference
affymetrix_calvin_io::CDFQCProbeSetInformation Class Reference
#include <CDFQCProbeSetInformation.h>
Public Member Functions
CDFQCProbeSetInformation ()
~CDFQCProbeSetInformation ()
std::wstring GetQCProbeSetType () const
int32_t GetNumCells () const
void GetProbeInformation (int index, CDFQCProbeInformation &info)
Protected Member Functions
void SetDataSet (DataSet *ds)
Protected Attributes
DataSet * dataSet
Friends
class CDFData
Detailed Description
Class that exposes the CDF QC probe set information
Definition at line 44 of file CDFQCProbeSetInformation.h.
Constructor & Destructor Documentation
CDFQCProbeSetInformation::CDFQCProbeSetInformation ()
Constructor
Definition at line 30 of file CDFQCProbeSetInformation.cpp.
References dataSet.
CDFQCProbeSetInformation::~CDFQCProbeSetInformation ()
Destructor
Definition at line 35 of file CDFQCProbeSetInformation.cpp.
References affymetrix_calvin_io::DataSet::Close(), dataSet, and affymetrix_calvin_io::DataSet::Delete().
Member Function Documentation
int32_t CDFQCProbeSetInformation::GetNumCells () const
Get the number of cells in the probe set - number of rows in the DataSet
Definition at line 55 of file CDFQCProbeSetInformation.cpp.
References dataSet, and affymetrix_calvin_io::DataSet::Rows().
void affymetrix_calvin_io::CDFQCProbeSetInformation::GetProbeInformation (int index, CDFQCProbeInformation & info)
Get the QC probe information
Referenced by affymetrix_fusion_io::FusionCDFQCProbeInformation::Initialize().
std::wstring CDFQCProbeSetInformation::GetQCProbeSetType () const
Get the QC type - DataSet name
Definition at line 47 of file CDFQCProbeSetInformation.cpp.
References dataSet, affymetrix_calvin_io::DataSetHeader::GetName(), and affymetrix_calvin_io::DataSet::Header().
void CDFQCProbeSetInformation::SetDataSet (DataSet * ds) [protected]
Definition at line 62 of file CDFQCProbeSetInformation.cpp.
References affymetrix_calvin_io::DataSet::Close(), dataSet, affymetrix_calvin_io::DataSet::Delete(), and affymetrix_calvin_io::DataSet::Open().
Referenced by affymetrix_calvin_io::CDFData::GetQCProbeSetInformation().
Friends And Related Function Documentation
friend class CDFData [friend]
Definition at line 66 of file CDFQCProbeSetInformation.h.
Member Data Documentation
DataSet* affymetrix_calvin_io::CDFQCProbeSetInformation::dataSet [protected]
DataSet pointer
Definition at line 64 of file CDFQCProbeSetInformation.h.
Referenced by CDFQCProbeSetInformation(), GetNumCells(), affxcdf::CCDFQCProbeSetInformation::GetProbeInformation(), GetQCProbeSetType(), SetDataSet(), and ~CDFQCProbeSetInformation().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CDFQCProbeSetInformation.h
C:/f112/affy/sdk/calvin_files/data/src/CDFQCProbeSetInformation.cpp