Affymetrix Fusion SDK: affymetrix_calvin_io::TextFileReader Class Reference
affymetrix_calvin_io::TextFileReader Class Reference
#include <TextFileReader.h>
Public Member Functions
TextFileReader ()
~TextFileReader ()
void ReadFile (const std::string &fileName, std::map< std::string, std::string > &textData)
void ReadFile (std::ifstream &fileStream, std::map< std::string, std::string > &textData)
Protected Member Functions
void ReadFileBody (std::ifstream &fileStream, std::map< std::string, std::string > &textData)
Detailed Description
This class provides interfaces to store text parameter information.
Definition at line 43 of file TextFileReader.h.
Constructor & Destructor Documentation
TextFileReader::TextFileReader ()
Constructor
Definition at line 35 of file TextFileReader.cpp.
TextFileReader::~TextFileReader ()
Destructor
Definition at line 42 of file TextFileReader.cpp.
Member Function Documentation
void TextFileReader::ReadFile (const std::string & fileName, std::map< std::string, std::string > & textData)
Reads the entire contents of the file.
Parameters:
fileName The name of the text file to read.
textData The text file parameter name/value pairs.
Exceptions:
affymetrix_calvin_exceptions::CFileNotFoundException The file does not exist.
Definition at line 49 of file TextFileReader.cpp.
References Fs::aptOpen(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), and ReadFileBody().
void TextFileReader::ReadFile (std::ifstream & fileStream, std::map< std::string, std::string > & textData)
Reads the entire contents of the file.
Parameters:
fileStream The file stream of the open text file.
textData The text file parameter name/value pairs.
Definition at line 66 of file TextFileReader.cpp.
References ReadFileBody().
void TextFileReader::ReadFileBody (std::ifstream & fileStream, std::map< std::string, std::string > & textData) [protected]
Reads the body of the file.
Parameters:
fileStream The file stream.
textData The parameter name/value pairs.
Definition at line 76 of file TextFileReader.cpp.
Referenced by ReadFile().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/TextFileReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/TextFileReader.cpp