Affymetrix Fusion SDK: affymetrix_calvin_io::ArrayFileWriter Class Reference
affymetrix_calvin_io::ArrayFileWriter Class Reference
#include <ArrayFileWriter.h>
Public Member Functions
ArrayFileWriter ()
~ArrayFileWriter ()
bool Write (const std::string &fileName, affymetrix_calvin_array::ArrayData &arrayData)
Protected Attributes
affymetrix_calvin_utilities::AffymetrixGuidType dataTypeIdentifier
Detailed Description
This class provides interfaces to write an array file.
Definition at line 40 of file ArrayFileWriter.h.
Constructor & Destructor Documentation
ArrayFileWriter::ArrayFileWriter ()
Constructor
Definition at line 268 of file ArrayFileWriter.cpp.
References ARRAY_FILE_TYPE_IDENTIFIER.
ArrayFileWriter::~ArrayFileWriter ()
Destructor
Definition at line 276 of file ArrayFileWriter.cpp.
Member Function Documentation
bool ArrayFileWriter::Write (const std::string & fileName, affymetrix_calvin_array::ArrayData & arrayData)
Writes the array object to an array file.
Parameters:
fileName The name of the array file to write.
arrayData The array data to write to the file.
Returns:
True if the file was successfully written.
Definition at line 283 of file ArrayFileWriter.cpp.
References AddPhysicalArrays(), AddUserAttributes(), ARRAY_FILE_ENCODING, CreateArrayElement(), and ToXMLCh.
Member Data Documentation
affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_calvin_io::ArrayFileWriter::dataTypeIdentifier [protected]
An identifier to the type of data stored in the file
Definition at line 52 of file ArrayFileWriter.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/ArrayFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/ArrayFileWriter.cpp