Affymetrix Fusion SDK: Util::StaticMem Class Reference
Util::StaticMem Class Reference
Public Member Functions
StaticMem ()
uint64_t getMemFreeAtStart ()
uint64_t getMemFreeAtBlock ()
void pushMemFreeAtStart (uint64_t mem)
uint64_t popMemFreeAtStart ()
Private Attributes
std::vector< uint64_t > m_MemFreeAtStart
Detailed Description
Definition at line 469 of file Util.h.
Constructor & Destructor Documentation
Util::StaticMem::StaticMem () [inline]
Definition at line 471 of file Util.h.
References Util::memInfo().
Member Function Documentation
uint64_t Util::StaticMem::getMemFreeAtBlock () [inline]
Definition at line 479 of file Util.h.
Referenced by Util::getMemFreeAtBlock().
uint64_t Util::StaticMem::getMemFreeAtStart () [inline]
Definition at line 476 of file Util.h.
Referenced by Util::getMemFreeAtStart().
uint64_t Util::StaticMem::popMemFreeAtStart () [inline]
Definition at line 485 of file Util.h.
Referenced by Util::popMemFreeAtStart().
void Util::StaticMem::pushMemFreeAtStart (uint64_t mem) [inline]
Definition at line 482 of file Util.h.
Referenced by Util::pushMemFreeAtStart().
Member Data Documentation
std::vector<uint64_t> Util::StaticMem::m_MemFreeAtStart [private]
Definition at line 492 of file Util.h.
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/Util.h