Affymetrix Fusion SDK: SocketClient Class Reference
SocketClient Class Reference
#include <SocketClient.h>
Public Member Functions
SocketClient ()
Constructor.
~SocketClient ()
Destructor closes sockets.
void cleanUp ()
void socketConnect (const std::string &host, const std::string &port)
void checkForMsgs (std::vector< std::string > &messages)
void sendMsg (const std::string &msg, int type, int channel)
Private Attributes
int m_Socket
listening socket descriptor
std::string m_Host
Host connected to.
std::string m_Port
Port that client is connected to.
std::vector< int > m_Sockets
List of open sockets/file descriptors currently connected to, sorted by file descriptor.
Detailed Description
Class for reading and writing to a server over a socket.
Definition at line 39 of file SocketClient.h.
Constructor & Destructor Documentation
SocketClient::SocketClient ()
Constructor.
Definition at line 40 of file SocketClient.cpp.
References APT_ERR_ABORT, Err::configureErrHandler(), Err::setExitOnError(), Err::setExitOnErrorValue(), Err::setNewLineOnError(), and Err::setThrowStatus().
SocketClient::~SocketClient ()
Destructor closes sockets.
Definition at line 57 of file SocketClient.cpp.
Member Function Documentation
void SocketClient::checkForMsgs (std::vector< std::string > & messages)
Try reading from the socket to see if there is anything sent.
Parameters:
messages - data from the socket as delivered by recv()
Definition at line 113 of file SocketClient.cpp.
References APT_ERR_ABORT, and SocketBase::checkForMsgs().
void SocketClient::cleanUp ()
Definition at line 61 of file SocketClient.cpp.
References CLOSE_SOCKET.
void SocketClient::sendMsg (const std::string & msg, int type, int channel)
Write string to open socket.
Parameters:
msg - Message to write into the socket
Definition at line 120 of file SocketClient.cpp.
References APT_ERR_ABORT, and SocketBase::sendMsg().
void SocketClient::socketConnect (const std::string & host, const std::string & port)
Open a connection to a listening server.
Parameters:
host - ip address or name of computer to connect to, often just 127.0.0.1
port - which port to try and connect on.
Definition at line 71 of file SocketClient.cpp.
References APT_ERR_ABORT, APT_ERR_ASSERT, CLOSE_SOCKET, Verbose::out(), and ToStr().
Member Data Documentation
std::string SocketClient::m_Host [private]
Host connected to.
Definition at line 73 of file SocketClient.h.
std::string SocketClient::m_Port [private]
Port that client is connected to.
Definition at line 74 of file SocketClient.h.
int SocketClient::m_Socket [private]
listening socket descriptor
Definition at line 72 of file SocketClient.h.
std::vector<int> SocketClient::m_Sockets [private]
List of open sockets/file descriptors currently connected to, sorted by file descriptor.
Definition at line 75 of file SocketClient.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/SocketClient.h
C:/f112/affy/sdk/util/SocketClient.cpp