Affymetrix Fusion SDK: CFusionCDFProbeGroupInformationCOM Class Reference
CFusionCDFProbeGroupInformationCOM Class Reference
#include <FusionCDFProbeGroupInformationCOM.h>
Public Member Functions
CFusionCDFProbeGroupInformationCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_fusion_io::FusionCDFProbeGroupInformation & Group ()
STDMETHOD() get_Direction (DirectionType *pVal)
STDMETHOD() get_NumLists (int *pVal)
STDMETHOD() get_NumCells (int *pVal)
STDMETHOD() get_NumCellsPerList (int *pVal)
STDMETHOD() get_Start (int *pVal)
STDMETHOD() get_Stop (int *pVal)
STDMETHOD() get_Name (BSTR *pVal)
STDMETHOD() GetCell (int index, IFusionCDFProbeInformation *info)
STDMETHOD() get_WobbleSituation (USHORT *pVal)
STDMETHOD() get_AlleleCode (USHORT *pVal)
STDMETHOD() get_Channel (int *pVal)
STDMETHOD() get_RepType (ReplicationType *pVal)
Private Attributes
affymetrix_fusion_io::FusionCDFProbeGroupInformation group
Detailed Description
Definition at line 30 of file FusionCDFProbeGroupInformationCOM.h.
Constructor & Destructor Documentation
CFusionCDFProbeGroupInformationCOM::CFusionCDFProbeGroupInformationCOM () [inline]
Definition at line 37 of file FusionCDFProbeGroupInformationCOM.h.
Member Function Documentation
HRESULT CFusionCDFProbeGroupInformationCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionCDFProbeGroupInformationCOM.h.
void CFusionCDFProbeGroupInformationCOM::FinalRelease () [inline]
Definition at line 60 of file FusionCDFProbeGroupInformationCOM.h.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_AlleleCode (USHORT * pVal)
Definition at line 98 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetAlleleCode(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_Channel (int * pVal)
Definition at line 104 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetChannel(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_Direction (DirectionType * pVal)
Definition at line 43 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetDirection(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_Name (BSTR * pVal)
Definition at line 79 of file FusionCDFProbeGroupInformationCOM.cpp.
References COMStringUtils::ConvertString(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetName(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_NumCells (int * pVal)
Definition at line 55 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetNumCells(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_NumCellsPerList (int * pVal)
Definition at line 61 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetNumCellsPerList(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_NumLists (int * pVal)
Definition at line 49 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetNumLists(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_RepType (ReplicationType * pVal)
Definition at line 109 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetRepType(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_Start (int * pVal)
Definition at line 67 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetStart(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_Stop (int * pVal)
Definition at line 73 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetStop(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::get_WobbleSituation (USHORT * pVal)
Definition at line 92 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetWobbleSituation(), and group.
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::GetCell (int index, IFusionCDFProbeInformation * info)
Definition at line 85 of file FusionCDFProbeGroupInformationCOM.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetCell(), group, and CFusionCDFProbeInformationCOM::Probe().
affymetrix_fusion_io::FusionCDFProbeGroupInformation& CFusionCDFProbeGroupInformationCOM::Group () [inline]
Definition at line 68 of file FusionCDFProbeGroupInformationCOM.h.
Referenced by CFusionCDFProbeSetInformationCOM::GetGroup().
STDMETHODIMP CFusionCDFProbeGroupInformationCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 28 of file FusionCDFProbeGroupInformationCOM.cpp.
Member Data Documentation
affymetrix_fusion_io::FusionCDFProbeGroupInformation CFusionCDFProbeGroupInformationCOM::group [private]
Definition at line 65 of file FusionCDFProbeGroupInformationCOM.h.
Referenced by get_AlleleCode(), get_Channel(), get_Direction(), get_Name(), get_NumCells(), get_NumCellsPerList(), get_NumLists(), get_RepType(), get_Start(), get_Stop(), get_WobbleSituation(), and GetCell().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFProbeGroupInformationCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCDFProbeGroupInformationCOM.cpp