Affymetrix Fusion SDK: TableFile Class Reference
TableFile Class Reference
#include <TableFile.h>
Public Member Functions
TableFile (char delim= '\t', char comment= '#', bool useRowNames=false, bool useColNames=true)
~TableFile ()
bool open (const std::string &fileName)
bool open (const std::string &fileName, const std::vector< std::string > &requiredCols)
bool write (const std::string &fileName)
size_t numCols ()
size_t numRows ()
unsigned int colIndex (const std::string &colName)
unsigned int rowIndex (const std::string &rowName)
std::string & getData (unsigned int rowIx, unsigned int colIx)
std::string & getColName (unsigned int colIx)
std::string & getRowName (size_t rowIx)
void setUseRowNames ()
Change state to use row names.
bool getUseRowNames ()
Are we using row names?
void setUseColNames (bool use)
void setUseRowNames (bool use)
const std::vector< std::string > & getHeaderValue (const std::string &key)
Get the value of a layout key=value header pair.
Static Public Member Functions
static void writeVector (std::ostream &out, std::vector< std::string > data, char delim)
static bool columnFromFile (const std::string &fileName, std::vector< std::string > &colVec, const std::string &colName, unsigned int skipCols, bool unique=false)
static bool columnFromFile (const std::string &fileName, std::vector< std::string > &colVec, unsigned int colIx, unsigned int skipCols, bool unique=false)
static bool columnFromRowFile (RowFile &rf, std::vector< std::string > &colVec, unsigned int colIx, bool unique=false)
Static Public Attributes
static const unsigned int npos = UINT_MAX
Error value indicating not found.
Private Types
typedef std::map< std::string,
unsigned int, Util::ltstring >
::iterator TMapIter
typedef const std::map
< std::string, unsigned int,
Util::ltstring >::iterator TMapConstIter
Private Attributes
char m_Delim
Delimiter in table.
char m_Comment
Comment character for data.
bool m_UseRowNames
Should row names be expected.
bool m_UseColNames
Header parameters from thisKey=thisParam.
std::map< std::string,
std::vector< std::string > > m_Header
All header lines for easy recovery.
std::vector< std::string > m_HeaderLines
Name of columns.
std::vector< std::string > m_ColNames
Name of rows.
std::vector< std::string > m_RowNames
Core table of words.
std::vector< std::vector
< std::string > > m_Data
std::map< std::string,
unsigned int, Util::ltstring > m_ColNameMap
std::map< std::string,
unsigned int, Util::ltstring > m_RowNameMap
std::vector< char * > m_MemToFree
Detailed Description
TableFile - File for reading and using files that have delimited rows of data. Specifically for R table files and the like.
Definition at line 47 of file TableFile.h.
Member Typedef Documentation
typedef const std::map<std::string, unsigned int, Util::ltstring>::iterator TableFile::TMapConstIter [private]
Iterator to walk through the map.
Definition at line 248 of file TableFile.h.
typedef std::map<std::string, unsigned int, Util::ltstring>::iterator TableFile::TMapIter [private]
Iterator to walk through the map.
Definition at line 246 of file TableFile.h.
Constructor & Destructor Documentation
TableFile::TableFile (char delim = '\t', char comment = '#', bool useRowNames = false, bool useColNames = true)
Constructor.
Parameters:
delim - Character to use for word separator. i.e. ',' or '\t'
comment - Character that comment lines begin with.
useRowNames - Is first column the names of the rows?
useColNames - Is the first row the column headers?
Constructor.
Parameters:
delim - Character to use for word separator. i.e. ',' or '\t'
comment - Character that comment lines begin with.
Definition at line 47 of file TableFile.cpp.
TableFile::~TableFile ()
Destructor.
Definition at line 54 of file TableFile.cpp.
References m_MemToFree.
Member Function Documentation
unsigned int TableFile::colIndex (const std::string & colName)
Look up the index of column with name specified.
Parameters:
colName - Name of column of interest.
Returns:
- npos if not found, column index otherwise.
Definition at line 67 of file TableFile.cpp.
References m_ColNameMap, and npos.
bool TableFile::columnFromFile (const std::string & fileName, std::vector< std::string > & colVec, const std::string & colName, unsigned int skipCols, bool unique = false) [static]
Rip the column out of a file by name filling in the data in colVec.
Parameters:
fileName - File to read column from.
colVec - Strings to be filled in from column.
colName - Name of column to be read in.
skipCols - Number of (non-commented) rows to skip before header.
unique - If true check to make sure every entry is unique.
Returns:
true if successful false otherwise.
Definition at line 249 of file TableFile.cpp.
References columnFromRowFile(), Err::errAbort(), RowFile::nextRow(), npos, RowFile::open(), Verbose::out(), and ToStr().
Referenced by Util::matrixDifferences().
bool TableFile::columnFromFile (const std::string & fileName, std::vector< std::string > & colVec, unsigned int colIx, unsigned int skipCols, bool unique = false) [static]
Rip the column out of a file by index filling in the data in colVec.
Parameters:
fileName - File to read column from.
colVec - Strings to be filled in from column.
colIx - Column index to read.
skipCols - Number of (non-commented) rows to skip before header.
unique - If true check to make sure every entry is unique.
Returns:
true if successful false otherwise.
Definition at line 293 of file TableFile.cpp.
References columnFromRowFile(), Err::errAbort(), RowFile::nextRow(), RowFile::open(), and RowFile::reuseLine().
bool TableFile::columnFromRowFile (RowFile & rf, std::vector< std::string > & colVec, unsigned int colIx, bool unique = false) [static]
Rip a column out of an open RowFile.
Parameters:
rf - RowFile to read from.
colVec - Strings to be filled in with column's data.
colIx - Column index to read.
unique - If true check to make sure every entry is unique.
Returns:
true if successful false otherwise.
Definition at line 321 of file TableFile.cpp.
References Err::errAbort(), RowFile::getCurrentLineNumber(), RowFile::getFileName(), RowFile::nextRow(), and ToStr().
Referenced by columnFromFile().
std::string& TableFile::getColName (unsigned int colIx) [inline]
Return column name at specified index.
Parameters:
colIx - column number of interest.
Returns:
- reference to column name at index of interest.
Definition at line 131 of file TableFile.h.
References m_ColNames.
std::string& TableFile::getData (unsigned int rowIx, unsigned int colIx) [inline]
Return data at the position specified in table.
Parameters:
rowIx - row number.
colIx - column number.
Returns:
- string representation of data.
Definition at line 122 of file TableFile.h.
References m_Data.
const std::vector<std::string>& TableFile::getHeaderValue (const std::string & key) [inline]
Get the value of a layout key=value header pair.
Parameters:
key String to lookup value of.
Returns:
value of key/value pair.
Definition at line 220 of file TableFile.h.
References Err::errAbort(), and m_Header.
std::string& TableFile::getRowName (size_t rowIx) [inline]
Return row name at specified index.
Parameters:
rowIx - Row number of interest.
Returns:
- reference to row name at index of interest.
Definition at line 138 of file TableFile.h.
References m_RowNames.
bool TableFile::getUseRowNames () [inline]
Are we using row names?
Returns:
true if using row names, false otherwise.
Definition at line 200 of file TableFile.h.
References m_UseRowNames.
size_t TableFile::numCols () [inline]
Return number of columns in data.
Returns:
- number of columns.
Definition at line 94 of file TableFile.h.
References m_ColNames.
size_t TableFile::numRows () [inline]
Return number of rows in data.
Returns:
- number of rows.
Definition at line 100 of file TableFile.h.
References m_RowNames.
bool TableFile::open (const std::string & fileName, const std::vector< std::string > & requiredCols)
Read data from file specified.
Parameters:
fileName - file to be read.
requiredCols - column names that must be present.
Returns:
- true if successful.
Definition at line 106 of file TableFile.cpp.
References Fs::basename(), Util::cloneString(), RowFile::close(), Fs::convertToUncPath(), Err::errAbort(), FS_QUOTE_PATH, RowFile::getCurrentLineNumber(), m_ColNameMap, m_ColNames, m_Data, m_Header, m_HeaderLines, m_MemToFree, m_RowNameMap, m_RowNames, m_UseColNames, m_UseRowNames, RowFile::nextRow(), RowFile::open(), Verbose::out(), RowFile::readHeader(), RowFile::reuseLine(), ToStr(), and Convert::toString().
bool TableFile::open (const std::string & fileName)
Read data from file specified.
Parameters:
fileName - file to be read.
Returns:
- true if successful.
Definition at line 95 of file TableFile.cpp.
unsigned int TableFile::rowIndex (const std::string & rowName)
Look up the index of row with name specified.
Parameters:
rowName - Name of row of interest.
Returns:
- npos if not found, row index otherwise.
Definition at line 81 of file TableFile.cpp.
References m_RowNameMap, and npos.
void TableFile::setUseColNames (bool use) [inline]
Set the flag to look for column names (i.e. column headers).
Parameters:
use - should column names be used
Definition at line 206 of file TableFile.h.
References m_UseColNames.
void TableFile::setUseRowNames () [inline]
Change state to use row names.
Definition at line 194 of file TableFile.h.
References m_UseRowNames.
void TableFile::setUseRowNames (bool use) [inline]
Set the flag to look for row names (i.e. row ids).
Parameters:
use - should row names be used
Definition at line 212 of file TableFile.h.
References m_UseRowNames.
bool TableFile::write (const std::string & fileName)
Write data to file specified.
Parameters:
fileName - name of file to write to.
Returns:
- true if successful.
Definition at line 222 of file TableFile.cpp.
References Err::errAbort(), m_ColNames, m_Data, m_Delim, m_HeaderLines, m_RowNames, RowFile::writeHeader(), and writeVector().
void TableFile::writeVector (std::ostream & out, std::vector< std::string > data, char delim) [static]
Write out words in vector delimited by specified character.
Parameters:
out - stream to write to.
data - vector of data to write.
delim - delimiter to separate words with.
Definition at line 206 of file TableFile.cpp.
Referenced by write().
Member Data Documentation
std::map<std::string, unsigned int, Util::ltstring> TableFile::m_ColNameMap [private]
Used as hash of column names.
Definition at line 251 of file TableFile.h.
Referenced by colIndex(), and open().
std::vector<std::string> TableFile::m_ColNames [private]
Name of rows.
Definition at line 240 of file TableFile.h.
Referenced by getColName(), numCols(), open(), and write().
char TableFile::m_Comment [private]
Comment character for data.
Definition at line 231 of file TableFile.h.
std::vector< std::vector<std::string> > TableFile::m_Data [private]
Definition at line 243 of file TableFile.h.
Referenced by getData(), open(), and write().
char TableFile::m_Delim [private]
Delimiter in table.
Definition at line 230 of file TableFile.h.
Referenced by write().
std::map<std::string, std::vector<std::string> > TableFile::m_Header [private]
All header lines for easy recovery.
Definition at line 236 of file TableFile.h.
Referenced by getHeaderValue(), and open().
std::vector<std::string> TableFile::m_HeaderLines [private]
Name of columns.
Definition at line 238 of file TableFile.h.
Referenced by open(), and write().
std::vector<char *> TableFile::m_MemToFree [private]
Way to quickly free up memory in hash.
Definition at line 255 of file TableFile.h.
Referenced by open(), and ~TableFile().
std::map<std::string, unsigned int, Util::ltstring> TableFile::m_RowNameMap [private]
Used as hash of row names.
Definition at line 253 of file TableFile.h.
Referenced by open(), and rowIndex().
std::vector<std::string> TableFile::m_RowNames [private]
Core table of words.
Definition at line 242 of file TableFile.h.
Referenced by getRowName(), numRows(), open(), and write().
bool TableFile::m_UseColNames [private]
Header parameters from thisKey=thisParam.
Should row names be expected
Definition at line 233 of file TableFile.h.
Referenced by open(), and setUseColNames().
bool TableFile::m_UseRowNames [private]
Should row names be expected.
Definition at line 232 of file TableFile.h.
Referenced by getUseRowNames(), open(), and setUseRowNames().
const unsigned int TableFile::npos = UINT_MAX [static]
Error value indicating not found.
Definition at line 52 of file TableFile.h.
Referenced by colIndex(), columnFromFile(), and rowIndex().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/TableFile.h
C:/f112/affy/sdk/util/TableFile.cpp