Affymetrix Fusion SDK: CalvinToText Class Reference
CalvinToText Class Reference
#include <CalvinToText.h>
Public Member Functions
CalvinToText ()
void run (const std::string &strFileNameIn, const std::string &strFileNameOut, bool bHeader, bool bBody, bool bNewGuid)
Protected Member Functions
void error (const AffxString &strMessage)
bool ReadFile (const std::string &fileName, GenericData &gdata)
void OutputData (GenericData &gdata, int groupIndex, int setIndex, int startRow, int endRow)
void OutputFileHeaderParameters (GenericData &gdata, bool bNewGuid)
void OutputParameters (ParameterNameValueTypeIt &begin, ParameterNameValueTypeIt &end)
void OutputParameters (ParameterNameValueTypeConstIt &begin, ParameterNameValueTypeConstIt &end)
void OutputDataHeaderParameters (GenericDataHeader *hdr, bool bNewGuid)
void OutputSetInfo (GenericData &gdata, int groupIndex, int setIndex)
void OutputGroupInfo (GenericData &gdata, const std::wstring &groupName, int groupIndex)
void OutputGroupsAndSets (GenericData &gdata)
void OutputHeader (const std::string &strFileName, affymetrix_calvin_io::GenericData &genericData, bool bNewGuid)
bool isCalvinFile (const AffxString &strFileName)
Protected Attributes
AffxString m_strFileNameIn
AffxString m_strFileNameOut
CalvinToTextFile m_file
bool m_bHeader
int m_iXChromosome
int m_iYChromosome
Detailed Description
Definition at line 66 of file CalvinToText.h.
Constructor & Destructor Documentation
CalvinToText::CalvinToText () [inline]
Definition at line 76 of file CalvinToText.h.
Member Function Documentation
void CalvinToText::error (const AffxString & strMessage) [protected]
Error handling for the class.
Parameters:
strMessage - The error messagae to report.
Definition at line 101 of file CalvinToText.cpp.
References Err::errAbort().
bool CalvinToText::isCalvinFile (const AffxString & strFileName) [protected]
Definition at line 504 of file CalvinToText.cpp.
References AffxBinaryFile::close(), AffxBinaryFile::LOAD, AffxBinaryFile::open(), and AffxBinaryFile::readUnsignedChar().
void CalvinToText::OutputData (GenericData & gdata, int groupIndex, int setIndex, int startRow, int endRow) [protected]
Definition at line 194 of file CalvinToText.cpp.
References affymetrix_calvin_io::ASCIICharColType, affymetrix_calvin_io::ByteColType, affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::FloatColType, getDouble(), getInt(), getUnsignedInt(), affymetrix_calvin_io::IntColType, Max, Min, affymetrix_calvin_io::DataSet::Open(), affymetrix_calvin_io::ShortColType, affymetrix_calvin_io::UByteColType, affymetrix_calvin_io::UIntColType, affymetrix_calvin_io::UnicodeCharColType, and affymetrix_calvin_io::UShortColType.
void CalvinToText::OutputDataHeaderParameters (GenericDataHeader * hdr, bool bNewGuid) [protected]
Definition at line 390 of file CalvinToText.cpp.
References affxutil::Guid::GenerateNewGuid(), affymetrix_calvin_io::GenericDataHeader::GetFileId(), affymetrix_calvin_io::GenericDataHeader::GetFileTypeId(), affymetrix_calvin_io::GenericDataHeader::GetLocale(), affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), affymetrix_calvin_io::GenericDataHeader::GetParent(), and affymetrix_calvin_io::GenericDataHeader::GetParentCnt().
void CalvinToText::OutputFileHeaderParameters (GenericData & gdata, bool bNewGuid) [protected]
Definition at line 318 of file CalvinToText.cpp.
References Fs::fileSize(), affymetrix_calvin_io::GenericDataHeader::GetFileCreationTime(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), getInt(), affymetrix_calvin_io::FileHeader::GetMagicNumber(), getUnsignedInt(), affymetrix_calvin_io::FileHeader::GetVersion(), and affymetrix_calvin_io::GenericData::Header().
void CalvinToText::OutputGroupInfo (GenericData & gdata, const std::wstring & groupName, int groupIndex) [protected]
Definition at line 461 of file CalvinToText.cpp.
References affymetrix_calvin_io::GenericData::DataSetCnt().
void CalvinToText::OutputGroupsAndSets (GenericData & gdata) [protected]
Definition at line 479 of file CalvinToText.cpp.
References affymetrix_calvin_io::GenericData::DataGroupNames().
void CalvinToText::OutputHeader (const std::string & strFileName, affymetrix_calvin_io::GenericData & genericData, bool bNewGuid) [protected]
Definition at line 494 of file CalvinToText.cpp.
References affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::GenericFileReader::Open(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
void CalvinToText::OutputParameters (ParameterNameValueTypeIt & begin, ParameterNameValueTypeIt & end) [protected]
Definition at line 347 of file CalvinToText.cpp.
References getInt(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::ToString().
void CalvinToText::OutputParameters (ParameterNameValueTypeConstIt & begin, ParameterNameValueTypeConstIt & end) [protected]
Definition at line 368 of file CalvinToText.cpp.
References getInt(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::ToString().
void CalvinToText::OutputSetInfo (GenericData & gdata, int groupIndex, int setIndex) [protected]
Definition at line 437 of file CalvinToText.cpp.
References affymetrix_calvin_io::DataSet::Cols(), affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::DataSet::Delete(), getInt(), affymetrix_calvin_io::DataSetHeader::GetName(), affymetrix_calvin_io::DataSetHeader::GetNameValIterators(), affymetrix_calvin_io::DataSet::Header(), and affymetrix_calvin_io::DataSet::Rows().
bool CalvinToText::ReadFile (const std::string & fileName, GenericData & gdata) [protected]
Definition at line 174 of file CalvinToText.cpp.
References affymetrix_calvin_io::GenericFileReader::ReadHeader(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
void CalvinToText::run (const std::string & strFileNameIn, const std::string & strFileNameOut, bool bHeader, bool bBody, bool bNewGuid)
Definition at line 106 of file CalvinToText.cpp.
References AffxByteArray::assign(), Fs::convertToUncPath(), affymetrix_calvin_utilities::StringUtils::ConvertWCSToMBS(), affymetrix_calvin_exceptions::CalvinException::Description(), Err::errAbort(), Verbose::out(), ToStr(), and Except::what().
Member Data Documentation
bool CalvinToText::m_bHeader [protected]
Definition at line 72 of file CalvinToText.h.
CalvinToTextFile CalvinToText::m_file [protected]
Definition at line 71 of file CalvinToText.h.
int CalvinToText::m_iXChromosome [protected]
Definition at line 73 of file CalvinToText.h.
int CalvinToText::m_iYChromosome [protected]
Definition at line 74 of file CalvinToText.h.
AffxString CalvinToText::m_strFileNameIn [protected]
Definition at line 69 of file CalvinToText.h.
AffxString CalvinToText::m_strFileNameOut [protected]
Definition at line 70 of file CalvinToText.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/CalvinToText.h
C:/f112/affy/sdk/util/CalvinToText.cpp