Affymetrix Fusion SDK: affymetrix_calvin_io::CHPGenotypeEntry Class Reference
affymetrix_calvin_io::CHPGenotypeEntry Class Reference
#include <CHPGenotypeEntry.h>
Public Member Functions
CHPGenotypeEntry ()
CHPGenotypeEntry (const std::string &probeSetname, u_int8_t call, float confidence, float RAS1, float RAS2, float AACall, float ABCall, float BBCall, float NoCall)
~CHPGenotypeEntry ()
void Clear ()
CHPGenotypeEntry operator= (CHPGenotypeEntry zn)
std::string GetProbeSetName () const
u_int8_t GetCall () const
float GetConfidence () const
float GetRAS1 () const
float GetRAS2 () const
float GetAACall () const
float GetABCall () const
float GetBBCall () const
float GetNoCall () const
void SetProbeSetName (const std::string &p)
void SetCall (u_int8_t p)
void SetConfidence (float p)
void SetRAS1 (float p)
void SetRAS2 (float p)
void SetAACall (float p)
void SetABCall (float p)
void SetBBCall (float p)
void SetNoCall (float p)
Private Attributes
std::string probeSetName
u_int8_t call
float confidence
float RAS1
float RAS2
float aaCall
float abCall
float bbCall
float noCall
Detailed Description
This class stores a genotype result
Definition at line 37 of file CHPGenotypeEntry.h.
Constructor & Destructor Documentation
CHPGenotypeEntry::CHPGenotypeEntry ()
Definition at line 26 of file CHPGenotypeEntry.cpp.
References Clear().
CHPGenotypeEntry::CHPGenotypeEntry (const std::string & probeSetname, u_int8_t call, float confidence, float RAS1, float RAS2, float AACall, float ABCall, float BBCall, float NoCall)
Definition at line 31 of file CHPGenotypeEntry.cpp.
References aaCall, abCall, bbCall, call, confidence, noCall, probeSetName, RAS1, and RAS2.
CHPGenotypeEntry::~CHPGenotypeEntry ()
Definition at line 52 of file CHPGenotypeEntry.cpp.
Member Function Documentation
void CHPGenotypeEntry::Clear ()
Definition at line 54 of file CHPGenotypeEntry.cpp.
References aaCall, abCall, bbCall, call, confidence, noCall, probeSetName, RAS1, and RAS2.
Referenced by CHPGenotypeEntry().
float CHPGenotypeEntry::GetAACall () const
Definition at line 106 of file CHPGenotypeEntry.cpp.
References aaCall.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), operator=(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), and affymetrix_calvin_io::CHPFileBufferWriter::WriteGenotypeEntry().
float CHPGenotypeEntry::GetABCall () const
Definition at line 111 of file CHPGenotypeEntry.cpp.
References abCall.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), operator=(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), and affymetrix_calvin_io::CHPFileBufferWriter::WriteGenotypeEntry().
float CHPGenotypeEntry::GetBBCall () const
Definition at line 116 of file CHPGenotypeEntry.cpp.
References bbCall.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), operator=(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), and affymetrix_calvin_io::CHPFileBufferWriter::WriteGenotypeEntry().
u_int8_t CHPGenotypeEntry::GetCall () const
Definition at line 86 of file CHPGenotypeEntry.cpp.
References call.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), operator=(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), and affymetrix_calvin_io::CHPFileBufferWriter::WriteGenotypeEntry().
float CHPGenotypeEntry::GetConfidence () const
Definition at line 91 of file CHPGenotypeEntry.cpp.
References confidence.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), operator=(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), and affymetrix_calvin_io::CHPFileBufferWriter::WriteGenotypeEntry().
float CHPGenotypeEntry::GetNoCall () const
Definition at line 121 of file CHPGenotypeEntry.cpp.
References noCall.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), operator=(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), and affymetrix_calvin_io::CHPFileBufferWriter::WriteGenotypeEntry().
std::string CHPGenotypeEntry::GetProbeSetName () const
Definition at line 81 of file CHPGenotypeEntry.cpp.
References probeSetName.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetProbeSetName(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry().
float CHPGenotypeEntry::GetRAS1 () const
Definition at line 96 of file CHPGenotypeEntry.cpp.
References RAS1.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), operator=(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), and affymetrix_calvin_io::CHPFileBufferWriter::WriteGenotypeEntry().
float CHPGenotypeEntry::GetRAS2 () const
Definition at line 101 of file CHPGenotypeEntry.cpp.
References RAS2.
Referenced by affymetrix_fusion_io::CalvinCHPDataAdapter::GetGenotypingResults(), operator=(), affymetrix_calvin_io::CHPFileWriter::WriteGenotypeEntry(), and affymetrix_calvin_io::CHPFileBufferWriter::WriteGenotypeEntry().
CHPGenotypeEntry CHPGenotypeEntry::operator= (CHPGenotypeEntry zn)
Assignment operator
Parameters:
zn The zone to copy
Returns:
The new zone object
Definition at line 67 of file CHPGenotypeEntry.cpp.
References aaCall, abCall, bbCall, call, confidence, GetAACall(), GetABCall(), GetBBCall(), GetCall(), GetConfidence(), GetNoCall(), GetProbeSetName(), GetRAS1(), GetRAS2(), noCall, probeSetName, RAS1, and RAS2.
void CHPGenotypeEntry::SetAACall (float p)
Definition at line 151 of file CHPGenotypeEntry.cpp.
References aaCall.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void CHPGenotypeEntry::SetABCall (float p)
Definition at line 156 of file CHPGenotypeEntry.cpp.
References abCall.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void CHPGenotypeEntry::SetBBCall (float p)
Definition at line 161 of file CHPGenotypeEntry.cpp.
References bbCall.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void CHPGenotypeEntry::SetCall (u_int8_t p)
Definition at line 131 of file CHPGenotypeEntry.cpp.
References call.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void CHPGenotypeEntry::SetConfidence (float p)
Definition at line 136 of file CHPGenotypeEntry.cpp.
References confidence.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void CHPGenotypeEntry::SetNoCall (float p)
Definition at line 166 of file CHPGenotypeEntry.cpp.
References noCall.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void CHPGenotypeEntry::SetProbeSetName (const std::string & p)
Definition at line 126 of file CHPGenotypeEntry.cpp.
References probeSetName.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void CHPGenotypeEntry::SetRAS1 (float p)
Definition at line 141 of file CHPGenotypeEntry.cpp.
References RAS1.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
void CHPGenotypeEntry::SetRAS2 (float p)
Definition at line 146 of file CHPGenotypeEntry.cpp.
References RAS2.
Referenced by affymetrix_calvin_io::CHPData::GetEntry().
Member Data Documentation
float affymetrix_calvin_io::CHPGenotypeEntry::aaCall [private]
Definition at line 47 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetAACall(), operator=(), and SetAACall().
float affymetrix_calvin_io::CHPGenotypeEntry::abCall [private]
Definition at line 48 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetABCall(), operator=(), and SetABCall().
float affymetrix_calvin_io::CHPGenotypeEntry::bbCall [private]
Definition at line 49 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetBBCall(), operator=(), and SetBBCall().
u_int8_t affymetrix_calvin_io::CHPGenotypeEntry::call [private]
Definition at line 43 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetCall(), operator=(), and SetCall().
float affymetrix_calvin_io::CHPGenotypeEntry::confidence [private]
Definition at line 44 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetConfidence(), operator=(), and SetConfidence().
float affymetrix_calvin_io::CHPGenotypeEntry::noCall [private]
Definition at line 50 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetNoCall(), operator=(), and SetNoCall().
std::string affymetrix_calvin_io::CHPGenotypeEntry::probeSetName [private]
Definition at line 42 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetProbeSetName(), operator=(), and SetProbeSetName().
float affymetrix_calvin_io::CHPGenotypeEntry::RAS1 [private]
Definition at line 45 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetRAS1(), operator=(), and SetRAS1().
float affymetrix_calvin_io::CHPGenotypeEntry::RAS2 [private]
Definition at line 46 of file CHPGenotypeEntry.h.
Referenced by CHPGenotypeEntry(), Clear(), GetRAS2(), operator=(), and SetRAS2().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CHPGenotypeEntry.h
C:/f112/affy/sdk/calvin_files/data/src/CHPGenotypeEntry.cpp