Affymetrix Fusion SDK: TextFileCheck Class Reference
TextFileCheck Class Reference
#include <TextFileCheck.h>
Public Member Functions
TextFileCheck (const std::string &generatedFile, const std::string &goldFile, const unsigned int skipLines)
TextFileCheck (const std::string &generatedFile, const std::string &goldFile, const std::string &headerDelimiter)
bool check (std::string &errorMsg)
Private Attributes
std::string m_GeneratedFile
Name of file generated by application being tested.
std::string m_GoldFile
Name of file assumed to be correct.
const unsigned int m_SkipLines
Number of lines to skip.
std::string m_HeaderDelimiter
Header Delimiter.
Detailed Description
Class for testing that two text files are equal, except for line endings.
Definition at line 38 of file TextFileCheck.h.
Constructor & Destructor Documentation
TextFileCheck::TextFileCheck (const std::string & generatedFile, const std::string & goldFile, const unsigned int skipLines) [inline]
Constructor.
Parameters:
generatedFile File generated by application.
goldFile Comparison file, assumed to be correct.
skipLines Number of lines to skip.
Definition at line 48 of file TextFileCheck.h.
References Fs::basename(), and m_HeaderDelimiter.
TextFileCheck::TextFileCheck (const std::string & generatedFile, const std::string & goldFile, const std::string & headerDelimiter) [inline]
Definition at line 54 of file TextFileCheck.h.
References Fs::basename().
Member Function Documentation
bool TextFileCheck::check (std::string & errorMsg) [inline]
Check that the two files are the same.
Parameters:
errorMsg Error message generated if the test fails.
Returns:
bool Returns true if files the same, else false.
Definition at line 66 of file TextFileCheck.h.
References LineFile::eof(), LineFile::fail(), LineFile::getline(), LineFile::is_open(), m_GeneratedFile, m_GoldFile, m_HeaderDelimiter, m_SkipLines, and LineFile::open().
Referenced by main().
Member Data Documentation
std::string TextFileCheck::m_GeneratedFile [private]
Name of file generated by application being tested.
Definition at line 133 of file TextFileCheck.h.
Referenced by check().
std::string TextFileCheck::m_GoldFile [private]
Name of file assumed to be correct.
Definition at line 135 of file TextFileCheck.h.
Referenced by check().
std::string TextFileCheck::m_HeaderDelimiter [private]
Header Delimiter.
Definition at line 139 of file TextFileCheck.h.
Referenced by check(), and TextFileCheck().
const unsigned int TextFileCheck::m_SkipLines [private]
Number of lines to skip.
Definition at line 137 of file TextFileCheck.h.
Referenced by check().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/TextFileCheck.h