Affymetrix Fusion SDK: CProbeSetMultiDataExpressionDataCOM Class Reference
CProbeSetMultiDataExpressionDataCOM Class Reference
#include <ProbeSetMultiDataExpressionDataCOM.h>
Public Member Functions
CProbeSetMultiDataExpressionDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_calvin_data::ProbeSetMultiDataExpressionData & Data ()
STDMETHOD() get_name (BSTR *pVal)
STDMETHOD() get_quantification (float *pVal)
STDMETHOD() get_metricCount (int *pVal)
STDMETHOD() GetMetric (int index, VARIANT *pVal)
STDMETHOD() GetMetricName (int index, BSTR *pVal)
Private Attributes
affymetrix_calvin_data::ProbeSetMultiDataExpressionData data
Detailed Description
Definition at line 28 of file ProbeSetMultiDataExpressionDataCOM.h.
Constructor & Destructor Documentation
CProbeSetMultiDataExpressionDataCOM::CProbeSetMultiDataExpressionDataCOM () [inline]
Definition at line 35 of file ProbeSetMultiDataExpressionDataCOM.h.
Member Function Documentation
affymetrix_calvin_data::ProbeSetMultiDataExpressionData& CProbeSetMultiDataExpressionDataCOM::Data () [inline]
Definition at line 67 of file ProbeSetMultiDataExpressionDataCOM.h.
Referenced by CFusionCHPMultiDataDataCOM::GetExpressionEntry().
HRESULT CProbeSetMultiDataExpressionDataCOM::FinalConstruct () [inline]
Definition at line 54 of file ProbeSetMultiDataExpressionDataCOM.h.
void CProbeSetMultiDataExpressionDataCOM::FinalRelease () [inline]
Definition at line 59 of file ProbeSetMultiDataExpressionDataCOM.h.
STDMETHODIMP CProbeSetMultiDataExpressionDataCOM::get_metricCount (int * pVal)
Definition at line 56 of file ProbeSetMultiDataExpressionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataExpressionDataCOM::get_name (BSTR * pVal)
Definition at line 44 of file ProbeSetMultiDataExpressionDataCOM.cpp.
References COMStringUtils::ConvertString().
STDMETHODIMP CProbeSetMultiDataExpressionDataCOM::get_quantification (float * pVal)
Definition at line 50 of file ProbeSetMultiDataExpressionDataCOM.cpp.
STDMETHODIMP CProbeSetMultiDataExpressionDataCOM::GetMetric (int index, VARIANT * pVal)
Definition at line 69 of file ProbeSetMultiDataExpressionDataCOM.cpp.
References affymetrix_calvin_parameter::ParameterNameValueType::AsciiType, COMStringUtils::ConvertString(), COMStringUtils::ConvertWString(), affymetrix_calvin_parameter::ParameterNameValueType::FloatType, affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueAscii(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueFloat(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt8(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt32(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8(), affymetrix_calvin_parameter::ParameterNameValueType::Int16Type, affymetrix_calvin_parameter::ParameterNameValueType::Int32Type, affymetrix_calvin_parameter::ParameterNameValueType::Int8Type, affymetrix_calvin_parameter::ParameterNameValueType::TextType, affymetrix_calvin_parameter::ParameterNameValueType::UInt16Type, affymetrix_calvin_parameter::ParameterNameValueType::UInt32Type, and affymetrix_calvin_parameter::ParameterNameValueType::UInt8Type.
STDMETHODIMP CProbeSetMultiDataExpressionDataCOM::GetMetricName (int index, BSTR * pVal)
Definition at line 62 of file ProbeSetMultiDataExpressionDataCOM.cpp.
References COMStringUtils::ConvertWString(), and affymetrix_calvin_parameter::ParameterNameValueType::GetName().
STDMETHODIMP CProbeSetMultiDataExpressionDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 29 of file ProbeSetMultiDataExpressionDataCOM.cpp.
Member Data Documentation
affymetrix_calvin_data::ProbeSetMultiDataExpressionData CProbeSetMultiDataExpressionDataCOM::data [private]
Definition at line 64 of file ProbeSetMultiDataExpressionDataCOM.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataExpressionDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/ProbeSetMultiDataExpressionDataCOM.cpp