Affymetrix Fusion SDK: SnpTable Class Reference
SnpTable Class Reference
#include <SnpTable.h>
Public Member Functions
void open (const std::string &fileName)
int getNumRows ()
Return the number of rows in the file.
int getNumCols ()
Return the number of columns in the file.
const std::string & getRowName (int rowIx)
Get the name of row rowIx.
const std::string & getColName (int colIx)
Get the name of column colIx.
int getRowIndex (const std::string &s)
int getColIndex (const std::string &s)
int getGenotypeForSnp (int rowIndex, int colIndex)
Static Public Attributes
static const int NN = -1
static const int AA = 0
static const int AB = 1
static const int BB = 2
Private Attributes
std::vector< std::string > m_RowNames
Unique identifiers (usually probeset ids) associated with each row.
std::vector< std::string > m_ColNames
Unique identifiers (usually chip names) associated with each column.
std::map< std::string, int > m_RowNameMap
std::map< std::string, int > m_ColNameMap
std::vector< std::vector< int > > m_GTypes
Matrix of genotypes rows are snps, columns are the chips.
Detailed Description
Definition at line 40 of file SnpTable.h.
Member Function Documentation
int SnpTable::getColIndex (const std::string & s)
Find the col index associated with a particular identified, -1 if not found.
Parameters:
s - col identifier.
Returns:
- index if found, -1 otherwise.
Definition at line 131 of file SnpTable.cpp.
const std::string & SnpTable::getColName (int colIx)
Get the name of column colIx.
Parameters:
colIx
Returns:
the name
Definition at line 102 of file SnpTable.cpp.
int SnpTable::getGenotypeForSnp (int rowIndex, int colIndex)
Get the genotype for the particular row and index of the genotype matrix.
Parameters:
rowIndex - Row of interest.
colIndex - Column of interest.
Returns:
the genotype requested.
Definition at line 147 of file SnpTable.cpp.
int SnpTable::getNumCols ()
Return the number of columns in the file.
Returns:
columns
Definition at line 81 of file SnpTable.cpp.
int SnpTable::getNumRows ()
Return the number of rows in the file.
Returns:
rows
Definition at line 73 of file SnpTable.cpp.
int SnpTable::getRowIndex (const std::string & s)
Find the row index associated with a particular identified, -1 if not found.
Parameters:
s - row identifier.
Returns:
- index if found, -1 otherwise.
Definition at line 115 of file SnpTable.cpp.
const std::string & SnpTable::getRowName (int rowIx)
Get the name of row rowIx.
Parameters:
rowIx
Returns:
the name
Definition at line 91 of file SnpTable.cpp.
void SnpTable::open (const std::string & fileName)
Read in genotypes from a file that looks like probeset_id [tab] chip1 [tab] chip2 [tab]... chipN SNP_A-1889420 [tab] -1 [tab] 0 [tab] 2 [tab] ... 1
Entries are -1 = NN, 0 = AA, 1 = AB, 2 = BB
Parameters:
fileName - name of file to open.
Definition at line 44 of file SnpTable.cpp.
References affx::TsvFile::bind(), affx::TsvFile::cidx2cname(), affx::TsvFile::close(), affx::TsvFile::getColumnCount(), affx::TsvFile::nextLevel(), affx::TsvFile::open(), and affx::TSV_OK.
Member Data Documentation
const int SnpTable::AA = 0 [static]
Definition at line 45 of file SnpTable.h.
const int SnpTable::AB = 1 [static]
Definition at line 46 of file SnpTable.h.
const int SnpTable::BB = 2 [static]
Definition at line 47 of file SnpTable.h.
std::map<std::string, int> SnpTable::m_ColNameMap [private]
Map of probeset ids to the index of the column that contains the data for that chip
Definition at line 120 of file SnpTable.h.
std::vector<std::string> SnpTable::m_ColNames [private]
Unique identifiers (usually chip names) associated with each column.
Definition at line 114 of file SnpTable.h.
std::vector<std::vector<int> > SnpTable::m_GTypes [private]
Matrix of genotypes rows are snps, columns are the chips.
Definition at line 122 of file SnpTable.h.
std::map<std::string, int> SnpTable::m_RowNameMap [private]
Map of probeset ids to the index of the row that contains the data for that snp
Definition at line 117 of file SnpTable.h.
std::vector<std::string> SnpTable::m_RowNames [private]
Unique identifiers (usually probeset ids) associated with each row.
Definition at line 112 of file SnpTable.h.
const int SnpTable::NN = -1 [static]
Definition at line 44 of file SnpTable.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/SnpTable.h
C:/f112/affy/sdk/file/TsvFile/SnpTable.cpp