Affymetrix Fusion SDK: affymetrix_calvin_io::CDFCntrlProbeSetWriter Class Reference
affymetrix_calvin_io::CDFCntrlProbeSetWriter Class Reference
#include <CDFCntrlProbeSetWriter.h>
Public Member Functions
CDFCntrlProbeSetWriter (DataSetWriter *dpw)
~CDFCntrlProbeSetWriter ()
void WriteHeader ()
void Close ()
void Write (u_int16_t xCoord, u_int16_t yCoord, u_int8_t probeLength, u_int8_t perfectMatchFlag, u_int8_t backgroundProbeFlag)
Private Attributes
DataSetWriter * writer
Detailed Description
Definition at line 36 of file CDFCntrlProbeSetWriter.h.
Constructor & Destructor Documentation
affymetrix_calvin_io::CDFCntrlProbeSetWriter::CDFCntrlProbeSetWriter (DataSetWriter * dpw) [inline]
Definition at line 41 of file CDFCntrlProbeSetWriter.h.
References writer.
affymetrix_calvin_io::CDFCntrlProbeSetWriter::~CDFCntrlProbeSetWriter () [inline]
Definition at line 42 of file CDFCntrlProbeSetWriter.h.
References writer.
Member Function Documentation
void CDFCntrlProbeSetWriter::Close (void)
Definition at line 29 of file CDFCntrlProbeSetWriter.cpp.
References affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), and writer.
void CDFCntrlProbeSetWriter::Write (u_int16_t xCoord, u_int16_t yCoord, u_int8_t probeLength, u_int8_t perfectMatchFlag, u_int8_t backgroundProbeFlag)
Definition at line 36 of file CDFCntrlProbeSetWriter.cpp.
References affymetrix_calvin_io::DataSetWriter::Write(), and writer.
void CDFCntrlProbeSetWriter::WriteHeader ()
Definition at line 24 of file CDFCntrlProbeSetWriter.cpp.
References affymetrix_calvin_io::DataSetWriter::WriteHeader(), and writer.
Member Data Documentation
DataSetWriter* affymetrix_calvin_io::CDFCntrlProbeSetWriter::writer [private]
Definition at line 42 of file CDFCntrlProbeSetWriter.h.
Referenced by CDFCntrlProbeSetWriter(), Close(), Write(), WriteHeader(), and ~CDFCntrlProbeSetWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CDFCntrlProbeSetWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CDFCntrlProbeSetWriter.cpp