Affymetrix Fusion SDK: affymetrix_calvin_io::DataGroupReader Class Reference
affymetrix_calvin_io::DataGroupReader Class Reference
#include <DataGroupReader.h>
Public Member Functions
DataGroupReader (std::ifstream &o, DataGroupHeader &hdr)
~DataGroupReader ()
int32_t GetDataSetCnt () const
std::wstring GetDataGroupName () const
DataSetReader GetDataSetReader (int32_t index)
DataSetReader GetDataSetReader (const std::wstring &name)
Private Attributes
std::ifstream & fileStream
DataGroupHeader & dataGroupHdr
Detailed Description
Class to read a DataGroup
Definition at line 41 of file DataGroupReader.h.
Constructor & Destructor Documentation
DataGroupReader::DataGroupReader (std::ifstream & o, DataGroupHeader & hdr)
Constructor
Parameters:
o Reference to an open ifstream
hdr Reference to a DataGroupHeader that has been initialized
Definition at line 31 of file DataGroupReader.cpp.
DataGroupReader::~DataGroupReader ()
Destructor
Definition at line 36 of file DataGroupReader.cpp.
Member Function Documentation
std::wstring DataGroupReader::GetDataGroupName () const
Get the name of the DataGroup
Returns:
DataGroup name
Definition at line 51 of file DataGroupReader.cpp.
References dataGroupHdr, and affymetrix_calvin_io::DataGroupHeader::GetName().
int32_t DataGroupReader::GetDataSetCnt () const
Get the number of DataSets in the DataGroup
Returns:
DataSet count
Definition at line 43 of file DataGroupReader.cpp.
References dataGroupHdr, and affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt().
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroup().
DataSetReader DataGroupReader::GetDataSetReader (int32_t index)
Get the DataSetReader by index
Parameters:
index Index of the DataSet
Exceptions:
DataSetNotFoundException
Definition at line 59 of file DataGroupReader.cpp.
References dataGroupHdr, fileStream, affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_io::DataGroupHeader::GetDataSet(), and affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt().
Referenced by affymetrix_calvin_io::DATFileReader::ReadGlobalGrid(), affymetrix_calvin_io::DATFileReader::ReadSubgrids(), and affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataGroup().
DataSetReader DataGroupReader::GetDataSetReader (const std::wstring & name)
Get the DataSetReader by name
Parameters:
name Name of the DataSet
Exceptions:
DataSetNotFoundException
Definition at line 75 of file DataGroupReader.cpp.
References dataGroupHdr, fileStream, affymetrix_calvin_io::DataGroupHeader::FindDataSetHeader(), and affymetrix_calvin_utilities::DateTime::GetCurrentDateTime().
Member Data Documentation
DataGroupHeader& affymetrix_calvin_io::DataGroupReader::dataGroupHdr [private]
Data dataGroup header that has been initialized
Definition at line 81 of file DataGroupReader.h.
Referenced by GetDataGroupName(), GetDataSetCnt(), and GetDataSetReader().
std::ifstream& affymetrix_calvin_io::DataGroupReader::fileStream [private]
Open file stream
Definition at line 79 of file DataGroupReader.h.
Referenced by GetDataSetReader().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/DataGroupReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/DataGroupReader.cpp