Affymetrix Fusion SDK: affymetrix_fusion_io::IFusionCHPDataAdapter Class Reference
affymetrix_fusion_io::IFusionCHPDataAdapter Class Reference
Data class for the Fusion CHP adapter.
#include <FusionCHPDataAdapterInterface.h>
Public Member Functions
virtual ~IFusionCHPDataAdapter ()
Virtual destructor.
virtual IFusionCHPHeaderAdapter & GetHeader ()=0
Accessors to header.
virtual bool CanReadFile ()=0
Can this object read the file.
virtual std::string GetProbeSetName (int index)=0
virtual bool GetExpressionResults (int index, affymetrix_fusion_io::FusionExpressionProbeSetResults &result)=0
Returns the expression probe set result.
virtual bool GetGenotypingResults (int index, affymetrix_fusion_io::FusionGenotypeProbeSetResults &result)=0
Returns the genotyping probe set result.
virtual bool GetUniversalResults (int index, affymetrix_fusion_io::FusionUniversalProbeSetResults &results)=0
Returns the universal (tag array) probe set result.
virtual bool GetResequencingResults (affymetrix_fusion_io::FusionResequencingResults &results)=0
Gets resequencing results.
virtual bool Read ()=0
Functions to read file.
virtual bool ReadHeader ()=0
Reads the header of the CHP file.
virtual void SetFileName (const std::string &value)=0
Sets the file name.
virtual std::string GetFileName () const =0
Gets the file name.
virtual void Clear ()=0
Deallocates any memory used by the class object.
virtual
affymetrix_calvin_utilities::AffymetrixGuidType FileId ()=0
virtual
affymetrix_calvin_io::GenericData * GetGenericData ()=0
Detailed Description
Data class for the Fusion CHP adapter.
Definition at line 177 of file FusionCHPDataAdapterInterface.h.
Constructor & Destructor Documentation
virtual affymetrix_fusion_io::IFusionCHPDataAdapter::~IFusionCHPDataAdapter () [inline, virtual]
Virtual destructor.
Definition at line 182 of file FusionCHPDataAdapterInterface.h.
Member Function Documentation
virtual bool affymetrix_fusion_io::IFusionCHPDataAdapter::CanReadFile () [pure virtual]
Can this object read the file.
Returns:
If the cell file can be read.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::CreateAdapter().
virtual void affymetrix_fusion_io::IFusionCHPDataAdapter::Clear () [pure virtual]
Deallocates any memory used by the class object.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::Clear().
virtual affymetrix_calvin_utilities::AffymetrixGuidType affymetrix_fusion_io::IFusionCHPDataAdapter::FileId () [pure virtual]
Get the id of the file (only valid for Command Console "calvin" files)
Returns:
The unique file id.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::FileId().
virtual bool affymetrix_fusion_io::IFusionCHPDataAdapter::GetExpressionResults (int index, affymetrix_fusion_io::FusionExpressionProbeSetResults & result) [pure virtual]
Returns the expression probe set result.
Parameters:
index Index to the result object of interest.
result Expression result.
Returns:
True if the expression result was found.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::GetExpressionResults().
virtual std::string affymetrix_fusion_io::IFusionCHPDataAdapter::GetFileName () const [pure virtual]
Gets the file name.
Returns:
Full path to the CHP file.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
virtual affymetrix_calvin_io::GenericData* affymetrix_fusion_io::IFusionCHPDataAdapter::GetGenericData () [pure virtual]
Returns the GenericData object associated with a Calvin file, NULL for GCOS files.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::GetGenericData().
virtual bool affymetrix_fusion_io::IFusionCHPDataAdapter::GetGenotypingResults (int index, affymetrix_fusion_io::FusionGenotypeProbeSetResults & result) [pure virtual]
Returns the genotyping probe set result.
Parameters:
index Index to the result object of interest.
result Genotyping result.
Returns:
True if the genotyping result was found.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::GetGenotypingResults().
virtual IFusionCHPHeaderAdapter& affymetrix_fusion_io::IFusionCHPDataAdapter::GetHeader () [pure virtual]
Accessors to header.
Returns:
Header object
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPHeader::AlgorithmParameterCount(), affymetrix_fusion_io::FusionCHPHeader::AlgorithmParameters(), affymetrix_fusion_io::FusionCHPHeader::GetAlgName(), affymetrix_fusion_io::FusionCHPHeader::GetAlgorithmParameter(), affymetrix_fusion_io::FusionCHPHeader::GetAlgVersion(), affymetrix_fusion_io::FusionCHPHeader::GetAssayType(), affxchp::CCHPFileHeader::GetBackgroundZone(), affymetrix_fusion_io::FusionCHPHeader::GetChipType(), affymetrix_fusion_io::FusionCHPHeader::GetCols(), affymetrix_fusion_io::FusionCHPHeader::GetMagic(), affymetrix_fusion_io::FusionCHPHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCHPHeader::GetParentCellFile(), affymetrix_fusion_io::FusionCHPHeader::GetProgID(), affymetrix_fusion_io::FusionCHPHeader::GetRows(), affymetrix_fusion_io::FusionCHPHeader::GetSummaryParameter(), affymetrix_fusion_io::FusionCHPHeader::GetVersion(), affymetrix_fusion_io::FusionCHPHeader::SummaryParameterCount(), and affymetrix_fusion_io::FusionCHPHeader::SummaryParameters().
virtual std::string affymetrix_fusion_io::IFusionCHPDataAdapter::GetProbeSetName (int index) [pure virtual]
Get the probe set name (only valid for Command Console "calvin" files)
Parameters:
index The index to the result object of interest.
Returns:
The probe set name.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::GetProbeSetName().
virtual bool affymetrix_fusion_io::IFusionCHPDataAdapter::GetResequencingResults (affymetrix_fusion_io::FusionResequencingResults & results) [pure virtual]
Gets resequencing results.
Parameters:
results Hold the resequencing results.
Returns:
True if resequencing results were retrieved.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::GetReseqResults().
virtual bool affymetrix_fusion_io::IFusionCHPDataAdapter::GetUniversalResults (int index, affymetrix_fusion_io::FusionUniversalProbeSetResults & results) [pure virtual]
Returns the universal (tag array) probe set result.
Parameters:
index Index to the result object of interest.
results Universal result.
Returns:
True if the universal result was found.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::GetUniversalResults().
virtual bool affymetrix_fusion_io::IFusionCHPDataAdapter::Read () [pure virtual]
Functions to read file.
Returns:
True if the cell file was read.
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::Read().
virtual bool affymetrix_fusion_io::IFusionCHPDataAdapter::ReadHeader () [pure virtual]
Reads the header of the CHP file.
Returns:
True if successful
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::ReadHeader().
virtual void affymetrix_fusion_io::IFusionCHPDataAdapter::SetFileName (const std::string & value) [pure virtual]
Sets the file name.
Parameters:
value Full path to the CHP file
Implemented in affymetrix_fusion_io::CalvinCHPDataAdapter, and affymetrix_fusion_io::GCOSCHPDataAdapter.
Referenced by affymetrix_fusion_io::FusionCHPLegacyData::CreateAdapter(), affymetrix_fusion_io::FusionCHPLegacyData::Read(), and affymetrix_fusion_io::FusionCHPLegacyData::ReadHeader().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionCHPDataAdapterInterface.h