Affymetrix Fusion SDK: affymetrix_calvin_io::DataSetHeader Class Reference
affymetrix_calvin_io::DataSetHeader Class Reference
#include <DataSetHeader.h>
Public Member Functions
DataSetHeader ()
~DataSetHeader ()
void Clear ()
void ClearNameValueParameters ()
int32_t GetDataSize () const
int32_t GetRowSize () const
void SetName (const std::wstring &p)
std::wstring GetName () const
int32_t GetNameValParamCnt () const
void AddNameValParam (const ParameterNameValueType &p)
void GetNameValIterators (ParameterNameValueTypeConstIt &begin, ParameterNameValueTypeConstIt &end) const
void GetNameValIterators (ParameterNameValueTypeIt &begin, ParameterNameValueTypeIt &end)
bool FindNameValParam (const std::wstring &name, ParameterNameValueType &result) const
void AddColumn (const ColumnInfo &colInfo)
void AddIntColumn (const std::wstring &name)
void AddUIntColumn (const std::wstring &name)
void AddShortColumn (const std::wstring &name)
void AddUShortColumn (const std::wstring &name)
void AddByteColumn (const std::wstring &name)
void AddUByteColumn (const std::wstring &name)
void AddFloatColumn (const std::wstring &name)
void AddAsciiColumn (const std::wstring &name, int32_t len)
void AddUnicodeColumn (const std::wstring &name, int32_t len)
ColumnInfo GetColumnInfo (int32_t index) const
int32_t GetRowCnt () const
void SetRowCnt (int32_t p)
int32_t GetColumnCnt () const
void SetHeaderStartFilePos (u_int32_t pos)
u_int32_t GetHeaderStartFilePos () const
void SetDataStartFilePos (u_int32_t pos)
u_int32_t GetDataStartFilePos () const
void SetNextSetFilePos (u_int32_t pos)
u_int32_t GetNextSetFilePos () const
Protected Member Functions
ParameterNameValueTypeConstIt FindNameValParam (const ParameterNameValueType &p) const
Private Attributes
int32_t rowCount
std::wstring name
ParameterNameValueTypeVector nameValParams
ColInfoVector columnTypes
u_int32_t headerStartFilePos
u_int32_t dataStartFilePos
u_int32_t nextSetFilePos
Detailed Description
The DataSetHeader information container class.
Definition at line 47 of file DataSetHeader.h.
Constructor & Destructor Documentation
DataSetHeader::DataSetHeader ()
Definition at line 30 of file DataSetHeader.cpp.
References Clear().
DataSetHeader::~DataSetHeader ()
Definition at line 35 of file DataSetHeader.cpp.
References Clear().
Member Function Documentation
void DataSetHeader::AddAsciiColumn (const std::wstring & name, int32_t len)
Parameters:
len Maximum number of char in string
Definition at line 144 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionData::AddColumns(), affymetrix_calvin_io::CHPQuantificationData::AddColumns(), affymetrix_calvin_io::CHPMultiDataData::AddColumns(), affymetrix_calvin_io::CHPData::AddExprColumns(), and affymetrix_calvin_io::CHPData::AddGenoColumns().
void DataSetHeader::AddByteColumn (const std::wstring & name)
Definition at line 129 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPMultiDataData::AddColumns(), affymetrix_calvin_io::CHPData::AddReseqColumns(), affymetrix_calvin_io::CDFFileWriter::CreateProbeSetWriter(), affymetrix_calvin_io::CHPData::SetForceCnt(), and affymetrix_calvin_io::CHPData::SetOrigCnt().
void DataSetHeader::AddColumn (const ColumnInfo & colInfo)
Definition at line 104 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPMultiDataData::AddColumns(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), and affymetrix_calvin_io::DataSetHeaderReader::ReadColumns().
void DataSetHeader::AddFloatColumn (const std::wstring & name)
Definition at line 139 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPTilingData::AddColumns(), affymetrix_calvin_io::CHPQuantificationDetectionData::AddColumns(), affymetrix_calvin_io::CHPQuantificationData::AddColumns(), affymetrix_calvin_io::CHPMultiDataData::AddColumns(), affymetrix_calvin_io::CHPData::AddExprColumns(), affymetrix_calvin_io::CHPData::AddGenoColumns(), affymetrix_calvin_io::CHPData::AddReseqColumns(), affymetrix_calvin_io::CHPData::AddUnivColumns(), affymetrix_calvin_io::DATFileUpdater::CreateGridDataSetHeader(), affymetrix_calvin_io::DATFileUpdater::CreateSubGridDataSetHeader(), affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CelFileData::SetIntensityCount(), and affymetrix_calvin_io::CelFileData::SetStdDevCount().
void DataSetHeader::AddIntColumn (const std::wstring & name)
Definition at line 109 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionData::AddColumns(), affymetrix_calvin_io::CHPQuantificationData::AddColumns(), affymetrix_calvin_io::CHPMultiDataData::AddColumns(), affymetrix_calvin_io::CDFData::CreateContentsGroup(), affymetrix_calvin_io::CHPData::SetForceCnt(), and affymetrix_calvin_io::CHPData::SetOrigCnt().
void affymetrix_calvin_io::DataSetHeader::AddNameValParam (const ParameterNameValueType & p)
Referenced by AddDataSetHeaderToGroup(), affymetrix_calvin_io::DATFileUpdater::AddGridDataSetHeaderParameters(), affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), affymetrix_calvin_io::CDFFileWriter::CreateProbeSetWriter(), CopyNumberResultWriter::CreateResultFile(), affymetrix_calvin_io::CDFCntrlFileWriter::GetCntrlProbeSetWriter(), and affymetrix_calvin_io::DataSetHeaderReader::ReadParameters().
void DataSetHeader::AddShortColumn (const std::wstring & name)
Definition at line 119 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPMultiDataData::AddColumns(), affymetrix_calvin_io::CelFileData::SetMaskCount(), affymetrix_calvin_io::CelFileData::SetOutlierCount(), and affymetrix_calvin_io::CelFileData::SetPixelCount().
void DataSetHeader::AddUByteColumn (const std::wstring & name)
Definition at line 134 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPMultiDataData::AddColumns(), affymetrix_calvin_io::CHPData::AddExprColumns(), affymetrix_calvin_io::CHPData::AddGenoColumns(), and affymetrix_calvin_io::CDFCntrlFileWriter::GetCntrlProbeSetWriter().
void DataSetHeader::AddUIntColumn (const std::wstring & name)
Definition at line 114 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPTilingData::AddColumns(), affymetrix_calvin_io::CHPMultiDataData::AddColumns(), affymetrix_calvin_io::DATFileUpdater::CreateGridDataSetHeader(), affymetrix_calvin_io::CDFFileWriter::CreateProbeSetWriter(), and affymetrix_calvin_io::DATFileUpdater::CreateSubGridDataSetHeader().
void DataSetHeader::AddUnicodeColumn (const std::wstring & name, int32_t len)
Parameters:
name The name of the column.
len Maximum number of wchar_t in string
Definition at line 149 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPMultiDataData::AddColumns(), and affymetrix_calvin_io::CDFData::CreateContentsGroup().
void DataSetHeader::AddUShortColumn (const std::wstring & name)
Definition at line 124 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::CHPData::AddExprColumns(), affymetrix_calvin_io::CDFFileWriter::CreateProbeSetWriter(), affymetrix_calvin_io::CDFCntrlFileWriter::GetCntrlProbeSetWriter(), affymetrix_calvin_io::DATData::SetPixelCount(), affymetrix_calvin_io::DATData::SetStatsCount(), and OutputMessageStream::Write().
void DataSetHeader::Clear ()
Definition at line 40 of file DataSetHeader.cpp.
References ClearNameValueParameters(), columnTypes, dataStartFilePos, headerStartFilePos, name, nextSetFilePos, and rowCount.
Referenced by affymetrix_calvin_io::CHPMultiDataData::Clear(), affymetrix_calvin_io::CDFFileWriter::CreateProbeSetWriter(), DataSetHeader(), affymetrix_calvin_io::CDFCntrlFileWriter::GetCntrlProbeSetWriter(), OutputMessageStream::Write(), and ~DataSetHeader().
void DataSetHeader::ClearNameValueParameters ()
Definition at line 51 of file DataSetHeader.cpp.
References nameValParams.
Referenced by Clear().
ParameterNameValueTypeConstIt affymetrix_calvin_io::DataSetHeader::FindNameValParam (const ParameterNameValueType & p) const [protected]
Finds a ParameterNameValueType by name in the nameValPairs collection
Parameters:
p The ParameterNameValueType to find
Returns:
An iterator referencing the NameValPair if it exists, otherwise it returns nameValPairs.end()
bool affymetrix_calvin_io::DataSetHeader::FindNameValParam (const std::wstring & name, ParameterNameValueType & result) const
Finds a ParameterNameValueType by name in the nameValPairs collection
Parameters:
name The name of the NameValPair to find
result Reference to a ParameterNameValueType to fill with the found ParameterNameValueType.
Returns:
true if the ParameterNameValueType was found
Referenced by affymetrix_calvin_io::CDFProbeSetInformation::SetDataGroup(), and affymetrix_calvin_io::CDFProbeGroupInformation::SetDataSet().
int32_t DataSetHeader::GetColumnCnt () const
Definition at line 169 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::DataSet::BytesPerRow(), affymetrix_calvin_io::DataSet::CheckRowColumnAndType(), affymetrix_calvin_io::DataSet::Cols(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), affymetrix_calvin_io::DataSetWriter::DataSetWriter(), affymetrix_calvin_io::DataSet::GetDataRawT(), affymetrix_calvin_io::DataSet::GetDataT(), GetRowSize(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::GenericData::IsDSHPartiallyRead(), affymetrix_calvin_io::MMDataSetDataWriter::OpenData(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), affymetrix_calvin_io::DATFileReader::ReadGlobalGrid(), affymetrix_calvin_io::DATFileReader::ReadSubgrids(), affymetrix_calvin_io::DataSet::UpdateColumnByteOffsets(), affymetrix_calvin_io::DataSetHeaderWriter::WriteColumnCnt(), and affymetrix_calvin_io::DataSetHeaderWriter::WriteColumnTypes().
ColumnInfo DataSetHeader::GetColumnInfo (int32_t index) const
Definition at line 154 of file DataSetHeader.cpp.
References columnTypes.
Referenced by affymetrix_calvin_io::DataSet::CheckRowColumnAndType(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), Calvin::equivalent(), GetRowSize(), affymetrix_calvin_io::DataSetUpdater::Initialize(), Calvin::load(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), affymetrix_calvin_io::DataSet::UpdateColumnByteOffsets(), and affymetrix_calvin_io::DataSetHeaderWriter::WriteColumnTypes().
int32_t DataSetHeader::GetDataSize () const
Definition at line 56 of file DataSetHeader.cpp.
References GetRowSize(), and rowCount.
Referenced by affymetrix_calvin_io::DataSet::FilePosition(), affymetrix_calvin_io::DataSetWriter::GetDataSetSize(), affymetrix_calvin_io::MMDataSetDataWriter::MMDataSetDataWriter(), affymetrix_calvin_io::DataSet::OpenMM(), affymetrix_calvin_io::DataSet::ReadDataSetUsingStream(), and affymetrix_calvin_io::MultiChannelCelFileCollater::WriteDataSet().
u_int32_t affymetrix_calvin_io::DataSetHeader::GetDataStartFilePos () const [inline]
Get the file position of the start of the DataSet data.
Definition at line 147 of file DataSetHeader.h.
Referenced by affymetrix_calvin_io::DataSetReader::DataSetReader(), affymetrix_calvin_io::DataSet::FilePosition(), affymetrix_calvin_io::MMDataSetDataWriter::GetFirstRowMapped(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::DataSet::LastRowMapped(), affymetrix_calvin_io::DataSet::LoadDataAndReturnFilePosition(), affymetrix_calvin_io::MMDataSetDataWriter::MapData(), affymetrix_calvin_io::MMDataSetDataWriter::OpenData(), affymetrix_calvin_io::DataSet::OpenMM(), and affymetrix_calvin_io::DataSet::ReadDataSetUsingStream().
u_int32_t affymetrix_calvin_io::DataSetHeader::GetHeaderStartFilePos () const [inline]
Get the file position of the start of the DataSet header.
Definition at line 140 of file DataSetHeader.h.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::DataSetHeaderUpdater::DataSetHeaderUpdater(), affymetrix_calvin_io::GenericFileUpdater::GetUpdateDataSetWriter(), and affymetrix_calvin_io::GenericData::ReadFullDataSetHeader().
std::wstring DataSetHeader::GetName () const
Definition at line 77 of file DataSetHeader.cpp.
References name.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), affymetrix_calvin_io::DataSetHeaderUpdater::DataSetHeaderUpdater(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::DataSetWriter::GetDataSetName(), affymetrix_calvin_io::DataSetReader::GetDataSetName(), affymetrix_calvin_io::CDFProbeGroupInformation::GetName(), affymetrix_calvin_io::CDFQCProbeSetInformation::GetQCProbeSetType(), affymetrix_calvin_io::GenericFileUpdater::GetUpdateDataSetWriter(), affymetrix_calvin_io::DataSetUpdater::Initialize(), affymetrix_calvin_io::CHPMultiDataData::OpenMultiDataDataSet(), CalvinToText::OutputSetInfo(), affymetrix_calvin_io::DataGroupHeader::ReplaceDataSetHdr(), affymetrix_calvin_io::DATData::UpdateDataSetRowCount(), affymetrix_calvin_io::CelFileData::UpdateDataSetRowCount(), and affymetrix_calvin_io::DataSetHeaderWriter::WriteName().
void DataSetHeader::GetNameValIterators (ParameterNameValueTypeIt & begin, ParameterNameValueTypeIt & end)
Definition at line 98 of file DataSetHeader.cpp.
References nameValParams.
void affymetrix_calvin_io::DataSetHeader::GetNameValIterators (ParameterNameValueTypeConstIt & begin, ParameterNameValueTypeConstIt & end) const
Referenced by affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), CFusionCHPMultiDataDataCOM::GetDataSetHeaderParameters(), affymetrix_calvin_io::CHPTilingData::GetTilingSequenceData(), CalvinToText::OutputSetInfo(), affymetrix_calvin_io::DATFileReader::ReadGridAlignmentAlgorithmParameters(), and affymetrix_calvin_io::DataSetHeaderWriter::WriteNameValParams().
int32_t DataSetHeader::GetNameValParamCnt () const
Definition at line 82 of file DataSetHeader.cpp.
References nameValParams.
Referenced by CFusionCHPMultiDataDataCOM::GetDataSetHeaderParameters(), affymetrix_calvin_io::GenericData::IsDSHPartiallyRead(), and affymetrix_calvin_io::DataSetHeaderWriter::WriteNameValCnt().
u_int32_t affymetrix_calvin_io::DataSetHeader::GetNextSetFilePos () const [inline]
Get the file position of the next DataSet header.
Definition at line 152 of file DataSetHeader.h.
Referenced by affymetrix_calvin_io::DATFileUpdater::GetGridDataSetOffset(), affymetrix_calvin_io::DATFileUpdater::GetSubGridDataSetOffset(), and affymetrix_calvin_io::GenericFileUpdater::GetUpdateDataSetWriter().
int32_t DataSetHeader::GetRowCnt () const
Definition at line 159 of file DataSetHeader.cpp.
References rowCount.
Referenced by affymetrix_calvin_io::DataSet::CheckRowColumnAndType(), affymetrix_calvin_io::DataSet::ComputeEndRow(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), affymetrix_calvin_io::DataSetWriter::DataSetWriter(), affymetrix_calvin_io::DataSet::FilePosition(), affymetrix_calvin_io::CHPData::GetBackgroundZoneCnt(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::GetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetEntryCount(), affymetrix_calvin_io::CHPData::GetForceCnt(), affymetrix_calvin_io::CHPData::GetOrigCnt(), affymetrix_calvin_io::CHPTilingData::GetTilingSequenceEntryCount(), affymetrix_calvin_io::CelFileData::HasNumPixels(), affymetrix_calvin_io::CelFileData::HasStdev(), affymetrix_calvin_io::GenericData::IsDSHPartiallyRead(), affymetrix_calvin_io::MMDataSetDataWriter::MapData(), affymetrix_calvin_io::MMDataSetDataWriter::OpenData(), affymetrix_calvin_io::DATFileReader::ReadSubgrids(), affymetrix_calvin_io::DataSet::Rows(), affymetrix_calvin_io::DATData::UpdateDataSetRowCount(), affymetrix_calvin_io::CelFileData::UpdateDataSetRowCount(), and affymetrix_calvin_io::DataSetHeaderWriter::WriteRowCnt().
int32_t DataSetHeader::GetRowSize () const
Definition at line 61 of file DataSetHeader.cpp.
References GetColumnCnt(), GetColumnInfo(), and affymetrix_calvin_io::ColumnInfo::GetSize().
Referenced by GetDataSize(), affymetrix_calvin_io::DataSetUpdater::Initialize(), and affymetrix_calvin_io::MMDataSetDataWriter::MMDataSetDataWriter().
void affymetrix_calvin_io::DataSetHeader::SetDataStartFilePos (u_int32_t pos) [inline]
Set the file position of the start of the DataSet data. The value set here is not written to the file.
Definition at line 145 of file DataSetHeader.h.
Referenced by affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::DataSetHeaderReader::ReadDataFilePos(), affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader(), and affymetrix_calvin_io::DataSetWriter::WriteHeader().
void affymetrix_calvin_io::DataSetHeader::SetHeaderStartFilePos (u_int32_t pos) [inline]
Set the file position of the start of the DataSet header. The value set here is not written to the file.
Definition at line 138 of file DataSetHeader.h.
Referenced by affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::DataSetHeaderReader::ReadDataSetStartFilePos(), and affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader().
void DataSetHeader::SetName (const std::wstring & p)
Definition at line 72 of file DataSetHeader.cpp.
References name.
Referenced by affymetrix_calvin_io::DataSetHeaderAppend::AddDataSetHeader(), AddDataSetHeaderToGroup(), affymetrix_calvin_io::CHPData::AddExprColumns(), affymetrix_calvin_io::CHPData::AddGenoColumns(), affymetrix_calvin_io::CHPData::AddReseqColumns(), affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::CHPData::AddUnivColumns(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), affymetrix_calvin_io::CDFData::CreateContentsGroup(), affymetrix_calvin_io::DATFileUpdater::CreateGridDataSetHeader(), affymetrix_calvin_io::CDFFileWriter::CreateProbeSetWriter(), affymetrix_calvin_io::DATFileUpdater::CreateSubGridDataSetHeader(), affymetrix_calvin_io::CDFCntrlFileWriter::GetCntrlProbeSetWriter(), affymetrix_calvin_io::DataSetHeaderReader::ReadName(), affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::SetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetForceCnt(), affymetrix_calvin_io::CelFileData::SetIntensityCount(), affymetrix_calvin_io::CelFileData::SetMaskCount(), affymetrix_calvin_io::CHPData::SetOrigCnt(), affymetrix_calvin_io::CelFileData::SetOutlierCount(), affymetrix_calvin_io::DATData::SetPixelCount(), affymetrix_calvin_io::CelFileData::SetPixelCount(), affymetrix_calvin_io::DATData::SetStatsCount(), affymetrix_calvin_io::CelFileData::SetStdDevCount(), and OutputMessageStream::Write().
void affymetrix_calvin_io::DataSetHeader::SetNextSetFilePos (u_int32_t pos) [inline]
Set the file position of the next DataSet header.
Definition at line 150 of file DataSetHeader.h.
Referenced by affymetrix_calvin_io::DataGroupHeaderUpdater::AppendDataSetHeader(), affymetrix_calvin_io::DataSetHeaderReader::ReadNextDataSetFilePos(), affymetrix_calvin_io::DataGroupHeaderUpdater::ReplaceDataSetHeader(), and affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset().
void DataSetHeader::SetRowCnt (int32_t p)
Definition at line 164 of file DataSetHeader.cpp.
References rowCount.
Referenced by AddDataSetHeaderToGroup(), affymetrix_calvin_io::CHPTilingData::AddTilingSequenceData(), affymetrix_calvin_io::MultiChannelCelFileCollater::CopyDataSetHdr(), affymetrix_calvin_io::CDFData::CreateContentsGroup(), affymetrix_calvin_io::DATFileUpdater::CreateGridDataSetHeader(), affymetrix_calvin_io::CDFFileWriter::CreateProbeSetWriter(), affymetrix_calvin_io::DATFileUpdater::CreateSubGridDataSetHeader(), affymetrix_calvin_io::DataSetHeaderReader::ReadRowCount(), affymetrix_calvin_io::CHPData::SetBackgroundZoneCnt(), affymetrix_calvin_io::CHPQuantificationDetectionData::SetEntryCount(), affymetrix_calvin_io::CHPQuantificationData::SetEntryCount(), affymetrix_calvin_io::CHPMultiDataData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetEntryCount(), affymetrix_calvin_io::CHPData::SetForceCnt(), affymetrix_calvin_io::CelFileData::SetIntensityCount(), affymetrix_calvin_io::CelFileData::SetMaskCount(), affymetrix_calvin_io::CHPData::SetOrigCnt(), affymetrix_calvin_io::CelFileData::SetOutlierCount(), affymetrix_calvin_io::DATData::SetPixelCount(), affymetrix_calvin_io::CelFileData::SetPixelCount(), affymetrix_calvin_io::DATData::SetStatsCount(), affymetrix_calvin_io::CelFileData::SetStdDevCount(), affymetrix_calvin_io::DATData::UpdateDataSetRowCount(), affymetrix_calvin_io::CelFileData::UpdateDataSetRowCount(), and OutputMessageStream::Write().
Member Data Documentation
ColInfoVector affymetrix_calvin_io::DataSetHeader::columnTypes [private]
column information
Definition at line 63 of file DataSetHeader.h.
Referenced by AddAsciiColumn(), AddByteColumn(), AddColumn(), AddFloatColumn(), AddIntColumn(), AddShortColumn(), AddUByteColumn(), AddUIntColumn(), AddUnicodeColumn(), AddUShortColumn(), Clear(), GetColumnCnt(), and GetColumnInfo().
u_int32_t affymetrix_calvin_io::DataSetHeader::dataStartFilePos [private]
file position of the start of the data
Definition at line 67 of file DataSetHeader.h.
Referenced by Clear().
u_int32_t affymetrix_calvin_io::DataSetHeader::headerStartFilePos [private]
file position of the start of the dataSet header
Definition at line 65 of file DataSetHeader.h.
Referenced by Clear().
std::wstring affymetrix_calvin_io::DataSetHeader::name [private]
data data set name
Definition at line 59 of file DataSetHeader.h.
Referenced by Clear(), GetName(), and SetName().
ParameterNameValueTypeVector affymetrix_calvin_io::DataSetHeader::nameValParams [private]
name/value pairs
Definition at line 61 of file DataSetHeader.h.
Referenced by affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), ClearNameValueParameters(), GetNameValIterators(), and GetNameValParamCnt().
u_int32_t affymetrix_calvin_io::DataSetHeader::nextSetFilePos [private]
file position of the next dataSet header
Definition at line 69 of file DataSetHeader.h.
Referenced by Clear().
int32_t affymetrix_calvin_io::DataSetHeader::rowCount [private]
total rows in the data set
Definition at line 57 of file DataSetHeader.h.
Referenced by Clear(), GetDataSize(), GetRowCnt(), and SetRowCnt().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/DataSetHeader.h
C:/f112/affy/sdk/calvin_files/data/src/DataSetHeader.cpp