Affymetrix Fusion SDK: affx1lq::C1LQFileData Class Reference
affx1lq::C1LQFileData Class Reference
#include <1LQFileData.h>
Public Member Functions
C1LQFileData ()
~C1LQFileData ()
void SetFileName (const char *name)
std::string GetFileName () const
bool Read ()
bool Exists ()
void Clear ()
int GetNumberColumns () const
int GetNumberRows () const
int GetNumberRotates ()
void Rotate ()
const std::list< DataEntry > & GetEntries () const
Protected Member Functions
bool Read (std::ifstream &instr)
Protected Attributes
std::string m_FileName
int m_NumberRows
int m_NumberColumns
std::list< DataEntry > m_Entries
int m_NumberRotates
Detailed Description
The class provides storage and reading capabilities for 1LQ files.
Definition at line 101 of file 1LQFileData.h.
Constructor & Destructor Documentation
C1LQFileData::C1LQFileData ()
Constructor
Definition at line 44 of file 1LQFileData.cpp.
C1LQFileData::~C1LQFileData ()
Destructor
Definition at line 53 of file 1LQFileData.cpp.
References Clear().
Member Function Documentation
void C1LQFileData::Clear (void)
Deallocate memory.
Definition at line 61 of file 1LQFileData.cpp.
References m_Entries, m_NumberColumns, and m_NumberRows.
Referenced by Read(), and ~C1LQFileData().
bool C1LQFileData::Exists ()
Checks if the file exists.
Returns:
True if exists.
Definition at line 71 of file 1LQFileData.cpp.
References m_FileName.
const std::list<DataEntry>& affx1lq::C1LQFileData::GetEntries () const [inline]
Gets the data list.
Returns:
The data list.
Definition at line 179 of file 1LQFileData.h.
References m_Entries.
Referenced by affxgrc::CGRCFileWriter::ParseLibData().
std::string affx1lq::C1LQFileData::GetFileName () const [inline]
Gets the full path of the file.
Returns:
The full path of the file.
Definition at line 141 of file 1LQFileData.h.
References m_FileName.
int affx1lq::C1LQFileData::GetNumberColumns () const [inline]
Gets the number of columns of features on the array.
Returns:
The number of columns of features on the array.
Definition at line 159 of file 1LQFileData.h.
References m_NumberColumns.
Referenced by affxgrc::CGRCFileWriter::ParseLibData().
int affx1lq::C1LQFileData::GetNumberRotates () [inline]
Return the number of times this data has been rotate.
Returns:
The number of times this data has been rotate. In normal condition, it should return 0 for no-rotation or 1 for one time rotate.
Definition at line 171 of file 1LQFileData.h.
References m_NumberRotates.
int affx1lq::C1LQFileData::GetNumberRows () const [inline]
Gets the number of rows of features on the array.
Returns:
The number of rows of features on the array.
Definition at line 164 of file 1LQFileData.h.
References m_NumberRows.
Referenced by affxgrc::CGRCFileWriter::ParseLibData().
bool C1LQFileData::Read ()
Reads the contents of the file.
Returns:
True if successful.
Definition at line 82 of file 1LQFileData.cpp.
References Clear(), and m_FileName.
bool C1LQFileData::Read (std::ifstream & instr) [protected]
Reads the file data
Parameters:
instr The input file stream.
Returns:
True if successful.
Definition at line 115 of file 1LQFileData.cpp.
References affx1lq::_DataEntry::atom, affx1lq::_DataEntry::block, affx1lq::_DataEntry::cbase, Clear(), affx1lq::_DataEntry::destype, affx1lq::_DataEntry::expos, affx1lq::_DataEntry::feature, affx1lq::_DataEntry::ipbase, m_Entries, m_NumberColumns, m_NumberRows, MAXLINELENGTH, NUM_1LQ_COLUMNS, affx1lq::_DataEntry::pbase, affx1lq::_DataEntry::plength, affx1lq::_DataEntry::position, affx1lq::_DataEntry::probe, affx1lq::_DataEntry::qualifier, ReadNextLine(), affx1lq::_DataEntry::tbase, affx1lq::_DataEntry::unit, affx1lq::_DataEntry::x, and affx1lq::_DataEntry::y.
void C1LQFileData::Rotate ()
Rotate the data one time.
Definition at line 195 of file 1LQFileData.cpp.
References m_Entries, m_NumberColumns, and m_NumberRows.
void affx1lq::C1LQFileData::SetFileName (const char * name) [inline]
Sets the full path to the BAR file.
Parameters:
name The file name.
Definition at line 136 of file 1LQFileData.h.
References m_FileName.
Member Data Documentation
std::list<DataEntry> affx1lq::C1LQFileData::m_Entries [protected]
The sequence results.
Definition at line 121 of file 1LQFileData.h.
Referenced by Clear(), GetEntries(), Read(), and Rotate().
std::string affx1lq::C1LQFileData::m_FileName [protected]
The full path to the BAR file.
Definition at line 112 of file 1LQFileData.h.
Referenced by Exists(), GetFileName(), Read(), and SetFileName().
int affx1lq::C1LQFileData::m_NumberColumns [protected]
The number of columns of features on the array.
Definition at line 118 of file 1LQFileData.h.
Referenced by Clear(), GetNumberColumns(), Read(), and Rotate().
int affx1lq::C1LQFileData::m_NumberRotates [protected]
The number of rotations that have been done on the data.
Definition at line 124 of file 1LQFileData.h.
Referenced by GetNumberRotates().
int affx1lq::C1LQFileData::m_NumberRows [protected]
The number of rows of features on the array.
Definition at line 115 of file 1LQFileData.h.
Referenced by Clear(), GetNumberRows(), Read(), and Rotate().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/1LQFileData.h
C:/f112/affy/sdk/file/1LQFileData.cpp