Affymetrix Fusion SDK: CelCheck Class Reference
CelCheck Class Reference
#include <CelCheck.h>
Public Member Functions
CelCheck (std::vector< std::string > &generated, std::vector< std::string > &gold, double eps, const std::string &prefix="affymetrix-", int diffAllowed=0)
Constructor.
CelCheck (std::string &generated, std::string &gold, double eps, const std::string &prefix="affymetrix-", int diffAllowed=0)
bool checkFilePair (int genIdx, int goldIdx, std::string &msg)
bool check (std::string &msg)
Private Member Functions
bool headersSame (const std::string &generated, const std::string &gold, std::string &msgs)
bool dataSame (const std::string &generated, const std::string &gold, std::string &msgs)
Static Private Member Functions
static void fillInToIgnore (std::set< std::string > &ignoreMap, const std::string &prefix)
Private Attributes
std::vector< std::string > m_Generated
std::vector< std::string > m_Gold
double m_Eps
std::string m_Prefix
int m_DiffAllowed
Detailed Description
Class for testing that CEL files are the same +/- some epsilon. Also checks to make sure that at least some of the headers are the same (times/dates/versions change so not checked).
Definition at line 54 of file CelCheck.h.
Constructor & Destructor Documentation
CelCheck::CelCheck (std::vector< std::string > & generated, std::vector< std::string > & gold, double eps, const std::string & prefix = "affymetrix-", int diffAllowed = 0) [inline]
Constructor.
Parameters:
generated
gold the reference data to compare with
eps epsilon
prefix
diffAllowed
Returns:
Definition at line 67 of file CelCheck.h.
CelCheck::CelCheck (std::string & generated, std::string & gold, double eps, const std::string & prefix = "affymetrix-", int diffAllowed = 0) [inline]
Definition at line 80 of file CelCheck.h.
Member Function Documentation
bool CelCheck::check (std::string & msg) [inline]
Definition at line 129 of file CelCheck.h.
Referenced by main().
bool CelCheck::checkFilePair (int genIdx, int goldIdx, std::string & msg) [inline]
Check to make sure that two files are the same +/- some epsilon.
Parameters:
msg - Fills in an error message if test fails, empty string otherwise.
Returns:
- Returns true if files are close enough, false otherwise.
Definition at line 99 of file CelCheck.h.
References affymetrix_calvin_exceptions::CalvinException::Description(), Fs::normalizePath(), ToStr(), and Except::what().
bool CelCheck::dataSame (const std::string & generated, const std::string & gold, std::string & msgs) [inline, private]
Definition at line 160 of file CelCheck.h.
References affymetrix_fusion_io::FusionCELData::GetIntensity(), affymetrix_fusion_io::FusionCELData::GetNumCells(), Verbose::out(), affymetrix_fusion_io::FusionCELData::Read(), affymetrix_fusion_io::FusionCELData::SetFileName(), and ToStr().
static void CelCheck::fillInToIgnore (std::set< std::string > & ignoreMap, const std::string & prefix) [inline, static, private]
Definition at line 150 of file CelCheck.h.
bool CelCheck::headersSame (const std::string & generated, const std::string & gold, std::string & msgs) [inline, private]
Todo:
implement cel header check once we have new regression data
Definition at line 155 of file CelCheck.h.
Member Data Documentation
int CelCheck::m_DiffAllowed [private]
Definition at line 208 of file CelCheck.h.
double CelCheck::m_Eps [private]
Definition at line 206 of file CelCheck.h.
std::vector<std::string> CelCheck::m_Generated [private]
Definition at line 204 of file CelCheck.h.
std::vector<std::string> CelCheck::m_Gold [private]
Definition at line 205 of file CelCheck.h.
std::string CelCheck::m_Prefix [private]
Definition at line 207 of file CelCheck.h.
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/CelCheck.h