Affymetrix Fusion SDK: CFusionCHPLegacyDataCOM Class Reference
CFusionCHPLegacyDataCOM Class Reference
#include <FusionCHPLegacyDataCOM.h>
Public Member Functions
CFusionCHPLegacyDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
STDMETHOD() get_FileTypeIdentifier (BSTR *pVal)
STDMETHOD() get_FileTypeIdentifiers (VARIANT *pVal)
STDMETHOD() FromBase (IFusionCHPData *baseChp, VARIANT_BOOL *pVal)
STDMETHOD() GetExpressionResults (int index, IFusionExpressionProbeSetResults *pVal)
STDMETHOD() GetGenotypingResults (int index, IFusionGenotypeProbeSetResults *pVal)
STDMETHOD() GetUniversalResults (int index, IFusionUniversalProbeSetResults *pVal)
STDMETHOD() GetReseqResults (IFusionResequencingResults *pVal)
STDMETHOD() Clear (void)
STDMETHOD() GetHeader (IFusionCHPHeader **pVal)
STDMETHOD() get_FileId (BSTR *pVal)
STDMETHOD() GetProbeSetName (int index, BSTR *pVal)
Private Attributes
affymetrix_fusion_io::FusionCHPLegacyData * chp
Detailed Description
Definition at line 29 of file FusionCHPLegacyDataCOM.h.
Constructor & Destructor Documentation
CFusionCHPLegacyDataCOM::CFusionCHPLegacyDataCOM () [inline]
Definition at line 36 of file FusionCHPLegacyDataCOM.h.
Member Function Documentation
STDMETHODIMP CFusionCHPLegacyDataCOM::Clear (void)
Definition at line 136 of file FusionCHPLegacyDataCOM.cpp.
References chp, and affymetrix_fusion_io::FusionCHPLegacyData::Clear().
HRESULT CFusionCHPLegacyDataCOM::FinalConstruct () [inline]
Definition at line 56 of file FusionCHPLegacyDataCOM.h.
void CFusionCHPLegacyDataCOM::FinalRelease () [inline]
Definition at line 61 of file FusionCHPLegacyDataCOM.h.
STDMETHODIMP CFusionCHPLegacyDataCOM::FromBase (IFusionCHPData * baseChp, VARIANT_BOOL * pVal)
Definition at line 87 of file FusionCHPLegacyDataCOM.cpp.
References chp, and CFusionCHPDataCOM::GetChip().
STDMETHODIMP CFusionCHPLegacyDataCOM::get_FileId (BSTR * pVal)
Definition at line 56 of file FusionCHPLegacyDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPLegacyData::FileId().
STDMETHODIMP CFusionCHPLegacyDataCOM::get_FileTypeIdentifier (BSTR * pVal)
Definition at line 48 of file FusionCHPLegacyDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPData::FileTypeIdentifier().
STDMETHODIMP CFusionCHPLegacyDataCOM::get_FileTypeIdentifiers (VARIANT * pVal)
Definition at line 62 of file FusionCHPLegacyDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPData::FileTypeIdentifiers().
STDMETHODIMP CFusionCHPLegacyDataCOM::GetExpressionResults (int index, IFusionExpressionProbeSetResults * pVal)
Definition at line 100 of file FusionCHPLegacyDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPLegacyData::GetExpressionResults(), and CFusionExpressionProbeSetResultsCOM::Results().
STDMETHODIMP CFusionCHPLegacyDataCOM::GetGenotypingResults (int index, IFusionGenotypeProbeSetResults * pVal)
Definition at line 109 of file FusionCHPLegacyDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPLegacyData::GetGenotypingResults(), and CFusionGenotypeProbeSetResultsCOM::Results().
STDMETHODIMP CFusionCHPLegacyDataCOM::GetHeader (IFusionCHPHeader ** pVal)
Definition at line 147 of file FusionCHPLegacyDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPLegacyData::GetHeader(), and CFusionCHPHeaderCOM::SetHeader().
STDMETHODIMP CFusionCHPLegacyDataCOM::GetProbeSetName (int index, BSTR * pVal)
Definition at line 159 of file FusionCHPLegacyDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPLegacyData::GetProbeSetName().
STDMETHODIMP CFusionCHPLegacyDataCOM::GetReseqResults (IFusionResequencingResults * pVal)
Definition at line 127 of file FusionCHPLegacyDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPLegacyData::GetReseqResults(), and CFusionResequencingResultsCOM::Results().
STDMETHODIMP CFusionCHPLegacyDataCOM::GetUniversalResults (int index, IFusionUniversalProbeSetResults * pVal)
Definition at line 118 of file FusionCHPLegacyDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPLegacyData::GetUniversalResults(), and CFusionUniversalProbeSetResultsCOM::Results().
STDMETHODIMP CFusionCHPLegacyDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 33 of file FusionCHPLegacyDataCOM.cpp.
Member Data Documentation
affymetrix_fusion_io::FusionCHPLegacyData* CFusionCHPLegacyDataCOM::chp [private]
Definition at line 68 of file FusionCHPLegacyDataCOM.h.
Referenced by Clear(), FromBase(), get_FileId(), get_FileTypeIdentifier(), get_FileTypeIdentifiers(), GetExpressionResults(), GetGenotypingResults(), GetHeader(), GetProbeSetName(), GetReseqResults(), and GetUniversalResults().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPLegacyDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPLegacyDataCOM.cpp