Affymetrix Fusion SDK: affymetrix_calvin_io::CHPQuantificationDetectionFileWriter Class Reference
affymetrix_calvin_io::CHPQuantificationDetectionFileWriter Class Reference
#include <CalvinCHPQuantificationDetectionFileWriter.h>
Public Member Functions
CHPQuantificationDetectionFileWriter (CHPQuantificationDetectionData &p)
~CHPQuantificationDetectionFileWriter ()
void WriteEntry (const affymetrix_calvin_data::ProbeSetQuantificationDetectionData &p)
void SeekToDataSet ()
Private Member Functions
void WriteHeaders ()
int32_t SetFilePositions ()
Private Attributes
GenericFileWriter * writer
DataSetWriter * dataSetWriter
int32_t entryPos
int32_t maxProbeSetName
Detailed Description
A class to write a quant/detection CHP file.
Definition at line 35 of file CalvinCHPQuantificationDetectionFileWriter.h.
Constructor & Destructor Documentation
CHPQuantificationDetectionFileWriter::CHPQuantificationDetectionFileWriter (CHPQuantificationDetectionData & p)
Constructor
Parameters:
p Pointer to the quant/detection CHP data object.
Definition at line 28 of file CalvinCHPQuantificationDetectionFileWriter.cpp.
References affymetrix_calvin_io::CHPQuantificationDetectionData::GetFileHeader(), affymetrix_calvin_io::CHPQuantificationDetectionData::GetMaxProbeSetName(), maxProbeSetName, WriteHeaders(), and writer.
CHPQuantificationDetectionFileWriter::~CHPQuantificationDetectionFileWriter ()
Destructor
Definition at line 35 of file CalvinCHPQuantificationDetectionFileWriter.cpp.
References writer.
Member Function Documentation
void CHPQuantificationDetectionFileWriter::SeekToDataSet ()
Seeks to the data set.
Definition at line 59 of file CalvinCHPQuantificationDetectionFileWriter.cpp.
References dataSetWriter, entryPos, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter(), affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), and writer.
int32_t CHPQuantificationDetectionFileWriter::SetFilePositions () [private]
Sets the file positions.
Returns:
The current file position.
Definition at line 76 of file CalvinCHPQuantificationDetectionFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::DataSetWriter::GetDataSetSize(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), affymetrix_calvin_io::GenericFileWriter::SeekFromCurrentPos(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), and writer.
Referenced by WriteHeaders().
void CHPQuantificationDetectionFileWriter::WriteEntry (const affymetrix_calvin_data::ProbeSetQuantificationDetectionData & p)
Write an entry.
Parameters:
p A pointer to a quant/detection entry.
Definition at line 66 of file CalvinCHPQuantificationDetectionFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::id, maxProbeSetName, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::name, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::pvalue, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::quantification, and affymetrix_calvin_io::DataSetWriter::Write().
void CHPQuantificationDetectionFileWriter::WriteHeaders () [private]
Writes the headers to the file.
Definition at line 40 of file CalvinCHPQuantificationDetectionFileWriter.cpp.
References dataSetWriter, entryPos, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriters(), SetFilePositions(), affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), and writer.
Referenced by CHPQuantificationDetectionFileWriter().
Member Data Documentation
DataSetWriter* affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::dataSetWriter [private]
The data set writer.
Definition at line 42 of file CalvinCHPQuantificationDetectionFileWriter.h.
Referenced by SeekToDataSet(), SetFilePositions(), WriteEntry(), and WriteHeaders().
int32_t affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::entryPos [private]
The file position of the entry for each data set.
Definition at line 45 of file CalvinCHPQuantificationDetectionFileWriter.h.
Referenced by SeekToDataSet(), and WriteHeaders().
int32_t affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::maxProbeSetName [private]
The maximum probe set name length.
Definition at line 48 of file CalvinCHPQuantificationDetectionFileWriter.h.
Referenced by CHPQuantificationDetectionFileWriter(), and WriteEntry().
GenericFileWriter* affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::writer [private]
The file writer.
Definition at line 39 of file CalvinCHPQuantificationDetectionFileWriter.h.
Referenced by CHPQuantificationDetectionFileWriter(), SeekToDataSet(), SetFilePositions(), WriteHeaders(), and ~CHPQuantificationDetectionFileWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPQuantificationDetectionFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPQuantificationDetectionFileWriter.cpp