Affymetrix Fusion SDK: CFusionBaseCallTypeCOM Class Reference
CFusionBaseCallTypeCOM Class Reference
#include <FusionBaseCallTypeCOM.h>
Public Member Functions
CFusionBaseCallTypeCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_fusion_io::FusionBaseCallType & Call ()
STDMETHOD() get_Position (int *pVal)
STDMETHOD() get_Call (CHAR *pVal)
Private Attributes
affymetrix_fusion_io::FusionBaseCallType call
Detailed Description
Definition at line 29 of file FusionBaseCallTypeCOM.h.
Constructor & Destructor Documentation
CFusionBaseCallTypeCOM::CFusionBaseCallTypeCOM () [inline]
Definition at line 36 of file FusionBaseCallTypeCOM.h.
Member Function Documentation
affymetrix_fusion_io::FusionBaseCallType& CFusionBaseCallTypeCOM::Call () [inline]
Definition at line 68 of file FusionBaseCallTypeCOM.h.
Referenced by CFusionResequencingResultsCOM::GetOrigCall().
HRESULT CFusionBaseCallTypeCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionBaseCallTypeCOM.h.
void CFusionBaseCallTypeCOM::FinalRelease () [inline]
Definition at line 60 of file FusionBaseCallTypeCOM.h.
STDMETHODIMP CFusionBaseCallTypeCOM::get_Call (CHAR * pVal)
Definition at line 48 of file FusionBaseCallTypeCOM.cpp.
References call, and affymetrix_fusion_io::FusionBaseCallType::GetCall().
STDMETHODIMP CFusionBaseCallTypeCOM::get_Position (int * pVal)
Definition at line 42 of file FusionBaseCallTypeCOM.cpp.
References call, and affymetrix_fusion_io::FusionBaseCallType::GetPosition().
STDMETHODIMP CFusionBaseCallTypeCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 27 of file FusionBaseCallTypeCOM.cpp.
Member Data Documentation
affymetrix_fusion_io::FusionBaseCallType CFusionBaseCallTypeCOM::call [private]
Definition at line 65 of file FusionBaseCallTypeCOM.h.
Referenced by get_Call(), and get_Position().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionBaseCallTypeCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionBaseCallTypeCOM.cpp