Affymetrix Fusion SDK: affx::TsvFileDiff Class Reference
affx::TsvFileDiff Class Reference
#include <TsvFileDiff.h>
Public Types
enum { FMT_1 = 1, FMT_2 = 2 }
Public Member Functions
TsvFileDiff ()
~TsvFileDiff ()
void clear ()
void open_residuals (const std::string &filename, affx::TsvFile &tsv1, affx::TsvFile &tsv2)
void close_residuals ()
void p_linenums (affx::TsvFile &tsv1, affx::TsvFile &tsv2)
void p_linenums (int lnum1, int lnum2)
void p_line (affx::TsvFile &tsv)
bool p_inc ()
void p_diff_1line (affx::TsvFile &tsv1, affx::TsvFile &tsv2)
void p_diff_2line (affx::TsvFile &tsv1, affx::TsvFile &tsv2)
int readOptionsFrom (const std::string &filename)
int readOptionsFrom (affx::TsvFile &tsv)
int diff (const std::string &filename1, const std::string &filename2)
int diff (affx::TsvFile &tsv1, affx::TsvFile &tsv2)
int diffHeaders (affx::TsvFile &tsv1, affx::TsvFile &tsv2)
int diffData (affx::TsvFile &tsv1, affx::TsvFile &tsv2)
Public Attributes
bool m_opt_print_same
bool m_opt_print_linenums
int m_opt_print_format
int m_opt_print_max
bool m_opt_do_headers
bool m_opt_do_data
double m_opt_max_diff
int m_diff_cnt
int m_print_cnt
std::string m_residuals_filename
affx::TsvFile * m_residuals_tsv
Detailed Description
Definition at line 37 of file TsvFileDiff.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
FMT_1
FMT_2
Definition at line 52 of file TsvFileDiff.h.
Constructor & Destructor Documentation
affx::TsvFileDiff::TsvFileDiff ()
Definition at line 37 of file TsvFileDiff.cpp.
References clear(), FMT_2, m_opt_do_data, m_opt_do_headers, m_opt_max_diff, m_opt_print_format, m_opt_print_linenums, m_opt_print_max, m_opt_print_same, m_residuals_filename, and m_residuals_tsv.
affx::TsvFileDiff::~TsvFileDiff ()
Definition at line 57 of file TsvFileDiff.cpp.
Member Function Documentation
void affx::TsvFileDiff::clear ()
Definition at line 63 of file TsvFileDiff.cpp.
Referenced by TsvFileDiff().
void affx::TsvFileDiff::close_residuals ()
Definition at line 104 of file TsvFileDiff.cpp.
int affx::TsvFileDiff::diff (const std::string & filename1, const std::string & filename2)
Definition at line 241 of file TsvFileDiff.cpp.
References affx::TsvFile::close(), affx::TsvFile::open(), and affx::TSV_OK.
Referenced by main().
int affx::TsvFileDiff::diff (affx::TsvFile & tsv1, affx::TsvFile & tsv2)
Definition at line 456 of file TsvFileDiff.cpp.
int affx::TsvFileDiff::diffData (affx::TsvFile & tsv1, affx::TsvFile & tsv2)
Definition at line 319 of file TsvFileDiff.cpp.
References affx::TsvFile::eof(), Err::errAbort(), FMT_1, FMT_2, affx::TsvFile::get(), affx::TsvFile::getColumnCount(), affx::TsvFile::lineLevel(), affx::TsvFile::nextLine(), affx::TsvFile::rewind(), and affx::TSV_OK.
int affx::TsvFileDiff::diffHeaders (affx::TsvFile & tsv1, affx::TsvFile & tsv2)
Definition at line 266 of file TsvFileDiff.cpp.
References affx::TsvFile::getHeader(), affx::TsvFile::headersBegin(), affx::TsvFile::headersNext(), and affx::TSV_OK.
void affx::TsvFileDiff::open_residuals (const std::string & filename, affx::TsvFile & tsv1, affx::TsvFile & tsv2)
Definition at line 73 of file TsvFileDiff.cpp.
References affxutil::Guid::GenerateNewGuid(), affx::TsvFile::getColumnCount(), affx::TsvFile::getColumnName(), affx::TsvFile::getFileName(), and affx::TsvFile::getLevelCount().
void affx::TsvFileDiff::p_diff_1line (affx::TsvFile & tsv1, affx::TsvFile & tsv2)
Definition at line 200 of file TsvFileDiff.cpp.
References affx::TsvFile::get(), affx::TsvFile::getColumnCount(), and affx::TsvFile::lineLevel().
void affx::TsvFileDiff::p_diff_2line (affx::TsvFile & tsv1, affx::TsvFile & tsv2)
Definition at line 228 of file TsvFileDiff.cpp.
bool affx::TsvFileDiff::p_inc ()
Definition at line 188 of file TsvFileDiff.cpp.
void affx::TsvFileDiff::p_line (affx::TsvFile & tsv)
Definition at line 167 of file TsvFileDiff.cpp.
References affx::TsvFile::get(), affx::TsvFile::getColumnCount(), and affx::TsvFile::lineLevel().
void affx::TsvFileDiff::p_linenums (int lnum1, int lnum2)
Definition at line 146 of file TsvFileDiff.cpp.
References P_LINENUMS_WIDTH.
void affx::TsvFileDiff::p_linenums (affx::TsvFile & tsv1, affx::TsvFile & tsv2)
Definition at line 140 of file TsvFileDiff.cpp.
References affx::TsvFile::lineNumber().
int affx::TsvFileDiff::readOptionsFrom (affx::TsvFile & tsv)
Definition at line 129 of file TsvFileDiff.cpp.
int affx::TsvFileDiff::readOptionsFrom (const std::string & filename)
Definition at line 116 of file TsvFileDiff.cpp.
References affx::TsvFile::close(), Err::errAbort(), affx::TsvFile::open(), and affx::TSV_OK.
Member Data Documentation
int affx::TsvFileDiff::m_diff_cnt
Definition at line 49 of file TsvFileDiff.h.
Referenced by main().
bool affx::TsvFileDiff::m_opt_do_data
Definition at line 46 of file TsvFileDiff.h.
Referenced by main(), and TsvFileDiff().
bool affx::TsvFileDiff::m_opt_do_headers
Definition at line 45 of file TsvFileDiff.h.
Referenced by main(), and TsvFileDiff().
double affx::TsvFileDiff::m_opt_max_diff
Definition at line 47 of file TsvFileDiff.h.
Referenced by main(), and TsvFileDiff().
int affx::TsvFileDiff::m_opt_print_format
Definition at line 42 of file TsvFileDiff.h.
Referenced by main(), and TsvFileDiff().
bool affx::TsvFileDiff::m_opt_print_linenums
Definition at line 41 of file TsvFileDiff.h.
Referenced by main(), and TsvFileDiff().
int affx::TsvFileDiff::m_opt_print_max
Definition at line 43 of file TsvFileDiff.h.
Referenced by main(), and TsvFileDiff().
bool affx::TsvFileDiff::m_opt_print_same
Definition at line 40 of file TsvFileDiff.h.
Referenced by main(), and TsvFileDiff().
int affx::TsvFileDiff::m_print_cnt
Definition at line 50 of file TsvFileDiff.h.
std::string affx::TsvFileDiff::m_residuals_filename
Definition at line 58 of file TsvFileDiff.h.
Referenced by main(), and TsvFileDiff().
affx::TsvFile* affx::TsvFileDiff::m_residuals_tsv
Definition at line 59 of file TsvFileDiff.h.
Referenced by TsvFileDiff().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/TsvFileDiff.h
C:/f112/affy/sdk/file/TsvFile/TsvFileDiff.cpp