Affymetrix Fusion SDK: affymetrix_calvin_io::DataSetHeaderWriter Class Reference
affymetrix_calvin_io::DataSetHeaderWriter Class Reference
#include <DataSetHeaderWriter.h>
Public Member Functions
DataSetHeaderWriter ()
~DataSetHeaderWriter ()
void Write (std::ofstream &os, DataSetHeader &dc)
void UpdateDataOffset (std::ofstream &os, u_int32_t pos) const
void UpdateNextDataSetOffset (std::ofstream &os, u_int32_t pos) const
Private Member Functions
void WriteDataOffset (std::ofstream &os, u_int32_t pos)
void WriteNextDataSetOffset (std::ofstream &os, u_int32_t pos)
void WriteName (std::ofstream &os, const DataSetHeader &dc) const
void WriteNameValCnt (std::ofstream &os, const DataSetHeader &dc) const
void WriteNameValParams (std::ofstream &os, DataSetHeader &dc)
void WriteColumnTypes (std::ofstream &os, const DataSetHeader &dc) const
void WriteColumnCnt (std::ofstream &os, const DataSetHeader &dc) const
void WriteRowCnt (std::ofstream &os, const DataSetHeader &dc) const
Private Attributes
u_int32_t dataPos
u_int32_t nextDataSetPos
Detailed Description
Definition at line 34 of file DataSetHeaderWriter.h.
Constructor & Destructor Documentation
affymetrix_calvin_io::DataSetHeaderWriter::DataSetHeaderWriter () [inline]
Definition at line 44 of file DataSetHeaderWriter.h.
References dataPos, and nextDataSetPos.
affymetrix_calvin_io::DataSetHeaderWriter::~DataSetHeaderWriter () [inline]
Definition at line 45 of file DataSetHeaderWriter.h.
Member Function Documentation
void DataSetHeaderWriter::UpdateDataOffset (std::ofstream & os, u_int32_t pos) const
Definition at line 44 of file DataSetHeaderWriter.cpp.
References dataPos, and affymetrix_calvin_io::FileOutput::WriteUInt32().
Referenced by affymetrix_calvin_io::DataSetWriter::WriteHeader().
void DataSetHeaderWriter::UpdateNextDataSetOffset (std::ofstream & os, u_int32_t pos) const
Definition at line 60 of file DataSetHeaderWriter.cpp.
References nextDataSetPos, and affymetrix_calvin_io::FileOutput::WriteUInt32().
Referenced by affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset().
void DataSetHeaderWriter::Write (std::ofstream & os, DataSetHeader & dc)
Definition at line 26 of file DataSetHeaderWriter.cpp.
References WriteColumnCnt(), WriteColumnTypes(), WriteDataOffset(), WriteName(), WriteNameValCnt(), WriteNameValParams(), WriteNextDataSetOffset(), and WriteRowCnt().
Referenced by affymetrix_calvin_io::DataSetWriter::WriteHeader().
void DataSetHeaderWriter::WriteColumnCnt (std::ofstream & os, const DataSetHeader & dc) const [private]
Definition at line 97 of file DataSetHeaderWriter.cpp.
References affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
void DataSetHeaderWriter::WriteColumnTypes (std::ofstream & os, const DataSetHeader & dc) const [private]
Definition at line 102 of file DataSetHeaderWriter.cpp.
References affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::ColumnInfo::GetColumnType(), affymetrix_calvin_io::ColumnInfo::GetName(), affymetrix_calvin_io::ColumnInfo::GetSize(), affymetrix_calvin_io::FileOutput::WriteInt32(), WriteInt8(), and affymetrix_calvin_io::FileOutput::WriteString16().
Referenced by Write().
void DataSetHeaderWriter::WriteDataOffset (std::ofstream & os, u_int32_t pos) [private]
Definition at line 38 of file DataSetHeaderWriter.cpp.
References dataPos, and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
void DataSetHeaderWriter::WriteName (std::ofstream & os, const DataSetHeader & dc) const [private]
Definition at line 70 of file DataSetHeaderWriter.cpp.
References affymetrix_calvin_io::DataSetHeader::GetName(), and affymetrix_calvin_io::FileOutput::WriteString16().
Referenced by Write().
void DataSetHeaderWriter::WriteNameValCnt (std::ofstream & os, const DataSetHeader & dc) const [private]
Definition at line 75 of file DataSetHeaderWriter.cpp.
References affymetrix_calvin_io::DataSetHeader::GetNameValParamCnt(), and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
void DataSetHeaderWriter::WriteNameValParams (std::ofstream & os, DataSetHeader & dc) [private]
Definition at line 80 of file DataSetHeaderWriter.cpp.
References affymetrix_calvin_io::DataSetHeader::GetNameValIterators(), affymetrix_calvin_io::FileOutput::WriteBlob(), and affymetrix_calvin_io::FileOutput::WriteString16().
Referenced by Write().
void DataSetHeaderWriter::WriteNextDataSetOffset (std::ofstream & os, u_int32_t pos) [private]
Definition at line 54 of file DataSetHeaderWriter.cpp.
References nextDataSetPos, and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
void DataSetHeaderWriter::WriteRowCnt (std::ofstream & os, const DataSetHeader & dc) const [private]
Definition at line 116 of file DataSetHeaderWriter.cpp.
References affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and affymetrix_calvin_io::FileOutput::WriteInt32().
Referenced by Write().
Member Data Documentation
u_int32_t affymetrix_calvin_io::DataSetHeaderWriter::dataPos [private]
Definition at line 39 of file DataSetHeaderWriter.h.
Referenced by DataSetHeaderWriter(), UpdateDataOffset(), and WriteDataOffset().
u_int32_t affymetrix_calvin_io::DataSetHeaderWriter::nextDataSetPos [private]
Definition at line 40 of file DataSetHeaderWriter.h.
Referenced by DataSetHeaderWriter(), UpdateNextDataSetOffset(), and WriteNextDataSetOffset().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/DataSetHeaderWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/DataSetHeaderWriter.cpp