Affymetrix Fusion SDK: affx::TsvFile Class Reference
affx::TsvFile Class Reference
A class for reading and writing Tab Seperated Value (TSV) files. See the TsvFile format document and the example program tsv-example.cpp .
#include <TsvFile.h>
Public Member Functions
TsvFile ()
Create and clear.
TsvFile (const std::string &fname)
Create, clear and open a tsvfile.
~TsvFile ()
Destroy a TsvFile.
TsvFile (const TsvFile &that)
Dont allow a TsvFile to be copied.
TsvFile & operator= (const TsvFile &that)
int setError (int err)
Set the error value.
int getError ()
Return the current error number.
int clearError ()
clear the error
void setAbortOnError (bool value)
Set the option abortonerror.
int bindErrorCnt ()
The number of binding errors. (vars which couldnt be linked)
void flush ()
Flushs the data to the file. If you are debugging, you might want to explictly flush the output. It is not required. Be warned that this slows down the IO.
int setFilename (const std::string &filename)
Set the filename for this Tsv.
std::string getFileName ()
Get the filename of the TsvFile.
int getLevelCount ()
The number of levels defined.
int getColumnCount (int clvl)
The number of columns for this level.
int open (const std::string &filename)
Opens a file -- attempts to guess some defaults.
int openCsv (const std::string &filename)
Open a Csv file.
int openTable (const std::string &filename)
Opens a file as a table.
int close ()
Close the file.
void clear ()
Closes the file and clears bindings and other info.
void clearBindings ()
Clear the bindings of columns to variables.
void clearIndexes ()
Clear (ie delete) all the indexes.
void clearFields ()
Clear all the fields. (set them all to null)
void clearFieldsBelowClvl (int clvl_start)
Clear the columns at greater indents.
void clearColumnHeaders ()
clear all the column headers.
void clearHeaders ()
clear all the headers.
int headerCount ()
Note that the "headerN" lines may not have been generated yet.
void default_options ()
Resets the options to the defaults.
int isFileOpen ()
Check if file is opened.
bool is_open ()
bool good ()
int f_getline (std::string &line)
Read a line from a TsvFile into a string.
bool f_lookingat_eol ()
Are we looking at the end of a line?
int f_read_header_v1 ()
Read a classic "v1" header from the top of a file.
int f_read_header_v2 ()
Read and parse a v2 header line.
int f_read_headers ()
Read all the headers and set up the file.
int f_advance_tabs ()
Gobble up the tabs without skipping over eol.
int f_advance_eol ()
advance over the end of the line (eol)
int f_read_column (affx::TsvFileField *col)
Read data into a column from the file.
int f_read_columns (int clvl)
Read the columns of this level.
void headers_to_fields_v2 ()
Parse the "headerN" lines.
int defineColumn (int clvl, int cidx, const std::string &cname)
User methods.
int defineColumn (int clvl, int cidx, const std::string &cname, tsv_type_t ctype)
record the mapping of column names (cname) to column indexes (cidx).
int defineFile (const std::string &definition)
Define a TSV file from a string of field names.
int defineFileParse (const std::string &definition)
Overlay the definition on top of the current file.
tsv_return_t writeOpen (const std::string &filename)
open the stream for writing
tsv_return_t writeTsv (const std::string &filename)
open the file for writing in "v2" format.
tsv_return_t writeTsv_v1 (const std::string &filename)
Set the options up for "tsv" format and write the tsv-v1 header.
tsv_return_t writeTsv_v2 (const std::string &filename)
Open the file and write the headers.
tsv_return_t writeCsv (const std::string &filename)
Set the options up for "csv" format and write the CSV header.
int write_str (const std::string &str)
Write a string to the output stream, quoting if needed.
void writeHeaders ()
Write the file headers.
void writeKeyValHeaders ()
Write the keyval headers to the file.
void writeColumnHeaders ()
Write the "headerN" lines which define the Columns.
void writeColumnHeaders_clvl (int clvl)
Write the headers for a given level.
void writeFieldSep (int cnt)
Write a number of Field seperators to the file.
int writeLevel (int clvl)
Write a level of data to the file.
int defineIndex (int clvl, const std::string &cname, int kind, int flags)
Creates an index object.
int defineIndex (int clvl, int cidx, int kind, int flags)
Creates an index object.
int getHeader (const std::string &key, std::string &val)
Get the value of a header.
int getHeader (const std::string &key, int &val)
Get the integer value of a header.
int getHeader (const std::string &key, double &val)
Get the integer value of a header.
int getHeader (const std::string &key, std::vector< std::string > &val)
Get string values of all headers exactly matching a key.
int getHeaderAppend (const std::string &key, std::vector< std::string > &val)
Append string values of all headers exactly matching a key.
int getHeaderMatchingKeySubstr (const std::string &key, std::vector< std::string > &val)
Get string values of all headers containing the substring.
int getHeaderMatchingKeySubstrAppend (const std::string &key, std::vector< std::string > &val)
Append string values of all headers containing the substring.
int hasHeaderEqualTo (const std::string &key, const std::string &val)
Does the file have a key==value header which matches.
int addHeader (const std::string &key, const std::string &val, int order)
Add a key-value to the headers plus its sort order.
int addHeader (const std::string &key, const std::string &val)
Add a key-value to the headers.
int addHeader (const std::string &key, int val)
Add a int value as a header.
int addHeader (const std::string &key, double val)
Add a int value as a header.
int addHeader (const std::string &key, const std::vector< std::string > &val)
Add a series of headers as key=val1, key=val2, key=valN.
int addHeadersFrom (affx::TsvFile &f_tsv, int flags)
Add all the headers from another TSV to this one.
int addHeadersFrom (affx::TsvFile &f_tsv, const std::string &prefix, int flags)
append the headers from another TSV to this one.
int addHeadersFrom (affx::TsvFile &f_tsv, const std::string &prefix, std::vector< std::string > &key_vec)
Add headers specified in a vector to this TSV from another TSV.
int addHeader_nocheck (const std::string &key, const std::string &val, int order)
Add a header to the TSV without checking to see if it is legal.
int addHeader_nocheck (const std::string &key, const std::string &val)
Add a header to the TSV without checking to see if it is legal.
int headerKeyLegal (const std::string &key)
Is the key a legal key to have in a header?
int headersCount ()
How many headers are there?
void headersBegin ()
Start at the beginning of the headers.
int headersNext (std::string &key, std::string &val)
Advance to the next header of the file and set the values.
int headersFindNext (const std::string &key, std::string &val)
Advance to the next header matching key.
int deleteHeaders (const std::string &key)
Remove the headers named with the key.
int deleteHeaders (const std::vector< std::string > &keys)
int deleteHeaders (const char **keys)
int printDuplicateHeaders ()
TsvFileHeaderLine * nextHeaderPtr ()
Return the next non-null header pointer. NULL when at or past the end.
int deleteHeaderPtr (TsvFileHeaderLine *hdrptr)
Remove the header pointed to.
int addHeaderComment (const std::string &comment)
Add a comment to the headers.
int addHeaderComment (const std::string &comment, int order)
Add a comment to the headers.
int addHeaderComments (const std::vector< std::string > &comments)
void repackHeaders ()
void resortHeaders ()
Sort the headers of this TSV file by (order,key,value)
int writeFileComment (const std::string &comment)
Writes a comment directly to the file.
int cname2cidx (int clvl, int cidx)
Covert a column index to a column index.
int cname2cidx (int clvl, const std::string &cname, tsv_optionflag_t options=TSV_OPT_NONE)
Look up the cidx of a column.
int cname2cidx (int clvl, const std::string &alias1, const std::string &alias2, tsv_optionflag_t options=TSV_OPT_NONE)
Find a column index by one of its names.
int cname2cidx (int clvl, const std::string &alias1, const std::string &alias2, const std::string &alias3, tsv_optionflag_t options=TSV_OPT_NONE)
Find a column index by one of its names.
int cname2cidx (int clvl, const std::string &alias1, const std::string &alias2, const std::string &alias3, const std::string &alias4, tsv_optionflag_t options=TSV_OPT_NONE)
Find a column index by one of its names.
TsvFileField * clvlcidx2colptr (int clvl, int cidx)
Get a pointer to a column given clvl and cidx.
TsvFileField * clvlcidx2colptr (int clvl, const std::string &cname)
Return a pointer to the column.
int cidx2cname (int clvl, int cidx, std::string &cname)
Get the name of a column by its level and index.
std::string getColumnName (int clvl, int cidx)
int setPrecision (int places)
int setPrecision (int clvl, const std::string &cname, int places)
int setPrecision (int clvl, int cidx, int places)
TsvFileBinding * linkvar_alloc ()
Allocate a new binding object.
void linkvar_column (int clvl, int cidx, affx::TsvFileBinding *var)
Link a binding to a column.
void linkvar_link (affx::TsvFileBinding *var)
Link a binding var to a column.
int linkvars_makelinks ()
Examine the list of bindings and establish the linkages.
int linkvars_maybe ()
Dont do anything if the linkages are done, otherwise link.
void linkvars_clear ()
clear all the linkages from columns to vars
void linkvars_free ()
int formatOk ()
Is the format of the file ok.
void unbindAll ()
Remove all the bindings.
int bind (int clvl, const std::string &name, std::string *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, int cidx, std::string *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, const std::string &name, int *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, int cidx, int *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, const std::string &name, double *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, int cidx, double *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, const std::string &name, float *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, int cidx, float *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, const std::string &name, unsigned int *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, int cidx, unsigned int *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, const std::string &name, uint64_t *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
int bind (int clvl, int cidx, uint64_t *ptr, tsv_bindopt_t flags=TSV_BIND_OPTIONAL, int interncache_size=TSV_INTERNSIZE_UNSET)
void printBindingErrors ()
print messages about unbound variables.
unsigned int lineNumber ()
What line did we just read? (external)
linenum_t lineNum ()
The line number of the current line (internal)
int lineLevel ()
The indentation level of the line just read.
bool eof ()
Returns the value of m_eof.
int nextLine ()
advance to the next line and bind the values
int nextLevel (int clvl)
Skip to the next level of data which matches seek_clvl.
int rewind ()
Rewind back to the start of the data and clear the fields.
int seekLine (linenum_t line)
Seek to the start of a line but dont read it.
int gotoLine (linenum_t line)
goto a line reading the parent lines and then the line itself
int countTotalDataLines ()
void currentLineAsString (std::string &line)
bool isNull (int clvl, int cidx)
Is the field set?
bool isNull (int clvl, const std::string &cname)
Is the field set?
bool isEmpty (int clvl, int cidx)
Is the field empty (null or no value)?
bool isEmpty (int clvl, const std::string &cname)
Is the field set?
affx::tsv_type_t get_type (int clvl, const std::string &cidx)
Return the declared type of this column.
affx::tsv_type_t get_type (int clvl, int cidx)
Return the declared type of this column.
affx::tsv_type_t set_type (int clvl, const std::string &cidx, affx::tsv_type_t type)
Return the declared type of this column.
affx::tsv_type_t set_type (int clvl, int cidx, affx::tsv_type_t type)
Return the declared type of this column.
int clear_max_sizes ()
int deduce_types ()
Read a couple of lines of the TsvFile and figure out the types.
int deduce_sizes ()
int get (int clvl, int cidx, std::string &val)
Get the string value of a field.
int get (int clvl, int cidx, short &val)
int get (int clvl, int cidx, int &val)
Get the integer value of a field.
int get (int clvl, int cidx, double &val)
Get the double value of a field.
int get (int clvl, int cidx, float &val)
Get the float value of a field.
int get (int clvl, int cidx, unsigned int &val)
Get the unsigned integer value of a field.
int get (int clvl, int cidx, uint64_t &val)
Get the unsigned integer value of a field.
int get (int clvl, const std::string &cname, std::string &val)
Get the string value of a field.
int get (int clvl, const std::string &cname, short &val)
int get (int clvl, const std::string &cname, int &val)
Get the integer value of a field.
int get (int clvl, const std::string &cname, double &val)
Get the double value of a field.
int get (int clvl, const std::string &cname, float &val)
Get the float value of a field.
int get (int clvl, const std::string &cname, unsigned int &val)
Get the unsigned integer value of a field.
int get (int clvl, const std::string &cname, uint64_t &val)
Get the unsigned integer value of a field.
int get (int clvl, int cidx, std::vector< int > *val, char sep=',')
int get (int clvl, int cidx, std::vector< float > *val, char sep=',')
int get (int clvl, int cidx, std::vector< double > *val, char sep=',')
int get (int clvl, int cidx, std::vector< std::string > *val, char sep=',')
int get (int clvl, const std::string &cname, std::vector< int > *val, char sep=',')
int get (int clvl, const std::string &cname, std::vector< float > *val, char sep=',')
int get (int clvl, const std::string &cname, std::vector< double > *val, char sep=',')
int get (int clvl, const std::string &cname, std::vector< std::string > *val, char sep=',')
int set (int clvl, int cidx, const std::string &val)
int set (int clvl, int cidx, int val)
int set (int clvl, int cidx, float val)
int set (int clvl, int cidx, double val)
int set (int clvl, int cidx, unsigned int val)
int set (int clvl, int cidx, uint64_t val)
int set (int clvl, const std::string &cname, const std::string &val)
int set (int clvl, const std::string &cname, int val)
int set (int clvl, const std::string &cname, float val)
int set (int clvl, const std::string &cname, double val)
int set (int clvl, const std::string &cname, unsigned int val)
int set (int clvl, const std::string &cname, uint64_t val)
int set (int clvl, int cidx, const std::vector< int > &val, char sep=',')
int set (int clvl, int cidx, const std::vector< float > &val, char sep=',')
int set (int clvl, int cidx, const std::vector< double > &val, char sep=',')
int set (int clvl, int cidx, const std::vector< std::string > &val, char sep=',')
int set (int clvl, const std::string &cname, const std::vector< int > &val, char sep=',')
int set (int clvl, const std::string &cname, const std::vector< float > &val, char sep=',')
int set (int clvl, const std::string &cname, const std::vector< double > &val, char sep=',')
int set (int clvl, const std::string &cname, const std::vector< std::string > &val, char sep=',')
TsvFileIndex * index_alloc ()
Allocate a TsvFileIndex.
int indexBuild ()
build the indexes for a file
int indexBuildMaybe ()
build the indexes if needed
TsvFileIndex * index_matching (int clvl, int cidx, int kind)
Find an index which matches what we need.
TsvFileIndex * index_matching_1 (int clvl, int cidx, std::string &val)
Do we have a index on this column for strings?
TsvFileIndex * index_matching_1 (int clvl, int cidx, int val)
Do we have a index on this column for ints?
TsvFileIndex * index_matching_1 (int clvl, int cidx, double val)
Do we have a index on this column for doubles?
TsvFileIndex * index_matching_1 (int clvl, int cidx, unsigned int val)
Do we have a index on this column for unsigned ints?
TsvFileIndex * index_matching_1 (int clvl, int cidx, uint64_t val)
Do we have a index on this column for uint64_t?
std::fstream::pos_type line_fpos ()
int findBegin (int clvl, std::string cname, int op, std::string val, int flags=TSV_ORDERBY_LINE)
int findBegin (int clvl, int cidx, int op, std::string val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findBegin (int clvl, std::string cname, int op, int val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findBegin (int clvl, int cidx, int op, int val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findBegin (int clvl, std::string cname, int op, double val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findBegin (int clvl, int cidx, int op, double val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findBegin (int clvl, std::string cname, int op, unsigned int val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findBegin (int clvl, int cidx, int op, unsigned int val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findBegin (int clvl, std::string cname, int op, uint64_t val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findBegin (int clvl, int cidx, int op, uint64_t val, int flags=TSV_ORDERBY_LINE)
like findBegin with different types
int findNext ()
Goto the next result.
unsigned int findResultsCount ()
Return the count of found lines.
int findResultsClear ()
Clear the results of the last findBegin.
void dump ()
used for debugging
void dump_headers ()
Dump the header values of the tsvfile.
void dump_data ()
Dump the data of the tsvfile.
void dump_bindings ()
Dump the bindings of the tsvfile.
void dump_indexes ()
Dump the indexes.
void copyFormat (affx::TsvFile &f_tsv)
Copy the "format" of the file.
int copyLevel (affx::TsvFile &f_tsv, int clvl)
copy the fields from one tsv to another tsv
affx::TsvFile * tsv_ptr ()
Return a pointer to ourself for swig.
Static Public Member Functions
static int getLineCountInFile (const std::string &filename, bool abortOnError=false)
Count the number of total lines, assuming a text file.
static int replaceCharInFile (const std::string &filename, char a, char b, bool abortOnError=true)
Replace a character in a file with another.
static int extractColToVec (const std::string &fileName, const std::string &colName, std::vector< std::string > *vec)
static int extractColToVec (const std::string &fileName, const std::string &colName, std::vector< std::string > *vec, int optEscapeOk)
static affx::tsv_type_t stringToColType (const std::string &str)
Public Attributes
bool m_optAllowDataComment
Options which can be set.
bool m_optAbortOnError
?
bool m_optAutoColumns
add more columns as needed.
bool m_optAutoDequote
remove quotes when reading?
bool m_optAutoIndex
?
bool m_optAutoSenseSep
Autosense between tabs and commas.
bool m_optAutoTrim
remove whitespace from value?
bool m_optCheckFormatOnOpen
Automatically check for binary files?
bool m_optDoQuote
Put quotes on output?
char m_optEscapeChar
the escape char to use
bool m_optEscapeOk
Obey the escapechar?
bool m_optHasColumnHeader
read the first line as column headers?
bool m_optThrowOnError
?
unsigned char m_optQuoteChar
Quote char to use.
std::string m_optEndl
End of line sequence to use.
unsigned char m_optFieldSep
Field seperator defaults to TAB.
bool m_optHdrDblQuoteComma
Header contains '","'.
bool m_optLinkVarsOnOpen
Link variables when calling open()
char m_optQuoteChar1
Quoting Character.
char m_optQuoteChar2
Quoting Character.
int m_optPrecision
Default Precision.
int m_errno
The error number.
bool m_eof
at eof?
int m_fileFormat
What version of file was read?
std::string m_fileName
The filename being visited.
std::fstream::pos_type m_fileDataPos
Where the data begins (line 0)
std::string m_headName
Tag name of column header.
std::filebuf * m_rdbuf
Private Types
typedef TsvFileHeaderLine header_t
typedef std::multimap
< std::string, header_t * >
::iterator header_iter_t
Private Member Functions
void init ()
init a new object
template<typename T1 , typename T2 >
int findBegin_tmpl (int clvl, T1 cidx, int op, T2 val, int flags)
Handy template.
Private Attributes
bool m_rawOpen
int m_lineNum
The current line number.
int m_lineLvl
The level of the current line.
std::fstream m_fileStream
std::fstream::pos_type m_line_fpos
Where the current line starts.
std::vector< header_t * > m_headers_vec
bool m_headers_vec_packed
int m_headers_idx
header_t * m_headers_curptr
std::multimap< std::string,
header_t * > m_headers_bykey
the key=val headers in string form.
header_iter_t m_headers_iter
used for headersNext
std::string m_headers_curkey_string
std::vector< std::vector
< affx::TsvFileField > > m_column_map
The columns by column level and column index.
std::vector< std::map
< std::string, int > > m_cnametocidx_map
Map the columns names to column indexes.
bool m_linkvars_done
The state of the bound and linked vars...
int m_linkvars_errors
Count of link errors.
int m_linkvars_warnings
Count of link warnings.
std::vector< TsvFileBinding * > m_linkvars_vec
Vector of bindings linked to us.
bool m_index_done
Have the indexing been done?
std::vector< unsigned int > m_index_linefpos
A map of line numbers to file postions.
std::vector< std::vector
< unsigned int > > m_index_lineclvl
A map of line numbers by level so we can find the parent lines.
std::vector< TsvFileIndex * > m_index_vec
A vector of indexes which are defined.
std::vector< unsigned int > m_findresults
A vector of lines which match the last "findBegin".
std::vector< unsigned int >
::size_type m_findresults_pos
The postition we are at in the returned results.
Detailed Description
A class for reading and writing Tab Seperated Value (TSV) files. See the TsvFile format document and the example program tsv-example.cpp .
Definition at line 418 of file TsvFile.h.
Member Typedef Documentation
typedef std::multimap<std::string,header_t*>::iterator affx::TsvFile::header_iter_t [private]
Definition at line 421 of file TsvFile.h.
typedef TsvFileHeaderLine affx::TsvFile::header_t [private]
Definition at line 420 of file TsvFile.h.
Constructor & Destructor Documentation
affx::TsvFile::TsvFile ()
Create and clear.
Returns:
lvalue
Definition at line 1309 of file TsvFile.cpp.
affx::TsvFile::TsvFile (const std::string & filename)
Create, clear and open a tsvfile.
Parameters:
filename
Returns:
lvalue
Definition at line 1318 of file TsvFile.cpp.
affx::TsvFile::~TsvFile ()
Destroy a TsvFile.
Returns:
lvalue
Definition at line 1334 of file TsvFile.cpp.
affx::TsvFile::TsvFile (const TsvFile & that)
Dont allow a TsvFile to be copied.
Definition at line 1326 of file TsvFile.cpp.
References TSV_ERR_ABORT.
Member Function Documentation
int affx::TsvFile::addHeader (const std::string & key, const std::string & val, int order)
Add a key-value to the headers plus its sort order.
Todo:
maybe add a flag to "addHeader" to skip checking?
Parameters:
key string key
val string val
order the sort order
Returns:
tsv_error_t
Definition at line 1798 of file TsvFile.cpp.
References affx::TSV_OK.
Referenced by check_headers_1(), check_headers_2(), check_headers_3(), check_headers_4(), example_write_1(), example_write_2(), example_write_3(), example_write_4(), tsv_util_benchmark(), and tsv_util_paste_basic().
int affx::TsvFile::addHeader (const std::string & key, const std::string & val)
Add a key-value to the headers.
Parameters:
key string key
val string value
Remarks:
sort order defaults to "0"
Definition at line 1785 of file TsvFile.cpp.
int affx::TsvFile::addHeader (const std::string & key, int val)
Add a int value as a header.
Parameters:
key name of header
val value to set
Returns:
Definition at line 1812 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::addHeader (const std::string & key, double val)
Add a int value as a header.
Parameters:
key name of header
val double value to set
Returns:
Definition at line 1826 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::addHeader (const std::string & key, const std::vector< std::string > & val)
Add a series of headers as key=val1, key=val2, key=valN.
Parameters:
key name of header
val vector of values to add.
Returns:
Definition at line 1855 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::addHeader_nocheck (const std::string & key, const std::string & val, int order)
Add a header to the TSV without checking to see if it is legal.
Parameters:
key key
val value
order sort order
Returns:
TSV_OK
Definition at line 1922 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::addHeader_nocheck (const std::string & key, const std::string & val)
Add a header to the TSV without checking to see if it is legal.
Parameters:
key string key
val string val
Returns:
tsv_error_t
Definition at line 1897 of file TsvFile.cpp.
int affx::TsvFile::addHeaderComment (const std::string & comment)
Add a comment to the headers.
Parameters:
comment string comment
Returns:
tsv_error_t
Remarks:
sort order defaults to order added
Definition at line 1878 of file TsvFile.cpp.
Referenced by check_headers_1(), and check_headers_2().
int affx::TsvFile::addHeaderComment (const std::string & comment, int order)
Add a comment to the headers.
Parameters:
comment string comment
order sort order
Returns:
tsv_error_t
Definition at line 1868 of file TsvFile.cpp.
int affx::TsvFile::addHeaderComments (const std::vector< std::string > & comments)
Definition at line 1884 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::addHeadersFrom (affx::TsvFile & f_tsv, int flags)
Add all the headers from another TSV to this one.
Parameters:
f_tsv where to copy the headers from
flags what kind of headers to add (TSV_ADD_COMMENTS,TSV_ADD_KEYS)
Returns:
TSV_OK
Definition at line 1936 of file TsvFile.cpp.
Referenced by tsv_util_copy().
int affx::TsvFile::addHeadersFrom (affx::TsvFile & f_tsv, const std::string & prefix, int flags)
append the headers from another TSV to this one.
Parameters:
f_tsv TSV to copy headers from
prefix string to prefix keys with
flags which kind of headers to add (TSV_ADD_COMMENTS,TSV_ADD_KEYS)
Returns:
tsv_error_t
Definition at line 1947 of file TsvFile.cpp.
References headersBegin(), headersNext(), affx::TSV_ADD_COMMENTS, affx::TSV_ADD_KEYS, and affx::TSV_OK.
int affx::TsvFile::addHeadersFrom (affx::TsvFile & f_tsv, const std::string & prefix, std::vector< std::string > & key_vec)
Add headers specified in a vector to this TSV from another TSV.
Parameters:
f_tsv source of TSV headers
prefix prefix to add to keys
key_vec vector of keys to add
Returns:
tsv_error_t
Definition at line 1973 of file TsvFile.cpp.
References getHeader(), and affx::TSV_OK.
int affx::TsvFile::bind (int clvl, const std::string & name, std::string * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
Referenced by affx::BgpFile::makeBgpBindings(), affx::ClfFile::makeClfBindings(), affx::PgfFile::makePgfBindings(), SnpTable::open(), tsvJoin::openInputFiles(), dumpPgf::openInputFiles(), and dumpPgf::readIdFiles().
int affx::TsvFile::bind (int clvl, int cidx, std::string * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, const std::string & name, int * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, int cidx, int * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, const std::string & name, double * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, int cidx, double * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, const std::string & name, float * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, int cidx, float * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, const std::string & name, unsigned int * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, int cidx, unsigned int * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, const std::string & name, uint64_t * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bind (int clvl, int cidx, uint64_t * ptr, tsv_bindopt_t flags = TSV_BIND_OPTIONAL, int interncache_size = TSV_INTERNSIZE_UNSET)
int affx::TsvFile::bindErrorCnt ()
The number of binding errors. (vars which couldnt be linked)
Returns:
same as linkvars_makelinks
Definition at line 3189 of file TsvFile.cpp.
int affx::TsvFile::cidx2cname (int clvl, int cidx, std::string & cname)
Get the name of a column by its level and index.
Todo:
rename this nicer...
Parameters:
clvl column level
cidx column index
cname where to put the name
Returns:
tsv_return_t
Definition at line 2597 of file TsvFile.cpp.
References affx::TsvFileField::m_cname, affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
Referenced by copyFormat(), example_dump_columns(), SnpTable::open(), tsvJoin::openInputFiles(), and dumpPgf::openInputFiles().
void affx::TsvFile::clear ()
Closes the file and clears bindings and other info.
clear all the resources of a TsvFile.
Definition at line 1430 of file TsvFile.cpp.
Referenced by extractColToVec().
int affx::TsvFile::clear_max_sizes ()
Definition at line 3458 of file TsvFile.cpp.
References affx::TSV_OK.
void affx::TsvFile::clearBindings ()
Clear the bindings of columns to variables.
Definition at line 1455 of file TsvFile.cpp.
void affx::TsvFile::clearColumnHeaders ()
clear all the column headers.
Definition at line 1665 of file TsvFile.cpp.
int affx::TsvFile::clearError ()
clear the error
Returns:
tsv_error_t
Definition at line 1532 of file TsvFile.cpp.
References affx::TSV_OK.
void affx::TsvFile::clearFields ()
Clear all the fields. (set them all to null)
Definition at line 1483 of file TsvFile.cpp.
void affx::TsvFile::clearFieldsBelowClvl (int clvl_start)
Clear the columns at greater indents.
Parameters:
clvl_start Clear fields at or larger than this level.
Definition at line 1491 of file TsvFile.cpp.
void affx::TsvFile::clearHeaders ()
clear all the headers.
Definition at line 1647 of file TsvFile.cpp.
void affx::TsvFile::clearIndexes ()
Clear (ie delete) all the indexes.
Definition at line 1471 of file TsvFile.cpp.
int affx::TsvFile::close ()
Close the file.
Close the TsvFile.
Definition at line 2759 of file TsvFile.cpp.
References affx::TSV_OK.
Referenced by check_comment_1(), check_csv_1(), check_headers_2(), check_index_1(), check_nextline(), check_read_table_1(), check_read_vec_1(), check_winpath_1(), check_write_10(), check_write_vec_1(), affx::PgfFile::close(), affx::ClfFile::close(), affx::BgpFile::close(), affx::TsvFileDiff::diff(), example_dump_columns(), example_index_1(), example_read_table_1(), example_write_1(), example_write_2(), example_write_3(), example_write_4(), extractColToVec(), SnpTable::open(), dumpPgf::readIdFiles(), affx::TsvFileDiff::readOptionsFrom(), tsv_util_benchmark(), tsv_util_copy(), tsv_util_headers(), tsv_util_linecount(), tsv_util_paste_basic(), and tsv_util_print_duplicate_headerkeys().
TsvFileField * affx::TsvFile::clvlcidx2colptr (int clvl, int cidx)
Get a pointer to a column given clvl and cidx.
Parameters:
clvl level of column
cidx index of column
Returns:
NULL if not found
Definition at line 2572 of file TsvFile.cpp.
TsvFileField * affx::TsvFile::clvlcidx2colptr (int clvl, const std::string & cname)
Return a pointer to the column.
Parameters:
clvl level of column
cname name of column
Returns:
NULL if not found
Definition at line 2587 of file TsvFile.cpp.
int affx::TsvFile::cname2cidx (int clvl, int cidx)
Covert a column index to a column index.
Parameters:
clvl level
cidx index
Returns:
column index
Remarks:
This exists to make the templates eaiser to write
Definition at line 2557 of file TsvFile.cpp.
References affx::TSV_ERR_NOTFOUND.
Referenced by check_field_name(), and extractColToVec().
int affx::TsvFile::cname2cidx (int clvl, const std::string & cname, tsv_optionflag_t options = TSV_OPT_NONE)
Look up the cidx of a column.
Parameters:
clvl column level at which to look
cname column name
Returns:
level or less than zero on error
Definition at line 2460 of file TsvFile.cpp.
References affx::tolower(), affx::TSV_ERR_NOTFOUND, and affx::TSV_OPT_CASEINSENSTIVE.
int affx::TsvFile::cname2cidx (int clvl, const std::string & alias1, const std::string & alias2, const std::string & alias3, tsv_optionflag_t options = TSV_OPT_NONE)
Find a column index by one of its names.
Parameters:
clvl level
alias1 first alias to try
alias2 second alias to try
alias3 third alias to try
Returns:
Definition at line 2518 of file TsvFile.cpp.
References CNAME_FIND, and affx::TSV_ERR_NOTFOUND.
int affx::TsvFile::cname2cidx (int clvl, const std::string & alias1, const std::string & alias2, tsv_optionflag_t options = TSV_OPT_NONE)
Find a column index by one of its names.
Parameters:
clvl level
alias1 first alias to try
alias2 second alias to try
Returns:
Definition at line 2502 of file TsvFile.cpp.
References CNAME_FIND, and affx::TSV_ERR_NOTFOUND.
int affx::TsvFile::cname2cidx (int clvl, const std::string & alias1, const std::string & alias2, const std::string & alias3, const std::string & alias4, tsv_optionflag_t options = TSV_OPT_NONE)
Find a column index by one of its names.
Parameters:
clvl level
alias1 first alias to try
alias2 second alias to try
alias3 third alias to try
alias4 fourth alias to try
Returns:
Definition at line 2537 of file TsvFile.cpp.
References CNAME_FIND, and affx::TSV_ERR_NOTFOUND.
void affx::TsvFile::copyFormat (affx::TsvFile & f_tsv)
Copy the "format" of the file.
Parameters:
f_tsv the tsv to copy from
Definition at line 4736 of file TsvFile.cpp.
References cidx2cname(), getColumnCount(), and getLevelCount().
Referenced by tsv_util_copy().
int affx::TsvFile::copyLevel (affx::TsvFile & f_tsv, int clvl)
copy the fields from one tsv to another tsv
Parameters:
f_tsv
clvl level at which to copy
Returns:
tsv_return_t
Definition at line 4754 of file TsvFile.cpp.
References getColumnCount(), getLevelCount(), m_column_map, affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
Referenced by tsv_util_copy().
int affx::TsvFile::countTotalDataLines ()
Definition at line 4091 of file TsvFile.cpp.
References affx::TSV_OK.
Referenced by check_csv_1(), and check_read_table_1().
void affx::TsvFile::currentLineAsString (std::string & line)
Definition at line 4111 of file TsvFile.cpp.
int affx::TsvFile::deduce_sizes ()
Definition at line 3470 of file TsvFile.cpp.
References affx::TsvFileField::m_buffer, affx::TsvFileField::m_max_size, and affx::TSV_OK.
int affx::TsvFile::deduce_types ()
Read a couple of lines of the TsvFile and figure out the types.
Returns:
Definition at line 3396 of file TsvFile.cpp.
References affx::TSV_ERR_UNKNOWN, affx::TSV_OK, affx::TSV_TYPE_DOUBLE, affx::TSV_TYPE_INT, affx::TSV_TYPE_STRING, and affx::TSV_TYPE_UNKNOWN.
void affx::TsvFile::default_options ()
Resets the options to the defaults.
set options to their defaults
Definition at line 1342 of file TsvFile.cpp.
References TSV_CHAR_TAB, and TSV_EOL.
int affx::TsvFile::defineColumn (int clvl, int cidx, const std::string & cname)
User methods.
Define a column with a.
Parameters:
clvl
cidx
cname
ctype
Returns:
Definition at line 2411 of file TsvFile.cpp.
References affx::TSV_TYPE_UNKNOWN.
Referenced by check_field_name(), check_write_10(), check_write_vec_1(), example_write_4(), tsv_util_benchmark(), and tsv_util_paste_basic().
int affx::TsvFile::defineColumn (int clvl, int cidx, const std::string & cname, tsv_type_t ctype)
record the mapping of column names (cname) to column indexes (cidx).
Parameters:
clvl column level the mapping is for
cidx position the column is at
cname name of the column
Remarks:
resizes the maps as needed
Definition at line 2424 of file TsvFile.cpp.
References affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
int affx::TsvFile::defineFile (const std::string & definition)
Define a TSV file from a string of field names.
Todo:
Parameters:
definition
Returns:
tsv_return_t
Definition at line 4407 of file TsvFile.cpp.
Referenced by affx::BgpFile::defineFileBgp(), affx::ClfFile::defineFileClf(), affx::PgfFile::defineFilePgf(), example_write_1(), and example_write_3().
int affx::TsvFile::defineFileParse (const std::string & definition)
Overlay the definition on top of the current file.
Parameters:
definition
Returns:
tsv_return_t
Remarks:
defineFile uses "\n" to seperate levels, "\t" to seperate columns and "," to add options to the field name. at the moment there arent any options.
Definition at line 4422 of file TsvFile.cpp.
References affx::splitstr(), and affx::TSV_OK.
int affx::TsvFile::defineIndex (int clvl, int cidx, int kind, int flags)
Creates an index object.
Parameters:
clvl column level
cidx column
kind
flags
Returns:
Definition at line 4005 of file TsvFile.cpp.
References affx::TsvFileIndex::m_bindto_cidx, affx::TsvFileIndex::m_bindto_clvl, affx::TsvFileIndex::m_bindto_type, affx::TsvFileIndex::m_flags, affx::TsvFileIndex::m_kind, affx::TSV_BINDTO_CIDX, and affx::TSV_OK.
int affx::TsvFile::defineIndex (int clvl, const std::string & cname, int kind, int flags)
Creates an index object.
Todo:
should check for duplicate indexes and not make them
Parameters:
clvl column level
cname column name
kind TSV_INDEX_STRING or TSV_INDEX_INT
flags unused at the moment
Returns:
TSV_OK
Remarks:
The indexing is not done until it is actually needed
Definition at line 3984 of file TsvFile.cpp.
References affx::TsvFileIndex::m_bindto_clvl, affx::TsvFileIndex::m_bindto_cname, affx::TsvFileIndex::m_bindto_type, affx::TsvFileIndex::m_flags, affx::TsvFileIndex::m_kind, affx::TSV_BINDTO_CNAME, and affx::TSV_OK.
Referenced by check_index_1(), example_index_1(), example_index_2(), tsvJoin::openInputFiles(), and dumpPgf::openInputFiles().
int affx::TsvFile::deleteHeaderPtr (affx::TsvFileHeaderLine * hdrptr)
Remove the header pointed to.
Parameters:
hdrptr pointer to the header to delete
Returns:
tsv_error_t
Definition at line 2209 of file TsvFile.cpp.
References affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
int affx::TsvFile::deleteHeaders (const std::string & key)
Remove the headers named with the key.
Parameters:
key the header key value.
Returns:
tsv_error_t
Definition at line 2174 of file TsvFile.cpp.
References affx::TSV_OK.
Referenced by check_headers_4().
int affx::TsvFile::deleteHeaders (const std::vector< std::string > & keys)
Definition at line 2186 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::deleteHeaders (const char ** keys)
Definition at line 2195 of file TsvFile.cpp.
References affx::TSV_OK.
void affx::TsvFile::dump ()
used for debugging
Dump the meta-information of the tsvfile.
Remarks:
Used for debugging
Definition at line 3870 of file TsvFile.cpp.
void affx::TsvFile::dump_bindings ()
Dump the bindings of the tsvfile.
Remarks:
Used for debugging
Definition at line 3912 of file TsvFile.cpp.
References affx::TsvFileBinding::m_bindto_cidx, affx::TsvFileBinding::m_bindto_clvl, and affx::TsvFileBinding::m_bindto_cname.
void affx::TsvFile::dump_data ()
Dump the data of the tsvfile.
Remarks:
Used for debugging
Definition at line 3927 of file TsvFile.cpp.
References affx::TSV_OK.
void affx::TsvFile::dump_headers ()
Dump the header values of the tsvfile.
Remarks:
Used for debugging
Definition at line 3883 of file TsvFile.cpp.
References affx::TsvFileHeaderLine::m_key, affx::TsvFileHeaderLine::m_order, and affx::TsvFileHeaderLine::m_value.
void affx::TsvFile::dump_indexes ()
Dump the indexes.
Remarks:
Used for debugging
Definition at line 3951 of file TsvFile.cpp.
References affx::TsvFileIndex::dump().
bool affx::TsvFile::eof ()
Returns the value of m_eof.
Returns:
should be true when at the end of the file.
Definition at line 1386 of file TsvFile.cpp.
Referenced by affx::TsvFileDiff::diffData().
int affx::TsvFile::extractColToVec (const std::string & fileName, const std::string & colName, std::vector< std::string > * vec) [static]
put the column of a file into a vector. the column and file are required to exist or we die.
Definition at line 4801 of file TsvFile.cpp.
Referenced by check_read_colvec_1().
int affx::TsvFile::extractColToVec (const std::string & fileName, const std::string & colName, std::vector< std::string > * vec, int optEscapeOk) [static]
Definition at line 4766 of file TsvFile.cpp.
References clear(), close(), cname2cidx(), get(), m_optEscapeOk, nextLevel(), open(), TSV_ERR_ABORT, and affx::TSV_OK.
int affx::TsvFile::f_advance_eol ()
advance over the end of the line (eol)
Returns:
the number of chars read to get there (not including eol chars)
Remarks:
The eol chars are not included in the count as there could be 1 or 2
Todo:
this is duplicated from getline but we dont want to accum the data so ok?
Definition at line 2866 of file TsvFile.cpp.
References M_GETC, M_PEEK, TSV_CHAR_CR, TSV_CHAR_LF, and affx::TSV_ERR_FILEIO.
int affx::TsvFile::f_advance_tabs ()
Gobble up the tabs without skipping over eol.
Returns:
the number of tabs skipped
Definition at line 2782 of file TsvFile.cpp.
References M_GETC, M_PEEK, M_UNGETC, ToStr(), TSV_CHAR_COMMENT, TSV_CHAR_CR, TSV_CHAR_LF, TSV_CHAR_SPACE, TSV_CHAR_TAB, TSV_ERR_ABORT, affx::TSV_LINE_BLANK, and affx::TSV_LINE_COMMENT.
int affx::TsvFile::f_getline (std::string & line)
Read a line from a TsvFile into a string.
Parameters:
line A buffer to modify
Returns:
tsv_return_t
Remarks:
Lines end with (0x0a "\n") (0x0d "\r") or (0x0d 0x0a "\r\n")
Definition at line 1601 of file TsvFile.cpp.
References M_GETC, M_PEEK, TSV_CHAR_CR, TSV_CHAR_EOF, TSV_CHAR_LF, affx::TSV_ERR_FILEIO, and affx::TSV_OK.
bool affx::TsvFile::f_lookingat_eol ()
Are we looking at the end of a line?
Returns:
true if at end of line.
Definition at line 1577 of file TsvFile.cpp.
References M_PEEK, TSV_CHAR_CR, and TSV_CHAR_LF.
int affx::TsvFile::f_read_column (affx::TsvFileField * col)
Read data into a column from the file.
Parameters:
col column to fill
Returns:
tsv_return_t
Remarks:
Dont read past the end of the line. Only use f_advance_eol to do that.
Definition at line 2920 of file TsvFile.cpp.
References affx::dequote(), affx::TsvFileField::m_buffer, M_GETC, affx::TsvFileField::m_isnull, affx::TsvFileField::m_optAutoDequote, M_UNGETC, affx::TsvFileField::m_value_double_done, affx::TsvFileField::m_value_int_done, affx::TsvFileField::m_value_uint_done, affx::TsvFileField::m_value_ulonglong_done, affx::trim(), TSV_CHAR_CR, TSV_CHAR_LF, affx::TSV_ERR_FILEIO, affx::TSV_OK, and affx::unescapeChar().
int affx::TsvFile::f_read_columns (int line_clvl)
Read the columns of this level.
Parameters:
line_clvl column level at which we are reading
Returns:
tsv_return_t
Definition at line 3012 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::f_read_header_v1 ()
Read a classic "v1" header from the top of a file.
Returns:
tsv_return_t
Remarks:
Attempts to guess if this is a tab or comma seperated file
Definition at line 2252 of file TsvFile.cpp.
References affx::countchars(), affx::dequote(), affx::splitstr(), TSV_CHAR_COMMA, TSV_CHAR_TAB, and affx::TSV_OK.
int affx::TsvFile::f_read_header_v2 ()
Read and parse a v2 header line.
Definition at line 2293 of file TsvFile.cpp.
References affx::ltrim(), affx::rtrim(), affx::trim(), affx::TSV_ERR_FORMAT, affx::TSV_HEADER, affx::TSV_HEADER_LAST, and affx::TSV_OK.
int affx::TsvFile::f_read_headers ()
Read all the headers and set up the file.
Returns:
tsv_return_t
Definition at line 2337 of file TsvFile.cpp.
References affx::TSV_FORMAT_TABLE, affx::TSV_FORMAT_V1, affx::TSV_FORMAT_V2, affx::TSV_HEADER, and affx::TSV_OK.
int affx::TsvFile::findBegin (int clvl, std::string cname, int op, std::string val, int flags = TSV_ORDERBY_LINE)
These are instances of the above template The user will get a better error message
Referenced by check_index_1(), example_index_1(), example_index_2(), dumpPgf::getCoordsByIndex(), tsvJoin::writeMatches(), and dumpPgf::writeMatches().
int affx::TsvFile::findBegin (int clvl, int cidx, int op, std::string val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
int affx::TsvFile::findBegin (int clvl, std::string cname, int op, int val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
int affx::TsvFile::findBegin (int clvl, int cidx, int op, int val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
int affx::TsvFile::findBegin (int clvl, int cidx, int op, double val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
int affx::TsvFile::findBegin (int clvl, std::string cname, int op, unsigned int val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
int affx::TsvFile::findBegin (int clvl, int cidx, int op, unsigned int val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
int affx::TsvFile::findBegin (int clvl, int cidx, int op, uint64_t val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
int affx::TsvFile::findBegin (int clvl, std::string cname, int op, uint64_t val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
int affx::TsvFile::findBegin (int clvl, std::string cname, int op, double val, int flags = TSV_ORDERBY_LINE)
like findBegin with different types
template<typename T1 , typename T2 > int affx::TsvFile::findBegin_tmpl (int clvl, T1 cidx, int op, T2 val, int flags) [private]
Handy template.
The error messages which one sees are nasty when using templates. This is the base template, make it private
Parameters:
clvl column level
cidx column index
op the kind of comparison to do (tsv_op_t)
val value to search for
flags how to order the results (tsv_orderby_t)
Returns:
tsv_error_t
Todo:
if (m_optAutoIndex==true){index_column
Definition at line 4319 of file TsvFile.cpp.
References affx::TsvFileIndex::results_append(), affx::TSV_ERR_NOTFOUND, affx::TSV_OK, and affx::TSV_ORDERBY_LINE.
int affx::TsvFile::findNext ()
Goto the next result.
Returns:
tsv_return_t
Definition at line 4392 of file TsvFile.cpp.
References affx::TSV_FIND_LAST.
Referenced by check_index_1(), example_index_1(), example_index_2(), dumpPgf::getCoordsByIndex(), tsvJoin::writeMatches(), and dumpPgf::writeMatches().
int affx::TsvFile::findResultsClear ()
Clear the results of the last findBegin.
Returns:
tsv_return_t
Definition at line 4303 of file TsvFile.cpp.
References affx::TSV_OK.
unsigned int affx::TsvFile::findResultsCount ()
Return the count of found lines.
Returns:
The number of matching lines to the last findBegin.
Definition at line 4384 of file TsvFile.cpp.
Referenced by example_index_2(), dumpPgf::getCoordsByIndex(), tsvJoin::writeMatches(), and dumpPgf::writeMatches().
void affx::TsvFile::flush ()
Flushs the data to the file. If you are debugging, you might want to explictly flush the output. It is not required. Be warned that this slows down the IO.
Definition at line 2772 of file TsvFile.cpp.
Referenced by check_write_10().
int affx::TsvFile::formatOk ()
Is the format of the file ok.
Returns:
tsv_return_t
Definition at line 3200 of file TsvFile.cpp.
References affx::TSV_ERR_FORMAT, and affx::TSV_OK.
int affx::TsvFile::get (int clvl, int cidx, unsigned int & val)
Get the unsigned integer value of a field.
Parameters:
clvl The column level level of field
cidx The column index (0-based) of the field
val The integer in which to store the value
Returns:
a tsv_return_t code
Definition at line 3618 of file TsvFile.cpp.
References TSV_GET_VALUE_CIDX.
int affx::TsvFile::get (int clvl, int cidx, std::string & val)
Get the string value of a field.
Parameters:
clvl The column level level of field
cidx The column index (0-based) of the field
val The string in which to store the value
Returns:
a tsv_return_t code
Definition at line 3570 of file TsvFile.cpp.
References TSV_GET_VALUE_CIDX.
Referenced by check_csv_1(), check_index_1(), check_read_table_1(), check_read_vec_1(), check_winpath_1(), affx::TsvFileDiff::diffData(), example_index_1(), example_read_table_1(), extractColToVec(), affx::TsvFileDiff::p_diff_1line(), and affx::TsvFileDiff::p_line().
int affx::TsvFile::get (int clvl, int cidx, short & val)
Definition at line 3576 of file TsvFile.cpp.
References TSV_GET_VALUE_CIDX.
int affx::TsvFile::get (int clvl, int cidx, int & val)
Get the integer value of a field.
Parameters:
clvl The column level level of field
cidx The column index (0-based) of the field
val The integer in which to store the value
Returns:
a tsv_return_t code
Definition at line 3587 of file TsvFile.cpp.
References TSV_GET_VALUE_CIDX.
int affx::TsvFile::get (int clvl, int cidx, double & val)
Get the double value of a field.
Parameters:
clvl The column level level of field
cidx The column index (0-based) of the field
val The double in which to store the value
Returns:
a tsv_return_t code
Definition at line 3597 of file TsvFile.cpp.
References TSV_GET_VALUE_CIDX.
int affx::TsvFile::get (int clvl, int cidx, float & val)
Get the float value of a field.
Parameters:
clvl The column level level of field
cidx The column index (0-based) of the field
val The float in which to store the value
Returns:
a tsv_return_t code
Definition at line 3608 of file TsvFile.cpp.
References TSV_GET_VALUE_CIDX.
int affx::TsvFile::get (int clvl, int cidx, uint64_t & val)
Get the unsigned integer value of a field.
Parameters:
clvl The column level level of field
cidx The column index (0-based) of the field
val The integer in which to store the value
Returns:
a tsv_return_t code
Definition at line 3628 of file TsvFile.cpp.
References TSV_GET_VALUE_CIDX.
int affx::TsvFile::get (int clvl, const std::string & cname, std::string & val)
Get the string value of a field.
Parameters:
clvl The column level level of field
cname the column name
val The string in which to store the value
Returns:
a tsv_return_t code
Definition at line 3649 of file TsvFile.cpp.
References TSV_GET_VALUE_CNAME.
int affx::TsvFile::get (int clvl, const std::string & cname, short & val)
Definition at line 3655 of file TsvFile.cpp.
References TSV_GET_VALUE_CNAME.
int affx::TsvFile::get (int clvl, int cidx, std::vector< std::string > * val, char sep = ',')
int affx::TsvFile::get (int clvl, const std::string & cname, double & val)
Get the double value of a field.
Parameters:
clvl The column level level of field
cname the column name
val The double in which to store the value
Returns:
a tsv_return_t code
Definition at line 3676 of file TsvFile.cpp.
References TSV_GET_VALUE_CNAME.
int affx::TsvFile::get (int clvl, const std::string & cname, float & val)
Get the float value of a field.
Parameters:
clvl The column level level of field
cname the column name
val The float in which to store the value
Returns:
a tsv_return_t code
Definition at line 3687 of file TsvFile.cpp.
References TSV_GET_VALUE_CNAME.
int affx::TsvFile::get (int clvl, const std::string & cname, unsigned int & val)
Get the unsigned integer value of a field.
Parameters:
clvl The column level level of field
cname the column name
val The integer in which to store the value
Returns:
a tsv_return_t code
Definition at line 3698 of file TsvFile.cpp.
References TSV_GET_VALUE_CNAME.
int affx::TsvFile::get (int clvl, const std::string & cname, uint64_t & val)
Get the unsigned integer value of a field.
Parameters:
clvl The column level level of field
cname the column name
val The integer in which to store the value
Returns:
a tsv_return_t code
Definition at line 3709 of file TsvFile.cpp.
References TSV_GET_VALUE_CNAME.
int affx::TsvFile::get (int clvl, int cidx, std::vector< int > * val, char sep = ',')
int affx::TsvFile::get (int clvl, int cidx, std::vector< float > * val, char sep = ',')
int affx::TsvFile::get (int clvl, int cidx, std::vector< double > * val, char sep = ',')
int affx::TsvFile::get (int clvl, const std::string & cname, std::vector< int > * val, char sep = ',')
int affx::TsvFile::get (int clvl, const std::string & cname, std::vector< float > * val, char sep = ',')
int affx::TsvFile::get (int clvl, const std::string & cname, std::vector< double > * val, char sep = ',')
int affx::TsvFile::get (int clvl, const std::string & cname, std::vector< std::string > * val, char sep = ',')
int affx::TsvFile::get (int clvl, const std::string & cname, int & val)
Get the integer value of a field.
Parameters:
clvl The column level level of field
cname the column name
val The integer in which to store the value
Returns:
a tsv_return_t code
Definition at line 3666 of file TsvFile.cpp.
References TSV_GET_VALUE_CNAME.
affx::tsv_type_t affx::TsvFile::get_type (int clvl, const std::string & cname)
Return the declared type of this column.
Parameters:
clvl
cname
Returns:
Definition at line 3503 of file TsvFile.cpp.
References affx::TsvFileField::get_type(), and affx::TSV_TYPE_ERR.
affx::tsv_type_t affx::TsvFile::get_type (int clvl, int cidx)
Return the declared type of this column.
Parameters:
clvl
cidx
Returns:
Definition at line 3517 of file TsvFile.cpp.
References affx::TsvFileField::get_type(), and affx::TSV_TYPE_ERR.
int affx::TsvFile::getColumnCount (int clvl)
The number of columns for this level.
Parameters:
clvl the level we are asking about
Returns:
cidx
Definition at line 1566 of file TsvFile.cpp.
Referenced by check_read_table_1(), copyFormat(), copyLevel(), affx::TsvFileDiff::diffData(), example_dump_columns(), example_read_table_1(), example_write_1(), SnpTable::open(), affx::TsvFileDiff::open_residuals(), tsvJoin::openInputFiles(), dumpPgf::openInputFiles(), affx::TsvFileDiff::p_diff_1line(), and affx::TsvFileDiff::p_line().
std::string affx::TsvFile::getColumnName (int clvl, int cidx)
Definition at line 2608 of file TsvFile.cpp.
Referenced by affx::TsvFileDiff::open_residuals().
int affx::TsvFile::getError ()
Return the current error number.
Returns:
Definition at line 1540 of file TsvFile.cpp.
std::string affx::TsvFile::getFileName () [inline]
Get the filename of the TsvFile.
Definition at line 548 of file TsvFile.h.
Referenced by affx::TsvFileDiff::open_residuals().
int affx::TsvFile::getHeader (const std::string & key, std::string & val)
Get the value of a header.
Parameters:
key which header to get
val string to bind the value to
Returns:
tsv_return_t
Definition at line 2001 of file TsvFile.cpp.
References affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
Referenced by addHeadersFrom(), check_headers_1(), check_headers_2(), affx::TsvFileDiff::diffHeaders(), affx::ClfFile::getOrder(), affx::ClfFile::getSequential(), affx::ClfFile::getXMax(), affx::ClfFile::getYMax(), affx::PgfFile::open(), and affx::ClfFile::open().
int affx::TsvFile::getHeader (const std::string & key, int & val)
Get the integer value of a header.
Parameters:
key key to get
val integer value to be modfied.
Returns:
tsv_error_t
Definition at line 2016 of file TsvFile.cpp.
References affx::TSV_ERR_FORMAT, affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
int affx::TsvFile::getHeader (const std::string & key, double & val)
Get the integer value of a header.
Parameters:
key key to get
val integer value to be modfied.
Returns:
tsv_error_t
Definition at line 2039 of file TsvFile.cpp.
References affx::TSV_ERR_FORMAT, affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
int affx::TsvFile::getHeader (const std::string & key, std::vector< std::string > & val)
Get string values of all headers exactly matching a key.
Parameters:
key key to find
val string vector for matching values.
Returns:
tsv_error_t
Definition at line 2062 of file TsvFile.cpp.
int affx::TsvFile::getHeaderAppend (const std::string & key, std::vector< std::string > & val)
Append string values of all headers exactly matching a key.
Parameters:
key key to find
val string vector for appended values.
Returns:
tsv_error_t
Definition at line 2073 of file TsvFile.cpp.
References affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
Referenced by check_headers_1().
int affx::TsvFile::getHeaderMatchingKeySubstr (const std::string & key, std::vector< std::string > & val)
Get string values of all headers containing the substring.
Parameters:
key key substring to find
val string vector for matching values.
Returns:
tsv_error_t
Definition at line 2089 of file TsvFile.cpp.
Referenced by check_headers_1().
int affx::TsvFile::getHeaderMatchingKeySubstrAppend (const std::string & key, std::vector< std::string > & val)
Append string values of all headers containing the substring.
Parameters:
key key substring to find
val string vector for appended values.
Returns:
tsv_error_t
Definition at line 2100 of file TsvFile.cpp.
References affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
Referenced by check_headers_1().
int affx::TsvFile::getLevelCount ()
The number of levels defined.
Returns:
clvl
Definition at line 1558 of file TsvFile.cpp.
Referenced by copyFormat(), copyLevel(), example_dump_columns(), example_write_1(), and affx::TsvFileDiff::open_residuals().
int TsvFile::getLineCountInFile (const std::string & filename, bool abortOnError = false) [static]
Count the number of total lines, assuming a text file.
Parameters:
filename name of file to open
Returns:
Line count. TSV_ERR_FILEIO, TSV_ERR_NOTFOUND on error.
Definition at line 4885 of file TsvFile.cpp.
References Fs::aptOpen(), Fs::fileExists(), TSV_ERR_ABORT, and affx::TSV_ERR_FILEIO.
Referenced by check_line_count(), and check_replace().
bool affx::TsvFile::good () [inline]
Definition at line 582 of file TsvFile.h.
int affx::TsvFile::gotoLine (linenum_t line)
goto a line reading the parent lines and then the line itself
Parameters:
line
Returns:
tsv_return_t
Remarks:
When we goto a line, we need to goto the parents first to set the parent values. This presents a "read consistent" view of the data.
Definition at line 4050 of file TsvFile.cpp.
References ToStr(), TSV_ERR_ABORT, affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
int affx::TsvFile::hasHeaderEqualTo (const std::string & key, const std::string & val)
Does the file have a key==value header which matches.
Parameters:
key key to check
val value to check
Returns:
true if there is a matching key==val header
Remarks:
This is handy to check for matching chip types.
Definition at line 2120 of file TsvFile.cpp.
References affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
Referenced by check_headers_1().
int affx::TsvFile::headerCount ()
Note that the "headerN" lines may not have been generated yet.
Returns:
The number of headers for this file.
Definition at line 1990 of file TsvFile.cpp.
Referenced by check_headers_2().
int affx::TsvFile::headerKeyLegal (const std::string & key)
Is the key a legal key to have in a header?
Parameters:
key the key to check
Returns:
tsv_return_t
Definition at line 1766 of file TsvFile.cpp.
References affx::TSV_ERR_FORMAT, and affx::TSV_OK.
void affx::TsvFile::headers_to_fields_v2 ()
Parse the "headerN" lines.
Todo:
discard the leading spaces and split on whitespace?
Definition at line 2375 of file TsvFile.cpp.
References Verbose::out(), affx::splitstr(), and ToStr().
void affx::TsvFile::headersBegin ()
Start at the beginning of the headers.
Remarks:
This acts as the begin for all the ways of walking the headers.
Definition at line 1677 of file TsvFile.cpp.
Referenced by addHeadersFrom(), check_comment_1(), check_headers_1(), check_headers_3(), affx::TsvFileDiff::diffHeaders(), tsv_util_headers(), tsvJoin::writeHeadersFromFile(), and dumpPgf::writeOutputHeader().
int affx::TsvFile::headersCount ()
How many headers are there?
Returns:
Count of the headers
Definition at line 1753 of file TsvFile.cpp.
Referenced by check_headers_4().
int affx::TsvFile::headersFindNext (const std::string & key, std::string & val)
Advance to the next header matching key.
Parameters:
key key of the header
val value of the header matched
Returns:
Definition at line 1705 of file TsvFile.cpp.
References affx::TSV_HEADER_LAST, and affx::TSV_OK.
Referenced by check_headers_1(), check_headers_3(), and SequentialClfFile::isSequential().
int affx::TsvFile::headersNext (std::string & key, std::string & val)
Advance to the next header of the file and set the values.
Parameters:
key key of the header
val value of the header
Returns:
Definition at line 1731 of file TsvFile.cpp.
References affx::TSV_HEADER_LAST, and affx::TSV_OK.
Referenced by addHeadersFrom(), check_headers_1(), affx::TsvFileDiff::diffHeaders(), tsv_util_headers(), tsvJoin::writeHeadersFromFile(), and dumpPgf::writeOutputHeader().
TsvFileIndex * affx::TsvFile::index_alloc ()
Allocate a TsvFileIndex.
Returns:
pointer to the new index
Definition at line 3967 of file TsvFile.cpp.
TsvFileIndex * affx::TsvFile::index_matching (int clvl, int cidx, int kind)
Find an index which matches what we need.
Parameters:
clvl clvl
cidx cidx
kind What is being matched?
Returns:
NULL if no index found
Definition at line 4233 of file TsvFile.cpp.
References affx::TsvFileIndex::m_bindto_cidx, affx::TsvFileIndex::m_bindto_clvl, and affx::TsvFileIndex::m_kind.
TsvFileIndex * affx::TsvFile::index_matching_1 (int clvl, int cidx, double val)
Do we have a index on this column for doubles?
Parameters:
clvl clvl
cidx cidx
val a dummy value for typedness
Returns:
NULL or a pointer to the index
Definition at line 4275 of file TsvFile.cpp.
References affx::TSV_INDEX_DOUBLE.
TsvFileIndex * affx::TsvFile::index_matching_1 (int clvl, int cidx, unsigned int val)
Do we have a index on this column for unsigned ints?
Parameters:
clvl clvl
cidx cidx
val a dummy value for typedness
Returns:
NULL or a pointer to the index
Definition at line 4285 of file TsvFile.cpp.
References affx::TSV_INDEX_UINT.
TsvFileIndex * affx::TsvFile::index_matching_1 (int clvl, int cidx, std::string & val)
Do we have a index on this column for strings?
Parameters:
clvl clvl
cidx cidx
val a dummy value for typedness
Returns:
NULL or a pointer to the index
Definition at line 4255 of file TsvFile.cpp.
References affx::TSV_INDEX_STRING.
TsvFileIndex * affx::TsvFile::index_matching_1 (int clvl, int cidx, int val)
Do we have a index on this column for ints?
Parameters:
clvl clvl
cidx cidx
val a dummy value for typedness
Returns:
NULL or a pointer to the index
Definition at line 4265 of file TsvFile.cpp.
References affx::TSV_INDEX_INT.
TsvFileIndex * affx::TsvFile::index_matching_1 (int clvl, int cidx, uint64_t val)
Do we have a index on this column for uint64_t?
Parameters:
clvl clvl
cidx cidx
val a dummy value for typedness
Returns:
NULL or a pointer to the index
Definition at line 4295 of file TsvFile.cpp.
References affx::TSV_INDEX_ULONGLONG.
int affx::TsvFile::indexBuild ()
build the indexes for a file
Returns:
tsv_return_t
Definition at line 4129 of file TsvFile.cpp.
References affx::TsvFileIndex::clear(), affx::TsvFileIndex::data_add(), affx::TsvFileIndex::m_bindto_cidx, affx::TsvFileIndex::m_bindto_clvl, affx::TsvFileIndex::m_bindto_cname, affx::TsvFileIndex::m_bindto_type, affx::TsvFileIndex::m_done, affx::TSV_BINDTO_CNAME, and affx::TSV_OK.
int affx::TsvFile::indexBuildMaybe ()
build the indexes if needed
Returns:
tsv_return_t
Definition at line 4219 of file TsvFile.cpp.
References affx::TSV_OK.
void affx::TsvFile::init () [private]
init a new object
init a new TsvFile.
Definition at line 1420 of file TsvFile.cpp.
bool affx::TsvFile::is_open () [inline]
Definition at line 581 of file TsvFile.h.
bool affx::TsvFile::isEmpty (int clvl, const std::string & cname)
Is the field set?
Parameters:
clvl The column level level of field
cname The column index (0-based) of the field
Returns:
false if set, otherwise true
Definition at line 3856 of file TsvFile.cpp.
References affx::TsvFileField::isEmpty().
bool affx::TsvFile::isEmpty (int clvl, int cidx)
Is the field empty (null or no value)?
Parameters:
clvl The column level level of field
cidx The column index (0-based) of the field
Returns:
false if set, otherwise true
Definition at line 3843 of file TsvFile.cpp.
References affx::TsvFileField::isEmpty().
Referenced by check_csv_1().
int affx::TsvFile::isFileOpen () [inline]
Check if file is opened.
Definition at line 579 of file TsvFile.h.
References affx::TSV_ERR_FILEIO, and affx::TSV_OK.
bool affx::TsvFile::isNull (int clvl, int cidx)
Is the field set?
Parameters:
clvl The column level level of field
cidx The column index (0-based) of the field
Returns:
false if set, otherwise true
Definition at line 3816 of file TsvFile.cpp.
References affx::TsvFileField::isNull().
Referenced by check_csv_1().
bool affx::TsvFile::isNull (int clvl, const std::string & cname)
Is the field set?
Parameters:
clvl The column level level of field
cname The column index (0-based) of the field
Returns:
false if set, otherwise true
Definition at line 3829 of file TsvFile.cpp.
References affx::TsvFileField::isNull().
std::fstream::pos_type affx::TsvFile::line_fpos ()
< Where the current line starts
Definition at line 3048 of file TsvFile.cpp.
int affx::TsvFile::lineLevel ()
The indentation level of the line just read.
Returns:
the level
Definition at line 1403 of file TsvFile.cpp.
Referenced by check_csv_1(), check_nextline(), check_read_table_1(), affx::TsvFileDiff::diffData(), example_read_table_1(), affx::TsvFileDiff::p_diff_1line(), affx::TsvFileDiff::p_line(), and tsv_util_copy().
linenum_t affx::TsvFile::lineNum ()
The line number of the current line (internal)
Returns:
number
Definition at line 1550 of file TsvFile.cpp.
linenum_t affx::TsvFile::lineNumber ()
What line did we just read? (external)
Returns:
The line number of the line which was just read.
Definition at line 1394 of file TsvFile.cpp.
Referenced by check_nextline(), example_index_1(), example_index_2(), affx::TsvFileField::linkedvars_assign(), and affx::TsvFileDiff::p_linenums().
TsvFileBinding * affx::TsvFile::linkvar_alloc ()
Allocate a new binding object.
Returns:
pointer to the allocated binding var
Definition at line 3058 of file TsvFile.cpp.
void affx::TsvFile::linkvar_column (int clvl, int cidx, affx::TsvFileBinding * var)
Link a binding to a column.
Parameters:
clvl where to link to
cidx where to link to
var the var to link
Definition at line 3100 of file TsvFile.cpp.
References affx::TsvFileBinding::islinked, and affx::TsvFileField::linkedvar_push().
void affx::TsvFile::linkvar_link (affx::TsvFileBinding * var)
Link a binding var to a column.
Parameters:
var var to link
Definition at line 3118 of file TsvFile.cpp.
References affx::TsvFileBinding::islinked, affx::TsvFileBinding::m_bindto_cidx, affx::TsvFileBinding::m_bindto_clvl, affx::TsvFileBinding::m_bindto_cname, affx::TsvFileBinding::m_bindto_type, affx::TsvFileBinding::m_flags, ToStr(), affx::TSV_BIND_REQUIRED, affx::TSV_BIND_WARNING, affx::TSV_BINDTO_CIDX, affx::TSV_BINDTO_CNAME, affx::TSV_BINDTO_NONE, and TSV_ERR_ABORT.
void affx::TsvFile::linkvars_clear ()
clear all the linkages from columns to vars
Definition at line 3068 of file TsvFile.cpp.
void affx::TsvFile::linkvars_free ()
Definition at line 3085 of file TsvFile.cpp.
int affx::TsvFile::linkvars_makelinks ()
Examine the list of bindings and establish the linkages.
Returns:
number of unlinked bindings
Definition at line 3158 of file TsvFile.cpp.
int affx::TsvFile::linkvars_maybe ()
Dont do anything if the linkages are done, otherwise link.
Returns:
same as linkvars_makelinks
Definition at line 3175 of file TsvFile.cpp.
TsvFileHeaderLine * affx::TsvFile::nextHeaderPtr ()
Return the next non-null header pointer. NULL when at or past the end.
Definition at line 1688 of file TsvFile.cpp.
Referenced by check_comment_1().
int affx::TsvFile::nextLevel (int seek_clvl)
Skip to the next level of data which matches seek_clvl.
Parameters:
seek_clvl the level to skip to
Returns:
tsv_return_t
Remarks:
nextLevel will skip over lines which are more indented than seek_clvl, but will not skip over lines less indented.
Definition at line 3338 of file TsvFile.cpp.
References M_PEEK, TSV_CHAR_COMMENT, TSV_CHAR_TAB, affx::TSV_ERR_EOF, affx::TSV_ERR_FILEIO, affx::TSV_ERR_UNKNOWN, and affx::TSV_LEVEL_LAST.
Referenced by check_csv_1(), check_read_table_1(), check_read_vec_1(), check_winpath_1(), dumpPgf::dumpProbesetData(), example_read_table_1(), extractColToVec(), affx::PgfFile::next_atom(), affx::BgpFile::next_bgprobe(), affx::PgfFile::next_probe(), affx::ClfFile::next_probe(), affx::PgfFile::next_probeset(), SnpTable::open(), dumpPgf::readIdFiles(), tsvJoin::writeMatches(), and dumpPgf::writeMatches().
int affx::TsvFile::nextLine ()
advance to the next line and bind the values
Returns:
tsv_return_t
Definition at line 3305 of file TsvFile.cpp.
References M_PEEK, affx::TSV_ERR_FILEIO, and affx::TSV_OK.
Referenced by check_csv_1(), check_nextline(), affx::TsvFileDiff::diffData(), tsv_util_copy(), and tsv_util_linecount().
int affx::TsvFile::open (const std::string & fname)
Opens a file -- attempts to guess some defaults.
open a TSV file
Parameters:
fname name of file to open
Returns:
TSV_OK or an error
Definition at line 2637 of file TsvFile.cpp.
References Fs::aptOpen(), Fs::isBinaryFile(), Fs::isCalvinFile(), Fs::isHdf5File(), Verbose::out(), ToStr(), TSV_ERR_ABORT, affx::TSV_ERR_BINARY, affx::TSV_ERR_CALVIN, affx::TSV_ERR_FILEIO, affx::TSV_ERR_HDF5, and affx::TSV_OK.
Referenced by check_comment_1(), check_csv_1(), check_index_1(), check_nextline(), check_read_vec_1(), check_winpath_1(), affx::TsvFileDiff::diff(), example_index_1(), extractColToVec(), SnpTable::open(), affx::PgfFile::open(), affx::ClfFile::open(), affx::BgpFile::open(), tsvJoin::openInputFiles(), dumpPgf::openInputFiles(), dumpPgf::readIdFiles(), affx::TsvFileDiff::readOptionsFrom(), tsv_util_copy(), tsv_util_headers(), tsv_util_linecount(), tsv_util_paste_basic(), and tsv_util_print_duplicate_headerkeys().
int affx::TsvFile::openCsv (const std::string & fname)
Open a Csv file.
Parameters:
fname
Returns:
Definition at line 2743 of file TsvFile.cpp.
int affx::TsvFile::openTable (const std::string & fname)
Opens a file as a table.
Open a table file. Tables dont have column headers.
Parameters:
fname
Returns:
Definition at line 2731 of file TsvFile.cpp.
Referenced by check_read_table_1(), example_dump_columns(), and example_read_table_1().
TsvFile& affx::TsvFile::operator= (const TsvFile & that) [inline]
Definition at line 525 of file TsvFile.h.
References Err::errAbort().
void affx::TsvFile::printBindingErrors ()
print messages about unbound variables.
Definition at line 3213 of file TsvFile.cpp.
References Verbose::out(), ToStr(), affx::TSV_BIND_REQUIRED, and affx::TSV_BIND_WARNING.
int affx::TsvFile::printDuplicateHeaders ()
Definition at line 4824 of file TsvFile.cpp.
Referenced by tsv_util_print_duplicate_headerkeys().
void affx::TsvFile::repackHeaders ()
Definition at line 2136 of file TsvFile.cpp.
int TsvFile::replaceCharInFile (const std::string & filename, char a, char b, bool abortOnError = true) [static]
Replace a character in a file with another.
Parameters:
filename name of file for replacement
a source character
b replacement character
Returns:
TSV_OK or (TSV_ERR_FILEIO, TSV_ERR_NOTFOUND) on error.
Definition at line 4940 of file TsvFile.cpp.
References APT_OK, Fs::fileExists(), Fs::fileRename(), Fs::rm(), Fs::touch(), TSV_ERR_ABORT, affx::TSV_ERR_FILEIO, affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
Referenced by check_replace().
void affx::TsvFile::resortHeaders ()
Sort the headers of this TSV file by (order,key,value)
Definition at line 2161 of file TsvFile.cpp.
References affx::header_ptr_less().
Referenced by check_headers_2().
int affx::TsvFile::rewind ()
Rewind back to the start of the data and clear the fields.
Returns:
tsv_return_t
Definition at line 3285 of file TsvFile.cpp.
References affx::TSV_ERR_FILEIO, and affx::TSV_OK.
Referenced by affx::TsvFileDiff::diffData(), affx::PgfFile::rewind(), affx::ClfFile::rewind(), and affx::BgpFile::rewind().
int affx::TsvFile::seekLine (linenum_t line)
Seek to the start of a line but dont read it.
Parameters:
line line to seek to
Returns:
tsv_return_t
Definition at line 4023 of file TsvFile.cpp.
References affx::TSV_ERR_FILEIO, affx::TSV_ERR_NOTFOUND, and affx::TSV_OK.
int affx::TsvFile::set (int clvl, const std::string & cname, uint64_t val)
int affx::TsvFile::set (int clvl, const std::string & cname, const std::vector< float > & val, char sep = ',')
int affx::TsvFile::set (int clvl, int cidx, unsigned int val)
int affx::TsvFile::set (int clvl, const std::string & cname, const std::vector< int > & val, char sep = ',')
int affx::TsvFile::set (int clvl, const std::string & cname, const std::vector< double > & val, char sep = ',')
int affx::TsvFile::set (int clvl, int cidx, const std::vector< int > & val, char sep = ',')
int affx::TsvFile::set (int clvl, const std::string & cname, float val)
int affx::TsvFile::set (int clvl, int cidx, int val)
int affx::TsvFile::set (int clvl, int cidx, const std::string & val)
Referenced by check_write_10(), check_write_vec_1(), example_write_1(), example_write_2(), example_write_3(), example_write_4(), tsv_util_benchmark(), and tsv_util_paste_basic().
int affx::TsvFile::set (int clvl, int cidx, double val)
int affx::TsvFile::set (int clvl, const std::string & cname, const std::vector< std::string > & val, char sep = ',')
int affx::TsvFile::set (int clvl, const std::string & cname, unsigned int val)
int affx::TsvFile::set (int clvl, int cidx, const std::vector< float > & val, char sep = ',')
int affx::TsvFile::set (int clvl, int cidx, const std::vector< double > & val, char sep = ',')
int affx::TsvFile::set (int clvl, int cidx, float val)
int affx::TsvFile::set (int clvl, const std::string & cname, double val)
int affx::TsvFile::set (int clvl, const std::string & cname, int val)
int affx::TsvFile::set (int clvl, int cidx, const std::vector< std::string > & val, char sep = ',')
int affx::TsvFile::set (int clvl, const std::string & cname, const std::string & val)
int affx::TsvFile::set (int clvl, int cidx, uint64_t val)
affx::tsv_type_t affx::TsvFile::set_type (int clvl, const std::string & cname, affx::tsv_type_t type)
Return the declared type of this column.
Parameters:
clvl
cname
Returns:
Definition at line 3531 of file TsvFile.cpp.
References affx::TsvFileField::set_type(), and affx::TSV_TYPE_ERR.
affx::tsv_type_t affx::TsvFile::set_type (int clvl, int cidx, affx::tsv_type_t type)
Return the declared type of this column.
Parameters:
clvl
cidx
Returns:
Definition at line 3545 of file TsvFile.cpp.
References affx::TsvFileField::set_type(), and affx::TSV_TYPE_ERR.
void affx::TsvFile::setAbortOnError (bool value)
Set the option abortonerror.
Parameters:
value the new value.
Definition at line 1378 of file TsvFile.cpp.
int affx::TsvFile::setError (int err)
Set the error value.
Parameters:
err The error to set
Returns:
tsv_error_t
Definition at line 1513 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::setFilename (const std::string & filename)
Set the filename for this Tsv.
Parameters:
filename
Returns:
Definition at line 1412 of file TsvFile.cpp.
References affx::TSV_OK.
int affx::TsvFile::setPrecision (int clvl, const std::string & cname, int places)
Definition at line 2626 of file TsvFile.cpp.
int affx::TsvFile::setPrecision (int clvl, int cidx, int places)
Definition at line 2616 of file TsvFile.cpp.
References affx::TsvFileField::setPrecision(), and affx::TSV_ERR_NOTFOUND.
int affx::TsvFile::setPrecision (int places)
Definition at line 4815 of file TsvFile.cpp.
References affx::TSV_OK.
Referenced by check_write_vec_1(), and example_write_4().
affx::tsv_type_t TsvFile::stringToColType (const std::string & str) [static]
Definition at line 4862 of file TsvFile.cpp.
References affx::TSV_TYPE_DOUBLE, affx::TSV_TYPE_ERR, affx::TSV_TYPE_FLOAT, affx::TSV_TYPE_INT, and affx::TSV_TYPE_STRING.
affx::TsvFile* affx::TsvFile::tsv_ptr () [inline]
Return a pointer to ourself for swig.
Definition at line 928 of file TsvFile.h.
void affx::TsvFile::unbindAll ()
Remove all the bindings.
Definition at line 3229 of file TsvFile.cpp.
Referenced by affx::BgpFile::makeBgpBindings(), affx::ClfFile::makeClfBindings(), and affx::PgfFile::makePgfBindings().
int affx::TsvFile::write_str (const std::string & str)
Write a string to the output stream, quoting if needed.
Parameters:
str
Returns:
tsv_return_t
Definition at line 4459 of file TsvFile.cpp.
References affx::TSV_OK.
void affx::TsvFile::writeColumnHeaders ()
Write the "headerN" lines which define the Columns.
Definition at line 4519 of file TsvFile.cpp.
void affx::TsvFile::writeColumnHeaders_clvl (int clvl)
Write the headers for a given level.
Parameters:
clvl
Definition at line 4502 of file TsvFile.cpp.
tsv_return_t affx::TsvFile::writeCsv (const std::string & filename)
Set the options up for "csv" format and write the CSV header.
Parameters:
filename
Returns:
Definition at line 4636 of file TsvFile.cpp.
References affx::TSV_ERR_FORMAT, and affx::TSV_OK.
Referenced by example_write_3(), and tsv_util_copy().
void affx::TsvFile::writeFieldSep (int cnt)
Write a number of Field seperators to the file.
Parameters:
cnt
Definition at line 4448 of file TsvFile.cpp.
int affx::TsvFile::writeFileComment (const std::string & comment)
Writes a comment directly to the file.
Parameters:
comment
Returns:
tsv_error_t
Definition at line 1906 of file TsvFile.cpp.
References TSV_ERR_ABORT, affx::TSV_OK, and TSV_STRING_COMMENT.
Referenced by check_comment_1().
void affx::TsvFile::writeHeaders ()
Write the file headers.
Definition at line 4530 of file TsvFile.cpp.
void affx::TsvFile::writeKeyValHeaders ()
Write the keyval headers to the file.
Todo:
Maybe output them all anyways?
Definition at line 4471 of file TsvFile.cpp.
References affx::TsvFileHeaderLine::m_key, affx::TsvFileHeaderLine::m_value, affx::TSV_OK, TSV_STRING_COMMENT, and TSV_STRING_META.
int affx::TsvFile::writeLevel (int clvl)
Write a level of data to the file.
Parameters:
clvl The level to write
Returns:
tsv_return_t
Definition at line 4667 of file TsvFile.cpp.
References affx::escapeString(), affx::TsvFileField::m_buffer, affx::TsvFileField::m_precision, affx::TsvFileField::m_val_state, affx::TsvFileField::m_value_double, affx::TsvFileField::m_value_int, ToStr(), TSV_ERR_ABORT, affx::TSV_ERR_FILEIO, affx::TSV_ERR_NOTFOUND, affx::TSV_OK, affx::VALSTATE_DOUBLE, affx::VALSTATE_INT, and affx::VALSTATE_STRING.
Referenced by check_write_10(), check_write_vec_1(), example_write_1(), example_write_2(), example_write_3(), example_write_4(), tsv_util_benchmark(), tsv_util_copy(), and tsv_util_paste_basic().
tsv_return_t affx::TsvFile::writeOpen (const std::string & filename)
open the stream for writing
Parameters:
filename
Returns:
tsv_return_t
Definition at line 4540 of file TsvFile.cpp.
References Fs::aptOpen(), TSV_ERR_ABORT, affx::TSV_ERR_FILEIO, and affx::TSV_OK.
tsv_return_t affx::TsvFile::writeTsv (const std::string & filename)
open the file for writing in "v2" format.
Parameters:
filename
Returns:
tsv_error_t
Definition at line 4620 of file TsvFile.cpp.
Referenced by check_comment_1(), check_headers_2(), example_write_1(), example_write_4(), tsv_util_copy(), affx::PgfFile::write(), affx::ClfFile::write(), and affx::BgpFile::write().
tsv_return_t affx::TsvFile::writeTsv_v1 (const std::string & filename)
Set the options up for "tsv" format and write the tsv-v1 header.
Parameters:
filename
Returns:
Definition at line 4567 of file TsvFile.cpp.
References affx::TSV_ERR_FORMAT, and affx::TSV_OK.
Referenced by check_write_10(), check_write_vec_1(), example_write_3(), tsv_util_benchmark(), and tsv_util_paste_basic().
tsv_return_t affx::TsvFile::writeTsv_v2 (const std::string & filename)
Open the file and write the headers.
Parameters:
filename filename to open
Returns:
tsv_return_t
Remarks:
Once open, set the values with "tsv->set(lvl,col,val)" and write them with "tsv->writeLevel(lvl)". If you want to define your own format, you can cobble it up from: writeOpen, setting the options, and the writeHeaders().
Definition at line 4602 of file TsvFile.cpp.
References affx::TSV_OK.
Member Data Documentation
std::vector<std::map<std::string,int> > affx::TsvFile::m_cnametocidx_map [private]
Map the columns names to column indexes.
Definition at line 493 of file TsvFile.h.
std::vector<std::vector<affx::TsvFileField> > affx::TsvFile::m_column_map [private]
The columns by column level and column index.
Definition at line 491 of file TsvFile.h.
Referenced by copyLevel().
bool affx::TsvFile::m_eof
at eof?
Definition at line 451 of file TsvFile.h.
int affx::TsvFile::m_errno
The error number.
Definition at line 450 of file TsvFile.h.
std::fstream::pos_type affx::TsvFile::m_fileDataPos
Where the data begins (line 0)
Definition at line 458 of file TsvFile.h.
int affx::TsvFile::m_fileFormat
What version of file was read?
Definition at line 452 of file TsvFile.h.
std::string affx::TsvFile::m_fileName
The filename being visited.
Definition at line 455 of file TsvFile.h.
Referenced by affx::TsvFileField::linkedvars_assign().
std::fstream affx::TsvFile::m_fileStream [private]
Definition at line 472 of file TsvFile.h.
std::vector<unsigned int> affx::TsvFile::m_findresults [private]
A vector of lines which match the last "findBegin".
Definition at line 511 of file TsvFile.h.
std::vector<unsigned int>::size_type affx::TsvFile::m_findresults_pos [private]
The postition we are at in the returned results.
Definition at line 513 of file TsvFile.h.
std::multimap<std::string,header_t*> affx::TsvFile::m_headers_bykey [private]
the key=val headers in string form.
Definition at line 485 of file TsvFile.h.
std::string affx::TsvFile::m_headers_curkey_string [private]
Definition at line 488 of file TsvFile.h.
header_t* affx::TsvFile::m_headers_curptr [private]
Definition at line 483 of file TsvFile.h.
int affx::TsvFile::m_headers_idx [private]
Definition at line 482 of file TsvFile.h.
header_iter_t affx::TsvFile::m_headers_iter [private]
used for headersNext
Definition at line 487 of file TsvFile.h.
std::vector<header_t*> affx::TsvFile::m_headers_vec [private]
Definition at line 479 of file TsvFile.h.
bool affx::TsvFile::m_headers_vec_packed [private]
Definition at line 480 of file TsvFile.h.
std::string affx::TsvFile::m_headName
Tag name of column header.
Definition at line 461 of file TsvFile.h.
bool affx::TsvFile::m_index_done [private]
Have the indexing been done?
Definition at line 502 of file TsvFile.h.
std::vector<std::vector<unsigned int> > affx::TsvFile::m_index_lineclvl [private]
A map of line numbers by level so we can find the parent lines.
Definition at line 506 of file TsvFile.h.
std::vector<unsigned int> affx::TsvFile::m_index_linefpos [private]
A map of line numbers to file postions.
Definition at line 504 of file TsvFile.h.
std::vector<TsvFileIndex*> affx::TsvFile::m_index_vec [private]
A vector of indexes which are defined.
Definition at line 509 of file TsvFile.h.
std::fstream::pos_type affx::TsvFile::m_line_fpos [private]
Where the current line starts.
Definition at line 475 of file TsvFile.h.
int affx::TsvFile::m_lineLvl [private]
The level of the current line.
Definition at line 469 of file TsvFile.h.
int affx::TsvFile::m_lineNum [private]
The current line number.
Definition at line 468 of file TsvFile.h.
bool affx::TsvFile::m_linkvars_done [private]
The state of the bound and linked vars...
Are the links up to date
Definition at line 496 of file TsvFile.h.
int affx::TsvFile::m_linkvars_errors [private]
Count of link errors.
Definition at line 497 of file TsvFile.h.
std::vector<TsvFileBinding*> affx::TsvFile::m_linkvars_vec [private]
Vector of bindings linked to us.
Definition at line 499 of file TsvFile.h.
int affx::TsvFile::m_linkvars_warnings [private]
Count of link warnings.
Definition at line 498 of file TsvFile.h.
bool affx::TsvFile::m_optAbortOnError
?
Definition at line 426 of file TsvFile.h.
Referenced by example_walk_clf(), and example_walk_pgf().
bool affx::TsvFile::m_optAllowDataComment
Options which can be set.
allow comments mixed in with data?
Definition at line 425 of file TsvFile.h.
Referenced by tsvJoin::openInputFiles().
bool affx::TsvFile::m_optAutoColumns
add more columns as needed.
Definition at line 427 of file TsvFile.h.
bool affx::TsvFile::m_optAutoDequote
remove quotes when reading?
Definition at line 428 of file TsvFile.h.
bool affx::TsvFile::m_optAutoIndex
?
Definition at line 429 of file TsvFile.h.
bool affx::TsvFile::m_optAutoSenseSep
Autosense between tabs and commas.
Definition at line 430 of file TsvFile.h.
bool affx::TsvFile::m_optAutoTrim
remove whitespace from value?
Definition at line 431 of file TsvFile.h.
bool affx::TsvFile::m_optCheckFormatOnOpen
Automatically check for binary files?
Definition at line 432 of file TsvFile.h.
bool affx::TsvFile::m_optDoQuote
Put quotes on output?
Definition at line 433 of file TsvFile.h.
std::string affx::TsvFile::m_optEndl
End of line sequence to use.
Definition at line 440 of file TsvFile.h.
char affx::TsvFile::m_optEscapeChar
the escape char to use
Definition at line 434 of file TsvFile.h.
bool affx::TsvFile::m_optEscapeOk
Obey the escapechar?
Definition at line 435 of file TsvFile.h.
Referenced by check_winpath_1(), and extractColToVec().
unsigned char affx::TsvFile::m_optFieldSep
Field seperator defaults to TAB.
Definition at line 441 of file TsvFile.h.
bool affx::TsvFile::m_optHasColumnHeader
read the first line as column headers?
Definition at line 436 of file TsvFile.h.
bool affx::TsvFile::m_optHdrDblQuoteComma
Header contains '","'.
Definition at line 442 of file TsvFile.h.
bool affx::TsvFile::m_optLinkVarsOnOpen
Link variables when calling open()
Definition at line 443 of file TsvFile.h.
int affx::TsvFile::m_optPrecision
Default Precision.
Definition at line 448 of file TsvFile.h.
unsigned char affx::TsvFile::m_optQuoteChar
Quote char to use.
Definition at line 439 of file TsvFile.h.
char affx::TsvFile::m_optQuoteChar1
Quoting Character.
Definition at line 445 of file TsvFile.h.
char affx::TsvFile::m_optQuoteChar2
Quoting Character.
Definition at line 446 of file TsvFile.h.
bool affx::TsvFile::m_optThrowOnError
?
Definition at line 437 of file TsvFile.h.
bool affx::TsvFile::m_rawOpen [private]
Definition at line 465 of file TsvFile.h.
std::filebuf* affx::TsvFile::m_rdbuf
Definition at line 913 of file TsvFile.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/TsvFile/TsvFile.h
C:/f112/affy/sdk/file/TsvFile/TsvFile.cpp