Affymetrix Fusion SDK: AffxBinaryFile Class Reference
AffxBinaryFile Class Reference
A class for managing binary files.
#include <AffxBinaryFile.h>
Public Types
enum m_enumOpenOptions { LOAD = 0, SAVE, APPEND }
Public Member Functions
AffxBinaryFile ()
virtual ~AffxBinaryFile ()
bool open (const AffxString &strFileName, m_enumOpenOptions enumOpenOption)
void close ()
bool isLittleEndian ()
unsigned int getOffset ()
void setOffset (unsigned int ui)
void advanceOffset (unsigned int ui)
double readDouble ()
float readFloat ()
int readInt ()
unsigned int readUnsignedInt ()
short readShort ()
unsigned short readUnsignedShort ()
char readChar ()
unsigned char readUnsignedChar ()
AffxString readString ()
AffxString readString (char *pszValue, int iStringLength)
AffxString readString (int iStringLength)
AffxString readWString (wchar_t *pszValue, int iStringLength)
AffxString readBigEndianHalfWString ()
AffxString readHalfWString (int iStringLength)
short readBigEndianShort ()
unsigned short readBigEndianUnsignedShort ()
int readBigEndianInt ()
unsigned int readBigEndianUnsignedInt ()
float readBigEndianFloat ()
AffxString readBigEndianString ()
AffxString readBigEndianString (int iStringLength)
AffxString readBigEndianWString ()
short readLittleEndianShort ()
unsigned short readLittleEndianUnsignedShort ()
int readLittleEndianInt ()
unsigned int readLittleEndianUnsignedInt ()
float readLittleEndianFloat ()
AffxString readLittleEndianString ()
void writeFloat (float f)
void writeInt (int i)
void writeUnsignedInt (unsigned int ui)
void writeShort (short n)
void writeUnsignedShort (unsigned short un)
void writeChar (char c)
void writeUnsignedChar (unsigned char uc)
void writeString (const AffxString &str)
void writeString (const char *pszBuffer, int iStringLength)
void writeBigEndianShort (short i)
void writeBigEndianUnsignedShort (unsigned short ui)
void writeBigEndianInt (int i)
void writeBigEndianUnsignedInt (unsigned int ui)
void writeBigEndianFloat (float f)
void writeBigEndianString (const AffxString &str)
void writeLittleEndianShort (short i)
void writeLittleEndianUnsignedShort (unsigned short ui)
void writeLittleEndianInt (int i)
void writeLittleEndianUnsignedInt (unsigned int ui)
void writeLittleEndianFloat (float f)
void writeLittleEndianString (const AffxString &str)
Private Attributes
std::ifstream * m_pistrm
std::ofstream * m_postrm
Detailed Description
A class for managing binary files.
Definition at line 40 of file AffxBinaryFile.h.
Member Enumeration Documentation
enum AffxBinaryFile::m_enumOpenOptions
Enumerator:
LOAD
SAVE
APPEND
Definition at line 43 of file AffxBinaryFile.h.
Constructor & Destructor Documentation
AffxBinaryFile::AffxBinaryFile ()
Definition at line 28 of file AffxBinaryFile.cpp.
References m_pistrm, and m_postrm.
AffxBinaryFile::~AffxBinaryFile () [virtual]
Definition at line 34 of file AffxBinaryFile.cpp.
References close().
Member Function Documentation
void AffxBinaryFile::advanceOffset (unsigned int ui) [inline]
Definition at line 67 of file AffxBinaryFile.h.
References getOffset(), and setOffset().
void AffxBinaryFile::close ()
Definition at line 64 of file AffxBinaryFile.cpp.
References m_pistrm, and m_postrm.
Referenced by CalvinToText::isCalvinFile(), and ~AffxBinaryFile().
unsigned int AffxBinaryFile::getOffset () [inline]
Definition at line 65 of file AffxBinaryFile.h.
References m_pistrm.
Referenced by advanceOffset().
bool AffxBinaryFile::isLittleEndian () [inline]
Definition at line 56 of file AffxBinaryFile.h.
References LITTLE_ENDIAN.
Referenced by readBigEndianFloat(), readBigEndianInt(), readBigEndianShort(), readBigEndianUnsignedInt(), readBigEndianUnsignedShort(), readLittleEndianFloat(), readLittleEndianInt(), readLittleEndianShort(), readLittleEndianUnsignedInt(), readLittleEndianUnsignedShort(), writeBigEndianFloat(), writeBigEndianInt(), writeBigEndianShort(), writeBigEndianUnsignedInt(), writeBigEndianUnsignedShort(), writeLittleEndianFloat(), writeLittleEndianInt(), writeLittleEndianShort(), writeLittleEndianUnsignedInt(), and writeLittleEndianUnsignedShort().
bool AffxBinaryFile::open (const AffxString & strFileName, m_enumOpenOptions enumOpenOption)
Definition at line 39 of file AffxBinaryFile.cpp.
References APPEND, LOAD, m_pistrm, m_postrm, and SAVE.
Referenced by CalvinToText::isCalvinFile().
float AffxBinaryFile::readBigEndianFloat () [inline]
Definition at line 223 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
AffxString AffxBinaryFile::readBigEndianHalfWString () [inline]
Definition at line 139 of file AffxBinaryFile.h.
References readBigEndianInt(), and readUnsignedShort().
int AffxBinaryFile::readBigEndianInt () [inline]
Definition at line 199 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
Referenced by readBigEndianHalfWString(), readBigEndianString(), and readBigEndianWString().
short AffxBinaryFile::readBigEndianShort () [inline]
Definition at line 179 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
AffxString AffxBinaryFile::readBigEndianString () [inline]
Definition at line 237 of file AffxBinaryFile.h.
References m_pistrm, and readBigEndianInt().
AffxString AffxBinaryFile::readBigEndianString (int iStringLength) [inline]
Definition at line 252 of file AffxBinaryFile.h.
References m_pistrm, and readBigEndianInt().
unsigned int AffxBinaryFile::readBigEndianUnsignedInt () [inline]
Definition at line 211 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
unsigned short AffxBinaryFile::readBigEndianUnsignedShort () [inline]
Definition at line 189 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
AffxString AffxBinaryFile::readBigEndianWString () [inline]
Definition at line 268 of file AffxBinaryFile.h.
References readBigEndianInt(), and readUnsignedShort().
char AffxBinaryFile::readChar () [inline]
Definition at line 78 of file AffxBinaryFile.h.
References m_pistrm.
double AffxBinaryFile::readDouble () [inline]
Definition at line 71 of file AffxBinaryFile.h.
References m_pistrm.
float AffxBinaryFile::readFloat () [inline]
Definition at line 72 of file AffxBinaryFile.h.
References m_pistrm.
AffxString AffxBinaryFile::readHalfWString (int iStringLength) [inline]
Definition at line 160 of file AffxBinaryFile.h.
References readUnsignedShort().
int AffxBinaryFile::readInt () [inline]
Definition at line 73 of file AffxBinaryFile.h.
References m_pistrm.
Referenced by readString().
float AffxBinaryFile::readLittleEndianFloat () [inline]
Definition at line 331 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
int AffxBinaryFile::readLittleEndianInt () [inline]
Definition at line 307 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
Referenced by readLittleEndianString().
short AffxBinaryFile::readLittleEndianShort () [inline]
Definition at line 287 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
AffxString AffxBinaryFile::readLittleEndianString () [inline]
Definition at line 345 of file AffxBinaryFile.h.
References m_pistrm, and readLittleEndianInt().
unsigned int AffxBinaryFile::readLittleEndianUnsignedInt () [inline]
Definition at line 319 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
unsigned short AffxBinaryFile::readLittleEndianUnsignedShort () [inline]
Definition at line 297 of file AffxBinaryFile.h.
References isLittleEndian(), and readUnsignedChar().
short AffxBinaryFile::readShort () [inline]
Definition at line 76 of file AffxBinaryFile.h.
References m_pistrm.
AffxString AffxBinaryFile::readString (char * pszValue, int iStringLength) [inline]
Definition at line 96 of file AffxBinaryFile.h.
References m_pistrm.
AffxString AffxBinaryFile::readString (int iStringLength) [inline]
Definition at line 108 of file AffxBinaryFile.h.
References m_pistrm.
AffxString AffxBinaryFile::readString () [inline]
Definition at line 81 of file AffxBinaryFile.h.
References m_pistrm, and readInt().
unsigned char AffxBinaryFile::readUnsignedChar () [inline]
Definition at line 79 of file AffxBinaryFile.h.
References m_pistrm.
Referenced by CalvinToText::isCalvinFile(), readBigEndianFloat(), readBigEndianInt(), readBigEndianShort(), readBigEndianUnsignedInt(), readBigEndianUnsignedShort(), readLittleEndianFloat(), readLittleEndianInt(), readLittleEndianShort(), readLittleEndianUnsignedInt(), and readLittleEndianUnsignedShort().
unsigned int AffxBinaryFile::readUnsignedInt () [inline]
Definition at line 74 of file AffxBinaryFile.h.
References m_pistrm.
unsigned short AffxBinaryFile::readUnsignedShort () [inline]
Definition at line 77 of file AffxBinaryFile.h.
References m_pistrm.
Referenced by readBigEndianHalfWString(), readBigEndianWString(), readHalfWString(), and readWString().
AffxString AffxBinaryFile::readWString (wchar_t * pszValue, int iStringLength) [inline]
Definition at line 122 of file AffxBinaryFile.h.
References readUnsignedShort().
void AffxBinaryFile::setOffset (unsigned int ui) [inline]
Definition at line 66 of file AffxBinaryFile.h.
References m_pistrm.
Referenced by advanceOffset().
void AffxBinaryFile::writeBigEndianFloat (float f) [inline]
Definition at line 447 of file AffxBinaryFile.h.
References isLittleEndian(), and writeChar().
void AffxBinaryFile::writeBigEndianInt (int i) [inline]
Definition at line 411 of file AffxBinaryFile.h.
References isLittleEndian(), and writeChar().
Referenced by writeBigEndianString().
void AffxBinaryFile::writeBigEndianShort (short i) [inline]
Definition at line 383 of file AffxBinaryFile.h.
References isLittleEndian(), and writeChar().
void AffxBinaryFile::writeBigEndianString (const AffxString & str) [inline]
Definition at line 465 of file AffxBinaryFile.h.
References m_postrm, and writeBigEndianInt().
void AffxBinaryFile::writeBigEndianUnsignedInt (unsigned int ui) [inline]
Definition at line 429 of file AffxBinaryFile.h.
References isLittleEndian(), and writeUnsignedChar().
void AffxBinaryFile::writeBigEndianUnsignedShort (unsigned short ui) [inline]
Definition at line 397 of file AffxBinaryFile.h.
References isLittleEndian(), and writeUnsignedChar().
void AffxBinaryFile::writeChar (char c) [inline]
Definition at line 365 of file AffxBinaryFile.h.
References m_postrm.
Referenced by writeBigEndianFloat(), writeBigEndianInt(), writeBigEndianShort(), writeLittleEndianFloat(), writeLittleEndianInt(), and writeLittleEndianShort().
void AffxBinaryFile::writeFloat (float f) [inline]
Definition at line 360 of file AffxBinaryFile.h.
References m_postrm.
void AffxBinaryFile::writeInt (int i) [inline]
Definition at line 361 of file AffxBinaryFile.h.
References m_postrm.
Referenced by writeString().
void AffxBinaryFile::writeLittleEndianFloat (float f) [inline]
Definition at line 539 of file AffxBinaryFile.h.
References isLittleEndian(), and writeChar().
void AffxBinaryFile::writeLittleEndianInt (int i) [inline]
Definition at line 503 of file AffxBinaryFile.h.
References isLittleEndian(), and writeChar().
Referenced by writeLittleEndianString().
void AffxBinaryFile::writeLittleEndianShort (short i) [inline]
Definition at line 475 of file AffxBinaryFile.h.
References isLittleEndian(), and writeChar().
void AffxBinaryFile::writeLittleEndianString (const AffxString & str) [inline]
Definition at line 557 of file AffxBinaryFile.h.
References m_postrm, and writeLittleEndianInt().
void AffxBinaryFile::writeLittleEndianUnsignedInt (unsigned int ui) [inline]
Definition at line 521 of file AffxBinaryFile.h.
References isLittleEndian(), and writeUnsignedChar().
void AffxBinaryFile::writeLittleEndianUnsignedShort (unsigned short ui) [inline]
Definition at line 489 of file AffxBinaryFile.h.
References isLittleEndian(), and writeUnsignedChar().
void AffxBinaryFile::writeShort (short n) [inline]
Definition at line 363 of file AffxBinaryFile.h.
References m_postrm.
void AffxBinaryFile::writeString (const AffxString & str) [inline]
Definition at line 368 of file AffxBinaryFile.h.
References m_postrm, and writeInt().
void AffxBinaryFile::writeString (const char * pszBuffer, int iStringLength) [inline]
Definition at line 378 of file AffxBinaryFile.h.
References m_postrm.
void AffxBinaryFile::writeUnsignedChar (unsigned char uc) [inline]
Definition at line 366 of file AffxBinaryFile.h.
References m_postrm.
Referenced by writeBigEndianUnsignedInt(), writeBigEndianUnsignedShort(), writeLittleEndianUnsignedInt(), and writeLittleEndianUnsignedShort().
void AffxBinaryFile::writeUnsignedInt (unsigned int ui) [inline]
Definition at line 362 of file AffxBinaryFile.h.
References m_postrm.
void AffxBinaryFile::writeUnsignedShort (unsigned short un) [inline]
Definition at line 364 of file AffxBinaryFile.h.
References m_postrm.
Member Data Documentation
std::ifstream* AffxBinaryFile::m_pistrm [private]
Definition at line 46 of file AffxBinaryFile.h.
Referenced by AffxBinaryFile(), close(), getOffset(), open(), readBigEndianString(), readChar(), readDouble(), readFloat(), readInt(), readLittleEndianString(), readShort(), readString(), readUnsignedChar(), readUnsignedInt(), readUnsignedShort(), and setOffset().
std::ofstream* AffxBinaryFile::m_postrm [private]
Definition at line 47 of file AffxBinaryFile.h.
Referenced by AffxBinaryFile(), close(), open(), writeBigEndianString(), writeChar(), writeFloat(), writeInt(), writeLittleEndianString(), writeShort(), writeString(), writeUnsignedChar(), writeUnsignedInt(), and writeUnsignedShort().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/AffxBinaryFile.h
C:/f112/affy/sdk/util/AffxBinaryFile.cpp