Affymetrix Fusion SDK: affymetrix_calvin_io::CHPFileWriter Class Reference
affymetrix_calvin_io::CHPFileWriter Class Reference
#include <CalvinCHPFileWriter.h>
Public Member Functions
CHPFileWriter (CHPData &p)
~CHPFileWriter ()
void SeekToDataSet ()
void WriteExpressionEntry (const CHPExpressionEntry &p)
void WriteGenotypeEntry (const CHPGenotypeEntry &p)
void WriteUniversalEntry (const CHPUniversalEntry &p)
void WriteReseqEntry (const CHPReseqEntry &p)
void SeekToBgSet ()
void WriteBackgroundZone (const CHPBackgroundZone &zone)
void SeekToForceSet ()
void WriteForceCall (const CHPReseqForceCall &force)
void SeekToOrigCallSet ()
void WriteOrigCall (const CHPReseqOrigCall &orig)
Private Member Functions
void WriteHeaders ()
void SetFilePositions ()
Private Attributes
int maxProbeSetName
GenericFileWriter * writer
DataSetWriter * dataSetWriter
int32_t entryPos
int32_t bgZonePos
int32_t forcePos
int32_t origPos
Detailed Description
Provides write capabilities for expression, genotyping, resequencing and tag arrays.
Definition at line 40 of file CalvinCHPFileWriter.h.
Constructor & Destructor Documentation
CHPFileWriter::CHPFileWriter (CHPData & p)
Constructor.
Parameters:
p The CHP file object.
Definition at line 26 of file CalvinCHPFileWriter.cpp.
References bgZonePos, entryPos, forcePos, affymetrix_calvin_io::CHPData::GetFileHeader(), affymetrix_calvin_io::CHPData::GetMaxProbeSetName(), maxProbeSetName, origPos, WriteHeaders(), and writer.
CHPFileWriter::~CHPFileWriter ()
Destructor
Definition at line 37 of file CalvinCHPFileWriter.cpp.
References writer.
Member Function Documentation
void CHPFileWriter::SeekToBgSet ()
Seeks to the data set.
Definition at line 116 of file CalvinCHPFileWriter.cpp.
References bgZonePos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), and writer.
void CHPFileWriter::SeekToDataSet ()
Seeks to the data set.
Definition at line 68 of file CalvinCHPFileWriter.cpp.
References entryPos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), and writer.
void CHPFileWriter::SeekToForceSet ()
Seeks to the data set.
Definition at line 129 of file CalvinCHPFileWriter.cpp.
References forcePos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), and writer.
void CHPFileWriter::SeekToOrigCallSet ()
Seeks to the data set.
Definition at line 141 of file CalvinCHPFileWriter.cpp.
References origPos, affymetrix_calvin_io::GenericFileWriter::SeekFromBeginPos(), and writer.
void CHPFileWriter::SetFilePositions () [private]
Updates the file positions after a data set is added to the file.
Definition at line 152 of file CalvinCHPFileWriter.cpp.
References bgZonePos, CHP_BG_ZONE_GROUP, CHP_RESEQ_FORCE_CALL_GROUP, CHP_RESEQ_ORIG_CALL_GROUP, dataSetWriter, entryPos, forcePos, affymetrix_calvin_io::DataSetWriter::GetDataSetName(), affymetrix_calvin_io::DataSetWriter::GetDataSetSize(), affymetrix_calvin_io::GenericFileWriter::GetFilePos(), origPos, affymetrix_calvin_io::GenericFileWriter::SeekFromCurrentPos(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), and writer.
Referenced by WriteHeaders().
void CHPFileWriter::WriteBackgroundZone (const CHPBackgroundZone & zone)
Writes a background zone to the file.
Parameters:
zone The result to write.
Definition at line 121 of file CalvinCHPFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::CHPBackgroundZone::GetBackground(), affymetrix_calvin_io::CHPBackgroundZone::GetCenterX(), affymetrix_calvin_io::CHPBackgroundZone::GetCenterY(), affymetrix_calvin_io::CHPBackgroundZone::GetSmoothFactor(), and affymetrix_calvin_io::DataSetWriter::Write().
void CHPFileWriter::WriteExpressionEntry (const CHPExpressionEntry & p)
Writes an expression result to the file.
Parameters:
p The result to write.
Definition at line 73 of file CalvinCHPFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::CHPExpressionEntry::GetChange(), affymetrix_calvin_io::CHPExpressionEntry::GetChangePValue(), affymetrix_calvin_io::CHPExpressionEntry::GetCommonPairs(), affymetrix_calvin_io::CHPExpressionEntry::GetDetection(), affymetrix_calvin_io::CHPExpressionEntry::GetDetectionPValue(), affymetrix_calvin_io::CHPExpressionEntry::GetHasComparisonData(), affymetrix_calvin_io::CHPExpressionEntry::GetNumPairs(), affymetrix_calvin_io::CHPExpressionEntry::GetNumPairsUsed(), affymetrix_calvin_io::CHPExpressionEntry::GetProbeSetName(), affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatio(), affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatioHi(), affymetrix_calvin_io::CHPExpressionEntry::GetSigLogRatioLo(), affymetrix_calvin_io::CHPExpressionEntry::GetSignal(), maxProbeSetName, and affymetrix_calvin_io::DataSetWriter::Write().
void CHPFileWriter::WriteForceCall (const CHPReseqForceCall & force)
Writes a force call to the file.
Parameters:
force The result to write.
Definition at line 134 of file CalvinCHPFileWriter.cpp.
References affymetrix_calvin_io::_CHPReseqForceCall::call, dataSetWriter, affymetrix_calvin_io::_CHPReseqForceCall::position, affymetrix_calvin_io::_CHPReseqForceCall::reason, and affymetrix_calvin_io::DataSetWriter::Write().
void CHPFileWriter::WriteGenotypeEntry (const CHPGenotypeEntry & p)
Writes a genotype result to the file.
Parameters:
p The result to write.
Definition at line 92 of file CalvinCHPFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::CHPGenotypeEntry::GetAACall(), affymetrix_calvin_io::CHPGenotypeEntry::GetABCall(), affymetrix_calvin_io::CHPGenotypeEntry::GetBBCall(), affymetrix_calvin_io::CHPGenotypeEntry::GetCall(), affymetrix_calvin_io::CHPGenotypeEntry::GetConfidence(), affymetrix_calvin_io::CHPGenotypeEntry::GetNoCall(), affymetrix_calvin_io::CHPGenotypeEntry::GetProbeSetName(), affymetrix_calvin_io::CHPGenotypeEntry::GetRAS1(), affymetrix_calvin_io::CHPGenotypeEntry::GetRAS2(), maxProbeSetName, and affymetrix_calvin_io::DataSetWriter::Write().
void CHPFileWriter::WriteHeaders () [private]
Writes the header to the file.
Definition at line 42 of file CalvinCHPFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriters(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriters(), SetFilePositions(), affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos(), affymetrix_calvin_io::DataSetWriter::WriteHeader(), affymetrix_calvin_io::DataGroupWriter::WriteHeader(), affymetrix_calvin_io::GenericFileWriter::WriteHeader(), and writer.
Referenced by CHPFileWriter().
void CHPFileWriter::WriteOrigCall (const CHPReseqOrigCall & orig)
Writes original call to the file.
Parameters:
orig The result to write.
Definition at line 146 of file CalvinCHPFileWriter.cpp.
References affymetrix_calvin_io::_CHPReseqOrigCall::call, dataSetWriter, affymetrix_calvin_io::_CHPReseqOrigCall::position, and affymetrix_calvin_io::DataSetWriter::Write().
void CHPFileWriter::WriteReseqEntry (const CHPReseqEntry & p)
Writes a resequencing result to the file.
Parameters:
p The result to write.
Definition at line 110 of file CalvinCHPFileWriter.cpp.
References affymetrix_calvin_io::_CHPReseqEntry::call, dataSetWriter, affymetrix_calvin_io::_CHPReseqEntry::score, and affymetrix_calvin_io::DataSetWriter::Write().
void CHPFileWriter::WriteUniversalEntry (const CHPUniversalEntry & p)
Writes a universal (tag) result to the file.
Parameters:
p The result to write.
Definition at line 105 of file CalvinCHPFileWriter.cpp.
References dataSetWriter, affymetrix_calvin_io::CHPUniversalEntry::GetBackground(), and affymetrix_calvin_io::DataSetWriter::Write().
Member Data Documentation
int32_t affymetrix_calvin_io::CHPFileWriter::bgZonePos [private]
The position of the bg zone entry.
Definition at line 58 of file CalvinCHPFileWriter.h.
Referenced by CHPFileWriter(), SeekToBgSet(), and SetFilePositions().
DataSetWriter* affymetrix_calvin_io::CHPFileWriter::dataSetWriter [private]
The data set writer.
Definition at line 52 of file CalvinCHPFileWriter.h.
Referenced by SetFilePositions(), WriteBackgroundZone(), WriteExpressionEntry(), WriteForceCall(), WriteGenotypeEntry(), WriteHeaders(), WriteOrigCall(), WriteReseqEntry(), and WriteUniversalEntry().
int32_t affymetrix_calvin_io::CHPFileWriter::entryPos [private]
The position of the data entry.
Definition at line 55 of file CalvinCHPFileWriter.h.
Referenced by CHPFileWriter(), SeekToDataSet(), and SetFilePositions().
int32_t affymetrix_calvin_io::CHPFileWriter::forcePos [private]
The position of the force entry.
Definition at line 61 of file CalvinCHPFileWriter.h.
Referenced by CHPFileWriter(), SeekToForceSet(), and SetFilePositions().
int affymetrix_calvin_io::CHPFileWriter::maxProbeSetName [private]
The maximum length of a probe set name.
Definition at line 46 of file CalvinCHPFileWriter.h.
Referenced by CHPFileWriter(), WriteExpressionEntry(), and WriteGenotypeEntry().
int32_t affymetrix_calvin_io::CHPFileWriter::origPos [private]
The position of the orig entry.
Definition at line 64 of file CalvinCHPFileWriter.h.
Referenced by CHPFileWriter(), SeekToOrigCallSet(), and SetFilePositions().
GenericFileWriter* affymetrix_calvin_io::CHPFileWriter::writer [private]
The file writer.
Definition at line 49 of file CalvinCHPFileWriter.h.
Referenced by CHPFileWriter(), SeekToBgSet(), SeekToDataSet(), SeekToForceSet(), SeekToOrigCallSet(), SetFilePositions(), WriteHeaders(), and ~CHPFileWriter().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPFileWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPFileWriter.cpp