Affymetrix Fusion SDK: CFusionCHPDataCOM Class Reference
CFusionCHPDataCOM Class Reference
#include <FusionCHPDataCOM.h>
Public Member Functions
CFusionCHPDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
void SetChip (affymetrix_fusion_io::FusionCHPData *c)
affymetrix_fusion_io::FusionCHPData * GetChip ()
STDMETHOD() get_FileTypeIdentifier (BSTR *pVal)
STDMETHOD() get_FileTypeIdentifiers (VARIANT *pVal)
STDMETHOD() get_FileId (BSTR *pVal)
Private Attributes
affymetrix_fusion_io::FusionCHPData * chp
Detailed Description
Definition at line 29 of file FusionCHPDataCOM.h.
Constructor & Destructor Documentation
CFusionCHPDataCOM::CFusionCHPDataCOM () [inline]
Definition at line 36 of file FusionCHPDataCOM.h.
Member Function Documentation
HRESULT CFusionCHPDataCOM::FinalConstruct () [inline]
Definition at line 56 of file FusionCHPDataCOM.h.
void CFusionCHPDataCOM::FinalRelease () [inline]
Definition at line 61 of file FusionCHPDataCOM.h.
STDMETHODIMP CFusionCHPDataCOM::get_FileId (BSTR * pVal)
Definition at line 51 of file FusionCHPDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPData::FileId().
STDMETHODIMP CFusionCHPDataCOM::get_FileTypeIdentifier (BSTR * pVal)
Definition at line 43 of file FusionCHPDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPData::FileTypeIdentifier().
STDMETHODIMP CFusionCHPDataCOM::get_FileTypeIdentifiers (VARIANT * pVal)
Definition at line 57 of file FusionCHPDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPData::FileTypeIdentifiers().
affymetrix_fusion_io::FusionCHPData* CFusionCHPDataCOM::GetChip () [inline]
Definition at line 72 of file FusionCHPDataCOM.h.
Referenced by CFusionCHPQuantificationDetectionDataCOM::FromBase(), CFusionCHPQuantificationDataCOM::FromBase(), CFusionCHPMultiDataDataCOM::FromBase(), and CFusionCHPLegacyDataCOM::FromBase().
STDMETHODIMP CFusionCHPDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 28 of file FusionCHPDataCOM.cpp.
void CFusionCHPDataCOM::SetChip (affymetrix_fusion_io::FusionCHPData * c) [inline]
Definition at line 69 of file FusionCHPDataCOM.h.
Referenced by CFusionCHPDataRegCOM::Read(), and CFusionCHPDataRegCOM::ReadHeader().
Member Data Documentation
affymetrix_fusion_io::FusionCHPData* CFusionCHPDataCOM::chp [private]
Definition at line 66 of file FusionCHPDataCOM.h.
Referenced by get_FileId(), get_FileTypeIdentifier(), and get_FileTypeIdentifiers().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPDataCOM.cpp