Affymetrix Fusion SDK: affymetrix_calvin_io::CHPBackgroundZone Class Reference
affymetrix_calvin_io::CHPBackgroundZone Class Reference
#include <CHPBackgroundZone.h>
Public Member Functions
CHPBackgroundZone ()
CHPBackgroundZone (float x, float y, float bg, float smooth)
~CHPBackgroundZone ()
void Clear ()
CHPBackgroundZone operator= (CHPBackgroundZone zn)
float GetCenterX () const
float GetCenterY () const
float GetBackground () const
float GetSmoothFactor () const
void SetCenterX (float p)
void SetCenterY (float p)
void SetBackground (float p)
void SetSmoothFactor (float p)
Private Attributes
float centerX
float centerY
float background
float smoothFactor
Detailed Description
This class stores a zone's background value
Definition at line 39 of file CHPBackgroundZone.h.
Constructor & Destructor Documentation
CHPBackgroundZone::CHPBackgroundZone ()
Definition at line 26 of file CHPBackgroundZone.cpp.
References Clear().
CHPBackgroundZone::CHPBackgroundZone (float x, float y, float bg, float smooth)
Definition at line 31 of file CHPBackgroundZone.cpp.
References background, centerX, centerY, and smoothFactor.
CHPBackgroundZone::~CHPBackgroundZone ()
Definition at line 39 of file CHPBackgroundZone.cpp.
Member Function Documentation
void CHPBackgroundZone::Clear ()
Definition at line 41 of file CHPBackgroundZone.cpp.
References background, centerX, centerY, and smoothFactor.
Referenced by CHPBackgroundZone(), and affymetrix_calvin_io::CHPData::GetBackgroundZones().
float CHPBackgroundZone::GetBackground () const
Definition at line 68 of file CHPBackgroundZone.cpp.
References background.
Referenced by affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetBackgroundZone(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteBackgroundZone().
float CHPBackgroundZone::GetCenterX () const
Definition at line 58 of file CHPBackgroundZone.cpp.
References centerX.
Referenced by affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetBackgroundZone(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteBackgroundZone().
float CHPBackgroundZone::GetCenterY () const
Definition at line 63 of file CHPBackgroundZone.cpp.
References centerY.
Referenced by affymetrix_fusion_io::CalvinCHPHeaderAdapter::GetBackgroundZone(), operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteBackgroundZone().
float CHPBackgroundZone::GetSmoothFactor () const
Definition at line 73 of file CHPBackgroundZone.cpp.
References smoothFactor.
Referenced by operator=(), and affymetrix_calvin_io::CHPFileWriter::WriteBackgroundZone().
CHPBackgroundZone CHPBackgroundZone::operator= (CHPBackgroundZone zn)
Assignment operator
Parameters:
zn The zone to copy
Returns:
The new zone object
Definition at line 49 of file CHPBackgroundZone.cpp.
References background, centerX, centerY, GetBackground(), GetCenterX(), GetCenterY(), GetSmoothFactor(), and smoothFactor.
void CHPBackgroundZone::SetBackground (float p)
Definition at line 88 of file CHPBackgroundZone.cpp.
References background.
Referenced by affymetrix_calvin_io::CHPData::GetBackgroundZone().
void CHPBackgroundZone::SetCenterX (float p)
Definition at line 78 of file CHPBackgroundZone.cpp.
References centerX.
Referenced by affymetrix_calvin_io::CHPData::GetBackgroundZone().
void CHPBackgroundZone::SetCenterY (float p)
Definition at line 83 of file CHPBackgroundZone.cpp.
References centerY.
Referenced by affymetrix_calvin_io::CHPData::GetBackgroundZone().
void CHPBackgroundZone::SetSmoothFactor (float p)
Definition at line 93 of file CHPBackgroundZone.cpp.
References smoothFactor.
Referenced by affymetrix_calvin_io::CHPData::GetBackgroundZone().
Member Data Documentation
float affymetrix_calvin_io::CHPBackgroundZone::background [private]
The zone's background value
Definition at line 50 of file CHPBackgroundZone.h.
Referenced by CHPBackgroundZone(), Clear(), GetBackground(), operator=(), and SetBackground().
float affymetrix_calvin_io::CHPBackgroundZone::centerX [private]
The X coordinate of the center of the zone.
Definition at line 44 of file CHPBackgroundZone.h.
Referenced by CHPBackgroundZone(), Clear(), GetCenterX(), operator=(), and SetCenterX().
float affymetrix_calvin_io::CHPBackgroundZone::centerY [private]
The Y coordinate of the center of the zone.
Definition at line 47 of file CHPBackgroundZone.h.
Referenced by CHPBackgroundZone(), Clear(), GetCenterY(), operator=(), and SetCenterY().
float affymetrix_calvin_io::CHPBackgroundZone::smoothFactor [private]
The smoothing factor used to calculate the zone backgrounds
Definition at line 53 of file CHPBackgroundZone.h.
Referenced by CHPBackgroundZone(), Clear(), GetSmoothFactor(), operator=(), and SetSmoothFactor().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CHPBackgroundZone.h
C:/f112/affy/sdk/calvin_files/data/src/CHPBackgroundZone.cpp