Affymetrix Fusion SDK: affymetrix_calvin_io::GridControlFileReader Class Reference
affymetrix_calvin_io::GridControlFileReader Class Reference
#include <GridControlFileReader.h>
Public Member Functions
GridControlFileReader ()
~GridControlFileReader ()
void Read (const std::string &fileName, affymetrix_grid_control::GridControlData &data)
Detailed Description
This class reads a GRC data file. It is an interpreter class.
Definition at line 68 of file GridControlFileReader.h.
Constructor & Destructor Documentation
GridControlFileReader::GridControlFileReader ()
Constructor
Definition at line 36 of file GridControlFileReader.cpp.
GridControlFileReader::~GridControlFileReader ()
Destructor
Definition at line 43 of file GridControlFileReader.cpp.
Member Function Documentation
void GridControlFileReader::Read (const std::string & fileName, affymetrix_grid_control::GridControlData & data)
Reads the contents of a GRC file.
Parameters:
fileName The name of the file to read.
data A reference to an object that will receive information from the file.
Returns:
True if successfully read.
Definition at line 50 of file GridControlFileReader.cpp.
References affymetrix_grid_control::GridControlData::Clear(), affymetrix_calvin_io::DataSet::Close(), affymetrix_calvin_io::GenericData::DataSet(), affymetrix_calvin_io::DataSet::Delete(), affymetrix_calvin_io::GenericData::FileIdentifier(), affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_utilities::DateTime::GetCurrentDateTime(), affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32(), GRD_COLUMNS_PARAMETER_NAME, GRD_FILE_B1_SET_NAME, GRD_FILE_B2_SET_NAME, GRD_FILE_COORDINATE_GROUP_NAME, GRD_FILE_NS_SET_NAME, GRD_FILE_TYPE_IDENTIFIER, GRD_ROWS_PARAMETER_NAME, affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::DataSet::Open(), affymetrix_calvin_io::GenericFileReader::ReadHeader(), affymetrix_grid_control::GridControlData::ResizeB1(), affymetrix_grid_control::GridControlData::ResizeB2(), affymetrix_grid_control::GridControlData::ResizeNS(), affymetrix_calvin_io::DataSet::Rows(), affymetrix_grid_control::GridControlData::SetB1(), affymetrix_grid_control::GridControlData::SetB2(), affymetrix_grid_control::GridControlData::SetColumns(), affymetrix_calvin_io::GenericFileReader::SetFilename(), affymetrix_grid_control::GridControlData::SetNS(), affymetrix_grid_control::GridControlData::SetRows(), affymetrix_grid_control::_FeatureCoordinate::x, and affymetrix_grid_control::_FeatureCoordinate::y.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/parsers/src/GridControlFileReader.h
C:/f112/affy/sdk/calvin_files/parsers/src/GridControlFileReader.cpp