Affymetrix Fusion SDK: CFusionResequencingResultsCOM Class Reference
CFusionResequencingResultsCOM Class Reference
#include <FusionResequencingResultsCOM.h>
Public Member Functions
CFusionResequencingResultsCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
affymetrix_fusion_io::FusionResequencingResults & Results ()
STDMETHOD() Clear (void)
STDMETHOD() GetCalledBase (int index, CHAR *pVal)
STDMETHOD() get_CalledBasesSize (int *pVal)
STDMETHOD() GetScore (int index, float *pVal)
STDMETHOD() get_ScoresSize (int *pVal)
STDMETHOD() GetForceCall (int index, IFusionForceCallType **pVal)
STDMETHOD() get_ForceCallsSize (int *pVal)
STDMETHOD() GetOrigCall (int index, IFusionBaseCallType **pVal)
STDMETHOD() get_OrigCallsSize (int *pVal)
Private Attributes
affymetrix_fusion_io::FusionResequencingResults results
Detailed Description
Definition at line 29 of file FusionResequencingResultsCOM.h.
Constructor & Destructor Documentation
CFusionResequencingResultsCOM::CFusionResequencingResultsCOM () [inline]
Definition at line 36 of file FusionResequencingResultsCOM.h.
Member Function Documentation
STDMETHODIMP CFusionResequencingResultsCOM::Clear (void)
Definition at line 43 of file FusionResequencingResultsCOM.cpp.
References affymetrix_fusion_io::FusionResequencingResults::Clear(), and results.
HRESULT CFusionResequencingResultsCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionResequencingResultsCOM.h.
void CFusionResequencingResultsCOM::FinalRelease () [inline]
Definition at line 60 of file FusionResequencingResultsCOM.h.
STDMETHODIMP CFusionResequencingResultsCOM::get_CalledBasesSize (int * pVal)
Definition at line 55 of file FusionResequencingResultsCOM.cpp.
References affymetrix_fusion_io::FusionResequencingResults::GetCalledBasesSize(), and results.
STDMETHODIMP CFusionResequencingResultsCOM::get_ForceCallsSize (int * pVal)
Definition at line 83 of file FusionResequencingResultsCOM.cpp.
References affymetrix_fusion_io::FusionResequencingResults::GetForceCallsSize(), and results.
STDMETHODIMP CFusionResequencingResultsCOM::get_OrigCallsSize (int * pVal)
Definition at line 99 of file FusionResequencingResultsCOM.cpp.
References affymetrix_fusion_io::FusionResequencingResults::GetOrigCallsSize(), and results.
STDMETHODIMP CFusionResequencingResultsCOM::get_ScoresSize (int * pVal)
Definition at line 67 of file FusionResequencingResultsCOM.cpp.
References affymetrix_fusion_io::FusionResequencingResults::GetScoresSize(), and results.
STDMETHODIMP CFusionResequencingResultsCOM::GetCalledBase (int index, CHAR * pVal)
Definition at line 49 of file FusionResequencingResultsCOM.cpp.
References affymetrix_fusion_io::FusionResequencingResults::GetCalledBase(), and results.
STDMETHODIMP CFusionResequencingResultsCOM::GetForceCall (int index, IFusionForceCallType ** pVal)
Definition at line 73 of file FusionResequencingResultsCOM.cpp.
References CFusionForceCallTypeCOM::Force(), affymetrix_fusion_io::FusionResequencingResults::GetForceCall(), and results.
STDMETHODIMP CFusionResequencingResultsCOM::GetOrigCall (int index, IFusionBaseCallType ** pVal)
Definition at line 89 of file FusionResequencingResultsCOM.cpp.
References CFusionBaseCallTypeCOM::Call(), affymetrix_fusion_io::FusionResequencingResults::GetOrigCall(), and results.
STDMETHODIMP CFusionResequencingResultsCOM::GetScore (int index, float * pVal)
Definition at line 61 of file FusionResequencingResultsCOM.cpp.
References affymetrix_fusion_io::FusionResequencingResults::GetScore(), and results.
STDMETHODIMP CFusionResequencingResultsCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 28 of file FusionResequencingResultsCOM.cpp.
affymetrix_fusion_io::FusionResequencingResults& CFusionResequencingResultsCOM::Results () [inline]
Definition at line 68 of file FusionResequencingResultsCOM.h.
Referenced by CFusionCHPLegacyDataCOM::GetReseqResults().
Member Data Documentation
affymetrix_fusion_io::FusionResequencingResults CFusionResequencingResultsCOM::results [private]
Definition at line 65 of file FusionResequencingResultsCOM.h.
Referenced by Clear(), get_CalledBasesSize(), get_ForceCallsSize(), get_OrigCallsSize(), get_ScoresSize(), GetCalledBase(), GetForceCall(), GetOrigCall(), and GetScore().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionResequencingResultsCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionResequencingResultsCOM.cpp