Affymetrix Fusion SDK: AffxSplitArray< TYPE, NUM_ARRAYS > Class Template Reference
AffxSplitArray< TYPE, NUM_ARRAYS > Class Template Reference
#include <AffxSplitArray.h>
Public Member Functions
AffxSplitArray ()
~AffxSplitArray ()
int size () const
void allocate (int n)
void clear ()
TYPE * getAt (int i)
TYPE & operator[] (int i)
const TYPE & operator[] (int i) const
Private Member Functions
void allocate (int n, int narrays)
Private Attributes
std::vector< TYPE * > vData
std::vector< int > vDataSizes
int vDataSize
Detailed Description
template<class TYPE, int NUM_ARRAYS = 10>
class AffxSplitArray< TYPE, NUM_ARRAYS >
Definition at line 33 of file AffxSplitArray.h.
Constructor & Destructor Documentation
template<class TYPE , int NUM_ARRAYS = 10> AffxSplitArray< TYPE, NUM_ARRAYS >::AffxSplitArray () [inline]
Construct the class.
Definition at line 78 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::clear().
template<class TYPE , int NUM_ARRAYS = 10> AffxSplitArray< TYPE, NUM_ARRAYS >::~AffxSplitArray () [inline]
Clean up.
Definition at line 80 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::clear().
Member Function Documentation
template<class TYPE , int NUM_ARRAYS = 10> void AffxSplitArray< TYPE, NUM_ARRAYS >::allocate (int n, int narrays) [inline, private]
Allocate memory for the data.
Parameters:
n The number of data objects.
narrays The number of vector elements to create for the data storage.
Definition at line 46 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::vData, AffxSplitArray< TYPE, NUM_ARRAYS >::vDataSize, and AffxSplitArray< TYPE, NUM_ARRAYS >::vDataSizes.
Referenced by AffxSplitArray< TYPE, NUM_ARRAYS >::allocate().
template<class TYPE , int NUM_ARRAYS = 10> void AffxSplitArray< TYPE, NUM_ARRAYS >::allocate (int n) [inline]
Allocate storage for the data.
Parameters:
n The number of data elements to store.
Definition at line 86 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::allocate(), and AffxSplitArray< TYPE, NUM_ARRAYS >::clear().
template<class TYPE , int NUM_ARRAYS = 10> void AffxSplitArray< TYPE, NUM_ARRAYS >::clear (void) [inline]
Clear the data.
Definition at line 109 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::vData, AffxSplitArray< TYPE, NUM_ARRAYS >::vDataSize, and AffxSplitArray< TYPE, NUM_ARRAYS >::vDataSizes.
Referenced by AffxSplitArray< TYPE, NUM_ARRAYS >::AffxSplitArray(), AffxSplitArray< TYPE, NUM_ARRAYS >::allocate(), and AffxSplitArray< TYPE, NUM_ARRAYS >::~AffxSplitArray().
template<class TYPE , int NUM_ARRAYS = 10> TYPE* AffxSplitArray< TYPE, NUM_ARRAYS >::getAt (int i) [inline]
Get the element
Parameters:
i The index
Definition at line 122 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::vData, and AffxSplitArray< TYPE, NUM_ARRAYS >::vDataSizes.
Referenced by AffxSplitArray< TYPE, NUM_ARRAYS >::operator[]().
template<class TYPE , int NUM_ARRAYS = 10> TYPE& AffxSplitArray< TYPE, NUM_ARRAYS >::operator[] (int i) [inline]
Definition at line 133 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::getAt().
template<class TYPE , int NUM_ARRAYS = 10> const TYPE& AffxSplitArray< TYPE, NUM_ARRAYS >::operator[] (int i) const [inline]
Definition at line 138 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::getAt().
template<class TYPE , int NUM_ARRAYS = 10> int AffxSplitArray< TYPE, NUM_ARRAYS >::size () const [inline]
Returns the number of data elements stored.
Definition at line 82 of file AffxSplitArray.h.
References AffxSplitArray< TYPE, NUM_ARRAYS >::vDataSize.
Member Data Documentation
template<class TYPE , int NUM_ARRAYS = 10> std::vector<TYPE*> AffxSplitArray< TYPE, NUM_ARRAYS >::vData [private]
Vector of arrays of data objects.
Definition at line 37 of file AffxSplitArray.h.
Referenced by AffxSplitArray< TYPE, NUM_ARRAYS >::allocate(), AffxSplitArray< TYPE, NUM_ARRAYS >::clear(), and AffxSplitArray< TYPE, NUM_ARRAYS >::getAt().
template<class TYPE , int NUM_ARRAYS = 10> int AffxSplitArray< TYPE, NUM_ARRAYS >::vDataSize [private]
The total number of data objects stored.
Definition at line 41 of file AffxSplitArray.h.
Referenced by AffxSplitArray< TYPE, NUM_ARRAYS >::allocate(), AffxSplitArray< TYPE, NUM_ARRAYS >::clear(), and AffxSplitArray< TYPE, NUM_ARRAYS >::size().
template<class TYPE , int NUM_ARRAYS = 10> std::vector<int> AffxSplitArray< TYPE, NUM_ARRAYS >::vDataSizes [private]
The size of each array of data in the data vector.
Definition at line 39 of file AffxSplitArray.h.
Referenced by AffxSplitArray< TYPE, NUM_ARRAYS >::allocate(), AffxSplitArray< TYPE, NUM_ARRAYS >::clear(), and AffxSplitArray< TYPE, NUM_ARRAYS >::getAt().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/AffxSplitArray.h