Affymetrix Fusion SDK: CFusionCHPQuantificationDataCOM Class Reference
CFusionCHPQuantificationDataCOM Class Reference
#include <FusionCHPQuantificationDataCOM.h>
Public Member Functions
CFusionCHPQuantificationDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
STDMETHOD() get_FileTypeIdentifiers (VARIANT *pVal)
STDMETHOD() FromBase (IFusionCHPData *baseChp, VARIANT_BOOL *pVal)
STDMETHOD() get_AlgName (BSTR *pVal)
STDMETHOD() get_AlgVersion (BSTR *pVal)
STDMETHOD() get_ArrayType (BSTR *pVal)
STDMETHOD() get_AlgorithmParameters (VARIANT *pVal)
STDMETHOD() get_SummaryParameters (VARIANT *pVal)
STDMETHOD() get_EntryCount (int *pVal)
STDMETHOD() GetQuantificationEntry (int index, IProbeSetQuantificationData *pVal)
STDMETHOD() get_FileId (BSTR *pVal)
STDMETHOD() Close ()
Private Attributes
affymetrix_fusion_io::FusionCHPQuantificationData * chp
Detailed Description
Definition at line 29 of file FusionCHPQuantificationDataCOM.h.
Constructor & Destructor Documentation
CFusionCHPQuantificationDataCOM::CFusionCHPQuantificationDataCOM () [inline]
Definition at line 36 of file FusionCHPQuantificationDataCOM.h.
Member Function Documentation
STDMETHODIMP CFusionCHPQuantificationDataCOM::Close (void)
Definition at line 193 of file FusionCHPQuantificationDataCOM.cpp.
References chp.
HRESULT CFusionCHPQuantificationDataCOM::FinalConstruct () [inline]
Definition at line 56 of file FusionCHPQuantificationDataCOM.h.
void CFusionCHPQuantificationDataCOM::FinalRelease () [inline]
Definition at line 61 of file FusionCHPQuantificationDataCOM.h.
STDMETHODIMP CFusionCHPQuantificationDataCOM::FromBase (IFusionCHPData * baseChp, VARIANT_BOOL * pVal)
Definition at line 77 of file FusionCHPQuantificationDataCOM.cpp.
References chp, and CFusionCHPDataCOM::GetChip().
STDMETHODIMP CFusionCHPQuantificationDataCOM::get_AlgName (BSTR * pVal)
Definition at line 90 of file FusionCHPQuantificationDataCOM.cpp.
References chp, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgName().
STDMETHODIMP CFusionCHPQuantificationDataCOM::get_AlgorithmParameters (VARIANT * pVal)
Definition at line 114 of file FusionCHPQuantificationDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgParams(), CFusionTagValuePairTypeCOM::SetParam(), affymetrix_fusion_io::FusionTagValuePairType::Tag, and affymetrix_fusion_io::FusionTagValuePairType::Value.
STDMETHODIMP CFusionCHPQuantificationDataCOM::get_AlgVersion (BSTR * pVal)
Definition at line 98 of file FusionCHPQuantificationDataCOM.cpp.
References chp, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCHPQuantificationData::GetAlgVersion().
STDMETHODIMP CFusionCHPQuantificationDataCOM::get_ArrayType (BSTR * pVal)
Definition at line 106 of file FusionCHPQuantificationDataCOM.cpp.
References chp, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCHPQuantificationData::GetArrayType().
STDMETHODIMP CFusionCHPQuantificationDataCOM::get_EntryCount (int * pVal)
Definition at line 176 of file FusionCHPQuantificationDataCOM.cpp.
References chp, and affymetrix_fusion_io::FusionCHPQuantificationData::GetEntryCount().
STDMETHODIMP CFusionCHPQuantificationDataCOM::get_FileId (BSTR * pVal)
Definition at line 46 of file FusionCHPQuantificationDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPQuantificationData::FileId().
STDMETHODIMP CFusionCHPQuantificationDataCOM::get_FileTypeIdentifiers (VARIANT * pVal)
Definition at line 52 of file FusionCHPQuantificationDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPData::FileTypeIdentifiers().
STDMETHODIMP CFusionCHPQuantificationDataCOM::get_SummaryParameters (VARIANT * pVal)
Definition at line 145 of file FusionCHPQuantificationDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPQuantificationData::GetSummaryParams(), CFusionTagValuePairTypeCOM::SetParam(), affymetrix_fusion_io::FusionTagValuePairType::Tag, and affymetrix_fusion_io::FusionTagValuePairType::Value.
STDMETHODIMP CFusionCHPQuantificationDataCOM::GetQuantificationEntry (int index, IProbeSetQuantificationData * pVal)
Definition at line 184 of file FusionCHPQuantificationDataCOM.cpp.
References chp, CProbeSetQuantificationDataCOM::Data(), and affymetrix_fusion_io::FusionCHPQuantificationData::GetQuantificationEntry().
STDMETHODIMP CFusionCHPQuantificationDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 31 of file FusionCHPQuantificationDataCOM.cpp.
Member Data Documentation
affymetrix_fusion_io::FusionCHPQuantificationData* CFusionCHPQuantificationDataCOM::chp [private]
Definition at line 68 of file FusionCHPQuantificationDataCOM.h.
Referenced by Close(), FromBase(), get_AlgName(), get_AlgorithmParameters(), get_AlgVersion(), get_ArrayType(), get_EntryCount(), get_FileId(), get_FileTypeIdentifiers(), get_SummaryParameters(), and GetQuantificationEntry().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPQuantificationDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPQuantificationDataCOM.cpp