Affymetrix Fusion SDK: affymetrix_calvin_io::CHPQuantificationDetectionData Class Reference
affymetrix_calvin_io::CHPQuantificationDetectionData Class Reference
#include <CHPQuantificationDetectionData.h>
Public Member Functions
CHPQuantificationDetectionData ()
CHPQuantificationDetectionData (const std::string &filename)
~CHPQuantificationDetectionData ()
int GetMaxProbeSetName () const
void Clear ()
void SetFilename (const std::string &p)
std::string GetFilename () const
std::wstring GetArrayType ()
void SetArrayType (const std::wstring &value)
void SetEntryCount (int32_t ln, int32_t maxln)
void SetEntryCount (int32_t ln)
int32_t GetEntryCount ()
std::wstring GetAlgName ()
void SetAlgName (const std::wstring &value)
std::wstring GetAlgVersion ()
void SetAlgVersion (const std::wstring &value)
ParameterNameValueTypeList GetAlgParams ()
void AddAlgParams (const ParameterNameValueTypeList &params)
ParameterNameValueTypeList GetSummaryParams ()
void AddSummaryParams (const ParameterNameValueTypeList &params)
FileHeader * GetFileHeader ()
GenericData & GetGenericData ()
void GetQuantificationDetectionEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationDetectionData &entry)
void OpenQuantificationDetectionDataSet ()
DataSetHeader & GetDataSetHeader ()
Private Member Functions
std::wstring GetWStringFromGenericHdr (const std::wstring &name)
void SetWStringToGenericHdr (const std::wstring &name, const std::wstring value, int32_t reserve=-1)
void AddColumns (DataSetHeader &hdr, bool keyIsID)
Private Attributes
DataSetColumnTypes firstColumnType
GenericData genericData
DataSet * entries
int maxProbeSetName
Detailed Description
Holds data associated with quantification/detection CHP files.
Definition at line 40 of file CHPQuantificationDetectionData.h.
Constructor & Destructor Documentation
CHPQuantificationDetectionData::CHPQuantificationDetectionData ()
Constructor
Definition at line 46 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::UnicodeCharColType.
CHPQuantificationDetectionData::CHPQuantificationDetectionData (const std::string & filename)
Constructor with file name.
Parameters:
filename The name of the CHP file.
Definition at line 54 of file CHPQuantificationDetectionData.cpp.
References CHP_QUANTIFICATION_DETECTION_TYPE, QUANTIFICATION_DETECTION_NAME, and affymetrix_calvin_io::UnicodeCharColType.
CHPQuantificationDetectionData::~CHPQuantificationDetectionData ()
Destructor
Definition at line 66 of file CHPQuantificationDetectionData.cpp.
Member Function Documentation
void affymetrix_calvin_io::CHPQuantificationDetectionData::AddAlgParams (const ParameterNameValueTypeList & params)
Adds the algorithm parameters.
Parameters:
params The algorithm parameters.
void CHPQuantificationDetectionData::AddColumns (DataSetHeader & hdr, bool keyIsID) [private]
Adds the columns to the data set.
Parameters:
hdr The data set header.
keyIsID True if the probe set ids are to be stored, false for probe set names.
Definition at line 147 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddAsciiColumn(), affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), affymetrix_calvin_io::DataSetHeader::AddIntColumn(), QUANTIFICATION_DETECTION_DETECTION_NAME, QUANTIFICATION_DETECTION_PROBE_SET_ID, QUANTIFICATION_DETECTION_PROBE_SET_NAME, and QUANTIFICATION_DETECTION_QUANTIFICATION_NAME.
void CHPQuantificationDetectionData::AddSummaryParams (const ParameterNameValueTypeList & params)
Adds the summary parameters.
Parameters:
params The summary parameters.
Definition at line 1369 of file CHPMultiDataData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), CHIP_SUMMARY_PARAMETER_NAME_PREFIX, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
void CHPQuantificationDetectionData::Clear ()
Clears the members.
Definition at line 76 of file CHPQuantificationDetectionData.cpp.
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read().
std::wstring CHPQuantificationDetectionData::GetAlgName ()
Gets the name of the algorithm.
Returns:
The algorithm name.
Definition at line 180 of file CHPQuantificationDetectionData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgName().
ParameterNameValueTypeList CHPQuantificationDetectionData::GetAlgParams ()
Gets the algorithm parameters
Returns:
The algoirhtm parameters.
Definition at line 200 of file CHPQuantificationDetectionData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgParams().
std::wstring CHPQuantificationDetectionData::GetAlgVersion ()
Gets the algorithm version.
Returns:
The version.
Definition at line 190 of file CHPQuantificationDetectionData.cpp.
References ALG_VERSION_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgVersion().
std::wstring CHPQuantificationDetectionData::GetArrayType ()
Sets the array type
Definition at line 170 of file CHPQuantificationDetectionData.cpp.
References ARRAY_TYPE_PARAM_NAME.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetArrayType().
DataSetHeader & CHPQuantificationDetectionData::GetDataSetHeader ()
Returns the data set header.
Definition at line 71 of file CHPQuantificationDetectionData.cpp.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetDataSetHeader().
int32_t CHPQuantificationDetectionData::GetEntryCount ()
Gets the number of entries (probe sets)
Definition at line 92 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSet(), and affymetrix_calvin_io::DataSetHeader::GetRowCnt().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetEntryCount(), and CalvinChpCheck::quantificationDetectionDataSame().
FileHeader* affymetrix_calvin_io::CHPQuantificationDetectionData::GetFileHeader () [inline]
Gets the file header.
Returns:
The file header.
Definition at line 148 of file CHPQuantificationDetectionData.h.
References genericData, and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::CHPQuantificationDetectionFileWriter().
std::string CHPQuantificationDetectionData::GetFilename () const
Gets the file name.
Returns:
The file name.
Definition at line 87 of file CHPQuantificationDetectionData.cpp.
Referenced by CalvinChpCheck::quantificationDetectionDataSame(), and affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read().
GenericData& affymetrix_calvin_io::CHPQuantificationDetectionData::GetGenericData () [inline]
Gets the generic data object.
Returns:
The data object.
Definition at line 153 of file CHPQuantificationDetectionData.h.
References genericData.
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionFileReader::Read().
int affymetrix_calvin_io::CHPQuantificationDetectionData::GetMaxProbeSetName () const [inline]
The maximum length of a probe set name.
Definition at line 70 of file CHPQuantificationDetectionData.h.
References maxProbeSetName.
Referenced by affymetrix_calvin_io::CHPQuantificationDetectionFileWriter::CHPQuantificationDetectionFileWriter().
void CHPQuantificationDetectionData::GetQuantificationDetectionEntry (int index, affymetrix_calvin_data::ProbeSetQuantificationDetectionData & entry)
Gets the sequence data.
Parameters:
index The row index.
entry The quantification/detection value.
Definition at line 125 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::ASCIICharColType, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::id, affymetrix_calvin_io::IntColType, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::name, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::pvalue, affymetrix_calvin_data::_ProbeSetQuantificationDetectionData::quantification, and affymetrix_calvin_io::UnicodeCharColType.
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetQuantificationDetectionEntry(), and CalvinChpCheck::quantificationDetectionDataSame().
ParameterNameValueTypeList CHPQuantificationDetectionData::GetSummaryParams ()
Gets the summary parameters
Returns:
The summary parameters.
Definition at line 234 of file CHPQuantificationDetectionData.cpp.
References CHIP_SUMMARY_PARAMETER_NAME_PREFIX_S, affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
Referenced by affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetSummaryParams().
std::wstring CHPQuantificationDetectionData::GetWStringFromGenericHdr (const std::wstring & name) [private]
Gets a parameter value as a string.
Parameters:
name The name of the parameter.
Returns:
The string representation.
Definition at line 268 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueText().
void CHPQuantificationDetectionData::OpenQuantificationDetectionDataSet ()
Opens a group for reading.
Definition at line 157 of file CHPQuantificationDetectionData.cpp.
void CHPQuantificationDetectionData::SetAlgName (const std::wstring & value)
Sets the name of the algorithm.
Parameters:
value The algorithm name.
Definition at line 185 of file CHPQuantificationDetectionData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
void CHPQuantificationDetectionData::SetAlgVersion (const std::wstring & value)
Sets the algorithm version.
Parameters:
value The version.
Definition at line 195 of file CHPQuantificationDetectionData.cpp.
References ALG_VERSION_PARAM_NAME.
void CHPQuantificationDetectionData::SetArrayType (const std::wstring & value)
Sets the array type.
Definition at line 175 of file CHPQuantificationDetectionData.cpp.
References ARRAY_TYPE_MAX_LEN, and ARRAY_TYPE_PARAM_NAME.
void CHPQuantificationDetectionData::SetEntryCount (int32_t ln, int32_t maxln)
Sets the number of entries (probe sets). Use this function if names are to be stored.
Parameters:
ln The number of probe sets.
maxln The maximum length of a probe set name.
Definition at line 99 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::ASCIICharColType, QUANTIFICATION_DETECTION_NAME, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CHPQuantificationDetectionData::SetEntryCount (int32_t ln)
Sets the number of entries (probe sets). Use this function if ids are to be stored.
Parameters:
ln The number of probe sets.
Definition at line 112 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), affymetrix_calvin_io::IntColType, QUANTIFICATION_DETECTION_NAME, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CHPQuantificationDetectionData::SetFilename (const std::string & p)
Sets the file name.
Parameters:
p The name of the CHP file
Definition at line 82 of file CHPQuantificationDetectionData.cpp.
void CHPQuantificationDetectionData::SetWStringToGenericHdr (const std::wstring & name, const std::wstring value, int32_t reserve = -1) [private]
Adds a parameter name/value pair to the parameters section.
Parameters:
name The name of the parameter.
value The value of the parameter.
reserve The length of the string to reserve.
Definition at line 280 of file CHPQuantificationDetectionData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
Member Data Documentation
DataSet* affymetrix_calvin_io::CHPQuantificationDetectionData::entries [private]
chp data sets
Definition at line 62 of file CHPQuantificationDetectionData.h.
DataSetColumnTypes affymetrix_calvin_io::CHPQuantificationDetectionData::firstColumnType [private]
Flag indicating if the probe set names were stored in wide character format.
Definition at line 56 of file CHPQuantificationDetectionData.h.
GenericData affymetrix_calvin_io::CHPQuantificationDetectionData::genericData [private]
The generic data item.
Definition at line 59 of file CHPQuantificationDetectionData.h.
Referenced by GetFileHeader(), and GetGenericData().
int affymetrix_calvin_io::CHPQuantificationDetectionData::maxProbeSetName [private]
The maximum length of a probe set name.
Definition at line 65 of file CHPQuantificationDetectionData.h.
Referenced by GetMaxProbeSetName().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CHPQuantificationDetectionData.h
C:/f112/affy/sdk/calvin_files/data/src/CHPMultiDataData.cpp
C:/f112/affy/sdk/calvin_files/data/src/CHPQuantificationData.cpp
C:/f112/affy/sdk/calvin_files/data/src/CHPQuantificationDetectionData.cpp