Affymetrix Fusion SDK: affymetrix_fusion_io::FusionUniversalProbeSetResults Class Reference
affymetrix_fusion_io::FusionUniversalProbeSetResults Class Reference
#include <FusionProbeSetResults.h>
Public Member Functions
float GetBackground () const
void SetBackground (float bg)
void Clear ()
FusionUniversalProbeSetResults operator= (FusionUniversalProbeSetResults &src)
FusionUniversalProbeSetResults ()
~FusionUniversalProbeSetResults ()
Private Attributes
float background
Detailed Description
Universal (tag array) analysis probe set results.
Definition at line 386 of file FusionProbeSetResults.h.
Constructor & Destructor Documentation
FusionUniversalProbeSetResults::FusionUniversalProbeSetResults ()
Constructor
Definition at line 407 of file FusionProbeSetResults.cpp.
References Clear().
FusionUniversalProbeSetResults::~FusionUniversalProbeSetResults ()
Destructor
Definition at line 412 of file FusionProbeSetResults.cpp.
Member Function Documentation
void FusionUniversalProbeSetResults::Clear (void)
Definition at line 396 of file FusionProbeSetResults.cpp.
References background.
Referenced by FusionUniversalProbeSetResults().
float FusionUniversalProbeSetResults::GetBackground () const
Gets the background value.
Returns:
The background value.
Definition at line 386 of file FusionProbeSetResults.cpp.
References background.
Referenced by CFusionUniversalProbeSetResultsCOM::get_Background(), and operator=().
FusionUniversalProbeSetResults FusionUniversalProbeSetResults::operator= (FusionUniversalProbeSetResults & src)
Assignment operator
Parameters:
src The object to copy
Returns:
The copied object
Definition at line 401 of file FusionProbeSetResults.cpp.
References GetBackground(), and SetBackground().
void FusionUniversalProbeSetResults::SetBackground (float bg)
Sets the background value.
Parameters:
bg The background value.
Definition at line 391 of file FusionProbeSetResults.cpp.
References background.
Referenced by affymetrix_fusion_io::GCOSCHPDataAdapter::GetUniversalResults(), affymetrix_fusion_io::CalvinCHPDataAdapter::GetUniversalResults(), and operator=().
Member Data Documentation
float affymetrix_fusion_io::FusionUniversalProbeSetResults::background [private]
The background value.
Definition at line 391 of file FusionProbeSetResults.h.
Referenced by Clear(), GetBackground(), and SetBackground().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.h
C:/f112/affy/sdk/calvin_files/fusion/src/FusionProbeSetResults.cpp