Affymetrix Fusion SDK: SocketTextHandler Class Reference
SocketTextHandler Class Reference
#include <SocketTextHandler.h>
Public Member Functions
SocketTextHandler ()
Constructor.
bool hasFinished ()
Has the socket send the "completion" message?
bool successfulRun ()
was the run successful?
virtual void handleMessage (int type, int channel, const std::string &msg)
Protected Attributes
bool m_Finished
Has the socket sent the "completed" signal?
bool m_SuccessfulRun
Detailed Description
Basic Socket Handler (Listener) that parses out verbose and progress messages from a socket stream.
Definition at line 31 of file SocketTextHandler.h.
Constructor & Destructor Documentation
SocketTextHandler::SocketTextHandler ()
Constructor.
Definition at line 26 of file SocketTextHandler.cpp.
References SocketHandler::KILLMSG, SocketHandler::m_Channels, m_Finished, m_SuccessfulRun, SocketHandler::m_Types, SocketHandler::PROGRESS, SocketHandler::TEXT, and SocketHandler::VERBOSE.
Member Function Documentation
void SocketTextHandler::handleMessage (int type, int channel, const std::string & msg) [virtual]
Take a message and do whatever functionality this handler implements from simply displaying message to
Parameters:
type - What type (i.e. text, xml,) of message is this message.
channel - What channel (i.e. verbose, progress, etc.) is this message.
msg - Data to be parsed out
Implements SocketHandler.
Definition at line 44 of file SocketTextHandler.cpp.
References APT_ERR_ABORT, APT_ERR_ASSERT, SocketHandler::COMPLETION, SocketHandler::deserializeMap(), SocketHandler::KILLMSG, SocketHandler::m_Channels, m_Finished, m_SuccessfulRun, SocketHandler::m_Types, Verbose::out(), SocketHandler::PROGRESS, Verbose::progressBegin(), Verbose::progressEnd(), Verbose::progressStep(), Convert::toInt(), ToStr(), and SocketHandler::VERBOSE.
bool SocketTextHandler::hasFinished ()
Has the socket send the "completion" message?
Definition at line 36 of file SocketTextHandler.cpp.
References m_Finished.
bool SocketTextHandler::successfulRun ()
was the run successful?
Definition at line 40 of file SocketTextHandler.cpp.
References m_SuccessfulRun.
Referenced by SocketEngine::run().
Member Data Documentation
bool SocketTextHandler::m_Finished [protected]
Has the socket sent the "completed" signal?
Definition at line 56 of file SocketTextHandler.h.
Referenced by handleMessage(), hasFinished(), and SocketTextHandler().
bool SocketTextHandler::m_SuccessfulRun [protected]
Definition at line 57 of file SocketTextHandler.h.
Referenced by handleMessage(), SocketTextHandler(), and successfulRun().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/SocketTextHandler.h
C:/f112/affy/sdk/util/SocketTextHandler.cpp