Affymetrix Fusion SDK: affxmdl::CMDLFileData Class Reference
affxmdl::CMDLFileData Class Reference
#include <MDLFileData.h>
Public Member Functions
void SetFileName (const char *value)
std::string GetFileName () const
std::string GetError () const
CMDLFileHeader & GetHeader ()
void SetHeader (CMDLFileHeader &header)
void GetProbeData (int32_t index, CMDLProbeData &data)
void SetProbeData (int32_t index, CMDLProbeData data)
bool Read ()
bool ReadHeader ()
bool Write ()
bool Exists ()
void Close ()
void InitializeForWriting (int32_t nSize=0, double defAffinity=1.0, int32_t analysisType=MDL_PLIER)
bool PrintMDLToTextFile (const char *sFile, int32_t nProbes)
CMDLFileData (int32_t nSize=0, double defAffinity=1.0, int32_t analysisType=MDL_PLIER)
~CMDLFileData ()
Protected Member Functions
void GetHeaderInfo (MDLHeader *pHeader)
void SetHeaderInfo (MDLHeader *pHeader)
void SetDataInfo (MDLData *pData, CMDLProbeData *data)
void GetDataInfo (MDLData *pData, CMDLProbeData &data)
bool Open (bool bReadHeaderOnly=false)
bool ReadFile (bool bReadHeaderOnly=false)
bool ReadFileHeader (std::ifstream &instr)
Protected Attributes
CMDLFileHeader m_Header
std::string m_strFileName
std::string m_strError
std::vector< CMDLProbeData > m_ProbeData
Detailed Description
PLIER model file stores the model data as the structure defined above. (1) It is probe array type specific. Only the model file with the same probe array type can be used for PLIER analysis (2) It stores the model data for each probe (or cells). (3) It starts storing model data for all PM probes and follows by all MM probes. (4) Sum(a(j)) = # of probes
Definition at line 271 of file MDLFileData.h.
Constructor & Destructor Documentation
CMDLFileData::CMDLFileData (int32_t nSize = 0, double defAffinity = 1.0, int32_t analysisType = MDL_PLIER)
Constructor
Definition at line 142 of file MDLFileData.cpp.
References affxmdl::CMDLProbeData::SetAffinity().
CMDLFileData::~CMDLFileData ()
Destructor
Definition at line 171 of file MDLFileData.cpp.
References Close().
Member Function Documentation
void CMDLFileData::Close (void)
Closes the file
Definition at line 339 of file MDLFileData.cpp.
References m_ProbeData.
Referenced by Open(), Read(), ReadHeader(), and ~CMDLFileData().
bool CMDLFileData::Exists ()
Checks if the file exists
Returns:
True if the file exists
Definition at line 612 of file MDLFileData.cpp.
References m_strFileName.
Referenced by Read(), and ReadHeader().
void CMDLFileData::GetDataInfo (MDLData * pData, CMDLProbeData & data) [protected]
Gets the data from the class
Parameters:
pData The data
data The probe data
Definition at line 237 of file MDLFileData.cpp.
References affxmdl::_MDLData::Affinity, affxmdl::CMDLProbeData::GetAffinity(), affxmdl::CMDLProbeData::GetOffset(), affxmdl::CMDLProbeData::GetRelativeBkg(), affxmdl::CMDLProbeData::GetSaturation(), affxmdl::_MDLData::Offset, affxmdl::_MDLData::RelativeBkg, and affxmdl::_MDLData::Saturation.
Referenced by Write().
std::string affxmdl::CMDLFileData::GetError () const [inline]
The error message
Returns:
The error message
Definition at line 352 of file MDLFileData.h.
References m_strError.
std::string affxmdl::CMDLFileData::GetFileName () const [inline]
Returns the file name
Returns:
The file name
Definition at line 347 of file MDLFileData.h.
References m_strFileName.
CMDLFileHeader& affxmdl::CMDLFileData::GetHeader () [inline]
Returns the header
Returns:
The file header object
Definition at line 357 of file MDLFileData.h.
References m_Header.
void CMDLFileData::GetHeaderInfo (MDLHeader * pHeader) [protected]
Gets the header
Parameters:
pHeader The header data
Definition at line 214 of file MDLFileData.cpp.
References affxmdl::_MDLHeader::bMasked, affxmdl::CMDLFileHeader::GetAnalysisType(), affxmdl::CMDLFileHeader::GetChipType(), affxmdl::CMDLFileHeader::GetMasked(), affxmdl::CMDLFileHeader::GetModifiedDate(), affxmdl::CMDLFileHeader::GetNumProbes(), affxmdl::CMDLFileHeader::GetVersion(), m_Header, affxmdl::_MDLHeader::nAnalysisType, affxmdl::_MDLHeader::nNumProbes, affxmdl::_MDLHeader::nVersion, RESERVED_SIZE, affxmdl::_MDLHeader::sChipType, affxmdl::_MDLHeader::sModifiedDate, and affxmdl::_MDLHeader::sReserve.
Referenced by Write().
void CMDLFileData::GetProbeData (int32_t index, CMDLProbeData & data)
Gets the probe data
Parameters:
index Index to the probe data object
data The probe data
Definition at line 247 of file MDLFileData.cpp.
References FLOAT_SIZE, affxmdl::CMDLFileHeader::GetNumProbes(), affxmdl::CMDLProbeData::m_bMapped, affxmdl::CMDLProbeData::m_dAffinity, affxmdl::CMDLProbeData::m_fOffset, affxmdl::CMDLProbeData::m_fRelativeBkg, affxmdl::CMDLProbeData::m_fSaturation, m_Header, affxmdl::CMDLProbeData::m_lpData, affxmdl::CMDLProbeData::m_nIndex, m_ProbeData, affxmdl::CMDLProbeData::MakeShallowCopy(), and MDLDATASIZE.
Referenced by PrintMDLToTextFile().
void CMDLFileData::InitializeForWriting (int32_t nSize = 0, double defAffinity = 1.0, int32_t analysisType = MDL_PLIER)
Initializes the object for writing
Parameters:
nSize The size
defAffinity The default affynity value
analysisType The analysis type
Definition at line 179 of file MDLFileData.cpp.
References affxmdl::CMDLProbeData::SetAffinity().
bool CMDLFileData::Open (bool bReadHeaderOnly = false) [protected]
Opens the file
Parameters:
bReadHeaderOnly Flag to read only the header
Returns:
True if successful
Definition at line 325 of file MDLFileData.cpp.
References Close(), and ReadFile().
Referenced by Read(), and ReadHeader().
bool CMDLFileData::PrintMDLToTextFile (const char * sFile, int32_t nProbes)
Outputs the file context for debugging
Parameters:
sFile The output file name
nProbes The number of probes
Returns:
True if successful
Definition at line 621 of file MDLFileData.cpp.
References affxmdl::CMDLProbeData::GetAffinity(), affxmdl::CMDLFileHeader::GetAnalysisType(), affxmdl::CMDLFileHeader::GetChipType(), affxmdl::CMDLFileHeader::GetMasked(), affxmdl::CMDLFileHeader::GetModifiedDate(), affxmdl::CMDLFileHeader::GetNumProbes(), affxmdl::CMDLProbeData::GetOffset(), GetProbeData(), affxmdl::CMDLProbeData::GetRelativeBkg(), affxmdl::CMDLProbeData::GetSaturation(), affxmdl::CMDLFileHeader::GetVersion(), m_Header, and m_strError.
bool CMDLFileData::Read ()
Reads the entire file
Returns:
True if successful
Definition at line 291 of file MDLFileData.cpp.
References Close(), Exists(), and Open().
bool CMDLFileData::ReadFile (bool bReadHeaderOnly = false) [protected]
Reads the file
Parameters:
bReadHeaderOnly Flag to read only the header
Returns:
True if successful
Definition at line 363 of file MDLFileData.cpp.
References affxmdl::CMDLFileHeader::GetNumProbes(), m_Header, m_ProbeData, m_strError, m_strFileName, MDLDATASIZE, ReadFileHeader(), SetDataInfo(), and SwapFromLittleEndian().
Referenced by Open().
bool CMDLFileData::ReadFileHeader (std::ifstream & instr) [protected]
Reads the file header
Parameters:
instr The file stream.
Returns:
True if successful
Definition at line 517 of file MDLFileData.cpp.
References m_strError, MDLHEADERSIZE, SetHeaderInfo(), and SwapFromLittleEndian().
Referenced by ReadFile().
bool CMDLFileData::ReadHeader ()
Reads the file header only
Returns:
True if successful
Definition at line 308 of file MDLFileData.cpp.
References Close(), Exists(), and Open().
void CMDLFileData::SetDataInfo (MDLData * pData, CMDLProbeData * data) [protected]
Sets the data in the class
Parameters:
pData The data
data The probe data
Definition at line 227 of file MDLFileData.cpp.
References affxmdl::_MDLData::Affinity, affxmdl::_MDLData::Offset, affxmdl::_MDLData::RelativeBkg, affxmdl::_MDLData::Saturation, affxmdl::CMDLProbeData::SetAffinity(), affxmdl::CMDLProbeData::SetOffset(), affxmdl::CMDLProbeData::SetRelativeBkg(), and affxmdl::CMDLProbeData::SetSaturation().
Referenced by ReadFile().
void affxmdl::CMDLFileData::SetFileName (const char * value) [inline]
Sets the file name
Parameters:
value The file name
Definition at line 342 of file MDLFileData.h.
References m_strFileName.
void affxmdl::CMDLFileData::SetHeader (CMDLFileHeader & header) [inline]
Sets the header
Parameters:
header The header to save
Definition at line 362 of file MDLFileData.h.
References m_Header.
void CMDLFileData::SetHeaderInfo (MDLHeader * pHeader) [protected]
Sets the header
Parameters:
pHeader The header data
Definition at line 202 of file MDLFileData.cpp.
References affxmdl::_MDLHeader::bMasked, m_Header, affxmdl::_MDLHeader::nAnalysisType, affxmdl::_MDLHeader::nNumProbes, affxmdl::_MDLHeader::nVersion, affxmdl::_MDLHeader::sChipType, affxmdl::CMDLFileHeader::SetAnalysisType(), affxmdl::CMDLFileHeader::SetChipType(), affxmdl::CMDLFileHeader::SetMasked(), affxmdl::CMDLFileHeader::SetModifiedDate(), affxmdl::CMDLFileHeader::SetNumProbes(), affxmdl::CMDLFileHeader::SetVersion(), and affxmdl::_MDLHeader::sModifiedDate.
Referenced by ReadFileHeader().
void CMDLFileData::SetProbeData (int32_t index, CMDLProbeData data)
Sets the probe data
Parameters:
index Index to the probe data object
data The probe data
Definition at line 282 of file MDLFileData.cpp.
References affxmdl::CMDLFileHeader::GetNumProbes(), m_Header, and m_ProbeData.
bool CMDLFileData::Write ()
Writes the file
Returns:
True if successful
Definition at line 541 of file MDLFileData.cpp.
References GetDataInfo(), GetHeaderInfo(), affxmdl::CMDLFileHeader::GetNumProbes(), m_Header, m_ProbeData, m_strError, m_strFileName, MDLDATASIZE, MDLHEADERSIZE, affxmdl::CMDLFileHeader::SetModifiedDate(), and SwapToLittleEndian().
Member Data Documentation
CMDLFileHeader affxmdl::CMDLFileData::m_Header [protected]
The file header
Definition at line 275 of file MDLFileData.h.
Referenced by GetHeader(), GetHeaderInfo(), GetProbeData(), PrintMDLToTextFile(), ReadFile(), SetHeader(), SetHeaderInfo(), SetProbeData(), and Write().
std::vector<CMDLProbeData> affxmdl::CMDLFileData::m_ProbeData [protected]
The probe data
Definition at line 284 of file MDLFileData.h.
Referenced by Close(), GetProbeData(), ReadFile(), SetProbeData(), and Write().
std::string affxmdl::CMDLFileData::m_strError [protected]
Stores an error message
Definition at line 281 of file MDLFileData.h.
Referenced by GetError(), PrintMDLToTextFile(), ReadFile(), ReadFileHeader(), and Write().
std::string affxmdl::CMDLFileData::m_strFileName [protected]
The file name
Definition at line 278 of file MDLFileData.h.
Referenced by Exists(), GetFileName(), ReadFile(), SetFileName(), and Write().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/MDLFileData.h
C:/f112/affy/sdk/file/MDLFileData.cpp