Affymetrix Fusion SDK: affxgrc::CGRCFileWriter Class Reference
affxgrc::CGRCFileWriter Class Reference
#include <GRCFileWriter.h>
Public Member Functions
CGRCFileWriter ()
~CGRCFileWriter ()
bool Write (const affx1lq::C1LQFileData &libData, bool opposite=false)
bool Write (bool opposite=false)
void PopulateData (const affx1lq::C1LQFileData &libData)
void SetRows (int rows)
void SetColumns (int columns)
void ResizeB1 (int size)
void ResizeB2 (int size)
void ResizeNS (int size)
void SetB1 (int index, int x, int y)
void SetB2 (int index, int x, int y)
void SetNS (int index, int x, int y)
Protected Member Functions
void ParseLibData (const affx1lq::C1LQFileData &libData)
bool WriteFile (bool opposite=false)
Protected Attributes
affymetrix_grid_control::GridControlData m_Grid
Detailed Description
This class holds the coordinates of those probes used by the GCAST algorithm.
Definition at line 41 of file GRCFileWriter.h.
Constructor & Destructor Documentation
CGRCFileWriter::CGRCFileWriter ()
Constructor
Definition at line 65 of file GRCFileWriter.cpp.
CGRCFileWriter::~CGRCFileWriter ()
Destructor
Definition at line 72 of file GRCFileWriter.cpp.
Member Function Documentation
void CGRCFileWriter::ParseLibData (const affx1lq::C1LQFileData & libData) [protected]
Parses the data from the 1LQ object.
Parameters:
libData The data from a 1LQ file.
Definition at line 124 of file GRCFileWriter.cpp.
References affx1lq::C1LQFileData::GetEntries(), affx1lq::C1LQFileData::GetNumberColumns(), affx1lq::C1LQFileData::GetNumberRows(), affx1lq::_DataEntry::plength, affx1lq::_DataEntry::probe, affx1lq::_DataEntry::qualifier, STR_CTRLB1_21, STR_CTRLB1_25, STR_CTRLB2_21, STR_CTRLB2_25, STR_EXTENDB2_11, STR_EXTENDB2_PROBE_LENGTH, STR_EXTENDB2_QUALIFIER, STR_NONSYNTH, affx1lq::_DataEntry::x, affymetrix_grid_control::_FeatureCoordinate::x, affx1lq::_DataEntry::y, and affymetrix_grid_control::_FeatureCoordinate::y.
void CGRCFileWriter::PopulateData (const affx1lq::C1LQFileData & libData)
Populate the class with 1LQ file data.
Parameters:
libData The data from a 1LQ file.
Definition at line 79 of file GRCFileWriter.cpp.
void affxgrc::CGRCFileWriter::ResizeB1 (int size) [inline]
Resizes the B1 array.
Parameters:
size The size of the array.
Definition at line 86 of file GRCFileWriter.h.
References m_Grid, and affymetrix_grid_control::GridControlData::ResizeB1().
void affxgrc::CGRCFileWriter::ResizeB2 (int size) [inline]
Resizes the B2 array.
Parameters:
size The size of the array.
Definition at line 91 of file GRCFileWriter.h.
References m_Grid, and affymetrix_grid_control::GridControlData::ResizeB2().
void affxgrc::CGRCFileWriter::ResizeNS (int size) [inline]
Resizes the NS array.
Parameters:
size The size of the array.
Definition at line 96 of file GRCFileWriter.h.
References m_Grid, and affymetrix_grid_control::GridControlData::ResizeNS().
void CGRCFileWriter::SetB1 (int index, int x, int y)
Sets the B1 probe at the given index.
Parameters:
index The index of the array.
coord The new coordinate.
Definition at line 86 of file GRCFileWriter.cpp.
References affymetrix_grid_control::_FeatureCoordinate::x, and affymetrix_grid_control::_FeatureCoordinate::y.
void CGRCFileWriter::SetB2 (int index, int x, int y)
Sets the B2 probe at the given index.
Parameters:
index The index of the array.
coord The new coordinate.
Definition at line 98 of file GRCFileWriter.cpp.
References affymetrix_grid_control::_FeatureCoordinate::x, and affymetrix_grid_control::_FeatureCoordinate::y.
void affxgrc::CGRCFileWriter::SetColumns (int columns) [inline]
Sets the number of columns.
Parameters:
columns The number of columns.
Definition at line 81 of file GRCFileWriter.h.
References m_Grid, and affymetrix_grid_control::GridControlData::SetColumns().
void CGRCFileWriter::SetNS (int index, int x, int y)
Sets the NS probe at the given index.
Parameters:
index The index of the array.
coord The new coordinate.
Definition at line 110 of file GRCFileWriter.cpp.
References affymetrix_grid_control::_FeatureCoordinate::x, and affymetrix_grid_control::_FeatureCoordinate::y.
void affxgrc::CGRCFileWriter::SetRows (int rows) [inline]
Sets the number of rows.
Parameters:
rows The number of rows.
Definition at line 76 of file GRCFileWriter.h.
References m_Grid, and affymetrix_grid_control::GridControlData::SetRows().
bool CGRCFileWriter::Write (bool opposite = false)
Writes the existing 1lq data to the grc file. This method requires that this class be populated with 1LQ File Data before it can be invoked (To poluate 1LQ file, you must first call PopulateData or Write(const affx1lq::C1LQFileData &libData,..) method).
Parameters:
opposite The generated GRC File contains the reverse direction.
Returns:
True if successful.
Definition at line 249 of file GRCFileWriter.cpp.
bool CGRCFileWriter::Write (const affx1lq::C1LQFileData & libData, bool opposite = false)
Writes the contents of the file.
Parameters:
libData The data from a 1LQ file.
opposite The generated GRC File contains the reverse direction.
Returns:
True if successful.
Definition at line 240 of file GRCFileWriter.cpp.
bool CGRCFileWriter::WriteFile (bool opposite = false) [protected]
Writes the existing data to the GRC file
Parameters:
opposite The generated GRC File contains the reverse direction.
Returns:
True if successful.
Definition at line 259 of file GRCFileWriter.cpp.
References GRC_MAGIC, GRC_VERSION, WriteInt32_N(), WriteUInt16_N(), and WriteUInt8().
Member Data Documentation
affymetrix_grid_control::GridControlData affxgrc::CGRCFileWriter::m_Grid [protected]
The GRC file object.
Definition at line 118 of file GRCFileWriter.h.
Referenced by ResizeB1(), ResizeB2(), ResizeNS(), SetColumns(), and SetRows().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/GRCFileWriter.h
C:/f112/affy/sdk/file/GRCFileWriter.cpp