Affymetrix Fusion SDK: Fs Class Reference
Fs Class Reference
An APT interface to the OS file handling utilities. "Fs" is the simple 'paths as strings' library.
#include <Fs.h>
Static Public Member Functions
static AptErr_t setErr (AptErr_t err_num, const std::string &err_msg, bool abortOnErr)
Sets err num and message. Possibly calls Err::errAbort.
static AptErr_t getErrNum ()
The current error number.
static std::string getErrMsg ()
The current error string (Should include the pathname.)
static AptErr_t clearErr ()
Clears the error num and message.
static AptErr_t setErrFromErrno (const std::string &path, bool abortOnErr)
translate
static AptErr_t setErrFromErrno (const std::string &path, int sys_errno, bool abortOnErr)
translate
static std::string pathSep ()
Get the internal path seperator.
static std::string osPathSep (const std::string &path="")
Get the path seperator for the OS or replace path separators for input string.
static std::string normalizePath (const std::string &path)
static AptErr_t normalizePathInPlace (std::string &path)
static std::string windowifyPath (const std::string &path)
static AptErr_t windowifyPathInPlace (std::string &path)
do what needs to be done to windowify a string.
static std::string unixifyPath (const std::string &path)
static AptErr_t unixifyPathInPlace (std::string &path)
static std::string join (const std::string &arg1, const std::string &arg2)
static std::string join (const std::string &arg1, const std::string &arg2, const std::string &arg3)
static std::string join (const std::string &arg1, const std::string &arg2, const std::string &arg3, const std::string &arg4)
static std::string join (std::vector< std::string > &args)
static bool hasTrailingSlash (const std::string &path_in)
static std::string addTrailingSlash (const std::string &path_in)
static std::string trimTrailingSlash (const std::string &path_in)
static std::string basename (const std::string &path)
like the unix function of the same name.
static std::vector< std::string > basename (const std::vector< std::string > &paths)
Apply basename to a vector.
static std::string dirname (const std::string &path)
just the dirname (will return "." or "/" as well.)
static std::string extname (const std::string &path)
return the stuff after the "." including the "." ("foo.bar" => ".bar")
static std::string noextname (const std::string &path)
chop off ALL the exts. ("path/foo.a.b.c" => "path/foo")
static std::string noextname1 (const std::string &path)
chop off ONE of the exts. ("path/foo.a.b.c" => "path/foo.a.b")
static std::string noextnameN (const std::string &path, int cnt)
chop off N of the exts ("path/foo.a.b.c",2 => "path/foo.a")
static void splitPath (const std::string &path, std::string &drive, std::vector< std::string > &parts)
static std::vector< std::string > changeDirAndExt (const std::string &new_dir, const std::vector< std::string > &paths, const std::string &new_ext)
static std::string convertToUncPath (const std::string &path)
static std::wstring convertToUncPathW (const std::string &path)
static std::string convertToUncPath (const std::string &path, int uncshortlen)
static std::wstring convertToUncPathW (const std::string &path, int uncshortlen)
static std::string Unc (const std::string &path)
Short name for convertToUncPath.
static std::wstring UncW (const std::string &path)
static AptErr_t convertToUncPathInPlace (std::string &path)
static AptErr_t convertToUncPathInPlace (std::string &path, int uncshortlen)
static std::string convertCommandToUnc (const std::string &cmd)
static AptErr_t chmodBasic (const std::string &path, int mode, bool abortOnErr=true)
Change the mode of a dir or file. This is chmodBasic because on Windows only the write bit for the user can be set. There is no notion of group and other. Files are always readable.
static bool exists (const std::string &path)
static bool dirExists (const std::string &path)
static bool fileExists (const std::string &path)
static bool isReadable (const std::string &path)
static bool isReadable (const std::string &path, AptErr_t &rv)
static bool isReadableDir (const std::string &path)
static bool isReadableDir (const std::string &path, AptErr_t &rv)
static bool isWriteable (const std::string &path)
static bool isWriteable (const std::string &path, AptErr_t &rv)
static bool isWriteableDir (const std::string &path)
static bool isWriteableDir (const std::string &path, AptErr_t &rv)
static bool isCalvinFile (const std::string &path)
static bool isHdf5File (const std::string &path)
static bool isBinaryFile (const std::string &path)
static AptErr_t ensureWriteableDirPath (const std::string &path, bool abortOnErr=true)
This will make the dir if it isnt there. If it is there, that is ok as long as it is writeable. This will make a path like mkdirPath.
static int64_t fileSize (const std::string &path, bool abortOnErr=true)
The size of the file.
static int64_t fileSize (const std::string &path, AptErr_t &errnum)
static AptErr_t listDir (const std::string &path, std::vector< std::string > &names, bool abortOnErr=true)
static AptErr_t mkdir (const std::string &path, bool abortOnErr=true)
Make one directory.
static AptErr_t mkdirPath (const std::string &path, bool abortOnErr=true)
make all path of directories
static AptErr_t rm (const std::string &path, bool abortOnErr=true)
An error if it doesnt exist.
static AptErr_t rmIfExists (const std::string &path, bool abortOnErr=true)
An error if the rm fails.
static AptErr_t rmdir (const std::string &path, bool abortOnErr=true)
Remove a directory.
static AptErr_t rmdirPath (const std::string &path, bool abortOnErr=true)
static AptErr_t rm_rf (const std::string &path, bool abortOnErr=true)
static AptErr_t touch (const std::string &path, bool abortOnErr=true)
touchs a file (creates a zero length file if not exists.)
static int64_t getFreeDiskSpace (const std::string &path, bool abortOnErr=true)
static bool isSameVolume (const std::string &path1, const std::string &path2, AptErr_t &rv, bool abortOnErr=true)
Do these two paths refer to the same volume?
static int aptOpen (const std::string &pathname, int flags=O_RDONLY)
static int aptOpen (const std::string &pathname, int flags, int mode)
static void aptOpen (std::fstream &fs, const std::string &filename, std::ios_base::openmode iomode=std::ios_base::in|std::ios_base::out)
static void aptOpen (std::ofstream &ofs, const std::string &filename, std::ios_base::openmode iomode=std::ios_base::out|std::ios_base::binary)
static void aptOpen (std::ifstream &ifs, const std::string &filename, std::ios_base::openmode iomode=std::ios_base::in)
static std::string findLibFile (const std::string &fileName, const std::string &searchPath="")
Util carry overs. These need to be updated with abortOnError.
static void mustOpenToWrite (std::ofstream &out, const std::string &fileName)
static void carefulClose (std::ofstream &out)
static void carefulClose (std::fstream &out)
static bool fileCopy (const std::string &in, const std::string &out, bool throwOnError=true)
static bool fileRename (const std::string &in, const std::string &out, bool throwOnError=true)
Static Public Attributes
static AptErr_t m_err_num
The error code of the last error.
static std::string m_err_msg
The error message of the last error.
Private Member Functions
Fs ()
The user shouldnt make one one of these objects. Make this private so they cant.
Detailed Description
An APT interface to the OS file handling utilities. "Fs" is the simple 'paths as strings' library.
APT should keep all paths in normalized (unix) format. Fs.cpp keeps all paths as "/". "\"s are converted to "/"s automaticly.
This library converts the pathnames to windows as and when needed. The programmer (you) should always use unix style paths.
The paths are filesystem paths. This is different than FsPath which is a richer represenation of the location of a dataset. (IE: No internal tablenames or groupnames.)
All the methods are static to the class. The only state is the class state of the error number and message. (Just like the system errno.)
The last param of the methods is the optional "abortOnErr" which defaults to "true". When "true" an error during the call results in and APT_ERR_ABORT. When "false" an error code is returned and the caller can deal with it as they see fit.
The "InPlace" functions are like the normal ones, but change the strings Rather than returning a new string.
Note: The convertToUncPath will not convert an already converted path. Thus calling it twice on a path should be safe. We want it to be this way as we dont know how many times this method will be called on a path.
Note: Many of the file libraries will call "convertToUncPath" for you. All you need to do is pass them a normalized path. file/TsvFile, File5 and the SQLite io code does do this; The legacy file IO does not.
Note: All APIs are Windows 32KB path size compliant. This requires the internal use of std::wstring any time a file name is used. However the std::wstring implies more than just a path longer than MAX_PATH (260) bytes in lenght. The std::wstring also implies: 1.) Unicode. APT code is NOT Unicode compliant. Therefore APT code should always use std::string APIs, except when providing someone additional path, std::string API not provided here. Do not use std::wstring for application path names as this may allow Unicode characters to creep into paths that have ASCII encoding. File names in APT are encoded with application information and parsing of file names in APT is not done with Unicode parsing. Do not use std::wstring for file names and paths. 2.) Unviseral Naming Convention, or UNC. Unfortunately UNC is cognitive of Unicode. They do not refer to the same thing. Microsoft "Universal" means Microsoft specific. Specifially network paths must start with "\\?\" and be std::wstring for ALL paths, even those shorter than MAX_PATH. All UNC paths then are also Unicode. For convienence Fs::Unc API will return the std::string UNC version so inspection of the full path being used. Given APT is is NOT Unicode compliant then the Fs::Unc returns std::string full path for ease of use.
Definition at line 128 of file Fs.h.
Constructor & Destructor Documentation
Fs::Fs () [private]
The user shouldnt make one one of these objects. Make this private so they cant.
Member Function Documentation
std::string Fs::addTrailingSlash (const std::string & path_in) [static]
Definition at line 366 of file Fs.cpp.
References FS_PATHSEP, and hasTrailingSlash().
Referenced by FsPath::FsPath(), FsPath::getDirNameSlash(), FsPath::pushDir(), FsPath::setDirName(), and FsPath::setPath().
int Fs::aptOpen (const std::string & pathname, int flags = O_RDONLY) [static]
Definition at line 1438 of file Fs.cpp.
References UncW().
Referenced by MixedFileCheck::check(), affymetrix_calvin_utilities::FileUtils::Exists(), file_starts_with(), fileCopy(), Fs__stat(), affx::TsvFile::getLineCountInFile(), isBinaryFile(), affxchp::CCHPFileData::IsMas5File(), affxchp::CCHPFileData::IsXDACompatibleFile(), affymetrix_calvin_utilities::FileUtils::LockFile(), mustOpenToWrite(), RowFile::open(), LineFile::open(), CalvinToTextFile::open(), affx::TsvFile::open(), affxchp::CCHPFileData::Open(), affymetrix_calvin_io::TextFileWriter::OpenFile(), affymetrix_calvin_io::GenericFileReader::OpenFile(), affymetrix_calvin_io::GenericFileWriter::OpenFileOStream(), affymetrix_calvin_io::GenericData::OpenFStream(), affymetrix_calvin_io::AuditFileReader::Read(), AffxByteArray::readFile(), affymetrix_calvin_io::TextFileReader::ReadFile(), touch(), and affx::TsvFile::writeOpen().
int Fs::aptOpen (const std::string & pathname, int flags, int mode) [static]
Definition at line 1449 of file Fs.cpp.
References UncW().
void Fs::aptOpen (std::fstream & fs, const std::string & filename, std::ios_base::openmode iomode = std::ios_base::in | std::ios_base::out) [static]
Definition at line 1408 of file Fs.cpp.
References UncW().
void Fs::aptOpen (std::ofstream & ofs, const std::string & filename, std::ios_base::openmode iomode = std::ios_base::out|std::ios_base::binary) [static]
Definition at line 1418 of file Fs.cpp.
References UncW().
void Fs::aptOpen (std::ifstream & ifs, const std::string & filename, std::ios_base::openmode iomode = std::ios_base::in) [static]
Definition at line 1428 of file Fs.cpp.
References UncW().
std::string Fs::basename (const std::string & path) [static]
like the unix function of the same name.
Parameters:
path
Returns:
the basename of the path (abc/def/foo.bar => foo.bar)
Definition at line 386 of file Fs.cpp.
References FS_PATHSEP, and normalizePath().
Referenced by basename(), changeDirAndExt(), extname(), main(), MatrixCheck::MatrixCheck(), MixedFileCheck::MixedFileCheck(), TableFile::open(), CalvinChpCheck::ParameterNameValueTypeMostlySame(), PgOptions::setOptionsFromXMLFile(), ChpCheck::tagValuePairMostlySame(), and TextFileCheck::TextFileCheck().
std::vector< std::string > Fs::basename (const std::vector< std::string > & paths) [static]
Apply basename to a vector.
Parameters:
paths
Returns:
new vector of basenames.
Definition at line 410 of file Fs.cpp.
References basename().
void Fs::carefulClose (std::ofstream & out) [static]
Close an output stream making sure that it is ok before doing so.
Parameters:
out - stream to be closed.
Definition at line 1519 of file Fs.cpp.
References APT_ERR_ABORT.
void Fs::carefulClose (std::fstream & out) [static]
Close an output stream making sure that it is ok before doing so.
Parameters:
out - stream to be closed.
Definition at line 1533 of file Fs.cpp.
References APT_ERR_ABORT.
std::vector< std::string > Fs::changeDirAndExt (const std::string & new_dir, const std::vector< std::string > & paths, const std::string & new_ext) [static]
replace the dir and ext for all these filenames For example a vector of chip files for output. vec[0]="abc/foo.cel" => "outputdir/foo.chp" vec[1]="def/bar.cel" => "outputdir/bar.chp" vec[2]="def/baz" => "outputdir/baz.chp"
Definition at line 601 of file Fs.cpp.
References basename(), join(), and noextname1().
AptErr_t Fs::chmodBasic (const std::string & path, int mode, bool abortOnErr = true) [static]
Change the mode of a dir or file. This is chmodBasic because on Windows only the write bit for the user can be set. There is no notion of group and other. Files are always readable.
Parameters:
path
mode
abortOnErr
Returns:
Definition at line 986 of file Fs.cpp.
References APT_ERR, clearErr(), FS_ERRNO_STR, POSIX_CHMOD, setErr(), and UncW().
Referenced by FsPath::chmod().
AptErr_t Fs::clearErr () [static]
Clears the error num and message.
Returns:
always APT_OK
Definition at line 220 of file Fs.cpp.
References APT_OK, m_err_msg, and m_err_num.
Referenced by chmodBasic(), convertToUncPathInPlace(), dirExists(), ensureWriteableDirPath(), exists(), fileExists(), Fs__stat(), listDir(), mkdir(), mkdirPath(), rm(), rm_rf(), rmdir(), rmdirPath(), rmIfExists(), setErrFromErrno(), splitPath(), and touch().
std::string Fs::convertCommandToUnc (const std::string & cmd) [static]
convert only the first component of the command to unc. return the command string.
Definition at line 696 of file Fs.cpp.
References convertToUncPath().
std::string Fs::convertToUncPath (const std::string & path, int uncshortlen) [static]
Definition at line 621 of file Fs.cpp.
References convertToUncPathInPlace(), and unixifyPathInPlace().
std::string Fs::convertToUncPath (const std::string & path) [static]
Definition at line 617 of file Fs.cpp.
References FS_UNC_SHORTLEN.
Referenced by MixedFileCheck::check(), MatrixCheck::check(), CalvinChpCheck::check(), ChpCheck::checkFilePair(), convertCommandToUnc(), convertToUncPathW(), Calvin::equivalent(), Util::matrixDifferences(), affx::md5sum::ofFile(), TableFile::open(), SQLiteDatabase::open(), CalvinToText::run(), and Unc().
AptErr_t Fs::convertToUncPathInPlace (std::string & path) [static]
Definition at line 631 of file Fs.cpp.
References FS_UNC_SHORTLEN.
Referenced by FsPath::asUncPath(), and convertToUncPath().
AptErr_t Fs::convertToUncPathInPlace (std::string & path, int uncshortlen) [static]
Definition at line 635 of file Fs.cpp.
References APT_ERR_ABORT, APT_OK, clearErr(), normalizePathInPlace(), Util::toString(), and Util::toWString().
static std::wstring Fs::convertToUncPathW (const std::string & path, int uncshortlen) [inline, static]
Definition at line 272 of file Fs.h.
References convertToUncPath(), and Util::toWString().
static std::wstring Fs::convertToUncPathW (const std::string & path) [inline, static]
Definition at line 270 of file Fs.h.
References convertToUncPath(), and Util::toWString().
Referenced by _uncheckedFileRename(), affymetrix_calvin_io::GenericData::MapFile(), and UncW().
bool Fs::dirExists (const std::string & path) [static]
Definition at line 733 of file Fs.cpp.
References APT_ERR, clearErr(), Fs__stat(), setErr(), and setErrFromErrno().
Referenced by TmpFileFactory::genDirname(), BaseEngine::makeTempDir(), mkdirPath(), rm_rf(), FsPath::rmdir(), rmdir(), and rmdirPath().
std::string Fs::dirname (const std::string & path) [static]
just the dirname (will return "." or "/" as well.)
Parameters:
path
Returns:
Definition at line 421 of file Fs.cpp.
References APT_ERR_ABORT, FS_PATHSEP, and unixifyPathInPlace().
Referenced by SQLiteDatabase::error().
AptErr_t Fs::ensureWriteableDirPath (const std::string & path, bool abortOnErr = true) [static]
This will make the dir if it isnt there. If it is there, that is ok as long as it is writeable. This will make a path like mkdirPath.
Parameters:
path
abortOnErr
Returns:
Definition at line 1119 of file Fs.cpp.
References APT_ERR, clearErr(), isWriteableDir(), mkdirPath(), and setErr().
Referenced by BaseEngine::makeTempDir().
bool Fs::exists (const std::string & path) [static]
Definition at line 719 of file Fs.cpp.
References clearErr(), Fs__stat(), and setErrFromErrno().
std::string Fs::extname (const std::string & path) [static]
return the stuff after the "." including the "." ("foo.bar" => ".bar")
Definition at line 449 of file Fs.cpp.
References basename(), and FS_EXTSEP.
bool Fs::fileCopy (const std::string & in, const std::string & out, bool throwOnError = true) [static]
Return true on success. False otherwise
Parameters:
in - file to copy
out - name of the new file
Todo:
there is probably a better way to copy files and check for errors
Definition at line 1549 of file Fs.cpp.
References APT_ERR_ABORT, and aptOpen().
bool Fs::fileExists (const std::string & path) [static]
Definition at line 752 of file Fs.cpp.
References APT_ERR, clearErr(), Fs__stat(), setErr(), and setErrFromErrno().
Referenced by findLibFile(), TmpFileFactory::genFilename_basic(), affx::TsvFile::getLineCountInFile(), isWriteableDir(), affymetrix_calvin_utilities::FileUtils::ListFiles(), affymetrix_calvin_io::DataSet::MapDataPosix(), affymetrix_calvin_utilities::FileUtils::RemovePath(), affx::TsvFile::replaceCharInFile(), FsPath::rm(), rm_rf(), and rmIfExists().
bool Fs::fileRename (const std::string & in, const std::string & out, bool throwOnError = true) [static]
Return true on success. False otherwise
Parameters:
in - file to copy
out - name of the new file
Return true on success. False otherwise
Parameters:
in - file to move
out - name of the new file
Definition at line 1609 of file Fs.cpp.
References _uncheckedFileRename(), and APT_ERR_ABORT.
Referenced by affx::TsvFile::replaceCharInFile().
int64_t Fs::fileSize (const std::string & path, bool abortOnErr = true) [static]
The size of the file.
Parameters:
path The path to
abortOnErr If true, call Err::errAbort when a error occurs.
Returns:
the size of the file or -1
Definition at line 963 of file Fs.cpp.
References APT_OK, getErrMsg(), getErrNum(), and setErr().
Referenced by affymetrix_fusion_io::FusionCELData::GetFileSize(), affymetrix_calvin_io::DataSet::MapDataPosix(), CalvinToText::OutputFileHeaderParameters(), and AffxByteArray::readFile().
int64_t Fs::fileSize (const std::string & path, AptErr_t & errnum) [static]
Definition at line 973 of file Fs.cpp.
References APT_OK, and Fs__stat().
std::string Fs::findLibFile (const std::string & fileName, const std::string & searchPath = "") [static]
Util carry overs. These need to be updated with abortOnError.
Search the affy library file path for the actual file name to open
Parameters:
fileName - the name of the file to find
searchPath - alternative search path
Definition at line 1460 of file Fs.cpp.
References Util::chopString(), fileExists(), and join().
Referenced by BaseEngine::setLibFileOpt().
std::string Fs::getErrMsg () [static]
The current error string (Should include the pathname.)
Definition at line 216 of file Fs.cpp.
References m_err_msg.
Referenced by fileSize(), and FsPath::setErrFromFs().
AptErr_t Fs::getErrNum () [static]
The current error number.
Definition at line 212 of file Fs.cpp.
References m_err_num.
Referenced by fileSize(), and FsPath::setErrFromFs().
static int64_t Fs::getFreeDiskSpace (const std::string & path, bool abortOnErr = true) [static]
Parameters:
path
abortOnErr
Returns:
bool Fs::hasTrailingSlash (const std::string & path_in) [static]
Definition at line 359 of file Fs.cpp.
References FS_PATHSEP.
Referenced by addTrailingSlash(), and trimTrailingSlash().
bool Fs::isBinaryFile (const std::string & path) [static]
Definition at line 919 of file Fs.cpp.
References aptOpen().
Referenced by affx::TsvFile::open().
bool Fs::isCalvinFile (const std::string & path) [static]
Definition at line 914 of file Fs.cpp.
References file_starts_with().
Referenced by affx::TsvFile::open().
bool Fs::isHdf5File (const std::string & path) [static]
Definition at line 909 of file Fs.cpp.
References file_starts_with().
Referenced by affx::TsvFile::open().
bool Fs::isReadable (const std::string & path) [static]
Definition at line 771 of file Fs.cpp.
Referenced by MatrixCheck::check(), and test_write_data().
bool Fs::isReadable (const std::string & path, AptErr_t & rv) [static]
Definition at line 776 of file Fs.cpp.
References APT_OK, Fs__isreadable(), Fs__stat(), and setErrFromErrno().
bool Fs::isReadableDir (const std::string & path, AptErr_t & rv) [static]
Definition at line 812 of file Fs.cpp.
References APT_OK, Fs__isreadable(), Fs__stat(), and setErrFromErrno().
bool Fs::isReadableDir (const std::string & path) [static]
Definition at line 807 of file Fs.cpp.
static bool Fs::isSameVolume (const std::string & path1, const std::string & path2, AptErr_t & rv, bool abortOnErr = true) [static]
Do these two paths refer to the same volume?
Parameters:
path1
path2
rv
abortOnErr
Returns:
True if they are on the same volume.
bool Fs::isWriteable (const std::string & path) [static]
Definition at line 802 of file Fs.cpp.
bool Fs::isWriteable (const std::string & path, AptErr_t & rv) [static]
Definition at line 789 of file Fs.cpp.
References APT_OK, Fs__iswriteable(), Fs__stat(), and setErrFromErrno().
bool Fs::isWriteableDir (const std::string & path) [static]
Definition at line 828 of file Fs.cpp.
Referenced by ensureWriteableDirPath(), SQLiteDatabase::error(), TmpFileFactory::genDirname(), BaseEngine::makeTempDir(), and BaseEngine::openStandardLog().
bool Fs::isWriteableDir (const std::string & path, AptErr_t & rv) [static]
Definition at line 833 of file Fs.cpp.
References APT_ERR_ABORT, fileExists(), Fs__iswriteable(), Fs__stat(), FS_QUOTE_PATH, join(), rm(), setErrFromErrno(), and touch().
std::string Fs::join (const std::string & arg1, const std::string & arg2, const std::string & arg3) [static]
Todo:
could be changed not to norm
Definition at line 333 of file Fs.cpp.
References join().
std::string Fs::join (const std::string & arg1, const std::string & arg2, const std::string & arg3, const std::string & arg4) [static]
Definition at line 340 of file Fs.cpp.
References join().
std::string Fs::join (std::vector< std::string > & args) [static]
Definition at line 348 of file Fs.cpp.
References join().
std::string Fs::join (const std::string & arg1, const std::string & arg2) [static]
join strings with the path sep. while we would want people to keep the path with FsPath, we should face up to that there will be string pasting going on and make it less ugly. Fs::join("foo","bar") => "foo/bar"
Definition at line 317 of file Fs.cpp.
References normalizePath().
Referenced by changeDirAndExt(), findLibFile(), TmpFileFactory::genFilename_basic(), isWriteableDir(), join(), listDir(), mkdirPath(), BaseEngine::openStandardLog(), rm_rf(), and rmdirPath().
AptErr_t Fs::listDir (const std::string & path, std::vector< std::string > & names, bool abortOnErr = true) [static]
Parameters:
path
names
abortOnErr
Returns:
Definition at line 1010 of file Fs.cpp.
References APT_ERR, APT_ERR_NOTEXISTS, clearErr(), FS_ERRNO_STR, join(), setErr(), Util::toString(), and UncW().
Referenced by rm_rf().
AptErr_t Fs::mkdir (const std::string & path, bool abortOnErr = true) [static]
Make one directory.
Parameters:
path
abortOnErr
Returns:
Definition at line 1072 of file Fs.cpp.
References clearErr(), POSIX_MKDIR, setErrFromErrno(), and UncW().
Referenced by mkdirPath().
AptErr_t Fs::mkdirPath (const std::string & path, bool abortOnErr = true) [static]
make all path of directories
Parameters:
path
abortOnErr
Returns:
Definition at line 1090 of file Fs.cpp.
References APT_ERR, APT_OK, clearErr(), dirExists(), FS_QUOTE_PATH, join(), mkdir(), setErr(), and splitPath().
Referenced by ensureWriteableDirPath(), TmpFileFactory::genDirname(), and BaseEngine::openStandardLog().
void Fs::mustOpenToWrite (std::ofstream & out, const std::string & fileName) [static]
Open an ofstream for writing to. Abort if can't open for some reason.
Parameters:
out - stream to be opened.
fileName - name of file to be opened.
Definition at line 1504 of file Fs.cpp.
References APT_ERR_ABORT, aptOpen(), and FS_QUOTE_PATH.
Referenced by dumpPgf::dumpPgf(), main(), BaseEngine::openStandardLog(), and tsvJoin::tsvJoin().
std::string Fs::noextname (const std::string & path) [static]
chop off ALL the exts. ("path/foo.a.b.c" => "path/foo")
Definition at line 466 of file Fs.cpp.
References FS_EXTSEP, FS_PATHSEP, and unixifyPathInPlace().
std::string Fs::noextname1 (const std::string & path) [static]
chop off ONE of the exts. ("path/foo.a.b.c" => "path/foo.a.b")
Definition at line 488 of file Fs.cpp.
References FS_EXTSEP, FS_PATHSEP, and unixifyPathInPlace().
Referenced by changeDirAndExt().
std::string Fs::noextnameN (const std::string & path, int cnt) [static]
chop off N of the exts ("path/foo.a.b.c",2 => "path/foo.a")
Definition at line 509 of file Fs.cpp.
References FS_EXTSEP, FS_PATHSEP, and unixifyPathInPlace().
std::string Fs::normalizePath (const std::string & path) [static]
clean up the path.
Parameters:
path
Returns:
Definition at line 280 of file Fs.cpp.
References normalizePathInPlace().
Referenced by basename(), CelCheck::checkFilePair(), join(), and splitPath().
AptErr_t Fs::normalizePathInPlace (std::string & path) [static]
Definition at line 276 of file Fs.cpp.
References unixifyPathInPlace().
Referenced by convertToUncPathInPlace(), and normalizePath().
std::string Fs::osPathSep (const std::string & path = "") [static]
Get the path seperator for the OS or replace path separators for input string.
Returns:
Could be "\" , "/" or the translated string if one is passed in.
Definition at line 255 of file Fs.cpp.
References unixifyPath(), and windowifyPath().
Referenced by Util::chompLastIfSep().
std::string Fs::pathSep () [static]
Get the internal path seperator.
Returns:
Always "/"
Definition at line 251 of file Fs.cpp.
AptErr_t Fs::rm (const std::string & path, bool abortOnErr = true) [static]
An error if it doesnt exist.
Definition at line 1199 of file Fs.cpp.
References clearErr(), POSIX_UNLINK, setErrFromErrno(), and UncW().
Referenced by TmpFileFactory::cleanUp(), isWriteableDir(), affx::TsvFile::replaceCharInFile(), rm_rf(), rmIfExists(), and tsv_util_paste().
AptErr_t Fs::rm_rf (const std::string & path, bool abortOnErr = true) [static]
Parameters:
path
abortOnErr
Returns:
Definition at line 1281 of file Fs.cpp.
References APT_ERR, APT_ERR_NOTEXISTS, clearErr(), dirExists(), fileExists(), FS_QUOTE_PATH, join(), listDir(), rm(), rmdir(), and setErr().
AptErr_t Fs::rmdir (const std::string & path, bool abortOnErr = true) [static]
Remove a directory.
Parameters:
path
abortOnErr
Returns:
Todo:
handle errs
Definition at line 1225 of file Fs.cpp.
References APT_ERR, APT_ERR_NOTEXISTS, APT_OK, clearErr(), dirExists(), FS_ERRNO_STR, setErr(), and UncW().
Referenced by TmpFileFactory::cleanUp(), BaseEngine::removeTempDir(), rm_rf(), and rmdirPath().
AptErr_t Fs::rmdirPath (const std::string & path, bool abortOnErr = true) [static]
Parameters:
path
abortOnErr
Returns:
Definition at line 1254 of file Fs.cpp.
References APT_ERR, clearErr(), dirExists(), join(), rmdir(), setErr(), and splitPath().
AptErr_t Fs::rmIfExists (const std::string & path, bool abortOnErr = true) [static]
An error if the rm fails.
Definition at line 1215 of file Fs.cpp.
References clearErr(), fileExists(), and rm().
AptErr_t Fs::setErr (AptErr_t err_num, const std::string & err_msg, bool abortOnErr) [static]
Sets err num and message. Possibly calls Err::errAbort.
Parameters:
err_num
err_msg
abortOnErr When true, an error calls Err::errAbort.
Returns:
An error code.
Definition at line 206 of file Fs.cpp.
References m_err_msg, and m_err_num.
Referenced by chmodBasic(), dirExists(), ensureWriteableDirPath(), fileExists(), fileSize(), Fs__stat(), listDir(), mkdirPath(), rm_rf(), rmdir(), rmdirPath(), setErrFromErrno(), and touch().
AptErr_t Fs::setErrFromErrno (const std::string & path, bool abortOnErr) [static]
translate
Parameters:
path
abortOnErr
Returns:
Definition at line 227 of file Fs.cpp.
Referenced by dirExists(), exists(), fileExists(), isReadable(), isReadableDir(), isWriteable(), isWriteableDir(), mkdir(), and rm().
AptErr_t Fs::setErrFromErrno (const std::string & path, int sys_errno, bool abortOnErr) [static]
translate
Parameters:
path
sys_errno
abortOnErr
Returns:
Definition at line 232 of file Fs.cpp.
References APT_ERR, APT_ERR_ACCESS, APT_ERR_EXISTS, clearErr(), FS_QUOTE_PATH, and setErr().
void Fs::splitPath (const std::string & path, std::string & drive, std::vector< std::string > & parts) [static]
Definition at line 549 of file Fs.cpp.
References clearErr(), FS_PATHSEP, and normalizePath().
Referenced by FsPath::getDirNames(), mkdirPath(), and rmdirPath().
AptErr_t Fs::touch (const std::string & path, bool abortOnErr = true) [static]
touchs a file (creates a zero length file if not exists.)
Parameters:
path
abortOnErr
Returns:
Todo:
take an atime to adjust the file access to.
Definition at line 1134 of file Fs.cpp.
References APT_ERR, aptOpen(), clearErr(), FS_QUOTE_PATH, and setErr().
Referenced by isWriteableDir(), and affx::TsvFile::replaceCharInFile().
std::string Fs::trimTrailingSlash (const std::string & path_in) [static]
Definition at line 375 of file Fs.cpp.
References FS_PATHSEP, and hasTrailingSlash().
Referenced by FsPath::getDirName(), and FsPath::popDir().
static std::string Fs::Unc (const std::string & path) [inline, static]
Short name for convertToUncPath.
Definition at line 275 of file Fs.h.
References convertToUncPath().
Referenced by Util::addPrefixSuffix().
static std::wstring Fs::UncW (const std::string & path) [inline, static]
Definition at line 276 of file Fs.h.
References convertToUncPathW().
Referenced by aptOpen(), chmodBasic(), Fs__stat(), listDir(), mkdir(), rm(), and rmdir().
std::string Fs::unixifyPath (const std::string & path) [static]
turn the path into a normal (unix) path string
Parameters:
path
Returns:
Definition at line 294 of file Fs.cpp.
References unixifyPathInPlace().
Referenced by osPathSep().
AptErr_t Fs::unixifyPathInPlace (std::string & path) [static]
Definition at line 288 of file Fs.cpp.
References APT_OK.
Referenced by convertToUncPath(), dirname(), noextname(), noextname1(), noextnameN(), normalizePathInPlace(), FsPath::setDirName(), FsPath::setPath(), and unixifyPath().
std::string Fs::windowifyPath (const std::string & path) [static]
turn the path into a windows path string
Parameters:
path
Returns:
Definition at line 308 of file Fs.cpp.
References windowifyPathInPlace().
Referenced by osPathSep().
AptErr_t Fs::windowifyPathInPlace (std::string & path) [static]
do what needs to be done to windowify a string.
Definition at line 302 of file Fs.cpp.
References APT_OK.
Referenced by windowifyPath().
Member Data Documentation
std::string Fs::m_err_msg [static]
The error message of the last error.
Definition at line 144 of file Fs.h.
Referenced by clearErr(), getErrMsg(), and setErr().
AptErr_t Fs::m_err_num [static]
The error code of the last error.
Definition at line 141 of file Fs.h.
Referenced by clearErr(), getErrNum(), and setErr().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/Fs.h
C:/f112/affy/sdk/util/Fs.cpp