Affymetrix Fusion SDK: affymetrix_calvin_io::CelFileData Class Reference
affymetrix_calvin_io::CelFileData Class Reference
#include <CELData.h>
Public Member Functions
CelFileData ()
CelFileData (const std::string &filename)
~CelFileData ()
void Clear ()
bool Exists ()
void SetActiveChannel (const std::wstring &channel)
void SetFilename (const std::string &p)
std::string GetFilename () const
void SetIntensityCount (int32_t ln)
void SetStdDevCount (int32_t ln)
void SetPixelCount (int32_t ln)
void SetOutlierCount (int32_t ln)
void SetMaskCount (int32_t ln)
FileHeader * GetFileHeader ()
u_int8_t GetVersion ()
void SetArrayType (const std::wstring &value)
std::wstring GetArrayType ()
void SetMasterFileName (const std::wstring &value)
std::wstring GetMasterFileName ()
void SetLibraryPackageName (const std::wstring &value)
std::wstring GetLibraryPackageName ()
void SetAlgorithmName (const std::wstring &value)
std::wstring GetAlgorithmName ()
void SetAlgorithmVersion (const std::wstring &value)
std::wstring GetAlgorithmVersion ()
void SetRows (int32_t value)
int32_t GetRows ()
void SetCols (int32_t value)
int32_t GetCols ()
int32_t GetNumCells ()
void GetAlgorithmParameters (ParameterNameValueTypeVector &algParams)
bool FindAlgorithmParameter (const std::wstring &name, ParameterNameValueType &param)
void AddAlgorithmParameter (ParameterNameValueType &nvt)
void GetData (int32_t cellIdx, float &intensity, float &stdev, int16_t &numPixels, bool &outlier, bool &masked)
bool HasStdev ()
bool HasNumPixels ()
float GetIntensity (int index)
bool GetIntensities (int32_t cellIdxStart, int32_t count, FloatVector &values)
bool GetStdev (int32_t cellIdxStart, int32_t count, FloatVector &values)
bool GetNumPixels (int32_t cellIdxStart, int32_t count, Int16Vector &values)
bool GetOutliers (int32_t cellIdxStart, int32_t count, BoolVector &values)
bool GetMasked (int32_t cellIdxStart, int32_t count, BoolVector &values)
void GetOutlierCoords (XYCoordVector &coords)
void GetMaskedCoords (XYCoordVector &coords)
GenericData & GetGenericData ()
std::wstring GetDatHeader ()
void ComputeXY (int32_t cellIdx, int16_t &x, int16_t &y)
ParameterNameValueTypeList GetDataSetParameters (const std::wstring &setName)
bool IsMultiColor ()
WStringVector GetChannels ()
Protected Member Functions
void CloseDataSets ()
void ResetMaskAndOutliers ()
Private Member Functions
void SetFileCreationTime (const std::wstring &f)
std::wstring GetFileCreationTime () const
void InsertDataSetHeader (const DataSetHeader &hdr)
void UpdateDataSetRowCount (const DataSetHeader &hdr)
void SetVersion (u_int8_t value)
void PrepareIntensityPlane ()
void PrepareStdevPlane ()
void PrepareNumPixelPlane ()
void PrepareOutlierPlane ()
void PrepareMaskedPlane ()
void PrepareAllPlanes ()
int32_t GetInt32FromGenericHdrParameterList (const std::wstring &name)
void SetInt32ToGenericHdrParameterList (const std::wstring &name, int32_t value)
std::wstring GetWStringFromGenericHdr (const std::wstring &name)
void SetWStringToGenericHdr (const std::wstring &name, const std::wstring value, int32_t reserve=-1)
bool IsOutlier (int32_t cellIdx)
bool IsMasked (int32_t cellIdx)
DataSetHeader * FindDataSetHeader (const std::wstring &name)
Private Attributes
GenericData genericData
bool setIntensityMetaData
bool setStdDevMetaData
bool setPixelMetaData
bool setOutlierMetaData
bool setMaskMetaData
int32_t intensityColumnType
std::wstring activeChannel
DataSet * dpInten
DataSet * dpStdev
DataSet * dpPixels
bool outlierPlaneRead
std::set< XYCoord > outliers
bool maskPlaneRead
std::set< XYCoord > masked
int32_t cachedRows
int32_t cachedCols
Friends
class CelFileReader
class CelFileWriter
class MultiChannelCelFileWriter
Detailed Description
This is the container class for CEL data.
Definition at line 65 of file CELData.h.
Constructor & Destructor Documentation
CelFileData::CelFileData ()
Default Constructor
Definition at line 39 of file CELData.cpp.
CelFileData::CelFileData (const std::string & filename)
Constructor
Parameters:
filename Name of the cel file.
Definition at line 50 of file CELData.cpp.
References CelDataGroupName, and INTENSITY_DATA_TYPE.
CelFileData::~CelFileData ()
Destructor
Definition at line 66 of file CELData.cpp.
Member Function Documentation
void affymetrix_calvin_io::CelFileData::AddAlgorithmParameter (ParameterNameValueType & nvt)
Add an algorithm parameter. The algorithm parameter prefix will be added by the method.
Parameters:
nvt Algorithm parameter to add to the list.
void CelFileData::Clear ()
Clear the object members
Definition at line 74 of file CELData.cpp.
References CelDataGroupName.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::Clear(), and affymetrix_calvin_io::CelFileReader::Read().
void CelFileData::CloseDataSets () [protected]
Definition at line 90 of file CELData.cpp.
void CelFileData::ComputeXY (int32_t cellIdx, int16_t & x, int16_t & y)
Determine the x-y coordinate given a cell index.
Parameters:
cellIdx Cell index
x Cell x-coordinate
y Cell y-coordinate
Definition at line 899 of file CELData.cpp.
bool CelFileData::Exists ()
Check if the file exists
Definition at line 130 of file CELData.cpp.
bool CelFileData::FindAlgorithmParameter (const std::wstring & name, ParameterNameValueType & param)
Return an algorithm parameter given a name.
Parameters:
name Name of the parameter to find.
param The found parameter.
Returns:
True if the parameter was found.
Definition at line 1005 of file CELData.cpp.
References ALGORITHM_PARAM_NAME_PREFIX, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::GetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
DataSetHeader * CelFileData::FindDataSetHeader (const std::wstring & name) [private]
Find a DataSetHeader by name.
Parameters:
name DataSetHeader name
Returns:
Pointer to a DataSetHeader with name parameter, otherwise 0
Definition at line 957 of file CELData.cpp.
std::wstring CelFileData::GetAlgorithmName ()
Get the name of the algorithm used to generate the results.
Returns:
Algorithm name
Definition at line 717 of file CELData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetAlg().
void affymetrix_calvin_io::CelFileData::GetAlgorithmParameters (ParameterNameValueTypeVector & algParams)
Return the algorithm parameters. The algorithm parameter prefix is removed from the name.
Parameters:
algParams Vector with algorithm parameters.
std::wstring CelFileData::GetAlgorithmVersion ()
Definition at line 733 of file CELData.cpp.
References ALG_VERSION_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetAlgVer().
std::wstring CelFileData::GetArrayType ()
Get the array type
Returns:
array type name
Definition at line 669 of file CELData.cpp.
References ARRAY_TYPE_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetChipType().
WStringVector CelFileData::GetChannels ()
Returns a list of the channel (ie data group) names
Returns:
list of channel names
Definition at line 771 of file CELData.cpp.
References CelDataGroupName, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_io::GenericDataHeader::FindParent(), MULTI_SCAN_ACQUISITION_DATA_TYPE, and affymetrix_calvin_parameter::ParameterNameValueType::ToString().
int32_t CelFileData::GetCols ()
Get the number of columns of cells on the array.
Returns:
Number of columns of cells.
Definition at line 811 of file CELData.cpp.
References CEL_COLS_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetCols().
void CelFileData::GetData (int32_t cellIdx, float & intensity, float & stdev, int16_t & numPixels, bool & outlier, bool & masked)
Get the cell intensity, standard deviation, number of pixels, outlier flag and mask flag.
Parameters:
cellIdx Index of the cell.
intensity The intensity of the cell.
stdev The standard deviation of the cell.
numPixels The number of pixels in the cell.
outlier The outlier flag of the cell.
masked The masked flag of the cell.
Definition at line 426 of file CELData.cpp.
References affymetrix_calvin_io::FloatColType.
ParameterNameValueTypeList CelFileData::GetDataSetParameters (const std::wstring & setName)
Returns the list of parameters associated with a data set.
Parameters:
setName The data set name
Returns:
The list of parameters
Definition at line 1025 of file CELData.cpp.
References affymetrix_calvin_io::DataSet::DataSet().
std::wstring CelFileData::GetDatHeader ()
Return a wstring for DatHeader
Returns:
DatHeader
Definition at line 907 of file CELData.cpp.
References DAT_HEADER_PARAM_NAME, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), affymetrix_calvin_io::GenericDataHeader::FindParent(), FormatString2, affymetrix_calvin_parameter::ParameterNameValueType::GetParameterType(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueText(), affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt16(), MAX_PIXEL_INTENSITY_PARAM_NAME, MIN_PIXEL_INTENSITY_PARAM_NAME, MULTI_SCAN_ACQUISITION_DATA_TYPE, and PARTIAL_DAT_HEADER_PARAM_NAME.
std::wstring affymetrix_calvin_io::CelFileData::GetFileCreationTime () const [private]
FileHeader* affymetrix_calvin_io::CelFileData::GetFileHeader () [inline]
Definition at line 148 of file CELData.h.
References genericData, and affymetrix_calvin_io::GenericData::Header().
Referenced by affymetrix_calvin_io::CelFileWriter::CelFileWriter().
std::string CelFileData::GetFilename () const
Get the file name
Returns:
file name
Definition at line 154 of file CELData.cpp.
Referenced by affymetrix_calvin_io::CelFileReader::Read().
GenericData& affymetrix_calvin_io::CelFileData::GetGenericData () [inline]
Return a reference to the generic layer object
Returns:
Generic layer object
Definition at line 326 of file CELData.h.
References genericData.
Referenced by affymetrix_calvin_io::CelFileReader::Read().
int32_t CelFileData::GetInt32FromGenericHdrParameterList (const std::wstring & name) [private]
Read an int32_t value from the GenericDataHeader parameter list.
Parameters:
name Name of the parameter to read
Returns:
int32_t value of the named parameter
Definition at line 822 of file CELData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueInt32().
bool CelFileData::GetIntensities (int32_t cellIdxStart, int32_t count, FloatVector & values)
Get the intensities for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first intensity to retrieve.
count Number of intensities to retrieve.
values Retrieved cell intensities.
Returns:
True if all intensities were retrieved.
Definition at line 498 of file CELData.cpp.
References affymetrix_calvin_io::FloatColType.
float CelFileData::GetIntensity (int index)
Get the intensity for a cell index.
Parameters:
cell index of the intensity to retrieve.
Returns:
float of a particular intensity value.
Definition at line 486 of file CELData.cpp.
std::wstring CelFileData::GetLibraryPackageName ()
Get the library package
Returns:
library package name
Definition at line 701 of file CELData.cpp.
References LIBRARY_PACKAGE_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetLibraryPackageName().
bool CelFileData::GetMasked (int32_t cellIdxStart, int32_t count, BoolVector & values)
Get the mask flags for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first mask flag to retrieve.
count Number of cell mask flags to retrieve.
values Retrieved cell mask flags
Returns:
True if all mask flags were retrieved.
Definition at line 568 of file CELData.cpp.
void CelFileData::GetMaskedCoords (XYCoordVector & coords)
Get the coordinates of all masked cells (i.e. mask flag is true).
Parameters:
coords Cell coordinates.
Definition at line 599 of file CELData.cpp.
std::wstring CelFileData::GetMasterFileName ()
Get the master file
Returns:
master file name
Definition at line 685 of file CELData.cpp.
References MASTER_FILE_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetMasterFileName().
int32_t CelFileData::GetNumCells ()
Return the number of cells on the array. This is the number of the intensity data elements and is == GetRows() * GetCols() Stdev, NumPixels, Outlier and Masked data is optional, but if present they will have GetNumCells elements.
Returns:
Number of cells in the array.
Definition at line 276 of file CELData.cpp.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetNumCells().
bool CelFileData::GetNumPixels (int32_t cellIdxStart, int32_t count, Int16Vector & values)
Get the number of pixels for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first pixel count to retrieve.
count Number of cell pixels to retrieve.
values Retrieved cell pixel counts
Returns:
True if all pixel count (number of pixels) were retrieved.
Definition at line 536 of file CELData.cpp.
void CelFileData::GetOutlierCoords (XYCoordVector & coords)
Get the coordinates of all outlier cells (i.e. outlier flag is true).
Parameters:
coords Cell coordinates.
Definition at line 586 of file CELData.cpp.
bool CelFileData::GetOutliers (int32_t cellIdxStart, int32_t count, BoolVector & values)
Get the outlier flags for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first outlier flag to retrieve.
count Number of cell outlier flags to retrieve.
values Retrieved cell outlier flags
Returns:
True if all outlier flags were retrieved.
Definition at line 550 of file CELData.cpp.
int32_t CelFileData::GetRows ()
Get the number of rows of cells on the array.
Returns:
Number of rows of cells.
Definition at line 750 of file CELData.cpp.
References CEL_ROWS_PARAM_NAME.
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetRows().
bool CelFileData::GetStdev (int32_t cellIdxStart, int32_t count, FloatVector & values)
Get the standard deviations for a range of cell indexes.
Parameters:
cellIdxStart Cell index of the first standard deviation to retrieve.
count Number of cell standard deviations to retrieve.
values Retrieved cell standard deviations.
Returns:
True if all standard deviations were retrieved.
Definition at line 522 of file CELData.cpp.
u_int8_t CelFileData::GetVersion ()
Get the version of the CEL file
Returns:
CEL file version
Definition at line 646 of file CELData.cpp.
References FILE_VERSION_PARAM_NAME, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueUInt8().
Referenced by affymetrix_fusion_io::CalvinCELDataAdapter::GetVersion().
std::wstring CelFileData::GetWStringFromGenericHdr (const std::wstring & name) [private]
Read an wstring value from the GenericDataHeader parameter list.
Parameters:
name Name of the parameter to read
Returns:
wstring value of the named parameter
Definition at line 849 of file CELData.cpp.
References affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), and affymetrix_calvin_parameter::ParameterNameValueType::GetValueText().
bool CelFileData::HasNumPixels ()
Indicates whether there are number of pixel values.
Returns:
True if there are number of pixels values.
Definition at line 623 of file CELData.cpp.
References CelPixelLabel, and affymetrix_calvin_io::DataSetHeader::GetRowCnt().
bool CelFileData::HasStdev ()
Indicates whether there are standard deviation values.
Returns:
True if there are standard deviation values.
Definition at line 612 of file CELData.cpp.
References CelStdDevLabel, and affymetrix_calvin_io::DataSetHeader::GetRowCnt().
void CelFileData::InsertDataSetHeader (const DataSetHeader & hdr) [private]
Definition at line 267 of file CELData.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr().
bool CelFileData::IsMasked (int32_t cellIdx) [private]
Check if the cell is masked (mask flag is true)
Parameters:
cellIdx cell index
Returns:
True if the cell mask flag is true
Definition at line 888 of file CELData.cpp.
bool CelFileData::IsMultiColor ()
Is this a multi-color CEL file?
Returns:
True if it is multi-color
Definition at line 766 of file CELData.cpp.
bool CelFileData::IsOutlier (int32_t cellIdx) [private]
Check if the cell is an outlier (outlier flag is true)
Parameters:
cellIdx Cell index
Returns:
True if the cell outlier flag is true
Definition at line 877 of file CELData.cpp.
void CelFileData::PrepareAllPlanes () [private]
Prepare to read all data
Definition at line 414 of file CELData.cpp.
void CelFileData::PrepareIntensityPlane () [private]
Prepare to read intensity data
Definition at line 296 of file CELData.cpp.
References CelIntensityLabel.
void CelFileData::PrepareMaskedPlane () [private]
Prepare to read the mask data
Definition at line 378 of file CELData.cpp.
References CelMaskLabel, affymetrix_calvin_io::DataSet::DataSet(), affymetrix_calvin_io::DataSet::Delete(), affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::Open(), and affymetrix_calvin_io::DataSet::Rows().
void CelFileData::PrepareNumPixelPlane () [private]
Prepare to read the number of pixel data
Definition at line 327 of file CELData.cpp.
References CelPixelLabel.
void CelFileData::PrepareOutlierPlane () [private]
Prepare to read the outlier data
Definition at line 342 of file CELData.cpp.
References CelOutlierLabel, affymetrix_calvin_io::DataSet::DataSet(), affymetrix_calvin_io::DataSet::Delete(), affymetrix_calvin_io::DataSet::GetData(), affymetrix_calvin_io::DataSet::Open(), and affymetrix_calvin_io::DataSet::Rows().
void CelFileData::PrepareStdevPlane () [private]
Prepare to read the standard deviation data
Definition at line 312 of file CELData.cpp.
References CelStdDevLabel.
void CelFileData::ResetMaskAndOutliers () [protected]
Definition at line 109 of file CELData.cpp.
void CelFileData::SetActiveChannel (const std::wstring & channel)
Sets the active channel for a multi-channel CEL file. Default is single channel.
Definition at line 117 of file CELData.cpp.
void CelFileData::SetAlgorithmName (const std::wstring & value)
Set name of the algorithm used to generate the results.
Parameters:
value algorithm name
Definition at line 709 of file CELData.cpp.
References ALGORITHM_NAME_PARAM_NAME.
void CelFileData::SetAlgorithmVersion (const std::wstring & value)
Set version of the algorithm used to generate the results.
Parameters:
value algorithm name
Definition at line 725 of file CELData.cpp.
References ALG_VERSION_PARAM_NAME.
void CelFileData::SetArrayType (const std::wstring & value)
Set the array type
Parameters:
value array type name
Definition at line 661 of file CELData.cpp.
References ARRAY_TYPE_MAX_LEN, and ARRAY_TYPE_PARAM_NAME.
void CelFileData::SetCols (int32_t value)
Set the number of columns of cells on the array.
Parameters:
value Number of columns of cells.
Definition at line 760 of file CELData.cpp.
References CEL_COLS_PARAM_NAME.
void affymetrix_calvin_io::CelFileData::SetFileCreationTime (const std::wstring & f) [private]
void CelFileData::SetFilename (const std::string & p)
Set the file name
Parameters:
p file name
Definition at line 146 of file CELData.cpp.
void CelFileData::SetInt32ToGenericHdrParameterList (const std::wstring & name, int32_t value) [private]
Set a int32_t value into the GenericDataHeader parameter list.
Parameters:
name of the parameter to set
value Int32_t value to set
Definition at line 837 of file CELData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueInt32().
void CelFileData::SetIntensityCount (int32_t ln)
Definition at line 159 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), CelIntensityLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CelFileData::SetLibraryPackageName (const std::wstring & value)
Set the library package
Parameters:
value library package name
Definition at line 693 of file CELData.cpp.
References ARRAY_TYPE_MAX_LEN, and LIBRARY_PACKAGE_PARAM_NAME.
void CelFileData::SetMaskCount (int32_t ln)
Definition at line 228 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddShortColumn(), CelMaskLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CelFileData::SetMasterFileName (const std::wstring & value)
Set the master file
Parameters:
value master file name
Definition at line 677 of file CELData.cpp.
References MASTER_FILE_PARAM_NAME.
void CelFileData::SetOutlierCount (int32_t ln)
Definition at line 210 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddShortColumn(), CelOutlierLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CelFileData::SetPixelCount (int32_t ln)
Definition at line 193 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddShortColumn(), CelPixelLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CelFileData::SetRows (int32_t value)
Set the number of rows of cells on the array.
Parameters:
value Number of rows of cells.
Definition at line 741 of file CELData.cpp.
References CEL_ROWS_PARAM_NAME.
void CelFileData::SetStdDevCount (int32_t ln)
Definition at line 176 of file CELData.cpp.
References affymetrix_calvin_io::DataSetHeader::AddFloatColumn(), CelStdDevLabel, affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
void CelFileData::SetVersion (u_int8_t value) [private]
Set the version of the CEL file. Used by the reader.
Parameters:
value CEL file version
Definition at line 634 of file CELData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), FILE_VERSION_PARAM_NAME, affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueUInt8().
Referenced by affymetrix_calvin_io::CelFileWriter::CelFileWriter().
void CelFileData::SetWStringToGenericHdr (const std::wstring & name, const std::wstring value, int32_t reserve = -1) [private]
Set a wstring value into the GenericDataHeader parameter list.
Parameters:
name of the parameter to set
value wstring value to set
reserve The total number of characters to reserve for the value. -1 indicates not to reserve any extra space.
Definition at line 864 of file CELData.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), and affymetrix_calvin_parameter::ParameterNameValueType::SetValueText().
void CelFileData::UpdateDataSetRowCount (const DataSetHeader & hdr) [private]
Definition at line 246 of file CELData.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupHeader::GetDataSetCnt(), affymetrix_calvin_io::DataSetHeader::GetName(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Friends And Related Function Documentation
friend class CelFileReader [friend]
Definition at line 427 of file CELData.h.
friend class CelFileWriter [friend]
Definition at line 428 of file CELData.h.
friend class MultiChannelCelFileWriter [friend]
Definition at line 429 of file CELData.h.
Member Data Documentation
std::wstring affymetrix_calvin_io::CelFileData::activeChannel [private]
current wavelength which is the datagroup in this file
Definition at line 92 of file CELData.h.
int32_t affymetrix_calvin_io::CelFileData::cachedCols [private]
keep cols from being read from the header all the time
Definition at line 112 of file CELData.h.
int32_t affymetrix_calvin_io::CelFileData::cachedRows [private]
keep rows from being read from the header all the time
Definition at line 110 of file CELData.h.
DataSet* affymetrix_calvin_io::CelFileData::dpInten [private]
Intensity DataSet
Definition at line 96 of file CELData.h.
DataSet* affymetrix_calvin_io::CelFileData::dpPixels [private]
NumPixels DataSet
Definition at line 100 of file CELData.h.
DataSet* affymetrix_calvin_io::CelFileData::dpStdev [private]
Stdev DataSet
Definition at line 98 of file CELData.h.
GenericData affymetrix_calvin_io::CelFileData::genericData [private]
Generic layer object
Definition at line 83 of file CELData.h.
Referenced by GetFileHeader(), and GetGenericData().
int32_t affymetrix_calvin_io::CelFileData::intensityColumnType [private]
Definition at line 89 of file CELData.h.
std::set<XYCoord> affymetrix_calvin_io::CelFileData::masked [private]
A set of masked cell coordinates.
Definition at line 108 of file CELData.h.
bool affymetrix_calvin_io::CelFileData::maskPlaneRead [private]
Indicates whether an attempt to read the mask data set has been made.
Definition at line 106 of file CELData.h.
bool affymetrix_calvin_io::CelFileData::outlierPlaneRead [private]
Indicates whether an attempt to read the outlier data set has been made.
Definition at line 102 of file CELData.h.
std::set<XYCoord> affymetrix_calvin_io::CelFileData::outliers [private]
A set of outlier cell coordinates.
Definition at line 104 of file CELData.h.
bool affymetrix_calvin_io::CelFileData::setIntensityMetaData [private]
Definition at line 84 of file CELData.h.
bool affymetrix_calvin_io::CelFileData::setMaskMetaData [private]
Definition at line 88 of file CELData.h.
bool affymetrix_calvin_io::CelFileData::setOutlierMetaData [private]
Definition at line 87 of file CELData.h.
bool affymetrix_calvin_io::CelFileData::setPixelMetaData [private]
Definition at line 86 of file CELData.h.
bool affymetrix_calvin_io::CelFileData::setStdDevMetaData [private]
Definition at line 85 of file CELData.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CELData.h
C:/f112/affy/sdk/calvin_files/data/src/CELData.cpp