Affymetrix Fusion SDK: affymetrix_calvin_io::CDFProbeGroupInformation Class Reference
affymetrix_calvin_io::CDFProbeGroupInformation Class Reference
#include <CDFProbeGroupInformation.h>
Public Member Functions
CDFProbeGroupInformation ()
~CDFProbeGroupInformation ()
DirectionType GetDirection () const
u_int32_t GetNumLists () const
u_int32_t GetNumCells () const
u_int8_t GetNumCellsPerList () const
std::wstring GetName () const
u_int16_t GetWobbleSituation () const
u_int16_t GetAlleleCode () const
u_int8_t GetChannel () const
ReplicationType GetRepType () const
void GetCell (int32_t cell_index, CDFProbeInformation &info)
Protected Member Functions
void SetDataSet (DataSet *ds)
Protected Attributes
DataSet * dataSet
CDFDataTypeIds type
u_int8_t direction
u_int32_t listCnt
u_int32_t cellCnt
u_int16_t wobbleSituation
u_int16_t alleleCode
u_int8_t channel
u_int8_t repType
u_int32_t probeSetNumber
u_int8_t cellsPerList
Friends
class CDFProbeSetInformation
Detailed Description
Class that exposes the CDF probe group information
Definition at line 41 of file CDFProbeGroupInformation.h.
Constructor & Destructor Documentation
CDFProbeGroupInformation::CDFProbeGroupInformation ()
Constructor
Definition at line 30 of file CDFProbeGroupInformation.cpp.
References dataSet.
CDFProbeGroupInformation::~CDFProbeGroupInformation ()
Desctructor
Definition at line 35 of file CDFProbeGroupInformation.cpp.
References affymetrix_calvin_io::DataSet::Close(), dataSet, and affymetrix_calvin_io::DataSet::Delete().
Member Function Documentation
u_int16_t affymetrix_calvin_io::CDFProbeGroupInformation::GetAlleleCode () const [inline]
Get the allele
Definition at line 62 of file CDFProbeGroupInformation.h.
References alleleCode.
void CDFProbeGroupInformation::GetCell (int32_t cell_index, CDFProbeInformation & info)
Get information for the probe by index
Definition at line 114 of file CDFProbeGroupInformation.cpp.
References affymetrix_calvin_io::CDFProbeInformation::CopyFromDataSet(), dataSet, and affymetrix_calvin_io::DataSet::Rows().
Referenced by affymetrix_fusion_io::FusionCDFProbeInformation::Initialize().
u_int8_t affymetrix_calvin_io::CDFProbeGroupInformation::GetChannel () const [inline]
Get the channel
Definition at line 64 of file CDFProbeGroupInformation.h.
References channel.
DirectionType affymetrix_calvin_io::CDFProbeGroupInformation::GetDirection () const [inline]
Get the probe set direction
Definition at line 50 of file CDFProbeGroupInformation.h.
References direction.
std::wstring affymetrix_calvin_io::CDFProbeGroupInformation::GetName () const [inline]
Get the probe group name = DataPlane name
Definition at line 58 of file CDFProbeGroupInformation.h.
References dataSet, affymetrix_calvin_io::DataSetHeader::GetName(), and affymetrix_calvin_io::DataSet::Header().
u_int32_t affymetrix_calvin_io::CDFProbeGroupInformation::GetNumCells () const [inline]
Get the number of cells in the probe group
Definition at line 54 of file CDFProbeGroupInformation.h.
References cellCnt.
u_int8_t affymetrix_calvin_io::CDFProbeGroupInformation::GetNumCellsPerList () const [inline]
Get the number of cells per list (atom)
Definition at line 56 of file CDFProbeGroupInformation.h.
References cellsPerList.
u_int32_t affymetrix_calvin_io::CDFProbeGroupInformation::GetNumLists () const [inline]
Get the number of lists (atoms) in the probe group
Definition at line 52 of file CDFProbeGroupInformation.h.
References listCnt.
ReplicationType affymetrix_calvin_io::CDFProbeGroupInformation::GetRepType () const [inline]
Get the probe replication type
Definition at line 66 of file CDFProbeGroupInformation.h.
References repType.
u_int16_t affymetrix_calvin_io::CDFProbeGroupInformation::GetWobbleSituation () const [inline]
Get the wobble situation
Definition at line 60 of file CDFProbeGroupInformation.h.
References wobbleSituation.
void CDFProbeGroupInformation::SetDataSet (DataSet * ds) [protected]
Definition at line 44 of file CDFProbeGroupInformation.cpp.
References alleleCode, CDF_ATOMS, CDF_CELLS, CDF_CELLS_PER_ATOM, CDF_DIRECTION, CDF_PROBE_SET_NUMBER, CDF_UNIT_TYPE, cellCnt, cellsPerList, channel, affymetrix_calvin_io::DataSet::Close(), dataSet, affymetrix_calvin_io::DataSet::Delete(), direction, affymetrix_calvin_io::Expression, affymetrix_calvin_io::DataSetHeader::FindNameValParam(), affymetrix_calvin_io::DataSet::Header(), listCnt, affymetrix_calvin_io::DataSet::Open(), probeSetNumber, repType, type, and wobbleSituation.
Referenced by affymetrix_calvin_io::CDFProbeSetInformation::GetGroupInformation().
Friends And Related Function Documentation
friend class CDFProbeSetInformation [friend]
Definition at line 98 of file CDFProbeGroupInformation.h.
Member Data Documentation
u_int16_t affymetrix_calvin_io::CDFProbeGroupInformation::alleleCode [protected]
Allele
Definition at line 88 of file CDFProbeGroupInformation.h.
Referenced by GetAlleleCode(), and SetDataSet().
u_int32_t affymetrix_calvin_io::CDFProbeGroupInformation::cellCnt [protected]
Number of cells in the probe group
Definition at line 84 of file CDFProbeGroupInformation.h.
Referenced by GetNumCells(), and SetDataSet().
u_int8_t affymetrix_calvin_io::CDFProbeGroupInformation::cellsPerList [protected]
Cells per list (atom) - same as NumCellsPerList in C++
Definition at line 96 of file CDFProbeGroupInformation.h.
Referenced by GetNumCellsPerList(), and SetDataSet().
u_int8_t affymetrix_calvin_io::CDFProbeGroupInformation::channel [protected]
Channel
Definition at line 90 of file CDFProbeGroupInformation.h.
Referenced by GetChannel(), and SetDataSet().
DataSet* affymetrix_calvin_io::CDFProbeGroupInformation::dataSet [protected]
DataSet pointer
Definition at line 75 of file CDFProbeGroupInformation.h.
Referenced by CDFProbeGroupInformation(), GetCell(), GetName(), SetDataSet(), and ~CDFProbeGroupInformation().
u_int8_t affymetrix_calvin_io::CDFProbeGroupInformation::direction [protected]
Direction
Definition at line 80 of file CDFProbeGroupInformation.h.
Referenced by GetDirection(), and SetDataSet().
u_int32_t affymetrix_calvin_io::CDFProbeGroupInformation::listCnt [protected]
Number of lists (atoms) in the probe group
Definition at line 82 of file CDFProbeGroupInformation.h.
Referenced by GetNumLists(), and SetDataSet().
u_int32_t affymetrix_calvin_io::CDFProbeGroupInformation::probeSetNumber [protected]
Probe set number - same as ProbeSetNumber in C++
Definition at line 94 of file CDFProbeGroupInformation.h.
Referenced by SetDataSet().
u_int8_t affymetrix_calvin_io::CDFProbeGroupInformation::repType [protected]
Probe replication type
Definition at line 92 of file CDFProbeGroupInformation.h.
Referenced by GetRepType(), and SetDataSet().
CDFDataTypeIds affymetrix_calvin_io::CDFProbeGroupInformation::type [protected]
Probe set type - u_int8_t
Definition at line 78 of file CDFProbeGroupInformation.h.
Referenced by SetDataSet().
u_int16_t affymetrix_calvin_io::CDFProbeGroupInformation::wobbleSituation [protected]
Wobble situation
Definition at line 86 of file CDFProbeGroupInformation.h.
Referenced by GetWobbleSituation(), and SetDataSet().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/data/src/CDFProbeGroupInformation.h
C:/f112/affy/sdk/calvin_files/data/src/CDFProbeGroupInformation.cpp