Affymetrix Fusion SDK: CopyNumberResultWriter Class Reference
CopyNumberResultWriter Class Reference
#include <CopyNumberResultWriter.h>
Public Member Functions
CopyNumberResultWriter ()
~CopyNumberResultWriter ()
void Clear ()
void MaximumProbeSetNameLength (int len)
void MaximumCytoRegionNameLength (int len)
void MaximumGenotypeProbeSetNameLength (int len)
std::string & AlgName ()
std::string & AlgVersion ()
std::string & ProgramName ()
std::string & ProgramVersion ()
std::string & ProgramCompany ()
int & NumberProbeSets ()
int & NumberCytoRegions ()
int & NumberGenotypeProbeSets ()
std::vector
< affymetrix_calvin_io::ColumnInfo > & Columns ()
std::vector
< affymetrix_calvin_io::ColumnInfo > & GenotypeColumns ()
std::vector
< affymetrix_calvin_io::ColumnInfo > & CytoRegionColumns ()
affymetrix_calvin_parameter::ParameterNameValueTypeList & AlgParams ()
affymetrix_calvin_parameter::ParameterNameValueTypeList & SummaryParams ()
void SetChromosomeProbeSetIndexInformation (u_int8_t chr, int startIndex, int count)
void CreateResultFile (affymetrix_fusion_io::FusionCELData &cel, const std::string &fileName)
void WriteProbeSetResult (const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData &entry)
void WriteCytoRegionResult (const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData &entry)
void WriteGenotypeProbeSetResult (const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry)
void CloseResultsFile ()
Private Member Functions
void Init ()
Private Attributes
std::map
< affymetrix_calvin_io::MultiDataType,
int > maxProbeSetNameLength
int numberProbeSets
int numberCytoRegions
int numberGenotypeProbeSets
std::string algName
std::string algVersion
std::string programName
std::string programVersion
std::string programCompany
std::vector
< affymetrix_calvin_io::ColumnInfo > columns
std::vector
< affymetrix_calvin_io::ColumnInfo > genotypeColumns
std::vector
< affymetrix_calvin_io::ColumnInfo > cytoRegionColumns
affymetrix_calvin_parameter::ParameterNameValueTypeList algParams
affymetrix_calvin_parameter::ParameterNameValueTypeList summaryParams
affymetrix_calvin_parameter::ParameterNameValueTypeList chrStartStop
affymetrix_calvin_io::CHPMultiDataFileBufferWriter * bufferWriter
std::vector< std::string > outputFiles
Detailed Description
This class provides a wrapper to writing a single copy number file of the Command Console format.
Definition at line 39 of file CopyNumberResultWriter.h.
Constructor & Destructor Documentation
CopyNumberResultWriter::CopyNumberResultWriter () [inline]
Initialize the class
Definition at line 99 of file CopyNumberResultWriter.h.
References Init().
CopyNumberResultWriter::~CopyNumberResultWriter () [inline]
Clean up
Definition at line 102 of file CopyNumberResultWriter.h.
References Clear().
Member Function Documentation
std::string& CopyNumberResultWriter::AlgName () [inline]
The name of the algorithm.
Returns:
The algorithm name.
Definition at line 125 of file CopyNumberResultWriter.h.
References algName.
affymetrix_calvin_parameter::ParameterNameValueTypeList& CopyNumberResultWriter::AlgParams () [inline]
Algorithm parameters. This should include the genome name, version, etc.
Definition at line 166 of file CopyNumberResultWriter.h.
References algParams.
std::string& CopyNumberResultWriter::AlgVersion () [inline]
Sets the algorithm version.
Returns:
The version.
Definition at line 130 of file CopyNumberResultWriter.h.
References algVersion.
void CopyNumberResultWriter::Clear (void)
Clean up
Definition at line 54 of file CopyNumberResultWriter.cpp.
Referenced by ~CopyNumberResultWriter().
void CopyNumberResultWriter::CloseResultsFile ()
Close the output file.
Definition at line 151 of file CopyNumberResultWriter.cpp.
std::vector<affymetrix_calvin_io::ColumnInfo>& CopyNumberResultWriter::Columns () [inline]
The columns of data to store.
Definition at line 157 of file CopyNumberResultWriter.h.
References columns.
void CopyNumberResultWriter::CreateResultFile (affymetrix_fusion_io::FusionCELData & cel, const std::string & fileName)
Create the results file with the header information (no data is written). This function will throw a std::string exception on errors.
Parameters:
cel The CEL file data object.
fileName The name of the results file to create.
Returns:
True if successful.
Definition at line 80 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::CHPMultiDataData::AddAlgParams(), affymetrix_calvin_io::DataSetHeader::AddNameValParam(), affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_io::GenericDataHeader::AddParent(), affymetrix_calvin_io::CHPMultiDataData::AddSummaryParams(), affymetrix_calvin_io::CopyNumberMultiDataType, affymetrix_calvin_io::CytoMultiDataType, affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_fusion_io::FusionCELData::GetChipType(), affymetrix_calvin_io::CHPMultiDataData::GetDataSetHeader(), affymetrix_calvin_io::CHPMultiDataData::GetFileHeader(), affymetrix_fusion_io::FusionCELData::GetGenericData(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_calvin_io::GenericData::Header(), PROGRAM_COMPANY, PROGRAM_NAME, affymetrix_calvin_io::CHPMultiDataData::SetAlgName(), affymetrix_calvin_io::CHPMultiDataData::SetAlgVersion(), affymetrix_calvin_io::CHPMultiDataData::SetArrayType(), affymetrix_calvin_io::CHPMultiDataData::SetEntryCount(), affymetrix_calvin_parameter::ParameterNameValueType::SetName(), affymetrix_calvin_parameter::ParameterNameValueType::SetValueText(), and affymetrix_calvin_exceptions::CalvinException::ToString().
std::vector<affymetrix_calvin_io::ColumnInfo>& CopyNumberResultWriter::CytoRegionColumns () [inline]
The columns of cyto data to store.
Definition at line 163 of file CopyNumberResultWriter.h.
References cytoRegionColumns.
std::vector<affymetrix_calvin_io::ColumnInfo>& CopyNumberResultWriter::GenotypeColumns () [inline]
The columns of genotype data to store.
Definition at line 160 of file CopyNumberResultWriter.h.
References genotypeColumns.
void CopyNumberResultWriter::Init () [private]
Initialize the class
Definition at line 42 of file CopyNumberResultWriter.cpp.
Referenced by CopyNumberResultWriter().
void CopyNumberResultWriter::MaximumCytoRegionNameLength (int len) [inline]
Set the max cyto region name length.
Parameters:
len The maximum length.
Definition at line 115 of file CopyNumberResultWriter.h.
References affymetrix_calvin_io::CytoMultiDataType, and maxProbeSetNameLength.
void CopyNumberResultWriter::MaximumGenotypeProbeSetNameLength (int len) [inline]
Set the max genotype probe set name length.
Parameters:
len The maximum length.
Definition at line 120 of file CopyNumberResultWriter.h.
References affymetrix_calvin_io::GenotypeMultiDataType, and maxProbeSetNameLength.
void CopyNumberResultWriter::MaximumProbeSetNameLength (int len) [inline]
Set the max probe set name length.
Parameters:
len The maximum length.
Definition at line 110 of file CopyNumberResultWriter.h.
References affymetrix_calvin_io::CopyNumberMultiDataType, and maxProbeSetNameLength.
int& CopyNumberResultWriter::NumberCytoRegions () [inline]
The number of cyto regions
Returns:
The number of cyto regions
Definition at line 149 of file CopyNumberResultWriter.h.
References numberCytoRegions.
int& CopyNumberResultWriter::NumberGenotypeProbeSets () [inline]
The number of genotype probe sets return The number of genotype probe sets.
Definition at line 154 of file CopyNumberResultWriter.h.
References numberGenotypeProbeSets.
int& CopyNumberResultWriter::NumberProbeSets () [inline]
The number of probe sets
Returns:
The number of probe sets
Definition at line 144 of file CopyNumberResultWriter.h.
References numberProbeSets.
std::string& CopyNumberResultWriter::ProgramCompany () [inline]
The company name.
Definition at line 139 of file CopyNumberResultWriter.h.
References programCompany.
std::string& CopyNumberResultWriter::ProgramName () [inline]
The program name.
Definition at line 133 of file CopyNumberResultWriter.h.
References programName.
std::string& CopyNumberResultWriter::ProgramVersion () [inline]
The program version.
Definition at line 136 of file CopyNumberResultWriter.h.
References programVersion.
void CopyNumberResultWriter::SetChromosomeProbeSetIndexInformation (u_int8_t chr, int startIndex, int count)
Store the starting probe set index and count of probe sets for the given chromosome.
Parameters:
chr The chromosome value
startIndex The index of the probe sets that the given chromosome starts at.
count The number of probe sets for the given chromosome.
Definition at line 188 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_data::ChromosomeToString(), and affymetrix_calvin_parameter::ParameterNameValueType::SetName().
affymetrix_calvin_parameter::ParameterNameValueTypeList& CopyNumberResultWriter::SummaryParams () [inline]
Summary parameters. This includes items such as IQR, etc.
Definition at line 169 of file CopyNumberResultWriter.h.
References summaryParams.
void CopyNumberResultWriter::WriteCytoRegionResult (const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & entry)
Write the cyto region result to the file.
Parameters:
entry The results.
Definition at line 180 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::CytoMultiDataType.
void CopyNumberResultWriter::WriteGenotypeProbeSetResult (const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry)
Write the genotype probe set result to the file.
Parameters:
entry The results.
Definition at line 172 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::GenotypeMultiDataType.
void CopyNumberResultWriter::WriteProbeSetResult (const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & entry)
Write the probe set result to the file.
Parameters:
entry The results.
Definition at line 164 of file CopyNumberResultWriter.cpp.
References affymetrix_calvin_io::CopyNumberMultiDataType.
Member Data Documentation
std::string CopyNumberResultWriter::algName [private]
The name of the algorithm.
Definition at line 56 of file CopyNumberResultWriter.h.
Referenced by AlgName().
affymetrix_calvin_parameter::ParameterNameValueTypeList CopyNumberResultWriter::algParams [private]
Algorithm parameters.
Definition at line 80 of file CopyNumberResultWriter.h.
Referenced by AlgParams().
std::string CopyNumberResultWriter::algVersion [private]
The algorithm version.
Definition at line 59 of file CopyNumberResultWriter.h.
Referenced by AlgVersion().
affymetrix_calvin_io::CHPMultiDataFileBufferWriter* CopyNumberResultWriter::bufferWriter [private]
The writer for the results file.
Definition at line 89 of file CopyNumberResultWriter.h.
affymetrix_calvin_parameter::ParameterNameValueTypeList CopyNumberResultWriter::chrStartStop [private]
A list of start/stop indicies for the probesets in a chromosome.
Definition at line 86 of file CopyNumberResultWriter.h.
std::vector<affymetrix_calvin_io::ColumnInfo> CopyNumberResultWriter::columns [private]
The columns of data to store.
Definition at line 71 of file CopyNumberResultWriter.h.
Referenced by Columns().
std::vector<affymetrix_calvin_io::ColumnInfo> CopyNumberResultWriter::cytoRegionColumns [private]
The columns of cytoregion data to store.
Definition at line 77 of file CopyNumberResultWriter.h.
Referenced by CytoRegionColumns().
std::vector<affymetrix_calvin_io::ColumnInfo> CopyNumberResultWriter::genotypeColumns [private]
The columns of genotype data to store.
Definition at line 74 of file CopyNumberResultWriter.h.
Referenced by GenotypeColumns().
std::map<affymetrix_calvin_io::MultiDataType, int> CopyNumberResultWriter::maxProbeSetNameLength [private]
The maximum probe set name.
Definition at line 44 of file CopyNumberResultWriter.h.
Referenced by MaximumCytoRegionNameLength(), MaximumGenotypeProbeSetNameLength(), and MaximumProbeSetNameLength().
int CopyNumberResultWriter::numberCytoRegions [private]
The number of cyto regions
Definition at line 50 of file CopyNumberResultWriter.h.
Referenced by NumberCytoRegions().
int CopyNumberResultWriter::numberGenotypeProbeSets [private]
The number of genotype probe sets
Definition at line 53 of file CopyNumberResultWriter.h.
Referenced by NumberGenotypeProbeSets().
int CopyNumberResultWriter::numberProbeSets [private]
The number of probe sets
Definition at line 47 of file CopyNumberResultWriter.h.
Referenced by NumberProbeSets().
std::vector<std::string> CopyNumberResultWriter::outputFiles [private]
Used by the buffer writing. The list of output files.
Definition at line 92 of file CopyNumberResultWriter.h.
std::string CopyNumberResultWriter::programCompany [private]
The company name.
Definition at line 68 of file CopyNumberResultWriter.h.
Referenced by ProgramCompany().
std::string CopyNumberResultWriter::programName [private]
The program name.
Definition at line 62 of file CopyNumberResultWriter.h.
Referenced by ProgramName().
std::string CopyNumberResultWriter::programVersion [private]
The program version.
Definition at line 65 of file CopyNumberResultWriter.h.
Referenced by ProgramVersion().
affymetrix_calvin_parameter::ParameterNameValueTypeList CopyNumberResultWriter::summaryParams [private]
Summary parameters.
Definition at line 83 of file CopyNumberResultWriter.h.
Referenced by SummaryParams().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CopyNumberResultWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CopyNumberResultWriter.cpp