Affymetrix Fusion SDK: affymetrix_calvin_io::MultiChannelCelFileCollater Class Reference
affymetrix_calvin_io::MultiChannelCelFileCollater Class Reference
#include <MultiChannelCelFileCollater.h>
Public Member Functions
MultiChannelCelFileCollater ()
~MultiChannelCelFileCollater ()
void Collate (const StringVector &celFiles, const std::string &outFile)
Protected Member Functions
void CopyDataGroupHdr (DataGroupHeader &src, DataGroupHeader &dst)
void CopyFileHdr (FileHeader &src, FileHeader &dst)
void OpenReader (const std::string &file, GenericData &data)
void WriteDataGroup (DataGroupReader &gReader, DataGroupHeader &fileHdr, DataGroupWriter &writer, bool lastGroup)
void WriteDataSet (DataSetReader &setReader, DataSetHeader &setHdr, DataSetWriter &setWriter)
Private Member Functions
void CopyHeaders (const std::vector< std::string > &celFiles, FileHeader &outFileHdr)
void CopyDataSetHdr (DataSetHeader &src, DataSetHeader &dst)
void CopyParentHeaders (GenericDataHeader *src, GenericDataHeader *dst)
void CopyGenericHeader (GenericDataHeader *src, GenericDataHeader *dst)
void CopyGenericHeaderParams (GenericDataHeader *src, GenericDataHeader *dst)
void WriteDataGroups (const StringVector &celFiles, GenericFileWriter &writer)
void UpdateWavelength (GenericDataHeader *hdr)
Private Attributes
std::wstring wavelength
Detailed Description
Definition at line 42 of file MultiChannelCelFileCollater.h.
Constructor & Destructor Documentation
MultiChannelCelFileCollater::MultiChannelCelFileCollater ()
Definition at line 27 of file MultiChannelCelFileCollater.cpp.
References NO_WAVELENGTH, and wavelength.
MultiChannelCelFileCollater::~MultiChannelCelFileCollater ()
Definition at line 35 of file MultiChannelCelFileCollater.cpp.
Member Function Documentation
void MultiChannelCelFileCollater::Collate (const StringVector & celFiles, const std::string & outFile)
Definition at line 49 of file MultiChannelCelFileCollater.cpp.
References CopyHeaders(), affymetrix_calvin_io::FileHeader::SetFilename(), WriteDataGroups(), and affymetrix_calvin_io::GenericFileWriter::WriteHeader().
void MultiChannelCelFileCollater::CopyDataGroupHdr (DataGroupHeader & src, DataGroupHeader & dst) [protected]
Definition at line 181 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::DataGroupHeader::AddDataSetHdr(), CopyDataSetHdr(), affymetrix_calvin_io::DataGroupHeader::GetDataSetIterators(), affymetrix_calvin_io::DataGroupHeader::SetName(), and wavelength.
Referenced by CopyHeaders().
void MultiChannelCelFileCollater::CopyDataSetHdr (DataSetHeader & src, DataSetHeader & dst) [private]
Definition at line 195 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::DataSetHeader::AddColumn(), affymetrix_calvin_io::DataSetHeader::AddNameValParam(), affymetrix_calvin_io::DataSetHeader::GetColumnCnt(), affymetrix_calvin_io::DataSetHeader::GetColumnInfo(), affymetrix_calvin_io::DataSetHeader::GetName(), affymetrix_calvin_io::DataSetHeader::GetNameValIterators(), affymetrix_calvin_io::DataSetHeader::GetRowCnt(), affymetrix_calvin_io::DataSetHeader::SetName(), and affymetrix_calvin_io::DataSetHeader::SetRowCnt().
Referenced by CopyDataGroupHdr().
void MultiChannelCelFileCollater::CopyFileHdr (FileHeader & src, FileHeader & dst) [protected]
Definition at line 140 of file MultiChannelCelFileCollater.cpp.
References CopyGenericHeader(), CopyParentHeaders(), and affymetrix_calvin_io::FileHeader::GetGenericDataHdr().
Referenced by CopyHeaders().
void MultiChannelCelFileCollater::CopyGenericHeader (GenericDataHeader * src, GenericDataHeader * dst) [private]
Definition at line 157 of file MultiChannelCelFileCollater.cpp.
References CopyGenericHeaderParams(), MULTI_CHANNEL_FILE_ID, and affymetrix_calvin_io::GenericDataHeader::SetFileTypeId().
Referenced by CopyFileHdr().
void MultiChannelCelFileCollater::CopyGenericHeaderParams (GenericDataHeader * src, GenericDataHeader * dst) [private]
Definition at line 163 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), AFFY_FILTER_WAVELENGTH, affymetrix_calvin_io::GenericDataHeader::GetNameValIterators(), and wavelength.
Referenced by CopyGenericHeader().
void MultiChannelCelFileCollater::CopyHeaders (const std::vector< std::string > & celFiles, FileHeader & outFileHdr) [private]
Definition at line 59 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::FileHeader::AddDataGroupHdr(), affymetrix_calvin_io::GenericData::Clear(), CopyDataGroupHdr(), CopyFileHdr(), affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_calvin_io::GenericData::Header(), OpenReader(), and UpdateWavelength().
Referenced by Collate().
void MultiChannelCelFileCollater::CopyParentHeaders (GenericDataHeader * src, GenericDataHeader * dst) [private]
Definition at line 146 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::GenericDataHeader::AddParent(), and affymetrix_calvin_io::GenericDataHeader::GetParentIterators().
Referenced by CopyFileHdr().
void MultiChannelCelFileCollater::OpenReader (const std::string & file, GenericData & data) [protected]
Definition at line 40 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::GenericData::Clear(), affymetrix_calvin_io::GenericFileReader::Close(), affymetrix_calvin_io::GenericFileReader::Open(), and affymetrix_calvin_io::GenericFileReader::SetFilename().
Referenced by CopyHeaders().
void MultiChannelCelFileCollater::UpdateWavelength (GenericDataHeader * hdr) [private]
Definition at line 80 of file MultiChannelCelFileCollater.cpp.
References AFFY_FILTER_WAVELENGTH, affymetrix_calvin_io::GenericDataHeader::FindNameValParam(), NO_WAVELENGTH, and wavelength.
Referenced by CopyHeaders().
void MultiChannelCelFileCollater::WriteDataGroup (DataGroupReader & gReader, DataGroupHeader & fileHdr, DataGroupWriter & writer, bool lastGroup) [protected]
Definition at line 110 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::DataGroupHeader::GetDataSet(), affymetrix_calvin_io::DataGroupReader::GetDataSetCnt(), affymetrix_calvin_io::DataGroupReader::GetDataSetReader(), affymetrix_calvin_io::DataGroupWriter::GetDataSetWriter(), affymetrix_calvin_io::DataGroupWriter::UpdateNextDataGroupPos(), WriteDataSet(), and affymetrix_calvin_io::DataGroupWriter::WriteHeader().
Referenced by WriteDataGroups().
void MultiChannelCelFileCollater::WriteDataGroups (const StringVector & celFiles, GenericFileWriter & writer) [private]
Definition at line 94 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::FileHeader::GetDataGroup(), affymetrix_calvin_io::GenericFileWriter::GetDataGroupCnt(), affymetrix_calvin_io::GenericFileReader::GetDataGroupReader(), affymetrix_calvin_io::GenericFileWriter::GetDataGroupWriter(), affymetrix_calvin_io::GenericData::Header(), affymetrix_calvin_io::GenericFileReader::Open(), affymetrix_calvin_io::GenericFileReader::SetFilename(), and WriteDataGroup().
Referenced by Collate().
void MultiChannelCelFileCollater::WriteDataSet (DataSetReader & setReader, DataSetHeader & setHdr, DataSetWriter & setWriter) [protected]
Definition at line 125 of file MultiChannelCelFileCollater.cpp.
References affymetrix_calvin_io::DataSetHeader::GetDataSize(), affymetrix_calvin_io::DataSetReader::ReadBuffer(), affymetrix_calvin_io::DataSetWriter::UpdateNextDataSetOffset(), affymetrix_calvin_io::DataSetWriter::WriteBuffer(), and affymetrix_calvin_io::DataSetWriter::WriteHeader().
Referenced by WriteDataGroup().
Member Data Documentation
std::wstring affymetrix_calvin_io::MultiChannelCelFileCollater::wavelength [private]
Definition at line 47 of file MultiChannelCelFileCollater.h.
Referenced by CopyDataGroupHdr(), CopyGenericHeaderParams(), MultiChannelCelFileCollater(), and UpdateWavelength().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/MultiChannelCelFileCollater.h
C:/f112/affy/sdk/calvin_files/writers/src/MultiChannelCelFileCollater.cpp