Affymetrix Fusion SDK: GenoCallCoder Class Reference
GenoCallCoder Class Reference
#include <GenoCallCoder.h>
Public Member Functions
GenoCallCoder (const int max_allele_count=2, const std::string data_size="UCHAR", const std::string version="0", char allele_delimiter='\0')
Default constructor.
GenoCallCoder (const int max_allele_count, const std::string data_size, const std::string version, char allele_delimiter, const std::string marker_annotation_file)
Constructor.
void initialize (const int max_allele_count, const std::string data_size, const std::string version, char allele_delimiter)
Creates and populates marker translation data structure from given file path to marker annotation file.
std::vector< std::string > getProbesetIds ()
Retrieve vector of probeset ids in allele name table.
std::vector< unsigned char > getValidGenotypeCallCodes (std::string probeset_id)
Retrieve vector of genotype call codes allowable for given probeset_id -- based on probeset's allele count and allowable copy number states.
std::string genotypeCallNumToAbstractAllele (const unsigned char call_code)
Decode from call code number to abstract allele string.
std::string genotypeCallNumToReferenceAllele (const std::string probeset_id, const unsigned char call_code)
Decode from call code number to design allele name string for given probeset id.
std::string genotypeCallNumToReportAllele (const std::string probeset_id, const unsigned char call_code)
Decode from call code number to reporting allele name string for given probeset id.
std::string referenceAlleleToReportAllele (const std::string probeset_id, const std::string reference_allele)
Translate design allele name to reporting allele name for given probeset id.
std::string abstractAlleleToReferenceAllele (const std::string probeset_id, const std::string abstract_allele)
Translate abstract allele to design allele name for given probeset id.
std::string abstractAlleleToReportAllele (const std::string probeset_id, const std::string abstract_allele)
Translate abstract allele to reporting allele name for given probeset id.
unsigned char abstractAlleleToGenotypeCallNum (const std::string allele_string)
Decode from call code number to allele name string for given probeset id.
unsigned char abstractAlleleIntegersToGenotypeCallNum (const std::vector< int > abstract_allele_ints)
Takes vector of abstract allele characters encoded as integers and returns genotype call number.
std::vector< std::string > genotypeCallNumVecToAbstractAlleleVec (const std::vector< unsigned char > &call_codes)
Decode vector of call code numbers to vector of allele strings.
std::vector< unsigned char > abstractAlleleVecToGenotypeCallNumVec (const std::vector< std::string > &allele_string)
Encode from vector of allele strings to vector of numeric call codes.
std::vector< std::string > getAbstractAlleleVector ()
Retrieve a vector of abstract allele calls indexed by numeric call code.
bool isValidCallNum (const unsigned char call_code)
boolean indicating if code is within proper range for given GenoCallCoder instance
bool isValidAbstractAllele (const std::string allele)
boolean indicating if allele string is within proper set of possible alleles for given GenoCallCoder instance
bool isHom (const unsigned char call_code)
boolean indicating if call code corresponds to a homozygous call.
bool isHet (const unsigned char call_code)
boolean indicating if call code corresponds to a heterozygous call
Private Member Functions
std::string genotypeCallNumToAllele (const std::string probeset_id, const unsigned char call_code, const std::string allele_type)
Decode from call code number to allele string for given probeset id and allele type.
std::string alleleNameConvert (const std::string probeset_id, const std::string input_allele_string, const std::string input_type, const std::string output_type)
Translate allele name from one type to another {absract, reference, report} for given probeset id and allele type.
Private Attributes
int m_max_allele_count
number of alleles for marker with highest allele count
std::string m_data_size
string arg indicating size of call code field
int m_data_size_bits
number of bits used for encoding
unsigned int m_min_code
version dependent min call code
unsigned int m_min_translatable_code
version dependent min translatable call code
unsigned int m_max_code
data_size dependent max call code
unsigned int m_min_extra_code
version dependent min call code for extra codes
unsigned int m_max_extra_code
version dependent max call code for extra codes
std::string m_version
version
char m_allele_delimiter
character to delimit alleles in allele string
std::vector< std::string > m_abstract_codes
hard-coded codes, for now
std::map< std::string,
unsigned char > m_alleles
hard-coded code map, for now
std::vector< AlleleRecord > m_probeset_allele_name_table
table relating abstract alleles to allele names for each marker
std::map< char, int > m_alpha2num
legacy code map
Static Private Attributes
static const std::string m_annotation_csv_delimiter = " // "
annotation csv file intra-column delimiter
static const std::string m_extra_codes []
extra codes
static const std::string m_marker_annotation_file_cnames []
list of columns to grab from marker annotation file
static const std::string m_version_zero_codes []
version zero codes
static const char m_abstract_nocall_char = 'n'
character to represent a nocall when making partial calls (v1+)
static const std::string m_annot_csv_skip_text = "N/A"
string in annotation csv file indicating that there are no alleles to decode
static const char m_num2alpha [] = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'}
alphabet map
Detailed Description
GenoCallCoder - Class for encoding and decoding numeric genotype call codes to and from allele strings
Definition at line 129 of file GenoCallCoder.h.
Constructor & Destructor Documentation
GenoCallCoder::GenoCallCoder (const int max_allele_count = 2, const std::string data_size = "UCHAR", const std::string version = "0", char allele_delimiter = '\0')
Default constructor.
Constructor
Parameters:
max_allele_count - number of possible alleles for marker with highest allele count
data_size - string describing size of call field
allele_delimiter - character to delimit alleles in string
version - numeric version of coding scheme
GenoCallCoder::GenoCallCoder (const int max_allele_count, const std::string data_size, const std::string version, char allele_delimiter, const std::string marker_annotation_file)
Constructor.
Parameters:
max_allele_count - number of possible alleles for marker with highest allele count
data_size - string describing size of call field
version - numeric version of coding scheme
allele_delimiter - character to delimit alleles in string
probeset_allele_name_table - vector of (size 3 or 4) vector containing probeset ids, allele names, abstract alleles, and optional boolean report RevComp fields Constructor
max_allele_count - number of possible alleles for marker with highest allele count
data_size - string describing size of call field
version - numeric version of coding scheme
allele_delimiter - character to delimit alleles in string
marker_annotation_file - TsvFile instance of marker annotation file with columns for probeset ids, allele names, abstract alleles, and optional boolean report RevComp fields
Member Function Documentation
unsigned char GenoCallCoder::abstractAlleleIntegersToGenotypeCallNum (const std::vector< int > abstract_allele_ints)
Takes vector of abstract allele characters encoded as integers and returns genotype call number.
Parameters:
allele_string - string of allele calls to encode
Definition at line 914 of file GenoCallCoder.cpp.
References abstractAlleleToGenotypeCallNum(), m_num2alpha, ToStr(), and Verbose::warn().
unsigned char GenoCallCoder::abstractAlleleToGenotypeCallNum (const std::string allele_string)
Decode from call code number to allele name string for given probeset id.
Encode from allele string to numeric call code.
Parameters:
probeset_id - id of probeset to decode
alleleName - number to decode Encode from allele string to numeric call code
allele_string - string of allele calls to encode
allele_string - string of allele calls to encode
Definition at line 899 of file GenoCallCoder.cpp.
References m_alleles, and Verbose::warn().
Referenced by abstractAlleleIntegersToGenotypeCallNum().
string GenoCallCoder::abstractAlleleToReferenceAllele (const std::string probeset_id, const std::string abstract_allele)
Translate abstract allele to design allele name for given probeset id.
Parameters:
probeset_id - id of probeset to decode
abstract_allele - abstract allele to decode
Definition at line 877 of file GenoCallCoder.cpp.
References alleleNameConvert().
string GenoCallCoder::abstractAlleleToReportAllele (const std::string probeset_id, const std::string abstract_allele)
Translate abstract allele to reporting allele name for given probeset id.
Parameters:
probeset_id - id of probeset to decode
abstract_allele - abstract allele to decode
Definition at line 889 of file GenoCallCoder.cpp.
References alleleNameConvert().
vector< unsigned char > GenoCallCoder::abstractAlleleVecToGenotypeCallNumVec (const std::vector< std::string > & allele_string)
Encode from vector of allele strings to vector of numeric call codes.
Parameters:
allele_string - vector of allele call strings to encode
Definition at line 958 of file GenoCallCoder.cpp.
References m_alleles, and Verbose::warn().
string GenoCallCoder::alleleNameConvert (const std::string probeset_id, const std::string input_allele_string, const std::string input_type, const std::string output_type) [private]
Translate allele name from one type to another {absract, reference, report} for given probeset id and allele type.
Parameters:
probeset_id - id of probeset to decode
abstract_allele - abstract allele to decode
input_type - flag to indicate input type of allele name {"abs","ref","rep"}
output_type - flag to indicate output type of allele name {"abs","ref","rep"}
Definition at line 732 of file GenoCallCoder.cpp.
References AlleleRecord::compareAlleleRecordsByProbesetId(), Err::errAbort(), m_abstract_codes, m_abstract_nocall_char, m_allele_delimiter, m_probeset_allele_name_table, and Verbose::warn().
Referenced by abstractAlleleToReferenceAllele(), abstractAlleleToReportAllele(), genotypeCallNumToAllele(), and referenceAlleleToReportAllele().
string GenoCallCoder::genotypeCallNumToAbstractAllele (const unsigned char call_code)
Decode from call code number to abstract allele string.
Decode from call code number to allele string.
Parameters:
call_code - number to decode
Definition at line 702 of file GenoCallCoder.cpp.
References m_abstract_codes, m_data_size, ToStr(), and Verbose::warn().
Referenced by genotypeCallNumToAllele(), isHet(), and isHom().
string GenoCallCoder::genotypeCallNumToAllele (const std::string probeset_id, const unsigned char call_code, const std::string allele_type) [private]
Decode from call code number to allele string for given probeset id and allele type.
Parameters:
probeset_id - id of probeset to decode
call_code - number to decode
allele_type - type of allele string to return
Definition at line 841 of file GenoCallCoder.cpp.
References alleleNameConvert(), genotypeCallNumToAbstractAllele(), m_max_code, m_max_extra_code, m_min_code, m_min_extra_code, and m_min_translatable_code.
Referenced by genotypeCallNumToReferenceAllele(), and genotypeCallNumToReportAllele().
string GenoCallCoder::genotypeCallNumToReferenceAllele (const std::string probeset_id, const unsigned char call_code)
Decode from call code number to design allele name string for given probeset id.
Decode from call code number to reference allele name string for given probeset id.
Parameters:
probeset_id - id of probeset to decode
call_code - number to decode
Definition at line 719 of file GenoCallCoder.cpp.
References genotypeCallNumToAllele().
string GenoCallCoder::genotypeCallNumToReportAllele (const std::string probeset_id, const unsigned char call_code)
Decode from call code number to reporting allele name string for given probeset id.
Decode from call code number to report allele string for given probeset id.
Parameters:
probeset_id - id of probeset to decode
call_code - number to decode
Definition at line 828 of file GenoCallCoder.cpp.
References genotypeCallNumToAllele().
vector< string > GenoCallCoder::genotypeCallNumVecToAbstractAlleleVec (const std::vector< unsigned char > & call_codes)
Decode vector of call code numbers to vector of allele strings.
Parameters:
call_codes - vector of numbers to decode
Definition at line 938 of file GenoCallCoder.cpp.
References m_abstract_codes, m_data_size, ToStr(), and Verbose::warn().
std::vector<std::string> GenoCallCoder::getAbstractAlleleVector () [inline]
Retrieve a vector of abstract allele calls indexed by numeric call code.
Definition at line 307 of file GenoCallCoder.h.
References m_abstract_codes.
vector< string > GenoCallCoder::getProbesetIds ()
Retrieve vector of probeset ids in allele name table.
Definition at line 675 of file GenoCallCoder.cpp.
References m_probeset_allele_name_table.
vector< unsigned char > GenoCallCoder::getValidGenotypeCallCodes (std::string probeset_id)
Retrieve vector of genotype call codes allowable for given probeset_id -- based on probeset's allele count and allowable copy number states.
Parameters:
probeset_id - id of probeset to get codes for
Definition at line 689 of file GenoCallCoder.cpp.
References AlleleRecord::compareAlleleRecordsByProbesetId(), and m_probeset_allele_name_table.
void GenoCallCoder::initialize (const int max_allele_count, const std::string data_size, const std::string version, char allele_delimiter)
Creates and populates marker translation data structure from given file path to marker annotation file.
Parameters:
filepath - path to marker annotation file
use_report_revcomp - boolean to indicate whether report_revcomp should be utilized Populate member data structures from given input
max_allele_count - number of possible alleles for marker with highest allele count
data_size - string describing size of call field
version - numeric version of coding scheme
allele_delimiter - character to delimit alleles in string
filepath - path to marker annotation file
use_report_revcomp - boolean to indicate whether report_revcomp should be utilized initialize
max_allele_count - number of possible alleles for marker with highest allele count
data_size - string describing size of call field
version - numeric version of coding scheme
Definition at line 484 of file GenoCallCoder.cpp.
References choose(), Err::errAbort(), m_abstract_codes, m_allele_delimiter, m_alleles, m_alpha2num, m_data_size_bits, m_extra_codes, m_max_allele_count, m_max_code, m_max_extra_code, m_min_code, m_min_extra_code, m_min_translatable_code, m_num2alpha, m_version, m_version_zero_codes, ToStr(), and Verbose::warn().
bool GenoCallCoder::isHet (const unsigned char call_code)
boolean indicating if call code corresponds to a heterozygous call
boolean indicating if call code corresponds to a heterozygous call. false if call code corresponds to partial call.
Parameters:
call_code - numeric call code to test
Definition at line 1030 of file GenoCallCoder.cpp.
References genotypeCallNumToAbstractAllele(), m_allele_delimiter, m_alpha2num, m_max_code, and m_min_translatable_code.
bool GenoCallCoder::isHom (const unsigned char call_code)
boolean indicating if call code corresponds to a homozygous call.
Parameters:
call_code - numeric call code to test boolean indicating if call code corresponds to a homozygous call
call_code - numeric call code to test
call_code - numeric call code to test
Definition at line 1004 of file GenoCallCoder.cpp.
References genotypeCallNumToAbstractAllele(), m_allele_delimiter, m_alpha2num, m_max_code, and m_min_translatable_code.
bool GenoCallCoder::isValidAbstractAllele (const std::string allele)
boolean indicating if allele string is within proper set of possible alleles for given GenoCallCoder instance
boolean indicating if code is within proper range for given instance
Parameters:
allele - string of alleles to test
code - numeric call code to test
Definition at line 995 of file GenoCallCoder.cpp.
References m_alleles.
bool GenoCallCoder::isValidCallNum (const unsigned char call_code)
boolean indicating if code is within proper range for given GenoCallCoder instance
Retrieve a vector of allele call strings indexed by numeric call code.
Parameters:
call_code - numeric call code to test
boolean indicating if code is within proper range for given instance
Parameters:
code - numeric call code to test
Definition at line 986 of file GenoCallCoder.cpp.
References m_max_code, m_max_extra_code, m_min_code, and m_min_extra_code.
string GenoCallCoder::referenceAlleleToReportAllele (const std::string probeset_id, const std::string reference_allele)
Translate design allele name to reporting allele name for given probeset id.
Translate abstract allele to allele name for given probeset id and allele type.
Parameters:
probeset_id - id of probeset to decode
reference_allele - string of design alleles to be converted to report alleles
probeset_id - id of probeset to decode
abstract_allele - abstract allele to decode
Definition at line 866 of file GenoCallCoder.cpp.
References alleleNameConvert().
Member Data Documentation
std::vector<std::string> GenoCallCoder::m_abstract_codes [private]
hard-coded codes, for now
Definition at line 376 of file GenoCallCoder.h.
Referenced by alleleNameConvert(), genotypeCallNumToAbstractAllele(), genotypeCallNumVecToAbstractAlleleVec(), getAbstractAlleleVector(), and initialize().
const char GenoCallCoder::m_abstract_nocall_char = 'n' [static, private]
character to represent a nocall when making partial calls (v1+)
Definition at line 349 of file GenoCallCoder.h.
Referenced by alleleNameConvert().
char GenoCallCoder::m_allele_delimiter [private]
character to delimit alleles in allele string
Definition at line 374 of file GenoCallCoder.h.
Referenced by alleleNameConvert(), initialize(), isHet(), and isHom().
std::map<std::string, unsigned char> GenoCallCoder::m_alleles [private]
hard-coded code map, for now
Definition at line 378 of file GenoCallCoder.h.
Referenced by abstractAlleleToGenotypeCallNum(), abstractAlleleVecToGenotypeCallNumVec(), initialize(), and isValidAbstractAllele().
std::map<char, int> GenoCallCoder::m_alpha2num [private]
legacy code map
Definition at line 385 of file GenoCallCoder.h.
Referenced by initialize(), isHet(), and isHom().
const string GenoCallCoder::m_annot_csv_skip_text = "N/A" [static, private]
string in annotation csv file indicating that there are no alleles to decode
Definition at line 351 of file GenoCallCoder.h.
const string GenoCallCoder::m_annotation_csv_delimiter = " // " [static, private]
annotation csv file intra-column delimiter
Definition at line 341 of file GenoCallCoder.h.
std::string GenoCallCoder::m_data_size [private]
string arg indicating size of call code field
Definition at line 358 of file GenoCallCoder.h.
Referenced by genotypeCallNumToAbstractAllele(), and genotypeCallNumVecToAbstractAlleleVec().
int GenoCallCoder::m_data_size_bits [private]
number of bits used for encoding
Definition at line 360 of file GenoCallCoder.h.
Referenced by initialize().
const string GenoCallCoder::m_extra_codes [static, private]
Initial value:
 {
  string("NotAvailable"),
  string("PossibleRareAllele")
}
extra codes
Definition at line 343 of file GenoCallCoder.h.
Referenced by initialize().
const string GenoCallCoder::m_marker_annotation_file_cnames [static, private]
Initial value:
 {
  string("Probe Set ID"),
  string("Allele Code"),
  string("Alleles Design Strand"),
  string("Alleles Reported Strand"),
  string("Alleles-Alias Reported Strand")
}
list of columns to grab from marker annotation file
Definition at line 345 of file GenoCallCoder.h.
int GenoCallCoder::m_max_allele_count [private]
number of alleles for marker with highest allele count
Definition at line 356 of file GenoCallCoder.h.
Referenced by initialize().
unsigned int GenoCallCoder::m_max_code [private]
data_size dependent max call code
Definition at line 366 of file GenoCallCoder.h.
Referenced by genotypeCallNumToAllele(), initialize(), isHet(), isHom(), and isValidCallNum().
unsigned int GenoCallCoder::m_max_extra_code [private]
version dependent max call code for extra codes
Definition at line 370 of file GenoCallCoder.h.
Referenced by genotypeCallNumToAllele(), initialize(), and isValidCallNum().
unsigned int GenoCallCoder::m_min_code [private]
version dependent min call code
Definition at line 362 of file GenoCallCoder.h.
Referenced by genotypeCallNumToAllele(), initialize(), and isValidCallNum().
unsigned int GenoCallCoder::m_min_extra_code [private]
version dependent min call code for extra codes
Definition at line 368 of file GenoCallCoder.h.
Referenced by genotypeCallNumToAllele(), initialize(), and isValidCallNum().
unsigned int GenoCallCoder::m_min_translatable_code [private]
version dependent min translatable call code
Definition at line 364 of file GenoCallCoder.h.
Referenced by genotypeCallNumToAllele(), initialize(), isHet(), and isHom().
const char GenoCallCoder::m_num2alpha = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'} [static, private]
alphabet map
Definition at line 353 of file GenoCallCoder.h.
Referenced by abstractAlleleIntegersToGenotypeCallNum(), and initialize().
std::vector<AlleleRecord> GenoCallCoder::m_probeset_allele_name_table [private]
table relating abstract alleles to allele names for each marker
Definition at line 380 of file GenoCallCoder.h.
Referenced by alleleNameConvert(), getProbesetIds(), and getValidGenotypeCallCodes().
std::string GenoCallCoder::m_version [private]
version
Definition at line 372 of file GenoCallCoder.h.
Referenced by initialize().
const string GenoCallCoder::m_version_zero_codes [static, private]
Initial value:
 {
  string(""),
  string(""),
  string(""),
  string(""),
  string(""),
  string(""),
  string("AA"),
  string("BB"),
  string("AB"),
  string("AB_A"),
  string("AB_B"),
  string("NN"),
  string(""),
  string(""),
  string(""),
  string("")
}
version zero codes
Definition at line 347 of file GenoCallCoder.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/utils/src/GenoCallCoder.h
C:/f112/affy/sdk/calvin_files/utils/src/GenoCallCoder.cpp