Affymetrix Fusion SDK: MsgSocketHandler Class Reference
MsgSocketHandler Class Reference
An abstract handler for messages.
#include <MsgSocketHandler.h>
Public Member Functions
MsgSocketHandler (int verbosity)
~MsgSocketHandler ()
void checkForKill ()
void openSocket (const std::string &host, const std::string &port)
virtual void progressBegin (int verbosity, const std::string &msg, int total)
void progressStep (int verbosity)
void progressEnd (int verbosity, const std::string &msg)
void message (int level, const std::string &msg, bool delimiter=true)
void setBaseVerbosity (int level)
void finishedMsg ()
void setEndOfLine (const std::string &s)
Protected Attributes
SocketClient * m_Client
Class for reading from and writing to socket.
int m_LocVerbosity
Our verbosity level.
int m_Total
How many steps total are we expecting?
std::vector< std::string > m_Messages
Buffer for messages from the socket.
std::string m_EndLine
Any end to tack on messages (like "\n");.
Detailed Description
An abstract handler for messages.
Definition at line 46 of file MsgSocketHandler.h.
Constructor & Destructor Documentation
MsgSocketHandler::MsgSocketHandler (int verbosity)
Constructor
Parameters:
verbosity - Verbosity level to print at higher -> more messages
Definition at line 36 of file MsgSocketHandler.cpp.
References ProgressHandler::m_Verbosity, and MsgHandler::m_Verbosity.
MsgSocketHandler::~MsgSocketHandler ()
Destructor
Definition at line 41 of file MsgSocketHandler.cpp.
Member Function Documentation
void MsgSocketHandler::checkForKill ()
Check to see if handler has been sent the message to abort by server.
Definition at line 45 of file MsgSocketHandler.cpp.
References Err::errAbort(), FATALERROR, and SOCKETSTOP.
void MsgSocketHandler::finishedMsg ()
Send message indication termination of computation.
Definition at line 119 of file MsgSocketHandler.cpp.
References SocketHandler::COMPLETION, SocketHandler::serializeMap(), and SocketHandler::TEXT.
Referenced by BaseEngine::run().
void MsgSocketHandler::message (int level, const std::string & msg, bool delimiter = true) [virtual]
A message to be processed by the handler.
Parameters:
level - What level of verbosity is associated with this message, higher number == more verbosity.
msg - Message that is to be processed.
delimiter - Should a delimiter be emitted as well?
Implements MsgHandler.
Definition at line 104 of file MsgSocketHandler.cpp.
References FATALERROR, SocketHandler::KILLMSG, SocketHandler::serializeMap(), SOCKETSTOP, SocketHandler::TEXT, ToStr(), and SocketHandler::VERBOSE.
void MsgSocketHandler::openSocket (const std::string & host, const std::string & port)
Open a socket for reading/writing on the specified host and port
Parameters:
host - Ip address, often 127.0.0.1 or localhost
port - Which port to open
Definition at line 56 of file MsgSocketHandler.cpp.
Referenced by BaseEngine::parseArgv().
void MsgSocketHandler::progressBegin (int verbosity, const std::string & msg, int total) [virtual]
Begin a progress reporting. After this initial call the progressStep call will be called N times where N = the parameter total passed in below.
Parameters:
verbosity - What level of verbosity is the progress associated with. Higher levels of verbosity produce more messages.
msg - String message associated with the beginning of this task.
total - Expected number of times that the progressStep() will be called after this.
Implements ProgressHandler.
Definition at line 60 of file MsgSocketHandler.cpp.
References SocketHandler::PROGRESS, SocketHandler::serializeMap(), SocketHandler::TEXT, and ToStr().
void MsgSocketHandler::progressEnd (int verbosity, const std::string & msg) [virtual]
Signals the end of progress report.
Parameters:
verbosity - Level of verbosity associated with this progress report.
msg - Closing message from calling function.
Implements ProgressHandler.
Definition at line 85 of file MsgSocketHandler.cpp.
References SocketHandler::PROGRESS, SocketHandler::serializeMap(), SocketHandler::TEXT, and ToStr().
void MsgSocketHandler::progressStep (int verbosity) [virtual]
This function is called when one unit of work has been done. In general it is expected that the units of work should be roughly equal in size.
Parameters:
verbosity - At what verbosity level should this step be displayed.
Implements ProgressHandler.
Definition at line 74 of file MsgSocketHandler.cpp.
References SocketHandler::PROGRESS, SocketHandler::serializeMap(), SocketHandler::TEXT, and ToStr().
void MsgSocketHandler::setBaseVerbosity (int level)
What level of verbosity is requested. This is a hint to the class and can be ignored if desired.
Parameters:
level - Level below which progress messages are printed.
Reimplemented from MsgHandler.
Definition at line 133 of file MsgSocketHandler.cpp.
void MsgSocketHandler::setEndOfLine (const std::string & s) [inline]
Set end of line suffix
Definition at line 131 of file MsgSocketHandler.h.
References m_EndLine.
Referenced by BaseEngine::parseArgv().
Member Data Documentation
SocketClient* MsgSocketHandler::m_Client [protected]
Class for reading from and writing to socket.
Definition at line 136 of file MsgSocketHandler.h.
std::string MsgSocketHandler::m_EndLine [protected]
Any end to tack on messages (like "\n");.
Definition at line 140 of file MsgSocketHandler.h.
Referenced by setEndOfLine().
int MsgSocketHandler::m_LocVerbosity [protected]
Our verbosity level.
Definition at line 137 of file MsgSocketHandler.h.
std::vector<std::string> MsgSocketHandler::m_Messages [protected]
Buffer for messages from the socket.
Definition at line 139 of file MsgSocketHandler.h.
int MsgSocketHandler::m_Total [protected]
How many steps total are we expecting?
Definition at line 138 of file MsgSocketHandler.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/util/MsgSocketHandler.h
C:/f112/affy/sdk/util/MsgSocketHandler.cpp