Affymetrix Fusion SDK: affxgqc::GQCFileData Class Reference
affxgqc::GQCFileData Class Reference
#include <GQCFileData.h>
Public Member Functions
GQCFileData ()
~GQCFileData ()
void Clear ()
affymetrix_calvin_parameter::ParameterNameValuePairList & QCResults ()
affymetrix_calvin_parameter::ParameterNameValuePairList & SampleSignature ()
affymetrix_calvin_parameter::ParameterNameValuePairList & AnalysisParameters ()
bool Read (const std::string &fileName)
bool Write (const std::string &fileName)
Private Attributes
affymetrix_calvin_parameter::ParameterNameValuePairList qcResults
affymetrix_calvin_parameter::ParameterNameValuePairList sampleSignature
affymetrix_calvin_parameter::ParameterNameValuePairList analysisParameters
Detailed Description
Used to store information in a GQC file.
Definition at line 33 of file GQCFileData.h.
Constructor & Destructor Documentation
GQCFileData::GQCFileData ()
Constructor
Definition at line 328 of file GQCFileData.cpp.
GQCFileData::~GQCFileData ()
Destructor
Definition at line 333 of file GQCFileData.cpp.
Member Function Documentation
affymetrix_calvin_parameter::ParameterNameValuePairList& affxgqc::GQCFileData::AnalysisParameters () [inline]
The analysis parameters
Definition at line 52 of file GQCFileData.h.
References analysisParameters.
void GQCFileData::Clear (void)
Clear the data.
Definition at line 339 of file GQCFileData.cpp.
affymetrix_calvin_parameter::ParameterNameValuePairList& affxgqc::GQCFileData::QCResults () [inline]
The QC analysis results.
Definition at line 46 of file GQCFileData.h.
References qcResults.
bool GQCFileData::Read (const std::string & fileName)
Reads the entire contents of the file.
Parameters:
fileName The name of the file to read.
Returns:
true if successful
Definition at line 347 of file GQCFileData.cpp.
affymetrix_calvin_parameter::ParameterNameValuePairList& affxgqc::GQCFileData::SampleSignature () [inline]
The sample signature
Definition at line 49 of file GQCFileData.h.
References sampleSignature.
bool GQCFileData::Write (const std::string & fileName)
Write the data to the file.
Parameters:
fileName The name of the file to read.
Returns:
true if successful
Definition at line 432 of file GQCFileData.cpp.
References AddBlankReportTable(), AddNameValuePairs(), ANALYSIS_PARAMETERS, CreateGenericReportElement(), GENERIC_REPORT_FILE_ENCODING, QC_RESULTS, SAMPLE_SIGNATURE, and ToXMLCh.
Member Data Documentation
affymetrix_calvin_parameter::ParameterNameValuePairList affxgqc::GQCFileData::analysisParameters [private]
The analysis parameters
Definition at line 74 of file GQCFileData.h.
Referenced by AnalysisParameters().
affymetrix_calvin_parameter::ParameterNameValuePairList affxgqc::GQCFileData::qcResults [private]
The QC analysis results.
Definition at line 68 of file GQCFileData.h.
Referenced by QCResults().
affymetrix_calvin_parameter::ParameterNameValuePairList affxgqc::GQCFileData::sampleSignature [private]
The sample signature
Definition at line 71 of file GQCFileData.h.
Referenced by SampleSignature().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/GQCFileData.h
C:/f112/affy/sdk/file/GQCFileData.cpp