Affymetrix Fusion SDK: CFusionCHPQuantificationDetectionDataCOM Class Reference
CFusionCHPQuantificationDetectionDataCOM Class Reference
#include <FusionCHPQuantificationDetectionDataCOM.h>
Public Member Functions
CFusionCHPQuantificationDetectionDataCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
STDMETHOD() get_FileTypeIdentifiers (VARIANT *pVal)
STDMETHOD() FromBase (IFusionCHPData *baseChp, VARIANT_BOOL *pVal)
STDMETHOD() get_AlgName (BSTR *pVal)
STDMETHOD() get_AlgVersion (BSTR *pVal)
STDMETHOD() get_ArrayType (BSTR *pVal)
STDMETHOD() get_AlgorithmParameters (VARIANT *pVal)
STDMETHOD() get_SummaryParameters (VARIANT *pVal)
STDMETHOD() get_EntryCount (int *pVal)
STDMETHOD() GetQuantificationDetectionEntry (int index, IProbeSetQuantificationDetectionData *pVal)
STDMETHOD() get_FileId (BSTR *pVal)
STDMETHOD() Close ()
Private Attributes
affymetrix_fusion_io::FusionCHPQuantificationDetectionData * chp
Detailed Description
Definition at line 29 of file FusionCHPQuantificationDetectionDataCOM.h.
Constructor & Destructor Documentation
CFusionCHPQuantificationDetectionDataCOM::CFusionCHPQuantificationDetectionDataCOM () [inline]
Definition at line 36 of file FusionCHPQuantificationDetectionDataCOM.h.
Member Function Documentation
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::Close (void)
Definition at line 195 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp.
HRESULT CFusionCHPQuantificationDetectionDataCOM::FinalConstruct () [inline]
Definition at line 56 of file FusionCHPQuantificationDetectionDataCOM.h.
void CFusionCHPQuantificationDetectionDataCOM::FinalRelease () [inline]
Definition at line 61 of file FusionCHPQuantificationDetectionDataCOM.h.
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::FromBase (IFusionCHPData * baseChp, VARIANT_BOOL * pVal)
Definition at line 79 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, and CFusionCHPDataCOM::GetChip().
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::get_AlgName (BSTR * pVal)
Definition at line 92 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgName().
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::get_AlgorithmParameters (VARIANT * pVal)
Definition at line 116 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgParams(), CFusionTagValuePairTypeCOM::SetParam(), affymetrix_fusion_io::FusionTagValuePairType::Tag, and affymetrix_fusion_io::FusionTagValuePairType::Value.
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::get_AlgVersion (BSTR * pVal)
Definition at line 100 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetAlgVersion().
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::get_ArrayType (BSTR * pVal)
Definition at line 108 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, COMStringUtils::ConvertWString(), and affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetArrayType().
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::get_EntryCount (int * pVal)
Definition at line 178 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, and affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetEntryCount().
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::get_FileId (BSTR * pVal)
Definition at line 48 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPQuantificationDetectionData::FileId().
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::get_FileTypeIdentifiers (VARIANT * pVal)
Definition at line 54 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, COMStringUtils::ConvertString(), and affymetrix_fusion_io::FusionCHPData::FileTypeIdentifiers().
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::get_SummaryParameters (VARIANT * pVal)
Definition at line 147 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetSummaryParams(), CFusionTagValuePairTypeCOM::SetParam(), affymetrix_fusion_io::FusionTagValuePairType::Tag, and affymetrix_fusion_io::FusionTagValuePairType::Value.
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::GetQuantificationDetectionEntry (int index, IProbeSetQuantificationDetectionData * pVal)
Definition at line 186 of file FusionCHPQuantificationDetectionDataCOM.cpp.
References chp, CProbeSetQuantificationDetectionDataCOM::Data(), and affymetrix_fusion_io::FusionCHPQuantificationDetectionData::GetQuantificationDetectionEntry().
STDMETHODIMP CFusionCHPQuantificationDetectionDataCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 32 of file FusionCHPQuantificationDetectionDataCOM.cpp.
Member Data Documentation
affymetrix_fusion_io::FusionCHPQuantificationDetectionData* CFusionCHPQuantificationDetectionDataCOM::chp [private]
Definition at line 68 of file FusionCHPQuantificationDetectionDataCOM.h.
Referenced by Close(), FromBase(), get_AlgName(), get_AlgorithmParameters(), get_AlgVersion(), get_ArrayType(), get_EntryCount(), get_FileId(), get_FileTypeIdentifiers(), get_SummaryParameters(), and GetQuantificationDetectionEntry().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPQuantificationDetectionDataCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionCHPQuantificationDetectionDataCOM.cpp