Affymetrix Fusion SDK: COMStringUtils Class Reference
COMStringUtils Class Reference
#include <COMStringUtils.h>
Static Public Member Functions
static BSTR ConvertString (const std::string &str)
static BSTR ConvertWString (const std::wstring &str)
static std::string ConvertString (BSTR str)
static std::wstring ConvertWString (BSTR str)
Private Member Functions
COMStringUtils ()
Detailed Description
Definition at line 23 of file COMStringUtils.h.
Constructor & Destructor Documentation
COMStringUtils::COMStringUtils () [private]
Definition at line 25 of file COMStringUtils.cpp.
Member Function Documentation
static BSTR COMStringUtils::ConvertString (const std::string & str) [static]
Referenced by CFusionCDFDataCOM::get_ChipType(), CFusionCDFDataCOM::get_ChipTypes(), CFusionCDFDataCOM::get_Error(), CFusionCHPQuantificationDetectionDataCOM::get_FileId(), CFusionCHPQuantificationDataCOM::get_FileId(), CFusionCHPMultiDataDataCOM::get_FileId(), CFusionCHPLegacyDataCOM::get_FileId(), CFusionCHPDataCOM::get_FileId(), CFusionCELDataCOM::get_FileId(), CFusionPSIFileCOM::get_FileName(), CFusionCELDataCOM::get_FileName(), CFusionCDFDataCOM::get_FileName(), CFusionCHPLegacyDataCOM::get_FileTypeIdentifier(), CFusionCHPDataCOM::get_FileTypeIdentifier(), CFusionCHPQuantificationDetectionDataCOM::get_FileTypeIdentifiers(), CFusionCHPQuantificationDataCOM::get_FileTypeIdentifiers(), CFusionCHPMultiDataDataCOM::get_FileTypeIdentifiers(), CFusionCHPLegacyDataCOM::get_FileTypeIdentifiers(), CFusionCHPDataCOM::get_FileTypeIdentifiers(), CFusionCDFFileHeaderCOM::get_GUID(), CFusionCDFDataCOM::get_GUID(), CFusionCDFFileHeaderCOM::get_IntegrityMd5(), CFusionCDFDataCOM::get_IntegrityMd5(), CProbeSetQuantificationDetectionDataCOM::get_name(), CProbeSetQuantificationDataCOM::get_name(), CProbeSetMultiDataGenotypeDataCOM::get_name(), CProbeSetMultiDataExpressionDataCOM::get_name(), CProbeSetMultiDataCytoRegionDataCOM::get_name(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::get_name(), CProbeSetMultiDataCopyNumberDataCOM::get_name(), CFusionCDFProbeGroupInformationCOM::get_Name(), CFusionCDFFileHeaderCOM::get_Reference(), CFusionGenotypeProbeSetResultsCOM::GetAlleleCallString(), CFusionExpressionProbeSetResultsCOM::GetChangeString(), CFusionExpressionProbeSetResultsCOM::GetDetectionString(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), CFusionPSIFileCOM::GetProbeSetName(), CFusionCHPMultiDataDataCOM::GetProbeSetName(), CFusionCHPLegacyDataCOM::GetProbeSetName(), CFusionCDFDataCOM::GetProbeSetName(), CFusionCDFDataCOM::IsCalvinCompatibleFile(), CFusionCDFDataCOM::IsXDACompatibleFile(), CFusionPSIFileCOM::put_FileName(), CFusionCELDataCOM::put_FileName(), CFusionCDFDataCOM::put_FileName(), CFusionCHPDataRegCOM::Read(), and CFusionCHPDataRegCOM::ReadHeader().
string COMStringUtils::ConvertString (BSTR str) [static]
Definition at line 41 of file COMStringUtils.cpp.
wstring COMStringUtils::ConvertWString (BSTR str) [static]
Definition at line 47 of file COMStringUtils.cpp.
static BSTR COMStringUtils::ConvertWString (const std::wstring & str) [static]
Referenced by CFusionCELDataCOM::get_Alg(), CFusionCHPQuantificationDetectionDataCOM::get_AlgName(), CFusionCHPQuantificationDataCOM::get_AlgName(), CFusionCHPMultiDataDataCOM::get_AlgName(), CFusionCHPHeaderCOM::get_AlgName(), CFusionCELDataCOM::get_AlgorithmParameters(), CFusionCHPQuantificationDetectionDataCOM::get_AlgVersion(), CFusionCHPQuantificationDataCOM::get_AlgVersion(), CFusionCHPMultiDataDataCOM::get_AlgVersion(), CFusionCHPHeaderCOM::get_AlgVersion(), CFusionCHPQuantificationDetectionDataCOM::get_ArrayType(), CFusionCHPQuantificationDataCOM::get_ArrayType(), CFusionCHPMultiDataDataCOM::get_ArrayType(), CFusionCHPHeaderCOM::get_ChipType(), CFusionCELDataCOM::get_ChipType(), CFusionCELDataCOM::get_DatHeader(), CFusionCELDataCOM::get_Error(), CFusionCELDataCOM::get_Header(), CFusionCELDataCOM::get_LibraryPackageName(), CFusionCELDataCOM::get_MasterFileName(), CFusionCELDataCOM::get_Params(), CFusionCHPHeaderCOM::get_ParentCellFile(), CFusionCHPHeaderCOM::get_ProgID(), CFusionTagValuePairTypeCOM::get_Tag(), CFusionTagValuePairTypeCOM::get_Value(), CFusionCHPHeaderCOM::GetAlgorithmParameter(), CFusionCELDataCOM::GetAlgorithmParameter(), CFusionCHPHeaderCOM::GetAlgorithmParameterName(), CFusionCELDataCOM::GetAlgorithmParameterTag(), CFusionCELDataCOM::GetChannels(), CFusionCELDataCOM::GetHeaderKey(), CProbeSetMultiDataGenotypeDataCOM::GetMetric(), CProbeSetMultiDataExpressionDataCOM::GetMetric(), CProbeSetMultiDataCytoRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetric(), CProbeSetMultiDataCopyNumberDataCOM::GetMetric(), CFusionCHPMultiDataDataCOM::GetMetricColumnName(), CProbeSetMultiDataGenotypeDataCOM::GetMetricName(), CProbeSetMultiDataExpressionDataCOM::GetMetricName(), CProbeSetMultiDataCytoRegionDataCOM::GetMetricName(), CProbeSetMultiDataCopyNumberVariationRegionDataCOM::GetMetricName(), CProbeSetMultiDataCopyNumberDataCOM::GetMetricName(), CFusionCHPHeaderCOM::GetSummaryParameter(), CFusionCHPHeaderCOM::GetSummaryParameterName(), CFusionCHPMultiDataDataCOM::InitializeGetGenotypeEntries(), and CFusionCELDataCOM::SetActiveDataGroup().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/COMStringUtils.h
C:/f112/affy/sdk/calvin_files/fusion/com/COMStringUtils.cpp