Affymetrix Fusion SDK: CFusionTagValuePairTypeCOM Class Reference
CFusionTagValuePairTypeCOM Class Reference
#include <FusionTagValuePairTypeCOM.h>
Public Member Functions
CFusionTagValuePairTypeCOM ()
STDMETHOD() InterfaceSupportsErrorInfo (REFIID riid)
HRESULT FinalConstruct ()
void FinalRelease ()
void SetParam (affymetrix_fusion_io::FusionTagValuePairType &p)
STDMETHOD() get_Tag (BSTR *pVal)
STDMETHOD() get_Value (BSTR *pVal)
Private Attributes
affymetrix_fusion_io::FusionTagValuePairType param
Detailed Description
Definition at line 29 of file FusionTagValuePairTypeCOM.h.
Constructor & Destructor Documentation
CFusionTagValuePairTypeCOM::CFusionTagValuePairTypeCOM () [inline]
Definition at line 36 of file FusionTagValuePairTypeCOM.h.
Member Function Documentation
HRESULT CFusionTagValuePairTypeCOM::FinalConstruct () [inline]
Definition at line 55 of file FusionTagValuePairTypeCOM.h.
void CFusionTagValuePairTypeCOM::FinalRelease () [inline]
Definition at line 60 of file FusionTagValuePairTypeCOM.h.
STDMETHODIMP CFusionTagValuePairTypeCOM::get_Tag (BSTR * pVal)
Definition at line 42 of file FusionTagValuePairTypeCOM.cpp.
References COMStringUtils::ConvertWString(), param, and affymetrix_fusion_io::FusionTagValuePairType::Tag.
STDMETHODIMP CFusionTagValuePairTypeCOM::get_Value (BSTR * pVal)
Definition at line 48 of file FusionTagValuePairTypeCOM.cpp.
References COMStringUtils::ConvertWString(), affymetrix_fusion_io::FusionTagValuePairType::DetailedType(), param, affymetrix_calvin_parameter::ParameterNameValueType::ToString(), and affymetrix_fusion_io::FusionTagValuePairType::Value.
STDMETHODIMP CFusionTagValuePairTypeCOM::InterfaceSupportsErrorInfo (REFIID riid)
Definition at line 27 of file FusionTagValuePairTypeCOM.cpp.
void CFusionTagValuePairTypeCOM::SetParam (affymetrix_fusion_io::FusionTagValuePairType & p) [inline]
Definition at line 68 of file FusionTagValuePairTypeCOM.h.
Referenced by CFusionCHPQuantificationDetectionDataCOM::get_AlgorithmParameters(), CFusionCHPQuantificationDataCOM::get_AlgorithmParameters(), CFusionCHPMultiDataDataCOM::get_AlgorithmParameters(), CFusionCHPHeaderCOM::get_AlgorithmParameters(), CFusionCHPQuantificationDetectionDataCOM::get_SummaryParameters(), CFusionCHPQuantificationDataCOM::get_SummaryParameters(), CFusionCHPMultiDataDataCOM::get_SummaryParameters(), CFusionCHPHeaderCOM::get_SummaryParameters(), CFusionCHPMultiDataDataCOM::GetDataSetHeaderParameters(), and CFusionCELDataCOM::GetParameters().
Member Data Documentation
affymetrix_fusion_io::FusionTagValuePairType CFusionTagValuePairTypeCOM::param [private]
Definition at line 65 of file FusionTagValuePairTypeCOM.h.
Referenced by get_Tag(), and get_Value().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/fusion/com/FusionTagValuePairTypeCOM.h
C:/f112/affy/sdk/calvin_files/fusion/com/FusionTagValuePairTypeCOM.cpp