Affymetrix Fusion SDK: affxcel::CCELFileData Class Reference
affxcel::CCELFileData Class Reference
CEL file object.
#include <CELFileData.h>
Public Types
enum {
UNKNOWN = 0, TEXT_CEL = 1, XDA_BCEL = 2, TRANSCRIPTOME_BCEL = 3,
COMPACT_BCEL = 4
}
CEL file formats.
enum { CEL_ALL = 1, CEL_DATA = 2, CEL_OUTLIER = 4, CEL_MASK = 8 }
CEL file reading states.
Public Member Functions
CCELFileData ()
Default constructor.
~CCELFileData ()
Destructor.
void SetError (const std::string &str)
Set error string.
void SetError (const char *str)
std::string GetError ()
Retrieve error string.
affxcel::CCELFileData * GetThisPtr ()
Retrieve the pointer of the current object instance.
void SetFileName (const char *str)
Set CEL file name.
std::string GetFileName () const
Retrieve CEL file name.
std::string GetHeaderKey (const char *key)
Retrieve header value in string by specifying header key.
int GetVersion ()
Call affxcel::CCELFileHeaderData::GetVersion() to retrieve file format version number.
int GetCols ()
Call affxcel::CCELFileHeaderData::GetCols() to retrieve number of columns in array.
int GetRows ()
Call affxcel::CCELFileHeaderData::GetRows() to retrieve number of rows in array.
int GetNumCells ()
Call affxcel::CCELFileHeaderData::GetNumCells() to retrieve number of cells in array.
std::string GetHeaderString ()
Call affxcel::CCELFileHeaderData::GetHeader() to retrieve header in a single string.
CCELFileHeaderData & GetHeader ()
Gets the header object.
std::string GetAlg ()
Call affxcel::CCELFileHeaderData::GetAlg() to retrieve algorithm name.
std::string GetParams ()
Call affxcel::CCELFileHeaderData::GetParams() to retrieve algorithm parameters.
std::string GetAlgorithmParameter (const char *tag)
Call affxcel::CCELFileHeaderData::GetAlgorithmParameter() to retrieve algorithm parameter of specified tag.
std::string GetAlgorithmParameterTag (int index)
int GetNumberAlgorithmParameters ()
std::string GetAlgorithmParameters ()
Call affxcel::CCELFileHeaderData::GetAlgorithmParameters() to retrieve algorithm parameters.
std::string GetDatHeader ()
Call affxcel::CCELFileHeaderData::GetDatHeader() to retrieve DAT header.
std::string GetChipType ()
Call affxcel::CCELFileHeaderData::GetChipType() to retrieve chip type.
int GetCellMargin ()
Call affxcel::CCELFileHeaderData::GetCellMargin() to retrieve cell margin.
uint32_t GetNumOutliers ()
Call affxcel::CCELFileHeaderData::GetNumOutliers() to retrieve number of outliers.
uint32_t GetNumMasked ()
Call affxcel::CCELFileHeaderData::GetNumMasked() to retrieve number of masked cells.
GridCoordinatesType GetGridCorners ()
Call affxcel::CCELFileHeaderData::GetGridCorners() to retrieve grid coordinates.
int IndexToX (int index)
Get x coordinates from index.
int IndexToY (int index)
Get y coordinates from index.
int XYToIndex (int x, int y)
Convert x, y coordinates to index.
void GetEntry (int index, CELFileEntryType &entry)
Retrieve entry of specified cell for xda and text formats.
void GetEntry (int x, int y, CELFileEntryType &entry)
Retrieve entry of specified cell for xda and text formats.
void GetTranscriptomeEntry (int index, CELFileTranscriptomeEntryType &entry)
Retrieve entry of specified cell for transcriptome bcel format.
void GetTranscriptomeEntry (int x, int y, CELFileTranscriptomeEntryType &entry)
Retrieve entry of specified cell for transcriptome bcel format.
float GetIntensity (int index)
Retrieve intensity of specified cell.
int GetIntensities (int index, std::vector< float > &intensities)
Get a vector of intensities with one call.
float GetIntensity (int x, int y)
Retrieve intensity of specified cell.
float GetStdv (int index)
Retrieve standard deviation of specified cell.
float GetStdv (int x, int y)
Retrieve standard deviation of specified cell.
short GetPixels (int index)
Retrieve number of pixels of specified cell.
short GetPixels (int x, int y)
Retrieve number of pixels of specified cell.
bool IsMasked (int x, int y)
Determine if specified cell is masked.
bool IsMasked (int index)
Determine if specified cell is masked.
bool IsOutlier (int x, int y)
Determine if specified cell is outlier.
bool IsOutlier (int index)
Determine if specified cell is outlier.
void Close ()
Unmap file view and reset data pointer.
uint32_t GetFileSize ()
Retrieve file size.
bool Exists ()
Check if the CEL file exists by using the already set full path name.
std::string ResolveName ()
bool ReadHeader ()
Determine CEL file format and call appropriate function to read header section only.
bool Read (bool bIncludeMaskAndOutliers=true)
Determine CEL file format and call appropriate function to read file.
bool IsXDACompatibleFile ()
Determine if CEL file is in xda format.
bool IsVersion3CompatibleFile ()
Determine if CEL file is in text (version 3) format.
bool IsTranscriptomeBcelFile ()
Determine if CEL file is in transcriptome binary format.
bool IsCompactCelFile ()
Determine if CEL file is in compact binary format.
bool IsUnsupportedCompactCelFile ()
Determine if CEL file is in unsupported compact binary format.
bool ReadEx (const char *filename=0, int nState=CEL_ALL)
Determine CEL file format and call appropriate function to read file using the specified file name.
int GetReadState ()
void Clear ()
Reset content and deallocate memory.
int GetFileFormat ()
void SetFileFormat (int i)
Set CEL file format to determine the appropriate data storage in cell.
void SetAlgorithmName (const char *str)
Call CCELFileHeaderData::SetAlg() to set algorithm name.
void SetAlgorithmParameter (const char *tag, const char *value)
Call CCELFileHeaderData::SetAlgorithmParameter() to add algorithm parameter.
void AddAlgorithmParameter (const char *tag, const char *value)
Call CCELFileHeaderData::AddAlgorithmParameter() to add algorithm parameter.
void SetAddAlgorithmParameter (const char *tag, const char *value)
Call CCELFileHeaderData::SetAddAlgorithmParameter() to add algorithm parameter.
void SetDimensions (int rows, int cols)
Set array dimensions in header section and allocate memory for intensity data.
void SetChipType (const char *str)
Set chip type and regenerate header string.
void SetMargin (int margin)
Set cell margin.
void SetGridCorners (GridCoordinatesType grid)
Call CCELFileHeaderData::SetGridCorners() to set grid coordinates.
void SetCellEntry (int x, int y, CELFileEntryType *pEntry)
Set cell file entry.
void SetCellEntry (int index, CELFileEntryType *pEntry)
Set cell file entry.
void AllocateEntries ()
Allocate memory for cell entries.
void SetTranscriptomeCellEntry (int x, int y, CELFileTranscriptomeEntryType *pEntry)
Set cell file entry.
void SetTranscriptomeCellEntry (int index, CELFileTranscriptomeEntryType *pEntry)
Set cell file entry.
void AllocateTranscriptomeEntries ()
Allocate memory for cell entries.
void SetIntensity (int index, float intensity)
Set intensity of specified cell.
void SetIntensity (int x, int y, float intensity)
Set intensity of specified cell.
void SetStdv (int index, float stdev)
Set standard deviation intensity of specified cell.
void SetStdv (int x, int y, float stdev)
Set standard deviation intensity of specified cell.
void SetPixels (int index, short pixels)
Set number of pixels of specified cell.
void SetPixels (int x, int y, short pixels)
Set number of pixels of specified cell.
void SetMask (int index, bool mask)
Set if specified cell is masked.
void SetMask (int x, int y, bool masked)
Set if specified cell is masked.
void SetOutlier (int index, bool outlier)
Set if specified cell is outlier.
void SetOutlier (int x, int y, bool outlier)
Set if specified cell is outlier.
void Munmap ()
Unmap file view.
void EnsureNotMmapped ()
Static Public Member Functions
static int XYToIndex (int x, int y, int r, int c)
Protected Member Functions
bool Open (bool bReadHeaderOnly=false)
Determine the CEL file format and call corresponding function to read it.
bool ReadTextCel (bool bReadHeaderOnly=false)
Read text CEL file in memory.
bool ReadXDABCel (bool bReadHeaderOnly=false)
Read xda format CEL file using memory mapping.
bool ReadTranscriptomeBCel (bool bReadHeaderOnly=false)
Read transcriptome binary CEL file using memory mapping.
bool ReadCompactBCel (bool bReadHeaderOnly=false)
Read compact binary CEL file using memory mapping.
void DetermineFileFormat ()
Determine the CEL file format by checking teh file against each of the format type.
unsigned short RoundNumber (float f)
Round floating point to integer.
Protected Attributes
int m_FileFormat
CEL file format.
std::string m_strError
Error string.
std::string m_FileName
CEL file name without path.
CCELFileHeaderData m_HeaderData
CEL file header data object.
CELFileEntryType * m_pEntries
Pointer to intensity entries for each cell (used for text and xda formats)
CELFileTranscriptomeEntryType * m_pTransciptomeEntries
Pointer to intensity entries for each cell (used for transcriptome bcel format)
unsigned short * m_pMeanIntensities
Pointer to intensity entries for each cell (used for compact cel format)
std::map< int, bool > m_MaskedCells
STL map for masked cell coordinates.
std::map< int, bool > m_Outliers
STL map for outlier coordinates.
int m_nReadState
CEL file reading state.
bool m_bReadMaskedCells
Flag to determine if masked cell data should be read.
bool m_bReadOutliers
Flag to determine if outlier data should be read.
FILE * m_File
Pointer to file object.
size_t m_MapLen
Memory mapping size used by mmap (POSIX)
char * m_lpData
Pointer to memory mapping data.
void * m_lpFileMap
Pointer to memory mapping file view.
Detailed Description
CEL file object.
affxcel::CCELFileData
Include read and write support of the following file formats:
text (version 3)
xda binary (version 4)
transcriptome binary (internal use only)
compact binary (not supported by software other than Bruce)
All file formats include the same header information. The intensity data for each cell are stored as follows:
text format
mean (data type: float - 4 bytes)
stdev (data type: float - 4 bytes)
pixels (data type: short - 2 bytes)
xda binary format
mean (data type: float - 4 bytes)
stdev (data type: float - 4 bytes)
pixels (data type: short - 2 bytes)
trancriptome binary format
mean (data type: unsigned short - 2 bytes)
stdev (data type: unsigned short - 2 bytes)
pixels (data type: unsigned char - 1 byte)
compact binary format
mean (data type: unsigned short - 2 bytes)
Definition at line 536 of file CELFileData.h.
Member Enumeration Documentation
anonymous enum
CEL file formats.
Enumerator:
UNKNOWN
TEXT_CEL
XDA_BCEL
TRANSCRIPTOME_BCEL
COMPACT_BCEL
Definition at line 540 of file CELFileData.h.
anonymous enum
CEL file reading states.
Enumerator:
CEL_ALL
CEL_DATA
CEL_OUTLIER
CEL_MASK
Definition at line 550 of file CELFileData.h.
Constructor & Destructor Documentation
CCELFileData::CCELFileData ()
Default constructor.
Constructor
public constructor CCELFileData
Returns:
void
Definition at line 2878 of file CELFileData.cpp.
References CEL_ALL, m_bReadMaskedCells, m_bReadOutliers, m_FileFormat, m_FileName, m_lpData, m_lpFileMap, m_nReadState, m_pEntries, m_pMeanIntensities, m_pTransciptomeEntries, m_strError, and XDA_BCEL.
CCELFileData::~CCELFileData ()
Destructor.
Destructor
public destructor ~CCELFileData
Returns:
void
Definition at line 2899 of file CELFileData.cpp.
References Clear().
Member Function Documentation
void CCELFileData::AddAlgorithmParameter (const char * tag, const char * value)
Call CCELFileHeaderData::AddAlgorithmParameter() to add algorithm parameter.
Adds a parameter to the parameter list.
Parameters:
tag The parameter name.
value The parameter value.
public AddAlgorithmParameter
Parameters:
tag const char * Algorithm parameter tag
value const char * Algorithm paramter value
Returns:
void
See also:
CCELFileHeaderData::AddAlgorithmParameter
Definition at line 2955 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::AddAlgorithmParameter(), and m_HeaderData.
void CCELFileData::AllocateEntries ()
Allocate memory for cell entries.
Allocates entries for a text or XDA file.
public AllocateEntries
Returns:
void
Definition at line 3091 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCells(), m_HeaderData, and m_pEntries.
void CCELFileData::AllocateTranscriptomeEntries ()
Allocate memory for cell entries.
Allocates memory for the transcriptome file type entries.
public AllocateEntries
Returns:
void
Definition at line 3130 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCells(), m_HeaderData, and m_pTransciptomeEntries.
void CCELFileData::Clear (void)
Reset content and deallocate memory.
Clears the members.
public Clear
Returns:
void
Definition at line 2039 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::Clear(), m_HeaderData, m_MaskedCells, m_Outliers, m_pEntries, m_pMeanIntensities, m_pTransciptomeEntries, and Munmap().
Referenced by Close(), ReadCompactBCel(), ReadTextCel(), ReadTranscriptomeBCel(), ReadXDABCel(), and ~CCELFileData().
void CCELFileData::Close (void)
Unmap file view and reset data pointer.
Closes the file
public Close
Returns:
void
Definition at line 2112 of file CELFileData.cpp.
References Clear().
Referenced by Open(), Read(), ReadCompactBCel(), ReadEx(), ReadHeader(), ReadTranscriptomeBCel(), ReadXDABCel(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
void CCELFileData::DetermineFileFormat () [protected]
Determine the CEL file format by checking teh file against each of the format type.
Determines the type of CEL file.
private DetermineFileFormat
Returns:
void
See also:
IsXDACompatibleFile, IsTranscriptomeBcelFile, IsCompactCelFile
Definition at line 2837 of file CELFileData.cpp.
References COMPACT_BCEL, IsCompactCelFile(), IsTranscriptomeBcelFile(), IsUnsupportedCompactCelFile(), IsXDACompatibleFile(), m_FileFormat, TEXT_CEL, TRANSCRIPTOME_BCEL, and XDA_BCEL.
Referenced by Open().
void CCELFileData::EnsureNotMmapped ()
Store data in memory if CEL file is memory mapped.
public EnsureNotMmapped
Returns:
void
Definition at line 1662 of file CELFileData.cpp.
References COMPACT_BCEL, GetCols(), GetRows(), m_FileFormat, m_lpFileMap, m_pEntries, m_pMeanIntensities, m_pTransciptomeEntries, Munmap(), TRANSCRIPTOME_BCEL, and XDA_BCEL.
bool CCELFileData::Exists ()
Check if the CEL file exists by using the already set full path name.
Checks if the file exists.
Returns:
True if the file exists.
public Exists
Returns:
bool true if exists; false otherwise
Definition at line 661 of file CELFileData.cpp.
References ResolveName().
std::string affxcel::CCELFileData::GetAlg () [inline]
Call affxcel::CCELFileHeaderData::GetAlg() to retrieve algorithm name.
inline public GetAlg
Returns:
std::string Algorithm name
See also:
affxcel::CCELFileHeaderData::GetAlg
Definition at line 740 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetAlg(), and m_HeaderData.
Referenced by GetHeaderKey().
std::string affxcel::CCELFileData::GetAlgorithmParameter (const char * tag) [inline]
Call affxcel::CCELFileHeaderData::GetAlgorithmParameter() to retrieve algorithm parameter of specified tag.
inline public GetAlgorithmParameter
Parameters:
tag const char* Algorithm parameter tag
Returns:
std::string Algorithm parameter value
See also:
affxcel::CCELFileHeaderData::GetAlgorithmParameter
Definition at line 757 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetAlgorithmParameter(), and m_HeaderData.
void CelFileData::GetAlgorithmParameters () [inline]
Call affxcel::CCELFileHeaderData::GetAlgorithmParameters() to retrieve algorithm parameters.
inline public GetAlgorithmParameters
Returns:
std::string Algorithm parameters
See also:
affxcel::CCELFileHeaderData::GetAlgorithmParameters
Definition at line 776 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetAlgorithmParameters(), and m_HeaderData.
std::string affxcel::CCELFileData::GetAlgorithmParameterTag (int index) [inline]
Retrieves the algorithm parameter name (tag) for a given index position.
Parameters:
index The zero based index to the parameter array (0 to the number of alg parameters - 1).
Returns:
The parameter name (tag).
Definition at line 763 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetAlgorithmParameterTag(), and m_HeaderData.
int affxcel::CCELFileData::GetCellMargin () [inline]
Call affxcel::CCELFileHeaderData::GetCellMargin() to retrieve cell margin.
inline public GetCellMargin
Returns:
int Cell margin
See also:
affxcel::CCELFileHeaderData::GetCellMargin
Definition at line 800 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetMargin(), and m_HeaderData.
Referenced by affymetrix_fusion_io::GCOSCELDataAdapter::GetCellMargin().
std::string affxcel::CCELFileData::GetChipType () [inline]
Call affxcel::CCELFileHeaderData::GetChipType() to retrieve chip type.
inline public GetChipType
Returns:
std::string Chip type
See also:
affxcel::CCELFileHeaderData::GetChipType
Definition at line 792 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetChipType(), and m_HeaderData.
int affxcel::CCELFileData::GetCols () [inline]
Call affxcel::CCELFileHeaderData::GetCols() to retrieve number of columns in array.
inline public GetCols
Returns:
int Number of columns in array
See also:
affxcel::CCELFileHeaderData::GetCols
Definition at line 701 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetCols(), and m_HeaderData.
Referenced by EnsureNotMmapped(), affymetrix_fusion_io::GCOSCELDataAdapter::GetCols(), GetHeaderKey(), ReadCompactBCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
std::string affxcel::CCELFileData::GetDatHeader () [inline]
Call affxcel::CCELFileHeaderData::GetDatHeader() to retrieve DAT header.
inline public GetDatHeader
Returns:
std::string DAT header
See also:
affxcel::CCELFileHeaderData::GetDatHeader
Definition at line 784 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetDatHeader(), and m_HeaderData.
Referenced by affymetrix_fusion_io::GCOSCELDataAdapter::GetDatHeader(), and GetHeaderKey().
void CCELFileData::GetEntry (int index, CELFileEntryType & entry)
Retrieve entry of specified cell for xda and text formats.
Retrieves a CEL file entry.
Parameters:
index The index to the CEL file entries.
entry The CEL file entry.
public GetEntry
Parameters:
index int Cell index
entry CELFileEntryType& Cell entry
Definition at line 2336 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCells(), GetIntensity(), GetPixels(), GetStdv(), affxcel::_CELFileEntryType::Intensity, m_HeaderData, affxcel::_CELFileEntryType::Pixels, and affxcel::_CELFileEntryType::Stdv.
Referenced by GetEntry().
void CCELFileData::GetEntry (int x, int y, CELFileEntryType & entry)
Retrieve entry of specified cell for xda and text formats.
Retrieves a CEL file entry.
Parameters:
x The X coordinate.
y The Y coordinate.
entry The CEL file entry.
public GetEntry
Parameters:
x int X coordinates
y int Y coordinates
entry CELFileEntryType& Cell entry
Definition at line 2321 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), GetEntry(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, and XYToIndex().
std::string affxcel::CCELFileData::GetError () [inline]
Retrieve error string.
inline public GetError
Returns:
std::string Error string
Definition at line 660 of file CELFileData.h.
References m_strError.
int affxcel::CCELFileData::GetFileFormat () [inline]
Get the file format type.
Returns:
The file format type.
Definition at line 1037 of file CELFileData.h.
References m_FileFormat.
std::string affxcel::CCELFileData::GetFileName () const [inline]
Retrieve CEL file name.
inline public constant GetFileName
Returns:
std::string File name
Definition at line 682 of file CELFileData.h.
References m_FileName.
uint32_t CCELFileData::GetFileSize ()
Retrieve file size.
Returns the file size.
Returns:
The file size.
public GetFileSize
Returns:
uint32_t Size in bytes
Definition at line 697 of file CELFileData.cpp.
References ResolveName().
Referenced by ReadCompactBCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
GridCoordinatesType affxcel::CCELFileData::GetGridCorners () [inline]
Call affxcel::CCELFileHeaderData::GetGridCorners() to retrieve grid coordinates.
inline public GetGridCorners
Returns:
GridCoordinatesType Grid coordinates
See also:
affxcel::CCELFileHeaderData::GetGridCorners
Definition at line 824 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetGridCorners(), and m_HeaderData.
Referenced by GetHeaderKey().
CCELFileHeaderData& affxcel::CCELFileData::GetHeader () [inline]
Gets the header object.
public GetHeader
Returns:
CCELFileHeaderData The header object.
Definition at line 732 of file CELFileData.h.
References m_HeaderData.
std::string CCELFileData::GetHeaderKey (const char * key)
Retrieve header value in string by specifying header key.
public GetHeaderKey
Parameters:
key const char * Header section key
Returns:
std::string Header section value
Definition at line 2218 of file CELFileData.cpp.
References GetAlg(), GetCols(), GetDatHeader(), GetGridCorners(), GetHeaderString(), GetNumCells(), GetNumMasked(), GetNumOutliers(), GetParams(), GetRows(), GetVersion(), and SVALUE_LENGTH.
std::string affxcel::CCELFileData::GetHeaderString () [inline]
Call affxcel::CCELFileHeaderData::GetHeader() to retrieve header in a single string.
inline public GetHeaderString
Returns:
std::string Header string
See also:
affxcel::CCELFileHeaderData::GetHeader
Definition at line 725 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetHeader(), and m_HeaderData.
Referenced by GetHeaderKey().
int CCELFileData::GetIntensities (int index, std::vector< float > & intensities)
Get a vector of intensities with one call.
Parameters:
index starting index
intensities vector to fill.
Returns:
non-zero on error
Definition at line 2434 of file CELFileData.cpp.
References COMPACT_BCEL, affxcel::CCELFileHeaderData::GetCells(), m_FileFormat, m_HeaderData, m_pEntries, m_pMeanIntensities, m_pTransciptomeEntries, MmGetFloat_I(), MmGetUInt16_I(), MmGetUInt16_N(), TEXT_CEL, TRANSCRIPTOME_BCEL, and XDA_BCEL.
float CCELFileData::GetIntensity (int index)
Retrieve intensity of specified cell.
Retrieves a CEL file intensity.
Parameters:
index The index to the CEL file entries.
Returns:
The CEL file intensity.
public GetIntensity
Parameters:
index int Cell index
Returns:
float intensity
Definition at line 2400 of file CELFileData.cpp.
References COMPACT_BCEL, affxcel::CCELFileHeaderData::GetCells(), m_FileFormat, m_HeaderData, m_pEntries, m_pMeanIntensities, m_pTransciptomeEntries, MmGetFloat_I(), MmGetUInt16_I(), MmGetUInt16_N(), TEXT_CEL, TRANSCRIPTOME_BCEL, and XDA_BCEL.
Referenced by GetEntry(), GetIntensity(), GetTranscriptomeEntry(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
float CCELFileData::GetIntensity (int x, int y)
Retrieve intensity of specified cell.
Retrieves a CEL file intensity.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
The CEL file intensity.
public GetIntensity
Parameters:
x int X coordinates
y int Y coordinates
Returns:
float intensity
Definition at line 2385 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), GetIntensity(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, and XYToIndex().
int affxcel::CCELFileData::GetNumberAlgorithmParameters () [inline]
Retrieves the number of algorithm parameters.
Returns:
The number of algorithm parameters.
Definition at line 768 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetNumberAlgorithmParameters(), and m_HeaderData.
Referenced by affymetrix_fusion_io::GCOSCELDataAdapter::GetNumberAlgorithmParameters().
int affxcel::CCELFileData::GetNumCells () [inline]
Call affxcel::CCELFileHeaderData::GetNumCells() to retrieve number of cells in array.
inline public GetNumCells
Returns:
int Number of cells in array
See also:
affxcel::CCELFileHeaderData::GetNumCells
Definition at line 717 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetCells(), and m_HeaderData.
Referenced by GetHeaderKey(), and affymetrix_fusion_io::GCOSCELDataAdapter::GetNumCells().
uint32_t affxcel::CCELFileData::GetNumMasked () [inline]
Call affxcel::CCELFileHeaderData::GetNumMasked() to retrieve number of masked cells.
inline public GetNumMasked
Returns:
uint32_t Number of masked cells
See also:
affxcel::CCELFileHeaderData::GetNumMasked
Definition at line 816 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetMasked(), and m_HeaderData.
Referenced by GetHeaderKey(), affymetrix_fusion_io::GCOSCELDataAdapter::GetNumMasked(), ReadCompactBCel(), and ReadXDABCel().
uint32_t affxcel::CCELFileData::GetNumOutliers () [inline]
Call affxcel::CCELFileHeaderData::GetNumOutliers() to retrieve number of outliers.
inline public GetNumOutliers
Returns:
uint32_t Number of outliers
See also:
affxcel::CCELFileHeaderData::GetNumOutliers
Definition at line 808 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetOutliers(), and m_HeaderData.
Referenced by GetHeaderKey(), affymetrix_fusion_io::GCOSCELDataAdapter::GetNumOutliers(), ReadCompactBCel(), and ReadXDABCel().
std::string affxcel::CCELFileData::GetParams () [inline]
Call affxcel::CCELFileHeaderData::GetParams() to retrieve algorithm parameters.
inline public GetParams
Returns:
std::string Algorithm parameters
See also:
affxcel::CCELFileHeaderData::GetParams
Definition at line 748 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetAlgorithmParameters(), and m_HeaderData.
Referenced by GetHeaderKey().
short CCELFileData::GetPixels (int index)
Retrieve number of pixels of specified cell.
Retrieves a CEL file pixel count.
Parameters:
index The index to the CEL file entries.
Returns:
The CEL file pixel count.
public GetPixels
Parameters:
index int Cell index
Returns:
short Number of pixels
Definition at line 2544 of file CELFileData.cpp.
References COMPACT_BCEL, affxcel::CCELFileHeaderData::GetCells(), m_FileFormat, m_HeaderData, m_pEntries, m_pTransciptomeEntries, MmGetInt16_I(), MmGetUInt8(), TEXT_CEL, TRANSCRIPTOME_BCEL, and XDA_BCEL.
Referenced by GetEntry(), GetPixels(), GetTranscriptomeEntry(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
short CCELFileData::GetPixels (int x, int y)
Retrieve number of pixels of specified cell.
Retrieves a CEL file pixel count.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
The CEL file pixel count.
public GetPixels
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
Returns:
short Number of pixels
Definition at line 2529 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), GetPixels(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, and XYToIndex().
int affxcel::CCELFileData::GetReadState () [inline]
Returns the reading state.
Returns:
The reading state.
Definition at line 1027 of file CELFileData.h.
References m_nReadState.
Referenced by affymetrix_fusion_io::GCOSCELDataAdapter::GetReadState().
int affxcel::CCELFileData::GetRows () [inline]
Call affxcel::CCELFileHeaderData::GetRows() to retrieve number of rows in array.
inline public GetRows
Returns:
int Number of rows in array
See also:
affxcel::CCELFileHeaderData::GetRows
Definition at line 709 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetRows(), and m_HeaderData.
Referenced by EnsureNotMmapped(), GetHeaderKey(), affymetrix_fusion_io::GCOSCELDataAdapter::GetRows(), ReadCompactBCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
float CCELFileData::GetStdv (int index)
Retrieve standard deviation of specified cell.
Retrieves a CEL file stdv value.
Parameters:
index The index to the CEL file entries.
Returns:
The CEL file stdv value.
public GetStdv
Parameters:
index int Cell index
Returns:
float Standard deviation intensity
Definition at line 2499 of file CELFileData.cpp.
References COMPACT_BCEL, affxcel::CCELFileHeaderData::GetCells(), m_FileFormat, m_HeaderData, m_pEntries, m_pTransciptomeEntries, MmGetFloat_I(), MmGetUInt16_N(), TEXT_CEL, TRANSCRIPTOME_BCEL, and XDA_BCEL.
Referenced by GetEntry(), GetStdv(), GetTranscriptomeEntry(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
float CCELFileData::GetStdv (int x, int y)
Retrieve standard deviation of specified cell.
Retrieves a CEL file stdv value.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
The CEL file stdv value.
public GetStdv
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
Returns:
float Standard deviation intensity
Definition at line 2484 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), GetStdv(), m_HeaderData, and XYToIndex().
affxcel::CCELFileData* affxcel::CCELFileData::GetThisPtr () [inline]
Retrieve the pointer of the current object instance.
inline public GetThisPtr
Returns:
affxcel::CCELFileData * Pointer to current object instance
Reimplemented in affxcel::CCELFileWriter.
Definition at line 667 of file CELFileData.h.
void CCELFileData::GetTranscriptomeEntry (int index, CELFileTranscriptomeEntryType & entry)
Retrieve entry of specified cell for transcriptome bcel format.
Retrieves a CEL file entry.
Parameters:
index The index to the CEL file entries.
entry The CEL file entry.
public GetTranscriptomeEntry
Parameters:
index int Cell index
entry CELFileTranscriptomeEntryType& Cell entry
Definition at line 2368 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCells(), GetIntensity(), GetPixels(), GetStdv(), affxcel::_CELFileTranscriptomeEntryType::Intensity, m_HeaderData, affxcel::_CELFileTranscriptomeEntryType::Pixels, RoundNumber(), and affxcel::_CELFileTranscriptomeEntryType::Stdv.
Referenced by GetTranscriptomeEntry().
void CCELFileData::GetTranscriptomeEntry (int x, int y, CELFileTranscriptomeEntryType & entry)
Retrieve entry of specified cell for transcriptome bcel format.
Retrieves a CEL file entry.
Parameters:
x The X coordinate.
y The Y coordinate.
entry The CEL file entry.
public GetTranscriptomeEntry
Parameters:
x int X coordinates
y int Y coordinates
entry CELFileTranscriptomeEntryType& Cell entry
Definition at line 2353 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), GetTranscriptomeEntry(), m_HeaderData, and XYToIndex().
int affxcel::CCELFileData::GetVersion () [inline]
Call affxcel::CCELFileHeaderData::GetVersion() to retrieve file format version number.
inline public GetVersion
Returns:
int File format version number
See also:
affxcel::CCELFileHeaderData::GetVersion
Definition at line 693 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetVersion(), and m_HeaderData.
Referenced by GetHeaderKey(), and affymetrix_fusion_io::GCOSCELDataAdapter::GetVersion().
int affxcel::CCELFileData::IndexToX (int index) [inline]
Get x coordinates from index.
inline public IndexToX
Returns:
int X coordinates
Definition at line 833 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetCols(), and m_HeaderData.
Referenced by affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
int affxcel::CCELFileData::IndexToY (int index) [inline]
Get y coordinates from index.
inline public IndexToY
Returns:
int Y coordinates
Definition at line 840 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetCols(), and m_HeaderData.
Referenced by affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
bool CCELFileData::IsCompactCelFile ()
Determine if CEL file is in compact binary format.
Checks if the file type is compact.
Returns:
True if compact type.
public IsCompactCelFile
Returns:
bool true if compact; false otherwise
Definition at line 2748 of file CELFileData.cpp.
References CCEL_HEADER_BYTES, CCEL_HEADER_LEN, ReadFixedCString(), and ResolveName().
Referenced by DetermineFileFormat(), and Open().
bool CCELFileData::IsMasked (int x, int y)
Determine if specified cell is masked.
Retrieves a CEL file mask flag.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
True if the feature is masked.
public IsMasked
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
Returns:
bool true if masked cell; false otherwise
Definition at line 2574 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, and XYToIndex().
bool CCELFileData::IsMasked (int index)
Determine if specified cell is masked.
Retrieves a CEL file mask flag.
Parameters:
index The index to the CEL file entries.
Returns:
True if the feature is masked.
public IsMasked
Parameters:
index int Cell index
Returns:
bool true if masked cell; false otherwise
Definition at line 2589 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCells(), m_HeaderData, and m_MaskedCells.
bool CCELFileData::IsOutlier (int x, int y)
Determine if specified cell is outlier.
Retrieves a CEL file outlier flag.
Parameters:
x The X coordinate.
y The Y coordinate.
Returns:
True if the feature is an outlier.
public IsOutlier
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
Returns:
bool true if outlier; false otherwise
Definition at line 2608 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, and XYToIndex().
bool CCELFileData::IsOutlier (int index)
Determine if specified cell is outlier.
Retrieves a CEL file outlier flag.
Parameters:
index The index to the CEL file entries.
Returns:
True if the feature is an outlier.
public IsOutlier
Parameters:
index int Cell index
Returns:
bool true if outlier; false otherwise
Definition at line 2623 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCells(), m_HeaderData, and m_Outliers.
bool CCELFileData::IsTranscriptomeBcelFile ()
Determine if CEL file is in transcriptome binary format.
Checks if the file type is transcriptome.
Returns:
True if transcriptome type.
public IsTranscriptomeBcelFile
Returns:
bool true if transcriptome binary; false otherwise
Definition at line 2706 of file CELFileData.cpp.
References BCEL_HEADER_BYTES, BCEL_HEADER_LEN, ReadFixedCString(), and ResolveName().
Referenced by DetermineFileFormat(), and Open().
bool CCELFileData::IsUnsupportedCompactCelFile ()
Determine if CEL file is in unsupported compact binary format.
Checks if the file type is previous unspported version of compact.
Returns:
True if compact type.
public IsUnsupportedCompactCelFile
Returns:
bool true if unsupported compact; false otherwise
Definition at line 2792 of file CELFileData.cpp.
References CCEL_HEADER_LEN, OLD_CCEL_HEADER_BYTES, ReadFixedCString(), and ResolveName().
Referenced by DetermineFileFormat(), and Open().
bool CCELFileData::IsVersion3CompatibleFile ()
Determine if CEL file is in text (version 3) format.
Checks if the file type is version 3.
Returns:
True if version 3 type.
public IsVersion3CompatibleFile
Returns:
bool true if version 3; false otherwise
Definition at line 2680 of file CELFileData.cpp.
References m_FileName, and MAXLINELENGTH.
bool CCELFileData::IsXDACompatibleFile ()
Determine if CEL file is in xda format.
Checks if the file type is XDA.
Returns:
True if XDA type.
public IsXDACompatibleFile
Returns:
bool true if xda; false otherwise
Definition at line 2640 of file CELFileData.cpp.
References CELL_FILE_MAGIC_NUMBER, ReadUInt32_I(), and ResolveName().
Referenced by DetermineFileFormat(), and Open().
void CCELFileData::Munmap ()
Unmap file view.
Unmap the file.
public Munmap
Returns:
void
Definition at line 2062 of file CELFileData.cpp.
References m_File, m_lpData, m_lpFileMap, m_MapLen, m_pEntries, m_pMeanIntensities, and m_pTransciptomeEntries.
Referenced by Clear(), and EnsureNotMmapped().
bool CCELFileData::Open (bool bReadHeaderOnly = false) [protected]
Determine the CEL file format and call corresponding function to read it.
Opens the file.
Parameters:
bReadHeaderOnly Flag indicating if the header is only to be read.
Returns:
True if successful.
private Open
Parameters:
bReadHeaderOnly bool [=false] Flag to determine if reading header section only
Returns:
bool true if success; false if fail
See also:
DetermineFileFormat, ReadXDABCel, ReadTranscriptomeBCel, ReadCompactBCel, ReadTextCel
Definition at line 720 of file CELFileData.cpp.
References Close(), DetermineFileFormat(), IsCompactCelFile(), IsTranscriptomeBcelFile(), IsUnsupportedCompactCelFile(), IsXDACompatibleFile(), ReadCompactBCel(), ReadTextCel(), ReadTranscriptomeBCel(), ReadXDABCel(), and SetError().
Referenced by Read(), ReadEx(), and ReadHeader().
bool CCELFileData::Read (bool bIncludeMaskAndOutliers = true)
Determine CEL file format and call appropriate function to read file.
Reads the CEL file.
Parameters:
bIncludeMaskAndOutliers Flag to indicate if the mask and outlier sections should also be read.
Returns:
True if successful.
public Read
Parameters:
bIncludeMaskAndOutliers bool Flag for including masked cells and outliers
Returns:
bool true if success, false if fail
Remarks:
File name has to be preset using SetFileName()
See also:
ReadEx, Open
Definition at line 2147 of file CELFileData.cpp.
References Close(), m_bReadMaskedCells, m_bReadOutliers, and Open().
bool CCELFileData::ReadCompactBCel (bool bReadHeaderOnly = false) [protected]
Read compact binary CEL file using memory mapping.
Reads the compact binary CEL file.
Parameters:
bReadHeaderOnly Flag indicating if the header is only to be read.
Returns:
True if successful.
private ReadCompactBCel
Parameters:
bReadHeaderOnly bool [=false] Flag to determine if reading header section only
Returns:
bool true if success; false if fail
Remarks:
Header section is read in memory.
Definition at line 1418 of file CELFileData.cpp.
References CCEL_HEADER_BYTES, CCEL_HEADER_LEN, Clear(), Close(), affxcel::CCELFileHeaderData::GetCells(), affxcel::CCELFileHeaderData::GetCols(), GetCols(), GetFileSize(), affxcel::CCELFileHeaderData::GetMasked(), GetNumMasked(), GetNumOutliers(), GetRows(), INT_SIZE, m_bReadMaskedCells, m_File, m_FileName, m_HeaderData, m_lpData, m_lpFileMap, m_MapLen, m_MaskedCells, m_pMeanIntensities, MmGetUInt16_I(), PAGE_TRUNC, affxcel::CCELFileHeaderData::ParseAlgorithmParameters(), affxcel::CCELFileHeaderData::ParseChipType(), affxcel::CCELFileHeaderData::ParseCorners(), affxcel::CCELFileHeaderData::ParseDatHeader(), ReadCString_I(), ReadFixedString(), ReadInt32_I(), ReadUInt32_I(), ResolveName(), affxcel::CCELFileHeaderData::SetAlg(), affxcel::CCELFileHeaderData::SetCells(), affxcel::CCELFileHeaderData::SetCols(), SetError(), affxcel::CCELFileHeaderData::SetHeader(), affxcel::CCELFileHeaderData::SetMargin(), affxcel::CCELFileHeaderData::SetMasked(), affxcel::CCELFileHeaderData::SetParams(), affxcel::CCELFileHeaderData::SetRows(), affxcel::CCELFileHeaderData::SetVersion(), SHORT_SIZE, UINT32_SIZE, and USHORT_SIZE.
Referenced by Open().
bool CCELFileData::ReadEx (const char * filename = 0, int nState = CEL_ALL)
Determine CEL file format and call appropriate function to read file using the specified file name.
Determine CEL file format and call appropriate function to read file using the specified file name.
Parameters:
filename The name of the file.
nState Reading state
Returns:
bool true if success, false if fail
nState can be one or combination of the following values: CEL_ALL Read all information in file (default) CEL_DATA Read header and intensities only CEL_OUTLIER Read header, intensities and outliers CEL_MASK Read header, intensities and masked cells
public ReadEx
Parameters:
filename const char * [=0] File name of CEL file to be read
nState int [=CEL_ALL] Reading state
Returns:
bool true if success, false if fail
nState can be one or combination of the following values:
CEL_ALL Read all information in file (default)
CEL_DATA Read header and intensities only
CEL_OUTLIER Read header, intensities and outliers
CEL_MASK Read header, intensities and masked cells
File name previously set by using SetFileName() will be replaced by the current input.
See also:
Read, Open, GetReadingState
Definition at line 2179 of file CELFileData.cpp.
References CEL_ALL, CEL_MASK, CEL_OUTLIER, Close(), m_bReadMaskedCells, m_bReadOutliers, m_nReadState, Open(), and SetFileName().
Referenced by affymetrix_fusion_io::GCOSCELDataAdapter::ReadEx().
bool CCELFileData::ReadHeader ()
Determine CEL file format and call appropriate function to read header section only.
Reads the header of the CEL file.
Returns:
True if successful.
public ReadHeader
Returns:
bool true if success, false if fail
Remarks:
File name has to be preset using SetFileName()
See also:
Read, Open
Definition at line 2126 of file CELFileData.cpp.
References Close(), and Open().
bool CCELFileData::ReadTextCel (bool bReadHeaderOnly = false) [protected]
Read text CEL file in memory.
Reads the text version of the CEL file.
Parameters:
bReadHeaderOnly Flag indicating if the header is only to be read.
Returns:
True if successful.
private ReadTextCel
Parameters:
bReadHeaderOnly bool [=false] Flag to determine if reading header section only
Returns:
bool true if success; false if fail
Remarks:
The reading of masked cells and outlier information is determined by the reading state which is set in ReadEx().
Definition at line 1728 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::AppendHeader(), Clear(), affxcel::CCELFileHeaderData::GetAlg(), affxcel::CCELFileHeaderData::GetAlgorithmParameter(), affxcel::CCELFileHeaderData::GetAlgorithmParameters(), affxcel::CCELFileHeaderData::GetCells(), affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetDatHeader(), affxcel::CCELFileHeaderData::GetGridCorners(), affxcel::CCELFileHeaderData::GetHeader(), affxcel::CCELFileHeaderData::GetRows(), affxcel::CCELFileHeaderData::GetVersion(), _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_bReadMaskedCells, m_bReadOutliers, m_FileName, m_HeaderData, m_MaskedCells, m_Outliers, m_pEntries, MAXLINELENGTH, MIN_CELLSTR, affxcel::CCELFileHeaderData::ParseAlgorithmParameters(), affxcel::CCELFileHeaderData::ParseChipType(), affxcel::CCELFileHeaderData::ParseCorners(), ResolveName(), affxcel::CCELFileHeaderData::SetAlg(), affxcel::CCELFileHeaderData::SetCells(), affxcel::CCELFileHeaderData::SetCols(), affxcel::CCELFileHeaderData::SetDatHeader(), SetError(), affxcel::CCELFileHeaderData::SetHeader(), SetIntensity(), affxcel::CCELFileHeaderData::SetMargin(), affxcel::CCELFileHeaderData::SetMasked(), affxcel::CCELFileHeaderData::SetOutliers(), affxcel::CCELFileHeaderData::SetParams(), SetPixels(), affxcel::CCELFileHeaderData::SetRows(), SetStdv(), affxcel::CCELFileHeaderData::SetVersion(), _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Referenced by Open().
bool CCELFileData::ReadTranscriptomeBCel (bool bReadHeaderOnly = false) [protected]
Read transcriptome binary CEL file using memory mapping.
Reads the transcriptome groups custom CEL file.
Parameters:
bReadHeaderOnly Flag indicating if the header is only to be read.
Returns:
True if successful.
private ReadTranscriptomeBCel
Parameters:
bReadHeaderOnly bool [=false] Flag to determine if reading header section only
Returns:
bool true if success; false if fail
Remarks:
Header section, masked cells and outlier information are read in memory. The reading of masked cells and outlier information is determined by the reading state which is set in ReadEx().
Definition at line 1095 of file CELFileData.cpp.
References BCEL_CHUNK_NAME_SIZE, BCEL_HEADER_BYTES, BCEL_HEADER_LEN, CHAR_SIZE, Clear(), Close(), FLOAT_SIZE, affxcel::CCELFileHeaderData::GetAlg(), affxcel::CCELFileHeaderData::GetAlgorithmParameter(), affxcel::CCELFileHeaderData::GetCells(), GetCols(), affxcel::CCELFileHeaderData::GetCols(), GetFileSize(), affxcel::CCELFileHeaderData::GetMasked(), affxcel::CCELFileHeaderData::GetOutliers(), affxcel::CCELFileHeaderData::GetParams(), GetRows(), affxcel::CCELFileHeaderData::GetRows(), _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_bReadMaskedCells, m_bReadOutliers, m_File, m_FileName, m_HeaderData, m_lpData, m_lpFileMap, m_MapLen, m_MaskedCells, m_Outliers, m_pTransciptomeEntries, MmGetUInt32_N(), OPEN_ERR_MSG, PAGE_TRUNC, affxcel::CCELFileHeaderData::ParseAlgorithmParameters(), affxcel::CCELFileHeaderData::ParseChipType(), affxcel::CCELFileHeaderData::ParseCorners(), ReadFixedString(), ReadFloat_N(), ReadUInt16_N(), ReadUInt32_N(), ResolveName(), affxcel::CCELFileHeaderData::SetAlg(), affxcel::CCELFileHeaderData::SetCells(), affxcel::CCELFileHeaderData::SetCols(), affxcel::CCELFileHeaderData::SetDatHeader(), SetError(), affxcel::CCELFileHeaderData::SetGridCorners(), affxcel::CCELFileHeaderData::SetHeader(), affxcel::CCELFileHeaderData::SetMargin(), affxcel::CCELFileHeaderData::SetMasked(), affxcel::CCELFileHeaderData::SetOutliers(), affxcel::CCELFileHeaderData::SetParams(), affxcel::CCELFileHeaderData::SetRows(), affxcel::CCELFileHeaderData::SetVersion(), SHORT_SIZE, STRUCT_SIZE_FEATURE_DATA, STRUCT_SIZE_XY_PAIR, UINT32_SIZE, _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, and _CoordinatePoint::y.
Referenced by Open().
bool CCELFileData::ReadXDABCel (bool bReadHeaderOnly = false) [protected]
Read xda format CEL file using memory mapping.
Reads the XDA version of the CEL file.
Parameters:
bReadHeaderOnly Flag indicating if the header is only to be read.
Returns:
True if successful.
private ReadXDABCel
Parameters:
bReadHeaderOnly bool [=false] Flag to determine if reading header section only
Returns:
bool true if success; false if fail
Remarks:
Header section, masked cells and outlier information are read in memory. The reading of masked cells and outlier information is determined by the reading state which is set in ReadEx().
Definition at line 756 of file CELFileData.cpp.
References CELL_FILE_MAGIC_NUMBER, Clear(), Close(), FLOAT_SIZE, affxcel::CCELFileHeaderData::GetCells(), affxcel::CCELFileHeaderData::GetCols(), GetCols(), GetFileSize(), affxcel::CCELFileHeaderData::GetMasked(), GetNumMasked(), GetNumOutliers(), affxcel::CCELFileHeaderData::GetOutliers(), GetRows(), INT_SIZE, m_bReadMaskedCells, m_bReadOutliers, m_File, m_FileName, m_HeaderData, m_lpData, m_lpFileMap, m_MapLen, m_MaskedCells, m_Outliers, m_pEntries, MmGetUInt16_I(), OPEN_ERR_MSG, PAGE_TRUNC, affxcel::CCELFileHeaderData::ParseAlgorithmParameters(), affxcel::CCELFileHeaderData::ParseChipType(), affxcel::CCELFileHeaderData::ParseCorners(), affxcel::CCELFileHeaderData::ParseDatHeader(), ReadCString_I(), ReadInt32_I(), ReadUInt32_I(), ResolveName(), affxcel::CCELFileHeaderData::SetAlg(), affxcel::CCELFileHeaderData::SetCells(), affxcel::CCELFileHeaderData::SetCols(), SetError(), affxcel::CCELFileHeaderData::SetHeader(), affxcel::CCELFileHeaderData::SetMagic(), affxcel::CCELFileHeaderData::SetMargin(), affxcel::CCELFileHeaderData::SetMasked(), affxcel::CCELFileHeaderData::SetOutliers(), affxcel::CCELFileHeaderData::SetParams(), affxcel::CCELFileHeaderData::SetRows(), affxcel::CCELFileHeaderData::SetVersion(), SHORT_SIZE, and UINT32_SIZE.
Referenced by Open().
std::string CCELFileData::ResolveName ()
Definition at line 669 of file CELFileData.cpp.
References m_FileName.
Referenced by Exists(), GetFileSize(), IsCompactCelFile(), IsTranscriptomeBcelFile(), IsUnsupportedCompactCelFile(), IsXDACompatibleFile(), ReadCompactBCel(), ReadTextCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
unsigned short CCELFileData::RoundNumber (float f) [protected]
Round floating point to integer.
Rounds a value to the nearest interger.
Parameters:
f The value to round.
Returns:
The rounded value.
private RoundNumber
Parameters:
f float Floating point
Returns:
unsigned short Rounded integer
RoundNumber(3.3) = 3
RoundNumber(3.5) = 4
Definition at line 2863 of file CELFileData.cpp.
Referenced by GetTranscriptomeEntry(), SetIntensity(), SetStdv(), affxcel::CCELFileWriter::WriteCompactBCel(), and affxcel::CCELFileWriter::WriteTranscriptomeBCel().
void CCELFileData::SetAddAlgorithmParameter (const char * tag, const char * value)
Call CCELFileHeaderData::SetAddAlgorithmParameter() to add algorithm parameter.
Adds a parameter to the parameter list.
Parameters:
tag The parameter name.
value The parameter value.
public SetAddAlgorithmParameter
Parameters:
tag const char * Algorithm parameter tag
value const char * Algorithm paramter value
Returns:
void
See also:
CCELFileHeaderData::SetAddAlgorithmParameter
Definition at line 2983 of file CELFileData.cpp.
References m_HeaderData, and affxcel::CCELFileHeaderData::SetAddAlgorithmParameter().
void CCELFileData::SetAlgorithmName (const char * str)
Call CCELFileHeaderData::SetAlg() to set algorithm name.
Sets the name of the algorithm used to create the CEL file.
Parameters:
str The algorithm name.
public SetAlgorithmName
Parameters:
str const char * Algorithm name
Returns:
void
See also:
CCELFileHeaderData::SetAlg
Definition at line 2941 of file CELFileData.cpp.
References m_HeaderData, and affxcel::CCELFileHeaderData::SetAlg().
void CCELFileData::SetAlgorithmParameter (const char * tag, const char * value)
Call CCELFileHeaderData::SetAlgorithmParameter() to add algorithm parameter.
Adds a parameter to the parameter list.
Parameters:
tag The parameter name.
value The parameter value.
public SetAlgorithmParameter
Parameters:
tag const char * Algorithm parameter tag
value const char * Algorithm paramter value
Returns:
void
See also:
CCELFileHeaderData::SetAlgorithmParameter
Definition at line 2969 of file CELFileData.cpp.
References m_HeaderData, and affxcel::CCELFileHeaderData::SetAlgorithmParameter().
void CCELFileData::SetCellEntry (int index, CELFileEntryType * pEntry)
Set cell file entry.
Sets a CEL file entry.
Parameters:
index The index to the CEL file entries.
pEntry The CEL file entry.
public overloaded SetCellEntry
Parameters:
index int Cell index
pEntry CELFileEntryType * Pointer to CEL File entry for xda and text formats
Returns:
void
Definition at line 3119 of file CELFileData.cpp.
References m_pEntries.
void CCELFileData::SetCellEntry (int x, int y, CELFileEntryType * pEntry)
Set cell file entry.
Sets a CEL file entry.
Parameters:
x The X coordinate.
y The Y coordinate.
pEntry The CEL file entry.
public overloaded SetCellEntry
Parameters:
x int X coordinates
y int Y coordinates
pEntry CELFileEntryType * Pointer to CEL File entry for xda and text formats
Returns:
void
Definition at line 3106 of file CELFileData.cpp.
References XYToIndex().
void CCELFileData::SetChipType (const char * str)
Set chip type and regenerate header string.
Sets probe array (chip) type.
Parameters:
str The probe array type.
public SetChipType
Parameters:
str const char * Chip type
Returns:
void
Definition at line 3055 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetChipType(), affxcel::CCELFileHeaderData::GetHeader(), m_HeaderData, affxcel::CCELFileHeaderData::SetChipType(), and affxcel::CCELFileHeaderData::SetHeader().
void CCELFileData::SetDimensions (int rows, int cols)
Set array dimensions in header section and allocate memory for intensity data.
Sets dimentions (rows/cols) of the CEL file.
Parameters:
rows The number of rows.
cols The number of columns.
public SetDimensions
Parameters:
rows int Number of rows in array
cols int Number of columns in array
Returns:
void
Todo:
UnMap
Definition at line 3016 of file CELFileData.cpp.
References COMPACT_BCEL, _GridCoordinatesType::lowerleft, _GridCoordinatesType::lowerright, m_FileFormat, m_HeaderData, m_pEntries, m_pMeanIntensities, m_pTransciptomeEntries, affxcel::CCELFileHeaderData::SetCells(), affxcel::CCELFileHeaderData::SetCols(), affxcel::CCELFileHeaderData::SetGridCorners(), affxcel::CCELFileHeaderData::SetRows(), TEXT_CEL, TRANSCRIPTOME_BCEL, _GridCoordinatesType::upperleft, _GridCoordinatesType::upperright, _CoordinatePoint::x, XDA_BCEL, and _CoordinatePoint::y.
void CCELFileData::SetError (const std::string & str)
Set error string.
Sets the error string.
Parameters:
str The error.
public SetError
Parameters:
str const char * Error string
Returns:
void
Definition at line 2911 of file CELFileData.cpp.
References m_strError.
Referenced by Open(), ReadCompactBCel(), ReadTextCel(), ReadTranscriptomeBCel(), ReadXDABCel(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
void CCELFileData::SetError (const char * str)
Definition at line 2915 of file CELFileData.cpp.
References m_strError.
void CCELFileData::SetFileFormat (int i)
Set CEL file format to determine the appropriate data storage in cell.
Sets the file format type.
Parameters:
i The file format type.
public SetFileFormat
Parameters:
i int File format
Returns:
void
i can be one of the following values:
TEXT_CEL
XDA_BCEL
TRANSCRIPTOME_BCEL
COMPACT_BCEL
Definition at line 3002 of file CELFileData.cpp.
References COMPACT_BCEL, m_FileFormat, and TEXT_CEL.
void affxcel::CCELFileData::SetFileName (const char * str) [inline]
Set CEL file name.
inline public constant SetFileName
Parameters:
str const char* File name
Returns:
void
Definition at line 675 of file CELFileData.h.
References m_FileName.
Referenced by ReadEx().
void CCELFileData::SetGridCorners (GridCoordinatesType grid)
Call CCELFileHeaderData::SetGridCorners() to set grid coordinates.
Sets the grid coordinates.
Parameters:
grid The grid coordinates.
public SetGridCorners
Parameters:
grid GridCoordinatesType Algorithm name
Returns:
void
See also:
CCELFileHeaderData::SetGridCorners
Definition at line 2928 of file CELFileData.cpp.
References m_HeaderData, and affxcel::CCELFileHeaderData::SetGridCorners().
void CCELFileData::SetIntensity (int x, int y, float intensity)
Set intensity of specified cell.
Sets the intensity value.
Parameters:
x The X coordinate.
y The Y coordinate.
intensity The intensity value.
public SetIntensity
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
intensity float Mean intensity
Returns:
void
Definition at line 3172 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, SetIntensity(), and XYToIndex().
void CCELFileData::SetIntensity (int index, float intensity)
Set intensity of specified cell.
Sets the intensity value.
Parameters:
index The index to the CEL file.
intensity The intensity value.
public SetIntensity
Parameters:
index int Cell index
intensity float Mean intensity
Returns:
void
Definition at line 3188 of file CELFileData.cpp.
References COMPACT_BCEL, affxcel::CCELFileHeaderData::GetCells(), m_FileFormat, m_HeaderData, m_pEntries, m_pMeanIntensities, m_pTransciptomeEntries, MmSetFloat_I(), MmSetUInt16_I(), MmSetUInt16_N(), RoundNumber(), TEXT_CEL, TRANSCRIPTOME_BCEL, and XDA_BCEL.
Referenced by ReadTextCel(), and SetIntensity().
void CCELFileData::SetMargin (int margin)
Set cell margin.
Sets the margin used in creating the CEL file.
Parameters:
margin The margin used in creating the CEL file.
public SetMargin
Parameters:
margin int Cell margin
Returns:
void
Definition at line 3080 of file CELFileData.cpp.
References m_HeaderData, and affxcel::CCELFileHeaderData::SetMargin().
void CCELFileData::SetMask (int x, int y, bool masked)
Set if specified cell is masked.
Sets the mask flag.
Parameters:
x The X coordinate.
y The Y coordinate.
masked The mask flag.
public SetMask
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
masked bool true if masked; false otherwise
Returns:
void
Definition at line 3308 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, SetMask(), and XYToIndex().
void CCELFileData::SetMask (int index, bool masked)
Set if specified cell is masked.
Sets the mask flag.
Parameters:
index The index to the CEL file.
mask The mask flag.
public SetMask
Parameters:
index int Cell index
masked bool true if masked; false otherwise
Returns:
void
Definition at line 3324 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::DecrementMasked(), affxcel::CCELFileHeaderData::GetCells(), affxcel::CCELFileHeaderData::IncrementMasked(), m_HeaderData, and m_MaskedCells.
Referenced by SetMask().
void CCELFileData::SetOutlier (int x, int y, bool outlier)
Set if specified cell is outlier.
Sets the outlier flag.
Parameters:
x The X coordinate.
y The Y coordinate.
outlier The outlier flag.
public SetOutlier
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
outlier bool true if outlier; false otherwise
Returns:
void
Definition at line 3353 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, SetOutlier(), and XYToIndex().
void CCELFileData::SetOutlier (int index, bool outlier)
Set if specified cell is outlier.
Sets the outlier flag.
Parameters:
index The index to the CEL file.
outlier The outlier flag.
public SetOutlier
Parameters:
index int Cell index
outlier bool true if outlier; false otherwise
Returns:
void
Definition at line 3369 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::DecrementOutliers(), affxcel::CCELFileHeaderData::GetCells(), affxcel::CCELFileHeaderData::IncrementOutliers(), m_HeaderData, and m_Outliers.
Referenced by SetOutlier().
void CCELFileData::SetPixels (int index, short pixels)
Set number of pixels of specified cell.
Sets the pixel count.
Parameters:
index The index to the CEL file.
pixels The pixel count.
public SetPixels
Parameters:
index int Cell index
pixels short Number of pixels
Returns:
void
Definition at line 3285 of file CELFileData.cpp.
References COMPACT_BCEL, affxcel::CCELFileHeaderData::GetCells(), m_FileFormat, m_HeaderData, m_pEntries, m_pTransciptomeEntries, MmSetUInt16_I(), MmSetUInt8(), TEXT_CEL, TRANSCRIPTOME_BCEL, and XDA_BCEL.
Referenced by ReadTextCel(), and SetPixels().
void CCELFileData::SetPixels (int x, int y, short pixels)
Set number of pixels of specified cell.
Sets the pixel count.
Parameters:
x The X coordinate.
y The Y coordinate.
pixels The pixel count.
public SetPixels
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
pixels short Number of pixels
Returns:
void
Definition at line 3269 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, SetPixels(), and XYToIndex().
void CCELFileData::SetStdv (int index, float stdev)
Set standard deviation intensity of specified cell.
Sets the stdev value.
Parameters:
index The index to the CEL file.
stdev The stdev value.
public SetStdv
Parameters:
index int Cell index
stdev float Standard deviation intensity
Returns:
void
Definition at line 3243 of file CELFileData.cpp.
References COMPACT_BCEL, affxcel::CCELFileHeaderData::GetCells(), m_FileFormat, m_HeaderData, m_pEntries, m_pTransciptomeEntries, MmSetFloat_I(), MmSetUInt16_N(), RoundNumber(), TEXT_CEL, TRANSCRIPTOME_BCEL, and XDA_BCEL.
Referenced by ReadTextCel(), and SetStdv().
void CCELFileData::SetStdv (int x, int y, float stdev)
Set standard deviation intensity of specified cell.
Sets the stdev value.
Parameters:
x The X coordinate.
y The Y coordinate.
stdev The stdev value.
public SetStdv
Parameters:
x int X coordinate of cell
y int Y coordinate of cell
stdev float Standard deviation intensity
Returns:
void
Definition at line 3227 of file CELFileData.cpp.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, SetStdv(), and XYToIndex().
void CCELFileData::SetTranscriptomeCellEntry (int x, int y, CELFileTranscriptomeEntryType * pEntry)
Set cell file entry.
Sets a CEL file entry.
Parameters:
x The X coordinate.
y The Y coordinate.
pEntry The CEL file entry.
public overloaded SetCellEntry
Parameters:
x int X coordinates
y int Y coordinates
pEntry CELFileEntryType * Pointer to CEL File entry for transcriptome bcel format
Returns:
void
Definition at line 3145 of file CELFileData.cpp.
References XYToIndex().
void CCELFileData::SetTranscriptomeCellEntry (int index, CELFileTranscriptomeEntryType * pEntry)
Set cell file entry.
Sets a CEL file entry.
Parameters:
index The index to the CEL file entries.
pEntry The CEL file entry.
public overloaded SetCellEntry
Parameters:
index int Cell index
pEntry CELFileEntryType * Pointer to CEL File entry for transcriptome bcel format
Returns:
void
Definition at line 3158 of file CELFileData.cpp.
References m_pTransciptomeEntries.
int affxcel::CCELFileData::XYToIndex (int x, int y) [inline]
Convert x, y coordinates to index.
inline public XYToIndex
Returns:
int Index
Definition at line 847 of file CELFileData.h.
References affxcel::CCELFileHeaderData::GetCols(), affxcel::CCELFileHeaderData::GetRows(), m_HeaderData, and XYToIndex().
Referenced by GetEntry(), GetIntensity(), GetPixels(), GetStdv(), GetTranscriptomeEntry(), IsMasked(), IsOutlier(), SetCellEntry(), SetIntensity(), SetMask(), SetOutlier(), SetPixels(), SetStdv(), SetTranscriptomeCellEntry(), and XYToIndex().
static int affxcel::CCELFileData::XYToIndex (int x, int y, int r, int c) [inline, static]
Maps X/Y coordinates to CEL file index.
Parameters:
x The x coordinate.
y The y coordinate.
r The number of rows.
c The number of columns.
Returns:
The index to the intensity arrays.
Definition at line 856 of file CELFileData.h.
Member Data Documentation
bool affxcel::CCELFileData::m_bReadMaskedCells [protected]
Flag to determine if masked cell data should be read.
Definition at line 588 of file CELFileData.h.
Referenced by CCELFileData(), Read(), ReadCompactBCel(), ReadEx(), ReadTextCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
bool affxcel::CCELFileData::m_bReadOutliers [protected]
Flag to determine if outlier data should be read.
Definition at line 590 of file CELFileData.h.
Referenced by CCELFileData(), Read(), ReadEx(), ReadTextCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
FILE* affxcel::CCELFileData::m_File [protected]
Pointer to file object.
Definition at line 599 of file CELFileData.h.
Referenced by Munmap(), ReadCompactBCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
int affxcel::CCELFileData::m_FileFormat [protected]
CEL file format.
Definition at line 566 of file CELFileData.h.
Referenced by CCELFileData(), DetermineFileFormat(), EnsureNotMmapped(), GetFileFormat(), GetIntensities(), GetIntensity(), GetPixels(), GetStdv(), SetDimensions(), SetFileFormat(), SetIntensity(), SetPixels(), and SetStdv().
std::string affxcel::CCELFileData::m_FileName [protected]
CEL file name without path.
Definition at line 570 of file CELFileData.h.
Referenced by CCELFileData(), GetFileName(), IsVersion3CompatibleFile(), ReadCompactBCel(), ReadTextCel(), ReadTranscriptomeBCel(), ReadXDABCel(), ResolveName(), SetFileName(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
CCELFileHeaderData affxcel::CCELFileData::m_HeaderData [protected]
CEL file header data object.
Definition at line 572 of file CELFileData.h.
Referenced by AddAlgorithmParameter(), AllocateEntries(), AllocateTranscriptomeEntries(), Clear(), GetAlg(), GetAlgorithmParameter(), GetAlgorithmParameters(), GetAlgorithmParameterTag(), GetCellMargin(), GetChipType(), GetCols(), GetDatHeader(), GetEntry(), GetGridCorners(), GetHeader(), GetHeaderString(), GetIntensities(), GetIntensity(), GetNumberAlgorithmParameters(), GetNumCells(), GetNumMasked(), GetNumOutliers(), GetParams(), GetPixels(), GetRows(), GetStdv(), GetTranscriptomeEntry(), GetVersion(), IndexToX(), IndexToY(), IsMasked(), IsOutlier(), ReadCompactBCel(), ReadTextCel(), ReadTranscriptomeBCel(), ReadXDABCel(), SetAddAlgorithmParameter(), SetAlgorithmName(), SetAlgorithmParameter(), SetChipType(), SetDimensions(), SetGridCorners(), SetIntensity(), SetMargin(), SetMask(), SetOutlier(), SetPixels(), SetStdv(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), affxcel::CCELFileWriter::WriteXDABCel(), and XYToIndex().
char* affxcel::CCELFileData::m_lpData [protected]
Pointer to memory mapping data.
Definition at line 605 of file CELFileData.h.
Referenced by CCELFileData(), Munmap(), ReadCompactBCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
void* affxcel::CCELFileData::m_lpFileMap [protected]
Pointer to memory mapping file view.
Definition at line 607 of file CELFileData.h.
Referenced by CCELFileData(), EnsureNotMmapped(), Munmap(), ReadCompactBCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
size_t affxcel::CCELFileData::m_MapLen [protected]
Memory mapping size used by mmap (POSIX)
Definition at line 601 of file CELFileData.h.
Referenced by Munmap(), ReadCompactBCel(), ReadTranscriptomeBCel(), and ReadXDABCel().
std::map<int, bool> affxcel::CCELFileData::m_MaskedCells [protected]
STL map for masked cell coordinates.
Definition at line 581 of file CELFileData.h.
Referenced by Clear(), IsMasked(), ReadCompactBCel(), ReadTextCel(), ReadTranscriptomeBCel(), ReadXDABCel(), SetMask(), affxcel::CCELFileWriter::WriteCompactBCel(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
int affxcel::CCELFileData::m_nReadState [protected]
CEL file reading state.
Definition at line 586 of file CELFileData.h.
Referenced by CCELFileData(), GetReadState(), and ReadEx().
std::map<int, bool> affxcel::CCELFileData::m_Outliers [protected]
STL map for outlier coordinates.
Definition at line 583 of file CELFileData.h.
Referenced by Clear(), IsOutlier(), ReadTextCel(), ReadTranscriptomeBCel(), ReadXDABCel(), SetOutlier(), affxcel::CCELFileWriter::WriteTextCel(), affxcel::CCELFileWriter::WriteTranscriptomeBCel(), and affxcel::CCELFileWriter::WriteXDABCel().
CELFileEntryType* affxcel::CCELFileData::m_pEntries [protected]
Pointer to intensity entries for each cell (used for text and xda formats)
Definition at line 574 of file CELFileData.h.
Referenced by AllocateEntries(), CCELFileData(), Clear(), EnsureNotMmapped(), GetIntensities(), GetIntensity(), GetPixels(), GetStdv(), Munmap(), ReadTextCel(), ReadXDABCel(), SetCellEntry(), SetDimensions(), SetIntensity(), SetPixels(), and SetStdv().
unsigned short* affxcel::CCELFileData::m_pMeanIntensities [protected]
Pointer to intensity entries for each cell (used for compact cel format)
Definition at line 578 of file CELFileData.h.
Referenced by CCELFileData(), Clear(), EnsureNotMmapped(), GetIntensities(), GetIntensity(), Munmap(), ReadCompactBCel(), SetDimensions(), and SetIntensity().
CELFileTranscriptomeEntryType* affxcel::CCELFileData::m_pTransciptomeEntries [protected]
Pointer to intensity entries for each cell (used for transcriptome bcel format)
Definition at line 576 of file CELFileData.h.
Referenced by AllocateTranscriptomeEntries(), CCELFileData(), Clear(), EnsureNotMmapped(), GetIntensities(), GetIntensity(), GetPixels(), GetStdv(), Munmap(), ReadTranscriptomeBCel(), SetDimensions(), SetIntensity(), SetPixels(), SetStdv(), and SetTranscriptomeCellEntry().
std::string affxcel::CCELFileData::m_strError [protected]
Error string.
Definition at line 568 of file CELFileData.h.
Referenced by CCELFileData(), GetError(), and SetError().
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/file/CELFileData.h
C:/f112/affy/sdk/calvin_files/data/src/CELData.cpp
C:/f112/affy/sdk/file/CELFileData.cpp