Affymetrix Fusion SDK: affymetrix_calvin_io::CHPMultiDataFileBufferWriter Class Reference
affymetrix_calvin_io::CHPMultiDataFileBufferWriter Class Reference
#include <CalvinCHPMultiDataFileBufferWriter.h>
Public Member Functions
CHPMultiDataFileBufferWriter ()
~CHPMultiDataFileBufferWriter ()
void SetMaxBufferSize (int MaxBufferSize)
void Cleanup ()
void Initialize (std::vector< std::string > *CHPFileNames, std::vector< MultiDataType > &dataTypes, std::map< MultiDataType, int > &maxProbeSetNmLn)
void Initialize (std::vector< std::string > *CHPFileNames, std::vector< MultiDataType > &dataTypes, std::map< MultiDataType, int > &maxSegmentTypeLn, std::map< MultiDataType, int > &maxReferenceSegmentIDLn, std::map< MultiDataType, int > &maxFamilialSegmentIDLn, std::map< MultiDataType, int > &maxFamilialARRIDLn, std::map< MultiDataType, int > &maxFamilialCHPIDLn, std::map< MultiDataType, int > &maxFamilialCHPFilenameLn, std::map< MultiDataType, int > &maxFamilialRoleLn)
void WriteMultiDataGenotypeEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData &entry)
void WriteMultiDataCopyNumberEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData &entry)
void WriteMultiDataCytoRegionEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData &entry)
void WriteMultiDataExpressionEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataExpressionData &entry)
void WriteMultiDataCopyNumberVariationRegionEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::DmetCopyNumberData &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::DmetMultiAllelicData &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::DmetBiAllelicData &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ChromosomeMultiDataSummaryData &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ChromosomeSegmentData &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ChromosomeSegmentDataEx &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::FamilialSegmentOverlap &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::FamilialSample &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::AllelePeaks &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::MarkerABSignals &entry)
void WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::CytoGenotypeCallData &entry)
void FlushBuffer ()
Private Member Functions
void Initialize (std::vector< std::string > *CHPFileNames, std::vector< MultiDataType > &dataTypes, std::map< MultiDataType, int > &maxProbeSetNmLn, std::map< MultiDataType, int > &maxSegmentTypeLn, std::map< MultiDataType, int > &maxReferenceSegmentIDLn, std::map< MultiDataType, int > &maxFamilialSegmentIDLn, std::map< MultiDataType, int > &maxFamilialARRIDLn, std::map< MultiDataType, int > &maxFamilialCHPIDLn, std::map< MultiDataType, int > &maxFamilialCHPFilenameLn, std::map< MultiDataType, int > &maxFamilialRoleLn)
Private Attributes
std::vector< std::string > * chpFileNames
std::map< MultiDataType,
std::vector< std::vector< char * > > > dataBuffers
std::map< MultiDataType,
std::vector< int > > rowIndexes
int m_BufferSize
int m_MaxBufferSize
std::map< MultiDataType, int > maxProbeSetNameLength
std::map< MultiDataType, int > maxSegmentType
std::map< MultiDataType, int > maxReferenceSegmentID
std::map< MultiDataType, int > maxFamilialSegmentID
std::map< MultiDataType, int > maxFamilialARRID
std::map< MultiDataType, int > maxFamilialCHPID
std::map< MultiDataType, int > maxFamilialCHPFilename
std::map< MultiDataType, int > maxFamilialRole
std::map< MultiDataType, int > dataBufferSz
Detailed Description
Definition at line 43 of file CalvinCHPMultiDataFileBufferWriter.h.
Constructor & Destructor Documentation
CHPMultiDataFileBufferWriter::CHPMultiDataFileBufferWriter ()
Constructor
Definition at line 55 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References MAX_BUFFER_SIZE.
CHPMultiDataFileBufferWriter::~CHPMultiDataFileBufferWriter ()
Destructor
Definition at line 61 of file CalvinCHPMultiDataFileBufferWriter.cpp.
Member Function Documentation
void CHPMultiDataFileBufferWriter::Cleanup ()
Cleans up memory
Definition at line 83 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References ClearBuffer().
void CHPMultiDataFileBufferWriter::FlushBuffer ()
Write the content of the buffer to CHP files.
Definition at line 977 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_io::AllelePeaksMultiDataType, affymetrix_calvin_io::ChromosomeSummaryMultiDataType, ClearBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::CloseCHPFile(), affymetrix_calvin_io::CopyNumberMultiDataType, affymetrix_calvin_io::CopyNumberVariationMultiDataType, affymetrix_calvin_io::CytoGenotypeCallMultiDataType, affymetrix_calvin_io::CytoMultiDataType, affymetrix_calvin_io::DmetBiAllelicMultiDataType, affymetrix_calvin_io::DmetCopyNumberMultiDataType, affymetrix_calvin_io::DmetMultiAllelicMultiDataType, affymetrix_calvin_io::ExpressionMultiDataType, affymetrix_calvin_io::FamilialSamplesMultiDataType, affymetrix_calvin_io::FamilialSegmentOverlapsMultiDataType, affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_calvin_io::MarkerABSignalsMultiDataType, affymetrix_calvin_io::CalvinCHPFileUpdater::OpenCHPFile(), affymetrix_calvin_io::SegmentCNLossLOHConcordanceMultiDataType, affymetrix_calvin_io::SegmentCNMultiDataType, affymetrix_calvin_io::SegmentCNNeutralLOHConcordanceMultiDataType, affymetrix_calvin_io::SegmentCNNeutralLOHMultiDataType, affymetrix_calvin_io::SegmentDenovoCopyNumberMultiDataType, affymetrix_calvin_io::SegmentGenotypeConcordanceMultiDataType, affymetrix_calvin_io::SegmentGenotypeDiscordanceMultiDataType, affymetrix_calvin_io::SegmentHemizygousParentOfOriginMultiDataType, affymetrix_calvin_io::SegmentHeteroUPDMultiDataType, affymetrix_calvin_io::SegmentIsoUPDMultiDataType, affymetrix_calvin_io::SegmentLOHMultiDataType, affymetrix_calvin_io::SegmentMosaicismMultiDataType, affymetrix_calvin_io::SegmentNoCallMultiDataType, affymetrix_calvin_io::SegmentNormalDiploidMultiDataType, affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateChromosomeSegmentEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateChromosomeSummaryEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetBiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateDmetMultiAllelicEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateFamilialSampleEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateFamilialSegmentOverlapEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataAllelePeaksEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCopyNumberEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCopyNumberVariationRegionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCytoGenotypeEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataCytoRegionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataExpressionEntryBuffer(), affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataGenotypeEntryBuffer(), and affymetrix_calvin_io::CalvinCHPFileUpdater::UpdateMultiDataMarkerABSignalsEntryBuffer().
Referenced by AddFileBody().
void affymetrix_calvin_io::CHPMultiDataFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames, std::vector< MultiDataType > & dataTypes, std::map< MultiDataType, int > & maxSegmentTypeLn, std::map< MultiDataType, int > & maxReferenceSegmentIDLn, std::map< MultiDataType, int > & maxFamilialSegmentIDLn, std::map< MultiDataType, int > & maxFamilialARRIDLn, std::map< MultiDataType, int > & maxFamilialCHPIDLn, std::map< MultiDataType, int > & maxFamilialCHPFilenameLn, std::map< MultiDataType, int > & maxFamilialRoleLn)
Initialize the buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
dataTypes The data types.
maxSegmentTypeLn The maximum segment type length
maxReferenceSegmentIDLn The maximum ref sample key length
maxFamilialSegmentIDLn The maximum familial seg id length
maxFamilialARRIDLn The maximum familial arr id length
maxFamilialCHPIDLn The maximum familial sample chp id length
maxFamilialCHPFilenameLn The maximum familial sample chp file length
maxFamilialRoleLn The maximum familial sample role length
void CHPMultiDataFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames, std::vector< MultiDataType > & dataTypes, std::map< MultiDataType, int > & maxProbeSetNmLn, std::map< MultiDataType, int > & maxSegmentTypeLn, std::map< MultiDataType, int > & maxReferenceSegmentIDLn, std::map< MultiDataType, int > & maxFamilialSegmentIDLn, std::map< MultiDataType, int > & maxFamilialARRIDLn, std::map< MultiDataType, int > & maxFamilialCHPIDLn, std::map< MultiDataType, int > & maxFamilialCHPFilenameLn, std::map< MultiDataType, int > & maxFamilialRoleLn) [private]
Initialize the buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
dataTypes The data types.
maxProbeSetNmLn The maximum probe set name length
maxSegmentTypeLn The maximum segment type length
maxReferenceSegmentIDLn The maximum ref sample key length
maxFamilialSegmentIDLn The maximum familial seg id length
maxFamilialARRIDLn The maximum familial arr id length
maxFamilialCHPIDLn The maximum familial sample chp id length
maxFamilialCHPFilenameLn The maximum familial sample chp file length
maxFamilialRoleLn The maximum familial sample role length
Definition at line 127 of file CalvinCHPMultiDataFileBufferWriter.cpp.
void affymetrix_calvin_io::CHPMultiDataFileBufferWriter::Initialize (std::vector< std::string > * CHPFileNames, std::vector< MultiDataType > & dataTypes, std::map< MultiDataType, int > & maxProbeSetNmLn)
Initialize the buffer writer
Parameters:
CHPFileNames Reference to a list of CHP file names.
dataTypes The data types.
maxProbeSetNmLn The maximum probe set name length
Referenced by AddFileBody().
void affymetrix_calvin_io::CHPMultiDataFileBufferWriter::SetMaxBufferSize (int MaxBufferSize) [inline]
Set maximum buffer size
Definition at line 53 of file CalvinCHPMultiDataFileBufferWriter.h.
References m_MaxBufferSize.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::FamilialSegmentOverlap & entry)
Write an entry.
Parameters:
entry A pointer to a multi data entry.
Definition at line 914 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_FamilialSegmentOverlap::familialSampleKey, affymetrix_calvin_data::_FamilialSegmentOverlap::familialSegmentID, MmSetUInt32_N(), affymetrix_calvin_data::_FamilialSegmentOverlap::referenceSampleKey, affymetrix_calvin_data::_FamilialSegmentOverlap::referenceSegmentID, and affymetrix_calvin_data::_FamilialSegmentOverlap::segmentType.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::FamilialSample & entry)
Write an entry.
Parameters:
entry A pointer to a multi data entry.
Definition at line 843 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_FamilialSample::arrID, affymetrix_calvin_data::_FamilialSample::chpFilename, affymetrix_calvin_data::_FamilialSample::chpID, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_FamilialSample::role, affymetrix_calvin_data::_FamilialSample::roleConfidence, affymetrix_calvin_data::_FamilialSample::roleValidity, and affymetrix_calvin_data::_FamilialSample::sampleKey.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ChromosomeSegmentDataEx & entry)
Write an entry.
Parameters:
entry A pointer to a multi data entry.
Definition at line 776 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_ChromosomeSegmentDataEx::call, affymetrix_calvin_data::_ChromosomeSegmentDataEx::chr, affymetrix_calvin_data::_ChromosomeSegmentDataEx::confidence, CopyMetricToBuffer(), affymetrix_calvin_data::_ChromosomeSegmentDataEx::familialSampleKey, GetMetricBufferSize(), affymetrix_calvin_data::_ChromosomeSegmentDataEx::heterozygosity, affymetrix_calvin_data::_ChromosomeSegmentDataEx::homozygosity, affymetrix_calvin_data::_ChromosomeSegmentDataEx::markerCount, affymetrix_calvin_data::_ChromosomeSegmentDataEx::metrics, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_ChromosomeSegmentDataEx::referenceSampleKey, affymetrix_calvin_data::_ChromosomeSegmentDataEx::segmentId, affymetrix_calvin_data::_ChromosomeSegmentDataEx::startPosition, and affymetrix_calvin_data::_ChromosomeSegmentDataEx::stopPosition.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::AllelePeaks & entry)
Write an entry.
Parameters:
entry A pointer to a multi data entry.
Definition at line 362 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_AllelePeaks::chr, CopyMetricToBuffer(), GetMetricBufferSize(), MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_AllelePeaks::name, affymetrix_calvin_data::_AllelePeaks::peaks, and affymetrix_calvin_data::_AllelePeaks::position.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ChromosomeMultiDataSummaryData & entry)
Write an entry.
Parameters:
entry A pointer to a multi data entry.
Definition at line 667 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::chr, CopyMetricToBuffer(), affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::display, GetMetricBufferSize(), affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::hetFrequency, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::homFrequency, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::markerCount, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::maxSignal, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::medianCnState, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::metrics, affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::minSignal, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), and affymetrix_calvin_data::_ChromosomeMultiDataSummaryData::startIndex.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::CytoGenotypeCallData & entry)
Write an entry.
Parameters:
entry A pointer to a multi data entry.
Definition at line 408 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_CytoGenotypeCallData::aSignal, affymetrix_calvin_data::_CytoGenotypeCallData::bSignal, affymetrix_calvin_data::_CytoGenotypeCallData::call, affymetrix_calvin_data::_CytoGenotypeCallData::confidence, affymetrix_calvin_data::_CytoGenotypeCallData::contrast, CopyMetricToBuffer(), affymetrix_calvin_data::_CytoGenotypeCallData::forcedCall, GetMetricBufferSize(), affymetrix_calvin_data::_CytoGenotypeCallData::index, affymetrix_calvin_data::_CytoGenotypeCallData::metrics, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), and affymetrix_calvin_data::_CytoGenotypeCallData::signalStrength.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::DmetCopyNumberData & entry)
Write a DMET copy number entry to buffer. If the buffer is full, flush it.
Parameters:
dataType The data type.
target Target for the entry.
entry Value for the copy number entry.
Definition at line 625 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_DmetCopyNumberData::call, affymetrix_calvin_data::_DmetCopyNumberData::confidence, CopyMetricToBuffer(), affymetrix_calvin_data::_DmetCopyNumberData::estimate, affymetrix_calvin_data::_DmetCopyNumberData::force, GetMetricBufferSize(), affymetrix_calvin_data::_DmetCopyNumberData::lower, affymetrix_calvin_data::_DmetCopyNumberData::metrics, MmSetFloat_N(), MmSetUInt16_N(), MmSetUInt32_N(), affymetrix_calvin_data::_DmetCopyNumberData::name, and affymetrix_calvin_data::_DmetCopyNumberData::upper.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::DmetMultiAllelicData & entry)
Write a DMET multi-allelic entry to buffer. If the buffer is full, flush it.
Parameters:
dataType The data type.
target Target for the entry.
entry Value for the copy number entry.
Definition at line 553 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_DmetMultiAllelicData::alleleCount, affymetrix_calvin_data::_DmetMultiAllelicData::call, affymetrix_calvin_data::_DmetMultiAllelicData::confidence, affymetrix_calvin_data::_DmetMultiAllelicData::contextA, affymetrix_calvin_data::_DmetMultiAllelicData::contextB, affymetrix_calvin_data::_DmetMultiAllelicData::contextC, affymetrix_calvin_data::_DmetMultiAllelicData::contextD, affymetrix_calvin_data::_DmetMultiAllelicData::contextE, affymetrix_calvin_data::_DmetMultiAllelicData::contextF, CopyMetricToBuffer(), affymetrix_calvin_data::_DmetMultiAllelicData::force, GetMetricBufferSize(), affymetrix_calvin_data::_DmetMultiAllelicData::metrics, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_DmetMultiAllelicData::name, affymetrix_calvin_data::_DmetMultiAllelicData::signalA, affymetrix_calvin_data::_DmetMultiAllelicData::signalB, affymetrix_calvin_data::_DmetMultiAllelicData::signalC, affymetrix_calvin_data::_DmetMultiAllelicData::signalD, affymetrix_calvin_data::_DmetMultiAllelicData::signalE, and affymetrix_calvin_data::_DmetMultiAllelicData::signalF.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::MarkerABSignals & entry)
Write an entry.
Parameters:
entry A pointer to a multi data entry.
Definition at line 387 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References CopyMetricToBuffer(), GetMetricBufferSize(), affymetrix_calvin_data::_MarkerABSignals::index, affymetrix_calvin_data::_MarkerABSignals::metrics, and MmSetUInt32_N().
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::DmetBiAllelicData & entry)
Write a DMET copy number entry to buffer. If the buffer is full, flush it.
Parameters:
dataType The data type.
target Target for the entry.
entry Value for the copy number entry.
Definition at line 508 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_DmetBiAllelicData::call, affymetrix_calvin_data::_DmetBiAllelicData::confidence, affymetrix_calvin_data::_DmetBiAllelicData::contextA, affymetrix_calvin_data::_DmetBiAllelicData::contextB, CopyMetricToBuffer(), affymetrix_calvin_data::_DmetBiAllelicData::force, GetMetricBufferSize(), affymetrix_calvin_data::_DmetBiAllelicData::metrics, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_DmetBiAllelicData::name, affymetrix_calvin_data::_DmetBiAllelicData::signalA, and affymetrix_calvin_data::_DmetBiAllelicData::signalB.
void CHPMultiDataFileBufferWriter::WriteEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ChromosomeSegmentData & entry)
Write an entry.
Parameters:
entry A pointer to a multi data entry.
Definition at line 729 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_ChromosomeSegmentData::chr, CopyMetricToBuffer(), GetMetricBufferSize(), affymetrix_calvin_data::_ChromosomeSegmentData::markerCount, affymetrix_calvin_data::_ChromosomeSegmentData::meanMarkerDistance, affymetrix_calvin_data::_ChromosomeSegmentData::metrics, MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_ChromosomeSegmentData::segmentId, affymetrix_calvin_data::_ChromosomeSegmentData::startPosition, and affymetrix_calvin_data::_ChromosomeSegmentData::stopPosition.
void CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberData & entry)
Write a copy number entry to buffer. If the buffer is full, flush it.
Parameters:
dataType The data type.
target Target for the entry.
entry Value for the copy number entry.
Definition at line 337 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::chr, CopyMetricToBuffer(), GetMetricBufferSize(), affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::metrics, MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberData::position.
void CHPMultiDataFileBufferWriter::WriteMultiDataCopyNumberVariationRegionEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataCopyNumberVariationRegionData & entry)
Write a copy number variation region entry to buffer. If the buffer is full, flush it.
Parameters:
dataType The data type.
target Target for the entry.
entry Value for the copy number entry.
Definition at line 479 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::confidenceScore, CopyMetricToBuffer(), GetMetricBufferSize(), affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::metrics, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::name, and affymetrix_calvin_data::_ProbeSetMultiDataCopyNumberVariationRegionData::signal.
void CHPMultiDataFileBufferWriter::WriteMultiDataCytoRegionEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataCytoRegionData & entry)
Write a cyto region entry to buffer. If the buffer is full, flush it.
Parameters:
dataType The data type.
target Target for the entry.
entry Value for the copy number entry.
Definition at line 446 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::call, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::chr, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::confidenceScore, CopyMetricToBuffer(), GetMetricBufferSize(), affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::metrics, MmSetFloat_N(), MmSetUInt32_N(), MmSetUInt8(), affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::name, affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::startPosition, and affymetrix_calvin_data::_ProbeSetMultiDataCytoRegionData::stopPosition.
void CHPMultiDataFileBufferWriter::WriteMultiDataExpressionEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataExpressionData & entry)
Write an expression entry to buffer. If the buffer is full, flush it.
Parameters:
dataType The data type.
target Target for the entry.
entry Value for the expression entry.
Definition at line 314 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References CopyMetricToBuffer(), GetMetricBufferSize(), affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::metrics, MmSetFloat_N(), MmSetUInt32_N(), affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::name, and affymetrix_calvin_data::_ProbeSetMultiDataExpressionData::quantification.
void CHPMultiDataFileBufferWriter::WriteMultiDataGenotypeEntry (MultiDataType dataType, int target, const affymetrix_calvin_data::ProbeSetMultiDataGenotypeData & entry)
Write a genotype entry to buffer. If the buffer is full, flush it.
Parameters:
dataType The data type.
target Target for the entry.
entry Value for the genotype entry.
Definition at line 287 of file CalvinCHPMultiDataFileBufferWriter.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, CopyMetricToBuffer(), GetMetricBufferSize(), affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::metrics, MmSetFloat_N(), MmSetUInt32_N(), and affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::name.
Referenced by AddFileBody().
Member Data Documentation
std::vector<std::string>* affymetrix_calvin_io::CHPMultiDataFileBufferWriter::chpFileNames [private]
Pointer to list of CHP file names.
Definition at line 209 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, std::vector< std::vector<char *> > > affymetrix_calvin_io::CHPMultiDataFileBufferWriter::dataBuffers [private]
List of targets used for storing entries.
Definition at line 212 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::dataBufferSz [private]
The size of the buffer for each data type.
Definition at line 248 of file CalvinCHPMultiDataFileBufferWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileBufferWriter::m_BufferSize [private]
Size of the current buffer in bytes.
Definition at line 218 of file CalvinCHPMultiDataFileBufferWriter.h.
int affymetrix_calvin_io::CHPMultiDataFileBufferWriter::m_MaxBufferSize [private]
Maximum size of the buffer before it gets flushed
Definition at line 221 of file CalvinCHPMultiDataFileBufferWriter.h.
Referenced by SetMaxBufferSize().
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::maxFamilialARRID [private]
The maximum familial sample arr id length
Definition at line 236 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::maxFamilialCHPFilename [private]
The maximum familial sample chp file length
Definition at line 242 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::maxFamilialCHPID [private]
The maximum familial sample chp id length
Definition at line 239 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::maxFamilialRole [private]
The maximum familial sample role length
Definition at line 245 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::maxFamilialSegmentID [private]
The maximum familial seg id length
Definition at line 233 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::maxProbeSetNameLength [private]
The maximum probe set name length
Definition at line 224 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::maxReferenceSegmentID [private]
The maximum ref sample key length
Definition at line 230 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, int> affymetrix_calvin_io::CHPMultiDataFileBufferWriter::maxSegmentType [private]
The maximum segment type length
Definition at line 227 of file CalvinCHPMultiDataFileBufferWriter.h.
std::map<MultiDataType, std::vector<int> > affymetrix_calvin_io::CHPMultiDataFileBufferWriter::rowIndexes [private]
Buffer for storing row indexes.
Definition at line 215 of file CalvinCHPMultiDataFileBufferWriter.h.
The documentation for this class was generated from the following files:
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPMultiDataFileBufferWriter.h
C:/f112/affy/sdk/calvin_files/writers/src/CalvinCHPMultiDataFileBufferWriter.cpp