Affymetrix Fusion SDK: MatrixCheck Class Reference
MatrixCheck Class Reference
#include <MatrixCheck.h>
Public Member Functions
MatrixCheck (const std::string &generated, const std::string &gold, double eps, int rowSkip, int colSkip, bool matchNames, unsigned int allowedMisMatch, double frac=0.0)
void setPrintMismatch (bool print)
void setPrintMismatchMax (int max)
bool check (std::string &msg)
Public Attributes
std::string m_Generated
File created by application being tested.
std::string m_Gold
File believed to be "truth".
double m_Epsilon
Maximum abosolute difference from truth acceptable.
double m_Fraction
Maximum fractional difference from truth acceptable.
int m_RowSkip
Number of rows to skip before comparing.
int m_ColSkip
Number of columns to skip before comparing.
bool m_MatchNames
unsigned int m_AllowedMisMatch
How many can we get wrong before failing?
bool m_PrintMismatch
Mismatches printed if true, not printed if false.
int m_PrintMismatchMax
Maximum number of mismatches to print (default -1 for no limit)
Detailed Description
Class for testing that two files are the same +/- some epsilon. Currently only supports tab separated matrixes of numerical data.
Definition at line 46 of file MatrixCheck.h.
Constructor & Destructor Documentation
MatrixCheck::MatrixCheck (const std::string & generated, const std::string & gold, double eps, int rowSkip, int colSkip, bool matchNames, unsigned int allowedMisMatch, double frac = 0.0) [inline]
Constructor.
Parameters:
generated - File created by application being tested.
gold - File believed to be "truth"
eps - Maximum absolute difference from truth acceptable.
rowSkip - Number of rows to skip before comparing.
colSkip - Number of columns to skip before comparing.
matchNames - Should we try to match the names using first column? Useful when the files aren't necessarily in same order.
allowedMisMatch - How many can we get wrong before failing?
frac - Maximum fractional difference from truth acceptable
Definition at line 64 of file MatrixCheck.h.
References Fs::basename().
Member Function Documentation
bool MatrixCheck::check (std::string & msg) [inline]
Check to make sure that two files are the same +/- some epsilon.
Parameters:
msg - Fills in an error message if test fails, empty string otherwise.
Returns:
- Returns true if files are close enough, false otherwise.
Definition at line 102 of file MatrixCheck.h.
References Fs::convertToUncPath(), FS_QUOTE_PATH, Fs::isReadable(), m_AllowedMisMatch, m_ColSkip, m_Epsilon, m_Fraction, m_Generated, m_Gold, m_MatchNames, m_PrintMismatch, m_PrintMismatchMax, m_RowSkip, Util::matrixDifferences(), Err::setThrowStatus(), ToStr(), and Except::what().
Referenced by main().
void MatrixCheck::setPrintMismatch (bool print) [inline]
Utility function to enable/disable reporting of individual differences
Parameters:
print - mismatches printed if true, not printed if false.
Returns:
- void
Definition at line 84 of file MatrixCheck.h.
References m_PrintMismatch.
void MatrixCheck::setPrintMismatchMax (int max) [inline]
Utility function to set the max number of mismatches reported
Parameters:
max - maximum number of mismatches to report (set to -1 for no limit default behavior)
Returns:
- void
Definition at line 93 of file MatrixCheck.h.
References m_PrintMismatchMax.
Member Data Documentation
unsigned int MatrixCheck::m_AllowedMisMatch
How many can we get wrong before failing?
Definition at line 155 of file MatrixCheck.h.
Referenced by check().
int MatrixCheck::m_ColSkip
Number of columns to skip before comparing.
Definition at line 151 of file MatrixCheck.h.
Referenced by check().
double MatrixCheck::m_Epsilon
Maximum abosolute difference from truth acceptable.
Definition at line 148 of file MatrixCheck.h.
Referenced by check().
double MatrixCheck::m_Fraction
Maximum fractional difference from truth acceptable.
Definition at line 149 of file MatrixCheck.h.
Referenced by check().
std::string MatrixCheck::m_Generated
File created by application being tested.
Definition at line 146 of file MatrixCheck.h.
Referenced by check().
std::string MatrixCheck::m_Gold
File believed to be "truth".
Definition at line 147 of file MatrixCheck.h.
Referenced by check().
bool MatrixCheck::m_MatchNames
Should we try to match the names using first column? Useful when the files aren't necessarily in same order.
Definition at line 152 of file MatrixCheck.h.
Referenced by check().
bool MatrixCheck::m_PrintMismatch
Mismatches printed if true, not printed if false.
Definition at line 156 of file MatrixCheck.h.
Referenced by check(), and setPrintMismatch().
int MatrixCheck::m_PrintMismatchMax
Maximum number of mismatches to print (default -1 for no limit)
Definition at line 157 of file MatrixCheck.h.
Referenced by check(), and setPrintMismatchMax().
int MatrixCheck::m_RowSkip
Number of rows to skip before comparing.
Definition at line 150 of file MatrixCheck.h.
Referenced by check().
The documentation for this class was generated from the following file:
C:/f112/affy/sdk/util/MatrixCheck.h