Affymetrix Fusion SDK: affxutil Namespace Reference
affxutil Namespace Reference
Classes
class CheckSum
class Guid
Typedefs
typedef std::string GuidType
typedef std::list< GuidType > GuidTypeList
Functions
void ensure_srand_seeded ()
Ensure that srand has been seeded. Safe to call multiple times.
void affy_seed_srand ()
Seed srand with data from the system env Or from 'APT_DEBUG_SRAND_SEED' on unix. It will always set the srand seed when called.
Typedef Documentation
typedef std::string affxutil::GuidType
The GUID type
Definition at line 57 of file Guid.h.
typedef std::list<GuidType> affxutil::GuidTypeList
An STL list of guid types
Definition at line 60 of file Guid.h.
Function Documentation
void affxutil::affy_seed_srand ()
Seed srand with data from the system env Or from 'APT_DEBUG_SRAND_SEED' on unix. It will always set the srand seed when called.
Todo:
: log the seed and tell the user we are using a debugging seed.
Definition at line 64 of file Guid.cpp.
References AFFY_DEBUG_SRAND_SEED_ENVVAR, affy_seed_srand_done, AFFY_SEEDVAL, Err::errAbort(), and ToStr().
Referenced by ensure_srand_seeded().
void affxutil::ensure_srand_seeded ()
Ensure that srand has been seeded. Safe to call multiple times.
Ensure that the seed as been set once.
Definition at line 100 of file Guid.cpp.
References affy_seed_srand(), and affy_seed_srand_done.
Referenced by affxutil::Guid::GenerateNewGuid(), and affxutil::Guid::Guid().