Affymetrix Fusion SDK: affymetrix_calvin_array Namespace Reference
affymetrix_calvin_array Namespace Reference
Classes
class ArrayAttributes
class ArrayAuditEntry
class ArrayData
Typedefs
typedef std::vector
< ArrayAttributes > ArrayAttributesVector
typedef std::vector
< ArrayAuditEntry > ArrayAuditEntryVector
typedef std::list
< ArrayAuditEntry > ArrayAuditEntryList
typedef enum
affymetrix_calvin_array::_ArrayMedia ArrayMedia
typedef enum
affymetrix_calvin_array::_CreateStep CreateStep
typedef enum
affymetrix_calvin_array::_PATAssignmentMethod PATAssignmentMethod
Enumerations
enum _ArrayMedia { CartridgeMedia, PlateOrStripMedia }
enum _CreateStep {
NoStep, ArrayRegistrationStep, ScanningStep, GriddingStep,
CELAnalysisStep, FromStep, JobOrderServerStep, FileIndexerStep,
OtherStep
}
enum _PATAssignmentMethod { NoAssignment, AffyBarcodeAssignment, UserSelectedAssignment, OtherAssignment }
Functions
std::wstring MediaToString (ArrayMedia media)
ArrayMedia MediaFromString (const std::wstring &media)
std::wstring CreateStepToString (CreateStep step)
CreateStep CreateStepFromString (const std::wstring &step)
std::wstring PATAssignmentMethodToString (PATAssignmentMethod pat)
PATAssignmentMethod PATAssignmentMethodFromString (const std::wstring &pat)
Variables
static const int32_t ARRAY_FILE_CREATEION_ACTION = 1
static const int32_t ARRAY_FILE_ATTRIBUTE_UPDATE_ACTION = 2
static const int32_t FLUIDICS_INSTRUMENT_CONTROL_ACTION = 3
static const int32_t SCAN_INSTRUMENT_CONTROL_ACTION = 4
Typedef Documentation
typedef std::vector<ArrayAttributes> affymetrix_calvin_array::ArrayAttributesVector
An STL vector of array attributes.
Definition at line 193 of file ArrayAttributes.h.
typedef std::list<ArrayAuditEntry> affymetrix_calvin_array::ArrayAuditEntryList
An STL list of tbd objects
Definition at line 123 of file ArrayAudit.h.
typedef std::vector<ArrayAuditEntry> affymetrix_calvin_array::ArrayAuditEntryVector
An STL vector of tbd objects
Definition at line 120 of file ArrayAudit.h.
typedef enum affymetrix_calvin_array::_ArrayMedia affymetrix_calvin_array::ArrayMedia
The type of media of the array.
typedef enum affymetrix_calvin_array::_CreateStep affymetrix_calvin_array::CreateStep
Defines the steps that can create array data.
typedef enum affymetrix_calvin_array::_PATAssignmentMethod affymetrix_calvin_array::PATAssignmentMethod
The method the probe array type was assigned.
Enumeration Type Documentation
enum affymetrix_calvin_array::_ArrayMedia
The type of media of the array.
Enumerator:
CartridgeMedia
PlateOrStripMedia
A GeneChip cartridge.
A 96 well plate or peg strip.
Definition at line 34 of file ArrayMedia.h.
enum affymetrix_calvin_array::_CreateStep
Defines the steps that can create array data.
Enumerator:
NoStep
ArrayRegistrationStep
No step.
ScanningStep
Array registration.
GriddingStep
Scanning.
CELAnalysisStep
Grid analysis.
FromStep
CEL file analysis.
JobOrderServerStep
From.
FileIndexerStep
Job order.
OtherStep
File indexer.
Any other step.
Definition at line 35 of file CreateStep.h.
enum affymetrix_calvin_array::_PATAssignmentMethod
The method the probe array type was assigned.
Enumerator:
NoAssignment
AffyBarcodeAssignment
Unknown
UserSelectedAssignment
User entered an Affy barcode.
OtherAssignment
User selected.
Other method.
Definition at line 35 of file PATAssignment.h.
Function Documentation
CreateStep affymetrix_calvin_array::CreateStepFromString (const std::wstring & step)
Converts a string to step type.
Parameters:
step The string representation.
Returns:
The create step
Definition at line 105 of file CreateStep.cpp.
References ArrayRegistrationStep, CELAnalysisStep, CREATED_STEP_ARRAY_REG, CREATED_STEP_CEL, CREATED_STEP_FILE_INDEXER, CREATED_STEP_FROM, CREATED_STEP_GRID, CREATED_STEP_JOB_ORDER, CREATED_STEP_NONE, CREATED_STEP_OTHER, CREATED_STEP_SCAN, FileIndexerStep, FromStep, GriddingStep, JobOrderServerStep, NoStep, OtherStep, and ScanningStep.
Referenced by affymetrix_calvin_io::SAXArrayHandlers::StoreArrayFileAttributes(), and affymetrix_calvin_io::SAXArrayHandlers::StorePhysicalArrayElementAttributes().
std::wstring affymetrix_calvin_array::CreateStepToString (CreateStep step)
Converts the step type to a string.
Parameters:
step The create step
Returns:
The string representation.
Definition at line 56 of file CreateStep.cpp.
References ArrayRegistrationStep, CELAnalysisStep, CREATED_STEP_ARRAY_REG, CREATED_STEP_CEL, CREATED_STEP_FILE_INDEXER, CREATED_STEP_FROM, CREATED_STEP_GRID, CREATED_STEP_JOB_ORDER, CREATED_STEP_NONE, CREATED_STEP_OTHER, CREATED_STEP_SCAN, FileIndexerStep, FromStep, GriddingStep, JobOrderServerStep, NoStep, OtherStep, and ScanningStep.
Referenced by AddPhysicalArrays(), and CreateArrayElement().
ArrayMedia affymetrix_calvin_array::MediaFromString (const std::wstring & media)
Converts a string to media type.
Parameters:
media The string representation.
Returns:
The media
Definition at line 56 of file ArrayMedia.cpp.
References CartridgeMedia, MEDIA_TYPE_CARTRIDGE, MEDIA_TYPE_PLATE_OR_STRIP, and PlateOrStripMedia.
Referenced by affymetrix_calvin_io::SAXArrayHandlers::StorePhysicalArrayElementAttributes().
std::wstring affymetrix_calvin_array::MediaToString (ArrayMedia media)
Converts the media type to a string.
Parameters:
media The media type
Returns:
The string representation.
Definition at line 35 of file ArrayMedia.cpp.
References CartridgeMedia, MEDIA_TYPE_CARTRIDGE, MEDIA_TYPE_PLATE_OR_STRIP, and PlateOrStripMedia.
Referenced by AddPhysicalArrays().
PATAssignmentMethod affymetrix_calvin_array::PATAssignmentMethodFromString (const std::wstring & pat)
Converts a string to the probe array assignment type.
Parameters:
pat The string representation.
Returns:
The probe array assignment
Definition at line 70 of file PATAssignment.cpp.
References AffyBarcodeAssignment, NoAssignment, OtherAssignment, PAT_ASSIGNMENT_BARCODE, PAT_ASSIGNMENT_NONE, PAT_ASSIGNMENT_OTHER, PAT_ASSIGNMENT_USER_SELECTED, and UserSelectedAssignment.
Referenced by affymetrix_calvin_io::SAXArrayHandlers::StorePhysicalArrayElementAttributes().
std::wstring affymetrix_calvin_array::PATAssignmentMethodToString (PATAssignmentMethod pat)
Converts the probe array assignment type to a string.
Parameters:
pat The probe array assignment
Returns:
The string representation.
Definition at line 41 of file PATAssignment.cpp.
References AffyBarcodeAssignment, NoAssignment, OtherAssignment, PAT_ASSIGNMENT_BARCODE, PAT_ASSIGNMENT_NONE, PAT_ASSIGNMENT_OTHER, PAT_ASSIGNMENT_USER_SELECTED, and UserSelectedAssignment.
Referenced by AddPhysicalArrays().
Variable Documentation
const int32_t affymetrix_calvin_array::ARRAY_FILE_ATTRIBUTE_UPDATE_ACTION = 2 [static]
Attribute update action.
Definition at line 37 of file ArrayAuditActionTypes.h.
const int32_t affymetrix_calvin_array::ARRAY_FILE_CREATEION_ACTION = 1 [static]
Initial creation of an array file.
Definition at line 34 of file ArrayAuditActionTypes.h.
const int32_t affymetrix_calvin_array::FLUIDICS_INSTRUMENT_CONTROL_ACTION = 3 [static]
Fluidics instrument control action.
Definition at line 40 of file ArrayAuditActionTypes.h.
const int32_t affymetrix_calvin_array::SCAN_INSTRUMENT_CONTROL_ACTION = 4 [static]
Scanner instrument control action.
Definition at line 43 of file ArrayAuditActionTypes.h.