Affymetrix Fusion SDK: C:/f112/affy/sdk/parser_examples/cpp/read_cel/read_cel.cpp File Reference
read_cel.cpp File Reference
#include "calvin_files/fusion/src/FusionCELData.h"
#include "calvin_files/fusion/src/FusionCDFData.h"
#include "calvin_files/utils/src/StringUtils.h"
#include <iostream>
Functions
void ReadMultipleIntensitiesAndStdDev (FusionCELData *cel)
void ReadSingleChannelCelFile (FusionCELData *cel, FusionCDFData *cdf)
void ReadSingleOrMultiChannelCelFile (FusionCELData *cel, FusionCDFData *cdf)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 157 of file read_cel.cpp.
References affymetrix_fusion_io::FusionCELData::IsMultiColor(), affymetrix_fusion_io::FusionCDFData::Read(), affymetrix_fusion_io::FusionCELData::Read(), ReadMultipleIntensitiesAndStdDev(), ReadSingleChannelCelFile(), ReadSingleOrMultiChannelCelFile(), affymetrix_fusion_io::FusionCDFData::SetFileName(), and affymetrix_fusion_io::FusionCELData::SetFileName().
void ReadMultipleIntensitiesAndStdDev (FusionCELData * cel)
Definition at line 16 of file read_cel.cpp.
References affymetrix_fusion_io::FusionCELData::GetChannels(), affymetrix_fusion_io::FusionCELData::GetIntensities(), affymetrix_fusion_io::FusionCELData::GetStdv(), and affymetrix_fusion_io::FusionCELData::SetActiveDataGroup().
Referenced by main().
void ReadSingleChannelCelFile (FusionCELData * cel, FusionCDFData * cdf)
Definition at line 62 of file read_cel.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetCell(), affymetrix_fusion_io::FusionCDFData::GetHeader(), affymetrix_fusion_io::FusionCELData::GetIntensity(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetNumCells(), affymetrix_fusion_io::FusionCELData::GetNumCells(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation(), affymetrix_fusion_io::FusionCDFData::GetProbeSetName(), affymetrix_fusion_io::FusionCDFProbeInformation::GetX(), and affymetrix_fusion_io::FusionCDFProbeInformation::GetY().
Referenced by main().
void ReadSingleOrMultiChannelCelFile (FusionCELData * cel, FusionCDFData * cdf)
Definition at line 109 of file read_cel.cpp.
References affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetCell(), affymetrix_fusion_io::FusionCELData::GetChannels(), affymetrix_fusion_io::FusionCDFData::GetHeader(), affymetrix_fusion_io::FusionCELData::GetIntensity(), affymetrix_fusion_io::FusionCDFProbeGroupInformation::GetNumCells(), affymetrix_fusion_io::FusionCELData::GetNumCells(), affymetrix_fusion_io::FusionCDFFileHeader::GetNumProbeSets(), affymetrix_fusion_io::FusionCDFData::GetProbeSetInformation(), affymetrix_fusion_io::FusionCDFData::GetProbeSetName(), affymetrix_fusion_io::FusionCDFProbeInformation::GetX(), affymetrix_fusion_io::FusionCDFProbeInformation::GetY(), and affymetrix_fusion_io::FusionCELData::SetActiveDataGroup().
Referenced by main().