Affymetrix Fusion SDK: C:/f112/affy/sdk/util/test-tmpfilefactory.cpp File Reference
test-tmpfilefactory.cpp File Reference
#include "util/Fs.h"
#include "util/PgOptions.h"
#include "util/TmpFileFactory.h"
#include "util/Util.h"
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
Functions
void test_write_data (const std::string &filename)
Dump the filename to the file as test data.
void test_1 ()
void test_2_helper (TmpFileFactory *tff, int cnt)
void test_2 ()
void test_3 ()
void test_4 ()
int main (int argc, char *argv[])
Variables
int opt_debug = 0
int opt_verbose = 0
Function Documentation
int main (int argc, char * argv[])
Definition at line 144 of file test-tmpfilefactory.cpp.
References PgOpt::BOOL_OPT, PgOptions::defineOption(), PgOptions::getInt(), GlobalTmpFileFactory(), GlobalTmpFileFactoryFree(), PgOpt::INT_OPT, opt_debug, opt_verbose, PgOptions::parseArgv(), TmpFileFactory::setDebug(), TmpFileFactory::setPrefix(), PgOptions::setUsage(), TmpFileFactory::setVerbose(), test_1(), test_2(), test_3(), and test_4().
void test_1 ()
Definition at line 57 of file test-tmpfilefactory.cpp.
References TmpFileFactory::genFilename(), opt_debug, opt_verbose, TmpFileFactory::setDebug(), TmpFileFactory::setPrefix(), TmpFileFactory::setVerbose(), and test_write_data().
Referenced by main().
void test_2 ()
Definition at line 90 of file test-tmpfilefactory.cpp.
References opt_debug, opt_verbose, TmpFileFactory::setDebug(), TmpFileFactory::setPrefix(), TmpFileFactory::setVerbose(), and test_2_helper().
Referenced by main().
void test_2_helper (TmpFileFactory * tff, int cnt)
this function has a TmpFileFactory pointer passed into it. the allocations are done within its context.
Definition at line 82 of file test-tmpfilefactory.cpp.
References TmpFileFactory::genFilename().
Referenced by test_2(), and test_3().
void test_3 ()
Definition at line 104 of file test-tmpfilefactory.cpp.
References TmpFileFactory::genDirname(), opt_debug, opt_verbose, TmpFileFactory::setDebug(), TmpFileFactory::setPrefix(), TmpFileFactory::setTmpdir(), TmpFileFactory::setVerbose(), and test_2_helper().
Referenced by main().
void test_4 ()
Definition at line 124 of file test-tmpfilefactory.cpp.
References TmpFileFactory::genDirname(), GlobalTmpFileFactory(), TmpFileFactory::setTmpdir(), and test_write_data().
Referenced by main().
void test_write_data (const std::string & filename)
Dump the filename to the file as test data.
Parameters:
filename filename to create
Definition at line 44 of file test-tmpfilefactory.cpp.
References Fs::isReadable().
Referenced by test_1(), and test_4().
Variable Documentation
int opt_debug = 0
Definition at line 36 of file test-tmpfilefactory.cpp.
Referenced by main(), test_1(), test_2(), and test_3().
int opt_verbose = 0
Definition at line 37 of file test-tmpfilefactory.cpp.