Affymetrix Fusion SDK: C:/f112/affy/sdk/file/TsvFile/tsv-util.cpp File Reference
tsv-util.cpp File Reference
collection of utilities for working with tsv-format files.
#include "file/TsvFile/TsvFile.h"
#include "file/TsvFile/TsvFileDiff.h"
#include "util/Convert.h"
#include "util/Err.h"
#include "util/Fs.h"
#include "util/PgOptions.h"
#include "util/Util.h"
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
Defines
#define SNPRINTF snprintf
#define TSV_PASTE_FH_LIMIT 900
The limit of filehandles we can paste at one time.
#define BENCHMARK_COL_CNT 10
Functions
void tsv_util_linecount (const std::string &fileName)
Count the datalines in the tsvfile fname.
void tsv_util_headers (const std::string &fileName)
Dump the just the headers of the TsvFile to stdout.
int tsv_util_print_duplicate_headerkeys (const std::string &fileName)
void tsv_util_copy (const std::string &f_fileName, const std::string &t_fileName, int fmt)
Copy contents from one tsvfile to another.
void tsv_util_paste_basic (const std::string &out_fileName, const std::vector< std::string > in_tsv_fileNames, const std::vector< std::string > in_header_fileNames, int seg_max_lines, const std::string &key_col_name, int verbose)
Paste the columns of several tsvFiles into one tsvfile in one pass. Cant to more than the limit in one pass.
void tsv_util_paste (const std::string &out_fileName, const std::vector< std::string > in_tsv_fileNames, int seg_max_lines, const std::string &key_col_name, int verbose, int tsv_paste_fh_limit)
Paste the columns of the input tsv files into a big tsv file. If there are too many inputs, do the work in several passes. Also splits the output into seg_max_line size files if requested.
void tsv_util_benchmark (int benchmark_cnt, const std::string &filename)
int main (int argc, const char *argv[])
entry point for tsv-util
Detailed Description
collection of utilities for working with tsv-format files.
Definition in file tsv-util.cpp.
Define Documentation
#define BENCHMARK_COL_CNT 10
Definition at line 457 of file tsv-util.cpp.
Referenced by tsv_util_benchmark().
#define SNPRINTF snprintf
Definition at line 42 of file tsv-util.cpp.
Referenced by tsv_util_paste(), and tsv_util_paste_basic().
#define TSV_PASTE_FH_LIMIT 900
The limit of filehandles we can paste at one time.
Definition at line 174 of file tsv-util.cpp.
Referenced by tsv_util_paste_basic().
Function Documentation
int main (int argc, const char * argv[])
entry point for tsv-util
Parameters:
argc
argv
Returns:
Definition at line 506 of file tsv-util.cpp.
References PgOpt::BOOL_OPT, PgOptions::defineOption(), affx::TsvFileDiff::diff(), PgOpt::DOUBLE_OPT, PgOptions::get(), PgOptions::getArg(), PgOptions::getArgCount(), PgOptions::getArgVector(), PgOptions::getBool(), PgOptions::getDouble(), PgOptions::getInt(), PgOpt::INT_OPT, PgOpt::isSet(), affx::TsvFileDiff::m_diff_cnt, affx::TsvFileDiff::m_opt_do_data, affx::TsvFileDiff::m_opt_do_headers, affx::TsvFileDiff::m_opt_max_diff, affx::TsvFileDiff::m_opt_print_format, affx::TsvFileDiff::m_opt_print_linenums, affx::TsvFileDiff::m_opt_print_max, affx::TsvFileDiff::m_opt_print_same, affx::TsvFileDiff::m_residuals_filename, PgOptions::mustFindOpt(), PgOptions::parseArgv(), PgOptions::setUsage(), PgOpt::setValue(), PgOpt::STRING_OPT, tsv_util_benchmark(), tsv_util_copy(), tsv_util_headers(), tsv_util_linecount(), tsv_util_paste(), tsv_util_print_duplicate_headerkeys(), and PgOptions::usage().
void tsv_util_benchmark (int benchmark_cnt, const std::string & filename)
Definition at line 460 of file tsv-util.cpp.
References affx::TsvFile::addHeader(), BENCHMARK_COL_CNT, affx::TsvFile::close(), affx::TsvFile::defineColumn(), affx::TsvFile::set(), affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv_v1().
Referenced by main().
void tsv_util_copy (const std::string & f_fileName, const std::string & t_fileName, int fmt)
Copy contents from one tsvfile to another.
Parameters:
f_fileName filename of the "from/source" tsvfile
t_fileName filename of the "to/destination" tsvfile
fmt
Definition at line 140 of file tsv-util.cpp.
References affx::TsvFile::addHeadersFrom(), affx::TsvFile::close(), affx::TsvFile::copyFormat(), affx::TsvFile::copyLevel(), affx::TsvFile::lineLevel(), affx::TsvFile::nextLine(), affx::TsvFile::open(), affx::TSV_ADD_ALL, affx::TSV_OK, affx::TsvFile::writeCsv(), affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv().
Referenced by main().
void tsv_util_headers (const std::string & fileName)
Dump the just the headers of the TsvFile to stdout.
Parameters:
fileName filename fo the tsvFile
Definition at line 84 of file tsv-util.cpp.
References affx::TsvFile::close(), affx::TsvFile::headersBegin(), affx::TsvFile::headersNext(), affx::TsvFile::open(), and affx::TSV_OK.
Referenced by main().
void tsv_util_linecount (const std::string & fileName)
Count the datalines in the tsvfile fname.
Parameters:
fileName filename of the tsvFile
Definition at line 50 of file tsv-util.cpp.
References affx::TsvFile::close(), affx::TsvFile::nextLine(), affx::TsvFile::open(), and affx::TSV_OK.
Referenced by main().
void tsv_util_paste (const std::string & out_fileName, const std::vector< std::string > in_tsv_fileNames, int seg_max_lines, const std::string & key_col_name, int verbose, int tsv_paste_fh_limit)
Paste the columns of the input tsv files into a big tsv file. If there are too many inputs, do the work in several passes. Also splits the output into seg_max_line size files if requested.
Parameters:
out_fileName
in_tsv_fileNames
seg_max_lines
key_col_name
verbose
tsv_paste_fh_limit
Definition at line 366 of file tsv-util.cpp.
References Err::errAbort(), Fs::rm(), SNPRINTF, and tsv_util_paste_basic().
Referenced by main().
void tsv_util_paste_basic (const std::string & out_fileName, const std::vector< std::string > in_tsv_fileNames, const std::vector< std::string > in_header_fileNames, int seg_max_lines, const std::string & key_col_name, int verbose)
Paste the columns of several tsvFiles into one tsvfile in one pass. Cant to more than the limit in one pass.
Parameters:
out_fileName filename of the output tsvfile.
in_tsv_fileNames vector of input tsvfile names.
in_header_fileNames vector of names to put in header. (This is needed for the final multi-pass case.)
seg_max_lines If non-zero, split the output file into segments. (0=>no segments.)
key_col_name Key column name to match while pasting. (""=> no key column.)
verbose The verbosity level
Definition at line 186 of file tsv-util.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::close(), affx::TsvFile::defineColumn(), Err::errAbort(), affx::TsvFile::open(), affx::TsvFile::set(), SNPRINTF, ToStr(), affx::TSV_OK, TSV_PASTE_FH_LIMIT, affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv_v1().
Referenced by tsv_util_paste().
int tsv_util_print_duplicate_headerkeys (const std::string & fileName)
Definition at line 111 of file tsv-util.cpp.
References affx::TsvFile::close(), affx::TsvFile::open(), affx::TsvFile::printDuplicateHeaders(), and affx::TSV_OK.
Referenced by main().