Affymetrix Fusion SDK: C:/f112/affy/sdk/file/TsvFile/tsv-example.cpp File Reference
tsv-example.cpp File Reference
#include "file/TsvFile/ClfFile.h"
#include "file/TsvFile/PgfFile.h"
#include "file/TsvFile/TsvFile.h"
#include <cstring>
#include <string.h>
#include <string>
Functions
void example_walk_clf (std::string file_name)
Walk the contents of a clf file and count the entries.
void example_walk_pgf (std::string file_name)
Walk the contents of a PGF file and count the number of each items.
void example_index_1 (std::string file_name)
Query the tsv file by gc_count and print out the matching probes.
void example_index_2 (std::string file_name)
Search a pgf file for a matching sequence.
void example_write_1 (std::string file_name)
Example of writing a custom TSV file.
void example_write_2 (std::string file_name)
Example of writing the start of a PgfFile.
void example_write_3 (std::string file_name, int fmt)
write v1 tsv and csv files
void example_write_4 (std::string file_name, int row_cnt, int col_cnt)
Example of writing a custom TSV file.
void example_read_table_1 (std::string file_name)
An example of how to read a table.
void example_dump_columns (std::string file_name)
example of dumping columns
void usage ()
Print usage instructions.
int main (int argc, char *argv[])
entry point for the program
Variables
int opt_benchmark
When set, dont generate much output -- used when benchmarking the code.
int opt_verbose
How much output to generate.
Function Documentation
void example_dump_columns (std::string file_name)
example of dumping columns
Parameters:
file_name file to be read and dumped
Definition at line 384 of file tsv-example.cpp.
References affx::TsvFile::cidx2cname(), affx::TsvFile::close(), affx::TsvFile::getColumnCount(), affx::TsvFile::getLevelCount(), affx::TsvFile::openTable(), and affx::TSV_OK.
Referenced by main().
void example_index_1 (std::string file_name)
Query the tsv file by gc_count and print out the matching probes.
Parameters:
file_name Filename to search
Definition at line 124 of file tsv-example.cpp.
References affx::TsvFile::close(), affx::TsvFile::defineIndex(), affx::TsvFile::findBegin(), affx::TsvFile::findNext(), affx::TsvFile::get(), affx::TsvFile::lineNumber(), affx::TsvFile::open(), opt_verbose, affx::TSV_INDEX_INT, affx::TSV_OK, affx::TSV_OP_LTEQ, and affx::TSV_ORDERBY_VAL.
Referenced by main().
void example_index_2 (std::string file_name)
Search a pgf file for a matching sequence.
Parameters:
file_name
Definition at line 186 of file tsv-example.cpp.
References affx::TsvFile::defineIndex(), affx::TsvFile::findBegin(), affx::TsvFile::findNext(), affx::TsvFile::findResultsCount(), affx::TsvFile::lineNumber(), affx::PgfFile::m_tsv, affx::PgfFile::open(), opt_verbose, affx::PgfFile::probe_id, affx::PgfFile::probe_sequence, affx::TSV_INDEX_STRING, affx::TSV_OK, and affx::TSV_OP_EQ.
Referenced by main().
void example_read_table_1 (std::string file_name)
An example of how to read a table.
Parameters:
file_name table file to be read
Definition at line 357 of file tsv-example.cpp.
References affx::TsvFile::close(), affx::TsvFile::get(), affx::TsvFile::getColumnCount(), affx::TsvFile::lineLevel(), affx::TsvFile::nextLevel(), affx::TsvFile::openTable(), and affx::TSV_OK.
Referenced by main().
void example_walk_clf (std::string file_name)
Walk the contents of a clf file and count the entries.
Parameters:
file_name
Definition at line 59 of file tsv-example.cpp.
References affx::TsvFile::m_optAbortOnError, affx::ClfFile::m_tsv, affx::ClfFile::next_probe(), affx::ClfFile::open(), and affx::TSV_OK.
void example_walk_pgf (std::string file_name)
Walk the contents of a PGF file and count the number of each items.
Parameters:
file_name
Definition at line 85 of file tsv-example.cpp.
References affx::PgfFile::close(), affx::TsvFile::m_optAbortOnError, affx::PgfFile::m_tsv, affx::PgfFile::next_atom(), affx::PgfFile::next_probe(), affx::PgfFile::next_probeset(), affx::PgfFile::open(), and affx::TSV_OK.
Referenced by main().
void example_write_1 (std::string file_name)
Example of writing a custom TSV file.
Parameters:
file_name file to write to
Definition at line 210 of file tsv-example.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::close(), affx::TsvFile::defineFile(), affx::TsvFile::getColumnCount(), affx::TsvFile::getLevelCount(), affx::TsvFile::set(), affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv().
Referenced by main().
void example_write_2 (std::string file_name)
Example of writing the start of a PgfFile.
Parameters:
file_name where to write.
Definition at line 255 of file tsv-example.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::close(), affx::PgfFile::defineFilePgf(), affx::PgfFile::m_tsv, affx::TsvFile::set(), affx::PgfFile::write(), and affx::TsvFile::writeLevel().
Referenced by main().
void example_write_3 (std::string file_name, int fmt)
write v1 tsv and csv files
Parameters:
file_name name of file
fmt 1 for tsv, 2 for csv
Definition at line 291 of file tsv-example.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::close(), affx::TsvFile::defineFile(), affx::TsvFile::set(), affx::TsvFile::writeCsv(), affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv_v1().
Referenced by main().
void example_write_4 (std::string file_name, int row_cnt, int col_cnt)
Example of writing a custom TSV file.
Parameters:
file_name file to write to
row_cnt number of rows to write
col_cnt number of colss to write
Definition at line 324 of file tsv-example.cpp.
References affx::TsvFile::addHeader(), affx::TsvFile::close(), affx::TsvFile::defineColumn(), affx::TsvFile::set(), affx::TsvFile::setPrecision(), affx::TsvFile::writeLevel(), and affx::TsvFile::writeTsv().
int main (int argc, char * argv[])
entry point for the program
Parameters:
argc argument count
argv vector of arguments
Returns:
exit value
Definition at line 434 of file tsv-example.cpp.
References example_dump_columns(), example_index_1(), example_index_2(), example_read_table_1(), example_walk_pgf(), example_write_1(), example_write_2(), example_write_3(), opt_benchmark, opt_verbose, and usage().
void usage ()
Print usage instructions.
Definition at line 413 of file tsv-example.cpp.
Referenced by main(), and PgOptions::usage().
Variable Documentation
int opt_benchmark
When set, dont generate much output -- used when benchmarking the code.
Definition at line 50 of file tsv-example.cpp.
Referenced by main().
int opt_verbose
How much output to generate.
Definition at line 52 of file tsv-example.cpp.
Referenced by example_index_1(), example_index_2(), main(), test_1(), test_2(), and test_3().