Affymetrix Fusion SDK: C:/f112/affy/sdk/calvin_files/converters/txt2mchp/txt2mchp.cpp File Reference
txt2mchp.cpp File Reference
#include "calvin_files/converters/utils/src/CmdLine.h"
#include "calvin_files/fusion/src/FusionCELData.h"
#include "calvin_files/utils/src/FileUtils.h"
#include "calvin_files/utils/src/StringUtils.h"
#include "calvin_files/writers/src/CalvinCHPMultiDataFileBufferWriter.h"
#include "calvin_files/writers/src/CalvinCHPMultiDataFileWriter.h"
#include <vector>
#include <list>
#include <iostream>
#include <fstream>
Functions
static void CreateFileWithHeader (const string &execId, const string &celFile, const string &outFile, const vector< string > &extraColNames, const vector< string > &extraColTypes, unsigned long numEntries, int maxProbeSetNameLength, const string &algName, const string &algVersion, const string &chipType, const string &programName, const string &programVersion, const string &programCompany, const vector< string > &paramNames, const vector< string > &paramValues, const vector< string > &sumNames, const vector< string > &sumValues, const vector< string > &extraNames, const vector< string > &extraValues)
static int CallToCode (const string &call)
static list< string > ParseLine (char *line)
static void AddFileBody (const string &inFile, const string &outFile, int maxProbeSetNameLength, const vector< string > &extraColTypes)
static unsigned long ReadData (const string &inFile, int &maxProbeSetNameLength)
static void show_help ()
int main (int argc, char *argv[])
Function Documentation
static void AddFileBody (const string & inFile, const string & outFile, int maxProbeSetNameLength, const vector< string > & extraColTypes) [static]
Adds the genotype results to the CHP file. This function uses the buffer writer object to write the data to the CHP file.
Parameters:
inFile The name of the input TSV file.
outFile The name of the output CHP file.
maxProbeSetNameLength The maximum length of the probe set names.
extraColTypes The types (float, int, ubyte) of the extra columns.
Definition at line 254 of file txt2mchp.cpp.
References affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::call, CallToCode(), affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::confidence, affymetrix_calvin_io::CHPMultiDataFileBufferWriter::FlushBuffer(), affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_calvin_io::CHPMultiDataFileBufferWriter::Initialize(), affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::metrics, affymetrix_calvin_data::_ProbeSetMultiDataGenotypeData::name, ParseLine(), and affymetrix_calvin_io::CHPMultiDataFileBufferWriter::WriteMultiDataGenotypeEntry().
Referenced by main().
static int CallToCode (const string & call) [static]
Convert a call to a code
Parameters:
call The call, or can be a code
Returns:
The code
Definition at line 211 of file txt2mchp.cpp.
References SNP_AA_CALL, SNP_AB_CALL, SNP_BB_CALL, and SNP_NO_CALL.
Referenced by AddFileBody().
static void CreateFileWithHeader (const string & execId, const string & celFile, const string & outFile, const vector< string > & extraColNames, const vector< string > & extraColTypes, unsigned long numEntries, int maxProbeSetNameLength, const string & algName, const string & algVersion, const string & chipType, const string & programName, const string & programVersion, const string & programCompany, const vector< string > & paramNames, const vector< string > & paramValues, const vector< string > & sumNames, const vector< string > & sumValues, const vector< string > & extraNames, const vector< string > & extraValues) [static]
Create a "multi-data" CHP file with just the header information. The remainder of the file will be created at a later time using the buffer writer technique. The CHP file will contain only "genotyping" results.
Parameters:
execId The execution identifier. This identifier is used to identify the batch run that created the CHP files.
celFile The full path to the parent CEL file. The header of the CEL file is copied to the CHP file.
outFile The name of the output CHP file.
extraColNames The names of the extra data columns. Should not include probe set name, call and confidence columns.
extraColTypes The types (float, int, ubyte) of the extra columns.
numEntries The number of rows (entries) of results to store in the CHP file.
maxProbeSetNameLength The maximum length of the probe set names.
algName The name of the algorithm used to create the results.
algVersion The algorithm version.
chipType the chip type, also known as the probe array type.
programName The name of the program used to create the CHP file.
programVersion The version of the program.
programCompany The company or institution who developed the CHP creating software.
paramNames A list of parameter names to store in the CHP file header.
paramValues A list of parameter values to store in the CHP file header.
sumNames A list of summary statistic names to store in the CHP file header.
sumValues A list of summary statistic values to store in the CHP file header.
Definition at line 79 of file txt2mchp.cpp.
References affymetrix_calvin_io::CHPMultiDataData::AddAlgParams(), affymetrix_calvin_io::GenericDataHeader::AddNameValParam(), affymetrix_calvin_io::GenericDataHeader::AddParent(), affymetrix_calvin_io::CHPMultiDataData::AddSummaryParams(), affymetrix_fusion_io::FusionCELData::Close(), affymetrix_calvin_io::GenotypeMultiDataType, affymetrix_calvin_io::CHPMultiDataData::GetFileHeader(), affymetrix_calvin_io::CHPMultiDataData::GetGenericData(), affymetrix_fusion_io::FusionCELData::GetGenericData(), affymetrix_calvin_io::FileHeader::GetGenericDataHdr(), affymetrix_calvin_io::GenericData::Header(), affymetrix_fusion_io::FusionCELData::ReadHeader(), affymetrix_calvin_io::CHPMultiDataData::SetAlgName(), affymetrix_calvin_io::CHPMultiDataData::SetAlgVersion(), affymetrix_calvin_io::CHPMultiDataData::SetArrayType(), affymetrix_calvin_io::CHPMultiDataData::SetEntryCount(), and affymetrix_fusion_io::FusionCELData::SetFileName().
Referenced by main().
int main (int argc, char * argv[])
The main entrance to the program.
Definition at line 374 of file txt2mchp.cpp.
References AddFileBody(), CreateFileWithHeader(), CCmdLine::GetArgument(), CCmdLine::GetArgumentCount(), CCmdLine::GetSafeArgument(), ReadData(), show_help(), and CCmdLine::SplitLine().
static list<string> ParseLine (char * line) [static]
Parse a line into a list.
Parameters:
line The line of data
Returns:
A list of strings from the line (separated by tabs).
Definition at line 234 of file txt2mchp.cpp.
Referenced by AddFileBody(), and ReadData().
static unsigned long ReadData (const string & inFile, int & maxProbeSetNameLength) [static]
Reads the genotype results from a simple TSV text file.
Parameters:
inFile The name of the input TSV file.
maxProbeSetNameLength The maximum length of the probe set names.
Definition at line 314 of file txt2mchp.cpp.
References ParseLine().
Referenced by main().
static void show_help () [static]
Show a help message on the use of the command line parameters.
Definition at line 342 of file txt2mchp.cpp.
Referenced by main().